### ISSUE TITLE
Are there plans to release a beta version?

### ISSUE THREAD

**Issue by stephan75** [westnordost/StreetComplete#1]
Since summer 2016 the google play store has that new beta release feature for apps,

see https://forum.openstreetmap.org/viewtopic.php?id=55203 for some OSM related apps.

Dou you have plans to release a beta apk of osmagent via that way?

Thanks for all your efforts so far.

**Comment by westnordost** [comment]
I planned to release a beta simply as a downloadable APK in the forum first to get more qualitative feedback from the community. Currently I do not see any benefit of using this google play beta feature. When I release on the play store, I think I will release a non-beta right away.

**Comment by noflag** [comment]
can't wait for an apk,i want to contribute! f-droid is more important than google play, imho

**Comment by IzzySoft** [comment]
May I suggest attaching an `.apk` here at Github? You could consider something like "snapshots", i.e. creating a tag each time you think the current code should serve as "public beta", and attach the `.apk` to that (see [Creating Releases](https://help.github.com/articles/creating-releases/) for details).

If you do that, I could even see if I integrate it with [my repo](https://android.izzysoft.de/repo), so "beta testers" could use the F-Droid client to stay updated.

**Comment by westnordost** [comment]
Hmm, sounds good. Yeah, also I may not forget F-Droid.

**Comment by IzzySoft** [comment]
@westnordost Just let me know when there's an `.apk` available here at Github (preferably via the `releases/` page, as pointed out). I'll then take care for the rest on my end :) As combination, once listed via the "official F-Droid repo", you still could put the "stable releases" there and I pick the "stable betas" from here :)

**Comment by RobJN** [comment]
A beta has now been released. This can therefore be closed.

**Comment by IzzySoft** [comment]
@RobJN I see no `.apk`, so not sure if it should really be closed…

**Comment by RobJN** [comment]
@IzzySoft See https://lists.openstreetmap.org/pipermail/talk/2016-December/077170.html

**Comment by IzzySoft** [comment]
@RobJN Who will find it there if looking at the project here? I was talking about the APK being published here at Github (see my previous comments). But of course that could be moved to a separate issue if @westnordost prefers that :) My updater script (see [this comment](https://github.com/westnordost/StreetComplete/issues/1#issuecomment-260036856)) works with Github structures, not with other sites.

**Comment by westnordost** [comment]
A version here will follow

**Comment by westnordost** [comment]
I plan 0.3 or 0.4 to be the first version I want to expose to a larger "beta" audience.

**Comment by IzzySoft** [comment]
Looking forward to that then! Thanks for the heads-up!

**Comment by westnordost** [comment]
Sorry, I got sidetracked and then had other things to do. I put a release build here and will put one on Google Play too.

**Comment by IzzySoft** [comment]
Thanks a lot! Just added it to my repository. Updates (whenever you add an `.apk` to a new release) should show up there within 24h, so be welcome to point your users/beta-testers [here](https://apt.izzysoft.de/fdroid/index/apk/de.westnordost.streetcomplete) :smiley_cat:
