### ISSUE TITLE
Quest: Is this parking area Public, Private, Customers or Other?

### ISSUE THREAD

**Issue by CloCkWeRX** [westnordost/StreetComplete#100]
Apps that use this data:
 * http://product.itoworld.com/map/7
 * https://play.google.com/store/apps/details?id=fr.lcdm.freeparking&hl=en

Its very easy to tag an area as amenity=parking, but less easy to determine what kind of parking it is.

**Comment by HolgerJeromin** [comment]
This is important. You could ask  for parking type (underground, multi storage and surface), too.
 
If you add access please do not add access = public but only yes.

**Comment by matkoniecz** [comment]
yes, private, customers (and their equivalents) account for more than 96% of values, with other values fragmented or nonsense.

My current ideas for question/answers:

Who can use the parking?

- Available to anybody (may be paid or free)
- Private parking
- Access restricted to people using specific object, typically customers of a shop (may be paid or free)

I feel that these answers can be improved, but I run out of ideas.

> You could ask for parking type (underground, multi storage and surface), too.

It is better to create a separate issue for a separate quest idea.

**Comment by westnordost** [comment]
It might be more natural to answer (from the user perspective) to combine this with whether there is a fee or not. Usually I'd say the sign that says that is a parking here also includes whether the parking requires a fee.
Naturally, if it is private parking, there is no fee and I have not heard of customer parking that still requires a fee. Does this exist?

**Comment by HolgerJeromin** [comment]
Yes. There are many parkings for hotel guests only which has to be payed.

**Comment by westnordost** [comment]
mh, okay. Then it may not be a good idea to combine it. But the wording must be clear, "Available to anybody" may suggest that it is free, "Available to anybody (may be paid or free)" on the other hand seems to be a bit long.

**Comment by matkoniecz** [comment]
> I have not heard of customer parking that still requires a fee. Does this exist?

In Poland there is plenty of "free for customers for up to X hours", "free to customers, paid otherwise", "first X minutes are free, longer stay is paid".

**Comment by matkoniecz** [comment]
> "Available to anybody" may suggest that it is free, "Available to anybody (may be paid or free)" on the other hand seems to be a bit long.

That is why I am unhappy with the wording.

**Comment by HolgerJeromin** [comment]
Access can be answered always, fee can be unknown.
Perhaps we can reuse the surface gui. 

What Access?
Public (implicit unknown fee)
   fee
   no fee
Customers (implicit unknown fee)
   fee
   no fee
Private

**Comment by matkoniecz** [comment]
I wanted to avoid question about fees - not sure it is unique to Poland but in many cases public parking spaces are paid/free depending on time (hour, day of week) and some private parkings (at places like tourist attractions) are staffed during some time and free otherwise.

**Comment by HolgerJeromin** [comment]
Imo is fee=no never paid, but fee=yes is normaly paid (but can be free at night for example)

**Comment by westnordost** [comment]
In light of #101 and #102, it might be a good idea after all to force the user to also answer _if_ there is a maxstay and fee. The UI could look like this:

Select one of: | and Select if applicable:
------------ | -------------
[ public, customers, private ] | but: [requires fee, has maxstay]

**Comment by matkoniecz** [comment]
If somebody wants to implement this my partial implementation at https://github.com/matkoniecz/Zazolc/tree/fork/app/src/main/java/de/westnordost/streetcomplete/quests/parking_access may be useful (I did easy 10%, remaining 90% - making nice interface still remains).
