### ISSUE TITLE
Run unit tests automatically

### ISSUE THREAD

**Issue by rugk** [westnordost/StreetComplete#1003]
You could use Travis CI (or other services) to run the unit tests automatically (for each PR, e.g.), so contributors (and you :wink:) see if they break something.

**Comment by matkoniecz** [comment]
@rugk Can you give an example of project that runs continous integration involving Android emulation?

**Comment by HolgerJeromin** [comment]
https://docs.travis-ci.com/user/languages/android/

**Comment by rugk** [comment]
That's not strictly an example, but likely a good doc. :smile: 

But there are also enough examples, [as I assume](https://github.com/search?utf8=%E2%9C%93&q=android+travis&type=). (there are a lot test projects and stuff like that)
But realistically the docs should be enough to setup it. :smiley:

**Comment by ENT8R** [comment]
Is there already somebody working on it?

**Comment by rugk** [comment]
I think no, otherwise one would have commented here or be assigned. :smile:

**Comment by ENT8R** [comment]
Okay. Then I will try to do this. I already set up Travis CI for some Node.js projects...

**Comment by matkoniecz** [comment]
@ENT8R Can you consider finishing #774 and #959 before starting that?

**Comment by ENT8R** [comment]
@matkoniecz This was my plan! 👍
