### ISSUE TITLE
Regression: wrong boundary detection (wrong signs shown in Germany)

### ISSUE THREAD

**Issue by RubenKelevra** [westnordost/StreetComplete#1007]
In v5.0b1 a wrong type of maxspeed sign is shown, well within German borders.

![](https://i.imgur.com/rVyoFIM.jpg)

**Comment by RubenKelevra** [comment]
The bikelane markings look wrong too. They are usually white not yellow in Germany!

![](https://i.imgur.com/GTf5h0h.jpg)

**Comment by westnordost** [comment]
I cannot reproduce this on my phone at that location. What is your android version, language and device?

**Comment by westnordost** [comment]
Do you have Android Studio installed?

**Comment by westnordost** [comment]
Could you please download, install and start the attached Android application on your device (rename .zip to .apk), zoom into the location where the two screenshots above happened and click on the map there? What country code is shown for these locations?

[countryboundaries-debug.zip](https://github.com/westnordost/StreetComplete/files/1889647/countryboundaries-debug.zip)

**Comment by matkoniecz** [comment]
> I cannot reproduce this on my phone at that location.

Can you share the location? I would test whatever I am able to reproduce.

**Comment by westnordost** [comment]
@matkoniecz The first is here https://www.openstreetmap.org/way/154904063

**Comment by matkoniecz** [comment]
I am unable to reproduce reported behavior.

**Comment by matkoniecz** [comment]
BTW, where yellow cyclelane and MAXIMUM are supposed to be appearing?

**Comment by westnordost** [comment]
Yellow cycle lane should appear in Switzerland, MAXIMUM in Canada.

**Comment by ENT8R** [comment]
> BTW, where yellow cyclelane and MAXIMUM are supposed to be appearing

AFAIK they should appear in the United States and maybe even some other countries...

**Comment by rugk** [comment]
Uh, but that is really bad then as these positions are far away. :laughing: How can it detect one position for one quest and a position on the other hand of the globe on the other?

Also is not this an issue with https://github.com/westnordost/countryboundaries? So could not the OP try to reproduce with the [sample app](https://github.com/westnordost/countryboundaries/tree/master/sampleapp)? (easier if https://github.com/westnordost/countryboundaries/issues/1 is done, maybe)

**Comment by matkoniecz** [comment]
> Yellow cycle lane should appear in Switzerland, MAXIMUM in Canada.

Thanks, for me everything works normally (MAXIMUM in Canada, yellow cyclelanes in Switzerland, what I would expect in Poland...)

**Comment by RubenKelevra** [comment]
Yeah sure it's within the boundaries of Wuppertal, NRW, Germany

**Comment by RubenKelevra** [comment]
So, here's the requested test:

![](https://i.imgur.com/FOt7MJD.jpg)

![](https://i.imgur.com/QeTyGVE.jpg)

Both applications at the same location, just retested. And reproduceable for me.

**Comment by westnordost** [comment]
Okay, so it is not a problem in the countryboundaries library but in the (Android) resource selection in StreetComplete. This makes the bug not critical, as the bug is only in display.

I will try to reproduce it on an Android 8.0 emulator.

Do you have Android Studio installed?

**Comment by francois2metz** [comment]
Same here in France. The sign here are different than the screenshot.
![screenshot_20180409-180659](https://user-images.githubusercontent.com/86659/38509220-9442ef60-3c21-11e8-9683-8aeda8d48a4c.png)

**Comment by westnordost** [comment]
Can reproduce on Android 8.0

**Comment by RubenKelevra** [comment]
@westnordost well, that was more a peak than the mean. So 80% of the time it's between 0.150 and 0.800 ms. But sometimes it's a bit above 2ms and in CH I saw values above 6ms for the first 3-4 positions, than it dropped. Overall the speed seem to improve after the first several locations in a country, looks like a kind of catching works here to improve it.

Overall, the delay feels longer in the app you provided. Between touch and the display it feels like 200-400ms, maybe just the "animation" of the box. 😉

**Comment by westnordost** [comment]
Yes, it feels slower because of that fading-in-fading-out box (it's called a toast in Android-sprech).

> Your fix sounds good, just out of curiosity, if I switch my device to English like "EN-US", are then US signs showed or the German ones, when I select a task in Germany? 🤔

Always the resources for the country the quest is displayed in should be selected. With the fix, this is now the case also for newer Android versions.

**Comment by RubenKelevra** [comment]
... which is great. This solution meet exactly my expectations :)

**Comment by RubenKelevra** [comment]
Checked and I can confirm a successful fix for v5.0b2.

Thanks a lot!
