### ISSUE TITLE
Add "About OpenStreetMap", add more info in "About StreetComplete"

### ISSUE THREAD

**Issue by matkoniecz** [westnordost/StreetComplete#1009]
App currently has "About StreetComplete" with some technical info.

I think that this program is directed also at people unaware how exactly OSM works, maybe it would be a good idea to add some additional explanation

- basic info about OSM (directed at people with nearly no knowledge about it)
- additional, more involved info how StreetComplete works (or maybe just a link to OSM wiki in "About StreetComplete" menu)

If that would be considered as a good idea I would prepare a PR.

**Comment by rugk** [comment]
Expanding "About Streetcomplete" for this would be okay, IMHO. Just a part like "StreetComplete depends/uses/contributes OpenStreetMap" and then all stuff you mentioned…

Note that for:
> additional, more involved info how StreetComplete works

the FAQ in the OSM wiki has already enough information? So a link to the FAQ in the app would likely not hurt. :smiley:

**Comment by matkoniecz** [comment]
> the FAQ in the OSM wiki has already enough information?

I though about explanation clear for somebody unaware about OSM beyond "good idea related to maps, something like Wikipedia and Google maps".

**Comment by westnordost** [comment]
So what would be the text?

**Comment by rugk** [comment]
That is too much text and much stuff can be covered in the "panes" shown at certain star levels, as it has been proposed in another "gamification" issue, I think.

**Comment by rugk** [comment]
Possibly also https://github.com/westnordost/StreetComplete/issues/1294 (requested by @Natenom) can be solved here, too, i.e. just add a link to the OSM quest list in the wiki there, too.

**Comment by westnordost** [comment]
Sovled through achievements
