### ISSUE TITLE
Quest: Does this parking area[access=customers|public] have a fee?

### ISSUE THREAD

**Issue by CloCkWeRX** [westnordost/StreetComplete#101]
Apps that use this data:
 * http://product.itoworld.com/map/7
 * https://play.google.com/store/apps/details?id=fr.lcdm.freeparking&hl=en

Answers:
https://wiki.openstreetmap.org/wiki/Key:fee
 * Yes (amount) - set fee:amount=$12.34 and fee=yes
 * No
 * Varies with time of day - add note

**Comment by gappleto97** [comment]
It would also be useful to note if the fee is flat, or based on the time you're there for.

**Comment by HolgerJeromin** [comment]
> It would also be useful to note if the fee is flat, or based on the time you're there for.

@gappleto97 Without a proper tagging schema this could not be supported by this app.

**Comment by Codain** [comment]
+1, also for bicycle parkings

**Comment by HolgerJeromin** [comment]
I have know very few bicycle parking places which needs a fee. 
I am not sure if a cycle parking fee quest would be overkill.

**Comment by matkoniecz** [comment]
For bicycle parkings it would be weird, at least in Poland I have never seen a paid bicycle parking.

**Comment by westnordost** [comment]
This quest basically has the same problem as #102, so that this quest would need to be limited to public/customer underground and parking houses.

**Comment by manuelVo** [comment]
I don't think that it would be acutally a false positive, because parking spaces with no `fee` tag basically mean that it's not known while `fee:no` ensures the user, that there are no fees for that parking space.

**Comment by ENT8R** [comment]
A user sent me the code of a possible implementation of this quest created by my tool, the [StreetCompleteQuestCreator](https://github.com/ENT8R/StreetCompleteQuestCreator). But it contains only the possibility to answer "Yes, there is a fee" or "No, there is no fee".
If this quest would be implemented, it would be easy to ask what the amount of the fee is... But I have no idea for a proper UI... The only thing that I think that might work is a small dialog after the user tapped on "Yes" which asks then for the amount of the parking fee...
Or should this quest be better a plain Yes/No quest, as I know some parkings which increase or decrease the amount of the fee **after** a specific time, which would be pretty hard to implement... Is there even a proper tagging scheme for this case?

**Comment by westnordost** [comment]
No, let's not ask for the fee. This kind of data should not be in the OSM database, it will also change all the time. Whether there is a fee or not is acceptable because it is like an access restriction: I.e. public/paid/private

**Comment by ENT8R** [comment]
Good point! So this can be an easy Yes/No quest. But what to do if there is a time-restricted fee? Should the user leave a note or should we offer another answer option using the opening hours selctor? I'd prefer the second one...

**Comment by westnordost** [comment]
Phew, I don't know, does this happen?

**Comment by ENT8R** [comment]
According to taginfo , yes...

**Comment by HolgerJeromin** [comment]
I would go for yes/no. This is shown in osmand app with an separate icon. 
opening_hour for free parking can change like the fee itself.
The question to ask should be something like 
"Is there at some time a fee needed [never] [sometimes/always]" or
"Is there at some time a fee needed [never] [yes]"

**Comment by manuelVo** [comment]
There are definitely parking spaces which have fees only during certain hours of the day (and none at all on weekends). There are plenty of those in my area.

I think the best way to tackle this would be 3 answer question "Is there a fee to park here?" with the answers "yes/no/depends on time (someone might reword that)" where the third option pops open the opening hours ui.

**Comment by HolgerJeromin** [comment]
yes+no are 97.03% of [all values in osm](https://taginfo.openstreetmap.org/keys/fee#values). 
Are there data consumers of the 2% valid hours tags? 
(pretending we have 1% other values like "privat" and many other values)

**Comment by ENT8R** [comment]
I think that fee=yes/no is the most important information. And if there is a parking which has only a fee during a specific time, the user can always leave a note.
