### ISSUE TITLE
one-way residential street do not show up with bicycle quest

### ISSUE THREAD

**Issue by RubenKelevra** [westnordost/StreetComplete#1013]
I found a bicycle lane which I seemed to have overseen before, so I looked at SC and it showed no quest.

I've tooked a look at the data with Vespucci and it revealed no tag for bicycle lanes.

I've voided the cache for quests, just activated the bicycle lane quest and reload the data. Still no quest-popup.

The street is a quite usual 4 way residential street with a center divider, that's why it's mapped as two one-way lanes, but from the tags I don't see a reason why it shouldn't be suitable for a bicycle lane quest.

Did I overlooked something?

Version is v5.0b1

I've added a yellow marking is next to the way:
![](https://i.imgur.com/nTA3cPP.jpg)

![](https://i.imgur.com/I4E510F.jpg)

**Comment by matkoniecz** [comment]
Low maxspeed roads are excluded from this quest on assumption that cycleway infrastructure is unlikely in that cases.

**Comment by matkoniecz** [comment]
It may or may not be a good idea.

**Comment by westnordost** [comment]
I think low maxspeed roads are very unlikely to have bicycle infrastructure. I have no statistics, just my personal experience.

**Comment by RubenKelevra** [comment]
Well, this street got one on both sides, actually not that uncommon 🤔

**Comment by rugk** [comment]
Hmm, also cannot follow the logic that "low maxspeed" makes it unlikely to have bicycle infrastructure. Actually, It's kinda the reverse, IMHO, asa  high maxspeed may endanger bicyclists, so when there is a high maxspeed it is rather unlikely to have bicycle infrastructure there. E.g. on autobahns/highways there is no bicycle infrastructure… :wink: (i know, there are other reasons for that, but just so you get my point)

**Comment by matkoniecz** [comment]
>  when there is a high maxspeed it is rather unlikely to have bicycle infrastructure there

That is exact reason why this roads have cycleways along them, separate from traffic (or sidewalks with legal cycling or at least cycle lanes). 

Are you seriously claiming that road with maxspeed 70 is less likely to have cycling infrastructure than residential road in maxspeed 30 zone?

Motorways are a special case and are excluded anyway...

**Comment by rugk** [comment]
> separate from traffic 

Okay, that's a good argument. I only thought of cycleway lanes or so. In these cases maxspeed 70 is likely less likely to have such a lane.

Then, however, one still has to explain why maxspeed 30 (or lower) is unlikely to have bicycle infrastructure. These streets are common in cities or villages and I think such infrastructure (even if it is just a bike lane) is not really rare there.

**Comment by westnordost** [comment]
Present statistics that show otherwise and I will drop this requirement.

**Comment by rugk** [comment]
Maybe we could do since parsing of the data already mapped in OSM?

**Comment by matkoniecz** [comment]
> Maybe we could do since parsing of the data already mapped in OSM?

Yes, but as I am 99,9% sure that (except highway=trunk, motorway and links) road with maxspeed above 30 are significantly more likely to have cycling infrastructure* than roads with maxspeed below 30 I am not planning on doing that.

*except oneway:bicycle=no in some places - if you count it as "infrastructure"

**Comment by westnordost** [comment]
So, I will close this. If anyone wants to try to research there more and find some statistics (through overpass?) that show otherwise, you are welcome to open another issue.

**Comment by rugk** [comment]
"I'm planning to do that"_so statistics incoming.😉
In other words you could have left this open for the time until this final stat is made, to solve this issue for good and all!

**Comment by rugk** [comment]
> Who is quoted here?

You: "I am not planning on doing that" – sorry, my quote was not literally. :smiley: 

And yes, I know it is okay to call for a new issue and close this one. It's just only one statistic is missing, then this issue can be closed finally. And as you pledged to provide that, why not let it open until you do? (Hope it's not too much work.)

**Comment by RubenKelevra** [comment]
> That is exact reason why this roads may have cycleways along them, separate from traffic (or sidewalks with legal cycling or at least cycle lanes).
> 
> Are you seriously claiming that road with maxspeed 70 is less likely to have cycling infrastructure than residential road in maxspeed 30 zone?

Yes I am.

This one got a cycleway (not tagged in OSM):
https://www.openstreetmap.org/way/113482748

This one has not:
https://www.openstreetmap.org/way/37178440

They are actually directly next to each other and the second one has less elevation - since it's an old railway. Also, there's a cycleway over the whole old railway line, except this part which is a 70 zone. They decided it would be better to route it thru the 30 zone with a cycleway on the street, which has a lot more elevation.

> Present statistics that show otherwise and I will drop this requirement.
@westnordost 

Well, this doesn't work this time. SC had 2% of all changesets last year, so much details were added on the ground by this app. Many cycle ways might not be tagged, because of this filter. So any statistic based on this data might be biased, because of this bug. But my typical example shows, that you can't assume this.

Want more proof? Wuppertal got 174 ways with cycleway=* tag and maxspeed=30, just 11 of them are tagged with cycleway=no. The most common tag is "opposite" which shows cycleways in real oneway streets are a common thing, even in a 30 kph area.

**Comment by rindlerblabla** [comment]
In my experience (from Sweden) it's connected to the classification of the highway when it comes to highways with speed lower than 50 (whether there is a cycle lane or not). Residential highways very seldom have cycle lanes, but unclassified highways, tertiary highways and so on can have a cycle lane even if the maxspeed is low.

In this case obviously the highway is classified as a residential highway though. Maybe the classification is wrong, hehe?

**Comment by rindlerblabla** [comment]
Hehe, thanks. Maybe it's out of the scope for this issue, but I think that highway could have been tagged as tertiary as well. Compared to other residential highways I think that highway has a higher importance for routing etc. But i havent seen that place IRL.

Ordinary residential highways seldom have bicycle lanes when the maxspeed is low, in my experience, but when it comes to residential highways with greater importance (=tertiary) the maxspeed is not as important.

At least I have used tertiary highways that way.

**Comment by rindlerblabla** [comment]
Yes, or just exclude residential and skip the maxspeed thing but maybe it's just the area where I am mapping this is the situation.

**Comment by westnordost** [comment]
Ok so I will exclude `highway=residential` and only exclude speed limits of 20km/h and below.

**Comment by RubenKelevra** [comment]
@rindlerblabla well, I got your point, but using this tag would fool routers to use it, which makes no sense, using the parallel Kölner Straße is much faster. That's the reason why it's nearly ignored by locals which lowers it's importance. :)

**Comment by RubenKelevra** [comment]
Well, version 5.0 allow streets which are **not** residential to be included to this quest, but my issue was about residential roads with bicycle infrastructure and 30 kph speed restrictions. So actually the issue was not fixed, but very edgy scenarios for streets which are not residential but have a speed restriction below 30 kph. 😐

**Comment by westnordost** [comment]
I know. The app will not ask for residential 30kphs

**Comment by RubenKelevra** [comment]
But this was the point of this ticket, that I found a residential street with 30 kph and cycle way which the app does not show. And I also showed, that this case is pretty common.

**Comment by RubenKelevra** [comment]
@westnordost so if you did not want to fix this issue with your change, why did you closed this ticket with it?

I totally don't get your change... streets which aren't residential but maxspeed=30 are pretty uncommon. And I showed that on the other hand streets with maxspeed=30 and residential have bike lanes.

So what exactly do did I miss here?

**Comment by ENT8R** [comment]
> And I showed that on the other hand streets with maxspeed=30 and residential have bike lanes.

IMO the amount of residential roads with maxspeed=30 and a cycle way really depends on the area you live in. In urban areas you will maybe encounter more of these than in rural areas, where (just speaking from my experience) those roads do nearly never exist...

**Comment by RubenKelevra** [comment]
@ENT8R well, that might be true for your area, but my data here, as shown, draw a different picture.

Furthermore we do ask for residential streets for bicycle lanes, in case the maxspeed was previously not determined the maxspeed quest is followed by the bicycle quest:

https://www.openstreetmap.org/changeset/58398593

**Comment by matkoniecz** [comment]
@RubenKelevra See #746

**Comment by ENT8R** [comment]
> that might be true for your area, but my data here, as shown, draw a different picture.

But it is also not possible to disable this question for low maxspeeds in rural areas and enable it only in urban areas... So how should we handle this?

**Comment by RubenKelevra** [comment]
@ENT8R what about splitting this into two categories? A standard and an extended bicycle quest, with the extended disabled by default without this restriction. I don't see an issue with adding more definitive answers to the database, stating that this residential road has no bicycle lane. But I understand that those quests might cause many additionally "clicks" for users in the wrong areas.
