### ISSUE TITLE
Allow one side mapping of bicycle lanes at a time

### ISSUE THREAD

**Issue by RubenKelevra** [westnordost/StreetComplete#1014]
This might sound a bit ridiculous, but it's actually quite difficult to find the information for both directions of a street at a time.  With a dedicated bike lane it's might be easy, but with a sidewalk which allows bikes it's often not marked anywhere on the sidewalk. There's just a sign on each junction.

Even in the city they are often more that a 5 minute walk appart, so in short it's often for me possible to tag just one side, but I'm not able to just tag this side and leave the other side blank.

It would be nice if you could consider to split the quest in half, display it the same way as before, but let the user submit just a half completed quest. The quest should still show up, for me and others, to complete the other side. 🙂

**Comment by westnordost** [comment]
So, in other words, allow the quest to be answered when the surveyor only filled in one side. This is problematic:
1. I already got feedback from users who wondered why the app would tell them that the form is not completed even though they specified the cycleway. They obviously did not understand the form and just specified it for "any" side. To require both sides to be filled out is a safeguard against this because it requires the surveyor to understand the form first before he blindly fills it out
2. It's not clear if the app should then still show a quest for such a half-specified road. If yes, then the quest would then immediately pop up again, asking for the other side to be specified as well (because automatically the "next" quest is selected for the same element). This might be irritating. If not, it would be even worse, because it robs oneself and other surveyors to fill in this info later.

**Comment by rugk** [comment]
First, as a reference link. The requirement to fill out both sides has been introduced in https://github.com/westnordost/StreetComplete/issues/700, and IMHO it is really good and should stay there.

As a middle-way maybe we could add an "Other answer": "I can only fill out one side"
This would then drop the requirement to fill both sides for the current quest (only!).

If done so:
> It's not clear if the app should then still show a quest for such a half-specified road.

I'd say no. If the user explicitly selects they can only fill out one side, then they cannot fill out the other side even if the quest pops up again.

**Comment by westnordost** [comment]
> The requirement to fill out both sides has been introduced in #700

No, only the error message was made clearer.

Yeah, I will close this. To change this is too problematic.

**Comment by RubenKelevra** [comment]
Well, I understand your criticism, but if this dialog is a issue, we might want to rework it.

The feature is really needed since it's also problematic to add details a half hour to an hour later out of memory instead of just adding this directly. I also tend to tag by some days old memory, when I drive the way down in opposite direction on a different day.

If you're not clear how to solve it, it's a bad habit to close it. Let's just wait, if someone got a better idea for this and tag it as backlog.

There's nothing explicit mentioned by you why this is a bad idea, just UI issues and user confusions. :)

**Comment by RubenKelevra** [comment]
@westnordost 

So... I've created a draft for a UI change to accommodate this issue and also might fix the confusion for some users. 

If you click on an icon for the bicycle lane, the icon split in two, allowing the user to select which side he wants to edit.

We would need 4 different layouts: top-bottom, left-right, left&up-right&down and left&down-right&up to adapt to the different direction of a way somewhat dynamically. My draft just shows an example of a north-south-way and in for this case a left-right layout.

![quest_pin_duplicate_example](https://user-images.githubusercontent.com/614929/38758678-66753936-3f72-11e8-95b5-670fb2ecbae7.png)

I think an additionally "skip this task for this session", would help to uncover the next possible task, if you just want to tag one side.

---

This might look like a lot of work for just bicycle lanes, but it would actually help getting more details to maxspeed-tagging as well, which we currently just select as "for a section of a road" and not for the direction. So I think currently it's a lot of guessing, that the other side has the same max-speed, which is often the case, but the edge-cases are probably completely overlooked by SC mappers currently.
