### ISSUE TITLE
Inconsistent checking and head's up for house number quest

### ISSUE THREAD

**Issue by RubenKelevra** [westnordost/StreetComplete#1015]
We've added a new information about housenumbers, stating that house numbers can be submitted as range (with a dash) or as list (with a comma separation).

First of all, there's a typing error in the German popup about this:
![](https://i.imgur.com/zt4xf2G.jpg)
(there should be no white space in front of the comma)

Wiki clearly states, that there shouldn't be a whitespace in this case.

But the real issue is, that we're showing a popup if the housenumbers "looks" odd. But we show this for values like "1,2" but not for "1-2", which is confusing.

We should remove the warning for comma seperated lists, since they are okay as we explained the users in the popup above.

Please still show them when the user starts to input lists with a empty space, like "1 2" or "1, 2". They should be considered wrong.

**Comment by RubenKelevra** [comment]
I just noticed that the font for the housenumbers are suboptimal, it has a huge spacing in front of the comma, which looks like a white space. If this is the same font than on the popup, where we explain the housenumber lists and ranges, than this might be no typo but just the suboptimal font.

**Comment by matkoniecz** [comment]
>  (there should be no white space in front of the comma)

See https://github.com/westnordost/StreetComplete#contributing - it is fixable by fixing translation at https://poeditor.com/join/project/IE4GC127Ki

**Comment by rugk** [comment]
I don't exactly understand your issue here.

Can't you enter `3-5` as a house number? Or can't you enter `3,5` as a house number and is it rejecvted by SC, or what is the issue here?

**Comment by matkoniecz** [comment]
@rugk 

> But the real issue is, that we're showing a popup if the housenumbers "looks" odd. But we show this for values like "1,2" but not for "1-2", which is confusing.

**Comment by rugk** [comment]
Ah okay, thanks for pointing me there.

Actually both things are more or less valid as house numbers, however.
