### ISSUE TITLE
List of StreetComplete-related (GitHub) repositories

### ISSUE THREAD

**Issue by rugk** [westnordost/StreetComplete#1018]
Follow-up of https://github.com/westnordost/StreetComplete/issues/928

## Problem

* SC has inspired many to create tools or other stuff in connection to SC
* Finding all related tools or dependencies or stuff, which has been created for StreetComplete or is used by SC or is otherwise (directly) connected to it

This has the following effects:
* contributors may not notice stuff, where they could contribute (code), if they e.g. do not know Java/Android
* the maintenance of the other repos is not very good/few people actually discover them

## Solution
list of all related repos/source code/projects

There is just one question:

## Where?

* GitHub wiki (it is mostly development-related and still connected to this repo)
* OSM wiki (I'd rather avoid thta, as it is too much focused on users or OSM mappers, not devs)
* Contributing.md file (maybe, I am anyway expanding it and already include some dependencies)
* another separate GitHub repo (not really possible, because one would not find that repo then, this would require https://github.com/westnordost/StreetComplete/issues/928 then, i.e. the StreetComplete organization would have only one other repo called "community", similar to like [borg has done it](https://github.com/borgbackup/community))
* issue in this repo (note: very ugly)
* somewhere else?

## How?

IMHO it should be a small list (or table?) like:
``` 
* [author/blabla-tool-sc](link-to-project), used for XY/created because XY
* …
```

maybe structured a bit, if needed (i.e. separated in "tools", "dependencities" and "others")

It could e.g. look like this:
* https://github.com/borgbackup/community

## Why?

It would also have the following advantages:
* it demonstrates that this project has quite a community
* anyone can help by writing stuff in their own language, if needed for an issue or so

## What to consider?
* The list has to be editable by contributors (via PRs or directly).
* The list should be some development reference, not intended for SC users.
* It should allow attribution of the author. (AFAIK always possible)
* Contributors should be able to find it.
* anything else?

**Comment by matkoniecz** [comment]
@rugk 

I would just make PRs similar to https://github.com/westnordost/StreetComplete/pull/836 if there are some project that are missing

**Comment by rugk** [comment]
In other words: You'd favor to include it in the Contributing file.

**Comment by westnordost** [comment]
Yes, me too. So, see the PR.

**Comment by rugk** [comment]
So okay, I've added this too https://github.com/westnordost/StreetComplete/pull/1005.
