### ISSUE TITLE
Tile caching issue

### ISSUE THREAD

**Issue by abendebury** [westnordost/StreetComplete#1019]
Sometimes at a certain zoom level it seems like a tile is not available (see first pic). However, after zooming out, the tile loads at a reduced zoom (see second pic), then after zooming back to the original level the tile remains (third pic).

It seems like it should either always be shown (if it is not in the local cache) or never be shown (if it is not in the cache).

https://ibb.co/hBngXS
https://ibb.co/bYpvsS
https://ibb.co/eE5qRn

**Comment by ENT8R** [comment]
Even if you can reproduce this again, it should not be an issue with this app but rather with the render library https://github.com/tangrams/tangram-es
