### ISSUE TITLE
Add an API to "inject" quests into StreetComplete

### ISSUE THREAD

**Issue by gappleto97** [westnordost/StreetComplete#1027]
The idea here is to allow other app developers to come up with quests that are either partially or tangentially related to OpenStreetMap, and use StreetComplete as a framework. This can be achieved by providing an API to other apps on your phone. This API should provide at least the following:

1. A way to insert a "quest label" that can be turned on or reordered like standard quests
2. A broadcast that says "I'm scanning for quests in this bbox, please request if you want the contents"
3. A way to request the contents of a bbox
4. A way for quests to designate which UI they want, and provide stuff to get put in the template
5. Either
    1. A broadcast that has the serialized contents of that UI, when completed, OR
    2. The ability for an app to specify how that input gets translated into OSM objects like a normal quest

Additionally, it would be useful if these quests could interact with the camera, like if you were leaving a note. That would enable quests like "These Wikipedia objects with locations do not have pictures", or other such things.

This also allows quest developers to have an easy way to develop quests before submitting them to the main project, since they can push it out for people to test. It also enables regional quests (like #639), or community-specific quests (like #904).

I was told to make this issue in #98

**Comment by matkoniecz** [comment]
> This also allows quest developers to have an easy way to develop quests before submitting them to the main project

Why making quest and injecting quest would be easier than just making quest?

**Comment by gappleto97** [comment]
@matkoniecz I'm not actually sure that it would be easier. However, if there were an example plugin, and an easy way to fill in your details as if it were a builtin quest, then you could (hopefully) just copy the appropriate parts as a pull request once you've tested it.

**Comment by matkoniecz** [comment]
> The use case I'd imagine would be quests clearly outside of the scope of SC (e.g. that Wikipedia thing, which has been mentioned)

That would make sense, as it would allow distributing addons with quests rejected by @westnordost (including some too specialized ones)

There is cost-benefit question whatever necessary code is worth it, but it is question to @westnordost 

> You would then maybe "only" have to develop a plugin, which adds the quests you want.

In my case it would not be helpful as I tweak also some parts of interface (like "are you sure" for toggling quest disabled by default), change what is disabled by default and quest order and switch the map style and do some other changes.

**Comment by ENT8R** [comment]
> then you could (hopefully) just copy the appropriate parts as a pull request once you've tested it.

But you can do the same with a normal quest. Just search for an already implemented quest, copy the parts that you need and modify them. This is how I did it too in the beginning

**Comment by gappleto97** [comment]
In any case, I think we agree that it would help things that are unrelated to OSM, and things that are too specific/specialized to get in mainline StreetComplete.

**Comment by RubenKelevra** [comment]
Well, JOSM actually have this kind of functionality. Some stuff is defined in a Wiki which is fetched on startup. Maybe this is also worth a discussion for SC? 🤔

**Comment by rugk** [comment]
> I think we agree that it would help things that are unrelated to OSM

BTW, can you provide some actual examples/use cases for it? (or things you have in mind or maybe would even implement…)

**Comment by gappleto97** [comment]
I dont think that I would necessarily implement any of these, but:

* add camera info to both OSM and WhereAreTheEyes
* add Pokemon Go spawn things to the website I forget the name of
* add highly specific dietary guideline quests (kosher, halal, pescetarian, etc)
* add more advanced surveying quests (specific building height)
* Wikipedia locations without pictures
* Any quests that dont meet StreetComplete's guidlines (eg, "does this Walmart also have a pharmacy", which then adds a pharmacy node if yes)

**Comment by rugk** [comment]
> add camera info to both OSM and WhereAreTheEyes

is in the scope of StreetComplete and tracked in https://github.com/westnordost/StreetComplete/issues/87

> add highly specific dietary guideline quests (kosher, halal, pescetarian, etc)

same: https://github.com/westnordost/StreetComplete/issues/639

As for the otherrs (that are not related to SC): yes, some ideas at least.

**Comment by gappleto97** [comment]
I mentioned #639 at the top as well, because the main protest against it is that it would be difficult to tell. It seemed to me at the time of writing that it would not be included.

**Comment by rugk** [comment]
Not included, but discussed and not rejected.

Anyway, let's get back to topic…

**Comment by westnordost** [comment]
I do not plan to implement such a thing. However, I can follow your argument and it may certainly make sense for other people to use the framework provided by StreetComplete as a data-collector framework but this is clearly nothing I would do, it is out of scope for this project. StreetComplete is for the time-being OpenStreetMap only.
Forkers shouldn't have much problems in customizing this for their needs though.
