### ISSUE TITLE
Zoomed tiles not loading

### ISSUE THREAD

**Issue by abendebury** [westnordost/StreetComplete#1032]
Loading new tiles at low zoom works fine, but if I zoom in to the level that I expect to see street buildings no tiles load at all. Using street complete 5.0 on Android 4.4.4. have tried reinstalling and clearing cache without success.

**Comment by ENT8R** [comment]
Seems to be the same issue as #987...

**Comment by ilyaguy** [comment]
No tiles at any zoom level. Android 7.1, app installed from play market.

**Comment by Akasch** [comment]
I have a look at it as soon as possible, could be a few hours as I am traveling at the moment.

Am 24. April 2018 22:45:01 MESZ schrieb Illia Hai <notifications@github.com>:
>No tiles at any zoom level. Android 7.1, app installed from play
>market.
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/westnordost/StreetComplete/issues/1032#issuecomment-384073942

-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.

**Comment by matkoniecz** [comment]
@Akasch Can you consider looking also at #1011 - any reply, also one that makes clear that it is unfixable, like "for financial reasons it is not feasible to do this", is better than no reply at all.

**Comment by matkoniecz** [comment]
Thanks!

**Comment by ENT8R** [comment]
@abendebury as this is fixed now, can this be closed?
