### ISSUE TITLE
Facilitate translation in Weblate

### ISSUE THREAD

**Issue by PanderMusubi** [westnordost/StreetComplete#1035]
Translation of the PO files can be done on Weblate https://hosted.weblate.org/about/ They offer free hosting for FOSS projects.

**Comment by ENT8R** [comment]
But why should we offer two translation platforms? Doesn't this add too much complexity? Also the strings are not saved in PO files but in the normal XML format for android: https://developer.android.com/guide/topics/resources/string-resource#String

**Comment by PanderMusubi** [comment]
Excuse, meant to say XML, not PO. also now I see that it is facilitated at POEdit**or**, which I had mistaken for https://poedit.net/
