### ISSUE TITLE
StreetComplete uses a lot of battery

### ISSUE THREAD

**Issue by Rudloff** [westnordost/StreetComplete#1036]
Hello,

I am using a Fairphone 2 with Android 6.0.1. My battery is is 2-3 years old and does not last very long but it is way worse when I'm using StreetComplete 5.0. When I'm actively using the app, I lose ~30% of my battery in 30 minutes.
At first I thought it was mostly due to the GPS, but I disabled geolocation in Android settings and it still uses a lot of battery.

The strange thing it that in the battery report, most of the battery usage is not attributed to StreetComplete but to "other usages":
![screenshot_20180428-160922](https://user-images.githubusercontent.com/840125/39401755-7cb8feee-4b4d-11e8-9714-813792bd55a6.png)
(You can see the battery dropping very quickly near the end, when I started using StreetComplete.)

**Comment by westnordost** [comment]
Is it the same if you disable GPS?

Am 29. April 2018 01:36:57 MESZ schrieb Pierre Rudloff <notifications@github.com>:
>Hello,
>
>I am using a Fairphone 2 with Android 6.0.1. My battery is is 2-3 years
>old and does not last very long but it is way worse when I'm using
>StreetComplete 5.0. When I'm actively using the app, I lose ~30% of my
>battery in 30 minutes.
>At first I thought it was mostly due to the GPS, but I disabled
>geolocation in Android settings and it still uses a lot of battery.
>
>The strange thing it that in the battery report, most of the battery
>usage is not attributed to StreetComplete but to "other usages":
>![screenshot_20180428-160922](https://user-images.githubusercontent.com/840125/39401755-7cb8feee-4b4d-11e8-9714-813792bd55a6.png)
>(You can see the battery dropping very quickly near the end, when I
>started using StreetComplete.)

**Comment by Rudloff** [comment]
Yes, I tried to completely disable geolocation and it still uses a lot of battery.

**Comment by westnordost** [comment]
What is "autres utilisations" if you switch the smartphone to English? Did you try to google for what is behind this item?

**Comment by rugk** [comment]
He said:
> The strange thing it that in the battery report, most of the battery usage is not attributed to StreetComplete but to "other usages":

(and DeepL also translates it to "other applications")

BTW; personally, I've never seen that entry in the Android battery usage – very strange it cannot attribute such a large amount of battery usage to an app.

**Comment by westnordost** [comment]
I asked not how it translates but how specifically it is translated in Android - so that one can google for it.

**Comment by Rudloff** [comment]
It is called *Miscellaneous* in English. The detailed view contains some explanation:
![screenshot_20180429-235602](https://user-images.githubusercontent.com/840125/39411385-5b647356-4c09-11e8-886a-25b7a4e72e3c.png)

This article also has some useful explanations: https://medium.com/@dotandroid911/what-is-miscellaneous-battery-drain-in-android-how-to-fix-it-d6eb9035e513

**Comment by matkoniecz** [comment]
Is it possible that it was happening in area with poor network connection?

I never encountered it, but some people claimed to notice extreme battery consumption with phone attempting to use low quality or missing network connection (constant reconnecting).

It would fit that battery consumption was not attributed directly to Street implemented.

**Comment by Rudloff** [comment]
I already encountered the behavior you are talking about, but here it happened in a city with a good 4G signal.

I could reproduce the issue several times in the past days, it clearly happens when I'm using StreetComplete, the battery starts draining very fast (almost 1% per minute) and it stops when I kill the app.

**Comment by westnordost** [comment]
Also if it is in the background?

Am 30. April 2018 10:56:49 MESZ schrieb Pierre Rudloff <notifications@github.com>:
>I already encountered the behavior you are talking about, but here it
>happened in a city with a good 4G signal.
>
>I could reproduce the issue several times in the past days, it clearly
>happens when I'm using StreetComplete, the battery starts draining very
>fast (almost 1% per minute) and it stops when I kill the app.

**Comment by Rudloff** [comment]
No, only if the app is in the foreground I think.

**Comment by westnordost** [comment]
I can reproduce it. It seems to be caused by the compass on the upper right corner. Will investigate.

**Comment by westnordost** [comment]
It looks like looking for the compass was a red herring.

It is true that while the map is shown, even if not moved, rotated etc, 10% CPU is used continuously (as opposed to i.e. 0% when in the settings screen), so I guess this could be the reason for the battery drain. However, even if the compass is never updated, it changes nothing.

**Comment by westnordost** [comment]
It looks like most of the CPU time is spent in a GL thread, I guess the tangram-ES GL thread, more specifically, in the function `eglSwapBuffers`.

![profiler](https://user-images.githubusercontent.com/4661658/39478571-207e0350-4d63-11e8-90a6-02111fd7e264.png)

I checked if the existance of shader code in the map style may be the culprit. It is not.

I think I will ask in the tangram-es bugtracker for help.

**Comment by westnordost** [comment]
https://github.com/tangrams/tangram-es/issues/1800

**Comment by westnordost** [comment]
fixed

**Comment by Rudloff** [comment]
Thanks a lot for investigating this!

**Comment by ENT8R** [comment]
In https://github.com/westnordost/StreetComplete/issues/1041#issuecomment-385463857 @westnordost said that he wanted to release an update today/tomorrow
