### ISSUE TITLE
UK speed limit quest inaccurate in built up areas

### ISSUE THREAD

**Issue by mwild1** [westnordost/StreetComplete#1037]
The speed limit quest explicitly asks the user about signs, however not every road will have a sign. This is especially true in built-up 30mph areas where street lighting is present.

Currently the quest let's you answer 'no sign' but then appears to assume this means national speed limit applies.

Sources:
- https://en.wikipedia.org/wiki/Built-up_area_%28Highway_Code%29
- http://www.speedlimit.org.uk/speed_markings.html

**Comment by westnordost** [comment]
So with what maxspeed:type value is the street supposed to be tagged in the case of such a built-up area?

**Comment by westnordost** [comment]
So with what maxspeed:type value is the street supposed to be tagged in the case of such a built-up area?

Am 29. April 2018 09:27:16 MESZ schrieb Matthew Wild <notifications@github.com>:
>The speed limit quest explicitly asks the user about signs, however not
>every road will have a sign. This is especially true in built-up 30mph
>areas where street lighting is present.
>
>Currently the quest let's you answer 'no sign' but then appears to
>assume this means national speed limit applies.
>
>Sources:
>- https://en.wikipedia.org/wiki/Built-up_area_%28Highway_Code%29
>- http://www.speedlimit.org.uk/speed_markings.html

**Comment by mwild1** [comment]
That's something I'm not 100% clear on (I'm no OSM expert, just trying to contribute casually), which is why I limited my issue to the problems with what the user sees.

[The wiki](https://wiki.openstreetmap.org/wiki/OSM_tags_for_routing/Maxspeed#United_Kingdom) is not exactly clear with "Recommended tagging" listing multiple different incompatible ways of tagging!

There was a long discussion in https://github.com/westnordost/StreetComplete/issues/492 which led to the current implementation, but focused on issues with the national speed limit (which varies on different types of road, as well as different types of vehicle).

I notice this quote though from https://github.com/westnordost/StreetComplete/issues/492#issue-250618018:

> The UK consensus was to always add a numeric value in maxspeed, use maxspeed:type to clarify whether the value was absolute (explicitly signed as such) or a national speed limit (denoted by the black bend on white sign).

However all of the above seem to agree that there should be a numeric value, which for 30mph often means there is no sign in the immediate vicinity (30mph areas typically have street lights, and street lights legally mean 30mph if there is no sign).

**Comment by westnordost** [comment]
I read your links. The second link you posted contains the following paragraph (not the sentence in bold):

> Any road with regular street lighting has a default speed limit of 30 mph unless signs indicate otherwise. **The entry to a 30 mph zone must be marked by a "30" sign on both sides of the road**, but no repeater signs are permitted within the zone (on the grounds that they might be confusing if some roads had them and others didn't). "30" roundels on the road surface are however permitted, with a special dispensation. 

This sounds like the sections within a built-up area with *"implicit"* speed limits actually *do have* a sign at the very beginning of the road.

**Comment by westnordost** [comment]
*2* would be an option, but it seems inconsistent to not tag a `maxspeed:type` on an implicit speed limit within a built-up area in UK but use a completely different tag to infer an implicit speed limit. 
After all, the `maxspeed:type` tagging is an invention of the British OSM community.

My concern is additionally, that it might make things more complicated for data consumers who will have to infer the implicit speed limits then because then they not only have to look at road type and `maxspeed:type` (et al) but at theoretically any tag.

Anyway, this is something that the community should decide. I will post a question in the forum or on the British mailing list in the next days.

**Comment by westnordost** [comment]
By the way, 1 is not an option because of https://github.com/westnordost/StreetComplete/issues/457

**Comment by westnordost** [comment]
So I posted to the mailing list, one reply was especially helpful: Someone extensively researched the legislative situation in the UK and wrote it down here: https://wiki.openstreetmap.org/wiki/User:Jamicu/UK_Speed_Limits

The quest will now ask after the user confirmed that there is no sign whether the street is lit or not. If it is lit, `maxspeed:type=nsl_restricted` will be tagged. If not, it will ask the usual "are the carriageways segregated?" question.
In case that the road is already tagged with `lit=yes` or `no`, it will skip the "is the road lit" question.

**Comment by SomeoneElseOSM** [comment]
For completeness, the mailing list post is https://lists.openstreetmap.org/pipermail/talk-gb/2018-April/021319.html
