### ISSUE TITLE
Wrong position when creating a new note

### ISSUE THREAD

**Issue by deerwood** [westnordost/StreetComplete#1039]
When creating a new free note (with button bottom left) I always make sure to set the mark at the very exact position, even zooming in as far as possible.

But the marks don't show up in OpenStreetMap at the correct location. They have some offset, annoying other OSM editors.

See examples:

Note north of POI

![notes_offset1](https://user-images.githubusercontent.com/90085/39414498-8b6ddbf8-4c38-11e8-8a10-f54b499bdf03.jpg)

Note south of POI:

![notes_offset2](https://user-images.githubusercontent.com/90085/39414530-fe800e4a-4c38-11e8-8e4c-11f92d8bf811.jpg)

The offset in the samples is ~10-20 meters. I couldn't find a systematic/pattern for the direction.

**Comment by ENT8R** [comment]
Do you know the direction which the map was oriented to when you created the note? This could maybe be the pattern...

**Comment by westnordost** [comment]
This would be quite the critical bug. However, I cannot reproduce it. Placing the note works precisely on portrait and landscape mode, and on any map rotation for my phone.

So, I need more information, starting with device and android version, and the things enquired by @matkoniecz

**Comment by westnordost** [comment]
Also not reproducable with extremely tilted map. I need more information from you, @deerwood

**Comment by deerwood** [comment]
First 4 tests today: untilted map, fixed to always north, phone in portrait orientation and held almost parallel to ground, phone turned N, S, E and W when positioning marker an pressing OK. All good, position of marker in OSM as set in SC. Will further try to reproduce with tilted map.

Besides, my phone is a cheap Wiko Pulp 3G with Android 5.1, in case that matters.

**Comment by westnordost** [comment]
Perhaps this came together like this?:

[http://www.westnordost.de/misc/screenrotate_shifts_note.mp4](http://www.westnordost.de/misc/screenrotate_shifts_note.mp4)

You first placed the note, then rotated the screen to have a larger input field and on finishing it you did not notice that the note shifted on screen rotate (because the keyboard covered it)

**Comment by westnordost** [comment]
I implemented now that a press on "OK" first closes the keyboard if it is still open, then another click on "OK" will save the note.

**Comment by goldfndr** [comment]
I suggest changing the word "Ok" to "Save" when the keyboard is collapsed.

**Comment by goldfndr** [comment]
Er, collapsed and the field isn't zero-length.

**Comment by deerwood** [comment]
Closing the keyboard and thus showing the marker again is a good idea. However I'm pretty sure to have closed the keyboard manually always. And I never use landscape mode (only accidently). Usually the phone is on my bikes handlebar in portrait mode ~30° tilt, when entering longer text, I remove it and hold it ~45° tilt. I most often have the map tilted and manually turned into driving direction, even when entering new notes.

The wrongly placed notes where added after having used SC for 2-4 hours with screen always on and thus battery rather low. I'll further investigate the next days. Maybe it is a problem with my phone?

**Comment by deerwood** [comment]
I tested again several times, now with tilted and rotated map and after ~1-3 hours usage of SC. No problem at all aka I can't reproduce.

So I'm sorry to have bothered you with a false alarm.
