### ISSUE TITLE
Quest: Does this amenity=cafe|restaurant|fast_food offer takeaway?

### ISSUE THREAD

**Issue by CloCkWeRX** [westnordost/StreetComplete#104]
Answers:
 * https://wiki.openstreetmap.org/wiki/Key:takeaway

**Comment by westnordost** [comment]
Difficult. Perhaps only limited to fast food. Answering quests should be able to be done on the go. If you need to go inside ans ask, that is usually to much already. Few fast food places will have a sign telling you that they have takeaway available.

**Comment by ENT8R** [comment]
I am working on adding this quest at the moment, but I could not find a good icon... Can you help me?

**Comment by westnordost** [comment]
Before implementation it must be cleared up whether / how this quest should be implemented at all. See my previous comment.

**Comment by ENT8R** [comment]
Well... Then I think this quest doesn't make much sense, because nearly all fast food restaurants have a `takeaway` tag and like you said, restaurants and cafes for example won't have a sign if they offer takeaway...

**Comment by westnordost** [comment]
Ill close it then.

**Comment by ENT8R** [comment]
> Then I think this quest doesn't make much sense, because nearly all fast food restaurants have a takeaway tag

I made a mistake while doing an overpass query... There are some fast food restaurants **without** a `takeaway` tag... Sorry for the inconveniences...

> Before implementation it must be cleared up whether / how this quest should be implemented at all

I think this quest would be useless, because the most fast food restaurant offer takeaway and I don't see any concrete use of this data...

**Comment by rugk** [comment]
This quest may now be possible to implement, because https://github.com/westnordost/StreetComplete/issues/558 (or, rather, https://github.com/westnordost/StreetComplete/pull/672) is resolved.

We now handle **indoor quests** by disabling them by default and allowing users to enable them in the settings.

(@westnordost reopen…?)

**Comment by westnordost** [comment]
I'm still not sure about this quest.

**Comment by westnordost** [comment]
Yeah, no...
