### ISSUE TITLE
New Quest: farm shops and food vending machines

### ISSUE THREAD

**Issue by stefangrotz** [westnordost/StreetComplete#1042]
### General
Affected tag(s) to be modified/added: 
* [shop=farm](https://wiki.openstreetmap.org/wiki/Tag:shop%3Dfarm)
* [amenity=vending_machine](https://wiki.openstreetmap.org/wiki/DE:Tag:amenity%3Dvending_machine)
** [vending=milk](https://wiki.openstreetmap.org/wiki/Tag:vending%3Dmilk)
** [vending=food](https://wiki.openstreetmap.org/wiki/Tag:vending%3Dfood)
* [name](https://wiki.openstreetmap.org/wiki/Key:opening_hours)
* [opening_hours](https://wiki.openstreetmap.org/wiki/Key:opening_hours)
* [addr](https://wiki.openstreetmap.org/wiki/Key:addr)
* [website](https://wiki.openstreetmap.org/wiki/Key:website)

### Checklist
Checklist for quest suggestions (see guidelines):
- [x] 🚧 To be added tag is established and has a useful purpose
- [x] 🤔 Any answer the user can give must have an equivalent tagging (Quest should not reappear to other users when solved by one)
- [x] 🐿️ Easily answerable by everyone from the outside but a survey is necessary 
- [x] 💤 Not an overwhelming percentage of elements have the same answer (No spam)
- [x] 🕓 Applies to a reasonable number of elements (Worth the effort)

### Ideas for implementation
Start with basic information and go into detail laiter

**Element selection:** 
```
[out:json][timeout:25];
  // gather results
  (
  // query part for: “vending=milk”
  node["vending"="milk"]({{bbox}});
  way["vending"="milk"]({{bbox}});
  relation["vending"="milk"]({{bbox}});
  // query part for: “shop=farm”
  node["shop"="farm"]({{bbox}});
  way["shop"="farm"]({{bbox}});
  relation["shop"="farm"]({{bbox}});
  // query part for: “vending=food”
  node["vending"="food"]({{bbox}});
  way["vending"="food"]({{bbox}});
  relation["vending"="food"]({{bbox}});
  );
  // print results
  out body;
  >;
  out skel qt;
```

**Metadata needed:** 

**Proposed GUI:** 
Proposal will be added later.

I will add aditional information on this issue later.

Disclaimer: I use all the tags above for my project that shows farm shops around my city:
https://codeforkarlsruhe.github.io/direktvermarkter/

Best wishes,
Stefan

**Comment by rugk** [comment]
"Affected tag(s) to be modified/added:" is for the tags you want to add/change when the quest is solved, _not_ the one where you specify what to select(as you specify that in "Element selection").
Also you did not say what your quest is actually supposed to ask, so I don't know at all what this quest is actually about.

**Comment by stefangrotz** [comment]
Hey,

> Also you did not say what your quest is actually supposed to ask, so I don't know at all what this quest is actually about.

You are right, I didn't think this trough enough.

> @stefangrotz did you really read the quest suggestion checklist? I doubt that there are many farm shops with an own vending machine

At least in my regions there a quite a few farms with milk and egg vending machines. When you look at this map from Karlsruhe, the blue markers are vending machines and the green ones are regular farm shops:
https://codeforkarlsruhe.github.io/direktvermarkter/

>For the name quest see #309; shop=farm is already included in the opening hours quest; for the website see #454; the addr:*=* tag should be set independent of whether this element is a shop or a house (BTW: there is even already a quest which asks for the house number and another quest for adding the street name is planned in #213

I get your point. Do you think that it would be better to have a seperate quest for vending machines in general and keep farm shops out of this? 

>Why not doing it directly if you open a new issue?

I don't have much time right now but I wanted to use the time I have to start working on this. I didn't expect you guys to react so quickly :) I thought I could finish writing this issue in the evening.

**Comment by ENT8R** [comment]
> I get your point. Do you think that it would be better to have a seperate quest for vending machines in general and keep farm shops out of this?

But I don't really get yours 😄... What should be the question which is asked to the user? And what should be set if the answer is yes and what if the answer is no?

**Comment by rugk** [comment]
Whatever the actual question asked is, it may be better when @stefangrotz thinks this over another time, maybe splits it into multiple quests and actually fills out the issue template. There is still so much confusion about what this should ask.

Also remember to [read-through the quest guidelines](https://github.com/westnordost/StreetComplete/wiki/Adding-new-Quests-to-StreetComplete). There, e.g.one important guideline is the atomic quest one:
> ⚛️ Atomic quests: Per quest, only one thing should need to be answered by the user.

So don't tag thousand things per quest, but one thing, and ask one question.

**Comment by stefangrotz** [comment]
You are right. I will start over in the evening :)

**Comment by danieldegroot2** [comment]
This issue has since been partially superseded by #3587.
