### ISSUE TITLE
Add review mode

### ISSUE THREAD

**Issue by PanderMusubi** [westnordost/StreetComplete#1043]
As StreetComplete evolves with better functionality and improved instructions, also users evolve as they learn more about how to tag what. When undo is not an option, because you have added a lot in the past that isn't optimal, at the moment you have to edit OSM in another way. For example, one would use the edit function on OSM on a laptop or desktop. What would be beneficial for OSM, is that StreetComplete offers a review mode for:
* only your own contributions
* all contributions (your own and that from others)
and perhaps be able to filter in only a certain kind of contribution for which you would like to do a review.

Implementing this would offer a good way of adding more quality assurance to StreetComplete.

**Comment by PanderMusubi** [comment]
Those created by SC. Created by OSM could be another option. So:
* changes from user:
    * only you
    * only others
    * all users
* changes contributed by:
    * only SC
    * only OSM
    * SC or OSM

**Comment by westnordost** [comment]
This feature request is far too vague, I have no idea what you actually envision here.

**Comment by westnordost** [comment]
Hmm, I think with the current tools, this is impossible. I.e. it is not trivial to find such recent changes in a given bbox.

Also, a second, smaller, problem is that the app is not able to translate the tagged tags back into human readable text. (I.e. "maxspeed:type=DE:zone30" to "It is a 30 zone")

**Comment by rugk** [comment]
Also AFAIK it would be hard to determine with what editor a change is made. So that filtering is not really possible.

**Comment by PanderMusubi** [comment]
Ah, it is not in the changeset that SC was the origin?

**Comment by ENT8R** [comment]
Actually the name of the editor is stored in every changeset (otherwise statistics like https://wiki.openstreetmap.org/wiki/Editor_usage_stats#Tables_and_figures would be impossible), but there is currently no possibility to get recent edits filtered by the used editor via the Overpass API (see also https://github.com/drolbr/Overpass-API/issues/189)
