### ISSUE TITLE
Version 5.1 is unusable and laggy on Nexus 5x

### ISSUE THREAD

**Issue by dbdean** [westnordost/StreetComplete#1047]
Since the new 5.1 update, the app has been unusable and very slow at doing anything on Nexus 5x. Android keeps coming up and asking me if I wan't to close StreetComplete as it is non responsive.

**Comment by deerwood** [comment]
I had the same issue ("StreetComplete reagiert nicht, Schließen oder Warten?") after installing the new 5.1 version. A reboot of my phone solved the problem.

**Comment by dbdean** [comment]
Mine has continued being laggy and slow through a reboot, as well as completely wiping the app storage. I don't have Android Studio running at the moment, but I have submitted some reports through the android reporting thing that might contain some details on where it is lagging.

**Comment by westnordost** [comment]
Oh yeah, I got quite a few ANR reports.

```
  #05  pc 0000000000043f74  /data/app/de.westnordost.streetcomplete-QZPCJrGp6mDZfd8FT12p1g==/oat/arm64/base.odex (Java_com_mapzen_tangram_MapController_nativeMarkerSetVisible__JJZ+116)
  at com.mapzen.tangram.MapController.nativeMarkerSetVisible (Native method)
- waiting to lock <0x0edf674d> (a com.mapzen.tangram.MapController) held by thread 15
  at com.mapzen.tangram.MapController.setMarkerVisible (MapController.java:1144)
  at com.mapzen.tangram.Marker.setVisible (Marker.java:185)
  at de.westnordost.streetcomplete.tangram.MapFragment.onRotationChanged (MapFragment.java:478)
  at de.westnordost.streetcomplete.tangram.CompassComponent.onRotationChanged (CompassComponent.java:138)
  at de.westnordost.streetcomplete.tangram.CompassComponent.onSensorChanged (CompassComponent.java:129)
  at android.hardware.SystemSensorManager$SensorEventQueue.dispatchSensorEvent (SystemSensorManager.java:846)
```

**Comment by westnordost** [comment]
(And thread 15 is the GL thread in this case)

Apparently, this occurs only on Android 8 (and perhaps Android 7).

**Comment by dbdean** [comment]
I'm Android 8.1, myself. It isn't laggy when I'm moving the map around inside, but gets laggy when I go outside and attempt the same thing, so it might have something to do with GPS.

**Comment by padan** [comment]
Experienced this lag too, with StreetComplete 5.1 on Android 5.1 and only with GPS enabled. Downgrading to StreetComplete 5.0 or upgrading to StreetComplete 6.0-beta1 provided by @westnordost works for me. Looking forward to an official update.

**Comment by westnordost** [comment]
Testing the fix, now on master, would be highly appreciated. (It is yet different from what I sent @padan)

**Comment by westnordost** [comment]
https://www.westnordost.de/misc/app-debug1.apk

**Comment by westnordost** [comment]
@padan tested it on his phone, looks good.

**Comment by dbdean** [comment]
Looks good for me to.
