### ISSUE TITLE
New Design

### ISSUE THREAD

**Issue by Yasujizr** [westnordost/StreetComplete#1049]
![streetcomplate](https://user-images.githubusercontent.com/36993664/39658651-4cb95234-5020-11e8-9cd8-150d01081258.jpg)

Hi @westnordost,

I have studied your work and I think a new design will make you more visible. I designed for you, I hope you like it and you want to use it. If you want to reach me, you can look at the my profile. I can give you all the formats of the design free. If you want a change please specify.

**Comment by ENT8R** [comment]
> will make you more visible

In what sense? Do you propose this to be the new app icon? To be honest, IMO the old icon is much more simpler and looks pretty good, so why do we need a new one?

**Comment by matkoniecz** [comment]
What is proposed in this issue?

**Comment by Yasujizr** [comment]
This issue suggests a new logo for you. I aimed to draw more attention among other applications. If you think you have not added anything to your previous logo, you can refuse.

**Comment by ENT8R** [comment]
Which other applications do you have in mind? AFAIK the icon StreetComplete uses is unique and not used by any other application...

**Comment by Yasujizr** [comment]
Apps in the same category as yours. If your logo is too simple, this program may show poor quality. Do not get it wrong, the program is very good but it is visually important in marketing.

**Comment by matkoniecz** [comment]
> Apps in the same category as yours.

For example?

> If your logo is too simple, this program may show poor quality

Fortunately, SC is not suffering from this problem.

**Comment by Yasujizr** [comment]
I see that as an outsider. If you like, you can do a survey so that the end user is a focused logo. I do not want to change your idea, it's just a suggestion. you can look at the applications in the same category as yours. You can even look at the results of "street complete".

**Comment by ENT8R** [comment]
> You can even look at the results of "street complete".

Well, Google Play shows only some racing games besides this app 😄:
<img src="https://user-images.githubusercontent.com/25306497/39662345-6d6c61b6-5060-11e8-815e-22fb9217ef65.PNG" width="500px">

And searching for [street complete](https://staging.f-droid.org/search?q=street+complete) on F-Droid results only in this app and OsmAnd...

Maybe we should just hear @westnordost's opinion on this?!

**Comment by Yasujizr** [comment]
I do not understand why you're so angry and prejudiced, it's just a suggestion.

Android Phone Search "Street Complete"
![screenshot_2018-05-05-13-42-33](https://user-images.githubusercontent.com/36993664/39662503-c5c2fd20-506a-11e8-91a4-8a5f0f4df252.jpg)

Category Search
![screenshot_2018-05-05-13-43-38](https://user-images.githubusercontent.com/36993664/39662510-f0e2abfe-506a-11e8-9f13-2da3b23e38bf.jpg)

**Comment by exploide** [comment]
While I'm a bit reluctant regarding the lettering with the yellow bar, I thing the logo looks really nice! However, I'm also not convinced that the current one needs to be replaced but that's for others to decide anyway. Just want to say thanks to @Yasujizr and compliment on the logo design.

But the actual reason I answer: Independent from this issue, maybe if @Yasujizr likes to support SC with his design skills, maybe it would be useful to have someone help out with all the icons needed for quests. IIRC the building type quest still needs a lot of well distinguishable icons for different building types. Just an idea..

**Comment by rugk** [comment]
That's a Google Play search? If yo, it likely is just some strange personalisation of Google to not show you the results.
Or, likely, it filters by country. (E.g. DuckDuckGo only shows the – English – wiki site of StreetComplete [as a top result](https://duckduckgo.com/?q=street+complete).

Also with a new icon, you cannot influence how Google sorts/searches stuff. It likely also considers the user count in a given country.

> IIRC the building type quest still needs a lot of well distinguishable icons for different building types

Yeah, good idea. See here for details: https://github.com/westnordost/StreetComplete/pull/774

**Comment by axre** [comment]
Thanks @Yasujizr for the design work done.

However i also dont understand why this icon is better than the actual one. Dont get me wrong - this is a good designed icon. But the current icon does "the job" well, and has fitting colors.

**Comment by Yasujizr** [comment]
Thank u all feedback, the previous logo was simple and I wanted to make improvements.

I will look at the details. you can close or delete this issue.

:)

**Comment by westnordost** [comment]
Hi @Yasujizr, thank you for your design! I kind of like this icon, it is inspiring.
But I prefer to keep the current icon, actually. Just in my personal not professional opinion, I think the icon is a bit much - an icon (street sign) within a circle within another icon. 

I have long been planning of some visual redesigning of the app, when I come around to finally realize it, I might come back to you there.

In the meantime, if you are interested in creating icons and such in the same style as the already available ones ([1](https://github.com/westnordost/StreetComplete/blob/master/res/sport_icons.svg), [2](https://github.com/westnordost/StreetComplete/blob/master/res/building_icons.svg)), you are invited to contribute there. I know at least for the building quest and the "what goes into this recycling container" quest, icons are needed.
(I should probably warn you though that I am very picky about icon design though :-/ )
