### ISSUE TITLE
Quest: Does this amenity=cafe|restaurant|fast_food offer delivery?

### ISSUE THREAD

**Issue by CloCkWeRX** [westnordost/StreetComplete#105]
Answers:
 * https://wiki.openstreetmap.org/wiki/Key:delivery (Yes/No)
 * Other: Add note

**Comment by westnordost** [comment]
Note sure, perhaps limited to fast_food. Otherwise there will be too many false positives.

**Comment by westnordost** [comment]
I'll rather close this because too many false positives.

**Comment by rory** [comment]
I'd like to suggest that this be re-opened and added.

I'm not sure what you mean be "too many false positives". There are only 2 answers (yes/no), and surely that's a simple question to answer?

**Comment by ENT8R** [comment]
Many false positives means here that there would be a lot of quests, but nearly all of them are answered with "no". So this quest would not fulfill the " No spam" requirement...

**Comment by rory** [comment]
[Taginfo](https://taginfo.openstreetmap.org/keys/?key=delivery#values) says that of the thing with this tag, it's about 50:50 yes versus no. Drilling down, there are about 50:50 delivery=yes/no for amenity=restaurant ([9.9K `amenity=restaurant,delivery=yes`(https://taginfo.openstreetmap.org/tags/delivery=yes#combinations) vs [11.7K] `amenity=restaurant,delivery=no`](https://taginfo.openstreetmap.org/tags/delivery=no#combinations). `amentity=fast_food` is similarly about evenly split. What makes you think the restaurants & fast_food in OSM without the delivery tag would be much different?

**Comment by rugk** [comment]
Sure it's 50:50 yes/no, but the vast majority of the shop, restaurant etc. likely do not have any `delivery` tag. This is what you need to compare and I encourage you to look it up on taginfo and e.g. compare the absolute numbers.
And all these, who do not have this tag likely offer no delivery.

Additionally this quest may require you to get inside the building, so even if it were to be included, it would have to be disabled.

**Comment by rory** [comment]
I don't suggest a quest for delivery for shops. Only restaurant & fast_food. I know a tiny percentage of amenity=restaurant/fast_food have that tag, that's why I suggest a quest for it! It's clearly something that's missing from OSM. **If** the objects with delivery tag set are representative of all in OSM without the tag, we can predict the final result to be 50:50. i.e. it wouldn't be a false positive. Am I making sense?

**Comment by rugk** [comment]
I understand your reasoning, okay, but I'd rather say it is more luck that it currently is split 50:50. Actually, I think most ("serious") restaurants (i.e. not fast food/ pizza or other "smaller" restaurants) do not offer any delivery.
And if they do, you explicitly have to ask them, i.e. it's not something they advertise anywhere.

As such, the quest is also hard to answer for many restaurants. You'd possible even have to ask the personal.

**Comment by rugk** [comment]
I understand your reasoning, okay, but I'd rather say it is more luck that it currently is split 50:50. Actually, I think most ("serious") restaurants (i.e. not fast food/ pizza or other "smaller" restaurants) do not offer any delivery.
And if they do, you explicitly have to ask them, i.e. it's not something they advertise anywhere.

As such, the quest is also hard to answer for many restaurants. You'd possible even have to ask the personal.
