### ISSUE TITLE
data privacy statement needs an update

### ISSUE THREAD

**Issue by RubenKelevra** [westnordost/StreetComplete#1051]
Since the Mapzen service was shut down (https://github.com/westnordost/StreetComplete/issues/747), we needed a new tile service, but the data privacy statement (German locale) still mention and link the Mapzen web service.

**Comment by ENT8R** [comment]
@westnordost wanted to change this later... See the comments on this comment: 25baa93d8cc1e4f71d9672ca60da07c442f366b0

**Comment by ENT8R** [comment]
The same was asked here: https://github.com/westnordost/StreetComplete/issues/747#issuecomment-366469410

**Comment by RubenKelevra** [comment]
Oh, well. Haven't seen those things. I was just trying to replicate the crash of the settings in my device and stumbled across this. :)

**Comment by rugk** [comment]
Yes, but good to a have a proper issue for that…

**Comment by Haikuch** [comment]
I am a bit unhappy about the choice of words in 

> No worries, the app keeps your location for itself.

This isn't really the truth, is it? As even explained later, ones location will be shared with the tile server, with the quest server and with Overpass Api. So you can't really tell its just kept on the app, even when the location is not used to track the user but its needed to get the proper data.

**Comment by westnordost** [comment]
@Haikuch 
1. there is no "quest server"
2. The location is not shared. You can look at the map anywhere and you can download quests anywhere, independent of your location. I think it should not come as a surprise to anyone that the app will need to tell the server at what location it wants to have the map and quests displayed.

Changing the choice of words will mark it fuzzy and thus make it necessary to translate the text in every language anew. So, I'd rather only change this if the new suggestion is a big improvement over the current text. So, what is your suggestion?

**Comment by Haikuch** [comment]
> there is no "quest server"

yes of course, my mistake :)

> I think it should not come as a surprise to anyone that the app will need to tell the server at what location it wants to have the map and quests displayed.

Of course, if someone starts thinking about how the process behind the app has to work, but most people do not, especially the non-techy ones. Actually, because SC is a survery app (as mentioned multiple times here), the mapview is more or less the location of the user. So, the users location is shared. 
I see that you do not want to make the choice of words fuzzy, but when the situation is just not as easy as given in the text it simply needs to be adjusted.

**Comment by rugk** [comment]
One needs to update the privacy policy anyway, as we use a new tile sever and stuff like that. This was actually the original reason to create this issue, but of course once you are at it, you can make many other changes too, so translators will only need to translate it once afterwards.

**Comment by rugk** [comment]
Uh… BTW, especially since today, you should really do that. :smile:

**Comment by Haikuch** [comment]
Well, well, I don't want to join the DSGVO panic :) This is certainly not appropriate, I see it more as a motivation to really think about these things and to be able to communicate them.

Anyway, I'm still pretty busy right now with exactly such DSGVO stuff, I'd like to formulate something for the app here as well. But I can't guarantee that this will happen within the next month... 

So if you feel it's urgent, please don't wait for me.

**Comment by rugk** [comment]
Well… not a panic, nobody would care about a FLOSS app very likely (or do you have enemies, @westnordost ? :wink: ), but I doubt StreetComplete can be perceived as for "friends and familly" (these are excluded from the regulation). Or we are all a big family here… :laughing:

**Comment by rugk** [comment]
@RubenKelevra Yet another issue you closed, that should not be closed…
