### ISSUE TITLE
renaming autosync ?

### ISSUE THREAD

**Issue by Haikuch** [westnordost/StreetComplete#1054]
In the settings one can activate Auto-Sync, is this the right description for the setting? Is there more than just auto-upload when activating this?

Anyway, I would love to have a more detailed description here for the users what it means to set this option.

**Comment by Haikuch** [comment]
ok I see, its more than just uploading the quest results. But is there any documentation or explanation like you have given here? How can users know, what the switches actually cause?

**Comment by rugk** [comment]
A place for that could be the FAQ, but I think that is "too far away". Better add a small helper text to the option or so, which explains that.

**Comment by RubenKelevra** [comment]
I think this option is pretty self-explanatory.

**Comment by RubenKelevra** [comment]
@matkoniecz well it also auto-sync notes and images attached to notes... so this would be wrong. 🤔

Maybe Auto-Sync with a comment in the second line small (map tiles are always fetched automatically)

**Comment by rugk** [comment]
So what is the decicion here, @westnordost?

**Comment by westnordost** [comment]
Leave it as is
