### ISSUE TITLE
Option to add pictures not only photos

### ISSUE THREAD

**Issue by Haikuch** [westnordost/StreetComplete#1056]
Currently there is the possibility to take photos and contribute them via a note. But it would make sense, to allow uploading any imagefiles, because one might have already taken photos earlier.

Moreover, I am interested if the metadata is removed from the pictures before uploading them? Just as a privacy concern.

**Comment by rugk** [comment]
> Moreover, I am interested if the metadata is removed from the pictures before uploading them?

As for the location that should hardly matter in our use case. And phone model well… mhh…

**Comment by westnordost** [comment]
As far as I remember, all metadata is stripped.

**Comment by matkoniecz** [comment]
> But it would make sense, to allow uploading any imagefiles, because one might have already taken photos earlier.

I am not convinced that it is worth complicating program. Especially as this is supposed to be used on survey, not as a remote editor.

**Comment by Haikuch** [comment]
> As far as I remember, all metadata is stripped.

I looked some photos up that I found with https://api.openstreetmap.org/api/0.6/notes/search?q=StreetComplete. There all metadata is stripped, that might also be done by the server, but I will try to check it in the code as well

**Comment by ENT8R** [comment]
> Especially as this is supposed to be used on survey, not as a remote editor.

I also think that adding the ability to attach pictures which were already taken some time ago does not make sense and in the worst case it lowers the trustworthiness of StreetComplete (and especially the attached photos)

> I looked some photos up that I found with https://api.openstreetmap.org/api/0.6/notes/search?q=StreetComplete.

Do you know that you can also easily view the notes on a map or as a list here:
https://ent8r.github.io/NotesReview/?query=StreetComplete&limit=100&start=true
https://ent8r.github.io/NotesReview/expert/?query=StreetComplete&limit=100&start=true

**Comment by westnordost** [comment]
I do share the same opinion.
