### ISSUE TITLE
Background of compass needle is flickering 

### ISSUE THREAD

**Issue by RubenKelevra** [westnordost/StreetComplete#1057]
When a dialogue is opend, which grey out the background, the compass needle's background is flickering as a rectangular.

Observed on a OnePlus 5T running Android Oreo (8.1) with SC 5.2

![](https://i.imgur.com/4XXxnrh.jpg) 

(I was not able to screenshot it, so I just marked the area for better understanding)

**Comment by rindlerblabla** [comment]
Duplicate of #1045 (closed)?

**Comment by matkoniecz** [comment]
no, as #1045 was closed as

> this is a problem of the Twilight Android app, not of StreetComplete

here no third-party apps are involved.

I also want to confirm that I am able to replicate this problem (I planned to send bug report but I had no time to do this)

**Comment by RubenKelevra** [comment]
I can confirm this bug also with "night-mode" off. Which is part of Oreo.

**Comment by westnordost** [comment]
A solution would be to redo this View as a normal View which is simply rotated around X,Y,Z axis, like any view can. Would also make it easier actually (less code). Don't know why I did not do it like this from the start.

**Comment by RubenKelevra** [comment]
A quick fix might be to just move the compass (the full circle) to the front. I doubt that someone would really mind, that it's not greyed out on dialogues.

**Comment by rugk** [comment]
> I doubt that someone would really mind, that it's not greyed out on dialogues.

Oh, no, many people would as that stands out very much! Actually "people" also minded about a special edge case, where this happened: https://github.com/westnordost/StreetComplete/issues/1045

**Comment by rugk** [comment]
@westnordost reopen
