### ISSUE TITLE
Add an option to disable automatic zooming completely

### ISSUE THREAD

**Issue by RubenKelevra** [westnordost/StreetComplete#1058]
Currently the map will be zoomed, when clicking on a quest and also when GPS tracking is activated. Both zoom way to much in and also trigger a refresh of tiles, which isn't really useful IMHO.

I would like to see a simple checkbox added, which just disable the automatic zooming, which would save some traffic.

**Comment by westnordost** [comment]
There will be no option for now.

I am not convinced by the reason you gave. There is no reason why someone who is not going to answer a quest would click on a quest. To answer a quest, it is necessary to show the quest geometry and the precise location. Not zooming in at all would make it easier for those black sheep who "game" the app and just answer one quest after another without actually verifying it on a survey.
