### ISSUE TITLE
Registration at 'iedereeneenwetenschapper'

### ISSUE THREAD

**Issue by PanderMusubi** [westnordost/StreetComplete#1060]
The website https://www.iedereenwetenschapper.be (_everybody a scientist_) aimed at Belgium and the Netherlands lists projects where citizens can participate in scientific research on all different levels. StreetComplete would be a good candidate to get listed there.

Google translate of the website's description is https://translate.google.com/translate?sl=nl&tl=en&js=y&prev=_t&hl=en&ie=UTF-8&u=https%3A%2F%2Fwww.iedereenwetenschapper.be%2Fover-ons&edit-text=&act=url

What is the opinion of the core maintainers of StreetComplete on this? Fill out an application?

**Comment by westnordost** [comment]
On first glance I do not see any connection. But I do also not care so much. If you think that StreetComplete should be on that list, it is up to you.
