### ISSUE TITLE
Change Language

### ISSUE THREAD

**Issue by Haikuch** [westnordost/StreetComplete#1064]
It looks like there is no option to choose another language that might be different to the system language settings, is there?

**Comment by westnordost** [comment]
Correct. And this will not be changed.

**Comment by Haikuch** [comment]
Sorry, why not?

**Comment by ENT8R** [comment]
AFAIK this is a bad behaviour of apps and a no-go if you follow the material design guidelines. Also, why would you need something like this? Can't you simply change your phone's language?

**Comment by Haikuch** [comment]
I don't see what problems could emerge from an option to change the language used in an app and why this would be a bad behavior? I can have specific demands for each app language settings, for example because translation is bad, because I want to have the english text for error messages to find more help, because i want to check translation, because some wordings are very special and there are not exact translations possible.

**Comment by matkoniecz** [comment]
> I don't see what problems could emerge from an option to change the language used in an app

It is necessary to implement it. AFAIK in Android it is quite obnoxious as apps are expected to use system language.
