### ISSUE TITLE
Quests disappear on App switch until the map is moved

### ISSUE THREAD

**Issue by RubenKelevra** [westnordost/StreetComplete#1065]
This bug is quite some time in SC (at least as long as I use it).

Happend to me on Android 7.X, 8.0 and now on 8.1.

I haven't seen an recent ticket mentioning this bug, so I created a new one.

https://youtu.be/HKR8pFWLB64

**Comment by westnordost** [comment]
Won't fix for now because I will not work on anything related to the map display.

I remember I have looked into it in the past but did not find anything, might be a problem with tangram-es.
