### ISSUE TITLE
tag source differently if user if far away from the quest

### ISSUE THREAD

**Issue by RubenKelevra** [westnordost/StreetComplete#1066]
Currently SC tags everything with source=survey. This might be true for most stuff people insert, but I tend to spot stuff and add them some minutes later as a batch via SC.

Since our brain is good but not perfect, we might want to change the behavior of SC to tag stuff edited from farer away with `source=memory` instead of survey.

This reflects the data quality better and helps to understand why there are sometimes things added wrongly while sometimes not, by other mappers.

**Comment by HolgerJeromin** [comment]
This is / was implemented like this:
https://github.com/westnordost/StreetComplete/blob/b2b5eafd2768d87c185a5ca4bf2a56aec874d52b/app/src/main/java/de/westnordost/streetcomplete/quests/FindQuestSourceComponent.java#L50
I am not sure if this is still the case.

**Comment by westnordost** [comment]
Still, I reckon there are people who answer quests that are further away from memory (=local knowledge) against the app's explicit instructions.
As I said, surveyed some minutes back still counts as survey, but not something that really comes from local knowledge.

I thought about this thoroughly and I rather not explicitly allow users to add something "from memory". Some reasons:
- Less quality / more errors. There will be people who take it as a free pass to i.e. add asphalt everywhere because they are 90% sure that this is correct. Too bad that the information value of the 10% (=not asphalt) is actually what matters
- Once answered from local knowledge, it cannot be answered again (from real survey). So, no way to correct the 10% later
- If users really decide to ignore the app's instructions because they feel super sure about it and add things from memory without verifying it on a survey, the warning dialog makes clear that they are acting on their own account there

Maybe I should implement a hard maximum distance to current location for allowing to answer quests at all. I did not do that yet because that means that users would need to have a GPS fix at all times.

**Comment by RubenKelevra** [comment]
Well, I was not thinking about a change in the actual UI or do restrictions on the ability to use SC. Just for quests which the app detects are farer away it's fair to change the source. Sure the actual source is the same: You did a survey, but you don't look at it and remembering sometimes lead to additional errors in the data.

When I look at a change done in my surrounding and I know it's wrong, it's better to understand that the user just remembered wrong instead of stating "I did a survey and it's different now". It would lead me to a survey of my own to check this and would add some frustration.

**Comment by westnordost** [comment]
This would mean that quests solved would need to be put automatically into a different changeset if more than X meters away from the user's position.
Problem:
- What is X?
- behavior quite intransparent to the user
- user may have no gps fix or location is (very) inaccurate

**Comment by RubenKelevra** [comment]
> What is X?

Well - we already do such a decision, we show the user a information about his distance from the Quest.

> behavior quite intransparent to the user

We can just extend the current hint on a quest (usually out of sight), to state that his change will be marked as "source=memory".

> user may have no gps fix or location is (very) inaccurate

On my phone, a position acquiring is usually way below 1 second ... is this really still a problem nowadays? If so we could simply tag everything with source=survey until the position is 3D fixed by the GPS chip and just decide in such cases for source=memory or source=survey.

Just one sidenote: source=local_knowledge sounds wrong in such cases, this would require a long time knowledge of a topic, which we cannot assume with a simple solve of a topic out of sight.

**Comment by rugk** [comment]
> to state that his change will be marked as "source=memory".

Actually I don't think the average user cares how that stuff will be tagged. Usually they don't even know what "tagging" is or what that means or maybe how OSM works in general… At least we should not assume that, so IMHO this is useless – or even confusing – information.

> On my phone, a position acquiring is usually way below 1 second

Also for battery usage reasons users may decide to just disable GPS…

**Comment by RubenKelevra** [comment]
> Also for battery usage reasons users may decide to just disable GPS…

Also, SC already detect this. In such cases it's possible to still tag them with survey (assume that the user uses this app with it's intended usecase).

So my proposal would just change the tagging in cases where the app currently show the warning about a large distance. We can show a pretty easy to understand message, extending the current one, like "If you choose to upload this anyway, your information will be marked to reflect that you editing from a distance." or something like that. :)

**Comment by westnordost** [comment]
Doing that would mean to soften up that the app always requires the user to verify any question answered. See https://github.com/westnordost/StreetComplete/issues/1066#issuecomment-388613579 for my answer to that.

Anyhow, I realized there is a solution for setting this "hard limit" I mentioned: If the GPS is off, assume the rough location of the user to where he answered the (first) quest in this session.

**Comment by RubenKelevra** [comment]
> Anyhow, I realized there is a solution for setting this "hard limit" I mentioned: If the GPS is off, assume the rough location of the user to where he answered the (first) quest in this session.

This doesn't work for users which use this app while in motion... which should be the default usage scenario.

I don't feel like we should implement a hard limit at all, that's an unnessary limitation.

For example, I often take snapshots while driving/riding a bike with mapillary, upload them and later look for details in those pictures while mapping stuff with SC on the next stop. Sure, this isn't the default usecase but you completly block such use cases when you choose to implement a hard limit for distance from the quests.

**Comment by rugk** [comment]
@westnordost reopen

**Comment by NotSoImportant** [comment]
Hi @westnordost: maybe not the best location to discuss, but I strongly disagree with "ensure that users actually comply to not solving quests at other locations at where they are".

Why?
A lot of information can be easily correctly remembered or looked up via different sources (web search, Mapillary, ....)
I think it is more about "I am aware of the consequences of my changes and will act accordingly careful".

I think you should not forbid people to add the things they really know,
but warn them from adding things they are unsure about.

Examples:
- Name of shops, restaurants, doctors, ... can easily be known / remembered / looked up
- If a parking is private or public and has fee can (if known) easily be remembered
- One-way streets can typically be remembered
- Construction finished can typically be remembered
- Existance of a sidewalk / cycle path can sometimes be remembered
- Speed limits can sometimes be remembered (but most likely not the exact point where they change)

Finally: I agree that tagging everything uploaded with "source=survey" is not correct always and should be improved.

Yes, there is the risk of answering something wrong
    - but so is also when editing via iD, JOSM, ...
    - but (lower) chances are also that users do errors while (or short after) surveying

**Comment by HolgerJeromin** [comment]
> I think you should not forbid people to add the things they really know,
> but warn them from adding things they are unsure about.

This is exactly the behavior the app has (since at least a few years).
