### ISSUE TITLE
Feature request: Additional buttons on maxspeed-quest

### ISSUE THREAD

**Issue by RubenKelevra** [westnordost/StreetComplete#1068]
Answering the maxspeed quest with 'rural' or 'urban' feels unnecessarily hard, 4 clicks in comparison to 1 click + ok for a maxspeed=30 zone.

![screenshot_20180513-170506](https://user-images.githubusercontent.com/614929/39968597-f2daf126-56cf-11e8-8024-3c9fe1f3c75d.jpg)

There is plenty of room left and right for additional icons and if a "newbie might answer it wrong" is a concern: I think newbies might answer it wrong without such additional icons. They might answer it with 50 kph manually added instead of clicking thru all this menus.

But I think it would be a good idea to show the current warning for "check for a sign" the first 20 or so times a user click on one of the new buttons.

For Germany there are already established pictograms to show this, I think they might be universal understandable:

https://de.m.wikipedia.org/wiki/Zul%C3%A4ssige_H%C3%B6chstgeschwindigkeit_im_Stra%C3%9Fenverkehr_%28Deutschland%29?wprov=sfla1

**Comment by westnordost** [comment]
What exactly is your suggestion?

**Comment by RubenKelevra** [comment]
@westnordost maybe something like this? I'm not good at designing icons, but to give you a visual idea what I propose, I did it anyway.

![39968597-f2daf126-56cf-11e8-8024-3c9fe1f3c75d](https://user-images.githubusercontent.com/614929/40519334-469aad40-5fbf-11e8-8f65-18bbc91cc866.jpg)

**Comment by rugk** [comment]
@westnordost reopen
