### ISSUE TITLE
Accessibility quest for restaurants etc could be on by default

### ISSUE THREAD

**Issue by jancborchardt** [westnordost/StreetComplete#1073]
Currently the wheelchair accessibility quest for places like cafés, restaurants etc is not active by default.

But just like opening times and similar, the accessibility of a place is often very easily visible from outside on the street as you can see the entrance and most often also the entire venue. It would really help accessibility mapping to make it a default quest. :)

**Comment by rugk** [comment]
And interiors are exactly where? Yes, _inside_ of the building… :wink: 

But seriously there is more than that for shops, because steps can of course also be inside of it. If so, one needs to check for elevators or stuff like that…

**Comment by westnordost** [comment]
See @rugk

**Comment by jancborchardt** [comment]
Ok, good points. :)
