### ISSUE TITLE
Improve opening hours control (similar to maps.me UI) to support 'multiple' different opening hours

### ISSUE THREAD

**Issue by CloCkWeRX** [westnordost/StreetComplete#108]
Unfortunately the current UI makes a simple assumption of "All of the days selected are open for these hours"; which isn't the case in a lot of businesses.

maps.me gets this a bit more right (still can't handle restaurants open for lunch; closed; then reopen for dinner) by defaulting to 'all of these days are open all of these hours'; and lets you then add additional hours for specific days.

Probably a lot of effort; so a short term fix may be including an answer of:
 * "Multiple opening hours" -> Add note

**Comment by westnordost** [comment]
Did you try to add i.e.
Mo-Fr 8:00-12:00 and then
Mo-Fr 14:00-18:00?

StreetComplete will then add
opening_hours=Mo-Fr 8:00-12:00,14:00-18:00

Am 6. April 2017 06:05:36 MESZ schrieb CloCkWeRX <notifications@github.com>:
>Unfortunately the current UI makes a simple assumption of "All of the
>days selected are open for these hours"; which isn't the case in a lot
>of businesses.
>
>maps.me gets this a bit more right (still can't handle restaurants open
>for lunch; closed; then reopen for dinner) by defaulting to 'all of
>these days are open all of these hours'; and lets you then add
>additional hours for specific days.
>
>Probably a lot of effort; so a short term fix may be including an
>answer of:
> * "Multiple opening hours" -> Add note
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/westnordost/StreetComplete/issues/108

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by penpendede** [comment]
I first entered 

> Mo-Sa 08:00-13:00

and then

> Mo-Fr 14:00-18:30

and got

> Mo-Sa 08:00-13:00; Mo-Fr 14:00-18:30

Is that the way it is supposed to be? Wouldn't one rather this?

> Mo-Fr 08:00-13:00, 14:00 - 18:30; Sa 14:00-18:30

This is the result after entering said opening hours for node 3363052691, see http://www.openstreetmap.org/node/3363052691

**Comment by westnordost** [comment]
@penpendede: Depends on how you enter it. You can enter it either way and both are semantically correct.

Am 6. April 2017 10:21:46 MESZ schrieb penpendede <notifications@github.com>:
>I first entered 
>
>> Mo-Sa 08:00-13:00
>
>and then
>
>> Mo-Fr 14:00-18:30
>
>and got
>
>> Mo-Sa 08:00-13:00; Mo-Fr 14:00-18:30
>
>Is that the way it is supposed to be? Wouldn't one rather this?
>
>> Mo-Fr 08:00-13:00, 14:00 - 18:30; Sa 14:00-18:30
>
>This is the result after entering said opening hours for node
>3363052691, see http://www.openstreetmap.org/node/3363052691
>
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/westnordost/StreetComplete/issues/108#issuecomment-292103355

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by westnordost** [comment]
So, everything cleared up, right?

**Comment by Sora1248** [comment]
I just ran into the same problem and as far as I understand a semicolon will override any previous definition for the given days while a comma will append them.

In this [changeset](http://osmhv.openstreetmap.de/changeset.jsp?id=48454487) StreetComplete created `opening_hours=Mo-Fr 08:30-12:30; Mo,Th 14:00-18:00; Tu,We,Fr 14:00-16:30`. This will look like [this](http://openingh.openstreetmap.de/evaluation_tool/?EXP=Mo-Fr%2008%3A30-12%3A30%3B%20Mo%2CTh%2014%3A00-18%3A00%3B%20Tu%2CWe%2CFr%2014%3A00-16%3A30&lat=48.7769&lon=9.1844&mode=0&DATE=1494093480000) (notice the missing 08:30-12:30 timespan).
One correct way would be `opening_hours=Mo-Fr 08:30-12:30, Mo,Th 14:00-18:00, Tu,We,Fr 14:00-16:30` which looks like [this](http://openingh.openstreetmap.de/evaluation_tool/?EXP=Mo-Fr%2008%3A30-12%3A30%2C%20Mo%2CTh%2014%3A00-18%3A00%2C%20Tu%2CWe%2CFr%2014%3A00-16%3A30&lat=48.7769&lon=9.1844&mode=0&DATE=1494093480000). Now it includes the 08:30-12:30 timespan.

I made a little test after finding this with some made up times:
![screenshot_2017-05-06-19-40-42](https://cloud.githubusercontent.com/assets/19750809/25774811/214f15d6-3297-11e7-9335-ae38f5b69e13.png)

[Version 3 of this way](http://www.openstreetmap.org/way/210685100/history) contains the resulting opening_hours-tag. (Version 4 reverts the changes right away).
The Tu-Th times are grouped correctly and the Mo-Fr time overrides everything at the end.

So either there is a bug when handling the opening hours or the UI is missleading.

**Comment by westnordost** [comment]
Hmm! It looks like I misunderstood a a detail how opening hours are defined! This'd be bad.

Please create a seperate bug out of it and I will flag it as high priority. This warrants a patch release.

**Comment by westnordost** [comment]
Ah whatever, I'll just reopen this bug, it is related

**Comment by westnordost** [comment]
It looks like this can be solved by just concatenating the rules with "," instead of ";" because all rules specified in the UI are meant to be additive.

**Comment by westnordost** [comment]
I am not usually this quick with fixing and releasing a new version, but this concerns the validity of data inserted into the OSM DB, so it has the critical priority.

**Comment by Sora1248** [comment]
Thanks for solving it right away! :+1: 
I'll have a look at it when it pops up on F-Droid.

**Comment by ax3l** [comment]
@westnordost I just got a remark to my newly added opening hours in changeset
  https://www.openstreetmap.org/changeset/48702644
on a supermarket
  https://www.openstreetmap.org/node/420205285/history

Are you sure the format in 0.10 is correct and the recommended way to add them?

**Comment by westnordost** [comment]
luschi already answered on the changeset: Both are correct. Which format is "simpler" is a matter of taste.

I usually write down opening hours the way it is mentioned on the opening hours plate.

**Comment by ax3l** [comment]
ok, that's also my understanding.

I still don't get why people get so obsessed with formatting the opening hours beyond semantic correctness. First sentence in all OSM manuals is **OSM is a database** and "do not optimize for a renderer". That also means to me that short and on the point data sets are preferred over longer formats. Dates and opening hours should not be printed out raw as in the DB anyway and are queried instead of printed in many ways how one would work with them ("open right now"; "open on date X and time t", etc.).

**Comment by westnordost** [comment]
Germans

**Comment by ax3l** [comment]
Haha, we all three are.

> I usually write down opening hours the way it is mentioned on the opening hours plate.

Which still would result in
`Mo-Fr 07:30-12:00, Mo-Fr 15:30-19:00, Sa 07:30-12:00`
instead of
`Mo-Fr 07:30-12:00; 15:30-19:00, Sa 07:30-12:00`

;)
