### ISSUE TITLE
Node was displaced, while answering "lit"-task

### ISSUE THREAD

**Issue by TheRadialActive** [westnordost/StreetComplete#1083]
1. Walking through the streets, answering a lot of quests (in the end about 200).
2. Submitting those via Wifi.
3. Later, people comment [the changelog](https://osmcha.mapbox.com/changesets/59299562), that something went wrong with the [node](https://www.openstreetmap.org/node/1018751122 ) (it was displaced kilometers by StreetComplete).
4. Somebody fixed the mistake, but the mystery how the node could have been displaced, stays.

- Has anybody else seen this kind of behavior?
- Is it a bug or mistake by the user?
- Which information would help to evaluate the problem?

**Comment by westnordost** [comment]
The node was displaced not in your changeset but by someone else via JOSM after that
