### ISSUE TITLE
Maxspeed quest : Ensure contributors choose between implicit and explicit maxspeeds before submitting

### ISSUE THREAD

**Issue by gileri** [westnordost/StreetComplete#1085]
With the current wording/UI many quest answers are incorrect in France, as often maxspeed is implicit and do not require maxspeed signs. However, as the UI is biased towards sign-based speed limits, both new and seasoned users are using the default choice without checking the "other options".

At least half of [those ways](http://overpass-turbo.eu/s/z70) shouldn't have maxspeed_type=sign, as 50 kph/kmh is the default speed limit in urban areas, so those ways don't have a sign.

I believe displaying both implicit and explicit maxspeeds choices equally would reduce errors, while not impeding input. Here is an UI mockup:
![fk00tf5](https://user-images.githubusercontent.com/4661658/40626063-881ba3a6-62b6-11e8-86ce-2f5e843235de.png)
![qwie9ae](https://user-images.githubusercontent.com/4661658/40626064-88448d52-62b6-11e8-92cf-3295e70c33d9.png)
![n2crgip](https://user-images.githubusercontent.com/4661658/40626066-886c6f84-62b6-11e8-98a9-c11f990028fa.png)
![k5ypvop](https://user-images.githubusercontent.com/4661658/40626067-8895c898-62b6-11e8-8208-fca047fa2077.png)

**Comment by westnordost** [comment]
I took the liberty of adding them here on github.

The mockup as such looks good, only for implicit speed limits it is not that easy and IMO needs more explanation - in other words, in the "worst" case, the UI flow after having selected "implicit speed limit" would stay the same.

What are the opinions of the other regulars here?

**Comment by matkoniecz** [comment]
Looks OK, though normal person may be surprised by "implicit speed limit" term (and maybe also by "living street"), but I see no way to avoid it.

**Comment by gileri** [comment]
I agree that "implicit" could be more explicit :) When showing the urban/extra-urban choice the user should understand, but as @matkoniecz there could be better way to express that.

Living street (translated) + the sign sound easy enough to understand imo.

**Comment by westnordost** [comment]
(If someone else wouldn't do this, this will probably not find its way into v6)

**Comment by westnordost** [comment]
Put some more thought into this (and started it on a private branch). A few comments:
- To not litter the main view with uncommon answers, the other items in the "Other answers..." menu should not be added. Specifically, not _"living street"_ and not "advisory speed limit". Also because it is not a direct answer to the question what defines this speed limit
- The dialog flow of when selecting "no sign, defaults apply" should stay the same and not be simplified to as it can be seen in the illustration as long as we do not have the big picture of what `maxspeed:type`s there are in total for each country (see [default speed limits](https://wiki.openstreetmap.org/wiki/Default_speed_limits)). When the linked list is ~complete, one can think about redesigning/simplifying this flow to something similar than proposed, offering different options for each different country. Because I find it necessary to see the big picture for a comprehensive tagging scheme here, I am putting this on blocked and on help wanted.

**Comment by gileri** [comment]
What got us here is that if users are given a default, easy answer they will most likely ignore other answers (and they do). Making the user choose between 4 options slows down maybe the first one or two contributions, but will make sure that they makes a conscious decision between them, and not just doing as little as possible to validate the quest with incorrect data. [Another example](http://overpass-turbo.eu/s/zXN)

I've also started a private branch but I'm not used to Android development, so I didn't want to give any false hope by annoucing it. But since the issue is blocked on an external and open-ended task that will likely never be considered as complete, I will stop devoting time for it, except if we find another solution that is implementable in the near future.

Should the quest be disabled for the time being ?

As an aside : a road being designed as a "living street" [does define a legal speed limit in a lot of coutries.](https://wiki.openstreetmap.org/wiki/Tag:highway%3Dliving_street#National_specialities)

**Comment by rugk** [comment]
> As an aside : a road being designed as a "living street" does define a legal speed limit in a lot of coutries.

That's why we have an option to select that.

So what is actually blocking this issue?

**Comment by StanislavTichy** [comment]
I second to thr fact that while using streetcomplete for first time I have automatically filled 50kmh speed limit onto every urban road i came across only after some time i noticed there are other options to choose from. As a result of my experience As a translator I have rephrased the string in poeditor to be more precise about sign. In my czech language I have currently worded main quest question appearing after clicking on icon as something like that:
"Is there a speed limit sign at this street? If yes, what is the speed written?"

This sounds very clearly i think.
