### ISSUE TITLE
note is not blocking quest generation

### ISSUE THREAD

**Issue by matkoniecz** [westnordost/StreetComplete#1089]
https://www.openstreetmap.org/way/230183858#map=19/50.07652/19.89367 generates housenumber quest despite that https://www.openstreetmap.org/note/997033#map=19/50.07652/19.89367&layers=N exists 

tested on master with default settings

That note was generated by an old SC version

**Comment by westnordost** [comment]
Shouldn't there be this "Cannot answer XYZ" string?

**Comment by matkoniecz** [comment]
This note was generated by a very old version - probably 1 year ago, by StreetComplete 0.10 - as https://www.openstreetmap.org/changeset/48700556#map=17/50.07694/19.88955 was applied to https://www.openstreetmap.org/way/230183858#map=19/50.07652/19.89367

From what I remember "Unable to answer..." was added later.

And anyway, from what I remember any note is supposed to block quest generation (maybe I misremember or misinterpreted something).
