### ISSUE TITLE
Displaying of quests in English, though having Ukrainian translation

### ISSUE THREAD

**Issue by nikita-nikiforov** [westnordost/StreetComplete#1090]
In Ukrainian interface, some last quests (about postbox' time and completion of objects) are displayed in English, though having translation on POEditor.

![](https://farm2.staticflickr.com/1729/40628125620_dfd1f21847_z_d.jpg)

**Comment by westnordost** [comment]
It's in POEditor, but not in the app yet. It will be in the next update.

**Comment by nikita-nikiforov** [comment]
Oh, sorry. Very dull notice  :shit:
