### ISSUE TITLE
(housenumber) quests not displayed

### ISSUE THREAD

**Issue by davidak** [westnordost/StreetComplete#1094]
existing housenumbers and quests are not displayed. i noticed at different locations.

example: https://www.openstreetmap.org/?mlat=52.27572&mlon=8.01589#map=18/52.27572/8.01589

OSM has some housenumbers, but not for every house

![screenshot from 2018-06-01 06-01-12](https://user-images.githubusercontent.com/91113/40820504-3974890e-6561-11e8-8496-ba07bed1c578.png)

i would expect quests for the houses without housenumbers, but they are not displayed. the existing housenumbers are also not displayed...

![screenshot_20180529-184836](https://user-images.githubusercontent.com/91113/40820534-6ca3cb5a-6561-11e8-855a-b48ad2f7a84a.png)

Version 5.2
on Andoid 6.0.1

**Comment by ENT8R** [comment]
The house numbers should be displayed on the map if they were added some months ago.
And how often did you press the button with "Download quests for this area"? And what priority does the house number quest have if you go into the settings?

**Comment by davidak** [comment]
>And how often did you press the button with "Download quests for this area"?

At least 2 times ;)

>And what priority does the house number quest have if you go into the settings?

default, 3rd position

**Comment by matkoniecz** [comment]
housenumbers quests are not generate for building=yes like https://www.openstreetmap.org/way/231905020#map=19/52.27586/8.01591

There is work in progress to add quest that allows to specify building type - see #1092 that will fix #25

I would classify this issue as duplicate of #25 unless there are buildings with specified building type that typically has housenumber, without housenumber and without generated quest.

**Comment by matkoniecz** [comment]
>  the existing housenumbers are also not displayed...

This issue is tracked as #1011

**Comment by davidak** [comment]
@matkoniecz thank you!
So i close this as duplicate and follow the other issues. Will create a new one if there are still issues.
