### ISSUE TITLE
Feature: select multiple markers for semi-batch input

### ISSUE THREAD

**Issue by gsurrel** [westnordost/StreetComplete#110]
When streets are cut in many small pieces or a suburb has many clones houses, the input is always the same. It would be nice to tap a 1st marker and the app displays all the nearby markers for the same kind which can be added to the current selection.

Then, the tagging occurs the same way as currently: tap to tag and save.

**Comment by westnordost** [comment]
Duplicate of #73 (reason for closing see there)
