### ISSUE TITLE
Move "Map cache size" to advanced at the end of the list

### ISSUE THREAD

**Issue by matkoniecz** [westnordost/StreetComplete#1104]
There is no good reason to reduce it and increasing it also is useful only in extreme situations.

partially inspired by https://github.com/westnordost/StreetComplete/issues/1091#issuecomment-395599597

> Oh, and the “Quest selection” menu should be at the top of the “Settings” screen, not hidden behind the scary-sounding “Advanced” section. I discovered its existence only thanks to @matkoniecz telling me it existed on a Vespucci issue, as I usually don't look in the “Advanced” portion of the config until having gotten used to an application, and StreetComplete never went past “getting used to it”, as I felt like it was useless due to the kind of quests proposed.

**Comment by westnordost** [comment]
Hm, I wouldn't want to put too much thought in grouping the options now as there are so few, perhaps later when they grow to be more.
