### ISSUE TITLE
New Quest: Dedicated disabled parking spaces

### ISSUE THREAD

**Issue by gorgobacka** [westnordost/StreetComplete#1106]
### General
Affected tag(s) to be modified/added: [amenity=parking + capacity:disabled=](https://wiki.openstreetmap.org/wiki/Key:amenity=disabled)
Question asked: **Does this parking area has dedicated disabled parking spaces?**

### Checklist
Checklist for quest suggestions (see guidelines):
- [X] 🚧 To be added tag is established and has a useful purpose
- [X] 🤔 Any answer the user can give must have an equivalent tagging (Quest should not reappear to other users when solved by one)
- [X] 🐿️ Easily answerable by everyone from the outside but a survey is necessary 
- [X] 💤 Not an overwhelming percentage of elements have the same answer (No spam)
- [X] 🕓 Applies to a reasonable number of elements (Worth the effort)

### Ideas for implementation
**Element selection:** 
1.  Search for 'amenity=parking' without 'capacity:disabled' -> Possible answers: yes, no, or a number.
1.  Search for 'amenity=parking' with 'capacity:disabled=yes' -> Possible answers: a number.

**Proposed GUI:**
Something small GUI similar to the backrest question for benches.
Possible answers: yes, no, or a number.

The same quest could be adapted for 'capacity:women' or 'capacity:parent'. But I think 'capacity:disabled' is more important.

**Comment by westnordost** [comment]
Aren't parking lots (of shops etc) required by law to have one lot reserved for disabled persons? If it can be assumed that there will always be one, disabled persons driving cars don't need to consult an (openstreet)map to find places where they can park close to the entrance.

**Comment by gorgobacka** [comment]
> Aren't parking lots (of shops etc) required by law to have one lot reserved for disabled persons?

I haven't thought about that. I searched a bit in the internet, but couldn't find a clear evidence.

But parking lots are not always connected to shops. I got the idea, when I was in the city center this weekend. And many dedicated disabled parking spaces seem not related to a special shop.

**Comment by westnordost** [comment]
My point is that disabled persons might (in some countries) not have the need to search (on a map) for a dedicated parking lot at their destination. And in other countries where disabled-parkings are unusual, it makes no sense to ask surveyors for this information because they will always answer "no, nothing".

**Comment by rugk** [comment]
Actually I have never heard/have a source for the claim that "required by law to have one lot reserved for disabled persons" (as for Germany, at least). I also guess it depends on the size of the parking space in general.
So does anyone have a source for that?

**Comment by NonnEmilia** [comment]
In Italy we have an act ([DM 236/1989](http://www.gazzettaufficiale.it/eli/id/1989/06/23/089G0298/sg)) ruling on free lot reserved for disabled persons in a parking each 50 standard lots (Art. 8.2.3). It applies to every residential building, public or private.

I.e: 30 lots = 1 for disabled + 29 for others; 80 lots = 2 for disabled, 78 for others.

Lots reserved for disabled persons are very commons in parkings.

**Comment by matkoniecz** [comment]
Is there any region where disabled parking spaces are at the same time reasonably popular and not present nearly elsewhere?

In Poland it seems that new legislation got passed or someone started to enforce it as huge number of parking spaces for disabled appeared and at least here such quest would be pointless.

**Comment by rugk** [comment]
So I looked up the situation in Germany:
* from my knowledge they are pretty common here
* neither the German Wikipedia article nor any other source I could quickly find mentions any obligation for such parking spaces. There is only one gutefrage question](https://www.gutefrage.net/frage/behindertenparkplatz-pflicht) that mentions the commune could make an obligation in some way or another, but generally no one is required to have such parking spaces

Thus, as for Germany, I would support this quest.

**Comment by matkoniecz** [comment]
https://www.eversheds-sutherland.com/global/en/what/articles/index.page?ArticleID=en/Discrimination_and_equal_pay/DLR_disabled_parking_230812 discusses minimal number of parkings for disabled in UK.

**Comment by westnordost** [comment]
gutefrage is a shitty source. Anyway, at the moment I see no reason to further pursue this quest.

**Comment by rugk** [comment]
> gutefrage is a shitty source.

Oh, sure, but as for Germany, I would need a proof for the reverse: That parking spaces are required. And I could find nothing about this, so I assume this is not the case, as anyone would have to write about that. Also I think I've seen many parking spaces with or without such places. As such, for Germany, this quest is totally suitable.

**Comment by ViolaineDo** [comment]
In France there is some law to reglement that but it is not rare that it is not applied (or badly applied)..And sometime  there is a room dedicated for disabled person but this one is not wheelchair accessible. I think it makes sense to map this.
