### ISSUE TITLE
New Quest: Steps

### ISSUE THREAD

**Issue by mahdi1234** [westnordost/StreetComplete#1107]
Hi,

I think it would make sense to add a quest for steps asking about

- stroller/bicycle ramp (ramp:*)

and the fun one

- amount of steps (step_count)

**Comment by ENT8R** [comment]
And also: please fill out the issue template for proposing a new quest if you are proposing a new quest... (even though this is obviously not necessary here anymore)

**Comment by mahdi1234** [comment]
Ok, sorry guys I have misread "If you are not suggesting a new quest, ignore this issue template" part thought not to fill it ... and seems I need search better for "staircase" and "step" not only "steps". Lesson learned. Cheers.

**Comment by matkoniecz** [comment]
@mahdi1234 No problem - it is good that you tried searching (and now it will be easier for others to find that it was proposed already).

You should see "close" button below, you may use it to close this issue.
