### ISSUE TITLE
consider adding language-specific screenshots in Google Play

### ISSUE THREAD

**Issue by matkoniecz** [westnordost/StreetComplete#1108]
https://android-developers.googleblog.com/2013/03/now-is-time-to-switch-to-new-google.html

> store listings in more languages with language-specific graphics

I am not sure is it fixable by a PR but I can at least provide graphics for Polish (as I can check whatever there are some embarrassing mistakes in a translation).

**Comment by westnordost** [comment]
Imo, it is too much work. Design may change every now and then, I neither want to have loads of outdated screenshots nor have this kind of work.

**Comment by rugk** [comment]
Is not there some way to, at least, partially automate that? But I guess that would be hard. Getting a screenshot from the mobile to the desktop is likely easy, but apart from that you need to the ui and language.

Or you could give thus task to translators, but I have never seen a translation service allowing you to "translate"/upload screenshots.

**Comment by ENT8R** [comment]
I don't know exactly but can this be done with [Fastlane](https://fastlane.tools)? It says something with "automated localized screenshots" on its website...

**Comment by westnordost** [comment]
Theoretically yes, but practically not really in the case of StreetComplete.
