### ISSUE TITLE
Small bug. Asks for path surface for cycleways as well

### ISSUE THREAD

**Issue by rindlerblabla** [westnordost/StreetComplete#1111]
For the surface quest highway=cycleway should lead to the question "What surface does the cycleway here have?" But instead the app asks "What surface does this path have here?"

The path question is asked for e.g this one https://www.openstreetmap.org/way/255611820

**Comment by westnordost** [comment]
It is not a bug. Isn't a cycleway also a type of path?

**Comment by rindlerblabla** [comment]
Hehe, sure, in English at least. Just thought it was a bug since the cycleway question was translatable in poeditor.
