### ISSUE TITLE
Quest suggestion - Access to playgrounds

### ISSUE THREAD

**Issue by rindlerblabla** [westnordost/StreetComplete#1114]
### General
Affected tag(s) to be modified/added: [](https://wiki.openstreetmap.org/wiki/Tag:leisure%3Dplayground)
Question asked: **Is this playground private or public??**

### Checklist
Checklist for quest suggestions (see guidelines):
- [x] 🚧 To be added tag is established and has a useful purpose
- [x] 🤔 Any answer the user can give must have an equivalent tagging (Quest should not reappear to other users when solved by one)
- [x] 🐿️ Easily answerable by everyone from the outside but a survey is necessary 
- [x] 💤 Not an overwhelming percentage of elements have the same answer (No spam)
- [x] 🕓 Applies to a reasonable number of elements (Worth the effort)

There are 455 486 objects (https://taginfo.openstreetmap.org/tags/leisure=playground) 2.96% have an access tag. At least in my area there are quite a lot of private playgrounds (mostly belonging to kindergartens) without proper access tag and when filtering out playgrounds in ie Osmand shows them as well.

Values yes, private or permissive (?) should be added to the access tag.

**Comment by ENT8R** [comment]
> Not an overwhelming percentage of elements have the same answer (No spam)

I know a village with a kindergarten which also has a playground (`access=private`). But also in the same village there are 3 other playgrounds which are accessible to the public. Just in this small village the ratio would be 3:1 and I think that in bigger cities this ratio could be even 8:1... So is this then really no spam anymore?

**Comment by rindlerblabla** [comment]
Hm. Maybe it's different in different areas. The same applies to the parking access quest, which is already accepted, where I live...

**Comment by rindlerblabla** [comment]
Another comment could also be if it's better to have a general access quest, similar to the purposed general fee quest #873, with other amenities/nodes/areas as well. If it is consider "no spam".

**Comment by matkoniecz** [comment]
My city has relative well mapped playgrounds and well mapped access on ones that are mapped.

Out of 478 playgrounds 24 have access that is restricted ( http://overpass-turbo.eu/s/zWb http://overpass-turbo.eu/s/zWd ).

**Comment by matkoniecz** [comment]
It is trivial to implement but I have doubts - how many private playgrounds are not marked as private? I expect that it will be end as "lets add access=yes to 99% of playgrounds that currently have no access tags".

**Comment by rindlerblabla** [comment]
Hard to say. Obviously we have different experiences from different cities(/countries). Probably it depends on how well mapped the area is. When I have a look on the playgrounds in my city through an overpass turbo probably around 10-20% are missing a probable private access tag.

**Comment by matkoniecz** [comment]
@westnordost How you would feel about adding this quest but with very low importance, above power poles material.

And reevaluating it after some time by checking values typically added in this quest - is it overwhelmingly =yes or maybe at least sometimes it =private? And after that its priority may be increased or it may be dropped.

**Comment by matkoniecz** [comment]
I think in this case "Is it a public playground?", with `yes` setting access=yes and `no` setting access=private should be sufficient.

**Comment by matkoniecz** [comment]
I changed to "Is it generally accessible playground?" to avoid misinterpretation and people thinking that question is about an ownership type.

**Comment by rugk** [comment]
I see a commit, so where's the PR. 😊

**Comment by matkoniecz** [comment]
Waits for testing to complete, which waits for my free time.

**Comment by westnordost** [comment]
@matkoniecz is stepping into my footsteps :-)
