### ISSUE TITLE
Tourist information type (`information` key for `tourism=information`)

### ISSUE THREAD

**Issue by rory** [westnordost/StreetComplete#1115]
### General
Affected tag(s) to be added: [information](https://wiki.openstreetmap.org/wiki/Key:information) for `tourism=information` which doesn't have it.

Question asked: **What type of tourist information is this?** *(This question needs improvement because, in English, "tourist information" means a tourist information office.)*

[`tourism=information`](https://wiki.openstreetmap.org/wiki/Tag:tourism%3Dinformation) is used for tourist information offices, and guideposts and maps etc. The [`information` key](https://wiki.openstreetmap.org/wiki/Key:information) is used to specify what type it is (`information=office` for a tourist information office). Currently 15% of `tourism=information` do not have a `information` tag ([cf. taginfo](http://taginfo.openstreetmap.ie/tags/tourism=information#combinations)). There is  big difference between a tourist information office and a guidepost! OSM data can be improved by adding this.

### Checklist
Checklist for quest suggestions (see guidelines):
- [x] 🚧 To be added tag is established and has a useful purpose - Yes, 500k instances of `information`.
- [x] 🤔 Any answer the user can give must have an equivalent tagging (Quest should not reappear to other users when solved by one) 
- [x] 🐿️ Easily answerable by everyone from the outside but a survey is necessary
- [x] 💤 Not an overwhelming percentage of elements have the same answer (No spam) Taginfo says 49% are `information=guidepost`, 23% `board`, 10% `map`, 3% `office`.
- [x] 🕓 Applies to a reasonable number of elements (Worth the effort). There are [~150 examples in London](https://overpass-turbo.eu/s/zYd), and [50 in Berlin](https://overpass-turbo.eu/s/zYe).

### Ideas for implementation
`[tourism=information][!information]` overpass filter to select it. [https://overpass-turbo.eu/s/zYb Overpass Turbo link].

There are ~40K `information=add` which could be a note for "add this information type"? Perhaps those objects could be changed? Further research needed.

For implementation, multiple choice based on common values on the [https://wiki.openstreetmap.org/wiki/Key:information OSM wiki for `information`].

I'm a programmer and willing to look at implementing this myself, if it's acceptable.

**Comment by matkoniecz** [comment]
> Applies to a reasonable number of elements (Worth the effort). There are ~150 examples in London, and 50 in Berlin.

https://taginfo.openstreetmap.org/tags/tourism=information#combinations - and around 40k worldwide

**Comment by matkoniecz** [comment]
information=add appears to be spammed in https://www.openstreetmap.org/changeset/46507755 (undiscussed import of addresses in Italy) and is unrelated to tagging of tourism=information.

**Comment by matkoniecz** [comment]
> I'm a programmer and willing to look at implementing this myself, if it's acceptable.

Idea looks great, no problems are present (checklist looks well), @westnordost looked at it and is not protesting so making PR looks like a good idea.

**Comment by matkoniecz** [comment]
@rory Are you stuck on something unclear/tricky? Maybe I can help in such case.

**Comment by rory** [comment]
Thanks for your offer of help. 🙂 I haven't been able to work on this since I filed the bug! 🙂 A bad Ubuntu upgrade, and having visitors means I haven't had that time. 🙂 

On 14 July 2018 14:42:13 CEST, Mateusz Konieczny <notifications@github.com> wrote:
>@rory Are you stuck on something unclear/tricky? Maybe I can help in
>such case.

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by matkoniecz** [comment]
> information=add appears to be spammed in https://www.openstreetmap.org/changeset/46507755 (undiscussed import of addresses in Italy) and is unrelated to tagging of tourism=information.

And now it is gone (I reverted part of import that added information=add, after consultation with mapper who imported the data) - https://taginfo.openstreetmap.org//search?q=information%3Dadd

**Comment by rory** [comment]
Hi, I'm going to try and look at this. However I don't know how to develop for android (but can probably muddle my way though. :) ). A 'how to compile and run StreetComplete' locally would be helpful. ;)

**Comment by rugk** [comment]
@rory Just get Android Studio, clone the project and load it there. Everything else [should be explained here](https://github.com/westnordost/StreetComplete/blob/master/CONTRIBUTING.md#development).

**Comment by rory** [comment]
@rugk thanks, I'm doing that now and getting somewhere. I was a little confused at first.

**Comment by matkoniecz** [comment]
Just in case that you are interested in restarting - mention if something project-specific is a problem (missing documentation on specific topic or something similar).

**Comment by Dosenpfand** [comment]
If @rory is not planning on implementing it anymore, I would like to give it a try.

**Comment by westnordost** [comment]
Sure, go ahead!

**Comment by westnordost** [comment]
I made an icon for this, it's ic_quest_information
