### ISSUE TITLE
since Update to aktual f-droid version no acces to map

### ISSUE THREAD

**Issue by Mannshoch** [westnordost/StreetComplete#1122]
At moment my screen is blank i only see the Questions.

**Comment by Akasch** [comment]
I am on it, the tile server has an issue after restarting

**Comment by Akasch** [comment]
It should work again now. i will add more monitoring and auto restarting to better detect fails like this.

**Comment by ENT8R** [comment]
Yes, it works again: https://map-data.de/#style=streetcomplete-light
