### ISSUE TITLE
New building quest doesn't have toilets/restroom option

### ISSUE THREAD

**Issue by cstackpole** [westnordost/StreetComplete#1125]
Greetings,
Version 6.0. I was at an outdoor park venue and the new building type quest popped up. I noticed two issues, one bigger than the other (IMO).

1. Permanent buildings for concession stands, as I understand it, should be labeled building=yes amenity=concession_stand. As that wasn't an option, I didn't know how to answer it so that the quest wouldn't be answered incorrectly by someone else. Can we make it more obvious to have an option that just says "It's none of these things" and perhaps just leave it as building=yes and put a tag on it for StreetComplete to ignore others that pull that quest?
https://wiki.openstreetmap.org/wiki/Tag:amenity%3Dconcession_stand

2. Permanent buildings for restrooms. These building were properly tagged as building=yes amenity=toilets and yet there was no option for selecting restrooms in the new quest that I could find. This is slightly more disconcerning because I checked and I DO have the restroom quests in my StreetComplete options and I refreshed the quests until I no longer had any it would download. Yet, I never got a single restroom quest even after I selected an option for the building quest. Is it possible that the new building quest some how superseded the restroom quests? I admit, I didn't have a ton of options to explore this on so it might be something I did. However, I did verify that the wheelchair access, fee, and baby changing were NOT configured on any of the bathrooms, but I did not get them as quests.
https://wiki.openstreetmap.org/wiki/Tag:amenity%3Dtoilets

Thanks!

**Comment by matkoniecz** [comment]
> Permanent buildings for concession stands, as I understand it, should be labeled building=yes amenity=concession_stand.

I am not convinced that tagging of that situation is settled. amenity=concession_stand is used 10 times worldwide. I planned to write proposal for shop=snacks that would be IMHO better tagging for that situation.

> should be labeled building=yes

It depends on situation: https://en.wikipedia.org/wiki/File:Concession_stand_at_Hanlans_Point.jpg seems building=shop or building=kiosk for me, https://en.wikipedia.org/wiki/Concession_stand#/media/File:Hillsboro_Stadium_concession_stand.JPG is building=shop, https://en.wikipedia.org/wiki/Concession_stand#/media/File:FineArtsMovieConcessionStand.png shoul not get its own building tag.

**Comment by matkoniecz** [comment]
>  These building were properly tagged as building=yes amenity=toilets and yet there was no option for selecting restrooms in the new quest that I could find. 

Use "Can't say" and create a note?

**Comment by westnordost** [comment]
Are there really that many toilet-houses around that it is worth adding the possibility to directly tag it? After all, see @matkoniecz ,  one can always leave a note.

**Comment by cstackpole** [comment]
Greetings,

>>   Permanent buildings for concession stands, as I understand it, should be labeled building=yes amenity=concession_stand.   

> I am not convinced that tagging of that situation is settled. amenity=concession_stand is used 10 times worldwide. I planned to write proposal for shop=snacks that would be IMHO better tagging for that situation.

I personally don't care either way, I'm just going based on the information I have seen. All that I really ask is that it be clear as to what the user is to select. Right now, I don't think it is.

>>   should be labeled building=yes   

> It depends on situation

I agree. The ones I'm talking about range from maybe a 10ft by 5ft building that is just selling t-shirts, to a 8ft by 8ft building selling snow cones, to a 40ft by 10ft building that is open length wise for selling drinks and snacks with a very tiny back room kitchen to fry the food. Those buildings serve no other purpose than concession sales. Again, I don't really have an opinion on HOW it is labeled, I just ask that it be clear for the user as to what should be selected.

>>  These building were properly tagged as building=yes amenity=toilets and yet there was no option for selecting restrooms in the new quest that I could find.

> Use "Can't say" and create a note?

Which is what I did. However, the building was properly tagged. Do we want users contently adding notes to the same already-properly tagged buildings? Besides, doesn't this just add a cycle to the quest? Building quest: "This is a bathroom". Next user gets a Note quest: "Yes, this is a bathroom." What good does that do when the building is already tagged as toilets? Then the cycle starts over when someone resolves the notes and just leaves the bathroom tagged just as it was before.

> Are there really that many toilet-houses around that it is worth adding the possibility to directly tag it? After all, see @matkoniecz , one can always leave a note.

I don't know what the percentage is world wide, but I know there are a TON of open air concert venues, amphitheaters, parks, festival / fair grounds near where I live. They all have these buildings. The state fair grounds have buildings that are nearly identical and different companies are in theses booths every year selling various things. Could be snacks one year, beer the next, T-shirts the next, hand-made jewelry the next after that. Concessions makes the most sense to me, though I would easy back the argument it should be a shop instead. 

I can also say that as someone who frequently visits national and state parks in the mid-US that seeing free standing permanent buildings for restrooms is quite common. Sometimes they are spilt men/women and sometimes it is just a bathroom. Sometimes they are large and others just a one-at-a-time. Some can be used by those with a handicap others can not. Some are family oriented, others not. The one thing that is common, they are permanent buildings. The only time I've ever encountered a fee-required toilet that was not owned by a business (eg: a restaurant for customers only) was out in Utah at a popular out-door venue for concerts. There were free ones but not many and the lines were HUGE. The owner in the lot next door charged 1$ a visit and there were a lot of nicely kept stalls. :-)

I honestly don't know an app that would tell you that information, and I doubt I'm going to go look at OSM for it.  But I don' think that is the point. Rather it is to have good reliable information and maybe someone will eventually write an app that needs that information.

I hope that helps. Thank you for your efforts on StreetComplete!

**Comment by HolgerJeromin** [comment]
Buildings with only toilets are not that rare IMO.

**Comment by matkoniecz** [comment]
> Those buildings serve no other purpose than concession sales. 

And were build with that purpose? In that case it is clearly building=retail (maybe building=shop or building=kiosk).

In terms of selection: at least for me concession stands are clearly type of a shop.

> I can also say that as someone who frequently visits national and state parks in the mid-US that seeing free standing permanent buildings for restrooms is quite common.

building=toilets are tagged 2k times worldwide what is relatively tiny (0.00%) part of 52 902k buildings with tagged type. I would leave notes for now, and check whatever StreetComplete notes show many about purpose-built toilet buildings.

**Comment by cstackpole** [comment]
> And were build with that purpose? In that case it is clearly building=retail (maybe building=shop or building=kiosk). In terms of selection: at least for me concession stands are clearly type of a shop.

Works for me. Can we think of a way to make that more clear in the description then please? Maybe just subtext under Shop(s) that adds "concession stands"?

> building=toilets are tagged 2k times worldwide what is relatively tiny (0.00%) part of 52 902k buildings with tagged type. I would leave notes for now, and check whatever StreetComplete notes show many about purpose-built toilet buildings.

I understand they are not popular worldwide, however, is it really OK to generate known bad data [Eg: wrong building type selected; pointless notes]? Maybe it isn't worth putting in a option for restrooms, but at least giving an option that is "None of these; just a building" that leaves it building=yes and doesn't bring up that quest again to others should be considered.

And to take this from a hypothetical to practical, here is one that I used coming off of the Harney trail not too long ago in Sylvan Lake, SD: https://www.openstreetmap.org/way/509518983

What value does adding a note that building bring to OSM?
Is it a building? Already tagged yes.
What is it for? Already tagged amenity=toilets.
When I just ask StreetComplete to hide that quest and I scan until it has no more quests, I do not see any of the restroom quests. All three of those are valid questions (and are enabled in my settings), but I don't get those quests. Is it just me?

And just for completeness sake:
Does it require a fee? No (at least not when I was there - but that is also why I'm not going to couch-map it).
Is it wheelchair accessible? Most certainly not. It was tiny.
Baby table? No.

And the bigger building nearby also tagged as restrooms? Either it was added or removed recently as I am really confident there wasn't a building there. But we actually stopped in 509518983 so I know it exists. :-)

Thank you.

**Comment by rory** [comment]
IME (as someone who just did a project to make toilets), free standing toilet buildings are pretty common for things tagged `amenity=toilets`. [21% of `amenity=toilets` have a `building` tag](https://taginfo.openstreetmap.org/tags/amenity=toilets#combinations). Toilets inside a shopping centre (etc) are not buildings. Would it be possible to offer a special option (for `building=toilets`) if the way is also tagged `building=toilets`?

**Comment by matkoniecz** [comment]
>  21% of amenity=toilets have a building tag.

Good point. And for almost all of them have building=yes (44k of amenity=toilets have building=yes). So 2k of building=toilets was a big underestimate.

At this point I think that building=toilet may make sense (it is hard to say - it depends on how much time of @westnordost  is needed to make an icon and whatever building list is in danger of getting too big).

**Comment by HolgerJeromin** [comment]
should be closed by https://github.com/westnordost/StreetComplete/commit/67fdf1e31d33f8d7b150bb992797e6ad41bf6116
