### ISSUE TITLE
Building can have both a housename and a housenumber

### ISSUE THREAD

**Issue by Kjarrval** [westnordost/StreetComplete#1126]
Would it be possible to add an option to "other answers" in the housenumber quest to encounter the situation where a building has both a housename and a housenumber?

It's somewhat common in my country that houses with only housenames before street addresses were implemented, that they later became integrated into the residential areas and given the usual modern addresses, while keeping their original names. The owners sometimes display both the name of the house and the housenumber, so it would be useful to be able to record both.

**Comment by matkoniecz** [comment]
> It's somewhat common in my country

Which one?

**Comment by westnordost** [comment]
Also, do not mix up names of buildings and addr:housenames. For example some buildings in Hamburg do have names, but they are not `addr:housename`s but just `name`s. [This one for example.](https://www.google.de/maps/@53.5678448,9.9440057,3a,75y,247.97h,105.63t/data=!3m6!1e1!3m4!1sWUZSH30I95AOlAGqGQUDVA!2e0!7i13312!8i6656)

**Comment by Kjarrval** [comment]
It's Iceland in my case, but I wouldn't be surprised if there were similar occurrences elsewhere.

In Iceland (and probably in some other countries) it's generally the land which has the name but not the building itself, although there are many occurrences where it's only the building. Sometimes it's the building which has the name but not the land, but you'd still be able to get mail delivered there if you were to use it. Since defining the area boundaries for the land hasn't been feasible with the data provided, it's fairly limited in OSM. Therefore the name and addr:housename tags have been used interchangeably in Iceland when it comes to those types of names. So in that case it wouldn't matter (at this moment) which tag would eventually be used.

**Comment by matkoniecz** [comment]
At this moment there are 400 object like this in Iceland (checked using http://overpass-turbo.eu/s/Aa2)

**Comment by matkoniecz** [comment]
There are around 1200 addr:housename in Iceland ( http://overpass-turbo.eu/s/Abe ) and 55 000 addr:housenumber ( http://overpass-turbo.eu/s/Abf ).

In that situation 400 combined addr:housename and addr:housenumber may be something where notes may be enough, I think that at this moment it is not worth implementing. Negative consequences (increased complexity of code, time to code it, time to maintain it, increased complexity of interface) looks to be bigger than benefits,

**Comment by westnordost** [comment]
I agree with @matkoniecz , sorry @Kjarrval
