### ISSUE TITLE
Let users triage issues with codetriage

### ISSUE THREAD

**Issue by rugk** [westnordost/StreetComplete#1127]
Maybe let's add this badge somewhere, where it is appropriate, to motivate users to get one or two issues per day in their inbox?

[![Open Source Helpers](https://www.codetriage.com/westnordost/streetcomplete/badges/users.svg)](https://www.codetriage.com/westnordost/streetcomplete)
url: https://www.codetriage.com/westnordost/streetcomplete

As you can see, some already use it.

**Comment by westnordost** [comment]
No thanks, I think this will not be of help. Those who are interseted to help, can watch this repos, they will also get emails this way.

**Comment by rugk** [comment]
BTW don't want to open a new issue for that, but here seems to be a service that is free for a small volume of issues that automatically tries to detect duplicates: https://gitmate.io/home
Used by Nextcloud e.g. I guess this would maybe be useful. :smile:
