### ISSUE TITLE
Consider tweaking language in quest settings reset confirmation

### ISSUE THREAD

**Issue by matkoniecz** [westnordost/StreetComplete#1128]
> Reset both quest enablement and order to the default?

Seems to be not optimal. Maybe

> Restore original quest order and status?

would be better? (I am not making PR as I want to verify whatever it is really an useful improvement - if it is really better I may make a PR for it)

**Comment by westnordost** [comment]
"Status" is not explained anywhere, so I prefer enablement.
If you prefer "Restore original quest order and enablement" over the current wording, you can make a PR and I will accept it, I have no strong opinion on what sounds better.

**Comment by matkoniecz** [comment]
I wanted to avoid enablement, so it is best to close it.
