### ISSUE TITLE
Quest request: Shop type

### ISSUE THREAD

**Issue by NotAFile** [westnordost/StreetComplete#1129]
it would be neat to be able to tag shops with the shop=* tags

**Comment by NotAFile** [comment]
closing because I missed the template

**Comment by matkoniecz** [comment]
Also note that StreetComplete is not going to allow adding new shop (is there enough of shop=yes and amenity=shop to make this an useful quest)?

**Comment by NotAFile** [comment]
there's at least a few in my neighbourhood. This was prompted by me not being able to specify what type the shop is is after selecting shop as building purpose. The fact that shops are nodes and buildings are areas complicates this of course.
