### ISSUE TITLE
bug: crash on osm login

### ISSUE THREAD

**Issue by wombalton** [westnordost/StreetComplete#113]
When I try to give my login credentials the app crashes with the first character in the username field. 
Appversion 0.5 from f-droid on Android 5.1.1

**Comment by westnordost** [comment]
Would it be possible for you to send me the log that includes the stack trace?

**Comment by wombalton** [comment]
If you tell me how to get it.

**Comment by westnordost** [comment]
The easiest way would be if you get an app like aLogcat or SysLog. You need to start it, then reproduce the crash. In the app, you have the possibility to mail the log somewhere (etc), which would be osm@westnordost.de

I reckon that I should probably program something that records crashes automatically.

**Comment by wombalton** [comment]
Hm, alogcat produces no output. Any recommendations on the settings? I noticed today that the crash only happens if my email starts with a w other mail addresses seem to be fine. Can't test more, cause my osm mail starts with w ...

**Comment by HolgerJeromin** [comment]
You need root access so alogcat is able to catch foreign log output. The other possibility is attaching the phone with usb and use the adb programm on the computer to show all logs.

**Comment by westnordost** [comment]
Reading the log shouldn't require root, just the READ_LOGS permission. I will take the look at the hint you gave me regarding the "w". Sounds really odd.

**Comment by westnordost** [comment]
I have another idea what could be the reason. Can you tell me the device you are testing on?

**Comment by wombalton** [comment]
Well my device is a sony xperia z1 compact. And it is rooted. But alogcat is not asking for root permissions.

**Comment by westnordost** [comment]
Oh, I have the same! Well, then I have no clue :-(

Anyway, I am currently implementing advanced error reporting. With the next version, you will be able to send an error report for crashes (to my email address) with the click of a button.

**Comment by falematte** [comment]
I have this device too and I cannot login... Anyway the credentials are correct...

**Comment by westnordost** [comment]
Please try again with StreetComplete 0.8. If it crashes, you will be asked to send the report to my email address. Then I will have a look at it.

**Comment by westnordost** [comment]
User did not report back
