### ISSUE TITLE
Project website

### ISSUE THREAD

**Issue by rugk** [westnordost/StreetComplete#1130]
Did you ever consider creating a project website for StreetComplete?

## Why?

* When e.g. linking to StreetComplete one can currently only link to the GitHub page, which is not a nice URL long, and not really descriptive
* GitHub is rather a place for developers (e.g. you are always greeted with a list of files in the repo when you link to this project "main page"), so as the target audience of StreetComplete are actually "not-so-techy" users, we need a friendly, nice and welcoming page, that keeps users away from the source code.
* Your project is certainly big enough for this, already… :smile: 

## Ideas

Some points I have in mind:

**Content:**
* of course, feature the header image of StreetComplete, note you can get the source images and some other examples/ideas [here](https://github.com/rugk/streetcomplete-ad-34c3), with `100vh` to make it look awesome :wink: 
* present some example quests… (to make users interested in trying out the app) 
* of course animation/video/gif in phone frames etc.; screenshots
* "deep" at the bottom maybe also explain OSM a bit – so users get what this is all about and why/where they contribute/why this is good

**UI/design:**
* should look-alike to the UI of StreetComplete, i.e. use same colors, etc. but it's still a website, of course
* to some extend a bit funny/gamified (i.e. there may be some small animations on hover, stuff with [existing] pictograms, may be overlapping outside of the page and e.g. slide in on scroll…) to present contributing not as a hard task, but as something you _want to do_
* maybe a map showing example quests (interactive, if possible, again) OR the "in photo" image mentioned before maybe just as an interactive example (it does not have to have the exact same design, simple map popups on hover are enough, 
* even if the example "quests" are not shown on the map, we may use it as a stylictic element i.e. just for design), because it is a main part of the app (in a visual sense, it's what the user will see), so we also have to feature the StreetComplete map style(s); maybe even in a _parallax_-style

**Marketing stuff:**
* currently, the "tagline" of this app is "OpenStreetMap surveyor app". IMHO, that's also a bit technical and one may come up with a better one. I know, it's actually not related to this issue hee, but once we are at it (make a human-friendly starting/launching page, instead of GitHub), we can reconsider it here, too

**Advanced:** (currently out-of-scope IMHO)
* localization (I'd say no for the initial version, but this can get into the long-term plan)

**Technical:**
* a one-page is fine, IMHO (there is really not the need for more pages)
* I'd prefer a 100% static version, or (if really need – and I doubt so) maybe Jekyll or another static site processor, but in the end it should be hostable on GitHub Pages, if needed. There is just no need for dynamic stuff and static sites are always the fastest to load
* we hopefully need not so much JS, maybe only for scrolling effects (i.e. click on -> visually scroll to part of the page)

## Examples

A simple, but already quite nice example is https://transportr.grobox.de/ for the Transportr app. Or https://www.davdroid.com/. Of course, the design is different than what I described above (and it is supposed to be :wink:), but it demonstrates how you can do it in a useful way.

## Howto

Of course, totally a community project. :smile: 
And I'd make a new repo for it, that's for sure. There this stuff can be discussed in multiple issues in more detail then.

And, @ENT8R, gotta interested? :wink:

**Comment by westnordost** [comment]
No, I never really considered it, because it would take too much time away from actually working on the app. Since unlike for desktop applications, the app is distributed almost solely on app stores, having an actual website to present the app is much less important than for desktop software, since the description, screenshots, ratings etc etc are already in one place - where the app is downloaded.

**Comment by rugk** [comment]
Ah good point about that desktop software comparison. But yet again you also may not want to link to Google Play directly, because you then scare F-Droid users away – and vice versa…
So it needs a "neutral" "linkable" page, and since today, this had to be GitHub. And that's not the best thing, as I've explained above.

**Comment by rugk** [comment]
BTW @ENT8R are you on board? I meant that "interested" thing literally, so I'd think we can do that together. (Also anyone else, who's interested.)

**Comment by ENT8R** [comment]
> BTW @ENT8R are you on board?

Of course! I would really like to help... I just did not answered directly because I had not enough time. So I just gave a thumb up :+1:
We could use [Materialize](https://materializecss.com/) as a framework (it follows the Material Design Guidelines just as the app does too so it should be pretty easy to achieve a similar look and feel; in addition to that it can be used without jQuery or any other external library since the current beta version (1.0)) but all these things can of course be discussed in the new repository!
Just a quick note: I can't help you in the next two to three weeks because I have some other stuff to do :grinning:
But generally I agree with all your ideas!

**Comment by rugk** [comment]
Sure, I also don't want to rush this thing…

So the plan ahead:
* as for the general project, this issue here is there for now, also comment if you want to chime in and help
* I'll create a repo later these days… so there we can collect issues (put this top post into smaller tasks e.g.)
* Once, we've got this, maybe first add some sketch (via Inkscape?) so we have a common vision of how it should look like
* Then we can really fill the repo. :smiley:

**Comment by rugk** [comment]
Oh, Transportr has a new domain, with a .app TLD :hugs:: https://transportr.app/
That's something for StreetComplete, too, is not it, @westnordost?

**Comment by rugk** [comment]
We could also use https://github.com/material-components/material-components-web

**Comment by matkoniecz** [comment]
Are you sure that spending time on duplicating documentation in yet another place is a good idea?

I would rather improve documentation on OSM wiki, maybe upload short movie how SC is used and update https://github.com/matkoniecz/StreetCompleteJSON/blob/master/taginfo.json .

**Comment by ENT8R** [comment]
But does a new user really look at the OSM wiki? I'm sure a new user who just searched for a method to contribute easily to OSM will rather visit an official website of the app than some kind of wiki...

**Comment by matkoniecz** [comment]
In that case - maybe adding content to https://learnosm.org/en/beginner/ and similar resources would be a better idea? Or creating new one if all existing ones are dead/not accepting contributors?

**Comment by rugk** [comment]
I am very content with the current documentation of SC. sure, always add it to beginner guies.

**Comment by rugk** [comment]
Repo is there: https://github.com/rugk/streetcomplete-website/issues

**Comment by rugk** [comment]
Okay, as @westnordost is closing this, I guess we should now track it all in https://github.com/rugk/streetcomplete-website/issues. (I would rather leave it open, so other users can find it, but well... your decision.)
