### ISSUE TITLE
surface stone for steps

### ISSUE THREAD

**Issue by rza31** [westnordost/StreetComplete#1132]
Add option surface= stone for steps. Many steps at historic places have surface stone.

### General
 [surface=stone](https://wiki.openstreetmap.org/wiki/Key:surface) 

[taginfo stone](https://taginfo.openstreetmap.org/tags/surface=stone)

### Checklist
Checklist for quest suggestions (see guidelines):
- [x] 🚧 To be added tag is established and has a useful purpose
- [x] 🤔 Any answer the user can give must have an equivalent tagging (Quest should not reappear to other users when solved by one)
- [x] 🐿️ Easily answerable by everyone from the outside but a survey is necessary 
- [x] 💤 Not an overwhelming percentage of elements have the same answer (No spam)
- [x] 🕓 Applies to a reasonable number of elements (Worth the effort)

**Comment by matkoniecz** [comment]
> surface=stone

Is it documented anywhere at OSM wiki?

**Comment by matkoniecz** [comment]
Also, can you give an example image of steps that you want to tag as a surface=stone?

**Comment by rugk** [comment]
Also what should the question be: "Are these stone steps?" (And if you answer with no, what should it tag? -> this is the "Any answer the user can give must have an equivalent tagging" requirement, which you tickwed above, but provided no explanation why it is true)

So this quest would have to be more general. But as far as I remmeber, the path surface quest or similar does include steps. So your use case might already be solved.

**Comment by ENT8R** [comment]
> Also what should the question be: "Are these stone steps?" 

This ticket is not about a filly new quest but rather about the extension of an already existing quest (obviously the surface quest)

I'm not sure if it is worth to include an option which is only used 3000 times around the whole world and which seems to not be documented somewhere...

**Comment by rza31** [comment]
![Uploading Vlotho_-_Steintreppe_am_Brink.jpg…](File:Vlotho - Steintreppe am Brink.jpg) from wikimedia commons

**Comment by matkoniecz** [comment]
Both are surface=paving_stones

> A relatively smooth surface paved with artificial blocks (block pavers, bricks) or natural stones (flagstones), with a flat top. The gaps between individual paving stones are very narrow, either because the stones have a perfectly regular shape (rectangular, or any surface-filling shape) or because they have been carefully selected, fitted and placed in order to form an even, closed surface.

**Comment by matkoniecz** [comment]
Though maybe surface quest may be improved to reduce confusion.

**Comment by rugk** [comment]
Ah, was confused as the op used the issue template.

In this case, I'd agree. Stone steps are quite common.

**Comment by matkoniecz** [comment]
> Stone steps are quite common.

How commons are stone steps that do not fit surface=paving_stones definition?

**Comment by rugk** [comment]
Mhh, hard to say. Actually it may be hard to even explain the user the difference. But the ones @rza31 [linked before](https://github.com/westnordost/StreetComplete/issues/1132#issuecomment-404831155) are really only stone ones.

**Comment by westnordost** [comment]
They look like concrete, tbh

**Comment by rugk** [comment]
Maybe the second one [but this](https://commons.wikimedia.org/wiki/File:Vlotho_-_Steintreppe_am_Brink.jpg) is certainly stone. Likely you'll also see it better "IRL" than on photos.

**Comment by matkoniecz** [comment]
> but this is certainly stone

and it is certainly fitting surface=paving_stones

**Comment by westnordost** [comment]
By the way, I always thought `stone` was defined as "bare rock", so, a natural, unhewn stone surface as found on some trails in the mountains.

Anyway, I will make a decision here: I will not add this option in the surface quest, because the definition of stone is unclear and, more importantly, pure stone surface is rare enough that in that case, the user can leave a note.
