### ISSUE TITLE
Building type Question - elevator 

### ISSUE THREAD

**Issue by Mannshoch** [westnordost/StreetComplete#1138]
I detected many Buildingtype Question that came form elevators. All elevators I met so far where accessible from outside of a building and headed into a underpass (Unterführung) e.g. Elevators from/to a trainplatform.
How should I answer these Question?

**Comment by matkoniecz** [comment]
1) with "other answers" and "can't say" and create a note that it is an elevator building

or

2)  select "show more",  "civic building", "public  transportation building"

**Comment by westnordost** [comment]
See @matkoniecz 
The dialog can not cover every possible building type, the rest must be covered with leaving a note.

**Comment by billyonthemountain** [comment]
Question: Why is it even showing up as a building ? The [elevator tag](https://wiki.openstreetmap.org/wiki/Tag:highway=elevator) is usually used either on highways or features. An example where this quest pops up is on the [East-side overpass](https://www.openstreetmap.org/#map=19/46.94846/7.43648) of the Bern train station in Switzerland.

**Comment by westnordost** [comment]
Because someone tagged the elevators as buildings:
https://www.openstreetmap.org/way/380731123#map=19/46.94852/7.43696

**Comment by billyonthemountain** [comment]
Here's a screenshot showing the quests in question. I did make sure to refresh the quests in the area (invalidated quest cache, cleared app cache just in case). 

 ![screenshot](https://user-images.githubusercontent.com/238735/45181411-ac0b8800-b21e-11e8-850e-d88d956a6fa0.jpg)

**Comment by westnordost** [comment]
[You don't believe me, do you?](http://overpass-turbo.eu/s/BHC)

**Comment by billyonthemountain** [comment]
My bad. I just learned about levelmaps... iD always selects the top object. Querying the area reveals the lower ones.
