### ISSUE TITLE
Idea for an alternate Question design for Building

### ISSUE THREAD

**Issue by Mannshoch** [westnordost/StreetComplete#1139]
Instead of choosing the Icon directly you may could answer some basic information first and get presented possible Answer.

![building chooser](https://user-images.githubusercontent.com/7795891/42806636-2b7fe24a-89af-11e8-9dd9-3683dbe78e9a.png)

**Comment by matkoniecz** [comment]
The main problem is that is asking about the current use.

4 families living in building constructed as a church should be answered and tagged as a church, not as an apartment

**Comment by Mannshoch** [comment]
that's the Point.
As normal User I'm not able to decide for sure how to tag something. But Streetcompleet know that. 
If a church from a minority religion is located in a normal House. Should the building be tagged as Church? you know the answer. I don't. 
How should I tag a [historic Factory that was reused as cultural center](https://en.wikipedia.org/wiki/Rote_Fabrik). I don't know.
My idea is only an example, because I'm not familiar with all of this.

**Comment by matkoniecz** [comment]
> If a church from a minority religion is located in a normal House. Should the building be tagged as Church?

In this case user should select "Other answers...", "It has multiple purposes". Information that is displayed in such case should be enough to help her/him.

Do you think that something should be improved to make it more clear?

> How should I tag a historic Factory that was reused as cultural center. I don't know.

Are you using StreetComplete in English or in another language?

**Comment by Mannshoch** [comment]
German. Your question was the cause for looking again on Streetcomplete . I detected the sentence you may mentioned. I had a bit a problem with choosing the correct building because I have the Problem on some building to choose between house and business because of the rich history on some buildings and focused on it so I missed to read again the Text.

**Comment by westnordost** [comment]
I do not think this is appropriate. There are more options than houses and apartments.
