### ISSUE TITLE
Crash if no internet connection available

### ISSUE THREAD

**Issue by Natenom** [westnordost/StreetComplete#114]
How to reproduce:
* Activate WLAN and or mobile data
* Start StreetComplete
* Press Back button to leave StreetComplete
* Disable all networks (Airplane Mode)
* Start StreetComplete
* Press Backbutton again to leave app
* Crash (not always)

Another user has the same problem.
He is on 0.5++, I use https://github.com/westnordost/StreetComplete/commit/3cba998650a11753043f80753ad21d2b0811310f.

**Comment by westnordost** [comment]
Can reproduce, but doesn't seem to have anything to do with internet connection. It's the compass.
