### ISSUE TITLE
add bicycle=yes/no and foot=yes/no to barrier=lift_gate node

### ISSUE THREAD

**Issue by matkoniecz** [westnordost/StreetComplete#1141]
### General
Affected tag(s) to be modified/added: [](https://wiki.openstreetmap.org/wiki/Key:Access)
Question asked: **Is this lift gate blocking road for cyclists/pedestrians**

### Checklist
Checklist for quest suggestions (see guidelines):
- [x] 🚧 To be added tag is established and has a useful purpose
- [x] 🤔 Any answer the user can give must have an equivalent tagging (Quest should not reappear to other users when solved by one)
- [x] 🐿️ Easily answerable by everyone from the outside but a survey is necessary 
- [x] 💤 Not an overwhelming percentage of elements have the same answer (No spam) [30% has bicycle=yes, 5% bicycle=no, 30% has foot=yes and 4% foot=no - https://taginfo.openstreetmap.org/tags/barrier=lift_gate#combinations ]
- [x] 🕓 Applies to a reasonable number of elements (Worth the effort) around 140k quests for each

### Ideas for implementation

It may be tricky to have a good question for cases with cycleway/footway drawn separately - lift gate may be completely blocking road (including pedestrian traffic) and footway may allow to bypass it.

**Element selection:** standard query should be fitting, there is no need for anything complicated here

**Metadata needed:**  no

**Proposed GUI:**  trivial yes/no quest (main effort is to make the icon)

Related wiki pages: https://wiki.openstreetmap.org/wiki/Tag:barrier%3Dlift_gate

**Comment by HolgerJeromin** [comment]
Perhaps the same for `bollard` and `block`.

If we have already `access=no/private` this should be skipped. Is probably a valid tagging ([example](https://www.openstreetmap.org/node/4487156310)).

**Comment by matkoniecz** [comment]
> If we have already access=no/private this should be skipped.

no, it should be still asked. At least in my region barrier=lift_gate often blocks only car access, and allows passage of cyclists and pedestrians (as its function is to protect parking spaces rather than block access).

**Comment by westnordost** [comment]
What about the value of this tag, why is it important to map this?

**Comment by matkoniecz** [comment]
It is useful for routing (I am not sure is it actually used but I would expect that it is useful for bicycle or pedestrian route finding).

**Comment by matkoniecz** [comment]
Some of my bicycle routes are crossing semi-private areas - for example http://brouter.de/brouter-web/#zoom=16&lat=50.06501&lon=19.91864&layer=OpenStreetMap&lonlats=19.91817,50.06769|19.920305,50.066988|19.919736,50.065672|19.921346,50.062084&nogos=&profile=trekking&alternativeidx=0&format=geojson crossing university area (with lift gates on entrances blocking cars but not bicycles).

Other similar areas include hospital areas ( https://www.openstreetmap.org/#map=17/50.06094/19.95386 ) or residential areas blocking entrance for cars but allowing bicycle access including transit.

Maybe Kraków is unique in this case?

**Comment by HolgerJeromin** [comment]
This is a [classic tagging](http://www.openstreetmap.org/node/1314329857) error in many forests i know. At least south of Aachen and south-east of bielefeld has this problem.

**Comment by westnordost** [comment]
Okay, you convinced me that there are gates and lift gates "in the wild" on the route. However, are there also lift gates and gates for which it would not be the case that _of course_ a bicyclist and a pedestrian can pass it?

**Comment by matkoniecz** [comment]
I am now looking for images.

Cyclists passable ones: 

https://commons.wikimedia.org/wiki/File:Zone_commerciale_La_Croix-Blanche_%C3%A0_Sainte-Genevi%C3%A8ve-des-Bois_en_France_le_16_mars_2017_-_31.jpg

https://commons.wikimedia.org/wiki/File:Olomouc,_Pasteurova_8a.jpg

https://commons.wikimedia.org/wiki/File:P%C3%ADsnice,_%C5%A0vihovsk%C3%A1,_z%C3%A1vora_a_%C5%A1ikana.jpg

https://commons.wikimedia.org/wiki/File:2017-11-02_Rua_Almeida_Garret,_Albufeira.JPG

Cyclists impassable ones:

https://commons.wikimedia.org/wiki/File:Praha,_N%C3%A1dra%C5%BE%C3%AD_Hole%C5%A1ovice,_autobus_Arriva_Praha_do_Neratovic.jpg

One thing TODO: confirm that cases like https://commons.wikimedia.org/wiki/File:Slan%C3%BD_(0486).jpg (foot access not allowed, lift gate is not blocking foot traffic) should be tagged with foot=private on way and foot=yes on lift gate node itself.

One more TODO: is there such thing as foot=limited (lift gate where I will pass but my grandmother may have trouble as it is necessary to go under boom as it is impossible to just walk through).

**Comment by matkoniecz** [comment]
Potential blocker for pedestrian ones: cases like https://commons.wikimedia.org/wiki/File:NN_Old_Fair_Cathedral_08-2016_img2.jpg?fastcci_from=5117570&c1=5117570&d1=15&s=200&a=fqv are fairly common what may make answers quite low quality. Currently I am planning to ask only about cyclist access.

**Comment by rugk** [comment]
So as it seems these barriers can vary a lot, and this quest is not about determinating the barrier _type_. As such, I guess you can just show one image of a barrier (so it is obvious to the user what that thing is; actually I doubt this is even needed when you e.g. have a nice quest icon) and then use pictographs to just indicate "passable by :running_man:"/:no_pedestrians: and "passable by :bike:"/:no_bicycles:. Actually these Emojis, IMHO already catch it quite well.

The only thing that may still be needed to be conveyed is that this is **not about legal access**, or is it actually also about that? In the OP, you @matkoniecz totally forgot to mention the tag that this quest wants to change. It is about `foot` and `bicycle`, I guess?

**Comment by matkoniecz** [comment]
> not about legal access, or is it actually also about that

I want to clarify that in Wiki docs first to confirm that my tagging idea is shared by others.

>  It is about foot and bicycle, I guess?

Yes.

**Comment by westnordost** [comment]
Why struggle to find images anyway? Couldn't this be two yes/no questions?

**Comment by matkoniecz** [comment]
> Why struggle to find images anyway?

Partially because I thought that it may be better to give explicit example (so people who never used bicycle will not be confused what is the difference), partially to check whatever I missed something (and I noticed that I missed legal vs physical block that I will need to clarify).

Also, in one of discussions I remember guideline that it is always better to have an image than to not have one (it may be from leaf_type/leaf_cycle one).

**Comment by rugk** [comment]
> Also, in one of discussions I remember guideline that it is always better to have an image than to not have one (it may be from leaf_type/leaf_cycle one).

Rather call it an illustration, IMHO, as an image may not always be preferably (see building type quest e.g.).

Anyway, if it helps for background check that is okay, but I'd still say in the GUI of SC, use graphics like :no_bicycles:  or :no_pedestrians:.

**Comment by matkoniecz** [comment]
It is problematic as 

1) there is no good way to distinguish "legal access" and "physical access" in tagging
1b) new tagging needs to be established and SC is not the good place to do this
2) there is a big gray area where legal access is uncertain and unclear
3) I have no idea how to exactly implement that
