### ISSUE TITLE
ask about missing oneway:bicycle=no for cycleway=opposite/cycleway=opposite_lane/...

### ISSUE THREAD

**Issue by matkoniecz** [westnordost/StreetComplete#1147]
### General
Affected tag(s) to be modified/added: [oneway:bicycle](https://wiki.openstreetmap.org/wiki/Key:oneway:bicycle)
Question asked: **Is this way oneway for cyclists?**

### Checklist
Checklist for quest suggestions (see guidelines):
- [x] 🚧 To be added tag is established and has a useful purpose
- [x] 🤔 Any answer the user can give must have an equivalent tagging (Quest should not reappear to other users when solved by one)
- [x] 🐿️ Easily answerable by everyone from the outside but a survey is necessary (or at least it is useful to check whatever road is really oneway for cyclists, such tagging indicated inexperienced and possibly confused mapper)
- [x] 💤 Not an overwhelming percentage of elements have the same answer (No spam)
- [x] 🕓 Applies to a reasonable number of elements (Worth the effort)

### Ideas for implementation

Note that way may be oneway for cars and oneway for bicycles - but in opposite directions. It should be checked is it something that is really happening.

**Element selection:** 

cycleway/cycleway:left/cycleway:right/cycleway:both = opposite/opposite_lane

**Metadata needed:** 

**Proposed GUI:** 

Based on oneway quest.

**Comment by rugk** [comment]
> "It has been proposed that this page or section be merged with Tag:cycleway=opposite. ([Discuss](https://wiki.openstreetmap.org/wiki/Talk:Key:oneway:bicycle))"

So this would the the only counter case:
> Note that way may be oneway for cars and oneway for bicycles - but in opposite directions.

And I doubt that happens very often. I've never seen that. I don't even know how they would sign that thing, as they needed an "oneway sign" that only applies for bicyclers and is placed next to the contrary sign for cars.

**Comment by ServusWorld** [comment]
This exists quite often in Vienna. Even if there is nothing like a segregated cycleway, it says "Ausgen. Fahrradfahrer" below the oneway or "no entry" sign. But it can only be found on streets that are wide enough and with few cars.

The easiest way to cover those cyclist exceptions would be to place a checkbox inside the "Is this a oneway" quest, which the user can tick if such an exception is in place. If it is ticked, simply `oneway:bicycle=no` will be added.

**Comment by rugk** [comment]
Yeah this "except :bike:" sign is also often visible in Germany for one-ways. However, this is very unlikely to happen:
> Note that way may be oneway for cars and oneway for bicycles - but in opposite directions.

So was this issue just about asking whether a oneway also applies to bicyclists? If so, then yes, could be an acceptable quest.

However, what is it supposed to tag the oneway like, if there is _no_ special "exemption" for bikes?

**Comment by matkoniecz** [comment]
I added this quest in my fork as there are regions (for example Vienna) where roads are tagged with cycleway=opposite/opposite_lane but oneway:bicycle=no tags are missing.

And I do not feel comfortable with adding oneway:bicycle=no without a survey.

So for me it is basically special case of #1112

**Comment by westnordost** [comment]
Nothing changed since my previous comment.

I understand and agree that a mechanical edit cannot be made to tag all cycleway=opposite roads additionally with oneway:bicycle=no because there is a theoretical *possibility* that roads exists in the world where one former does not imply the latter.

That does not mean however that they really exist or if they do, in sufficient numbers to make it eligible as a quest in StreetComplete (99% of answers... / no spam rule). Especially, because I still doubt that there are any numbers at all.
