### ISSUE TITLE
0.6 crash on startup

### ISSUE THREAD

**Issue by Locke** [westnordost/StreetComplete#115]
Tonight I upgraded from 0.5 to 0.6 (via Google Playstore). When I try to open the app it immediately crashes, I don't even see it starting.

**Comment by westnordost** [comment]
I am terribly sorry about this. I will prepare a new version with a fix right now.

**Comment by westnordost** [comment]
https://github.com/westnordost/StreetComplete/commit/28d1373743c9b29a8773f85fe71162893a90dc78

**Comment by Locke** [comment]
Thanks for the fast fix :+1:
