### ISSUE TITLE
Wrong message for quests disabled in some countries ?

### ISSUE THREAD

**Issue by PanierAvide** [westnordost/StreetComplete#1150]
It seems that now, StreetComplete implements a sort of filter for quests by countries, which is a good idea. But when I first saw this :
![screenshot_2018-08-04-09-42-53](https://user-images.githubusercontent.com/1349014/43673921-3a0ba5ae-97cb-11e8-878b-b22e400486c4.png)

I was like : why do they disabled these quests in France ?? ("Ne jamais afficher en France" = "Do not display in France"). Looking up at the source code led me to the conclusion that in fact it's the contrary which is done : these quests are enabled only in a few countries, including France.

So, there is an issue somewhere : whether the label is not correctly translated (maybe should be instead "Available in France"), or the condition to make it show up/hide is wrong (should not appear on these quests). As I'm not sure which should be corrected, I'm opening this issue.

Regards.

**Comment by ENT8R** [comment]
> whether the label is not correctly translated (maybe should be instead "Available in France")

That a quest is available in a country is the default case, so this is not displayed at all.

**Comment by rugk** [comment]
> these quests are enabled only in a few countries, including France.

I can confirm it. [From the quest list](https://wiki.openstreetmap.org/wiki/StreetComplete/Quests) you have the "disabled in … countries" link, which takes you to [the map, and you'll see that tactile pavings are enabled](https://ent8r.github.io/blacklistr/?java=tactile_paving/AddTactilePavingCrosswalk.java).

Also I see a little display error: If they were actually disabled, it should display them greyed out and without a checkmark, so they cannot be enabled by a user.

**Comment by matkoniecz** [comment]
> so they cannot be enabled by a user

Why? Disable quests are not disabled because are actively harmful but because added data is usually nearly useless. But users may want (because they live in a unique place or because they have different priorities or maybe because situation changed and quest is now useful)

**Comment by matkoniecz** [comment]
> whether the label is not correctly translated

Can you look at https://github.com/westnordost/StreetComplete/blob/master/CONTRIBUTING.md#translating-the-app and check translation? I am unable to check translation into French.

**Comment by PanierAvide** [comment]
The translation is right according to english "never shown in XXX" is correctly translated in french by "ne jamais afficher en XXX". As the translation seems right, the bug is elsewhere.

**Comment by matkoniecz** [comment]
Can you switch language of your Android to English and upload screenshot with app in English? (and switch later back to your language)

I am still not 100% sure what is the problem.

**Comment by PanierAvide** [comment]
I'm pretty sure the error comes from this method, as the rest seems good :
https://github.com/westnordost/StreetComplete/blob/ea49f25bfe1b16d57674861b76137fde2c1a98b7/app/src/main/java/de/westnordost/streetcomplete/settings/QuestSelectionAdapter.java#L197
I will send you the screenshot in English ASAP.

**Comment by PanierAvide** [comment]
![screen_en](https://user-images.githubusercontent.com/1349014/43674337-ac3f434a-97d2-11e8-8187-8bd9b2aed1a5.png)

**Comment by westnordost** [comment]
Looks like a bug

**Comment by westnordost** [comment]
So, do bus stop quests pop up in France? (Is this only a display bug in this view?)

**Comment by PanierAvide** [comment]
Yes, I can retrieve tactile_paving on bus stop quest in France, it's still working.

**Comment by westnordost** [comment]
Okay, so the issue is that the country code for France is **FX**

**Comment by westnordost** [comment]
Fixed. I think there was also a crash bug: If you scroll into the middle of the ocean and then open the quest list (and scroll down to one quest that is not enabled everywhere), it used to crash I think. Replaced the crash with an easter egg ;-)

**Comment by rugk** [comment]
> Replaced the crash with an easter egg ;-)

:heart_eyes:

**Comment by rugk** [comment]
> Okay, so the issue is that the country code for France is FX

Ugh, [no](https://duckduckgo.com/?q=country+code+fr&t=ffab&ia=answer)…?
Or who does say so? DDG quotes ISO 3166.

**Edit:** Actually [that seems to be an outdated code](https://en.wikipedia.org/wiki/ISO_3166-3#FXFR) for "France metropolitan"…

**Comment by westnordost** [comment]
Hmm well, FX is used in the country [boundaries ](https://josm.openstreetmap.de/browser/josm/trunk/data/boundaries.osm) file in JOSM, StreetComplete just uses this file as well.
