### ISSUE TITLE
undo of unuploaded quest is shown wrong name

### ISSUE THREAD

**Issue by HolgerJeromin** [westnordost/StreetComplete#1151]
I have latest play store beta.
It was a few days ago. I answered a quest, but now don't remember which it was (street surface?). 
At undo the quest "do you want to undo xy?" was shown the wrong quest name.
The app showed +1 to upload (bad mobile internet). After pushing it it went down to 0.
On osm.org no changeset was shown.

Perhaps this information is sufficiant. Otherwise ignore the report :-)

**Comment by westnordost** [comment]
Why would you think that the name displayed in the undo dialog would be of the wrong quest?

**Comment by HolgerJeromin** [comment]
it was like that: 
answering surface quest
undo dialog said:
"do you want to undo housenumber quest?"

**Comment by rugk** [comment]
> On osm.org no changeset was shown.

Maybe you did not wait long enough, see [FAQ](https://wiki.openstreetmap.org/wiki/StreetComplete/FAQ#How_does_the_app_handle_uploads.3F).

**Comment by rugk** [comment]
As for the actual issue: Can you reproduce it? I.e. answer surface quests, then click on undo, and then see the housenumber quest?

**Comment by westnordost** [comment]
@HolgerJeromin Do you have autosync on or off? If it is off, did you upload the previous answer (surface quest) before undoing?

**Comment by HolgerJeromin** [comment]
I will close this issue because I can not reproduce it in a small scale test without internet. Will reopen if I have more info.
