### ISSUE TITLE
new speed limit interface - focus the input field after selecting "A sign" and pressing OK

### ISSUE THREAD

**Issue by matkoniecz** [westnordost/StreetComplete#1154]
It is not obvious that sign circle is a textbox.

original title was "new speed limit interface gives no feedback on selecting "A sign" and pressing OK". Problems turned out to be limited to my phone.

<s>At least some quests mention that data is not filled yet on premature "OK" press.</s>

**Comment by matkoniecz** [comment]
I now tried to add picture how other quests are doing that, but apparently it stopped everywhere.

Feel free to close it as "it is my own fault for buying a suspiciously cheap phone made by a company from China" if it is working on other phones.

**Comment by westnordost** [comment]
So, the quest does not show a toast that the user left the form empty when he does not fill in the speed limit?

**Comment by matkoniecz** [comment]
Yes. But do not waste to much time on that, I now remember a previous mysterious toast-related bug that showed up only on my phone.

See https://github.com/MarcusWolschon/osmeditor4android/issues/641#issuecomment-352473640

**Comment by althio** [comment]
> It is not obvious that sign circle is a textbox.

+1!

Some hint would be appreciated. Any of:
- focus on input text box
- some characters ( __ or ? ), maybe greyed

**Comment by westnordost** [comment]
Cannot reproduce, the toast shows for me. Seems to be an issue of your smartphone, perhaps you do not get toasts at all.
@althio 's suggestion is good though, it should be possible to focus the input field in order to make the blinking cursor appear.
