### ISSUE TITLE
Support for building=terrace

### ISSUE THREAD

**Issue by 4tXJ7f** [westnordost/StreetComplete#1157]
In my neighborhood, there are a lot of row houses with a single house number, so each row house is mapped as one building. I couldn't find the terrace type in the menu of building types. It would be great if that option could be added (or was it omitted deliberately?).

**Comment by rugk** [comment]
OP says each house is mapped separatly, so selecting "row house" would thus be wrong. You may rather select just house.

However op also mentioned this as a osm tag, so let's look for that tag.

**Comment by 4tXJ7f** [comment]
> It's there, it is called "row house", in the residential category. See this overview, it's the 5th from the top.

Ah, I didn't realize that choosing residential opens another menu. This works for me, thanks a lot.

> Though, note that there is a common misconception regarding row houses: The tag is supposed to be used only if the building outline includes the whole row of houses, not for each and every house within such a row (For that, you'd use building=house.)

> OP says each house is mapped separatly, so selecting "row house" would thus be wrong. You may rather select just house.

Sorry, I wasn't very clear: Each outline corresponds to a whole row of houses (and they all have one house number), so it seems like the tag should apply.
