### ISSUE TITLE
Smoother quest redraw

### ISSUE THREAD

**Issue by lenod** [westnordost/StreetComplete#1159]
On completing a quest, all the quest icons are cleared and rendered again. On my phone (mid-range, moto G4), this takes almost a second to happen. 
This doesn't seem like much, but for quests like building_level, this makes me walk at snail speed if I want to be able to fill a full street of 20 houses all with two levels before I reach the next street/quest.

The current solution seems to be:
* clearQuests
* updateView (add the new quests layout on the layer)

Since it doesn't that updateView can be done faster, here is a possible solution (not sure about the feasibility):
* clear the solved quest
* update the new quests layout on a new, invisible layer
* clear the old layer
* reveal the new layer

In other terms, there could be two layers, alternating in turn from below the map to above the map.
My guess is that making the layer visible is faster than rendering all the quests icons one by one.

Such a solution would allow to select an "old-view quest" during the rendering time.

**Comment by westnordost** [comment]
Yes, it is the same with my phone, about one second. The addition of the house-quest makes everything really slow, because there are just so many of them.
However, I do not want to spend time and add code complexity to workaround deficiencies in the map rendering library.

Also, I tested StreetComplete recently, and I think the auto-opening of the next quest really doesn't feel good, even if the animation was smooth, so I am removing this feature again.

**Comment by rugk** [comment]
Wooah… this is an exact duplicate of https://github.com/westnordost/StreetComplete/issues/947

And quoting myself from some months ago:
> BTW I would even go so far to revert the behavior/disable it.

There, you did not want to do this, and now you…
I guess, you've just changed your opinion. :wink: 

Personally, I am not sure I would advocate for removing it again. Maybe I've accustomed myself to it (which is not good, if you want to evaluate the [first user] UX, of course).

**Comment by lenod** [comment]
@westnordost: I understand!
@rugk: I'm not sure this is related to #947. I'm only talking about the way quests are rendered, not selected.

**Comment by rugk** [comment]
Yeah, I basically just referred to
> Also, I tested StreetComplete recently, and I think the auto-opening of the next quest really doesn't feel good, even if the animation was smooth, so I am removing this feature again.

Sorry, your issue indeed is a valid one, but well known. 
I guess it is a dupe of https://github.com/westnordost/StreetComplete/issues/724.
