### ISSUE TITLE
Suggestion. Other answers - share location

### ISSUE THREAD

**Issue by rindlerblabla** [westnordost/StreetComplete#1160]
Sometimes (for me quite often) I would like to add other details than what's being asked, want to fix an issue directly (e.g. cut a highway where there are different maxspeeds along the osm way, change the name/type of amenity, remove a building which doesn't exist). 

This is obviously out of the scope for StreetComplete and I think it's clumsy to create notes all the time. An idea is to have the possibility to share the location, and then you can open the exact location in e.g. vespucci to fix the issues immediately. Know that it's possible to find your position in vespucci as well but this would be a smoother solution.

What do you think?

**Comment by ENT8R** [comment]
Sounds like a duplicate of #190

**Comment by rindlerblabla** [comment]
Yepp, didn't find it when I searched for similar ideas. Thanks.
