### ISSUE TITLE
"Leave note instead" should open in bottom sheet

### ISSUE THREAD

**Issue by westnordost** [westnordost/StreetComplete#1163]
**Use case**
One reason for leaving a note instead of answering the quest is because there is something wrong with the shown geometry of the element:
- either an answer wouldn't apply on the whole way
- or the geometry is wrong
- or the geometry belongs to another geometry (i.e. in case of buildings)

In these cases, one would want to review the element geometry while writing. For example:
- "the road is only a oneway south-west of crossing with Bakerstreet"
- "the road does not make a turn here, it ends and a footway continues NE"
- "this is not a building but just a building part of the office building to the SE"

**Proposed Solution**
Show the "Leave a note instead" dialog in the bottom sheet instead of a dialog.

**Comment by rugk** [comment]
Personally, I would not prefer it for your described use case, but actually just for design/stylistic reasons.

However, I just cannot imagine how this may go together with https://github.com/westnordost/StreetComplete/pull/1158 very well.
