### ISSUE TITLE
Zoom to previous zoom level after quest does not work if fixed to user position

### ISSUE THREAD

**Issue by pkoby** [westnordost/StreetComplete#1166]
The new feature returning the map to the zoom it was at before selecting a quest works great. However, if the geolocation button is enabled and the map is locked to user position, it does not seem to work at all. In this case, the map returns to the default zoom.

Video shows issue:
https://www.youtube.com/watch?v=RWVIe5w4aEk

**Comment by westnordost** [comment]
Hmm, is this a tablet? I did not test yet how the layout looks on tablets.

**Comment by pkoby** [comment]
It is a tablet (and some layout stuff is a little funny, but the GPS is better than my phone), but my phone does the same thing.
