### ISSUE TITLE
Disable sound

### ISSUE THREAD

**Issue by HolgerJeromin** [westnordost/StreetComplete#1167]
Wahh, sound in beta 7 :)

Please allow disabling it

**Comment by ENT8R** [comment]
Can't you do this with your phone's default settings? Is it really needed to have an extra setting in this app?

**Comment by westnordost** [comment]
Well, mute the sound then. I don't see a problem, after all, each button click also emits a "tick" sound by Android default.

Am 21. August 2018 15:56:43 MESZ schrieb ENT8R <notifications@github.com>:
>Can't you do this with your phone's default settings? Is it really
>needed to have an extra setting in this app?

**Comment by rugk** [comment]
> each button click also emits a "tick" sound by Android default.

And thankfully you can disable this. Same as the annoying keyboard sounds in Android.

It's just many people won't like them, and I have not tried the beta yet, but please include a sound option, in any case. You cannot mute your phone, because you may want to hear other things (music, in-view video, etc.) while using StreetComplete or after having used it.

**Comment by westnordost** [comment]
Let people speak for themselves, rugk.

**Comment by westnordost** [comment]
Anyway, it is not planned to implement such an option.

**Comment by iandees** [comment]
I would appreciate an option to disable sound completely in the app.

This may be a separate issue: My phone's media volume is muted and the app is still making noises. It looks like you're emitting sound in the "ring" channel, which is unintuitive.

**Comment by rugk** [comment]
@iandees Maybe do open a new issue, that looks like a bug.

**Comment by matkoniecz** [comment]
From my side: while sound and visual effect provides a great feedback that something is happening sounds is quite annoying.

**Comment by westnordost** [comment]
@iandees Hmm, the app uses the `STREAM_NOTIFICATION` to play the sound effects. There is not that much documentation on what streams are to be used for which class of sounds. Notification sounded the to be the right thing...

What do you think which stream should I use for sound effects? It should probably the same stream as for "click" sounds of buttons and so on, not sure which this is - I thought it would be notification.

```
    /** Used to identify the default audio stream volume */
    public static final int STREAM_DEFAULT = -1;
    /** Used to identify the volume of audio streams for phone calls */
    public static final int STREAM_VOICE_CALL = 0;
    /** Used to identify the volume of audio streams for system sounds */
    public static final int STREAM_SYSTEM = 1;
    /** Used to identify the volume of audio streams for the phone ring and message alerts */
    public static final int STREAM_RING = 2;
    /** Used to identify the volume of audio streams for music playback */
    public static final int STREAM_MUSIC = 3;
    /** Used to identify the volume of audio streams for alarms */
    public static final int STREAM_ALARM = 4;
    /** Used to identify the volume of audio streams for notifications */
    public static final int STREAM_NOTIFICATION = 5;
    /** Used to identify the volume of audio streams for phone calls when connected on bluetooth */
    public static final int STREAM_BLUETOOTH_SCO = 6;
    /** Used to identify the volume of audio streams for enforced system sounds in certain
     * countries (e.g camera in Japan) */
    public static final int STREAM_SYSTEM_ENFORCED = 7;
    /** Used to identify the volume of audio streams for DTMF tones */
    public static final int STREAM_DTMF = 8;
    /** Used to identify the volume of audio streams exclusively transmitted through the
     *  speaker (TTS) of the device */
    public static final int STREAM_TTS = 9;
    /** Used to identify the volume of audio streams for accessibility prompts */
    public static final int STREAM_ACCESSIBILITY = 10;
```

**Comment by iandees** [comment]
I'm not entirely sure what the best stream is, either. At least in Android P, the default action on the volume up/down buttons on the device is to change the "media" volume, which I think is `STREAM_MUSIC`. Prior to Android P, the default on the buttons was to change the ringer volume, which is `STREAM_RING`.

Although it might be unintuitive, I think the most intuitive answer might be the music one.

**Comment by rugk** [comment]
So, I just tested your beta and well… when first solving a quest that "plop" sound is quite satisfying, but I can easily assume this get's annoying when you solve many quests.

But that's subjective, so let's make up a use case:
As a user of SC, I want to be able to disable the sound effects in SC, because I do not want to hear interrupting sounds in my music when I take a walk, like to listen to music and use SC at the same time.

**Comment by matkoniecz** [comment]
@rugk  That part was closed as WONTFIX. See

> Anyway, it is not planned to implement such an option.

You may disagree and try to convince him to change opinion but "is still not fixed/satisied" is not sufficient reason to reopen the issue given that the project owner decided against implementing this.

Personally, I am not a fan of sounds emitted by apps (except ones expected to do this like a music player) but I will try to block sounds on a system level first.

**Comment by matkoniecz** [comment]
In general issues may be closed because whatever was reported was fixed/changed or because it was decided that changing/fixing is not going to happen.

**Comment by rugk** [comment]
And yes, I don't agree. Especially, as now the same stream channel **as your music player** is used, this whole problem may just now become appearant. 
And no, I agree the music stream is the correct one, but one does not want to annoy people listening to music while using SC. Then they just stop using SC, so that is not what we might want.

As said, that's the whole use case that still stands and completly demonstrates the problem of apps emitting sounds that you cannot disable.

**Comment by RubenKelevra** [comment]
I don't get the issue: Disable "Touch Sounds" in the System settings disable all sounds of the App.

**Comment by rugk** [comment]
No need to revive this old issue, @RubenKelevra. AFAIK this has been fixed in https://github.com/westnordost/StreetComplete/issues/1187#issuecomment-418338091 or so, so the behaviour was changed.

**Comment by RubenKelevra** [comment]
@rugk I haven't revived it, it was mentioned in the ongoing [Microgrant for Map Maintenance with StreetComplete](https://wiki.openstreetmap.org/wiki/Microgrants/Microgrants_2020/Proposal/Map_Maintenance_with_StreetComplete) by 'skorbut'.
