### ISSUE TITLE
Bike lane quest "never shown in US", except that its supposed to be

### ISSUE THREAD

**Issue by gappleto97** [westnordost/StreetComplete#1169]
In the quest selection settings, bike lanes says "never shown in United States". Except several states are whitelisted, and I am in one of them.

This seems like a problem. Shouldn't it be more granular if there are some states where it is shown?

**Comment by gappleto97** [comment]
Looking more closely, the same is true of speed limits. I see that quest locally as well, though I am not sure that I am supposed to.

**Comment by westnordost** [comment]
Could you check if this is not merely a display error in that quest list but all is fine on the map?

Am 22. August 2018 07:41:23 MESZ schrieb Gabe Appleton <notifications@github.com>:
>Looking more closely, the same is true of speed limits. I see that
>quest locally as well, though I am not sure that I am supposed to.

**Comment by gappleto97** [comment]
Both the bike lane quest and speed limit quest are showing on the map in California. Specifically the Sacramento area.
