### ISSUE TITLE
bug: tomatoe vs tomato

### ISSUE THREAD

**Issue by goldfndr** [westnordost/StreetComplete#1171]
While looking at [the taginfo counts for StreetComplete](https://taginfo.openstreetmap.org/projects/streetcomplete#tags), sorted by count (click on Count column), I noticed that [the produce=tomatoe entry](https://taginfo.openstreetmap.org/tags/produce=tomatoe) had a pretty low count. This didn't strike me as too absurd, but then I thought to look at [the produce=tomato entry](https://taginfo.openstreetmap.org/tags/produce=tomato). It's 3 vs 7, which to me makes sense, since "tomatoe" is arguably a misspelling; it struck me as odd when I added it to the json but then I guessed that maybe there was some British spelling precedent for it and didn't look into it.

I took a look at the 3 tomatoe instances. Each of them was created by StreetComplete. I looked at 2 of the tomato instances, each was created by one of the editors listed in the osm.org Edit menu.

I looked for the British spelling of tomato and it looks like that's how it's spelled there; at the very least, [the english Wikipedia entry](https://en.wikipedia.org/wiki/Tomato) doesn't include "tomatoe" as an alternative spelling.

**Comment by rugk** [comment]
["Tomatoe" is indeed wrong.](https://www.wordnik.com/words/tomato)

**Comment by westnordost** [comment]
True. [Your call](https://github.com/rugk/crops-parser/blob/master/osmcrops.csv), @rugk

**Comment by rugk** [comment]
Oh, yeah, [indeed](https://github.com/rugk/crops-parser/pull/56).
