### ISSUE TITLE
Building-type quests for non-residential buildings offer only residential options

### ISSUE THREAD

**Issue by gjm11** [westnordost/StreetComplete#1177]
I'm using StreetComplete version 7.1 on Android 8.1. Many of the quests I am offered ask "What was this building constructed as?" and offer two options: "Detached house" and "Apartment building". The "other answers" available are "still being constructed", "multiple purposes", and "can't say". But many of these buildings are *not* residential buildings.

For a few of them I have selected "can't say" and left a note along the lines of "this is not a residential building". For at least one of them, this note was then resolved with a comment saying "This appears to be tagged correctly" -- see https://www.openstreetmap.org/note/1507229#map=19/52.28947/0.12685 -- which suggests that maybe SC is giving residential-only choices even when a building is marked in the OSM database as not residential. (The web UI tells me that the building is question has "amenity: library", which _sounds_ as if it indicates a non-residential building, but I am not at all an OSM expert.)

**Comment by westnordost** [comment]
Did you try to scroll down?

**Comment by gjm11** [comment]
Yow! I feel extremely stupid now. No, obviously I didn't try to scroll. D'oh!

The "obvious" way to make it more obvious that it might be worth looking for more content further down would be to ensure that the lowest visible item is only _partially_ visible. Having said that ... that's already being done for the road-surfaces quests, and I managed not to notice there either. In the face of sufficiently determined stupidity, there's not much you can do :-).

**Comment by rugk** [comment]
Maybe you can add an arrow pointing down (I'd say a grey one and maybe only for the first 5/6/7 or so quests the user tries out:

Somthing like this (examples [from slides.com](https://slides.com/kentcdodds/simply-react#/)), but only down arrow, of course:
![arrow](https://user-images.githubusercontent.com/11966684/44838847-82aa9500-ac3d-11e8-9e6c-57b7172a47ea.gif)

And for the first start you could display a toast message, if the user does not do anything for a while or so. (this is done by slides.com too, in a similar way)

**Comment by westnordost** [comment]
Hmm, I will think about something and test it out in the frame of the speech bubble redesign

**Comment by rugk** [comment]
Does "thinking" require a closed issue or did you already finish your thought and quickly implemented it. :stuck_out_tongue_winking_eye:
