### ISSUE TITLE
extend capacity quest for motorcycle_parking

### ISSUE THREAD

**Issue by HolgerJeromin** [westnordost/StreetComplete#1181]
Should be small enough to count.

New icons needed?

**Comment by matkoniecz** [comment]
I am unsure is it always possible to tag capacity for motorcycle parking, but in case that it is possible it should be fairly easy to make a PR for that.

But quest icon and motorcycle image would be needed for UI.

**Comment by westnordost** [comment]
![device-2018-12-02-165204](https://user-images.githubusercontent.com/4661658/49341790-a2919080-f652-11e8-8a64-b2951f4e8dab.png)
