### ISSUE TITLE
Allow hiding completed quests

### ISSUE THREAD

**Issue by gutsle** [westnordost/StreetComplete#1182]
This is such an obvious thing, I am confused it doesn't exist.
I have been adding building types in my neighborhood for a while now but all the quests still remain which makes it harder to figure out what else there is to do. Am I missing something?

**Comment by matkoniecz** [comment]
Completed quests should hide immediately. If it is not happening then something went horribly wrong.

Is it possible that your area has many buildings with unspecified type that were not handled so far? Are you sure that building where quest was solved is still appearing?

**Comment by gutsle** [comment]
Okay, maybe I should clarify. The quest marker changes to show my answers but the marker doesn't disappear...

**Comment by gutsle** [comment]
Bah. I'm an idiot. :)
The new marker is actually for a different quest and I just didn't get it. I thought at some point I clicked on one and got the same question again. Nevermind.
