### ISSUE TITLE
Upload button not really intuitive

### ISSUE THREAD

**Issue by ServusWorld** [westnordost/StreetComplete#1184]
**Use case**
I think the upload button does not really look like a button at the moment, rather like an label for the number next to it. Thus, it's not really self-explaining how to upload quests if auto-sync is off.

**Proposed Solution**
Making the button more button-like (shadow, other color etc.) maybe wouldn't really fit into the title bar.
Instead, at the first time using the app, a hint pointing on this button should explain what it does.
This hint could be repeated if many answers (e.g. more than 50) have accumulated in the local database to remind the user uploading them.

**Comment by rugk** [comment]
> it's not really self-explaining

I guess this is the reason why the latest beta, at least, shows a notice when you disable auto-upload.

As such, I think what you want is already implemented. It has auto-upload enabled by default and only when it gets disabled the auto-upload button is shown and a note is shown, so you know what to do.

**Comment by westnordost** [comment]
When you disable auto-sync int the settings, a dialog is shown that explains the button. Did you miss it?

Am 3. September 2018 13:05:05 MESZ schrieb ServusWorld <notifications@github.com>:
>**Use case**
>I think the upload button does not really look like a button at the
>moment, rather like an label for the number next to it. Thus, it's not
>really self-explaining how to upload quests if auto-sync is off.
>
>**Proposed Solution**
>Making the button more button-like (shadow, other color etc.) maybe
>wouldn't really fit into the title bar.
>Instead, at the first time using the app, a hint pointing on this
>button should explain what it does.
>This hint could be repeated if many answers (e.g. more than 50) have
>accumulated in the local database to remind the user uploading them.

**Comment by ServusWorld** [comment]
oh okay ... I guess I didn't see it because I had already disabled auto-upload when the dialog was established :)

**Comment by althio** [comment]
But what happen with a fresh install?

Is it like this?
- auto-upload: enabled by default
- no upload button
- OSM account: not logged in
- any dialog to ask to login, any button, any counter to warn about quests not uploading?

**Comment by ENT8R** [comment]
> any dialog to ask to login, any button, any counter to warn about quests not uploading?

If you are not authenticated (and the app can't upload the answers) it asks the user if he would like to log in... Everything else would make no sense 😄 The text of the dialog can be found [here](https://github.com/westnordost/StreetComplete/blob/0457f7f4d4e795ade3f302684ea2216c661a940e/app/src/main/res/values/strings.xml#L89). it says:

> You need to authorize with your OSM user account to publish your answers. Authorize now?

Did you never saw this dialog before?

**Comment by althio** [comment]
Great, I remember the dialog now, thank you @ENT8R
