### ISSUE TITLE
In earlier version SC was able to use it from car

### ISSUE THREAD

**Issue by Mannshoch** [westnordost/StreetComplete#1185]
Earlier I was able to use StreetComplete while driving car (I'm not the Driver). In the newest version it's not anymore possible. SC seems not able to load the map and also the Questions fast enougth.

**Comment by westnordost** [comment]
See #1172 - will be fixed in the next version.

Also,  @Mannshoch, the two quests that cause the performance problems are "housenumber" and even more so, "building type". If you turn them off, all is like before.
