### ISSUE TITLE
Accurancy circle translates into weird 3D shape

### ISSUE THREAD

**Issue by bebehei** [westnordost/StreetComplete#1188]
When tilting into 3D mode, the circle of accurancy appears to be actually a heart shaped figure.

**How to Reproduce**

1. Switch to your location. It should be a bit inaccurate.
1. Tilt into 3D Mode.
1. Tilt until your actual location is outside the shape.

**Versions affected**
Streetcomplete 7.1, Android (LinageOS) 7.1

----

Sorry for the amount of screenshots, but I guess these are describing quite good the actual problem.

![screenshot_20180905-144540](https://user-images.githubusercontent.com/2073458/45094211-f0adfb00-b11a-11e8-8280-7a0622820133.png)
![screenshot_20180905-144622](https://user-images.githubusercontent.com/2073458/45094213-f0adfb00-b11a-11e8-883e-624f7c7df164.png)
![screenshot_20180905-144631](https://user-images.githubusercontent.com/2073458/45094214-f0adfb00-b11a-11e8-992c-629e55e2edbb.png)

**Comment by westnordost** [comment]
This is fixed for the next version

**Comment by goldfndr** [comment]
This is a duplicate of #833.
