### ISSUE TITLE
street names missing on Android 4.4.4

### ISSUE THREAD

**Issue by vmiklos** [westnordost/StreetComplete#119]
Hi,

I'm testing StreetComplete on Android 4.4.4 / CM11.

The street names are missing on the map. It looks like this:

https://farm4.staticflickr.com/3686/33822040631_5d52a8dc4b_o.png

It's not impossible to use the map with this, but it's certainly challenging. :-)

Thanks,

Miklos

**Comment by westnordost** [comment]
Hi Miklos

Which version of StreetComplete are you using?

**Comment by vmiklos** [comment]
Hmm, really good question. :-) I installed from the play store 1-2 weeks ago, but now that you asked, I updated to the latest one (0.7). This also means I forgot to check the version number before updating. :-(

However, it turns out 0.7 is a bit more problematic on Android 4.4.4; now some kind of atlas is flickering on top of the area which is shown as the current location. ;-) It looks like this:

https://farm4.staticflickr.com/3931/33831648441_bc5681f825_o.png

The small icons are not visible all the time, they are shown and hidden like 4 times in a second or so. Sadly that makes the usage quite problematic. If that is of interest, I can try to bisect which commit started to have this problem. (I haven't tried building from source so far, but I assume it should not be too hard. ;-) )

**Comment by westnordost** [comment]
Haha, what...! :-D What you see there is the icon sheet used for the markers.

What introduced it must have been the upgrade from tangram-es version 0.5.1 to 0.6.0. You can confirm it if you like, that might help to locate the bug.
If you can build your own versions anyway, I suggest you revert the tangram version back to 0.5.1 in the gradle file until it is fixed upstream. You will have the missing street names again, but 0.7 contains many other bugfixes.

**Comment by westnordost** [comment]
Could you also state which Android device you are using, just in case this helps to find the bug?

**Comment by vmiklos** [comment]
I'll give that a try. :-)

In the meantime, it's a Samsung GT-I9195.

**Comment by vmiklos** [comment]
Yes, reverting ca1a86e6faadde2ee7af5a171c0a36fb147f7107 fixes the strange icon problem visible on the second screenshot. There are still no street names, though.

**Comment by SansPseudoFix** [comment]
Oh, I have the exact same bug than @vmiklos 😆 

To be clear: I already had streets no-name issue with version 0.5 (but didn't notice it was a bug actually), and now, with 0.7, I have this icons sheet (pretty fun at first, but it's hard to use :P )

My phone: Moto G (Falcon) 4.4.4. I will go back to 0.5 though.

**Comment by westnordost** [comment]
I'll close this bug in favour of #130, since the street names should show now and the "flickering sheet" is another bug.

**Comment by vmiklos** [comment]
Uhm, what do you mean by fixed? I just pulled, keeping my local revert of ca1a86e, executed `./gradlew installDebug` and the street names are still missing. Do you remember which commit is supposed to fix this? I tested the master branch if that counts. Thanks! :-)

**Comment by westnordost** [comment]
That the street names don't show was fixed with ca1a86e.

This introduced the other bug you describe a few posts up.
This bug was now reported again in #130. Rather than closing #130 as duplicate, I closed this one because it describes the problem right in the title. One bug, one ticket.

On 20 April 2017 10:40:45 CEST, Miklos Vajna <notifications@github.com> wrote:
>Uhm, what do you mean by fixed? I just pulled, keeping my local revert
>of ca1a86e, executed `./gradlew installDebug` and the street names are
>still missing. Do you remember which commit is supposed to fix this? I
>tested the master branch if that counts. Thanks! :-)
>
>-- 
>You are receiving this because you modified the open/close state.
>Reply to this email directly or view it on GitHub:
>https://github.com/westnordost/StreetComplete/issues/119#issuecomment-295636305

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by westnordost** [comment]
(so as long as it is not fixed upstream in tangram-es, it's either no street names or flickering icons for Android 4.4 users)

On 20 April 2017 10:40:45 CEST, Miklos Vajna <notifications@github.com> wrote:
>Uhm, what do you mean by fixed? I just pulled, keeping my local revert
>of ca1a86e, executed `./gradlew installDebug` and the street names are
>still missing. Do you remember which commit is supposed to fix this? I
>tested the master branch if that counts. Thanks! :-)
>
>-- 
>You are receiving this because you modified the open/close state.
>Reply to this email directly or view it on GitHub:
>https://github.com/westnordost/StreetComplete/issues/119#issuecomment-295636305

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by vmiklos** [comment]
> One bug, one ticket.

Absolutely! :-) I see now, I wasn't aware it was exactly the missing street names thing that triggered the update of tangram-es.

**Comment by hjanetzek** [comment]
@vmiklos thanks for the report! There was definitely an issue with finding system fallback fonts on pre Lollipop Android - Should be fixed with the next release :)
