### ISSUE TITLE
black squares instead of quest icons / schwarze Quadrate anstelle von Aufgabensymbolen

### ISSUE THREAD

**Issue by Katzenstreu** [westnordost/StreetComplete#1192]
Hello,

since a lot of versions I can't see the icons of the quests. Instead the icons I am seeing black squares. Only a reboot is solving this problem temporally. See attachment. Version 7.1.

Hallo, 

seit vielen Versionen kann ich die Symbole der Aufgaben nicht sehen. Nur ein Neustart hilft übergangsweise. Anstelle der Aufgaben werden schwarze Quadrate angezeigt. Siehe Anhang.

Danke, thanks, 
Tim
![screenshot_street complete_20180909-150735](https://user-images.githubusercontent.com/1107883/45264906-223d0400-b444-11e8-8182-95bc795ba95e.png)

**Comment by ENT8R** [comment]
As this is a duplicate, you might close this issue...
