### ISSUE TITLE
Undo of Housenumber quest doesn't result in quest reappearing

### ISSUE THREAD

**Issue by siduenho** [westnordost/StreetComplete#1194]
Hi,

I think this may be related to #849.

When I answer the Housenumber quest. Example to 49, but should really be 49b. So I click on undo. After that the quest does not reappear.
It doesn't even reappear after I invalidate the quest cache and search again for quests.

Steps to reproduce:
1. Answer Housenumber quest.
![screenshot_20180913-142557](https://user-images.githubusercontent.com/5895949/45489001-64778580-b763-11e8-888e-ea8393391922.png)

2. Click on undo.
![screenshot_20180913-142620](https://user-images.githubusercontent.com/5895949/45489021-6fcab100-b763-11e8-8bba-3c2e415ded68.png)

3. Housenumber quest doesn't reappear.
![screenshot_20180913-142628](https://user-images.githubusercontent.com/5895949/45489127-bd471e00-b763-11e8-98f6-a0c24d87b14d.png)

4. Invalidate quest cache via settings.
5. Search for quests again.
6. Housenumber quest doesn't reappear.
![screenshot_20180913-142628](https://user-images.githubusercontent.com/5895949/45489138-c20bd200-b763-11e8-9518-8e94fb45aff0.png)

Settings:
Version 7.1 stable.
Auto Sync on.
Selected quests is standard.

**Comment by siduenho** [comment]
When using manual sync mode, the undo feature works as expected.

**Comment by ENT8R** [comment]
> I think this may be related to #849.

No, this is not related to this issue. @westnordost says there: 

> Because for certain quest types, this feature is disabled. Namely, for cycleway and housenumber quests, otherwise it should work.

As the housenumber quest depends on some post-processing on the client-side, this can't be undone that easily...

> It doesn't even reappear after I invalidate the quest cache and search again for quests.

BTW: it is often pretty helpful to provide an exact link to the location... So we can also check whether the data is already uploaded to the server or not... In this case this might be https://www.openstreetmap.org/way/338487055/history is that true?

---

@rugk maybe this should be added to the FAQ?

**Comment by siduenho** [comment]
Okay I'm sorry. The link to the node you provided is correct.
As far as I can see, the undo did work.

So if I understood correctly, only the reappearance of the quest is disabled. But as mentioned in #849, "another overpass query (= downloading the area anew)" should do the trick, right? Is this the invalidation of the quest cache or something else?
Because I did the invalidation without any effect.

It is actually pretty sad, that the reappearance doesn't work. Because I had the problem that I needed to undo something that happened like 3 Housenumber quests ago. So I had to blindly undo everything because I was unable to see anything on the map or read it inside the undo description.

It would be very helpful if
A) there is a note when undoing a Housenumber quest, that it may not be visible inside the map

B) the undo text contains the entered Housenumber (so you know what you will undo and can write it down somewhere).

C) there is somehow a way to make the quest visible again. This could be something to add as a note inside the undo of the housenumber.

D) see the feature in #748. But this would only be usable if the entered Housenumber would be visible somewhere.

**Comment by ENT8R** [comment]
> Because I did the invalidation without any effect.

You need to invalidate the quest cache and after that you need to **redownload** all quests in your area. Are you sure you pressed the button more than once?

> B) the undo text contains the entered Housenumber (so you know what you will undo and can write it down somewhere).

Should be covered with #748

**Comment by siduenho** [comment]
Okay I've done it multiple times. Settings - Invalidate quest cache (tried pressing it multiple times). Then all quests are gone.
If I do nothing, they will automatically reappear after a few seconds (Note that this is far away from my current GPS position).

If I click on "search here for quests" it will load everything but the housenumber quest won't reappear.

Even closing the app instantly after the invalidate doesn't work.

**Comment by westnordost** [comment]
> (tried pressing it multiple times). 

Really now? Come on...! But did you also read the dialog that pops up when the clicking on it? It explains how the invalidation works.

Anyway, I do not think this is a real bug here, but the logs will show what the app is doing.
1. install and start [CatLog](https://play.google.com/store/apps/details?id=com.nolanlawson.logcat) or similar
2. in StreetComplete, go to settings and invalidate quest cache.
3. Go back to the map, wait for the downoad to finish.
3. (If you turned auto-sync off, press "download quests here" (it should start automatically if auto-sync is on))
4. Go to CatLog, filter the log by `StreetComplete` and post it here.

**Comment by rugk** [comment]
> @rugk maybe this should be added to the FAQ?

Done: https://wiki.openstreetmap.org/wiki/StreetComplete/FAQ#Why_does_not_the_quest_show_up_again.2C_when_I_undo_it.3F
I hope that covers it.
