### ISSUE TITLE
"Scan for quests here" doesn't seem to apply quest selection settings

### ISSUE THREAD

**Issue by red-black-bonsai** [westnordost/StreetComplete#1195]
Recently tried to survey here
https://www.openstreetmap.org/#map=19/48.1955/16.34014
I've got the surface quest deselected in my settings. However, after downloading new quests with "Scan for quests here", I get lots of surface quests.

My expectation would be that the normal quest filters are applied also when downloading new quests with "Scan for quests here".

**How to Reproduce**
- Deactivate surface quests in settings
- Go here: https://www.openstreetmap.org/#map=19/48.1955/16.34014
- Download new quests
- Observe lots of surface quests?

**Versions affected**
StreetComplete version 7.1 from f-droid
LineageOS 14.1

**Comment by westnordost** [comment]
Which one did you deselect? The yellow or the blue one? And which do appear, yellow or blue?

**Comment by red-black-bonsai** [comment]
Aaah, apologies! Your suspicion is right, of course - I deselected the yellow one and got the blue one. 

Would it be possible to put the quests with similar icons next to each other in the settings list so that it's immediately obvious that there are more than one? (completed road/building, religion, parking, and surface)?

**Comment by westnordost** [comment]
No it wouldn't because the quests are sorted by priority. The priority decides in which order the quests are downloaded and which quest is displayed when there are several at the ~same position.
You can also change the order by long-pressing on an item.

**Comment by rugk** [comment]
> similar icons next to each other in the settings list so that it's immediately obvious that there are more than one

Just FYI, this is the way I try to sort the quest in https://wiki.openstreetmap.org/wiki/StreetComplete/Quests. But the wiki page is just for informative purposes.
