### ISSUE TITLE
Reword buttons for yes/no (toilet/parking fee, constructions) quests

### ISSUE THREAD

**Issue by rugk** [westnordost/StreetComplete#1197]
**Use case**
When I solve the toilet fee quest, I want a clear description of the buttons, so I do not accidentally press the wrong button.

The problem is I cannot remember that question and also don't want to read it each time. The reason is it can be easily asked for that in two ways, i.e. "Is it free?" and "Does it cost money?".

**Proposed Solution**
As the usability problem of this is quite well known in the user/office programs space, i.e. "Do you want to save this file? Yes/No." and solved there; I would propose the same solution: Rename the buttons to "Free"/"Not-free" or so.

**Comment by matkoniecz** [comment]
> "Free"/"Not-free"

Free/Paid?

**Comment by westnordost** [comment]
Makes sense

**Comment by westnordost** [comment]
Also for the other yes/no quests maybe?

**Comment by rugk** [comment]
Possibly, however this was the one, where I noticed it most/first.
I'd say this is due to the ambiguity on how the question can be phrased, i.e.:
> The reason is it can be easily asked for that in two ways, i.e. "Is it free?" and "Does it cost money?".

This problem does e.g. not exist (or is, at least, not so big :wink:) for the "Does XY have Something or not?", because nobody would does "Does XY _not_ exist?". (possibly subject to exceptions, of course.)

**Comment by westnordost** [comment]
Suggestions for other yes/no answer labels welcome, if possible without changing the question:
- Bench Backrest
- Oneway
- Tactile Paving
- Lit
- Diet type: yes/no/only
- wheelchair

**Comment by westnordost** [comment]
So, it would be helpful if you looked into how the questions for these is currently phrased and whether the yes/no buttons could and should have a different label based on that.

**Comment by rugk** [comment]
Bench: do not change, as explained above, it's the "XY has feature" quest
One way: also obvious IMHO
Tactile: no, "has feature" quest
Lit: also feature
Diet: possibly yes, might be a good idea
Wheelchair: also obvious IMHO, it's a "property quest" 

Note that where I state "no" I guess it won't hurt if it is phrased differently, but if it has some advantages, e.g. uses more space or so, I'd just say it's not necessary.

**Comment by goldfndr** [comment]
I propose the following:

* One-way/Two-way
* Lit/Dark
* Accessible/Hostile

That last one might be a *bit* strong. But I don't know any wheelchair users to interview.

**Comment by rugk** [comment]
"Dark" sounds a bit strange to me (especially when answering this not at night). 
I don't know whether the term "two-way" is obvious and think it is hard to translate, e.g. in German it can basically only translated as "not one-way" ("Keine Einbahnstraße", da "Zweibahnstraße" nicht existiert als Wort). And this is certainly not what we want, as a button description.

As such, generally, I'd be fine with only rewording the toilet-fee quests.

**Comment by matkoniecz** [comment]
> Lit/Dark

lit/unlit?

**Comment by rugk** [comment]
Hmm, possibly. At least the translation works in German ("unbeleuchtet"), but I'd think in some other languages it may get easily to something like "not lit" as there may not be a special word/prefix for negating that adjective in that language.

**Comment by westnordost** [comment]
And how to name the buttons?
(Btw I consider toilet fee buttons now as will not fix because of my earlier comment)

**Comment by rugk** [comment]
Okay, toilet: maybe "gratis/paid"? (Yes, "gratis" is a real English word. Don't know ho0w popular it is, though.) Otherwise I'd say "free" is not so bad, as you can easily see what it means when it is presented with "paid" as the other option and are thus unlikely to mistake/overread it. 

constructions:
Hard, as "in construction"/"being built" is a bit long…
Maybe one step could be to unify the construction question though: Either always ask "is XY built?" or "Is XY completed?".

**Comment by westnordost** [comment]
> Maybe one step could be to unify the construction question though: Either always ask "is XY built?" or "Is XY completed?".

This is already the case. It always asks "Is ... completed?".

**Comment by rugk** [comment]
Okay, then I misread something… :unamused:

**Comment by rugk** [comment]
Another quest, where this applies: parking fee. Well… it's also a fee quest.😊

**Comment by westnordost** [comment]
Well, I am going to close this. See https://github.com/westnordost/StreetComplete/issues/1197#issuecomment-422516321

Gratis is not a good word. Also, in many languages, fee/paid are not so short as in English.

**Comment by rugk** [comment]
I'd still think "free/paid" is totally clear and there is no big chance to confuse it. What's most important, however, is, that it is certainly **better than themselve current button labels**, because this yes/no is certainly much more confusing.

As such, please reconsider this issue.
