### ISSUE TITLE
[newest beta-version] Crash when anwsering a quest

### ISSUE THREAD

**Issue by ServusWorld** [westnordost/StreetComplete#1198]
**How to Reproduce**
Simply select a random quest and give any answer. On my phone, this leads to a crash (!)
(I sent an Android crash report after that happened.)

**Versions affected**
Android version: 3.10.61-12219145 (hope that's the wanted number)
SC version: 8.0-beta1

**Comment by rugk** [comment]
> hope that's the wanted number

Hu? No… Just state your Android version, i.e. Marshmallow, Oreo etc.

**Comment by westnordost** [comment]
Ypu have location off, right?

Am 17. September 2018 18:26:32 MESZ schrieb ServusWorld <notifications@github.com>:
>**How to Reproduce**
>Simply select a random quest and give any answer. On my phone, this
>leads to a crash (!)
>(I sent an Android crash report after that happened.)
>
>**Versions affected**
>Android version: 3.10.61-12219145 (hope that's the wanted number)
>SC version: 8.0-beta1

**Comment by ServusWorld** [comment]
No, I'm Samsung A3 ...
is that intended that the app crashes just because location is off?

**Comment by westnordost** [comment]
Okay weird, the only crash reports regarding this I guess are from that one user with that one device. Or the Google Play console is bugged.

Anyway, what kind of question is this? Of course not! I already fixed it as well

**Comment by ServusWorld** [comment]
Yes of course ...
I just wondered why the issue has been closed :)

**Comment by Binnette** [comment]
Hi @westnordost, since i'm also affected and i'm in the "beta program" in play store...
I'm gonna compile latest master in order to continue using SC without crash. :smiley: 

BTW, will you release a 8.0-beta2 soon ? :cat2:

**Comment by Binnette** [comment]
Of course, but i like to turn it off, to make my battery last longer :battery:
