### ISSUE TITLE
Has a bank an ATM?

### ISSUE THREAD

**Issue by Spanholz** [westnordost/StreetComplete#120]
Hey,

thanks for the great app! I have an idea for a new quest: I often see a bank mapped without an information if there is an ATM. Would be nice to add ATMs to banking houses.

**Comment by HolgerJeromin** [comment]
IMO adding atm=yes to the amenity=bank is not the way to go in the long run. They have at least other opening_hours= and wheelchair= attributes so they should be mapped as separate nodes.

**Comment by Spanholz** [comment]
Yeah I agree with you that they should be mapped seperately. But I thought it would be nice to get a check if there is an ATM near it. [For example all those four banks](http://www.flosm.de/en/poimap.html?lat=52.4428003&lon=13.2932397&r=647.86612&st=0&sw=atm,bank) have an ATM, but none of it is mapped seperately. Maybe the app can make notes or something like that. It was just a thought, maybe someone has a better idea.

**Comment by HolgerJeromin** [comment]
Sadly adding a node at the correct place is out of scope of this app... 8-/

**Comment by westnordost** [comment]
Yes. I can only ask, "does this bank have an ATM", but it is going to be a bit tricky (to find out) if the ATM is already mapped separately.
So, I think I am going to pass on this one.

**Comment by rugk** [comment]
I think the situation (or the knowledge) has changed since then, does not it? You can use bounding boxes to check whether there is an ATM inside of an area.
And it could also be a disabled-by-default indoor quest (ref https://github.com/westnordost/StreetComplete/issues/558).
