### ISSUE TITLE
Rename all fastlane directories to a country specific code

### ISSUE THREAD

**Issue by Poussinou** [westnordost/StreetComplete#1200]
Hi,

Would it be possible to rename the directories from fastlane to a country specific code? That's the only solution to make it works. We had a discussion about this [here](https://gitlab.com/fdroid/fdroidserver/issues/357#note_73054098)

For example, `en` directory should be renamed to `en-US` (this one will be the reference, so this is where the screenshots should be, and that's already the case 😃 ) or `fr` to `fr-FR`. You could have a look at [this repo](https://github.com/k3b/ToGoZip/tree/master/fastlane/metadata/android) and [this Wikipédia page](https://en.wikipedia.org/wiki/ISO_3166-2) to know the right name of the directory.

This enhancements would allow F-Droid users to have some nice screenshots the next time you tag a new release :)

Ask if you have any question 👍

**Comment by westnordost** [comment]
Hmm, wouldn't it be better if it was implemented on F-Droid side to also understand and fall back to language-only directory names?

What about if the F-Droid user's locale is on `es-AR` but this (or any other project) only has a directory named `es-ES`?

**Comment by westnordost** [comment]
I do not understand what what fastlane supports has to do with this. I thought F-Droid is just using the **directory structure** as generated by fastlane or alternatively the **directory structure** as generated by Triple-T.

The directories created by fastlane also are quite inconsistent, some are of the format `de-DE`, some of the format `ru`. fastlane is geared towards the (Apple) App Store which only supports very few countries - those in which they sell iPhones. A limitation to such few countries is completely unnecessary for a FOSS project like F-Droid.

If the directory selection was handled by Android the same way localized resources are handled by Android, then it wouldn't be a problem because it is perfectly fine to have e.g. a `strings.xml` for `es` and one for `es-AR`.

Can you perhaps point me to the code? I might create a PR to fix the directory selection.

**Comment by rugk** [comment]
Might this discussion not basically better be done in the FDroid issue tracker or so?

**Comment by Poussinou** [comment]
@westnordost Yes you're right, F-Droid just use the fastlane directory structure, but I though that keeping a directory structure that complies with the official Fastlane structure would allow you to use it everywhere (including the Google Play Store) and keep everything clean and simple, but as you want. And yes, other locals are inconsistent I agree with you.

Furthermore, as far as I can see, the screenshots are available trough the android client and the website with repos like [this one](https://gitlab.com/tom79/mastalab/tree/develop/fastlane/metadata/android/en-US/images/phoneScreenshots) who are using the "official" `en-US` local. I can't understand why it doesn't work with a simple `en` local. I'm sot sure anymore on how it works.

I couldn't find the right file where the fastlane metadata are handled in F-Droid repos. Maybe we should ask them, like rugk said.

**Comment by westnordost** [comment]
Ah, I thought you are from the F-Droid project. Well yes, it would make sense to open up a ticket there.

**Comment by Poussinou** [comment]
I contribute to the F-Droid project and I have some right access on 2 repos, but I do not consider myself as a core-team member, and I surely didn't wrote the python script that parse fastlane directories...

**Comment by westnordost** [comment]
So it is not the app itself who reads the fastlane directories but the server, I did not know that.

**Comment by Poussinou** [comment]
I think this is the server, but I'm not totally sure, since I wasn't involved in this new feature at all...

We really should ask, it'll be interesting. Do you want to open the Issue with all your questions by yourself, since you're more technical than me? I'm just a simple contributor, and I'm new to Android programming and things like Fastlane. Otherwise I'll do it.

PS : Sorry to bother you with all this and my inexperience.

**Comment by westnordost** [comment]
I think it is better if you opened a ticket because you have a better overview over the different projects within the F-Droid sphere.

**Comment by westnordost** [comment]
@Poussinou Did you open a ticket somewhere? If yes, can you paste the link here?

**Comment by westnordost** [comment]
@Poussinou ping

**Comment by westnordost** [comment]
I created an issue myself now
https://gitlab.com/fdroid/fdroidserver/issues/621

**Comment by westnordost** [comment]
And fixed in https://gitlab.com/fdroid/fdroidserver/merge_requests/611

While reading through the code, I also found out that the metadata is also searched for in `/metadata/`, so I changed it because it's shorter and I do not use fastlane.
