### ISSUE TITLE
Select / Unselect all in the quests selection

### ISSUE THREAD

**Issue by Phyks** [westnordost/StreetComplete#1203]
Hi,

**Use case**
Sometimes I only want to focus on a single quest and fill everything nearby (typically, if I fill while riding a bike, there is no point in having opening hours quest). I used to manually unselect (almost) everything in this case, but the number of quests is growing fast! :)

**Proposed Solution**
I have two solutions for this problem:

* The most simple one is probably to provide select / unselect all in quests selection, in addition to the "reset to default".
* The slightly more elaborate one (not sure if there is a real need for this one from users) would be to have profiles of quest selection, such as one could define their own list of quests to display in different situations and switch from one profile to another one easily.

Thanks!

**Comment by rugk** [comment]
Hmm, never had this use case. Even when riding by bike I just then ignore the quests I don't like  and the others are always shown due to high(er) priority.

However I can see profiles could be useful, but I don't think whether the effort is worth it.

**Comment by westnordost** [comment]
I do have this use case often when I have to test that one new quest type ;-)

**Comment by westnordost** [comment]
To solve this for your use case (you are using a specific form of transportation), the most reasonable thing would be to introduce profiles:
- in car/bus
- on bicycle
- on foot

But then, these profiles should not be hidden deep in the settings but at the same time I do not want to litter the main view with even more buttons.

**Comment by Phyks** [comment]
> Hmm, never had this use case. Even when riding by bike I just then ignore the quests I don't like and the others are always shown due to high(er) priority.

Oh, ok, this is another way of handling it, through priorities. My real world use case is that I'm currently mapping bicycle parkings nearby and I wanted StreetComplete to be kind of a companion app to show me where I should fill the bike capacity and the type of stands so that I can easily ride my bike there and complete the data :)


> To solve this for your use case (you are using a specific form of transportation), the most reasonable thing would be to introduce profiles:

This would truly be awesome quite often for me! I'd really enjoy such a feature. However, not sure if others have a similar need and then, if it's worth putting time and efforts in developing it (I don't know much about SC code, sadly :/).

A way to not clutter the main view might be to put it in the top right dropdown menu. Something like "Switch quest profile"? This has the disadvantage of not showing all the time what mode you are in (contrary to what OsmAnd do for instance) but will keep a simple interface without too many buttons.

**Comment by westnordost** [comment]
Yeah, also don't know if it is worth the effort and the additional UI. So for now I will rather not do it. Maybe I will add the "deselect all" option in the quest selection screen.

**Comment by Phyks** [comment]
> So for now I will rather not do it. Maybe I will add the "deselect all" option in the quest selection screen.

Definitely fine for now for my use case. "Deselect all" + "Reset defaults" (which is already there) should be fine! Thanks!

**Comment by rugk** [comment]
Okay, so this can be labelled as an "enhancement" at least? :smile: 

>  "Deselect all" + "Reset defaults"

Not really practical IMHO. I'd rather need a "reset before deselecting priorities" button, as otherwise I loose the custom priority too, with "reset defaults". I'd also loose the manually enabled quests, which are disabled by defaults.
 
IMHO yes, profiles are the way too goo, but whether these are really needed depends on how many quests will be added to SC in the future. :smile:

**Comment by rugk** [comment]
Anther question would be: Should profiles also save the priority (i.e. order) of the quests or only the enabled/disabled state? (I'd tend to favor the former.)

**Comment by westnordost** [comment]
Yes, only the former

**Comment by Phyks** [comment]
Thanks!

**Comment by georg-d** [comment]
For others landing here because they miss "select all": I thought I wanted this menu option and after reading related issues, I realized I do not want "select all" but quest presets (see #1654) because they are even quicker to switch between different "scenarios to use street complete" like train/foot or day/night or foot with/without time to stop and read signs. They are not only good to toggle on/off quests but also priority of quests and "undo" changes to quest settings.
