### ISSUE TITLE
Do not show quests for ways that are very long

### ISSUE THREAD

**Issue by mahdi1234** [westnordost/StreetComplete#1207]
Hi,

I know this is gonna be hard tackle, but to me SC is counter-productive in speed quests. This is for varios reasons:

- nodes for streets/roads are random, in cities quite often crossing-to-crossing but reality with speed limits is not that easy an SC asks very generic
- related to above quest never mentions go to the other side to check limit is same in opposite direction

While I like the app for tactile, opening hours etc I had to correct many wrong inputs for speeds already, not to mention "source" tag is not taken into into account by any navigation only explicit value.

Pleas try to provide app which gives some OSM-value, current speed quest is very questionable whether it really brings some value to real world.

**Comment by matkoniecz** [comment]
Do you know that you can disable quests in settings?

**Comment by rugk** [comment]
Okay, so you are speaking from the OSM site.

> I had to correct many wrong inputs for speeds already

Can you give us some concrete examples for that?

> not to mention "source" tag is not taken into into account by any navigation only explicit value.

Can you give any source for that statement or mention example navigation apps?

**Comment by mahdi1234** [comment]
Here's how quest is presented by the app

![screenshot_20180923-210833](https://user-images.githubusercontent.com/1097047/45931998-7680d180-bf76-11e8-8bd2-717071e2f342.png)

This is 2.5km https://www.openstreetmap.org/directions?engine=graphhopper_car&route=49.6328%2C16.3413%3B49.6528%2C16.3269#map=15/49.6429/16.3342 I don't think anyone can answer such question.

It's also typical in Austria/Czech republic there's 70km in the direction approaching village several hundreds meters ahead while other direction is country limit (I think this is the case here, but I have to map this area when I'm there again to match exactly those limit changes).

Also every crossing in Austria and most in Czech republic has some kind of 80/70 limit in direction approaching the junction outside the towns.

When I said I had to correct, it wasn't meant explicitly by SC, but in general (I correct things which I see when driving).

For the second question when I asked developers of Magic Earth https://play.google.com/store/apps/details?id=com.generalmagic.magicearth they confirmed not using source:maxspeed also from playing with https://play.google.com/store/apps/details?id=com.mapfactor.navigator and https://play.google.com/store/apps/details?id=com.mapswithme.maps.pro doesn't seem to be taken into account (unless implemented recently). I'm not sure about OSMand as I use it solely for hiking.

So in general I would very love to use source:maxspeed as it can help in situation like recently happen in France where overnight 90 went to 80 in rural areas (unless I'm mistaken), but reality is different.

Don't take me wrong SC can be really helpful in getting many missing details for varios POI's, but I think situation with ways is not that straightforward as giving one simple answer.

**Comment by mahdi1234** [comment]
SC also gives often quests like this i.e. street over junction(s) ...

![screenshot_20180923-214156](https://user-images.githubusercontent.com/1097047/45932244-cc0aad80-bf79-11e8-8b0e-c69d30f3b1af.png)

I've seen over more like crossing three or four streets, I guess this is based on how it's defined in OSM, but speed limits can vary.

**Comment by rugk** [comment]
Okay, so problem no. 2: IMHO this is not a problem of SC, but the routing tools. I have also no insight on how they do it, but that tag is properly documented in the wiki and that's how they should should use it. If they don't open issues in the corresponding repos or whatever they use.

**Comment by rugk** [comment]
Prolem no 1: Well, okay, i understand it now. So the issue is SC cannot split ways, and AFAIK the Overpass-API also does not allow to filter by length. As such, it just uses the length of the ways in OSM. And these vary much, AFAIK. Personally, however, I've never seen such long (multiple km's) ways.

**Comment by mahdi1234** [comment]
Yes, it's about splitting, but even short way can have 70/90 in either direction (or anything else).

Another issues is "Height" quest, it should be marked only part of a way where heigh limitation is applied, but SC takes way as defined thus whole way including connecting roads is marked as height limited which is incorrect.

**Comment by HolgerJeromin** [comment]
In short: all quests on ways have UX problems with "very long ways". Surface and lit come into my mind.

**Comment by westnordost** [comment]
So, maybe the app should not display quests for ways longer than X. What'd be a good X? (For starters, I'd choose it rather too long than too short)

Am 24. September 2018 08:34:49 MESZ schrieb Holger Jeromin <notifications@github.com>:
>In short: all quests on ways have UX problems with "very long ways".
>Surface and lit come into my mind.

**Comment by kayD** [comment]
I think it would be good if there was an additional option like "There are multiple speed limits in this part of the way. Leave a note for other users to split the way."

**Comment by westnordost** [comment]
But you can always leave a note

Am 24. September 2018 09:53:00 MESZ schrieb kayD <notifications@github.com>:
>I think it would be good if there was an additional option like "There
>are multiple speed limits in this part of the way. Leave a note for
>other users to split the way."

**Comment by matkoniecz** [comment]
Maybe add "max speed is changing in this road section" option leading to note creation with direction to explain where change happens?

**Comment by westnordost** [comment]
I'd rather not do that. But I will implement a max length of a way for it to be displayed as a quest. (Is this queryable via overpass?)

**Comment by althio** [comment]
> @westnordost 
I'd rather not do that. But I will implement a max length of a way for it to be displayed as a quest. (Is this queryable via overpass?)

length of way should be queryable: [see doc](https://wiki.openstreetmap.org/wiki/Overpass_API/Overpass_QL#Length) and [example](http://overpass-turbo.eu/s/tsJ).

**Comment by rugk** [comment]
Hmm… the example does not work in my browser. However, if it is possible I would also exclude very short ways (these are often annoying small connections between two other ways).

**Comment by matkoniecz** [comment]
> I  would also exclude very short ways

I see no reason to not collect data for them.

**Comment by rugk** [comment]
It annoys contributors without providing any or only a minor value for OSM.

**Comment by ENT8R** [comment]
But then some other mappers might say that SC creates "annoying detailed spots" (see the discussion at the German forum about this "issue" here: https://forum.openstreetmap.org/viewtopic.php?pid=707316#p707316)
I also see no reason to exclude ways which are too short. This is often very easy to answer as it is just a small piece of the road and you can directly determine the surface without walking up and down the whole street...

**Comment by matkoniecz** [comment]
> SC creates "annoying detailed spots"

Are they complaining that somebody else, not using SC, split roads in too many fragments?

**Comment by rugk** [comment]
Also think this discussion about these "detailed spots" does not really go anywhere. IMHO it is also not really related by excluding or including short ways in SC (which is what this issue is about) – the are a cause of the fundamental principles of SC and they may always be there, independent of whether these short ways are included or not. (though they may slightly increase the "problem" – if one sees it as such – but I'd say this is only marginally).

**Comment by goldfndr** [comment]
>Hmm… the example does not work in my browser.

@rugk Your "Data" tab is empty? Works for me.

**Comment by ENT8R** [comment]
And how is this related to this discussion?
