### ISSUE TITLE
Auto quest search does not lock manual search

### ISSUE THREAD

**Issue by rugk** [westnordost/StreetComplete#1209]
When the auto search triggers, it does not seem to "lock" the manual search. When you manually search, however, and directly afterwards (during the search) try to search again, a message appears saying a search is already running. (letting you confirm cancelling it) This does not happen, if the first query is an automatically triggered one (via going into a location with no quest).

**How to Reproduce**
1. Trigger an automatic quest search…
2. Tap on "Search for quests" to manually search for quests.

**Versions affected**
tested with SC v7.1 and LineageOS 14.1

**Comment by westnordost** [comment]
What do you mean, "lock".

**Comment by rugk** [comment]
This:
>  a message appears saying a search is already running. (letting you confirm cancelling it)

I could screenshot it, but I hope you know what I mean… :smile:

**Comment by matkoniecz** [comment]
It is a limitation of an overpass turbo. You must not run multiple queries at once.

**Comment by westnordost** [comment]
A auto search will simply not trigger while a manual search is running.

**Comment by rugk** [comment]
Uhh… but my issue was about the reverse, i.e. will the manual search be triggered when auto-search is running.

And you can see the auto-search is triggered by the shown notification.

**Comment by westnordost** [comment]
Yes, it will. You will not see a notification about canceling the previous search because you didn't start the previous search yourself.

**Comment by rugk** [comment]
Firstly I have no idea what answer of me you reply to with "Yes". I've not asked a yes/no question.

So can you explain the expected behavior again?

With the help of the progress indicator, here is my guess what happens:
1. Start automatic quest download. Notification is shown.
2. Progress bar starts. Trigger manual quest download.
3. _No cancel window appears_. Download seems to be automatically cancelled.

So is this expected? Knowing the cancel dialog, I guessed this was a bug.

**Comment by westnordost** [comment]
Correct. The user does not see the confirmation dialog about cancelling the previous search because he wasn't the one who started that previous search.

**Comment by rugk** [comment]
Hmm, yes, maybe it makes sense… So I'd close it.
