### ISSUE TITLE
"Single house" (deteched) is not obvious it's a residential building

### ISSUE THREAD

**Issue by rugk** [westnordost/StreetComplete#1210]
What's not obvious for me for the building type quest is whether – in the "fast" selection mode – the "single house" selection is a residential building or can e.g. also be a single house with a shop or so.

The description only explains it usually has a garden. This _usually_ is for a residential building where people are living, but may e.g. be the same for a restaurant or so.

**Comment by rindlerblabla** [comment]
Is it for detached? In that case I think it's a German translation issue that should be solved in poeditor.

The English description "free-standing single-family home" is translated to   "normalerweise mit Garten rundherum".

**Comment by matkoniecz** [comment]
This is a translation issue.

House is clearly residential - see https://en.wikipedia.org/wiki/House

**Comment by rugk** [comment]
Well… IMHO in German "house" can be any building for any purpose and does not have to be residential.

**Comment by matkoniecz** [comment]
What makes it a translation issue.

**Comment by matkoniecz** [comment]
Have you tried improving translation at Poeditor. (I am assuming that it is necessary, I may be wrong)?

**Comment by rugk** [comment]
I have not, otherwise I would not have opened this issue… :wink: 

So first I'd want to hear the feedback here on what needs to be improved or so. And as you also are not sure, as it seems… :wink:

**Comment by westnordost** [comment]
fixed (in POEditor)
