### ISSUE TITLE
Make the popup menu corners round too

### ISSUE THREAD

**Issue by ENT8R** [westnordost/StreetComplete#1211]
With the new redesign of the app a lot of corners were introduced (looks great BTW 👍). The only thing which didn't receive rounded corners is the popup menu of the action bar... Which is IMO a little bit inconsistent.

e.g. Google Chrome has these rounded corners too:
<img src="https://user-images.githubusercontent.com/25306497/45930736-0d905e00-bf64-11e8-88e8-c9129097f08c.png" width="300px">

**Comment by westnordost** [comment]
The style of the popup menu could be adapted as well, yeah

**Comment by westnordost** [comment]
Are you interested in doing this? In the end, it should just be a few lines of styling code in the themes.xml

**Comment by ENT8R** [comment]
Yes, I will try to do it...

**Comment by westnordost** [comment]
Did this quickly now by myself.

**Comment by ENT8R** [comment]
Thank you! :tada:
