### ISSUE TITLE
It shouldn't be possible to contribute to discussion of closed note

### ISSUE THREAD

**Issue by westnordost** [westnordost/StreetComplete#1213]
Apparently this note was only created because a user of StreetComplete wanted to contribute to a note discussion that had been closed in the meantime(?). Need to investigate:

https://www.openstreetmap.org/note/1533790#map=19/53.57992/9.94973&layers=N

**Comment by rugk** [comment]
No bug, user created note manually, as their second reply showed.

**Comment by westnordost** [comment]
Okay, I also checked the code and a comment added to a note discussion that has been closed in the meantime will automatically be dropped.
