### ISSUE TITLE
"OK" click on note creation only hides keyboard and needs to be clicked again

### ISSUE THREAD

**Issue by rugk** [westnordost/StreetComplete#1214]
When you confirm creating a custom note (in the bottom sheet) you have to click "OK" twice. For some reason… First click on "OK" hides the keyboard, second click creates note.

**How to Reproduce**
1. Create custom note, place it. Write some text.
2. Click "okay". -> Some seconds pass and finally keyboard disappears.
3. Click "okay" again. -> Note is created.

What should happen: One click should be enough to create note.

**Versions affected**
7.1, LineageOS 14.1, AOSP default keyboard

**Comment by westnordost** [comment]
This is not a bug but a feature.

**Comment by rugk** [comment]
Uuuh, but why? I can solve all other quests with a simple click on "OK". Also – if I remember correctly – even the ones where I enter data, i.e. the street name quest, but I have not checked that in th

**Comment by rugk** [comment]
Oh, if that is the reason, that would be a poor workaround for that… 🙁

Breaking UX for fixing an internal problem is likely not ideal.😁

**Comment by ENT8R** [comment]
> Breaking UX for fixing an internal problem

This is not really an internal problem at all! The problem is that if you are holding your phone in landscape mode to put in the note text, you likely don't see that the position of the marker changed while rotating the phone which leads to a wrong position of the submitted note. The "workaround" is to hide the keyboard on the first click so that the user can see the (new) position of the note.

**Comment by rugk** [comment]
Ah, BTW, I was holding my phone in portrait mode, not landscape…

**Comment by westnordost** [comment]
The user should still confirm the position of the note after writing it.

**Comment by rugk** [comment]
I think I've explained in enough detail, why I think so, which is what matters. I have to find some words to express disagreement, I'll try the edit the text a little though.

But let's better get on topic.
