### ISSUE TITLE
Mysterious text below some settings in v8.0

### ISSUE THREAD

**Issue by cyclingcat** [westnordost/StreetComplete#1215]
Since v8.0, some settings concerning quest selection display an additional text in a grey box below the setting's text: "Niemals in Europäische Union gezeigt" ("Never shown in European Union" or similar, see screenshot). This puzzles me, as I am located in Germany and currently see a lot of those quests which show this grey box. What's going wrong here?

![sc_settings](https://user-images.githubusercontent.com/32601012/46100945-ff904680-c1ca-11e8-8655-0611d35bc43a.jpg)

For testing purposes, I just reverted to v7.1 on one of my devices and these grey boxes never appeared since. (I have also never noticed it before.) Updated to v8.0 again and the grey boxes reappeared immediately.

The cycling cat

**Comment by westnordost** [comment]
Where did you focus your screen on when opening the settings?

**Comment by cyclingcat** [comment]
I don't want to disclose my home here publicly, but it's in the south of Germany, more than 100 km away from any border. The screen shows just my home and approx. 100 meters around. Let me know if you need the exact location, I will send it to you via e-mail.

**Comment by westnordost** [comment]
It would be better. But you can also scroll somewhere else and try there again.

**Comment by westnordost** [comment]
Also, are cycleway quests (etc) then not shown in your area?

**Comment by cyclingcat** [comment]
The cycleway quests are shown despite the grey box in the settings.

**Comment by cyclingcat** [comment]
Now it's getting even more mysterious: I scrolled around, just some kilometres away from my GPS location, looked into the settings, and the grey boxes are gone! Went back to the GPS location (by tapping on the button in the lower right corner): The boxes reappeared. Scrolled around just some metres: Boxes are still there. Scrolled around a little further away: Boxes are gone.

I will try to find a pattern behind all this.

**Comment by westnordost** [comment]
Perhaps you should send me the exact GPS position, it would be better. newton@westnordost.de

**Comment by cyclingcat** [comment]
It looks really random. Even when scrolling through Switzerland (no parts of other countries shown on the map), the box sometimes appears, containing the string "European Union" (!) or "ATLANTIS" (!!)

**Comment by matkoniecz** [comment]
@cyclingcat Please send/post one exact position where it happens. This way @westnordost will be able to check what happens.

BTW, Atlantis is easter egg that should appear when location is on ocean.

**Comment by westnordost** [comment]
Can reproduce. This is a bug in the countryboundaries library.... :-(

Introduced in this commit: https://github.com/westnordost/countryboundaries/commit/87eb02f3f59966d60a6d023a710f3e9e02ab707d

Apparently the winding number algorithm has some bug that (noone) knows about. Need to set a breakpoint and go through this step by step.

**Comment by westnordost** [comment]
The winding number algorithm is not from myself, I copied the code from its source. Apparently it is either inherently flawed in some way or another, or the polygons I am working with are somehow invalid (enough) for that algorithm to get confused.
If someone else wants to look into that, you are very welcome. The algorithm is as much as a black box to me than to anyone else. (Well, I understand its intention but apparently there is an edge case that is not accounted for)

**Comment by rugk** [comment]
So time for a "help wanted" tag?

**Comment by westnordost** [comment]
Found it. An integer overflow.

**Comment by ENT8R** [comment]
It seems like this issue caused some more problems: According to https://forum.openstreetmap.org/viewtopic.php?pid=718691#p718691 which mentions https://www.openstreetmap.org/changeset/63068614 there were some edits in Germany which set maxspeed:type=NL:urban in a city in Germany. And in the same changeset there were also some edits which added maxspeed:type=default:urban which makes absolutely no sense to me... Is this also caused by this issue? If yes, we should maybe block version 8.0 from uploading corrupted data?

**Comment by matkoniecz** [comment]
@ENT8R I think that data corruption may deserve a new issue.

**Comment by westnordost** [comment]
It's okay, I am subscribed to the whole project, inclusive all closed tickets. I added 8.0-beta1 and 8.0 to the block list, and will create a ticket to organize a repair/check of the wrong data now.
