### ISSUE TITLE
Give the user an option to fix the screen orientation

### ISSUE THREAD

**Issue by cyclingcat** [westnordost/StreetComplete#1217]
**Suggestion:**

 Give the user an option to fix the screen orientation in order to prevent unwanted screen rotation, independent from the corresponding global Android setting. Osmand, for example, lets the user explicitly choose between three possibilities in the settings:

- Portrait
- Landscape
- Same as device

(The latter option could be the default in SC which reflects the current behaviour).

**Use cases:**

1. If the phone is fixed on the handlebar of my mountain bike, the screen orientation sometimes turns from portrait to landscape and back on unpaved roads, especially if I have to mount the phone almost horizontally in order to avoid reflections of the sun on the display. In these cases it takes some time until the screen rotates back to the wanted orientation. With the described option the orientation could be fixed - autorotation makes no sense here.

2. (even more important): Sometimes I walk through a region in order to solve some quests. If the next quest is, say, 200 metres away from my current location, I don't want to hold my phone upright but drop my arm instead while walking there. However, the screen rotates by 180 degrees (and noone is looking at it), causing an annoying delay if I lift my arm again in order to solve the next quest, because the screen has to rotate a second time by 180 degrees . Again, autorotation is useless here and an option to fix the orientation would be very handy.

**User interface proposal:**

A third line in the "Display" section in the "Settings" with the three options mentioned above (similar to the three radio buttons in "Auto synchronization").

The cycling cat

**Comment by rugk** [comment]
Question: Why does not you just disable autorotation in the system settings (quickly done his the notifications area) system-wide? As far as I see, this solves both use cases you presented.

**Comment by cyclingcat** [comment]
Of course this would be a workaround, but for many other apps other than mapping, autorotation is very useful. Some websites for example are much better readable in landscape mode.

The cycling cat

**Comment by westnordost** [comment]
So, the actual problem is that the screen rotation is slow/disruptive.

**Comment by cyclingcat** [comment]
Unfortunately, both issues are still there with v8.3. Today I noticed no. 1 while riding my MTB - I had to fix my phone almost horizontally (perhaps with an angle of 10-20°) due to sun reflections and sometimes the screen rotated. Finally I locked the screen rotation in the system settings, but I still think that it would be a great improvement especially for those people using Street Complete on a bike.

Concerning no. 2, I don't see a big difference to the behaviour in earlier versions. Granted, my phone doesn't have the fastest CPU, but again a possibility to lock the screen orientation would improve the behaviour as well, especially for people who don't own a >500€ phone.

**Comment by westnordost** [comment]
I tend to say that this should be a system setting.

1. Do other apps do this?
2. I am unsure about if/how this technically feasible
3. You don't see a difference in speed when rotating the phone?? Before 8.0, the complete map was reinitialized, which took at least 2 seconds on its own on my phone (5years old 200$ phone). Now for me the rotation executes immediately (is shorter than the animation)

**Comment by matkoniecz** [comment]
> especially for people who don't own a >500€ phone.

On my 100$ phone orientation is usually limited by animation speed. From time to time there is lag second or two but it is, at least in my use, practically never a noticeable issue, It is unlike for example lag after solving quest, when all quests disappear and one waits for them to reappear - though it also was never was a sufficiently irritating for me to run a profiler.

**Comment by westnordost** [comment]
(the lag when solving a quest is a known issue)

**Comment by cyclingcat** [comment]
1. I have never seen this behaviour with OsmAnd so far (the only other GPS application I regularly use), but I will keep an eye on it the next time I ride my bike.

2. At least OsmAnd is able to do this, so it's technically possible. Don't know how easy an implementation would be though... perhaps a peek into OsmAnd's source code would help? 

3. Currently it takes about a second until the display has rotated. Maybe this time was a little longer in earlier versions, but 1 second is still somewhat disturbing IMHO.

The cycling cat

**Comment by westnordost** [comment]
A short google search reveals that there are a number of apps on Google Play that add a widget/setting to change and lock the screen orientation, like [this one](https://play.google.com/store/apps/details?id=org.crape.rotationcontrol) and many [others](https://play.google.com/store/search?q=screen+orientation&c=apps).
A system-wide setting makes more sense, as said, as every app individually implementing some kind of lock screen rotation feature.

**Comment by westnordost** [comment]
So, I will close this issue.
