### ISSUE TITLE
add amenity=arts_centre to opening hours quests (and maybe some others)

### ISSUE THREAD

**Issue by matkoniecz** [westnordost/StreetComplete#1219]
https://taginfo.openstreetmap.org//search?q=amenity%3Darts_centre

**Comment by westnordost** [comment]
Though: https://taginfo.openstreetmap.org/tags/amenity=arts_centre#combinations

**Comment by matkoniecz** [comment]
> Though

What wrong is suggested by this data?

**Comment by westnordost** [comment]
Hm ok. Well, in my experience, art exhibition centres are somewhat event/programme-driven. The same with theatres, concert halls, music venues (where bands perform), opera houses, small "programme" cinemas etc: They are not open regularly daily, but only for what's in their programme a given month. 

Am 3. Oktober 2018 23:43:09 MESZ schrieb Mateusz Konieczny <notifications@github.com>:
>> Though
>
>What wrong is suggested by this data?

**Comment by matkoniecz** [comment]
Then maybe https://www.openstreetmap.org/relation/63664#map=18/52.21939/21.03190 is unusual or mistagged.

**Comment by westnordost** [comment]
Are maybe programme driven arts venues tagged the same as so-called (in German at least) arts halls (e.g. Louvre)? The latter are more like museums in the sense that they have fixed hours and fixed art exhibits with only some rooms changing from time to time.

Am 4. Oktober 2018 07:12:51 MESZ schrieb Mateusz Konieczny <notifications@github.com>:
>Closed #1219.
