### ISSUE TITLE
add amenity=arts_centre to whelchair access quest (and maybe some others)

### ISSUE THREAD

**Issue by matkoniecz** [westnordost/StreetComplete#1220]
https://taginfo.openstreetmap.org//search?q=amenity%3Darts_centre

- in #1219 it turned out that it is not fitting opening hours quest
- it is already in add name quest

**Comment by westnordost** [comment]
Sure, makes sense

**Comment by matkoniecz** [comment]
amenity=arts_centre is already in place_name quest

I am unsure about internet_access quest

I would add to toilet_availability but it has really strict selection
