### ISSUE TITLE
REPAIR incorrect data added with StreetComplete v8.0-beta1 and v8.0

### ISSUE THREAD

**Issue by westnordost** [westnordost/StreetComplete#1222]
### What was broken?

In Version v8.0-beta1 and v8.0, the country detection was broken, it returned wrong results for a given geo position.
For some quests, StreetComplete shows a different UI for different countries and for a few, it also tags different things based on the country an element is in. With a broken country detection, the former could have led to misunderstandings by the users, the latter will have introduced wrong data.

This must be repaired.

### What needs to be repaired?

To repair, all changesets generated by v8.0-beta and v8.0 (the former has been released on the 16th of September; the versions have been blocked for upload on 4th October, 20:00 UTC+2) for certain quest types need to be checked for errors.

I identified the following quests to potentially contain errors (in order by importance):
1. **Max speed quest**:
  a) when answering that a road segment has no signed speed limit, the app tags `maxspeed:type=[ISO-COUNTRY_CODE]:[ROAD_TYPE]`. The` ISO-COUNTRY_CODE` may be wrong
  b) otherwise, in countries that use miles per hour, the app tags `maxspeed=[input] mph`. It may be that the app wrongly added `mph` or vice-versa
2. **Bicycleway**: The UI is a bit different for countries that drive on the left hand side and for countries that drive on the right hand side. Particularly, for oneways, the app only offers to specify if there is a cycleway on the _right_ for countries that drive _on the right_ and vice-versa for countries that drive on the _left_. So in instances where a oneway-road was tagged with a bicycleway, there may have been a misunderstanding and the wrong side has been tagged with having a bicycleway or not.
3. **Housenumber**: Specifically in Slovakia, the app may have failed to ask for the conscription and street number, instead of the housenumber (or vice-versa in the vicinity of Slovakia). This is half as bad though, because Slovakian OSM mappers usually duplicate the housenumber information into the conscription number etc., also, the UI is very clear about what the user should input. I.e. a user would never input the housenumber into the conscription number field.
4. **Max height**: Depending one the country on is in, the user is presented either with a feet+inch input or a meter input. It may be that user were asked for the wrong unit to input. However, the UI is quite clear about what the user should input (the unit is displayed next to the input field), so as in point 3, I think this is not a big problem here.
5. Quests that are disabled in certain countries, might have been downloaded even in those. Quests, once downloaded, stick around for quite a while, so this problem will continue to persist for some time. Though, this is not so bad, because the reason why these quests are disabled in those countries is not because they add wrong information, but by preference of the community. 
For example the Dutch don't want the housenumber quest because they import all their addresses from an official source and thus don't need individuals to map housenumbers. The cycleway quest on the other hand is disabled in in most parts of the world, because in most parts of the world, there doesn't even exist the concept of a way designated for cyclists. Same goes for tactile pavings at bus stops and crossings etc etc.

So, point 1 and 2 must be checked in any case, 3 and 4 maybe if there is a tool which allows to scan through it efficiently and point 5 I wrote here just for information.

### Help wanted

Help is wanted primarily so that someone could maybe point me to the best tool to find and browse through those changesets (find changesets by `created_by` with a certain changeset  `comment`) efficiently, and maybe even fix those in place without using another editor? Or maybe there is an even more efficient way to do this.

**Comment by ENT8R** [comment]
OSMCha has filters for the editor and the changeset comment: https://osmcha.mapbox.com

**Comment by westnordost** [comment]
Okay, currently using this.

**Comment by westnordost** [comment]
Progress:
https://www.openstreetmap.org/user/westnordost/history

**Comment by westnordost** [comment]
Repair for maxspeed is done for v8.0 and v8.0-beta1, continuing with cycleways...

**Comment by westnordost** [comment]
Alright, done.
