### ISSUE TITLE
Can't submit quests done with v8.0 and v8.1 is not on F-Droid

### ISSUE THREAD

**Issue by Freso** [westnordost/StreetComplete#1223]
I've just come home to Sweden from 7 days in Barcelona. I didn't have wifi at the last place I stayed at, so I have a number of completed quests I never got around submitting.

Now I'm back home in Sweden and trying to submit the completed quests, and it tells me that my version is too old:

> This version does not correctly determine in which country you are, necessary to tag certain answers correctly.

**How to Reproduce**

* Go to Barcelona and complete a number of quests, without submitting them
* Travel to Sweden and try to submit the completed quests

**Versions affected**

Android: 6.0.1 (Fairphone Open OS)
StreetComplete: 8.0 (F-Droid build)

**Comment by Freso** [comment]
Actually, this is probably "just" a case of the block mentioned in https://github.com/westnordost/StreetComplete/issues/1222 – there is one "house number" quest in the batch. Would it be possible to submit the rest and just discard the house number one?

**Comment by westnordost** [comment]
You just need to update to v8.1, and you will be able to upload again.

**Comment by Freso** [comment]
No 8.1 in F-Droid yet. I guess I'll try again tomorrow.

**Comment by westnordost** [comment]
According to F-Droid wiki, the new version was built yesterday successfully: https://f-droid.org/wiki/page/de.westnordost.streetcomplete/lastbuild_802

**Comment by Freso** [comment]
According to F-Droid packages, the latest available build is 8.0: https://f-droid.org/en/packages/de.westnordost.streetcomplete/ :man_shrugging:

**Comment by rugk** [comment]
However, AFAIK, you can still solve quests and when you update to v8.1 you will be able to upload the changes.

That said, actually this thing circumvents the blocking mechanism, does not it, @westnordost? Because users could then upload broken changes they created with v8.0 in v8.1?

**Comment by exploide** [comment]
Don't want to go too off-topic, but to clarify the F-Droid issue:

> According to F-Droid wiki, the new version was built yesterday successfully

> According to F-Droid packages, the latest available build is 8.0 :man_shrugging:

Both statements are true. While the apk has already been built, the relevant thing is that the deploy task did not happen yet. See https://f-droid.org/wiki/index.php?title=Special:RecentChanges&days=7&from=&hidebots=0&hideanons=1&hideliu=1&limit=500

Don't know why but this happens often. The next checkupdates task is already running but no deploy yet. Hopefully the relevant task will run in this round. We need to wait...

**Comment by westnordost** [comment]
I think this is the same problem as here:
https://forum.f-droid.org/t/steetcomplete-successful-build-but-newest-version-does-not-show-up/3302

Though, I still don't know where to report this to (in case the F-Droid guys did not notice yet)

**Comment by Freso** [comment]
I asked them on IRC (#fdroid on Freenode), and it seems the index hasn't been regenerated since last Friday(!), but it is apparently in the process of being regenerated now, so… Soon™.

**Comment by Etua** [comment]
@westnordost v8.1 is out, you can close the issue.

**Comment by westnordost** [comment]
Finally! Thanks for the notice.
