### ISSUE TITLE
Building quest shown for buildings tagged as something else already

### ISSUE THREAD

**Issue by rugk** [westnordost/StreetComplete#1225]
E.g. it sometimes happens the thing is tagged as `amenity=toilets` and `building=yes`– the last thing triggering the building type quest. Obviously, however, it is already tagged…

Or, I do misunderstand the `building` tagging, but in this case I e.g. just have no idea what building type to select as a small single house for (a public) toilet is just a _building_ for that exact thing.

**How to Reproduce**
Well… look for such an object on the map.

**Versions affected**
tested with SC 8

**Proposed solution**
If possible, you could try to search this quest only for "building=yes" _and no other tags_ (except some common ones like floors or so, which SC itself adds). This would be most failure-proof.
Alternatively, you could of course just exclude all `amenity` or so…

**Comment by westnordost** [comment]
With amenity, you tag the function of the building, with building, you tag for what this has been constructed. Certainly, any building is constructed for _some_ purposed, and certainly, these are related. Still, these are two tags. A hotel can also be tagged as `tourism=hotel + building=hotel`, this is not incorrect and not a duplication.

**Comment by rugk** [comment]
> A hotel can also be tagged as tourism=hotel + building=hotel

And a toilet? AFAIK there is no `building=toilet`…

**Comment by westnordost** [comment]
There is

**Comment by rugk** [comment]
Oh, okay, then I totally missed it, sorry.

Or, actually, if that story is helpful: I did not know it was a toilet and initially wanted to tag it as something else (with no value in SC), but on OSM saw it had a toilet amenity in it. Well… does not matter. Thanks FYI.
