### ISSUE TITLE
Golf Cart Path

### ISSUE THREAD

**Issue by monikarora** [westnordost/StreetComplete#1230]
Hey guys, I'm  android developer, In my app i want to add golf cart path. Please let me know open street map provides Golf cart path option.

Thanks!

**Comment by ENT8R** [comment]
And how exactly do you think is this related to the android app StreetComplete ❓
StreetComplete is an app to extend existing OpenStreetMap data but it can't add new (not already existing) data to the map. If you want to start to contribute to the OpenStreetMap I think you should have a look at some OSM beginners guide like the following:
https://learnosm.org/en/beginner/
https://wiki.openstreetmap.org/wiki/Beginners%27_guide

**Comment by rugk** [comment]
If you need information on how to develop an app and use osm with it see https://wiki.openstreetmap.org/wiki/Develop.
You may also have a look at the libraries this app uses or so.

Generally the OSM wiki is your friend and there you may find out what is supported already by OSM or not. SteetComplete is just an app that uses OSM and this here is no OSM support forum or so. There are other appropriate places you can find on the OSM website or so.
