### ISSUE TITLE
Building quests not showing in a certain place

### ISSUE THREAD

**Issue by NonnEmilia** [westnordost/StreetComplete#1232]
I was in this area today: https://www.openstreetmap.org/#map=19/44.67386/10.61509
and I downloaded the quests. I saw every quest except the building type and building levels ones.

I have invalidated the quest cache and I've re-scanned for quest, but no building quests appeared...

In other zones (northest from the point) everything work well and the building quests appears.

**How to Reproduce**
Go to the coordinates 44.67386 N, 10.61509 E and scan for quests.

**Versions affected**
Android v8.1.0 and StreetComplete v8.1

**Comment by ENT8R** [comment]
This is probably because there are too many possible quests in your area. If there are more than 2000 quests for a quest type, the rest is ignored and no quests are created (https://github.com/westnordost/StreetComplete/blob/master/app/src/main/java/de/westnordost/streetcomplete/data/osm/tql/OverpassQLUtil.java#L7).

**Comment by rugk** [comment]
Okay, that seems to be confusing. Could not SC then just try to download again with a smaller area (bounding box) in order to try to get less quests?

**Comment by ENT8R** [comment]
For reference: this was introduced because of https://github.com/westnordost/StreetComplete/pull/1180#issuecomment-417945915

**Comment by matkoniecz** [comment]
From reading it

> Overpass queries used to retrieve quests now cap the results to 2000

So it is possible that for given area only first 2000 buildings were fetched. And apparently buildings were  not distributed randomly.

**Comment by westnordost** [comment]
The results from overpass are sorted by id (so, oldest element first), IIRC, by the way. Looking at overpass turbo, the claim that this might be because of the mentioned change looks plausible ( http://overpass-turbo.eu/s/CF2 ), thus I can and will not change anything here.

**Comment by matkoniecz** [comment]
@NonnEmilia So in practice one way to solve that is to solve some building type quests in the region where they are available.

**Comment by NonnEmilia** [comment]
Ok, thanks you all for the explanation.
