### ISSUE TITLE
opening_hours uses localized number format

### ISSUE THREAD

**Issue by PromyLOPh** [westnordost/StreetComplete#1234]
The format string for opening_hours uses localized number format strings, resulting in unparseable data. Example:
Mo-Fr ٠٩:٠٠-١٨:٠٠; Sa ١٠:٠٠-١٣:٠٠
when it should have been
Mo-Fr 09:00-18:00; Sa 10:00-13:00

**How to Reproduce**
Switch device’s locale to a language that uses eastern arabic numerals, add opening hours to a shop and upload to OSM.

**Versions affected**
StreetComplete 8.1, Android 7.1.2

**Comment by westnordost** [comment]
Are these numerals also shown in the UI when selecting the time?

**Comment by PromyLOPh** [comment]
Yes, this is fine. I’m mainly concerned about what ends up in OSM’s database.

![screenshot_ - png scaled](https://user-images.githubusercontent.com/13182/47024397-e04d5f00-d161-11e8-92a4-db681437dd49.png)
![screenshot_ - png scaled](https://user-images.githubusercontent.com/13182/47024455-0541d200-d162-11e8-983c-fc9ffb4c9d7a.png)

**Comment by westnordost** [comment]
Ok, will solve this. The numerals need to be translated after selection. I wonder if I have to implement this myself (thinking that Arabic  is certainly not the only language with own numerals) or if there is already something for that.

**Comment by PromyLOPh** [comment]
I doubt that’ll be necessary.
https://github.com/westnordost/StreetComplete/blob/e371bed9e4f6e7de92c3961de20af35193ec3270/app/src/main/java/de/westnordost/streetcomplete/quests/opening_hours/model/TimeRange.java#L75
does not pass a locale, thus the system’s locale settings are applied.
Explicitly selecting English should do the trick. The question is: Does
that affect the UI as well or just the data sent to OSM?

**Comment by westnordost** [comment]
Thank you for the hint. This bug needs to stay open so I can clean up possible wrong taggings made by this app so far.

**Comment by westnordost** [comment]
Oh, I overread your comment. Yes, it affects the UI. I should change that then.

**Comment by westnordost** [comment]
I used this overpass-query to look for where it was tagged incorrectly
```
nwr[opening_hours~"[٠١٢٣٤٥٦٧٨٩۰۱۲۳۴۵۶۷۸۹۰۱۲۳۴۵۶۷۸۹௧௨௩௪௫௬௭௮௯०१२३४५६७८९੦੧੨੩੪੫੬੭੮੯૦૧૨૩૪૫૬૭૮૯০১২৩৪৫৬৭৮৯୦୧୨୩୪୫୬୭୮୯౦౧౨౩౪౫౬౭౮౯೦೧೨೩೪೫೬೭೮೯௦௧௨௩௪௫௬௭௮௯൦൧൨൩൪൫൬൭൮൯၀၁၂၃၄၅၆၇၈၉၁၀꧑꧒꧓꧔꧕꧖꧗꧘꧙០១២៣៤៥៦៧៨៩໐໑໒໓໔໕໖໗໘໙๐๑๒๓๔๕๖๗๘๙᠐᠑᠒᠓᠔᠕᠖᠗᠘᠙༠༡༢༢༣༤༥༦༧༨༩零〇一二三四五六七八九十零空一二三四五六七八九十영령공일이삼사오육륙칠팔구십〡〢〣〤〥〦〧〨〩〸〹〺א‬ב‬ג‬ד‬ה‬ו‬ז‬ח‬ט‬י‬აბგდევზჱთიԱԲԳԴԵԶԷԸԹԺ]"];
(._;>;);
out body;
```
The query also returns quite a few false-positives. Basically, there was only one survey in Germany and a few POIs in Iran and Saudi Arabia where a tagging with non-western numerals was made by StreetComplete.

**Comment by PromyLOPh** [comment]
Thanks :)
