### ISSUE TITLE
Privacy policy

### ISSUE THREAD

**Issue by HarryHeights** [westnordost/StreetComplete#1240]
Hello, I'm Harry. I came across your project recently and having looked around the repository, I was hoping to see a privacy policy statement. For an app that might deal with user data collection which in this case might be in terms of IP addresses and locations, it'll be cool to have a policy statement. 
What do you think about this?
If you think it's necessary, I could help draft the document and you just have to review if it suits the project accurately and isn't missing important details.

**Comment by westnordost** [comment]
There is one. In the menu, click "About StreetComplete", then "Privacy Policy"

Am 25. Oktober 2018 17:39:33 MESZ schrieb Harry <notifications@github.com>:
>Hello, I'm Harry. I came across your project recently and having looked
>around the repository, I was hoping to see a privacy policy statement.
>For an app that might deal with user data collection which in this case
>might be in terms of IP addresses and locations, it'll be cool to have
>a policy statement. 
>What do you think about this?
>If you think it's necessary, I could help draft the document and you
>just have to review if it suits the project accurately and isn't
>missing important details.

**Comment by westnordost** [comment]
Also available on Google Play: scroll down to my email address, there is a link to a simple HTML with the privacy policy.
https://play.google.com/store/apps/details?id=de.westnordost.streetcomplete
