### ISSUE TITLE
Add "metallic" to the way's surface options

### ISSUE THREAD

**Issue by CarlosBrys** [westnordost/StreetComplete#1241]
Pedestrian bridges builded on metallic strctures cannot be tagged

**Comment by westnordost** [comment]
You can leave a note, describing it.

**Comment by westnordost** [comment]
They can. It is implemented since version 4.0.

**Comment by CarlosBrys** [comment]
> They can. It is implemented since version 4.0.
I do not see that option in version 8.2
![image](https://user-images.githubusercontent.com/6495550/47606173-8dd43400-d9e6-11e8-99a9-ad506fe05b5a.png)

**Comment by ENT8R** [comment]
Did you try to press the button which says "Mostrar mas" (Show more)? There are all surfaces which are not that common

**Comment by CarlosBrys** [comment]
> Did you try to press the button which says "Mostrar mas" (Show more)? There are all surfaces which are not that common

Only paved, unpaved, generic and "I don't know"
![imagen](https://user-images.githubusercontent.com/6495550/47606849-2bcbfc80-d9ef-11e8-974c-b387ac2d6895.png)

**Comment by CarlosBrys** [comment]
> They can. It is implemented since version 4.0.

Why do you close my issu, if it is not resolved yet?

**Comment by ENT8R** [comment]
> Only paved, unpaved, natural and "I don't know"

And what happens if you click on one of those categories? There should be a submenu which has all other surfaces. If you press e.g. paved (pavimentado), there is an option called "metal" 😄
I can even prove this with the source code:
https://github.com/westnordost/StreetComplete/blob/ff8811507d50c25d36562a73271d0398dfb6ecfa/app/src/main/java/de/westnordost/streetcomplete/quests/surface/Surface.java#L20

> Why do you close my issue, if it is not resolved yet?

Sorry, but it is clearly resolved and I think that you can expect that the owner and creator of this repository and the app StreetComplete knows which options are available and which are not...

**Comment by rugk** [comment]
I guess @CarlosBrys just overlooked that you can select "paved" (and other's) and more answer possibilities appear.

**Comment by CarlosBrys** [comment]
> > Only paved, unpaved, natural and "I don't know"
> 
> And what happens if you click on one of those categories? There should be a submenu which has all other surfaces. If you press e.g. paved (pavimentado), there is an option called "metal" smile
> I can even prove this with the source code:
> 
> [StreetComplete/app/src/main/java/de/westnordost/streetcomplete/quests/surface/Surface.java](https://github.com/westnordost/StreetComplete/blob/ff8811507d50c25d36562a73271d0398dfb6ecfa/app/src/main/java/de/westnordost/streetcomplete/quests/surface/Surface.java#L20)
> 
> Line 20 in [ff88115](/westnordost/StreetComplete/commit/ff8811507d50c25d36562a73271d0398dfb6ecfa)
>  METAL =         new Item("metal", R.drawable.surface_metal, R.string.quest_surface_value_metal), 
> 
> > Why do you close my issue, if it is not resolved yet?
> 
> Sorry, but it is clearly resolved and I think that you can expect that the owner and creator of this repository and the app StreetComplete knows which options are available and which are not...

Honestly, it did not occur to me to see if there were more possible values in the "paved" option.
As an OpenStreetMap mapper, we chose the "paved" label when we do not know what the surface is.
It's the only thing the wiki: https://wiki.openstreetmap.org/wiki/Key:surface
highway=paved: A highway feature is predominantly paved along its length; i.e., it is covered with paving stones, concrete or bitumen. This value gives only a rough description; use a more precise value if possible.

I apologize for not having reviewed more closely, but I think it would be more intuitive if the text of the option "paved" also says "others"

Thanks for clarifying my question

**Comment by westnordost** [comment]
I am open for suggestions how to make it more clear that these panorama pictures are categories that are expanded when clicked on, I haven't been able to come up with anything so far (Same category-picker is used in the buildings quest.)

**Comment by goldfndr** [comment]
Perhaps add an icon for collapsed/expanded state?
