### ISSUE TITLE
History in quests completed counter

### ISSUE THREAD

**Issue by ivanhercaz** [westnordost/StreetComplete#1247]
**Use case**
Sometimes I want to check what quests I completed, why? For different purposes, sometimes it is only curiosity, another times it is because I want to review if I make an specific quest, and occasionally I want to review if I mapped correctly the quest.

The first case, curiosity, isn't very important and anyone can check it in their contributions page in osm.org. In my opinion the important cases are the other ones, in which the purposes is different, but related: review a quest.

**Proposed Solution**
Due to the above mentioned, I propose to make the quests completed counter (marked in the below screenshot) as a clickable option that shows the history with the quests completed. I read #748 but I am not sure because in the undo icon the action needs to be called by a different interaction, like a long press but it can be avoided if we set this function in the counter.

Keeping in mind what @westnordost mentioned about how to show the items in the list I think it could be with one of this formula:

- Icon and the name of the element, if it has one, that had been changed.
- Icon and the position in the map. If there are several quests in the same position, as westnordost ask in #748, I think it is sufficient with the icon + position, nor only the position, because when a quest is in the same position it usually is part of the same element (for example, the same building or the same crossroad).

As a difference with #748, I don't know if I would include the function to undo quests edited beyond the last. With this suggestion I want to emphasize the history and not the undo function.

<img src="https://user-images.githubusercontent.com/8690921/47623796-3b416780-db0d-11e8-904c-d2542853e289.jpg" width="300">

**Comment by westnordost** [comment]
> The first case, curiosity, isn't very important [...]. In my opinion the important cases are the other ones, in which the purposes is different, but related: review a quest.

You did not really explain what for one would need a history in which you can review the quest answers but not undo them. What exactly would you want to review there? It can't be the tags, because these are never shown in the app.

**Comment by ivanhercaz** [comment]
> What exactly would you want to review there?

What I would like to review is a list of what quests, where and when I completed each one.

> ... but not undo them. What

What I wanted to say is in my personal case I am not interested in the undo action in the history at the time to suggest this feature, I wanted to emphasize the history in the star counter with or without the undo button. This issue issue doesn't pretend to argue against the #748, both can be complemented. I may have expressed myself badly, excuse me.

> I plan to make the star counter clickable in the future, but it should lead to a statistics screen in which you get a complete overview over how many quests of which type you solved so far, and more.

That sounds nice to me too. I suggested the history in the star counter because the action would be easier, just a click and not a long-press click. Could the history function (with or without the undo action) be in the start counter at the same than the statistics screen you are planning?

**Comment by westnordost** [comment]
But *why* would you want to review what you solved, in a sorted order and displayed on the map?
You can't see if you made mistakes because you can't see the tags and you can't undo them in case you remember having mistakes. What *is* there to review?

Am 30. Oktober 2018 08:48:28 MEZ schrieb "Iván" <notifications@github.com>:
>> What exactly would you want to review there?
>
>What I would like to review is a list of what quests, where and when I
>completed each one.
>
>> ... but not undo them. What
>
>What I wanted to say is in my personal case I am not interested in the
>undo action in the history at the time to suggest this feature, I
>wanted to emphasize the history in the star counter with or without the
>undo button. This issue issue doesn't pretend to argue against the
>#748, both can be complemented. I may have expressed myself badly,
>excuse me.
>
>> I plan to make the star counter clickable in the future, but it
>should lead to a statistics screen in which you get a complete overview
>over how many quests of which type you solved so far, and more.
>
>That sounds nice to me too. I suggested the history in the star counter
>because the action would be easier, just a click and not a long-press
>click. Could the history function (with or without the undo action) be
>in the start counter at the same than the statistics screen you are
>planning?

**Comment by ivanhercaz** [comment]
> You can't see if you made mistakes because you can't see the tags

Well... Thinking more about it, you have reason, if I can't check it, the review will be just for the curiosity to know what the user have done.

Considering this I am going to close this issue. If you, or anyone, consider useful to have the history and the undo action mentioned in #748 but in the start counter, reopen it.

Excuse me this issue, it hasn't been very useful.

Regards,
Iván
