### ISSUE TITLE
Adding building levels and roof type for cabin

### ISSUE THREAD

**Issue by cstackpole** [westnordost/StreetComplete#1248]
**Use case**
I've been going to a lot of state parks recently where the buildings are correctly tagged building=cabin. However, I've noticed that StreetComplete doesn't give the options for roof type or building level for these types of buildings.

I understand that cabins are not well defined and as such they are not considered for selection as a building type (See westnordost's comment on May 31 here https://github.com/westnordost/StreetComplete/pull/774 ), but for existing buildings I don't see why roof type and levels would not be an appropriate quest.

**Proposed Solution**
I would like to see roof type and levels added to cabins and potentially to other ways with the building tag.

Thanks!

**Comment by matkoniecz** [comment]
> added to cabins

Makes sense for me, though I will wait with making PR until @westnordost looks at it

> potentially to other ways with the building tag

The best way to solve that is to look through https://taginfo.openstreetmap.org/keys/building#values and https://github.com/westnordost/StreetComplete/blob/0e0fe08227a4d18654ce2503a7aa6fa3505f21ca/app/src/main/java/de/westnordost/streetcomplete/quests/building_levels/AddBuildingLevels.java#L23 - and list other values (either in comment in this issue until it is open or create new issues for each one - I am not sure which would be preferred by @westnordost )

**Comment by matkoniecz** [comment]
Roof shape quest requires no building list update - see
https://github.com/westnordost/StreetComplete/blob/0e0fe08227a4d18654ce2503a7aa6fa3505f21ca/app/src/main/java/de/westnordost/streetcomplete/quests/roof_shape/AddRoofShape.java#L23

**Comment by westnordost** [comment]
Yes, I think this makes sense

**Comment by matkoniecz** [comment]
@cstackpole Thanks for a report! Proposed code change is now at https://github.com/westnordost/StreetComplete/pull/1249
