### ISSUE TITLE
Map new structures

### ISSUE THREAD

**Issue by SirCmpwn** [westnordost/StreetComplete#125]
Would be nice to be able to map new buildings nearby.

**Comment by westnordost** [comment]
Sorry, this is out of the scope of this app.

**Comment by SirCmpwn** [comment]
That's unfortunate. The biggest problem with OSM is that it's an incomplete map, not that it's missing metadata.

**Comment by westnordost** [comment]
True. Well, you can use Vespucci on a smartphone or tablet. Vespucci is a fully fledged editor.

On 18 April 2017 05:07:09 CEST, Drew DeVault <notifications@github.com> wrote:
>That's unfortunate. The biggest problem with OSM is that it's an
>incomplete map, not that it's missing metadata.
>
>-- 
>You are receiving this because you modified the open/close state.
>Reply to this email directly or view it on GitHub:
>https://github.com/westnordost/StreetComplete/issues/125#issuecomment-294661391

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.
