### ISSUE TITLE
ask whatever leisure=dog_park is wheelchair accessible

### ISSUE THREAD

**Issue by matkoniecz** [westnordost/StreetComplete#1252]
### General
Affected tag(s) to be modified/added: [wheelchair](https://wiki.openstreetmap.org/wiki/Key:wheelchair)
Question asked: **Is dog park wheelchair accessible?**

### Checklist
Checklist for quest suggestions (see guidelines):
- [x] 🚧 To be added tag is established and has a useful purpose
- [x] 🤔 Any answer the user can give must have an equivalent tagging (Quest should not reappear to other users when solved by one)
- [x] 🐿️ Easily answerable by everyone from the outside but a survey is necessary 
- [x] 💤 Not an overwhelming percentage of elements have the same answer (No spam)
- [x] 🕓 Applies to a reasonable number of elements (Worth the effort)

### Ideas for implementation

Should be fairly easy to base it on existing wheelchair quests (note that this one can be enabled by default).

**Element selection:** 

**Metadata needed:** No

**Proposed GUI:**

Should be fairly easy to base it on existing wheelchair quests.

**Other:**

https://github.com/simonpoole/beautified-JOSM-preset/issues/114 is a related issue (I was not 100% sure whatever tagging wheelchair on leisure=dog_park is a good idea).

**Comment by matkoniecz** [comment]
In case that it is not rejected I plan to implement this.

**Comment by westnordost** [comment]
Isn't a dog park basically a fenced park where dogs are allowed (designated)? Have you ever seen a dog park that is not accessible by wheelchair?
If it is asked for dog parks, then it should also be asked for parks, shouldn't it?

**Comment by matkoniecz** [comment]
> Have you ever seen a dog park that is not accessible by wheelchair?

Access only by steps, entrance was too narrow to fit wheelchair. And case of wheelchair=limited due to lack of any paved surface where pathes were really muddy after rain.

>  If it is asked for dog parks, then it should also be asked for parks, shouldn't it?

I think that it may make sense, though I never tried to map or use this kind of data. But in this case it may fail "Not an overwhelming percentage of elements have the same answer" check. I encountered some wheelchair unfriendly dog parks (maybe I was unlucky) but all parks that I remember now where wheelchair accessible (maybe I am lucky or missed something as I was never a wheelchair user).

**Comment by westnordost** [comment]
Mh okay. I am pretty indifferent to this proposal, so I'd say it should be the same as for beautified-JOSM-preset
