### ISSUE TITLE
FR: Location not sticky

### ISSUE THREAD

**Issue by woj-tek** [westnordost/StreetComplete#1255]
**Use case**
This is related to #429 - I want to use StreetComplete, but stickynees of GPS drives me nuts. Yes, it can be handy, but most of the time I have to get location and then leave the sticky mode.

**Proposed Solution**
Make the sticky-GPS optional (for example with long-tap, or make non-sticky location query with long tap).

**Comment by rugk** [comment]
Well… with one click on the "position :round_pushpin:" button you can unstick it and move the map they way you want. Is not that, what you need?

**Comment by woj-tek** [comment]
Not exactly, because then when I wan't to center on my location I have to tap on it again, then tap again to enter free-movement mode.

Most of the time I launch application in new location, so I tap on the Position button, then I tap again to actually be able to move and explore area (find out where are the chellanges and things I could contribute and then walk and explore and see around. But then I have to put my phone in the pocket and move myself further, so again tap on the location to center on my position, tap again to free move.
I'm aware that centering on my position constantly *may* be useful for some, but (at least for me) it's quite annoying and cumbersome.
Moreover, all maps applications follows 'non-sticky' principle, i.e. you center on your location and then move freely (to explore). Maybe that's the reason I find the sticky gps so annoying - after all habit is the second nature ;-)

Bottomline - it would be really great to have it optional :-)

**Comment by pkoby** [comment]
I can see the advantages of both methods, but have to agree that most apps do use the other form. Hitting the button locks to location and will follow if you move, unless you interact with the map by dragging, when it unsticks. I don't know which version would be better for this application, though.

A similar function is when you tap the compass to go into 3D mode, and the map follows your orientation as well, unless you interact with the quests, in which case it stops following your orientation and you have to hit the compass again (maybe twice? I haven't used that in awhile).

**Comment by goldfndr** [comment]
[Explanation]( https://github.com/westnordost/StreetComplete/issues/627#issuecomment-334703145)

Some apps I use have a configurable duration of inactivity to recenter the map.

@woj-tek When you put your phone in the pocket, is its screen off? Perhaps screen on could trigger re-centering (if it doesn't already).

**Comment by westnordost** [comment]
So, this will be a will not fix. UI things like this are obviously up to individual taste. In #627 I explained some reasons for the current behavior, which was also done due to a feature request **about the location being too un-sticky**. We could go back and forth here for a while. While there is no strong argument to go the one or the other way, I leave it as it is.

**Comment by westnordost** [comment]
I'll solve #1257

Am 19. November 2018 01:21:39 MEZ schrieb Wojtek <notifications@github.com>:
>Just one question - why not it make configurable - given this is "up to
>personal taste" and there seems to be rationale for both approaches
>(not to mention supporters)? I think that for me the biggest annoyance
>about non-sticky approach comes from #1257
