### ISSUE TITLE
[8.4] View doesn't return to previos position after solving challenge

### ISSUE THREAD

**Issue by woj-tek** [westnordost/StreetComplete#1257]
In un-sticky-gps, after solving some quest the maps jumps to different location. It happens most of the times, but not always, usually with longer quests (type of road)

**How to Reproduce**
* select quest (mostly surface type of the road)
* the view zooms out
* solve the quest
* view jumps to different location (it *seems* it jumps to the start/end of the road) -- it should return to the previous view from which we selected the object

**Versions affected**
Android 7.1 Nougat
StreetComplete 8.4

**Comment by westnordost** [comment]
It jumps back to the location that you had in view before clicking on the quest.

**Comment by matkoniecz** [comment]
Sticky GPS: viewport follows GPS signal

Unsticky: viewport is not following GPS signal

**Comment by woj-tek** [comment]
@westnordost 
https://www.dropbox.com/s/gb06kotnkyfp80d/streetcomplete.mp4?dl=0 - actually you don't have to solve quest - simply leave it's view. As you can see I start from one position (Urrutia street), enter quest view and then after leaving quest view I'm a couple of blocks down/north (train station). It kinda feels that it's related with long objects that forces change of underlying map view (to fit it completely). As for un-sticky-gpg -- I should say "non-sticky" - i.e. I can freely move around the map.

**Comment by westnordost** [comment]
That is definitely a bug, but I haven't been able to reproduce it so far.

**Comment by woj-tek** [comment]
It's quite reproducible for me - I could provide you with logcat if that helps.

**Comment by goldfndr** [comment]
Steps:

1. Move map so that quest is in top right or top left corner.
2. Tap quest.
3. Wait for quest to show.
4. Tap back in navigation bar (or equivalent gesture).
5. Observe that quest icon is no longer in top corner.

**Comment by westnordost** [comment]
Oh right, I was wrong: Only the zoom is reset to the previous zoom, but not the position. The position is not set to something different at all.

**Comment by rugk** [comment]
> Would it be an improvement if not only the zoom is reset but also the position?

IMHO, yes. :smile:

**Comment by woj-tek** [comment]
> Question is: Would it be an improvement if not only the zoom is reset but also the position? I am not so sure about that.

It would be huuuuge improvement (and this is the gist of this issue). IMHO, current behaviour is just a bug - I can't find any useful case for current behaviour (zoom out and then return zoom level but to completely different location).
