### ISSUE TITLE
bus stop shelter quests are shown for already mapped bus stop platform ways

### ISSUE THREAD

**Issue by zossebart** [westnordost/StreetComplete#1259]
SC shows bus stop shelter quests for nodes with highway=bus_stop (and no shelter tag), even if they are part of a way with public_transport=platform and shelter tag already set.

I think there is no benefit in duplicating the shelter tag to the node if it is already mapped for the bus stop platform way.
Here's an overpass query showing such nodes (look for example in Berlin): http://overpass-turbo.eu/s/DFs

**Versions affected**
Android 5.1.1 / StreetComplete 8.4

**Comment by matkoniecz** [comment]
In thought that correct mapping is to place highway=bus_stop on such areas of one decides to map them

**Comment by zossebart** [comment]
The wiki ([https://wiki.openstreetmap.org/wiki/Public_transport](https://wiki.openstreetmap.org/wiki/Public_transport)) says, for compatibility-reasons, highway=bus_stop should be placed on a node additionally to a platform mapped as a way or area. This is mainly for the renderer, because platform ways/areas are (still) not rendered.
I don't see why we should duplicate tags we already attach to platform ways/areas.

**Comment by westnordost** [comment]
Then, for the same reason (PTv1 compatibility), the duplication of the shelter tag, and any other tag on the highway=bus_stop node, is not an error, isn't it?
By what particular data consumer this is used, renderer or else, is not really relevant, as the reason for the duplication is backwards compatibilty, not mapnik-renderer-compatibility.

**Comment by zossebart** [comment]
Based on the note in the Wiki ("Note: Because the newer public_transport=* tags are currently not rendered on the main page, using highway=bus_stop is needed for rendering") I thought it is only necessary for the renderer.
But ok, if you decide to tag for PTv1 (in addition to PTv2), the duplication might be justified (although it makes no sense to me).
