### ISSUE TITLE
Reconsider collection max height for highway=pedestrian

### ISSUE THREAD

**Issue by matkoniecz** [westnordost/StreetComplete#1261]
Is there any region where highway=pedestrian is likely to have max height sign?

**Comment by westnordost** [comment]
Were they mistagged? (i.e. should they have been a service road?)

**Comment by westnordost** [comment]
Hmm well, the first would maybe be relevant for delivery trucks, the second certainly not. But I guess this is somewhat unimportant. Will remove the pedestrian.
