### ISSUE TITLE
[FR] More quests in current view

### ISSUE THREAD

**Issue by woj-tek** [westnordost/StreetComplete#1263]
**Use case**
Currently some quests are for large objects that span more than current view (especially roads spanning multiple blocks). There are some quests applicable to that item/road but are located out of the current view, i.e. a couple of blocks up/down.

**Proposed Solution**
It would be nice to see those quests in current view if the item to which they belong is currently visible (without having to zoom-out a couple of times)

**Comment by rugk** [comment]
Related to https://github.com/westnordost/StreetComplete/issues/642 or so…

**Comment by westnordost** [comment]
Or rather #733 ? @woj-tek , what do you think? Would #733 solve this use case for you?

**Comment by woj-tek** [comment]
yes, this one is duplicate of #733 - either realigning it to current view (supposedly technically impossible) or adding markers (like #642 I guess) would solve this issue.

**Comment by westnordost** [comment]
I'll try if I can do #733. Yes, aligning the markers is quite technically impossible.
