### ISSUE TITLE
Show quests clustered to show on all zoom levels

### ISSUE THREAD

**Issue by guerda** [westnordost/StreetComplete#1264]
Currently, not all quests are visible on each too. You have to zoom in to see all quests but then you don't see enough context.

**How to Reproduce**
1. Use a mid-range zoom level to explore quests.
2. Zoom into an area, where two quests exists
3. only one quest is shown, only if you zoom enough, both are shown

**Example**
Lower zoom:
![sc_lower_zoom](https://user-images.githubusercontent.com/230782/48695138-9df2c400-ebde-11e8-8627-7e8734dba073.png)
Higher zoom, a third quest appears:
![sc_higher_zoom](https://user-images.githubusercontent.com/230782/48695145-a519d200-ebde-11e8-9509-1eeea8dc930e.png)

**Expected behavior**
A grouped pin should collect all quests in that area if they cannot be displayed at the same time, like the [clustering feature in Leaflet](https://github.com/Leaflet/Leaflet.markercluster).

**Versions affected**
Android 7.0
StreetComplete 8.4 (FDroid)

**Comment by matkoniecz** [comment]
With clustering you would no longer be able to select quest and get zoomed to it. In some cases even at highest zoom you would not be able to select quests as they would be still clustered. Especially in cases of multiple quests for a single element.

Why clustering would be necessary/desirable?

**Comment by westnordost** [comment]
Sadly, this feature does not exist in tangram-es, which is the map rendering library StreetComplete uses.
So, this can/will not be fixed.
