### ISSUE TITLE
Bug report: Negative number on answers-to-upload counter

### ISSUE THREAD

**Issue by Poussinou** [westnordost/StreetComplete#1271]
Hi,

Just a simple bug to report : I sometimes have a negative number on the number of answers to upload. Just have a look at the screenshot.

![image](https://user-images.githubusercontent.com/19646549/48951491-0f17db80-ef3f-11e8-8783-0e48790b9d46.png)

**How to Reproduce**
It just appears sometimes. When I have a negative number (-1), I can close the app and then come back to it, the number is back to 0. I'm connected to internet via the WiFi of my university all the time.

**Versions affected**
8.4 (version I currently have)

**Comment by matkoniecz** [comment]
Are you using "undo" before it happens?

**Comment by Poussinou** [comment]
Nop, I never use it. I just answered the question, and then the answer was automatically uploaded since I have internet enabled.

**Comment by westnordost** [comment]
Hmm, right now I can't think of how this bug can come to pass, I will look at it later.

**Comment by westnordost** [comment]
Hm, can't find anything in the code. After an upload finished, the whole counter is updated from the database, so even if the counter was wrong in the meantime, it should be reset to the correct values then.

**Comment by rugk** [comment]
The question is what "feedback" you require? And from whom? (Maybe the tag "help wanted" would suit here?)

**Comment by westnordost** [comment]
More feedback on how to reliably reproduce the bug.

**Comment by cyclingcat** [comment]
This week I observed this phenomenon with v10.1 (Android 5.1). I solved 7 quests and left a note (no auto upload). After the upload, the counter after the arrow icon showed -1, similar to the screenshot of the issue opener. After minimizing and restoring the app the counter showed 0. Perhaps it has something to do with leaving notes? Will observe further.

The cycling cat

**Comment by westnordost** [comment]
I can reproduce it, by choosing to hide a quest, then undoing it (the hiding).

**Comment by westnordost** [comment]
Obsolete with new ui
