### ISSUE TITLE
What kind of police office is it ? (France only)

### ISSUE THREAD

**Issue by nlehuby** [westnordost/StreetComplete#1273]
### General
Affected tag(s) to be modified/added: `police:FR` & `operator` tags on [amenity=police](https://wiki.openstreetmap.org/wiki/FR:Tag:amenity%3Dpolice#En_France)
Question asked: **What kind of police office is it?**

This would be a France only quest.
We have [three kind of police forces](https://en.wikipedia.org/wiki/Law_enforcement_in_France) in France:
* "Police nationale": civilian police force, centralized at the national level. Mapped with operator & police:FR specific tags
* "Gendarmerie nationale": military one,  part of the French armed forces. Mapped with operator & police:FR specific tags
* "Police municipale": local police of towns, under the authority of the mayor. Mapped with police:FR specific tags

### Checklist
Checklist for quest 
- [x] 🚧 To be added tag is established and has a useful purpose
- [x] 🤔 Any answer the user can give must have an equivalent tagging (Quest should not reappear to other users when solved by one)
- [x] 🐿️ Easily answerable by everyone from the outside but a survey is necessary 
- [x] 💤 Not an overwhelming percentage of elements have the same answer (No spam)
- [x] 🕓 Applies to a reasonable number of elements (Worth the effort)

The kind of police is written on top of the building office, so it is quite easy to survey, even if you don't know about the details of French police forces.

About the last two items: as we just had a [Projet of the month](https://wiki.openstreetmap.org/wiki/FR:Project_of_the_month/Gendarmerie_nationale) about amenity = police, most of the "Gendarmerie nationale" are already ok in OSM.
But the quest will also be useful for maintenance because many police offices are still to be added.

### Ideas for implementation

**Element selection:** 
`amenity=police` without `police:FR` tag

**Proposed GUI:**
we could propose 3 building photos and let the user select the one that is the most similar. We already have [a MapContrib theme](https://www.cartes.xyz/t/5399a7-Commissariats_et_Gendarmeries#) that does that to pre-fill the tags when a new `amenity=police` is created:
![screenshot_2018-11-25 commissariats et gendarmeries - mapcontrib](https://user-images.githubusercontent.com/919962/48982019-42906c80-f0dd-11e8-8bb8-d45e5749c58c.png)

**Comment by matkoniecz** [comment]
> quick look there reveals that many other countries that divide their police forces in such categories (military, national, muncipal).

I can confirm that it is true in Poland. I think that this quest is viable, but it should be done with a proper tagging scheme rather than something France specific.

**Comment by nlehuby** [comment]
This has been briefly discussed in the French mailing list as part of the Project of the Month: https://lists.openstreetmap.org/pipermail/talk-fr/2018-November/090863.html

There is also a `police` tag that may or may not have the same purpose ... 
No doc either https://wiki.openstreetmap.org/wiki/Key%3Apolice
And very heterogeneous values: https://taginfo.openstreetmap.org/keys/police#values

**Comment by westnordost** [comment]
I have read through the discussion, it seems that at least on the French mailing list, there is no opposition to this tag, on the contrary, everyone is quite excited about mapping this. Still, the introduction of a country-specific tag somewhat troubles me. StreetComplete is not MapRoulette, where everyone can create a mission ad-hoc, but the quests in the app are aimed to be more persistent and apply to, well, an audience as large as possible. And, also unlike MapRoulette, I am usually held responsible for what is in the app (and not the one who proposed it) and already I am not so convinced that a country-specific tagging system is the way to go here.

I see you are half-through with all the police stations in France already, having tagged 2084 of 5543 already. To create and maintain a quest for a bit over 2000 elements (and shrinking quickly) seems like a wasted effort for me. In the end, I think it is possible to make a quest out of what kind of police station a police station is, but then I think we first need a tagging scheme first that applies to more than just France.
Perhaps doing the research for that and coming up with a key + values that can be applied globally could be another topic for a (French) project of the month?

**Comment by westnordost** [comment]
Closing because no feedback for some time.

To be clear: It would be eligible as a quest to ask users what type of police station something is, but for this, it is necessary to come up with a globally valid tagging scheme through a normal proposal process first.

**Comment by exploide** [comment]
FYI:

Meanwhile, there is a proposed feature in discussion: https://wiki.openstreetmap.org/wiki/Proposed_Features/Police_facilites

I haven't checked if this is compatible with the tagging established in France, now.
