### ISSUE TITLE
migrate to tangram-es 0.10

### ISSUE THREAD

**Issue by westnordost** [westnordost/StreetComplete#1279]
Migrate to the new tangram-es version

**Comment by rugk** [comment]
:tada: Any new features/advantages this brings for StreetComplete?

**Comment by westnordost** [comment]
Hopefully a fix for a long-standing crash issue, minor performance improvements and a feature that means that I can remove a custom implementation for a lack of that feature. So, nothing big, but the migration is a bit more laborious.

**Comment by westnordost** [comment]
Ah, and the flicker when moving in to show a quest should be gone. (The flicker when zooming back out again though probably not)

**Comment by westnordost** [comment]
I spent all day today migrating to 0.10.0, though there are some issues. Apart from the curious interface change decisions, with which I can live with, the chief feature why I wanted to upgrade does not work correctly. I created issues for that. So without these fixed, I cannot upgrade and I am unsure overall if it would be worthwhile. Usually I expect of updates of a library that all the things will be better.

**On the pro side:**
- there is now a listener for map updates -> makes it easier and less error prone for updating compass, view direction, GPS accuracy and makes it possible to [this (last paragraph)](https://github.com/westnordost/StreetComplete/issues/48#issuecomment-290249247)
- a long standing crash issue is fixed. Probably.

**On the meh side:**
- there is now a function to focus on a certain bounding box. But it doesn't work correctly. -> If it works, saves me about 100 lines of hacky workaround code

**On the bad side:**
- new camera update interface (rotate, pan, zoom, ... camera) is pretty awkward and apparently not thought through -> leads to more code and possibly to abrupt animations / camera animation bugs or more hacky workaround code
- new gesture responder interface is bad -> leads to 50 lines of hacky workaround code on my side

**Comment by rugk** [comment]
> I created issues for that.

Would have been useful to link them here, so I guess these are https://github.com/tangrams/tangram-es/issues/1960, https://github.com/tangrams/tangram-es/issues/1962 and https://github.com/tangrams/tangram-es/issues/1961.
Two of these three are closed (though it does not look you were content with the solutions), so is https://github.com/tangrams/tangram-es/issues/1960 so important to block this?

**Comment by westnordost** [comment]
tangrams/tangram-es#1962 and tangrams/tangram-es#1961 are just meh, in that they create more work for me in exchange for no gain. Point 1 and 2 of tangrams/tangram-es#1961 is important though, because without this, I can not even drop the prior 100 loc of hacky workaround code I have to use until now. I created a new ticket, tangrams/tangram-es#2033

**Comment by rugk** [comment]
> This release includes a major update of the map rendering library (in order to satisfy new Google Play guidelines). 

[in beta 17 release](https://github.com/westnordost/StreetComplete/releases/tag/v17.0-beta1)

@westnordost I am curious, could you please specify what you are referring to? Why/what/how exactly is Google forcing you to do this?

**Comment by westnordost** [comment]
Starting February 2020, all apps that use native libraries need to ship 64-bit binaries for those as well (even though the 64-bit architectures are in general compatible with 32-bit binaries).

Up until 0.9.x, Tangram-ES did not include a binary for a certain 64-bit architecture. Tangram-ES 0.10.x introduced big breaking changes in the interface but finally included those binaries.
