### ISSUE TITLE
Ability to add opening days without times

### ISSUE THREAD

**Issue by Qwertie-** [westnordost/StreetComplete#128]
A few times I have seen restaurants which say "Open 7 days till late" Usually this seems to mean about 10:00 to 23:00 but it would be better to just put in the days that the place is open as guessing the opening hours is not particularly useful.

For the UI maybe a button that says "Add opening days without opening hours" on the day selection popup.

**Comment by westnordost** [comment]
Hmm. `opening_hours=Mo-Su` is not a meaningful information though, as such, it won't enable apps to show information like that it is now open or not. This is why I chose to not allow this input.

Your example "Open 7 days till late" also has a different meaning than `Mo-Su`. So, for any such textual descriptions of opening hours like "opens sometime in the afternoon and open till late" or whatever, there is a special answer option already where you can enter free text: The answer is called "No regular opening hours" or something like that, its primary use is to cover shops with opening hours like "on appointment".

I could perhaps rename it to "no clear opening hours", but this may be more confusing than the current one. Opinions?

**Comment by Jotam** [comment]
No, the old phrase "No regular opening hours" is clear and concise. I wouldn't change this.

**Comment by westnordost** [comment]
I'll close this then.
