### ISSUE TITLE
recycling containers are not levitating (location=overground/surface)

### ISSUE THREAD

**Issue by matkoniecz** [westnordost/StreetComplete#1280]
It may be a good idea to use `location=surface` rather than `location=overground` for recycling containers.

`location=overground` seems to be describing objects that are a bit above ground (say, raised pipelines), not objects on the surface

Disclaimer: `location=surface` is strongly StreetComplete-inspired tagging. I invented and documented it to allow implementing #1267 - see https://github.com/westnordost/StreetComplete/issues/907#issuecomment-368252490 

This issues was spotted (and discussed) starting from https://github.com/westnordost/StreetComplete/pull/377#issuecomment-442938794

I created a new issue to avoid it getting lost (and because I consider starting new discussions in old PRs/issues as an offtopic, let me know @westnordost if you prefer that over opening new issues).

**Comment by westnordost** [comment]
Is it possible some easy way to get only elements that were tagged (last) by a certain editor?

**Comment by matkoniecz** [comment]
That will miss cases where StreetComplete used edited and later edit was made with other edit but maybe it will be really rare.

But anyway it seems to not be available - there is filter by user ( https://wiki.openstreetmap.org/wiki/Overpass_API/Overpass_QL#By_user_.28user.2C_uid.29 ).

This feature is requested at https://github.com/drolbr/Overpass-API/issues/189

**Comment by westnordost** [comment]
So the thing you have available does what?

**Comment by westnordost** [comment]
Actually, `overground` does not mean _"(levitating) above the ground"_ but **_"On or above the ground."_** according to most dictionaries. So, the counterpart to underground. Basically a 1:1 translation to German is possible: _"überirdisch"_ which also means exactly that (not underground).
**See** https://en.oxforddictionaries.com/definition/overground , https://www.thefreedictionary.com/overground, google translate (it's getting better, you know)

Thus, I would say that the tagging for recycling containers is correct and the (new) `surface` value for `location` is unnecessary. Or well, perhaps to denote that something is **on** the ground, like [street art painted on roads](https://designtaxi.com/news/358329/Colorful-Striking-Street-Art-That-Is-Painted-Directly-Onto-Asphalt-Roads/) or the [Stolpersteine](http://www.stolpersteine-gelsenkirchen.de/stolpersteine_vorbereitung_gelsenkirchen.htm)

**Comment by rugk** [comment]
…[or deepl](https://www.deepl.com/translator#en/de/overground) translates it as "oberirdisch". IMHO practically the same as "überirdisch".

**Comment by matkoniecz** [comment]
> Thus, I would say that the tagging for recycling containers is correct and the (new) surface value for location is unnecessary. 

In that case I am closing.
