### ISSUE TITLE
Make MaxSpeed quest disabled by default

### ISSUE THREAD

**Issue by westnordost** [westnordost/StreetComplete#1281]
To confirm that a section of road really has no sign, the user is asked to walk to the beginning of the street and sometimes even to the next main street. Both requirements can be somewhat fuzzy for non-residential (through) roads. To _really_ walk to the end of the street/to the main street or perhaps even further to solve one quest requires the user to be somewhat diligent.
Especially casual users, the main target audience of this app, cannot be expected to be that diligent and may just input something they *think* is correct after a quick look. This leads to a questionable data quality. Looking at some random changesets during the cleanup (#1222) seems to confirm this.

Overall, the quest should be left to more experienced users which deliberately chose to solve this kind of quest. These users, as well as users who deliberately choose to solve quests where they need to go inside, can be expected to be more diligent to input correctly surveyed data.

It is a pity, since I put so much effort into the implementation over the time, but in the end I think it would be better overall, also in aspect of verifiability, to map the actual signs (as nodes) and only derive the maxspeed-tags from that.
Not sure if this is done already and it cannot be done with StreetComplete anyway, but I came to the conclusion that collecting the maxspeed data[ from Mapillary because of their great traffic sign detection](https://blog.mapbox.com/fast-traffic-sign-mapping-with-openstreetmap-and-mapillary-9914943460fc) may be the more efficient and in the end also the more effective alternative because of the missing overview and diligence one has while being on foot.

The message displayed when trying to activate the quest again in the settings could be:
_"This quest type is disabled by default because in order to correctly solve a quest of this type, you are often required to walk down and check the whole street for speed limit signs, not just the highlighted section. This requires a high degree of diligence."_

**Comment by matkoniecz** [comment]
> Not sure if this is done already

Yes, but on really small scale.  See traffic_sign=maxspeed.

> map the actual signs (as nodes)

Good idea, but requires much better editor support. It reminds me about the issue that I should open on Vespucci bug tracker, thanks!

> and only derive the maxspeed-tags from that.

I am not sure is it really doable.

**Comment by westnordost** [comment]
>> and only derive the maxspeed-tags from that.

> I am not sure is it really doable.

I do not mean automatically.

**Comment by matkoniecz** [comment]
> I do not mean automatically.

That would work. Main hurdle currently is that tagging individual maxspeeed signs is not really time efficient at this moment.

> It is a pity, since I put so much effort into the implementation over the time

It is really unfortunate :( But for what it is worth - at least it will be useful for some/many experienced mappers. For example I very rarely tagged maxspeed tags before StreetComplete become available.

**Comment by cyclingcat** [comment]
+1. I thought about opening exactly this issue some months ago but obviously forgot it then. In many, many cases it's quite hard to solve this quest without further investigation. Granted, this is valid for some other types of quests too (e.g. surface of agricultural roads), but in the case of speed limits the chance that someone makes a serious mistake is much higher IMHO. Therefore, I disabled this quest long ago on my device.

By the way: The same is valid for the "road lit" quest. It's often impossible (!) to solve these quests at daylight time when the lights are out. For example: Does a road light reach the (separately mapped) parallel footway as well? (It often does, but you cannot be sure until it's dark!) So I decided for me to disable this quest also and to deliberately reenable it if I go out for an evening walk in the dark, and it's probably worth a thought to disable this quest by default, showing a message text if a user reenables it. Suggestion: "This quest type is disabled by default because it's often impossible to solve these quests correctly at daylight time."

The cycling cat

**Comment by illumiN8i** [comment]
While using the beta, even after re-enabling the speed limit quest, I still see the notice "Never shown in US-MI" and speed limit quests are not shown. StreetComplete would be a very convenient way for me to add speed limits to OSM. Mapillary has images in my area, but they aren't tagging the speed limit signs.

**Comment by westnordost** [comment]
The speed limit quest is **always** disabled in the US, independent of user preference.

The reason is that there is no tagging scheme for tagging implicit speed limits that can be applied to the United States. In other words, StreetComplete does not know what to ask the user if he clicked on "there is no sign" and also not how to tag it because it is not defined in the wiki.
#813 has the details.

The current tagging scheme is inherently flawed in that it requires to define the exact "legal category" (e.g. road in business district, road in residence district, national park road, ...etc ) for implicit speed limits if one just wants to say that the speed limit is not signposted. I outlined this here: https://lists.openstreetmap.org/pipermail/tagging/2018-September/039195.html

And here is my research regarding those "legal categories" in the US in other countries is here: https://wiki.openstreetmap.org/wiki/Default_speed_limits
