### ISSUE TITLE
Include crossing_ref in queries?

### ISSUE THREAD

**Issue by rugk** [westnordost/StreetComplete#1286]
While adding https://github.com/westnordost/StreetComplete/pull/1269 to the wiki, I noticed that some nodes have a strange tagging:
* https://www.openstreetmap.org/node/1660432231 with `crossing_ref = zebra`

This is totally contradictory, as I think a zebra crossing with a traffic light makes no sense(?).
`crossing_ref = pelican` [as here](https://www.openstreetmap.org/node/1531981700#map=19/41.88931/12.49638&layers=N), [make sense](https://en.wikipedia.org/wiki/Pelican_crossing) as a pelican crossing just seems to be a crossing with traffic lights.
So, IMHO, the whole `crossing_ref` tag [is totally duplicating information](https://wiki.openstreetmap.org/wiki/Key:crossing) as it is tagged with other information, but well… it's used. The only thing that may not be covered is [that pegasus crossing](https://en.wikipedia.org/wiki/Pegasus_crossing). Even the [toucan](https://en.wikipedia.org/wiki/Toucan_crossing) can be represented with access tags, IMHO; and [whether it is a puffin is likely totally unimportant](https://en.wikipedia.org/wiki/Puffin_crossing)… :smile: 
So far, enough "exotic" birds/animals…

So the question is, maybe we should include that in queries related to crossing/traffic-light crossing? Or do you think that we rather ignore it? Don't know what strange tagging combinations appear there, too…

**Comment by matkoniecz** [comment]
> as I think a zebra crossing with a traffic light makes no sense

In Germany crossing with traffic light never (almost never?) have painted zebra markings. In Poland typical crossing with traffic lights have painted zebra markings.

**Comment by westnordost** [comment]
Well the animal names crossing_ref are kind of UK specific. It is better to use tags like `bicycle=yes/no` (tiger vs zebra) etc.
I'd rather ignore this kind of tagging. 
But you could propose to add a check to a QA tool (osmose/keepright) to find inconsistencies between what the value of `crossing_ref` implies and other tags on the crossing.

**Comment by matkoniecz** [comment]
> crossing_ref are kind of UK specific

Or at least were supposed to be. See http://taginfo.openstreetmap.pl/keys/crossing_ref#values (23k+ of crossing_ref=zebra in Poland that sort of makes sense and someother values that are likely complete nonsense).

But in SC context situation is straightforward and answer to

> maybe we should include that in queries related to crossing/traffic-light crossing? Or do you think that we rather ignore it?

is "ignore" as there is no situation where it would be helpful/desirable to use it as a filter (if I missed it - give a specific quest and how it would be exactly used).

**Comment by rugk** [comment]
> crossing_ref are kind of UK specific

As @matkoniecz already said, in practical usage [I doubt so](https://taginfo.openstreetmap.org/keys/crossing_ref#map). Also, at least in the US they seem to be called like that too; I found that mentioned in the linked Wikipedia articles quite often.

> In Germany crossing with traffic light never (almost never?) have painted zebra markings. In Poland typical crossing with traffic lights have painted zebra markings.

Ah, okay, so probably I should explain the situation in Germany: The [zebra crossing](https://en.wikipedia.org/wiki/Zebra_crossing) gives the pedestrians :walking_man: :walking_woman: *always* priority over anyone else (:car: :bike: :motorcycle: :motor_scooter:  :motor_boat:). As in Wikipedia EN:
> A zebra crossing typically gives priority to rights of way to pedestrians. 

As they also say:
> In other countries, zebra crossings are also used on pedestrian crossings controlled by traffic signals.[2][citation needed]

Citing one Swiss source (https://www.tcs.ch/de/testberichte-ratgeber/ratgeber/verkehrsregeln/fussgaengerstreifen.php). @matkoniecz, you may add some of the wanted citations there… :wink:

So okay, I get this tagging may then be okay in some countries as is not an issue?

**Comment by westnordost** [comment]
Yeah, anyway crossing ref is not so closely related to crossing that it must be considered in the crossings quest.
