### ISSUE TITLE
Changes are not synced before login

### ISSUE THREAD

**Issue by Aschroet** [westnordost/StreetComplete#1287]
After installing the app i expected that i can do anonymous edits (without logging in with my account). Despite what was described (https://wiki.openstreetmap.org/wiki/StreetComplete/FAQ#How_does_the_app_handle_uploads.3F) the changes were not synched to OSM. Only after i made this login via the settings menu i saw the queued changes in OSM.

If a login is a prerequisite for synching the changes the credentials should be provided by the user during the first usage of the app. Or if not there should be some kind of warning that changes are not synched as long as the user does not provide this infomation. The FAQs should be updated accordingly.

**Comment by matkoniecz** [comment]
Sounds like case of #1283 and it should be fixed with the nearest app update.

**Comment by Aschroet** [comment]
@rugk i am quite sure that i did not get the request to authorize after my first change (a friend of mine stated the same). Then, this is a bug report.
But anyway it should be clear for the not yet logged in user that all its changes are queued. As already mentioned all this could be avoided by just have a mandatory authorization step at the first startup.

**Comment by westnordost** [comment]
You can start answering the quests without being logged in but the app will ask you every time to login. That the app did not ask for login is a bug in 8.4 and has been fixed for the next version (see #1282)
