### ISSUE TITLE
Quest: maxspeed

### ISSUE THREAD

**Issue by flohoff** [westnordost/StreetComplete#129]
If there is no maxspeed on highway=* except living_street it could be requested.

Probably with a maxspeed:source e.g. the German Zone maxspeeds.

living_streets at least in Germany dont have an explicit maxspeed so we should exclude them.

Flo

**Comment by westnordost** [comment]
Obvious and easy to implement. Thanks for the input.

**Comment by andrewharvey** [comment]
> living_streets at least in Germany dont have an explicit maxspeed so we should exclude them.

But in other parts of the world they might.

**Comment by Jotam** [comment]
I would definitely use this. Thanks!

**Comment by my-na-me** [comment]
I would also like to have this implemented.

> westnordost commented 5 days ago: "Obvious and easy to implement. Thanks for the input."

Hopefully easy to implement, because I know there are also some available street sections which have forward and backward tags. (see http://wiki.openstreetmap.org/wiki/Key:maxspeed >> Extended tagging >> Driving direction)

**Comment by flohoff** [comment]
After i opened the issue it came to me that with all the tag edit on roads we might have issues with road splitting in the near future. surface/maxspeed/lit will not always apply to whole of the road. The first thing to work around this might be to only show/edit roads with a max length of e.g. 500m or something. Later StreetComplete might offer to split a road by tapping on the road or something ...

**Comment by matkoniecz** [comment]
In my region maxspeed-related edit will typically include splitting roads, In addition in may case >500m heuristic would not help - typically such long ways are trunk/motorway roads with the same maxspeed for big chunks.

**Comment by westnordost** [comment]
The intended mechanism here is to answer "can't answer" in this case and write in a note why. I.e. "south of Flohoff Street, continues as cobblestone street, north of there asphalt".

**Comment by westnordost** [comment]
Done
