### ISSUE TITLE
problems with opening hours crossing midnight

### ISSUE THREAD

**Issue by matkoniecz** [westnordost/StreetComplete#1292]
Some places are closed after midnight (typically nightclubs, bars etc). In that case, at least in my region it is common to write opening hours like "Monday 20:00-2:00" to indicate that it is open from 20:00 Monday to 2:00 AM at Monday/Tuesday night.

StreetComplet opening hours quest happily accepts such syntax and writes it to OSM, but it ends raising warnings in opening hours parser and get misinterpreted.

See https://www.openstreetmap.org/node/279040195 for a real example, see http://openingh.openstreetmap.de/evaluation_tool/?EXP=Mo-We%2010%3A00-01%3A00%3B%20Th%2CFr%2010%3A00-03%3A00%3B%20Sa%2012%3A00-03%3A00%3B%20Su%2012%3A00-01%3A00&lat=50.0612594&lon=19.9318205 for results

For example I would expect that on Saturday this object is open from midnight to 3:00 AM and later from noon to the midnight.

**Comment by matkoniecz** [comment]
SC should at least complain or block opening hours crossing midnight (closing hour before opening hour).

**Comment by rugk** [comment]
IMHO it should just re-write them in a "conform" way. I'd say for a user it's okay to enter it like that, for data consumers it may be difficult…

**Comment by westnordost** [comment]
Hmm, are you sure that this is invalid syntax? I find Fr 20:00-03:00, Sa 16:00-03:00 pretty unambiguous, not only from a common sense perspective but also for parsers, because it is each ONE range. This is also the reason why the OH tool can detect and warn about it at all.

It makes no sense to warn or disallow entering OH that cross midnight if such OH are are just copied from the sign like that. Instead, if this is really an error, SC would need to handle this automatically. 

Though, as said, it would translate an easy to read and understand OH into something more cryptic and rather something intended for machines than humans. E.g. Fr 20:00-24:00, Sa 00:00-03:00, 16:00-24:00, So 00:00-03:00. Note that with this translation, the information that 20:00-03:00 actually belongs together is lost.


Am 14. Dezember 2018 18:53:07 MEZ schrieb Mateusz Konieczny <notifications@github.com>:
>Some places are closed after midnight (typically nightclubs, bars etc).
>In that case, at least in my region it is common to write opening hours
>like "Monday 20:00-2:00" to indicate that it is open from 20:00 Monday
>to 2:00 at Monday/Tuesday night.
>
>StreetComplet opening hours quest happily accepts such syntax and
>writes it to OSM, but it ends raising warnings in opening hours parser
>and get misinterpreted.
>
>See https://www.openstreetmap.org/node/279040195 for a real example,
>see
>http://openingh.openstreetmap.de/evaluation_tool/?EXP=Mo-We%2010%3A00-01%3A00%3B%20Th%2CFr%2010%3A00-03%3A00%3B%20Sa%2012%3A00-03%3A00%3B%20Su%2012%3A00-01%3A00&lat=50.0612594&lon=19.9318205
>for results

**Comment by westnordost** [comment]
Looking in the specification, I found this sentence:
"If time wraps over midnight are involved then you will probably also need to use additional rules to not overwrite the part which wraps into the next day."
https://wiki.openstreetmap.org/wiki/Key:opening_hours/specification#explain:timespan:time

It does not sound like that spanning midnight is illegal syntax. Though, I am not sure if SC properly handles the case described in the article. Someone cares to check?


Am 14. Dezember 2018 18:55:43 MEZ schrieb Mateusz Konieczny <notifications@github.com>:
>SC should at least complain or block opening hours crossing midnight
>(closing hour before opening hour).

**Comment by goldfndr** [comment]
The specification uses an [extended_time](https://wiki.openstreetmap.org/wiki/Key:opening_hours/specification#extended_time) concept for [time span](https://wiki.openstreetmap.org/wiki/Key:opening_hours/specification#timespan) endings.

So, for conformity, `Mo-We 10:00-01:00; Th,Fr 10:00-03:00; Sa 12:00-03:00; Su 12:00-01:00` should perhaps be rewritten as `Mo-We 10:00-25:00; Th,Fr 10:00-27:00; Sa 12:00-27:00; Su 12:00-25:00` to avoid the dual time ranges inherent in `Mo-Th 00:00-01:00,10:00-24:00; Fr 00:00-03:00,10:00-24:00; Sa,Su 00:00-03:00,12:00-24:00`.

**Comment by matkoniecz** [comment]
Mo-We 10:00-25:00; Th,Fr 10:00-27:00; Sa 12:00-27:00; Su 12:00-25:00 is also confusing for parser

http://openingh.openstreetmap.de/evaluation_tool/?EXP=Mo-We%2010%3A00-25%3A00%3B%20Th%2CFr%2010%3A00-27%3A00%3B%20Sa%2012%3A00-27%3A00%3B%20Su%2012%3A00-25%3A00&lat=50.0612594&lon=19.9318205&mode=0&DATE=1544819460000 

maybe parser is wrong and should be fixed, I have not checked specification so far

**Comment by goldfndr** [comment]
Indeed. The [extended_hours_minutes explanation](https://wiki.openstreetmap.org/wiki/Key:opening_hours/specification#explain:extended_hour_minutes) makes no mention of times greater than 24:00 being treated differently than times less than 24:00. The parser simply converts all times to minutes (with [MINUTES_MAX=1440](https://github.com/opening-hours/opening_hours.js/blob/master/js/yohours_model.js#L70)); the days arrays go to MINUTES_MAX, not MINUTES_MAX*2 (with consolidation). So there's a readability difference, not a semantic difference. Ouch.

**Comment by westnordost** [comment]
Wait, where exactly in the specification does it say that Su 12:00-25:00 etc is ok?

**Comment by westnordost** [comment]
Ok, to wrap this up, I looked at the warning emitted by the OH tool in the very first post. It makes exactly the same suggestion as https://github.com/westnordost/StreetComplete/issues/1292#issuecomment-447410415
I am going to check if StreetComplete already handles this case correctly and if not, fix it today, before releasing 9.0
