### ISSUE TITLE
Please refer to the list of StreetComplete quests in the OpenStreetMap somewhere in the app

### ISSUE THREAD

**Issue by Natenom** [westnordost/StreetComplete#1294]
Sometimes when trying to solve a quest I need more information to decide. Especially when the quest is something I did not yet do in OpenStreetMap. What I do in such a situation is to open $SEARCHENGINE and try to get information about the quest in the OpenStreetMap-Wiki and not always find the tag/key I need.

Then it would be very useful for me to have a link to the list of SC quests in the OSM wiki, for example in "About" -> "Help for Quests".

https://wiki.openstreetmap.org/wiki/StreetComplete/Quests

**Comment by westnordost** [comment]
StreetComplete does not show any tags. Can you tell me with which quests exactly you are unsure what to choose?

**Comment by Natenom** [comment]
I know there are some issues but can't describe them exactly now because I didn't use the app for some time.

I will give you an answer when able to go outside and use the app. Currently I am ill.

**Comment by rugk** [comment]
Yeah, I think maybe a link in the "About" section or so may be nice (i.e. for StreetComplete users that may want to learn more what StreetComplete/OpenStreetMap does "behind the scenes", so to convert users in the other direction), but well… it's not that important. :smile:
