### ISSUE TITLE
Railway crossing missing 'no crossing' for tunnel or fly over

### ISSUE THREAD

**Issue by PanderMusubi** [westnordost/StreetComplete#1295]
Railway crossing missing tunnel or fly over, see example. Perhaps, road and railway are in the incorrect layer, but even then an option "they do not cross on the same level" or "no crossing" would be minimally needed in the answers.

![screenshot_20181219-092724](https://user-images.githubusercontent.com/198964/50208081-89862080-0370-11e9-96c1-6a1710dcffba.jpg)

**Comment by matkoniecz** [comment]
In case of survey detecting that there is walkover or tunnel without level crossing "can't say" can be used to create an OSM note.

Completely broken data may happen in many ways and StreetComplete is fundamentally unable to handle all possible cases.

**Comment by PanderMusubi** [comment]
I understand that not all possible cases can be handled. However, some newbe or conservative minded users might think: "Yes, I can say, there is no crossing."

Since this quest is introduced, it appears on many railway stations that have a tunnel or a level above the tracks. Hence, this issue as it is not a single incident.

**Comment by rugk** [comment]
Can you probably point out, where this happened?

**Comment by PanderMusubi** [comment]
Some stations in the Netherlands. But if this is a clear error in the map, I will create notes on these so that they can be fixed. Think that is the best way.

**Comment by PanderMusubi** [comment]
I left notes, that should fix it.

**Comment by rugk** [comment]
Yeah, I just asked to see the exact error/wrong tagging _if_ SC were to exclude it, we would have to know it, of course. That said, as other's said we cannot exclude any edge case/wrong tagging. But as you closed this issue, I think there is no need to discuss that further…

**Comment by PanderMusubi** [comment]
It looked at something that was popping up in many places, as the conditions were similar, but it turns out that there are not that many and the conditions also change. Found four different settings for about 30 crossings that aren't there.

**Comment by westnordost** [comment]
Just as a note: Even if the user could specifically answer that it is not on the same level, the mistake could not be fixed   automatically by StreetComplete because a proper fix would include also ungluing the crossing point from one another. However, SC can only change taggings.

Am 19. Dezember 2018 16:19:13 MEZ schrieb rugk <notifications@github.com>:
