### ISSUE TITLE
Quest suggestion: Kitchen opening hours 

### ISSUE THREAD

**Issue by JoKeyser** [westnordost/StreetComplete#1297]
### General
Affected tag(s) to be modified/added: https://wiki.openstreetmap.org/wiki/Key:opening_hours:kitchen
Question asked: **What are the kitchen opening hours?**

### Checklist
Checklist for quest suggestions (see guidelines):
- [ ] 🚧 To be added tag is established and has a useful purpose
- [x] 🤔 Any answer the user can give must have an equivalent tagging (Quest should not reappear to other users when solved by one)
- [x] 🐿️ Easily answerable by everyone from the outside but a survey is necessary
- [x] 💤 Not an overwhelming percentage of elements have the same answer (No spam)
- [x] 🕓 Applies to a reasonable number of elements (Worth the effort)

**Proposed GUI:** Just like for opening hours.

**Comment by JoKeyser** [comment]
I'm not sure if the tag is established and has a useful purpose.

**Comment by JoKeyser** [comment]
I would also argue that for many places, the kitchen hours are visible from the outside. However if they are not, then it becomes even more useful to have them mapped by survey into OSM.

**Comment by JoKeyser** [comment]
Maybe the quest could also be restricted to places where the opening hours are likely different from the kitchen hours (like for restaurants), but not for fast food places etc?

**Comment by ENT8R** [comment]
> 🚧 To be added tag is established

At least the wiki says that there was no proposal at all and also the usage is not that wide spread... (only about 900 times used)

> 🐿️ Easily answerable by everyone from the outside

At least from my own experience, I would say that there are only a few restaurant which have this information posted and really visible and easily accessible...

> However if they are not, then it becomes even more useful to have them mapped by survey into OSM.

I don't think that every surveyor will ask about the kitchen hours inside of the restaurant if no information is visible outside...

---

So IMO this quest is actually a good idea, but there are some things which speak against implementing it 😞

**Comment by rugk** [comment]
I just "Why not use the opening hours quest?", but then I got it: These are a different kind of hours.

So while I agree that this does not really fit for a new quest, I totally see how it is useful. So what about including it in the opening hours quest? I've often seen plates, where both times were visible and it was hard for me to answer.

So:
Other answer -> "There are multiple times as the kitchens closes earlier"

(only for restaurants etc. obviously shown)

**Comment by rugk** [comment]
BTW the reason why the tag may not be popular could be the one stated in the wiki:
> service_times=* should probably be preferred over opening hours for a kitchen (kitchens aren’t open to the public nor to the customers, typically)

**Comment by rugk** [comment]
Okay I have to admit [this also does not return a lot of elements](https://overpass-turbo.eu/s/EEB).

**Comment by JoKeyser** [comment]
@ENT8R , @rugk thanks for your input.

Indeed, how often kitchen hours are accessible from the outside may vary between areas. However in cases where it isn't, I would argue that asking about them is comparable to asking about toilets (#1272), so if that's OK for a quest, this should be too.

The alternative tag `service_times` seems too vague for me for restaurants, because kitchen hours refer exclusively to the serving of dishes, while drinks and snacks might still be available later on. My interpretation of "service times" seems too unspecific.

**Comment by westnordost** [comment]
I am basically with @ENT8R on this one. Far from every restaurant will have explicit and fixed kitchen times apart from the normal opening hours. Too many times, the user will have to answer that (💤), if it is even possible to tag that (🤔). Also, that the times will be posted on the outside is somewhat rare and users should not be required to go inside and ask to solve the quest (🐿️). Finally, the tag is not really established (🚧) and used on very few elements (compared with the number of restaurants in total) (🕓)

**Comment by westnordost** [comment]
Ah, and of course, if the user actually find a opening hours plate that mentions separate kitchen times, he can always leave a note instead and explain the opening hours (or make a photo)

**Comment by JoKeyser** [comment]
@westnordost  for the record, I understand the reasoning to close this, but still disagree :).

I'll look into the tag business and hope that `opening_hours:kitchen` will get more established in the wider community and then maybe come back to this.

In any case, thanks for the consideration everybody, and of course for all the work on the app.
