### ISSUE TITLE
Add is drive through

### ISSUE THREAD

**Issue by ferdinand0101** [westnordost/StreetComplete#1299]
Only for restaurants

**Comment by ENT8R** [comment]
Would probably be spam, as most restaurants won't have it...
And also: please fill out the quest suggestion issue template if you want to propose a new quest so we can see all pros and cons at once...

**Comment by rugk** [comment]
Also likely a dupe of https://github.com/westnordost/StreetComplete/issues/104

**Comment by FloEdelmann** [comment]
For reference: It was suggested (properly with a filled issue template) again in #4656.

This issue is not a duplicate of #104; that one is about `takeaway` rather than `drive_through`.
