### ISSUE TITLE
Flickering Sprite over Center of Map

### ISSUE THREAD

**Issue by sknorr** [westnordost/StreetComplete#130]
On CM13 (Android 6), I get a flickering sprite over the center of my screen in StreetComplete 0.7 (from F-Droid).
This did not happen in StreetComplete 0.5 on the same OS/device.

When panning, the size of the flickering sprites varies between covering almost the entire screen and the size shown below. Resetting data for the app did not help.

Screenshots:
https://m.imgur.com/SIw4wf9
https://m.imgur.com/QrCuir1

**Comment by hjanetzek** [comment]
Hi! I've build some versions to track down which change in tangram-es might cause the issue. Please test if you have the chance.

[app-debug-master.apk.gz](https://github.com/westnordost/StreetComplete/files/947311/app-debug-master.apk.gz)
[app-debug-no-vao.apk.gz](https://github.com/westnordost/StreetComplete/files/947314/app-debug-no-vao.apk.gz)
[app-debug-no-mapbuffer.apk.gz](https://github.com/westnordost/StreetComplete/files/947315/app-debug-no-mapbuffer.apk.gz)

**Comment by transmit-receive** [comment]
@hjanetzek As requested: CyanogenOS 12.1.1, Android 5.1.1
-master: still crashes after seconds
-no-mapbuffer: still crashes after seconds

-no-vao: **works fine!** 
Street names are now correctly displayed
no crashes anymore, and - as far as I can see -
no disappearing quest icons anymore
Thanks for the quick fix!

**Comment by hjanetzek** [comment]
@transmit-receive thanks for testing!  We'll make a tangram bugfix release asap.

**Comment by sknorr** [comment]
Pretty much the same for me as for @transmit-receive: -master has the bug, -no-mapbuffer has the bug too but is less flickery (but also crashed for me), and -no-vao works exactly as expected.

Thanks!

**Comment by vmiklos** [comment]
Here is what I see:

-no-vao: no street names, no unexpected flicker
-no-mapbuffer: no street names, no unexpected flicker
-master: no street names, unexpected flicker

So yes, -no-vao at least solves the flickering part. :-)

**Comment by vmiklos** [comment]
Given that I guess Android-4.4 breaking isn't too interesting I upgraded to Android 6.0 in the meantime and there both issues are solved out of the box when just installing the latest play store version. So if it would be only me complaining about these missing street names on Android 4.4, ignore me. :-)

**Comment by Phyks** [comment]
I also noticed on Andrid 4.4.2 that when panning the map, the quest icons stay in place and take some time to adjust their position. I guess they should be moving in sync with the map.

I guess this is related to this issue, but if it is not the case, I can open another one.

**Comment by westnordost** [comment]
It's fixed upstream now.
