### ISSUE TITLE
Orange buttons on pre-lollipop devices

### ISSUE THREAD

**Issue by ENT8R** [westnordost/StreetComplete#1307]
While developing the dark mode (#1306) I encountered an issue on pre-lollipop devices.
The map control buttons are using the accent color of the app because they are using the `RoundButton` style (https://github.com/westnordost/StreetComplete/blob/master/app/src/main/res/values/styles.xml#L75-L80). This means that they are using the orange accent color (only on devices with API < 21)
Could it be that this style should only be used by the "OK" button of the quests but not of the map controls?
<img src="https://user-images.githubusercontent.com/25306497/50551502-c2cc6380-0c81-11e9-8645-7df4465c4102.png" width="300px">

**Comment by westnordost** [comment]
Yes, this is definitely a bug.
