### ISSUE TITLE
parking lots not rendered in map

### ISSUE THREAD

**Issue by tikeyknax** [westnordost/StreetComplete#1308]
Parking lots are not rendered in the map. This can be strange when using the app to check the data. Especially, as the quests regarding the parking spaces are still displayed. 
One example can be found here:
https://www.openstreetmap.org/way/111649631#map=19/49.37259/7.08022

**Comment by ENT8R** [comment]
The mapstyle is not very detailed so the user doesn't get distracted by it. This is also the reason why some things like parkings, pitches or any other kind of landuses all have the same color. If you want to have some more information I advise you to visit the repository of the mapstyle: https://github.com/ENT8R/streetcomplete-mapstyle

**Comment by pkoby** [comment]
I would consider whether the recent update to the map tiles might have left them out? In my area, for awhile I had a bunch of buildings that were about a month out of date, now I'm back to having no buildings, as well as a bunch of major roads simply missing from the map tiles.

**Comment by tikeyknax** [comment]
Thanks for your comments.
It is of course possible that this is done on purpose. However, I find not seeing the parking lot more distracting than seeing it. In the example above, it just looks plainly wrong. Also, the app shows quests about them. I.e. the app now shows quests about objects that are not even displayed in the map. I found that to be confusing. But if that's just me or if there are other reasons not to show the parking spaces, that's of course fine.

I've also double checked about the out of date thing. The parking lot was added 5 years ago, so I think that shouldn't be the issue.

**Comment by westnordost** [comment]
> I would consider whether the recent update to the map tiles might have left them out? In my area, for awhile I had a bunch of buildings that were about a month out of date, now I'm back to having no buildings, as well as a bunch of major roads simply missing from the map tiles.

The admin of the map tile server currently took it offline again to try something out that will make it easier to update the tiles in the future. So, for the moment, the map tiles from nextzen, which are old, are shown again.

**Comment by pkoby** [comment]
I knew I saw something about the tiles, but I didn't realize they reverted. It's kind of strange how I'm missing roads, though.

Good to know about the progress!

**Comment by matkoniecz** [comment]
@tikeyknax

> Especially, as the quests regarding the parking spaces are still displayed.

It is caused by loading days for quest from one source with recent data (overpass turbo) and map data from another (rendering server on shoestring).

**Comment by westnordost** [comment]
moved to other bugtracker
