### ISSUE TITLE
Streetcomplete total vs OSM my edits

### ISSUE THREAD

**Issue by moneyninja** [westnordost/StreetComplete#1311]
Apologies if this is covered elsewhere or not the correct place to ask this.

I've been using StreetComplete for a few months now and have submitted 400+ quests but when I look on OSM it only shows 63 under My Edits, I know half of these were likely made in through JOSM so there seems to be a very large disparity.  
I've checked OSM and it doesn't look like anyone else has beat me to entering the data so just curious if I'm missing something obvious?
Thanks

**Comment by HolgerJeromin** [comment]
If you enter 20 surface quests the app shows 20. But the data is uploaded in a single changeset so you see only a 1 on the osm.org websith.

**Comment by moneyninja** [comment]
Thanks for the speedy answer, much appreciated!
