### ISSUE TITLE
Offer direct input of times instead of the dial

### ISSUE THREAD

**Issue by hmartink** [westnordost/StreetComplete#1313]
For entering times, e.g. for shops, currently a dial is offered. This dial is awkward to use on a mobile, especially when the temperature is low like in winter. It would be much more useful if the numbers could be entered directly, especially if lots of time values have to be entered (like for some shops).

**Use case**
I'm standing in front of a shop. My son wants to continue and I would like to enter the opening times. It is winter. If I could quickly type in the times then this would be possible, but with the dial often it is interrupted (fingers are not precisely) and I have to redo the input, taking lots of time.

**Proposed Solution**
Either switch to an input box accepting legal time values as numbers (like on web pages from train companies, e.g. www.bahn.de) or offer this kind of input as an option (for people who like the dial).

**Comment by ENT8R** [comment]
I don't think that (especially new) users will know the correct tagging scheme for opening hours...
If it would be implemented the way you propose it, users will have to read https://wiki.openstreetmap.org/wiki/Key:opening_hours or another instruction before making their first edit. I don't think that's something we want, especially as there should be no knowledge about OSM in general if you want to use this app...
BTW: what do you think is awkward about the time picker? IMO this is one of the best UIs one can imagine for this purpose 😄

**Comment by hmartink** [comment]
When entering letters / numbers I only have to briefly hit the screen, and if I miss the key, I remove it and reenter. Easy. If I want to use the dial, I need to hold it, get the right circle and move the dial. And many clocks are digital now, so the dial is not universal. Also I can easily jump forward and backwards between the hour and minute.
Also I'm not sure I need to read a wiki page to enter opening times. To make sure, the UI could have "o'clock" or the native equivalent ("Uhr") hardcoded behind the values, e.g.
__;__ o'clock
where the user would enter the values at the places I put an underscore (_).

**Comment by ENT8R** [comment]
> Also I'm not sure I need to read a wiki page to enter opening times.

The opening hours need a specific format so they can be understood by other third party apps. And I still don't think that every user of StreetComplete is aware of the opening hours tagging scheme...

**Comment by westnordost** [comment]
@ENT8R There is a misunderstanding. The proposal is to use a simple (number) input field instead of the Android default time picker field to input the hours. E.g. [ 08 ] : [ 00 ] - [ 12 ] : [ 00 ] instead of the dial

**Comment by pkoby** [comment]
I'm not a fan of forcing this. As an option, I don't mind. But I like the dial time picker, especially for opening hours, because most of the time it's on the hour or at hour:30. I think the picker snaps to five-minute intervals, so a close-enough tap will find the minute. If an opening hour is like 10:42, then the shop has problems, not the time picker.

**Comment by rugk** [comment]
I never had a problem with the time picker, it aligns fit

**Comment by goldfndr** [comment]
My personal favorite time picker is the ["List" "Improved Time Picker" ](http://android.calengoo.com/pagedoc/pageedit/styled/pagetimepicker.html) (last image) in CalenGoo. A 6x6 grid: 24 spots for hours, 12 for 5 minute increments; lends itself to 12h and 24h time. Only a couple of drawbacks:

* I have no idea if there's a patent on it.
* It doesn't handle the full range of 00-59 minutes. On the other hand, I'm skeptical that non-5s (other than text) are ever used (other than transcription mistakes).

**Comment by rugk** [comment]
@goldfndr looking at the screenshots I do not find that superior. It's design look really outdated (like android 2, I.e. no material design) and I guess you first have to learn how to select it in the last screen with all these buttons. IMHO it's not really intuitive.

Maybe the idea of "tabs" though can be used. One tab for "time picker" and one for "numeric input".

**Comment by hmartink** [comment]
For me this would be a nicer UI. 
In English locales the UI already offers AM/PM (at least on your screenshot), but I agree that this would be hard to translate to e.g. German (though I would naively enter all times in 24 hour format intuitively.

**Comment by westnordost** [comment]
So, there doesn't seem to be a clear preference to switch from the Android default time picker to something self-made. So, I'd rather not invest any time in this then. That'd be another piece of code I would have to maintain as well.

**Comment by rugk** [comment]
AFAIK newer Android versions offer this thing which has a button at the bottom left, so you can switch to keyboard input. This should fix this issue here. :smile: 

![image](https://user-images.githubusercontent.com/11966684/58992671-c2656500-87eb-11e9-9849-be02d0fc1190.png)

([source](https://social.tchncs.de/@jeybe/102220775891579644), from Öffi)
