### ISSUE TITLE
Add "select all" button when all quest types are deselected

### ISSUE THREAD

**Issue by rugk** [westnordost/StreetComplete#1316]
Follow-up of https://github.com/westnordost/StreetComplete/issues/1203

**Use case**
Likely the same as in https://github.com/westnordost/StreetComplete/issues/1203, it's just some UX improvments.

E.g. one: "I accidentially selected the 'deselect all' button.".

**Proposed Solution**
When I click the "deselect all" button, nothing is selected anymore. Thus, afterwards the button has no effect anymore.

IMHO that button should then change to "select all" afterwards, so I can revert the previous deselection. (see use case above)

---

Thinking about it more, maybe just choose the button action based on how many quests are selected? 
I.e. when few (or 0) quests are selected, button should be "select all", otherwise "deselect all".

As said, I was not really happy with that whole solution when https://github.com/westnordost/StreetComplete/issues/1203 was closed, anyway. A proper way for "profiles" would certainly solve that in a much better way.

**Comment by westnordost** [comment]
Won't implement because I find the explained use case not convincing.
