### ISSUE TITLE
Pictures in questdialog are not visible

### ISSUE THREAD

**Issue by Ruediger34** [westnordost/StreetComplete#1317]
On my factory resetted Galaxy S3 with Android 4.3 and StreetComplete 9.0 the pictures of a questdialog are not visible. A picture shows up if it is selected and disappears immediately if another one is chosen, see following screenshot:

![screenshot_2019-01-06-21-33-51](https://user-images.githubusercontent.com/20127481/50781402-94fca580-12a5-11e9-9e3a-d8b01eb6ea31.png)

It also happens on other quests than the one in the screenshot.

I can also confirm the orange buttons #1307 .

**Comment by westnordost** [comment]
I hope this is not just a Samsung S3 issue. The older Samsung devices, especially S3 and S4 are somewhat idiosyncratic
