### ISSUE TITLE
Do not ask "How is this railway crossing protected?" on railway crossings on private roads

### ISSUE THREAD

**Issue by matkoniecz** [westnordost/StreetComplete#1321]
It is both hard to survey for (in some cases may be doable only for people working there) and value of this information is really low.

It typically happens within railway yards.

See say https://www.openstreetmap.org/node/1674572452#map=19/50.02815/20.00323 on https://www.openstreetmap.org/way/28013394#map=19/50.02815/20.00323 

I can do that, unfortunately it will make query more complicated.

**Comment by matkoniecz** [comment]
I can do that, unfortunately it will make query more complicated.

**Comment by westnordost** [comment]
👌

**Comment by matkoniecz** [comment]
First step, an overpass query is now completed.

```
way["highway"]["access"~"^private|no$"]({{bbox}});
(._;>;);
node(w) -> .private;
node["railway"="level_crossing"]({{bbox}})->.crossings;
(.crossings; - .private;)->.public;
.public;
out;
```
http://overpass-turbo.eu/s/FC1

**Comment by matkoniecz** [comment]
I see no reason to exclude just private service roads, rather than all private roads.

**Comment by matkoniecz** [comment]
It seems that discarding all `highway=*` with `access=no` or `private`, also ones with `foot=*` tagged is OK. See http://overpass-turbo.eu/s/HB0 listing cases where railway intersects with `highway=*` with with `access=no` or `private` and overriding `foot` tag.
