### ISSUE TITLE
After answering a quest, the following quest takes long time to appear

### ISSUE THREAD

**Issue by Ruediger34** [westnordost/StreetComplete#1323]
I don't know if it is a bug or a osm related issue or all work as designed.

For a better understanding I will describe my workflow: 
I walk through streets and will look on StreetComplete for possible quests.
In non-well mapped areas usually the building type quest is the first to answer on buildings. 

If the building type answer is submitted I usually expect the housenumber quest to appear immediately.
But I have to wait about an hour if the housenumber quest is shown.
(StreetComplete has a working data connection to internet)
I have also tried to search for new quests (after building type was answered) and to mark the quest cache as invalid with no success.

Is it possible that all following quests (building type -> housenumber) are shown immediately if the first is answered?

Why I want that?
I am standing in front of a building and will look at the type that I can answer and I also know that there is no housenumber. But I will not wait for an undefined time for the next (housenumber) quest and I will also not go through streets two or more times.

Thank you.

**Versions affected**
StreetComplete 9.0

**Comment by matkoniecz** [comment]
The problem with housenumber quest is that it requires some tricky geometry checks - for example building without address, within area with address should not be included in quest.

It is necessary as in some cases for example the entire hospital area has a single address.

As result StreetComplete runs query for address quest candidates not on smartphone but asks overpass turbo.

**Comment by matkoniecz** [comment]
And it runs this query from time to time, so as result some address quest may appear hours or days after building type was solved.

Solving this would require reimplementing overpass API to run on phone - what is not feasible as it would run extremely slowly, consume massive amounts of memory and eat through the entire battery.

**Comment by matkoniecz** [comment]
In short: you identified you issue that is unfortunately really hard to fix (in practise nearly impossible) :(

**Comment by westnordost** [comment]
@matkoniecz correctly summarized the issue. For most quests, the mechanic works exactly as you describe it: When you upload the answer to a quest, the app looks for another quest that may have become eligible after that change and shows it. However, this does not work for a few quests that have a logic for appearing-or-not too complicated to be solved offline (without using Overpass-Api). One of these is the housenumber quest, another is the cycleway quest. There may be a few others, I can't remember from the top of my head.
In any case, it is not feasible to do an overpass query for the surrounding area for every single quest you solve, but that would be the only solution to this UX problem.
