### ISSUE TITLE
New quest: Add address to restaurants/food/… (for FragDenStaat)

### ISSUE THREAD

**Issue by rugk** [westnordost/StreetComplete#1324]
### General
Affected tag(s) to be modified/added: obvious
Question asked: **Is this the correct address?**~~/**Is here a restaurant?**~~

### Checklist
Checklist for quest suggestions (see guidelines):
- [x] 🚧 To be added tag is established and has a useful purpose (story below)
- [x] 🤔 Any answer the user can give must have an equivalent tagging (Quest should not reappear to other users when solved by one)
- [x] 🐿️ Easily answerable by everyone from the outside but a survey is necessary (survey is totally recommend, because this is the only 100% reliable way to verify the address; user can see street signs or even address written, so this should always work)
- [x] 💤 Not an overwhelming percentage of elements have the same answer (No spam) (all different answers :wink:)
- [x] 🕓 Applies to a reasonable number of elements (Worth the effort)

### Background

FragDenStaat and Foodwatch started the campaign "Topd Secret". They use the German freedom of information act to request information about official hygienic reports. But the details are off-topic here. [During this campaign, they encountered a problem of the OSM data](https://fragdenstaat.de/blog/2019/01/30/topf-secret-dev/). To quote them:
>die OSM-Daten haben zwar immer einen Geobezug, aber leider oft keine Adresse hinterlegt, die aber für die Anfrage an die Behörde wichtig ist

**translated:**

> OSM data always have a geo reference, but unfortunately lack of an address, which is however important for the request to the agency.

## Solution

So maybe we can fix that problem/data with StreetComplete.

Because they also describe they have implemented a reverse-geocoding and thus limited the cases for potential quests to the [quest list here](https://fragdenstaat.de/kampagnen/lebensmittelkontrolle/app/osm-hilfe/), which has a website version.
Or wait, no, [this list, lists addresses that are not listed in OSM, not addresses with missing address tags](https://fragdenstaat.de/kampagnen/lebensmittelkontrolle/app/osm-hilfe/)…
~~However, that may also easily fit into a quest, i.e. "Does this restaurant exist here?" and then just yes/no, which adds the restaurant.~~ Okay, no, this can hardly be verified without seeing OSM nodes nearby, so forget it.

So maybe we should limit this to confirming addresses? (after you've got them from reverse geocoding) @stefanw, would this help?
In this case, we just need the list of node and (reverse geocoded) addresses. This can then be presented to the user and they can just "confirm" or "deny" that the address matches. (They also detect deleted restaurants this way…)

### Ideas for implementation

**Element selection:** specific `amenity` and `shop` tags, filtered by data above?

**Metadata needed:** possibly no country restriction, as the case itself (no clear address) can happen worldwide, but we may start with Germany first anyway, as we have data there.

**Proposed GUI:** show the name of the restaurant and the address that we suspect below. If missing, offer input fields. Let the user confirm the address?

/ccing @stefanw from @okfde

**Comment by matkoniecz** [comment]
Can you give example of OSM element where address is missing and it would be useful to add it?

**Comment by rugk** [comment]
I hoped @stefanw could explain what data may be needed/adjusted in a better way. I only wanted to spark the idea here, and do not have insides into the data that is there and what things are missing.

So I'd like to forward that question to @stefanw.

**Comment by westnordost** [comment]
I can think of the following situations which may occur and where people may argue that this is not really a missing information:
- address is tagged on the building or area outline that includes that shop
- address is tagged on the entrance(s) of the building
- address is tagged on an "address relation" (didn't know that existed, but found this in Hamburg) and the shop is member of that relation

**Comment by matkoniecz** [comment]
And in cases where nothing of above applies, the correct solution is to map address on building (or optionally on node places within building outline), what is already supported by SC.

**Comment by westnordost** [comment]
Okay, this stefanw also did not describe it here, so I'll close it.

**Comment by rugk** [comment]
Hmm, maybe someone else from @okfde like @arnese maqy be interested in improving the data for TopfSecret in this app? (Please refer to the history of this ticket?)

I know they are busy.

**Comment by stefanw** [comment]
Sorry for not reacting earlier.

This is basically about POIs (like restaurants) lacking address tags. Right now we have to reverse geocode the restaurant node without addresses to get an address.

[Here is an example](https://www.openstreetmap.org/node/678298228). There is a nearby house number address node, but the `amenity:restaurant` node does not have address tags. I'm sure there could be a solution for this.

**Comment by rugk** [comment]
@westnordost Could you reopen this for the discussion?

**Comment by westnordost** [comment]
No, because what has been written before still applies

Am 14. September 2020 22:32:23 MESZ schrieb rugk <notifications@github.com>:
>@westnordost Could you reopen this for the discussion?
