### ISSUE TITLE
Quest enhancement: Surface for footways etc.

### ISSUE THREAD

**Issue by Sora1248** [westnordost/StreetComplete#133]
I suggest to add highway=footway, highway=cycleway and highway=path to the "Road Surface" quest so pedestrian, bicycle, wheelchair, inline skating, whatever routing can benefit from surface information, too.
Without surface information these "optimal" routes can have some muddy surprises (speaking from experience).

**Comment by westnordost** [comment]
I'd probably try to find different "panorama" images for ground, unpaved, paved first that depict ways rather than roads.

**Comment by Natenom** [comment]
@westnordost I can make photos if you can't find some.

**Comment by westnordost** [comment]
You can, but I cannot guarantee you if I like them ;-)
Here is what I need:

They must be
* **generic**: neither clearly any particular type of way, i.e. cycleway, forest path or a sidewalk nor any particular type of pavement (<- this is hard)
* **symbolic**: not contain many distinctive features that deviate from their meaning (= paved, unpaved, ground). That's why I chose country roads for the road pictures

And should be
* **international**: try to be as generic country/region wise as possible. I.e. the road panorama are from Italy, US and I think somewhere in South East Asia
* **straight**: like the road pictures, also ~same perspective

**Comment by HolgerJeromin** [comment]
I think your current highway images are working really good even with footways, cycleway or all highways.

**Comment by rindlerblabla** [comment]
So do I.

**Comment by westnordost** [comment]
Yeah but on the other hand, it is not really that much effort to find 3 more way-like pictures.

It needs to be an own quest anyway because the question, the icon shall be different and because it should be counted in a different category later for the statistics (not in "road" category, but in "pedestrian/cycle" category)

**Comment by gappleto97** [comment]
I also like the current pictures, and think they're pretty applicable here.

**Comment by matkoniecz** [comment]
Recent changes to surface quest interface strongly deemphasized generic images. Is it still necessary to find separate images for paths and cycleways?

**Comment by westnordost** [comment]
Imo yes. Also c'mon, it's just three pictures.

  On February 5, 2018 at 9:15 AM Mateusz Konieczny <notifications@github.com> wrote:
 
 
 Recent changes to surface quest interface strongly deemphasized generic images. Is it still necessary to find separate images for paths and cycleways?

**Comment by BjornRasmussen** [comment]
I have some photospheres that might work for tracks:

https://drive.google.com/file/d/1VzhiJin8IUIMFnQzOLeyDurttyeVPnbuXA/view?usp=drivesdk

https://drive.google.com/file/d/1UTCdX9MdcchIHnQBoRfB2C8IoG4ZsKlKAg/view?usp=drivesdk

https://drive.google.com/file/d/1RJn5CW_AijVCWWtQ_cKHXmGFksTZ2ua9SQ/view?usp=drivesdk

https://drive.google.com/file/d/1WzgNFt9REDWXkSWnufWcUYDfTlSOg-QYnQ/view?usp=drivesdk

https://drive.google.com/file/d/16ACozF0ckZIiCCAZ7E-YuLHQLwEngNJzWQ/view?usp=drivesdk

**Comment by westnordost** [comment]
They are good pictures! This is the quest for footways though but perhaps they can be used for this as well. @ENT8R has a PR open for track types.
What is the license for these pictures?

https://drive.google.com/file/d/1RJn5CW_AijVCWWtQ_cKHXmGFksTZ2ua9SQ/view could be for paved
https://drive.google.com/file/d/16ACozF0ckZIiCCAZ7E-YuLHQLwEngNJzWQ/view for unpaved
and https://drive.google.com/file/d/1VzhiJin8IUIMFnQzOLeyDurttyeVPnbuXA/view perhaps for ground. Though, for ground, I guess just as well the picture from the street-surface quest could be used.

**Comment by BjornRasmussen** [comment]
I own the photos, but would be delighted if StreetComplete used them!  If it is necessary to release them into the public domain, I can do that.  You mentioned that this is a foot path quest, so I decided to take some more photospheres of foot paths.  

Paved foot path:  https://drive.google.com/file/d/11C0ylKtvr60sI3snocuGnwpPK7kKl2ko/view?usp=sharing

Unpaved foot path: https://drive.google.com/file/d/1i1xnoKc3LrSzNPSWcnKlIG9HCeh_iFHE/view?usp=sharing

Ground foot path: https://drive.google.com/file/d/13NEa_a64Q4KNRSCux8hA9f7oRp0idyp5/view?usp=sharing


Also, I thought that the unpaved track photo was not obviously unpaved. (Looked too much like asphalt in my opinion)  Here is a better unpaved track photo: https://drive.google.com/file/d/1BvehpmF461AKmRc2XSV7MrYTojFLlMeI/view?usp=sharing

The photo I took of a paved track was a little too dark too clearly see that it was paved.  Here is a better one:  https://drive.google.com/file/d/1jA0r2jhg8POxrowjRJZE18ttOQhl1fWJ/view?usp=sharing

For ground, I think that the existing image in StreetComplete will work well.  That one should be retained.  (I could not find a good track with surface ground in my area to photograph)

We can either make tracks and footpaths different quests or just keep them together as one.  I don't have strong opinions on that.  One thing we definitely need to keep in mind is [greenways](https://goo.gl/maps/48nLKzupvCD2)).  In the USA, a greenway is usually a 3 meter wide paved trail designated for use by any pedestrian or non-motorized vehicle.   They are usually tagged as "highway=cycleway" in OSM and should definitely be included in the Footpath-Surface quest.

**Comment by rugk** [comment]
>  If it is necessary to release them into the public domain, I can do that.

Public domain is possible, but not required. You can also [choose](https://choosealicense.com/non-software/) a license like a [Creative Commons one](https://creativecommons.org/choose/), but choose one, which is a "free culture" license.

**Comment by westnordost** [comment]
CC-BY-SA or CC-BY would be possible

**Comment by BjornRasmussen** [comment]
I officially release the following six images under the Attribution 4.0 International (CC BY 4.0) license.   

https://drive.google.com/file/d/11C0ylKtvr60sI3snocuGnwpPK7kKl2ko/view?usp=sharing
https://drive.google.com/file/d/1i1xnoKc3LrSzNPSWcnKlIG9HCeh_iFHE/view?usp=sharing
https://drive.google.com/file/d/13NEa_a64Q4KNRSCux8hA9f7oRp0idyp5/view?usp=sharing
https://drive.google.com/file/d/1BvehpmF461AKmRc2XSV7MrYTojFLlMeI/view?usp=sharing
https://drive.google.com/file/d/1jA0r2jhg8POxrowjRJZE18ttOQhl1fWJ/view?usp=sharing
https://drive.google.com/file/d/192R5OPNlOctTUs1YBl7dto182HXGdE6z/view?usp=sharing

============================================================

For paths, I think that we should include the option to choose bricks as a surface.  Brick paths are very common where I live.  I added a suitable image of bricks at the bottom of the list of images above.

**Comment by matkoniecz** [comment]
>  include the option to choose bricks as a surfac

I considered bricks to be a type of paving stones in my tagging.

**Comment by westnordost** [comment]
It is, but that doesn't make it wrong. Strictly speaking, even sett is a type of paving stone.

**Comment by matkoniecz** [comment]
> Strictly speaking, even sett is a type of paving stone.

To be more exact: I considered them suitable for surface=paving_stones (that at https://wiki.openstreetmap.org/wiki/Key:surface is described as "A relatively smooth surface paved with artificial blocks (block pavers, <b>bricks</b>) (...)"

**Comment by BjornRasmussen** [comment]
The wiki does not have bricks listed as a suitable tagging, however, the ID editor includes it as a preset.

**Comment by westnordost** [comment]
@BjornRasmussen 
Hmm I think there might be a problem with these photos. The panorama photos usually have (maximum) dimensions of 1152x384px (for smartphones with super-high pixel density). The (center) portion of these pictures that would be usable is just about half of that resolution. Do you have these pictures in higher resolution?

**Comment by BjornRasmussen** [comment]
They are 6144 x 3072 pixels.  Is that not high enough resolution?

**Comment by BjornRasmussen** [comment]
After I crop them to the correct size for use in StreetComplete, the resolution is still 1164 x 482.

**Comment by westnordost** [comment]
I decided to use the "track" photos (paved, unpaved) for the path quest (which includes paths, cycleways, footways, bridleways, steps) because it is not untypical for a path to be this broad and anyway, the scale of ways are not really obvious anyway. The track photos simply have more of the way on the photo, which I think is better than to show too much stuff on the left and right side.
