### ISSUE TITLE
Sidewalk quests should not be shown in roundabouts

### ISSUE THREAD

**Issue by waldyrious** [westnordost/StreetComplete#1332]
The new sidewalk quest introduced in v10 shows for all ways, including roundabouts. I'd say this is a case (there may be others) where that quest does not make sense, so it shouldn't even be shown at all.

**Comment by matkoniecz** [comment]
> I'd say this is a case

Why? Can you link more specific situation and why it makes no sense to ask this? For example in Poland roundabouts may have sidewalks or not (see for example https://www.openstreetmap.org/?mlat=50.08983&mlon=19.90345#map=19/50.08983/19.90345 for roundabout with a sidewalk).

**Comment by waldyrious** [comment]
Ok, I see what you mean. Still, I think only the outside of the roundabout would be a candidate to have a sidewalk, right? Not only from a semantic perspective, but also since the interface for inputting the information the in the app is a diagram depicting a linear section of the roundabout curve, which may confuse people about which side is the inside and which is the outside.

**Comment by rugk** [comment]
> I think only the outside of the roundabout would be a candidate to have a sidewalk, right?

I know roundabouts, where the sidewalk is actually _inside_ of it. (don't knopw who invented this design, but possibly for big roundabouts it makes sense)

**Comment by matkoniecz** [comment]
> diagram depicting a linear section of the roundabout curve

Right, this one is likely to be confusing and clearly a problem.

**Comment by waldyrious** [comment]
Ok, so if neither inside nor outside a roundabout should be omitted from the sidewalk quest, I guess this issue can be closed.

Alternatively, it could be reused to track a better interface for such "two-sided" quests when applied to very tight curves (not only roundabouts, but also loop ramps, etc.)

What do you guys think?

**Comment by westnordost** [comment]
@matkoniecz Not *that* confusing, though. I saw this in a similar situation already. The form shows the orientation of the road *at the quest pin*. If you know that, it is clear. Also, the compass in that form is a help, in case of doubt.
