### ISSUE TITLE
Force Close with v10.0

### ISSUE THREAD

**Issue by zossebart** [westnordost/StreetComplete#1333]
Since version 10.0 the app is force-closed very often, in fact it is unusable for me right now.

**How to Reproduce**
- Open the app.
- solve a quest (questtype seems to be irrelevant)
- after solving the quest, the app is closed and the android popup about it is shown
- re-open the app -> app is closed right away
- re-open the app -> app is running again, but closes after solving one quest

**Versions affected**
SC 10.0
Android 5.1.1

Does it help you if I submit a bug report via the android popup?

**Comment by westnordost** [comment]
What device do you use? Sony Xperia X?

**Comment by zossebart** [comment]
Nearly, it's a Sony Z1 Compact.

**Comment by westnordost** [comment]
Hmm, then I do not see the crash in the logs. Could you do one thing: In the settings, turn off auto-sync, and then, press on the upload button. Does it crash at the moment you press on the upload button?

**Comment by westnordost** [comment]
Also: 

> Does it help you if I submit a bug report via the android popup?

I overread this. Yes, it absolutely helps. If you press "no", I can't see the crash in the overview.

**Comment by zossebart** [comment]
Ok, did the manual upload. I could see the star counter going up step by step (there were 3 quests to upload). After the 3rd counter update the crash happened. Did send the bug report for the crash after app restart...

**Comment by westnordost** [comment]
Hmm, no crash report showed up in the google play console. Maybe it takes a while till it shows up.

If you installed the APK not via the Play Store but for example install the APK directly
https://github.com/westnordost/StreetComplete/releases/download/v10.0/StreetComplete-v10.0.apk
(or via F-Droid, but it is not there yet), crashes can instead be sent via Email directly to me.

**Comment by zossebart** [comment]
Did another one a minute ago. Maybe the last one wasnt submitted because I gave no comment...

**Comment by westnordost** [comment]
Nope, don't see anything. I guess maybe it takes a while to be visible for the developer.

**Comment by westnordost** [comment]
Hm, still got no error report. Perhaps you could install the app from F-Droid https://f-droid.org/en/packages/de.westnordost.streetcomplete/ , then, crashes can be sent via email directly to me.

Otherwise, do you remember which quest type it is for which the upload crashed the app?

**Comment by zossebart** [comment]
One last try...it was a road surface type quest. If you still don't see it by this evening, I'll install the Fdroid version.

**Comment by pkoby** [comment]
I am also having consistent crashing, also Play Store installed. I have submitted a couple of error reports too, so hopefully you see them.

I'm also on Android 5.1.1 on a Nexus 4.

**Comment by westnordost** [comment]
Nothing arrived. :-(

@zossebart I remembered that if you install it from F-Droid, it uses a different signature which makes this like a complete reinstall, so all your not-uploaded quests are cleared. Then of course, you will not be able to reproduce the crash (for now).
There is another way that should work: I prepare for you a special version, that is like StreetComplete v10.0 but additionally prompts the user to send any crash that occurs via email to me. It has the same signature as the one on Google Play, so this should work. Would you download and install this?:
https://www.westnordost.de/misc/StreetComplete-v10.1-reportCrashesViaEmail.apk

**Comment by zossebart** [comment]
I already did the uninstall of the playstore version and installed the f-droid version this noon. Reproduced the bug with it...but no means of sending an email with the bug report. The popup only showed an ok button.

Thank you for the special version! You should have received a mail now...

**Comment by westnordost** [comment]
ok, fixed
