### ISSUE TITLE
Something in Hanoi old quarter is blocking quest downloads

### ISSUE THREAD

**Issue by dbdean** [westnordost/StreetComplete#1338]
When I try and download quests around my hotel in Hanoi Old Quarter (https://www.openstreetmap.org/#map=17/21.03254/105.84891), I get a 'Connection Error' when trying to download quests:

![image](https://user-images.githubusercontent.com/12725310/52911509-c6cb4800-32f8-11e9-9a26-0528cfa99678.png)

I have to go a fair way out of Hanoi (like https://www.openstreetmap.org/#map=15/21.0033/105.9115) before I can find a spot that will let me download quests (which are a bit harder to get to from a walk around my hotel room!):

![image](https://user-images.githubusercontent.com/12725310/52911543-5c66d780-32f9-11e9-8e8a-bd38cfcd2092.png)

Is this something to do with some feature in the area breaking the overpass queries or something like that?

**How to Reproduce**
Try to load quests around Hanoi using StreetComplete.

**Versions affected**
StreetComplete 10.0 on Android 9 on a Pixel 1

**Comment by westnordost** [comment]
Thanks for the report, I will look into it!

**Comment by rugk** [comment]
Any special network connection? (I see you are using WLAN. Does it possibly work without wifi enabled?)
And – if you use your workaround to download quests – are quests then actually shown inside Hanoi?

**Comment by westnordost** [comment]
Okay, the culprit is an open note in that area with no text, no initial comment. I think this note should not exist in the first place, so I created a bug report for openstreetmap-website: https://github.com/openstreetmap/openstreetmap-website/issues/2146

For 10.1, I will add a check whether the note has no initial comment and ignore it if there is none.

**Comment by JeanFred** [comment]
I had a similar thing in Vienna in the past few days (I was trying to debug it yesterday by unticking quests until the search succeeded ^_^) − thanks for fixing!

**Comment by dbdean** [comment]
Thanks for the quick fix, and the subsequent quick release. It works now!
