### ISSUE TITLE
Increase visual distinction of images of sidewalk quest (& switch them)

### ISSUE THREAD

**Issue by rugk** [westnordost/StreetComplete#1339]
**Use case**
The sidewalk quest presents you with two images, currently. However, when you e.g. have bad light conditions (bright light/sun/…), you can hardly read the text and distinguish these both (very similar/"greyish") images from each other.
This can lead to accidentally choosing the wrong image.

**Proposed Solution**

IMHO you may e.g. add a green tick to the "yes answer/image", i.e. "has a sidewalk" and  a red cross to the negative answer, i.e. "has no sidewalk".

Also, maybe it is just me, but I am a little confused that the negative answer is on the left(?). Am I the only one, who is confused by that?
I am more accustomed to the fact that "yes" is always the first option you present, i.e. "Has a sidewalk? Yes/No" not "Has a sidewalk? No/Yes"… So IMHO, you should also switch the position of the elements.

**Comment by westnordost** [comment]
It is the same order as with the cycleway quest

**Comment by rugk** [comment]
Yes, but cycleway has much more options… (it's not just yes/no, so I did not notice it there)

**Comment by matkoniecz** [comment]
I agree that contrast is quite poor and at first difference is not obvious.

**Comment by westnordost** [comment]
I'd rather not change the icons, so rugk's suggestion about adding a checkmark and cross on top of it seems to be the best solution
