### ISSUE TITLE
Quest suggestion: Building type

### ISSUE THREAD

**Issue by Sora1248** [westnordost/StreetComplete#134]
A lot of buildings are tagged just with building=yes, especially when these buildings were drawn from aerial photos or cadaster maps. A quest might be used to ask for the specific type of a building as a short list of the most common building types and feature the full list of building types under "other answers".

List of possible buildings: http://wiki.openstreetmap.org/wiki/Key:building
Most common values for building: https://taginfo.openstreetmap.org/keys/building#values

Maybe this can be combined with the building levels quest somehow as this will probably generate a lot new quest items for the building level quest.

**Comment by Etua** [comment]
#25

**Comment by Sora1248** [comment]
Oops! Missed that when I was looking for an existing request for the building types.
