### ISSUE TITLE
"Are pedestrians prohibited from walking on this road here?" quest should be changed

### ISSUE THREAD

**Issue by Mannivu** [westnordost/StreetComplete#1342]
I think that a quest should ask "yes" for "yes" and not "no" for "yes". Therefore, I think that the quest "Are pedestrians **prohibited from walking** on this road here?" (which result is "foot=yes" if you click "no" and "foot=no" if you click "yes") should be changed into "Are pedestrians **allowed to walk** on this road here?", so that clicking "yes" would mean "foot=yes"

**Comment by ENT8R** [comment]
The wording of this quest has been changed intentionally with https://github.com/westnordost/StreetComplete/commit/32e20dd7c5658f39815a1545ab3dcd7a22f366c2 in v10 the question was the way you propose it right now, but there was a huge discussion on the tagging mailing list: https://lists.openstreetmap.org/pipermail/tagging/2019-February/042852.html about this quest which lead to the reworing of the question. Did you already read that thread?

**Comment by rugk** [comment]
So I clicked through that big discussion there, and here seem to be the important points for this issue:
* https://lists.openstreetmap.org/pipermail/tagging/2019-February/042894.html - here the negated question was suggested
* https://lists.openstreetmap.org/pipermail/tagging/2019-February/042915.html - here @westnordost agreed to change it:
  > So I'll negate the wording to specifically ask for it being forbidden.

---

IMHO the users/requests only wanted to have the "accessible" changed to something that implies _legally_ accessible...
No one requested having the wording turned around. (It is likely just the first thing that comes into your mind.) 
So the focus was on adding that pedestrians are legally allowed/forbitten to enter, in contrast to a stone blocking their way or so. 😉 

So IMHO the OPs question does carry the same meaning:
> "Are pedestrians **allowed to walk** on this road here?"

"_allowed to_" is certainly a legal term and I agree that such a question should be "linguistically positive", i.e. "yes" means "allowed to". (Especially if other quests do it in the same way, whcih I am not sure about though.) As such, I support the OPs request.

Alternatively one can also rename the button to make things clearer, e.g. "Is allowed" vs "Forbitten" or so.

**Comment by westnordost** [comment]
Asking for it being prohibited tends to imply that it is allowed if it is not explicitly forbidden. Asking for it being allowed tends to imply that it is forbidden unless explicitly allowed.

As the default is that pedestrians are allowed on roads (and more generally in law: all is allowed unless forbidden), it is clearer to ask for it being forbidden.

**Comment by rugk** [comment]
Okay, fair enough. I get the argument, but also get the confusion about this wording.

So possibly some way with renaming buttons?
> Are pedestrians **prohibited from walking** on this road here?
> [Yes, forbitten] [No]

(the exceptional is highlighted with a longer word/term)

Or the reverse?
> Are pedestrians **prohibited from walking** on this road here?
> [Yes] [No restriction]

(possibly also "No known restriction" or so to highlight the uncertanity)

**Comment by Mannivu** [comment]
I fully understand the complaints in the newsletter and I understand why the change was made. I support the idea of renaming the buttons to make clearer to the user what they are doing when clicking "Yes" or "No". Moreover, I'd like to make another suggestion: since the task asks if pedestrians are prohibited to walk on a road, maybe the task icon should be changed to something like this 🚷 or ![image](https://upload.wikimedia.org/wikipedia/commons/thumb/8/8f/UK_traffic_sign_625.1.svg/20px-UK_traffic_sign_625.1.svg.png) so that it's immediately clear the task asks for a prohibition.

**Comment by westnordost** [comment]
I rather do not change the wording of the YES NO buttons. The button would need to match the wording in the question and this may sound weird in certain languages. Even in English, it is marginal: "Are ... prohibited from ...?" - "Yes, prohibited". One would expect "Yes, **it is** prohibited" but this is already too long for a button there. There are enough other YES / NO quest(ion)s in the app and it was always quite clear. It depends on the question being clear.

Also, I would rather not change the icon because this may imply that it can only be forbidden if there is a sign, which is not the case.

**Comment by matkoniecz** [comment]
Not sure is it just me, but I multiple times answered 

> Are pedestrians prohibited from walking on this road here?

in opposite way than intended (I answered "yes" where they were allowed).

I also thought about changing icon a bit and adding crossing through.

![1708_-_No_pedestrian_crossing-512](https://user-images.githubusercontent.com/899988/59751705-4f46fe80-9281-11e9-9b7e-2183348127cf.png)

> this may imply that it can only be forbidden if there is a sign, which is not the case.

Not sure how big trouble this would be. For me that would be far less confusing, but maybe for others situation would be opposite :(

**Comment by rugk** [comment]
@matkoniecz Good point. I guess UX-feedback is always important. And the quest icon should indeed match the question IMHO, because I (likely others too) then tend notto read the question, because you "know"™ what the question is about… (and make mistakes)

Is this possibly worth a new issue though?

**Comment by westnordost** [comment]
Id prefer to have the red ring with red strike and white background be inside the blue circle, same as how the icon for the maxweight looks like

**Comment by Mannivu** [comment]
So, something like ![this](https://www.safetynetwork.com.au/wp-content/uploads/images/products/R6-15B.jpg)?

**Comment by matkoniecz** [comment]
> inside the blue circle (...) same as how the icon for the maxweight looks like

Looking at maxweight icon (`ic_quest_max_weight`) rendered as quest icon I see no blue circle

**Comment by westnordost** [comment]
![drawing](https://user-images.githubusercontent.com/4661658/62731706-14607c00-ba23-11e9-8812-ea8a68039847.png)

dadadidab dudab dadadadadudida
There is something strange...
