### ISSUE TITLE
Recycling Quest doesn't work for all cases

### ISSUE THREAD

**Issue by Discostu36** [westnordost/StreetComplete#1343]
The recycling_type quest does not work for all possible cases of amenity=recycling. 

According to the wiki it's possible to use this tag for places where people can dispose of their christmas trees for a limited time of the year. The proposed tagging is `recycling:christmas_trees=yes` with `opening_hours=*`. No recycling_type is fitting for these, but StreetComplete does ask for one. This is leading to incorrect tagging like in [this changeset](https://www.openstreetmap.org/changeset/67380218).

**Comment by HolgerJeromin** [comment]
I would consider that a bad tagging idea  even if this is documented

**Comment by rugk** [comment]
@Discostu36 So do you have any idea/proposed solution?

**Comment by westnordost** [comment]
For cases like these, there is always the "Can't answer" button where you can instead describe the problem at that point. Looking at taginfo, maybe tag it with recycling_type=dump?
