### ISSUE TITLE
build is failing for some reason

### ISSUE THREAD

**Issue by matkoniecz** [westnordost/StreetComplete#1344]
It started in https://github.com/westnordost/StreetComplete/commit/7d007c6b760483c5174ef1d54667b46e38f4cc5e - https://travis-ci.org/westnordost/StreetComplete/builds/493434504?utm_source=github_status&utm_medium=notification

Continues to fail in for example https://travis-ci.org/westnordost/StreetComplete/builds/497260913?utm_source=github_status&utm_medium=notification

**Comment by westnordost** [comment]
Forgot to update a test
