### ISSUE TITLE
Accessible on foot quest - support for foot=use_sidepath and sidewalk=separate

### ISSUE THREAD

**Issue by westnordost** [westnordost/StreetComplete#1345]
I noticed that it is quite common that in situations like these (https://www.openstreetmap.org/way/24911912), people tag `sidewalk=no` instead of `sidewalk=separate`. As far as I know, it is not (even) considered incorrect.

This leads to the situation that this app asks surveyors for road segments like these whether pedestrians are prohibited from using this road. I see two problems with this:
1. This may be confusing for the surveyor, as he is probably just walking on the sidewalk when answering this - it is not clear whether "this road here" refers to just the highlighted section in the app, or to "this road here, including sidewalk".
2. Even if `sidewalk=no` is not a mistake, it is imprecise, and StreetComplete would contribute to propagating this imprecision further by tagging `foot=no` in this case ("No you may not walk on the road, because there is a sidewalk")

So, I think a clarification is needed for the user:
1. Tell the user that this quest is asked because `sidewalk=no` is tagged on the road section, so that he can leave a note if this information turns out to be wrong. (This used to be the case in v10.0, but I foolishly removed the hint when I reworded the question after the mailing list discussion)
2. Create the possibility for the user to correct the sidewalk-tagging to `sidewalk=separate` and `foot=use_sidepath`

I was thinking that I could add the following description and add an additional button named "sidewalk" to the form:
_"This street was tagged as having no sidewalk on either side. In the case that there is a sidewalk after all but it is displayed as separate from the road, please answer 'sidewalk'."_

Opinions?

**Comment by rugk** [comment]
> people tag `sidewalk=no` instead of `sidewalk=separate`

Do you know whether people™ do this with StreetComplete or is this independent and just a usual error sometimes made by SC?
Because if it is done by SC, you would of course need to fix the sidewalk quest, not the foot accessible quest… (Or in general you can fix that.)

---

So I think 1. is not a controversial thing and can quickly be done – and I liked it in v10 and was actually surprised to see it is removed. As for 2. I have no strong opinion.

**Comment by westnordost** [comment]
> Do you know whether people™ do this with StreetComplete or is this independent and just a usual error sometimes made by SC?

This is independent of SC. In fact, it is very unlikely that this is tagged by StreetComplete users.
