### ISSUE TITLE
Opening times depending on the day

### ISSUE THREAD

**Issue by Jehan** [westnordost/StreetComplete#1346]
I tried my first quest. It was asking the opening time of a place nearby me. First screen is the opening days, then opening times. Unfortunately opening times are not the same for every day! This place in particular has different opening times for Tuesday, Wednesday and Friday, then others for Thursday, and finally a third set of times for Saturday.

The quest does not allow such accuracy.

I was hoping "Other answers" would allow this kind of case, but it was not available (there is a "change monthly", but this is not the case here; and the non regular schedule time neither, since it is regular!).

**How to Reproduce**

- Select the quest for the opening times of "Maison des Associations" (8 rue Général Renault 75011 Paris, France), then try to answer.
- Official times are available here: https://www.mairie11.paris.fr/mes-demarches/vie-associative/la-maison-des-associations-du-11e/informations-pratiques-et-presentation-generale-272#horaires_4

**Versions affected**

StreetComplete 10.1 on Android 5.1, but I don't think it matters here. :-)

**Comment by matkoniecz** [comment]
> This place in particular has different opening times for Tuesday, Wednesday and Friday, then others for Thursday, and finally a third set of times for Saturday.

> The quest does not allow such accuracy.

Have you tried selecting Tuesday, Wednesday and Friday selecting opening hours and later adding opening hours for Thursday and so on before marking that you are done?

**Comment by matkoniecz** [comment]
> I tried my first quest.

Welcome! What you mentions should be possible but maybe interface can be improved to make clear what is happening. Thanks for creating issue and feedback what is unclear.

**Comment by guushoekman** [comment]
For what it's worth, I did my first quest relatively recently and thought it was quite clear to simply select the appropriate days.

@Jehan you can simply pick the days which have the same times and repeat the process for the remaining days.

![Screenshot](https://i.imgur.com/QWRa43f.jpg)

**Comment by Jehan** [comment]
> Have you tried selecting Tuesday, Wednesday and Friday selecting opening hours and later adding opening hours for Thursday and so on before marking that you are done?

> you can simply pick the days which have the same times and repeat the process for the remaining days.

Oh ok! I didn't realize that was how it was working. I thought that in the first steps, we had to choose every opened days, then the next step was the time for all the days. I didn't get that you could continue later choosing more days.
Anyway now it works fine.

> maybe interface can be improved to make clear what is happening

Indeed. Though to be fair, I'm not sure either how to make it clearer without being excessively boring. But if you find, then it's worth it. :-)

P.S.: small unrelated question: at the very end, it asks if we checked the times on the very spot (not sure how it is worded in English, I got the translated one). So if I checked on the official website instead, you don't trust the information and I should not push it?

**Comment by matkoniecz** [comment]
StreetComplete is rather intended to be used during survey - during walking/cycling around some place.

> So if I checked on the official website instead, you don't trust the information and I should not push it?

I would say that it is preferable to check in a given place (though if you are 100% sure that official website is not outdated it would not be a big mistake to use that data).

**Comment by Jehan** [comment]
> though if you are 100%

Well who can be 100% sure?! ;-)
Even signs on doors are sometimes outdated, so…

Anyway thanks. For the current report, do as you wish since it turns out what I asked was indeed possible.
Though you can keep it opened to track better wording or adding usage notes if you want and can find something appropriate to make this clearer! :-)

**Comment by rugk** [comment]
> Well who can be 100% sure?! ;-)

Someone, who is standing in front of the sign, reading it. :wink: (as others said, this is the use case of SC)

> Though you can keep it opened to track better wording or adding usage notes if you want and can find something appropriate to make this clearer! :-)

:+1:

**Comment by westnordost** [comment]
Well, I am open to concrete ideas for a clearer UI. I will close this issue though because the issue of the user is solved
