### ISSUE TITLE
Adjust german text for building type "Bahnhofsgebäude"

### ISSUE THREAD

**Issue by FountainMapper** [westnordost/StreetComplete#1347]
German word "Bahnhofsgebäude" for building type is too general. Think about using "Empfangsgebäude" or "Bahnhofsempfangsgebäude".

Just noticed this small building: https://www.openstreetmap.org/way/233828304/history
It was changed to building=train_station. 
Check out this related note including link to photo: https://www.openstreetmap.org/note/1650743
The StreetComplete user changed several train related(!) buildings to train stations. Using a more precise text may reduce this.

**Comment by westnordost** [comment]
Hm, the wiki says "[a train station building](https://wiki.openstreetmap.org/wiki/DE:Tag:building%3Dtrain_station)", in the German article, it is "Bahnhofsgebäude" (not Empfangsgebäude or Bahnhofsempfangsgebäude).

**Comment by rugk** [comment]
> Bahnhofsempfangsgebäude

People will call the German language ridiculous again… :stuck_out_tongue_winking_eye: 

----

That said, should not this be discussed on POEditor? Specifically, here: https://poeditor.com/projects/po_edit?order=&filter=&id=97843&id_language=55&search=bahnhofs#showComments99823847

**Comment by westnordost** [comment]
@rugk: no, it shouldn't, because I just pointed out that the German translation accords 1:1 with the Wiki. And so does the English version and so on. If it should be discussed, then in the wiki or the mailing list because if it can be misunderstood in the StreetComplete app, it can be misunderstood by anyone reading the wiki( - and always could have been, by the way).

**Comment by FountainMapper** [comment]
Ok, I confirm, the mentioned wiki page is not detailed and lacks a clear statement. However, in the StreetComplete app is only one word visible, no context. (So it shall be exact). In the wiki page is a photo and text.
Here: https://wiki.openstreetmap.org/wiki/Railway_stations is an overview of a simple station, I assume, the building=train_station means the main, public building.
Here: https://wiki.openstreetmap.org/wiki/DE:OpenRailwayMap/Tagging is the term "Empfangsgebäude" mentioned.
The english website: https://wiki.openstreetmap.org/wiki/OpenRailwayMap/Tagging lists building=train_station as "Station Building" which translates to "Empfangsgebäude".
https://dict.leo.org/englisch-deutsch/Station%20Building

**Comment by westnordost** [comment]
I think the term "Empfangsgebäude" would lead to more misunderstandings than currently. Airport and port terminals are also "Empfangsgebäude". Me, as a German, didn't know until now what this building is supposed to be. Everybody knows what a "Bahnhof(sgebäude)" is.
Also, many/most metro (U-Bahn) and suburban railway (S-Bahn) stations are tagged as train_station. For these, "Empfangsgebäude" would be quite far off.

But anyway, as said, this is something that needs to be discussed at the source, the wiki, not here. Should this be changed in the wiki, we can reopen this ticket.
