### ISSUE TITLE
Multiple types of road surface on roundabouts

### ISSUE THREAD

**Issue by Etua** [westnordost/StreetComplete#135]
Roundabouts have a little chance to built with multiple types of surface yet StreetComplete treads them as a bunch of multiple pieces so a single roundabout can be split to over 5 different quests. It takes more type to complete them and as they usually cannot be seen in a single shot a chance to miss some part is present.

**Comment by westnordost** [comment]
True, but it is very difficult to find out what sections of road actually are the same road. So, won't/can't implement.
