### ISSUE TITLE
Maximum number of quests?

### ISSUE THREAD

**Issue by HolgerJeromin** [westnordost/StreetComplete#1351]
Is there a maximum number of loaded quests?

I have moved the building type quest to a lower priority. Now I never get this quest anymore in my home town (Verl, Germany). Even if i hit "search for new" a few times (which should load each time 10 more IIRC).
I raised the priority of this quest and got immediately many of them again.

**Versions affected**
I am always using the play store beta. My tests were a few weeks ago, but the missing quests are still there.

**Comment by matkoniecz** [comment]
>  I raised the priority of this quest and got immediately many of them again.

It sounds like other quest markers were blocking them from displaying. Were you checking on a highly zoomed map (preferably so zoomed in that there was no quest marker on the entire screen)?

**Comment by westnordost** [comment]
No

Am 6. März 2019 07:40:44 MEZ schrieb Holger Jeromin <notifications@github.com>:
>Is there a maximum number of loaded quests?
>
>I have moved the building type quest to a lower priority. Now I never
>get this quest anymore in my home town (Verl, Germany). Even if i hit
>"search for new" a few times (which should load each time 10 more
>IIRC).
>I raised the priority of this quest and got immediately many of them
>again.
>
>**Versions affected**
>I am always using the play store beta. My tests were a few weeks ago,
>but the missing quests are still there.

**Comment by HolgerJeromin** [comment]
Hmm.

I pushed (again) a few times "search for new quests" and I got them again (area around [here](https://www.openstreetmap.org/way/286058948#map=17/51.87592/8.48943&layers=N)) without priority change. 
But I suspect i will loose them again in a few weeks.

**Comment by westnordost** [comment]
Yes, unsolved quests are kept only for a month before they are deleted again if they haven't been refreshed (=downloaded again) within this time

Am 6. März 2019 11:40:19 MEZ schrieb Holger Jeromin <notifications@github.com>:
>Hmm.
>
>I pushed (again) a few times "search for new quests" and I got them
>again (area around
>[here](https://www.openstreetmap.org/way/286058948#map=17/51.87592/8.48943&layers=N))
>without priority change. 
>But I suspect i will loose them again in a few weeks.

**Comment by matkoniecz** [comment]
> Is there a maximum number of loaded quests?

AFAIK there is, at least in some cases. For example area with massive number of `building=yes` will display only part of the, right?

And I found https://github.com/westnordost/StreetComplete/blob/3244b26320754907a44bfa622338293d39318db9/app/src/main/java/de/westnordost/streetcomplete/data/download/QuestDownload.java#L179

**Comment by westnordost** [comment]
@matkoniecz Yes, only at most 2000 for each quest type are downloaded for any one area
