### ISSUE TITLE
New quest only after upload

### ISSUE THREAD

**Issue by wangongtsen** [westnordost/StreetComplete#1352]
While I see the reason behind behind the delay discussed in #1323, I think that's not the cause for my issue.
If automatic sync is disabled, "underlying" quest are not shown immediately. For example I have to upload all added road surfaces before I can see the quests for street lights.

Version 10.2

**Comment by matkoniecz** [comment]
Surface quests markers may hide street light quest markers.

New quests are downloaded either after app runs out of quests or by manual fetching new quests.

So, I would expect that either 
- solving surface quests made quest mark disappear, what allowed to display street light quests
- solving surface quests reduced number of known quests in your area what caused app to download more quests

It is also possible that you had no access to internet and once it become available new quests were downloaded.

Not all quests are downloaded at once, primary reason is avoiding overloading Overpass Turbo servers.

Ask for clarification, if something is still unclear hopefully it answers your question,

**Comment by matkoniecz** [comment]
Whoops. I missed the most important part

> If automatic sync is disabled

It means that automatic sync is disabled and you need to manually download new quests.

So

> If automatic sync is disabled, "underlying" quest are not shown immediately. For example I have to upload all added road surfaces before I can see the quests for street lights.

is expected.

https://github.com/westnordost/StreetComplete/blob/3517f02b880dc2c42ba079b21cdf35525fd4fd4c/app/src/main/java/de/westnordost/streetcomplete/data/QuestAutoSyncer.java#L28

**Comment by wangongtsen** [comment]
The new quest appears after the upload, without manually refreshing or activating auto sync and the delay is much shorter than the one for the manual refresh (takes less than 3 seconds). That's why I thought the quest is already downloaded to the device and the upload triggers it to be displayed. Is that not the case?

**Comment by matkoniecz** [comment]
See https://github.com/westnordost/StreetComplete/blob/3517f02b880dc2c42ba079b21cdf35525fd4fd4c/app/src/main/java/de/westnordost/streetcomplete/data/QuestAutoSyncer.java#L28

> Automatically downloads and uploads new quests around the user's location and uploads quests.
> Respects the user preference to only sync on wifi or not sync automatically at all

According to this comment with autosync disabled new quests are downloaded only when quests are also uploaded.

> the delay is much shorter than the one for the manual refresh (takes less than 3 seconds)

What you mean by manual refresh? Invalidating all quests or choosing to download new ones?

> upload triggers it to be displayed. Is that not the case?

As far as I know - not. They should appear in three situations 

- marker gets unblocked as other marker disappears - (zooming, panning or solving quests)
- priority or enablement changed (via settings menu)
- new quests were downloaded

**Comment by wangongtsen** [comment]
> According to this comment with autosync disabled new quests are downloaded only when quests are also uploaded.

I don't see, where uploading quests triggers a download of new quests.

> What you mean by manual refresh? Invalidating all quests or choosing to download new ones?

Just a _Scan for quests here_ from the menu, which spawns a progress bar and takes around 10 seconds (even when using wifi).

> They should appear in three situations
> * marker gets unblocked as other marker disappears - (zooming, panning or **solving quests**)

That's the behaviour I expected but don't see. At that moment, when you are in a position to solve the surface quest, you should also have information about whether there are street lights or not.

**Comment by matkoniecz** [comment]
> when you are in a position to solve the surface quest, you should also have information about whether there are street lights or not.

Yes - human using program may be aware about that. But data necessary to display street light quest may not be fetched yet.

**Comment by westnordost** [comment]
@wangongtsen: I skimmed through the previous posts and what @matkoniecz said is partly wrong, so better ignore that. Instead I'll answer to your original post:

This is not a bug.

The street lit quest is only asked for roads that are paved. Until the answers to the surface-question are uploaded, the street lights quest is not asked. If auto-sync is on, the upload is done immediately, and so, the street light quest would be shown immediately. If auto-sync is off, this only happens after the upload finished.
The displaying of the "underlying quest" happens immediately after upload and does not require another download, except for the following quest types: housenumber, cycleway, sidewalk, building construction, road construction

**Comment by wangongtsen** [comment]
Thanks for clearing things up.

Actually, I didn't intend to report this as a bug. I wanted to either suggest to change that behaviour or understand why it's done that way, because for me it seemed to be a big drawback of disabled auto sync.
If it's not the app, but the server, that's holding back the street light quest, everything makes sense.

**Comment by matkoniecz** [comment]
>  what @matkoniecz said is partly wrong, so better ignore that.

Sorry for being misleading :(

**Comment by westnordost** [comment]
It is done that way for easy conflict resolution: The answers you give are stored locally only as minimal diffs, one diff per answer (per element). For example, a diff looks like this: `ADD surface=asphalt`. Only when the upload is triggered, the change is applied to the element and uploaded. If now the element changed in the meantime, the element is downloaded again from the OSM API and the change is applied again (plus some additional checks), if possible. This has the advantage, that the collected data via StreetComplete can be quite stale and still apply fine with easy automatic conflict resolution. However, it means that the OSM element StreetComplete stores locally for each quest is always the unmodified element from the OSM server.
So, while you already answered the question whether the street is paved or not, it is not applied to the element, not even locally. But based on this locally stored element, new quests are created.

Of course, it would be possible to implement that StreetComplete stores locally two versions of the element: The original unchanged element used when during upload, and the element how it is assumed will be after the element has been uploaded without conflict. However, this is far from trivial and not worth the effort, IMO, because what then to do in case of conflict? What to do when undoing an answer? etc etc.

**Comment by wangongtsen** [comment]
Great answer and I see your point now.
