### ISSUE TITLE
Clarify "button to request green light"

### ISSUE THREAD

**Issue by camelCaseSucks** [westnordost/StreetComplete#1353]
I've never heard of drivers having to press a button for a green light, so I assume this is about crosswalks. If not, I have no idea what this is referring to. If so, it should say so, and it should not use the word "green" because crosswalk lights aren't green in the US.

**Comment by rugk** [comment]
> because crosswalk lights aren't green in the US.

..., but?

**Comment by camelCaseSucks** [comment]
I don't know what that's supposed to mean. If I need to press a button for the crosswalk, I'm not pressing it for a *green* light. This wording is confusing. It should ask if you need to press a button for a crosswalk signal without specifying color. (I'm still assuming it's referring to a crosswalk because your 1-word comment didn't really clarify anything.)

**Comment by westnordost** [comment]
Sorry, rugk's comments are often not helpful.

The question is supposed to ask if there is a buttons for pedestrians that they can press to, err, request that the cars need to stop and the pedestrians can go over the street.

Could you suggest a better US-English wording of the question? 

Am 11. März 2019 08:59:14 MEZ schrieb camelCaseSucks <notifications@github.com>:
>I don't know what that's supposed to mean. If I need to press a button
>for the crosswalk, I'm not pressing it for a *green* light. This
>wording is confusing. It should ask if you need to press a button for a
>crosswalk signal without specifying color. (I'm still assuming it's
>referring to a crosswalk because your 1-word comment didn't really
>clarify anything.)

**Comment by rugk** [comment]
Hey, sorry...

I thought you meant to imply there is a different color for the crosswalks or so.

I guess this is really just a bad translation from German, "to press for a green light to appear" or so.

But I agree the color can be dropped.

**Comment by gdt** [comment]
In the US: crosswalks are almost always white paint, cars go on green, speed up on yellow (in Boston :-), and stop on red.   Lights facing pedestrians at crosswalks are white for "walk", flashing orange for "keep walking if you are crossing but don't start" (kind of like yellow lights for cars), and solid orange for "don't walk".  Some of them cycle always, and some have buttons.   Some crosswalks have no lights (no car lights, no pedestrian lights).   Some have just car lights.  Some have both.

"Is there a button to request an ok-to-cross signal?" would be how I'd write it for a wide audience.  For just en_US, I would say "Is there a button to request a walk signal?"

But Ii don't expect non-native speakers or people in other countries to always call the signals "walk" and "don't walk"; while it seems near-universal in the US it feels a bit peculiar.

**Comment by gdt** [comment]
Probably this question should only be asked if it is known if there are pedestrian crossing lights.  Otherwise, it's a 3-part

Does this
   not have lights to tell you that you can cross?
   have lights that always cycle?
   have lights and  you need to push a button?
