### ISSUE TITLE
append extra space after note text

### ISSUE THREAD

**Issue by govvin** [westnordost/StreetComplete#1356]
For improved readability add a space after the note text, before appending ¨via StreetComplete 10.2" to improve readability. See examples below:

![image](https://user-images.githubusercontent.com/5821688/54469056-2882b300-47ce-11e9-8190-c0add82daa17.png)

**How to Reproduce**
Add a note with some text in StreetComplete.

**Versions affected**
10.2

**Comment by ENT8R** [comment]
There is actually a whole newline (`\n`) between the comment and the `via StreetComplete...`

See also https://www.openstreetmap.org/note/1695791 which renders it correctly and [the code](https://github.com/westnordost/StreetComplete/blob/master/app/src/main/java/de/westnordost/streetcomplete/data/osmnotes/CreateNoteUpload.java#L194-L211) which generates the text.

So I think this is rather an issue of the editor you are using (looks like JOSM) so better open an issue there.
