### ISSUE TITLE
Specify building type when building=yes

### ISSUE THREAD

**Issue by jluttine** [westnordost/StreetComplete#1359]
### General
Affected tag(s) to be modified/added: [building](https://wiki.openstreetmap.org/wiki/Key:building)
Question asked: **What type of building is this?**

Motivation: There's a huge number of `building=yes` tags. Would be great to convert these into something more informative.

### Checklist
Checklist for quest suggestions (see guidelines):
- [x] 🚧 To be added tag is established and has a useful purpose
- [x] 🤔 Any answer the user can give must have an equivalent tagging (Quest should not reappear to other users when solved by one)
- [x] 🐿️ Easily answerable by everyone from the outside but a survey is necessary 
- [x] 💤 Not an overwhelming percentage of elements have the same answer (No spam)
- [x] 🕓 Applies to a reasonable number of elements (Worth the effort)

### Ideas for implementation

**Proposed GUI:**

Perhaps the first question could be a higher level question whether it's for accomodation, commercial, religous, etc. Then, the next question could define it more accurately (apartments,  detached, terrace/rowhouse, etc).

My main concern is if it's too difficult to classify the building in many cases.. For instance, is it a hub or a cabin or a shed?

**Comment by ENT8R** [comment]
Ahhmm... Did you already used the app?
This quest is already available since version 6: https://github.com/westnordost/StreetComplete/releases/tag/v6.0 (more than half a year ago)

**Comment by ENT8R** [comment]
It is just not that high in the quest priority list, but you can modify that in the settings.

**Comment by jluttine** [comment]
Yeah, I've used the app, but that quest has never been offered to me although I've had plenty of `building=yes` buildings around. So I didn't realize it already existed. Thanks for pointing it out! I'm using version 10.2 and I can see the quest in the settings. It was enabled for me, and now that I moved it higher in the priority list I started getting those quests visible. Thanks!

**Comment by rugk** [comment]
BTW, note you can also see all currently included quests in https://wiki.openstreetmap.org/wiki/StreetComplete/Quests with a description of what they ask/use/…

**Comment by jluttine** [comment]
@rugk Thanks! I actually did check that but somehow missed this.. :see_no_evil:

**Comment by Eric-Sparks** [comment]
Ditto
