### ISSUE TITLE
Optimze Button and Marker backgrounds for dark theme

### ISSUE THREAD

**Issue by claudiush** [westnordost/StreetComplete#1361]
#1306 added a new dark mode which is a welcome addition for evening strolls. Thanks for the work on that @ENT8R .
I think the contrast of UI elements like buttons, marker outlines and the bottom bar are too high to be usable during night time with them glaring on the screen:
![image](https://user-images.githubusercontent.com/428616/54914312-f7546200-4ef4-11e9-911f-d43a64afa2fc.png)
Maybe it would just help tuning the light grey down a bit to preserve enough contrast with the icons on the elements. This is darkened 33%:
![image](https://user-images.githubusercontent.com/428616/54914368-118e4000-4ef5-11e9-982e-be6016d750a0.png)

**Comment by westnordost** [comment]
My concern with this is that if the button is (too) gray, it may look like as if they are disabled. The screenshot you posted is still a very light gray, but then there is not much of a difference to the original whit color.

**Comment by westnordost** [comment]
Well, I think I am going to close this. The new version is live for a few weeks now, and noone seemed to be bothered by the white pins in the dark layout.

**Comment by rugk** [comment]
I still need to try it out… (considering that F-Droid is a little slow)

But as from the screenshots I was "concerned" from the beginning on. I'll need to take a look how it looks, especially in the night or so…
