### ISSUE TITLE
Invoke Navigate Intent on Quest

### ISSUE THREAD

**Issue by dbdean** [westnordost/StreetComplete#1362]
**Use case**
Would it be possible to add an option to quests that invokes the Android Navigate Intent so that I can easily bring up OsmAnd (or even google maps) to drive/ride/walk to the next quest, rather than having to find the same location in a different navigation app?

I've cleared a lot of quests around my area now, so my normal lunch time process is
1. Find a quest (or cluster of quests) I want to solve
2. Open that same area in osmand to get navigation directions
3. Ride my bike to the quest, switch back to StreetComplete to solve quests
4. Repeat at 1 if I still have time
5. Go back to work

**Proposed Solution**
Invoke the navigation intent (if that's what it's called) on the lat/long of a quest so that any running navigation software can give me the option of finding my way there, particularly if the closest quest (or chosen quest) is far away and requires complicated navigation to get to.

**Comment by dbdean** [comment]
This is related to https://github.com/westnordost/StreetComplete/issues/190, but I'm not sure if it's the same thing. That issue appears to be asking about opening other editing apps like Vespucci. https://github.com/westnordost/StreetComplete/issues/426 is also related, but that's about moving the map in StreetComplete away from where you are an to a particular address/location.

**Comment by ENT8R** [comment]
#190 should already cover this as using [`geo:` intents](https://developer.android.com/guide/components/intents-common#Maps) is the only way to open another app with a specified location on Android.
So both OsmAnd and Vespucci should respond to that intent (i.e there is a selection dialog for the user to select the correct app he wants to use (if both are installed))

**Comment by HolgerJeromin** [comment]
I would solve this not on a quest base but in the menu as an entry:
"open this location in another app"

**Comment by westnordost** [comment]
Yes, this is actually the same as #190. Shouldn't be difficult to implement as well.
