### ISSUE TITLE
New quest: what insignia is on this postbox?

### ISSUE THREAD

**Issue by JayTurnr** [westnordost/StreetComplete#1363]
Can be used to identify the age of the post box

**Comment by ENT8R** [comment]
If you really want to propose a new quest, please use the issue template which was created for exact that purpose.

**Comment by matkoniecz** [comment]
See guidelines for quest suggestions: https://github.com/westnordost/StreetComplete/wiki/Adding-new-Quests-to-StreetComplete

Template has following questions:

### General
Affected tag(s) to be modified/added: 

Question asked:

If the answer is not obvious, please append a short explanation to each item (or, if it is longer, below), explaining the reason.

### Checklist
Checklist for quest suggestions (see guidelines):
- [ ] 🚧 To be added tag is established and has a useful purpose
- [ ] 🤔 Any answer the user can give must have an equivalent tagging (Quest should not reappear to other users when solved by one)
- [ ] 🐿️ Easily answerable by everyone from the outside but a survey is necessary 
- [ ] 💤 Not an overwhelming percentage of elements have the same answer (No spam)
- [ ] 🕓 Applies to a reasonable number of elements (Worth the effort)

Please try to satisfy all conditions. If one cannot be satisfied that may prevent your quest from getting included in StreetComplete.
If you are not sure about how one condition applies to your suggestion or you have (very) strong reasons that a condition may not needed to be satisfied in your case, just note that down. Someone else may come up with some ideas.

**Comment by westnordost** [comment]
(Please create a new issue after you have read the guidelines)

**Comment by JayTurnr** [comment]
> If you really want to propose a new quest, please use the issue template which was created for exact that purpose.

Hi sorry, I was on mobile and mobile github didn't suggest any templates to me. I'll edit this.

**Comment by JayTurnr** [comment]
#1370
