### ISSUE TITLE
New Quest: Royal Cypher

### ISSUE THREAD

**Issue by JayTurnr** [westnordost/StreetComplete#1370]
### General
Affected tag(s) to be modified/added: [royal_cypher](https://wiki.openstreetmap.org/wiki/Key:royal_cypher)
Question asked: **Is there an Royal Cypher on this post box?**

### Checklist
Checklist for quest suggestions (see guidelines):
- [x] 🚧 To be added tag is established and has a useful purpose
- [x] 🤔 Any answer the user can give must have an equivalent tagging (Quest should not reappear to other users when solved by one)
- [x] 🐿️ Easily answerable by everyone from the outside but a survey is necessary 
- [x] 💤 Not an overwhelming percentage of elements have the same answer (No spam)
- [x] 🕓 Applies to a reasonable number of elements (Worth the effort)

### Ideas for implementation

**Element selection:**  amenity=post_box, without a royal_cypher tag in the UK and related colonies. [Example query, i'm not the best of overpass](https://overpass-turbo.eu/s/HJ3) - countries limited to the [Commomwealth](https://en.wikipedia.org/wiki/Commonwealth_realm), current and historic

**Metadata needed:** 

**Proposed GUI:**

Simple to the GUI for Road Surface, [with the pictures and text from the official wiki](https://wiki.openstreetmap.org/wiki/Key:royal_cypher#Values%20for%20UK%20and%20Commonwealth%20monarchs), with an option for None, which gives the tag "no" as per the wiki

**Comment by ENT8R** [comment]
> and has a useful purpose

Could you maybe give some more information why this data might be useful and if possible, if there are any data consumers? I can't imagine a use case for that currently...

**Comment by JayTurnr** [comment]
Have you heard of Niantic and their line of Augmented Reality games?

In their original game, you can submit real world locations and one of the locations that get approved commonly is post boxes with certain cyphers. The rarer the cypher, the higher odds of being approved.

Apart from agents querying a database to find the rare cyphers, I can't think of a use case outside of that.

**Comment by westnordost** [comment]
Maybe historic maps?

**Comment by westnordost** [comment]
> The rarer the cypher, the higher odds of being approved.

Ok, well, I rather not have this in the app because the usefulness of this tag is a bit unclear and, if Pokemon Go is involved, the I see a data quality issue. In other words, if a rare cypher leads to an advantage in that game, there will be people who deliberately input wrong data to get this advantage.

**Comment by JayTurnr** [comment]
> In other words, if a rare cypher leads to an advantage in that game, there will be people who deliberately input wrong data to get this advantage.

I see your concerns; however, rest assured that OpenStreetMap is not used in the approval process to confirm if an object is there. Niantic still use Street view and Google, to my dismay. 

However, people are stupid, so they'll still try to game the system to I completely agree that it is susceptible to bad data.
