### ISSUE TITLE
Poor space usage by buttons with some text length (triggered in some localizations)

### ISSUE THREAD

**Issue by matkoniecz** [westnordost/StreetComplete#1372]
**How to Reproduce**
Switch language to Polish. Click on pedestrian access quest

First button should be smaller, second larger. Screenshot is from modified version but I tested it and buttons are exactly the same with regular StreetComplete.

![Screenshot_2019-04-12-16-52-28-350_de westnordost streetcomplete debug](https://user-images.githubusercontent.com/899988/56054010-ee1d1f00-5d55-11e9-9c32-5ac2f4ccef40.png)

**Versions affected**
Android release version	6.0.1

StreetComplete 11

**Comment by westnordost** [comment]
This is a duplicate. Also, from my side, this is will not fix, because I already tried to solve this but was not successful. You could have a try if you wanted.

**Comment by matkoniecz** [comment]
OK, I will try. Maybe I will find some solution.

**Comment by rugk** [comment]
I guess it is kinda a dupe of https://github.com/westnordost/StreetComplete/issues/1284. (only my issue there was a little more specialized)

**Comment by dAnjou** [comment]
Hi, I really like this app and I hope you'll reconsider the #wontfix because sometimes you can't see the labels at all.

Is there maybe a way to make this responsive? Like, have a minimum width for buttons and shove them in a menu when they exceed the given space?

![Screenshot_20200516-182817](https://user-images.githubusercontent.com/117147/82126019-07d73400-97aa-11ea-90ed-284532a29079.jpg)

**Comment by westnordost** [comment]
Which version is that?

Am 16. Mai 2020 19:22:10 MESZ schrieb Max Ludwig <notifications@github.com>:
>Hi, I really like this app and I hope you'll reconsider the #wontfix
>because sometimes you can't see the labels at all.
>
>Is there maybe a way to make this responsive? Like, have a minimum
>width for buttons and shove them in a menu when they exceed the given
>space?
>
>![Screenshot_20200516-182817](https://user-images.githubusercontent.com/117147/82126019-07d73400-97aa-11ea-90ed-284532a29079.jpg)

**Comment by dAnjou** [comment]
> Which version is that?

`v20.0-beta1`

**Comment by westnordost** [comment]
I think the width of the text changed inadvertently with v20.0, so this is a bug in v20

**Comment by dAnjou** [comment]
Just updating how it looks like in version 20.0-beta2:
![Screenshot_20200523-170233](https://user-images.githubusercontent.com/117147/82733897-6e62d180-9d17-11ea-852f-b4832826f609.jpg)

**Comment by westnordost** [comment]
hm.

**Comment by westnordost** [comment]
Bricht jetzt zum wenn es zu lang ist.
