### ISSUE TITLE
Sidewalk quest is regions related

### ISSUE THREAD

**Issue by ViolaineDo** [westnordost/StreetComplete#1373]
Sidewalks as an attribute of a road is one of the 2 option we have when tagging sidewalks. There is not one unique consensus manner to map sidewalk. Nevertheless the manner those sidewalks are mapped depends on the region. See dedicated [wiki]([https://wiki.openstreetmap.org/wiki/Sidewalks#Regional_variations]) Sidewalk might be mapped as a separated way in certain region. So I would like to specify in which region this quest is ok (or not). 

**How to Reproduce**
na

**Versions affected**
na

**Comment by westnordost** [comment]
In places where the sidewalk is mapped as a separate way, the sidewalk quest is not displayed already.

**Comment by ViolaineDo** [comment]
awesome :)

**Comment by ENT8R** [comment]
@ViolaineDo you can also close the issue if your question is solved :smile:
