### ISSUE TITLE
Clean up EXIF headers on photo upload

### ISSUE THREAD

**Issue by riccomatx** [westnordost/StreetComplete#1375]
**Upload photos without personal identifiers.**
When I want to submit a photography done with my mobile phone for e.g. a discussion about the state of a road, I'd like to be sure no EXIF data which could identify me or my mobile phone is uploaded to any public place.

**Proposed Solution**
* Clean up EXIF headers before upload
* Be able to upload photos afterwards, once I've removed the EXIF headers by myself with other software.

**Comment by matkoniecz** [comment]
According to the information available n privacy policy this is already done.

Can you link photo where this failed?

**Comment by riccomatx** [comment]
No, I can't; I haven't completely read the privacy policy and didn't know EXIF heades were already clean. Thanks! I'll close the issue.
