### ISSUE TITLE
allow to copy text from dialogs

### ISSUE THREAD

**Issue by matkoniecz** [westnordost/StreetComplete#1377]
I was checking whatever Polish translation is correct and it was a
bit irritating that copying text from displayed dialogs was blocked.

Making them copyable (is that is not too complicated and causing more important negative effects) would also make easier for users to copy message and search using it of they don't understand something or encounter some issue.

I encountered this one on toggling vegetarian quest.

**Comment by westnordost** [comment]
Hm, this would be quite unusual. I know no other Android app (or native app in general) that would allow this.

**Comment by westnordost** [comment]
So I rather will not make a break with the default Android UX here
