### ISSUE TITLE
Position is not updated while scanning for new quests

### ISSUE THREAD

**Issue by Natenom** [westnordost/StreetComplete#138]

**Comment by westnordost** [comment]
Would you elaborate, I don't get what mean. Following the user's position and (automatically) downloading quests are two completely separate processes. 

On 24 April 2017 09:15:11 CEST, Natenom <notifications@github.com> wrote:
>
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/westnordost/StreetComplete/issues/138

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by Natenom** [comment]
Ich war in einem fahrenden Auto und autosync war aus. Habe manuell "Scan for quests" gestartet und solange das lief, wurde die Position angezeigt zu dem Zeitpunkt als der Scan gestartet wurde.

**Comment by westnordost** [comment]
War der GPS Knopf denn noch aktiviert (orange)?

On 24 April 2017 15:05:41 CEST, Natenom <notifications@github.com> wrote:
>Ich war in einem fahrenden Auto und autosync war aus. Habe manuell
>"Scan for quests" gestartet und solange das lief, wurde die Position
>angezeigt zu dem Zeitpunkt als der Scan gestartet wurde.
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/westnordost/StreetComplete/issues/138#issuecomment-296661252

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by Natenom** [comment]
Vermutlich nicht, da ich ja ein quest inzwischen gelöst hatte. Aber auch der blaue Punkt, der meinen Standort angibt, hätte eigentlich aktualisiert werden müssen.

**Comment by westnordost** [comment]
Der blaue Punkt ist eigentlich irrelevant. Der wird aktualisiert, wenn die Sensoren eine neue Position melden. Wann die Sensoren eine neue Position melden, darüber habe ich keine Kontrolle.

Wenn der GPS Knopf orange ist, bedeutet das, dass der Bildschirm immer dem blauen Punkt folgt.

Also das Problem ist nicht, dass der Bildschirm nicht dem blauen Punkt folgt, sondern dass sich der blaue Punkt scheinbar nicht bewegt während nach neuen Aufgaben gescannt wird?

**Comment by Natenom** [comment]
Am Mittwoch werde ich vermutlich wieder in einem fahrenden Auto sitzen können, dann mache ich ein Video. Vielleicht hilft das.

**Comment by Natenom** [comment]
Habe heute die Situation nachgestellt und der blaue Punkte wurde aktualisiert auch beim Scannen nach neuen Quests. Muss wohl etwas anderes gewesen sein.

**Comment by westnordost** [comment]
okidoki, kannst ja nochmal hier reinschreiben wenn das Problem reproduzierbar wird.
