### ISSUE TITLE
Ongoing proposal for a new tag

### ISSUE THREAD

**Issue by ValorNaram** [westnordost/StreetComplete#1380]
The key 'diaper' is highly misunderstood and therefore misleading the tagging mailing list discovered. There's a ongoing proposal for a better suited key.

Please keep track of the state of https://wiki.openstreetmap.org/wiki/Proposed_features/baby_changing_tables and share with all who's interested.

**Comment by westnordost** [comment]
If the proposal in one form or another reaches consensus, just create a new ticket and/or answer to #344 and I will be notified that a change in Streetcomplete needs to be made.
