### ISSUE TITLE
Cannot 'complete' cycleway and sidewalk quests

### ISSUE THREAD

**Issue by kpfleming** [westnordost/StreetComplete#1381]
When a cycleway or sidewalk quest is selected, I am able to select the proper type of cycleway or sidewalk from the grid of pictures, but there is no "OK" button to submit the answer.

**How to Reproduce**
1. Open a 'cycleway' quest.
1. Click the example cycleway.
1. Select the appropriate type of cycleway from the menu of options.
1. Menu closes and app returns to the main quest screen, still displaying "Can't Say..." but without any other action butons.

**Versions affected**
Android 8.0.0 and StreetComplete 11.0

**Comment by ENT8R** [comment]
Did you try to select both sides of the road? Even if the value is the same on both sides, it needs to be stated explicitly. Only then the OK button is shown.

**Comment by kpfleming** [comment]
You're absolutely right, the OK button appears once both sides of the road have a selection made. It wasn't obvious to me that the app was asking me to do that.

**Comment by rugk** [comment]
Could be an UX issue, however, then…
@kpfleming FYI: In the past there was an ok button and if you tapped on it it showed you a toast message "Please complete both sides." or similar. Maybe this is the better way.

**Comment by kpfleming** [comment]
Or possibly the non-completed side of the road could be highlighted in some way to draw attention to it.
