### ISSUE TITLE
RfQ: Specify generator:source=solar generators

### ISSUE THREAD

**Issue by HolgerJeromin** [westnordost/StreetComplete#1383]
### General
Affected tag(s) to be modified/added: [plant:method](https://wiki.openstreetmap.org/wiki/Key:plant:method) and [generator:type](https://wiki.openstreetmap.org/wiki/Key:generator:type)
Question asked: **Is this a `solar_thermal_collector`, a `solar_photovoltaic_panel` or a `steam generator`**

### Checklist
Checklist for quest suggestions (see guidelines):
- [x] 🚧 To be added tag is established and has a useful purpose
- [x] 🤔 Any answer the user can give must have an equivalent tagging (Quest should not reappear to other users when solved by one)
- [x] 🐿️ Easily answerable by everyone from the outside but a survey is necessary 
- [x] 💤 Not an overwhelming percentage of elements have the same answer (No spam)
- [x] 🕓 Applies to a reasonable number of elements (Worth the effort)

Solar panels are visible from the aerial image. But a `solar_thermal_collector` with a glas cover looks quite similar as a `solar_photovoltaic_panel`.

ref https://wiki.openstreetmap.org/wiki/Renewable_energy_in_the_United_Kingdom/Rooftop_Solar_PV

### Ideas for implementation
**Element selection:** 

````
[out:json][timeout:25];
// gather results
(  
  node["generator:source"="solar"][!"generator:type"][!"generator:method"][!"generator:output:electricity"]({{bbox}});
  way["generator:source"="solar"][!"generator:type"][!"generator:method"][!"generator:output:electricity"]({{bbox}});
);

// count results
out count;
// print results
//out body;
//>;
//out skel qt;
````

Mapillary of a thermal collector: https://www.mapillary.com/map/im/Ay2SqrNCw9N8kJbWcBVG_Q
and a photovoltaic panel on the left: https://www.mapillary.com/map/im/Fp_ShB7jdDcNDJM5ylUXCQ

**Comment by rugk** [comment]
> Easily answerable by everyone

And how can I, as a user, see whether this is a solar panel or photovoltaic panel? (if it looks "with a glas cover looks quite similar")

**Comment by HolgerJeromin** [comment]
>> Easily answerable by everyone
> And how can I, as a user, see whether this is a solar panel or photovoltaic panel? (if it looks "[quite similar] with a glas cover")

We need good pictures and ask the right questions.  
https://de.wikipedia.org/wiki/Datei:Sonnenkollektoren.jpg
https://commons.wikimedia.org/wiki/File:Solar_heating_system_-_Thermosolaranlage_-_Mörfelden-Walldorf_-_Germany.jpg
https://commons.wikimedia.org/wiki/File:Dach_des_Gästehauses_Freiherr_vom_Stein_-_Solarthermie_und_Photovoltaik.JPG

The linear design or diffuse collectors are thermal collectors, the rectangular shapes (and sometimes thin) are photovoltatic.

**Comment by rugk** [comment]
Okay, then I would suggest this as a GUI:
* these (or similar, better cropped) three images to be selected-able
* when you select one, it shows you the additional status text somewhere "thermal collector" or "photovoltaic panel"

The last thing is IMHO quite nice to also educate the user and so they actually know, what their answer is. (It would be strange to not know your impact, if you just select how that thing there looks.) Obviously, it also allows for human verification (some common sense) in case the decision is not clear or so. 

Or we could just choose three images with descriptions, I just struggle with the issue that there are two very different images for thermal collectors. (and I doubt we should label/use such expert terms as "diffuse collector" – whatever that is… :laughing:)

----

Seeing your images: Another question: Can we somehow exclude them, if they are mounted at a roof? (We cannot expect surveyors to climb. :wink:)

**Comment by westnordost** [comment]
Okay so basically anything in a grid-pattern is photovoltaic and anything else is thermal?

**Comment by westnordost** [comment]
Hmm there is also another problem with this quest: These are usually on the roof. Oftentimes, you cannot see exactly what it is from the street.

**Comment by rugk** [comment]
This is exactly what i wrote at the end… :laughing: 

However, I'd say many are also on meadows or so, but, yes, often on an roof too. Maybe some stats on this would be nice…

**Comment by HolgerJeromin** [comment]
> diffuse collector

With the term diffuse I meant a [matte surface](https://en.wikipedia.org/wiki/Ground_glass) (de: Satiniertes Glas)

> These are usually on the roof. Oftentimes, you cannot see exactly what it is from the street.

Exclude them when they are surrounded with outlines with `roof:shape=flat` or `roof:level=0` :-)

ref #277

**Comment by westnordost** [comment]
I looked at a few pictures, among these [this one](https://upload.wikimedia.org/wikipedia/commons/8/8e/Solar_panels_on_house_roof.jpg) and I rather not have this in the app because
- difficult to explain to the user how to differentiate 
- difficult to ascertain which one of the two it should be, e.g. see the picture I linked - looks more like thermal than photovoltaic
- need to get really close and be in the right angle to make a distinction but with them being on the roof, that's quite difficult (see picture) - basically all would need to be excluded with building:levels > 1 or 2 and float or no roof.
- a house may be rotated towards the street so that you can't see the panels from the street or you can see them, but not "frontal" enough to make a distinction

All in all, some will not be answerable because it can't be seen, and those that are answerable, the data quality of it would be questionable.

**Comment by HolgerJeromin** [comment]
Probably the right decision:
![image](https://user-images.githubusercontent.com/2410353/56854695-fde25900-693a-11e9-8cf8-2cab24235e5d.png)
Looks like a thermal panel. But the [source](http://www.horneburger-systemholzbau.de/photovoltaik.html) is a photo-voltaic service provider.
