### ISSUE TITLE
AddPlaceName catchall results in "(null)" for missing names

### ISSUE THREAD

**Issue by matkoniecz** [westnordost/StreetComplete#1384]
https://www.openstreetmap.org/node/475387240#map=19/50.06232/19.93555

`shop=cobbler` without name is caught by `shop and shop !~ no|vacant` in https://github.com/westnordost/StreetComplete/blob/master/app/src/main/java/de/westnordost/streetcomplete/quests/place_name/AddPlaceName.kt#L22 but apparently no name is provided.

This results in "(null)" exposed to the user.

**Comment by westnordost** [comment]
Are you sure about this?

**Comment by westnordost** [comment]
Places where no name can be determined should be excluded. See 
https://github.com/westnordost/StreetComplete/blob/master/app/src/main/java/de/westnordost/streetcomplete/quests/place_name/AddPlaceName.kt#L66-L67

**Comment by matkoniecz** [comment]
It turned out that quest data leaked from fork. Full reinstall removed it.

**Comment by matkoniecz** [comment]
Sorry for a false alarm, I should check on fully reinstalled app before reporting.
