### ISSUE TITLE
Add whether shop=laundry is a self-service laundry

### ISSUE THREAD

**Issue by westnordost** [westnordost/StreetComplete#1385]
### General
Affected tag(s) to be modified/added: [self_service](https://wiki.openstreetmap.org/wiki/Key:self_service)
Question asked: **Is this a self-service laundry?**

### Checklist
Checklist for quest suggestions (see guidelines):
- [x] 🚧 To be added tag is established and has a useful purpose
- [x] 🤔 Any answer the user can give must have an equivalent tagging (Quest should not reappear to other users when solved by one)
- [x] 🐿️ Easily answerable by everyone from the outside but a survey is necessary: Coin-operated washing-machines can usually be seen from the outside
- [?] 💤 Not an overwhelming percentage of elements have the same answer (No spam)
- [x] 🕓 Applies to a reasonable number of elements (Worth the effort): Either taginfo is broken, or almost no laundry shops have self_service tagged right now

### Implementation
A yes-no quest or like the car-wash quest if there should be more options.

**Comment by majkaz** [comment]
This seems to be a very location specific quest. 

Locally, the test "Not an overwhelming percentage of elements have the same answer (No spam)" will fail - except in very touristy areas, where you might find the one or other odd self-service laundry, any other such shop operates more or less like a dry cleaning - you drop your laundry there, and get a clean (and pressed) one back later.

**Comment by matkoniecz** [comment]
> except in very touristy areas

And in some cities where washing machine is not present in all rooms/apartments.

**Comment by westnordost** [comment]
Well in my city usually every apartment has one, still, there are about as many self-service laundries scattered around town as laundry shops.

**Comment by majkaz** [comment]
Well, in my country, every apartment has one... and there are self-service laundries in the capital (touristy area and expats). In two additional towns (with big universities) there are few self-service laundries. In the rest of the country, there might be the odd one... 

In my region (which has about 1/10 of the whole country area), there isn't a single one, except the one I have found in a hostel, just for the guests... This is what I mean with a "location-specific" quest.

But never mind the issue, there are not many laundries either - neither on the ground, nor mapped - just dry cleaners. The quest won't matter here. "Our" equivalent of shop=laundry is traditionally just the ironing / pressing part. Not much changed here.
