### ISSUE TITLE
quest for steps on handrails

### ISSUE THREAD

**Issue by ViolaineDo** [westnordost/StreetComplete#1390]
This quest type is useful for accessibility purposes and used into algorythm to estimate accessibility of an itinerary for blind/elderly. 
I know that it was not seen as a priority in issue #503 , but I guess it was waiting for someone to create a dedicated issue on handrails especially (issue 503 was about different quests on staircases, including handrails).
Please tell me what do you think about it.. 
cc @smortex

>> QUEST PROPOSAL (UPDATE)

### General
Affected tag(s) to be modified/added: [handrail](https://wiki.openstreetmap.org/wiki/Key:handrail)
Question asked: **Is there (an) handrail(s) along these steps?**
Answer help : Select the location of the handrail (left, right, middle).

Use case : 
1 I am an elderly, connected, I love to travel, I am still active but have moving issue, I want to know if I can go to this supermarket where there is a few steps, with no concerns..
2 I am a travel agency, I want to show accessible path to my clients. 
3 I am a city planner, I want to make my city more welcoming to people.
### Checklist
Checklist for quest suggestions (see guidelines):
- [x] 🚧 To be added tag is established and has a useful purpose
- [x] 🤔 Any answer the user can give must have an equivalent tagging (Quest should not reappear to other users when solved by one)
- [x] 🐿️ Easily answerable by everyone from the outside but a survey is necessary 
- [x] 💤 Not an overwhelming percentage of elements have the same answer (No spam)
- [x] 🕓 Applies to a reasonable number of elements (Worth the effort)

### Ideas for implementation

**Proposed GUI:**
Use the same method as for sidewalks ("is there a pavement along this street), user choose the side of steps by clicking on an image/minimap and answer yes or no.

**Comment by rugk** [comment]
Please fill out the "new quest" issue template if requesting a new quest. Otherwise, we cannot accept it here.

**Comment by ViolaineDo** [comment]
> Please fill out the "new quest" issue template if requesting a new quest. Otherwise, we cannot accept it here.

Sorry I wasn't sure if it was needed at first. Updated.

**Comment by rugk** [comment]
Thanks. As I was the one who opened https://github.com/westnordost/StreetComplete/issues/503 initially, I am obviously biased and in favor of this quest. :wink: 

If you re-read https://github.com/westnordost/StreetComplete/issues/503 you'll see that idea was not well considered. However, I personally did not know, that **this is an accessibility feature**. 
Maybe you can elaborate on the exact use case a little more. How useful is it to know whether there are handrails?
And if so, is it actually useful to know _where_ these are (left/right/middle) or may the information that one is (not) there actually be enough?

Off-topic, but BTW: https://github.com/westnordost/StreetComplete/issues/503 also had the idea of asking for "ramps". If you think this is useful/also a good accessibility feature, feel free to create a new issue. (with filled-out issue template; shame on me that I did not do that in https://github.com/westnordost/StreetComplete/issues/503 properly, maybe it was before the time we had this template.)

**Comment by rugk** [comment]
Regarding GUI: If we want to map all left/middle/right, we need a multi-selection for these obviously, A step can have both left and right handrails.

**Comment by ViolaineDo** [comment]
> Regarding GUI: If we want to map all left/middle/right, we need a multi-selection for these obviously, A step can have both left and right handrails.

I think the quest on sidewalks is doing that, am I wrong?

**Comment by rugk** [comment]
Yes, may be. I just wanted to highlight it. (And I personally do not know that out of my head.)

**Comment by ViolaineDo** [comment]
Indeed : not great added value to know where the handrail is, just knowing there is one is great. 
For ramps : yes an other challenge, on my mind ;)  My issue for now with ramps is that they are not qualifying if those are accessible or not (they tell if there is but not if accessible, and it is explicitely explained on the wiki that we should map footway with incline info for that, where incline is quite hard to evaluate easily...)

**Comment by ViolaineDo** [comment]
Use case : updated on the description...

**Comment by westnordost** [comment]
Okay, makes sense. Though, I would limit this quest to specifying whether it has a handrail or not, not where it is.

**Comment by xuiqzy** [comment]
I would like to implement this as a new quest. As I understood, a simple yes/no quest is enough and I already have working code for that tested locally.
Can someone give me hints as to how to design a new logo? I am willing to do / learn that, but am not sure how to go about starting that. This would be very much appreciated!

**Comment by westnordost** [comment]
That's cool! Yes, yes/no is good.

Those files are not SVGs, but Android Vector Drawables. The paths within these are actually the same format as SVGs, but everything else is different. In Android Studio, you can import SVGs. But anyway, I already long created an icon for that, please use that. I just comitted and pushed it. It's `ic_quest_handrail.xml`
