### ISSUE TITLE
add quest toilets:wheelchair for object with toilets=yes

### ISSUE THREAD

**Issue by ViolaineDo** [westnordost/StreetComplete#1391]
I am suggesting here a quest about wheelchair accessibility for toilets in an amenity. This could be disabled by default as you would need to enter the facility. This would filter object with tags : toilets=yes or toilets:access=customers or permissive or yes.  
Defining if a toilet is wheelchair accessible or limited or not would be as for amenity=toilets (though instead of having as a result wheelchair=yes/no/limited we would have toilets:wheelchair=yes/no/limited)
This is an important information to know for people with disabilities in order for them to find their best restaurant / bar to go. 
What are your thoughts? 
cc @smortex

>> QUEST PROPOSAL (UPDATE)

### General
Affected tag(s) to be modified/added: [toilets:wheelchair](https://wiki.openstreetmap.org/wiki/Key:toilets:wheelchair)
Question asked: **Is this toilet accessible for wheelchair  ?**
Answers: 
* Yes means  doorway’s inner width are large enough (min. 90 cm), space is large enough (150 x 150 cm), wheelchair-height toilet seat, folding grab rails, accessible hand basin, doorway is openable (not to heavy), no steps
* No means toilets is not accessible at all : steps, door is too heavy or not large enough
* Limited means : you can access the toilet : door is large enough, no steps, door is openable but the services are limited (for ie their is no grab rails)

References :
 * [toilets:wheelchair](https://wiki.openstreetmap.org/wiki/Key:toilets:wheelchair)
 * [wheelchair](https://wiki.openstreetmap.org/wiki/Key:wheelchair#Toilets)

### Checklist
Checklist for quest suggestions (see guidelines):
- [ ] 🚧 To be added tag is established and has a useful purpose
- [x] 🤔 Any answer the user can give must have an equivalent tagging (Quest should not reappear to other users when solved by one)
- [ ] 🐿️ Easily answerable by everyone from the outside but a survey is necessary 
- [x] 💤 Not an overwhelming percentage of elements have the same answer (No spam)
- [x] 🕓 Applies to a reasonable number of elements (Worth the effort)

Remarks: 
* Tag is more or less established in regard to the 2 references I put, and [taginfo](https://taginfo.openstreetmap.org/keys/?key=toilets%3Awheelchair#values). Issue is that limited option is not explicitely set on wiki key:toilets:wheelchair but is on wiki key:wheelchair. Nevertheless the subtag system (wheelchair=*) has this "limited" option. I assume that the wiki for toilets:wheelchair is not up to date and would integer a limited option. Still this tag, "limited" is used (1000 times, see taginfo link)
* One would need to enter the amenity to fill in this quest, so as for similar quest, I would disable it by default. 

### Ideas for implementation

**Element selection:**  toilets=yes or toilets:access=customers or permissive or yes.

**Comment by rugk** [comment]
Please fill out the "new quest" issue template if requesting a new quest. Otherwise, we cannot accept it here.

**Comment by ViolaineDo** [comment]
> Please fill out the "new quest" issue template if requesting a new quest. Otherwise, we cannot accept it here.

Sorry I wasn't sure if it needed to be discussed first, done now

**Comment by rugk** [comment]
Thanks for filling it out.
FYI: The template is exactly the thing you need to fill out _in order_ for it to be discussed. :smile: 

Now some remarks about the general idea:
* Why did not you tick "To be added tag is established and has a useful purpose"? As far as I see it, it fits both these criterias. Anything that speaks against it?
* The problem I see is the "difficult"/extensive criteria you indicated in your answers. These are quite a lot… this is hard to explain/convey in a small space/quest that we have when asking a quest.
  I know [it's possibly an issue of the tag, because the wiki lists this criteria, too]https://wiki.openstreetmap.org/wiki/Key:toilets:wheelchair#Usage).
* You mentioned the result "Limited". However [this is not listed in the wiki](https://wiki.openstreetmap.org/wiki/Key:wheelchair#Toilets). Wiki has only yes or no… :thinking:

**Comment by ViolaineDo** [comment]
>     * Why did not you tick "To be added tag is established and has a useful purpose"? As far as I see it, it fits both these criterias. Anything that speaks against it?

Just because of the issue of the limited tag you also pointed out. I explained my view in my remarks.. "Tag is more or less established in regard to the 2 references I put, and taginfo. Issue is that limited option is not explicitely set on wiki key:toilets:wheelchair but is on wiki key:wheelchair. Nevertheless the subtag system (wheelchair=*) has this "limited" option. I assume that the wiki for toilets:wheelchair is not up to date and would integer a limited option. Still this tag, "limited" is used (1000 times, see taginfo link)" 

>  * You mentioned the result "Limited". However this is not listed in the wiki. Wiki has only yes or no… thinking There is a quite old and unanswered discussion about that, but nobody replied…
I would think not many would have seen this..  I do think that the wiki is not up to date on some places and that we need to play with taginfo, and crossreference different wikipages... Here a subtag doesn't take all the possible values of the initial tag (wheelchair) which is for me a problem...

**Comment by ViolaineDo** [comment]
One more input about this value limited : it is integrated in the wiki page about toilets (so i think it can be used): https://wiki.openstreetmap.org/wiki/Tag:amenity%3Dtoilets#Toilets_within_places

**Comment by westnordost** [comment]
Sounds reasonable, however, being disabled by default, this'd have quite a low priority to implement.
