### ISSUE TITLE
Question improvment: Has bus shelter OR is covered

### ISSUE THREAD

**Issue by Echolon** [westnordost/StreetComplete#1395]
Hello, 
I would like to suggest a minor improvement. The question about bus shelter should also offer to tell that the station is only covered (is the case normally for big or central busstations).

For example: 
https://de.wikipedia.org/wiki/Datei:ZOB_in_Flensburg_(2012).JPG
https://de.wikipedia.org/wiki/Datei:Zob-hamburg-lot.jpg

Kind regards

**Comment by westnordost** [comment]
Hmm, the quest type is intended for bus stops. But I understand that you noted that it is also asked for bus stations?

The quest is asked on `node`s with the tag `public_transport=platform`. To be able to answer something along the lines as _"there is not a shelter but the public transport platform is actually completely covered (with a roof)"_ appears to me as unsuitable when the shelter-question is asked only for nodes, not areas.

**Comment by Echolon** [comment]
You may just ask the user: How is the bussation covered/protected

Not covered - picture
Shelter - picture
Cover roof - picture

**Comment by westnordost** [comment]
The quest is not asked for bus stations, only for public transport platforms.

**Comment by Echolon** [comment]
But where is the problem about this?

**Comment by westnordost** [comment]
The pictures you gave as examples are from bus stations, not from public transport platforms.

The quest is only asked for public transport platforms **that are mapped as nodes**. So, this is usually only bus stops.

**Comment by Echolon** [comment]
Okay, like in the question about what kind of path is that (tarmac, paving stones,...) several options or examples could be shown, would that help?

**Comment by westnordost** [comment]
Can you show some examples of bus stops that are covered?
