### ISSUE TITLE
Does this restaurant have a kids area?

### ISSUE THREAD

**Issue by gorgobacka** [westnordost/StreetComplete#1397]
### General
Affected tag(s) to be modified/added: [Key:kids_area](https://wiki.openstreetmap.org/wiki/Key:kids_area)
Question asked: Does this restaurant/place have a kids area?

This tag is currently not much used. But for some people (like me) this information would be very helpful to plan the next family trip.

### Checklist
Checklist for quest suggestions (see guidelines):
- [X] 🚧 To be added tag is established and has a useful purpose
- [X] 🤔 Any answer the user can give must have an equivalent tagging (Quest should not reappear to other users when solved by one)
- [ ] 🐿️ Easily answerable by everyone from the outside but a survey is necessary 
- [ ] 💤 Not an overwhelming percentage of elements have the same answer (No spam)
- [X] 🕓 Applies to a reasonable number of elements (Worth the effort)

### Ideas for implementation
A simple Yes/No question would do the job.
But it could also be extended by indoor/outdoor/supervised/fee. Although, I think this wouldn't be neccessary.

**Comment by westnordost** [comment]
It is not answerable from the outside.

Also, the tag is not established enough for inclusion in StreetComplete, sorry. StreetComplete is not the place to push new tags.
