### ISSUE TITLE
Map tiles don't load since version 12.0

### ISSUE THREAD

**Issue by MaestroGlanz** [westnordost/StreetComplete#1399]
Since I updated to v12.0 the app doesnt load map tiles for the background any more. It is just the tan background color with the quests displayed. This does not affect all areas.

This issue did not appear in 12.0 beta.

If I zoom a lot out of the non displayed areas and zoom in again, the background map is loaded, but not the buildings. The streets are only displayed as thin lines. Quests appear still normal.

I tried:
- deleting all data
- set map cache to 1 and back to 250
- waiting
=> nothing did affect it.

This issue is contrary to Google-Store-App (where I normally can't connect with mobile data) also on wifi.

Android is 7.0, Honor branding

**Comment by ENT8R** [comment]
In my region all tiles are loading, so it seems to be just a local issue...
Could you tell in which city this happens exactly?
@Akasch

**Comment by MaestroGlanz** [comment]
It is Ludwigsburg and Schwieberdingen, but also Eisenburg, Memmingen.

**Comment by MaestroGlanz** [comment]
I tried to add Screenshots. Neither Firefox nor Seamonkey works.

**Comment by Akasch** [comment]
I am investigating

**Comment by Akasch** [comment]
Schould be working again.

**Comment by MaestroGlanz** [comment]
It does. Thanks.
