### ISSUE TITLE
make clear whatever pull requests are welcomed

### ISSUE THREAD

**Issue by matkoniecz** [westnordost/StreetComplete#140]
In readme file only translating and testing is mentioned. Some people would at least consider contributing code - maybe mention that it is welcomed.

I may make PR that makes clear that patches are welcomed - would it be welcomed?

**Comment by westnordost** [comment]
Hehe, I'll just write sth myself, thank you for mentioning it.

On 25 April 2017 07:52:50 CEST, Mateusz Konieczny <notifications@github.com> wrote:
>In readme file only translating and testing is mentioned. Some people
>would at least consider contributing code - maybe mention that it is
>welcomed.
>
>I may make PR that makes clear that patches are welcomed - would it be
>welcomed?
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/westnordost/StreetComplete/issues/140

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by westnordost** [comment]
done
