### ISSUE TITLE
Dark - bright theme - automatic switching did not work - minor bug

### ISSUE THREAD

**Issue by MaestroGlanz** [westnordost/StreetComplete#1400]
While having my other bug, I found a new, minor one.

The automatic switching of bright-dark theme did not work. It worked only after manually switching to dark, then bright, then auto again (switching to bright might be skipped, but thats what I did).

I guess, that the standard setting is bright, though it shows auto in the settings.

**Comment by westnordost** [comment]
In which cases does it not work? Do you expect to use the app and then at sundown, it switches to dark? Or does not not work at all, even if you end the app and start it new?

**Comment by matkoniecz** [comment]
In my experience app attempts to

> use the app and then at sundown, it switches to dark

but sometimes it breaks. For example styling changing partially, resulting in black text on very dark background. So far I made no attempts to reproduce it as change seems to happen depending on time (and I am not using dark style at all, so I never encountered it in my own use).

Restarting app fixed it in two cases when I encountered it.

**Comment by westnordost** [comment]
I cannot reproduce this.

**Comment by gmischler** [comment]
A few days ago, I have seen the "black text on dark background" effect as well.
I think that happened when I had selected "dark" manually during the day.
The "auto" setting seems to do the right thing day and night.
When I select "light" at night, everything looks as expected as well.
Apparently there is a specific combination of time and settings (and/or maybe sequence of settings changes) that triggers the issue.

**Comment by westnordost** [comment]
The "black text on dark background bug" (and the opposite) has been fixed some versions ago.
