### ISSUE TITLE
StreetComplete doesn't load all maptiles

### ISSUE THREAD

**Issue by boute002** [westnordost/StreetComplete#1401]
Since version 12.0, StreetComplete doesn't load all map tiles. Some tiles not loaded. Internet connection is fine. I did restart my phone, but problem remained. My phone is an Ulefone Amor 3, Android version 8.1.0
![Screenshot_20190520-182006](https://user-images.githubusercontent.com/30781749/58039125-1d336700-7b32-11e9-8a1c-a127013cb87c.png)

**Comment by matkoniecz** [comment]
What is the location where this happens? See #1011 for discussion of more general issue.

**Comment by Akasch** [comment]
Can you tell the approximate location so I can investigate?

**Comment by boute002** [comment]
Sorry, The location is https://www.openstreetmap.org/search?query=schiedam#map=19/51.92868/4.37243

**Comment by boute002** [comment]
Laan van Bol'Es Schiedam

**Comment by boute002** [comment]
I had it Last week also in Rotterdam

**Comment by Akasch** [comment]
I can reproduce it, I will fix it

**Comment by matkoniecz** [comment]
@Akasch Thanks again for keeping SC tile server alive!

**Comment by Akasch** [comment]
should work again, after a server restart some regions where not started correctly.

I have to find the time to implement an automatic monitoring for such failures....

**Comment by boute002** [comment]
All, Thanks for the quick response and solution.
