### ISSUE TITLE
How often are map tiles updated?

### ISSUE THREAD

**Issue by zyphlar** [westnordost/StreetComplete#1403]
I just realized that houses I've added to OSM are appearing as house number quests, but the underlying map graphics are outdated (the quest appears above what seems to be empty land.) Is this a server-side limitation or do I need to do something locally to refresh this?

**Comment by ENT8R** [comment]
When did you added the houses exactly? More than 2 weeks ago?

**Comment by matkoniecz** [comment]
It is a known issue, see #1011

Unfortunately in most of the world map is never updated. See https://github.com/westnordost/StreetComplete/issues/1011#issuecomment-495168351 for more details and https://map-data.de/#map=3/0/0&style=cinnabar&show_server for map (red area is never updated or extremely rarely, yellow is also not update but it is planned to change in the future)

**Comment by zyphlar** [comment]
I see, thank you for the prompt reply. I guess I didn't scroll back far
enough in the list of issues!

I guess my confusion was because OsmAnd allows me to download vector maps
"straight" from OSM, so I figured that was relatively standard. Is there a
reason for going with rasterized tiles?

I'd be interested in hosting a regional server but I have to wonder how
much use and terrible it'd be for an American to host American data on a
German map server that only seems to be used by this app. Maybe I'll just
sit patiently for the nextzen data to update.

**Comment by matkoniecz** [comment]
> Maybe I'll just sit patiently for the nextzen data to update.

There is risk that it may not happen, or happen in a far future it is maintained by volunteers after Mapzen company was closed (see #747)

> Is there a reason for going with rasterized tiles? 

Initially Mapzen was existing so it is still unsolved result of its sudden closure.

>  I guess my confusion was because OsmAnd allows me to download vector maps "straight" from OSM

Data is from OSM, files are from OsmAnd servers. Hosting of OsmAnd servers is paid by OsmAnd (presumably covered by money earned by OsmAnd).

> I'd be interested in hosting a regional server but I have to wonder how much use and terrible it'd be for an American to host American data on a German map server that only seems to be used by this app.

I think that it is likely to be useful, outdated map data remain one of the biggest weaknesses of this application. See https://github.com/westnordost/StreetComplete/issues/1011#issuecomment-495168351 for requirements for server.

**Comment by zyphlar** [comment]
Okay I'm unsure if I have the bandwidth and money to add it to my list of
things to sponsor, but I'll keep it in mind. I've read some ideas about
using satellite imagery, was that ever an option? Then at least referencing
the quests to a graphic is possible.

**Comment by matkoniecz** [comment]
covered by "add functionality to show satellite map", issue #56

**Comment by westnordost** [comment]
Satellite imagery was always an option, only I was never motivated enough to implement. It is not really a lot of work. Though, even with satellite imagery, you'd want to show the street names and housenumbers.

Anyhow, if you are interested in hosting vector data for some part of the United States, see https://github.com/westnordost/StreetComplete/issues/1011#issuecomment-495168351
That data would be hosted on your server, not on some German one. `map-server.de` forwards the calls to whatever map server is responsible for a region.

**Comment by zyphlar** [comment]
I just downloaded an app called Observe and it seems to have raster map tiles direct from OSM with very recent updates. Any reason why that's not an option?
