### ISSUE TITLE
remove building = government

### ISSUE THREAD

**Issue by martin-scholtes** [westnordost/StreetComplete#1404]
As the [wiki ](https://wiki.openstreetmap.org/wiki/Tag%3Abuilding%3Dgovernment)describes, it is not desirable to get the key building = goverment as this describes the building function and not the design. For the building function building: use should be used.

**Comment by matkoniecz** [comment]
Note that it may be possible that wiki is incorrect and should be changed/amended.

**Comment by westnordost** [comment]
The wiki is fine. The wiki doesn't say that the tag should not be used, it says that if it is an office building, it should be tagged as an office building.

`building:use` is only used if the current function deviates from the original purpose. If the building was built as for example a parliament, a town hall, maybe courts or some other kind of representative government building, the tag `building=government` suggests itself.

**Comment by westnordost** [comment]
Closing because no replay for over two weeks
