### ISSUE TITLE
[Feature] Reflect visual changes immediatly after edits

### ISSUE THREAD

**Issue by MegaArthur** [westnordost/StreetComplete#1405]
Hello,

I have thought of a feature that would probably help motivate people to edit more often. 

It would be nice if edits with visible visual changes (e.g. setting the number of building levels, roof shape or even road surface and street lighting) was reflected and shown immediatly on the map screen.

It would give contributors a completionist feeling and IMHO strongly motivate them to contribute more.

**Comment by ENT8R** [comment]
I agree that this would probably encourage users to answer a lot more questions as there would be a real progress then and users are directly seeing that their time they spent is useful.
But looking on it from a technical point of view, I think this is very diffucult (or even impossible) to implement: The data which is shown in the main view basically consists of two layers:
- the map to give a rough overview to the user where you are right now
- the quests

Those two data sources are independent from each other, so after you solve a quest it takes a few weeks for the map tiles to get updated and shown in the app. I currently can't think of any possibility to influence the display of the map with any own data... And I doubt that this is still in the range of [tangram-es](https://github.com/tangrams/tangram-es) (the map rendering library)

**Comment by MegaArthur** [comment]
Regarding the sync delay, it could be done locally, way properties could be injected before they are rendered, assuming they're vector maps.

**Comment by westnordost** [comment]
The idea is cool. I also thought about that when I started the project years ago. But looking at it now, while it might be technically doable theoretically (add new device local layer in local MBTiles database that is rendered the same way as the background map but appears (somehow) above it and add data from selected quest solvings to that layer; reload that database on each solving of a certain quest), I think the effort to implement this far outweights the gain. As @ENT8R said, I am not sure myself if the above is even possible in tangram-es. 
Also, it would only be relevant for the building height, addresses and street names, so only for a small subset of all quests.

Locally injecting is not possible really, tangram-es queries directly from the server. 

So, I am closing this. The idea is good, but technically not really doable or if, too much effort.
