### ISSUE TITLE
Note attached to the map in wrong position?

### ISSUE THREAD

**Issue by Bu33zhidao** [westnordost/StreetComplete#1406]
I've just used StreetComplete to add a note to the map and it seems it ended up with a wrong position. I'm referring to note #1791879. I was standing approx. here (https://osm.org/go/0GGIx9dp1-?layers=N&m=) when I added the note, but now the note can be found here https://osm.org/go/0GGI06Xuk-?layers=N&m=. I haven't walked along this place before or after adding the note.

Phone: Sony Xperia X
OS: Sailfish 3.0.3.9
App: StreetComplete 12.0

**Comment by westnordost** [comment]
The note is not placed where you stand, but where you put the pin. Was the pin not showing for you?

**Comment by Bu33zhidao** [comment]
Ah, OK. At least I didn't notice the notice the pin ;-)
I've checked it again and the pin is clearly visible. Also the description "move map to position the note" is very clear. So this was just up to me. Sorry!

**Comment by westnordost** [comment]
No problem, thanks for opening a ticket though. If it was a bug, it would have been a quite severe one.
