### ISSUE TITLE
Disable or adapt house number quests for Japan

### ISSUE THREAD

**Issue by westnordost** [westnordost/StreetComplete#1407]
The addressing system in Japan is very different from the standard street + housenumber addressing system used elsewhere. The quest in its current form should probably not be offered in Japan.

Same with the street name quest (streets usually have no name).

@higa4 , I need some input from a Japanese national here to fully understand it because the wiki is not complete here. Can you help?

According to [this source](https://resources.realestate.co.jp/living/how-to-read-a-japanese-address/) and the wiki, a full address looks like this, translated to OSM:

`addr:postcode = 106-0044`
`addr:province = 東京都` (Prefecture. One of 青森県, 東京都, 大坂府, 京都府 or 北海道)
`addr:city = 港区` (Municipality)
`addr:suburb = 中央区` <- what is this in the linked source?
`addr:quarter = 松波` <- what is this in the linked source?
`addr:neighbourhood = 一丁目` says the wiki, but "一丁目" translates to "District 1". So,   shouldn't this be a number, i.e. `addr:district_number`? Or are there also named districts?
`addr:block_number = 12` (番地)
`addr:housenumber = 13` (号)

Finally, the only thing that is actually necessary to know from all this complexity for StreetComplete, is, how a housenumber plate looks like. The plate that is attached to an entrance or building. Does it show only the housenumber, but also the block and district number?

**Comment by dazeo** [comment]
The photos show what the plate looks like.  The first one is for a block and the second one is for an individual home.

![addresssample2](https://user-images.githubusercontent.com/7299407/58598593-edb1f680-82b7-11e9-9c23-036a56352523.jpeg)
![addressSample](https://user-images.githubusercontent.com/7299407/58598595-f1457d80-82b7-11e9-8b2f-f39aae250865.jpg)

港区(Minato-ku), and 中央区(Chuo-ku) are the same category<-ku>.
++++++++
addr:city = 港区 (Municipality)
addr:suburb = 中央区 <- what is this in the linked source?       //addr:city = 中央区(Municipality)
++++++++

++++++++
addr:neighbourhood = 一丁目
++++++++
一丁目 is exactly "District1." 
It depends on the place, but, the address has two districts: the larger one and the smaller one.

**Comment by westnordost** [comment]
So, the first photo is
```
addr:city=品川区
addr:quarter=東五反田
addr:neighbourhood=2丁目
```
and
```
addr:block_number=1
addr:housenumber=1
```
right?

**Question**: Do **all** individual housenumber plates have a house number **and a block number**, also on the countryside?

**Comment by dazeo** [comment]
Your understanding about the first photo is correct.

This plate system is widely seen all over Japan. However, the style has
minor variations.

2019年5月30日(木) 22:10 Tobias Zwick <notifications@github.com>:

**Comment by westnordost** [comment]
Okay this looks like this now:

![ezgif-2-54d309e7ef5a](https://user-images.githubusercontent.com/4661658/58754420-d0f00b80-84cf-11e9-949e-6376361ac9d6.gif)

**Comment by dazeo** [comment]
Great!!!


2019年6月2日(日) 7:52 Tobias Zwick <notifications@github.com>:
