### ISSUE TITLE
Verständnisfrage zum Quest-Cache?

### ISSUE THREAD

**Issue by Natenom** [westnordost/StreetComplete#141]
Ich habe den Quest-Cache bei mir auf einen Tag eingestellt. Wenn ich also vor 24 Stunden Quests in einem bestimmten Ort abgerufen habe, würde ich erwarten, dass diese nach 24 Stunden nicht mehr sichtbar sind.

Jedoch sehe ich auch nach vielen Tagen immer noch alle Quests, die ich mal abgerufen hatte, auch wenn ich vorher jeden Netzwerkzugang deaktiviere.

Oder soll es so sein, dass diese Quests zwar noch sichtbar sind, aber in demselben Moment aktualisiert werden, wenn Netzwerk verfügbar ist?

**Comment by westnordost** [comment]
Vielleicht sollte man die Formulierung ändern, das hat schon mehrere User verwirrt. Mir ist bisher keine prägnantere eingefallen.

Die Einstellung beeinflusst, nach welcher Zeit Quests als "alt" markiert werden. Als "alt" markierte Quests werden beim nächsten Herunterladen (ob manuell oder automatisch ist egal) erneut heruntergeladen. Beim erneuten Herunterladen werden neben möglicherweise neu hinzugekommenen Quests auch diejenigen gelöscht, die von anderen Usern erledigt wurden.

Es bedeutet nicht, dass die Quests nach 24 Stunden gelöscht werden, sondern dass sie nach dieser Zeit als "sollte mal aktualisiert werden" markiert werden. Also die Zeit, in der man als Benutzer mitbekommt, dass auch andere Benutzer in der Gegend Quests lösen.
Dieser Mechanismus (dass Quests nicht generell "sofort" aktualisiert werden) dient dem, dass der Overpass-Server nicht mit zu vielen unnötigen Queries überfrachtet wird.

Im Prinzip, wenn man keine gute Formulierung findet, kann man die Option auch gleich weglassen und dieses Intervall auf eine feste Zeit stellen die Sinn macht.

**Comment by Natenom** [comment]
Vielleicht wäre es eine Möglichkeit, solche Quests halbtransparent oder sonstwie anders hervorzuheben und mit dem Hinweis beim Öffnen, dass diese schon x alt sind und ggf. veraltet sein könnten und dass man das auf eigene Gefahr macht oder lieber aktulisieren sollte.

**Comment by westnordost** [comment]
Nee, unnötige Komplexität und Benutzerverunsicherung. Theoretisch kann jedes Quest quasi sofort veraltet sein. Es ist nicht schlimm wenn man Quests löst die schon gelöst wurden, die doppelten werden beim Upload dann einfach still fallengelassen.

On 25 April 2017 12:41:41 CEST, Natenom <notifications@github.com> wrote:
>Vielleicht wäre es eine Möglichkeit, solche Quests halbtransparent oder
>sonstwie anders hervorzuheben und mit dem Hinweis beim Öffnen, dass
>diese schon x alt sind und ggf. veraltet sein könnten und dass man das
>auf eigene Gefahr macht oder lieber aktulisieren sollte.
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/westnordost/StreetComplete/issues/141#issuecomment-296991351

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by lightonflux** [comment]
> doppelten werden beim Upload dann einfach still fallengelassen.

Bekommt man trotzdem "Punkte?

**Comment by westnordost** [comment]
Nein

**Comment by Almtesh** [comment]
Sorry, can you only use English, so people can understand the issue and do not post another issue for that?

**Comment by westnordost** [comment]
In a nutshell: The quest cache has nothing to do with how long or how many quests are saved in local storage but how often the app attempts to refresh the quests from server (because there may be other users around that solve quests).
At the end of the discussion, I came to the conclusion that the option should be removed for the users because it only confuses them and instead be controlled globally for all apps (by some constant).

**Comment by rugk** [comment]
Maybe change the wording to "update quests after XY days" or "mark quests as outdated after XY days".
