### ISSUE TITLE
Building height evaluation

### ISSUE THREAD

**Issue by cascafico** [westnordost/StreetComplete#1410]
### General
Affected tag(s) to be modified/added: [height](https://wiki.openstreetmap.org/wiki/Key:height)
Question asked: **Which is the estimated building height?**

You can evaluate height considering each level usally spans 3 meters.
### Checklist
Checklist for quest suggestions (see guidelines):
- [x] 🚧 To be added tag is established and has a useful purpose
- [x] 🤔 Any answer the user can give must have an equivalent tagging (Quest should not reappear to other users when solved by one)
- [x] 🐿️ Easily answerable by everyone from the outside but a survey is necessary 
- [x] 💤 Not an overwhelming percentage of elements have the same answer (No spam)
- [x] 🕓 Applies to a reasonable number of elements (Worth the effort)

### Ideas for implementation

**Element selection:** 
```
way["building"][!"height"]({{bbox}});
relation["building"][!"height"]({{bbox}});
```

**Metadata needed:** 

**Proposed GUI:**

**Comment by westnordost** [comment]
The `height` is not the estimated height, but the exact height.

There is already the quest that asks for how many levels a building has, so exactly what you would like to have, it seems: `building:levels`

**Comment by cascafico** [comment]
I know there's already a building:level quest. My proposal is a little different. In my region, building are mostly from a cadastre import; AFAIK cadastres usually don't keep building level information, so I'm looking for a fast and practical tool to populate height tag aiming to environmental 3D renderings.
About height precision, in OSM there are lots of approximate values, due to GPS accuracy, photo estimations (Mapillary, Opestreetview...), tree growth ecc., so I wouldn't consider this matter as discriminatory.

**Comment by pkoby** [comment]
StreetComplete is about on-the-ground survey. So if you go to the imported buildings in-person, you can add the `building:levels` info by looking at the building. This app is not about fast data addition over a lot of area.

So I don't understand what this would add. You can add the estimated height in the form of `building:levels` already. If you really want to add `building:height` (which I would advise against if you're just estimating it), then you could infer from `building:levels` and `roof:level` × 3m to get the height. You'd still have to go there in person, though, either way.

**Comment by westnordost** [comment]
So I'll close this. Maybe an exact height could be determined by using the smartphone as an angle meter. But this is not what this issue was about.
