### ISSUE TITLE
Don't ask about crossing type for railway=abandoned

### ISSUE THREAD

**Issue by camelCaseSucks** [westnordost/StreetComplete#1413]
The app still asks about how crossings are protected for railways tagged as abandoned. If it's abandoned, the crossings are irrelevant. In my case, the tracks have been paved over so only the tops are visible in the surface of the street. I was confused for a minute about what tracks it was referring to because they are unnoticeable unless you're looking for them.

**Comment by matkoniecz** [comment]
It can be argued that data is simply wrong for paved-over tracks (it is no longer a level crossing). But to avoid confusing users it may be also excluded (in addition to tramway rails and private roads).
