### ISSUE TITLE
Missing option for bus stop under a builduing or large roof

### ISSUE THREAD

**Issue by PanderMusubi** [westnordost/StreetComplete#1417]
**How to Reproduce**
Find bus stop under building or large shared roof. Is an option missing missing for this? See screenshot.

![Screenshot_20190605-070951](https://user-images.githubusercontent.com/198964/58931831-7a99fb80-8761-11e9-80fe-a7c404813c40.jpg)

Perhaps offer option for `covered`, see https://wiki.openstreetmap.org/wiki/Tag:building%3Droof

**Versions affected**
12.1

**Comment by westnordost** [comment]
Fair enough. I was not sure if cases like these actually exist in the real world. Turns out they do, so I will create an "other answer" option for this.
