### ISSUE TITLE
Download all quests in a given area

### ISSUE THREAD

**Issue by ghost** [westnordost/StreetComplete#1418]
**Use case**
User have a bad or limited phone connection so they have to download quest for an area at home but as the total number of quest is increasing exponentially, it keeps getting longer to download all quest from an area.

**Proposed Solution**
It would be easier if we could choose the percentage of the total of quests that we can download in one go. Doing so would allow user to just launch a manual download one time and wait for it to finish while doing something else instead of waiting around and coming back several time to relaunch another download.

**Comment by westnordost** [comment]
Why would you need to have all quests in an area downloaded?

**Comment by callis** [comment]
I vote for a 'download them all' feature. The usecase for me would be: clear all quests in my neighborhood without revisiting a place or a repetitive download procedure.

**Comment by Dostoi** [comment]
When I go from point A to point B I like to clear quest on the way on my bike without having to wait for the download to finish (which can be long, we don't all have great internet connection on our phone), then relaunching another one and so on up until I have all quest.
Same as callis, this way I know that on my way back, I can finish the one left.

**Comment by westnordost** [comment]
@callis , well, this is not really technically possible anyway, and also does not really fit to the user story of this app:
1. Technical limitation: Some quests depend on other quests being solved first. So, these quests won't show up until the dependent quest has been answered and uploaded. Example: The building type needs to be specified before the housenumber or building levels can be specified. Roof shape can only be specified after the roof levels has been answered. I think sidewalk can only be answered after the lit quest was answered, etc.
2. With continued development of the app, and also growing details on the map (i.e. people adding buildings), there will always pop up new quests over time. We must arrange ourselves with the fact that the map will never be "done" but we can always only work towards making it more complete.
3. The quest download already works this way that if "not enough" quests are found when downloading the first X quest types in the queue, it will download the next X quest types in the queue - until there are enough. So, when using the app, you should never be "stranded" with no quests to do.
4. Thus, the user story of this app is to tag some stuff on the side, while you are going from A to B. Not a tool to do a "complete" survey. Making photos or other notes and then putting the data on the map via JOSM, iD or Vespucci is still the most efficient way to do such a complete survey. It makes no sense for StreetComplete to compete here.
5. Not showing all the quests at once to the surveyors has not only performance deliberations but also psychological: The surveyors should not be overwhelmed by the things to do ("I can never complete all this!" "This looks like work"). Instead, there should be always something to do, but not too much.

**Comment by westnordost** [comment]
So, maybe the "enough quests" settings is not tuned right. Currently, on a mobile data connection, there need to be at least **8 quests per km² in a radius of 300m** for the automatic download to stop.

**Comment by Dostoi** [comment]
1. Downloading all available (doable right now) quest would already be a huge improvement.
2. Yes I totally agree, but with this we could do all that can be done at the time. And the next time we come back to this area we could check out if there's new quest to answer.
3. This doesn't solve the issue for user with bad or limited internet connection on their phone
4. The goal isn't to do a complete survey but to be able to answer the maximum of quest the easiest way.
5. I'm not asking to show all quest at once, I totally agree with that. I just want to be able to only do one download of an area, then answer quest as they pop on the screen as it's already working.

Again, it wouldn't work for people with a bad or limited internet connection, it can be really long before the download is finished.

**Comment by westnordost** [comment]
> 3. This doesn't solve the issue for user with bad or limited internet connection on their phone

Yes, that is true. Though, note that a manual download will download 10 quest types in a row. That is quite a lot already, wouldn't you say? Should it be more? Or should it work the same as the autosync? (Download as long as "enough" are around)

> Again, it wouldn't work for people with a bad or limited internet connection, it can be really long before the download is finished.

Actually, for some quests, what takes long is not the response from the server but processing the result. The housenumbers quest is one of those. Got no data on it though.

**Comment by Dostoi** [comment]
Well I really would like to be able to go to a place with wifi, download everything that can be downloaded in one click (and not "enough", taking into account that some quests can't be downloaded as long as other quests aren't answered first) while doing something else in this place and then go out and answer the quest from this area on my way to point B.

**Comment by westnordost** [comment]
Hmm well, if this is implemented in the way you would like it to be, I think the download must be
1. cancellable by the user, for example if he is about to leave the café with wifi but the app is still downloading stuff
2. there needs to be more insight for the user about what has been downloaded already or at least what it is downloading now, so that the user can judge whether his favourite quests are already through

**Comment by Dostoi** [comment]
Well both 1 and 2 could be nice feature for the app as it is.
It's an optional feature that could help to quickly improve the quality of OSM.

**Comment by MegaArthur** [comment]
I'm also for the changes. Downloading many quests in a big area is especially valuable when abroad, so someone can download while they're connected to their hotel wifi and then go offline, cause mobile data is hella expensive when roaming.

**Comment by GITMichaelK** [comment]
As far as I understand, this issue is similar to [#122](https://github.com/westnordost/StreetComplete/issues/122). 
I strongly support both, would be really great to have a solution for an offline usage!

**Comment by westnordost** [comment]
Not sure if I said this before, but this is low prio for me because it means building stuff for a library we use where I am not sure if we will keep it on the long term (tangram-es).

**Comment by GITMichaelK** [comment]
Thank you, Tobias: Yes you mentioned it during our discussion on #122. I'm really convinced about the the idea of your software but without offline-mode it is not usable for me. Sorry, but that's the way it is.

**Comment by westnordost** [comment]
Well, I'll be sure to notify you if/when I implement that feature. It **is** on my list, but really rather further down. By the way, does your last name contain an "ä"? Just asking because I might know you from somewhere else.

**Comment by Mannshoch** [comment]
In my case, loading the first Questions need long time for a region (1-5min) until they appear. If I do some family trips I activate streetcomplete on the way down and be the driver and let streetcomplete collect all Questions on the way down. On the back way home I'm usually the co-driver and I try to solve the Questions. That's only on areas possible where we drive in low speed e.g. until 50km/h if we are faster there's sometimes holes where streetcomplete was not able to download any question.
In most cases it helps to deactivate some slow questions. But I sometimes forget to tick that settings.
May it would help if you prioritize fast Questions.

I only could work that way because I have flat rate Mobil connection. I still like the Idea of downloading Data by share a GPX route to streetcomplete like in #473
