### ISSUE TITLE
Chinese translation in the "Namless" option for road name quest

### ISSUE THREAD

**Issue by c933103** [westnordost/StreetComplete#1420]
**How to Reproduce**
1. Use Traditional Chinese user interface
2. Find a road name challenge
3. Click the option that say "the road have no name"
4. The first option say, "看起來像是得來速或是停車道道", and I don't understand what that mean.

**Versions affected**
Android 8.0
StreetComplete version 12.1

**Comment by matkoniecz** [comment]
If you want you may fix it by yourself at poeditor, you can join by following link https://poeditor.com/join/project/IE4GC127Ki ( see https://github.com/westnordost/StreetComplete/blob/master/CONTRIBUTING.md#translating-the-app )

In general translation is done by volunteer translators, unlike other parts of the application.

> The first option say, "看起來像是得來速或是停車道道", and I don't understand what that mean.

Google translate claims that it means

> Looks like a drive-through or a parking lane

**Comment by westnordost** [comment]
Hi @c933103 

If you are Taiwanese (or from Hong Kong or other places where Traditional Chinese is written), you are invited to fix and enhance the translation yourself, @matkoniecz posted the link for that in the post above. The translations are all maintained by the community.

The English version of the string is _"It is something like a driveway or parking aisle"_. This option sets the tag [`highway=service`](https://wiki.openstreetmap.org/wiki/Zh-hant:Tag:highway%3Dservice).

I am closing this ticket because there is nothing I can do myself, the quality of translation depends on dedicated community members (as yourself).

**Comment by c933103** [comment]
I have googled the terms a bit, seems like those are vocabularies that are more commonly used by people in Taiwan, whereas people in Hong Kong don't really use these terms.
So it seems like the most direct fix to the problem would be to create a separate user interface translation for Traditional Chinese (Hong Kong) users, but that appears to be too much work for me to do, and given the relatively limited amount of population in the territory that interest in the OSM project, it is also difficult to expect enough people to contribute completing the translation as well as keeping it up to date.
So for the time being, to help my personal use of the software, is it possible for me to change the user interface into English so that I can bypass the problem when I use the app?

**Comment by matkoniecz** [comment]
> seems like those are vocabularies that are more commonly used by people in Taiwan, whereas people in Hong Kong don't really use these terms.

Is it maybe possible to find terms clear for both groups (and other groups)?

> is it possible for me to change the user interface into English so that I can bypass the problem when I use the app?

Application is using language set on phone in settings. Unfortunately on Android there is no easy way to implement changing language using application settings.

**Comment by c933103** [comment]
>Is it maybe possible to find terms clear for both groups (and other groups)?

Let me think about it a bit.. Chinese Wikipedia and some other dictionary translate driveway into something equivalent to "private car lane" in Chinese but I won't really understand that as referring to road types commonly used for highway=service if I see the term separately.
And the current translation "得來速" is a Taiwanese term for drive-through which mean it is wrong even for users in Taiwan so that will need to be changed.

>Application is using language set on phone in settings. Unfortunately on Android there is no easy way to implement changing language using application settings.
What about copying other apps like Osmand that do have such option?
