### ISSUE TITLE
The marker of a new note should be on our current position

### ISSUE THREAD

**Issue by bristow** [westnordost/StreetComplete#1422]
**Use case**

I used StreetComplete with my students. They created notes but they all left the marker position by default.
Thus, we end up with notes that are not correctly placed, as here on buildings : [](https://www.openstreetmap.org/#map=19/45.76959/4.82478&layers=N)

**Proposed Solution**

By default, marker for new note should be on our current position.

Thanks !

**Comment by ENT8R** [comment]
But on the other hand, other users might also expect the marker to be in the center of the screen... I don't know if it would be a good user experience when the map jumps to your current location after clicking the note creation button.

**Comment by bristow** [comment]
I can understand but i give you the feedback of new users... They don't touch at all marker :(

**Comment by westnordost** [comment]
Is the description shown not clear in French? It says that one should move the marker by dragging the screen.

**Comment by bristow** [comment]
Sure, it's clear but students don't read.
And what about a pop-up before send the note with : 
"Is the marker at the good place ?"

2 buttons : Movit it and Yes to confirm

**Comment by rugk** [comment]
> And what about a pop-up before send the note with

[in case you have not moved the marker]

**Comment by bristow** [comment]
> > And what about a pop-up before send the note with
> 
> [in case you have not moved the marker] (i.e. just add this as a conditional detection)

:+1:

**Comment by westnordost** [comment]
Hmm I noticed that when you press the button to add the note, the view stays where it is. Perhaps it would be an improvement that if the current GPS position is in view (not sure if I can find that out), the view will be focussed in the way that if the user does not move the map, the note will be created exactly at the current GPS position.

Would need to investigate if this is technically feasible. @ENT8R are you perhaps interested in trying this out - given that this feature is mainly your baby (in a good way)?

**Comment by bristow** [comment]
@westnordost :+1:

**Comment by westnordost** [comment]
I fiddled around with it a bit and it is at least not trivial to implement. (So I am not doing this for now, but maybe there are others who want to give it a try.)
