### ISSUE TITLE
Never ask for opening times for gyms/sports halls

### ISSUE THREAD

**Issue by cyclingcat** [westnordost/StreetComplete#1423]
During my StreetComplete actions in some villages nearby I often encounter sports halls for which opening hours quests are shown. However, none of them showed any opening hours visible from the outside, so I regularly have to hide the quest, which is quite annoying. I suppose that sports halls rarely have fixed opening times; they are open when some training or events take place and closed otherwise.

Proposal: Never show the opening hours quests when the object is tagged with "building=sports_hall".

This is a little bit related to #868 which led to excluding private objects from the opening hours quest - but here we have public (often municipal) buildings.

(StreetComplete 12.1 on Android 5.1)

The cycling cat

**Comment by matkoniecz** [comment]
> Proposal: Never show the opening hours quests when the object is tagged with "building=sports_hall".

Or rather simply drop `leisure=sports_centre` (https://github.com/westnordost/StreetComplete/blob/master/app/src/main/java/de/westnordost/streetcomplete/quests/opening_hours/AddOpeningHours.kt)

**Comment by westnordost** [comment]
A sports hall on school grounds that is not really public should not be tagged as `leisure=sports_centre` though. Or what kind of sports halls are we talking about?

**Comment by cyclingcat** [comment]
The ones I'm talking about are those local handball/volleyball/table tennis clubs exercise and play their tournament matches. They are not always connected to school grounds, although they are probably used by schools, too.

The cycling cat

**Comment by westnordost** [comment]
And these clubs do not have opening hours? Don't they have an office or something which would have opening hours?

**Comment by westnordost** [comment]
Also, would there be a tagging available that distinguishes local sports clubs from those more commercial places like fitness studios and so on?

**Comment by cyclingcat** [comment]
Hm... even if there are opening hours for those kinds of buildings: If they aren't accessible while standing in front of it and you thus have to do further research (e.g. on the websites of the village or the club) in order to answer the quest, this would this be out of the scope of SC, wouldn't it?

OSM wiki mentions "leisure=fitness_centre" (https://wiki.openstreetmap.org/wiki/Tag:leisure%3Dfitness_centre), but it seems to be a little more complicated, see https://wiki.openstreetmap.org/wiki/Gym_/_Fitness_centre.

The cycling cat

**Comment by westnordost** [comment]
Yes, it wouldn't. Okay your argumentation convinced me, I'll remove `sports_centre` from the list.
