### ISSUE TITLE
Replacing key 'diaper' with 'changing_table'

### ISSUE THREAD

**Issue by ValorNaram** [westnordost/StreetComplete#1424]
**Use case**
The key described at https://wiki.openstreetmap.org/wiki/Key:diaper has been superseded by https://wiki.openstreetmap.org/wiki/Key:changing_table

See also #344 for details for what I am talking about.

**Proposed Solution**
Please use `changing_table` instead of 'diaper'

**Comment by westnordost** [comment]
Ok. Can go into the next minor update.
