### ISSUE TITLE
Ignore zoom in geo intent

### ISSUE THREAD

**Issue by HolgerJeromin** [westnordost/StreetComplete#1425]
The geo intent should ignore (or limit) the zoom parameter.
I clicked a poi marker in osmand with german like scale and opened StreetComplete. Ups :-) 
The poi was the location i wanted to visit later and wanted to download the region via wifi. The marker was selectable in osmand so i did not bothered zooming in.

cc @ENT8R

**Comment by westnordost** [comment]
What is a german like scale?

**Comment by HolgerJeromin** [comment]
Sorry, germany size. Zoom 7 or such a small thing

**Comment by westnordost** [comment]
Okay but not sure if this should be done. It is not known by the receiver of a geo intent that the user clicked a POI or clicked on "open this view in another app".

**Comment by HolgerJeromin** [comment]
This app is not designed or useful for large areas. So limiting its size is imo the right thing.

**Comment by westnordost** [comment]
You have a point there
