### ISSUE TITLE
Map tiles about 6 months out of date

### ISSUE THREAD

**Issue by cart0** [westnordost/StreetComplete#1427]
I recall an issue with needing to find a new tile server and possibly my issue is someway related to #1011 

I have been updating the south side of Dublin Ireland for a long time now but for the last 6 months or so,  StreetComplete does not update the tiles for Dublin and likely Ireland as a whole.  This means than buildings, housing estates and other features are not visible.

It looks like the overpass  tasks part is working as I am getting asked for things like numbers or buildings,  building levels etc for items I have done in the last 6 months.

The problems is,  that without the map tiles getting update too, it makes it near impossible to use StreetComplete for task completion as you really need the tiles to ensure you are putting tags on the correct feature.

It would be great it Ireland tiles could be updated but if not,  it seems like a main feature of StreetComplete is broken and some sort of notice should be given to users when starting the app that it should not be used for accurate tagging if maps are going to be so out of date.

**Comment by matkoniecz** [comment]
"Map tiles about 6 months out of date" is ecxactly #1011

**Comment by westnordost** [comment]
Maybe it would be an option to instead show a satellite map. Outdated map data would then only be relevant insofar as names on roads, housenumbers and other labels may be wrong

**Comment by cart0** [comment]
@matkoniecz   ooops I somehow got tickets mixed up the one I thought I linked to was about corrupt tiles.  I guess it worked out :)

@westnordost  that sounds like a possibly workable option,  I think though that there would be a need to be able to reference multiple satellite sources.  I know for some areas here most are outdated by a couple of years and eventually one source might update and only be months out.
