### ISSUE TITLE
Better offline display in places where several quests appear

### ISSUE THREAD

**Issue by Mbodin** [westnordost/StreetComplete#1428]
Thanks for this app, it is very nicely done. I used it to fill in some quests in my neighbourhood. I don’t have access to the Internet on the street, so I really appreciate the fact that we can fill them offline and only latter have them sent. Most of the quests I got were of the form “What kind of surface area is this street made of?”. However, once I got back home, I discovered that new quests were being added in the place I went (typically “Does this street have lights?”). I find this a shame: if the other quests were to have been suggested when I was there, I could have answered both very easily. So it seems to me that only one quest per map item is stored in the cache, and that only when synchronising new quests appear.

**Use case**
It would be great not to have to pass several times in the same place, and to fill in all quests for a given place, even when one doesn’t have access to the Internet in the given location. The quests could then be fulfilled much faster.

**Proposed Solution**
Just download all quests of the neighbourhood ☺ If the quests are already all downloaded, it may just be an issue with the part of the program that displays the map: maybe it isn’t looking for similar quests when a quest has been fulfilled.

On a parallel note, it would be nice to have some diversity in the displayed quests: when both the “surface area” and “light” quests are available, it seems that only the “surface area” is displayed. It would be nice to just choose one at random. That way, one could get some sense of the diversity of different quests, especially people trying out the app for the first time ☺

**Comment by westnordost** [comment]
Hmm, this is a recurring issue, I should write a FAQ entry about it.
@Mbodin perhaps you want to read #1418

**Comment by Mbodin** [comment]
I agree that #1418 is completely related, sorry to have missed it.
From what I’ve read from the comments in this other report, it seems that the current report doesn’t actually add much to the discussion, so I’m closing it.

**Comment by rugk** [comment]
>  I should write a FAQ entry about it.

Actually, this one is supposed to already address it :thinking: :
https://wiki.openstreetmap.org/wiki/StreetComplete/FAQ#Why_does_StreetComplete_show_so_few_quests_when_I_first_start_the_app.3F

Okay, maybe not only when you first start the app, but each time you search… :thinking:
