### ISSUE TITLE
Quests may hide on zooming in

### ISSUE THREAD

**Issue by matkoniecz** [westnordost/StreetComplete#143]
There are no nearby quests but marker hides as I zoom in.

Quest is to fill surface of http://www.openstreetmap.org/way/131300934#map=19/50.08072/19.88907

**Comment by lightonflux** [comment]
Which version do you use? There are many bug reports about this. #50  

It appears to been fixed a week ago, but it is not shipped yet.

**Comment by westnordost** [comment]
Jup, that will be a duplicate.

**Comment by matkoniecz** [comment]
Sorry, I forgot to check closed issues.
