### ISSUE TITLE
Loading of map vector tiles around Armidale, NSW, Australia is broken

### ISSUE THREAD

**Issue by dbdean** [westnordost/StreetComplete#1431]
At present, loading of the map vector tiles around Armidale, NSW, Australia appears to be broken:

![Screenshot_20190619-124148](https://user-images.githubusercontent.com/12725310/59733050-e7e47b00-928f-11e9-893f-21457a8ec121.jpg)

**How to Reproduce**

Load StreetComplete in this region, particularly after clearing the cache in StreetComplete's App Settings.

**Versions affected**

StreetComplete 12.1 on Android 9

**Comment by Akasch** [comment]
I think I know the problem, I will fix it in the next two hours

**Comment by Akasch** [comment]
Should work again

Am 19. Juni 2019 04:46:47 MESZ schrieb David Dean <notifications@github.com>:

**Comment by matkoniecz** [comment]
@dbdean Is it now working?

**Comment by dbdean** [comment]
Yep, it seems to be working again. Thanks!
