### ISSUE TITLE
No wheelchair quest for attraction=animal

### ISSUE THREAD

**Issue by HolgerJeromin** [westnordost/StreetComplete#1435]
https://www.openstreetmap.org/way/95634218
Should not get a wheelchair quest. :-)

**Comment by matkoniecz** [comment]
It got as result of `tourism=attraction`. Still, in some cases it may be useful - some of them may be unavailable on wheelchair.

Not sure is this usefulness is so rare to make exclusion desirable.

**Comment by westnordost** [comment]
Why should it not? It can very well be that a certain enclosure in a zoo is not accessible via wheelchair. Let's say there are stairs leading to one enclosure or something

**Comment by HolgerJeromin** [comment]
I thought that `attraction=animal` was about the feature itself. There a `wheelchair` tag is not really useful (animals with wheelchairs? :)
But being able to watch the attraction seems to validate the quest.
