### ISSUE TITLE
Exclude unreasonably small buildings from building quests

### ISSUE THREAD

**Issue by matkoniecz** [westnordost/StreetComplete#1439]
On some places people attempting to 3D map buildings created many small `building` ways instead of a correct `building:part=yes`.

Such "buildings" should be skipped in building quests. See for example "`building=hospital`" with 4 square meters and 8 square meters: https://www.openstreetmap.org/way/302589861/history https://www.openstreetmap.org/way/302589873/history appearing in housenumber quest (among group of other similarly confusing requests for address).

See also https://josm.openstreetmap.de/ticket/17846#ticket https://github.com/openstreetmap/iD/issues/6573 where I proposed automatic detection of such objects by validators.

**Comment by matkoniecz** [comment]
> added the bug label 1 minute ago

I would not describe it as a bug, may be cause by a selected template (I as usual blanked prewritten text and provided necessary info without temnplate)

**Comment by westnordost** [comment]
If it is a data problem, it should be fixed in the data, not in the app

**Comment by westnordost** [comment]
My point of view is that as long as the answers StreetComplete users are giving won't make the data (more) *wrong*, StreetComplete does not have to be considerate of wrong or oddly mapped data.

I find it problematic to go down the road of intentionally hiding from the user odd or wrong data (by some fuzzy indication, e.g. a X must be at least this big!). If something strikes the user as odd, he should leave a note!

So even if there are i.e. building parts mapped as single buildings that are only a few square meters big, tagging it as hospital is fine as long as that building part is really part of a hospital (building) if the user himself does not find this odd. (As noted, he could leave a note saying that "there is not a small square building here, it is the elevator shaft of that big hospital"!)

**Comment by matkoniecz** [comment]
> tagging it as hospital is fine as long as that building part is really part of a hospital

This may be highly confusing, I encountered case where each step on `highway=steps` was mapped as separate `building` area.

> My point of view is that as long as the answers StreetComplete users are giving won't make the data (more) wrong, StreetComplete does not have to be considerate of wrong or oddly mapped data.

This report was prompted not by concern of damage to OSM data. It was rather about protecting user from highly confusing questions that can be skipped automatically. Experienced mapper will recognize problem but a newbie will be just confused and think that SC is being mistaken.

![Screenshot_2019-06-24-23-05-17-049_de westnordost streetcomplete debug](https://user-images.githubusercontent.com/899988/60052254-0eae1180-96d5-11e9-81a9-e861e6d2457d.png)

> If something strikes the user as odd, he should leave a note! 

This kind of mistake can be detected automatically, using mapper time to spot it is not too useful.

**Comment by westnordost** [comment]
What do you think the user will do/answer in the case you linked? And what can we do as the app developers to make it more clear that he should press "Can't answer" in order to report the problem n a case like this?

**Comment by westnordost** [comment]
I'll close this. The app should not try to account for incorrectly mapped data. Going down this road, there will be no end.
