### ISSUE TITLE
On tip on Compass allow to set front allong the orientation 

### ISSUE THREAD

**Issue by Mannshoch** [westnordost/StreetComplete#1440]
If I tip on the compass, streetcompleet set the front on landscape even I have portrait active.

**Comment by westnordost** [comment]
I don't understand what you mean. Could you elaborate or add a screenshot?

**Comment by MegaArthur** [comment]
I think he might have his magnetic sensor not calibrated? Happened the same to me after installing a beta custom ROM, the compass would make SC point sideways instead of straight ahead

**Comment by westnordost** [comment]
Moving your smartphone in circles like this:
# ∞
should calibrate it and after that, it should be fine.

**Comment by Mannshoch** [comment]
Simple do this move ∞ is not working.
According to some Blogs it seems that calibration is not so simple and depends on devices.

**Comment by westnordost** [comment]
Well, if the ∞ does not work, no idea. Calibrating the system compass is not really something the app can do.

**Comment by Mannshoch** [comment]
Was not the Idea that this App should handle that. 😅

**Comment by westnordost** [comment]
Ok then could you explain what this ticket is about?

**Comment by matkoniecz** [comment]
To reproduce:

1. disable screen rotation lock if enabled
1. rotate phone to portrait
1. glue view to position (bottom right button)
1. press compass to enable perspective (top right round button)
1. rotate phone to landscape

expected: StreetComplete rotates view to landscape

what happens: StreetComplete view stays in portrait

**Comment by Mannshoch** [comment]
The ticket is about an option that allow to set the view orientation to above. In Portrait and in Landscape. The orientation should point at top.
Do not look at Magnetic or gps orientation.

**Comment by westnordost** [comment]
@matkoniecz : can't reproduce this.

@Mannshoch : Sorry, still do not understand. Maybe write it in German?

**Comment by matkoniecz** [comment]
> @matkoniecz : can't reproduce this.

Sorry! I got confused by fact that I am used to setting "enable rotation lock" and on my current phone it is "enable rotation".

By attempting to "disable screen rotation lock if enabled" I disabled rotation, not rotation lock :(

**Comment by Mannshoch** [comment]
Sorry. Hätte nicht gedacht, dass es so schwierig wird das zu erklären. 
Wenn ich streetcomplete vor mir geöffnet habe, dann soll die Bewegungsrichtung immer von oben nach unten verlaufen. d.h. mich interessiert es nicht ob ich nun mit dem Rücken zur fahrtrichtung oder mich seitwärts bewege. Die Karte soll sich so orientieren, dass sie sich von unten nach oben bewegt. 
Aktuell bewegt sich die karte immer etwas um meinen Standort herum. Selbst wenn ich das Telefon vor mich auf den Tisch lege, dreht sich die Karte dauernd. Dies natürlich noch mehr, wenn ich das Mobiltelefon in der Hand halte.
Ausserdem sehe ich zudem immer winklig auf die Karte, da "vorne" nie tatsächlich vorne ist. Das wird besonders unangenehm, wenn ich perspektivisch drauf schaue, um weiter voraus zu sehen. Und faktisch nur Strassenränder sehe.

**Comment by rugk** [comment]
Is this a dupe of https://github.com/westnordost/StreetComplete/issues/988?

**Comment by rugk** [comment]
...or https://github.com/westnordost/StreetComplete/issues/1040, after all?

**Comment by westnordost** [comment]
Also so ganz verstehe ich es noch immer nicht. 

Du möchtest, dass die Karte nicht nach Norden ausgerichtet ist, sondern in die Richtung in die du gehst. Und zwar speziell nicht die Richtung in die du das Smartphone hälst (Karte ist nach Kompass ausgerichtet), sondern die Richtung in die du dich bewegst (Karte nach Bewegung ausgerichtet, wie ein Navigationsgerät).

Das wäre dann ein Duplikat von #1040.

Zurzeit ist nur implementiert, dass du die Karte neben manueller Rotation von deinem Kompass ausrichten lassen kannst. Wenn das mit dem Kompass nicht funktioniert, (_"dreht sich die Karte dauernd"_), dann hat dein Smartphone ein Problem mit dem Kompassensor. Dann solltest Du diese Funktion einfach ausschalten indem du einmal auf den Kompass rechts oben drückst und die Karte mit der Zwei-Finger-Geste manuell ausrichten.

Habe ich das richtig verstanden, dass dieser Feature Request schon in #1040 reportet wurde?

**Comment by Mannshoch** [comment]
Hi @westnordost  Yes it seems that this is a duplicate of #1040 for me the solution with manual turning the map with my finger is no useful workaround.

Thanks for your patience and your will to understand my thoughts.
