### ISSUE TITLE
Feedback after building levels quest

### ISSUE THREAD

**Issue by HaasJona** [westnordost/StreetComplete#1447]
**Use case**

After answering the building levels question, it would be great if you would get immediate feedback with an updated 3d building way. This currently doesn't seem to be happening and even after a few days I still see old data in the map. 

How often does it update? 

**Proposed Solution**

After answer the quest, update the local map cache if possible to show the new height. 

If that isn't possible, consider adding a message that the new building heights will show after a few days (or whatever the typical update time span is)

**Comment by matkoniecz** [comment]
> and even after a few days I still see old data in the map.

See #1011 for issue covering this

> it would be great if you would get immediate feedback with an updated 3d building way

Unfeasible due to technical reasons (data used to render map is coming from outside service, producing it locally on a phone is de facto impossible)

**Comment by westnordost** [comment]
> If that isn't possible, consider adding a message that the new building heights will show after a few days (or whatever the typical update time span is)

Actually, this can be quite a long time, depending on the region.
