### ISSUE TITLE
minor mistake in SVG for parking symbol

### ISSUE THREAD

**Issue by matkoniecz** [westnordost/StreetComplete#1449]
![Selection_011](https://user-images.githubusercontent.com/899988/60372651-9493ca80-99fd-11e9-8bb3-5dfef67ce26c.png)

![Selection_010](https://user-images.githubusercontent.com/899988/60372654-95c4f780-99fd-11e9-86ed-9f5b5b19d08b.png)

**Comment by westnordost** [comment]
Likely a problem with your smartphone. The SVG path is pretty clear and correct:

<svg xmlns="http://www.w3.org/2000/svg" width="500" viewBox="10 10 40 40">
  <path fill="transparent" stroke-width="2" stroke="black" stroke-linecap="square" d="m13.61,22.22v-10.58h3.18c0,0 3.17,0 3.17,3.17 0,3.17 -3.17,3.17 -3.17,3.17h-3.18"/>
</svg
