### ISSUE TITLE
On wifi scan for nearby quests in background, also if there are still many quests farther away

### ISSUE THREAD

**Issue by matkoniecz** [westnordost/StreetComplete#145]
I cleaned my area from quests. After I used "Scan for quests here" new types (building level count, opening hours) appeared.

But

> The scanning process should be "transparent" to the user in the sense that he should not even get the idea to worry about whether or not an area without quests has been scanned or not. If there are any quests, they should simply be there as if they are a fixed and integral part of the map

@westnordost  from #9 

So I assume that app should download new ones and failing to do that may be considered bug/important feature missing.

Obviously, it should not happen all the time, some cooldown should be provided to avoid overloading Overpass servers by hammering them with data requests just because somebody left app open in region where all quests are currently done.

**Comment by lightonflux** [comment]
The app already has an "auto-sync only on wifi". And also a cache lifetime. Should a shorter lifetime be added? (24h is the current minimum)

Or do you suggest to invalidate the cache immediately if the number of open quests goes from 3 → 2 or 1 → 0?

**Comment by westnordost** [comment]
The "quest cache" has nothing to do with that, see #141 (sorry, please use google translate). I am considering to remove the option because it only confuses users.

On the download logic:
- The auto downloader will only be triggered each time after moving at least 400m
- The rest of the logic is in this class https://github.com/westnordost/StreetComplete/blob/master/app/src/main/java/de/westnordost/streetcomplete/data/download/AActiveRadiusStrategy.java and child classes https://github.com/westnordost/StreetComplete/blob/master/app/src/main/java/de/westnordost/streetcomplete/data/download/MobileDataAutoDownloadStrategy.java and https://github.com/westnordost/StreetComplete/blob/master/app/src/main/java/de/westnordost/streetcomplete/data/download/WifiAutoDownloadStrategy.java respectively.

**Comment by matkoniecz** [comment]
From reading code it seems that following happened: 
- I completed nearby quests (within 300m), without internet connection.
- I returned home, SC detected wifi
- there were still quests within 1200 m (I completed nothing beyond 300m)
- I manually requested quests
- new low priority quests appeared within 300m
- I got confused

Possible solutions: ignore this case (if unlikely to be happening for many people) or iff wifiDownloadStrategy decides to refuse to download anything retry with mobileDataDownloadStrategy.

It will cover case like mine where there are still quests but nothing that is nearby.

**Comment by matkoniecz** [comment]
pseudocode:

```
downloadStrategy = mobileDataDownloadStrategy;
if(isWifi){
  downloadStrategy = wifiDownloadStrategy;
  if(!downloadStrategy.mayDownloadHere(pos)) {
    //to handle case of many quests available far away with nearby ones exhausted
    downloadStrategy = mobileDataDownloadStrategy;
  }
  if(!downloadStrategy.mayDownloadHere(pos)) return;
  questController.download(...);
}
```

**Comment by westnordost** [comment]
Or perhaps instead make a further distinction between "active radius" and "download radius". For Wifi, the download radius is bigger, but the active radius is always the same?

**Comment by matkoniecz** [comment]
> Or perhaps instead make a further distinction between "active radius" and "download radius". For Wifi, the download radius is bigger, but the active radius is always the same?

It may cause opposite problem - one has uninteresting quests nearby, wants to go for walk (and go further than 300 m from home) -  and app is not autoupdating quests because there are some very close to the current location.

**Comment by westnordost** [comment]
Two possible solutions come to my mind:
- the active radius is specified as an array of radii, i.e. [1200,300], so the Wifi strategy first looks if there is enough in the big radius and then also if there is enough in the small radius. (This goes into the same direction as your proposal, only that it takes advantage of being able to transmit more data in wifi)
- A new OnlyWifiStrategy, that is selected if the user selected "Sync only on wifi" in the option. While the WifiStrategy covers the use case of just taking advantage of potentially getting more data cheaper, the OnlyWifiStrategy specifically targets the use case of people who use the wifi as their (only) base. How the two strategies should actually differ in behavior is TBD, but at least it would be possible to
