### ISSUE TITLE
Sometimes all quest icons vanish

### ISSUE THREAD

**Issue by matkoniecz** [westnordost/StreetComplete#1456]
Sometimes all quest icons (or significant part of them) suddenly vanish from display. Map display otherwise works normally.

Minimalising app and going back to it almost always solves the issue, sometimes it is necessary to do it multiple times.

**How to Reproduce**
Unfortunately so far I failed to way any way to consistently reproduce it. What worse it never happened during debugging when I can see application logs, but always as I actually survey something.

**Versions affected**
Android 6.0.1 on Xiaomi Redmi 4, appears across multiple versions.

**Other affected people**

Friend with a Huawei Honor 7x phone.

report from Google Play review by Pedro Vaz Teixeira matches this symptoms.

> Great app, but the quest behavior is inconsistent - all quests will often vanish for no reason, and updating doesn't seem get them back. Sometimes restarting the app fixes it.

**Comment by westnordost** [comment]
Could this be the same as #1415 ?

**Comment by matkoniecz** [comment]
> If I turn off the soft and lunch it again with the icon, the points of request display again correctly (even off line).

Fits

> screen off + on, no more points

Is not really fitting.

There is a delay, but for me it scales with number of visible quests and quests always reappear. Disappearance of all markers was something that happened with very low quest count (around 20), without disabling screen - with just scrolling.

**Comment by matkoniecz** [comment]
> Could this be the same as #1415 ?

I am starting to suspect that it may be. For me it was happening mostly on opening app, but sometimes it happened on unlocking screen.

I added log messages and I tracked down one of situations where it happens - listener in VisibleQuestRelay is null, so trigger to display quest markers is not passed down.

Normally:

https://github.com/westnordost/StreetComplete/blob/0457f7f4d4e795ade3f302684ea2216c661a940e/app/src/main/java/de/westnordost/streetcomplete/data/VisibleQuestRelay.java#L23 is called

https://github.com/westnordost/StreetComplete/blob/0457f7f4d4e795ade3f302684ea2216c661a940e/app/src/main/java/de/westnordost/streetcomplete/data/VisibleQuestRelay.java#L25 listener is set and call is relayed to 

https://github.com/westnordost/StreetComplete/blob/8f0a448473ccff747dd241df3ceb5687b308dbc5/app/src/main/java/de/westnordost/streetcomplete/MainActivity.java#L928 that in turn calls

https://github.com/westnordost/StreetComplete/blob/f103eca604e1f22994b5ed5070c3cb324757300d/app/src/main/java/de/westnordost/streetcomplete/tangram/QuestsMapFragment.java#L409

**Comment by matkoniecz** [comment]
I found way to consistently reproduce it on my phone: 

- enable requiring password on unlocking phone
- run SC
- lock phone
- short press power button and wake phone (getting password screen) - according to logcat relay will fail at this time
- type password/give fingerprint

Unlocking phone directly with fingerprint is not causing this bug to manifest.

----

```
07-22 10:38:50.466 26048-26082/de.westnordost.streetcomplete.debug E/OsmOAuthDialogFragment: Threadsafe relay for VisibleQuestListener - onQuestsCreated called, will relay if listener is not null
07-22 10:38:50.471 26048-26082/de.westnordost.streetcomplete.debug E/OsmOAuthDialogFragment: listener was null, not relayed
07-22 10:38:50.474 26048-26082/de.westnordost.streetcomplete.debug E/QuestController: relay failed
```

is a typical situation

Log made using https://github.com/matkoniecz/Zazolc/commits/log_marker_appearance (branching from max weight quest branch)

**Comment by matkoniecz** [comment]
Closing as duplicate of #1415
