### ISSUE TITLE
Settings indented

### ISSUE THREAD

**Issue by goldfndr** [westnordost/StreetComplete#1458]
The Settings list is horizontally indented. It looks like there's space for icons on the left but they aren't visible. I took a look at other apps (by Google: Photos, Rewards, Gmail, YouTube, Drive, Play Store, Chrome) and I'm not seeing this alignment elsewhere. They do have a left arrow in the action bar to go back from Settings. Google's apps don't tend to have icons in Settings, but some third party apps (e.g. SD Maid, Sleep as Android, Netflix, Podcast Addict, Relay for Reddit — which similarly indents settings submenus) do.

**How to Reproduce**
Launch StreetComplete, tap overflow menu icon, tap Settings.

**Versions affected**
Android 6.0.1 on a Galaxy Note 4 and a Galaxy S5, StreetComplete Version 12.2

**Comment by matkoniecz** [comment]
Is it something new in a recent version?

**Comment by matkoniecz** [comment]
From what I remember - it seems the same as in previous versions. And yes, StreetComplete has left margin in settings menu larger than 10+ apps that I checked.

**Comment by westnordost** [comment]
It's kind of a bug. I didn't find out why this indent is shown and figured that it is also not that important that there is no indent.

**Comment by westnordost** [comment]
Found it. https://stackoverflow.com/a/53212022

**Comment by rugk** [comment]
or, alternatively, you could add icons? 🤔

**Comment by westnordost** [comment]
No 

Am 6. September 2019 08:58:09 MESZ schrieb rugk <notifications@github.com>:
