### ISSUE TITLE
Show street names

### ISSUE THREAD

**Issue by Phyks** [westnordost/StreetComplete#146]
Hi,

Where I live, in Paris, there are no street names on the displayed map, and a lot of streets crossing each other.

At some point, I was not sure my GPS was taking the correct location, and without street names, it was really difficult to check.

Would it be possible to display street names on the map, or at least putting the name of the matching element when confirming a quest (typically, the name of the street when asking what is the type of ground in the street)?

Thanks!

**Comment by westnordost** [comment]
This will be fixed in the upcoming version.

**Comment by Phyks** [comment]
OK, thanks!
