### ISSUE TITLE
Require minimum variety of quest types 

### ISSUE THREAD

**Issue by matkoniecz** [westnordost/StreetComplete#1463]
In some places after initial download user see quests of only one type.

It would be useful to ensure at least some variety. It is not obvious for people how many different quests are available and this protests from displaying just single type of quests.

Also, often there is a big cluster of some quests blocking further downloads due to high quest count but user is uninterested on solving them (at least at this specific moment).

I am opening an issue as it looks like more than finding relevant part of code and tweaking line or two, so I prefer to check is it going to be accepted.

So I proposed to add also min quest type count in a download strategy

To modify /app/src/main/java/de/westnordost/streetcomplete/data/download/QuestDownload.java (downloadQuestTypes)

Code doing now related thing: /app/src/main/java/de/westnordost/streetcomplete/data/osm/download/OsmQuestDownload.java

Place to write an SQL query: /app/src/main/java/de/westnordost/streetcomplete/data/osm/persist/OsmQuestDao.java

**Comment by westnordost** [comment]
Sounds reasonable.

**Comment by matkoniecz** [comment]
Closing per https://github.com/westnordost/StreetComplete/pull/1486#issuecomment-680006560
