### ISSUE TITLE
Impossible to validate text in "Do not apply"

### ISSUE THREAD

**Issue by Bensansjerrys** [westnordost/StreetComplete#147]
Hello,
Once I click "Do not apply", the numeric keypad opens and it is no longer possible to confirm or press the OK button.
This is the first problem I just post on Github, I do not know if it really comes from the application or rather my smartphone or my version of android.

**Comment by westnordost** [comment]
Please specify: Where are you pressing "do not apply"? For which quest? Also, which version of the app are you using?
