### ISSUE TITLE
There is new syntax for missing keys in the Overpass API

### ISSUE THREAD

**Issue by matkoniecz** [westnordost/StreetComplete#1479]
See https://wiki.openstreetmap.org/wiki/Overpass_API/Overpass_QL#Not_exists - available since v0.7.53 (deployed on public instances, see https://wiki.openstreetmap.org/wiki/Overpass_API#Public_Overpass_API_instances )

It is `node[!"name"];` (new) vs `node["name"!~".*"];` (old)

https://github.com/westnordost/StreetComplete/blob/master/app/src/main/java/de/westnordost/streetcomplete/data/osm/tql/FiltersParser.java#L185-L192

**Comment by mmd-osm** [comment]
Release note for 14.0 mention this issue as part of „quest download now more than 4 times as fast as before“. That’s not quite correct: both versions are treated exactly the same internally, there’s no performance difference in any way.

**Comment by westnordost** [comment]
Correct, this ticket was simply part of a large refactor of the Overpass Query generation that in total resulted in a boost of 50% or so.
The new syntax did not contribute to the performance improvement, only to readability.
