### ISSUE TITLE
A question about osm map quantity

### ISSUE THREAD

**Issue by wangzi6578** [westnordost/StreetComplete#1483]
Hi，there，
Today,I found a question about OSM map, i get road data from any  one city  in osm map, it about 100M, but i get total country's road data, it only about 1G,however, it contains hundreds cities,that's incredible，is there any expert could solve my doubt

**Comment by claudiush** [comment]
This StreetComplete project here on Github is an app to improve OSM data quality.
Your question is probably better asked (and answered) on the OpenStreetMap Forum: https://forum.openstreetmap.org
