### ISSUE TITLE
Ask about cycleway/footway surface

### ISSUE THREAD

**Issue by matkoniecz** [westnordost/StreetComplete#1489]
### General
Affected tag(s) to be modified/added: [cycleway:surface](https://wiki.openstreetmap.org/wiki/Key%3Acycleway%3Asurface), [footway:surface](https://wiki.openstreetmap.org/wiki/Key%3Afootway%3Asurface)

Question asked: **What is the surface of bicycle part of this way?** + **What is the surface of pedestrian part of this way?**

### Checklist
Checklist for quest suggestions (see guidelines):
- [x] 🚧 To be added tag is established and has a useful purpose
- [x] 🤔 Any answer the user can give must have an equivalent tagging (Quest should not reappear to other users when solved by one)
- [x] 🐿️ Easily answerable by everyone from the outside but a survey is necessary 
- [x] 💤 Not an overwhelming percentage of elements have the same answer (No spam) (though is some regions it may be asphalt over and over again for cycleway part, but it should not be worse that standard `surface` quest)
- [x] 🕓 Applies to a reasonable number of elements (Worth the effort) - is 8000 elements worldwide enough? http://overpass-turbo.eu/s/KYI

### Ideas for implementation

**Element selection:** http://overpass-turbo.eu/s/KYK

**Metadata needed:** no

**Proposed GUI:** reuse existing surface GUI

I consider it as one of steps toward #279 ("add quest to make surface=paved/unpaved more detailed")

**Comment by westnordost** [comment]
Yes, makes sense, but the element selection is odd. Why `segregated=yes` instead of `cycleway=track` (+opposite_track etc)

**Comment by westnordost** [comment]
Oh, I get it, you proposed this to be about `highway=path|footway|cycleway`, not about `highway=residential|... + cycleway=track|...`.

Then, this is kind of a special case of `AddPathSurface`

**Comment by matkoniecz** [comment]
> Oh, I get it, you proposed this to be about highway=path|footway|cycleway

yes, though

> highway=residential|... + cycleway=track|...?

also may make sense - but should the question be asked also only for `surface=paved`? Or is it useful to ask for all elements where cycleway surface was not set explicitly?

**Comment by westnordost** [comment]
I think it makes sense to ask for any. If there is already an explicitly tagged cycleway, it will have some surface

**Comment by matkoniecz** [comment]
`cycleway=track` was implemented in https://github.com/westnordost/StreetComplete/pull/1493/commits/bfc5e9ab7f7d6a76d90cf8a9cdf6777b5218bf18 but after https://github.com/westnordost/StreetComplete/pull/1493#discussion_r307422098 discussion it turned out to require a special interface and will be implemented as a separate quest

**Comment by matkoniecz** [comment]
And it makes sense to include also `cycleway:left`/`cycleway:right`/`cycleway:both` With #1504 it would be even possible to exclude `cycleway=track`
