### ISSUE TITLE
Don't ask for name=value for a segment if ref=value is missing

### ISSUE THREAD

**Issue by dsp77** [westnordost/StreetComplete#1490]
I am referring to this changeset create by StreetComplete 12.2 on Android

https://www.openstreetmap.org/changeset/72474098

**How to Reproduce**

- A highway=secondary is only specified by a ref=value, no name=value.
- One segment of that way has the ref=value missing
- StreetComplete will suggest for this segment to enter name=value from a user

Missing information/problems that arise:

- From the details provided a user of the app cannot see why this part of the way needs a name to be entered, while the rest of the way does not.
- A user cannot see, that the rest of the way has ref=value attributes while this segment does not.
- For the specified segment a name=value attribute is added, while the rest of the way has a ref=value attribute.

**Versions affected**
Android 12.2

**Comment by westnordost** [comment]
I understand the problem, however, there is no easy way to solve this.

In OpenStreetMap, there is no notion of ways "that belong together". While for a human observer of the map, it seems like a matter of course that certain ways belong to the same road, it is not trivial to find this out for StreetComplete, or for that matter, any consumer of OpenStreetMap data, and that detection is always fuzzy.

The app already does not ask for a name, if a `ref` is tagged. But if nothing is tagged, then it asks for a name. 

The app could detect if the input "looks like" a ref (short, only capital letters and numbers) and either tag the input automatically as `ref` or ask the user if the name input is actually a ref. Though, at least in German, it would be difficult to explain the difference between `name` and `ref` because in common language, the L3121 would simply be referred to as the "name" of that road.

Do you have a suggestion how to handle this?

**Comment by dsp77** [comment]
One idea would be to ask only for a segment, that has at least one connected segment that is either `name` or `ref` tagged. With the request show the information of the connected segment and stay in the tagging `name` or `ref`.

If both neighbour segments are are tagged with the same `name` or `ref` tag and value. Suggest it also for this segment.

Allow an advanced mode, where a user can set the tag `ref` or `name` herself.

**Comment by matkoniecz** [comment]
> One idea would be to ask only for a segment, that has at least one connected segment

It would exclude also many valid uses.

> Though, at least in German, it would be difficult to explain the difference between name and ref because in common language, the L3121 would simply be referred to as the "name" of that road.

Is it still very hard to formulate a question asked after user set ref-like code?

Something like "Is it name like 'Hauptstraße' or is it a reference code like 'L3121'?"

Collecting missing ref is also useful anyway.

**Comment by westnordost** [comment]
> Is it still very hard to formulate a question asked after user set ref-like name?
> Something like "Is it name like 'Hauptstraße' or is it a reference code like 'L3121'?"

What do you mean with "still"? I am not sure I understand your suggestion.

**Comment by dsp77** [comment]
> > One idea would be to ask only for a segment, that has at least one connected segment
> 
> It would exclude also many valid uses.

I was thinking in terms of streets with the `highway` tag. I assume, that most (all?) ways are connected somewhere. Instead of asking for all segments that have neither `name` nor `ref` tag,  just ask for the segment that is already connected to a specified segment. After that got named, ask for the next segment.

**Comment by matkoniecz** [comment]
> What do you mean with "still"? I am not sure I understand your suggestion.

It would be hard to make clear in question "What is the name of this road?" that it is about `name` not `ref`.

But is this still hard to make the distinction clear in additional question, asked only for cases adding ref-like values?

So initial view would be exactly like it is now, in case of adding normal name nothing would change. And after adding reflike name StreetComplete would additionally ask "Is it name like 'Hauptstraße' or is it a reference code like 'L3121'?".

> Instead of asking for all segments that have neither name nor ref tag, just ask for the segment that is already connected to a specified segment. After that got named, ask for the next segment.

It will have problems for places with many missing names, not just small forgotten segments. Solving quests for ways attached to the main road with `ref` will not make next segment available (or to be more specific, will require expiration of quests and redownloading them).

**Comment by westnordost** [comment]
Ok I understand.

Or maybe, there is a proper word for `ref` in common language only that it does not occur to me. Using examples like "Hauptstraße" etc. has the problem that it has to be localized and it is not clear whether the example name in the own language should be used in that sentence or the language of the country where one is currently in.

**Comment by matkoniecz** [comment]
For translators - maybe introduce separate string with `popular_road_name_in_your_country` code and have main string with `%s` placeholder?

iD localizes its tutorial with names typical for various countries - https://github.com/openstreetmap/iD/issues/2881 https://github.com/openstreetmap/iD/issues/3976

**Comment by matkoniecz** [comment]
"proper word for ref in common language only that it does not occur to me"

`ref` - alphanumeric code / reference number vs `name` - name?

**Comment by matkoniecz** [comment]
> Hauptstraße

Or maybe example street name for each country may be added to metadata? (I can generate it)

**Comment by westnordost** [comment]
I tend towards automatically adding `ref` instead if the input looks like a `ref`, without user confirmation. The two should actually be pretty easy to tell apart.
