### ISSUE TITLE
Outdated or forgotten comment (needs to be extended when I re-enable tilt and rotation)

### ISSUE THREAD

**Issue by matkoniecz** [westnordost/StreetComplete#1496]
> needs to be extended when I re-enable tilt and rotation

in https://github.com/westnordost/StreetComplete/blob/f103eca604e1f22994b5ed5070c3cb324757300d/app/src/main/java/de/westnordost/streetcomplete/tangram/QuestsMapFragment.java#L282

tilt and rotation is now enabled

**Comment by westnordost** [comment]
Right, thanks. I added it.
