### ISSUE TITLE
Consider defining StreetComplete as an editor in the GitHub tagline

### ISSUE THREAD

**Issue by matkoniecz** [westnordost/StreetComplete#1499]
Current github tagline is

> OSM Surveyor app for Android

I propose to change it to

> Easy to use OpenStreetMap editor for Android

My motivations (listed as likely big part of them is a good idea, but text that I proposed may have other problems)

1. OSM may be not clear for people who need to read description - replaced by OpenStreetMap
1. "easy to use" is a major selling point and differentiation from for example Vespucci
1. "Surveyor app" may be something used to collect notes, not necessarily an editor
1. "app" and "for Android" is redundant

I know that short description on Google Play is the same (or very similar), but as this ones are translated I want to propose changes there in one step rather than in iteration like with README or here.

No PR, as it is impossible to edit this part of Github metadata with PR.

In addition I would consider adding `mapping` and `editor` tags (idea copied from iD repo - https://github.com/openstreetmap/iD)

**Comment by westnordost** [comment]
Ok! Thanks!
