### ISSUE TITLE
new quests are not shown until the map moves

### ISSUE THREAD

**Issue by gdt** [westnordost/StreetComplete#15]
I panned/zoomed to someplace of interest for offline use, and did a manual download.    The progress bar finished, but no quests appeared.  Panning just the slightest bit made them show up.  So there is perhaps a missing call to redraw them after download is complete.

**Comment by westnordost** [comment]
(I do not fix this yet because the map library I am using are introducing a feature which will properly support map markers, not like the workaround I am using for it currently. So, this bug is not forgotten, I will come back to it soon.)

**Comment by westnordost** [comment]
I cannot reproduce this any more with 0.4

**Comment by gdt** [comment]
I agree this is fixed.  Thanks!
