### ISSUE TITLE
Add type of objects that can be found in every cities : for gamification

### ISSUE THREAD

**Issue by JLZIMMERMANN** [westnordost/StreetComplete#150]
Some type of objects would create a really fun way to contribute : using pictures
- hydrants
- bench
- bus_stop
- advertising
- vending machine
- crossing

**Comment by matkoniecz** [comment]
It does not sound like something doable using simple questions. "Is there hydrant at this point?" would not work for obvious reasons.

It would require full-scale editor and AFAIK this is not goal of this program.

See

> An Android app which finds wrong, incomplete or extendable data in the user's vicinity and provides the tools to complete these easily and directly on site without having to use another editor.

in the readme. Note that while it is not explicitly rejected it does not include adding new objects.

**Comment by westnordost** [comment]
Basically, see @matkoniecz 

I agree this could be a reasonable extension for (much) later. But it is a whole new feature and has nothing to do with this "quest" system in place now (enhancing already existing data), so it is out of scope of this project for the time being.

What you probably want to use at this point in time is [OsmTracker](https://wiki.openstreetmap.org/wiki/OSMTracker_(Android)).

**Comment by JLZIMMERMANN** [comment]
Thanks for your answer : in my idea, there are already POI but without any other tags. I really wish to enhance already existing data for these objects.

**Comment by matkoniecz** [comment]
In case of possibility of adding new data to existing objects it is probably better to open issue for every object and carefully explain what kind of tags may be added (for example I have quite significant experience with OSM and I have no idea how one may improve tagging of already mapped hydrant).

**Comment by JLZIMMERMANN** [comment]
OK I'll do like you ask
