### ISSUE TITLE
Ask about cycleway position and replace cycleway=track by more detailed cycleway:left/cycleway:right/cycleway:both

### ISSUE THREAD

**Issue by matkoniecz** [westnordost/StreetComplete#1504]
### General
Affected tag(s) to be modified/added: [cycleway:left](https://wiki.openstreetmap.org/wiki/Key:cycleway:left), [cycleway:both](https://wiki.openstreetmap.org/wiki/Key:cycleway:both), [cycleway:right](https://wiki.openstreetmap.org/wiki/Key:cycleway:right)
Question asked: **Is there an example tag on item XY?**

### Checklist
Checklist for quest suggestions (see guidelines):
- [x] 🚧 To be added tag is established and has a useful purpose
- [x] 🤔 Any answer the user can give must have an equivalent tagging (Quest should not reappear to other users when solved by one)
- [x] 🐿️ Easily answerable by everyone from the outside but a survey is necessary 
- [x] 💤 Not an overwhelming percentage of elements have the same answer (No spam)
- [x] 🕓 Applies to a reasonable number of elements (Worth the effort)

### Ideas for implementation

**Element selection:** `cycleway=track and !'cycleway:left' and !'cycleway:right' and !'cycleway:both'`

**Metadata needed:** no

**Proposed GUI:** side selection, similar to sidewalk quest

Triggered by #1493, I thought about doing it in #1489 but it would be obnoxiously complex to tag both surface and presence of cycleway on sides of a road.

**Comment by westnordost** [comment]
While personally, I think this is a slight improvement to the data, I believe this would be quite controversial:
1. In many cases, where left and right do actually not differ, there is virtually no information gain, only the key is changed (`cycleway` -> `cycleway:both`). This comes across as a (mechanical) retagging effort. The `cycleway` tag is accepted and used more than `cycleway:both` etc., some community members even doubt the usefulness of the latter. 
2. In many cases where the above is not true and the sides do actually differ, they will differ only on certain sections, requiring the way to be split up first. So, an error or at least an imprecision in the data is found, great, but the app is unable to fix it itself but instead creates a note.

**Comment by matkoniecz** [comment]
So in cases where cycleway is just on one side user would be expected to leave a note?

**Comment by westnordost** [comment]
As in any case where the underlying data is wrong
