### ISSUE TITLE
Map tiles not loading in NSW, Australia

### ISSUE THREAD

**Issue by dbdean** [westnordost/StreetComplete#1508]
At present, map tiles are not loading or updating around [Armidale, NSW](https://www.openstreetmap.org/#map=15/-30.5162/151.6643).

![Screenshot_20190730-093229](https://user-images.githubusercontent.com/12725310/62089659-29b00a80-b2ad-11e9-96f6-e6083bcdb324.jpg)

**Versions affected**
StreetComplete 13.0-beta1 on Android 9

**Comment by matkoniecz** [comment]
Pinging @Akasch

**Comment by Akasch** [comment]
Solved by using nexzen tiles for the moment, the upstream server is offline at the moment

**Comment by westnordost** [comment]
Any news, @Akasch? Is the server for Australia hosted by someone else?

**Comment by misibacsi** [comment]
I experience the same "missing map" problem very frequently in Hungary, Europe.
I used to zoom out 2x-3x, and when the map appears, I zoom-in again 2x-3x.

Why is the map not stored locally in the app?

**Comment by 42prefect** [comment]
Same issue here (48.2073, 16.3713). Had to zoom out and in a few times to get tiles loaded. I also had to move the map to the west [(48.4101, 15.604)](https://www.openstreetmap.org/#map=12/48.4101/15.604) and wait for the map to be loaded. After app restart (also when going to background) I had to repeat this procedure.
SC: v16.0 (from F-Droid)
MapCache: 250MB
Android Version: Pie
Device: Xiaomi Mi A2lite

**Comment by matkoniecz** [comment]
> Why is the map not stored locally in the app?

Once downloaded map data is cached. It is downloaded rather than provided with app because full worldwide data requires gigabytes of storage.

**Comment by prefectAtEarth** [comment]
> > Why is the map not stored locally in the app?
> 
> Once downloaded map data is cached. It is downloaded rather than provided with app because full worldwide data requires gigabytes of storage.

Can confirm that after third (or fourth) retry it's working now as expected. Just had to more patient.
In new areas it's still taking really long to get map data,sometimes I have to do the "swipe west and zoom in and out" thing, but it's working.

**Comment by shikaruko** [comment]
Any fix for this issue ? I've the same for center town that i often contribute to the quest :
StreetComplete v16.1 on a CatS41 with 250mo Mapcache 

No issue for the same localtion with Osmand that use Openstreetmap tiles too.

**Comment by matkoniecz** [comment]
> No issue for the same localtion with Osmand that use Openstreetmap tiles too.

Osmand has completely different way of handling OSM data.

**Comment by shikaruko** [comment]
Because of the data were the same, i thought that storage infrastructure was shared across the two project. What is the best option to solve this kind of issue ?

**Comment by HolgerJeromin** [comment]
> Because of the data were the same, i thought that storage infrastructure was shared across the two project. What is the best option to solve this kind of issue ?

Please discuss this here:
#122 and #243

**Comment by peternewman** [comment]
I think this should be able to be closed based on https://github.com/westnordost/StreetComplete/issues/1700#issuecomment-645466148 given SC has switched tile provider.
