### ISSUE TITLE
Distribution through Galaxy Store

### ISSUE THREAD

**Issue by Etua** [westnordost/StreetComplete#1509]
@westnordost Did you consider distributing the app using Galaxy Store? It has smaller userbase than Play Store but it is preinstalled on Galaxy devices and some of the well known products are distributed there so I guess that the number of it's users isn't negligible and I suppose that SC should be as easily approachable as possible.

**Comment by westnordost** [comment]
Is the Play Store not preinstalled on Galaxy devices?

**Comment by Etua** [comment]
It is but as I said earlier if some of the big players decide to publish there anyway then it may be worth the effort. I don't know whether Samsung does sell phones without Google framework on some markets or is it just for those that for some reason prefer to use the other solution.

**Comment by westnordost** [comment]
Hm, then I do not see an advantage of also be present on the Galaxy store. To be present there would mean another overhead on release. People who do not want google on their smartphone will and should get F-Droid. To download apps on the Samsung Appstore requires a Samsung account.

Also, I read a bit about this store. 10k+ apps are available there. That is impressive, compared to 2.6k+ on F-Droid, but a dwarf compared to Google Play with 2700k+ and Amazon Appstore with 475k+.

**Comment by rugk** [comment]
> That is impressive, compared to 2.6k+ on F-Droid

Though that comparison is a little unfair, as only FLOSS apps (and additionally vetted/marked with antifeatures etc.) can get into F-Droid.
