### ISSUE TITLE
add build instructions

### ISSUE THREAD

**Issue by matkoniecz** [westnordost/StreetComplete#151]
Maybe it is obvious what is preferable and tested method to build this program (AKA "what was used by the author"). For example, for me it would be beginning of developing for Android, so I prefer to not combine it with adapting code to work properly in additional environments.

**Comment by westnordost** [comment]
Hmm, it should work out of the box in Android Studio. Naturally, I will not add instructions how to install the Android SDK :-P
Here is the download: https://developer.android.com/studio/index.html

I will close this issue, but if you run into any problems during setup, write here and I will notice it and answer you.

**Comment by matkoniecz** [comment]
What is the currently used method to install on phone both dev and release version? 

- https://stackoverflow.com/questions/8791829/install-dev-build-of-android-app-along-side-market-version/40360624#40360624 and https://stackoverflow.com/questions/4960235/how-to-manage-debug-and-release-version-on-android-device mention using buildTypes in Gradle as solution but https://github.com/westnordost/StreetComplete/blob/af448b3d14872050cf6ffa76e7b7f36267d37310/app/build.gradle#L27 has only release build.

- https://stackoverflow.com/questions/39169232/cannot-install-debug-and-release-version-on-same-device/39196206#39196206 mentions flavors but it also seems to be unused

Simply installing dev version on phone would uninstall release version (making harder to check whatever bug reproduces in upstream, uninstallig app is a also removing all data with it). 

Emulation is not a good solution - my CPU is not supporting VT-x so it would be hilariously slow even after solving https://stackoverflow.com/questions/44482279/add-arm-system-image-to-android-studio-avd-manager.

Alternative solution is to modify program so it will be say de.matkoniecz.streetcomplete rather than de.westnordost.streetcomplete but that would make preparing PRs awful (on top of that version at https://github.com/matkoniecz/StreetComplete/commit/75cfee1039917d836624771efcb4390e048e2697 is not even compiling for some reason - if that is the only way to do that I will hunt down what went wrong, but I hope that this is not a proper way to do that).

@westnordost If you are currently using solely emulation for dev version and on phone have only released version - would you accept PR using buildTypes in Gradle, or it something that should remain in my repo?

**Comment by westnordost** [comment]
If you are not me, you cannot create a release version because you need the private keys to sign the app. You can only build a debug version.

I basically only have the debug version installed I think, and I always use my phone to test. (My PC is also not the fastest,... i3-3227U...

So, you got a x64 PC now? :-)

**Comment by matkoniecz** [comment]
> So, you got a x64 PC now? :-)

I had x64 laptop, but with 32 bit OSes. Now I have the same laptop, with the same OSes and 64 bit OS on USB disk :)

> I basically only have the debug version installed I think

OK, so I will try to figure out Gradle (I want to keep released version to test easily whatever crashes in my version are happening also in released version).

**Comment by matkoniecz** [comment]
> You can only build a debug version.

Is there a separate build/release mode - or by "debug version" you mean "one obtained by cloning repo and using default build in Android Studio"?

**Comment by westnordost** [comment]
yes. You only need debug for developing, don't even bother about app signing.
