### ISSUE TITLE
404 link to POEditor in AUTHORS.md

### ISSUE THREAD

**Issue by matkoniecz** [westnordost/StreetComplete#1512]
https://github.com/westnordost/StreetComplete/blob/master/AUTHORS.md has 

> Translations: Check the project on POEditor to see language contributors

linking to https://poeditor.com/projects/view?id=97843 what is 404 page

https://poeditor.com/join/project/IE4GC127Ki link in https://github.com/westnordost/StreetComplete/blob/master/CONTRIBUTING.md works but I see no way to see contributor info.

There is https://poeditor.com/contributors/ link but it shows stats only about owned/administered projects.

**Comment by matkoniecz** [comment]
I think that the only way to fix this and #629 is to remove this links to POEditor.

Maybe also add direct link to https://poeditor.uservoice.com/forums/171919-general/suggestions/31242085-public-url-to-view-project-contributors in AUTHORS.md.

**Comment by matkoniecz** [comment]
@westnordost Is it maybe valid link for you as owner as POEditor project? If yes - is there maybe option to make it available to a general public?

**Comment by westnordost** [comment]
It is not 404 for me even if I am not logged in. It shows the "join the project" page

**Comment by matkoniecz** [comment]
I tried again. For unlogged user it shows me log in screen. For logged in user it shows me 404.

**Comment by westnordost** [comment]
Oh, ok. So I guess they changed the paths. It should point to the contributors tab of the project. Do you see it, or only I?

**Comment by matkoniecz** [comment]
I found only https://poeditor.com/contributors/

> There are no contributors assigned to the project(s) you own or administrate. Contributors can be added in any Project Page or Language Page and administrators in Project Settings.

**Comment by westnordost** [comment]
Yeah that'd be it. Too bad.

**Comment by westnordost** [comment]
So this is blocked, same as #629

**Comment by matkoniecz** [comment]
It is now general problem of missing link but I think that it should be removed as going to 404 (I can make a PR that will do this)

**Comment by westnordost** [comment]
Ok
