### ISSUE TITLE
Add photo to information board, map or guidepost

### ISSUE THREAD

**Issue by chstdu** [westnordost/StreetComplete#1515]
### General
Affected tag to be modified/added: [mapillary](https://wiki.openstreetmap.org/wiki/Key:mapillary) or other [photo tag](https://wiki.openstreetmap.org/wiki/Photo_linking)
Quests asked:
- **Please add a photo of this information board.**
- **Please add a photo of this information guidepost.**
- **Please add a photo of this information map.**

[`tourism=information`](https://wiki.openstreetmap.org/wiki/Tag:tourism=information) is used for tourist information boards, guideposts and maps etc. For these three sub-categories, the quest would ask the user to take a photo of the board, guidepost or map. StreetComplete would then upload the photo to a (free, open, long-term accessible) photo hosting site under a free copyright license (Creative Commons or Public Domain) and link it via [Photo linking](https://wiki.openstreetmap.org/wiki/Photo_linking) to the OSM object.

Information boards or maps are very useful also for planning a trip to some area. Accessing them online before visiting them on-site will be a huge advantage and might prevent large detours.

### Checklist
Checklist for quest suggestions (see guidelines):
- [x] 🚧 To be added tag is established and has a useful purpose - There are over 200k photo links (mapillary, Wikimedia Commons, others) in OSM already.
- [x] 🤔 Any answer the user can give must have an equivalent tagging (Quest should not reappear to other users when solved by one) - If there is a photo linked to an information source already, the quest does not (re)appear.
- [x] 🐿️ Easily answerable by everyone from the outside but a survey is necessary. - You cannot take a photo remotely but if you are on site, it is easy because (almost) all smartphones include cameras.
- [x] 💤 Not an overwhelming percentage of elements have the same answer (No spam) - No two answers will be the same ;-)
- [x] 🕓 Applies to a reasonable number of elements (Worth the effort) - There are 290k guideposts and 148k information boards and 60k information maps in OSM already.

- [x] 🏷️ So, basically: Only tags can be edited - In OSM the quest only adds some photo link as tag.
- [x] 👨‍💻 Users are no experts - No knowledge about OpenStreetMap or any other background knowledge is necessary because the upload and the login at mapillary could work automagically.
- [x] 🕵️ Publicly accessible - Usually all of the affected information elements are by definition public because they inform the public about the way or the area.
- [x] 💵 Valuable Surveyors - Taking photos cannot be done remotely.

### Ideas for implementation
**Element selection:** 
Filter to show only tourism information elements (e.g. information boards) which do not have any photo link yet: [Overpass Turbo example](https://overpass-turbo.eu/s/Li7)

Only elements in countries with [Freedom of Panorama](https://en.wikipedia.org/wiki/Freedom_of_panorama) should be selected. Otherwise, the user would have to check the copyright law of their country first.

**Proposed GUI:**
There should be an automatic upload to mapillary or another photo hosting service which allows login with OSM account. There is already existing work for StreetComplete to add photos as answers of quests here:

- [Issue 90: Solve quest with photo](https://github.com/westnordost/StreetComplete/issues/90)
- [Pull #655 Solve or create note with photo](https://github.com/westnordost/StreetComplete/pull/655)

**Comment by rugk** [comment]
Related quest proposals (about tourism information): https://github.com/westnordost/StreetComplete/issues/1226, https://github.com/westnordost/StreetComplete/issues/1115

The very similar quest proposal https://github.com/westnordost/StreetComplete/issues/952 for asking for photos has been rejected before.

**Comment by chstdu** [comment]
Thank you @rugk for the cross references and hinting at previous problems with photo quests.

#952 was closed mainly because it is ["too problematic [...] to find a heuristic first what a "photo worthy" object on the map would be."](https://github.com/westnordost/StreetComplete/issues/952#issuecomment-371606551) Information boards or maps should always be worthy enough to have a photo. At least some local authority decided that there is something worthy enough to explain to set up the board or map.

However, there might be guideposts, e.g., consisting only of arrows without any text. Thus, there should be the option to flag these _guideposts without text_ with the tag [`inscription=no`](https://wiki.openstreetmap.org/wiki/Key:inscription) instead of uploading a photo. No quest should be shown if there is any `inscription` tag already, just to be on the safe side. In the GUI, there should also be an option to upload several photos, e.g., if there is a back side of the guidepost or board which also contains information.

The other issue discussed in #952 was that it would be better/easier to photo link existing entries in Wikimedia Commons first. I totally agree with this because Wikimedia Commons photos tend to be of high quality and usually depict interesting objects. Thus, I would really like to have this done semi-automatically, e.g., via [Pic4Review](https://pic4review.pavie.info/#/). However, for most information boards, maps and (especially) guideposts, the probability that there is already a photo in Wikimedia Commons is quite low because the majority of photos there tends to be of important or at least named objects.

Although I would (even very much) prefer Wikimedia Commons over mapillary for storing single photos like the requested ones, I hope mapillary will be easier to use/implement because it offers login/sign up via OSM.

Mapillary automatically blurs faces and license plates. If mapillary blurs a board or guidepost by mistake, we can request to unblur it via their [admin review](https://help.mapillary.com/hc/en-us/articles/115001663705-Blurring-images).

**Comment by rugk** [comment]
> At least some local authority decided that there is something worthy enough to explain to set up the board or map.

…which yields the question whether the object should be photographed or the information board. (or both, in one photo – which could be possible)

**Comment by chstdu** [comment]
Thank you for your idea, @rugk. However, there are many information boards which do not describe a specific object but rather abstract concepts like the nature or history of a region. There is no easy way for us to decide whether there is a specific photo-worthy object just from the OSM data. Thus, the problem from #952 how to decide this question would show up again if we allow taking photos of the objects too.

Hence, for taking photos of specific objects like monuments, I would suggest to create new quests here. There we could discuss about the filters to come up with a good set of photo-worthy objects. I would suggest, e.g., [`historic=monument`](https://wiki.openstreetmap.org/wiki/Tag:historic%3Dmonument), [`historic=memorial`](https://wiki.openstreetmap.org/wiki/Tag:historic%3Dmemorial) and [`denotation=natural_monument`](https://wiki.openstreetmap.org/wiki/Key:denotation) as a beginning. However, we have to bear in mind that for these different forms of "monuments" there are usually already photos in Wikimedia Commons. Therefore, I would strongly suggest to first create a method to photo link these existing resources somehow semi-automagically, which is not within the scope of StreetComplete, but rather concerns projects like [Pic4Review](https://pic4review.pavie.info/#/). (Any experts here who could set up such tasks?)

Just another thought on the actual topic of this thread: The app should [tag](https://help.mapillary.com/hc/en-us/articles/115001963751-Tagging) the automatically uploaded photos on mapillary in a unique category, e.g., `Information-Board-via-StreetComplete`. Thereby, the photos can be easily reused later on, e.g., when we come up (maybe even somewhere else) with a follow-up task, e.g., determining the language of the text on the board or even making it machine-readable via OCR.

**Comment by rugk** [comment]
Wow _Pic4Review_ is a really nice project. And yet another nice OSM tool that nobody can find… :roll_eyes:

**Comment by westnordost** [comment]
Yeah, pretty cool idea and execution. You can vote for it in the upcoming OSM  awards in the category "innovation".

**Comment by rugk** [comment]
> OSM  awards

Also did not know, _such a_ thing exists… link: https://wiki.openstreetmap.org/wiki/OpenStreetMap_Awards (don't know how you know the candidates for 2019, however)

**Comment by chstdu** [comment]
> > OSM  awards
> 
> Also did not know, _such a_ thing exists… link: https://wiki.openstreetmap.org/wiki/OpenStreetMap_Awards (don't know how you know the candidates for 2019, however)

You can already vote for the 2019 Awards: http://awards.osmz.ru/

**Comment by westnordost** [comment]
There is also an app from wikimedia commons with which you can quickly contribute photos:
https://commons.wikimedia.org/wiki/Commons:Mobile_app
