### ISSUE TITLE
WiFi quest

### ISSUE THREAD

**Issue by fansanelli** [westnordost/StreetComplete#1517]
It would be interesting to do have a quest about "internet_access=wlan" quest.
In future could also be expanded to add also cost information.
Hotels, restaurants and cafes are common places where a free internet access (at least for customers).

### General
Affected tag(s) to be modified/added: [x] https://wiki.openstreetmap.org/wiki/Key:internet_access
Question asked: **Is WiFi internet access provided in item XY?**

### Checklist
Checklist for quest suggestions (see guidelines):
- [ ] 🚧 To be added tag is established and has a useful purpose
- [ ] 🤔 Any answer the user can give must have an equivalent tagging (Quest should not reappear to other users when solved by one)
- [x] 🐿️ Easily answerable by everyone from the outside but a survey is necessary 
- [ ] 💤 Not an overwhelming percentage of elements have the same answer (No spam)
- [x] 🕓 Applies to a reasonable number of elements (Worth the effort)

**Comment by ENT8R** [comment]
There is already a quest for that purpose (was implemented with #784).
To get an overview of all implemented quests, you can view the list of quests in the Wiki: https://wiki.openstreetmap.org/wiki/StreetComplete/Quests or directly in the app settings.

**Comment by fansanelli** [comment]
I'm sorry @ENR8R... I completely missed it!
