### ISSUE TITLE
Sidewalk available

### ISSUE THREAD

**Issue by TobiasMie** [westnordost/StreetComplete#152]
An idea for a new quest is the ability to say what is around the street e.g. sidewalk or parking_aisle.
A problem is the direction of the way. Maybe it could be solved by displaying an arrow.

**Comment by westnordost** [comment]
Would you please elaborate?

**Comment by TobiasMie** [comment]
A good information for pedestrians is to know if a sidewalk is available. It is declared with sidewalk="left|both|right". The problem is that the user don't know in which direction the way (street) is drawn. Maybe it is possible to display an arrow to make sure in which direction is "left" or "right".

**Comment by westnordost** [comment]
Ok I see.

**Comment by matkoniecz** [comment]
Note that equally valid method of tagging sidewalks (used especially in highly mapped places) is mapping sidewalks as separate way. See http://www.openstreetmap.org/#map=18/50.07528/20.03002 for an example.

**Comment by CloCkWeRX** [comment]
I am a bit opposed to this quest, as the mapping style isnt settled (seperate way or attribute). Its annoying we dont have a best way to do this

**Comment by matkoniecz** [comment]
Note that there is also sidewalk=separate tag that some use to mark roads where sidewalks are mapped separately.

**Comment by westnordost** [comment]
But it is not used consistently, so it is useless. But worry not, I have a solution. Did you check out the `cycleways` branch yet? The branch is basically ready to merge.

This quest can easily be created using the same technique(s) as used for the cycleway quest.

**Comment by matkoniecz** [comment]
> Did you check out the cycleways branch yet?

Looks interesting. I would recommend excluding also roads with bicycle=no in https://github.com/westnordost/StreetComplete/compare/cycleways?expand=1#diff-d36221f1f799ee2ad743fbe2bc979067R142

> But it is not used consistently, so it is useless.

I thought about "mapped separately" as an answer, not only to exclude in overpass query.

**Comment by westnordost** [comment]
> excluding also roads with bicycle=no

Why?

**Comment by matkoniecz** [comment]
Highway tagged as bicycle=no and with cycleway tag generally makes no sense (in theory, there may be a cycling infrastructure with forbidden use - but it is an extreme usecase).

So not asking whatever highway with bicycle=no has cycleway would reduce quest spam.

**Comment by westnordost** [comment]
That would mean that i.e. 
```
highway=primary
bicycle=no
cycleway:right=track
```
would be an error. I am not so sure about this, it could be tagged that way by people who mean to say "you _must_ use the track as a cyclist".

**Comment by matkoniecz** [comment]
> would be an error

I would interpret it as "there is a separate cycleway but cyclists are anyway unable to use it" (so it would be likely a tagging error - this situation happens extremely rarely).

But maybe mappers, routers and other data consumers interpret it differently?

**Comment by matkoniecz** [comment]
The same here - does it make sense to ask about sidewalks on road tagged foot=no?

**Comment by ftrebien** [comment]
The wiki recommends mapping cycle [lanes](https://wiki.openstreetmap.org/wiki/Bicycle#Cycle_lanes_in_bidirectional_motor_car_roads) as tags and cycle [tracks](https://wiki.openstreetmap.org/wiki/Bicycle#Cycle_tracks) as separate lines. In the case of mapping a cycle track separately, the wiki says that the cycleway tag [should be left empty](https://wiki.openstreetmap.org/wiki/Key:cycleway#Cycle_tracks), though [maybe](https://lists.openstreetmap.org/pipermail/tagging/2018-January/034812.html) cycleway=separate would be more reasonable, following the example of sidewalk=separate.

On [sidewalks](https://wiki.openstreetmap.org/wiki/Sidewalks#How_to_map), I think it is reasonable to suggest that they could be mapped as tags whenever possible and as lines whenever necessary. Complex sidewalks that would be difficult to map as tags tend to occur only in dense city cores.

**Comment by RubenKelevra** [comment]
I would love to be able to tag sidewalks with SC :)

**Comment by Mannshoch** [comment]
Yes, It's a bit strange that you could tag cycleways but not sidewalks.

**Comment by rugk** [comment]
Should not this issue be closed? (as it has been included with v10 of SC?)

**Comment by westnordost** [comment]
right
