### ISSUE TITLE
Marker for creating notes changes position when switching phone orientaton (portrait/landscape)

### ISSUE THREAD

**Issue by ltog** [westnordost/StreetComplete#1524]
When one is in the process of creating a new note (after pressing the `!` symbol), the position of the symbol (=where to create the note) jumps around when the phone orientation (portrait/landscape) is switched. The marker should stay at the same position instead.

Version 13.0 on Android 7.1.2

**Comment by westnordost** [comment]
This is not really a bug, but I agree that the pin could appear more stable when rotating the screen. Unfortunately, it is not trivial to do.

**Comment by rugk** [comment]
Related to https://github.com/westnordost/StreetComplete/issues/1422 https://github.com/westnordost/StreetComplete/issues/1039

This general thing is really re-occuring, as it seems.

**Comment by westnordost** [comment]
done
