### ISSUE TITLE
Deauthorisation when tapping "authorise OSM access" while being authorised

### ISSUE THREAD

**Issue by LimaKilo** [westnordost/StreetComplete#1534]
When the device is authorised and you tap on the "authorise OSM access" menu entry, the device gets deauthorised and OSM opens for a new authorisation. It should either ask for confirmation to do that or have a description that it will do this. I tapped on it because I thought it might show my profile.

**Versions affected**
Android 6, Streetcomplete Version 13.0

**Comment by westnordost** [comment]
And what's the problem with logging in again?

**Comment by LimaKilo** [comment]
> 
> And what's the problem with logging in again?

It's annoying. It's just a minor thing, but a button that logs me out should say so.

**Comment by westnordost** [comment]
Well ok, I don't mind if someone wants to implement this.

**Comment by typebrook** [comment]
@westnordost 
A single alert dialog should be fine, check #1535
