### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by matkoniecz** [westnordost/StreetComplete#154]
For start - sorry for mentioning the topic, but I think that it is better to handle potential licence issues as early as possible to avoid wasting more time on that than necessary.

It seems that https://github.com/westnordost/StreetComplete#license should be amended. At least https://github.com/westnordost/StreetComplete/blob/master/res/feature_graphic.png is CC-BY-SA 2.5

What is the status of other /res/ files? Is something else also under CC-BY-SA or other licenses?

**Comment by westnordost** [comment]
As far as I understand, CC-By-SA is compatible to GPL as in things under the cc can be shipped under the GPL as well because the latter is more restrictive.

Isn't it?

The rest in res/ I made myself.

On 27 April 2017 10:00:36 CEST, Mateusz Konieczny <notifications@github.com> wrote:
>For start - sorry for mentioning the topic, but I think that it is
>better to handle potential licence issues as early as possible to avoid
>wasting more time on that than necessary.
>
>It seems that https://github.com/westnordost/StreetComplete#license
>should be amended. At least
>https://github.com/westnordost/StreetComplete/blob/master/res/feature_graphic.png
>is CC-BY-SA 2.5
>
>What is the status of other /res/ files? Is something else also under
>CC-BY-SA or other licenses?
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/westnordost/StreetComplete/issues/154

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by matkoniecz** [comment]
It is not that simple, from what I understand CC-BY-SA cannot be used in GPLv1/GPLv2 projects (but I may be mistaken). 

I thought that it applies also to GPLv3 but during search for citation that would confirm this I found following in https://wiki.creativecommons.org/wiki/ShareAlike_compatibility https://creativecommons.org/share-your-work/licensing-considerations/compatible-licenses/

> For BY-SA 2.0, all future versions of BY-SA and all ports of BY-SA 2.0 or later are automatically compatible

(...)

> For BY-SA 4.0, all future versions of BY-SA and all ports (if any) of BY-SA 4.0 or later are automatically compatible, as well as licenses explicitly deemed compatible pursuant to the ShareAlike compatibility process

I have no idea whatever it should be interpreted as "CC-BY-SA 2.5 must not be used in GPL project" or "CC-BY-SA 2.5 is compatible with CC-BY-SA 4.0, therefore oneway compatible with GPL v3".

**Comment by matkoniecz** [comment]
Given that it would probably require lawyer to solve and image in readme is fairly easy to replace I think it may be ignored (unless somebody has clear indication that CC-BY-SA 2.5 is not upgradable to CC-BY-SA 4 in way that allows it to be used in GPL v3 projects).
