### ISSUE TITLE
Exclude ruins=yes - from address and building quest

### ISSUE THREAD

**Issue by matkoniecz** [westnordost/StreetComplete#1541]
I propose to start filtering out object with ruins=yes for quests about buildings (building type, address quest, roof shape maybe also building levels)

Such buildings are often not really answerable and value of answers will be low. Large number of questions will end in failure to reply.

Some ruins were built was reasons that are not clear now, a roof may be caved in making the roof shape question unanswerable (and not really fixable by tagging it), building levels are weird at the best (is 0 correct in case of completely missing roof) etc.

Though I admit that the real reason is that at least in some places many object could have historic=* tag, are missing it but ruins=yes is present.

![images](https://user-images.githubusercontent.com/899988/63712680-794b0d00-c83e-11e9-936f-32ea6ac01aa3.jpeg)

**Comment by westnordost** [comment]
Yes, makes sense
