### ISSUE TITLE
Parts of interface are broken by built-in text resizing from accessibility tools

### ISSUE THREAD

**Issue by matkoniecz** [westnordost/StreetComplete#1548]
In Android Settings there is setting "Accessibility" that in section "Display" has "Font size".

Switching it to maximum possible value breaks at least some parts of SC interface - for example building levels quest is not displaying parts of the text

My Android is on version 9, running on Mi A2 Lite.

Screenshot: https://user-images.githubusercontent.com/899988/64042601-7c0d7100-cb62-11e9-86f6-bab170b3f517.png

**Comment by westnordost** [comment]
These need to be looked at on a case by case basis. So, posting one example is not enough, all the cases need to be collected and then fixed or will-not-fixed.

**Comment by matkoniecz** [comment]
So it would be necessary to check interface of all quests. Hunting them manually would be a huge waste of time.

I thought about a special mode that would replace Overpass API connection by something returning fake data that would result in all quests generating one instance each at one place.

But now I think that it may be nicer to have script that will try to find real data where quests will be generated, finding a place for every quest.

**Comment by westnordost** [comment]
Easier: build an activity that lists all quest types (copy and simplify from the quest selection list), on click of a quest type, it shows the form with a mock element

Am 31. August 2019 11:54:58 MESZ schrieb Mateusz Konieczny <notifications@github.com>:
>So it would be necessary to check interface of all quests. Hunting them
>manually would be a huge waste of time.
>
>I thought about a special mode that would replace Overpass API
>connection by something returning fake data that would result in all
>quests generating one instance each at one place.
>
>But now I think that it may be nicer to have script that will try to
>find real data where quests will be generated, finding a place for
>every quest.

**Comment by westnordost** [comment]
And that activity could be shown when clicking on a certain item in the settings which is only available if the build is a debug build or something.

That should be about 50 LOC.

Am 31. August 2019 11:54:58 MESZ schrieb Mateusz Konieczny <notifications@github.com>:
>So it would be necessary to check interface of all quests. Hunting them
>manually would be a huge waste of time.
>
>I thought about a special mode that would replace Overpass API
>connection by something returning fake data that would result in all
>quests generating one instance each at one place.
>
>But now I think that it may be nicer to have script that will try to
>find real data where quests will be generated, finding a place for
>every quest.

**Comment by westnordost** [comment]
Added this. Was 100 LOC after all. So you can go ahead. Though, note that the view isn't perfect. It just creates a mock node as element but some quests assume certain tags on the element.

**Comment by matkoniecz** [comment]
Thanks! I will go through this in about a week.

**Comment by westnordost** [comment]
Also you can always extend the functionalities of that as screen of you wish 

Am 6. September 2019 04:44:44 MESZ schrieb Mateusz Konieczny <notifications@github.com>:
>Thanks! I will go through this in about a week.

**Comment by matkoniecz** [comment]
I reviewed now all interfaces, with most paths (should be all reachable with single set of hardcoded tags) and opened PR removing crashes for some quests.

Oneway and note quest were not reviewed using layout list, but note quest and note creation quests were reviewed manually.

---

systematic review: 

- building levels quest - the most noticeable breakage
- road name, bus stop name has top entry in "can't say" menu cut off
- bicycle parking - wheelbender text is not fully displayed despite available space
- toilet wheelchair acessibility - a bit weird intend
- note creation - for some reason hint text is very large, much larger than other texts

**Comment by westnordost** [comment]
> road name, bus stop name has top entry in "can't say" menu cut off

Apparently not trivial to do, too much effort

Rest is fixed.
