### ISSUE TITLE
Please make it possible to undo notes

### ISSUE THREAD

**Issue by hmartink** [westnordost/StreetComplete#1549]
You can undo the last entry/entries, but this only applies to quests but not to notes.

It would be great if notes could be undone as well.

**Comment by matkoniecz** [comment]
Note that parts are impossible to undo - for example there is no way to undo posting comment, and it is not limitation of just StreetComplete.

**Comment by typebrook** [comment]
Yup
> Resolved notes are not removed or deleted. After a period of seven days they are hidden from view. 

ref: https://wiki.openstreetmap.org/wiki/Notes#Resolving_notes

**Comment by westnordost** [comment]
@hmartink: Can you write something about your use case? Why would you need that? Also, do you have Auto-Sync on or off?

**Comment by westnordost** [comment]
Closing because of no feedback
