### ISSUE TITLE
Tangram + opengl ES + replicant = crash

### ISSUE THREAD

**Issue by pmaziere** [westnordost/StreetComplete#155]
hi,

I'm aware this is not directly a streetcomplete issue, but since this tool seems very useful and efficient I would very much like to use it on my replicant android device.
Since replicant does not support openGL ES because of the lack of open source drivers, any software that requires it crash on replicant devices.
It seems that Tangram uses openGL ES to display maps which makes your tool unusable on replicant devices.

Would it be possible to think of another library to handle maps in future versions, or to provide an non openGL way to display maps ?

thanks

**Comment by westnordost** [comment]
I read up a bit about Replicant OS. I am sorry, but this will be too much effort to implement. It would mean to (be able to) replace the rendering library tangram-es which only works with OpenGL ES with something else completely.
