### ISSUE TITLE
Add missing ref=* on amenity=post_box

### ISSUE THREAD

**Issue by rjw62** [westnordost/StreetComplete#1556]
### General
Affected tag(s) to be modified/added: [ref=*](https://wiki.openstreetmap.org/wiki/Key:ref) on [amenity=post_box](https://wiki.openstreetmap.org/wiki/Tag:amenity=post_box)
Question asked: **What is the reference number of this post box?**

### Checklist
Checklist for quest suggestions (see guidelines):
- [ x ] 🚧 To be added tag is established and has a useful purpose
- [ x ] 🤔 Any answer the user can give must have an equivalent tagging (Quest should not reappear to other users when solved by one)
- [ x ] 🐿️ Easily answerable by everyone from the outside but a survey is necessary 
- [ x ] 💤 Not an overwhelming percentage of elements have the same answer (No spam)
- [ x ] 🕓 Applies to a reasonable number of elements (Worth the effort)

### Ideas for implementation

**Element selection:** 

amenity=post_box nodes in countries where post boxes usually have numbers (certainly includes UK and France), which have no ref=* tag, and ref:signed=* (if present) is not equal to "no".

**Proposed GUI:**

Q: What is the reference number of this post box?

* The reference number is [ ________________ ]
* This box should have a number but it is not shown or is unreadable.
* This box does not have a number (perhaps it is a private post box).

In the first case ref=* is set to the value given. In the second case ref:signed=no is set. In the third case ref=no is set.

(There has been some discussion about ref=* more generally in #81.)

**Comment by matkoniecz** [comment]
Can you post of photo for typical ref number looks like?

Is there any current user of this data?

**Comment by westnordost** [comment]
I guess this very much depends on the country. Also, I'd say it depends on the country of postboxes have ref numbers visible on the box at all. So, This quest should only be activated in countries where it is verified that they do.

Otherwise, the quest is ok. I'd probably leave out the last option though because the this is something the surveyor likely won't able to answer.

Robert, would you be willing to do the research about it?

Am 11. September 2019 19:03:46 MESZ schrieb Mateusz Konieczny <notifications@github.com>:
>Can you post of photo for typical ref number looks like?
>
>Is there any current user of this data?

**Comment by rjw62** [comment]
Typical UK post box collection plate. The box number is in the bottom left.
![collection-plate](https://user-images.githubusercontent.com/726679/64720666-ec04eb00-d4c2-11e9-8b76-280e8fb23ed8.jpg)
I make use of the UK post box ref values in a tool I've set up to track mapping of boxes https://osm.mathmos.net/postboxes/progress/ . (The official data isn't available under a suitable licence to use directly in OSM, and the locations given aren't always precise enough anyway. But it's a good source for determining productive places to survey. Having the box numbers surveyed helps with matching the OSM data to the official list.)

Over at https://github.com/westnordost/StreetComplete/issues/81#issuecomment-366471694 a @fgouget was keen to get the numbers for French boxes, for similar reasons.

**Comment by westnordost** [comment]
@rjw62 Well as said, this is blocked until someone researches in which country posbox numbers are usually displayed. A similar research has been made for collection times on postboxes:

https://ent8r.github.io/blacklistr/?streetcomplete=postbox_collection_times/AddPostboxCollectionTimes.kt

**Comment by rjw62** [comment]
@westnordost I've been through the wikimedia commons category above and identified 11 countries that appear to have visible reference numbers on their post boxes. All these counties also have some examples mapped in OSM.

The countries are: France (FR), Guernsey (GG), Ireland (IE), Isle of Man (IM), Jersey (JE), Malta (MT), Singapore (SG), Slovakia (SK), Switzerland (CH), United Kingdom (GB), United States (US).

Will this do as a starting point? I'm also happy for the final answer option to be dropped if you think it will be better to keep things simpler.

**Comment by westnordost** [comment]
Yes, that is a good start! Thank you

**Comment by ltog** [comment]
I can confirm that reference numbers are visible on postboxes in Switzerland.

**Comment by j9d3it** [comment]
![Image](https://github.com/user-attachments/assets/79774d8e-2bab-44ff-81b6-2aca31db2f1e)
Hello, reference numbers are also posted on postboxes in Japan, please enable them as well.

**Comment by riQQ** [comment]
@j9d3it please open a new issue for this.
