### ISSUE TITLE
APK not installable on SailfishOS

### ISSUE THREAD

**Issue by charlycoste** [westnordost/StreetComplete#156]
I tried to install this package `https://f-droid.org/repo/de.westnordost.streetcomplete_4.apk` on my Jolla phone, but I just can't install the package. Maybe the Dalvik version of SailfishOS is too old to handle it.

I've got a message that says something like "Analysis error" and "A problem occured during package analysis"

![799e936de088b76e](https://cloud.githubusercontent.com/assets/352634/25477475/eaa9669a-2b3d-11e7-9059-8c1672064155.png)

**Comment by westnordost** [comment]
Oh, sorry, I have no idea about SailfishOS. It seems to be rather a problem of the OS not supporting the APK, nothing I can do about that.

The minimum Android API version is 17, I did not find out on which API version Sailfish OS is based on. Perhaps it is based on a lower version?

**Comment by westnordost** [comment]
According to https://together.jolla.com/question/66931/what-android-version-jolla-is-compatible-with/ Jolla is compatible with Android 4.1.2 which is Android API 16, so it is not supported. :-(
