### ISSUE TITLE
Auto-Sync should be triggered after pressing "invalidate quest cache"

### ISSUE THREAD

**Issue by matkoniecz** [westnordost/StreetComplete#1561]
**How to Reproduce**
Start app. Wait for quest download to finish. Go to setting and use "invalidate quest cache".

It is not triggering quest download.

It affects also "refetch quests on detection that uploaded quest was already done #307" feature.

Very similar to #1497

**Versions affected**
Tested on master - https://github.com/westnordost/StreetComplete/commit/3335e5f1226785dada06989ef1e8ab7df01ab6ca

**Comment by westnordost** [comment]
What do you mean with blocked? Do you mean that the auto-sync of quests is not triggered automatically after pressing that button? Or do you mean that if it the auto-sync is triggered, the quests are not downloaded?

**Comment by matkoniecz** [comment]
> Do you mean that the auto-sync of quests is not triggered automatically after pressing that button?

Yes.

**Comment by matkoniecz** [comment]
Sync is triggered but `Not downloading quests because there are enough quests in`

**Comment by westnordost** [comment]
Ok the culprit is in `AActiveRadiusStrategy.java`.
