### ISSUE TITLE
New quest on element not visible before old quest is uploaded

### ISSUE THREAD

**Issue by ltog** [westnordost/StreetComplete#1566]
I noticed the following behaviour: When a quest "What surface does the road ... have here?" is solved, a subsequent quest "Is ... lit here?" on the same object is not immediately displayed, but only when the first quest was manually uploaded (over cellular network).

I would expect that a new quest on the same object is immediately displayed after the first quest has been solved.

Settings: Auto-sync: Only on Wi-Fi (not sure if it's relevant)

**How to Reproduce**
see above

**Versions affected**

Android 7.1.2.
StreetComplete 13.0

**Comment by matkoniecz** [comment]
See #1510
