### ISSUE TITLE
Upload images from gallery (shinked, cropped, marked, painted images)

### ISSUE THREAD

**Issue by Katzenstreu** [westnordost/StreetComplete#1567]
Hello,

I want to upload smaller images to reduce my traffic. Sometimes I would like to mark thinks with "Paint" on my photos and upload them.
I suggest: Make uploading images from the gallery possible.

Thanks a lot, best regards,
Tim

**Comment by westnordost** [comment]
The pictures are already shrinked before upload. Regarding cropping, you could just zoom in before taking a picture, then, you also do not need to mark things in the picture.

**Comment by westnordost** [comment]
Of course it would be technically possible to implement it, however, not offering this choice has two advantages:
1. it is one tap less to do what most do (take a picture right now)
2. More importantly, it guarantees that any pictures uploaded are actually photos, made by the user himself and very likely really made on-site. So:
    - it is kind of a proof that you were really on site
    - it prevents abuse and spam of the image upload service
    - it prevents copyright infringements because photos are always guaranteed to be your own work. In light of the [latest prevailing legal norms](https://en.wikipedia.org/wiki/Directive_on_Copyright_in_the_Digital_Single_Market#Articles_11_and_13_(15_and_17_as_passed)), I rather stay on the safe side here, as I do not have time/resources to oversee the content uploaded

So, changing this would need a good reason, and marking photos is not that good of a reason.

Actually, if you really want to mark, resize and crop your photos, there is an easier solution: 

StreetComplete just tells your camera app to please take a photo and return it. If your default camera app would support modifying the taken photo before returning it to StreetComplete, it would solve your use case. Just look around in the Play Store, perhaps you find an app with which you can do that. If you do, you could kindly post it here so others looking for this can also get it.

**Comment by markwaters** [comment]
I would like the ability to upload photos , or more likely screen-grabs from my velomobile onboard security cameras.
At the moment I have to put a link to an image elsewhere.
https://www.openstreetmap.org/note/2049867

**Comment by westnordost** [comment]
So, you have access to this velomobile on-board security camera from your smartphone while being on the go?

Am 7. Januar 2020 19:28:21 MEZ schrieb Mark Waters <notifications@github.com>:
>I would like the ability to upload photos , or more likely screen-grabs
>from my velomobile onboard security cameras.
>At the moment I have to put a link to an image elsewhere.
>https://www.openstreetmap.org/note/2049867

**Comment by markwaters** [comment]
Yes.
But I usually review the footage later from a PC.

**Comment by westnordost** [comment]
And if you don't, you would be able to use it like a camera-device?

If you review and possibly edit / crop the footage later on Pc it would make most sense to also upload it from there rather than load it back on the smartphone only so that you are able to do it with StreetComplete. 
There is for example a free and open source image upload service available called framapic: https://framapic.org/


Am 7. Januar 2020 20:34:48 MEZ schrieb Mark Waters <notifications@github.com>:
>Yes.
>But I usually review the footage later from a PC.

**Comment by markwaters** [comment]
OK.

**Comment by matkoniecz** [comment]
> time/resources to oversee the content uploaded

See also https://wiki.openstreetmap.org/wiki/Category:Media_without_a_proper_attribution https://wiki.openstreetmap.org/wiki/Category:Media_without_a_license https://wiki.openstreetmap.org/w/index.php?title=Special:UncategorizedFiles&limit=500&offset=7000 - OSM Wiki has thousands of images waiting for exactly that, with things improving very slowly (at current rate it will take at least decades to process just already known problems)
