### ISSUE TITLE
"What is being cultivated here" only allows single type

### ISSUE THREAD

**Issue by eliasp** [westnordost/StreetComplete#1568]
**How to Reproduce**
When answering the *What is being cultivated here?* quest, it is only possible to select a single type of produce.
Most orchards around here have a wide variety of fruits, such as pears, plums, apples, ...

According to the documentation of [key:produce](https://wiki.openstreetmap.org/wiki/Key:produce#Multiple_values) multiple types can be tagged by separating them using a semicolon.

**Versions affected**
Android 8.0
StreetComplete 14.0

**Comment by westnordost** [comment]
This is correct, the app currently does not allow this. In this case, you need to leave a note instead to explain the situation.

These orchards, do they keep the trees grouped by produce, or are they all mixed together? If it was the former, the orchard area would better need to be split up.

**Comment by eliasp** [comment]
The trees are mostly relatively widely spaced and don't follow any particular grouping.
So it might possibly make more sense to place individual trees on orchards and tag them individually?

[Those orchards](https://de.wikipedia.org/wiki/Streuobstwiese) are quite common around here, so it's not quite a rare edge case:
![image](https://user-images.githubusercontent.com/48491/65150750-40a0ec80-da14-11e9-9c3d-362754a0e1cf.png)

**Comment by westnordost** [comment]
Well I guess both "Streuobstwiese" (traditional, polyculture) and "Obstplantage" (industrial mono-culture, trees pruned to short trunks) is `landuse=orchard`.

If the orchard is not a monoculture, as in your case, I guess it does not make much sense to let the surveyor check every type of fruit-tree he suspects to be somewhere on that orchard. This is highly error-prone (he might forget a few, or assume one too many cause he saw it on another orchard, etc).

Instead, it should be able to somehow tag that this orchard is a "Streuobstwiese". The wiki does not say anything about it, on the discussion page, someone suggested to tag it instead `landuse=meadow_orchard` a few years back, with no response.

I'll pitch a discussion about it on the tagging mailing list.

**Comment by westnordost** [comment]
Okay, so there is the tag `orchard=meadow_orchard` for "Streuobstwiese". It could be an "other answer" option. But then again, there might be places where it is not a Streuobstwiese but a normal plantation with mixed fruit trees. Or the other way round, it is a Streuobstwiese, but there is only one type of fruit on it. So, thinking about it, it really is a separate property.

What I am going to do, is to allow checking multiple types, like you suggested at the start. If it is a Streuobstwiese and one can not really ascertain it, one can always leave a note.
