### ISSUE TITLE
[New quest] What payment methods are accepted here?

### ISSUE THREAD

**Issue by Atrate** [westnordost/StreetComplete#1573]
### Affected tag(s) to be modified/added:
 payment:method=yes/no/interval

### Question asked:
What payment methods are accepted here?

### Example keys:

payment:coins=yes/no/interval

payment:cash=yes/no/interval

payment:notes=yes/no/interval

payment:visa=yes/no/interval

payment:mastercard=yes/no/interval

And the explicit

payment:debit_cards=no

payment:credit_cards=no

### Checklist for quest suggestions (see guidelines):

- [x]  🚧 To be added tag is established and has a useful purpose
- [x]  🤔 Any answer the user can give must have an equivalent tagging (Quest should not reappear to other users when solved by one)
- [x]  🐿️ Easily answerable by everyone from the outside but a survey is necessary
- [x]  💤 Not an overwhelming percentage of elements have the same answer (No spam)
- [x]  🕓 Applies to a reasonable number of elements (Worth the effort)

**Comment by ferdinand0101** [comment]
So where would you want to run this ?
Any shop and restaurant ?

**Comment by matkoniecz** [comment]
Is there any current user of this data?

Are there places where answer would not be basically the same for every shop? For example in Poland basically any shop accepts the same payments, with very rare case of cash-only shops and very rare cases of fully automated payment locations not accepting cash.

**Comment by ferdinand0101** [comment]
Well in a lot of restaurants especially imbisses it's a 50 50 thing if they'll accept cards
So I can definitely see some use here

**Comment by rugk** [comment]
In any case, this would be an indoor-only quest, i.e. disabled by default.

**Comment by MegaArthur** [comment]
Yes, it would be disabled by default. As matkoniecz has mentioned, most shops (in Poland) accept the same methods of payment, but it can differ substantially for amenities like restaurants or beauty shops etc.

**Comment by westnordost** [comment]
That's a lot of data to add, I am not sure about the usefulness of this.

**Comment by ferdinand0101** [comment]
I believe to make it more useful only EC and credit cards are relevant
I know of no store which doesn't accept cash

**Comment by matkoniecz** [comment]
>  I know of no store which doesn't accept cash

Happens in some regions, Sweden is quite famous for that.

**Comment by HolgerJeromin** [comment]
> I believe to make it more useful only EC and credit cards are relevant

I learned from osm discussions that EC is no current payment system anymore. Is is now girocard with different logos ("girocard" and "electronic cash PIN-Pad" are current, "ec electronic cash" is old). 
The girocard can be used with an EMV crypto chip (payment guarantee for the dealer) or without as "direct debit" (Lastschrift).
ref https://de.wikipedia.org/wiki/Girocard#Akzeptanzzeichen (sorry, german). But I am not sure if this difference is taggable.

But an "ec electronic cash" logo at the door is not sufficient, we probably need to see the terminal itself...

**Comment by goldfndr** [comment]
As consumers go, I know that OsmAnd will display Visa, MasterCard, American Express (AMEX), Discover Card, Gift Cards, and Maestro Card from the tags of [a local "Dollar Tree"](https://www.openstreetmap.org/node/2968207819). It might display others mentioned.

I have heard of a few places in the US that don't accept cash but they are rare.

The fun thing I've heard in the past with Android Pay (now Google Pay) and Apple Pay is that some can accept and they (cashiers) aren't aware, but that might be mostly rectified by now.

**Comment by sdicke** [comment]
The quest could be applied to vending machines, too. For example, some parking ticket vending machines in Germany only accept coins, other accept electronic pursue, too. And toy and chewing gums vending machines here normally just accepts coins.

**Comment by xuiqzy** [comment]
The _No spam_ criterium seems to depend on a combination of country and type of shop. In Germany, there are a lot of diners, but also some restaurants that do not accept any electronic payment but only cash.

**Comment by Atrate** [comment]
I guess this quest could be for example only applied to vending machines first and then expanded as needed?

**Comment by quite** [comment]
As has been mentioned, cash-only establishments are actually common in Sweden. Be it restaurants, cafés, and even regular shops. Perhaps grocery shops and convenience stores to a lesser extent. Obviously, it is hard to find a place where you cannot pay with some kind of card.

Being able to collect in particular `payment:cash=yes/no/interval` for essentially *any* kind of place where payment is needed in Sweden would be very useful. If people are indeed using StreetComplete, but I find this tool great; slick interface, easy to use.

A friend has even started to build an app/webapp for *finding* places where cash payment is still possible around here. Using OSM api. @stemid

**Comment by ferdinand0101** [comment]
So if I understand you correctly they cash part should be for only some countries and the electronic part only for some others ?

**Comment by quite** [comment]
I'm *only* saying that in my experience, cash yes/no would be very useful in Sweden. Card yes/no *much* less so.

**Comment by stemid** [comment]
Cash is disappearing in Sweden right now. More and more people want help finding places that accept cash. It's a growing movement and it has the potential to turn the cashless trend around.

So I vote for a quest where you can answer whether a business accepts cash or not.

**Comment by westnordost** [comment]
If there can be reasonable doubt in Sweden whether a shop accepts cash or not, asking whether a shop accept cash in Sweden is eligible as a quest.

**Comment by quite** [comment]
@westnordost in the faq about new quests it says "Publicly accessible: The information the users are supposed to collect must be easily accessible from the outside, don't lead users into trouble. I.e. users will not be able to answer reliably if a building has a basement or not, if a restaurant has toilets or not etc. without entering it.". Can we still have a simple cash-accepted-quest? :)

**Comment by westnordost** [comment]
Yes, but it would be disabled by default, just like the vegetarian quest.

**Comment by quite** [comment]
@stemid or anyone, feel free to pick up the work on #1743 -- i have very little time. Tried this out for fun :)

**Comment by matkoniecz** [comment]
`payment:cash` is now implemented and enabled for Sweden - and may be enabled for other countries if needed

`payment:notes` and `payment:coins` seems to not be really useful and can be answered only for vending machines

`payment:credit_cards`, `payment:debit_cards` seems dubious to me. You generally have specific card not generic "credit card"

`payment:visa`, `payment:mastercard` - while there are shops where you pay only by cash I am unsure about value of asking this.

**Comment by westnordost** [comment]
Ok so I will close this

**Comment by Atrate** [comment]
> payment:credit_cards, payment:debit_cards seems dubious to me. 

I just threw it as an example of a tag that should be only used explicitly with "no", seen as, as you point out, there are many types of cards so this key can only be used to say that no credit cards are accepted.
