### ISSUE TITLE
[New quest] What is the surface of this parking lot?

### ISSUE THREAD

**Issue by MegaArthur** [westnordost/StreetComplete#1577]
## General

We already have the surface quests for roads, paths and squares, so why not have it for parking lots? 

### Affected tag(s) to be modified/added:
 surface=*

(Provided there is a parking=surface tag)

### Question asked:
What is the surface of this parking lot?

### Checklist for quest suggestions (see guidelines):

- [x]  🚧 To be added tag is established and has a useful purpose
- [x]  🤔 Any answer the user can give must have an equivalent tagging (Quest should not reappear to other users when solved by one)
- [x]  🐿️ Easily answerable by everyone from the outside but a survey is necessary
- [x]  💤 Not an overwhelming percentage of elements have the same answer (No spam)
- [x]  🕓 Applies to a reasonable number of elements (Worth the effort)

**Comment by westnordost** [comment]
Surely, this is a thing that could be mapped. However, I wonder how this would be useful, since routers usually look at the roads only, not the areas the roads lead through. Also, since a parking lot is likely only the start or the end of a journey, even the surface information and the parking aisle ways is of little value.

**Comment by sdicke** [comment]
Maybe routers ignore the parking lot surfaces because too few a mapped? I think that parking lot surfaces could be a useful routing criterion, a router could prefer parking lots with paved surfaces when it is raining.

**Comment by westnordost** [comment]
This is a bit beside the point. This is about the parking area, not the aisles.

**Comment by westnordost** [comment]
Will not fix, see my first comment.

**Comment by paulklie** [comment]
I think think could be useful for wheelchair users:
Depending on if a (surface) parking lot is asphalted, or just grass, mobility can differ significantly.

**Comment by westnordost** [comment]
Parking spaces for disabled users are usually located closest to the destination, very close or right next to the sidewalk.
