### ISSUE TITLE
Upload results in a flood of tiny changesets

### ISSUE THREAD

**Issue by TO-92** [westnordost/StreetComplete#1579]
Some days ago I took a field trip with StreetComplete (latest version, 14.0). Auto-Sync was off, and when I got home to my WLAN I started a manual upload.

To my surprise I found that it had created almost 100 individual changesets, each with just one single edit, like 42× "Add path surfaces", 26× "Add whether way is lit", etc.

See https://www.openstreetmap.org/user/BC168/history between 2019-09-22T18:42:01Z and 2019-09-22T18:46:02Z

I seem to recall that StreetComplete used to "bundle" edits, creating only one changeset per quest containing all the changes of that type. So this does not look like it is intended behaviour, does it?

**Comment by westnordost** [comment]
Yes, it should bundle it. This is a critical bug, I will investigate.

**Comment by westnordost** [comment]
Hmm, I can not reproduce it. See https://www.openstreetmap.org/changeset/74897075

I tried both Auto-Sync on and Auto-Sync off. So it does not always happen. One example changeset of yours is https://www.openstreetmap.org/changeset/74779079
Interesting here is that the changeset was closed one second after it was opened. This will be the reason why a new changeset was created. The app tried to upload the change into the existing changeset but got rejected cause it was already closed.

So the question is, why is it closed?

**Comment by westnordost** [comment]
Got it. The bug was that the app was closing the changeset created for each change immediately before uploading the next change if the last quest was answered more than 20 minutes ago.

**Comment by peternewman** [comment]
> Got it. The bug was that the app was closing the changeset created for each change immediately before uploading the next change if the last quest was answered more than 20 minutes ago.

Hi @westnordost ,

Your comment here and the commit comment seem to disagree to me. I assume you mean the issue is if 20 minutes have elapsed between answering the quest and uploading the data?

I don't think that's true of some of mine either:
https://www.openstreetmap.org/user/Peter Newman/history

**Comment by westnordost** [comment]
> I assume you mean the issue is if 20 minutes have elapsed between answering the quest and uploading the data?

Yes 

> I don't think that's true of some of mine either:
> https://www.openstreetmap.org/user/Peter%20Newman/history

Why? One cannot see from the public history how much time elapsed between answering the question and uploading the answer. One can only see when it was uploaded, not when it was answered.

**Comment by peternewman** [comment]
> Why? One cannot see from the public history how much time elapsed between answering the question and uploading the answer. One can only see when it was uploaded, not when it was answered.

Sorry, I probably wasn't very clear, I know because of where I was walking that within 20 minutes of completing a number of those quests I was within WiFi range and still had the app running, or does it also need to be the foreground app to upload?

**Comment by westnordost** [comment]
It needs to be in the foreground, yes

**Comment by peternewman** [comment]
Hi @westnordost ,

I've updated to 14.1 and it still seems to be happening for me.

**Comment by peternewman** [comment]
> I've updated to 14.1 and it still seems to be happening for me.

Ignore me, I've just realised the edits are now grouped by quest, which I assume was the intended behaviour.

**Comment by matkoniecz** [comment]
Yes, this kind of splitting is intended!

Thanks for checking.
