### ISSUE TITLE
poor changeset description on changing road type

### ISSUE THREAD

**Issue by matkoniecz** [westnordost/StreetComplete#158]
To reproduce: AddRoadName quest -> other answers.. -> Not a proper street -> It is just a service road (a track variant will probably also do that)

expected: changeset description will include info that highway key was changed ('change value of highway key'?)

actual: changeset description 'Determine road names', StreetComplete:quest_type tag has 'AddRoadName'

In addition, as error prone this should be posted in changeset separate from updating name keys.

**Comment by matkoniecz** [comment]
This is especially important as user has no influence on changeset comment.

**Comment by westnordost** [comment]
Phew, this is difficult...

On 27 April 2017 15:21:21 CEST, Mateusz Konieczny <notifications@github.com> wrote:
>This is especially important as user has no influence on changeset
>comment.
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/westnordost/StreetComplete/issues/158#issuecomment-297711165

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by westnordost** [comment]
It would be easier to adapt the changeset comment to denote that this is also a possible change that can be made in the frame of this quest.

On 27 April 2017 15:21:21 CEST, Mateusz Konieczny <notifications@github.com> wrote:
>This is especially important as user has no influence on changeset
>comment.
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/westnordost/StreetComplete/issues/158#issuecomment-297711165

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by matkoniecz** [comment]
I see problem - now every quest is handled as belonging to single changeset type ( https://github.com/westnordost/StreetComplete/blob/ef46ee705101727d085c84aaffc7554d9cbf6631/app/src/main/java/de/westnordost/streetcomplete/data/osm/upload/OsmQuestChangesUpload.java#L253 ).

Changing it would require quest objects to split changes into multiple groups, each with their own changeset type (rather one change with quest type considered as sufficient to sort into changesets).

On the other hand description "all kind of street-related stuff changed" is not nice.

**Comment by matkoniecz** [comment]
> It would be easier to adapt the changeset comment to denote that this is also a possible change that can be made in the frame of this quest.

Yeah, as first step that would be great. But great changeset descriptions would really help to avoid causing problems among people editing with full scale editors.

**Comment by westnordost** [comment]
Yes. For a proper implementation, I'd have to make the changeset comment dependent of the actual quest again. The OpenChangesetsDao will need to also persist the changeset comment for each opened changeset and when determining whether or not to open a new changeset, it has to look not only onto the quest type but also the comment.
