### ISSUE TITLE
Cannot split way below a quest marker

### ISSUE THREAD

**Issue by janrieke** [westnordost/StreetComplete#1581]
Ways cannot be split at points where quest markers are shown.

**How to Reproduce**
Use the new "Split" function, and try to split the way right where the quest marker is shown.

Expected behavior: The way is split where you touched the screen, i.e. "below" the quest marker.

Actual behavior: Nothing happens.

**Versions affected**
StreetComplete 14.1 on Android 8.1.0 (LineageOS 15.1)

**Comment by matkoniecz** [comment]
Note that you can zoom in. With zooming in it still may happen but it requires desire to split at very specific locations.

**Comment by janrieke** [comment]
I know I can zoom in. But on my last 30 minutes mapping tour it happened 2 times to me that I could not split a way where I wanted to, and I had to switch to Vespucci. So at least for me that's not a exotic case.

**Comment by Helium314** [comment]
It might occur only in specific cases, but I see no reason why quest markers should receive priority over the split positions.
In some cases rotating the map seems like a reasonable way around this problem, as markers then block other positions.

**Comment by westnordost** [comment]
It is easier to hide the quest markers when in this view.

**Comment by westnordost** [comment]
Done!

**Comment by janrieke** [comment]
Thanks for the fix, works nicely.
