### ISSUE TITLE
Explicitly mention that changelog including images is also under an open licence

### ISSUE THREAD

**Issue by matkoniecz** [westnordost/StreetComplete#1582]
I know that it is intended, but from what I see it is never specified anywhere

Triggered by https://wiki.openstreetmap.org/w/index.php?title=Featured_image_proposals&diff=1906566&oldid=1906563

**Comment by westnordost** [comment]
Not sure if you noticed it, but the app is free software ;-)

See https://commons.wikimedia.org/wiki/Commons:Screenshots
