### ISSUE TITLE
AddTactilePavingBusStop Quest Prompts for Railway and Subway platforms with confusing text

### ISSUE THREAD

**Issue by peternewman** [westnordost/StreetComplete#1584]
**How to Reproduce**
This way offers the tactile paving quest:
https://www.openstreetmap.org/way/569053687

"Does the bus stop ... have tactile paving?"

**Versions affected**
Android 9, SC 14.1

Personally I'm not against the quest and I don't think it needs to be restricted, but it would be good if different text was displayed for the various transport types, similar to what was done to fix #806 .

In an ideal world, different icons would be good too, but I assume it then becomes lots of different quests and perhaps that isn't worth the coding overhead.

**Comment by matkoniecz** [comment]
Thanks for spotting and reporting!

requires equivalent of https://github.com/westnordost/StreetComplete/commit/7780b7308188790992b188e676eb7f28b1686003

AddBusStopName.kt, AddWheelchairAccessPublicTransport.kt, AddBusStopShelter.kt should be free from this bug

**Comment by peternewman** [comment]
Do we actually want to restrict (which seems unnecessary to me), or just have multiple worded prompts?

I'm hoping we can come up with some text that covers subway and railway as one (e.g. platform and train). I guess AddWheelchairAccessPublicTransport.kt might be inspiration there.

**Comment by peternewman** [comment]
It should probably also cover railway=platform_edge:
https://wiki.openstreetmap.org/wiki/Tag:railway=platform%20edge?uselang=en-GB

**Comment by peternewman** [comment]
Thanks @westnordost . It seems a shame not to cover railway and subway too though; whereas you've explicitly excluded them, or should I open a new enhancement/new quest to cover them?

**Comment by ferdinand0101** [comment]
if were allready there we could add text for Tram stops `tram=yes` (and why not also Light Rail,Monorail Aerialway,Funicular)
and while were add it how about doing the same for `amenity=ferry_terminal`

**Comment by westnordost** [comment]
Well, it could be a new quest. Code-wise, "new quests" are really really little work.

**Comment by peternewman** [comment]
Logically it feels like it probably just needs to be more different text prompts on the existing one, like where you added tram.
