### ISSUE TITLE
[New quest] Is this housenumber correct? (Import duplicate FIXMEs correction)

### ISSUE THREAD

**Issue by MegaArthur** [westnordost/StreetComplete#1585]
### General
Affected tag(s) to be modified/added: [addr:housenumber](https://wiki.openstreetmap.org/w/index.php?title=Key:addr:housenumber&redirect=no)
Question asked: **Is this housenumber correct/What is the housenumber of this building?**

### Checklist
Checklist for quest suggestions (see guidelines):
- [x] 🚧 To be added tag is established and has a useful purpose
- [X] 🤔 Any answer the user can give must have an equivalent tagging (Quest should not reappear to other users when solved by one)
- [X] 🐿️ Easily answerable by everyone from the outside but a survey is necessary 
- [X] 💤 Not an overwhelming percentage of elements have the same answer (No spam)
- [X] 🕓 Applies to a reasonable number of elements (Worth the effort)

**Element selection:** 
Housenumbers or buildings with FIXME/fixme="Duplicate housenumber in import"

Duplicate housenumbers in Poland, stemming from imports, are very common, at least where I live. SC could implement a quest to check addresses with FIXMEs and remove the FIXMEs or addresses or just correct the housenumber.

**Comment by westnordost** [comment]
For how many elements is this applicable?

Also, in the case of that the housenumber for that one building where a housenumber is seemingly assigned duplicate, couldn't it be that often instead of only for that building, all consecutive housenumbers are wrong? (offsetted by 1)

**Comment by matkoniecz** [comment]
>  Housenumbers or buildings with FIXME="Duplicate housenumber in import"

Can you link example object? I tried searching for FIXME="Duplicate housenumber in import" and fixme="Duplicate housenumber in import" and found 0 objects.

See http://overpass-turbo.eu/s/MGY

**Comment by MegaArthur** [comment]
Example of an easily fixable one (the nodes are literally in the same building):
https://www.openstreetmap.org/node/3667801070

One not that easily deduced from aerial imagery (the buildings are probably on the same lot, but not necessarily):
https://www.openstreetmap.org/node/3667798074

One pretty much impossible to deduce (the buildings are most probably on different lots):
https://www.openstreetmap.org/node/3683168252

Turns out the fixme is noncapitalised in this case.

**Comment by westnordost** [comment]
http://overpass-turbo.eu/s/MHL

Almost 50000 elements, that is a lot.

However, what do you say to my previous comment, @MegaArthur ?

**Comment by MegaArthur** [comment]
I haven't really seen off-by-one errors on big sets of elements. This doesn't mean they don't exist, just that I haven't seem them

**Comment by westnordost** [comment]
So what are the usual mistakes? Do the housenumbers sometimes not exist?

**Comment by MegaArthur** [comment]
With 2 housenumbers the case is usually that one is placed correctly and the other is not. Sometimes they overlap such that there are 2 different numbers in one building

**Comment by westnordost** [comment]
The app can only change the tags, not the position of the nodes though. So, in that case, this would be a problem with this point of the guidelines:
> 🤔 No unanswerable quests: All generated quests need to be actually answerable (no false-positives). This means that any answer given by the user must result in something being tagged. For example, a quest that asks for the website of a place must be able to tag the element somehow if the user answers that the place has no website - otherwise, the next user will be asked the same question. Sometimes, due to the nature of how things are tagged in OSM (such as the one given in the example) it is unfortunately simply not possible to fulfill this.

**Comment by MegaArthur** [comment]
Wouldn't it make sense to just delete the nodes? They are duplicates after all, address data is preserved, just on another node

**Comment by westnordost** [comment]
StreetComplete cannot delete elements.

**Comment by MegaArthur** [comment]
Oh, I didn't know that. This complicates things.

**Comment by westnordost** [comment]
So the answer options would be:
- Yes, correct
- No, it is.... [       ]
- It is correct but at a (slightly) wrong position 
- It is correct but at a wrong position, and I see that at the correct position, there is already a housenumber displayed on the map (so, it is duplicate)

And maybe more edge cases. Two of the cases I mentioned are not possible to do in StreetComplete and on top of that, the last two would need to be treated differently but a use may overlook that there is already one visible close by. 

So,  regrettably, I think this is not eligible for this app
