### ISSUE TITLE
highway=pedestrian is valid tagging of some service roads

### ISSUE THREAD

**Issue by matkoniecz** [westnordost/StreetComplete#159]
There are sometimes very wide footways (street-sized ones) that very infrequently are used for service vehicles.

These may be tagged as highway=service, highway=footway, highway=pedestrian depending on many factors.

These objects frequently either have no names or names are untagged.

Following selection will change such highway=pedestrian way to highway=service.

AddRoadName quest -> other answers.. -> Not a proper street -> It is just a service road

I think that in such cases this selection should merely hide the quest for user without changing highway key.

**Comment by westnordost** [comment]
Hmm, that sounds very specific. No pedestrian street would come to my mind that fits this description. 
Anyway, we could also not create street name quests at all for pedestrian ways to solve this.

On 27 April 2017 15:20:34 CEST, Mateusz Konieczny <notifications@github.com> wrote:
>There are sometimes very wide footways (street-sized ones) that very
>infrequently are used for service vehicles.
>
>These may be tagged as highway=service, highway=footway,
>highway=pedestrian depending on many factors.
>
>These objects frequently either have no names or names are untagged.
>
>Following selection will change such highway=pedestrian way to
>highway=service.
>
>AddRoadName quest -> other answers.. -> Not a proper street -> It is
>just a service road
>
>I think that in such cases this selection should merely hide the quest
>for user without changing highway key.
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/westnordost/StreetComplete/issues/159

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by matkoniecz** [comment]
> Anyway, we could also not create street name quests at all for pedestrian ways to solve this.

It may be the correct solution - but maybe this happens because my tagging style is not standard. 

For reference, most that encountered were similar to https://www.google.pl/maps/@50.0782317,19.8849402,3a,75y,49.06h,87.08t/data=!3m7!1e1!3m5!1soMLfSkA9xhRtHz5IVM4-7w!2e0!6s%2F%2Fgeo1.ggpht.com%2Fcbk%3Fpanoid%3DoMLfSkA9xhRtHz5IVM4-7w%26output%3Dthumbnail%26cb_client%3Dmaps_sv.tactile.gps%26thumb%3D2%26w%3D203%26h%3D100%26yaw%3D52.802795%26pitch%3D0%26thumbfov%3D100!7i13312!8i6656

![selection_001](https://cloud.githubusercontent.com/assets/899988/26302163/a3f4d73e-3ee3-11e7-8cdc-3f606dd58777.png)

(traffic sign forbidding access for vehicles is not present at the photo, but it is there nowadays)

**Comment by matkoniecz** [comment]
Or https://www.google.com/maps/@50.0645438,19.9448607,3a,75y,259.84h,106.12t/data=!3m6!1e1!3m4!1skxsTLQcKX7MtQfF_dhOhxQ!2e0!7i13312!8i6656

![selection_002](https://cloud.githubusercontent.com/assets/899988/26302298/0e25fef8-3ee4-11e7-8663-c680432e3473.png)

https://www.openstreetmap.org/?mlat=50.06457&mlon=19.94407#map=19/50.06457/19.94407

**Comment by westnordost** [comment]
Hmm, difficult. I would *probably* tag these as footway and include width=3m (+surface=asphalt). Is the wiki any clear about these cases?

**Comment by matkoniecz** [comment]
http://wiki.openstreetmap.org/wiki/Talk:Tag:highway%3Dpedestrian#footway_vs_pedestrian https://help.openstreetmap.org/questions/2750/pedestrian-vs-footway has some attempts at clarification  that IMHO make highway=pedestrian a valid tagging in this situation

**Comment by westnordost** [comment]
Hmm anyway, I think we deviated from the issue here.

If the way tagged as pedestrian has no name, one can answer "It has no name", if it is not a proper street but a service road, one can answer "it is not a proper street but a service road".

**Comment by westnordost** [comment]
So, closing it.
