### ISSUE TITLE
Add Italy to the "Tactile paving on crossings" country list.

### ISSUE THREAD

**Issue by Mannivu** [westnordost/StreetComplete#1590]
Some italian cities have tactile paving near crossings. See [this crossing](https://www.google.com/maps/@45.5543776,9.6192922,3a,75y,24.35h,46.09t/data=!3m6!1e1!3m4!1sUEfhuS7ufhBGvf0LrL73xw!2e0!7i16384!8i8192) for exemple. I think Italy shouldn't be on the whitelist for the crossings.

**Comment by matkoniecz** [comment]
See #750 - around 6% of crossings in Italy with tagged tactile paving status were marked as `tactile_paving=yes`

Now it is

http://overpass-turbo.eu/s/MN2 - 292 with `=yes`
http://overpass-turbo.eu/s/MN3 5080 with `=no`

292/(5080+292) = 5%

Do you disagree with "not the same answer over and over again " threshold for displaying quest (94% with answer "no" was considered to be below that threshold)?

Or do you think that more that 5% of crossing in Italy have tactile paving?

**Comment by Mannivu** [comment]
No, I think Italy is far below the 5% threshold.
