### ISSUE TITLE
On-site warning should take into account recent locations

### ISSUE THREAD

**Issue by waldyrious** [westnordost/StreetComplete#1591]
I often use StreetComplete when traveling as a passenger on cars and buses, and tend to get the "Are you sure you checked this on-site?" warning quite a lot, e.g. whenever it takes me more than a couple seconds to fill up the quest answer details and the vehicle moves away from the spot meanwhile.

IMO I should not get such a warning if my position has been near that location in the past few minutes.

**Comment by rugk** [comment]
Actually, maybe just save the position, when you _open_/"start" the quest and then compare it to this one. :smile: 

…instead of the current one.

**Comment by HolgerJeromin** [comment]
Open and close positions should be used to compare. 
open quest => oh, i am too far away to really see the reality stuff => walk towards => press OK.

**Comment by westnordost** [comment]
Fair enough, I'll implement it as @rugk suggested.
