### ISSUE TITLE
To-Do/Planning for discovery

### ISSUE THREAD

**Issue by hypervtechnics** [westnordost/StreetComplete#1592]
**Use case**
User has multiple quests at specific locations he wants to answer by a survey. Bike or walking would be the approach for survey. The user needs an optimal route to visit all quests. This should be dynamic. User should answer the quests and get a new route. E.g. when he can look into a street and answer all the quests without needing to follow in there. Also follow-up questions should be shown preventive.

**Proposed Solution**
1. Make the user able to mark quests as todo.
2. Continuously create a route to optimally visit each quests location and after answering one show follow-up questions and calculate a new route.

**Comment by matkoniecz** [comment]
Note that routing is not trivial to solve, adding such functionality would require very significant work - comparable to all work done so far.

What kind of problem are you trying to solve? Are you in a place with very limited quest count?

**Comment by hypervtechnics** [comment]
I know that this is very much work. Maybe it is possible to use some existing logic like matrix route calculation from ORS.

I am having some individual quests in several areas which require survey as I can't answer them by heart. Now I keep forgetting them if I come through these areas. Some are also a bit "offroad". With this feature I'd visit an area for some time and answer all questions by going/driving around.

The todo list and an export as gpx would be a good start as you may import the GPX into OsmAnd. I don't know if they offer a good usable API to integrate into StreetComplete.

**Comment by westnordost** [comment]
Sorry, I don't really see this feature as part of StreetComplete. Too much effort for a very specific use case.
