### ISSUE TITLE
v0.4 carries wrong version info

### ISSUE THREAD

**Issue by IzzySoft** [westnordost/StreetComplete#16]
Just a note: v0.4 and v0.3 have the same versionCode, which causes some trouble on updates:

    package: name='de.westnordost.streetcomplete' versionCode='1' versionName='0.3' platformBuildVersionName=''
    package: name='de.westnordost.streetcomplete' versionCode='1' versionName='0.4' platformBuildVersionName=''

Could you please check to increase versionCode with each new release? :smiley_cat: Thanks!

**Comment by westnordost** [comment]
Oh? Something must gone wrong there, I definitely increased the version. Will look into it

**Comment by westnordost** [comment]
From where do you read this information? When I unpack the APK and look into the AndroidManifest.xml, I read 0.4

**Comment by IzzySoft** [comment]
@westnordost Please read again the lines with code-markup: **`versionCode='1'`** for both versions. You need to increase that as well.

**Comment by IzzySoft** [comment]
Agreed, thanks!
