### ISSUE TITLE
Action icons disappear suddenly

### ISSUE THREAD

**Issue by mathieumd** [westnordost/StreetComplete#160]
I was hoping that app-debug-no-vao.apk from #130 would be a fix, but it doest help on my problem.

The action icons disappear suddenly after the tiles are displayed. Going into the about menu and going back briefly displays icons again, but they disappear again quickly. See this animated gif:
![ezgif-3-f2d4f6196b](https://cloud.githubusercontent.com/assets/2104679/25499042/70cd82dc-2b8a-11e7-881d-e0798416112b.gif)

StreetComplete version 0.7 / Galaxy Nexus with Android 4.3

**Comment by gilloud** [comment]
Reproduced also with android 4.4 ans streetcomplete 0.7

**Comment by westnordost** [comment]
Is it reproducable with version 0.8?

**Comment by westnordost** [comment]
Ping

**Comment by mathieumd** [comment]
Sorry for the delay.
Yes, with 0.8 the icons are shown correctly, thank you!
But... now, it's the tiles wich are not shown at all. I have the grey background, the blue "you are here" circle with the smartphone orientation, but not a single map tile. Maybe it's a temporary problem with Mapzen? (but [their website](https://mapzen.com/projects/vector-tiles/) seems to work well)

**Comment by hjanetzek** [comment]
@mathieumd the map tiles is a new issue with android 4.x, https and mapzen servers. We'll work on that. 
For now there is a build without https tiles: https://github.com/westnordost/StreetComplete/issues/175#issuecomment-299632589

**Comment by westnordost** [comment]
Perfect, so this bug is solved
