### ISSUE TITLE
Add description to shed to clarify for Dutch users

### ISSUE THREAD

**Issue by Sjord** [westnordost/StreetComplete#1602]
In Dutch, "schuur" can mean barn or shed. It would be nice if the "shed" building type would have a description that indicates what kind of "schuur" it is.

The value for quest_buildingType_shed_description could be:

> "Een gebouwtje voor opslag van tuinmateriaal, fietsen en gereedschap"

[BuildingTypes.kt](/westnordost/StreetComplete/blob/master/app/src/main/java/de/westnordost/streetcomplete/quests/building_type/BuildingTypes.kt) would need to be changed to use the `quest_buildingType_shed_description`. Is this possible without providing a description for all supported languages?

**Comment by westnordost** [comment]
But the icon is pretty clear already, isn't it?

**Comment by Sjord** [comment]
I guess the icon's pretty clear, especially compared to the barn icon. However, it's missing a sense of scale. Is this a small building with a normal-sized door, or a big barn with a big gate? Adding a doorknob or a window may give a better hint at size:

![shed](https://user-images.githubusercontent.com/113030/66741042-e3faeb00-ee74-11e9-873c-d4ad72f23988.png)

In another application, a shed is called a "Schuurtje" (little shed) and a barn is called a "Schuur". I don't really like this, since I would call a shed a "schuur" normally.

Maybe this isn't really an important issue and am I the only one with this problem. I ended up hesitantly tagging buildings as sheds in StreetComplete, but then went back in OpenStreetMap to check whether I used the right kind of "schuur".

**Comment by westnordost** [comment]
Maybe the easiest solution would be if you translated shed to "schuur (X)" while X is a very short clarification of what it is, or a synonym i.e. "schuurtje", or "for tools etc", "in the garden" or something like that.

**Comment by westnordost** [comment]
So, please rather change the translation of the name of "shed" in the Dutch translation. Adding a new string for the description would mean that for every other language, a mostly useless description would need to be added.
You can change the translation here:  https://poeditor.com/projects/view?id=97843
