### ISSUE TITLE
Ignore escalators for the path surface quest

### ISSUE THREAD

**Issue by ferdinand0101** [westnordost/StreetComplete#1604]
Escalator are usually directly next to steps which leads to false tagging

Ignore steps with the convey tag

**Comment by matkoniecz** [comment]
What is wrong with answering that surface is metal?

**Comment by ferdinand0101** [comment]
1. Yes it's pointless and due to escalors and stairs being usually close together you can not see which is which and that will lead to incorrect tagging

**Comment by sdicke** [comment]
A solution would be not to ask which surface the path has, but to ask something like „Which surface has this escalator?“ and for lifts „Which surface has this lift?“.

**Comment by ferdinand0101** [comment]
Well as matkoniez already mentioned escalators only have surface metal
But I agree on the elevator thing

**Comment by westnordost** [comment]
Good suggestion, I shall remove paths with the convey-tag from the overpass query.

**Comment by peternewman** [comment]
> Well as matkoniez already mentioned escalators only have surface metal

Pedant (although this particular one has gone):
https://londonist.com/2013/09/londons-undergrounds-last-wooden-escalator-to-be-removed

There are also Google hits for Macy's, I don't know if that one has gone too.
