### ISSUE TITLE
Update Gradle when contributing as suggested by Android Studio? Add info to docs?

### ISSUE THREAD

**Issue by xuiqzy** [westnordost/StreetComplete#1605]
Should Gradle be updated as suggested when first starting Android Studio with the cloned project?

After opening it and clicking update, the following parts have changed:
```
git diff

diff --git a/build.gradle b/build.gradle
index e44073a7..b9e92525 100644
--- a/build.gradle
+++ b/build.gradle
@@ -5,7 +5,7 @@ buildscript {
         jcenter()
     }
     dependencies {
-        classpath 'com.android.tools.build:gradle:3.3.0'
+        classpath 'com.android.tools.build:gradle:3.5.1'
         classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
     }
 }
diff --git a/gradle/wrapper/gradle-wrapper.properties b/gradle/wrapper/gradle-wrapper.properties
index 4c8cbc0e..467c0815 100644
--- a/gradle/wrapper/gradle-wrapper.properties
+++ b/gradle/wrapper/gradle-wrapper.properties
@@ -1,6 +1,6 @@
-#Tue Jan 15 20:28:35 CET 2019
+#Wed Oct 16 13:33:57 CEST 2019
 distributionBase=GRADLE_USER_HOME
 distributionPath=wrapper/dists
 zipStoreBase=GRADLE_USER_HOME
 zipStorePath=wrapper/dists
-distributionUrl=https\://services.gradle.org/distributions/gradle-4.10.1-all.zip
+distributionUrl=https\://services.gradle.org/distributions/gradle-5.4.1-all.zip
```

Should this not be done when contributing with other code or always or sometimes?
I personally am not that knowledgeable in Android development and thought it would only apply to programs used by the IDE and not the project itself, but then saw it in the git diffs.

Maybe one could add something in the documentation regarding this?

**Comment by typebrook** [comment]
> Should this not be done when contributing
> thought it would only apply to programs used by the IDE and not the project itself, but then saw it in the git diffs.

An Android project (git repo) should includes gradle settings, but you **should not** include it into your contributes unless it is related to gradle updates or etc (like #668 did)

Also, I recommand you **not** to let Android Studio automatically update gradle settings when you trying to make a PR. Make sure the setting consistent with upstream is important

**Comment by westnordost** [comment]
Additionally to what @typebrook wrote:

`gradle` is the build tools for Android. Android Studio is quite pushy regarding always updating the build tools to the latest version. This is why I turned off this automatic suggestion and thus didn't update the build tools for a while now.

If after updating the gradle version to the latest one, the app still compiles, the tests and androidTests can be run, there is no reason to not update the gradle version. So if you want, you can create a PR updating the gradle version and this will be your first contribution to the project, then :-)

**Comment by xuiqzy** [comment]
Thanks for the explanation!
I looked in the gradle tasks in the menu on the right in Android Studio but found no `androidTests` there but multiple `test` and `testSthElse in Streetcomplete subfolder and in app  subfolder.
Which should be run?
Also if some tests currently fail (I believe that is the case for both `test` tasks I found) without updating gradle, should I create an issue for that if I can't fix it myself?

**Comment by westnordost** [comment]
`test` is for unit tests that do not have dependencies on Android and thus are executed on the local machine, `androidTest` is for tests that are executed on the smartphone (or emulator).
If the tests that fail are `*IntegrationTest`, don't bother, I am going to delete or comment them out anyway. These tests are much too flaky, and slow.

![image](https://user-images.githubusercontent.com/4661658/67514851-ce1fce00-f69d-11e9-8c23-01e4798e00ba.png)

**Comment by rugk** [comment]
Maybe that's useful information for the contributing doc?
https://github.com/westnordost/StreetComplete/blob/master/CONTRIBUTING.md

**Comment by westnordost** [comment]
No, because this is standard for Android projects.
