### ISSUE TITLE
add more diet options

### ISSUE THREAD

**Issue by ferdinand0101** [westnordost/StreetComplete#1614]
I know this is simelar to #639 
but I would suggest forcing the user to activate the keys they care about.
Because as someone who is lactose intollerant I care and look ouf for lactose free places which means I notice them more
I'd assume that the smae also goes for other diets as documentet here
https://wiki.openstreetmap.org/wiki/Key:diet

Affected tag(s) to be modified/added: https://wiki.openstreetmap.org/wiki/Key:diet
Question asked: Thos this place serve lactose free(halal,kosher. ... ) food ?

Checklist for quest suggestions (see guidelines):
- [ ] 🚧 To be added tag is established and has a useful purpose
For many people with dietary restrictions it can be hard to find a restaurant
- [ ] 🤔 Any answer the user can give must have an equivalent tagging (Quest should not reappear to other users when solved by one)
yes clear tags exsist (allthough some are obvious like a vegan place is gonna be lactosefree)
- [ ] 🐿️ Easily answerable by everyone from the outside but a survey is necessary 
not by everyone.
This is why only "affected" people should awnser
- [ ] 💤 Not an overwhelming percentage of elements have the same answer (No spam)
~ while most places do not have those options the affected people are going to be in places where it's more common
- [ ] 🕓 Applies to a reasonable number of elements (Worth the effort)
Yes all restaurants cafes fastfood

for lactose free_people look for restaurants which do not have the lactose free or vegan tag

**Element selection:** 
for lactose_free if this is accepted I would also write the other ones
```
[out:json];
(
 nwr["amenity"="restaurant"]["diet:vegan"!="yes"]["diet:vegan"!="only"]
[!"diet:lactose_free"]
({{bbox}});
 nwr["amenity"="cafe"]["diet:vegan"!="yes"]["diet:vegan"!="only"]
[!"diet:lactose_free"]
({{bbox}});
 nwr["amenity"="fast_food"]["diet:vegan"!="yes"]["diet:vegan"!="only"]
[!"diet:lactose_free"]
({{bbox}});
);
out center;
>;
out skel qt;
```
**Proposed Metadate:**

no country meta data because user should select it

**Proposed GUI:**
just like the vegetraian or vegan quest

**Comment by westnordost** [comment]
Other than vegan and vegetarian, other diet types are not really in use yet, see https://taginfo.openstreetmap.org/search?q=diet

Additionally, while most people will have a relatively clear idea what is vegetarian/vegan or not, what is halal or kosher is nothing anyone would know and is something that very likely has to be advertised on the shop, in other words, it's specialist knowledge.

So because of these reasons, it's will not fix for now.
