### ISSUE TITLE
Feature Request: Show overflow quest points as dot at some zoom levels

### ISSUE THREAD

**Issue by pkoby** [westnordost/StreetComplete#1615]
**Use case**
When I am walking to work, I want to hit areas with a lot of unanswered quests. As it stands, it is hard to find a route with a lot of quests while at a low(ish) zoom level for a good overview. Say I have a choice of walking around a block. One direction has a lot of houses with unanswered level and roof quests, the other direction is all answered. If I zoom out to view the block and adjacent areas, one or two missed quests will show as densely as a whole row of quests.

In this example, it is hard to tell whether 10th St or 10th Avenue has more quests available, or how many there might be.
![image](https://user-images.githubusercontent.com/7786285/67340175-d390e300-f4fa-11e9-88f7-fe95321c142a.png)

Zoom in a little more on 10th Ave; still hard to tell if this is a good choice.:
![image](https://user-images.githubusercontent.com/7786285/67340467-8103f680-f4fb-11e9-93af-ccf9c2fbdd8a.png)

Finally, at full zoom we can see that there are a lot of quests!
![image](https://user-images.githubusercontent.com/7786285/67340485-8bbe8b80-f4fb-11e9-9ccc-a786f57f0eaa.png)
 
**Proposed Solution**
At some zoom levels (i.e. not city or neighborhood level, but perhaps block and street level), where there are quests that are hidden because of collision/overlap, show some tiny icon to show that there is a quest there.

Now it's obvious that the north side of 10th Ave is a good goal.
![image](https://user-images.githubusercontent.com/7786285/67340598-d213ea80-f4fb-11e9-8516-60d0a99c07a7.png)

And now we can see 10th St has nothing going for it at all.
![image](https://user-images.githubusercontent.com/7786285/67340618-e22bca00-f4fb-11e9-85e9-593107c3a4c7.png)

The icons could be smaller, and I would definitely suggest layering them beneath the main icon layer (so some dots would be hidden behind the big point icons). Also, this layer should not be selectable.

Also, I understand there might be a UI/UX issue with users not understanding what the layer represents. But in practice (not just screenshots), I think it might be more clear: as you zoom in, small points appear, and as you zoom farther, some of them pop into a large icon.

I could also see this as being useful for motivation: if a user sees many points as possible options, it can seem like a good goal. For me, I like to clear the map. Sometimes there is one point left in a block, but at higher zoom levels, that block looks the same as a very dense one.

**Comment by westnordost** [comment]
Would be nice, but as far as I know, it is not possible. Maybe what would be possible would be to _always_ show these points and _additionally_ the quest pin if there is enough space.
Would this work too?

**Comment by pkoby** [comment]
That would be fine with me. My thought about that was that it might be difficult to design a point that would be hidden by the big pin. Perhaps if the small points were quite small and just a bit vertically offset, the big pin would cover it suitably. (Or very small Xs? So the pin point lands on the center of the x?) 

I assume you would still have two layers? One for small points, showing all at all times, and one for the big pins working as usual? If there are two layers, could the small points be hidden when zoomed out? I don't think it would be helpful to show all points for a whole city at once.

**Comment by westnordost** [comment]
Yes, it would be possible to show the dots only at a later zoom level.

**Comment by pkoby** [comment]
I threw together some possible ideas:
![image](https://user-images.githubusercontent.com/7786285/67433607-6a6ea580-f5b6-11e9-98d3-a32a543e51d1.png)

I'm partial to the orange dots. The color is based off of the loading bar/location locked icon.

**Comment by westnordost** [comment]
Interesting. I already implemented it. It looks like this currently. The image can be exchanged easily, it is in `app\src\main\assets\map_theme\images\quest_dot@2x.png`. Maybe you'd like to experiment with other graphics.

Note that there is also the dark mode. A black X or + will be very difficult to see. This is why the color of the quest pin doesn't change in dark mode.
Just round solid dot, regardless of the color, may be confused for a map feature of the background map (f.e. a bollard). This is why the quest pin has a shadow and no element on the map has a shadow.

![device-2019-10-23-233339](https://user-images.githubusercontent.com/4661658/67435984-a6712d00-f5ed-11e9-8dc2-79f395fa8744.png)
![device-2019-10-23-233320](https://user-images.githubusercontent.com/4661658/67435985-a6712d00-f5ed-11e9-868b-a3d9de9ff1fd.png)
![device-2019-10-23-233410](https://user-images.githubusercontent.com/4661658/67435986-a6712d00-f5ed-11e9-90e3-e04e1ddade99.png)

**Comment by pkoby** [comment]
Wow, that was quick! I think this is looking good, but I fear that at this size, the dots look a little bit too much like a selectable icon. Also, the overlap of many close points is maybe not clearer than no points. I might give it a go with playing around with size/color if I can remember how to use Android Studio.

**Comment by pkoby** [comment]
Viewing it on a desktop is deceptive. I looked at your screenshots on my phone, and you're right, the dots don't seem crazy large. And I suppose areas that look super dense would be good places to visit and clean up!

**Comment by westnordost** [comment]
> Wow, that was quick! 

Yeah I realized that the idea is very cool and the effort is really rather low. It also solves the problem some people have that want to see quests at higher zoom levels already to know if it is worth cycling/going there.

From the screenshots above, I now further changed now:
- moved dots a px up, so one doesn't see them behind the pin anymore
- show dots one zoom level (13) before quest pins, so one can see where there are quests
- dots collide with each other and pins from zoom level 13-16, starting with zoom level 17, all are shown. So, a heap of dots like in the 2nd screenshot is never shown

**Comment by Katzenstreu** [comment]
A additionally idea is: a slider on the screen for the size of all quests or a slider for the count of the small dots.

I like the idea of seeing all possible solvable quests. Then it's a more exiting game.

**Comment by Katzenstreu** [comment]
Thanks @westnordost for beta 15! But there are too less pins in my case:

"In this area I'm seeing only one quest (house number) but no small white dots/pins. If I zoom-in, see second sscreenshot, there are a lot of quests. Why here are no pins?

![1](https://user-images.githubusercontent.com/1107883/68055133-4450b000-fcf0-11e9-9c2a-957d89b372cc.png)

![2](https://user-images.githubusercontent.com/1107883/68055139-461a7380-fcf0-11e9-8427-9f65d47b075d.png)

**Comment by pkoby** [comment]
Thanks for the update; I was so looking forward to seeing it working!

I do agree that at some zoom levels the map seems a little empty, but I assume that's due to the collisions? Perhaps the small dot always shows up underneath a big quest pin, and thus the dot collides away all nearby dots.

I had one small idea: the dots look a little weird offset from the actual location (to hide them behind the big pin). Perhaps the bottom of the dot could be a point of the same angle as the big pins. Then the dots would point to their actual location, look like a tiny version of the big pins (to associate the two), and still hide perfectly.

**Comment by westnordost** [comment]
As said, the dots still collide with the pins. Only starting at zoom level 17, all dots are shown no matter what.

> Perhaps the bottom of the dot could be a point of the same angle as the big pins. 

Yeah, tried that, didn't look good.

**Comment by Katzenstreu** [comment]
What about another idea?

Do you know heatmaps? See attachment. If there are many quests for one area, or the same element, the pins get bigger. Or the color of the pins is changing similar to heatmaps. https://www.patrick-wied.at/static/heatmapjs
![front](https://user-images.githubusercontent.com/1107883/68069047-8fec7380-fd5b-11e9-88ec-50b430da9c69.png)
![Heatmap](https://user-images.githubusercontent.com/1107883/68069058-b01c3280-fd5b-11e9-9305-a0ee74143495.png)

**Comment by westnordost** [comment]
Well, this is not possible with tangram-es

**Comment by matkoniecz** [comment]
It turned out to be extremely useful for finding places crowded with quests! It turns out that were some alternatives routes of my trips across city that were never taken* judging by number of quests that were still available. It ended more useful than I expected.

*at least not on trips where I was able to solve some SC quests

@pkoby Thanks for the idea! @westnordost Thanks for the implementation!

**Comment by Echolon** [comment]
@pkoby Wow, you just formulated what I had in mind for months! THANKS!

@westnordost THANKS for implementing this! :heart:
