### ISSUE TITLE
Clearer house numbers please

### ISSUE THREAD

**Issue by johnwhelan** [westnordost/StreetComplete#162]
When walking in sunlight viewing the house numbers on the screen is not easy even with the screen brightness turned up to full and fully zoomed in.

**Comment by escoand** [comment]
And also at more zoom levels. ATM you have to zoom really near to see them. I normally won't zoom so near.

**Comment by johnwhelan** [comment]
Just to clarify this applies to building outlines where the house number is tagged on the building outline.

**Comment by westnordost** [comment]
This was duplicated by #271
