### ISSUE TITLE
reduce quest icon size / more quests on screen

### ISSUE THREAD

**Issue by Katzenstreu** [westnordost/StreetComplete#1623]
Hi,

I love this app and like to help our community. I'm looking on the map for areas in which are many quests.

The quest icons are big. So I can see only very few quests on my screen. If I want to check if this area has a lot of quests I have to zoom in heavy. But I want to view many quests as overview.

Could we add a slider? So every person can filter themselves how many quests they want to see. The quest icon size can change in relation to the count of the quests (more quests > smaller icons).

Best regards
Tim

**Comment by westnordost** [comment]
How about this? https://github.com/westnordost/StreetComplete/issues/1615#issuecomment-545646291

**Comment by Katzenstreu** [comment]
Cool! That's similar.
The idea with the slider could be an extra feature.

When we will see, or may beta testing, the new function with the small dzts? I would like to "tidy up" the whole map in my area 👍.

**Comment by westnordost** [comment]
I plan to release a new beta version today. I usually give beta versions a week until I release them for everyone.

Though, regarding this ticket, apart from the things I already did, which seem to solve the use case that you mentioned in your first post, this will be a will not fix. I want to keep the number of UI on the map and the number of options in the settings to a minimum.
