### ISSUE TITLE
Better grouping of changes

### ISSUE THREAD

**Issue by 67192048** [westnordost/StreetComplete#1625]
### Use case
Currently, changes are grouped depending on the quest. However, this sometimes leads to lots of related quests/changesets that could be grouped together (eg. added parking type + add wether there is parking fee) in the openstreetmap history, which creates a kind of bloat.

### Proposed solution
The colors of the icons seem to group the quests into categories (eg. Green = services, Orange = restaurants/shops, Blue = pedestrians etc) that might be useful for grouping the changes, depending on the distance between them and the category of the quest.

The changeset comment could then either be a description of the group (eg. Added info about parkings) or (probably better) a description of all the changes. OsmAnd by default creates something like "update 2 restaurants, 1 shop in [place name]". Something similar could be done for StreetComplete.

### Implementation
It would be even better if the grouping level was customizable in the settings and if there was an option to enter a custom comment on upload. For example, a user might want to choose to group all changes together and then enter a comment once they upload them.

Proposed grouping levels : by quest (current), by quest category (proposed default), group all.

**Comment by westnordost** [comment]
Could you describe more your use case? I.e., why would you want to have the changesets grouped at all? And why would it be helpful to you if the changesets were grouped by color (= area of interest) preferentially to other aspects?

**Comment by 67192048** [comment]
It's mostly for the comfort of other OSM users. Sometimes the history in a certain place is full of StreetComplete changes and it gets difficult to find/review other changes. It also makes it harder to revert/edit them if it was a mistake.

The grouping doesn't have to be by color, it just seemed to me that the colors created consistent groups (anything other way is fine too, as long as the edits are relevant to each other).

The ability to add custom changeset messages can also be helpful for explaining changes that can seem strange, and for all the reasons listed in https://wiki.openstreetmap.org/wiki/Good_changeset_comments . I have had a few of my changes reverted because they were not explained properly.

**Comment by westnordost** [comment]
The question is perhaps, what things in a StreetComplete changesets would you want to review? Mistagging things is out, adding weird or virtual (Pokemon) things to the map is out. Vandalism perhaps? But what else?

How the changesets should best be grouped depends on what people would want to review.

**Comment by thibaultmol** [comment]
I agree the arguments on both sides of this issue. So not sure what the right decision is either.
But a sidenote: something I'd like to see is the ability to select which groups I would like to upload.
My reasoning for wanting to do this for example is when you've changed 20 of a certain quest, 10 of another question and one of another quest.
In that situation I will only want to upload those 20 and 10 changes.
(Because I know that I'll get more of that third Quest in the near future and thus upload one big change)

**Comment by matkoniecz** [comment]
> Because I know that I'll get more of that third Quest in the near future and thus upload one big change

Note that in case of uploading new quest after other from the same group it will join the same changeset, so it is not necessary to manage this manually.

**Comment by thibaultmol** [comment]
Wait, I think we're not on the same page. Let me try and rephrase it:
So in this example I do these quests on day 1
20 quest 1
10 quest 2
1 quest 3
and these quests on day 2:
10 quest 3

So I would want to wait with upload the 'quest 3' data till day 2 so they're grouped together.

(and this way avoiding to spam the history of a location with small changesets)

**Comment by HolgerJeromin** [comment]
No one knows if the app is going to be opened in the future (or if the phone breaks after day 1). 
Conflict handling would be much more complicated (more often needed). 
There are many/some quests which unlocks other quests...

**Comment by westnordost** [comment]
No feedback from op
