### ISSUE TITLE
Task shown in Italy even if country is whitelisted

### ISSUE THREAD

**Issue by Mannivu** [westnordost/StreetComplete#1629]
I've noticed that the task asking if a crossing has some tactile pavement is being shown on crossing in Italy even if Italy has been whitelisted for that task (see the screenshots)
!["Mai mostrato in Italia" means "Never shown in Italy"](https://i.imgur.com/313Zgrb.png)![](https://i.imgur.com/SHKLdjH.png)

_Inviato dal mio MI 8 usando [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by westnordost** [comment]
Could you tell me a GPS position at which I should be able to reproduce this?

**Comment by westnordost** [comment]
Also, which version of the app is this? Is this the v15.0-beta1 or v14?

**Comment by westnordost** [comment]
In Naples, I cannot reproduce this. On download, this is logged
```
QuestDownload: AddTactilePavingCrosswalk: Skipped because it is disabled for this country
```

**Comment by Mannivu** [comment]
The position is Via Alessandro Manzoni, Lurano
Posizione: geo:45.566303,9.642301?z=19
https://osmand.net/go?lat=45.566303&lon=9.642301&z=19

I use v14.1

**Comment by westnordost** [comment]
Hmm, I can't reproduce it there

**Comment by westnordost** [comment]
Could it be that you solved another quest at the same location and then the tactile quest popped up after you solved that other quest?

**Comment by westnordost** [comment]
Got it. The reason why I never noticed it before (old bug), is that one needs to solve and upload a quest whose follow-up quest is a quest that is disabled in the country one is in.
