### ISSUE TITLE
Building type quest not loaded

### ISSUE THREAD

**Issue by Discostu36** [westnordost/StreetComplete#1631]
In an area in my hometown that has many buildings with `building=yes`, the building type quest is not loaded.

**How to Reproduce**
- Make sure that the building type quest is activated in the options.
- Then move the map to [this location](https://www.openstreetmap.org/#map=19/54.32475/10.11148)

**Versions affected**
15.0-beta1 on Android 9

**Comment by matkoniecz** [comment]
Are more important (earlier in the list) quests loaded? Additional quests are loaded automatically when number of available ones is low.

**Comment by Discostu36** [comment]
No, no quests at all
![Screenshot_20191109-094307_StreetComplete](https://user-images.githubusercontent.com/30999326/68525780-68eeee00-02d5-11ea-91ac-b3150f23a09e.jpg)

**Comment by Discostu36** [comment]
Is there a filter on buildings with `fixme`-tag? Because all of these have got one by the original mapper ("finetune exaxt position")

**Comment by pkoby** [comment]
I've recently run into a similar issue. Here's what I think is going on for me, maybe it applies here.

Apparently, Overpass-API maxes out at 2000 features per query (or something like that). It orders the features by ID #, so older features, having lower ID #s, show up first. For the area I'm in, there are a _lot_ of building-type quests, probably more than 2000 (depends on the bounding box), so the areas with the newest additions of buildings aren't showing up as quests.

So I would check if the area you're in has a lot of unanswered quests nearby, especially if those buildings are newer than the surrounding (I see they're over 5 years old, but maybe everything else is older).

**Comment by matkoniecz** [comment]
>  2000 features per query

Exactly

```
AddBuildingType: Starting
AddBuildingType: Not adding a quest at 54.323450650000005, 10.13092175 because there is a note at that position
AddBuildingType: Not adding a quest at 54.32329274382503, 10.130743571901705 because there is a note at that position
AddBuildingType: Added 1998 new and removed 0 already resolved quests. (Total: 1998) in 13s
```

AddBuildingLevels quest is also hitting this limit, maybe also some other ones.

> So I would check if the area you're in has a lot of unanswered quests nearby

And lower left corner of this area is at https://www.openstreetmap.org/way/24933288#map=15/54.3065/10.0837 with upper left at https://www.openstreetmap.org/way/18813489#map=14/54.3391/10.1513

Within that area there is more than 2000 elements for building level quest

2000 element limit is a deliberate limit used by SC to ensure that app will not suffer from severe performance issues due to huge quest count.

Things that can be changed:
- reducing area size - would introduce problem of wifi scan fetching only nearby quests
- increasing limit - may result in performance problems on loading huge quest counts

**Comment by Discostu36** [comment]
Thanks for the feedback, interesting to know. BTW, the area above now has building types, I added them with Vespucci.

**Comment by Discostu36** [comment]
Wouldn't it be possible to SC to load quests first that are nearest to my GPS location and go further and further away until the limit is reached?

**Comment by westnordost** [comment]
No, the overpass query queries a rectangle (bounding box). It is not possible to control the order in which they come in, as far as I know.

**Comment by Discostu36** [comment]
Consecutive loading of increasing rectangles? OK, I guess this might break the Overpass limit.
