### ISSUE TITLE
Benches with partial backrests

### ISSUE THREAD

**Issue by peternewman** [westnordost/StreetComplete#1633]
The bench type quest that was added after #484 , doesn't have the ability to mark a bench with partial backrest, such as most of these:
https://www.furnitubes.com/street-furniture/railroad-delta-straight-curved-seating

I realise this is probably mostly an OSM question. There are currently 20 "partial" values, miniscule compared to yes and no, but the highest value that isn't just a variant of yes/no.

**How to Reproduce**
Try and answer the quest for a bench with partial backrest.

**Versions affected**
15.0-beta1, Android 9

I guess this could technically be an enhancement too...

CC @rugk

**Comment by rugk** [comment]
Uhm interesting observation (and thanks for pining me).

Yeah, the real world is not as binary as we sometimes think (:wink:), but unfortunately OSM currently specifies it like that:
https://wiki.openstreetmap.org/wiki/Key:backrest -> yes/no

So:
1. should not we start with the OSM "spec"/wiki first to make this a "valid" tagging value?
2. or what else is your proposed solution here?

**Comment by peternewman** [comment]
> Yeah, the real world is not as binary as we sometimes think (wink), but unfortunately OSM currently specifies it like that:
> https://wiki.openstreetmap.org/wiki/Key:backrest -> yes/no

True, although TagInfo shows some people already using partial:
https://taginfo.openstreetmap.org/keys/?key=backrest#values

Although a few more who can't use the same capitalisation on yes or who go for Y...

> So:
> 
>     1. should not we start with the OSM "spec"/wiki first to make this a "valid" tagging value?

Probably, I don't really know how that whole process works. Certainly there are some quests that can't be correctly answered currently.

>     2. or what else is your proposed solution here?

It varies along the way? :laughing:

**Comment by matkoniecz** [comment]
> This key is used in combination with amenity=bench to signify whether the bench has a backrest to lean against or not. 

https://wiki.openstreetmap.org/wiki/Key:backrest

I would say that bench that has backrest in at least part of it has backrest, so it would be `backrest=yes`

But it may be worth discussing at tagging mailing list.

**Comment by HolgerJeromin** [comment]
> I would say that bench that has backrest in at least part of it has backrest, so it would be backrest=yes

Correct. If you need a backrest hopefully you will be allowed to use this part of the bench. 

Perhaps tune the text a bit? 
Otherwise we still have the "leave note" option.

**Comment by peternewman** [comment]
> Correct. If you need a backrest hopefully you will be allowed to use this part of the bench.

It just seems a shame if we're going to the effort of collecting the info not to collect the most accurate info we can, given the changes to StreetComplete would be fairly trivial.

**Comment by westnordost** [comment]
The changes to StreetComplete would be trivial, but please post on the tagging mailing list first whether there should be a backrest=partial or not, then it can be added to the wiki and finally to this app.

**Comment by westnordost** [comment]
Closing for no feedback and this is not the place to establish new tags.

**Comment by peternewman** [comment]
Okay @westnordost I'll try and take it up with the tagging team first.
