### ISSUE TITLE
Text disappear in dark mode

### ISSUE THREAD

**Issue by ahangarha** [westnordost/StreetComplete#1634]
Texts disappear in dark mode. I guess texr follow theme but the background doesnt.

![](https://i.imgur.com/PRYqjp2.png) 

App Version: 14.1 (fdroid)
Android Version: 8.1.0

**Comment by westnordost** [comment]
Can you attach a screenshot? What is your Android version and device?

**Comment by westnordost** [comment]
I didn't notice that you already attached a screenshot. Additionally to the Android version, can you say whether this is reproducible if you restart the app? Also, does this only occur in a note discussion or for any quest?

**Comment by ahangarha** [comment]
> I didn't notice that you already attached a screenshot. Additionally to the Android version, can you say whether this is reproducible if you restart the app? Also, does this only occur in a note discussion or for any quest?

Android Version: 8.1.0

**Comment by westnordost** [comment]
This is Farsi, right? Perhaps it is a problem wit the right-to-left-layout - i.e. that there is no night-version for the right-to-left-speechbubbles, I will check.

Any other problem you encounter with the right-to-left layout, by the way? Anything seems to be on the wrong side?

**Comment by westnordost** [comment]
Jup, that was the problem. Fixed it!

**Comment by ahangarha** [comment]
> This is Farsi, right? Perhaps it is a problem wit the right-to-left-layout - i.e. that there is no night-version for the right-to-left-speechbubbles, I will check.
> 
> Any other problem you encounter with the right-to-left layout, by the way? Anything seems to be on the wrong side?

I haven't noticed any RTL issue in the app so far. If I see any, I will share for sure

Tnx for the app and your quick fix
