### ISSUE TITLE
Four digit star count goes behind upload count when it "pings"

### ISSUE THREAD

**Issue by peternewman** [westnordost/StreetComplete#1635]
This is a low priority "nit" bug.

**How to Reproduce**
If you've got four digits of star count (possibly only on a small screen), when it "pings" as it increments (gets bigger, then reverts to normal), it disappears behind a box which I assume is part of the upload count display.

**Versions affected**
15.0-beta1, Android 9

I think moving the upload count to the right a bit would solve the issue.

**Comment by matkoniecz** [comment]
For start - congratulations for triggering this kind of a bug!

**Comment by peternewman** [comment]
> For start - congratulations for triggering this kind of a bug!

I'm sure lots of people are well ahead of me. Or perhaps I'm just the only person using it in my local area. I do find a lot of segments of paths/roads broken up when it often seems they don't need to be, which does add to the tally quickly, for not much work.

**Comment by peternewman** [comment]
Thanks @westnordost !

**Comment by peternewman** [comment]
@westnordost this still happens on v19.0 although it now gets cropped on the right by an invisible box. Would you mind reopening this. I appreciate its not a high priority to fix, but it does still exist.

**Comment by westnordost** [comment]
No, I just fixed it already again

**Comment by peternewman** [comment]
Ah I see via https://github.com/westnordost/StreetComplete/commit/62ce3f99a1fcc7baa768ca8fd8b626a1241b0185 and #1808

**Comment by peternewman** [comment]
@westnordost this is still doing it on v19.1. I'm on a [Sony Xperia XZ1 Compact](https://www.sony.co.uk/electronics/smartphones/xperia-xz1-compact/specifications) which has a fairly small screen (also apparently 1,280 x 720) if that's part of the issue?

It disappears behind an invisible crop on the right hand side still.

**Comment by westnordost** [comment]
Okay, well I can't really reproduce this issue anymore. The text field has more than enough padding to allow a scale of 1.6x (the size to which it animates) to be in its bounds, plus I even add a " " to the start and end so the text field is larger than it needs to be.
I also tested it on an emulator, but wouldn't know how a real device would act any different.

**Comment by peternewman** [comment]
> Okay, well I can't really reproduce this issue anymore. The text field has more than enough padding to allow a scale of 1.6x (the size to which it animates) to be in its bounds, plus I even add a " " to the start and end so the text field is larger than it needs to be.
> I also tested it on an emulator, but wouldn't know how a real device would act any different.

I can try and get a screen capture, or run a test program or something if you'd like?
