### ISSUE TITLE
Ask for the type of crossing for crossing=island

### ISSUE THREAD

**Issue by westnordost** [westnordost/StreetComplete#1637]
### General
For 
```
highway=crossing
crossing=island
```
the app should ask again what type of crossing this crossing is, also for values like `crossing=island;unmarked` and similar, because whether an `island` has an island or not is orthogonal to whether it is marked, unmarked or with traffic lights.

A new tag called [`crossing:island`](https://wiki.openstreetmap.org/wiki/Key:crossing:island) has been approved. On answering the crossing type quest, the app would tag `crossing:island=yes` if it has previously been tagged with `crossing=island` additionally to tagging the user's answer.

`crossing=island` is currently tagged on 40k+ crossings.

**Comment by matkoniecz** [comment]
> also for values like crossing=island;unmarked and similar, because whether an island has an island or not is orthogonal to whether it is marked, unmarked or with traffic lights.

`crossing=island;unmarked` sounds like something that can be fixed into `crossing=unmarked` + `crossing:island=yes` by a validator. Or is there reason to suspect that data quality in such cases is low and everything except "this is a crossing with an island" should be thrown away?

Also, is it supposed to be a new quest or modification of existing crossing quest? 

First one seems better as user would be able to create note with "no, this crossing has no island" in case of wrong data (also, would be simpler to implement).

**Comment by westnordost** [comment]
I thought about modification. Just ask the question also if `crossing=island` and tag the answer accordingly.
