### ISSUE TITLE
Immediately open next quest for same element

### ISSUE THREAD

**Issue by westnordost** [westnordost/StreetComplete#164]
If there are several quests at the same position for the same element, the form for the next quest could slide right in (from right) after answering the first one. So, the user saves one click and has the impression as if he is going through wizard kind of dialog.

**Comment by CloCkWeRX** [comment]
+1 Doing building levels somewhere I may not visit again can be a bit annoying, as I wont complete the roof quests. Very useful for "I sit down in a business and answer multiple questions in a row" use case

**Comment by westnordost** [comment]
Your use case won't work as you imagine it to because roof quests are only **created** for buildings that do have levels already. So, you won't see a roof level quest for a building after setting the levels.

**Comment by rugk** [comment]
> So, you won't see a roof level quest for a building after setting the levels.

Can't you change that? I mean, if it always happens this way, just automatically add a roof quest when a levels quest has been answered.

**Comment by rugk** [comment]
Ah just saw that this issue is actually https://github.com/westnordost/StreetComplete/issues/221.

**Comment by westnordost** [comment]
That was more work than imagined. I almost decided not to do it because it was not worth it.

**Comment by riQQ** [comment]
For anyone finding this via search:
this was removed again in 25dcafd6c7c9c985dca06d7a6e81519d0a759621. 
Reason for removing it:
https://github.com/streetcomplete/StreetComplete/issues/2710#issuecomment-812444576

Could possibly implemented again if people like the way it's implemented:
https://github.com/streetcomplete/StreetComplete/issues/2710#issuecomment-890559783

**Comment by mnalis** [comment]
And for those wanting to try out how it works in practice, they can try in [SCEE](https://wiki.openstreetmap.org/wiki/SCEE) (StreetComplete _"Expert edition"_ fork), which has preferences in `Settings` / `UI` to enable/disable that behaviour:

![ResizedImage_2024-09-11_00-30-35_1609](https://github.com/user-attachments/assets/7453dfa2-8b57-4c6b-8e47-dda0396a5548)

I personally usually find it very useful, but sometimes very annoying :smile:
