### ISSUE TITLE
Tiles don't load when zoom

### ISSUE THREAD

**Issue by Yanux56** [westnordost/StreetComplete#1640]
When I start the app, map tiles doesn't appear. 
If I unzoom to the min zoom, map appear, but then when I zoom on, some tiles loads, other not. 
If I zoom at max to my position (Vannes, France), no map tiles loads. 

**How to Reproduce**
Try to zoom a lot on Vannes, France

**Versions affected**
Android 9PKQ1.190302.001
Xiaomi MI 9T (or K20) with MIUI 11.0.1 stable
street complete 15.0

Thanks a lot ! 

![Screenshot_2019-11-12-13-58-01-071_de westnordost streetcomplete](https://user-images.githubusercontent.com/37863459/68675334-f04b9400-0557-11ea-8a3f-51348f18b18b.jpg)
![Screenshot_2019-11-12-13-59-45-653_de westnordost streetcomplete](https://user-images.githubusercontent.com/37863459/68675336-f04b9400-0557-11ea-9e79-ab34c7b11994.jpg)

**Comment by Akasch** [comment]
I will look into it, something with an update seems to have gone wrong.

Am 12. November 2019 14:23:56 MEZ schrieb Yanux56 <notifications@github.com>:

**Comment by Akasch** [comment]
The missing database upgrade is running now. Unfortunately it will take some hours to be completely finished.

**Comment by Yanux56** [comment]
Ok, thanks ! I will wait for next playstore update :)

**Comment by Akasch** [comment]
It will be fixed without an update of the app, it is "only" the web server generating the tiles having a problem with its Database. So it will start to work again later today or early tomorrow morning.

**Comment by Yanux56** [comment]
ok cool !

**Comment by westnordost** [comment]
Thank you, @Akasch , for your continued support and administration of that tileserver! :-)

**Comment by jtracey** [comment]
Is the db still updating, or did another problem occur? Because I'm still experiencing this (in Ontario).

**Comment by Akasch** [comment]
The second server used for tiles was updated today and some other problems have occurred.  I will fix them later today once I have a little time.

Am 14. November 2019 18:06:10 MEZ schrieb Justin Tracey <notifications@github.com>:

**Comment by jtracey** [comment]
Seems to be fixed now :)

**Comment by Akasch** [comment]
All tiles should work again. If something is still broken please tell me.

On a side note: The tiles for central Europe are, at the moment, at most some weeks old, I hope that I can update the data each two weeks for this region. (Visualization: [here](https://map-data.de/#map=4.125/46.810715693459535/10.005207877881945&style=cinnabar&show_server).)

**Comment by Yanux56** [comment]
It's working for me ! 
Thank you very much :)

**Comment by Navigator-oss** [comment]
Hi,
It still doesn't seem to work.
If you zoom on Lille, France, several tiles are still missing.

**Comment by Akasch** [comment]
@Navigator-oss should also work again, somehow I had stopped this server manually due to some confusion, thanks for the message.

**Comment by Navigator-oss** [comment]
Everything is working as expected now, thank you !
