### ISSUE TITLE
Config only Quest handling 

### ISSUE THREAD

**Issue by HolgerJeromin** [westnordost/StreetComplete#165]
Perhaps it would be possible to have a generic quest infrastructure so (most) quest are defined only with a (JSON?) config file with linked images. 

With this everyone can add own quests similar to the way vespucci and josm handles tag Presets.

**Comment by westnordost** [comment]
This is a duplicate of #98

**Comment by HolgerJeromin** [comment]
Adding a configuration file is imo a different thing compared to a full app which act as a plug in.
