### ISSUE TITLE
AddTactilePavingCrosswalk quest broken

### ISSUE THREAD

**Issue by peternewman** [westnordost/StreetComplete#1652]
It's no longer possible to solve the AddTactilePavingCrosswalk quest. This was also present in the beta release.

It did used to work in an earlier version a few months ago.

**How to Reproduce**
Try and solve the AddTactilePavingCrosswalk quest, for example for this node:
https://www.openstreetmap.org/node/5719792211

**Versions affected**
SC 15, Android 9

https://github.com/westnordost/StreetComplete/blob/3cc12c72bff056c715e64dff43589a30cd703eb0/app/src/main/java/de/westnordost/streetcomplete/quests/tactile_paving/AddTactilePavingCrosswalk.kt#L23-L25
versus
https://github.com/westnordost/StreetComplete/blob/3cc12c72bff056c715e64dff43589a30cd703eb0/app/src/main/java/de/westnordost/streetcomplete/quests/tactile_paving/TactilePavingForm.kt#L10

Smells a bit funny to me, but I've not traced an actual bug in the code.

**Comment by westnordost** [comment]
The cited code is fine. What exactly does not work?

**Comment by peternewman** [comment]
> The cited code is fine. What exactly does not work?

The map doesn't get updated and the quest doesn't vanish when completed. Please feel free to try for yourself, the answer for that specific node is yes.

> (Also, what is it that smells funny in your opinion?)

Just the applyAnswer/applyAnswerTo, I couldn't trace the code where the form calls the backend, but I've probably just failed to trace it properly. I think I found other examples where it was applyAnswer in the backend too.

**Comment by westnordost** [comment]
I can't reproduce this, also not for the given node. Right now, the quest is not even displayed for that node because there is a note on it. But for the crossing just North of the roundabout, any answer I give works fine.

Can you reproduce this for any other place or other quest?

**Comment by peternewman** [comment]
> I can't reproduce this, also not for the given node. Right now, the quest is not even displayed for that node because there is a note on it.

Strange, the note isn't actually on that node as such, but probably on top of it, I do see the quest still, presumably because I don't see the note because it's mine.

> But for the crossing just North of the roundabout, any answer I give works fine.

Neither yes nor no works for me. It shows the orange ring around the upload count but the completed count doesn't increment and the quest doesn't go away either.

> Can you reproduce this for any other place or other quest?
The bus stop shelter just North of that crossing North of the roundabout works fine (I undid it after).

I think other quests work that I can think of, off hand it's only the crossing one that doesn't seem to work.

I've just disabled all quests apart from those found in this GitHub search (which look likely to be most similar):
https://github.com/westnordost/StreetComplete/search?p=1&q=SimpleOverpassQuestType%3CBoolean%3E&unscoped_q=SimpleOverpassQuestType%3CBoolean%3E

I've now gone to a random part of the country I've not visited or StreetComplete'd before and tried some of them. These all work okay:
AddTrafficSignalsButton: yes
AddTrafficSignalsButton: no
AddBabyChangingTable: yes
AddBabyChangingTable: no
AddBikeParkingCover: yes
AddBikeParkingCover: no
AddTactilePavingBusStop: yes
AddTactilePavingBusStop: no

Curiously these are working up there:
AddTactilePavingCrosswalk: yes
AddTactilePavingCrosswalk: no

So it seems it's some interaction with having visited the area before and/or tried to solve that quest and undone it or something.

I've tried invalidating my quest cache, what else can I try to debug it?

**Comment by westnordost** [comment]
> Curiously these are working up there:
> AddTactilePavingCrosswalk: yes
> AddTactilePavingCrosswalk: no

What do you mean, "up there"?

I think it might have something to do with the note being there.
What'd help me most at this point if you supplied a log from the time where the app tries to upload your answer. Could you send me the log?

**Comment by westnordost** [comment]
Also, what happens if you turn off auto-sync and then solve the quest? Is the quest then gone from the map until you hit the upload-button?

**Comment by peternewman** [comment]
> > Curiously these are working up there:
> > AddTactilePavingCrosswalk: yes
> > AddTactilePavingCrosswalk: no
> 
> What do you mean, "up there"?

Sorry, in Newcastle in the North of England, the area I've not used StreetComplete in and that I  arbitrarily chose to try and test the system.

> I think it might have something to do with the note being there.
It was broken before I added the note.

> What'd help me most at this point if you supplied a log from the time where the app tries to upload your answer. Could you send me the log?
So invalidating the quest cache seems to have fixed it (I'm not sure if I'd also restarted the software after I tried that unsuccessfully earlier), but for the future is there an explanation of how to gather logs? Would it be worth adding to the issue template? Does it need Android Studio installed?

> Also, what happens if you turn off auto-sync and then solve the quest? Is the quest then gone from the map until you hit the upload-button?

As mentioned it's now fixed itself. If it comes back I'll be sure to test that and report back.

**Comment by westnordost** [comment]
> but for the future is there an explanation of how to gather logs? Would it be worth adding to the issue template? Does it need Android Studio installed?

From my point of view, the easiest way is to have Android Studio installed and connect your phone via USB. Because I already have it installed. Not sure if there is an easier way for non-developers. To avoid Android Studio, one could instead only download the `adb` (android debug bridge) console application and then after connecting the phone via USB, get the logs via this application. Android Studio does the same.
If you have root on your phone, I think there should be a couple of apps on F-Droid (one of them is CatLog) that allows you to view all the logs.

> As mentioned it's now fixed itself. If it comes back I'll be sure to test that and report back.

Yes, please do. There must still be a bug lurking around there.
