### ISSUE TITLE
Sending some wrong or incomplete info about bus stops back to OSM?

### ISSUE THREAD

**Issue by forteller** [westnordost/StreetComplete#1657]
I'm very far from an expert on how OSM works in the backend, so apologies if this is not an issue. But I thought I should mention it, just in case.

I just found a service that can give you a list of issues on elements that were last modified by you. I noticed that there where [a lot of issues](https://osmose.openstreetmap.fr/en/byuser/forteller?username=forteller&item=2140) on my name connected to bus stops. I've only ever edited bus stops trough StreetComplete.

The issues says:

> Specify if it is a stop (platform) or a location on the road (stop_position)

Does this tell you anything? Is there anything that should be changed in SC to avoid this?

As I said, I don't know, just wanted to let you know.

Thanks!

**How to Reproduce**
1. Edit a bus stop in SC
2. See that the change has generated an issue on https://osmose.openstreetmap.fr/en/byuser/[your username]

**Versions affected**
All?

**Comment by sdicke** [comment]
That is not related with StreetComplete. Osmose obviously just count problems with elements a user edited, independent of the kind of edit.

**Comment by matkoniecz** [comment]
In this case 

- https://www.openstreetmap.org/node/6372880015 is perfectly fine, `highway=bus_stop` is sufficient to indicate "Specify if it is a stop". This error wants to add also a duplicate tagging scheme and may be safely ignored. I opened https://github.com/osm-fr/osmose-backend/issues/698 requesting removal this specific warning.

- @sdicke is right, your edit only modified objects where Osmose was complaining already and it was not making situation worse ( https://www.openstreetmap.org/node/6372880015/history )

**Comment by forteller** [comment]
Thank you so much for your kind replies, and for taking the issue to the correct instance! This was a nice experience :)
