### ISSUE TITLE
"Is there a pavement along this street?" and "Is there a cycleway here?" quest interfaces poorly readable in the night mode

### ISSUE THREAD

**Issue by matkoniecz** [westnordost/StreetComplete#1662]
**Use case**
Readable interface is better.

**Proposed Solution**
White or whitish alternative version for the dark mode.

**Comment by matkoniecz** [comment]
Was probably made worse by https://github.com/westnordost/StreetComplete/commit/06c0e54964b64cd8a952fc6fa353d362ed8eea87#diff-cc8f1789f12e020fb96a805d35845ce4

**Comment by westnordost** [comment]
Or a version with inverted colors
