### ISSUE TITLE
Auto switch of theme does not update icons

### ISSUE THREAD

**Issue by HolgerJeromin** [westnordost/StreetComplete#1666]
Theme set to auto. Use it with dark mode.
Reopen app later when bright is active.

Map is switched to new color, but quest icons remain dark and are therefor "invisible". 
Reopening app fixes it.

**Versions affected**

Latest play store version
Motorola g7 power with Android 9

**Comment by westnordost** [comment]
What quest icons?

**Comment by HolgerJeromin** [comment]
I think all of them. I have surface and building= quests here

**Comment by matkoniecz** [comment]
Quest icons (markers displayed on the map) are not changing at all between day and night mode. See #1361 where proposal to change them was wontfixed.

What kind if icon is problematic and invisible?

**Comment by HolgerJeromin** [comment]
Oh. You are right. 
The bubbles were completely filled black/dark.

**Comment by matkoniecz** [comment]
Possibly related: friend reported that descriptions are sometimes missing in the night mode. So far I was unable to reproduce this (though I want some icons problematic in the nigh mode, see my series of opened issues).

![photo_2019-11-20_06-28-50](https://user-images.githubusercontent.com/899988/69490479-eba4ab00-0e88-11ea-93d3-dac38e0eb395.jpg)

**Comment by westnordost** [comment]
Well that's fixed here https://github.com/westnordost/StreetComplete/commit/0e91964f48ee7df0da0b5025c45a8b657a5ceab9

**Comment by westnordost** [comment]
Which bubbles were completely filled black? You mean, the bubble background was black but the text as well, much like in @matkoniecz screenshot only the other way round?

**Comment by matkoniecz** [comment]
So https://github.com/westnordost/StreetComplete/commit/0e91964f48ee7df0da0b5025c45a8b657a5ceab9 fix may have affect not only in RTL languages?

**Comment by westnordost** [comment]
Mhh, I don't remember

**Comment by HolgerJeromin** [comment]
> Which bubbles were completely filled black?

All quest bubbles were filled black with no icons visible. 
I saw it for a few seconds, activated none of them, but reopened the app which fixed the rendering.
I was not able to reproduce the issue in the last days. So perhaps it is save to close it.
