### ISSUE TITLE
New Quest: What is the mount-type of this streetlamp?

### ISSUE THREAD

**Issue by DeusFigendi** [westnordost/StreetComplete#1667]
Sometimes I walk along a street and because #streetcomplete has no cool quests for me I try to add stuff with #vespucci. [Streetlamps for example](https://www.openstreetmap.org/changeset/77387744#map=19/52.02936/8.76188&layers=H) but often I'm too lazy to add details or (more often) I forgot the exact correct keys/values and don't want to look them up using a phone.

But such a question could be answered pretty easy with StreetComplete and I think it is pretty common, that a `highway=streetlamp` has no `lamp_mount` key.
Examples:
* [1316 streetlamps without mount in Manchester](https://overpass-turbo.eu/s/Oo0) (not a single one with mount defined)
* [84 in Tilburg NL](https://overpass-turbo.eu/s/Oo1) (none with mount)
* [2076 in Stuttgart](https://overpass-turbo.eu/s/Oo2) (none with mount)
* [314 in Düsseldorf](https://overpass-turbo.eu/s/Oo4) (11249 with mount defined)
* [696 in and around Philadelphia (New Jersey)(https://overpass-turbo.eu/s/Oo7) (45 with mount)

So I think it's worth to do this quest, most streetlamps seems to have no `lamp_mount` defined but there are a lot of streetlamps around, which are mapped.

So this is the overpass query I used, but I am not very familiar with that language I think there is a more elegant way with "intersection"

````
(
  // query part for: “highway=street_lamp”
  node["highway"="street_lamp"]({{bbox}});
  - node["lamp_mount"]({{bbox}});
);
````

[This is the wiki page where lamp_mount is defined](https://wiki.openstreetmap.org/wiki/Key:lamp_mount) there are five common values:

* `bent_mast`
* `high_mast`
* `straight_mast`
* `suspended` and
* `wall`

[additional there are some more values common for this key](https://taginfo.openstreetmap.org/keys/lamp_mount#values) and one might consider to ask the user in this quest if a streetlamp taged with `lamp_mount=straight mast` might be a `lamp_mount=straight_mast` (to unify `wall` and `ẁall mounted` and `wall mount`; `straight_mast` and `straight mast` and `mast` and `pole` and `streight_mast` and `Mast` and `straightmast`… now you know why I am usually not tagging this with vespucci)

I'd use pictograms/cliparts of the lamp-mount types instead of text or photos.
I am willing to draw those if this issue is accepted.

Here is a mokup (okay well drawing those cliparts might be challenging ^^)

![rect1831](https://user-images.githubusercontent.com/1711504/69484782-9f7d4a80-0e37-11ea-9534-ad4d51ec1878.png)

**Comment by westnordost** [comment]
Did you read the [quest guidelines](https://github.com/westnordost/StreetComplete/wiki/Adding-new-Quests-to-StreetComplete)?

Particularly, I don't see this fulfilled:

> 🤷 Useful purpose: Especially for tags that are not that well established yet - they should have some application. As by the design of OpenStreetMap, there are countless things that could be collected, such as the color of the cycleway, the brightness of street lamps, etc. and sometimes things like these are even documented on the wiki (because it is a wiki, obviously). That does not mean that it makes sense to collect this information (in this app).

**Comment by DeusFigendi** [comment]
> Did you read the quest guidelines?

Yep

> Particularly, I don't see this fulfilled:

I see, indeed I also wasn't sure on this point. That's why I checked if the key is common enough or "well established" and I thought with 100k nodes it is.

If you think this isn't "usefull" enough just close the issue. So next time me (or someone else) has this idea I/he/she will find it in the closed issues.

**Comment by westnordost** [comment]
Ok
