### ISSUE TITLE
Ask for aeroway=runway surface

### ISSUE THREAD

**Issue by matkoniecz** [westnordost/StreetComplete#1669]
### General
Affected tag(s) to be modified/added: [surface](https://wiki.openstreetmap.org/wiki/Key:surface)
Question asked: **What is the surface of this runway?**

### Checklist
Checklist for quest suggestions (see guidelines):
- [x] 🚧 To be added tag is established and has a useful purpose - `surface=grass` and similar indicates a small, less important surface. It was mentioned as one of ways to handle problems of deciding when airport icon should be displayed, as small airports and large airports have drastically different importance. Though note that using runway surface for rating airport importance requires matching different objects, and I am not aware of anyone actually using this data at this moment. This issue was triggered by https://josm.openstreetmap.de/ticket/15107#comment:9
- [x] 🤔 Any answer the user can give must have an equivalent tagging (Quest should not reappear to other users when solved by one)
- [ ] 🐿️ Easily answerable by everyone from the outside but a survey is necessary - here I am not 100% certain, but in my limited experience it is possible to see runway of a typical airport
- [x] 💤 Not an overwhelming percentage of elements have the same answer - see https://taginfo.openstreetmap.org/tags/aeroway=runway#combinations
- [x] 🕓 Applies to a reasonable number of elements (Worth the effort) - around 25k elements https://taginfo.openstreetmap.org/tags/aeroway=runway#combinations

### Ideas for implementation
Reuse surface GUI, should be fairly simple to DO

**Element selection:** https://overpass-turbo.eu/s/OsQ

**Metadata needed:** No

**Proposed GUI:** Reuse surface GUI

**Comment by HolgerJeromin** [comment]
Would this be better as a maproulette task?
Most of the surface (grass, asphalt/concrete) should be visible from aerial images. 
The 200 meter distance from Streetcomplete could be a problem here. 
And the matching of the runway to the correct osm way. Think about a small airport with a grass beneath a asphalt runway. You are not allowed to access the runway by foot. 
Is a SC user (500 meter away) sure he tag the correct runway if only one runway is missing the `surface` tag?

**Comment by westnordost** [comment]
Good idea, but @HolgerJeromin has a point. The features are usually so large, it should be visible from above. Also, most runways, even unimportant ones, will have asphalt or concrete anyway. The better way to decide if the icon should be shown or not is to calculate the total area covered by the feature (as with any feature).

**Comment by ferdinand0101** [comment]
I belive that the biggest problem is that while it is interesing and meight be often enough the case there are 0 pilots who (are allowed to) use OSM and as such basically no one will have use for it

**Comment by matkoniecz** [comment]
>  Most of the surface (grass, asphalt/concrete) should be visible from aerial images.

Paved vs grass is visible, and maybe this is the main part of the useful info. I hesitated to tag `surface=paved` because I was unsure about exact surface type, but on the second thought this is of an extremely minor importance. Closing per this.

> Also, most runways, even unimportant ones, will have asphalt or concrete anyway.

Note that there at least some airports of nearly zero importance that are quite large. Here grassy runways are an useful indicator.

> The better way to decide if the icon should be shown or not is to calculate the total area covered by the feature (as with any feature).

This part is sadly also tricky sometimes, as some minor aeroclub airports take huge area that is not directly used. See for example https://www.openstreetmap.org/way/218821049#map=16/50.0878/20.2024 https://pl.wikipedia.org/wiki/Lotnisko_Krak%C3%B3w-Pobiednik_Wielki#/media/Plik:Krakow-Pobiednik_Airfield_(ICAO-_EPKP)_view_from_N,_Pobiednik_Wielki_village,_Krak%C3%B3w_County,_Lesser_Poland_Voivodeship,_Poland.jpg

> I belive that the biggest problem is that while it is interesing and meight be often enough the case there are 0 pilots who (are allowed to) use OSM and as such basically no one will have use for it

See usecase mentioned in the initial post. It is certainly NOT about professional aviation maps.
