### ISSUE TITLE
Symbols don't show up or flicker

### ISSUE THREAD

**Issue by qoheniac** [westnordost/StreetComplete#167]
I always have to touch the map somewhere I don't expect symbols to be to make the symbols visable and when I move the map the symbols disappear again. Sometimes this doesn't work and I see flickering symbols at best or no symbols at all regardless of what I am trying.

**Comment by westnordost** [comment]
Which version of STreetComplete are you using`?

**Comment by qoheniac** [comment]
0.7

**Comment by qoheniac** [comment]
on Android 4.4.2

**Comment by westnordost** [comment]
Okay, that is a known bug in 0.7 and has been fixed for 0.8. See https://github.com/westnordost/StreetComplete/issues/168#issuecomment-298256582
