### ISSUE TITLE
Priorities not respected

### ISSUE THREAD

**Issue by thymaro** [westnordost/StreetComplete#1670]
The ordering of the tasks is not respected by the app.

**How to Reproduce**
Go to settings and task selection.
Move a task up in the list
Refresh all tasks
The task still won't appear with higher priority than other tasks

**Specifically**
I am trying to get the app to ask me about house numbers. Instead, it asks me about number of stories, type of building and roof shape.
Addresses have a priority above the other three properties mentioned.

To circumvent the issue, I tried to completely deactivate roof shape, building type and number of floors. Then, the app starts asking me about house numbers, but only for buildings where I have already answered the other three questions. Must it really be this tedious to input house numbers? What do others do to get to the house number task any quicker? It's rainy out here, I don't have time for roof shapes...

**Versions affected**
Android 8.0.0 on SM-A520F
Streetcomplete 15.0

**Comment by matkoniecz** [comment]
>  Refresh all tasks

Is it possible that address quests appeared for buildings where you answered question about their type?

See #1119 "New building type quest doesn't seem to lead to housenumber quest" for explanation why it is happening this way

Are you willing to share location where you edit? And specific objects where new quests appeared that were previously missing?

>  Addresses have a priority above the other three properties mentioned.

To be 100% sure - can you open setting, quest selection and make sure that address quest is above roof shape and number of floors quests?

Note also that building type quest is asked for `building=yes` objects and address quest is not asked for `building=yes` objects.

**Comment by thymaro** [comment]
After reading #1119 I think I understand the house number quest is only activated after fulfilling another type of quest. I will put building type above house number and go out to check how it behaves. brb.

**Comment by matkoniecz** [comment]
To be more exact, to get address quest for `building=yes` following must happen:

- building type quest is answered and uploaded (or someone else makes such edit)
- building value is on list of "almost certainly has housenumber" (for example `building=house` is on it, `building=garage` is not)
- housenumber quest overpass query is made (note that waiting for automatic invalidation or invalidating quest cache manually may be necessary if this query was made already recently for this area)
- valid housenumber quest should now appear

**Comment by MegaArthur** [comment]
If there was a need, maybe a toggle to override quest ordering could be made? I would certainly use it to put building:levels above building type, as it is (to me) a much more useful thing to map

**Comment by matkoniecz** [comment]
You can put `building:levels` above `building` type, and it will be respected. But `building:levels` still will be not asked for `building:yes` as it makes sense to ask about it only for building types that typically have building levels.

**Comment by thymaro** [comment]
Alrighty. Went back out with deactivated quests "roof type" and "number of floors", active quests "building type" and "house number" and reset the cache.
After input of building type and waiting a few minutes, when I do a refresh on the tasks, then "house number" appears. Of course, it would be nice if "house number" would appear as fast after input of "building type" as "roof type" and "N floors", but I understand now that this is not possible due to some server side queries that are made.
Still, if it's possible to get "house number" to appear as soon as possible, instead of having to refresh the tasks in the area, that would be nice.

Also, that might be due to the quest cache (110MB in my case), but when I have all four activated (type, roof, floors, number) and have "building type" and "house number" as top priorities and both "roof type" and "number of floors" in some nondescript lower priority, __but also activated__, then "house number doesn't appear for buildings where I have input the other three attirbutes, even after a few minutes. Since many buildings in the vicinity still have all other three tasks open, it seems the cache is full and "house number" doesn't get loaded for the buildings where it should be available. I have to go and deactivate "roof type" and "number of floors" in the quest list to get back "house number", even though it is one of the top priorities.

**Comment by westnordost** [comment]
>Also, that might be due to the quest cache (110MB in my case)

There is actually no limit to the "quest cache". The cache in the settings is for the map tiles.

Note that your answers need to be uploaded first before any new quests can pop up. New quests are only downloaded automatically if most around your area are solved. You can force a download by clicking on the appropriate button ("scan for quests here").
