### ISSUE TITLE
Notifications in the way

### ISSUE THREAD

**Issue by call-me-matt** [westnordost/StreetComplete#1672]
Searching/downloading new tasks takes quite some time and during this period the notifications are often in the way. I think this could be improved, see attached picture.
![Screenshot_20191124-101409_StreetComplete](https://user-images.githubusercontent.com/34400929/69892509-7ca2d880-1306-11ea-8254-72f386c406ae.jpg)

**Comment by westnordost** [comment]
That toast is only shown for a few seconds or so, not during the whole download.

Am 30. November 2019 00:15:23 MEZ schrieb call-me-matt <notifications@github.com>:
>Searching/downloading new tasks takes quite some time and during this
>period the notifications are often in the way. I think this could be
>improved, see attached picture.
>![Screenshot_20191124-101409_StreetComplete](https://user-images.githubusercontent.com/34400929/69892509-7ca2d880-1306-11ea-8254-72f386c406ae.jpg)

**Comment by matkoniecz** [comment]
I may be less impacted because I typically load quest data at home (I even use modified version that downloads all quest types at once).

But very similar thing in Vespucci was quite irritating.

Is it likely that toast at the top would be less likely to block important things?

**Comment by call-me-matt** [comment]
On my phone the toasts keep on showing. Once its gone it appears right away as I move along the street. That's often enough to frustrate impatient people like me.
Would it be possible to make the toast disappear when clicking on it (tried that in the beginning), or is the toast an android widget which cannot be influenced?

**Comment by westnordost** [comment]
Hmm, if it keeps showing, I guess that means that in your area there are almost no quests left? If there are very few quests, the app immediately starts to download the next batch of quest types after downloading another batch of quest types (that yielded very few quests).

Yes, the toast is an android widget, replacing it with something that vanishes when clicking on it will not solve the problem because as you observed, it pops up again and again.

**Comment by call-me-matt** [comment]
I will keep an eye on it, but I would say that it happens independently from the amount of items in the area. Had the impression that there is something slowing down the download and making it start over again (and again). It happens very often on my phone, no matter where I am.

**Comment by westnordost** [comment]
I found a bug where the component that triggers the automatic download was triggered all the time (each time a new GPS location is detected). Fix will be released in the next major release.
