### ISSUE TITLE
quest markers versus zoom levels

### ISSUE THREAD

**Issue by heavygale** [westnordost/StreetComplete#168]
I just came back from a little bicycle tour on wich I solved about 200 quests - overall the app works very good, but of course there are some little things to improve.  One issue I had were the quest markers not showing up in high/low zoom levels. For example at a crossroad with a lot of very short street sections I needed to zoom in a lot as the markers didn't show up otherwise. Or if there's a very long street, the markers only shows up if I zoom far out, as it's displayed in the conter of the street. Therefore I need to zoom in and out several times to make sure I solves all quests and didn't miss one. 

Sometimes the marker only shows up on a spezific zoom level, see the following gif:
![secret-quest](https://cloud.githubusercontent.com/assets/5744732/25567790/d8635da0-2df5-11e7-8ddc-4132ead5565b.gif)

Maybe you could add a option to show all loaded quests in any zoom level, so I won't miss any of them. Escpecially as I mostly don't want to zoom in that much - my display has a high resolution. Or at least show the markes even if there's a other marker close to ist? I don't know how the current logic works.

(I am using version 0.7, wich is the latest Version according to F-Droid - should I rather install it form google play?)

**Comment by westnordost** [comment]
That not all quests were displayed was a bug in 0.7, it is fixed in 0.8.

The releases on F-Droid lag behind by approximately one week. So, either wait one week or go to the Google. Or, third option, get StreetComplete from the IzzyOnDroid F-Droid repository (linked from the Readme.md), the update is already available there.

**Comment by Hillside502** [comment]
F-Droid is perennially late with updates for **ANY** and **ALL** apps.

IMHO, F-Droid is a useful **directory** of Open Source apps --- but useless as a **repository**!
