### ISSUE TITLE
Tiles don't load when zoom

### ISSUE THREAD

**Issue by matkoniecz** [westnordost/StreetComplete#1682]
At least in southern Poland, tiles in Asia are appearing to work well

https://www.openstreetmap.org/way/542843971#map=15/49.6386/20.8776 
https://www.openstreetmap.org/#map=16/50.0358/19.9117

pinging @Akasch

**Comment by HolgerJeromin** [comment]
Same in Gütersloh, germany

**Comment by Akasch** [comment]
Server issues are now fixed

**Comment by HolgerJeromin** [comment]
Thanks. Working again!
