### ISSUE TITLE
"Is it restricted who may park here?" public wording

### ISSUE THREAD

**Issue by andrewharvey** [westnordost/StreetComplete#1685]
"Is it restricted who may park here?" is unclear.

I'd suggest to change "It is public (with or without fee)" to "It is open to the public (with or without fee)".

The current text to me implies is it public operated/owner, ie. [operator:type=public](https://wiki.openstreetmap.org/wiki/Key:operator:type) rather than is it open to the public `access=yes`.

Around me we have public car parks which are usually council owned and private car parks which are owned by companies, but this is `operator:type=` and shouldn't be confused with `access=`.

PS. I would be happy to make a PR, but searching I couldn't find where this is set (I could only find an old commit ref, not on master).

**Comment by MegaArthur** [comment]
I can quickly make a PR if westnordost approves

**Comment by matkoniecz** [comment]
> PS. I would be happy to make a PR, but searching I couldn't find where this is set (I could only find an old commit ref, not on master).

You can search in repo for `It is public (with or without fee)` (search box in the top-left) - https://github.com/westnordost/StreetComplete/search?q=It+is+public+%28with+or+without+fee%29&unscoped_q=It+is+public+%28with+or+without+fee%29

It should find /app/src/main/res/values/strings.xml https://github.com/westnordost/StreetComplete/blob/715e740ac70734a3cb8294c117d9fe60f857ebe5/app/src/main/res/values/strings.xml#L484

**Comment by andrewharvey** [comment]
Thanks @matkoniecz I did that originally but it only found it in an old commit, and when I switched to master it could no longer find it that file, but I tried again now and it works, so I must have been doing something wrong.

**Comment by westnordost** [comment]
Sure, a PR is welcome

**Comment by westnordost** [comment]
nvm, I will do it quickly myself
