### ISSUE TITLE
Expand leaf type quest to also include tree rows

### ISSUE THREAD

**Issue by ferdinand0101** [westnordost/StreetComplete#1688]
**Use case**
Same as leaf type for Forests/woods

**Proposed Solution**
Since there was already discussion on doing single trees which was rejected
This should be acceptable since tree rows are usually relatively big

**Comment by MegaArthur** [comment]
Sounds reasonable.

If westnordost approves, I can make a PR tomorrow evening.

The tree row length could also have to be abovw a certain threshold for the quest to be made.

**Comment by westnordost** [comment]
Yes, I approve! Sorry for not answering 

Am 3. Januar 2020 00:07:48 MEZ schrieb MegaArthur <notifications@github.com>:
>Sounds reasonable.
>
>If westnordost approves, I can make a PR tomorrow evening.
>
>The tree row length could also have to be abovw a certain threshold for
>the quest to be made.
