### ISSUE TITLE
On switching to dark mode, quests vanish

### ISSUE THREAD

**Issue by westnordost** [westnordost/StreetComplete#1689]
Have some quests displayed on the map. Go to the settings, switch to dark mode, go back. The quests are now gone.

**Comment by davidbaumann** [comment]
Can't reproduce this on Android 9. Switching back and forth, stopping and starting the app, also disabling the internet connection, and switching afterwards.

**Comment by westnordost** [comment]
Okay good to know. I tested it on an Android Lollipop.

**Comment by peternewman** [comment]
Whereas I can on Android 9 (1st Sept 2019 security patches) on a Sony Xperia. I've also had it happen at other times I think (as my light/dark is on auto) and have to relaunch the app to get the quests back.

**Comment by JeanFred** [comment]
I can reproduce on Android 8.0.0 (Oreo). I first noticed it a couple of days ago when it auto-switched after sunset, and like peternewman had to relaunch. Just reproduced it by changing in the settings.

**Comment by MegaArthur** [comment]
Can reproduce on android 9, on an AOSP-based custom ROM

**Comment by gmischler** [comment]
There are several threads about disappearing quests, but I'm not sure which one this is related to, so I'm just picking one...
I see quests disappear with no apparent reason during normal operation of the app.
It used to happen regularly (several times an hour) on a Huawei Y5 with Android 5.1, and now happens occasionally (once every few days) on a Xiaomi Mi A3 with Android One 9.
Usually (some) quests outside the current view keep hanging around. Zooming and moving around the view may eventually bring them back, but not always. In some cases I need to scan for quests again to bring them back.
I have not observed any correlation with locking/unlocking the phone or switching display modes.

All that probably doesn't make the picture much clearer... ;)

**Comment by westnordost** [comment]
Fixed this
