### ISSUE TITLE
split streets

### ISSUE THREAD

**Issue by heavygale** [westnordost/StreetComplete#169]
Maybe add a feature to split streets? (In this case at my current location)

![two street sections](https://cloud.githubusercontent.com/assets/5744732/25567872/5ef2cf80-2df7-11e7-91c2-36ae5ceaae7e.png)

Mapped as a single track, but sometimes it's not helpful to tag the whole track with the same road surface.

![unbenannt](https://cloud.githubusercontent.com/assets/5744732/25567928/1d23c0a4-2df8-11e7-83dd-6ac5801ac067.jpg)

**Comment by westnordost** [comment]
Mh, nice photos! Say, if you come across **paths** (cycleways, forest paths etc) that look like they could well fit for generic panorama images for paved/unpaved/ground, will you make photos for me? :-)

I see that this feature might make sense, but this app will not support advanced editing features (cutting geometry means that the app needs to be able to automatically fix up any relations that went through the way as well!) anytime soon.
The way to go in this case is to leave a note (press "Nicht beantwortbar") and describe the situation.

**Comment by heavygale** [comment]
It actually was a panorama image, but the oneplus panorama stitching is really bad (as you may spot in the left image). But sure, I can look out for some images (sorting out useless ones will be up to you) - are you particularly interested in panroama images like the following, or are you more in images like the ones you already added into the app for road surface?
![crossway](https://cloud.githubusercontent.com/assets/5744732/25568129/c0563ca8-2dfc-11e7-91b4-b84843cf1a18.png)

Sure, the app would need to split it up properly (preserving relations and stuff), but I think at least the UI could be kept simple - if you ever decide to implement such a feature.

**Comment by westnordost** [comment]
Wow, looks cool. Well, here is what I need:
https://github.com/westnordost/StreetComplete/issues/133#issuecomment-296363980
