### ISSUE TITLE
potential modification of wording (changeset comment)

### ISSUE THREAD

**Issue by sun-geo** [westnordost/StreetComplete#1691]
Regarding quest: "Are pedestrians prohibited from walking on this road here?"
Frage: (de) "Ist es Fußgängern verboten, hier auf dieser Straße zu gehen?"
StreetComplete:quest_type | AddProhibitedForPedestrians

https://wiki.openstreetmap.org/wiki/StreetComplete/Quests
source:
https://github.com/westnordost/StreetComplete/tree/master/app/src/main/java/de/westnordost/streetcomplete/quests/foot

Current quest changset comment: “Add whether roads are accessible for pedestrians”
(de: roughly translated) "Hinzugefügt, ob Strassen für Fussgänger zugänglich sind" 

**How to Reproduce**

Run the quest: "Are pedestrians prohibited from walking on this road here?"

**Versions affected**

Noticed for v11.0 & v15.0

**Proposal**

Change quest changset comment to new wording: “Add whether roads are **prohibited** for pedestrians”

**Comment by westnordost** [comment]
Right, that makes sense. Will do 

Am 3. Januar 2020 01:16:12 MEZ schrieb sun-geo <notifications@github.com>:

**Comment by sun-geo** [comment]
Ok, thanks - take your time...
