### ISSUE TITLE
New quest: Ask about smoking

### ISSUE THREAD

**Issue by hmartink** [westnordost/StreetComplete#1695]
When fixing up some errors I made in SC I noticed that I could enter in the Web UI (which I rarely use) if smoking was permitted in the public building (here: a youth hostel). 

Answering the Wiki Questions:
Existing element: I could enter it in the Web UI (already with a set of predefined answers)
Atomic: Yes, in the web UI this question has a fixed set of answers
Established: Present in Web UI
Effort vs. impact: At least I'm very happy that many areas are smoke free but was not very happy when discovering that in other countries people smoke, e.g. in restaurants. So if this is more often filled in, users could check in advance if and where smoking is permitted. Probably also valuable for smokers to find the best place to spend their time. The Effort is limited. Usually there is a big sign near the door which tells the rules, i.e. you either see it from outside or just within the reach of the door (little effort). So when mapping opening times this might come into view as well.
No unanswerable quests: There is a limited set of answers in the Web UI and maybe a "Other / leave note" is necessary as is in other quests, though I'm not sure this is necessary here. 
Users are no experts: The (no) smoking sign is well established
Easy answer: Yes, look at window near main door or near coat hook
Publicly accessible: Yes, otherwise this information would not work
No spam: while in some countries the rules are well established the details are still different, i.e. if you may smoke at the front door, in a separate room, nearwhere at all
Valuable Surveyors: When standing at the door for the opening times, I can often see this as well. And if I don't like this tag, I can configure it out in SC

About openstreetmap tags I'm rather clueless - I mainly use SC. The UI could be similar to other selections, probably with (localized) text for the various options, though.

**Comment by ENT8R** [comment]
Duplicate of #539

**Comment by hmartink** [comment]
Sorry, I missed this. Unfortunately, there doesn't seem to be any conclusion on this,maybe my points can be taken into account as well.

**Comment by westnordost** [comment]
@hmartink Perhaps you can add to #539 what you think is missing there and close this ticket.

**Comment by hmartink** [comment]
Done
