### ISSUE TITLE
StreetComplete no longer builds from source due to missing/required keystore.propertires

### ISSUE THREAD

**Issue by gdt** [westnordost/StreetComplete#17]
In 9239f1d9, a reference to keystore.properties was added, but of course not the file.   I get an error building (up-to-date Android Studio).   I'm sure I could work around this, but it seems like the sources in github should by default allow building/installing unsigned apks for people to test/debug.  If it's easy to make a signed release if keystore.properties is present and just build if not, that would be great.

**Comment by westnordost** [comment]
Ah, okay. Yes, that makes sense.
I will need to research how to do that first. If you know a solution, let me know. I do not have time until Sunday evening.

El 24 de febrero de 2017 16:33:15 CET, Greg Troxel <notifications@github.com> escribió:
>In 9239f1d9, a reference to keystore.properties was added, but of
>course not the file.   I get an error building (up-to-date Android
>Studio).   I'm sure I could work around this, but it seems like the
>sources in github should by default allow building/installing unsigned
>apks for people to test/debug.  If it's easy to make a signed release
>if keystore.properties is present and just build if not, that would be
>great.
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/westnordost/StreetComplete/issues/17

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by westnordost** [comment]
Does it work now for you?

**Comment by gdt** [comment]
Yes, it works.  I updated and did a build/install to device and it just worked.  Thanks for fixing.
