### ISSUE TITLE
Limit the amount of scrolling

### ISSUE THREAD

**Issue by gjedeer** [westnordost/StreetComplete#170]
I have added some road features using this app and have a suggestion for a small improvement that would make this process much faster.

When I click "paved", the road types window should scroll all the way up so I can see all the choices.

When I choose Asphalt, it should take me to the end of the form, so I can approve my changes without scrolling. or display a floating OK button.

This way I can add the road type with 4 clicks total and minimum distraction, I always keep wondering how to approve changes after clicking " asphalt".

**Comment by westnordost** [comment]
Uh yeah, I had the same idea actually, but failed to get it working. I will revisit this later.

**Comment by westnordost** [comment]
> or display a floating OK button.
Done already on master https://github.com/westnordost/StreetComplete/commit/42b210f4faae40af25c7edea2c81e78d23a3a225

**Comment by MarcelWaldvogel** [comment]
How about having the latest few (3?) selected types available on top? In my area, none of the asphalt streets have the type set. So it is always doing the same thing. And every click helps :-)

**Comment by longpu** [comment]
> How about having the latest few (3?) selected types available on top? In my area, none of the asphalt streets have the type set. So it is always doing the same thing. And every click helps :-)

I would appreaciate that too, I was literally just going to file a feature request for this.

**Comment by MarcelWaldvogel** [comment]
When thinking more about it, a solution similar to the one proposed in #73 would be cool. When exploring streets (or when you are adding information about the town you're living in and know the ins and outs), repeating the same solution might be an excellent idea.

Very often, side streets or continuations of asphalt streets are also asphalt streets. Reducing the clicking and scrolling to the minimum is key to get people to enter the information in crowds. (As you may have guessed, I disagree with the reason for closing #73.)

**Comment by HolgerJeromin** [comment]
This is much easier now. Can we close this issue?

**Comment by gjedeer** [comment]
?

There was no update on f-droid so how could anything be easier?

**Comment by westnordost** [comment]
Updates take about 5-7 days to become active on F-Droid.

**Comment by HolgerJeromin** [comment]
I just rechecked with the newest version.

> When I click "paved", the road types window should scroll all the way up so I can see all the choices.

This is not solved in version 0.10

> When I choose Asphalt, it should take me to the end of the form, so I can approve my changes without scrolling. or display a floating OK button.

This is solved.

**Comment by zxmon21** [comment]
I agree with Holger

**Comment by Aypac** [comment]
Might also be further improved by #274

**Comment by westnordost** [comment]
So the only thing left do do here is the same as #76, so closing this.

**Comment by gjedeer** [comment]
Thank you, it's much easier to use now.

**Comment by westnordost** [comment]
After all, I managed to implement the original suggestion (scroll up).

**Comment by gjedeer** [comment]
Awesome, looking forward to test it (once in f-droid).
