### ISSUE TITLE
Resolving a quest using the splitting tool doesn't remove the quest.

### ISSUE THREAD

**Issue by dotjpg3141** [westnordost/StreetComplete#1701]
**How to Reproduce**
Resolving a quest using the splitting tool (Differs along the way...) doesn't remove the quest and I cannot open it anymore.

**Versions affected**
v16.1

**Comment by westnordost** [comment]
I can't reproduce this with the WIP version that will be released soon into beta. So I assume it has been fixed.

Or is this bug generally not always reproducible?

**Comment by dotjpg3141** [comment]
I can reproduce it always e.g. with the quest "Is this stretch of way lit?".

**Comment by westnordost** [comment]
Ok, then I consider this fixed :-)
