### ISSUE TITLE
There is no margin between language code and text field in multilingual forms

### ISSUE THREAD

**Issue by matkoniecz** [westnordost/StreetComplete#1703]
For an example, road name quest in areas with multiple languages.

**Comment by westnordost** [comment]
I don't know what you mean.

**Comment by matkoniecz** [comment]
Note "el" merging with the frame.

Or is it just my phone?

![Screenshot_20200127-054604](https://user-images.githubusercontent.com/899988/73149099-6926aa80-40c8-11ea-824c-b7c490f51611.png)

**Comment by westnordost** [comment]
Ah I see
