### ISSUE TITLE
Noticable delay on marker selection on beta 17-2

### ISSUE THREAD

**Issue by Atrate** [westnordost/StreetComplete#1705]
On the latest beta I have noticed a noticeable delay between pressing a quest marker and the map zomming in on it and the UI popping up.

I would guess that it's remnant from the older versions? The beta has made the animations quicker, so the delay might've become much more noticeable.

Android 10, beta 17-2

**Comment by westnordost** [comment]
There is no delay, it should happen immediately. Nothing changed in this aspect.

**Comment by westnordost** [comment]
And even on my old-ass 2014 phone I can't reproduce that there is a delay. Before there was definitely one (like, a jump / stutter)

**Comment by Atrate** [comment]
I guess it's minuscule enough
