### ISSUE TITLE
17b2 location and orientation north button broken

### ISSUE THREAD

**Issue by RubenKelevra** [westnordost/StreetComplete#1706]
The current beta 2 of v17 seems to have some issues with the button for location lock and the compass button to reset the orientation to north up.

But when the location button is 'on' you can enable 'direction of travel mode'.

Affected Android Version: 9

Deno:

https://youtu.be/M6ZS0Xa4Nzg

**Comment by westnordost** [comment]
Hmm, I can't reproduce this. What should happen is that if the GPS button is black, it rotates back to North (animated), and if it is orange, the "direction of travel mode" is activated.

From the video, it looks like neither the "follow me" functionality works, nor the "rotate to north". Does the zoom-to-quest even work?

What is the value of "animations off" in your system settings?

**Comment by RubenKelevra** [comment]
I found the reason, why it's broken:

I've turned the 'Animator Duration Scale' down to 0 in the developer options of Android.

This seems to breaks those features, returning it to 1x fixes it.

Sorry!

**Comment by westnordost** [comment]
Ok, cool!

**Comment by RubenKelevra** [comment]
@westnordost the fix works for me! Thanks!
