### ISSUE TITLE
Can't login via FireFox Preview, Open a page in the.browser instead of a webview page.

### ISSUE THREAD

**Issue by PoorPocketsMcNewHold** [westnordost/StreetComplete#1707]
Hi there,
I've been recently thinking into contributing a bit to OSM once again, so i've redownloaded my favorite OSM editor, and tried to login with my account.
However, The way StreetComplete doesn't seems to really make it work.

**Expected comportment.** 
1. Click on Login in the settings.
2. Open a webview browser page, allowing you to log to your account and confirm StreetComplete access.
3. Automatically close the browser when this process is done, and connect your account.

**Current comportment.** 
1. Click on Login in the settings.
2. Automatically switch to the Firefox Preview window process if opened, and open the log in page there.
  2.1 If no Firefox Preview process is opened, The app just switch to the login waiting process, until you click out of it, canceling the login process.
3. Once done, The FirefoxPreview process doesn't redirect to StreetComplete and display a error at https://www.openstreetmap.org/oauth/authorize.
It doesn't allows you to copy the authorization token manually, or manually try to open the openstreetmap page in StreetComplete.

I don't really know if it's more an issue with the Firefox browser or StreetComplete, but i prefer to report it, just to be sure.

**Comment by westnordost** [comment]
Yes, it is a problem with Firefox Preview.

For the next major version, I will change the login to not be dependent on the browser.

**Comment by matkoniecz** [comment]
And for now you may temporarily use normal Firefox version or Chrome.
