### ISSUE TITLE
Adding religion quest to more features

### ISSUE THREAD

**Issue by Dosenpfand** [westnordost/StreetComplete#1708]
The religion quest could easily be exended to include at least the following additional features:
1. [cemetery](https://wiki.openstreetmap.org/wiki/Tag:landuse%3Dcemetery)
2. [grave yard](https://wiki.openstreetmap.org/wiki/Tag:amenity%3Dgrave_yard)
3. [monastery](https://wiki.openstreetmap.org/wiki/Tag:amenity%3Dmonastery)

I implemented a f[irst draft for cemeteries](https://github.com/Dosenpfand/StreetComplete/commit/596326b6b66530f2509783739ef2e447343b4927) and can expand it and open a pull request if desired.

### General
Affected tag(s) to be modified/added: [religion](https://wiki.openstreetmap.org/wiki/Key:religion)
Question asked: **What religion is represented at this cemetery?**

### Checklist
Checklist for quest suggestions (see guidelines):
- [X] 🚧 To be added tag is established and has a useful purpose
- [X] 🤔 Any answer the user can give must have an equivalent tagging (Quest should not reappear to other users when solved by one)
- [X] 🐿️ Easily answerable by everyone from the outside but a survey is necessary 
- [X] 💤 Not an overwhelming percentage of elements have the same answer (No spam)
- [X] 🕓 Applies to a reasonable number of elements (Worth the effort)

### Ideas for implementation

**Element selection:** `"nodes, ways, relations with landuse = cemetery and !religion"`

**Metadata needed:** N/A

**Proposed GUI:** 
Similar to adding religion to places of worship and wayside shrines.

**Comment by westnordost** [comment]
Cemeteries and graveyards are problematic because oftentimes there will be no sign or something like that that will shed light on for which religion (if any, or any specific one, by the way) this is.
Monasteries could maybe be integrated into the place of worship quest.

**Comment by matkoniecz** [comment]
Monasteries make sense.

But cemeteries may have a tricky issue. In Poland many cemeteries are operated by local government, open for people of any religion but all (or nearly all) graves are using christian symbols (crosses etc). One may easily add an incorrect `religion=christian`.

**Comment by westnordost** [comment]
So, let's go with monasteries only. Would you like to create a PR for that yourself?

**Comment by Atrate** [comment]
I can make a PR if @Dosenpfand does not

**Comment by Dosenpfand** [comment]
I can create the pull request.
I assume it should be created as seperate class e.g. `AddReligionToMonastery`? Additionally, places of worship are currently only displayed if they have a name, is there any specific reason for that? Should that be handled the same way for monasteries?

**Comment by westnordost** [comment]
No, doesn't need to be separate as the icon can be the same and the current wording fits for monasteries as well.

Hmm, I guess a name is not necessary to identify a highlighted place. You can extend it to include also places of worships that do not have a name, but then you need to add a second string for unnamed places of worship. See for example `AddBusStopShelter` how this can be done. The text should then just ask the religion of the "place".
