### ISSUE TITLE
Unexpectedly disappearing quests on the bottom of the screen

### ISSUE THREAD

**Issue by matkoniecz** [westnordost/StreetComplete#1709]
When users scrolls toward north quests on the bottom edge disappear too soon - when part of the pin is still visible

**How to Reproduce**
Navigate to area with at least one pin.

Scroll toward north.

Note that pin disappears when part of it is still visible.

**Versions affected**

v17.0-beta2
Android 9, security patch 2020-01-01
Xiaomi Mi A2 Lite

**Comment by Atrate** [comment]
Can reproduce, but only with some pins and not in perspective view

**Comment by westnordost** [comment]
Is this new since 0.17?

**Comment by westnordost** [comment]
I posted it as a bug report at Tangram-ES: https://github.com/tangrams/tangram-es/issues/2140

I can not reproduce it, but if you can, you can maybe watch the issue in case the maintainer has some questions regarding your device, screen size or something.
