### ISSUE TITLE
on creating note link object from quest target that prompted note creation

### ISSUE THREAD

**Issue by matkoniecz** [westnordost/StreetComplete#171]
Something like "note was created during work on openstreetmap.org/node/24 "
It is especially useful for C shaped areas (for example buildings, lakes) where note may be placed outside reference object.

**Comment by westnordost** [comment]
This is already the case!

**Comment by matkoniecz** [comment]
Yes, but urls at OSM website are clickable. Current form of reference is not - see for example http://www.openstreetmap.org/note/980757#map=15/51.1675/17.1973

**Comment by matkoniecz** [comment]
Sorry for an unclear issue. Copy paste went wrong and my example was equally unlikable.

Entire proposal is about making reference in form of full URL.

**Comment by westnordost** [comment]
Okay, fair enough. The "(way #12345)" can be replaced with an Url. Perhaps some day notes can be formatted with bbcode, markdown, simple html or whatever.

**Comment by matkoniecz** [comment]
Thanks!

**Comment by westnordost** [comment]
You are welcome :-)
