### ISSUE TITLE
Flickering of solved quests on zoom

### ISSUE THREAD

**Issue by RubenKelevra** [westnordost/StreetComplete#1713]
This is super minor:

There's some flickering going on, when zooming. The already solved quests do show up for a split second and disappear again.

This also occurs when autoupload is on. 

Tested version: 17b3
https://youtu.be/NYgtkI5tU7U

**Comment by westnordost** [comment]
Yes, this is a known problem with the new tangram-es, see https://github.com/tangrams/tangram-es/issues/2133
But anyway a huge improvement because before, the whole map used to flicker.
