### ISSUE TITLE
Quest: bicycle parking capacity

### ISSUE THREAD

**Issue by PanierAvide** [westnordost/StreetComplete#172]
Only 60% of bicycle parkings have a `capacity` tag (according to Taginfo) to let people know how many bikes you can park. A quest for letting users add this information can be pretty simple: just ask "How many bikes can be parked here ?" and user enters an integer value.

**Comment by westnordost** [comment]
And some nice visualization perhaps?

**Comment by PanierAvide** [comment]
What kind of visualization do you think of ? Like [an icon](https://thenounproject.com/search/?q=bike%20parking&i=449496) to put next to the integer field ?

**Comment by westnordost** [comment]
Perhaps something like
[   ] x 🚲
There is a colorful icon for bicycles already in the repos.

Or, depending on the output, bicycles are displayed like
🚲🚲🚲🚲🚲🚲🚲🚲🚲

;-)

**Comment by PanierAvide** [comment]
As this quest was implemented, I think we can close the issue.
