### ISSUE TITLE
Allow entering 3d mode without first locking on current location

### ISSUE THREAD

**Issue by smichel17** [westnordost/StreetComplete#1724]
I just discovered 3d mode. It's really cool, and learning about it has made me more interested in completing "number of stories" type quests. However, it was very hard to find. I only learned about it because I saw screenshots on some issues here on the repo, and even after that it took me around 15 minutes of combined reading (to see if anyone said how to do it) and trial and error to figure it out. For anyone else like me: tap the compass twice while your current location is locked on.

A big reason for this is that I don't lock on to my location very much. I do *use* my location, but I prefer to drag around the map to help orient myself and make sure I'm tagging the right building/road/etc. And I use the compass even less, because I prefer to keep the view oriented along the road I'm walking on. Ironically, 3d mode helps with both of those problems, if only I'd known about it.

Anyway, it's possible to unpin the location and scroll around once you've entered 3d mode, so it's unclear to me why you have to be location locked to enter it in the first place. I *have* tapped the compass multiple times (to no effect) when not locked on location, so I believe this would help with discovery.

**Comment by smichel17** [comment]
Ah, I see. It's because compassMode is part of LocationAwareMapFragment and we use location lock to implicitly assume the type of map fragment :smiling_imp:

**Comment by westnordost** [comment]
You can also use the two-finger gesture (shove with two fingers) to tilt the map

**Comment by westnordost** [comment]
So, I am closing this because it is already possible to enter 3D mode by tilting the map, no compass or location required.

**Comment by smichel17** [comment]
Technically yes, but this was more about the discoverability of the feature than the actual functionality.

**Comment by smichel17** [comment]
I was looking into this this morning, but ran out of time; I'll get back to it in the evening.
