### ISSUE TITLE
Not prompted to login

### ISSUE THREAD

**Issue by joernheissler** [westnordost/StreetComplete#1726]
I installed StreetComplete on my new phone and solved the next best challenge, just to see how the app works.
The challenge disappeared and top-left is now showing a star.

It's completely unclear how to upload the changes to OSM. I'm expecting a prompt like "Click here to login to OSM" or similar.

I assume logging in is possible through the settings menu, but this is very user-unfriendly!

**How to Reproduce**
* Install the app
* Solve a challenge
* Be puzzled about how to upload it

**Versions affected**
Android 10, StreetComplete v17.0

**Comment by westnordost** [comment]
This is intended behavior and was introduced https://github.com/westnordost/StreetComplete/pull/1446

The app indeed asks you to login, but only after the third question answered. Then periodically later on. This is to lower the initial hurdle to start contributing.
