### ISSUE TITLE
Map not cached in version 17

### ISSUE THREAD

**Issue by Helium314** [westnordost/StreetComplete#1727]
Since the upgrade to version 17 (from fdroid, on Android 7) the map is not cached any more. Every time I start street complete, I have to download the map again, even if I just closed it.
This is very annoying when I want to use the app offline, as I can't close it or I will lose the map. But since the last update GPS remains switched on when the app is in background and not closed, so I actually want to close it to save battery...

The frequent reloading of the map might be related to #1723 (high load on map server), at least if I'm not the only one having this issue.

Map cache is set to 150 MB, and the phone has enough free space, so it is definitely not automatically deleting the cache.

**Comment by westnordost** [comment]
Can you please open a separate bug for that the GPS remains switched on when the app is in background?

**Comment by westnordost** [comment]
Will be fixed in next version
