### ISSUE TITLE
Attach images from the gallery to a note

### ISSUE THREAD

**Issue by RubenKelevra** [westnordost/StreetComplete#1730]
**Use case**
Sometimes you have to redact faces, id plates or windows in a picture for privacy and GDPR reasons, before attaching them to a note.

That's currently not possible since only camera apps are allowed on the button on notes.

**Optimal Solution**
Just open a menu where you can choose between the camera and gallery apps.

To prevent spam you could check the time of capture and the position recorded in the EXIF/XMP data if they closely match the image is accepted.

**Alternative solution**

Add the ability to censor parts of the image with black bars.

**Comment by RubenKelevra** [comment]
Example:
![IMG_20200207_115323~2](https://user-images.githubusercontent.com/614929/74174788-df80ec00-4c34-11ea-95fc-52f4ee12fb7b.jpg)

**Comment by matkoniecz** [comment]
Are you sure that redacting plates is actually necessary?

1) is needed to redact plates?
2) is redacting really easier than taking an image without vehicle plates in view?

**Comment by RubenKelevra** [comment]
> Are you sure that redacting plates is actually necessary?
>
> 1. is needed to redact plates?
According to GDPR, yes.

> 2. is redacting really easier than taking an image without vehicle plates in view?
Well, the vehicles are parked ... how should I take this picture without vehicles?

Also, I often take pictures from details along the road, in the background are windows of houses. I like to censor them too, just because of privacy concerns. There's no 'need' to publish these details, so I like to avoid it.

**Comment by westnordost** [comment]
I find the redaction of such features rather unimportant because the photos will not be visible forever but vanish after the note is closed. This distinguishes this from Mapillary, OpenStreetCam, Google StreetView and "TV-Reportagen".

Reasons why I wouldn't like that the user can select from the gallery are here https://github.com/westnordost/StreetComplete/issues/1567
Though, I can understand that some people would like to have the feature that they can redact certain features from the photo, so another angle would be to make it possible to edit the attached image by drawing on it. 

I would accept a PR that implements such an edit-function.

**Comment by pyrog** [comment]
If it will be possible to upload photos to Mapillary, there is no need to redact plates or blur faces because Mapillary's IA do this.

See #1780

**Comment by mxxcon** [comment]
Another app handles it like this
![Screenshot_20200814-173143](https://user-images.githubusercontent.com/847140/90294622-de837e00-de54-11ea-93ea-5c2b5e15de99.png)
Would be nice if StreetComplete offered similar functionality.

**Comment by westnordost** [comment]
Anyway, I am going to close this also to be legally on the safe side here. I do not have the resources to actually review if uploaded photos are really OK copyright-wise. So, limiting this on the client to only allow upload of photos that come directly from the camera is also some sort of "upload filter" to ensure this.

**Comment by pyrog** [comment]
I also appreciate to use this feature, because I take a lot of pictures and write the note after.
