### ISSUE TITLE
created_by in changeset tag has incorrect version number

### ISSUE THREAD

**Issue by peternewman** [westnordost/StreetComplete#1731]
created_by has incorrect version number:
https://www.openstreetmap.org/changeset/80872635

About StreetComplete, Version history shows v17.0, but the created_by still shows the beta version.

**How to Reproduce**
Complete a task

**Versions affected**
Android 9
v17.0 reporting as v17.0-beta3

**Comment by westnordost** [comment]
Hm. I need to remember to rebuild completely for v17.1 and see if the problem persists then. Thanks for the info.

**Comment by peternewman** [comment]
> Hm. I need to remember to rebuild completely for v17.1 and see if the problem persists then. Thanks for the info.

Thanks @westnordost . I assume the version history should show an identical thing then, the Play Store certainly suggests I've got v17 with a link to that GitHub release.

**Comment by westnordost** [comment]
Yes, it is a very weird problem. The app itself also reports that it is v17.0, and the string that is displayed to the user is aggregated from the same constant as the `created_by` field for the changeset.

I remember @matkoniecz also analysing this problem but IIRC he also did not find the source. ATM I am just assuming that it has something to do with that I didn't do a complete rebuild for the release.

**Comment by matkoniecz** [comment]
Yeah, it seemed to be some very weird caching issue without an obvious reason. Now I think that I should also try cloning fresh project and compiling to verify that instead of shrugging and giving up.

**Comment by peternewman** [comment]
Sounds sort of like a make clean/Makefile type issue in C++ land.

**Comment by peternewman** [comment]
I imagine you might have already checked but this is fine in v17.3 thanks @westnordost.
