### ISSUE TITLE
Cached map not visible when there is no internet connection

### ISSUE THREAD

**Issue by tuxayo** [westnordost/StreetComplete#1732]
**How to Reproduce**
- have an internet connection
- open SC
- see an area
- shutdown internet connection
- "close" SC with the back button
- open it
- no map visible even when moving and zooming in and out
- quests still visible
- enable internet connection
- zoom in and out
- map is displayed

network monitoring doesn't show much traffic so it's not like there is no cache and it has to re download the map. Cache seems to be still here.

**Versions affected**
17.0 F-Droid

**Context**
Happened on two device with Android 9 (Lineage OS 16)

**Comment by HolgerJeromin** [comment]
Thanks for the report. This is a 
duplicate of #1727

**Comment by tuxayo** [comment]
Indeed, more testing by moving more the map on a same pattern showed that indeed it redownloads the map each time. No cache contrary to the first impression.
