### ISSUE TITLE
[Bug] Immediate crash upon launch on v17.2

### ISSUE THREAD

**Issue by Atrate** [westnordost/StreetComplete#1733]
Log:
https://del.dog/oseckafyck.txt

Device info:
Rooted Android 10 without Google Services

**Comment by westnordost** [comment]
Oh no.... Network location provider does not exist?? Didn't know this was even possible!

Could I send you a build with a fix and you test if you can reproduce it?

**Comment by westnordost** [comment]
Well, a crash on startup, ... I'll rather release a hotfix right away

**Comment by Atrate** [comment]
Now it's good, thanks
