### ISSUE TITLE
User should be prompted to link an OSM account when creating a note

### ISSUE THREAD

**Issue by tuxayo** [westnordost/StreetComplete#1736]
**How to Reproduce**
- unlink OSM account
- create a note
- go to osm.org and display the notes. It's not there!
- link an account
- restart the app (swipe away from recent apps menu)
- go to osm.org and display the notes. It's there!

**Versions affected**
Android 7.1 (Lineage OS for microG 14.1)
Android 9 (Lineage OS for microG 16)

SC: 17.0 F-Droid

**Comment by tuxayo** [comment]
Should an account be mandated for notes by StreetComplete?

**Comment by Atrate** [comment]
IIRC there has been a proposal that would make it so that anonymous notes on OSM would not be possible anymore.

Maybe it went through and SC didn't adapt yet, @westnordost?

**Comment by tuxayo** [comment]
Oh, wait it came back when I linked the account and restarted SC ^^"
https://www.openstreetmap.org/note/2092166

So anonymous notes are not possible via SC.

**Comment by ferdinand0101** [comment]
I mean I really think that especially for newcomers it's useful to require an account for notes cause sometimes from other apps people create new notes all the time and never awnser cause they don't get notified of comments

**Comment by tuxayo** [comment]
bug report updated

**Comment by HolgerJeromin** [comment]
https://github.com/westnordost/StreetComplete/issues/1726#issuecomment-583875167

> The app indeed asks you to login, but only after the third question answered. [...] This is to lower the initial hurdle to start contributing.

**Comment by Atrate** [comment]
@HolgerJeromin This is for notes, not quests (I think). Even so, it should as the user immediately when creating notes.

**Comment by HolgerJeromin** [comment]
This issue is a bit hard to read. But as I understand it, there is no difference in notes and quests.

**Comment by westnordost** [comment]
> 
> 
> Oh, wait it came back when I linked the account and restarted SC ^^"
> https://www.openstreetmap.org/note/2092166
> 
> So anonymous notes are not possible via SC.

Yes. Notes should only be uploaded when you are logged in.

**Comment by westnordost** [comment]
If the user creates a note, the app asks if the user wants to log in now. However, as for other quests, only after the third contribution. This is working as intended. New users should not be pestered on their first contribution to (register and) login already.

**Comment by westnordost** [comment]
@matkoniecz
