### ISSUE TITLE
Ignore Germany for Pedestrian Acces quest

### ISSUE THREAD

**Issue by ferdinand0101** [westnordost/StreetComplete#1739]
I'm doing this because of the German (Talk-de) Mailing list.
Especially because of this mail
https://lists.openstreetmap.org/pipermail/talk-de/2020-February/116660.html

but there are also a lot of other mails

**Problem**
In germany everything except motorway or trunks are ALL foot yes as such SC shouldn't ask for if pedestrians are allowed on a road

**Proposed Solution**
Put germany on the blacklist for this quest

**Note**

The mailing list isn't 100% sure so I'll raise this issue here

**Comment by westnordost** [comment]
Germany has been considered for this quest, and the current application of this quest in Germany is correct. That pedestrians may use a road unless explicitly prohibited is not specific to Germany.

So, the app asks if pedestrians may explicitly NOT use the road at all here and it is only asked for those pieces of road where there is sufficient reason to assume that pedestrians might not be allowed on this road. Specifically, it is only asked for certain non-residential roads with no sidewalk for which a certain stage of development can be assumed.

See https://lists.openstreetmap.org/pipermail/tagging/2019-February/042852.html 

I don't know why Florian Lohoff brings this topic up again after the topic from last year. Apparently he did forget about it.
