### ISSUE TITLE
Alert dialog with cancel / ok button not clear

### ISSUE THREAD

**Issue by pvarry** [westnordost/StreetComplete#1741]
The "Stop the current search and scan here instead?" alert dialog is not clear.

In french we have the following alert dialog:
- "Annuler la recherche en cours et rechercher ici à la place ?" -> `Stop the current search and scan here instead?`
- "Annuler" -> mean `Cancel` or `Dismiss`
- "OK"

The problem is:
Does "Annuler" ("Cancel") button will actually cancel the current search or it will cancel the request of a *new* scan

The Material Design response about this problem :
[https://material.io/components/dialogs/#alert-dialog](https://material.io/components/dialogs/#alert-dialog)
(Behavior section)

I search in poeditor.com project but the ressource is not present

![Screenshot_20200220-130142 (1)](https://user-images.githubusercontent.com/9653913/74943629-fd98da00-53f4-11ea-8ec1-e0a3e6d7d6df.png)

**Versions affected**
17.3

**Comment by smichel17** [comment]
A simple solution would be to change "OK" to "Start".

I haven't completely figured out the wording yet but a different solution would be to make the verbs "Change" and "Keep", with the question something like "A different search is already in progress. Change to scanning this location?" I'm not happy with that phrasing but I think I might like this approach more.

**Comment by pvarry** [comment]
For the action you can use something like :
Positive : "Run again" or "Change location"
Negative : "Keep running" or "Continue current"

A unique verb like "keep" is maybe too vague and some translators may not currently understand the action

**Comment by HolgerJeromin** [comment]
> I search in poeditor.com project but the ressource is not present

This is probably an android global translation.

**Comment by westnordost** [comment]
Correct, it is in `MainActivity.java::downloadDisplayedArea`, just using the default `android.R.string.ok`.
The proper solution was already mentioned here. If possible the current wording for the question should be retained ("Stop the current search and scan here instead?"), the answer options according to Android design guidelines could then for example be (in English) "scan here instead" and "continue current scan". If I remember correctly, buttons in Android dialogs switch to a vertical orientation automatically if the text of all buttons does not fit into one line, right, @smichel17 ?

**Comment by smichel17** [comment]
I think that's true but not 100% sure.
