### ISSUE TITLE
Ask for roof type even with roof:levels not present

### ISSUE THREAD

**Issue by Atrate** [westnordost/StreetComplete#1744]
My reasoning is simple: not all buildings have levels in the roof, yet virtually all buildings have a roof, thus the roof shape quest should be asked even for buildings that do not have a roof:levels tag.

**Comment by westnordost** [comment]
Please search the issue tracker for related issues before you open a new one

**Comment by westnordost** [comment]
https://github.com/westnordost/StreetComplete/issues/277

**Comment by Atrate** [comment]
Oh sorry, searched but didn't find that
