### ISSUE TITLE
Recycling is missing none (rest garbage)

### ISSUE THREAD

**Issue by PanderMusubi** [westnordost/StreetComplete#1745]
Quest for recycling is missing the option none (rest garbage). According to the OSM wiki, if there is no specific recyclling, no tag should be added. But the app offers only selection of one or more from 10 options or "CAN'T SAY...".

But it is not can't say for a bin that accepts rest garbage. Hence, please offer the option "NO RECYCLING". How this should be storeg in OSM tags, I have no idea.

Please see also the screenshot and the picture.

![Screenshot_20200227-135840_Street�Complete](https://user-images.githubusercontent.com/198964/75447681-275c7e80-596a-11ea-8ef9-803c3af5663c.png)

![ra](https://user-images.githubusercontent.com/198964/75448252-24ae5900-596b-11ea-940b-a4887421cddc.jpg)

**How to Reproduce**
Do a quest for a (underground) recycle bin.

**Versions affected**
17.3

**Comment by westnordost** [comment]
For now, you can leave a note, describing that it is not a recycling container but a generic waste disposal. It seems it was wrongly tagged as `amenity=recycling`. An other-answer option could be added to the app that will re-tag the facility as 
`amenity=waste_disposal` as proposed in the wiki:

> [`amenity=recycling`] is for sites where waste of specific types is accepted to be reused or recycled - if the site is for disposing of arbitrary waste, consider a different tag as listed under [Waste Processing](https://wiki.openstreetmap.org/wiki/Waste_Processing). 

Waste processing lists
> `amenity=waste_disposal`: A medium size disposal bin, typically for bagged up household or industrial waste. May be in the street, but not primarily for use by passing pedestrians.

Do you or someone else reading here have suggestions for the wording of that other answer option (and the confirmation dialog if necessary?)

**Comment by PanderMusubi** [comment]
For my city these are hundreds of bins. They are `waste_dispocal` but only accessible by people living nearby via a special chip card. Perhaps offer an option: '_this is not recycling by waste disposal_'

**Comment by westnordost** [comment]
That's too long

**Comment by matkoniecz** [comment]
"for trash, without recycling"?

**Comment by ferdinand0101** [comment]
How about adding residual waste as an option and if it's only that make it waste disposal and if it's not the only one add recycling: residual

**Comment by PanderMusubi** [comment]
That was not a serious name for an option, more a description of what it should mean. :smile:

**Comment by smichel17** [comment]
What about "Not for recycling" or "For trash only", with a confirmation dialog that includes both parts?

**Comment by PanderMusubi** [comment]
Well, you don't know if residual garbage is also recycled at the garbage process, i.e. metals are extracted via magnets. So I would prefer "**residual trash**" (and it can be kept under recycling). What is residual also differs from local community to local community.

**Comment by westnordost** [comment]
I avoided the term "residual trash" in the implementation but chose "It's for general waste" and "So, this is a container for any waste, such as bagged up household or industrial waste?" because while quite fitting in Netherlands and Germany ("Restmüll"), in areas of the world where recycling (containers) are not that common, it might be weird to call "any" waste "residual" waste. Like: Residual of what?
Also, "trash" is apparently more American-English, while "waste" is equally known in BE and AE, see https://en.wikipedia.org/wiki/Waste_container

**Comment by smichel17** [comment]
Yes, here in the US it's unfortunately more common that the contents of recycling bins end up exported and dealt with exactly as regular trash (or even mixed together!) instead of being recycled, than recyclable materials being picked out of otherwise non-recyclable waste.

**Comment by PanderMusubi** [comment]
Yes, "Restmüll", but in the Netherlands, where it is called "restafval".

**Comment by smichel17** [comment]
Translations can also use different words here as appropriate to reflect cultural standards, instead of strictly literal translations. Even to the extent of "waste" in the base and "trash" in en_US locale.

**Comment by westnordost** [comment]
The default is the en-US locale. I understood that "waste" is understood in en-US equally.

**Comment by matkoniecz** [comment]
> So, this is a container for any waste, such as bagged up household or industrial waste?

Not a native speaker but "industrial waste" seems to strong to me. Typical trash bin accepts random household waste, but not industrial waste, that at least to me seems to include also toxic materials, waste produced in large sizes/quantifies/etc.

**Comment by PanderMusubi** [comment]
Bagged up household and alike if you can fit it in the gated opening. Recyclables and toxic/hazardous stuff is forbidden.

**Comment by westnordost** [comment]
I copied the wording from the wiki. I'll change it to "commercial waste"

**Comment by matkoniecz** [comment]
now old version was

> So, this is a container for any waste, such as bagged up household or industrial waste?

vs

> typically for bagged up household or industrial waste 

from https://wiki.openstreetmap.org/wiki/Tag%3Aamenity%3Dwaste_disposal

SC version had "any waste" qualifier, while in wiki version "industrial waste" remained optional.

I am mentioning it here as I went initially to wiki to fix wording there.

**Comment by PanderMusubi** [comment]
Commercial waste is not where these containers are used for. The commercial waste in the wiki is referring to private collection companies. So it is neither commercial nor industrial. Sorry if this was already mentioned.

**Comment by westnordost** [comment]
Hum, so what's your suggestion?

**Comment by matkoniecz** [comment]
I translated it into Polish as "So, this is a container for mixed waste" ("odpady zmieszane" is used by municipal companies collecting waste, not sure whatever "mixed waste" is such term that would be both clear and readable).

**Comment by PanderMusubi** [comment]
Difficult, as there is no a key/value for it yet. Think something in the area of:

[`recycling_type=container`](https://taginfo.openstreetmap.org/tags/recycling_type=container)

[`recycling:waste=yes`](https://taginfo.openstreetmap.org/tags/recycling%3Awaste=yes)

or a new key/value `waste=household, `waste=combustible`, `recycling:household=yes` or `recycling:combustible=yes`

Often, this stuff is burned. In Japan, this is called literally combustible trash.

**Comment by westnordost** [comment]
@PanderMusubi , I meant the wording, not the tag. The tag is very clearly amenity=waste_disposal or do we not agree on that?

**Comment by PanderMusubi** [comment]
Sorry about that. Wording in Dutch is "restafval" in English, I'd say "household trash" or "household waste" in the quest. That should exclude toxic stuff.

**Comment by westnordost** [comment]
I did a little research and I will stick with mentioning "commercial waste", it is only mentioned as an example for "general waste" anyway. "Gewerbeabfall" (DE) means basically the household trash of companies, "commercial waste" is the English translation of that. According to the pictures here, this pretty much hits the spot as well
https://duckduckgo.com/?t=ffab&q=gewerbeabfall&ia=images&iax=images

The way I read the OSM wiki is that Tag:amenity=waste_basket is a bin for trash and   Tag:amenity=waste_disposal is a container for trash.

**Comment by PanderMusubi** [comment]
IMHO there are a lot of differences and "household trash of companies" mixes the two. In the Netherlands (and probably Germany):
1. commercial (corporate offices/small industrial/restaurant/shop) waste is collected separately from large metal rolling containers than combustible/non-recyclable 'household waste/trash' which is dumped via bags in underground containers
2. this is also done via a separate commercial contract compared to a public service for citizens
3. commercial waste rolling containers are usually not on public grounds, but the household underground are (as seen in the picture of this issue compared to your image search)
4. commercial waste is often unsorted (depending on your contract) and gets sorted into different recycling categories by the waste processor (hence the more costs) while household trash goes (almost) straight into the incinerator

For the quest/this issue, I'm only interested the underground containers for household trash bags, not the commercial rolling container or public waste baskets and I understand we don't have all the definitions available we might need. I accept the name you choose for the label as not to drag this out any further, just wanted to share these details.

**Comment by PanderMusubi** [comment]
I used the fix in the new version of the app successfully regarding this issue. Thanks all!
