### ISSUE TITLE
Map buttons don't work when Energy Saver is enabled

### ISSUE THREAD

**Issue by kuba-orlik** [westnordost/StreetComplete#1753]
**How to Reproduce**

1. Enable Battery Saver
2. Press the zoom in / zoom out / go to current location buttons on the map
3. Nothing happens
4. Disable Battery Saver
5. Now map buttons work properly

**Versions affected**

StreetComplete 17.3
Android 8.1.0

**Comment by westnordost** [comment]
Cannot reproduce. This used to be a bug in beta versions of v17.0. What energy saver options do you mean exactly? Power Management => Low-Battery-Mode?

**Comment by kuba-orlik** [comment]
In my case it's Settings → Battery → Battery saver and performance → Extreme power saver

I'm on LineageOS

**Comment by westnordost** [comment]
Can you reproduce this with "normal" power saver? If not, does it say what "extreme power saver" entails?

**Comment by hferee** [comment]
I cannot reproduce this either with the following:
StreetComplete 17.3
Android 9
LineageOS 16.0

**Comment by Helium314** [comment]
Can reproduce with StreetComplete 17.3 on (LineageOS 14.1 based) AOKP on S4 Mini. Also the automatic zoom level change when tapping a quest marker does not work.

Activating Battery Saver automatically switches to Power save performance profile and enables Extreme power saver. Manually disabling Extreme power saver, gives normal zoom button behaviour even with Power save performance profile.

**Comment by kuba-orlik** [comment]
My system does not provide a "normal" power saver. Can't really tell what "Extreme" power saver does differently from normal one. One thing I do notice is that all system animations are disabled when extreme power saver is enabled. Maybe that would be somewhat helpful? It should be noted that the app works fine when all system animations are disabled in system developer settings

**Comment by westnordost** [comment]
I am positive that it has something to do with animations being disabled. However, there is already a check whether the animations are disabled or not. See
https://github.com/westnordost/StreetComplete/blob/master/app/src/main/java/de/westnordost/streetcomplete/map/tangram/CameraManager.kt#L102-L103

Apparently, certain versions of LineageOS does not correctly report that animations are disabled. Which LineageOS version do you use?

**Comment by westnordost** [comment]
@kuba-orlik Could you download, start https://www.westnordost.de/misc/TestAnimatorDuration.apk and say what number is shown in the center of the screen?

**Comment by kuba-orlik** [comment]
Sure thing. No matter if I run the app with Extreme Power Saver enabled or not, it says `0.5` (that's what I set it to in Developer Settings)

**Comment by westnordost** [comment]
Oh okay. This is the animator scale. 0.5 means that all your animator-based animations run at 2x the speed, regardless of whether extreme power save is enabled or not.

But you said that all animations are disabled in extreme power saver. So, there must be another switch that is making the animations not being animated on your LineageOS version. But I did not find anything about it on the net.

One more thing: You might need to restart the TestAnimatorDuration app when you switched on or off the extreme power saver. Does it report any different values then?

**Comment by Helium314** [comment]
For me it also reports the correct animator duration scale (after restarting)
The (reported) animator duration is not changed by (extreme) power saver.
When setting animator duration to 0 the zoom buttons are still working.

**Comment by kuba-orlik** [comment]
> One more thing: You might need to restart the TestAnimatorDuration app when you switched on or off the extreme power saver. Does it report any different values then?

I did try restarting the test app, and it always reported 0.5x - both with energy saver enabled and disabled

**Comment by westnordost** [comment]
Okay, would you try out this app?

https://www.westnordost.de/misc/TestAnimatorDuration2.apk

How does the pink background animate with and without energy saver? What is written in the "log"?

**Comment by kuba-orlik** [comment]
Without energy saver the background animates smoothly over multiple frames, and the log is filled with intermediate numbers from 0 to 1.

With energy saver enabled the background just becomes ping immediately and the log says:

```
pressed button
started animation
animating 1.0
ended animation
```

**Comment by westnordost** [comment]
Sorry for not getting back at this, I am a bit out of ideas. The demo app showed that your system's animation system is behaving correctly, but that the method that the app uses to find out if the animations are off is not working (for your system).

You could help by starting the app yourself from source via Android Studio and set a breakpoint at CameraManager.kt line 155:
- Does the execution flow ever enter that block? If not, what is lastAnimatorEndTime, what is endTime?
- If it does enter the block, is this::animate ever called?

What I expect when it was working would be that in your case, animate should be called once with the final animation value.

**Comment by kuba-orlik** [comment]
Thanks for giving this another look.

I have zero experience with Android debugging, but I will try to set everything up and report the results. It will keep some time, though! I hope my PC can handle Android Studio :sweat_smile:  Unless there is some more lightweight way to enter a debugger that would work in this case, like a CLI?

**Comment by smichel17** [comment]
The only spec that would make it actually hard to run is if you're on a computer with 4GB of RAM, since you'll be running the app on your phone and not an emulator. If that's the case you'll likely need to close everything else on your laptop and let me know so I can share a few settings that should reduce ram usage.

A slow processor or disk will affect compile times a little but that doesn't matter too much; it's a linear slowdown, compared to hitting a huge cliff if you max out your ram.

**Comment by kuba-orlik** [comment]
> The only spec that would make it actually hard to run is if you're on a computer with 4GB of RAM

That is the case, actually :sweat_smile: 

I'll look into it soon, thanks!

**Comment by dreua** [comment]
It seems to be fixed for me, can someone else confirm it is fixed or still present? I know I had the issue earlier but now it seems to be gone, not sure when exactly. (I'm on v21.)

**Comment by kuba-orlik** [comment]
I can confirm the issue is solved :)
