### ISSUE TITLE
[New Quest] Defibrillator location (access/opening hours)

### ISSUE THREAD

**Issue by Sequynth** [westnordost/StreetComplete#1756]
### General
Even though a lot of defibrillators have been deployed recently in public spaces, usage remains [fairly low](https://www.sueddeutsche.de/gesundheit/gesundheit-defibrillatoren-in-deutschland-werden-selten-genutzt-dpa.urn-newsml-dpa-com-20090101-190426-99-971052) (situation in germany, german). One reason for such few uses is that people dont know where they are located or are even unaware of their existence. This quest could serve two purposes: First, it further specifies the location of a defibrillator, potentially saving time spent on looking for a specific device. Second, it actually raises awareness among SC users that such devices are available in many cities these days and some of those are already mapped.
Providing also access= and opening_hours= information, this could prevent people from going for a nearby but inaccessible defibrillator, while a second one further away might be readily available.

Affected tag(s) to be modified/added: [defibrillator:location=](https://wiki.openstreetmap.org/wiki/DE:Tag:emergency%3Ddefibrillator)
Question asked: **Where exactly is this defbrillator?**

Two separate quests could be
(access=yes/private **Is this a public defibrillator?**
opening_hours= **When is this defibrillator available?**)
access and opening_hours could potentially be inferred from the values of the building they are located in, but im not sure how this is generally handled/mapped in OSM.

### Checklist
Checklist for quest suggestions (see guidelines):
- [x] 🚧 To be added tag is established and has a useful purpose
The tag was approved back in [2013](https://wiki.openstreetmap.org/wiki/Proposed_features/automated_external_defibrillator) and there are currently [~25k](https://taginfo.openstreetmap.org/tags/emergency=defibrillator) nodes worldwide, of which [~5k](https://taginfo.openstreetmap.org/keys/defibrillator:location#overview) have a value for defibrillator:location, leaving ~20k nodes without further information about the location.
- [x] 🤔 Any answer the user can give must have an equivalent tagging (Quest should not reappear to other users when solved by one)
Once a location= tag is provided, the quest does not appear to other users (do I understand this check-element correctly?)
- [ ] 🐿️ Easily answerable by everyone from the outside but a survey is necessary
Many defibrillators are located in public buildings, i.e. entering is possible, but survey from outside is usually not sufficient. Some devices might be on private property, here a second quest could ask for access=
- [x] 💤 Not an overwhelming percentage of elements have the same answer (No spam)
Since distribution of defibrillators is rather sparse and the location is usually completely different between devices.
- [x] 🕓 Applies to a reasonable number of elements (Worth the effort)
~20k is not a lot, but i see other advantages in adding this quest (see General). In that sense worth the effort.

### Ideas for implementation
I guess this quest requires the user to input a short text, which i havent seen on other quests in SC thus far, so im afraid this would need to be implemented. Im also not sure whether arbitrary text input is in line with SC philosopy.
The information should be provided in local language, but maybe an option to also provide the information in english could be helpful (possibly clogging the UI, though)
One could also think about a regular recheck of the presence of a device (e.g. every half a year), since not all map styles render defibrillators (e.g. OSM carto) and old nodes could remain unnoticed in the database.

**Comment by matkoniecz** [comment]
I also thought about asking for `location=outdoor` / `location=indoor`.

If defibrillator is supposed to be useful at all then it should be possibly to locate it quickly, and info whatever it is inside building or outside building would probably help.

And looking at https://taginfo.openstreetmap.org/keys/defibrillator%3Alocation#values many description it would be more useful in this form, being machine-readable (so much easier translation).

**Comment by westnordost** [comment]
> I guess this quest requires the user to input a short text, which i havent seen on other quests in SC thus far, so im afraid this would need to be implemented. Im also not sure whether arbitrary text input is in line with SC philosopy.
> The information should be provided in local language, but maybe an option to also provide the information in english could be helpful (possibly clogging the UI, though)

It has been done before, for the opening hours quest, if one selects that it has irregular opening hours, one is supposed to add a short description in the local language, like for example "per appointment".

**Comment by Sequynth** [comment]
> If defibrillator is supposed to be useful at all then it should be possibly to locate it quickly, and info whatever it is inside building or outside building would probably help.

Those that I'm aware of are not really easy to find, they just hang on a wall. 

> And looking at https://taginfo.openstreetmap.org/keys/defibrillator%3Alocation#values many description it would be more useful in this form, being machine-readable (so much easier translation).

I'm actually voting for human readable in this case. It's supposed to give further information to somenone that looks for a specific defibrillator (i.e. knowing to turn right when entering a building). That does not exclude location= from being tagged. This could be a two-staged quest:
**Is this defibrillator inside a building?** _yes/no_
independent on the answer given, follow-up with:
**Briefly describe where exactly it is located**

**Comment by rugk** [comment]
> access=yes/private Is this a public defibrillator?

This is hard to answer, because: Is it already private if it is inside any building? Even if it is a public mall, central station, public service buildings (that are _usually_ open, but not 24/7) etc.? (I guess most of these are usually indoors, i.e. at such places)
Or is it only public if it is outdoors?

So IMHO asking for indoor/outdoor is more useful.

**Comment by Sequynth** [comment]
I went past some defibrillators on the university campus today. All of them are marked with a 'defibrillator sign' (green lightning-bolt on white heart on green background) on the entrance door and they are located in the entrance hall / lobby / .... These two factors I think are clear signs of a publicly available AED. There are also AEDs that are installed at a workplace by the employer and as such more or less only available to the employees. Im not sure how to tag those... they could still be used by the public (the AED in the canteen of my workplace is not signposted but easy to reach in the 1st floor if you know where to look). Who in their right mind would deny somebody to use it in an emergency (especially since they have considerable maintenance cost: best before dates on battery and electrodes, mandatory safety tests...)


**Is this defibrillator signposted in a public area by _IMAGE_ (or similar) or is located close to the entrance?**
No: access=unknown, end quest here
Yes: access=yes

if access==yes:
**Is this defibrillator located indoors or outdoors?**
indoors: indoors=yes
outdoors: ? (i dont think [indoors](https://wiki.openstreetmap.org/wiki/Key:indoor)=no is a supported combination)

if access==yes:
**Briefly describe where exactly it is located**
defibrillator:location=...

if access==yes:
**At what times is it possible to reach this defibrillator, i.e. what are the opening hours?**
opening_hours=...

**Comment by ModProg** [comment]
> if access==yes:
> **Is this defibrillator located indoors or outdoors?**
> indoors: indoors=yes
> outdoors: ? (i dont think [indoors](https://wiki.openstreetmap.org/wiki/Key:indoor)=no is a supported combination)

We would need a way to tell SC if indoors is already answered. And probably indoors=no would be a solution, as it is already used:
https://taginfo.openstreetmap.org/tags/emergency=defibrillator#combinations

**Comment by matkoniecz** [comment]
@Sequynth I am making one more quest (asking about `indoor` status). Do you know whatever this tag is used by any already existing data consumer - or is it just collecting data to make such data consumer more likely to appear?

**Comment by Sequynth** [comment]
I checked a few emergency apps (Cisali, Staying Alive, Defikataster), but they dont seem to use OSM data. The last uses their own database for location of AEDs (http://definetz.online/defikataster-1). I only know https://defikarte.ch/index.html where OSM data is used. Why this has to be restricted to switzerland is beyond me, but could be explained by server load...
Of course you can also search for one using OsmAnd, but this is not a dedicated data use.

My intention was more to get some attention for AEDs and also get their data right and usable. I had no specific data user in mind. The french community currently currently have a [project of the month](https://projetdumois.fr/projects/2020-09_aed) for mapping AEDs (but I'm sure you are already aware of it)

**Comment by rugk** [comment]
> The french community currently currently have a project of the month for mapping AEDs (but I'm sure you are already aware of it)

Then maybe do the reverse: Make _them_ (i.e. the French community) aware of this idea/issue here. They may be experts in this field and have more ideas/use casses/apps, where this may be used.
