### ISSUE TITLE
Idea: Verification mode

### ISSUE THREAD

**Issue by Natenom** [westnordost/StreetComplete#176]
In this mode all supported quest types would be visible so one can verify and/or correct them.

* Streets: Use different colors to represent paved/unpaved/ground and the details.
* Levels: Display levels
* ...

**Comment by westnordost** [comment]
Uh, this warrants an own app actually. Currently, this kind of feature is completely out of scope of this app. I believe there are some other QA tools around that display i.e. street surfaces and building types.

**Comment by HolgerJeromin** [comment]
osmand can show lit, street surface and other stuff.
