### ISSUE TITLE
User interface suggests OSM contributions happen even when not logged in

### ISSUE THREAD

**Issue by nospam3059** [westnordost/StreetComplete#1761]
**How to Reproduce**

0. Install and start StreetComplete.
1. Start contributing answers and see the star count increase.
2. Click the star.
3. Read the text in the pop-up occurring, claiming that answers are added to OpenStreetMap immediately.

From the information given, and the lack of user feedback, it would be natural to get the impression that any answers given are automatically uploaded with no other user action required.

I think one possible way to greatly improve this would be to slightly modify the behavior when using the app without being logged. One suggestion would be to show the upload icon and change counter when not logged in and there are pending changes, similarly to how that information is visible when having the synchronization set to manual mode. Clicking the upload icon will already inform about the necessity to login. The problem is just that with the default settings, that information is far from obvious.

**Versions affected**

Android: Several versions tested.
StreetComplete: v18.0

**Comment by westnordost** [comment]
> From the information given, and the lack of user feedback, it would be natural to get the impression that any answers given are automatically uploaded with no other user action required.

Well, that's the way it works right now.

Regarding to tell the user to log in, it is told to the user after he solved the third quest. The text is _"You need to authorize with your OSM user account to publish your answers. Authorize now?"_.

When #1552 gets done, maybe this should also be mentioned.
