### ISSUE TITLE
Include certain surfaces in the surface quest query

### ISSUE THREAD

**Issue by ferdinand0101** [westnordost/StreetComplete#1763]
**Use case**
List of tags that should be included:
surface=yes
surface=unknown

**Proposed Solution**
included them

**Comment by pkoby** [comment]
`surface=yes` is meaningless. All roads have a surface.
`surface=unknown` is the same as not tagging it, so that's already in the system.

Those values have 425 and 113 uses respectively, making up 0.00% of uses. I don't see the need.

**Comment by ferdinand0101** [comment]
> surface=yes is meaningless. All roads have a surface.
surface=unknown is the same as not tagging it, so that's already in the system.
I was asking to include these roads in the querry so they than can get fixed

**Comment by ferdinand0101** [comment]
but yes it might not be enough cases

**Comment by pkoby** [comment]
StreetComplete is made for on-site survey, so you should be standing on the road when you answer what the surface is. Since it is now possible to split ways if the surface changes, there is no reason not to be able to accurately add the surface for each section.

**Comment by smichel17** [comment]
@pkoby I think you may be misinterpreting the proposal. @ferdinand0101 Is not proposing that we allow people to tag surfaces as those two, but rather that when either of those is tagged, we should present a quest to tag it properly.

**Comment by pkoby** [comment]
You're probably right. If this is what @ferdinand0101 meant, my bad.

**Comment by ferdinand0101** [comment]
Yes that is what I meant but I have to admit that I worded it weirdly

**Comment by westnordost** [comment]
I've looked at taginfo again and decided to not add the checks for the suggested values because it is not worth making the query more complicated for such a low volume of odd values. There are some odd values for about every tag there is, add them all (even those with really small usage numbers) would be an unmaintainable effort.
