### ISSUE TITLE
replace all context!!, activity!! etc with require*

### ISSUE THREAD

**Issue by westnordost** [westnordost/StreetComplete#1765]
Since the new Android Studio version, a warning (actually, an "error") is displayed when one uses !! when a `require`* alternative exists.

The (little) advantage of using `require`* that I see would be that not a nullpointer is thrown but an illegal state exception which describes the problem more precisely. Not that much of an advantage, but the other reason is that with the default settings, Android Studio shows this as an error, which is disruptive and gives the impression that the code is in a bad shape.

**Comment by smichel17** [comment]
There's also `check`, which behaves the same as `require` but throws an `IllegalStateException` instead of an `IllegalArgumentException`. Also there's `checkNotNull` and `requireNotNull` variants, which only take the argument and throw a better error message if you don't pass one yourself.

**Comment by westnordost** [comment]
Actually I meant `Fragment.requireContext` etc.
