### ISSUE TITLE
[new quest] check if the speed limit is up to date

### ISSUE THREAD

**Issue by letypequividelespoubelles** [westnordost/StreetComplete#1766]
Hi all,
I think that would be very nice if it was possible to check if the speed limit is ip to date. In fact, it's most of the tile while in car/bike (and not driving :) ) that we can see that speed limit aren't up to date, but it's not easy to update it on a laptop. So if a quest (like what is being done now for open time) was create to update speed limit, it would be amazing. I think this is one of the most changing things, with the development of 20/30 km/h zone in city.

Thanks

**Comment by westnordost** [comment]
But how often a year / a decade should a surveyor be sent to each street to verify if the current speed limit is still the same? Every half a year? Every year? Every 5 years? On what (data) basis should the interval be decided?

**Comment by letypequividelespoubelles** [comment]
Honnestly, Idk. I think it can't be less than a year (it should be user friendly), no more than 5 years (the aim is to have accurate data). How has it been decided for the the "resurveying of opening hours" now in pull request ?

**Comment by ferdinand0101** [comment]
the resurveying of opening hours quest is not based on time but on "false entries" which then should be corrected

**Comment by westnordost** [comment]
@ferdinand0101 This is not correct, @letypequividelespoubelles is referring to #1676

**Comment by letypequividelespoubelles** [comment]
yes, right. So do you think it should be possible and usefull?

**Comment by westnordost** [comment]
Yes, it is both possible and useful. This belongs to a group of quests I'd call "maintenance quests" that has not been implemented yet and should be solved in a generic manner: The answer for possibly for many quest type should be re-evaluated every X months/years.

Since the solution that would enable this sort of quest has not been implemented yet, I also set this on blocked.

**Comment by letypequividelespoubelles** [comment]
Thanks for the answer. How could I help ?

**Comment by westnordost** [comment]
Nothing directly. But what you could do, is look through the list of quest types and see which of those should be re-surveyed and at which intervals (in your opinion), then post the list here. This would help me find for which quests it should be done.

**Comment by letypequividelespoubelles** [comment]
Ok, will do it. For the intervals, is  there some data somewhere which could be analyze to determine it ?

**Comment by westnordost** [comment]
Data like studies or government statistics how often f.e. streets are re-made, new shops open and others close etc, or statistics on how often this is changed in OpenStreetMap?

For the former: No idea. For the latter: Well, the data is there, but I do not know any tools that would enable you to analyze the "half life". I think the best would be to go by personal experience or better by personal experience of many people. Maybe make a survey?

**Comment by letypequividelespoubelles** [comment]
I took a look at the french datas [INSEE](https://www.insee.fr/fr/accueil) but couldn't find any interesting datas to analyze. Here after, the quests I think we should resurvey :
- What are the opening hours of […]? : 1 year ; it's on pull request now
- What is the speed limit sign for this street? : every 2 years
- Is […] wheelchair accessible? : every 2 years
- Are these toilets wheelchair accessible? : every 2 years
- Is this place wheelchair accessible? every 2 years
- Is the restroom at […] wheelchair accessible? 2 years
- Is there a cycleway in this street? : every 2 years, but just i the previous tag was "no".
- Does […] have vegetarian meals on the menu? : every 2 years
- Does […] have vegan meals on the menu?  : same, every 2 years
- Does it cost a fee to park here? every 5 years
- What kind of internet connection does […] offer?  : every year
- Do these traffic lights have a button to request green light? : no idea
- Are there sound signals for the blind here? : no idea
- What is the surface firmness of this track? : every 1 year
- Are pedestrians prohibited from walking on this road here?  : 2 years
- Does this street have a sidewalk?  : 2 years
- What is the name of this place? : 1 year
- What can be left here for recycling? : 2 years

**Comment by ferdinand0101** [comment]
I would maybe like to add that depending on the value not everything needs to be survey at the same interval.

for example with Is this place wheelchair accessible? every 2 years
a places are far more likely to ADD wheelchair accesibillity than remove it

**Comment by HolgerJeromin** [comment]
Is there still the shop/restaurant xy? Could be asked every two years.

**Comment by letypequividelespoubelles** [comment]
to HolgerJeromin : this would be already in asking the opening hours, and with the name of this place. So, in my mind, no need for one more quest

**Comment by westnordost** [comment]
I submitted an [application for a microgrant at the OSMF](https://wiki.openstreetmap.org/wiki/Microgrants/Microgrants_2020/Proposal/Map_Maintenance_with_StreetComplete) to develop this feature.

**Comment by letypequividelespoubelles** [comment]
Hi westnordost,
If you have the grant and do the implementation (which I hope ! ) I would like to point out one possible difficulty for the "name of the street" quest. If it has changed, you'll have to change the adress of every POI on the street, and a minority of adress's POI have the ["associatedstreet"](https://wiki.openstreetmap.org/wiki/Relation:associatedStreet) relation.

**Comment by westnordost** [comment]
The app will likely not ask again if the street name has changed because such things happen too rarely 

Am 5. Mai 2020 09:16:09 MESZ schrieb letypequividelespoubelles <notifications@github.com>:
>Hi westnordost,
>If you have the grant and do the implementation (which I hope ! ) I
>would like to point out one possible difficulty for the "name of the
>street" quest. If it has changed, you'll have to change the adress of
>every POI on the street, and a minority of adress's POI have the
>["associatedstreet"](https://wiki.openstreetmap.org/wiki/Relation:associatedStreet)
>relation.

**Comment by elgaard** [comment]
If could be based on nearby OSM activity.
For example if new residential roads were added after the speed limit was last set.
Or roundabouts, speed bumps.

Or if the number of lanes change. 
In DK they often change a 2 lane road to a 1+1 road and lower the speed limit at the same time.
The lanes can be seen on aireal images, but not the speed limit signs.

**Comment by westnordost** [comment]
I now posted this on the tagging mailing list: https://lists.openstreetmap.org/pipermail/tagging/2020-July/054208.html

Please feel free to join the discussion there

**Comment by westnordost** [comment]
So, as described in https://github.com/westnordost/StreetComplete/issues/1998#issuecomment-676787192 , this will unfortunately not be implemented.
