### ISSUE TITLE
Photos are not uploaded on Android <5.0

### ISSUE THREAD

**Issue by nospam3059** [westnordost/StreetComplete#1768]
After using StreetComplete for a while I've noticed my note attached pictures fail to upload. 

**How to Reproduce**
0. On quests, answer quest_generic_answer_notApplicable and add photos.
1. Attempt to synchronize.
2. Realize the counter will not reach zero, but that any notes with pictures get stuck on the device.
3. Connect a USB cable and fire up `adb logcat`:

```
E/CreateNotesUpload(17531): Error uploading image attached to note "Tak?" at 55.59314299787648, 13.01233971321108
E/CreateNotesUpload(17531): de.westnordost.streetcomplete.data.osmnotes.ImageUploadException: Upload failed
E/CreateNotesUpload(17531):     at de.westnordost.streetcomplete.data.osmnotes.StreetCompleteImageUploader.upload(StreetCompleteImageUploader.kt:57)
E/CreateNotesUpload(17531):     at de.westnordost.streetcomplete.data.osmnotes.AttachPhotoUtilsKt.uploadAndGetAttachedPhotosText(AttachPhotoUtils.kt:7)
E/CreateNotesUpload(17531):     at de.westnordost.streetcomplete.data.osmnotes.SingleCreateNoteUploader.createNote(SingleCreateNoteUploader.kt:37)
E/CreateNotesUpload(17531):     at de.westnordost.streetcomplete.data.osmnotes.SingleCreateNoteUploader.upload(SingleCreateNoteUploader.kt:33)
E/CreateNotesUpload(17531):     at de.westnordost.streetcomplete.data.osmnotes.CreateNotesUploader.uploadSingle(CreateNotesUploader.kt:81)
E/CreateNotesUpload(17531):     at de.westnordost.streetcomplete.data.osmnotes.CreateNotesUploader.upload(CreateNotesUploader.kt:45)
E/CreateNotesUpload(17531):     at de.westnordost.streetcomplete.data.upload.QuestChangesUploadService.onHandleIntent(QuestChangesUploadService.kt:86)
E/CreateNotesUpload(17531):     at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:65)
E/CreateNotesUpload(17531):     at android.os.Handler.dispatchMessage(Handler.java:102)
E/CreateNotesUpload(17531):     at android.os.Looper.loop(Looper.java:136)
E/CreateNotesUpload(17531):     at android.os.HandlerThread.run(HandlerThread.java:61)
E/CreateNotesUpload(17531): Caused by: javax.net.ssl.SSLHandshakeException: javax.net.ssl.SSLProtocolException: SSL handshake aborted: ssl=0x7ce3d960: Failure in SSL library, usually a protocol error
E/CreateNotesUpload(17531): error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure (external/openssl/ssl/s23_clnt.c:744 0x746c7d74:0x00000000)
E/CreateNotesUpload(17531):     at com.android.org.conscrypt.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:449)
E/CreateNotesUpload(17531):     at com.android.okhttp.Connection.upgradeToTls(Connection.java:146)
E/CreateNotesUpload(17531):     at com.android.okhttp.Connection.connect(Connection.java:107)
E/CreateNotesUpload(17531):     at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:294)
E/CreateNotesUpload(17531):     at com.android.okhttp.internal.http.HttpEngine.sendSocketRequest(HttpEngine.java:255)
E/CreateNotesUpload(17531):     at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:206)
E/CreateNotesUpload(17531):     at com.android.okhttp.internal.http.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:345)
E/CreateNotesUpload(17531):     at com.android.okhttp.internal.http.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:89)
E/CreateNotesUpload(17531):     at com.android.okhttp.internal.http.HttpURLConnectionImpl.getOutputStream(HttpURLConnectionImpl.java:197)
E/CreateNotesUpload(17531):     at com.android.okhttp.internal.http.HttpsURLConnectionImpl.getOutputStream(HttpsURLConnectionImpl.java:254)
E/CreateNotesUpload(17531):     at de.westnordost.streetcomplete.data.osmnotes.StreetCompleteImageUploader.upload(StreetCompleteImageUploader.kt:35)
E/CreateNotesUpload(17531):     ... 10 more
E/CreateNotesUpload(17531): Caused by: javax.net.ssl.SSLProtocolException: SSL handshake aborted: ssl=0x7ce3d960: Failure in SSL library, usually a protocol error
E/CreateNotesUpload(17531): error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure (external/openssl/ssl/s23_clnt.c:744 0x746c7d74:0x00000000)
E/CreateNotesUpload(17531):     at com.android.org.conscrypt.NativeCrypto.SSL_do_handshake(Native Method)
E/CreateNotesUpload(17531):     at com.android.org.conscrypt.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:406)
E/CreateNotesUpload(17531):     ... 20 more
```

My first guess was that the errors above might mean unknown SSL certificate on upload server. Having a look at the source code gave me the impression that https://westnordost.de/streetcomplete/photo-upload/ is the relevant service url.

Running `openssl s_client  -showcerts -connect westnordost.de:443 </dev/null` seems to suggest the site use regular letsencrypt certificates, which I assume android should recognize. Never the less, I tested manually adding the certificates to android's trust store, but with no luck.

Collecting pcaps on my router verifies that the phone is indeed trying to talk to 62.108.32.100.

I'm out of ideas on how to debug this any further.

**Versions affected**
Android 4.4.3
StreetComplete v18.0

**Comment by westnordost** [comment]
Since when did you notice that pictures cannot be uploaded anymore? The last upload I see was at 17:18:01 today.

The SSL certificate of the site looks fine.

Looking at that you have quite an old version of Android, did it ever work for you?

**Comment by westnordost** [comment]
I can't reproduce it on my Android 5.1

**Comment by westnordost** [comment]
Okay, searched for it and found that Android versions below 5.0 are unable to communicate over HTTPS with servers that do not allow SSL 3.0 by default.

Use of SSL 3.0 was disallowed by the standard due to security vulnerabilities in 2015. See https://tools.ietf.org/html/rfc7568

**Comment by westnordost** [comment]
Currently, **0.6%** of StreetComplete users from Google Play still use an Android version below 5.0. I am not sure if trying to find a workaround is worth it.

**Comment by nospam3059** [comment]
I'm not in the market of replacing an otherwise perfectly fine, working good phone before it starts failing. Would love it if we could find some constructive way to improve StreetComplete regarding this.

What are your thoughts about the error being silently ignored and only visible when using logcat? Have you considered catching exceptions like these and present some kind of user feedback when they happen?

Who knows, maybe next time a similar change happens a larger portion of the user base might be affected? I would had loved to have gotten some feedback already when the first image upload failed, rather than figuring out what happened now first after five notes from different places have gotten stuck.

Am I understanding it correctly that all other uploads go to osm-servers, and it's merely pictures for notes that go to westnordost.de? (I have 375 stars, which were successfully uploaded)

Did you find a reference to the cause? Is this the relevant bug report: [https://github.com/square/okhttp/issues/4053](https://github.com/square/okhttp/issues/4053) ?

**Comment by smichel17** [comment]
At least for now, maybe just disable the camera for notes on old Android devices?

**Comment by nospam3059** [comment]
How about having the app use a configurable value rather than hard coding SC_PHOTO_SERVICE_URL, allowing users to setup their own sc-photo-service?

**Comment by westnordost** [comment]
Well, apparently there is one or several workarounds for this, I didn't look too deep into this. The OkHttp issue you link is related, however the app does not use OkHttp but simply HttpUrlConnection. One apparently quite easy solution is to use some gms google service stuff that exchanges the system default with a modern SSL-thingy, however, we can't use that because as far as I know this is part of google play services, which is not used in this app and for apps on F-Droid.

Because of the really low number of users still using <= 4.4, I didn't look much into this yet though. A PR is of course welcome!

> Am I understanding it correctly that all other uploads go to osm-servers, and it's merely pictures for notes that go to westnordost.de?

Yes, correct.


> How about having the app use a configurable value rather than hard coding SC_PHOTO_SERVICE_URL, allowing users to setup their own sc-photo-service?

It would almost be easier to just create a custom version of the app for yourself, that simply exchanges the https:// url with a http:// url.

**Comment by westnordost** [comment]
By the way, what is your device? I wonder what kind of devices hold out that long. How many times did you change the battery?

**Comment by HolgerJeromin** [comment]
>> Am I understanding it correctly that all other uploads go to osm-servers, and it's merely pictures for notes that go to westnordost.de?

> Yes, correct.

And the https://www.westnordost.de/streetcomplete/banned_versions.txt !

**Comment by nospam3059** [comment]
I fully agree it's unreasonable to do intrusive workarounds, like e.g. bundling backported libraries just for ancient devices. I am also thankful and happy the app actually runs great and is mostly useful on older devices.

With that said, what I ideally would like to see is improved resilience in recovering data from states like these. Be it configuring to use another server, exporting failed notes and images to the sdcard or something smart I can not think of. Something flexible enough to get people out of other trouble, be it broken networks, unability to authorize against OSM or whatever.

We'll see if I ever manage to contribute a patch, or even build my owned custom version. I got past the hurdle of gradle yesterday, but stopped short of installing the SDK version providing Kotlin.

My device is a Yotaphone2. Great hardware, but horrible software. Supposedly it should be able to run newer android, but that seems to be with the cost of losing the e-ink screen, which kind of is it's primary feature. The special hardware made it ship with an older android than it's contemporary Lollipop devices, and I bought it new at the end of it's sales-life-cycle in 2017. The screen is great!

**Comment by westnordost** [comment]
> We'll see if I ever manage to contribute a patch, or even build my owned custom version. I got past the hurdle of gradle yesterday, but stopped short of installing the SDK version providing Kotlin.

Hmm, if you get android studio, all that you need should be downloaded automatically through the SDK manager. (i.e. is suggested when you try to build and it fails because a dependency is missing)

> With that said, what I ideally would like to see is improved resilience in recovering data from states like these.

Well, it kind of is resilient already in that that an error during image upload does not cancel the whole upload process. It used to be like that.

**Comment by westnordost** [comment]
I've now disable photo upload for Android <5 because I will unlikely implement a workaround for devices below Android 5 (if there is one).
If anyone who reads this wants to do this, a PR can be opened for this.
