### ISSUE TITLE
Re-add double tap to zoom on map

### ISSUE THREAD

**Issue by grrrrr** [westnordost/StreetComplete#1773]
**Use case**

With previous versions of StreetComplete (<18.0), it was possible to zoom into the map by double tapping on an area.  With recent updates this feature looks to have been removed.

I would like to see tap to zoom re-added.   As a left handed person I found the functionality very useful to zoom in on the map on large phones,  as stretching to reaching the on screen zoom in / out buttons is quite difficult one handed

**Comment by westnordost** [comment]
As a left handed person, have you considered to switch your phone to left-handed mode?

**Comment by grrrrr** [comment]
Yes but for the most part I am fine as is,  this is one of the few instances where it's a little bit of a, " I wish the old functionality was still there"

The double tap also had the benefit of zooming in on the area you tapped,  not just the center of screen as is with the soft buttons.

**Comment by westnordost** [comment]
OK, I'm not sure why I removed it. It's back in for the next version.
