### ISSUE TITLE
Add a fixme quest

### ISSUE THREAD

**Issue by peternewman** [westnordost/StreetComplete#1775]
### General
Affected tag(s) to be modified/added:

[Fixme](https://wiki.openstreetmap.org/wiki/Key:fixme)

Possibly also [Note](https://wiki.openstreetmap.org/wiki/Key:note)

### Checklist
Checklist for quest suggestions (see guidelines):
- [x] 🚧 To be added tag is established and has a useful purpose
- [ ] 🤔 Any answer the user can give must have an equivalent tagging (Quest should not reappear to other users when solved by one) - How does this currently work with traditional notes?
- [ ] 🐿️ Easily answerable by everyone from the outside but a survey is necessary - Hard to tell
- [ ] 💤 Not an overwhelming percentage of elements have the same answer (No spam) - Hard to tell - Yes https://taginfo.openstreetmap.org/keys/?key=fixme
- [ ] 🕓 Applies to a reasonable number of elements (Worth the effort) - Yes https://taginfo.openstreetmap.org/keys/?key=fixme

### Ideas for implementation
Just clone the existing "do you have anything to add to this note" one.

**Comment by westnordost** [comment]
And how would you "add" something to a fixme?

By default, only notes with a question mark in the text are shown. How many fixmes have a question mark in its text? And how many of those are instances where a StreetComplete user can add any useful information?

> How does this currently work with traditional notes?

If the note discussion already contains a comment from the user, it is not shown.

**Comment by peternewman** [comment]
> And how would you "add" something to a fixme?

Append to the existing text for example, perhaps with a "<Username>: <comment>" style.

Although I appreciate you'd probably need another tag like fixme:streetcomplete=<date> to avoid spamming the next user.

> By default, only notes with a question mark in the text are shown. How many fixmes have a question mark in its text? And how many of those are instances where a StreetComplete user can add any useful information?

Ah that's rather neat, not great, but not terrible TBH, for the top 999 values worldwide, the question marked ones are:
```
name?
Where does Public Footpath go from here?
building?
What is this?
old mine workings?
access rights?
Where does the public footpath go from here?
what are these?
path?
?trace?
```

And top ten total:
```
add full address
add precise address where possible
incomplete
Longer than this
stub
continue
check
yes
resurvey
check on ground
Review with an on-ground survey. These may actually be solar thermal instead of PV.
```

So yeah maybe not quite so good...

Same style spreadsheet as postboxes:
https://docs.google.com/spreadsheets/d/174ghq3UzwuxrU_WDVUbxwQoEHNrFtBkSolAq0M74XN8/edit?usp=sharing

**Comment by westnordost** [comment]
> Append to the existing text for example, perhaps with a ": " style.
> Although I appreciate you'd probably need another tag like fixme:streetcomplete= to avoid spamming the next user.

Yes, that would be necessary, but StreetComplete should not invent own tags. Within the fixme/note sphere of tags, it might be okay, but it doesn't feel right.

Thank you for the analysis in the spreadsheet. It looks like, only the tiny fraction of fixme-values do contain a question mark and of this again only a tiny fraction is really a legible question that would be answerable on a survey.
So, only very few fixmes would lead to a proper quest (-> not worth the effort) but more importantly, there'd be many false positives where users are prompted to "contribute" something to a fixme where the fixme ist just something like "continue?" or "position?" where the user cannot be expected to understand what it is about.

So, this is not eligible for a quest in StreetComplete

**Comment by peternewman** [comment]
> > Append to the existing text for example, perhaps with a ": " style.
> > Although I appreciate you'd probably need another tag like fixme:streetcomplete= to avoid spamming the next user.
> 
> Yes, that would be necessary, but StreetComplete should not invent own tags. Within the fixme/note sphere of tags, it might be okay, but it doesn't feel right.

Yep, fair enough.
 
> Thank you for the analysis in the spreadsheet. It looks like, only the tiny fraction of fixme-values do contain a question mark and of this again only a tiny fraction is really a legible question that would be answerable on a survey.
> So, only very few fixmes would lead to a proper quest (-> not worth the effort) but more importantly, there'd be many false positives where users are prompted to "contribute" something to a fixme where the fixme ist just something like "continue?" or "position?" where the user cannot be expected to understand what it is about.

Continue is actually explicitly called out in the documentation as valid:
https://wiki.openstreetmap.org/wiki/Key:fixme#Examples
 
> So, this is not eligible for a quest in StreetComplete

Understood.

I've raised an issue in the OSM GitHub instead to try and fix the problem at source:
https://github.com/openstreetmap/openstreetmap-website/issues/2588

Which would generally improve StreetComplete's note behavior, and hopefully give a potential way to progress this particular suggestion in future.
