### ISSUE TITLE
Improve the postbox collection time form

### ISSUE THREAD

**Issue by peternewman** [westnordost/StreetComplete#1776]
**Use case**
Currently the postbox collection time quest defaults to collections for Mo-Sa, in reality over 61% of current values (looking at the top 999 values) are Mo-Fr, with only 15% being Mo-Sa, so most people are either having to deselect Sa, or potentially submit invalid data.

**Proposed Solution**
Default to Mo-Fr when you open the form.

As a bonus, if you've completed a Mo-Fr, it would be nice if when you added the next collection it default to just Sa ticked (over 40% have Mo-Fr+Sa), it could then move onto Su.

Stats:
https://docs.google.com/spreadsheets/d/1twJhvSKajD2vtn71AEPF0e3_o2gUz3mf6qaNcytkVjM/edit?usp=sharing

**Comment by westnordost** [comment]
> in reality over 61% of current values (looking at the top 999 values) are Mo-Fr

In which country? When the workweek starts and how long it is is different from country to country.


Currently, the preset is set to 
[firstDayOfWorkweek](https://github.com/westnordost/StreetComplete/blob/master/res/country_metadata/firstDayOfWorkweek.yml) + [regularShoppingDays](https://github.com/westnordost/StreetComplete/blob/master/res/country_metadata/regularShoppingDays.yml), the same as for opening hours.

**Comment by peternewman** [comment]
> > in reality over 61% of current values (looking at the top 999 values) are Mo-Fr
> 
> In which country? When the workweek starts and how long it is is different from country to country.

That was for the whole map, via TagInfo, but it looks like the UK is responsible for a quarter of the overall tag usage:
https://taginfo.openstreetmap.org.uk/keys/collection_times#overview

My overpass skills aren't clever enough to see how that data varies if you only look at postboxes for example.

> Currently, the preset is set to
> [firstDayOfWorkweek](https://github.com/westnordost/StreetComplete/blob/master/res/country_metadata/firstDayOfWorkweek.yml) + [regularShoppingDays](https://github.com/westnordost/StreetComplete/blob/master/res/country_metadata/regularShoppingDays.yml), the same as for opening hours.

Ah, I'd suggest in the UK at least, there's a difference between most shops and "business" oriented stuff, so post boxes, banks (estate agents) etc who will have regular hours Mo-Fr, and then reduced or non-existent hours at the weekends, often something on Saturday and shut Sunday.

For example see:
https://en.wikipedia.org/wiki/Business_hours
https://www.bankopeningtimes.co.uk/

Unfortunately I can't find a definitive list of stuff but perhaps a few others could feed in to see if this is generally true or the UK is a special case. Although obviously the current situation might make some things more complicated.

From your link ( https://en.wikipedia.org/wiki/Workweek_and_weekend#Around_the_world ), the vast majority of countries seem to have a five day working week, and the majority of those Mo-Fr, which would suggest a lot of people must work then. Would it not therefore make sense to have different default opening hours for "offices" from "shops"?

**Comment by westnordost** [comment]
> Ah, I'd suggest in the UK at least, there's a difference between most shops and "business" oriented stuff, so post boxes, banks (estate agents) etc who will have regular hours Mo-Fr, and then reduced or non-existent hours at the weekends, often something on Saturday and shut Sunday.

Okay, so in the UK, most shops will have identical opening hours from Monday to Saturday, but offices will have working hours from Monday to Friday?

Then, the best solution would be to create another file called `workweek.xml` in https://github.com/westnordost/StreetComplete/tree/master/res/country_metadata and fill in the info from https://en.wikipedia.org/wiki/Workweek_and_weekend#Around_the_world into it. Then, use this info in the collection times quest.

Do you want to help? Then, you could create this file `workweek.xml` in a PR, and I do the rest (adapt quest etc.)

**Comment by smichel17** [comment]
I assume that's a typo/autocorrect and you meant `workweek.yml`?

**Comment by peternewman** [comment]
> > Ah, I'd suggest in the UK at least, there's a difference between most shops and "business" oriented stuff, so post boxes, banks (estate agents) etc who will have regular hours Mo-Fr, and then reduced or non-existent hours at the weekends, often something on Saturday and shut Sunday.
> 
> Okay, so in the UK, most shops will have identical opening hours from Monday to Saturday, but offices will have working hours from Monday to Friday?

Yes, for some definition of shops and offices, with post boxes (and possibly post offices), banks, estate agents being in the Mo-Fr list. I can advise better on others after the situation finishes and stuff starts to return to normal.

> Then, the best solution would be to create another file called `workweek.xml` in https://github.com/westnordost/StreetComplete/tree/master/res/country_metadata and fill in the info from https://en.wikipedia.org/wiki/Workweek_and_weekend#Around_the_world into it. Then, use this info in the collection times quest.

Sounds good, and as above, hopefully in a subset of opening hours quests too.

> Do you want to help? Then, you could create this file `workweek.xml` in a PR, and I do the rest (adapt quest etc.)

Okay great thanks, will do. Do you mean .xml, or .yml like the others?

@matkoniecz I see you also did this for Poland in #702/#296/#306.

**Comment by westnordost** [comment]
> Okay great thanks, will do. Do you mean .xml, or .yml like the others?

Sorry I meant .yml

**Comment by natrius** [comment]
In austria postbox collections times are usally Mo-Fr, at least what i tagged until now. Just additional input.

**Comment by peternewman** [comment]
Work week data added in #1789.

**Comment by peternewman** [comment]
Thanks @westnordost .

What are your thoughts on my other part:
> As a bonus, if you've completed a Mo-Fr, it would be nice if when you added the next collection it default to just Sa ticked (over 40% have Mo-Fr+Sa), it could then move onto Su.

I appreciate this will also vary by country. For postboxes there is some detail here:
https://wiki.openstreetmap.org/wiki/Key%3Acollection_times#Images

I know there was discussion of similar stuff here https://github.com/westnordost/StreetComplete/issues/702#issuecomment-346147117

For postboxes from those images, it's a lot more clear cut (and we can look at existing mapping data). I.e. generate a field for if collection times has one time (i.e. LAST collection time as per the UK, Italy), or multiple collection times (Germany, America, Belarus). Defaulting to the current behaviour of not moving on.

I think for shops and the other stuff discussed in #702 you could differentiate countries which have a siesta from those which don't. Or explicitly add/whitelist countries where opening hours are primarily normalised. If the automatic behaviour is also cancelled if the default is unset I think that covers a lot of the edge cases. So if I enter collection times for just Mo-We on the form (i.e. deselect Th-Fr), it won't try and guess what I'm going to enter next.

I think it shouldn't be too challenging to gather some more info on this too if you're onboard with the principal?

**Comment by westnordost** [comment]
I think that's too much work for too little gain. I won't do it, if you have a special interest there, you can try to implement it.
