### ISSUE TITLE
[traduction] mistake in French for the max weight quest

### ISSUE THREAD

**Issue by letypequividelespoubelles** [westnordost/StreetComplete#1779]
Hi all, 
there is a traduction mistake in Franch for the max weight quest, when we select the option "there is no sign". It's "Il n'y a pas de panneau" instead of "Il n'y a**s** pas de panneau". 
If someone want to show me where is it in the code, I could change it.

Thank you all for this amazing app !

**Comment by smichel17** [comment]
Translation info is here :)

https://github.com/westnordost/StreetComplete/blob/master/CONTRIBUTING.md#translating-the-app

**Comment by letypequividelespoubelles** [comment]
Perfect, I did it, thanks :)
