### ISSUE TITLE
Describe what happened to photos in notes

### ISSUE THREAD

**Issue by pyrog** [westnordost/StreetComplete#1781]
**Use case**
I use SC to take notes with photos.

* Is there a local backup in the smartphone memory ?
* Where are they uploaded ?
* At what resolution ?
* Are they stored forever ?
* Is it possible to choose the online storage ?

It didn't found answers to these questions in the Faq.

**Workflow of photos**
If I understand correctly, it seem that the workflow is:

1. Create a note and add photos.
1. Note is uploaded to OSM and photos are resized and uploaded to [westnordost.de](https://westnordost.de/)
1. Notes and pictures are visible on OSM website, [NotesReview](https://ent8r.github.io/NotesReview/)…
1. An OSM contributor resolve the note and close it.
1. Pictures are discarded from [westnordost.de](https://westnordost.de/)

**Issues**
- Picture seem resized to 554x312 (original size 4032x2268)<br >It's difficult or impossible to read i.e street numbers
- Some pictures seem lost (See #1768)

**Proposed Solution**
- Document the exact process somewhere.
- Warn user that images could ou will be deleted.
- Provide options in settings to:
  - Set the resolution of picture, or warn the user if it's not full resolution
  -  Choose an online storage and a way to log in.<br /> Could be Mapillary, [Wikimedia Commons](https://commons.wikimedia.org/wiki/Special:UploadWizard),…<br />See #1780.
  - Backup pictures locally in smartphone's gallery or warn user that images could be lost<br />See #1768

**Comment by westnordost** [comment]
Photos are resized to a max resolution of 1280x1280px and a JPEG quality of 80%. 554x312 seems like somewhat of an odd size. Could you link the note in which this happened? Maybe it is a bug.

**Comment by pyrog** [comment]
Sorry, I read properties in Safari web browser 😞 

Size is 1280 x 720 (or 720 x 1280)

**Comment by westnordost** [comment]
I'll close this issue in favor of #1788

**Comment by pyrog** [comment]
Notes with photos is a really good feature 😎 

It allow to share pictures with others OSM users.
Some of theses pictures could be kept and associated with OSM objects.
Permanent storage could be Mapillary, Wikimedia Commons and also [Panoramax](https://panoramax.openstreetmap.fr/#focus=pic&map=18.47/48.8533495/2.3488051&pic=cbc0f10b-c98b-4ac0-aaf8-cc9f281aaac1&speed=250&xyz=338.75/2.12/30) (multi instances Street View, FOSS).
