### ISSUE TITLE
AddRecyclingContainerMaterialsForm.kt - spelling mistakes

### ISSUE THREAD

**Issue by mueschel** [westnordost/StreetComplete#1783]
The AddRecyclingContainerMaterialsForm quests asks to add "recycling:electric_appliances" as key, but this key is not used anywhere.

We have plenty other keys for the large and small devices already:

4000x recycling:electrical_appliances
3700x recycling:small_appliances
1000x recycling:electrical_items
560x recycling:small_electrical_appliances

**Comment by westnordost** [comment]
Oh damn, you are right. This ticket will remain open until well after the fix was released so that I remember to manually clean up the mistaggings.

**Comment by westnordost** [comment]
I find very very few usages of `recycling:electric_appliances` on taginfo, have you been correcting them? If yes, to what tag?

**Comment by westnordost** [comment]
Tags used in combination with `recycling_type = container`:

| tag | yes | no | documented in wiki |
| ---- | ---- | ---- | ----- |
| `recycling:small_appliances` | 745 | 1424 | listed but without explanation. Probably any small appliances, whether electrical or not |
| `recycling:small_electrical_appliances` | 463 | 10 | described as pretty much what is shown to the user in StreetComplete:  <br/><img src ="https://user-images.githubusercontent.com/4661658/79780671-8a500d80-833c-11ea-8632-b97f0f89da05.png"/> |
| `recycling:electrical_appliances` | 490 | 1641 | described as "large" appliances, like freezers |

Thus, I conclude that `recycling:small_electrical_appliances` is the correct tag to use.

**Comment by mueschel** [comment]
Yes, I corrected a couple of them. I didn't notice that it's from a software issue, so I treated them like a simple spelling mistake and corrected them to the closest tag, 'electrical_appliances'.

Seems like there are 12 nodes where I'm the last editor:
http://overpass-turbo.eu/s/T5C

**Comment by westnordost** [comment]
Ah okay, as researched, I think these should actually be `recycling:small_electrical_appliances` because that is what is shown to the user.

**Comment by Lukas458** [comment]
The tagging of "electric containers" is a bit weird, yes.

But I think what has to be differentiated are really the "big" electrical applicances and the "small" ones.

So when looking at tagging:
- recycling:white_goods are _only_ the "really big" ones

- recycling:electrical_items and recycling:electrical_appliances are the same, small _and_ big electricals. Maybe I make a discussion on tagging to merge them.

- recycling:small_appliances is used for/to mean quite the same as recycling:small_electrical_appliances I think, but that's not clear from the key and so the tag whithout the "electrical" part is not so useful.

Also, when choosing recycling:electrical_appliances for the small _and_ the big ones, then the key for only the small ones should be recycling:small_electrical_appliances, and not recycling:small_appliances or something else. So westnordost is right.

**Comment by westnordost** [comment]
This can be closed now. In taginfo, I see no more occurances of `recycling:electric_appliances` and v19 has been out for a while.
