### ISSUE TITLE
Hail & Ride/Hail and Ride Bus Stop Quests

### ISSUE THREAD

**Issue by peternewman** [westnordost/StreetComplete#1784]
StreetComplete incorrectly offers quests of shelter and tactile paving for hail and ride stops which don't really exist.

https://en.wikipedia.org/wiki/Hail_and_ride

**How to Reproduce**
Search for a Hail and Ride:
https://www.openstreetmap.org/search?query=Hail and Ride

See the quests exist, whereas it should be hidden in those cases.

From what I can tell officially these stops shouldn't exist and there's some way to tag the way relationship into the route instead, although the documentation for that is pretty non-existent, but others advise it's required for "It exists for routing and timetable purposes only."
https://www.openstreetmap.org/note/2165209

**Versions affected**
Android 9, SC v18.0

**Comment by westnordost** [comment]
We can do nothing without a proper tagging for hail and ride bus stops. Also, why have bus stops for hail and ride at all? If it is hail and ride, there should not be bus stops at all, right?

**Comment by peternewman** [comment]
> We can do nothing without a proper tagging for hail and ride bus stops.

Can you not at least filter out the irrelevant stops, or can you not do wildcard filtering on the name field?

> Also, why have bus stops for hail and ride at all? If it is hail and ride, there should not be bus stops at all, right?

Yes, that was why I initially added a note in OSM and then struggled to find any clear notes on how it should be tagged instead.

This may be relevant:
https://wiki.openstreetmap.org/wiki/NaPTAN/Surveying_and_Merging_NaPTAN_and_OSM_data#physically_present
Or
http://overpass-turbo.eu/s/oNM
Or
https://wiki.openstreetmap.org/wiki/NaPTAN/Tag_mappings#Bus.2FCoach

**Comment by westnordost** [comment]
I find it a bit weird to have somethiing on a map that is not physically present at all.

But anyway, StreetComplete would not tag this stuff but just interpret it, so adding `physically_present != no` to the query is fine by me.

**Comment by peternewman** [comment]
> I find it a bit weird to have somethiing on a map that is not physically present at all.

Agreed, I can't personally see the correct way to tag it in the interim and I'm loath to remove it until we can represent the data in another way.

> But anyway, StreetComplete would not tag this stuff but just interpret it, so adding `physically_present != no` to the query is fine by me.

Thanks, I think also `naptan:BusStopType != HAR` as some seem to have that but not physically present.

However there are also others that have neither of these taggings and just "Hail & Ride" (>900) or "Hail and Ride" (~30) at the start or end of the name. Is it technically possible to exclude them too?

**Comment by smichel17** [comment]
> I find it a bit weird to have something on a map that is not physically present at all.

Agreed, to the point where I left this note: https://www.openstreetmap.org/note/2083607#map=19/42.32651/-72.67773

I can't see how that particular location is any more suitable to flag down a bus than any other location along the route.

**Comment by peternewman** [comment]
> Agreed, to the point where I left this note: https://www.openstreetmap.org/note/2083607#map=19/42.32651/-72.67773

I wonder if all the massDOT nodes from that import use the same name style, that might be another one to filter out? https://www.openstreetmap.org/node/1408377614

**Comment by harry-wg** [comment]
> I find it a bit weird to have somethiing on a map that is not physically present at all.

> I find it a bit weird to have somethiing on a map that is not physically present at all.

That may be hard to grasp, but mapping H&R stops does serve a useful purpose. If I had been visiting premises along the route, it would be quite annoying if the map directed me to walk a mile to the nearest mapped stop. Then the bus would take me back through the mile I had just walked and I hear that I could have hailed the bus right outside the place I started. 

Should maps **primarily** for the benefit of the mapper, or for the end user? I'd say the latter, and for that purpose H&R stops need to be **visible** at sensible intervals along the route -- we have some flexibility about how we achieve that, but we should not do so in a way that makes them disappear altogether.

Now, consider a possible analogy. Maps usually show town names at the approximate centre of the town. If you zoom in on a town name and visit the exact spot, you will probably not find a physical town name at that exact spot. The physical signposts for towns are generally on each entrance road at the boundary. So if a particular town has 8 roads crossing its boundary. should we unmap the name at the centre and replace it with 8 copies of the town names strategically placed along its boundary to reflect the physical signs? That would be extremely confusing.

H&R stops need to be visibly mapped somewhere. They should not disappear from the map just because there is no pole alongside the road.




It's actually similar to mapping a street name. Physically the street signs are likely to be at each *end* of the street, but the map will probably show it somewhere in the centre.

**Comment by peternewman** [comment]
@westnordost on a related note, `naptan:BusStopType=CUS` which apparently means customary, at least for some near me don't have a physical stop, so I guess would be good to change the wording there, or perhaps generally add a can't say which puts in a note to say this stop isn't visible on the ground, or possibly just filter them out too, I don't know how many of those really exist either.

> > I find it a bit weird to have somethiing on a map that is not physically present at all.
> 
> > I find it a bit weird to have somethiing on a map that is not physically present at all.
> 
> That may be hard to grasp, but mapping H&R stops does serve a useful purpose. If I had been visiting premises along the route, it would be quite annoying if the map directed me to walk a mile to the nearest mapped stop. Then the bus would take me back through the mile I had just walked and I hear that I could have hailed the bus right outside the place I started.
> 
> Should maps **primarily** for the benefit of the mapper, or for the end user? I'd say the latter, and for that purpose H&R stops need to be **visible** at sensible intervals along the route -- we have some flexibility about how we achieve that, but we should not do so in a way that makes them disappear altogether.
>
> It's actually similar to mapping a street name. Physically the street signs are likely to be at each _end_ of the street, but the map will probably show it somewhere in the centre.

That was what brought me here @harry-wg , after trying and failing to find any stuff on the OSM Wiki as to how to map these properly.

The street name is what it should do to map them properly for the benefit of the end user. The map should know that the whole road is H&R, so when I ask for routing from my house on that road, or on an adjacent road, it simply directs me to the first point I join that road and asks me to hail and ride. That also avoids the confusion of walking half way up the street for a non-existent bus stop. It would also mean it could show it for the entire duration of the H&R section at any zoom level if part of it was in view. There doesn't seem to be any clearly defined way for how to do this tagging, at least that I've been able to read and make sense of.

To apply your analogy, the street name is actually the behaviour it should have, the name is an attribute of the way, so regardless of my zoom level, it tells me the name of the street (imprinted on the road, which you certainly don't normally find in real life). You could also map the road signs themselves if you wanted, which as you say are usually only at the end of the road (incidentally that's also a regular failing in London, where they often aren't on the junctions). Whereas the town name mapping is the current behaviour we currently have, where I have to zoom out to some arbitrary level to see a nominal location of a non-existent but theoretically point where I can catch a bus.
