### ISSUE TITLE
Postbox Collection Time Separator (and possibly opening hours too)

### ISSUE THREAD

**Issue by peternewman** [westnordost/StreetComplete#1786]
The collection_times separator used by StreetComplete is a comma, e.g. `Mo-Fr 17:00, Sa 12:45`.

However everything seems to favour semicolon then space between days (including @rjw62 's reporting page, which initially flagged this up to me):
https://wiki.openstreetmap.org/wiki/Key:collection_times#Examples
https://wiki.openstreetmap.org/wiki/Key:opening_hours#Simple_examples
https://osm.mathmos.net/postboxes/osm-collection-times.html#details
https://projets.pavie.info/yohours/?oh=Mo-Fr%2009:00;%20Sa%2007:00 - Works
https://projets.pavie.info/yohours/?oh=Mo-Fr%2009:00,%20Sa%2007:00 - Doesn't work

Although the summary syntax says it would be two rulesets separated by a semicolon:
https://wiki.openstreetmap.org/wiki/Key:opening_hours#Summary_syntax

The supposed grammar has additional_rule_separator:
https://wiki.openstreetmap.org/wiki/Key:opening_hours/specification#Syntax_diagram

And seems to imply either would work:
https://wiki.openstreetmap.org/wiki/Key:opening_hours/specification#explain:additional_rule_separator

> An additional rule is treated exactly the same as a normal rule, except that an additional rule does not overwrite the day for which it applies (unlike the <normal_rule_separator> which starts always with a new, empty day, deleting any previous rules applying for the given day).

So clear as mud!

However in terms of normal usage, I added stats to my previous spreadsheet and it found no commas from when I did that snapshot:
https://docs.google.com/spreadsheets/d/1twJhvSKajD2vtn71AEPF0e3_o2gUz3mf6qaNcytkVjM/edit?usp=sharing

As mentioned, and given I believe they use the same code, opening hours may be affected too?

**How to Reproduce**
Fill in a postbox collection time quest with different times on different days.

**Versions affected**
Android 9, SC v18.0

This appears to be since SC 11 for some people:
https://www.openstreetmap.org/changeset/69425227

**Comment by westnordost** [comment]
This came up a couple of times and been discussed a couple of times, so I am closing this as duplicate.

> So clear as mud!

That's a matter of opinion. The `additional_rule_separator` reflects the real life intuitive usage, i.e. if you would copy 1:1 the opening hours plate on shops, that separator would be the one you would want to use. Example opening hours:

**_"Open Mo-Fr 8-12, Tu and Th 14-16"_**

Now, what do you think did the shop owner mean when he hang that plate, 
[`Mo-Fr 8:00-12:00, Tu,Th 14:00-16:00`](https://openingh.openstreetmap.de/evaluation_tool/?EXP=Mo-Fr%208%3A00-12%3A00%2C%20Tu%2CTh%2014%3A00-16%3A00&mode=0&) or 
[`Mo-Fr 8:00-12:00; Tu,Th 14:00-16:00`](https://openingh.openstreetmap.de/evaluation_tool/?EXP=Mo-Fr%208%3A00-12%3A00%3B%20Tu%2CTh%2014%3A00-16%3A00&mode=0&)

**Comment by peternewman** [comment]
> This came up a couple of times and been discussed a couple of times, so I am closing this as duplicate.

Sorry @westnordost I neglected to search and Github's possibly related issues thing didn't spot it. I guess for anyone else this covers it as well as others:
https://github.com/westnordost/StreetComplete/issues/773
 
> > So clear as mud!
> 
> That's a matter of opinion. The `additional_rule_separator` reflects the real life intuitive usage, i.e. if you would copy 1:1 the opening hours plate on shops, that separator would be the one you would want to use. Example opening hours:
> 
> **_"Open Mo-Fr 8-12, Tu and Th 14-16"_**
> 
> Now, what do you think did the shop owner mean when he hang that plate,
> [`Mo-Fr 8:00-12:00, Tu,Th 14:00-16:00`](https://openingh.openstreetmap.de/evaluation_tool/?EXP=Mo-Fr%208%3A00-12%3A00%2C%20Tu%2CTh%2014%3A00-16%3A00&mode=0&) or
> [`Mo-Fr 8:00-12:00; Tu,Th 14:00-16:00`](https://openingh.openstreetmap.de/evaluation_tool/?EXP=Mo-Fr%208%3A00-12%3A00%3B%20Tu%2CTh%2014%3A00-16%3A00&mode=0&)
> ?

Yeah I can see your point there. I'd suggest collection times are far less likely to be ambiguous, but I appreciate you'd probably like the code to stay constant between them.

> Also, yohours is not maintained anymore, as far as I know.

Ah, it's still the main thing linked in tools:
https://wiki.openstreetmap.org/wiki/Key:opening_hours#More_maps_and_applications

Whereas the other one is just in see also:
https://wiki.openstreetmap.org/wiki/Key:opening_hours#See_also

@rjw62 given this, would you be willing to update your page to also include comma?

**Comment by rjw62** [comment]
> @rjw62 given this, would you be willing to update your page to also include comma?

Now done: https://osm.mathmos.net/postboxes/osm-collection-times.html

**Comment by peternewman** [comment]
> > @rjw62 given this, would you be willing to update your page to also include comma?
> 
> Now done: https://osm.mathmos.net/postboxes/osm-collection-times.html

Brilliant thanks @rjw62 . It looks a lot happier now!
