### ISSUE TITLE
Make app movable to SD card

### ISSUE THREAD

**Issue by yegorich** [westnordost/StreetComplete#1787]
**Use case**

I'm on a rather old Android 6 smartphone with very limited flash capacity. So it would be very practical to make the app installable/movable to the external memory (SDcard). The same is true for the map cache. 

**Proposed Solution**

The solution for the map cache would be an option configuring the storage path.

**Comment by westnordost** [comment]
I am surprised that it is not possible but checked on my phone, and the button to move it is greyed out (as well). I did a quick search whether there are any requirements for apps to be movable, but did not find anything.

**Comment by westnordost** [comment]
So, any help here would be appreciated (by people with small internal memory)

**Comment by Atrate** [comment]
```
Application developers can set the field android:installLocation in the root manifest element to one of these values:

    internalOnly: Install the application on internal storage only. This will result in storage errors if the device runs low on internal storage.

    preferExternal: The android system tries to install the application on external storage. If that is full, the application is installed on internal storage.

    auto: Let the Android system decide the best install location for the application. The default system policy is to install the application on internal storage first. If the system is running low on storage, the application is then installed on external storage.
```

Old but still relevant?

https://android-developers.googleblog.com/2010/07/apps-on-sd-card-details.html

**Comment by westnordost** [comment]
Hm, the install location is not set in the manifest, so it defaults to auto. Which makes sense. There is no reason for the app to either prefer external memory or internal memory.

**Comment by Atrate** [comment]
> The auto option sounds like the system would automatically decide to move it to external if there is not enough space?

Sounds like it but never noticed it happen on older (4, 5, 6) devices

**Comment by Mortein** [comment]
Here's the official doc: https://developer.android.com/guide/topics/data/install-location

The default if not specified in the manifest is internal storage only and the app cannot be moved.

**Comment by westnordost** [comment]
Ah right, then I will specify it to "auto"

**Comment by westnordost** [comment]
Thanks for the link!
