### ISSUE TITLE
v19.0-alpha2 : typo in German translation

### ISSUE THREAD

**Issue by agschaid** [westnordost/StreetComplete#1790]
There is a typo in the German translation.
**How to Reproduce**

Mein Profil (My Profile) -> Trophy Icon -> "erste Aufgabe gelöst" (probably the left uppermost trophy)

"...Im Profilbereich kannst du mehr zu **dienen** gelösten Aufgaben einsehen."
It should read "deinen"

**Versions affected**

Affected: v19.0-alpha2 on LineageOS 16

**Comment by HolgerJeromin** [comment]
Thanks for reporting. I have just fixed it. Will be included in the next version.

**Comment by westnordost** [comment]
thanks
