### ISSUE TITLE
Mark the quest to be answered in order to avoid confusion

### ISSUE THREAD

**Issue by cyclingcat** [westnordost/StreetComplete#1792]
Hi there,

if there are several quests of the same kind in close proximity, it's maybe difficult (if not impossible) to distinguish between them while trying to answer the quest.

See the following screenshot as an example, taken some hours ago in my neighbourhood:

![which_one](https://user-images.githubusercontent.com/32601012/80314458-ed84e880-87f1-11ea-990a-40fa28041935.png)

Which of the three quests is the one the user is currently answering? (And I've seen comparable situations with 5 or 6 of the same icons side by side, often parkings or benches, but missed taking screenshots.)

**Suggestion:**
Mark the current quest somehow, for example with a small overlay icon attached to it or a red circle around it (sorry, I'm not a graphics man):

![this_one](https://user-images.githubusercontent.com/32601012/80314594-c0850580-87f2-11ea-8987-a360c80ac74c.png)

The cycling cat

**Comment by westnordost** [comment]
the place is higlighted in blue. Also, the view zooms to the place.

![image](https://user-images.githubusercontent.com/4661658/80315050-8ec16e00-87f5-11ea-8177-0de98e766ab3.png)

**Comment by cyclingcat** [comment]
Okay, in this case people with better eyes than mine would be able to notice this on a sunlit display. I will try to look carefully on my display the next time. But what about the situations where the items to tag aren't areas (like the example shown above with the three parkings) but nodes (like the mentioned example with the benches)? If I will come across an example for the latter, I will take another screenshot (unfortunately I haven't the last time, but it shouldn't be too difficult to find one in the forests nearby, maybe next to a picnic area or a hiking car park).

The cycling cat

**Comment by westnordost** [comment]
I wanted to write that it's not really possible easily but then I had an idea how it would be and tried it out. It's okay, I do not think it helps the visibility a lot, but maybe a little.

![image](https://user-images.githubusercontent.com/4661658/80415527-f5688980-88d2-11ea-8c11-9824142b3e6f.png)

**Comment by smichel17** [comment]
I got a bug with this where it did not appear in quite the right spot:

![image](https://user-images.githubusercontent.com/6563664/80653844-0b985600-8a49-11ea-9de3-2008dc06ae43.png)

**Comment by westnordost** [comment]
Already fixed on master
