### ISSUE TITLE
v19.0alpha1 should not be the recommended stable version on F-Droid

### ISSUE THREAD

**Issue by ati3** [westnordost/StreetComplete#1795]
F-Droid recommends the version 19.0-alpha1 as the new stable version. I have installed it, and it is obviously unstable. It crashed immediately, and I could not even downgrade it (I had to uninstall and install the previous version).

**Comment by HolgerJeromin** [comment]
This is a known issue:
https://github.com/westnordost/StreetComplete/releases/tag/v19.0-alpha2

**Comment by smichel17** [comment]
And seems to be an [f-droid bug](https://gitlab.com/fdroid/fdroidserver/-/issues/698#note_331152987), not @westnordost's fault.

**Comment by westnordost** [comment]
On top of that, it [looks like the F-Droid build bot is stuck since Friday](https://f-droid.org/wiki/index.php?title=Special:RecentChanges&days=7&from=&hidebots=0&hideanons=1&hideliu=1&limit=500), so the alpha2 update is not even coming through.

**Comment by westnordost** [comment]
I added another bug report because I think the one you commented on reads a little obscure and/or the F-Droid maintainers don't understand the big issue about the field not working

> "I would not consider it reliable, just a helper"

https://gitlab.com/fdroid/fdroidserver/-/issues/765

**Comment by westnordost** [comment]
And added a forum topic regarding the build bot being stuck, if it is:

https://forum.f-droid.org/t/f-droid-build-bot-stuck-since-friday/9563

**Comment by westnordost** [comment]
v19.0 is now on f-droid
