### ISSUE TITLE
Map returns to user location when closing Settings (v19.0)

### ISSUE THREAD

**Issue by pkoby** [westnordost/StreetComplete#1799]
First off, love love LOVE the new version! The quest download is amazing, the achievements are really cool, and the stats are super fun!

However: I was pre-downloading a new area (I'm going somewhere else to do quests, and I want to use wifi to download beforehand). I went to the Settings page, then when I went back to the map, it flung me back to my current location with the Locate button orange. I expected to be returned to the spot on the map where I was downloading previously. I think the map state (location, zoom) should retain the same parameters before adjusting settings. In this case, I don't have to do anything in the Settings, just go in and out.

I'm not sure if it did this before this version.

Also, unrelated, but if you tap the star in the corner, perhaps go to the Stats page?

**Comment by westnordost** [comment]
If the button is orange, it will fling you back to your position. You need to press it once so that it becomes black in order to not have the app return you to your location.

**Comment by pkoby** [comment]
I just checked. If it's orange and I drag away from my location, it turns black. I open Settings, close, the button turns orange and sends me back to my location.

If I am at my location and I tap the button to turn it black and then move the map, open Settings, close, it does the same thing, turning the button orange.

**Comment by westnordost** [comment]
Oh, okay. That's a bug then
