### ISSUE TITLE
French Translation complete

### ISSUE THREAD

**Issue by james2432** [westnordost/StreetComplete#18]
https://poeditor.com/projects/po_edit?id_language=50&id=97843

**Comment by westnordost** [comment]
Hooray, thank you very much! I pushed your translations.

I also reorganized the app translation-wise a bit and threw everything project related that can be translated into POEditor. Would you be so kind to have another look at POEditor? If you translate these strings, I can add this as the French description in Google Play - the first thing anyone is going to see who will want to download StreetComplete.

**Comment by james2432** [comment]
Done :)

**Comment by westnordost** [comment]
Very cool, French translation 110% complete.
