### ISSUE TITLE
Quest: pitches with unknown sport

### ISSUE THREAD

**Issue by PanierAvide** [westnordost/StreetComplete#180]
According to [Taginfo](https://taginfo.openstreetmap.org/tags/leisure=pitch#combinations), 19% of `leisure=pitch` features in OSM don't have a `sport=*` tag. A quest could allow users to define what kind of sport can be played on a given pitch. Graphically, it could be done like the roof shape quest, having [several sport symbols](https://commons.wikimedia.org/wiki/Category:Sports_pictograms) and user can choose one. Proposed values can be the [most used ones](https://taginfo.openstreetmap.org/keys/sport#values) (from most to least usage, and specific to pitches):
- soccer
- tennis
- baseball
- basketball
- golf
- equestrian
- athletics
- volleyball
- beachvolleyball
- american_football
- skateboard
- bowls
- boules
- shooting
- cricket
- table_tennis
- gymnastics

For pitch where multiple sports can be played, we have the `sport=multi` value, which may be linked to a specific button (like on roof shape quest). The difficult task here will be to find meaningful icons for each sport (to don't have to add the sport name as a string for each one), but I think it is something achievable.

**Comment by westnordost** [comment]
Good idea.

Some input:
- For icons, all the colors of the rainbow can be used to make it easier to recognize
- Instead of abstract "Olympic style" icons, displaying the play-thing (i.e. tennis bat with tennis ball etc) or representative photos will be more effective. Might also be easier to find?
- The amount of different sports may be a bit much, but I have a cool idea how to limit it to less: Analyze the shape and size of the pitch and X the most unlikely values based on this.
- Also, perhaps for later when there is better country detection: The order could be manipulated based on the country. I.e. in Myanmar, Chinlone pitches might be a thing?

On 4 May 2017 11:03:45 CEST, Adrien Pavie <notifications@github.com> wrote:
>According to
>[Taginfo](https://taginfo.openstreetmap.org/tags/leisure=pitch#combinations),
>19% of `leisure=pitch` features in OSM doesn't have a `sport=*` tag. A
>quest could allow users to define what kind of sport can be played on a
>given pitch. Graphically, it could be done like the roof shape quest,
>having [several sport
>symbols](https://commons.wikimedia.org/wiki/Category:Sports_pictograms)
>and user can choose one. Proposed values can be the [most used
>ones](https://taginfo.openstreetmap.org/keys/sport#values) (from most
>to least usage, and specific to pitches):
>- soccer
>- tennis
>- baseball
>- basketball
>- golf
>- equestrian
>- athletics
>- volleyball
>- beachvolleyball
>- american_football
>- skateboard
>- bowls
>- boules
>- shooting
>- cricket
>- table_tennis
>- gymnastics
>
>For pitch where multiple sports can be played, we have the
>`sport=multi` value, which may be linked to a specific button (like on
>roof shape quest). The difficult task here will be to find meaningful
>icons for each sport (to don't have to add the sport name as a string
>for each one), but I think it is something achievable.
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/westnordost/StreetComplete/issues/180

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by PanierAvide** [comment]
Yes it will be better to use icons symbolizing what you play with, in colour of course (in particular for distinguishing all spherical-ball sports). Is the country-detection already implemented in another quest ?

About the shape/size distinction, I'm not sure it is very pertinent. In fact, pitches respecting a given sport official rules will have a standard size. But for example in France's countryside, a lot of soccer pitches don't have the official size, and some are not even rectangular (like just the half of a complete pitch, with only one goal). I think it could give a lot of false positives. Maybe instead sports can be grouped (ball sports, racquet sports, others) ?

**Comment by westnordost** [comment]
> country detection

In add street name there is something, but not in the form you need it. I will be doing this in the quest-maxspeed branch. I am thinking about one countryInfo.json file per country (and a default one) which is a huge list of properties like speed_unit=kmh, maxurbanspeed=50, popularsports=soccer,.... etc.
One file because it's easier for translators and because only one file needs to be read for a language.

The thing with the sizes was just an idea, if the variance is too big, then it doesn't make sense to filtwr, yes. I was thinking about certain pitches that have very unique pitches (bowling??)

On 4 May 2017 12:54:26 CEST, Adrien Pavie <notifications@github.com> wrote:
>Yes it will be better to use icons symbolizing what you play with, in
>colour of course (in particular for distinguishing all spherical-ball
>sports). Is the country-detection already implemented in another quest
>?
>
>About the shape/size distinction, I'm not sure it is very pertinent. In
>fact, pitches respecting a given sport official rules will have a
>standard size. But for example in France's countryside, a lot of soccer
>pitches don't have the official size, and some are not even rectangular
>(like just the half of a complete pitch, with only one goal). I think
>it could give a lot of false positives. Maybe instead sports can be
>grouped (ball sports, racquet sports, others) ?
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/westnordost/StreetComplete/issues/180#issuecomment-299153247

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by PanierAvide** [comment]
OK, so we must wait for this configuration file before implementing the quest.

Even for bowling you can have false positive if pitches are not drawn individually, the global polygon will have the shape and size which could let us think that it is a small soccer pitch. The country-specific ordering approach seems to be more appropriate to filter values.

**Comment by althio** [comment]
You could have a conservative filter, which only remove the very unlikely options, as suggested in https://github.com/westnordost/StreetComplete/issues/180#issuecomment-299151063.

Or instead of filtering out, you could only order the options based on country and shape/size so that top proposal is more likely but you can still browse and scroll as much options as needed.

**Comment by westnordost** [comment]
No, we don't have to wait. This can be done later to further augment the quest with some intelligence.

**Comment by PanierAvide** [comment]
Some icons proposal:
- soccer : https://commons.wikimedia.org/wiki/File:Simple_Soccer_Ball.svg
- tennis : https://commons.wikimedia.org/wiki/File:Emojione_1F3BE.svg
- baseball : mix of https://commons.wikimedia.org/wiki/File:Baseball_bat.svg + https://commons.wikimedia.org/wiki/File:Baseball.svg
- basketball : https://commons.wikimedia.org/wiki/File:Basketball_Clipart.svg
- golf : https://commons.wikimedia.org/wiki/File:Nuvola_apps_kolf.svg
- equestrian : https://commons.wikimedia.org/wiki/File:Sinnbild_Reiter.svg
- athletics : https://commons.wikimedia.org/wiki/File:Olympic_Rings_black.svg
- volleyball : https://commons.wikimedia.org/wiki/File:Volleyball.svg
- beachvolleyball : https://thenounproject.com/search/?q=beach%20volleyball&i=550530
- american_football : https://commons.wikimedia.org/wiki/File:American_football_icon_simple.svg
- skateboard : https://commons.wikimedia.org/wiki/File:Noun_project_240.svg
- bowls : https://thenounproject.com/search/?similar=945119&i=945119
- boules : https://thenounproject.com/search/?q=p%C3%A9tanque&i=421460
- shooting : https://commons.wikimedia.org/wiki/File:Emoji_u1f52b.svg
- cricket : https://commons.wikimedia.org/wiki/File:Cricketball.svg
- table_tennis : https://commons.wikimedia.org/wiki/File:Table_tennis.svg
- gymnastics : https://thenounproject.com/search/?q=gymnastics&i=655094

**Comment by westnordost** [comment]
This looks like Kraut und Rüben (topsy-turvy), every icon has a different style. I suggest to take a set of as a base that defines the style and then go from there (find icons that fit to the style and/or make some yourself). For the latter, I might get around to help.

The EmojiOne 2 emoticons are free: https://github.com/Ranks/emojione/tree/2.2.7
and the Twitter Emoticons are free: https://github.com/twitter/twemoji

Both contain some sport icons like baseball, soccer, tennis, basketball etc. and have a very similar style. To get each the better ones of those would be a good starting point. I suggest to copy paste the icons into one SVG document like I did for the quest icons to have a better visual overview of what fits together and what not.

**Comment by HolgerJeromin** [comment]
Perhaps real Photos which shows the line markings would help.

**Comment by PanierAvide** [comment]
Done, here it is:
![sports](https://cloud.githubusercontent.com/assets/1349014/25909604/fec709be-35ad-11e7-85ad-c1e3faf21e55.png)

**Comment by westnordost** [comment]
Nice! I will just add them to the repos already then and perhaps add missing ones if there are any missing ones, so you can directly use them in your PR

**Comment by PanierAvide** [comment]
Great ! By my side, I have started to add the appropriate classes, let me know when icons are ready so I can include them. Also, I was thinking about the map icon for the quest, which background colour can be used ?

**Comment by westnordost** [comment]
Man, some of the SVGs are really low "code" quality. Got some problems exporting, please be patient.

I also take the oppurtunity to beautify them :-)

**Comment by westnordost** [comment]
Sorry, I am being carried away. Already started to add icons for less popular/regional sports which could i.e. turn up when the sports can be sorted by country.

![wip](https://cloud.githubusercontent.com/assets/4661658/25975976/f5b52dba-36b1-11e7-81cf-935e57461ff1.png)

Too late today, I will export them tomorrow.

Also, regarding the quest icon: I think "leisure" could get a new color, perhaps green?

**Comment by PanierAvide** [comment]
Woh, the icons looks great 👍 Green for leisure seems adapted.

**Comment by westnordost** [comment]
I added them finally to the repos...

...been researching a lot which sports are popular where, sorry for getting sidetracked.

**Comment by westnordost** [comment]
Regarding the icons: Are there any sources that need to be credited beyond twitter emoji and emoji one?

**Comment by PanierAvide** [comment]
The skateboard icon [comes from here](https://www.svgrepo.com/svg/113471/skateboard). The license is Creative Commons with No commercial use, but it is not clear which one precisely.

**Comment by westnordost** [comment]
Oh, then I need to replace it because this is incompatible with GPL / Cc by sa.

Am 15. Mai 2017 08:05:51 MESZ schrieb Adrien Pavie <notifications@github.com>:
>The skateboard icon [comes from
>here](https://www.svgrepo.com/svg/113471/skateboard). The license is
>Creative Commons with No commercial use, but it is not clear which one
>precisely.
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/westnordost/StreetComplete/issues/180#issuecomment-301384185

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by PanierAvide** [comment]
Oh sorry, I didn't knew about this license incompatibility. It was kind of hard to find a good-looking skateboard icon, as it is not available as an Unicode symbol (and consequently in emoji sets). Noun project has a few skateboards icons but single-colored. I think it will be faster for you to create one from scratch.

**Comment by rugk** [comment]
also see discussion at https://wiki.openstreetmap.org/wiki/Talk:Key:trees#Missing.2Fwrong_keys (about sports/leisure)
