### ISSUE TITLE
More informative message for empty Achievements tab

### ISSUE THREAD

**Issue by waldyrious** [westnordost/StreetComplete#1800]
If I open my profile and go to the Achievements tab, currently all I see is the following message:

> You have no achievements yet

First, I think that sentence needs a period at the end! :smile: but more importantly, it would be nice to add a sentence with a suggestion or two of what one can do to get some achievements shown there.

**Comment by waldyrious** [comment]
(Same for the Links tab, btw: it's not clear what these are for so maybe an informative message when it's empty would help.)

**Comment by westnordost** [comment]
You get an achievement for the very first quest you solve that explains that you get achievements through solving more quests.
Did you not solve any quest yet?

**Comment by waldyrious** [comment]
> Did you not solve any quest yet?

Not since I opened the app after the latest update. I have many quests solved from before then, though.

**Comment by westnordost** [comment]
Ah okay. Then, you are seeing the "you have no achievements yet" because your quest count has not been synced yet. If you latest open the app after one hour, it should not be empty anymore.

Otherwise, that is some bug

**Comment by waldyrious** [comment]
Ah, yeah, seems to be the case. I now see a higher completed quest count, and some achievements in that page (with a "graphic coming soon" text, but I assume that's intentional).

This issue still should remain open for improving the actual case of accounts with no Achievements, right?

**Comment by westnordost** [comment]
Yeah well, users that do really not have any achievements yet will learn what they need to do on their very first contribution. I think that is okay.

**Comment by smichel17** [comment]
An easy fix would be to change the text to

> You have no achievements yet. Solve a quest to learn more!

Or something like that.

**Comment by westnordost** [comment]
I'd rather leave it as is. If a new user even finds this screen, then I do not think he will be surprised that he has no achievements so far because he also didn't do anything so far.

Also, the text will change now for old users, it will not say anymore "you have no achievements" but "still syncing, check again later".
