### ISSUE TITLE
On first start: App will stay in bright theme

### ISSUE THREAD

**Issue by RubenKelevra** [westnordost/StreetComplete#1802]
I've cleaned all the data from the app and did a fresh startup. While it's well after sunset the app will remain in the bright theme.

After switching manually to the dark and back to auto, the app will remain in the dark theme.

**Comment by westnordost** [comment]
Found the bug. But it was ancient. Probably existed since the dark mode was firs implemented.

**Comment by RubenKelevra** [comment]
Cool!

Thanks for the fast fix :)
