### ISSUE TITLE
Show comments on user authored notes as a notification

### ISSUE THREAD

**Issue by peternewman** [westnordost/StreetComplete#1804]
**Use case**
If I can't answer a quest via OSM I can leave a note (or if I spot something else I can manually add one). It would be nice to know if people had commented on those notes. Similar to the inbox functionality.

**Proposed Solution**
I see a few types of potential query, possibly reporting as different styles:
- Notes I authored where I'm not the last commenter
- Notes I authored where I'm not the last commenter that aren't resolved
- Notes I commented on where I'm not the last commenter
- Notes I commented on where I'm not the last commenter that aren't resolved

I guess the challenge may be how you stop showing them, so perhaps ignoring the resolved ones would do the trick so they'd expire. I'm assuming you'd either respond to a comment or resolve the note.

I guess it could also do something more complicated tracking note IDs like it does for ones I choose to hide.

**Comment by westnordost** [comment]
The OSM API does not offer any endpoint for this. So, it's a really nice idea, but not possible.
