### ISSUE TITLE
Misaligned circle around active quest marker

### ISSUE THREAD

**Issue by Helium314** [westnordost/StreetComplete#1805]
Since the upgrade to version 19, active (tapped) quest markers have a blue circle that looks like it should be aligned with the edge of the marker, but isn't.
Screenshot:
![screenshot](https://user-images.githubusercontent.com/43007630/80835365-e5161e80-8bf2-11ea-8beb-ac2df2d69839.png)

I assume this is related to something specific to my phone, as it would have been already noticed otherwise...
SteetComplete 19 (fdroid)
AOKP Pie (Lineage 16.0 based)
S4 Mini

**Comment by westnordost** [comment]
Already fixed on master, thanks

**Comment by Atrate** [comment]
Still happens, at least here.

SC version: 20.1
Android 10
Native phone resolution: 2880x1440
Overridden size: 1440x720
Native DPI: 560
Override DPI: 240

**Comment by westnordost** [comment]
Yes, see #1810
