### ISSUE TITLE
Menu button not working any more

### ISSUE THREAD

**Issue by Helium314** [westnordost/StreetComplete#1806]
When I tap the menu button (capacitive hardware button on the phone), the menu does not open in StreetComplete 19. The button just does nothing.
Up to StreetComplete 18.3, the menu button had the same effect as tapping the 3 dots on top right (now 3 lines).

I am not sure whether this is a bug, but it feels like an annoying change in my usual flow. Plus, I don't see any possible benefit if the change was intentional.

SteetComplete 19 (fdroid)
AOKP Pie (Lineage 16.0 based)
S4 Mini

**Comment by westnordost** [comment]
What capacitive hardware menu button? 

Looking at https://www.gsmarena.com/samsung_i9190_galaxy_s4_mini-pictures-5375.php ..., isn't the button to the left the 🔲 (black square) on modern devices which opens the list of recent activities (like Alt+Tab on a PC), and the big one in the middle the home button that brings you back to the launcher (=desktop on a PC)?

**Comment by Helium314** [comment]
This (bottom left) button opened the menu by default in the earlier versions of android I used, but was switched to open recent activities later. I still use it to open the menu.
There is some setting to change behaviour of that button in my rom, and it works in almost all apps I use.

**Comment by westnordost** [comment]
I see, I found that it is possible to respond to hardware buttons and implemented it.

I can't test it though, so feel free to reopen it if it does still not work for the next version.

**Comment by Helium314** [comment]
Will do, thanks!

**Comment by Helium314** [comment]
It sort of works now (19.1 fdroid), but there seem to be 2 menus on top of each other.
By this I mean I have to close the menu twice (e.g. by pressing back twice) to get back to the map.
When using the 3 line button on screen the menu opens normal.

**Comment by westnordost** [comment]
What if you press and hold the menu button, does it open only once then?

Am 11. Mai 2020 11:11:57 MESZ schrieb Helium314 <notifications@github.com>:
>Reopened #1806.

**Comment by Helium314** [comment]
As long as I hold the button nothing happens.
Once I release it the menu opens twice.

**Comment by westnordost** [comment]
Should be solved now
