### ISSUE TITLE
Black text on gray background with dark theme (until restart)

### ISSUE THREAD

**Issue by Helium314** [westnordost/StreetComplete#1807]
The menu (when pressing the 3 lines on top right) has black text on gray background after switching to the dark theme (hard to read!).
This changes to (probably correct) white on gray after restarting the app.
I think the text color should switch immediately, or the app should ask for a restart to avoid confusion.

SteetComplete 19 (fdroid)
AOKP Pie (Lineage 16.0 based)
S4 Mini

![screenshot](https://user-images.githubusercontent.com/43007630/80836676-8ef6aa80-8bf5-11ea-9cfb-d9cce1f3159f.png)

**Comment by westnordost** [comment]
I can not reproduce it.

**Comment by Atrate** [comment]
Can reproduce
SC v19 from GitHub
LG G6
Havoc OS Q (Android 10 based on AOSP)

**Comment by westnordost** [comment]
Manually switch?

**Comment by Helium314** [comment]
After manual switch in the app. I did not try the "auto" setting (when does automatic switching happen?)

**Comment by HolgerJeromin** [comment]
> (when does automatic switching happen?)

This is the system theme which can be changed in the device settings depending on time. This is available since android 10 (without hacks).

**Comment by LostInWeb** [comment]
Hello,
I can reproduce the problem with the black text on gray background if I switch from bright to dark. It does not matter if I use auto or manual switching.
But I can solve the wrong formatting. I terminate the app and re-open it.

The attached zip contains a video with the problem:
[streetcomplete.webm.zip](https://github.com/westnordost/StreetComplete/files/4577215/streetcomplete.webm.zip)

Device:
Samsung Galaxy S10
Android 10

**Comment by westnordost** [comment]
So all who can reproduce this are on Android 10 so far. Gonna try it out with Android 10

**Comment by westnordost** [comment]
I can reproduce it on an Android 10 emulator,  but was unable to fix it. Everything seems correct, the dialog is created anew every time one clicks that button, so it should correctly apply the new style. And it does, but only half (background and graphics, not the text color).

No idea how to fix or even workaround this, this seems like a bug in Android 10.

**Comment by westnordost** [comment]
@ENT8R Do you remember why you did that change? https://github.com/westnordost/StreetComplete/commit/57e06fbdbee47cf2eef2044d399831f68f916597

**Comment by ENT8R** [comment]
I don't know the error message anymore, but the problem was that the app didn't start without the additional `configChanges` parameter (I think it crashed in a very early state directly after opening the app, there wasn't even a visible layout). So I probably can't tell you more information than the commit message already does...

**Comment by westnordost** [comment]
ok, thanks
