### ISSUE TITLE
Star count is cut off when increasing size (when uploading)

### ISSUE THREAD

**Issue by Helium314** [westnordost/StreetComplete#1808]
The "quest upload" animation where the star count grows and shrinks cuts off the on the right side.
I don't have any screenshot of this, didn't manage to catch the animation at the right time. (will try again if you need it)

SteetComplete 19 (fdroid)
AOKP Pie (Lineage 16.0 based)
S4 Mini

**Comment by westnordost** [comment]
Huh, I thought I fixed that
