### ISSUE TITLE
Can't upload

### ISSUE THREAD

**Issue by Natureshadow** [westnordost/StreetComplete#181]
Version 0.8 from F-Droid

The upload menu entry simply does nothing.

**Comment by westnordost** [comment]
Perhaps it has nothing to do?

**Comment by Natureshadow** [comment]
>Perhaps it has nothing to do?

Haha. If I hadn't quests to upload, I'd not try to upload them, eh?

**Comment by westnordost** [comment]
How do you see that you have quests to upload?

**Comment by Natureshadow** [comment]
>How do you see that you have quests to upload?

Because I just answered them and it says ⭐18 in the toolbar?!

**Comment by althio** [comment]
@Natureshadow your uploads are automatic, no need to manually trigger them

For more explanation, discussions, enhancements this ticket is good: https://github.com/westnordost/StreetComplete/issues/75#issuecomment-290947528

**Comment by Natureshadow** [comment]
> @Natureshadow your uploads are automatic, no need to manually trigger them

Aha…

So, the UI is entirely unhelpful. The star with the number looks like I
have stuff to upload, and the upload menu doing nothing, not even giving
a toast "nothing to do" does not help either.

How do I tell "everything uploaded automatically" from "cannot upload
anything"?

**Comment by althio** [comment]
> How do I tell "everything uploaded automatically" from "cannot upload anything"?

You read and participate in the other thread? #75 `Feedback for data upload`

**Comment by westnordost** [comment]
So I'll close this as duplicate.
