### ISSUE TITLE
In the achievements screen, illustrations are flickering

### ISSUE THREAD

**Issue by lost-geographer** [westnordost/StreetComplete#1813]
When I open the achievements screen, illustrations are flickering.
It seems that the different illustrations interfere with each other.

Here a screen capture of the behaviour : https://cloud-lstg.yourownnet.fr/s/Z9XgipXbSorwCiT

**How to Reproduce**

Open the achievements screen and it happens.
(I guess that you must have some achievements)

**Versions affected**

Android 9
StreetComplete 19 (from F-Droid)

**Comment by westnordost** [comment]
Heh, it's not flickeriing but the physics simulation. The big bubble is pressing the one into the corner so that little bubble is under very high pressure to get out but can't.

I am not sure if I can do anything about it. You could fling the one bubble upwards so the smaller has some more space.

**Comment by lost-geographer** [comment]
Oh ok... I didn't get that those were bubbles and you could move them around :D

**Comment by smichel17** [comment]
There is a bug here — two bubbles should never overlap each other.

I am not sure if this is a bug in streetcomplete or jbox2d.
