### ISSUE TITLE
Undo after sucessfull upload still possible, no flush of upload queue

### ISSUE THREAD

**Issue by gislars** [westnordost/StreetComplete#1814]
I did some quests and uploaded it. After upload, the undo button is still shown. When touching it, the upload queue gets a new entry with every undo. Now I'm stuck since I can't flush the upload queue and I don't want to upload my undos. 

I only use manual upload no auto sync.

**How to Reproduce**
* switch off auto sync (not sure this is necessary)
* Take one ore more quests.
* upload all by hitting upload button
* after upload finished, the undo button on the lower left is still available
* hitting undo, the count on upload queue is increased with every hit
* there is no way to flush the upload queue or "undo the undo"

**Versions affected**

19.1 from playstore
![screenshot_streetcomplete](https://user-images.githubusercontent.com/402166/81062675-b8a22100-8ed6-11ea-914b-4e2478ebd448.jpg)

**Comment by westnordost** [comment]
Yes, you can undo your changes even after upload. these undos need to be uploaded as well. Undoing undos is not possible, you need to re-answer the question after an undo.

This has always been the case since undos have been introduced.

**Comment by gislars** [comment]
Ok, undo is possible even after upload. When I accidentally hit the undo button, I don't want to upload the undo.  How can I clear the upload queue? I couldn't find anything in the settings. Invalidating Cache doesn't touch the upload queue. Do I miss anything?

**Comment by westnordost** [comment]
As said, you cannot undo an undo. After upload, you need to answer the question you uploaded another time.

What is your use case, why would you want to undo an undo but not re-answer the question?

**Comment by HolgerJeromin** [comment]
> When I accidentally hit the undo button, I don't want to upload the undo. 

undo has a "are you sure?" dialog to prevent this.

**Comment by gislars** [comment]
Ok, now I see what I did wrong.

* I finished quests
* uploaded all of them, upload queue was empty
* I hit undo **and confirmed "are you sure" dialog** (actually this is the point I really shouldn't have done, but I did. )
* my upload queue holds now the undo operation
* there is no way to flush the upload queue

* in the mean time I did a uninstall and reinstall and the upload queue is now empty. 
* <ironic mode> probably for me the "are you sure" dialog should have be named "are you absolutely sure since you have to upload the undo and can't remove it from the upload queue"</ironic mode>
* I should have stopped at the confirmation dialog

Sorry for the noise. I really like StreetComplete and please keep up your good work!

**Comment by westnordost** [comment]
So, you were primarily confused why the undo button is shown even though you already uploaded your changes?

I could disable undoing uploaded things for auto-sync=off users, but that sounds like a negative feature.

**Comment by gislars** [comment]
Yes, I was wondering what would happen if I do an undo after an upload. The confusing part kicked in as I didn't understand what to do now, because I didn't want to upload the undo.

I don't know if this (my) case should be handled somehow. A feature "flush upload queue" could solve it. On the other hand, why would a user want to do this. Apart from ignoring the warning issued by undo function. I can't imaging a use case where you want to flush all changes.

**Comment by westnordost** [comment]
Currently, one can undo changes for 24h hours. Maybe I could drastically reduce this time to ~1h or something. Who is going to remember after 1 hour that he made a mistake?

**Comment by gislars** [comment]
Maybe it is different whether autosync is on or off. Probably if you sync as you go you want more than an hour to undo. From my perspective, as a user with autosync off, I don't need a undo right after the quests are uploaded. Also one could argue a undo after upload a set of quests should undo the whole set. But that heavily depends on the use cases, which seems to have a wide spectrum. 

I guess you can leave the current 24h and if more users (not just me) are having trouble with it, you still can reduce it.

Another idea just popped up but is far out of scope and only autosync-off-users might interest: have a list of the queued upload items, where you can swipe items out of the upload stack.

**Comment by westnordost** [comment]
It's not so out of scope, there is actually a ticket for that somewhere, a pretty old ticket: #748

Never got around to doing it though, even though it is not really a lot of work. The data is there, UI concept is there.
