### ISSUE TITLE
Quest selection, unable to disable quest

### ISSUE THREAD

**Issue by hbogner** [westnordost/StreetComplete#1815]
When selecting quests to be enabled/disabled one quest is not responding. It's gray and can't be enabled/disabled, or moved to lover priority. All other quest are interactive, just this one fails.

Quest type: Can you contribute anything to this note?

![streetcomplete-quest-selection](https://user-images.githubusercontent.com/794472/81116326-75bb6a00-8f25-11ea-882b-c9b06819eb85.jpg)

**How to Reproduce**
Settings -> Quest selection -> Can you contribute anything to this note

**Versions affected**
Android: 9
StreetComplete: 19.0

**Comment by westnordost** [comment]
Yes, it cannot be disabled, it is always on for technical reasons.

**Comment by westnordost** [comment]
And you can also not reorder it, also for technical reasons.

**Comment by hbogner** [comment]
Any other way to not show it?

**Comment by westnordost** [comment]
Why, what's the problem? Are there two many senseless around near your area?

**Comment by hbogner** [comment]
I create most of notes in my area via OsmAnd, and when i want to add other info via StreetComplete there are all my notes clogging up the screen. I have to wait until i get back to computer and fix all the notes before notes stop clogging the screen,

**Comment by westnordost** [comment]
Actually, the app should hide your own notes or notes where there is a comment by you. Are you sure your own notes are shown in StreetComplete? If yes, please open another bug report and provide a screenshot.

Also, the app should only show notes that contain a question mark ("?"), but this behavior can be changed in the settings.

**Comment by hbogner** [comment]
If i disable "Show all notes" then it doesn't show my notes, only those with a question mark ("?") and I don't use it so it fixes my problem :)
If I enable "Show all notes" then it shows my notes, so disabling it solution for me.

Thank you for a clarification about Notes being fixed quest.
