### ISSUE TITLE
Missing building=stable (barn, cowshed, sty) in building quest

### ISSUE THREAD

**Issue by HolgerJeromin** [westnordost/StreetComplete#1816]
They were soft rejected in https://github.com/westnordost/StreetComplete/pull/774#issuecomment-393496914
But when the doors are open it is often very clear what/that here lives something :-)
It feels wrong to tag farm_auxiliary here.

Perhaps we could have it as a subcategory with indention:

- on a farm
- - farmhouse
- - farm building (farm_auxiliary)
- - - barn (farm_auxiliary house icon with the green tractor)
- - - stable (farm_auxiliary house icon with a horse)
- - - cowshed (farm_auxiliary house icon with a cow)
- - - sty (farm_auxiliary house icon with a pig)
- - greenhouse 
- - [...]

**Comment by smichel17** [comment]
There's been at least one building I skipped tagging because it was a chicken coop.

**Comment by westnordost** [comment]
That would be the first subcategory of a category, would probably need some implementation effort, also, effort for drawing the icons.
Also, as @smichel17 hinted, then there'd be many more possible choices and many people might not even know the exact definition of a barn or other specific buildings on a farm and just go about tagging everything for example as a barn.

Truth is, farm buildings, whether they are used as a cowshed, a stable, a barn etc. are more or less constructed in the same way, thus look alike from the outside and their usage may change over time. 

The `building` tag is primarily for what kind of building it is, not its use. So, if you can only determine whether a particular farm building is a cowshed or a barn by looking inside, then it stands to question whether tagging the building type for farm buildings anymore detailed than `farm_auxiliary` at all makes sense. 
The purpose of a farm building should better be recorded in an own tagging schema in that case. Though, one demur against this, against tagging the use of farm buildings at all, is, that farms are private businesses and thus private property, and in OSM, we shall not record private information nor should surveyors using StreetComplete be tempted to enter private property to answer questions.
For example, we also do not tag which building in a factory is used for which manufacturing process.
