### ISSUE TITLE
Add quest for incline on steps

### ISSUE THREAD

**Issue by HolgerJeromin** [westnordost/StreetComplete#1817]
### General
Affected tag(s) to be modified/added: [incline](https://wiki.openstreetmap.org/wiki/Key:incline)
Question asked: **Which side is the "up" direction?**

### Checklist
Checklist for quest suggestions (see guidelines):
- [x] 🚧 To be added tag is established and has a useful purpose
- [x] 🤔 Any answer the user can give must have an equivalent tagging (Quest should not reappear to other users when solved by one)
- [x] 🐿️ Easily answerable by everyone from the outside but a survey is necessary 
- [x] 💤 Not an overwhelming percentage of elements have the same answer (No spam)
- [x] 🕓 Applies to a reasonable number of elements (Worth the effort)

https://taginfo.openstreetmap.org/tags/highway=steps#combinations only about 20% of one million steps have this tag. 

### Ideas for implementation

**Element selection:** 
All `highway=steps` without `incline` tag. 
**Proposed GUI:**
Simplyfied steps should be rotated as in the map like done in the cycleway / footway quests. User should tab on the "up" side.

ref https://github.com/westnordost/StreetComplete/issues/875#issuecomment-554540298

**Comment by westnordost** [comment]
I thought it is determined by the direction of the way 

Am 6. Mai 2020 11:14:33 MESZ schrieb Holger Jeromin <notifications@github.com>:

**Comment by HolgerJeromin** [comment]
[Wiki](https://wiki.openstreetmap.org/wiki/Tag:highway%3Dsteps#How_to_map)
> By convention, the direction of the way should preferably point uphill, but the key incline=* should always be added to the way (see the talk page for more details).

I did not knew this convention so no step from me is correct :-)

**Comment by westnordost** [comment]
Ok.

Would need a new UI similar to the "is oneway?" quest, ideas?

**Comment by HolgerJeromin** [comment]
I already wrote:

> Simplyfied steps should be rotated as in the map like done in the cycleway / footway quests. User should tab on the "up" side.
