### ISSUE TITLE
My Profile Star view icons shake

### ISSUE THREAD

**Issue by ecksun** [westnordost/StreetComplete#1818]
When I view the Icon with a Star (★, second tab) under the My Profile page the icons doesnt seem to fit, causing them to shake.

[Here is a zipped recording of the behaviour](https://github.com/westnordost/StreetComplete/files/4596225/recording.zip)

**How to Reproduce**
I only have to open the view to see the bug. I'm guessing solving a lot of different quests is the key to triggering it

**Versions affected**
I'm running StreetComplete 19.0 from f-droid with android version 9 (LineageOS)

**Comment by smichel17** [comment]
Here's the video as a gif, so it can be embedded:

![streetcomplete2](https://user-images.githubusercontent.com/6563664/81355895-d2da2b80-909d-11ea-83a4-bf1d9e7204b5.gif)

**Comment by westnordost** [comment]
Hmm, it should not be that full

**Comment by smichel17** [comment]
Maybe the same underlying issue as #1813?
