### ISSUE TITLE
Copying building information for semidetached house, terrace and apartments

### ISSUE THREAD

**Issue by ModProg** [westnordost/StreetComplete#1819]
**Use case** 
Add a possibility to copy the information to the neighboring houses for houses that touch and therefore probably have the same settings for building type, height and roof type. 

**Proposed Solution** 
I am not sure about the best solution to implement this visually, but maybe when the user wants to enter information for connected buildings, they can choose, maybe by dragging, maybe by tapping the houses with the same properties.
![Proposed Interface](https://user-images.githubusercontent.com/11978847/81401575-e6ce6d80-912f-11ea-8a53-4fe6edf9366a.jpg)

**Comment by smichel17** [comment]
I used to feel something like this was *very* sorely needed.

Over time quest completion has become easier (fewer taps, less opening of the keyboard), and now I feel it is needed *less*.

I still feel it is needed. However, I also wonder whether it will always be needed, or if we can keep making individual quest completion easier and easier, and that would be good enough.

There is a risk to this multi-selection approach: it makes it easy to fill out entire sections *without really checking if they're all the same*. Especially for new mappers, who are the app's target audience. Making each individual quest easier to fill out does not run that risk.

Therefore, I think this ought to wait until individual quests have been optimized as much as possible; then we can re-evaluate if it is still needed.

**Comment by westnordost** [comment]
Issues like this has been raised multiple times Adding something like multi-selection is not planned.
Your suggestion is still something else (a little smarter), but even more effortful to implement.
