### ISSUE TITLE
Login : can't log in with Google 

### ISSUE THREAD

**Issue by alex-devg** [westnordost/StreetComplete#182]
the problem : I can't log in the app with my Google account which is my only way to log in OpenStreetMap 

possible reason : two factor authentication? 

Thanks, alex

**Comment by westnordost** [comment]
Can you elaborate on the details? The dialog shown there is just a browser.

On 4 May 2017 15:26:29 CEST, Alexandre L <notifications@github.com> wrote:
>the problem : I can't log in the app with my Google account which is my
>only way to log in OpenStreetMap 
>
>possible reason : two factor authentication? 
>
>Thanks, alex
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/westnordost/StreetComplete/issues/182

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by afmenez** [comment]
I have the same problem.  I also use two factor authentication.  I type the user name and password, and then I have to switch apps to get the authentication code.  When I switch back, the form has aborted and I have to restart, but then the previous code is invalid.

**Comment by westnordost** [comment]
Hmm I see. The web view reloads when you switch applications. I will see if I can change it so it doesn't do that.
