### ISSUE TITLE
Cycleway quest and one-way entry-exit routes onto roundabouts

### ISSUE THREAD

**Issue by peternewman** [westnordost/StreetComplete#1822]
On some roads tagged as oneway, the cycleway quest still asks for both directions (although not on others, it seems to depend on if the sidewalk quest has been answered, or possibly the road classification).

**How to Reproduce**
Answer the cycleway quest on a one-way road. It should (probably) only ask in one direction IMHO.

It should also not tag using :both.

**Versions affected**
Android 9.0 SC v19.1

**Comment by westnordost** [comment]
Could you please link the position where this occurs?

**Comment by peternewman** [comment]
These both show it:
https://www.openstreetmap.org/way/200516429
https://www.openstreetmap.org/way/200516427

Or anything here connected to a roundabout:
https://overpass-turbo.eu/s/TMc

I think it's due to this:
https://github.com/westnordost/StreetComplete/blob/master/app/src/main/java/de/westnordost/streetcomplete/quests/bikeway/AddCyclewayForm.kt#L33-L36
In conjunction with this:
https://github.com/westnordost/StreetComplete/blob/master/app/src/main/java/de/westnordost/streetcomplete/quests/bikeway/AddCycleway.kt#L68

Because anything that matches here will be returned:
primary|primary_link|secondary|secondary_link|tertiary|tertiary_link|unclassified
But only these are checked for the one-way stuff:
primary|secondary|tertiary

So I think it will break for any that aren't in both.

**Comment by westnordost** [comment]
right, thanks!

**Comment by peternewman** [comment]
Is it worth some code comments to ensure the two lists stay in sync if one gets updated in future?
