### ISSUE TITLE
Compass direction shows while GPS dot is missing

### ISSUE THREAD

**Issue by peternewman** [westnordost/StreetComplete#1823]
Compass direction shows while GPS dot is missing and GPS accuracy is being measured/calculated.

**How to Reproduce**
Turn on and off location services (I'd think), or move, then switch back to SC. You get the wedge showing which way you're facing, and this spins around as expected, but there's no dot or doughnut to show where you are and to what accuracy. This seems a bit odd to me and hiding everything would seem better, or making the compass wedge huge in the middle of the screen or something, as it implies you are somewhere and looking somewhere you aren't or might not be.

**Versions affected**
Android 9.0 SC v19.1

**Comment by westnordost** [comment]
Can't reproduce.

**Comment by peternewman** [comment]
![Screenshot_20200509-085601](https://user-images.githubusercontent.com/6216436/81467812-213d1680-91d3-11ea-90b4-68815b788a56.png)

**Comment by westnordost** [comment]
I believe you that it occurs for you, I can simply not reproduce it with the steps you described.

Am 9. Mai 2020 09:57:52 MESZ schrieb Peter Newman <notifications@github.com>:
>![Screenshot_20200509-085601](https://user-images.githubusercontent.com/6216436/81467812-213d1680-91d3-11ea-90b4-68815b788a56.png)

**Comment by peternewman** [comment]
> I believe you that it occurs for you, I can simply not reproduce it with the steps you described.

Ah gotcha, even on my simpler reproduction.

Let me know if I can do anything else to help diagnostics.

**Comment by westnordost** [comment]
Was able to reproduce it with another device
