### ISSUE TITLE
Add Sports Pavilion to building type quest

### ISSUE THREAD

**Issue by peternewman** [westnordost/StreetComplete#1824]
**Use case**
There are lots of sports pavilions which we can currently only tag as sports centre or stadium, neither of which are correct:
https://wiki.openstreetmap.org/wiki/Tag:building%3Dpavilion

**Proposed Solution**
Add it, it could use the existing icon.

**Comment by westnordost** [comment]
Rather not. There are countless building types, there is no limit to it. The UI can not contain an arbitrary number of choices, I need to draw the line somewhere. One good line to draw is if there is one building type that contains other "sub-types", like farm_auxiliary or sports centre in this instance, I show only the category.

I'd say that any sport club related building is a sports centre building. Not a `leisure=sports_centre`, mind you, but `building=sports_centre`, just like all the buildings on a university campus are usually tagged as `building=university`.

**Comment by peternewman** [comment]
> Rather not. There are countless building types, there is no limit to it. The UI can not contain an arbitrary number of choices, I need to draw the line somewhere.

There are more choices in residential than Civic currently.

> One good line to draw is if there is one building type that contains other "sub-types", like farm_auxiliary or sports centre in this instance, I show only the category.
> 
> I'd say that any sport club related building is a sports centre building. Not a `leisure=sports_centre`, mind you, but `building=sports_centre`, just like all the buildings on a university campus are usually tagged as `building=university`.

Sports centre (and sports hall) seems to talk about having a big hall to do sport in:
https://wiki.openstreetmap.org/wiki/Tag:building%3Dsports_centre

The pavilion doesn't have any space to do sport in, just to get changed:
https://wiki.openstreetmap.org/wiki/Tag:building%3Dpavilion

So IMHO, tagging a pavilion as a sports hall/centre is wrong.

Interestingly, looking at this, sports_centre or center isn't even listed in the summary:
https://wiki.openstreetmap.org/wiki/Key:building#Sports

I was going to say logically there would be more pavilions than stadiums, as everyone needs to get changed, but only bigger stuff will have people watching.

https://taginfo.openstreetmap.org/tags/building=sports_hall - 2590
https://taginfo.openstreetmap.org/tags/building=sports_centre - 2337
https://taginfo.openstreetmap.org/tags/building=pavilion - 5722
https://taginfo.openstreetmap.org/tags/building=stadium - 6145

**Comment by peternewman** [comment]
Also I, and 90 other people had misspelt pavilion with two L's, I've now corrected a bunch I feel I can safely to so remotely, but adding it to SC would avoid some of those errors.
