### ISSUE TITLE
Background map tiles of specific places aren't visible

### ISSUE THREAD

**Issue by ciconi** [westnordost/StreetComplete#1828]
On some places the background map tiles are not visible at all or only streets are visible (an no buildings). I tried to reinstall the app and/or delete the cache and also waited and retried for 10 minutes, also tried moving the map from time to time. Everything is rendered except those exact same tiles. As it's always the same area, it's probably because of mapping errors or too complex map data? 

**How to Reproduce**
1. (Re-)install the app
2. Move to the central station of munich/germany
3. Two tiles south of the station between Hermann-Lingg-Str and Sonnenstraße are not rendered. 

**Versions affected**
19.0 - 19.2.

![Street Complete_1](https://user-images.githubusercontent.com/31411407/81940429-e0d90080-95f7-11ea-9eb8-d25b7bf5f42e.png)
![Street Complete_2](https://user-images.githubusercontent.com/31411407/81940437-e2a2c400-95f7-11ea-83ce-48ac4a713c86.png)

**Comment by westnordost** [comment]
@Akasch

**Comment by Akasch** [comment]
Should be better now

**Comment by westnordost** [comment]
Okay thanks! What was the problem?

**Comment by ciconi** [comment]
Thanks a lot, it works!
