### ISSUE TITLE
Recycling station: add oil recycling

### ISSUE THREAD

**Issue by Mannshoch** [westnordost/StreetComplete#1830]
**How to Reproduce**
Answer recycling quests. Oil as recycling product is missing. 

**Versions affected**

19.2

**Comment by westnordost** [comment]
Never heard of it. Do you have a link? Is it common anywhere?

**Comment by Mannshoch** [comment]
In Switzerland almost any Recycling station has Oil recycling.
http://www.swissrecycling.ch/wertstoffe/oel/

**Comment by westnordost** [comment]
But the quest asks for what is recycled at recycling containers, not recycling stations.

**Comment by Mannshoch** [comment]
On most Recycling places where you find container for aluminum, glass bottles, etc. you also find a container for Oil like you could see on this picture:
![grafik](https://user-images.githubusercontent.com/7795891/82049861-666fb580-96b7-11ea-9838-a7852622728b.png)
![grafik](https://user-images.githubusercontent.com/7795891/82050238-10e7d880-96b8-11ea-9afb-3c1025343c69.png)

**Comment by westnordost** [comment]
"Altbrot", wow

Okay, interesting.

So if it really is the case in Switzerland that on most/many recycling containers, you find containers like this, then an oil-choice should be added to reduce the number of notes that people created with StreetComplete for this quest type in Switzerland.

**Comment by Mannshoch** [comment]
👍

"Altbrot" is not that common. In this case a Farmer had placed this container to collect bread for feeding.

**Comment by JorgeSanzS** [comment]
In Spain they also exist on the street

**Comment by westnordost** [comment]
![image](https://user-images.githubusercontent.com/4661658/82080217-6f2ab080-96e4-11ea-998f-334e9b3a3328.png)

**Comment by westnordost** [comment]
Hmm, might there be places which do not accept vegetable oil but mineral oil or the other way round?
@JorgeSanzS  @Mannshoch

**Comment by peternewman** [comment]
I was going to say, vegetable oil, engine/motor oil?

**Comment by Mannshoch** [comment]
I don't know. In my town both are accepted. We have the green container. You could see it only if you open the container. I'm not sure if it may exist container which only accept one of them. A friend of mine says that a restaurant he worked for put their frying oil into this kind of container. So he think this containers may common on any recycling station. I do not know how the situation is on the motor oil side.

**Comment by westnordost** [comment]
Hm because documented values are only for vegetable oil and mineral oil, but I wonder if it even makes sense to put these two apart - if there are any places that accept one but not the other.

**Comment by peternewman** [comment]
Out of interest is it a container you pour oil into, or something you put your bottle of oil into?

> Hm because documented values are only for vegetable oil and mineral oil, but I wonder if it even makes sense to put these two apart - if there are any places that accept one but not the other.

This page lists engine and cooking oil:
https://wiki.openstreetmap.org/wiki/Tag:amenity%3Drecycling

I cook with both sunflower and olive oil, only one of which is a vegetable, so be mindful of the wording @westnordost .Is vegetable a translation of the German page on the wiki back to English on GitHub?

**Comment by JorgeSanzS** [comment]
in Spain there are containers that are only for cooking oil
