### ISSUE TITLE
Animation time is too long

### ISSUE THREAD

**Issue by HolgerJeromin** [westnordost/StreetComplete#1832]
Opening the germany stats for me (6190) needs >20 seconds!

Opening the "by type" overview needs 6 seconds.
The largest quest details takes about 6 seconds, too.

Yes, the stats are pure gimmick, but this times are too long imo.
**How to Reproduce**

Use this account
https://www.openstreetmap.org/user/HolgerJeromin

**Versions affected**

20.0 beta1

**Comment by westnordost** [comment]
You got the version wrong.

I fear there is not that much I could do though. If anything takes long, it will probably be the physics simulation. What device do you use? How many different quest types did you solve?

Was it any different in v19?

Or are you not speaking of the time it takes to appear and settle, but the time it takes to "blow up" the bubbles?

**Comment by nmxcgeo** [comment]
I think, what @HolgerJeromin means is the following:
![Screenshot_20200516_192130_de westnordost streetcomplete](https://user-images.githubusercontent.com/25130823/82126109-d0b55280-97aa-11ea-8b6a-042893e68eb3.jpg)
The time it takes for the number 10170 to settle takes a long time (about 44 seconds in my case). I don't think this time has changed substantially from v19.
My version: v20.0-beta1

If that's not, what was meant, I would still like to shorten this and take it to a separate issue.

**Comment by HolgerJeromin** [comment]
This issue is about two different animation times.

@nmxcgeo 
Yes, I mean the time to rise the number (10170 in your case).

But also the bubbles. I only have a little bit IT, AT and the rest DE. Till the huge DE bubble gets its full radius 20 seconds are needed. Which is not so interesting to watch.
I think the config is equal in "by quest" and "by country" but in the "by quest" I have many bubbles to fill and not only "one" big one.

**Comment by westnordost** [comment]
But you do not need to watch the bubble grow, the UI is fully usable already while the bubble is still growing.

How about for the quest counter, I implement that if you tap on it, it will immediately show the final count? Would that solve that issue?

**Comment by matkoniecz** [comment]
No animation for count would resolve it, but maybe animation surf of changing number can get faster for larger values?

Animation is quite nice here.

**Comment by HolgerJeromin** [comment]
I thought of animation time of x( = 2) second, regardless of the number.

**Comment by westnordost** [comment]
The time is longer because I want to convey the meaning "this is a lot"

**Comment by Atrate** [comment]
I agree the animation is quite fun to see for someone in the top 3, gives you a big sense of "that's large"

**Comment by westnordost** [comment]
I now reduced the animation time somewhat. Before, the time in ms was:
`(150 * questCount)^0.75` (green)
Now, it is
`300 + (500 * questCount)^0.6` (blue)

![image](https://user-images.githubusercontent.com/4661658/82264737-ca1f0a80-9965-11ea-90a4-5402f8bd3886.png)

**Comment by peternewman** [comment]
> How about for the quest counter, I implement that if you tap on it, it will immediately show the final count? Would that solve that issue?

Could we have this @westnordost , or otherwise make the animation times tend sooner to a fixed value? I don't know about other people but its interesting comparing how many quests of different types I've done (either by type or country) and when it takes 4-5 seconds to see the result when you tap on each quest type (1500+ answers), let alone countries (7 times that), it gets a bit boring waiting.

The difference in size of circles can also make it a bit of a challenge to even hit some of the smaller ones.

**Comment by westnordost** [comment]
OK sure, it's just one line of code

**Comment by peternewman** [comment]
> OK sure, it's just one line of code

Thanks @westnordost . It works well. Any chance we could have it on the country section too please?

There also seems to be other inconsistent behaviour (in bold) between the two:
By type:
- Tap bubble, detail opens
- Count starts increasing
- Tap and it resolves to total
- Tap again, **nothing happens**
- Press back to get back to overview

By country:
- Tap bubble, detail opens
- Count starts increasing
- Tap and it **closes**/wait and it finishes counting
- Tap again and it closes back to overview
- Pressing back also gets back to overview

Being able to tap to resolve the total on both would be good and tapping again to close (as well as the back button).
