### ISSUE TITLE
Allow copy and paste in about view

### ISSUE THREAD

**Issue by HolgerJeromin** [westnordost/StreetComplete#1833]
The text in the about dialog does not allow copy and paste.
**How to Reproduce**

Need the version string for a bug report. Copy not possible.
**Versions affected**

20.0 beta1

**Comment by westnordost** [comment]
Okay, why not. Any other strings that you think should be selectable in the app?

**Comment by westnordost** [comment]
I assume you mean v20.0 beta1

**Comment by HolgerJeromin** [comment]
> Okay, why not. Any other strings that you think should be selectable in the app?

`my profile/<last tab>`
A long press on each entry (osm wiki, welcome mat,...) should do something. Perhaps copy target url to clipboard (with a small toast "URL saved to clipboard").

**Comment by westnordost** [comment]
Okay, I added it to the credits, privacy screen and changelog. Regarding the buttons for the links: Rather not.
