### ISSUE TITLE
Achievement icons disappear

### ISSUE THREAD

**Issue by Etua** [westnordost/StreetComplete#1834]
**How to Reproduce**

Open a few achievement descriptions in a row and the bigger icons (those above detailed descriptions) stop to load until the app is restarted.

**Versions affected**

19.1, Android 9

![Screenshot_20200516-202454_Street�Complete](https://user-images.githubusercontent.com/13040148/82127476-2a6e4a80-97b4-11ea-8b63-0eac86e80416.png)

**Comment by westnordost** [comment]
So there is also no animation?

**Comment by westnordost** [comment]
I can not reproduce that they disappear, but the achievement graphic gets more and more transparent if I frantically click on the achievements.

**Comment by Etua** [comment]
I think that the video will suffice. The time between first click and encountering the problem is not fixed. In this GIF I encounter the problem in the third try (the record is two) and in the [linked video](https://nc.danelski.pl/s/nbtkw6jJTMPgJet) you can see as I click intensively for more than 30 seconds and what happens next.
![TRIM-20200517-210058](https://user-images.githubusercontent.com/13040148/82157692-63c1bb80-9883-11ea-9086-8c8e27a0e868.gif)

**Comment by westnordost** [comment]
This and other oddities were basically caused by overlapping animations. I changed it now that it is not possible to click away the dialog before it is done animating.
