### ISSUE TITLE
Buildings terraced but address quest not appearing

### ISSUE THREAD

**Issue by RobJN** [westnordost/StreetComplete#1835]
6 days ago I split a building in JOSM in to several separate buildings. Tag: building=terrace. Location: Albert Street, Warwick, Warwickshire, UK. I had expected them to appear on StreetComplete so that I could add the address. The building levels quest loads but not the address quest. Why?

I have invalidated the quest cache and even tried uninstalling and reinstalling the app.

Android. V 19

Any help much appreciated as I hope to use this workflow for the rest of the town.

**Comment by westnordost** [comment]
I don't see a reason why the buildings at https://www.openstreetmap.org/#map=19/52.28568/-1.59203 should not get a housenumber quest.

The housenumber quest does not load at all? Or only not for these buildings?

**Comment by RobJN** [comment]
Just not for the new buildings. I get a single quest (presumably because on
way in the terrace retained the old way ID) but that's all.

**Comment by matkoniecz** [comment]
I tried and it is shown for me. Can you flush cache again and retry?

Are you sure that app scanned for this quest?

Can you try with house number quest in top of the quest list and enabled?

**Comment by RobJN** [comment]
I switched off all quests except address and building levels. I clicked invalidate quest cache. I then rescanned. Still same issue: building levels shows and just one address quest (presumably on the historic way ID).

Address quest is at top of list second to the notes quest.

What am I doing wrong?

![Screenshot_20200517-170628](https://user-images.githubusercontent.com/5060210/82153721-23e9dc80-9861-11ea-8ab3-525beb902398.png)

**Comment by westnordost** [comment]
If you switched off all other quest types, why are the building height quests still shown?

**Comment by matkoniecz** [comment]
>  just one address quest

Also, this small dots indicate locations of other housenumber quests that will appear once nearby quests will be solved/hidden.

**Comment by RobJN** [comment]
> If you switched off all other quest types, why are the building height quests still shown?

Because I added that to show that since terracing the building in JOSM, StreetComplete has detected the separate ways for that quest but not the address quest.

> Also, this small dots indicate locations of other housenumber quests that will appear once nearby quests will be solved/hidden.

The small dots are all building height quests.

I've played with this several times over several days and still cannot get it to show the address quest. Is it really showing on your version of the app? I ask because I've even tried uninstalling and reinstalling the app. I've also tried wiping cache and user data via the android settings menu.

**Comment by matkoniecz** [comment]
![Screenshot_20200517-203214](https://user-images.githubusercontent.com/899988/82156795-aed8d000-987d-11ea-8182-4fb168286956.png)

**Comment by matkoniecz** [comment]
![Screenshot_20200517-203331](https://user-images.githubusercontent.com/899988/82156827-f0697b00-987d-11ea-8b29-c2880105d319.png)

**Comment by matkoniecz** [comment]
> The small dots are all building height quests.

Is it possible that building levels quest has priority higher than house number one?

Can you check in seeing whatever you use an alternative overpass servers (though it persisted across reinstalls,  so it is extremely unlikely to be related).

**Comment by RobJN** [comment]
I've tried all those things. Still not working. Argh this is annoying as it's clearly fine for you.

**Comment by RobJN** [comment]
Ah, it seems to be related to my broadband. After reinstalling the app again with no change, I just tried running on 4G mobile data rather than my WiFi and it's all fine now.

I guess you can close this ticket now. Although if you do have any ideas as to what caused that so that I can go search a solution, that would be much appreciated.

**Comment by westnordost** [comment]
Hm, wouldn't know how that would be related.
The most possible cause might be a lag of the overpass server (=the overpass server doesn't have the newest data). I know that kumi systems (the alternative overpass server) has or had some problems.

**Comment by matkoniecz** [comment]
I remember now that the main official servers also had some noticeable lag recently.

Sadly I don't remember exact value (yellow background for element count window), but it seems likely.

> Ah, it seems to be related to my broadband.

This really should not be possible. Completely failing quests scan - yes, though it was improved. But malformed results should not happen.

**Comment by RobJN** [comment]
Hmm. I'll try and keep an eye on it. If it happens again I will let you know. Thanks for all your efforts to help me.
