### ISSUE TITLE
GPS direction arrow overlaps star count >999

### ISSUE THREAD

**Issue by HolgerJeromin** [westnordost/StreetComplete#1838]
All icons are excluded (move it inside) from the gps arrow. 
But the star count is only excluded with three digits.

**How to Reproduce**

![rps20200517_135604_178](https://user-images.githubusercontent.com/2410353/82143725-4e7a6c00-9846-11ea-9b45-bfb224f56a54.jpg)

**Versions affected**

20.0 Beta1

**Comment by westnordost** [comment]
Does the arrow otherwise avoid that area but only comes short of it?

**Comment by m-rey** [comment]
The arrow pointer (i. e. the "corner" point of the arrow) avoids the star count area. However, the rest of the arrow image may still overlap the counter.

**Comment by westnordost** [comment]
Ah! Okay maybe this cannot be fixed then with reasonable effort. 

I will look into it anyway.

**Comment by westnordost** [comment]
What could be done in any case is to have the pointer pin behind other buttons on the screen. Would that make it better?

By the way, how do you like the pointer pin?

**Comment by matkoniecz** [comment]
> By the way, how do you like the pointer pin?

It is great!

**Comment by m-rey** [comment]
> have the pointer pin behind other buttons on the screen. 
As long as the pointer can still be pressed, yes. 

> By the way, how do you like the pointer pin?
It's a great feature!

**Comment by westnordost** [comment]
I moved the pointer pin now below the other map buttons, but hte overlapping is still there and will be a will-not-fix.

**Comment by peternewman** [comment]
Given it doesn't tightly follow the edge of other buttons (presumably square/circle type thing), couldn't you just add more of a border to the icons/pointer @westnordost ?
