### ISSUE TITLE
Donation link

### ISSUE THREAD

**Issue by pserwylo** [westnordost/StreetComplete#184]
This is exactly the type of high quality open source app that I'd like to donate to in order to show my appreciation. Do you have a donation method that you prefer, that you could:

 * Add to your README.md files.
 * Then subsequently add to the F-Droid metadata for others who get your app from there.

Cheers.

**Comment by westnordost** [comment]
I'd rather not have a donation method right now, perhaps later. 
If you want to give me something, you could send me a CD of your favourite local band :-)
