### ISSUE TITLE
My Profile - by country has poor display of countries with large white areas in flags

### ISSUE THREAD

**Issue by matkoniecz** [westnordost/StreetComplete#1840]
For example Poland has red & white flag shown on white background, with top half in exactly the same color as background.

Not sure is any country going to be affected in night mode.

**How to Reproduce**
Map in Poland?

**Versions affected**
v20.0-beta1, Android 9

**Comment by matkoniecz** [comment]
Not sure what the best fix would be.

**Comment by westnordost** [comment]
Is there no shadow at all?

**Comment by matkoniecz** [comment]
![Screenshot_20200517-164816](https://user-images.githubusercontent.com/899988/82151929-75dd3300-985e-11ea-9083-ad0d45cdbcbc.png)

**Comment by westnordost** [comment]
I wonder why the elevation is not displayed correctly. Maybe if this can be solved, it does not look odd anymore.

**Comment by matkoniecz** [comment]
It is Android One phone, so it should be not affected by bugs caused by low quality Xiaomi modifications (like my previous Xiaomi phone was affected).

**Comment by m-rey** [comment]
Can reproduce with the flag of Czech Republic using Android 10:
![IMG_20200517_222538](https://user-images.githubusercontent.com/42996147/82159277-688b6d00-988d-11ea-933b-78a379e5dd76.jpg)

**Comment by HolgerJeromin** [comment]
IT and AT
![rps20200517_231122_489](https://user-images.githubusercontent.com/2410353/82160177-c7ec7b80-9893-11ea-80af-43667f7a4e3c.jpg)
