### ISSUE TITLE
Number of days in main profile and achievement text

### ISSUE THREAD

**Issue by matkoniecz** [westnordost/StreetComplete#1841]
179 days active in the basic menu of profile, 176 in the achievement text.

![Screenshot_20200517-165119](https://user-images.githubusercontent.com/899988/82152007-e5532280-985e-11ea-821e-cdc5ad7d0712.png)
![Screenshot_20200517-165129](https://user-images.githubusercontent.com/899988/82152009-e71ce600-985e-11ea-958b-8b8c41384af5.png)

**How to Reproduce**
No idea.

**Versions affected**
V 20.0-beta1, Android 9

**Comment by westnordost** [comment]
You got the achievement level 44 of "regular" for being active 176 days. But you are active 179 days.

**Comment by westnordost** [comment]
Hmm, also what's your rank in Poland? It should display in that window.

**Comment by matkoniecz** [comment]
> Hmm, also what's your rank in Poland? It should display in that window.

No idea. Clicking flag in "by country" ball display shows 12 stars (with unclear meaning).

**Comment by matkoniecz** [comment]
> You got the achievement level 44 of "regular" for being active 176 days. But you are active 179 days.

Maybe "You contributed 176 days or more" or "176+" would be better?

Or "at least 176 days"?

Or maybe it is confusing in my case where achievement was awarded for past events, and will be less confusing in case of getting notification that achievement was awarded.

**Comment by westnordost** [comment]
12 stars, means the app thinks that you contributed 12 quests in Poland.

**Comment by westnordost** [comment]
Something is off with your statistics. You should have 10 country-flag balls floating around there.

"12" should be nowhere at all in your statistics.

**Comment by westnordost** [comment]
Is this from when you logged in the first time? Is it still the same if you log in again?

**Comment by matkoniecz** [comment]
It got fixed! Though flag balls are still without borders/shade.

**Comment by westnordost** [comment]
Hmm okay, then I thinks this happened because the backend was still syncing your changes and the 12 solved quests were from the day(s) since you updated to v20

**Comment by westnordost** [comment]
I think I will not fix this, because this is the case for all achievements. It's always "you solved X something". It's untypical for achievements to say something like "You killed _at least_ 1.000 skeletons".

**Comment by smichel17** [comment]
> "You killed at least 1.000 skeletons".

Ah-ha! I think this is the issue: imagine if the achievement happened at 973 skeletons. It would be confusing, because 973 is not a round number or one with obvious meaning. Therefore, I would not guess that it is an achievement and would instead assume that it is my current count.

Similarly, 176 is not a number I can easily assign meaning to.

- It's not a round number (100, 150, 200)
- It's not *quite* 6 months / half a year.
- It's not evenly divisible by 7, so it's not some number of weeks
- Maybe it's intended as "one more than 175"?

So, I think the fix would be to change the achievement milestone so the significance is more obvious.

**Comment by HolgerJeromin** [comment]
I think the logic is: 
I have x days done. (shown in achievement)
The day x+1 is partly over, so this x+1 is shown in days active.

But still: no one understands this :-)
