### ISSUE TITLE
[Bug] Zooming in with position indicator offscreen makes it point the wrong way

### ISSUE THREAD

**Issue by Atrate** [westnordost/StreetComplete#1842]
Zooming in with the position indicator offscreen makes it point towards the upper left corner, no matter of the actual position.

**How to Reproduce**

1. Scroll the map so the position indicator can't be seen on-screen
2. Zoom in

**Versions affected**

v20.0-beta1
Android 10

**Comment by westnordost** [comment]
I don't understand what is the problem

**Comment by matkoniecz** [comment]
> Zooming in with the position indicator offscreen makes it point towards the upper left corner, no matter of the actual position.

Are you sure that your location as reported by phone GPS is somewhere else? And not to north-west

> I don't understand what is the problem

And I think that I understand it (offscreen locator indicator stuck to a star count), but I am unable to reproduce it. Can you attach a recording of a screen (I can explain how I do this)?

**Comment by HolgerJeromin** [comment]
@Atrate What if you tap/click on the position indicator?

**Comment by Atrate** [comment]
> Are you sure that your location as reported by phone GPS is somewhere else? And not to north-west

Yep, tested it with various angles

> What if you tap/click on the position indicator?

It returns properly

> Can you attach a recording of a screen (I can explain how I do this)?

Sure, but gonna do it in a few days so that I don't share my home location (though I could try spoofing location with root)

> I don't understand what is the problem

The indicator at the edge of the screen changes position to an incorrect one when zooming in, gets stuck to star count.

This might also be something to do with the animations, I no longer see an animation when zooming in at high zoom levels. For some reason the animation is still there at high (worldwide) zoom levels.

My animation length in Android is set to 0.8x

**Comment by peternewman** [comment]
FWIW I can't reproduce it either.

> > Are you sure that your location as reported by phone GPS is somewhere else? And not to north-west
> 
> Yep, tested it with various angles

So if you have it zoomed out to the SE and continue zooming in to a point on the map it migrates around the screen as you zoom in? Does it migrate back if you zoom back out.

**Comment by Atrate** [comment]
Update: the bug only happens in perspective view

**Comment by peternewman** [comment]
> Update: the bug only happens in perspective view

You mean tapping the compass once? I still can't reproduce it.

**Comment by westnordost** [comment]
I was able to reproduce it once when in perspective view and north was down somehow.

**Comment by westnordost** [comment]
Here are two pictures of the bug
1. The position indicator actually points at screen position 0,0. It is a bug in tangram-es, I reported it already here: https://github.com/tangrams/tangram-es/issues/2165
![Screenshot_1590535484](https://user-images.githubusercontent.com/4661658/82959823-f74c6800-9fb8-11ea-996a-696f66eb7953.png)
2. Zooming out a bit reveals that the user's location is not actually southeast, but roughly north
![Screenshot_1590535501](https://user-images.githubusercontent.com/4661658/82959922-44c8d500-9fb9-11ea-8390-a8917231a6af.png)

**Comment by kmpoppe** [comment]
I can reproduce the exact same issue in the perspective view - in top-down the location pointer points the correct way.
![Screenshot_20200531-130339](https://user-images.githubusercontent.com/24451207/83350813-1cd1cc80-a33f-11ea-97c2-9a3ed0e87ab0.png)
![Screenshot_20200531-130331](https://user-images.githubusercontent.com/24451207/83350816-20655380-a33f-11ea-94a3-46f47d47423d.png)

**Comment by Mannivu** [comment]
I'm having this issue in SC v20.2 F-Droid version. This happens when switching from top down view to 3D view.

![Screen record](https://i.imgur.com/LR0ieff.gifv)

**Comment by matkoniecz** [comment]
Note "blocked" label - it means that it requires fix in some external thing.

In this case it is blocked by https://github.com/tangrams/tangram-es/issues/2165 - you can add thumb up reaction there (though please do not make "+1" or "plz fix" comments) or write a PR changing the behaviour.

**Comment by Mannivu** [comment]
> Note "blocked" label - it means that it requires fix in some external thing.
> 
> In this case it is blocked by https://github.com/tangrams/tangram-es/issues/2165 - you can add thumb up reaction there (though please do not make "+1" or "plz fix" comments) or write a PR changing the behaviour.

Oh, I see. Thank you, I'll upvote the other issue.
