### ISSUE TITLE
[Beta change] Bring back the location button

### ISSUE THREAD

**Issue by Atrate** [westnordost/StreetComplete#1843]
I would personally find it nice if the location button was brought back. Pressing the position indicator is much more tedious and sometimes doesn't work while in perspective mode, so just having this AND the location button back would be very nice.

v20.0-beta1
Android 10

**Comment by smichel17** [comment]
Granted you got to observe them in person and I only read your summary, but it seemed like the confusion was mostly about **un**locking from the current location. I can't speak to whether that's necessary since I haven't tried the new version yet.

@westnordost If you do bring it back, I would suggest:

- Change the layout to be like OsmAnd, with the location button to the left of the zoom out button
- While locked on, hide the location button (it's redundant with panning the map)

**Comment by westnordost** [comment]
The location pin is the location button, only that it now shows the direction to where you are in relation to the current screen position.

**Comment by matkoniecz** [comment]
> but it seemed like the confusion was mostly about unlocking from the current location.

People were completely confused how to unlock, what is purpose of that button and after explanation were still describing it as confusing and unclear.

People were describing it as confusing also after explanation. From what I remember - this part was unique and not applying to other parts of interface.

**Comment by westnordost** [comment]
I suggest both of you do not talk about this ticket while not having tested the current beta, because how else will you know what this is about?

**Comment by HolgerJeromin** [comment]
Btw the old button is rendered for a few hundred milliseconds and then hidden...

**Comment by westnordost** [comment]
Because it is shown when no location is known, either when location is off or location permission is not granted or when the app is still requesting the location from the system. This takes at least a few hundred ms.

**Comment by westnordost** [comment]
It's not planned to bring the location button back in the old form

**Comment by Atrate** [comment]
Hey,
May I know which commit changed the location button's behaviour? I'd like to restore it to the old behav in my own fork

**Comment by westnordost** [comment]
Mh, don't know it anymore. I am pretty sure that wasn't a well separated commit. Try commenting out where the visibility of the button is changed.

**Comment by Atrate** [comment]
To anyone coming across this issue, the discussion continues in #1996
