### ISSUE TITLE
Achievement Levels partially hidden behind OSM Profile Link

### ISSUE THREAD

**Issue by peternewman** [westnordost/StreetComplete#1844]
**How to Reproduce**
Menu, My Profile "Achievement Levels" button is partially hidden behind OSM Profile Link

Can't scroll it up either.

**Versions affected**
 Android 9.0 SC v20.0-beta1. I'm on a Sony Xperia XZ1 Compact which has a fairly small screen (also apparently 1,280 x 720) if that's part of the issue?

**Comment by westnordost** [comment]
Can you add a screenshot, please?

**Comment by westnordost** [comment]
Because I got a Sony Xperia Z1 Compact, it has the same resolution and it looks fine on my phone

**Comment by peternewman** [comment]
I guess it's the X bit. 

![Screenshot_20200519-113720](https://user-images.githubusercontent.com/6216436/82316763-33823600-99c5-11ea-8fdd-4e382e9f7516.png)

**Comment by westnordost** [comment]
Thanks!

**Comment by westnordost** [comment]
Ah, that's because 
"United 
Kingdom"

**Comment by westnordost** [comment]
I should probably put this into a scroll view. Though of course, in a scroll view, it will look exactly like the screenshot, only that you can scroll the view so that "Achievement levels" is completely visible.

**Comment by peternewman** [comment]
> I should probably put this into a scroll view.

That would make it future-proofed for new stats.

> Though of course, in a scroll view, it will look exactly like the screenshot, only that you can scroll the view so that "Achievement levels" is completely visible.

I assume the headshot would be a picture if I'd added one on OSM somewhere? With a fixed size so you won't want to make that smaller?

What about halving the space between the top of the first row of circles and the bottom of the overview/profile bit?

Is mine one of the smaller screen resolutions in active use currently? Do you have any stats on that either generally or within SC?

**Comment by westnordost** [comment]
> I assume the headshot would be a picture if I'd added one on OSM somewhere? With a fixed size so you won't want to make that smaller?

It's resized to a fixed size.

> Is mine one of the smaller screen resolutions in active use currently? Do you have any stats on that either generally or within SC?

Your screen (=my screen) is the smallest I seriously support, which is 360x640 in device independent pixels. Sometimes I look if a layout looks fine for a Nexus S (320x533), but not exhaustively, so no guarantee.
There are no statistics for user display sizes.

**Comment by westnordost** [comment]
I reduced the margin a bit
