### ISSUE TITLE
By Country Stats take too long to display

### ISSUE THREAD

**Issue by peternewman** [westnordost/StreetComplete#1845]
**How to Reproduce**
I've got just over 5000 quests completed, with over 4500 in one country and some elsewhere. Because of this it takes ages (almost 30s) to count up the total there. It would be better if all the times were capped at say 10s or less.

**Versions affected**
Android 9.0 SC v20.0-beta1

**Comment by smichel17** [comment]
#1832

**Comment by peternewman** [comment]
Damn, thanks @smichel17 . I looked back in closed and missed it, or this beta has been out longer than I thought.

**Comment by peternewman** [comment]
Ah, the title wasn't very obvious.
