### ISSUE TITLE
Improved visuals when changing order of quests

### ISSUE THREAD

**Issue by Sequynth** [westnordost/StreetComplete#1848]
**Introduction**
To change the order in which possible quests on an object are shown to the user, the user can adjust the order in the settings. This is done by pressing and holding on a quest until it is unhinged from the list and can be placed at a desired location. 

**Problem**
It is sometimes very hard to see when exactly the quest is unhinged, thus prompting the premature move of the finger resulting in a scrolling motion of the list rather than just movng the quest. Currently i notice a small discplacement (~5px or less) when the element is unhinged. This displacement also seems to depend on the position of the finger on the element (vertical center-> larger displacement, vertical edge -> smaller displacement).

**Proposed Solution**
A more noticable change in visuals to tell the user that the element can be moved freely, e.g. a change in background color of the quest-element or a 'wiggling' animation.

**Comment by westnordost** [comment]
The app doesn't do any displacement and stuff itself, it uses the standard drag and drop behavior of the Android system. Thus, there is also no customization of the drag and drop effect available, as far as I know.
