### ISSUE TITLE
Improve sidewalk quest in roundabouts

### ISSUE THREAD

**Issue by borjadp** [westnordost/StreetComplete#1852]
**Use case**
The sidewalk quest graphic doesn't work well with roundabouts, since it shows a straight street and it's not possible to tell which part is the inner part and which is the outer part.

**Proposed Solution**
Maybe a specific graphic for roundabouts where inner and outer parts are clearly defined, or reuse the current one and use arrows both in the graphic and the map so the user can be sure of the traffic direction.

![Roundbout](https://user-images.githubusercontent.com/4894505/82735213-ee893700-9d17-11ea-8350-62f8ec176528.jpg)

**Comment by westnordost** [comment]
The graphic at the bottom always shows the road at the point where the pin is located. So, up is out, bottom is inner.

Though I think it makes sense not to ask for the inner part. Will change that.

**Comment by borjadp** [comment]
> The graphic at the bottom always shows the road at the point where the pin is located. So, up is out, bottom is inner.

That makes sense, but it wasn't obvious to me.

> Though I think it makes sense not to ask for the inner part. Will change that.

I haven't looked for other examples, but I think in some roundabouts it makes sense, since you can also walk on the inner part.

**Comment by westnordost** [comment]
> I haven't looked for other examples, but I think in some roundabouts it makes sense, since you can also walk on the inner part.

Well, how to solve this then?

**Comment by borjadp** [comment]
> Well, how to solve this then?

Well, a new graphic with round shape and inner and outer clicable parts, would be ideal, I don't know how much work it would take.

Maybe a simpler way to make more obvious which part of the roundabout is being shown, could be to use arrows like this:

![Proposal](https://user-images.githubusercontent.com/4894505/82837801-11efe580-9ec2-11ea-9448-a61ce327a063.jpg)

**Comment by westnordost** [comment]
Unfortunately, this would be quite a lot of work to implement. I'll add one more sentence to the explanation.

**Comment by andrewharvey** [comment]
>> I haven't looked for other examples, but I think in some roundabouts it makes sense, since you can also walk on the inner part.
>
> Well, how to solve this then?

Are inner sidewalks common enough to justify asking this for every roundabout?
