### ISSUE TITLE
Add opening hours button icon lacks contrast

### ISSUE THREAD

**Issue by claudiush** [westnordost/StreetComplete#1853]
The "+" icon of the add opening hours quest button is black on dark blue blackground and therefor only barely visible. See this screenshot:
![Screenshot of icon barely visible](https://user-images.githubusercontent.com/428616/82759996-113b4e80-9df1-11ea-949c-fba14b80f0f9.jpg)

**How to Reproduce**
Open quest details of opening hours quest and review icon of "Add Opening Hours" button

**Versions affected**
Android 10
StreetComplete v20.0-beta2

**Comment by westnordost** [comment]
Well, it's the heavy plus sign:

https://www.fileformat.info/info/unicode/char/2795/browsertest.htm

For some reason, Google decided that a heavy plus sign is an emoji and added a cool gradient to it 🙄 

Three possible solutions:
- change the text to "Öffnungszeiten hinzufügen". Quite long, but should still fit
- use an image of a plus sign
- use the normal "+" sign

Solution 1 is the solution used for all the other languages except German. ("Hinzufügen" is such a long word)

**Comment by claudiush** [comment]
"Öffnungszeiten eintragen" saves one character :P

**Comment by HolgerJeromin** [comment]
You can try the unicode [text presentation selector](http://www.unicode.org/reports/tr51/#def_text_presentation_selector).

**Comment by westnordost** [comment]
I chose solution 1 now
