### ISSUE TITLE
StreetComplete doesn't understand `Bandstand` building type.

### ISSUE THREAD

**Issue by mxxcon** [westnordost/StreetComplete#1854]
There's a [feature in OSM ](https://www.openstreetmap.org/way/248500394) that's mapped as
```
building=yes
height=6.8
leisure=bandstand
```
This is based on iD editor's template.
Yet, StreetComplete is asking what type of building this is.

**How to Reproduce**
Look at https://www.openstreetmap.org/#map=19/40.57521/-73.97167 in OSM and StreetComplete.
**Versions affected**
v19.2

**Comment by westnordost** [comment]
And what is the problem?

**Comment by mxxcon** [comment]
StreetComplete shouldn't ask what type of building it is since (from my understanding) it is already properly and completely mapped..at least according to https://wiki.openstreetmap.org/wiki/Tag:leisure%3Dbandstand

**Comment by westnordost** [comment]
Well, this is about as what kind of building it was constructed as, the type of building, not (exactly) for what it is used.

Of course, this data model - to strictly separate building type from what amenity/thing is contained withing - might in some cases appear somewhat verbose. I agree that it is not intuitive.

What I could do is to not ask for the building type of a building if the element contains a key `leisure`, `amenity` or `tourism`.

The caveat would be that the app would then never ask for the address for buildings that are used as fitness centers, museums, amusement arcades, cinemas, townhalls, embassies, libraries, banks, post  offices etc.

**Comment by smichel17** [comment]
> never ask for the address

(You meant building type, I assume?)

**Comment by HolgerJeromin** [comment]
>> never ask for the address
> (You meant building type, I assume?)

I don't think so. After the building quest the user gets the address quest on the same object.

**Comment by mxxcon** [comment]
> The caveat would be that the app would then never ask for the address for buildings that are used as fitness centers, museums, amusement arcades, cinemas, townhalls, embassies, libraries, banks, post offices etc.

We definitely wouldn't want for the app to bail out on asking additional data enrichment questions..
However, the completionist/OCD in me gets that uneasy feeling if I were to ignore that quest. At the same time I wouldn't want to undo the correct mapping (from my understanding) done in iD by selecting some random building option..

**Comment by matkoniecz** [comment]
Adding specific building value matching reality is not undoing a correct mapping.

Would it be OK to describe bandstand as a special case of roof (at least that is what I selected for one in the nearby park, in this case it was matching)?

**Comment by westnordost** [comment]
In this case, roof sounds ok. However, we had some confusion with the building quest in the past as well. For example, users complained that they cannot select "police station", "fire station" etc. obviously thinking the quest is also to describe what amenity it is exactly. And it is only intuitive to think the quest works like this.
So maybe I should really exclude all buildings whose purpose (amenity/tourism/leisure) has already been recorded to avoid confusion. Maybe later the housenumber quest could be extended to include not only buildings but certain amenities/shops/etc. as well.
