### ISSUE TITLE
Type of pavement

### ISSUE THREAD

**Issue by Rumberto86** [westnordost/StreetComplete#1855]
I have a question.  In Poland, most pavements are made of such concrete tiles.  When selecting them, what kind should I select if they are not already on the lists?  The school's catalog lacks a nursery for children and a kindergarten for children.
![DSC_0035](https://user-images.githubusercontent.com/65910740/82826079-b5ce9680-9eac-11ea-946b-956b50f6b456.JPG)

**Comment by matkoniecz** [comment]
That is `surface=paving_stones`, currently translated as "brukowa".

See https://wiki.openstreetmap.org/wiki/Tag:surface%3Dpaving_stones

Maybe more than one image would be useful to capture variety of `surface=paving_stones`.

> When selecting them, what kind should I select if they are not already on the lists? 

The should be "can't say" ("Odpowiedź niemożliwa…") that allows to leave note (with an optional photo), if available answers are not capturing situation or question makes no sense (like asking about name of shop that is not existing).

> The school's catalog lacks a nursery for children and a kindergarten for children.

? I am unsure what are you asking here.

O co chodzi z żłobkiem i przedszkolem? Który katalog szkół?

**Comment by matkoniecz** [comment]
ping @Rumberto86

**Comment by Rumberto86** [comment]
Żłobek jest dla dziecka 1-3 letniego.
przedszkole dla 3-6 roku.
od 7roku zaczyna się szkoła.

**Comment by smichel17** [comment]
I think it is about the building type quest. There are options for university, school, and kindergarten, but not nursery (for even younger children).

**Comment by matkoniecz** [comment]
> I have a question. In Poland, most pavements are made of such concrete tiles. When selecting them, what kind should I select if they are not already on the lists?

#2088 intended to help with that confusion and explicitly include multiple types of paving stones, including big square ones
