### ISSUE TITLE
Quests "blocking/hiding" each other when too close

### ISSUE THREAD

**Issue by rYR79435** [westnordost/StreetComplete#1857]
If multiple quests are close to each other, some are only shown as little dots, which are unclickable. This forces the user to solve the quest which is "blocking/hiding" others.

One possible fix would be to allow the user to (maybe temporarily) hide that quest (read: remove its quest bubble).

**How to Reproduce**
Go to a place with multiple quests next to each other.
[Image](https://imgur.com/a/qIln9hE)

**Versions affected**
19.2

**Comment by westnordost** [comment]
Yes, this is known and not better solvable than it is currently.

You have the following options:
- Reorder the quest priority in the settings. Quests that are at the top are also displayed on top on the map
- Hide the particular quest you are not interested in: Tap on it, press "Can't say", then press "Hide". This is not temporary though
- Temporarily hide all quests of one type in the same screen where you can reorder the quests types.

**Comment by smichel17** [comment]
Granted I don't live in a particularly dense area, but I'm also often able to get a dot to expand with the camera controls -- ie, zooming in and panning the map.
