### ISSUE TITLE
House numbers not recognized when mapped on entrance on building part

### ISSUE THREAD

**Issue by DennisKempel** [westnordost/StreetComplete#1858]
Compare address Lyserstraße 30, 22761 Hamburg for example. I mapped the house numbers for the buildings as the quest was raised by SC. However, the housenumbers were already given. Each of this buildings has a seperate small entrance building (building:part=yes). And this building part has an entrance and each is mapped with the correct house number. I think this should be changed as otherwise JOSM will complain about double house numbers...

**How to Reproduce**
See above

**Versions affected**
SC v20.0-beta2

**Comment by matkoniecz** [comment]
I believe that https://www.openstreetmap.org/way/679667197#map=19/53.56276/9.90056 is currently mapped incorrectly.

`building:part=yes` should be always within `building=*` geometry.

> In addition to the different ways tagged building:part=yes, there should be one area (closed way) marking the outline of the whole building, tagged with building=*.

https://wiki.openstreetmap.org/wiki/Key:building:part

**Comment by matkoniecz** [comment]
Basically the number is currently tagged outside building rather than inside or on its edge.

**Comment by westnordost** [comment]
See @matkoniecz
