### ISSUE TITLE
Describe quests in config file instead of a java class

### ISSUE THREAD

**Issue by gustavecha** [westnordost/StreetComplete#186]
Hi all,

I've recently discovered this project and was looking forward to add new quest.

Files like this more look like a config file than an actual class.
https://github.com/westnordost/StreetComplete/blob/master/app/src/main/java/de/westnordost/streetcomplete/quests/building_levels/AddBuildingLevels.java

Would it sound acceptable to move existing quests to a yaml or json file from all classes?
It will enable more people to develop their own quests than now.

All the best

**Comment by westnordost** [comment]
Duplicate of #98
