### ISSUE TITLE
[question] House number quest & unit

### ISSUE THREAD

**Issue by Helium314** [westnordost/StreetComplete#1860]
I had some cases where I was asked the house number where a bunch of houses shared the same house number, but have a different unit number (e.g. 43/1, 43/2,...). Since StreetComplete does not give any information about unit numbers, this can potentially lead to wrong tagging (and did for me). Until recently I wasn't even aware that addr:unit exists, and only found out because I looked at houses I tagged using openstreetmap.org which then had "double" unit numbers (43/1/1, 43/2/2,...).

So it might be good to make the user aware that there is a unit number, or show unit number if it is tagged, or don't ask for house number if addr:unit exists (assumption: whoever added unit numbers added the common house number somewhere).

Should something be changed there, or am I the only one who tagged this wrong?

**Comment by matkoniecz** [comment]
What you mean by wrong/incorrect edit?

Adding `addr:housenumber=43` would be correct though incomplete. Unit number identifying house and added as  `addr:housenumber=43/1` without using `add:unit` seems also OK for me (after all, it is number of a house).

Though `addr:unit=1` + `addr:housenumber=43/1` seems wrong it is unclear to me how it may happen.

**Comment by Helium314** [comment]
It happened because I thought house number 43/1 would be correct, but the house already had addr:unit=/1 and I could not see this in StreetComplete.

But now that I think about it... could it be that addr:unit is actually shown on the map, but I did not see it because of the outdated map tiles?

**Comment by westnordost** [comment]
Shouldn't it be `addr:unit=1` or something then?

**Comment by Helium314** [comment]
Maybe yes. I looked a bit around and found both styles, addr:unit=1 and addr:unit=/1
Anyway, I think it would be useful to know if addr:unit is already present when asking for house numbers

**Comment by westnordost** [comment]
What do you mean exactly? Should the app not ask for the housenumber if the unit was set?

**Comment by Helium314** [comment]
Either not ask for house number, or bett show that the unit number is already present.
In the latter case I know that I should use 43 and not 43/1

**Comment by westnordost** [comment]
Who is going to understand what a "unit number" is though? "What housenumber does the building with the unit number */2* have?" -  sounds confusing.
You will usually see on the number plate something like "43/1", so why dissect it at all? I've always tagged housenumbers as they appear on the sign, and if the sign says "43 house 1", then that's the housenumber.

 I am really puzzled what kind of situation would lead to the unit number being recorded but not the housenumber, is it not on the same plate?

**Comment by Helium314** [comment]
No, there are cases where there is one plate for the house number, and each unit has a separate plate containing just the unit number (this is actually pretty common).

Example: https://www.openstreetmap.org/#map=19/48.24561/16.42556
On site there is one house number plate, and each unit has a sign with (only) the unit number.
On the map the number 2 is floating around (and displayed in the app), the unit numbers on the houses is present but not shown in StreetComplete.
The app is asking for house numbers, so I would tag 2/1, 2/2, ... which would (as far as I now understand) be correct, but only if addr:unit was not present.

**Comment by westnordost** [comment]
Hm, all the buildings are part of a relation: https://www.openstreetmap.org/relation/9425768#map=19/48.24551/16.42589

Hui, I wonder if this is standard in any way, or if the user who created that made up this scheme.

StreetComplete would understand it if the housenumber 2 would actually be an area that encloses all those buildings.

**Comment by westnordost** [comment]
It appears that at that site, all those buildings have three housenumbers:

Weinwurmweg 1, Fiebrichgasse 16 and Drygalskiweg 2, hence the unusual tagging.

Okay, hm, next steps:
- find out if how this is tagged is in any way standard or documented anywhere. StreetComplete cannot account for made-up tagging schemes.
- Evaluate if it is necessary to support standard/documented address tagging schemes to exclude buildings from the housenumber-question that are part of a relation that has a housenumber. For associatedStreet relation perhaps? And if it is not necessary, perhaps it is still relatively easy to do to exclude quirky cases like this example.

**Comment by westnordost** [comment]
[It is actually documented:](https://wiki.openstreetmap.org/wiki/Addresses#Buildings_with_multiple_house_numbers)

> ### Multiple buildings for one housenumber
> This often happens in farms, factories or schools. In that case, it's possible to add a perimeter to the site which contains the addr tags and other general tags such as the name. This makes sure you have less redundancy in your data. If the buildings cannot be contained in a single perimeter (for example, school with two buildings a block apart), use a multipolygon relation or site relation.

**Comment by westnordost** [comment]
So I'd classify this as a bug

**Comment by mnalis** [comment]
- (related `addr:unit` comments: https://github.com/streetcomplete/StreetComplete/issues/4196#issuecomment-1182802988 and below)
