### ISSUE TITLE
single space at the end of streetnames

### ISSUE THREAD

**Issue by BeKri65** [westnordost/StreetComplete#1861]
Hi everybody,
my first bug report, hope doing right.

Doing some correction at
http://81.190.82.62:31337/QA_map/mismatched_street_names_de.html
a had now serveral times at the end of a streetname a single space

Now I had a new on to see:
https://www.openstreetmap.org/changeset/85892526
https://www.openstreetmap.org/way/268569690/history
"Gögginger Straße " had an extra " " at the end

**How to Reproduce**
I didn't use Streetcomplete (yet) so I can't give information

**Versions affected**
see above

May be same situation :
javascript:editObjects('w178431872,w154819403') Hauptstraße

Hope it helps
Greeting derBeKri

**Comment by Helium314** [comment]
Several keyboard app add a space after tapping a word for auto-complete, that's probably how it happens.

**Comment by westnordost** [comment]
Normalerweise schneidet die App bei Nutzereingaben immer vorne und hinten Leerzeichen ab. An dieser Stelle scheine ich das vergessen zu haben.

Usually the app trims whitespaces at the beginning and end. It seems at this point I have missed it.

**Comment by matkoniecz** [comment]
>  my first bug report, hope doing right.

Just to confirm: it is a great bug report, thanks for mentioning it here.

**Comment by BeKri65** [comment]
OK, thank you und
good to help you.
