### ISSUE TITLE
Quest: add addr:flats to apartment buildings

### ISSUE THREAD

**Issue by Miroff** [westnordost/StreetComplete#1862]
### General
Large apartment buildings usually has few entrances, each of them leads to some number of flats. it is crucial to know what entrance lead to given flat when navigating around such buildings. 

Affected tag(s) to be modified/added: [addr:flats](https://wiki.openstreetmap.org/wiki/Key:addr:flats)
Question asked: **What number of flats behind the door?**

Number of flats can be a simple range (1-20), semicolon-separated list (1;3;5) or a single number (2A). User may enter any variant, he sees on a label next to a door.

### Checklist
Checklist for quest suggestions (see guidelines):
- [+] 🚧 To be added tag is established and has a useful purpose

I think so, this tag is rendered in default Mapnik style, and OsmAnd navigator and used for navigation.

- [+] 🤔 Any answer the user can give must have an equivalent tagging (Quest should not reappear to other users when solved by one)
- [+] 🐿️ Easily answerable by everyone from the outside but a survey is necessary 
- [+] 💤 Not an overwhelming percentage of elements have the same answer (No spam)

This quest should be limited to certain types of building and certain types of entrances only. See implementation suggestions below.

- [+] 🕓 Applies to a reasonable number of elements (Worth the effort)

### Ideas for implementation

**Element selection:** 

Select all building outlines in the area, then select all entrance nodes from those outlines: 

```[out:json][timeout:300];
(
  way[building=apartments]({{bbox}});
  relation[building=apartments]({{bbox}});
  way["building:part"=apartments]({{bbox}});
  relation["building:part"=apartments]({{bbox}});
  >;
)->.buildings;

(
  node(w.buildings)[entrance~"yes|staircase"][!"addr:flats"];
);

out meta;
```

**Proposed GUI:**

1. The only input box is shown. User may enter anything, but the input is sanitized after submission. All extra spaces are removed, all commas are replaced to semicolons. Then this input is added as a value of addr:flats tag. If entrance=yes it should be changed to entrance=staircase

2. Other answers are:
2.1 "This is not an apartment building" In this case building type may be changed to generic building=yes if it is possible, or note may be created. 
2.2 "This is an emergency exit" In this case entrance=emergency tag should be set
2.3 "This is a service entrance" In this case entrance=service tag should be set
2.4 "This is a public entrance to a shop or office" In this case entrance=main tag should be set
2.5 "There is no entrance here" In this case entrance tag should be removed
2.6 "I'm not sure" nothing is changed

**Comment by HolgerJeromin** [comment]
We would have reduce the quest to buildings with more than one entrance. This would reduce the false positives. 

Access=private should be filtered (and tagged), too.

**Comment by HolgerJeromin** [comment]
https://www.openstreetmap.org/way/83911245#map=19/50.78664/6.07224
has two entrance which leads to the same central staircase...

**Comment by westnordost** [comment]
What about apartment buildings where every entrance actually has an own housenumber and not a flat number?

**Comment by peternewman** [comment]
> semicolon-separated list (1;3;5)

Why does addr:flat use semicolons, but addr:housenumber allow either commas or semicolons:
https://wiki.openstreetmap.org/wiki/Addresses#Buildings_with_multiple_house_numbers

And I believe SC encourages commas for this.

**Comment by westnordost** [comment]
So, I summarize the further filters:
1. Only display for entrances that do not have a housenumber, housename, conscription number or street number tagged on them.
2. Only display for entrances that are either undetermined (=yes) or tagged as staircase entrances. **Alternatively**, only display entrances that are tagged as staircase and put the determination of what kind of entrance it is into an own quest.
3. Only display for entrances that are not tagged as private
4. After filtering out 1., 2., 3., only display for buildings that have multiple of such entrances (https://github.com/westnordost/StreetComplete/issues/1862#issuecomment-636322394)
5. Only display for apartment buildings that _already have_ a housenumber, housename, conscription number or street number tagged

...

Now there is the difficulty that I mentioned (https://github.com/westnordost/StreetComplete/issues/1862#issuecomment-636355911).
One solution:

6. a) **If the housenumber of the building is a range** (f.e. 4-8) or a list (1;2;4) or both, label the input field with "housenumber of this entrance" or similar and tag the input as `addr:housenumber` 
6. b) **If the housenumber of the building is not a range**, label the input field with "flats numbers" or similar and tag the input as `addr:flats`
7. Probably the label for the input should be a dropdown where the user can choose whether it is a flat number or a house number, alternatively there is an other-answer-option that would switch the layout.

All in all, it is quite an effort, not sure if it is worth it.

**Comment by peternewman** [comment]
> 2. Only display for entrances that are either undetermined (=yes) or tagged as staircase entrances. **Alternatively**, only display entrances that are tagged as staircase and put the determination of what kind of entrance it is into an own quest.

Why does this need to be restricted to only staircases? I can think of a few examples (for example tunnels) or single story blocks or split level maisonette type things.

**Comment by westnordost** [comment]
Because what will the user answer / what shall be tagged if an unspecified entrance does indeed not have flat number(s)?

**Comment by peternewman** [comment]
> Because what will the user answer / what shall be tagged if an unspecified entrance does indeed not have flat number(s)?

I don't know if you're replying to me or someone else @westnordost , but because there are lots of other non-staircase entrances which might be for a set of flats, entrance=gate and entrance=residence stand out from taginfo and home/main/secondary/service as potential ones from the wiki.

**Comment by westnordost** [comment]
To you.

**Comment by westnordost** [comment]
So if the user answers "there are no flat-numbers on this door", what should be tagged?

**Comment by peternewman** [comment]
> So if the user answers "there are no flat-numbers on this door", what should be tagged?

I don't know, whatever is already planned for staircase entrances, although I'm guessing that has the same issue. What guarantees every staircase will?

My point was more that I know of a number of real world examples where the entrance to a block of flats isn't via a staircase, and therefore restricting it to only that type of entrance would mean equally valuable data couldn't be collected.

Terrible example, and not a greatly indicative photo, but there could be something like this with gates at either end of a block, so you'd want to know which end to enter:
http://www.kjbramble.co.uk/html/detail.asp?folioID=599

Or things similar to this, where one set of entrances has no stairs to get to the flat numbers, it's entirely flat (if you'll pardon the pun):
https://en.wikipedia.org/wiki/Scissor_section_flat

>     4. After filtering out 1., 2., 3., only display for buildings that have multiple of such entrances ([#1862 (comment)](https://github.com/westnordost/StreetComplete/issues/1862#issuecomment-636322394))

The scissor one has the challenge the entrances may be of different types, one staircase, one flat.

**Comment by westnordost** [comment]
> I don't know, whatever is already planned for staircase entrances, although I'm guessing that has the same issue. What guarantees every staircase will?

Okay, actually I assumed that any staircase on an apartment building that has a housenumber would lead to flats. So, this is a problem.

**Comment by peternewman** [comment]
> Okay, actually I assumed that any staircase on an apartment building that has a housenumber would lead to flats. So, this is a problem.

A fire escape jumps out at me as the obvious one or perhaps a staircase to a basement bin room/garages.

The scissor style one I know well is built on a hill, so you actually enter the road flat in the middle of the building and walk along a level corridor with flats either side. Instead of going along the corridor you can  also go downstairs to the garages (on the low side of the building). You might be able to enter from that side too, I've never tried. There is also a fire escape at the far end going downstairs (to the low side of the hill). So that's potentially three entrances, two share the same set of flat numbers, one doesn't have any.

Possibly see also bits of this:
https://en.wikipedia.org/wiki/City_of_London_Pedway_Scheme

Where up and down and bits of staircase in apartment buildings might not do what's normal (although don't quote me on that, I've not explored them a lot, let alone seen how they're mapped in OSM).

**Comment by westnordost** [comment]
Looking through the discussion again and the problems presented, I unfortunately see no way how the issues mentioned can be solved (by making the element selection smarter). So unfortunately, tagging flat numbers will not be possible with streetcomplete, a "classic" survey is necessary. But on the other hand, I think this does not concern so many elements. Many such places where this usually would apply are also tagged like `addr:housenumber=97/4` (housenumber 97, flat/entrance/house/section 4)

**Comment by andrewharvey** [comment]
I'd suggest for this quest it's ask on the building way, and the user can either enter the flats within the building, or under other answers "Varies by entrance" in which case the entrances need to be mapped first before the `addr:flats` can then be set on the entrances.

> Many such places where this usually would apply are also tagged like addr:housenumber=97/4 (housenumber 97, flat/entrance/house/section 4)

A bit off topic but I realise now why that's a bad practice, because you can't assume if it's unit/number or number/unit format.

Another quest could find instances like this and ask the user is this actually housenumber 97 and unit 4 or housenumber 4 or unit 97 and retag those correctly as `addr:unit` and `addr:housenumber`.
