### ISSUE TITLE
Add wood as suitable surface

### ISSUE THREAD

**Issue by Mannivu** [westnordost/StreetComplete#1863]
Especially in some rural area, some bridges are made of wood. However, wood is not a suggested surface on the app. I think that wood could be added as a surface but only if there's a bridge tag on the highway, since I don't think there are roads made of wood.

**Comment by Atrate** [comment]
You can certainly find paths made of wood, esp in the mountains, haven't seen a wooden non-bridge road, thougj

**Comment by matkoniecz** [comment]
Have you tried selecting paved surface option and possibly scrolling a bit? Because wood is listed and available.

What is the language of your phone? Maybe it was mistranslated.

**Comment by Mannivu** [comment]
Ok, so I see wood it's not a bridge-only surface (my bad, I must travel more).

@matkoniecz my phone is in italian. However, I've found the wood surface (I was looking at "road" quests, not path quests), but only for steps, not for plain paths.

**Steps**
![photo_2020-05-30_15-21-18](https://user-images.githubusercontent.com/42747216/83329345-44665d80-a289-11ea-914f-d656c891859b.jpg)

**Plain path**
![photo_2020-05-30_15-21-19](https://user-images.githubusercontent.com/42747216/83329360-56480080-a289-11ea-8d5d-daced580c790.jpg)

**Comment by matkoniecz** [comment]
"Monstrane altre..." should mean something like "Show more..."

Clicking on it should show ability to select first surface category then the exact surface.

Is it not working or confusing for some reason?

**Comment by Mannivu** [comment]
Yes, you are right. I've found it. I always thought these were generic surfaces, not categories. Maybe a more specific description on top, something like "Choose the more suitable category" would be less confusing.
![Screenshot_2020-05-30-15-55-42-720_de westnordost streetcomplete](https://user-images.githubusercontent.com/42747216/83330396-e3418880-a28e-11ea-8156-6bc397b036ff.jpg)

**Comment by RubenKelevra** [comment]
So this can be closed, or was the UX too surprising? 🤔

**Comment by Mannivu** [comment]
I really don't know. I think the phrase "Select the most specific one that fits:" might be a little confusing or misleading. I think this should be to something that tells clearly the users that those are Macro-Categories and not generic answers.

**Comment by RubenKelevra** [comment]
Well, as soon as the user will click on one of those "macro categories" - which are also fine for non-specific values, they will extend and show the user more specific values.

So it might be slightly surprising, but I think it's fine, since the UI will basically "teach" the user how it works.

**Comment by matkoniecz** [comment]
Note that we have direct evidence that sometimes it is confusing and not working.

**Comment by Mannivu** [comment]
@RubenKelevra I understand what you mean. But many times I needed to add a surface that was not in the 6 basic answers and, since I thought those three were generic answers, I edited the feature with Vespucci or I waited until I got home and edited the map using JOSM. It's no big deal for me, but I know how to use different app to edit the map. But what would a less skilled user do? Leave a note? Dismiss the editing and forget about it? Maybe another user could do the proper edit a bit later, but why wait another user when we can simply use a different phrasing to make the app more clear?

**Comment by RubenKelevra** [comment]
Well, I don't think there's an issue with showing just 6 pictures and a large "show more" button.

What about that is confusing?

**Comment by Mannivu** [comment]
About that nothing. It's the next dialog that is confusing to me. When clicking "show more" you are shown a dialog that says "Select the most specific one that fits:" giving the user three options: Paved (generic), Unpaved (generic) and Ground (generic). Before matkoniecz explained me that those are categories, I thought that clicking on one of that would put a generic tag. Let's say I needed to add a "surface=wood" to a path, but I couldn't find it in the 6 pictures; I thought that after clicking "Show more" and then on "Paved (generic)" the app would have tagged the path with "surface=paved". But, since this was wrong, I didn't want to add this tag, so I exited the app and edit the map with another app.

**Comment by westnordost** [comment]
The UI for the building types looks the same. Did you have any problems understanding there that those are expandable categories?

Am 31. Mai 2020 11:07:49 MESZ schrieb Manuel Tassi <notifications@github.com>:
>About that nothing. It's the next dialog that is confusing to me. When
>clicking "show more" you are shown a dialog that says "Select the most
>specific one that fits:" giving the user three options: Paved
>(generic), Unpaved (generic) and Ground (generic). Before matkoniecz
>explained me that those are categories, I thought that clicking on one
>of that would put a generic tag. Let's say I needed to add a
>"surface=wood" to a path, but I couldn't find it in the 6 pictures; I
>thought that after clicking "Show more" and then on "Paved (generic)"
>the app would have tagged the path with "surface=paved". But, since
>this was wrong, I didn't want to add this tag, so I exited the app and
>edit the map with another app.

**Comment by Mannivu** [comment]
Yes, I didn't know they are expandable. I thought they add generic tag.

**Comment by westnordost** [comment]
Okay. If you have an idea how to make the UI more clear that it is categories you can expand, please feel free to open a new issue with the suggestion. I am closing this because it was just a misunderstanding and indeed it is possible to tag a way with surface wood.
