### ISSUE TITLE
Quests are shown as scanned for even if actually disabled

### ISSUE THREAD

**Issue by matkoniecz** [westnordost/StreetComplete#1865]
"What is the reference number of this postbox?" is shown as scanned for in countries where quests is disabled, as long as many quick scanning quests.

Not checked for now whatever it is actually running queries or is it just shown, query skipped and some timeout is applied despite query never running (I am trying to debug mysteriously missing quest).

**How to Reproduce**
Enable "What is the reference number of this postbox?" quest.
Move location to Poland or other country where not enabled.
Start scan.

**Versions affected**

9, v20.0

**Comment by matkoniecz** [comment]
> Not checked for now whatever it is actually running queries or is it just shown, query skipped and some timeout is applied despite query never running (I am trying to debug mysteriously missing quest).

Looking at logs it appears that both cases are happening.

`AddAcceptsCash: Skipped because it is disabled for this country`

but

`05-30 17:35:53.226 31793-31947/de.westnordost.streetcomplete.debug D/QuestDownload: AddPostboxRef: Not adding a quest at 50.0666674, 19.9291508 because the quest is disabled in this country`


```
05-30 17:35:48.395 31793-31947/de.westnordost.streetcomplete.debug I/QuestDownload: AddAcceptsCash: Skipped because it is disabled for this country
05-30 17:35:48.412 31793-31947/de.westnordost.streetcomplete.debug I/QuestDownload: (19.9072265625,50.0641917366591,19.951171875,50.0923932109388) Finished
05-30 17:35:52.025 31793-31793/de.westnordost.streetcomplete.debug I/QuestAutoSyncer: Checking whether to automatically download new quests at 50.07842326,19.93229712
05-30 17:35:52.073 31793-31942/de.westnordost.streetcomplete.debug I/AutoQuestDownload: Not downloading quests because there are enough quests in 600m radius
05-30 17:35:52.104 31793-31947/de.westnordost.streetcomplete.debug I/QuestDownload: Quest types already in local store: AddAcceptsCash, AddAddressStreet, AddOpeningHours, AddRoadSurface
05-30 17:35:52.105 31793-31947/de.westnordost.streetcomplete.debug I/QuestDownload: (19.9072265625,50.0641917366591,19.951171875,50.0923932109388) Starting
05-30 17:35:52.105 31793-31947/de.westnordost.streetcomplete.debug I/QuestDownload: Quest types to download: OsmNoteQuestType, AddPostboxRef
05-30 17:35:53.220 31793-31947/de.westnordost.streetcomplete.debug D/QuestDownload: AddPostboxRef: Not adding a quest at 50.0844634, 19.9356167 because the quest is disabled in this country
05-30 17:35:53.222 31793-31947/de.westnordost.streetcomplete.debug D/QuestDownload: AddPostboxRef: Not adding a quest at 50.07173, 19.9133661 because the quest is disabled in this country
05-30 17:35:53.223 31793-31947/de.westnordost.streetcomplete.debug D/QuestDownload: AddPostboxRef: Not adding a quest at 50.0676976, 19.9498183 because the quest is disabled in this country
05-30 17:35:53.226 31793-31947/de.westnordost.streetcomplete.debug D/QuestDownload: AddPostboxRef: Not adding a quest at 50.0666674, 19.9291508 because the quest is disabled in this country
```

**Comment by westnordost** [comment]
Well, technically it _does_ download quests that are disabled in a country but if the box in which it downloads is completely in a country for which the quest is disabled, the download will return immediately. If the box is only partly in a country for which the quest ist disabled, it will download and exclude individually each found quest that is in that country.

**Comment by westnordost** [comment]
I rather not change this behavior because that would introduce going through some inconvenient loops in the code.

Note that this is only about quests that are disabled in the country one is in, so has nothing to do with disabling the quest type by user interaction. These are really not downloaded at all if disabled. Since no user action is involved, there can not arise an uncertainty like "huh, why is it downloading, I thought I disabled the quest type?!".
