### ISSUE TITLE
Allow sliding through introductory screens

### ISSUE THREAD

**Issue by matkoniecz** [westnordost/StreetComplete#1867]
**Use case**
In apps that I encountered it is typically possible to

- get back to the previous screen

- move to previous/next by sliding gesture - at least that what I tried at first

**Proposed Solution**
Support sliding gesture (and optionally also add "back") UI button.

Maybe also support "back" action. Currently it exists app and intro is lost.

I just tested:

uninstall app
install app
click next
use "back" action to see the previous screen

app exists, on reopening intro screens are lost (and inaccessible from "about" menu)

Not sure whatever "support "back" action", "link intro from about menu" "do not exit app if selected back on intro screens" are worth reporting as separate issues or should be classified "feel free to make a PR".

**Comment by westnordost** [comment]
Going back would actually mean considerable implementation effort.

But if you send the app to the background via back (or does "back" actually exit the app, I am not sure, I thought it wouldn't) and if you bring it back to foreground, the tutorial is gone, that's a bug. Does it behave that way?

**Comment by matkoniecz** [comment]
> if you bring it back to foreground, the tutorial is gone, that's a bug. Does it behave that way?

Yes. Old phone (with Android 6)

> Going back would actually mean considerable implementation effort.

Then not worth it.

**Comment by matkoniecz** [comment]
> But if you send the app to the background via back (or does "back" actually exit the app, I am not sure, I thought it wouldn't)

Sends to background, and yes I retested again - and tutorial is gone.

**Comment by matkoniecz** [comment]
What about allowing to slide forward (in addition to allowing use of a "next" button)?

Looking at https://github.com/westnordost/StreetComplete/commit/9748840fe3b7efa94d23ae2956e52a835701458f it is not changed and it was not wontfixed like allowing to get back to a previous screen.

**Comment by westnordost** [comment]
Having a slide forward when not having a slide backward would be a bit weird.

Also, sliding can happen by accident. That wouldn't be a problem if there was a slide-back, but there isn't

**Comment by smichel17** [comment]
There are only 3 slides, maybe an easier implementation would be to add a back button that goes all the way to the beginning. It would be unexpected, but at least someone who wanted to see an earlier slide could do so.
