### ISSUE TITLE
Quest: Power poles material

### ISSUE THREAD

**Issue by gustavecha** [westnordost/StreetComplete#187]
Hi,

According to taginfo, only a small amount of power=pole nodes have a material=* value.
This key is used to indicate whether a given pole is made of wood, concrete, metal or whatever.
It's useful to now that to detect the most climate vulnerable poles (wood) in the country.

Such information (only 3 values for material key) is easy to gather but needs a lot of survey since it can't be seen on aerial imagery.
It would be great to ask for material=* key on power=pole objects which haven't.

We can start with those values:
*material=wood
*material=concrete
*material=metal
I can provide corresponding pictures if needed

let me know if you agree.

**Comment by westnordost** [comment]
Is this an approved tag? Do you have a wikipedia link?

**Comment by gustavecha** [comment]
Yes power=pole is approved and material appears in its reviewed tagging guidelines
https://wiki.openstreetmap.org/wiki/Tag:power%3Dpole#Tagging

**Comment by rugk** [comment]
BTW, what is actually the value added by this quest? By today's standards (see Contributing etc.) I guess this would not be included, as – apart from 3d rendering – I hardly see a use case for why to map the material of each single pole.

**Comment by gustavecha** [comment]
What standards are you talking about?
Mapping poles material is really useful to detect vulnerable points on power lines. Wooden poles are less resistant to wind than concrete ones.
Concrete poles are unlikely expected to rust instead of iron ones.
Etc

As StreetComplete propose values instead of allowing users to type their own, it would be really hard to propose operator=* ones. Dozen of different operator may be found in some areas.

**Comment by rugk** [comment]
> What standards are you talking about?

Mostly https://github.com/westnordost/StreetComplete/wiki/Adding-new-Quests-to-StreetComplete (and the issue template for new issues here)

Okay, that "resistance" argument is a thing, I wonder about the target audience (I mean, possible city planers or so, but they should have such stats :wink:), but well… does not matter.
This just came to my mind when I saw the quest. I just wondered, "hmm, who would need that information?"…

**Comment by gustavecha** [comment]
And let's include ones who need it the most : power grid operators
Many of them in Europe don't have this information in their asset management systems.
OSM and crowdsourcing is an opportunity for us to get accurate information and for the community to show its strength.
