### ISSUE TITLE
Add 'this is only a part of a building' for house (number) quests

### ISSUE THREAD

**Issue by RubenKelevra** [westnordost/StreetComplete#1870]
There are many different house quests in SC, but as far as I found, none of them gives the user advice if the 'house' is just a small part of a building.

This is especially problematic for house number quests, where we might up ending with two buildings next to each other with the same house number, because the user just tagged both (building parts) with the correct house number.

**Use case**
In those situations the  building shape needs to be reevaluated in a different editor, tagging both current _houses_ as building parts.

**Proposed Solution**
Add 'this is only part of a building' and prefill a note with a text which explains the situation, while the user can choose to add details or a photo.

**Comment by westnordost** [comment]
Did you know that this answer option already exists for the building type quest?

Am 31. Mai 2020 07:45:40 MESZ schrieb "@RubenKelevra" <notifications@github.com>:
>There are many different house quests in SC, but as far as I found,
>none of them gives the user advice if the 'house' is just a small part
>of a building.
>
>This is especially problematic for house number quests, where we might
>up ending with two buildings next to each other with the same house
>number, because the user just tagged both (building parts) with the
>correct house number.
>
>**Use case**
>In those situations the  building shape needs to be reevaluated in a
>different editor, tagging both current _houses_ as building parts.
>
>**Proposed Solution**
>Add 'this is only part of a building' and prefill a note with a text
>which explains the situation, while the user can choose to add details
>or a photo.

**Comment by RubenKelevra** [comment]
@westnordost I don't think so:

There's an "multi purpose" option for building types as well as "differ per building part" for the building level quest.

The issue here is the other way around: One actual building in reality is mapped as two separate building shapes. So the user is asked twice for one actual building to supply a house number.

There are only three "other answers" for this quest:

* Multiple numbers
* No number but a name
* No house number

Since nothing fit exactly this case the user might either choose the first or the third option.

The first option would add maybe lead to two numbers assigned to an OSM building, which is actually just the connection between two real buildings which is mapped wrong.

The last option would add a wrong tag. 

---

I found that many houses here are mapped the way that the main buildings are a house in OSM and the extention between them, which connects them is mapped as an additional building.

So you end up with 3 buildings connected to each other and the building in the middle will show up as an house number quest:

![Screenshot_20200531-124010~2](https://user-images.githubusercontent.com/614929/83350394-0d04b900-a33c-11ea-9f94-000eff2bf850.jpg)

**Comment by westnordost** [comment]
Well, if trying to tag "no house number", a warning is shown that explains the rammifications. The warning should make it clear that the app started from wrong assumptions, that is, that this building part is actually an own building. And such cases - in cases where there is a mistake on the map - users are encouraged to leave a note instead.

To be honest, I often stumble upon such cases and I am usually too lazy to leave a note, so I just hide or ignore the quest for now and decide to do it later on the PC, but then forget about it.
I can imagine that some users are lazy and choose the third option anyway, but I don't think the error, if you can even call it that way, is very significant. For many of these kind of house-extensions it is often unclear whether they may actually be sheds (or garages) and it is also a smooth transition from "this is one and the same building" and "this extension is an own building".

Your proposed solution though would be a will-not-fix, because StreetComplete should not prefill a note with automatically generated text.

**Comment by RubenKelevra** [comment]
> Your proposed solution though would be a will-not-fix, because StreetComplete should not prefill a note with automatically generated text.

Didn't knew that. We had some generated texts early on, IIRC.

In this case, a dedicated selection for the users would be good.

"This is only part of one or more building(s)" -> popup "This building is wrongly mapped, please fill out a node and add a picture to help other mappers to fix this issue"

**Comment by westnordost** [comment]
Yes, something like that. The other-answer-option would need to be a little shorter worded though.

**Comment by westnordost** [comment]
Hm on the other hand, why wouldn't this be covered by the "Can't say" option?

**Comment by RubenKelevra** [comment]
> Hm on the other hand, why wouldn't this be covered by the "Can't say" option?

Can't say feels more like a "I cannot determine/find this information". But in this case the information is available.

**Comment by westnordost** [comment]
My point is that the tutorial explicitly states 

>Whenever you are uncertain, you can always reply "Can\'t Say" and leave a note

and that the warning if one wanted to tag with with "no house number" also specifically asks for whether this isn't just a part of a building

![image](https://user-images.githubusercontent.com/4661658/83357118-c11d3880-a36a-11ea-8830-0b7287ba1779.png)

With the option "No (leave note)".

So if the user is not sure what to answer, he will press "Can't say". If he recognizes it is part of another building and/but chooses to answer "no house number", he will also be led to creating a note. Why isn't that enough?

**Comment by westnordost** [comment]
I reread this issue, based on my last comment I rather leave it as it is.
