### ISSUE TITLE
Extend maxspeed quest

### ISSUE THREAD

**Issue by RubenKelevra** [westnordost/StreetComplete#1871]
I think the maxspeed quest is currently only shown if there's no maxspeed=* value tagged on the street.

**Use case**
It feels like 50% of the maxspeed value around here are just plain wrong and many many years old, it's like some people just tagged from their memory whole areas over time, while there are actually 30 zones etc.

Street complete sometimes show up a small section of a street, which has no tag yet. I answer it with 30 zone, and look at home at the data, just to find out the rest is wrongly tagged with `maxspeed=50` and nothing else.

**Proposed Solution**
Can we extend the maxspeed quest to show up (with the tagged `maxspeed` value in the quest text), if there's no maxspeed-zone/type (sign or rural/urban) info on the street?

I feel like the maxspeed definition isn't complete without the additional info if it's a zone, a general rule or a sign.

**Comment by westnordost** [comment]
Definitely, yes and no: Yes, the maxspeed value can be very old. But no, it is not only old if the maxspeed-zone/type is missing.
So, this is definitely a case where re-checking every few years makes sense, see the grant proposal.

**Comment by RubenKelevra** [comment]
@westnordost will the re-checking include adding the "maxspeed-zone/type (sign or rural/urban)" information?

If so it would be cool if max speeds could be immediately marked for re-checking, if those infos are missing. :)

**Comment by westnordost** [comment]
1. Yes, 2. Hmm, maybe
