### ISSUE TITLE
Act on Accessibility Report (produced as part of NGI 0)

### ISSUE THREAD

**Issue by westnordost** [westnordost/StreetComplete#1872]
Here is the report: [Report_NGI_StreetComplete.pdf](https://github.com/westnordost/StreetComplete/files/4707633/Report_NGI_StreetComplete.pdf)

Thank you, Yulia Valencia from https://accessibility.nl for the report and Mateusz for forwarding it to me. I have carefully read the report and determined the following action items:

~**Enable users who are blind to use this app:**~
You need vision to contribute with this app at all. So the below are not applicable.
- [x] ~1.3.1 (a) Connect checkboxes in "Enabled" column in quest selection screen programmatically to the header column titled "Enabled".~ will not fix, because this will only help text-to-speech systems for blind people
- [x] ~1.3.1 (b) Add "Quest completed" message when quest is completed~ will not fix, there is already audio feedback as well as an animation feedback
- [x] ~1.3.1 (c) Add a textual indication what he loading indicator is doing, f.e. "Loading..."~ Well, I'd say this is will not fix as well, because mostly aimed at blind users plus it should be pretty clear that it is a loading indicator for other users due to the rotating circle being widely known as such.
- [x] ~4.1.2 Add labels/state labels to buttons for text-to-speech~

**Enable users who have problems with their eyes (but are not blind):**
- [x] 1.4.3 Make text have more contrast, in particular, text buttons using the orange accent color. Maybe make the orange a little darker.
- [x] 1.4.4 (a) The "N" on the compass should always have the same size, independent of the system font size
- [x] 1.4.4 (b) Text on the map is not resized if the system font size is changed. The texts shown on the map should also get bigger if the system font size is bigger.
- [x] related: #1769

**Enable users who cannot use the touch screen to use this app:**
Hmm, TalkBack navigation is likely a bigger topic. There is probably more to do than what is listed in the quick accessibility report. So, it is not will-not-fix but I will probably not do this. Help is welcome, though.
- [ ] 2.1.1 TalkBack navigation for selecting the quests on the map
- [x] ~2.1.2~ this point is obsolete, report was based on old version of app
- [x] ~2.5.1 There should be buttons to control the map gestures like rotate and tilt~ Tilting and rotating the map are not vital features for using this app properly, so there is little reason to clutter the UI for such unimportant functionality

**Miscellaneous:**
- [x] 3.3.2 Use text hints like "type here" or similar for large input texts fields like for the "Create note" dialog. The text field is only indicated by one horizontal line, some people might have difficulties to realize that one can type there. (This is not a will not fix, but I think it is rather unimportant because whoever has an Android smartphone is used to seeing text fields that way. On the other hand, might consult the material design guidelines about if multiline textfields should maybe look different than the single-line ones)

**Comment by matkoniecz** [comment]
>  1.4.3 Make text have more contrast, in particular, text buttons using the orange accent color. Maybe make the orange a little darker.

I was looking into it (I hoped for a quick one-line PR) and just making it darker reduces contrast for the night style, below the recommended threshold (also done with the quite old app version but it seems to not be changed).

**Comment by matkoniecz** [comment]
> Text on the map is not resized if the system font size is changed. The texts shown on the map should also get bigger if the system font size is bigger.

What about making text bigger as one zooms in? It also would remove (very minor) problem of labels looking tiny and silly on heavy zoom and help users not changing system settings.

**Comment by westnordost** [comment]
Don't know, you could try it out if it feels weird. As far as I know, this behavior would be pretty unusual.

**Comment by matkoniecz** [comment]
> As far as I know, this behavior would be pretty unusual.

MAPS.ME, Google Maps, mapy.cz are doing this (sometimes it is hard to catch, but it is noticeable by slowly zooming in and noting that some labels got larger). A bit confused by labels jumping around due to changing collisions.

It seems that OSMAND is not doing this.

**Comment by westnordost** [comment]
solved 3.3.2

The talk-back navigation is something I will definitely not do, because I think it is not worth the effort. However, PRs for this are welcome.
