### ISSUE TITLE
Pre-fetch map and quest data 

### ISSUE THREAD

**Issue by frlan** [westnordost/StreetComplete#1873]
When going for a hike/bicycle tour it would be nice to get a bigger area prefetched with quests and map data in prior to save mobile data or to make usage of StreetComplete inside areas with no/bad mobile connectivity. 

**Proposed Solution**

Maybe increasing the local map cache and adding a feature like "getting map data of this area" could help a lot.

**Comment by westnordost** [comment]
Quests and map data are handled completely disparate. For the former, you can pre-download quests for the current view by selecting the "Scan for quests here" in the menu.
For the map, there is no way to pre-download an area beforehand other than the "hack" of looking at the area you go beforehand extensively (the map data is cached, there is an option about the cache size in the options). But to introduce a full offline-mode, there is already another ticket.

**Comment by frlan** [comment]
Actually I'm doing this right now. ;)
I guess we can close it in prior of the already open one (that I somehow did not see while short checking)

**Comment by westnordost** [comment]
#122

**Comment by smichel17** [comment]
Once the duplicate issue is found, I'd suggest leaving a comment in that issue with the keywords you searched for, so others (and you) can find it in the future
