### ISSUE TITLE
Don't ask for tactile pavings for bicycle (only) crossings

### ISSUE THREAD

**Issue by Helium314** [westnordost/StreetComplete#1875]
I get the tactile pavings quest for many bicycle crossings. Since the text implies that it is a pedestrian crossing, the quest is not applicable.

Example: https://www.openstreetmap.org/way/188390023
This is tagged as cycleway, without foot=yes. The footpath is separate next to it.

Is it some default that assumes foot access if the tag is not present?

**Comment by westnordost** [comment]
If it is bicycle only, it should be foot=no. Otherwise, how should StreetComplete know that it is not a pedestrian crossing?

**Comment by westnordost** [comment]
See also https://github.com/westnordost/StreetComplete/pull/1868

**Comment by matkoniecz** [comment]
`highway=cycleway` in many (most?) locations allows pedestrians, though they must give way to cyclists.

If someone maps footway and cycleway as a separate lines separate from the road it is then necessary to apply `bicycle=no` `foot=no` in many paces that would be not necessary with mapping them as tag on road or as a single `highway=path foot=designated bicycle=designated segregated=yes`.

I am pretty sure that https://www.openstreetmap.org/node/299019994#map=19/48.25199/16.42749 and https://www.openstreetmap.org/way/188390023 has `foot=no` missing.

Not sure is it happening so often that special "it is cyclist only crossing" shoud be added in "can't say" menu.

**Comment by Helium314** [comment]
In Vienna I encounter this problem quite often...

So if there is no foot=no, then foot access is assumed? Then maybe the app could instead ask whether foot access is allowed on the cycle path, at least if there is a parallel foot path nearby.

**Comment by westnordost** [comment]
> at least if there is a parallel foot path nearby.

For a human, this is easy to determine, for software, not that much, because it is fuzzy.

**Comment by westnordost** [comment]
Maybe the tactile paving quest should not be asked at all for `highway=cycleway` unless `foot=designated` or `yes` is tagged.

Would someone go through this list https://wiki.openstreetmap.org/wiki/OSM_tags_for_routing/Access_restrictions and list here for which countries `highway=cycleway` does **not** default to `foot=no`?

**Comment by Helium314** [comment]
This would be Austrialia, Belgium, Denmark, Finland, Iceland, Netherlands, Norway, Oman, Phillipines, Poland, Romania, Russia, Slovakia, Switzerland, Turkey, UK, USA

**Comment by Helium314** [comment]
I think this issue also applies for the sound signal quest...

**Comment by westnordost** [comment]
Thanks! I skimmed through the table another time and saw that for many of those countries, there is a remark like "only if there is no extra path for pedestrians. Most rural cycleways are like that" etc.

In cases like these, I'd expect that the cycleway is tagged explicitly with `foot=yes` because software surely doesn't just know if a cycleway is rural or not. Software does not have common sense.

So I think to be on the safe side, rather not ask for `highway=cycleway` after all at all for now. Maybe later, if there is feedback from communities in certain countries that they *never* put `foot=yes` on a cycleway because that is a given, we can soften it for these countries.

**Comment by westnordost** [comment]
Oh wait, I forgot this is about the node, not the way. So the query is currently

`nodes with highway = crossing and !tactile_paving and foot != no`

`highway=cycleway` does not even appear there. Not sure if it is possible at all to do filtering like that.

**Comment by Helium314** [comment]
Can the "part of" I see in https://www.openstreetmap.org/node/4328102858 be used there?
So e.g. it would be excluded if it is part of a cycleway without foot access and no foot path.

Or maybe as @matkoniecz suggests, just have an answer "this is a bicycle-only crossing" which adds foot=no to the crossing.

**Comment by matkoniecz** [comment]
> Not sure if it is possible at all to do filtering like that.

It is possible, see level crossing quest exclusions - though it reduces performance. See https://github.com/westnordost/StreetComplete/pull/1366/files#diff-0b083c0b338d41c649b9a8336e916026R31 https://github.com/westnordost/StreetComplete/blob/master/app/src/main/java/de/westnordost/streetcomplete/quests/railway_crossing/AddRailwayCrossingBarrier.kt#L32

**Comment by westnordost** [comment]
Does this make sense to you?

```
        way[highway = cycleway][foot !~ '^(yes|designated)$']; node(w) -> .exclusive_cycleway_nodes;
        way[highway][access ~ '^(private|no)${'$'}']; node(w) -> .private_road_nodes;

        node[highway = crossing][!tactile_paving][foot != no] -> .crossings;
        
        ((crossings; - .private_road_nodes; ); - .exclusive_cycleway_nodes;);
```

**Comment by westnordost** [comment]
Also, thanks @matkoniecz for the hint!

**Comment by matkoniecz** [comment]
`((crossings` -> `((.crossings`

**Comment by matkoniecz** [comment]
And with such bonus filtering applied here, it may make sense to use it also on crossing type quest and expand #1868 to more resource intensive but covering also crossings without explicit `foot=no`.

**Comment by westnordost** [comment]
Why, the crossing type is also relevant for cycle-only crossings

**Comment by westnordost** [comment]
Actually, I didn't think when I merged your PR. Why exactly exclude foot=no crossings from determining what crossing type it is?

**Comment by matkoniecz** [comment]
> Actually, I didn't think when I merged your PR. Why exactly exclude foot=no crossings from determining what crossing type it is?

Images are pedestrian focused what is confusing for mappers. Latest example in https://www.openstreetmap.org/note/2058179#map=19/50.06387/19.92272&layers=N what triggered this PR.

It gets worse with translations where "crossing for pedestrians" and "crossing for cyclists" is using different words, for example in Polish it would be respectively "przejście" and "przejazd".

**Comment by westnordost** [comment]
Hm, okay

**Comment by Helium314** [comment]
On the bicylce-only crossing https://www.openstreetmap.org/node/289485959 I got quests for sound signals and button operated (which I only realized is pedestrian only once I saw the changeset comment...).
The cycle path has `foot=no`, so those quests should not appear... or were the exclusions discussed above done only added for the tactile paving quest?
