### ISSUE TITLE
Secondary Quests only pop-up after manual upload

### ISSUE THREAD

**Issue by RubenKelevra** [westnordost/StreetComplete#1876]
I mapped some house details today with SC, and notices, that after the building type was answered, the usual "how much levels does this building have?" quest doesn't pop up.

After switching to manual sync and pressing the upload-button, the next quests appear.

So something is preventing the next quests to be shown on an object until the last quest is synched.

**Versions affected**
20.0

**Comment by matkoniecz** [comment]
https://github.com/westnordost/StreetComplete/issues/1352#issuecomment-471003445

**Comment by RubenKelevra** [comment]
@matkoniecz thanks, that makes sense!

In this case, maybe the auto-upload is (partly) broken? Never seen this behavior before... 🤔

I had a very good 4G cell reception, 10 quest changes are basically instantly uploaded when manually triggered.

**Comment by westnordost** [comment]
> In this case, maybe the auto-upload is (partly) broken? Never seen this behavior before... 🤔

Seen what behavior before?

**Comment by RubenKelevra** [comment]
> > In this case, maybe the auto-upload is (partly) broken? Never seen this behavior before... thinking
> 
> Seen what behavior before?

Well, I always have autoupload on and have often added details to buildings while on the go. I never had to wait for the secondary and third quest on a building to pop up. They would just take 1-2 seconds maximum to pop up.

Currently when I resolve the first quest, the secondary and third quest isn't shown, I can walk a block and map 10 buildings and there's still no secondary quest on the map for these.

When I switch to manually sync, I see 10 unsynchronized items in the queue. When I press upload they are uploaded in the matter of fractions of a second and all "missing" quests pop up.

Has the auto-sync behavior been changed in the last (say 2-3) versions?

**Comment by westnordost** [comment]
It has not been changed. A manually triggered upload behaves exactly the same as an automatically triggered upload.

Note that not all quests pop up automatically after upload. For what quests did the pop-up not work?

**Comment by RubenKelevra** [comment]
@westnordost Well, I think the issue is, that automatic updates are not triggered or triggered with a high delay. So when I switch to manual upload, I see still not-uploaded quests which I can manually upload and this will allow other quests to pop up.

In my case building type isn't uploaded immediately and therefore the building level quest isn't showing up.

When I switch from automatic uploads to manual uploads, I can see like 10 answered quests still in the queue and push them to get the building level quests pop up on the map.

**Comment by RubenKelevra** [comment]
Just tested it on 21-beta1 and the bug seems to be gone :)

If it's intermittent, I'll reopen this, but I guess it was just fixed by working on something else :)

**Comment by westnordost** [comment]
There is no difference between v20.1 and v21.0-beta1 in that regard
