### ISSUE TITLE
maxspeed:type is not widely used

### ISSUE THREAD

**Issue by Theodin** [westnordost/StreetComplete#1878]
From what I read from other issues, maxspeed is a fairly complicated topic, but I have to nevertheless add another issue :-)

If I tag a street as inside a german residential area, it gets marked as follows:
`maxspeed:type=DE:urban`
While this is almost correct according to the Wiki ( https://wiki.openstreetmap.org/wiki/Key:maxspeed ), I personally would tag the road as 
`maxspeed=50` and `source:maxspeed=DE:urban`

Taginfo tells me that StreetComplete is the only app using maxspeed:type
https://taginfo.openstreetmap.org/keys/maxspeed%3Atype#projects
so I wanted to open a discussion about how to improve the way StreetComplete is tagging maxspeed.

**Comment by westnordost** [comment]
This has been discussed several times. You are not bringing new arguments to the table.

**Comment by ENT8R** [comment]
See especially https://github.com/westnordost/StreetComplete/issues/492#issuecomment-326080750 where @westnordost left a detailed comment about why `maxspeed:type` will be used by StreetComplete. And I don't think that any of the mentioned arguments changed since then.

**Comment by westnordost** [comment]
#457 should also be mentioned.

**Comment by Theodin** [comment]
Thanks, I will read those. Must have not searched well enough to find those issues. Sorry for that.
