### ISSUE TITLE
Pointer pin changes resolution along left/right edge

### ISSUE THREAD

**Issue by Sequynth** [westnordost/StreetComplete#1879]
When rotating the view while the pointer pin is at the edge of the screen, the resolution of the pointer pin gradually gets very low, when the pointer pin approaches the center of the left screen edge. Also happens at the center of the right edge of the screen. Does not happen at top or bottom edge
![20200603_003647](https://user-images.githubusercontent.com/29228990/83577523-b0b8b980-a534-11ea-884c-c0cabbbd8859.gif)
**How to Reproduce**
Move view away from actual position to get pointer pin; rotate the screen 

**Versions affected**
SC 20.0
Android 6.0

**Comment by westnordost** [comment]
😆 That is a funny bug. Needless to say, I cannot reproduce it, neither with Android 5 nor Android 7. Haven't tried with an Android 6 though. Which manufacturer?

**Comment by matkoniecz** [comment]
Reproduced on Xiaomi with Android 6. What would be the first step to debug this?

I see nothing interesting in logs.
Maybe try to display this marker image while horizontal and try whatever static horizontal display is also mangled?

**Comment by westnordost** [comment]
The code is in `PointerPinView`. It is a custom view that draws itself in `onDraw`. Since ony the pin and not the icon itself gets blurred, the relevant code is [at line 97-103 ](https://github.com/westnordost/StreetComplete/blob/master/app/src/main/java/de/westnordost/streetcomplete/map/PointerPinView.kt#L97-L103):
```
        val size = min(width, height)
        val r = pinRotation

        pointerPin.setBounds(0,0, size, size)
        c.withRotation(r, width/2f, height/2f) {
            pointerPin.draw(c)
        }
```
Setting a breakpoint there might help, maybe check if `size` has a reasonable value. Maybe try if using `canvas.width` (instead of `width`) and height solves the problem.

**Comment by matkoniecz** [comment]
`canvas.width: 96 canvas.height: 96 width: 96 height: 96 size: 96` hold constant.

Things get weird with `r` around 450 and around 630.

> Maybe try if using canvas.width (instead of width) and height solves the problem.

Sadly, it has not worked.

**Comment by Sequynth** [comment]
> Which manufacturer?
LG G4

**Comment by westnordost** [comment]
Maybe Android 6 doesn't handle angles >= 360° well. Maybe you could try `% 360` the rotation.

**Comment by westnordost** [comment]
If this is in degrees and all and not radians

**Comment by westnordost** [comment]
Are you still trying it out, @matkoniecz ?

**Comment by matkoniecz** [comment]
> Maybe Android 6 doesn't handle angles >= 360° well. Maybe you could try % 360 the rotation.

Tried that (`val r = pinRotation % 360`), 270/90 is still problematic.

**Comment by westnordost** [comment]
Ok, interesting. Will you do a fix, or shall I?

**Comment by matkoniecz** [comment]
Feel free to fix! I am trying to finally finish one of my open PRs at this moment so I will be perfectly fine to be just a tester for this one.
