### ISSUE TITLE
Tie star count to OSM account

### ISSUE THREAD

**Issue by gappleto97** [westnordost/StreetComplete#188]
I just had to reinstall your app. It decided to crash on open constantly, so I had no other choice, but I lost >500 stars in doing so. If your goal is to gameify this process, it seems logical to associate thin data with an account, rather than an install.

**Comment by HolgerJeromin** [comment]
This would need an own server infrastructure. 
IMO osm.org provides not way to store custom data for an app.

**Comment by Natenom** [comment]
@westnordost Could you implement a button to restore old quest counter with a big warning "could take some minutes" instead of doing it automatically as it was on an old version?

**Comment by matkoniecz** [comment]
Or document where data is stored (though it may require full access to phone and be available only for people with rooted devices).

**Comment by westnordost** [comment]
@gappleto97 It is basically already implemented but I had to disable it after 0.5 because with the new way changes are uploaded now it has become too data and time intensive.

I will reintroduce the "syncing" of quests with OSM account when I introduce a leaderboard. Your stars are not lost, only not "synced" right now.

I'll close this issue because it will be fixed together with the introduction of a bigger upcoming feature.

**Comment by gappleto97** [comment]
Alright. I look forward to it. Any idea what release that'll be in?

**Comment by matkoniecz** [comment]
@gappleto97 I guess that it depends on free time of the author.

Note that giving number is not helpful as it is impossibble to guess how many bugfix releases will be needed.

**Comment by gappleto97** [comment]
I'm more than aware. I do this sort of stuff too, so I was pretty sure I'd be getting a guesstimate.

**Comment by westnordost** [comment]
It's big feature number 3 on my priority list of big features to implement. Number 1 is #35, number 2 is an offline reverse country geocoder (GPS position -> country+region you are in, necessary for localized quests).

Very rough guesstimate: in 3 months.

**Comment by HolgerJeromin** [comment]
Just for reference: I just found that osm.org can [host own data](https://wiki.openstreetmap.org/wiki/API_v0.6#Preferences_of_the_logged-in_user). 
This is probably known to westnordost but was new to me.

**Comment by matkoniecz** [comment]
I now opened #1485 - Synchronization of statistics (tie star count to OSM account) as the first step toward coding this feature.
