### ISSUE TITLE
Max weight quest: Select and tag traffic sign

### ISSUE THREAD

**Issue by westnordost** [westnordost/StreetComplete#1880]
It should be possible to select the type of max weight sign in the max weight quest because there are several alternatives which look similar to people who do not have a truck driver's license. [See documentation](https://wiki.openstreetmap.org/wiki/Key:maxweight#Lookalikes)  on similar signs.

It has also been suggested to then additionally tag the country-specific [`traffic_sign`](https://wiki.openstreetmap.org/wiki/Key:traffic_sign) when answering the max weight quest to increase the confidence that actually the correct sign has been tagged as there exists the suspicion that many `maxweight` values are actually wrong because the sign was actually a `maxweightrating` or `maxaxleload` (or even other) sign.

This necessitates quite some research with which I could use some help. No coding skills required, just diligent research. Most importantly:
- list the countries in which the different signs exist at all: `maxbogieweight`, `maxweightrating`, `maxaxleload`, `maxunladenweight` (and more?)
- post here in this ticket if you see that in a particular country, the sign visually very different from what it usually looks in other countries. (For example, US signs look very different, the German `maxweightrating` sign looks different from the rest, etc)

But then, if we want to tag the traffic sign numbers as well, also:
- list the traffic sign numbers for the `maxweight` sign for all countries
- list the traffic sign numbers for the `maxaxleload` sign for all countries
- list the traffic sign numbers for the `maxweightrating` sign for all countries
- list the traffic sign numbers for the `maxbogieweight` sign for all countries
- (etc, for other signs)

The sign reference numbers should be listed in this format, for example:
```
DE: 123 # [link to source of this info]
EE: 456 # [link to source of this info]
FR: 789 # [link to source of this info]
UA: unknown # (for when it is known that the traffic sign is known there, but the ref number is unknown) + [link to source of this info]
```
, each in YML files named like `maxweightSignRef.yml` etc.

The MVP however is first to determine which signs are known in which countries.

**Comment by westnordost** [comment]
![Screenshot_1600885180](https://user-images.githubusercontent.com/4661658/94053645-e252da80-fdda-11ea-94a1-abd9995413ac.png)
![Screenshot_1600885505](https://user-images.githubusercontent.com/4661658/94053664-e848bb80-fdda-11ea-845b-3c85c3534c54.png)
![Screenshot_1600885196](https://user-images.githubusercontent.com/4661658/94053685-ee3e9c80-fdda-11ea-97e8-8299fba7a5cc.png)
![Screenshot_1600885287](https://user-images.githubusercontent.com/4661658/94053693-f26aba00-fdda-11ea-9dd8-dcbe532b8e46.png)
![Screenshot_1600885314](https://user-images.githubusercontent.com/4661658/94053708-f7c80480-fdda-11ea-9cfa-132c325750e4.png)

**Comment by westnordost** [comment]
So, I implemented it without tagging the ref of the actual sign and also did not reserach which sign exists actually in which country. It's just 4 to choose from anyway, so that's fine.

**Comment by westnordost** [comment]
I also activated the quest for US, CA and AU. Even if their signs usually look more complex ...

<img src="https://upload.wikimedia.org/wikipedia/commons/0/0a/Delaware_R12-5-DE.svg"/>

... I think it is worth to let the users make a photo of it instead.

**Comment by kmpoppe** [comment]
> So, I implemented it without tagging the ref of the actual sign and also did not reserach which sign exists actually in which country. It's just 4 to choose from anyway, so that's fine.

Just to reiterate: You've now build it without any country-specific signs, right? 

The **english** OSM Wiki actually lists quite some variants with the links to the images containing some numbers which could be a start reference for looking up the numbering scheme in the country. 

Is this like a long-running Issue so that we could come up with an initial list and then add more signs and numbers later or do you want this to be a one-off thing?

**Comment by westnordost** [comment]
Better a one-off thing because it would make it easily possible to for example let users resurvey every maxweight that does not have a sign ref (tagged before day X)
Though I am beginning to doubt if adding the sign ref would be that helpful - what is this for again?

**Comment by kmpoppe** [comment]
Then, I'd go for let's try to find as many signs as possible for different countries (tedious, but possible with data from the wiki and some sophox/PHP magic).
What's it for? I think your initial idea was to display the sign to the user so that they get the right limit. Which I find totally sufficient as a reason. The `traffic_sign` tag exists for a reason and almost 800k uses seem to make it a good idea to tag it - even more so because you literally have the information the user choose, so why waste it. Other people or data consumers might need it.
