### ISSUE TITLE
Suggestion of new quest: How is this telephone protected from rain?

### ISSUE THREAD

**Issue by Lukas458** [westnordost/StreetComplete#1881]
In my country (Germany) there are still many public telephones, and some are still covered by a full-covered telephone box (covered=booth), some are covered by a roof (covered=yes) and some others aren't covered (covered=no).

While some telephones get removed in these days in Europe and elsewhere, many developing countries still have a dense network of those telephones.

### General
Affected tag(s) to be modified/added: It would be the key covered=*, see https://wiki.openstreetmap.org/wiki/Key:covered and https://wiki.openstreetmap.org/wiki/Tag:amenity%3Dtelephone for this.
Question asked: **How is this telephone protected from rain?** (the same as according to amenity=bicycle_parking)

**Phones which have an indoor=yes tag and maybe also those which lay "in" a building (can SC recognize that?) would have to be excluded, because when a phone is indoor, no extra cover is needed.**

Concerning the checklist for good quests, all requirements are satisfied in my eyes. Easy to verify, many telephones are out there, three different answers to give and allt three do exist often. But someone might ask what's the useful information carried by adding this tag. I think it's just to show whether some kind of service (protecting from rain while using the phone) is provided or not, similar to adding shelter=yes/no to bus stops or adding covered=yes/no to bicycle parkings.

**Comment by matkoniecz** [comment]
While I see no big value in collecting this info it has a nice side effect of verifying whatever mapped phones are still existing.

**Comment by matkoniecz** [comment]
> maybe also those which lay "in" a building (can SC recognize that?) would have to be excluded

Without this part it is very easy to implement. Is it necessary? Maybe exclude ones `indoor=yes` and have "covered" / "not covered" / "in building" answers?

After all telephone may be in inside building outline but outside (for example, on the roof level).

**Comment by Lukas458** [comment]
> Without this part it is very easy to implement. Is it necessary? Maybe exclude ones indoor=yes and have "covered" / "not covered" / "in building" answers?

Oh yes, I would like that. Hmm but now, I read a discussion on the tagging mailing list, that covered=booth is not liked by some mappers because is does not fit into the covered=yes/no scheme. Hmm I think I would have to clear that first...

**Comment by westnordost** [comment]
It's documented and well used. There are quite some other values for `covered` as well. That it doesn't fit into a yes/no scheme is not an argument in itself.

**Comment by Lukas458** [comment]
@westnordost I think you are right, yes. I think I'm going to make a proposal of covered=roof / phone_hood / open_phone_box / closed_phone_box to refine tagging of how a telephone is covered. covered=roof is also in use already.

**Comment by westnordost** [comment]
`covered=open_phone_box sounds` weird because pretty specific to phones. What's wrong with roof / booth?

**Comment by Lukas458** [comment]
covered=roof would be very okay, it's this: https://www.teltarif.de/img/i/i_telefonzelle-2l1.jpg

But when using covered=booth, we have two types of it. The closed ones are these I think: https://de.wikipedia.org/wiki/Telefonzelle#/media/Datei:B%C3%BCsingen_am_Hochrhein_Swiss_and_German_Telephone_Booth.jpg

But we have also the open ones: https://en.wikipedia.org/wiki/Telephone_booth#/media/File:Telephone_box_with_internet_access.JPG

at the moment there is no real way to distinguish between them. Both are booths because of the sides going to the floor, a phone hood is another thing again: https://commons.wikimedia.org/wiki/File:Kreta_-_Telefonhaube.jpg

Nevertheless, I could live with covered=booth, but I find it a bit imprecise and some mappers use booth=yes/no because they see no added value with covered=booth then, and we have some other issues, so I think I will treat them in my proposal. Of course its not said this would be "the solution of all" but maybe a try worth, in my eyes definetely at least covered=* shouldn't be so a strcit yes/no value as some see it.

**Comment by RubenKelevra** [comment]
At least in Germany we have 5 types:
* Inside of buildings
* just a pole/attached to a wall
* a pole with a roof/attached to a wall with a roof
* a pole with a roof and side walls (1/2 of the height down) (or at a wall)
* full small "buildings" with a door with either White pink colors or old yellow ones

Also, many of the old "building" types are repainted and now used as public bookshelves. It would be great if that's one of the options.

![IMG_7425](https://user-images.githubusercontent.com/614929/83982597-2dc6a300-a928-11ea-81c3-0fa9ebf101cb.JPG)

_Note: The type attached to a building (not on a pole) but outside are quite rare._

**Comment by Lukas458** [comment]
Thank you. I think some of them I looked at in the proposal I mentioned:

> Inside of buildings

no cover needed. amenity=telephone + indoor=yes
> just a pole/attached to a wall

I would say this is then amenity=telephone + support=wall_mounted + covered=no + maybe location=outdoor or indoor=no.

>a pole with a roof/attached to a wall with a roof

In my proposal I proposed covered=roof for this. support=wall_mounted and others do exist but have nothing to do with the cover.


> a pole with a roof and side walls (1/2 of the height down) (or at a wall)

Hmm, I proposed also using covered=roof for this in my proposal, but don't really know how to map the side walls really. "phone_hood" would not fit it.

>full small "buildings" with a door with either White pink colors or old yellow ones

Yes, actually covered=booth and booth=* are used for this, but I propose to use covered=closed_phone_box.

phone_box:type can then be used to specify the exact type of phone box (you mentioned there are some different), and this can also be used for public bookcases, **where we have the tag public_bookcase:tpye=phone_box already.**

**For going on I think we should use the proposal's discussion page, shouldn't we?**

**Comment by westnordost** [comment]
> For going on I think we should use the proposal's discussion page, shouldn't we?

Yes, please do

**Comment by westnordost** [comment]
Well, let's not overthink this. Let's have booth, covered (just a roof) and no.

However, this has lower priority as the "is X still there" quest, let's see how many telephones are actually still remaining after a lot of phones get re-checked.

**Comment by Lukas458** [comment]
> With the "X still there?" quest implemented, what use case remains for this information anyway though?

Yeah, I think this quest propose is not really important then, so no big relevance. Is "Is X still there?" already implemented? Then we can close this.

**Comment by westnordost** [comment]
No, it's not. This is #2074 , but this will be implemented soon. Then I'll close this one.
