### ISSUE TITLE
Extend maxheight quest to bridges

### ISSUE THREAD

**Issue by RubenKelevra** [westnordost/StreetComplete#1882]
**Use case**
Currently, the max-height quest only searches for ways which are tagged with `tunnel=*` or `covered=yes`.

But there are a lot of bridges which are just above highways limiting vehicles passing below them to a certain height.

**Proposed Solution**
Overpass can search for ways that are [adjacent](https://wiki.openstreetmap.org/wiki/Overpass_API/Overpass_API_by_Example#.C2.AB_n_.C2.BB_adjacent_ways). This will return all ways which are directly connected or intersecting with the specified way.

We need to do some processing with the ways afterward, to remove all ways which have a direct connection to the bridge-way.

This would leave us with a list of ways that are either below or above the bridge. Intersecting with it. So it makes sense to filter out everything "above" the bridge, filtering by the layer tag.

---

I don't know if we do something similar already somewhere, depending on this it would be more or less work to do.

**Comment by westnordost** [comment]
Okay, that's interesting that this is possible.

Another issue is however that those roads that go beneath bridges are not always cut up nicely so that there is a section just below the bridge. Imagine a situation where there is a long road segment of 500m with several intersections that goes below a bridge at one point.
We wouldn't want to confront a user with answering this.

Can you come up with any solutions for this?

**Comment by matkoniecz** [comment]
> Can you come up with any solutions for this?

Silently autosplit way, so user gets shown only segment under a single bridge? Probably overly complicated.

Additional filtering skipping longer ways (AFAIK can be done directly in a query), more strict than 500m limit?

**Comment by westnordost** [comment]
To limit the max length of road sections returned to a few meters around the supposed width of the bridge would be an almost surefire way but there is still no guarantee that that road does not contain any intersections.

It would be best to exclude all roads segments that have intersections but I don't know if this can be done with Overpass.

Since StreetComplete can not cut ways, it would be theoretically possible to ask the user to cut the road if it is "too long" but difficult to make it easy to understand for the user what he has to do. And also, he ought cut it exactly at where the bridge starts and ends, that's difficult to determine without looking at the satellite picture.

**Comment by matkoniecz** [comment]
> he ought cut it exactly at where the bridge starts and ends

Cutting it where height limit start to apply should be fine, doing it for example where height limit is starting to apply (last intersection, including driveway intersections) also would be correct. I think that splitting way at any location between last place to leave road and bridge is OK.

I never bothered with splitting exactly under bridge during manual mapping.

**Comment by RubenKelevra** [comment]
We can calculate the width of the bridge if there's already `lanes=*` and `sidewalk=*` tagged.

So the process would be:

* Find everything around the way with the bridge tag.
* Remove every way that shares nodes with the bridge way.
* Calculate the width: by default 2 lanes and sidewalks if there are no other tags
* Cut the way silently to the length calculated plus say 2 meters on both sides.
* Request the way *below* the bridge, the same way as the bridge way.
* Check if the nodes which forms the way below the bridge has any connections to other ways. If not:
* Upload the change

**Comment by westnordost** [comment]
Well, that's much to complex.

What would help here was help for finding 
- Ovwepass syntax for finding ways that are below bridges 
- And of these, find those that have intersections with other roads or ways

**Comment by RubenKelevra** [comment]
> Well, that's much to complex.

Well, I don't know if we can cut corners here 🤔

We need to cut the ways before and after they are under the bridge, to make sure we add the height restriction just for one bridge - if there are two close together and the way is running below both of them.

I get the idea of searching for intersections, but this wouldn't avoid all corner cases I think as explained above.


> * Ovwepass syntax for finding ways that are below bridges
> * And of these, find those that have intersections with other roads or ways

I can look into that, if that helps. :)

**Comment by RubenKelevra** [comment]
by @westnordost 

> Well, that's much to complex.
> 
> What would help here was help for finding
> 
> * Ovwepass syntax for finding ways that are below bridges
> * And of these, find those that have intersections with other roads or ways

Here's the query to only find the ways below bridges, while filtering out all ways which are connected to the bridge-ways.

```
{{roads=motorway|motorway_link|trunk|trunk_link|primary|primary_link|secondary|secondary_link|tertiary|tertiary_link|unclassified|residential|living_street|track|road|service|path|cycleway|footpath}}
[timeout:120];
way
  ["highway"~"{{roads}}"]
  ["bridge"="yes"]
  ["layer"="1"]
  ({{bbox}});
foreach->.bridges(
  way
    (around.bridges:0)
    ["highway"~"{{roads}}"]
    [layer !~ '^(-8|-7|-6|-5|-4|-3|-2|-1|1|2|3|4|5|6|7|8)$']
    ->.intersections;
  node(w.bridges);
  way(bn)
    ["highway"~"{{roads}}"]
    [layer !~ '^(-8|-7|-6|-5|-4|-3|-2|-1|1|2|3|4|5|6|7|8)$']
    ["layer"!="1"]
    ->.crossings;
  (
    way.intersections;
      -
    way.crossings;
  )->.errors;
  (.errors;);/*hmmm?*/
  (
    ._;
    way.bridges(around:0)["layer"!="1"];
  );
  out body;
  node(w);
  out skel;
);
```

Only issue is, that the ways might be pretty long - no one cuts them down to only the part below the bridge:

![Screenshot_20201026_153931-1](https://user-images.githubusercontent.com/614929/97186470-9ad8b900-17a1-11eb-83fe-791f0e2b506d.png)

So we might remove access to a full road, while there's only a bridge at the last bit of the road.

I think we could ask the users to cut the way if necessary with the SC tool? :)

**Comment by smichel17** [comment]
If I am walking under the bridge with my gps on, it would not be too hard to figure out where to split it, if I were asked. Although, I'm not sure how accurate the gps usually is. I wonder if the best way might be to automatically guess where the way should be split, and then ask the user to confirm and adjust if needed.

The information is definitely [useful](http://11foot8.com/), though.

**Comment by RubenKelevra** [comment]
> If I am walking under the bridge with my gps on, it would not be too hard to figure out where to split it, if I were asked. Although, I'm not sure how accurate the gps usually is. I wonder if the best way might be to automatically guess where the way should be split, and then ask the user to confirm and adjust if needed.
> 
> The information is definitely [useful](http://11foot8.com/), though.

Well, the map view alone should actually be enough to cut the way down.

... something something please make sure to cut the way displayed to the section where the height limit applies before answering this quest something something...

(It only applies to this section) (I will cut it down) 

Or something like this should be enough - I think :)
