### ISSUE TITLE
"Take Mapillary photo" in the quests

### ISSUE THREAD

**Issue by Janjko** [westnordost/StreetComplete#1883]
### General
Affected tag(s) to be modified/added: [mapillary=*](https://wiki.openstreetmap.org/wiki/Key:mapillary)
Question asked: **Take a photo of this xxx**

### Checklist
Checklist for quest suggestions (see guidelines):
- [+ ] 🚧 To be added tag is established and has a useful purpose
- [+ ] 🤔 Any answer the user can give must have an equivalent tagging (Quest should not reappear to other users when solved by one)
- [ +] 🐿️ Easily answerable by everyone from the outside but a survey is necessary 
- [ +] 💤 Not an overwhelming percentage of elements have the same answer (No spam)
- [ +] 🕓 Applies to a reasonable number of elements (Worth the effort)

### Ideas for implementation

**Element selection:** 

Just include anything that can be photographed whole at once. There is no sense in photographing streets (hard to photo a whole street), lamps (they are all the same), parks (often too big), and so on.
These are some suggestions:
```
(
  way["building"]["mapillary"!~".*"]({{bbox}});
  relation["building"]["mapillary"!~".*"]({{bbox}});
  node["entrance"]["mapillary"!~".*"]({{bbox}});
  node["tourism"="artwork"]["mapillary"!~".*"]({{bbox}});
  way["tourism"="artwork"]["mapillary"!~".*"]({{bbox}});
  relation["tourism"="artwork"]["mapillary"!~".*"]({{bbox}});
  node["amenity"="fountain"]["mapillary"!~".*"]({{bbox}});
  way["amenity"="fountain"]["mapillary"!~".*"]({{bbox}});
  relation["amenity"="fountain"]["mapillary"!~".*"]({{bbox}});
  node["amenity"="drinking_water"]["mapillary"!~".*"]({{bbox}});
  way["amenity"="drinking_water"]["mapillary"!~".*"]({{bbox}});
  relation["amenity"="drinking_water"]["mapillary"!~".*"]({{bbox}});
  node["leisure"="playground"]["mapillary"!~".*"]({{bbox}});
  way["leisure"="playground"]["mapillary"!~".*"]({{bbox}});
  relation["leisure"="playground"]["mapillary"!~".*"]({{bbox}});
  way["man_made"="bridge"]["mapillary"!~".*"]({{bbox}});
  relation["man_made"="bridge"]["mapillary"!~".*"]({{bbox}});
  node["amenity"="bicycle_parking"]["mapillary"!~".*"]({{bbox}});
  way["amenity"="bicycle_parking"]["mapillary"!~".*"]({{bbox}});
  relation["amenity"="bicycle_parking"]["mapillary"!~".*"]({{bbox}});
  node["shop"]["mapillary"!~".*"]({{bbox}});
  way["shop"]["mapillary"!~".*"]({{bbox}});
  relation["shop"]["mapillary"!~".*"]({{bbox}});
  node["highway"="bus_stop"]["mapillary"!~".*"]({{bbox}});
  way["highway"="bus_stop"]["mapillary"!~".*"]({{bbox}});
  relation["highway"="bus_stop"]["mapillary"!~".*"]({{bbox}});
);
out meta;
```

After taking a photo, it should be uploaded to Mapillary, and then comes the unknown part. I don't know if Mapillary gives you the image ID right away. If it doesn't then this becomes problematic, because StreetComplete would have to somehow find the ID of the same exact photo later. But I think having photos of a lot of features would be very valuable, so it would be worth the effort. Maybe there's a way to tag the images being uploaded, and then later find them by that tag.

**Proposed GUI:**
- Text bubble with: **Take a photo of this building | artwork | fountain...**

- Classic camera interface, with a tick to approve the photo, and an x to cancel.

- *Magic* 😄

**Comment by westnordost** [comment]
For every building, shop, etc? Are you insane? 😆 
Anyway, that would be far too much.

A similar thing has already been proposed by an employee of Mapillary, discussed there and withdrawn.

**Comment by Janjko** [comment]
> For every building, shop, etc? Are you insane? 😆
> Anyway, that would be far too much.

Too much for who? Mapillary or OSM? Wouldn't a picture of every feature be useful?

**Comment by westnordost** [comment]
Yes, I strongly doubt that a picture of every building would be useful. I can't speak for Mapillary, but I know that at least this is not was mapillary was created for. To attach a mapillary-tag to every building would also be something that would meet with considerable resentment in the community - if even such a proprietary tag is even accepted.

Also and most importantly, it is too much for the users of the app. If they want to contribute to Mapillary, they should use the Mapillary app.
