### ISSUE TITLE
Max Weight Quest gives wrong proof question regarding height

### ISSUE THREAD

**Issue by CarstenG** [westnordost/StreetComplete#1884]
Today I answered a quest about the maximum allowable weight of a bridge. After typing "30" for the 30 t limit I got a proof question like "This height looks unusual. Are you sure, that this is correct?" (retranslation from German). The quest itself was done right in the osm database, see changeset [86201014](https://www.openstreetmap.org/changeset/86201014), but only the proof question should be fixed.

**How to Reproduce**
Answer a maxweight quest with 30.
Click ok.
See the wrong proof question and cancel it or commit it.

**Versions affected**
StreetComplete Version 20.0, Android 7.0
![Screenshot_20200604-191828](https://user-images.githubusercontent.com/7836755/83798451-9271cb80-a6a4-11ea-83d5-91cd60e09491.jpg)

**Comment by westnordost** [comment]
Thanks for the report! This is a copy&paste error in the German translation. I changed the translation to
"Dieses Gewicht sieht ungewöhnlich aus. Bist du sicher, dass es korrekt ist?"

The confirmation dialog is shown if the input is above 25t or below 2t.
