### ISSUE TITLE
Problem in the "By country" menu.

### ISSUE THREAD

**Issue by miggazElquez** [westnordost/StreetComplete#1886]
When I am in the new menu where you can see the quest by country, I see roughly half of my quest in France, and the other quest are in a gray ball. The application crash if I click on the ball.
![signal-attachment-2020-06-05-185148](https://user-images.githubusercontent.com/50714529/83903253-1471fb00-a75e-11ea-9b95-2ed862c325d9.jpeg)

**How to Reproduce**

**Versions affected**

StreetComplete v20.0
Android 9

**Comment by westnordost** [comment]
Yes, this will have been fixed in the next release.
