### ISSUE TITLE
New quest suggestion: meal voucher

### ISSUE THREAD

**Issue by raspbeguy** [westnordost/StreetComplete#1888]
Hello,

I think it would be great to ask if a restaurant accepts meal vouchers (aka. Tickets restaurant in France).

In osm: [`payment:meal_voucher`](https://wiki.openstreetmap.org/wiki/Key:payment)

**Comment by westnordost** [comment]
Please read the https://github.com/westnordost/StreetComplete/wiki/Adding-new-Quests-to-StreetComplete before suggesting a new quest.

**Comment by raspbeguy** [comment]
Ok so about the nodes where the quests would apply : `amenity=restaurant`
The form :
Does this place accepts meal vouchers? Yes | No

**Comment by westnordost** [comment]
> 🚧 Established tags only: No new or unestablished tags should be introduced through StreetComplete. Establishing tags must remain a community process and not be dictated by software implementation.

Not really established

> 💤 No spam: It must be possible to determine whether the quest should reasonably be asked. A quest which is to be answered in 99% of the time with the same answer is not a good quest, don't bore the users. I.e. asking for any road if it is a one-way road, is silly, because the vast majority of all roads will not be one-ways.

\> 99.9% of restaurants do not accept meal vouchers.

**Comment by raspbeguy** [comment]
In the pages I linked in my first post, the tag exists, so I don't see why you say that.

> 99.9% of restaurants do not accept meal vouchers.

In France most of restaurants accepts them. So we could then limit this quest to France. I this that Luxembourg at least has "tickets restaurants" accepted in most restaurants.

**Comment by westnordost** [comment]
Ok, I don't know the situation in France. Can you link an article or something? Is it something that is visible from the outside, if yes, how does it look?

> In the pages I linked in my first post, the tag exists, so I don't see why you say that.

Because it has 212 uses worldwide.
https://taginfo.openstreetmap.org/keys/payment%3Ameal_voucher

Now if the app would start asking for every restaurant, even if limited to France, the tag would be established through StreetComplete.

**Comment by raspbeguy** [comment]
I don't have an article that states specifically that a lot of restaurants accepts tickets restaurants, but here is a list of symbols that can been displayed on the outside of the restaurant: https://www.aide-sociale.fr/tickets-restaurant/amp/#Quels_sont_les_endroits_o%C3%B9_vous_pouvez_utiliser_un_ticket_restaurant

**Comment by raspbeguy** [comment]
Even if the tag is not much used, it is official at least, and should be used in my opinion.

**Comment by westnordost** [comment]
I read the linked article. It claims that 180000 restaurants in France accept payment by meal voucher. It also looks like it is a nationally used system. Still, in light of the tag being used very little so far, before I mark this as OK to be implemented for France, please bring up this topic in the French community first and ask if they are ok with potentially every restaurant in France being tagged with this additional information.

**Comment by HolgerJeromin** [comment]
Germany has this too:
https://www.edenred.de/ticket-restaurant/
I know one bank (without a canteen) which gives these coupons to their employes. Mcdonald's accepts them for example.

There is often a logo an the restaurant door.

**Comment by westnordost** [comment]
Hm, I am still closing this one because this tag is barely used so far. New tags should not be established by this app.

**Comment by matkoniecz** [comment]
Additionally, is there compatibility between different meal vouchers? For example Sodexo vs whatever Ticket Restaurant issues vs LV vouchers?

If there is no compatibility them using `payment:meal_voucher=yes` for all seems a bad idea.
