### ISSUE TITLE
Immediate crashes on 0.8

### ISSUE THREAD

**Issue by gappleto97** [westnordost/StreetComplete#189]
I think you've put out a new version since, but this is what's on F-Droid. I'm running LineageOS on my Nexus 6P. Your app consistently works for a few hours after each install, then starts crashing on open. Clearing cache, force stop, etc, does not fix this. Reinstall temporarily alleviates the issue.

Are there any log files I can dig up for you? It doesn't make it to the bug report screen.

**Comment by gappleto97** [comment]
Also, this is the cause for filing #188

**Comment by westnordost** [comment]
Clearing cache does not solve the problem? And Clear data?

**Comment by gappleto97** [comment]
I did not try clearing data. I can download 0.8 again to replicate the issue if you'd like. I'm running 0.7 for now.

**Comment by westnordost** [comment]
I am very eager to get to the bottom of this crash. Perhaps you could get 0.10 as soon as it is available and see if you get the crash there? If yes, either
* get the app from Google Play: Crashes of apps installed via the Play store are automatically recorded from outside of the app -> so I get the crash report even if you are unable to re-start the app
* or leave an app like SysLog running while trying to use the app. SysLog (and similar apps) show you the current system log. It should be possible to record the crash there

**Comment by gappleto97** [comment]
I can no longer replicate the bug. Don't know what happened at all, but the second reinstall seems to have fixed everything. I'll reopen this and post logs if it happens again.

**Comment by westnordost** [comment]
Hmm okay, let me know if it happens again
