### ISSUE TITLE
Requests about name shoult contain Operator

### ISSUE THREAD

**Issue by Mannshoch** [westnordost/StreetComplete#1890]
I recently began to answer also Questions about Names. Some Questions are about petrol station. So I answered their Name with the Gas Company name. I now detected that some petrol stations are named by the shop which operates the petrol station and some are named like the Operators name. 
It may helpful if the petrol station name request contain the already known operator name.
It's may helpful if the request ask kind of that:

```
This petrol stations Operator is {Operator} 
Does it have a Shop which is responsible for that petrol Station? (e.g. Possibility to pay in the shop)
YES / NO /Other
```
No = `StreetComplete set {Operator} as Name`
Other = `{Take a Note}`

YES
```
Please Enter the Shop name or chose one from the list of surrounded shops.

If you wish to add {Translated-name-for-Patrol-station} to the name set a Tick [ ]
```

**Comment by westnordost** [comment]
I don't really understand your suggestion. Why would the operator or existance of a shop at a petrol station change anything for the name of the petrol station?

**Comment by Mannshoch** [comment]
Petrol station do not have own name. But If you are searching on map you may search for {shop name} petrol station. Here in Switzerland e.g.: Coop Tankstelle. With the name tag you may able to search for the operator e.g: Socar or for Coop Tankstelle.
(You may need to search that way in OpenStreetMap, because on Sunday they are the only open shops)

If you think that is not what it meant to, you may remove the naming quest for petrol stations.

**Comment by westnordost** [comment]
I still don't understand the issue. Maybe write in German? Or post a link to an element?

**Comment by Mannshoch** [comment]
https://www.openstreetmap.org/search?query=coop tankstelle

**Comment by westnordost** [comment]
What?

**Comment by Mannshoch** [comment]
There you can see a list of petrol stations. So you could compare my description with the current situation. If you do not understand what I mean, please describe what you have understood and what you have not understood.

**Comment by westnordost** [comment]
Yes, I see a list of petrol stations. The petrol station part and the convenience store part are mapped separately. Ok why not. You say 

> Petrol station do not have own name.

But they do, in the link you posted: https://www.openstreetmap.org/node/1426129681

**Comment by matkoniecz** [comment]
Some people claim that `name=Coop Tankstelle` is incorrect and only `brand=Coop Tankstelle` should be tagged. Maybe that is the case here?

**Comment by Mannshoch** [comment]
Yes.  In my region you find a lot of these https://www.openstreetmap.org/node/578221549
In these case you fill your car but pay in the Migrolino shop. 
I'm not sure where the Operator of the cash point may should be placed.

**Comment by westnordost** [comment]
The quest is not asked for places that do have a `brand` tagged.

**Comment by westnordost** [comment]
See last comment.

**Comment by timothywashere** [comment]
Should it ask for a name when the petrol station contains an Operator?

One near me has neither name nor brand but does have operator=Texaco
I suspect most people seeing the  prompt "What is the name of this place (petrol station)?" would enter Texaco which I understand is wrong.

In fact, I'm not sure in the UK you ever really see the name of the Petrol station, which tends to be something like MFG Retail Boxhill. The signs always show a Brand/Operator. Only a few rural stations might have a name, like "Boxhill Garage"

**Comment by matkoniecz** [comment]
> which I understand is wrong.

As far as I am aware this is considered as OK (I used to be not sure and wanted to tag this in `brand`, not `name` but I have not convinced people.)
