### ISSUE TITLE
Do not ask for the building type for elements tagged with 'attraction:'?

### ISSUE THREAD

**Issue by mxxcon** [westnordost/StreetComplete#1891]
This seems like a situation similar to issue #1854 I reported a few days ago.
OSM feature https://www.openstreetmap.org/way/248474742

---|---
:--- | :---
attraction | swing_carousel
building | yes
name | Parachute Jump

StreetComplete is asking for the building type yet none of the available options are applicable.

**Comment by matkoniecz** [comment]
Select general building type "commercial", without selecting more specific entry?

**Comment by mxxcon** [comment]
Would that be an accurate selection considering it last operated in 1964 and is now a landmark structure? Also wouldn't making that selection override ID's template?

**Comment by matkoniecz** [comment]
> Would that be an accurate selection considering it last operated

It was constructed as a commercial building, right? Then `building=commercial` is not very accurate but correct.

----

sorry for offtopic, hopefully it is OK to answer that (if not then please let me know)

> Also wouldn't making that selection override ID's template?

It will change `building=yes` to `building=commercial` what should not break anything. iD had /has a bug with destroying building value and resetting it to `building=yes` but it never had trouble with more specific building values

> considering it last operated in 1964

So it is no long a working swing carousel, but recognized as a former and now disused swing carousel?

In such case `disused:tourism=swing_carousel` should be used (as current tagging claims to be an active swing carousel)

**Comment by westnordost** [comment]
@mxxcon Your suggestion makes sense, will do.
