### ISSUE TITLE
[Question] Maintaining forks with additional quest types

### ISSUE THREAD

**Issue by Atrate** [westnordost/StreetComplete#1894]
Hello,

I am maintaining a fork of StreetComplete with a few features I find handy. I have a question about implementing new quests, though.

To avoid conflicts with SC, the StreetComplete:quest_type key would certiainly need to be changed — is it enough for me to simply change it to e.g. CompleteStreet:quest_type or do I need to do something else?

**Comment by westnordost** [comment]
`StreetComplete:quest_type` is used to generate the statistics. If you for example implemented a custom quest named `AddParkingLanes`, your fork will add that quest type information to each changeset.

The statistics backend will then record this information and count how many `AddParkingLanes` quests you solved and also send out this information to (your) client on update of the statistics. If your client is able to display this quest type, it will also show it in your statistics.

So, I do not see a reason for you to change anything there.

**Comment by Atrate** [comment]
Alright, so as long as I am sure that a quest won't get implemented in SC (e.g. AddBenchMaterial) then I can just tag the changeset with StreetComplete:AddBenchMateral, right?

**Comment by westnordost** [comment]
Even if you are sure that the quest will get implemented, I don't see a problem with it.

**Comment by matkoniecz** [comment]
What about cases where quest is modified and asks about more elements or in other way increases number of edited objects?

Or quests that are out of scope for SC?
