### ISSUE TITLE
Addition to House Number quest: Street name ambiguity

### ISSUE THREAD

**Issue by matthiasfeist** [westnordost/StreetComplete#1897]
Hi!

I use your app quite a lot for tagging. I do however find myself in a situation where I would like to map the street name together with the house number. For example when the house is on a corner or a junction of 2 streets like this here: https://www.openstreetmap.org/way/331309510
Simply adding the house number does not really help that much since it needs to be clear to which street this house number belongs.

My suggestion:
Whenever a building is close to 2 streets, the dialog for adding the house number should also show a drop down (or similar) of the street names that are close by.

**Comment by matkoniecz** [comment]
Already implemented in v20.1, see #213 and https://github.com/westnordost/StreetComplete/releases

It is possible that 

- this version is not yet released for you (especially of you use F-droid that sometimes lags behind significantly)
- you have not updated app
- this quest have not been downloaded yet (note #1856)

**Comment by matthiasfeist** [comment]
Thanks. I'll re-install the app and see that I get the right version!
Thanks and sorry for the spam.

**Comment by westnordost** [comment]
If you have auto-sync off, the quest will also not appear right away but only after you uploaded the housenumber.

**Comment by matkoniecz** [comment]
Note that reinstall should not be necessary, upgrading apps in store should work as usual.
