### ISSUE TITLE
offline mode

### ISSUE THREAD

**Issue by Haikuch** [westnordost/StreetComplete#19]
I would like to download areas and then use the map offline

**Comment by westnordost** [comment]
You can download quests in an area beforehand and also solve these while being offline already. The solutions will be uploaded when you next have a connection/have wifi automatically.

To download the quests in any given area, simply zoom there in the map, then select "Scan for quests here", voilà.


This only downloads the quests however, not the map. The map will appear simply white if you are offline. If that bothers you, what you can do is to increase the map cache size in the settings and scroll through the area you want to survey beforehand.

Am 20. März 2017 12:22:03 MEZ schrieb Haikuch <notifications@github.com>:
>I would like to download areas and then use the map offline
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/westnordost/StreetComplete/issues/19

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by Haikuch** [comment]
> If that bothers you, what you can do is to increase the map cache size in the settings and scroll through the area you want to survey beforehand.

yes thats what bothered me :) I will try like you said

**Comment by Haikuch** [comment]
ok it works. but it would be much nicer to see a highlighted area where you can be sure that all data is there to go into offline survey. Just like choose an area, click download and have it marked with a border and color for example that you can go there on offline survey. i understand that this might be complicated because you rely on an external map library?

And I always get an error that the answer could not be uploaded

**Comment by westnordost** [comment]
Yes, the lib I am using is missing this feature so far. So the current solution is an intermediate one. 


Acknowledged, this error while being offline is annoying, I'll fix that.

On 21 March 2017 14:53:23 CET, Haikuch <notifications@github.com> wrote:
>ok it works. but it would be much nicer to see a highlighted area where
>you can be sure that all data is there to go into offline survey. Just
>like choose an area, click download and have it marked with a border
>and color for example that you can go there on offline survey. i
>understand that this might be complicated because you rely on an
>external map library?
>
>And I always get an error that the answer could not be uploaded
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/westnordost/StreetComplete/issues/19#issuecomment-288084561

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by westnordost** [comment]
Actually it is even a bug. Currently the setting when to sync automatically is also not being respected.
