### ISSUE TITLE
it is possible to open cycleway selection menu multiple times

### ISSUE THREAD

**Issue by matkoniecz** [westnordost/StreetComplete#1902]
Menu should be openable exactly once.

**How to Reproduce**
Find place where `cycleway:both=no` is not yet tagged.
Select cycleway quest.
Quickly tap multiple times at one side with question marks, before interface will appear.
Now one needs to answer multiple times before feature selection menu will disappear.

**Versions affected**
v21.0-beta1 was tested, likely also earlier ones

Android 10

**Comment by westnordost** [comment]
Not really worth fixing. So if the menu opens twice, it doesn't lead to anything bad.
