### ISSUE TITLE
highway=construction is not rendered

### ISSUE THREAD

**Issue by RubenKelevra** [westnordost/StreetComplete#1903]
Previously `highway=construction` was rendered as a zebra line, now it's just missing from the map (in dark and light theme).

**Versions affected**
v21.0-beta1

**Comment by westnordost** [comment]
Noted. For v21.0, the provider of vector map tiles was changed. The tiles they serve have fewer details. I think to display highway=construction is not crucial.

**Comment by peternewman** [comment]
Presumably there aren't any quests which cover highways in that state?

**Comment by matkoniecz** [comment]
There is a quest asking whatever `highway=construction` is already completed (with protection to not ask it over and over again).

**Comment by RubenKelevra** [comment]
Yeah there's a construction quest, to ask the users if a highway is completed - or better, is driveable again. `highway=construction` doesn't mean it doesn't exist, but only that it's currently not (yet) allowed to drive on.

@westnordost thanks!

It just looks odd, since a part of a street is missing, and then it appears in blue when the quest is asked - might be a bit confusing to the users ;D

**Comment by matkoniecz** [comment]
Looking at https://www.jawg.io/docs/apidocs/maps/#endpoint-to-use examples it seems Jawg Maps limitation.

**Comment by westnordost** [comment]
So I'll mark this as will not fix, the vector tile provider in use simply does not contain this information
