### ISSUE TITLE
Named roads sometimes don't show quests, just dots

### ISSUE THREAD

**Issue by peternewman** [westnordost/StreetComplete#1905]
Named roads sometimes don't show quests, just dots

**How to Reproduce**
Find a short named road with a quest on it (e.g. surface type), zoom in, due to the name changing size, and depending on the length of the road and the length of the name, you may only ever get a dot, or sometimes get a dot and sometimes a quest. It doesn't happen on unnamed ones as there is nothing to clash with.

Sometimes the quest appears and disappears as you zoom in, sometimes it never appears.

**Versions affected**
v21.0-beta1 Android 9

**Comment by matkoniecz** [comment]
Is it happening with some specific location? In general dots should be appearing only on zooming out. 

And quests markers should not be blocked by street names - AFAIK there should be no collision at all.

**Comment by m-rey** [comment]
I think I can confirm this. Quest markers interfere with road names. Note that I zoomed in enough, as other quests markers can be seen: ![screenshot](https://user-images.githubusercontent.com/42996147/85061220-c1a93200-b1a6-11ea-98e1-631b1f1f97da.png)

After rotating the screen (so road name and quest marker don't overlap anymore): ![screenshot](https://user-images.githubusercontent.com/42996147/85061373-00d78300-b1a7-11ea-8bee-3f065e557449.png)

**Comment by matkoniecz** [comment]
Location for testing: https://www.openstreetmap.org/#map=19/49.42402/11.07473

**Comment by westnordost** [comment]
Okay, text should of course not block display of the pins

**Comment by peternewman** [comment]
> Okay, text should of course not block display of the pins

However also we'll want to see the street names, unless it's already in the quest text, to ensure we're answering for the right street. So ideally it just wants to resize around the pin if possible.

**Comment by matkoniecz** [comment]
I found where order is defined, I am now experimenting to reliably trigger this bug.

**Comment by westnordost** [comment]
Actually, text should have a `priority`, not an `order`. Not sure how these two interact.

**Comment by matkoniecz** [comment]
Looking at https://github.com/tangrams/tangram-docs/blob/610d78b966d603bfdd409580d32e8a793d3d29cd/docs/Syntax-Reference/layers.md#priority it seems that priority is about something else (which styling is applied) - see https://github.com/tangrams/tangram-docs/blob/1f5bf1c6b0568b42aab4ad9cb9c5abfc8e55bc1e/docs/Syntax-Reference/draw.md#order

Though text is supposed to be special, and I am not 100% sure that problem reported here actually happens - text is quite irritating with its disappearing/jumping around, dots make it even more confusing etc

**Comment by peternewman** [comment]
> Though text is supposed to be special, and I am not 100% sure that problem reported here actually happens - text is quite irritating with its disappearing/jumping around, dots make it even more confusing etc

I assume you're referring to something else (in the documentation perhaps)? I can provide some more proof of this specific issue if you'd like?

**Comment by matkoniecz** [comment]
I debugged it and submitted #1908 - location from https://github.com/westnordost/StreetComplete/issues/1905#issuecomment-646251956 was very useful
