### ISSUE TITLE
Errors to different zooms

### ISSUE THREAD

**Issue by JorgeSanzS** [westnordost/StreetComplete#1906]
When zooming there are anomalous behaviors regarding the viewing of quests. Large areas that are not shown although they do exist. As you zoom, they appear and disappear again. By zooming instead of appearing more all disappear.

I've noticed it only in the last beta.

Some recorded examples. Sorry for the music.
https://photos.app.goo.gl/ueSkFrUdAJUtwVUm7

**How to Reproduce**
Trying to increase and decrease the zoom in different areas.

**Versions affected**
V21.0-beta1 Android 9

**Comment by westnordost** [comment]
Hi JorgeSanzS, thanks for the videos! Could you describe the bug(s) again in Spanish, maybe each with a link to the video that shows this?

**Comment by peternewman** [comment]
This looks similar to my report in #1905 . Only happening with more stuff. I think I saw the occasional thing with quests which aren't on roads, but there aren't so many quests left near me so it happend less.

**Comment by JorgeSanzS** [comment]
Son varios problemas que viéndolo con más tiempo creo que tiene que ver con los nombres de las calles.
Hay zonas grandes que hay misiones pero no te aparece ninguna resaltada cuando no tienes zoom. Antes si salían algunas.
https://photos.app.goo.gl/AATswQgPhd8o7k4V9

Hay tareas en las que tienes que conseguir encontrar el zoom en el que salen. Según aumentas o alejas aparecen o desaparecen y vuelven aparecer.
https://photos.app.goo.gl/r2UritcRHFARBeLr9
https://photos.app.goo.gl/UgMHx9i78oNMQpMu6

Hay otros directamente que ni aparecen. Zoom máximo y no aparece ninguna tarea cuando si hay puntos de que existen tareas en esa posición.
https://photos.app.goo.gl/ayyzeNcmYMJLWcnc7
https://photos.app.goo.gl/siZC2pSa7CSszYjAA

**Comment by westnordost** [comment]
Gracias, @JorgeSanzS 
Voy a continuar in Ingles:

Ok, turns out that all the three things you observed were the same underlying problem that was fixed by @matkoniecz in #1908 . So, this issue can be closed, it is the same as #1905.
