### ISSUE TITLE
Consider tracktype to surface tag relation

### ISSUE THREAD

**Issue by patman15** [westnordost/StreetComplete#1909]
**Use case**
When tagging the surface of tracks StreetComplete does not consider a possibly already existing tracktype tag. The problem arises from the fact that tracktype and surface are somewhat linked as you can read from the [Wiki](https://wiki.openstreetmap.org/wiki/DE:Key:tracktype) (unfortunately only in the german version). See section (that does not exist in English version) starting at "Welche Werte bei welch einem tracktype=* sinnvoll sind kann man hier entnehmen:"
Basically it says having tracktype=grade1 and surface=grass is not reasonable as tracktype=grade3 and surface=asphalt is not.

It happend to me that I added a surface in Streetcomplete that did not make sense due to the fact that I was not aware of the tracktype.

**Proposed Solution**
1. make sure that the tracktype quest is answered first (currently default is after surface)
2. limit the selectable surfaces in dependence on the tracktype as suggested by the wiki or the there linked overpass checks.

OR
* at least give a hint about the tracktype to the user while selecting the surface

Feedback warmly welcome, I hope I could explain the problem that could lead to inconsistent mapping.

**Comment by matkoniecz** [comment]
Note that sandy track may be tagged already as `tracktype=grade1` - due to incorrect or outdated answer.

In such case correct `surface` will mismatch `tracktype` - what is good as it may alert other mappers that something is wrong.

**Comment by matkoniecz** [comment]
> It happend to me that I added a surface in Streetcomplete that did not make sense due to the fact that I was not aware of the tracktype.

Have you added the correct `surface`? Maybe `tracktype` that was present was incorrect?

**Comment by patman15** [comment]
> > It happend to me that I added a surface in Streetcomplete that did not make sense due to the fact that I was not aware of the tracktype.
>
> Have you added the correct `surface`? Maybe `tracktype` that was present was incorrect?

Well, to be exact, no. It was a `tracktype=grade3` and I added `surface=grass` because there was definitely grass in the middle of the track. Still I would have decided differently (hopefully) if I would have been aware of the `grade3` so at least the hint (see my second proposal) would reduce wrong mappings or point out misalignments.
Put I see where you are heading to; it's quite complex.

**Comment by westnordost** [comment]
There could be a quest that asks for the surface of a track whose tracktype contradicts the currently set surface. However, I think it is not necessary if the "maintenance quests" are implemented, in other words, Streetcomplete will ask for surfaces and track types in regular intervals to keep the data current.

**Comment by matkoniecz** [comment]
> Streetcomplete will ask for surfaces and track types in regular intervals to keep the data current.

Though maybe as an extra feature StreetComplete may be smart and ask more often for unstable or dubious data. For example `surface=asphalt` is less likely to change than `surface=compacted` that much more often will degrade into `surface=dirt` or will be upgraded to `surface=asphalt`

**Comment by westnordost** [comment]
Yes, it could, thanks for the input. However, that's off topic here and it is still not clear whether this extension to StreetComplete will be funded or not.

Regarding this issue, see https://github.com/westnordost/StreetComplete/issues/1909#issuecomment-648851270 : If maintenance quests are not implemented, then this particular case could be implemented as an own quest.
