### ISSUE TITLE
Create quest for "The place has gone or never existed. This is an auto-generated note from MAPS.ME" notes

### ISSUE THREAD

**Issue by matkoniecz** [westnordost/StreetComplete#191]
Maps.me generates massive amount of notes like https://www.openstreetmap.org/note/608015

This type of note is nearly impossible to be remotely fixed as it requires visit.

It should be possible to turn it into yes/no quest.

Notes are already downloaded so it should not increase data usage and load on OSM servers on checking whatever quest is possible.

Actions: add answer to the note if StreetComplete user confirms, close note if the object is present.

Main problem is (a) fragility - it relies on data created by another program and format may change without warning (but existing notes will stay) (b) describing matched element without exposing user to OSM tags.

Pseudocode:

- find all notes
- keep notes with "The place has gone or never existed."
- search for all very close shop=*/amenity=*/maybe something else

Create quest "is foobar still present?"

How one may describe element? Maybe for start ignore cases of objects without names and use "shop <name field>" for shop=* objects and "<name field>" for amenities?

**Comment by westnordost** [comment]
Hm, users of this app should clean up after another app? That sounds twisted. Anyway, what makes a StreetComplete user so much more trustworthy than than a Maps.Me user?

So far, the app does not delete data. This is a little more complicated as well because edge cases are that the to-be-deleted object is part of a relation etc.

**Comment by matkoniecz** [comment]
I though that it should not delete data, but post comment to the note (and ignore notes that already have any comments).

**Comment by westnordost** [comment]
Ah, I see. Well, that's doable.

**Comment by matkoniecz** [comment]
I would classify it as new quest (https://github.com/westnordost/StreetComplete/issues?q=is%3Aissue+is%3Aopen+label%3A%22new+quest%22)

**Comment by rugk** [comment]
Wow, actually this is bad from Maps.me as in the Maps.me app there is a very clear connection to the object, where one "creates this comment". (Actually in the app it is a delete button, which can only be used with an object being selected). However also blaming OSM here as there you cannot add comments for specific objects/cannot bind this comment to an object…
Nevertheless, it does not matter who's to blame it, so let's get to this issue…

> Anyway, what makes a StreetComplete user so much more trustworthy than than a Maps.Me user?

Maybe that they can only edit nearby areas in the future?

I think the idea is good, so one can easily add more opinions to one such "deletion suggestion". If the user declines it (aka "No the object is there!"), I think the comment can be closed immediately.

> and ignore notes that already have any comments

Mhh, then you only have two opinions. Two +1 for deleting is IMHO maybe not enough. ~~Just imagine too "clever" users using both apps immediately marking their comment as "true".~~ Okay, no, they use the same account, so this would be suspicious and if they use different accounts that's active violation…

Anyway I am not sure whether two times confirming such a deleti8on suggestion is enough. Maybe it is, however, when we consider that on all other editors one can do it immediately.

**Comment by matkoniecz** [comment]
> Wow, actually this is bad from Maps.me as in the Maps.me app there is a very clear connection to the object, where one "creates this comment". (Actually in the app it is a delete button, which can only be used with an object being selected)

Wow, that is really bad. I created https://github.com/mapsme/omim/issues/6016 but I have limited hope for fix, given that maps.me developers seem to ignore that edits/notes created by maps.me are nearly useless (some are useful but it is balanced by harmful ones).

**Comment by westnordost** [comment]
So this is kinda blocked by omim#6016. I figure it would be possible to guess the element that was meant, but perhaps they fix this on their side before this quest is implemented in SC, this would make it easier.

**Comment by claudiush** [comment]
Looks like this is unblocked now that Maps.Me added more details on the deleted object in the notes they generate since version 7.3.3

**Comment by rugk** [comment]
The question could look like this:

> #### Is a `<POI types>`, called "`<POI name>`", still there?
> (small text:) *At <date> another user reported that this object is not here anymore.*
> **[ It still exists ]** | **[ No, it's gone ]**

Taking [this example](https://www.openstreetmap.org/note/1009059#map=15/-33.5533/-70.6770):
> #### Is a shop-mall, called "Supermercado Tottus", still here?
> *At 2017-05-11 another user reported that this object is not here anymore.*
> **[ It still exists ]** | **[ No, it's gone ]**

**Comment by rugk** [comment]
>  westnordost assigned westnordost and unassigned westnordost

So you thought about implementing it, but finally thought not to do it? :smile: 
As it seems this should now be one of the easier quests to implement.

**Comment by matkoniecz** [comment]
> Is a shop-mall, called "Supermercado Tottus", still here?

So, like #309 it is blocked by missing descriptions of objects based on a tag. Though here it seems that base form of word would be sufficient - so maybe it may be done as a first steep toward AddPlaceName quest?

**Comment by westnordost** [comment]
Yes I would say as long as the object has a name, it is not blocked by #309 . It could only be improved by when #309 is (ever) done.

**Comment by matkoniecz** [comment]
After thinking more about this and processing some notes like this

- it is impossible to make delete edit with SC
- confirmation that maps.me is correct is not useful
- it is really rare for maps.me deletion reports to be wrong

As result I am no longer considering this quest as a good idea.
