### ISSUE TITLE
minor bug: animation of solved quests is cropped while uploading

### ISSUE THREAD

**Issue by Norwi** [westnordost/StreetComplete#1910]
The counter of solved quests is cropped while uploading changes.

![0001-0250](https://user-images.githubusercontent.com/18899671/85235415-f15d7180-b414-11ea-9a49-9ac35bdda1e4.gif)

**How to Reproduce**
- press upload button

**Versions affected**
- Android 10
- StreetComplete v20.2

**Comment by m-rey** [comment]
Can confirm. It's not limited to the latest version, but also existed in many previous releases.

**Comment by peternewman** [comment]
This is a duplicate of https://github.com/westnordost/StreetComplete/issues/1635 (although I see that didn't get re-opened when I confirmed it was still broken. However @Norwi has a nicer demo of the fault.

**Comment by westnordost** [comment]
Is this groundhog day? :-(

I'll try to fix it

**Comment by peternewman** [comment]
Looks like you found Punxsutawney Phil @westnordost , this is finally gone for me! :partying_face:

**Comment by Norwi** [comment]
Thank you! It's gone for me as well.
