### ISSUE TITLE
Crash in question type settings

### ISSUE THREAD

**Issue by OpenKartat** [westnordost/StreetComplete#1911]
**How to Reproduce**

Open settings -> questions type settings -> scroll to bottom. The app crash before getting to the bottom. 
The bug doesn't get fixed by reinstalling app.

**Versions affected**

Samsung A70, android 10, One UI version 2.0, knox 3.5
StreetComplete 20.2 (this bug was also in 20.0 version). App is used in Finnish.

**Comment by peternewman** [comment]
Assume you mean "Quest selection", this doesn't happen on v21.0-beta1 on Android 9 in British English. It's perhaps worth trying switching to English as a first test @OpenKartat ?

**Comment by OpenKartat** [comment]
Yes, I mean Quest selection. The problem doesn't appear when I changed my phone to English. 

Usually the app crash just before questions "Does this ferry route transport motor vehicles?"

**Comment by matkoniecz** [comment]
Thanks for reporting!

App goes down with "java.util.UnknownFormatConversionException: Conversion: k" 

It is fixable by changing translations

from
 
``<string name="quest_accepts_cash_title">"Hyväksyykö s% käteismaksun?"</string>`

into

`<string name="quest_accepts_cash_title">"Hyväksyykö %s käteismaksun?"</string>`

What I just did - https://github.com/westnordost/StreetComplete/blob/master/CONTRIBUTING.md#translating-the-app and will take effect once translations are pulled in

Not sure how it should be systematically prevented and is it a bug in my #1648.

**Comment by matkoniecz** [comment]
BTW, if there are any other issues in Finnish translation - feel free to improve it! (see https://github.com/westnordost/StreetComplete/blob/master/CONTRIBUTING.md#translating-the-app )

Again, thanks for the report - "Usually the app crash just before questions "Does this ferry route transport motor vehicles?"" was a very helpful part.

**Comment by matkoniecz** [comment]
Any idea how can I leave Finnish language translation at SC poeditor page? I joined Finnish at https://poeditor.com/join/project/IE4GC127Ki and now it appears that I am unable to leave - what I would like to do as in general I am not really able to contribute.

**Comment by peternewman** [comment]
> Not sure how it should be systematically prevented (add check in translation import script?) and is it a bug in my #1648 (add check there?).

If we assume there should be the same number of substitutions in the default translation as in all the translations, then it would be trivial to count them and therefore flag an alert when the number differs between them. It would be easy enough to knock together some Perl or similar to do so.

Although I then found this, and maybe the solution is to add it to this:
https://github.com/marketplace/actions/android-translations

Then run the whole action against the repo.

**Comment by westnordost** [comment]
> Not sure how it should be systematically prevented (add check in translation import script?) and is it a bug in my #1648 (add check there?).

Actually, I try to do just that: The Inspector in Android Studio warns if the number of placeholders in different translations is different. So I usually run the Inspector before each release. Looks like I missed it.

**Comment by westnordost** [comment]
So I'll close this because I saw that @matkoniecz already fixed it in POEditor

**Comment by smichel17** [comment]
> So I usually run the Inspector before each release

Is it possible to automate this? (Here I must sheepishly admit that I have never taken the time to familiarize myself with testing in Android)

**Comment by westnordost** [comment]
Don't know

**Comment by peternewman** [comment]
It seems it is. This says run `gradlew lint`:
https://developer.android.com/studio/write/lint#commandline

I've added a run of that to some previous work I'd started about adding CI to the repo to also run lint #1917 .
