### ISSUE TITLE
Show type of place when asking for details

### ISSUE THREAD

**Issue by Helium314** [westnordost/StreetComplete#1912]
Some places are rather badly named, e.g. stores without name / with only generic name that are named after the owner in OSM.
In such cases it is often completely unclear which of possibly several nearby shops is meant in the quest.
Another somewhat similar situation is a place that has different opening hours for different parts, e.g a shop with attached Café where both have the same name in OSM, and it is unclear which part is meant.

In such cases it would help to know the type of shop, so one can better identify the place where details should be added (wheelchair access, opening hours,...).

I am aware that these cases are quite rare, and always adding the type can increase the amount of text considerably. So maybe the type could be added to the "can't say" menu.

**Comment by matkoniecz** [comment]
I was sometimes confused and unable to locate place, while "oh, I am looking shoe shop" or "right, is is a restaurant" type of hint allowed me to locate it. Or made my more certain that it is actually gone.

**Comment by westnordost** [comment]
For which quests should this be done in your opinion?

**Comment by matkoniecz** [comment]
opening hours, wheelchair and probably other business ones (I solve primarily opening hours one).

**Comment by Helium314** [comment]
This, and possibly the cash payment quest.
Maybe the WiFi access quest... but I would assume this is only asked for restaurants and cafés (never tried it).
Vegetarian/vegan quest is only for restaurants and cafés, so adding the type would not help.

**Comment by Helium314** [comment]
I don't want to be as annoying as I feel I am right now, but almost every time I'm answering opening hours and wheelchair quests in Czechia I have problems, because (compared to more "western" countries):
* Shops often have no name (and even many that have, have it written in a way that you need to search for it)
* Many people apparently don't/didn't care about putting the actual name (if it exists) into the name tag, often the name tag seems to contain some random word written in large letters on the store front
* There seems to be rather high fluctuation, meaning many shops only live for a short time
* Shop locations are often only accurate within ~20 m, which is not enough when there are several shops nearby

All this means I have to really search for the place the quest is about in roughly 30% of the cases, and even if I don't find it often I am not certain that it doesn't exist.
So I would really appreciate ANYTHING that helps me identify a shop...

I would even try to add this enhancement myself, as it seems to be rather simple. But after looking at the code I concluded my non-existent coding skills are not enough to even follow how anything makes its way into the strings (replacing %s).

**Comment by westnordost** [comment]
Absolutely. You do not need to argue that this would make sense, it is already accepted as a possible enhancement. However, I currently have limited time. If you like to implement it yourself, I can give you some hints:
- in a quest, `getTitle` returns which string id (defined in `strings.xml`) to use
- in a quest, `getTitleArgs` returns an array of strings that should be placed into any placeholders (`%1$s`, `%2$s`,...) mentioned in the used string id

**Comment by Helium314** [comment]
It took me a while to learn what is going on, at least to the level I needed...

I changed https://github.com/westnordost/StreetComplete/blob/master/app/src/main/java/de/westnordost/streetcomplete/quests/opening_hours/AddOpeningHours.kt#L101
from
`return if (name != null) arrayOf(name) else arrayOf()`
to
`return if (name != null) arrayOf(name,featureName.value.toString()) else arrayOf()`
and added a second placeholder in strings.xml: `What are the opening hours of %1$s (%$2s)`

This seems to work as intended, but I'm not sure if there could be trouble in some rare cases.
Now should I modify strings.xml for every language, or is this done some other way?

**Comment by westnordost** [comment]
No, just English. On accepting the PR, I will change them all in POEditor manually, no need to impose a new string on the translators to translate (that would be the normal process)

**Comment by Helium314** [comment]
Alright, I'll first try to add the same for the wheelchair quest... may take a while, since it seems to use the same string whether the place has a name or not, and so far I didn't find a place where I can test my changes (no-name places that are actually tagged as such are pretty rare...)
