### ISSUE TITLE
[Meta Analysis] Quest download, processing, and display

### ISSUE THREAD

**Issue by smichel17** [westnordost/StreetComplete#1914]
I have been watching this repo for a while, and have noticed that there are some common issues/requests that are all related. I think the solution to any one of these issues would do well to take the others into consideration. I also think now is a good time for that consideration, since #1901 may make solutions to this type of problem easier to implement.

Here are **some** of the issues I'm talking about. I've attempted to categorize them, but there's some overlap.

- Offline maps & quests: #122, #1418
- Quest download order: #1510, #1428
- Multiple quests for the same element: #1550, #1352, #124, #1717, #1119
- Which quests to display: #1301, #1746, #1829, #1190, #869, #1654, and https://github.com/westnordost/StreetComplete/issues/1874#issuecomment-645441710, which is what directly prompted me to write this issue (specifically the last point about how many quests are shown).

The common thread is that they are all related to our strategy for choosing what quests appear on screen at any given time. Some of them also challenge the abstraction of a quest (https://github.com/westnordost/StreetComplete/issues/1717#issuecomment-581188710). And, I think they all come from a common set of use cases.

- New and casual users (and power users, some of the time) care most about **solving interesting/meaningful quests.**
     - We should limit displayed quests to a certain density, prioritizing those most important to the user.
    - We could ask the user to rank their interest on or near first run. Could double as a stalling tactic while we wait for initial quest download/processing :laughing: 
    - For the user's top priority quests, we could search a larger area. I might go out of my way to fill out street names and house numbers, but not building levels.
- Power users (completionists, and/or more interested in mapping for its own sake) care about **efficiency**. Ideally, they would like to walk through an area, selecting  each element once, as they pass it, and answer all quests for it, without stopping.
    - Quest display density should not be limited.
    - It would be useful to download and precompute as many quests as possible.
- Users with **limited data or cell coverage** are in between.
    - They need everything pre-*downloaded*, but not necessarily pre-*computed*.
    - They may or may not want all quests displayed.
    - They probably want the ability to pre-download a specific route (rather than just a big circle in their vicinity) and limit both downloaded and displayed quests to that area.
- People mapping while they are a **passenger in a car** (or bus, train…) are a mix of everything.
    - While they may not need quests pre-downloaded or pre-computed, those quests must appear far enough ahead of them that they are populated on the map before they reach that area. So, a route planning feature would be useful.
    - Probably want prioritized quests, since time to solve may be limited.
    - Certain quests are unsolvable and should be hidden entirely.

I was originally going to include some suggested implementation, but that was taking a long time to write and maybe will change with discussion anyway.

**Comment by smichel17** [comment]
I'm going to close this since it has garnered no discussion and I think any suggestions I have can be made on other issues and reference this one. Feel free to re-open if there is anything actionable that is not covered by open issues.

**Comment by westnordost** [comment]
Sorry, as announced, I cannot put much time into StreetComplete anymore. Such open ended discussions do have the least priority for me, especially those that may result in possibly big UX changes as I wouldn't find the time anyway to then implement it.

**Comment by matkoniecz** [comment]
For me it was also on the "read this" list, to do once I will have time, access to phone and unable to do something else (I have multiple open projects, even in just SC I started more that it is optimal).

**Comment by smichel17** [comment]
All good. Feel free to still read and respond if you'd like; closing just means I'm not requesting any response -- I am mindful that the number of open issues is creeping upward and I have what I need from this one (the ability to refer to it; for example, when I chime in on download strategy in #1874).
