### ISSUE TITLE
"Display always on" setting doesn't work anymore

### ISSUE THREAD

**Issue by cyclingcat** [westnordost/StreetComplete#1919]
Hi there,

currently I'm trying out a new smartphone in order to use it exclusively with my bikes, following a hint from a road bike forum. It's a Cubot Quest with Android 9. Waterproof, shockproof, not too heavyweighted, looks like a reasonable tradeoff between weight, price and features like battery time, size and so on.

Of course I installed StreetComplete on it and tried it out immediately, however, on this device the "Display always on" setting doesn't work anymore. The display regularly goes off after 2 minutes without usage. My regular smartphone (bq Aquaris M4.5, Android 5.1) doesn't show this behaviour, the setting works here as long as SC is in the foreground.

Is this a well-known behaviour? A bug in SC? An Android bug? Some Android setting I could have changed inadvertently and shows this side effect? A compatibility issue? Apart from that, SC seems to work well.

StreetComplete v20.2 (on both devices).

The cycling cat

**Comment by matkoniecz** [comment]
> The display regularly goes off after 2 minutes without usage

Is there maybe system-wide setting to lock phone screen (or disable it) after this time?

Is it an unmodified Google Android (Android One)? Or with modifications from phone maker?

Is there some related phone-wide setting? Or some "deep battery saving"/"ultra battery saving" mode? Some Android modifications were doing questionable/inconsistent things to get longer-lasting battery (see https://dontkillmyapp.com/ for complaints about killing apps working in background).

My Xiaomi phone was doing very stupid things before I disabled such customizations.

**Comment by westnordost** [comment]
The app is setting the window flag to request to keep the screen on. There is nothing beyond that the app can do (if for example the system does not consider this setting).
