### ISSUE TITLE
covered=yes/no for bicycle parkings

### ISSUE THREAD

**Issue by matkoniecz** [westnordost/StreetComplete#192]
documented at http://wiki.openstreetmap.org/wiki/Tag:amenity%3Dbicycle_parking

From looking at https://github.com/westnordost/StreetComplete/blob/master/app/src/main/java/de/westnordost/streetcomplete/quests/bus_stop_shelter/AddBusStopShelter.java adding yes/no quests is fairly easy.

**Comment by westnordost** [comment]
Jup it's easy. How about you try yourself on your first quest? :-)
