### ISSUE TITLE
Cog wheel (settings icon) broken on some phones

### ISSUE THREAD

**Issue by matkoniecz** [westnordost/StreetComplete#1921]
**How to Reproduce**

Buy a cheap phone? For example Xiaomi Redmi 4, running Android 6.0.1 MMB29M

![Screenshot_2020-06-26-12-40-37-540_de westnordost streetcomplete debug](https://user-images.githubusercontent.com/899988/85850087-6978be00-b7ac-11ea-895a-d188cf20f1c3.png)

Though on Xiaomi A2 Lite with Android 10 it works perfectly fine.

**Versions affected**
See above, tested with latest master.

**Comment by matkoniecz** [comment]
Probably not worth thorough investigation for a long time but maybe there is obvious source of that glitch?

**Comment by westnordost** [comment]
Mh, a will not fix I fear, except if you would like to dig into it. It's `ic_settings_48dp.xml` and a clipart actually supplied by Android itself. So, obviously a rendering issue on certain Android versions. IIRC I have this display bug on a Android 5.1 as well.

**Comment by matkoniecz** [comment]
`clipart actually supplied by Android itself` - so I will file it as "Google/Xiaomi failed somehow". Probably Google given "I have this display bug on a Android 5.1 as well.".

Or maybe someone liked bucket wheel excavators a bit too much.
