### ISSUE TITLE
Allow answering "sidewalk mapped separately" (sidewalk=separate) in the sidewalk quest

### ISSUE THREAD

**Issue by matkoniecz** [westnordost/StreetComplete#1925]
Via can't say menu

**Use case**
https://www.openstreetmap.org/note/2244771

**Proposed Solution**
See title (I will make pr for this after the signal that it would be accepted)

**Comment by westnordost** [comment]
Hmm weird, I thought such an other answer option already existed! But now I can't find it.

**Comment by westnordost** [comment]
Would be the same for cycleway.

**Comment by matkoniecz** [comment]
> Hmm weird, I thought such an other answer option already existed! But now I can't find it.

The same for me. It turns out that it exists for quest asking about foot access on roads tagged as without sidewalks (with some additional filters).  have not checked git history, but it is unlikely that it was present and it disappeared.

**Comment by westnordost** [comment]
Ah, there was something like that for the `AddProhibitedForPedestrians` quest.

Yes, makes sense to include it as an other answer option, IF the sidewalk is visible on the JawgMaps map. A vector tile provider may decide to not include ways that are tagged as `highway=footway + footway=sidewalk` or similar to have a cleaner map. Didn't check how it is with JawgMaps.

**Comment by matkoniecz** [comment]
> Would be the same for cycleway.

This is trickier as user is unable to recognize whatever line mapped as separate is marked as cycleway - it may be justa  regular footway (technically the same may happen with cyleway tagged `foot=no`, with footway not mapped for sidewalk quest and user thinking that it is a sidewalk - but for many reasons it is very unlikely).

**Comment by westnordost** [comment]
So that's the general problem about that: The user needs to view and trust the background map.
For example if the user were to switch to a satellite-only view, this won't work.

**Comment by matkoniecz** [comment]
In cases where user is aware about separately map way this answer will allow him/her to answer correctly (without note creation etc).

In cases where user is unaware about separately mapped way (missed on the map, old map data etc) then it will not result in nothing bad.

In cases where user thought wrongly that there is a separately mapped way but it false it would make situation worse (bigger problem for cycleways).

And as usual, it increases maintenance burden and has some setup costs (especially for translators).

----------

Overall I will certainly add it to my fork (to avoid note creation), let me know whatever I should open PR for that or keep it as a fork-only change.

**Comment by westnordost** [comment]
I think it can be included as a PR, but the wording must be something like "sidewalk displayed separately on map" or similar. That it is "mapped separately" is OpenStreetMap-speak

**Comment by matkoniecz** [comment]
"Already visible on the map"/"Visible on the map"?
