### ISSUE TITLE
dark mode has black font on dark background

### ISSUE THREAD

**Issue by qorron** [westnordost/StreetComplete#1926]
**How to Reproduce**

activate dark mode
**Versions affected**

Android 10
v20.2
![Screenshot_20200628-154040](https://user-images.githubusercontent.com/808330/85949354-8bae3f80-b956-11ea-98d6-4d0d1f69d1f8.jpg)
![Screenshot_20200628-154045](https://user-images.githubusercontent.com/808330/85949363-979a0180-b956-11ea-90e0-96ed47bd992f.jpg)

**Comment by matkoniecz** [comment]
The same as #1400 but with a better title.

I noticed this issue but I never managed to find what is causing this or even find way to reliably trigger this

**Comment by westnordost** [comment]
duplicate

**Comment by qorron** [comment]
restarting with dark mode on fixed it.
