### ISSUE TITLE
Translation for "Norsk Bokmål (Norge)" is not used

### ISSUE THREAD

**Issue by matsrand** [westnordost/StreetComplete#1931]
My phone is configured to use "Norsk Bokmål (Norge)", but all the text in StreetComplete is in english.

**How to Reproduce**
In "Settings" select "System", "Languages & input", "Languages".
Push "Add a language" and select "Norsk bokmål (Norge)" and ensure that it is on the top of the list of preferred languages.
Start StreetComplete and you will see that the language is still English (or maybe an other of your preferred languages).

If I select for instance "Nynorsk (Noreg)" is the text translated correctly.

**Versions affected**
Android: 10
Streetcomplete: v20.2

**Comment by westnordost** [comment]
Can you select just Norwegian?

**Comment by westnordost** [comment]
the Bokmal strings are copied to the language code "no". I changed it that they are also copied to "nb".

**Comment by matsrand** [comment]
No, the options for Norway are:
- Norsk bokmål (where I can select between "Norge" or "Svalbard og Jan Mayen" even though they write the same language there as on the mainland)
- Nynorsk
