### ISSUE TITLE
[Bug | UX] Scrolling "the sky" on maximum tilt makes map jump tens of kilometers

### ISSUE THREAD

**Issue by Atrate** [westnordost/StreetComplete#1932]
Scrolling the screen above the horizon line in tilted mode makes the map jump by tens/hundreds of kilometers.

**How to Reproduce**

 - Tilt the map to the max using two fingers
 - Try scrolling the map above the horizon line
 - End up in a neighbouring country

**Versions affected**

v21.0, compiled from latest master (7e6b88981d726c6ca7553583029fd4589a29af24)

**Comment by westnordost** [comment]
Well, not really a bug. It would be solved by not allowing such an extreme tilt. However, it is not possible in tangram-es to set a maximum tilt and not trivial to implement a maximum tilt "on top" of tangram-es.
