### ISSUE TITLE
Small patches of water look funny. (Ponds, Pools)

### ISSUE THREAD

**Issue by dreua** [westnordost/StreetComplete#1934]
Small patches of water are odd shaped. All water areas have a wave-like animation at the border, is that a bug or a feature? 

**How to Reproduce**

Look at an area with ponds or pools. Try "rich" housing areas, your public swimming pool or ponds.
Happens in both day and night color mode.

**Versions affected**
Android 7.1.1
StretComplete v21.0

![photo_2020-06-30_16-21-44](https://user-images.githubusercontent.com/15114715/86137651-cc8c8c80-baed-11ea-90fb-801dabf384d4.jpg)

**Comment by westnordost** [comment]
It's a feature. Though what you see here is a side-effect of that animation.

It would be possible to replace the water border animation with a pattern like this: https://www.maptiler.com/maps/#bright//vector/14.11/9.05128/53.89519
But I think the animation is nicer.

**Comment by matkoniecz** [comment]
Is it possible to remove it for very small ones?

**Comment by westnordost** [comment]
I don't think so

**Comment by westnordost** [comment]
So this is a will not fix then.
