### ISSUE TITLE
Add a simple way to get a position out of SC as an OSM URL

### ISSUE THREAD

**Issue by peternewman** [westnordost/StreetComplete#1935]
> Is there a simple way to get a position out of SC for issues like this? I know you can press, but that only has add a note or open in another app with no way to extract it.

If you have the editor vespucci installed, you get there an "open on osm.org" in the list. This url you can copy in the browser

_Originally posted by @HolgerJeromin in https://github.com/westnordost/StreetComplete/issues/1927#issuecomment-652214570_

Could we have another option in the press and hold menu, or add a similar option to what vespucci offers?

**Comment by westnordost** [comment]
If something like what vespucci offers would be implemented, then you'd have two entries with "open on osm.org". This is proof that an option of this form doesn't really belong in any particular application (other than a theoretical "OpenStreetMap" app).

So what is the use case to share the location?

**Comment by peternewman** [comment]
> If something like what vespucci offers would be implemented, then you'd have two entries with "open on osm.org". This is proof that an option of this form doesn't really belong in any particular application (other than a theoretical "OpenStreetMap" app).

Agreed entirely. Although adding it as a proper shortcut on the press, rather than within the open in another app menu would avoid the duplication.

> So what is the use case to share the location?

To assist with raising issues on GitHub and sharing example locations (hence why I initially asked in #1972).

I did initially think about proposing a report a bug type thing, but I suspect that would get spammed with too much that was actually notes, and I'd rather do as much as I can on GitHub proper on a real keyboard.

TBH I also use SC as my main nav when wandering around (given I'm filling in quests too; although it's got a bit harder with the new tile provider with less detail), so being able to send location links to people would be good too.

**Comment by westnordost** [comment]
Hm, I wouldn't want to litter the main interface with something that is mostly only meaningful to report bugs. At the same time, adding it automatically to a bug report infringes on the privacy of the user.

So far, it was always easily possible to derive a location from the address the person with the problem stated. Let's stick with addresses.

**Comment by peternewman** [comment]
> Hm, I wouldn't want to litter the main interface with something that is mostly only meaningful to report bugs. At the same time, adding it automatically to a bug report infringes on the privacy of the user.

Personally I don't really feel like adding an entry to a press and hold menu which only has two things is cluttering the interface (given it's mostly invisible) it would just need to be "Copy Location". I'd agree adding it automatically wouldn't be great.
 
> So far, it was always easily possible to derive a location from the address the person with the problem stated. Let's stick with addresses.

Every time I've been asked for locations ( https://github.com/westnordost/StreetComplete/pull/1908#issue-437334580 , https://github.com/westnordost/StreetComplete/issues/1927 the latter has three or four demos).

From the address perspective, I'd have said the street name and not been sure what level of detail for the town/city is needed (indeed one I've just tried didn't work off the bat). Does that mean I have to fire up OSM and confirm my report is sufficient? For another it was a building, there's no efficient way to describe that in text (the four building from the North end on the East side of Foo Street). Surely like all developers you want good bug reports @westnordost and me being able to say https://www.openstreetmap.org/search?query=london#map=19/51.50760/-0.12765 must be infinitely better than "London". That feels like it's proved my point quite well by accident, do I mean "Trafalgar Square" the road, or the square (if so which part of it).

**Comment by westnordost** [comment]
Well, I am the one who takes the bug reports. If I really needed this, I'd certainly add it for my own convenience.
