### ISSUE TITLE
roof/building material/colour

### ISSUE THREAD

**Issue by arne182** [westnordost/StreetComplete#1937]
### General
https://wiki.openstreetmap.org/wiki/Key:building:colour
https://wiki.openstreetmap.org/wiki/Key:roof:colour
https://wiki.openstreetmap.org/wiki/Key:building:material
https://wiki.openstreetmap.org/wiki/Key:roof:material

### Checklist
Checklist for quest suggestions (see guidelines):
- [x] 🚧 To be added tag is established and has a useful purpose. This will add depth and colour to the 3d representation of maps  (https://demo.f4map.com/#lat=53.0756263&lon=8.8029777&zoom=17&camera.theta=59.324&camera.phi=-28.648)
- [x] 🤔 Any answer the user can give must have an equivalent tagging (Quest should not reappear to other users when solved by one)
- [x] 🐿️ Easily answerable by everyone from the outside but a survey is necessary 
- [x] 💤 Not an overwhelming percentage of elements have the same answer (No spam)
- [x] 🕓 Applies to a reasonable number of elements (Worth the effort)

### Ideas for implementation
Either a swatch for the colours or a colour average from a photo which gets added as a hex value. The roof material and building material are all already in the wiki.

**Proposed GUI:**

**Comment by matkoniecz** [comment]
See #1358

**Comment by arne182** [comment]
Thanks.
