### ISSUE TITLE
Restaurant cuisine

### ISSUE THREAD

**Issue by FloEdelmann** [westnordost/StreetComplete#1938]
### General
Affected tag(s) to be modified/added: [cuisine=*](https://wiki.openstreetmap.org/wiki/Key:cuisine)
Question asked: **Which cuisine does XY offer?**

### Checklist
Checklist for quest suggestions (see guidelines):
- [x] 🚧 To be added tag is established and has a useful purpose
- [x] 🤔 Any answer the user can give must have an equivalent tagging (Quest should not reappear to other users when solved by one)
- [x] 🐿️ Easily answerable by everyone from the outside but a survey is necessary 
- [x] 💤 Not an overwhelming percentage of elements have the same answer (No spam)
- [x] 🕓 Applies to a reasonable number of elements (Worth the effort)

### Ideas for implementation

**Element selection:**
 * amenity=cafe
 * amenity=fast_food
 * amenity=restaurant
 * diet=*

**Metadata needed:** 

**Proposed GUI:**

**Comment by matkoniecz** [comment]
The tricky issue is that one would need to find list of cuisine values sufficient to answer in nearly all cases.

And at the same time this list would need to include values understandable to people in general, and would need to not be extremely long and must not be confusing.

Not sure is it doable.

What worse there are classifications in many directions at once - "japanese" and "burger".

**Comment by matkoniecz** [comment]
If "select values from list" would be an acceptable GUI and someone would prepare list of values + matching images then implementation should be relatively easy.

So

1) is "select values from list" a viable interface?
2) is it even possible to have list of values of a decent coverage without having list with 267 million values?
3) what is the meaning of multiple values? Is `japanese;burger` meaning "Japanese cuisine and burgers" or "Japanese burgers"? Or is there no consistency here?
4) Is cuisine tag usable one or is it needed to reinvent trading from scratch here?
5) If nothing else is a blocker - then what would be list of necessary values? How would it differ between various countries?
6) if image list interface world be used - images on suitable licences are needed for each entry (ones from Wikimedia Commons are suitable)

If image list interface is ok interface and everything else is resolved then implementation is relatively easy - I would almost certainly would do that (with disclaimer that I may be more busy in say 2021 or 2022). But it is not the hard part.

Disclaimer: I would wait for @westnordost to say what he thinks about this quest, maybe it has some issues that I failed to notice

**Comment by matkoniecz** [comment]
Damnit, it is #103

So it is apparently greenlit by @westnordost - things that I mentioned above are still needed (at least if I would be doing the programming part)

**Comment by FloEdelmann** [comment]
> it is duplicate of #103

Oh, seems like I haven't looked well enough. I'm going to close this then and add the information to #103.

**Comment by smichel17** [comment]
@FloEdelmann If you searched for duplicates, please also add any keywords you searched for to that issue so others can find it more easily in the future :)
