### ISSUE TITLE
Explain quests in a help dialog 

### ISSUE THREAD

**Issue by HolgerJeromin** [westnordost/StreetComplete#194]
In my home town I had very few quests about buildings. I checked the osm ways and guessed that they are not asked for building=yes

Perhaps every quest should get a human readable explanation of the overpass api call.

**Comment by HolgerJeromin** [comment]
I just found the list for this quest in #109 :-)

**Comment by westnordost** [comment]
Or you look into the source:

https://github.com/westnordost/StreetComplete/blob/master/app/src/main/java/de/westnordost/streetcomplete/quests/building_levels/AddBuildingLevels.java#L21-L29

> Perhaps every quest should get a human readable explanation of the overpass api call.
But no, won't do that.

**Comment by HolgerJeromin** [comment]
This makes the app a Blackbox for most users. :-(

But this is your decision.
