### ISSUE TITLE
More options like adding notes. Add Trees/Street Lamps

### ISSUE THREAD

**Issue by arne182** [westnordost/StreetComplete#1945]
**Use case**
Adding Trees to OSM

**Proposed Solution**
Similar to adding a note to the map make the option available to add a tree at that location. Maybe even a street lamp

**Comment by westnordost** [comment]
For adding things, you should try out this app: https://play.google.com/store/apps/details?id=fr.dogeo.osmgo
And then of course there is Vespucci, but there is a learning curve.

This will not be added to StreetComplete. One (good) reason is, that you can't see the trees on the StreetComplete map that are already there (and also not the bins, the park benches, the street lamps, not even the shops and amenities etc). So the user has no chance to check if something already exists or not.
