### ISSUE TITLE
Quest stays dot even at highest zoom

### ISSUE THREAD

**Issue by arne182** [westnordost/StreetComplete#1946]
**How to Reproduce**

**Versions affected**

**Comment by arne182** [comment]
48.172537,9.870081
![Screenshot_20200711-115524_Street­Complete](https://user-images.githubusercontent.com/844102/87221713-6b2ab000-c36e-11ea-850e-9fd362621102.jpg)

**Comment by matkoniecz** [comment]
#1927, I am trying to fix it

**Comment by westnordost** [comment]
Though we have problems to reproduce this issue. Maybe you can help in #1927:
1. You can disable the quests one by one in the settings. Which are the minimum quests enabled for which tis is reproducible?
2. Also reproducible after restart of the app? Also reproducible after new fresh install of the app?

**Comment by arne182** [comment]
It is reproducibile. With three quests enabled.  
What surface does the road have? No longer a point.
What kind of building is this? Still available
Is the stretch of road lit? Becomes a dot

**Comment by westnordost** [comment]
What do you mean with no longer a point?

**Comment by arne182** [comment]
Even with just 2 road lit and surface quest on. It changes to a dot.

**Comment by westnordost** [comment]
Okay, so it looks like road lit and surface quest block each other and none is shown as result(?)

So if only road lit is activated, it is not a dot?

**Comment by arne182** [comment]
![Screenshot_20200711-140406_Street­Complete](https://user-images.githubusercontent.com/844102/87223738-9a95e880-c37f-11ea-8aaf-1d71251d0b7b.jpg)
![Uploading Screenshot_20200711-140512_Street­Complete.jpg…]()

**Comment by arne182** [comment]
![Screenshot_20200711-140512_Street­Complete](https://user-images.githubusercontent.com/844102/87223761-c913c380-c37f-11ea-8c51-72731a8dec85.jpg)

**Comment by arne182** [comment]
Exactly. The dot becomes a quest when the street lit quest is off

**Comment by arne182** [comment]
Could it be that the way is too small?

**Comment by westnordost** [comment]
No, the length of the way does not matter.
