### ISSUE TITLE
Add keywords to the Notes quest

### ISSUE THREAD

**Issue by Identitaet** [westnordost/StreetComplete#1948]
**Use case**
Add more notes especially ones asking **what** is here

**Proposed Solution**
Just like looking for the different question mark we should also look for specific key words indicating questions 
This would ideally incloude local versions of what like `was, welches` for german but given that I'm unsure if this is easily implementable using only the english what would be a good start

**Comment by westnordost** [comment]
Not sure if I understand. "was" could be used in any context in German, not only mostly questions.

If you like to see all the notes, even those not phrased as questions, there is an option for that in the settings.

**Comment by Identitaet** [comment]
1. I meant something like 'Was ist die Anzahl der Spuren hier' just as an example.
2. Oh I didn't know that thanks (feel free to close this issue)

**Comment by westnordost** [comment]
Ok I'll close it then
