### ISSUE TITLE
Deletion of Notes Photos

### ISSUE THREAD

**Issue by arne182** [westnordost/StreetComplete#1949]
I sadly got a car's registration plate on this photo. 
https://westnordost.de/p/15620.jpg
Would it be possible to delete it?

**Comment by arne182** [comment]
These two as well if possible
https://westnordost.de/p/15656.jpg
https://westnordost.de/p/15615.jpg
Thanks

**Comment by westnordost** [comment]
The photo is deleted a short time after the note is closed. To delete the photo, you close note.

**Comment by Helium314** [comment]
Actually this information might be useful to have when creating a note.
Maybe you could add something like "The photo will be deleted a short time after the note is closed" to the photo upload.

**Comment by arne182** [comment]
Will this work even if the note has been manually deleted by OSM?

**Comment by westnordost** [comment]
You mean by an administrator? It should, if not, it is a bug.

**Comment by arne182** [comment]
Yes. The admins deleted the note completely. Let us see in a few days if it also gets deleted on your end

**Comment by arne182** [comment]
One week has past and still the photos are available.

**Comment by Atrate** [comment]
Maybe it would be possible for SC to automatically blur faces/license plates or allow the user to blur them manually?

**Comment by westnordost** [comment]
Ok, something was stuck. I refactored the server-side code and ran the clean-up job again manually

**Comment by westnordost** [comment]
There were over 13000 pictures on the server, after clean-up, only about 4000 are left.

**Comment by arne182** [comment]
Thanks
