### ISSUE TITLE
Encourage users to come back

### ISSUE THREAD

**Issue by rugk** [westnordost/StreetComplete#195]
I admit this is going to be a controversial approach and a bit like an anti-pattern for some users, so make it optional in any case.

### So what?
I think the app could regularly show a notification to encourage users to use the app again, if it has not been used for some time (a week, maybe?).

### Why?
* Users may forget that they have the app installed.
* Users may be lazy not opening the app.
* User may not think about the app when there is actually a good place to map where they are.
* Users may not notice they have not used the app for a while.
* User may have tried out the app once (maybe even liked it), but are not the types of people constantly opening all apps and doing that again
* nowadays, user often have many apps, so this app can get lost in the shuffle
* If they really do not want to use the app anymore (which is a synonym to contribute to OSM here), they'll uninstall it anyway, so by installing the app they already confirm their interest in this.
If it is optional (but opt-out IMHO) they can also just disable it if they think the app patronizes them. However, as explained, the user is actually interesting in doing the thing the app encourages the user.

### How?
Of course we should keep the notifications to a minimum and not scare them away saying "this app annoys me, I uninstalled it.". That's why:
* it must not be shown when the user already actively uses the app
* it could maybe already do a background scan for quests and pick out a nice one near the user making it interesting to solve the quest
* it should be very clear about why it is notifying the user, e.g. say: "Hey, you have not used StreetComplete for XY days, but I have an interesting quest (about XY/named/…) here for you. Do you want to solve it?"
* or it somehow uses the stars ("Only XY starts to get to 1000!"), although this may be criticised as too much gamification

## Background
This can of course also be seen as a part of the gamification, however, of course, this is a technique many nasty (game) apps (or so) employ too - to quite some success. We, however, here have legitimate reasons (helping keeping OSM contributions).
The app may already be a good thing to attract new OSM contributors and I think this is also somehow the aim of @westnordost, that's why I've also proposed https://github.com/westnordost/StreetComplete/issues/178, but the further steps are:
* keeping them (this issue)
* getting them to get more encouraged with OSM in general (ideas in https://github.com/westnordost/StreetComplete/issues/178#issuecomment-299734982)

I don't know if this app could have such a "problem" with many users not actively using it – we would need statistics for it, which we don't have (or maybe we have with install count or so?), but this idea won't hurt if implemented responsibly.

**Comment by westnordost** [comment]
Personally, I despise behavior like this. It might be a matter of taste, but it would certainly put me off. And since I am the one who programs this app, my taste is what counts :-P
Sorry, I won't implement this.

What I will implement at some point is to provide an option for the user to turn on notifications that inform him about that quests are in the vicinity. However, he will be in control.

**Comment by rugk** [comment]
> However, he will be in control.

Hey, hey, have you read my whole post? I repeately said, it should be optional, so the user will always be in control. Also the big "Why?" part should explain why to do it and the "How?" part how it does not put one off and respect all user privacy and so on.

**Comment by westnordost** [comment]
Yes, I read the whole post.

Sorry for discarding this ideas so quickly after you put so much effort into nicely writing up the rationale. I can follow you there and the reasons you give make sense, but this really is a no go for me. No amount of "being cautious about it" will fix that for me, as soon as I see one notification, it is game over for that app, right in the trash.

**Comment by rugk** [comment]
Well… the challenge would be to make a notification you immediately agree to. :wink: 
But, okay, I understand your reason very well… I also somehow expected this, but I had to throw the idea into here… It was worth it. And unless many users comment here wanting it, I'll better forget it. :wink:

**Comment by Hillside502** [comment]
@westnordost 
"despise"?

**Comment by rugk** [comment]
[Yeah, why not](https://www.macmillandictionary.com/dictionary/british/despise)? He dislikes such notifications/behaviour. Not me, of course… :smile: (hopefully :wink: )
