### ISSUE TITLE
Allow to specify that split ways qualify for quest

### ISSUE THREAD

**Issue by matkoniecz** [westnordost/StreetComplete#1950]
**Use case**
I am testing parking lane quest (that is not generated for ways near `amenity=parking` and therefore not triggerable without overpass query).

Currently on splitting ways with parking lane quest none will get parking lane quest.

And one needs to wait until rescan happens or flush cache.

I want to add special property "afterSplitAllWaysQualifyForThisQuest".

**Proposed Solution**
No idea, but I will look for it if it is not rejected.

Not sure whatever any of current quest would benefit from that, probably not.

**Comment by westnordost** [comment]
How should that work, technically? I don't think this is (easily) possible.

After all, not every split way should receive this quest, right?

**Comment by matkoniecz** [comment]
In this case, every way that had parking lane quest and splitting was used as an answer will produce 2 or more ways.

All such ways should receive parking lane quest.

Splitting used as solution of other quests should not result in creation of parking lane quests.

No idea whatever it is implementable in a sane way.

**Comment by westnordost** [comment]
Hmm, actually I think it might. `SplitWaysUploader:uploadSingle` uploads a single split way and knows the quest type. It could be hacked in there somewhere...

**Comment by westnordost** [comment]
I'll do it

**Comment by matkoniecz** [comment]
Done by #1951
