### ISSUE TITLE
Width of cycle paths

### ISSUE THREAD

**Issue by jonpsp** [westnordost/StreetComplete#1956]
### General
Affected tag(s) to be modified/added: [cycleway:width](https://wiki.openstreetmap.org/wiki/Key:)
Question asked: **How wide is the path available to cyclists in metres?**
Applies to highway=cycleway and to highway=footway/path where bicycle=yes/permissive/designated. 
The full width of a path may not be available to cyclists (eg if segregated, or if the path has barriers), hence the cycleway:width tag being separate to the width tag. 
Note that the question should not be asked if the way already has the similar tag cycleway:est_width. 

### Checklist
Checklist for quest suggestions (see guidelines):
- [x] 🚧 To be added tag is established and has a useful purpose - wide cycle paths allow overtaking, and reduce conflict with pedestrians if shared use. Narrow cycle paths lead to slow journeys and difficulty avoiding dogs
- [x] 🤔 Any answer the user can give must have an equivalent tagging (Quest should not reappear to other users when solved by one) - the answer is a value in metres
- [x] 🐿️ Easily answerable by everyone from the outside but a survey is necessary - if necessary, use your feet to measure it, then convert to metres
- [ ] 💤 Not an overwhelming percentage of elements have the same answer (No spam) - not meaningful for this tag
- [x] 🕓 Applies to a reasonable number of elements (Worth the effort)

### Ideas for implementation

**Element selection:** 

**Metadata needed:** 

**Proposed GUI:**

**Comment by matkoniecz** [comment]
see #698
