### ISSUE TITLE
Set position manually

### ISSUE THREAD

**Issue by giambr1** [westnordost/StreetComplete#1957]
**Use case**

Easily search for a quest near a specific point on the map.

**Proposed Solution**

A "manual" mode where to select the "default" position. Maybe using an address or coordinates.

**Personal comments**
"Easly" means that I do not have to navigate the map to reach a specific location.
I did not find a similar issue. I hope this is not a duplicate.

**Comment by HolgerJeromin** [comment]
You can use the website osm.org or osmand and call streetcomplete with share/geo

**Comment by giambr1** [comment]
Really appreciate your answer. Should I understand it as "there is no need to add this feature"?

**Comment by westnordost** [comment]
Maybe there is a misunderstanding. By default, the app searches for quests in your vicinity automatically. But you can in fact also search for quests somewhere else as well. Just pan the map to the location where you want to search for quests, open the menu and tap "Search for quests here".

**Comment by giambr1** [comment]
Hi! My request concerns your last sentence. 

Actually, I am already using the method you suggest. Instead, I was wandering if you are interested in adding the possibilty to search for a specific place and directly "jump" there. Maybe I can make myself clear by means of an example.

How I have to do it:
My deafult position is A. Now, I want to search for quests near B. Unfortunately, I do not know the exact position of B on the map. I know that B is just above C, so I zoom out and zoom in near C. Then, after a couple of minutes I find B. Fine, now I search for quests.

How I'd like to do it:
I type B in a "search bar". The map "moves" to B by itself. I search for quests.

I hope my point is clear now. If the request doesn't make sense, I will close the issue. 

Thanks

**Comment by westnordost** [comment]
I actually already implemented a geocoding-search recently https://github.com/westnordost/Luftlinie/tree/master/app/src/main/java/de/westnordost/luftlinie/geocoding , so if I planned to include it, I'd probably take most of the code from there. I decided against having this in the app for now mostly because there is no good place in the UI to put it so that it is not obstrusive.

However, when/if I implement a prepare-offline-mode (downloading quests **and map** for offline use and managing it), there is space to include that. So for now, will not fix / see @HolgerJeromin , but may come in the future.

**Comment by HolgerJeromin** [comment]
>  I decided against having this in the app for now mostly because there is no good place in the UI to put it so that it is not obstrusive.

In the menu under
"🔍 search here for quests" add
"🔍 search elsewhere for quests"

**Comment by harry-wg** [comment]
> when/if I implement a prepare-offline-mode (downloading quests **and map** for offline use

It seems you have already implemented the offline mode (and that itself was working well in my short test yesterday, so perhaps you can consider including that now?

Although I found no problem visually panning to a place near home that I know well, visually panning to a more distant place that I don't know took about 10 minutes to find. So, the offline mode really does need a better way to choose the location.
