### ISSUE TITLE
Make it easier to contribute quest types

### ISSUE THREAD

**Issue by rugk** [westnordost/StreetComplete#196]
From https://github.com/westnordost/StreetComplete/issues/192#issuecomment-299730451 I see how it can be useful to make it possible for contributors to add easy quests **without coding**. That's very important and can be a good argument to find contributors.
The aim could be to get it working as in [HTTPS Everywhere](https://github.com/EFForg/https-everywhere/), where you have many, many contributors adding XML files.

So what could be covered?
* Simple yes/no questions. (https://github.com/westnordost/StreetComplete/issues/107, e.g.)
* A generic image.
* Simple questions with text input connected to a tag.

How?
Your decision: JSON, XML, …
The only thing I'd suggest is to put one new quest type into a new file, so we won't have crazy big files, disputes how to sort/order entries or maybe even merge conflicts.

Also:
* A guide or a small tool making it even easier to create a quest.
* Example quests. (or just in the guide if it is easy)
* A very clear explanation what quests are wanted and what not. And maybe suggest to open an issue before, so one can check whether it is wanted first.

**Comment by matkoniecz** [comment]
I would expect that with yes/no quests that have all assets prepared, including quest icon, prepared question and overpass query somebody will soon make pr.

**Comment by westnordost** [comment]
#98

**Comment by rugk** [comment]
Ah, okay, I'd not call this a "plugin", but yeah… I'll post it there.
