### ISSUE TITLE
Position marker sometimes showing in the wrong direction

### ISSUE THREAD

**Issue by cyclingcat** [westnordost/StreetComplete#1960]
Hi,

today I noticed that the position marker sometimes shows in the wrong direction! See the following screenshots:

This one is correct, my current location lies in the south of the displayed map section and the position marker at the bottom points in this direction:

![correct](https://user-images.githubusercontent.com/32601012/87760790-9864db80-c810-11ea-8c5a-2c79f10778a8.png)

Now I pan the map **_a very little bit_** downwards and the position marker suddenly jumps to the top left corner of the screen, pointing in the opposite direction:

![incorrect](https://user-images.githubusercontent.com/32601012/87760888-cd712e00-c810-11ea-968b-4ba88d34b82a.png)

If I undo above panning (the same very short distance), the marker jumps to the correct position again. It seems as it there is some miscalculation of the marker position in some cases.

(StreetComplete 20.2 on Android 9.)

The cycling cat

**Comment by Helium314** [comment]
this is the same as #1842
in 21.1 the pin disappears instead of pointing to the wring direction

**Comment by cyclingcat** [comment]
Indeed, this one looks very similar although I didn't zoom but just pan the map.

The cycling cat
