### ISSUE TITLE
The pin to make notes is missing

### ISSUE THREAD

**Issue by hmartink** [westnordost/StreetComplete#1962]
I was on vacation and spotted several places where I would have liked to make notes; however, the note taking pin is gone and I was unable to position any notes. Sometimes notes can be added as alternative (e.g. if you cannot answer a question at all), but e.g. when noticing missing buildings or other incorrect (but not asked) issues, the note pin is necessary.

Could you readd the note pin? It is really needed and useful.

The version is the one prior to todays update.

**Comment by HolgerJeromin** [comment]
It was moved to the long tab on the map menu.

**Comment by hmartink** [comment]
I just double checked. In the map menu (you mean the circle with three horizontal bars?) I can see "My profile", "Settings" and "About", and below: "Search for quests here" (translated back from German). 

I checked all four menu options, but neither allowed me to make a note.

In the "map menu" there is a vacant spot, should this appear there?

**Comment by HolgerJeromin** [comment]
I meant "long tab on the map".

**Comment by hmartink** [comment]
Ok, this works, but as users of previous versions it was not obvious to me.

**Comment by westnordost** [comment]
Yes, this is intentional
