### ISSUE TITLE
Asking for type of parking spot but not for fees

### ISSUE THREAD

**Issue by hmartink** [westnordost/StreetComplete#1963]
I was asked several times for parking spots and provided the type (and sometimes the layout, e.g. on ground or parking building) but was *never* asked if fees are collected. Is this intended? This question is trivially to answer and I expect most usefull to users.

The version is the one prior to todays update.

**Comment by matkoniecz** [comment]
Maybe it is already tagged in your region? Or maybe there are there are yet-to-be-solved quests? Or maybe quest is not shown because you have old version where dots are bugged?

Can you link specific public parking lot where this quest is not asked?

**Comment by hmartink** [comment]
I was on vacation and lots of meta data was missing in the area and I was *never* asked for the parking fee, that's why I'm reporting this.

An example (but I can give you several others) is 54.44097, 12.71672

However, it could be because of the dots bug, I did not check that on site.

**Comment by matkoniecz** [comment]
https://www.openstreetmap.org/way/319134362#map=19/54.44097/12.71685 - fee quest is not asked for `access=private` parkings.

Can you link specific parking lots accessible to general public, tagged as accessible to general public where this quest is not asked?

**Comment by hmartink** [comment]
I tagged quite a few parking spots in that area, however, I'm not sure which exactly. I think I tagged 54.43727, 12.68318 and 54.43711, 12.68331. Is there an easy way to show who tagged parking spots?

**Comment by matkoniecz** [comment]
https://wiki.openstreetmap.org/wiki/StreetComplete/Quests has overpass turbo links of eligible objects. In this regions just fee parkings qualify - see https://overpass-turbo.eu/s/WeK (click run to run query, interface may be broken on small screens)

Plenty of parkings are with already tagged fee - see https://overpass-turbo.eu/s/WeL

**Comment by westnordost** [comment]
Ok, sounds like this is invalid then.
