### ISSUE TITLE
Questions are not shown

### ISSUE THREAD

**Issue by hmartink** [westnordost/StreetComplete#1964]
I was on vacation and this bug made working very frustrating at times. Some quest are marked in StreetComplete as little bulltets, but the corresponding questions are never shown. I zoomed in and out, sometimes this helped (e.g. when zooming out some questions appeared), sometimes I could see it very briefly while zooming, but usually I could not reach the quest. I could expect what it was, but I was not able to answer. I can provide you location details of examples if this helps tracking it down.

The version is the one prior to todays update.

**Comment by matkoniecz** [comment]
> The version is the one prior to todays update.

And it is fixed in the latest update. See #1927 for details.

**Comment by hmartink** [comment]
Great to know that this is fixed. Sorry, I did not read the announcement in detail before reporting.
