### ISSUE TITLE
Gamifikation without use?

### ISSUE THREAD

**Issue by hmartink** [westnordost/StreetComplete#1965]
The apps becomes more and more gameified. I don't know if this is actually helpful, I usually find it distracting when entering lots of information. Of course, having some feedback gives a nice feeling. But I would rather get some useful feedback and not big graphics. E.g. quite a bit of information I enter I cannot read out, e.g. the number of parking spots for bikes or (whoever needs this) the types of plants, but also opening times etc. are not visible on maps.openstreetmap.org nor www.openrouteservice.org. So giving pointers how to use the information entered would be more helpful then big graphics (ideally with links which could be opended immmediately).

Also the bell is often there (but not always) even if no score has been reached, tapping on it does not make a difference. Is this intended?

The version is the one prior to todays update.

**Comment by westnordost** [comment]
Yes, the bell was a bug.

Achievements sometimes contain links to things that do exactly what you ask for, showcase how that information is used.
