### ISSUE TITLE
Please always show house numbers

### ISSUE THREAD

**Issue by hmartink** [westnordost/StreetComplete#1968]
I was on vacation and lots of house information was missing. Sometimes the orientation was not immediately clear to me and the GPS signal is not too precise always as well. Some buildings show the house number by default, which makes it easy to locate (and enter the right building information), but quite often the house number is not shown. It is there, because when I tap on the building quest to enter e.g. the number of stories or the type of the building, the question mentiones the house number. If I intended to enter the building besides this one, I have to abort the entry and select the desired one, which is frustrating (it takes time). A practical example is if I'm in a queue (e.g. in front of a building, which happens frequently in these times) and I'm able to see one building well (or the opening times). But if taping takes time, the queue might move on and I'm no longer able to enter the information.

The version is the one prior to todays update.

**Comment by matkoniecz** [comment]
See https://github.com/westnordost/StreetComplete/issues/1939 ( https://github.com/westnordost/StreetComplete/issues?q=is%3Aissue+house+is%3Aclosed ) and https://github.com/ENT8R/streetcomplete-mapstyle/issues/82

This one is upstream issue and fixing requires action by hoster of map tiles or changing hoster of map tiles.

**Comment by hmartink** [comment]
Sorry, I looked through all issues but obviously missed this. Should this be merged?

**Comment by matkoniecz** [comment]
> Should this be merged?

It can be just closed (it gets linked automatically). If there is any new info you can post it there.

**Comment by smichel17** [comment]
> Sorry, I looked through all issues but obviously missed this.

If you searched but didn't find the duplicate issue, it can be helpful to comment on that issue with the keywords you searched for, so others coming after might find it more easily.
