### ISSUE TITLE
see all quests for each feature at the same time

### ISSUE THREAD

**Issue by andrewharvey** [westnordost/StreetComplete#1970]
**Use case**
While it may make it more complicated, I'd like to see all quests available on a feature so I can pick which one to answer. Currently one one is shown at a time and the next one won't appear until after completing and uploading.

**Comment by andrewharvey** [comment]
similar to #1463

**Comment by matkoniecz** [comment]
Covered by #124 - it is basically in state of "nice feature, valid request, someone would need to implement it". And this is a bit complicated and probably not the best way to start making changes in this program.

**Comment by andrewharvey** [comment]
I didn't see #124, it's close enough so I'll close here.
