### ISSUE TITLE
Clarify wording for highway=service

### ISSUE THREAD

**Issue by creideiki** [westnordost/StreetComplete#1972]
In my area, there are a lot of service roads in business parks, hospital and university campuses, etc. These are often tagged as `highway=unclassified`, `source=Bing`, generating a quest of "What is the name of this road?". While I had found "Other answers..." -> "It has no name...", I did not feel that any of the options fit.

When I searched through the GitHub issues to find if anyone else had reported difficulties, I found https://github.com/westnordost/StreetComplete/issues/1274#issuecomment-441545707 which implied it was possible to tag roads as `highway=service`, but not exactly how (I am not going to trust a two year old report on the order of UI elements). It was not until I searched the source code that I could confirm that I should have selected "It is something like a drive or parking aisle".

In my mind, the difference between a driveway and a wide road between industrial buildings where two fully-loaded lorries can easily pass is large enough that I never considered they could both refer to the same `highway=service` tag. I think the wording of the option should be changed to better imply [all the things the OpenStreetMap wiki says are `highway=service`](https://wiki.openstreetmap.org/wiki/Tag:highway%3Dservice).

This, of course, immediately brings up the question of what it should be changed to. There is very little space in the UI for the description to be any longer, and the terms "service road" and "access road" are [already overloaded](https://en.wikipedia.org/wiki/Frontage_road). I'll suggest the clunky "It provides access to something like parking or a business", in the hope that it offends someone into coming up with something better.

**Comment by smichel17** [comment]
Maybe related discussion: https://github.com/westnordost/StreetComplete/issues/756

**Comment by westnordost** [comment]
I think your suggested wording would be an improvement. However, since each and every string is translated to a big number of languages, let's first try to find the best possible wording. If I remember correctly, the wording was already tweaked once.

So, are there any more suggestions?

**Comment by westnordost** [comment]
Particularly, of the suggested text, I am missing a mention of driveways, alleys etc.

Maybe

"It's a driveway, alley or otherwise provides access to a place"

**Comment by westnordost** [comment]
So to be honest neither your suggestion nor mine is an improvement big enough to warrant yet another replacement of the string so far. It's a little better but yeah...

**Comment by westnordost** [comment]
So, closing
