### ISSUE TITLE
Rename "row house" to "row houses"

### ISSUE THREAD

**Issue by FloEdelmann** [westnordost/StreetComplete#1973]
See <https://wiki.openstreetmap.org/wiki/Tag:building%3Dterrace> and https://github.com/westnordost/StreetComplete/issues/1157#issuecomment-413156202:

> Though, note that there is a common misconception regarding row houses: The tag is supposed to be used only if the building outline includes the whole row of houses, not for each and every house within such a row (For that, you'd use building=house.)

We could make this more obvious by renaming the "row house" option to "row houses", like it is done in iD: https://github.com/openstreetmap/iD/blob/v2.18.1/data/presets/presets/building/terrace.json

In German, this would be "Reihenhäuser": https://www.deepl.com/translator#en/de/row%20houses

**Comment by westnordost** [comment]
You are right, let's change this.

**Comment by peternewman** [comment]
I've fixed up the British which had the same singular.

Is it worth also tweaking quest_buildingType_terrace_description to be:
`multiple similar single-family homes in a linear row`

I.e. adding the word multiple, or putting a more explicit note in about the fact it is more than one.

I see the garage one has "Multiple Garages" and "Separate spaces for different owners/tenants".

Would "Multiple terraced houses" be even more explicit?

**Comment by westnordost** [comment]
I think it is explicit enough

**Comment by smichel17** [comment]
> I see the garage one has "Multiple Garages" and "Separate spaces for different owners/tenants".

This was to address a specific confusion/misunderstanding (of mine). See #1720 for context (the discussion in the PR, mostly, or the linked issue if you want a *lot* of context)

**Comment by peternewman** [comment]
> > I see the garage one has "Multiple Garages" and "Separate spaces for different owners/tenants".
> 
> This was to address a specific confusion/misunderstanding (of mine). See #1720 for context (the discussion in the PR, mostly, or the linked issue if you want a _lot_ of context)

I'd made a similar mistake in the past I think and tagged terraced houses as terrace(d|s). In the UK there is a bit of class connotation between detached, semi, terrace, flat, so when I see an individual terraced house on OSM, I still think of it as a terraced house rather than just a house (despite the fact my end of terraced house is equivalent to a semi-detached).

I'll have to double check my tagging and see if I actually miss-tagged any.
