### ISSUE TITLE
Quest: Is there an information display at this bus/tram stop?

### ISSUE THREAD

**Issue by FloEdelmann** [westnordost/StreetComplete#1974]
### General
Affected tag(s) to be modified/added: [passenger_information_display](https://wiki.openstreetmap.org/wiki/Key:passenger_information_display)
Question asked: **Is there an information display at this bus stop?** or **Is there an information display at this tram stop?**

### Checklist
Checklist for quest suggestions (see guidelines):
- [x] 🚧 To be added tag is established and has a useful purpose
- [x] 🤔 Any answer the user can give must have an equivalent tagging (Quest should not reappear to other users when solved by one)
- [x] 🐿️ Easily answerable by everyone from the outside but a survey is necessary 
- [x] 💤 Not an overwhelming percentage of elements have the same answer (No spam)
- [x] 🕓 Applies to a reasonable number of elements (Worth the effort)

### Ideas for implementation

**Element selection:** 
`public_transport = "platform" and !passenger_information_display`

**Proposed GUI:**
Simple Yes/No

### Related

Briefly mentioned in https://github.com/westnordost/StreetComplete/issues/1079#issuecomment-417069812.

**Comment by westnordost** [comment]
On the talk page in the wiki for that tag, there is discussion whether this tag should be deprecated.

**Comment by westnordost** [comment]
So this means that this is blocked until the two state of the two tags is cleared up (which tag to use).

**Comment by matkoniecz** [comment]
I would discuss it first at tagging mailing list (or possibly somewhere else) to establish a clear tag for marking this, before making a quest.

Note - this person will not be me, but it can be you, whoever you are reading this. If you have trouble with how to post to tagging mailing list I can help.

**Comment by westnordost** [comment]
Right, so I will close this because this needs to be cleared up first. No reason to have an open issue lying around here forever if this isn't solved "upstream".
