### ISSUE TITLE
One-way quest description doesn't make sense and can't flag that it's the wrong way round

### ISSUE THREAD

**Issue by peternewman** [westnordost/StreetComplete#1975]
The quest has quest_street_side_puzzle_tutorial but doesn't show any question marks.

Also if a road is one-way, but the direction shown is incorrect, there is no way to fix it (aside from leaving a note)>

**How to Reproduce**
Find a road, e.g. using https://www.westnordost.de/streetcomplete/oneway-data-api/?bbox=-0.1,51.5,0,51.6
E.g. https://www.openstreetmap.org/way/4253833#map=18/51.50275/-0.09008

**Versions affected**
v21.2

**Comment by peternewman** [comment]
![Screenshot_20200721-015220](https://user-images.githubusercontent.com/6216436/88000157-e588cc00-caf4-11ea-8f9a-31e0d742c1a5.png)

**Comment by westnordost** [comment]
Yes, leaving a note, best with a photo is the correct way to solve this case.

The assumption about the direction is derived from actual GPS traces of vehicles that went down that road in the direction indicated. 

Am 21. Juli 2020 02:52:15 MESZ schrieb Peter Newman <notifications@github.com>:
>The quest has quest_street_side_puzzle_tutorial but doesn't show any
>question marks.
>
>Also if a road is one-way, but the direction shown is incorrect, there
>is no way to fix it (aside from leaving a note)>
>
>**How to Reproduce**
>Find a road, e.g. using
>https://www.westnordost.de/streetcomplete/oneway-data-api/?bbox=-0.1,51.5,0,51.6
>E.g. https://www.openstreetmap.org/way/4253833#map=18/51.50275/-0.09008
>
>**Versions affected**
>v21.2

**Comment by westnordost** [comment]
Though I see on the screenshot, the text shouldn't be there, that's a bug.

**Comment by westnordost** [comment]
![Screenshot_1595434657](https://user-images.githubusercontent.com/4661658/88201372-a74ff180-cc47-11ea-8624-e75d98e298f1.png)

**Comment by peternewman** [comment]
Thanks @westnordost . Although that wording to me is crying out for an "Other Answer" of "Yes it's one way but it goes the wrong way", even if it just tells you to leave a note.
