### ISSUE TITLE
Do not ask for a handrail at private steps

### ISSUE THREAD

**Issue by Lukas458** [westnordost/StreetComplete#1976]
Hi,
i saw that for some quests, like adding the surface of a road or a path, private ways get excluded already. But at the moment, this seems not be to be for the handrail quest at highway=steps: https://www.openstreetmap.org/note/2263038

Even though there might be not so many steps that are private, maybe we should exclude steps with access=private/no and foot=private/no from the handrail question?

**Comment by westnordost** [comment]
ok
