### ISSUE TITLE
Contributing quests needed for data related to wheelchair routing 

### ISSUE THREAD

**Issue by svstoll** [westnordost/StreetComplete#1978]
Hi,

For a university project, I'm looking for ways to improve OSM coverage regarding data that is needed for wheelchair routing algorithms such as the one used by [Openrouteservice](https://openrouteservice.org/). Given that the solution should be easy to use and does not require users to have previous OSM knowledge, I think that StreetComplete would be a great place to include such crowdsourcing tasks.

As of now, StreetComplete already has some quests that are relevant for wheelchair routing such as the surface type quests. On top of that, I would like to implement quests for the following things:

* Information about **curb types** on pedestrian crossings (see also #1305)
* **Incline** of ways that are relevant for wheelchair routing (using the smartphone's gyroscope to measure exact values)
* **Width** of sidewalks and other paths that are relevant for wheelchair routing (using Google's ARCore SDK for measuring as recently also suggested in #698)
* **Smoothness** of sidewalks and other paths that are relevant for wheelchair routing (see also #1630)
* Potential **barriers** on sidewalks and other paths that are relevant for wheelchair routing

While all of the involved OSM tags are already well-established, they are not used very often, yet. Hence, there may be a large amount of quests that will be generated until the coverage (hopefully) improves over time. Obviously, there are still other difficulties related to each of the proposed quest types, but I don't think that it makes sense to discuss them in great detail using this general issue.

I mainly opened this thread because I'm interested to know if you have some general feedback regarding the idea and to let you know that I would like to work on these things if you are willing to include such accessibility related quest types in StreetComplete (given proper testing etc.). If this is the case, I will create some more detailed quest proposals according to the contribution guidelines over the next couple of weeks (or continue the discussion on already existing ones).

**Comment by westnordost** [comment]
Hi  @svstoll , that sounds interesting! People contributing (new quests) are always welcome. Thank you also to pitch it first here before opening PRs directly so I and other community members have a chance to comment on your ideas whether it is worth creating an issue/PR for that in the first place.

My general feedback is that of course, quests to improve wheelchair accessibility are very welcome in StreetComplete, because the data collected is inherently useful for at least one purpose (wheelchair accessibility).

> Information about curb types on pedestrian crossings (see also #1305)

Can't say much about it right now, not sure what the state of the ticket #1305 is. If I remember correctly there was some problem with the definition/standardization of kerbs (where they have to be tagged). But it could be that I remember wrong

> Incline of ways that are relevant for wheelchair routing (using the smartphone's gyroscope to measure exact values)

You probably mean accelerometer. The app already uses this sensor, so no new permissions would be necessary, which is good. It might be difficult to find ways that are eligible for asking for the incline. It should only be asked for ramps because for "everything" is too much.
Also, "Put your smartphone on the ground to measure the incline of this dirt path" is maybe something some people wouldn't want to do.

> Width of sidewalks and other paths that are relevant for wheelchair routing (using Google's ARCore SDK for measuring as recently also suggested in #698)

Yes. This is quite high on my priority list as well but you are also welcome to implement it if you like. Though, this by the way means that the app requires a new permission (camera). New permissions always mean that some users will never update the app (or update only after a very long time), so I was thinking that I would implement that quest in the same update I also remove support for devices below Android 5.0. 

> Smoothness of sidewalks and other paths that are relevant for wheelchair routing (see also #1630)

The bigger part of the implementation effort here would be the UI design (both mock ups and final implementation) and art.

> Potential barriers on sidewalks and other paths that are relevant for wheelchair routing

Yes, but this is now how StreetComplete works.

**Comment by svstoll** [comment]
Thank you very much for your immediate feedback!

> You probably mean accelerometer. The app already uses this sensor, so no new permissions would be necessary, which is good. It might be difficult to find ways that are eligible for asking for the incline. It should only be asked for ramps because for "everything" is too much.
Also, "Put your smartphone on the ground to measure the incline of this dirt path" is maybe something some people wouldn't want to do.

Regarding the incline quest, it might be possible to filter overpass turbo query results by using some elevation API such as [Open-Elevation](https://open-elevation.com/) to prevent generating too many quests for ways that are most likely level anyway. Ways whose incline does not necessarily depend on the terrain (such as ramps) could be treated differently though.

I can also see that putting the smartphone on the ground might be a problem sometimes (especially if it is rainy), but somehow there is no way around it if a user does have a specific tool available. Clearly, the quest should make this requirement obvious to the users so that they know about it before visiting the location.

> Yes. This is quite high on my priority list as well but you are also welcome to implement it if you like. Though, this by the way means that the app requires a new permission (camera). New permissions always mean that some users will never update the app (or update only after a very long time), so I was thinking that I would implement that quest in the same update I also remove support for devices below Android 5.0.

For sure, some sort of AR ruler should be implemented in a way that it can be used by different quests and you are right about the need for new permissions. Do you have any plans when you would like to remove support for devices below Android 5.0? Because I would contribute the quests as part of a university project, I only have a limited time frame until development should be completed so that I also have some time for user testing etc. (i.e. around November). However, if that is too early I could do the testing also on a forked version of the project and contribute the code once you are ready for it.

> Yes, but this is not how StreetComplete works.

I know that such a barrier quest is somewhat problematic, because there are no good criteria to filter ways where a barrier could potentially exist and because there are many different values available for this tag. Generating a quest for every relevant way would also be obnoxious, because the answer will typically be always the same. Ideally, apps that offer wheelchair routing should have something similar like the notes feature from StreetComplete so that wheelchair users could report an inaccessible barrier with a picture if their route contains such a barrier.

However, if someone does have an idea how at least some inaccessible barriers could be detected by generating quests, I would welcome your input :)

Given that you welcome the idea in general, I will come up with more detailed proposals for needed quests in the next days/weeks.

**Comment by matkoniecz** [comment]
#1305  was mentioned, but from open quests proposals also #875 #1961 #1850 #1817 #1593 #1487 #398 #279 (requires adaptation of road surface detailing quest, should be simple) seems also related to wheelchair tagging quality.

**Comment by peternewman** [comment]
> > Incline of ways that are relevant for wheelchair routing (using the smartphone's gyroscope to measure exact values)
> 
> You probably mean accelerometer. The app already uses this sensor, so no new permissions would be necessary, which is good. It might be difficult to find ways that are eligible for asking for the incline. It should only be asked for ramps because for "everything" is too much.

For the stuff that isn't correctly tagged as a ramp, what about finding paths that are parallel (i.e. both connect point A and B, and shorter than some distance, where one path is steps). It seems quite likely to me the non-steps one will probably be a ramp, or would hopefully be in enough circumstances to not be spammy.

> Yes. This is quite high on my priority list as well but you are also welcome to implement it if you like. Though, this by the way means that the app requires a new permission (camera). New permissions always mean that some users will never update the app (or update only after a very long time), so I was thinking that I would implement that quest in the same update I also remove support for devices below Android 5.0.

Could you not do the within app/just in time permissions (sorry I don't know the real name for them). So it only asks for the camera position when you open an ARCore quest, and if you say no it can prompt you to disable all those type of quests. For example I (for various reason) have the Instagram app installed, I've never given it camera permissions, but I can browse Instagram if I want, and even upload images taken in the phone camera app. Each time I go to take a photo via Instagram it just prompts me for camera access (which I've so far denied).

**Comment by westnordost** [comment]
> Do you have any plans when you would like to remove support for devices below Android 5.0

I was aiming at some time end of this year.

**Comment by svstoll** [comment]
> #1305 was mentioned, but from open quests proposals also #875 #1961 #1850 #1817 #1593 #1487 #398 #279 (requires adaptation of road surface detailing quest, should be simple) seems also related to wheelchair tagging quality.

@matkoniecz Thanks for bringing these up. I think solving #1593 would be especially important, because the interface that asks about different surface values on each side of a sidewalk would also be needed to ask about the sidewalk width and smoothness. I'll try to include that in my proposals.

Potentially, all the different combinations of possible values (especially on roads with sidewalks) could lead to a lot of cases where a way would need to be split over and over again, because each individual value could be different for a certain segment of the way. However, I guess that this is a problem that already exists in OSM in general and needs some pragmatism.

**Comment by westnordost** [comment]
For recording the surface (and smoothness) for sidewalks tagged on the road, we'd also need to come up with a fitting UI. Should the quest only ask for one side of the road at a time and somehow clearly display for which side it is asking? Or should there be a UI like for the sidewalk-quest, where you define both sides at the same time? If so, how should the graphics for that look like?

**Comment by xuiqzy** [comment]
@westnordost 
Regarding the camera permission for measuring widths: One can limit the requesting of the new permission to devices that support runtime permissions (Android 6+), so no one is forced to accept the new permission when wanting to update the app.
One just has to use `<uses-permission-sdk-23>` instead of the normal `<uses-permission>` for the new permission, see here:
https://developer.android.com/guide/topics/manifest/uses-permission-sdk-23-element

Of course, the quest or the used functionality would also have to be disabled for devices not having the permission either way.

**Comment by westnordost** [comment]
I am closing this because I think your @svstoll question has been answered.
