### ISSUE TITLE
combine quests: "street name of a building" right after "house number"?

### ISSUE THREAD

**Issue by Katzenstreu** [westnordost/StreetComplete#1979]
Hello, 

Would it be possible to ask for the "street name of a building" right after the "house number" was given?  Usually the street name is asked later, the next day.

Best regards
Tim

**Comment by smichel17** [comment]
Do you have auto-sync on? Most quests that depends on a previous quest will not be shown until after the previous quest has been uploaded.

**Comment by matkoniecz** [comment]
> Most quests that depends on a previous quest will not be shown until after the previous quest has been uploaded.

Sadly, for technical reason, `addr:street` is special and just upload is unsufficient.

**Comment by westnordost** [comment]
Will not fix, for technical reasons.
At the point where you answer the house number, the app (likely) doesn't know the names of the streets around the housenumber. Which means, that the UI of tapping on the street it belongs to wouldn't work.
The names of the streets around missing `addr:street` housenumbers are downloaded together with when data necessary for the quest itself is downloaded.
