### ISSUE TITLE
Black/dark mode

### ISSUE THREAD

**Issue by rugk** [westnordost/StreetComplete#198]
Already mentioned in https://github.com/westnordost/StreetComplete/issues/183#issuecomment-299417767, but an issue for that was still missing…

Note:
* a black mode should also be suitable for AMOLED users wanting `#000` as much as possible. This may even have a strong contrast so that these users can use the app at daytime with the screen always-on, but can easily see what matters; thus maybe explicitly call it "AMOLED mode"
* the usual dark mode can be a mode with just some dark grey things and low contrast to be used at night, maybe call it "night mode"

**Comment by westnordost** [comment]
When a custom style is implemented, the color values can be defined at the start as constants and be exchanged. In other words: technically it is possible. but it is blocked by #183. I won't get to that anytime soon but as said, you are invited to busy yourself with that.

**Comment by westnordost** [comment]
Blocked by #183

**Comment by westnordost** [comment]
This black mode should make use of the DayNight base themes, see
https://blog.iamsuleiman.com/daynight-theme-android-tutorial-example/
