### ISSUE TITLE
missing, incorrect or no pictures assigned to a note after upload to OSM

### ISSUE THREAD

**Issue by ironspock** [westnordost/StreetComplete#1981]
1) mobile in offline mode 
2) creating multiple notes including one or two photos assigned to each note
3) connecting to WLAN, uploading answers and taken notes
4) checking in OSM
5) observing issues:
5a) that some of the notes have no photo(s) assigned (refer to 5b)
   (OSM notes 2275126, 2275127, 2275128)
5b) that photo(s) should be assigned to notes as per 5a) are incorrectly assigned to other notes 
    note 2275121: has photo assigned which should belong to note 2275126           
    note 2275122: has photo assigned which should belong to note 2275127
    note 2275124: has photo assigned which should belong to note 2275128
5c) due of 5a) and 5b) missing correct photo(s) of notes as per 5b)
  (OSM notes 2275121, 2275122, 2275124)

**How to Reproduce**

first occurence, will keep in mind and observe

**Versions affected**

 Android 5.1 / StreetComplete 21.1

**Comment by westnordost** [comment]
So there should be 6 photos in 6 notes but there are only 3 photos?

**Comment by westnordost** [comment]
So if I understand this report correctly, all these 6 notes should have photos. But what happened is that 3 of these notes have no photos and those that do actually have the photos of *the other* notes.

I looked at the code, and indeed it is theoretically possible: When a photo is taken, the photo is saved to the file system with a (random) unique name. Each note remembers which temporary photo files are referenced. On upload of the note, this photo file is then also uploaded and after that, deleted. This process only works if the file name of the photo taken is really unique and it can not happen that two photos taken get assigned the same name.

For creating such a file with a unique name, the app uses the platform function [`File.createTempFile`](https://developer.android.com/reference/java/io/File#createTempFile(java.lang.String,%2520java.lang.String)). It is documented as

> Creates a new empty file in the specified directory, using the given prefix and suffix strings to generate its name. If this method returns successfully then it is guaranteed that:
> 1. The file denoted by the returned abstract pathname did not exist before this method was invoked, and
> 2. Neither this method nor any of its variants will return the same abstract pathname again in the current invocation of the virtual machine.

This issue indicates that this may not be true for all versions of Android.

**Comment by westnordost** [comment]
I replaced using `file.createTempFile` with using the current time since 1970 in milliseconds to construct the name of the file. I think it is a fair assumption that no user will be able to create two photos for notes in the same millisecond :-)

**Comment by westnordost** [comment]
In the very initial implementation (v4.0-beta), @ENT8R actually added the date as well to the file name but I think he removed it because I argued that File.createTempFile already guarantees to return files with a unique name.

https://github.com/westnordost/StreetComplete/commit/d28f9420284a8c3f3fcbca7ecd238d10a06e7cd3

**Comment by matkoniecz** [comment]
If someone is both unlucky and changed time on his phone it may be possible to hit it.

**Comment by westnordost** [comment]
Technically, yes... feel free to create a PR to make it infallable (createNewFile returns a boolean whether creating a new file was successful)

Anyway, I can't really believe that the implementation for File.createTempFile is supposed to be broken on a certain Android device and version because that would have a number of other repercussions, but the bug indicates that. So just to be on the safe side, I used an own "unique"-name

**Comment by Atrate** [comment]
Wouldn't it make sense to simply call 
`file.createNewFile` a second time instead of throwing an exception and only throwing it if the second one fails?

**Comment by westnordost** [comment]
With the same logic, I could also try a third time and only throw if it failed after that. Or a fourth, or fifth,...

**Comment by Atrate** [comment]
Wonder what would even lead to that, is it possible for the system clock to freeze?

**Comment by m-rey** [comment]
Create a file, set back the system clock and create a file again with millisecond accuracy to trigger a collision. Technically possible, sure, but really really unlikely.
