### ISSUE TITLE
Quest suggestion: Ask if a street is one-way only (for smaller towns/cities)

### ISSUE THREAD

**Issue by naposm** [westnordost/StreetComplete#1982]
### General
Affected tag(s) to be modified/added: [oneway](https://wiki.openstreetmap.org/wiki/Key:oneway)
Question asked: **Is this road one-way only?**

### Checklist
Checklist for quest suggestions (see guidelines):
- [X] 🚧 To be added tag is established and has a useful purpose
- [X] 🤔 Any answer the user can give must have an equivalent tagging (Quest should not reappear to other users when solved by one)
- [X] 🐿️ Easily answerable by everyone from the outside but a survey is necessary 
- [ ] 💤 Not an overwhelming percentage of elements have the same answer (No spam)
- [X] 🕓 Applies to a reasonable number of elements (Worth the effort)

### Ideas for implementation

The idea is to ask this question for only some roads which don't have a oneway=no tag or oneway=yes tag (the "Assumed to be No" on the iD editor). Its is aimed at surveying small towns or rural areas where OpenStreetMap is not updated or where roads are added only using aerial imagery and no OpenStreetCam/Mapillary support and where there aren't a lot of people contributing.
The problem is that when people add streets from aerial imagery, they do not put the oneway tag so it would be a bit spammy...  To avoid that I would only ask this question for some roads(residential, tertiary and unclassified). 
This would be a spammier but more targeted to small towns version of the "Is this a one-way street?" quest (where data for the quest is not available), so maybe it would be better to put it at the very end of the quest priority and maybe with a different icon.
It would be targeted at tertiary, unclassified and residential road as these are the most common in the smaller towns).
This quest would ask if one of these roads is one-way and add it if the answer is positive (of course the user would select the direction as with the other quests).
The implementation is a bit more difficult than expected, because as far as I know oneway=-1 is discouraged, so there might be needed to reverse the whole way to add oneway=yes

**Element selection:** 
```
/*
This has been generated by the overpass-turbo wizard.
The original search was:
“oneway!=* and (highway=tertiary or highway=unclassified or highway=residential)”
*/
[out:json][timeout:25];
// gather results
(
  // query part for: “oneway!=* and highway=tertiary”
  node["oneway"!~".*"]["highway"="tertiary"]({{bbox}});
  way["oneway"!~".*"]["highway"="tertiary"]({{bbox}});
  relation["oneway"!~".*"]["highway"="tertiary"]({{bbox}});
  // query part for: “oneway!=* and highway=unclassified”
  node["oneway"!~".*"]["highway"="unclassified"]({{bbox}});
  way["oneway"!~".*"]["highway"="unclassified"]({{bbox}});
  relation["oneway"!~".*"]["highway"="unclassified"]({{bbox}});
  // query part for: “oneway!=* and highway=residential”
  node["oneway"!~".*"]["highway"="residential"]({{bbox}});
  way["oneway"!~".*"]["highway"="residential"]({{bbox}});
  relation["oneway"!~".*"]["highway"="residential"]({{bbox}});
);
// print results
out body;
>;
out skel qt;
```

**Metadata needed:** 

**Proposed GUI:**
Is this street one-way only?
| Yes |  | No | | It changes throughout the way | 
| More | -->  | This road alternates between different directions frequently and often|
                     | This road alternates between different directions regularly but infrequently. | (just an example)

If yes then the common road selection question pops out to let the person decide the direction.

**Comment by matkoniecz** [comment]
I think that it may be extremely hard to distinguish and detect areas where such quest would be useful. Note that "smaller towns/cities" may be very well mapped with active local contributors.

**Comment by westnordost** [comment]
Well, it could be asked for extremely slim streets. Something like
```
ways with highway ~ residential|service|tertiary|unclassified and !oneway and width < 4
```

**Comment by naposm** [comment]
Mh, to be onest I meant it would help small and not well updated cities, but I would ask it for every street on any width. I'll give you an example. Here in Italy we have a lot of small cities which are not very well mapped because people who live there are mostly elderly or not tech savvy people. This kind of city is just 10/15 minutes from mine, which instead is a very big city of southern Italy and well mapped. So, it has happened a lot of times that, when I travel to some of the near towns, I find a lot of unmapped one-way roads, which is a serious problem for routing. For this reason I often have to use GMaps for that. These towns are important locally mostly because of their roads which cross important motorways (so they should be mapped well for navigation). The problem is that these cities have also a lot of mappers who use StreetComplete (since they are visited often) but what lacks more is one-ways. The streets all have their names, some people also report problems like one-ways and other elements. So I think it would be useful to just let them edit it in the app... That's why I added for _smaller cities/towns_, because they are the ones who need it more, but it would be useful also in larger ones. The problem with asking only for streets with width < 4 is that most of these cities are mapped only from aerial imagery so (as for one-ways) they do not include such tags and the quest would never be asked...
I hope to have clarified it more, sorry for being so vague but English is not my main language 🙈

**Comment by naposm** [comment]
I'm writing another message because the previous one was not very clear and did not explain what I meant at all...
So, by smaller towns/cities I mean cities which have a lot of visitors (by foot or by car), but since these visitors come from bigger cities/other countries (so they only visit the city, they do not live there), it would be useful to just let them edit one ways.

What made me think about this quest is that in a small but busy city near my main city, there are usually some StreetComplete users who add streets and more details. 
Since this has also a lot of connection with many motorways, often I find a lot of one-ways which are not mapped. When I remember them, I just map them myself, but since I drive I can't open notes and such things, I just try to remember them.
So that's why, since a lot of people visit those city and I've seen some edits made by StreetComplete users, it would be useful to ask this question.
I think that it would be useful also in some big cities, my "for smaller towns/cities" was just to mark the difference with the already existing quest which is aimed at big cities where a lot of data is available (the improveosm data for one-ways).

The problem with the width < 4 is that since these cities are mostly mapped from aerial imagery, this data is often not available.

I hope to have explained it a little better, I apoligize for any mistake 😅

**Comment by westnordost** [comment]
I understand, but it is not possible to show a quest only for "small towns (in Italy) that are known to have small streets".

But no problem: What I plan to do is to add a quest that asks for the number of lanes on a road. If the number of lanes is 0 or 1, another quest is shown that asks for the width of the road. If the width is <4m or so, this quest can be shown.

**Comment by naposm** [comment]
I know, ideed my idea was to show it for every single road (of the 3 categories) of every city of every country. 

But it would cause too much span. Your idea makes perfect sense, in that case then it's perfect. Maybe lanes and one way could be in the same quest? I mean it could ask how many lanes per direction? I know it would become not a "simple quest" like the ones wich are usually asked but may be an idea 🤔

**Comment by westnordost** [comment]
> I mean it could ask how many lanes per direction?

Ah right, it could. But the user will also have the possibility to answer "there are no marked lanes". Many very small residential or country roads do not have any lane markings. In that case, lanes=0 or lanes=1 is tagged. It may not be immediately visible when you are in the midst of a road whether it is a oneway or not. If asked for the lanes, you can answer that immediately from anywhere on that road, while to answer if it is a oneway usually necessitates to go to one end of the road.

**Comment by matkoniecz** [comment]
> Many very small residential or country roads do not have any lane markings. In that case, lanes=0 or lanes=1 is tagged.

Are you sure that lanes=0 is correct? AFAIK lanes if for number of lanes for motor vehicles, not count of marked lanes.

**Comment by westnordost** [comment]
No, not sure, will need to look it up.

**Comment by peternewman** [comment]
Would it also make sense to filter out dead ends to reduce the spamming, as a road with only one connection to the rest of the network can't be one way unless another road hasn't been mapped (or unless it's a car factory! 😄).

**Comment by naposm** [comment]
> 
> 
> Would it also make sense to filter out dead ends to reduce the spamming, as a road with only one connection to the rest of the network can't be one way unless another road hasn't been mapped (or unless it's a car factory! 😄).

Yes, absolutely! I hadn't thought about that.

**Comment by kmpoppe** [comment]
Re `lanes=0`:

I was like: There can't be that many ... * queries overpass * ... oh!

I believe that most of them fall into what's described in the [Wiki](https://wiki.openstreetmap.org/wiki/Key:lanes#No_lane_markings): [...]To signify that a road has no lane markings, it is recommended to use an explicit tag like `lane_markings=no` or similar instead of an odd value for the `lanes=*` key like `0`, `1.5` or `none`[...]

So my take on that would be: lane_markings=no is fine, lanes=0 should be avoided.

Re the quest overall:

I like the idea (asking with width < 4 makes sense). When creating the quest we need to consider that the direction of the way must be shown to the user, because `oneway` is only supposed to be tagged with `yes` meaning "in the direction of the way". If the user hits "Yes, this is a one-way", but the order of the nodes in the way faces opposite to the marked one-way, that would be counter-productive.

Also I've yet to find a oneway in my homezone that's either `alternating` (changes direction often, think "Messeschnellweg" in Hannover which is the trunk-road towards the Fairground, that would be a perfect candidate, albeit it's currently oneway=yes) or `reversible` ("[Herbert-Weichmann-Straße](https://www.openstreetmap.org/way/169194882)" in Hamburg seems to be the closest to me that has a correct and consistent mapping on all it's points) - the latter adding an `opening_hours`-like complexity to the quest.

**Comment by westnordost** [comment]
Yes correct, so in this version of "is this a oneway", there must be a UI that enables (and explicitly demands from) the user to select into which direction this is a oneway.
I think alternating and reversible are so exotic that they don't need to be supported, in such cases the user can leave a note instead.

**Comment by kmpoppe** [comment]
@westnordost would you be able to find the time to give those issues that you think need a pretty high work-load on your part due to additional UI design a "blocked" label (like this one and 856), because I was looking for things to get my head into implementing quests ("Fingerübung") but that's no use if you can't do anything with said work yet. Thanks!

**Comment by westnordost** [comment]
I wouldn't consider things that are more effort blocked. I will look at what quests may be easier to do and comment here

**Comment by westnordost** [comment]
@kmpoppe 
The following quests are easy: #1961, probably #1756, #1572
The most effort however for most new quest would be the research how tags are actually used and which answer options should reasonably be displayed, then also to find fitting pictures in case the UI should consist of pictures being selected.

**Comment by westnordost** [comment]
@peternewman Any idea how to filter this with overpass?

**Comment by westnordost** [comment]
![Screenshot_1601071284](https://user-images.githubusercontent.com/4661658/94319655-72d01d00-ff8b-11ea-9788-e23c89e4a8be.png)

**Comment by peternewman** [comment]
> @peternewman Any idea how to filter this with overpass?

I've no idea if it's even possible, but as no-one else has responded I'll have a hunt and see what I can find.

**Comment by peternewman** [comment]
Best I've managed to find so far is this:
https://dev.overpass-api.de/blog/loop_and_group.html#complete

And then run this, which finds all the related nodes to a way recursively with the same name:
https://overpass-turbo.eu/s/YsP

So that gets all of a road. But then we'd need to count how many nodes they have linking to other roads.

iD also has these validations, but it looks like they use a lot of client-side processing:
https://github.com/openstreetmap/iD/tree/develop/modules/validations
