### ISSUE TITLE
Undo map tilt does not work when position is gps locked

### ISSUE THREAD

**Issue by HolgerJeromin** [westnordost/StreetComplete#1984]
**How to Reproduce**
* open SC
* have position gps locked
* tab north arrow icon => map is tilted
* tab north arrow icon again => map is **not** untilted
* **move map a bit to unlock** gps 
* tab north arrow icon => map **is** untilted
* tab north arrow icon again => map is tilted
* tab north arrow icon => map is untilted

* tab position circle => map is centered and locked again
* tab north arrow icon => map is tilted
* tab north arrow icon again => map is **not** untilted again

**Versions affected**
Since a few versions. Right now 22.0-beta1

**Comment by HolgerJeromin** [comment]
Is this a feature not a bug? I am not sure after reading #1725
cc @smichel17

**Comment by smichel17** [comment]
Seems like a bug. The feature from that issue is basically "if the map is untilted and very close to north but not exactly, tilt it, instead of rotating an imperceptably tiny amount so that it faces true north."

If the map is currently tilted, tapping the compass should always untilt it.
