### ISSUE TITLE
Not all quests are displayed

### ISSUE THREAD

**Issue by NotSoImportant** [westnordost/StreetComplete#1986]
If not all fit the screen some are shown as dots, some not at all
- what is the difference
- is there any prioritization (also see #1985)

**Use case**
I want to know where are quests available

**Proposed Solution**
1. always show the dots
1. visualize zoom level and affect of it
    - i.e. visialize how may (of the loaded) quests are currently been displayed (not the same as #1985 solution nr.3 as this talks about loading them from the server)
1. if any: visualize quest type priorities in the config (same as #1985 solution nr.5)

version: 21.0

**Comment by NotSoImportant** [comment]
A comparison. Before:
![grafik](https://user-images.githubusercontent.com/35758921/88730106-a16d7b00-d135-11ea-8ef1-1be13a088918.png)

After zooming 1 level (no search changes in between):
![grafik](https://user-images.githubusercontent.com/35758921/88730168-c6fa8480-d135-11ea-973c-aa4fb93511a7.png)

Legend:
- green = dot expanded to baloon
- yellow = dot appeared
- red = baloon appeared

**Comment by matkoniecz** [comment]
> is there any prioritization

Yes, there is. See quest list in settings.

> version: 21.0

Note that 21.2 fixed major prioritization error (it was inverted) See https://github.com/westnordost/StreetComplete/releases

Please update if you are able (note that F-droid updates are controlled by an external entity).

> always show the dots

Done on higher zoom levels where it is reasonable.

**Comment by westnordost** [comment]
So, this was fixed in a version after 21.0
