### ISSUE TITLE
Add a car mode

### ISSUE THREAD

**Issue by XioNoX** [westnordost/StreetComplete#1987]
**Use case**
It would be useful to have a switch to only show quests doable from a moving vehicle (car, bus, etc).

**Proposed Solution**

Something quick to flip. And should still respects the quests disabled in the "normal" mode.

**Comment by thibaultmol** [comment]
I feel like that might encourage people using StreetComplete while driving which either is or should be illegal depending on your country.
Makes more sense I think to just go to some place with a folding bike or bike rack and ride around (if you want to streetcomplete somewhere far from home)

**Comment by HolgerJeromin** [comment]
I think this issue is a duplicate of #1654 (quest presets)

**Comment by XioNoX** [comment]
Indeed!
