### ISSUE TITLE
collection_times value incorrectly formatted

### ISSUE THREAD

**Issue by JacLavi** [westnordost/StreetComplete#1988]
This the way SC formats collection_times for a postbox

collection_times=Mo-Fr 16:30, Sa 12:00

https://www.openstreetmap.org/node/1395865959

which is reported as wrong by Osmose according to the Wiki : 

https://wiki.openstreetmap.org/wiki/Key:collection_times

and should be : 

collection_times=Mo-Fr 16:30; Sa 12:00  (semi-colon)

**How to Reproduce**

**Versions affected**  :

SC 10.2 

Android 9

**Comment by matkoniecz** [comment]
both version are correct, Osmose is wrong to complain https://openingh.ypid.de/evaluation_tool/?EXP=Mo-Fr%2016%3A30%2C%20Sa%2012%3A00&lat=48.7769&lon=9.1844&mode=1&DATE=1596111000000 and https://wiki.openstreetmap.org/wiki/Key:opening_hours
