### ISSUE TITLE
No quest till manual search

### ISSUE THREAD

**Issue by kudlav** [westnordost/StreetComplete#1989]
I see no quest till manual search for quests. Maybe I have to wait a bit longer, but quests are appearing very fast after start of manual search.

**How to Reproduce**
- Open app and wait for GSP position.
- You can wait for quests - but they are not loaded

**Versions affected**
- App from Google Play - v21.2
- Android 10
- Samsung Galaxy A40

**Comment by westnordost** [comment]
So, do you get a GPS position? Does the loading indicator start indicating that quests are being loaded?

**Comment by kudlav** [comment]
I get a GPS position, map is centered and fixed to the position. What do
you mean by loading indicator? There is no indicator of auto-downloading
process.

--
Vladan Kudláč

Dne čt 30. 7. 2020 18:17 uživatel Tobias Zwick <notifications@github.com>
napsal:

**Comment by westnordost** [comment]
Well, there should be. Do you have auto-sync on or off?

**Comment by matkoniecz** [comment]
> What do you mean by loading indicator?

Quest icon at the bottom and bar scrolling around.

**Comment by kudlav** [comment]
I have auto-sync disabled, I don't want to automatically upload answered quests.
Downloading quests is also connected with the sync? I so, it is very unclear. This field is just called Auto sync  without description.

**Comment by westnordost** [comment]
Yes, sync goes both ways, otherwise it would be called auto-upload

**Comment by kudlav** [comment]
So what includes sync? It would be useful to add description into settings.

**Comment by westnordost** [comment]
Upload and download

**Comment by kudlav** [comment]
Should I open new issue for feature request: Add description for sync
settings?

Dne čt 30. 7. 2020 19:04 uživatel Tobias Zwick <notifications@github.com>
napsal:

**Comment by westnordost** [comment]
No, because auto-sync is on by default and it is explained when you turn it off.

**Comment by matkoniecz** [comment]
It seems that English version is also not warning about manual download.
