### ISSUE TITLE
in map display access restrictions - fully restricted ways and barriers like fences and walls

### ISSUE THREAD

**Issue by matkoniecz** [westnordost/StreetComplete#199]
One may end not reaching quest because chosen route is blocked by access restriction/barriers like fences.

It is a bit irritating to end in such situation and discover that obstacle was mapped in OSM.

Would it be considered preferable to use map style that marks roads unavailable for foot travel and marks barrier=fence/wall, and potentially also other obstacles that make reaching to the destination impossible?

from #198 I understand that iff somebody forks current map style or makes new one from scratch it may be potentially used so I want to check whatever such canges would be considered as desirable

**Comment by matkoniecz** [comment]
It seems that currently Cinnabar from https://mapzen.com/products/maps/ is the currently used basemap. And it would mean that https://mapzen.com/documentation/tangram/tutorials/editing-basemaps/ is potentially useful.

**Comment by westnordost** [comment]
Makes sense

Am 8. Mai 2017 08:44:49 MESZ schrieb Mateusz Konieczny <notifications@github.com>:
>One may end not reaching quest because chosen route is blocked by
>access restriction/barriers like fences.
>
>It is a bit irritating to end in such situation and discover that
>obstacle was mapped in OSM.
>
>Would it be considered preferable to use map style that marks roads
>unavailable for foot travel and marks barrier=fence/wall, and
>potentially also other obstacles that make reaching to the destination
>impossible?
>
>from #198 I understand that iff somebody forks current map style or
>makes new one from scratch it may be potentially used so I want to
>check whatever such canges would be considered as desirable
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/westnordost/StreetComplete/issues/199

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by matkoniecz** [comment]
https://github.com/westnordost/StreetComplete/blob/604f6b02f797f8aafedeb0649d29da514501ab08/app/src/main/assets/cinnabar-style-7.0.0.yaml is location of the currently used style.

https://github.com/tangrams/cinnabar-style is repository of this style.

I am a bit confused by relation of code in these locations, StreetComplete is using version 7.0.0 while https://github.com/tangrams/cinnabar-style/commits/gh-pages has only version 0.12. Is it a correct guess that if one would use the same formatting of version number then street complete would be using v0.7 and current would be v0.12?

**Comment by matkoniecz** [comment]
In addition I opened issue at https://github.com/tangrams/cinnabar-style/issues/26 ("show major barriers like barrier=fence or barrier=wall") to check whatever PR that adds showing wall/fences would be welcomed upstream

**Comment by westnordost** [comment]
> I am a bit confused by relation of code in these locations, StreetComplete is using version 7.0.0 while https://github.com/tangrams/cinnabar-style/commits/gh-pages has only version 0.12

See https://github.com/tangrams/cinnabar-style/releases

Though, in danger to repeat myself: If there will be a custom style for street complete, it should start from a basic template, not one of these "house styles".

**Comment by matkoniecz** [comment]
What you meab by "house styles"? Focusing too much on buildings? Developed as showcase by company? Or something else?

**Comment by matkoniecz** [comment]
Updating cinnabar style will readd fences - see https://github.com/tangrams/cinnabar-style/commit/7d905d4b382097e297bc87908629632a29a0f6e8

**Comment by matkoniecz** [comment]
> This is released in https://github.com/tangrams/cinnabar-style/releases/tag/v7.0.1 and on the Mapzen CDN.

https://github.com/tangrams/cinnabar-style/issues/26#issuecomment-304115800

**Comment by westnordost** [comment]
>What you mean by "house styles"? Focusing too much on buildings? Developed as showcase by company? Or something else?

Developed as showcase by the company

**Comment by matkoniecz** [comment]
For now I opened also https://github.com/tangrams/cinnabar-style/issues/32
