### ISSUE TITLE
Profile login page blank with spinner

### ISSUE THREAD

**Issue by quite** [westnordost/StreetComplete#1991]
**How to Reproduce**

Just installed the app on device. Profile login page is blank except for a "spinner" at the top. Nothing more happens 

**Versions affected**

Android 10 on Oneplus 6. 21.2

**Comment by matkoniecz** [comment]
Can you log into OSM in a regular browser?

**Comment by quite** [comment]
Yes, on same device. (Never get a chance to type credentials in StrC). Could some part of OSM api be down right now...

Just tried again right now. Worked, I guess I was very unlucky...

**Comment by matkoniecz** [comment]
I asked because I suspected that wifi/OSM server/??? was broken - and I am not sure whatever SC can do anything useful in such case.
