### ISSUE TITLE
New achievement link: finde.cash!

### ISSUE THREAD

**Issue by FloEdelmann** [westnordost/StreetComplete#1994]
As highlighted in [weeklyOSM 523](http://weeklyosm.eu/archives/13451#wn523_22996):

> [Finde.cash](https://finde.cash/) displays banks and ATMs with the respective ATM networks on a map? It also offers route planning by foot, bicycle or public transport, and four background options including OpenCycleMap. Missing ATMs can be inserted directly. The map is worldwide but the menu is only available in German.

This could be a great link to add to the [achievement links](https://github.com/westnordost/StreetComplete/blob/master/app/src/main/java/de/westnordost/streetcomplete/data/user/achievements/AchievementsModule.kt).

**Comment by westnordost** [comment]
I read the weeklyOSM myself and the weeklyOSM is also in the list of links. Still thank you for the input, I'll consider it. (There are are couple of other links that I deem to be more important when I extend the links list another time). Could it be that it hasn't been updated in 3 years? https://github.com/nils-v/finde.cash/

**Comment by FloEdelmann** [comment]
Indeed, it looks like the project is not really maintained anymore, although the website looks fine.

Just wanted to bring it into consideration.
