### ISSUE TITLE
Adjust addr:housenumber validation to include 5 digit house numbers as valid

### ISSUE THREAD

**Issue by MattWhilden** [westnordost/StreetComplete#1995]
**How to Reproduce**

Add a house number that is 5 digits to in the house number flow. You'll get a warning for each house even though such numbers are quite common for houses in various American suburbs. It would be nice if [the validation](https://github.com/westnordost/StreetComplete/blob/master/app/src/main/java/de/westnordost/streetcomplete/quests/address/AddHousenumberForm.kt#L212) was modified to be a bit more inclusive as this would speed up the flow and decrease confusion for new mappers. What do you think?

I'm happy to try and track down the overall distribution of number of digits in house numbers if that helps validate or invalidate this request.

**Versions affected**
All versions

**Comment by MattWhilden** [comment]
Small data point: According to data from Overpass 2/3rds of the housenumbers for my city (Redmond WA) are 5 digits. The rest are 4.

**Comment by westnordost** [comment]
Right, let's change this to 5 then.

**Comment by MattWhilden** [comment]
Wonderful. Thank you!
