### ISSUE TITLE
Community Vote - Always show GPS Button?

### ISSUE THREAD

**Issue by Atrate** [westnordost/StreetComplete#1996]
Related issues: #1843, #1896, #1990, especially https://github.com/westnordost/StreetComplete/issues/1990#issuecomment-667721833.

### Background

Quite a few issues have been opened so far discussing the way the GPS button works in StreetComplete after v20.0.
This issue aims to summarise main arguments for and against the GPS button disappearing after getting a lock-on. Feel free to ping me with additional arguments and I'll add them to the list as soon as I can.

### Pros of the current state of things:

- Minimizes the amount of UI elements cluttering the map at any given time
- The functionality of the GPS button is provided by the new location pin
- It is planned to replace the +/- buttons with a slider which then would free up the right side of the screen completely

### Cons of the current state of things

- The GPS button's disappearance can cause confusion
- It is easier to simply tap a GPS button instead of searching for the pin all over the screen
- The GPS button should be very familiar from similar location-based apps such as OSMAnd, GMaps, Vespucci, etc.
- Some users have reported the location pin to be hard to tap on smaller displays
- If the location pin is very close to/overlapping a quest pin you are likely to press the wrong one

### Solution(s)

There are a number of ways to approach this issue, each will have its own emoji for voting. Feel free to ping me with additional solutions and I'll add them to the list as soon as I can.

 - Bring back the old functionality — make the GPS button not disappear at all. The new position marker can stay or go, depending on the design considerations. Emoji: 👍 

 - Leave it as it is — the GPS button will disappear when getting a good GPS lock. Emoji: 👎 

- Make the GPS button disappear only when the map is locked onto your position and following. Emoji: :confused: 
 - I don't mind either way. Emoji: :eyes:

Feel free to vote on multiple options, after all, it's all non-binding, @westnordost has the final say here.

**Comment by westnordost** [comment]
(I edited the voting options because certain things I do not plan to implement in any case)

**Comment by smichel17** [comment]
I want to propose a fourth option: the GPS button should disappear when when the map is locked on to your position (ie, disappears after pressing it if location is already found, or when location is found) and appears when no longer locked on (ie, when scrolling the map).

Tapping the gps pin (whether off screen or on) should center the gps on screen, but not lock on.

I volunteer to implement this, if it is accepted. I *might* be willing to implement it sooner than that so you (@westnordost) can play around with it and convince yourself it makes sense :)

**Comment by westnordost** [comment]
> Maybe this option can be 😕 in the poll?

Ok

**Comment by thibaultmol** [comment]
I didn't even realise that was the condition of the GPS icon to appear or not. I did find it confusing that sometimes it was there, sometimes not.
(Personally i use the location pin anyway) 

Somehow if you ask me how I would have implemented a GPS status thing. I guess I would have gone with a more traditional "GPS BAD" (red), "GPS fine" (orange), "GPS good"(green. But have it  disappear after 3 to 5 seconds if it's good)
Text in top left or right corner

**Comment by forteller** [comment]
Thank you for this possibility to vote on this! The new way of doing this has been annoying me quite a lot, but I didn't feel like I could ask to revert it.

Please let me add one more point to the cons list:

If the location pin is very close to/overlapping a quest pin you are likely to press the wrong one.

**Comment by smichel17** [comment]
There's enough interest in the solution I proposed that I've partially implemented it in #2101, just enough to play around with and get a feel for what it's like.

**Comment by smichel17** [comment]
Functionality is now done, although the code isn't quite good enough quality to merge yet. **Feedback is very welcome.** If you can't build yourself, I can provide a debug apk.
