### ISSUE TITLE
Group quests for the same way/node so they are available offline together

### ISSUE THREAD

**Issue by rhhsm** [westnordost/StreetComplete#1999]
I've been using Streetcomplete quite intensively for the last 2 months now (and completed 4000+ quests), and like it very much! However, I would like to suggest a few improvements.

I think to keep volunteer mappers motivated, the number of times a certain place needs to be visited should be minimised as much as possible. I understand that there are software restrictions on this, but maybe more can be done? I'd like to suggest that quests for a certain node or way are always downloaded in groups, so that as many quests as possible for the same way/node are available offline while surveying. I think the following groups are most common:
- path: surface? -> lit?
- road: name? -> surface? -> lit? -> sidewalks?
- steps: surface? -> handrail?
- shop: name? -> hours?
- parking: public? -> paid? -> kind? (this one usually groups together well)
- bicycle parking: kind? -> covered? -> no. of bikes?
Probably there are more...

**Comment by FloEdelmann** [comment]
Related to #1969.

**Comment by westnordost** [comment]
Actually, pretty much a duplicate.

In a nutshell, for example the surface quest must be answered before the lit quest is even generated. Quests are only generated on upload for the reasons stated in #1969.

**Comment by westnordost** [comment]
But you can thumbs-up the other feature request to indicate that you'd like that implemented.
