### ISSUE TITLE
Release on F-Droid too

### ISSUE THREAD

**Issue by picsi** [westnordost/StreetComplete#2]
It would be excellent to have this also on F-Droid, when it is launched. See https://f-droid.org/contribute/ for instructions

**Comment by IzzySoft** [comment]
As it's currently not available anywhere, it would be nice to have at least an `.apk` here at Github meanwhile, so end-users have a chance to test it and give feedback. I'm also offering to place it into [my F-Droid compatible repo](https://android.izzysoft.de/repo) then to ease installation and auto-updating (unless the `.apk` is too big).

**Comment by westnordost** [comment]
I'll do as soon as it is in a usable state, no worries.

**Comment by IzzySoft** [comment]
@westnordost if you mention that in this issue, let me know if it's OK with you to have it in my repo. I'll then set that up, and it will fetch updates automatically. Thanks in advance!

**Comment by westnordost** [comment]
Of course it is okay, thanks for your engagement :-)
However, I think as soon as I want to go out of beta with this, I'll try to have it added to the main repository through the [submission queue](https://f-droid.org/forums/forum/submission-queue/), otherwise I fear it will not be found.

**Comment by IzzySoft** [comment]
Fair enough. And can be combined: pushing it through the queue might take some time. Once it's through, just drop me a note if I shall remove it from my repo then (to avoid confusion). 2 things why it might be useful to leave it in would be: 1) I do not re-sign the `.apk`, so one can cross-update with Playstore and 2) updates are usually showing up faster here (within 24h, F-Droid sometimes takes a week). But we can decide about that when it's due :)

**Comment by IzzySoft** [comment]
For now, you can find it in my Repo (see [here](https://apt.izzysoft.de/fdroid/index/apk/de.westnordost.streetcomplete)), which you can configure in the F-Droid client. Updates usually are available within 24h of their appearance here (as long as the APK was attached to the release).

**Comment by westnordost** [comment]
Added a merge request here. https://gitlab.com/fdroid/fdroiddata/merge_requests/2121
As soon as this is closed, StreetComplete should be in the main F-Droid repository as well.

The hurdle to not use Google Play but F-Droid is high enough as it is, so I find it quite important that the app is findable through F-Droid without any further configuration.

**Comment by IzzySoft** [comment]
Fully agreed on that, Tobias! If you can bring it into the main repo, by all means, do so!

Until then (and if you don't reason against it) it will be available via my repo, with your own signing (and faster updates: ATM, F-Droid didn't update their repo for 5 days in a row), so people can chose (and easily cross-update with the Playstore). In the end, chosing the "official repo" as source gives another level of assurance, as folks there do a good and thorough check as far as I've heard.

**Comment by Roxxor91** [comment]
It arrived in the F-Droid main repo, by which I found it! Thank you! I directly went for a walk in Riga oldtown and added opening hours etc.
I found some old entries of stores/restaurants which have been replaced by others. Are you planning to add editing Locations? Or would that be overload?

**Comment by IzzySoft** [comment]
After 10 days not updating their index at all, it arrived in the main repo today, true – congrats! If you want me to remove the app from mine because of that, just let me know (otherwise I happily keep it there). But keep in mind that mine picks up updates faster, and the `.apk` files are signed by *your* key – i.e. they can be cross-updated with other sources you are placing it (e.g. Playstore). Your decision, @westnordost :innocent:

**Comment by westnordost** [comment]
I am not planning to add a feature to edit elements, I think Vespucci et al or Maps.me et al is a better tool for that.

I don't see any reason why StreetComplete should not remain on Izzy's repository as well, so, yeah, keep it on :-) 
-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by IzzySoft** [comment]
Thanks a lot, Tobias – will keep it updated then whenever you attach a new release :+1:
