### ISSUE TITLE
"trash can" and "bench" for bus stop quests

### ISSUE THREAD

**Issue by Natenom** [westnordost/StreetComplete#200]

**Comment by westnordost** [comment]
I never understood why one would want to map trash cans at all.

**Comment by matkoniecz** [comment]
> I never understood why one would want to map trash cans at all.

I used Humanitarian layer with waste baskets as map illustration in petition to local government (obviously, the petition was about waste baskets missing in one praticular region). Though it is rather weird use case and I am not expecting that this happens frequently.

**Comment by Hillside502** [comment]
Mapping **waste basket**s (in OpenStreetMap parlance) is useful for surveying their distribution throughout a locality --- anywhere, not just at bus stops.

Tag:amenity=waste_basket - OpenStreetMap Wiki
https://wiki.openstreetmap.org/wiki/Tag:amenity%3Dwaste_basket

**Comment by matkoniecz** [comment]
More on topic - AFAIK adding new objects is out of scope, and this quest is not going to be doable by adding new attributes to existing objects (bus stop and amenity=waste_basket should not be mapped as one node).

**Comment by westnordost** [comment]
Well, I think more important quests should also have higher priority in implementation.

**Comment by Natenom** [comment]
@matkoniecz According to the German page (https://wiki.openstreetmap.org/wiki/DE:Tag:highway%3Dbus_stop) there is a bin=yes attribute for bus stops. This is not mentioned in the English page, though.

**Comment by matkoniecz** [comment]
> bin=yes

This is really poor idea. Even if something is somehow using waste basket data (displaying it on map or something) it is not going to use really weird way of tagging it. Or at least it should not to avoid encouraging tagging that makes everything more complicated.

If somebody wants to tag waste baskets, at least tag their accurate location not some weird approximation,

**Comment by rugk** [comment]
Okay, so can someone remove it from the German wiki page? It is clearly bad to map it like this.

**Comment by westnordost** [comment]
Hmm yeah, I am going to close this

**Comment by Carnildo** [comment]
If "bin=yes" is bad, then how do you propose mapping situations where the wastebasket is part of the pole holding the bus stop marker?

https://www.google.com/maps/@47.6679785,-117.4172541,3a,75y,137.92h,76.87t/data=!3m7!1e1!3m5!1sukRxBZWaOp0STHe2RrT4Cw!2e0!6s%2F%2Fgeo2.ggpht.com%2Fcbk%3Fpanoid%3DukRxBZWaOp0STHe2RrT4Cw%26output%3Dthumbnail%26cb_client%3Dmaps_sv.tactile.gps%26thumb%3D2%26w%3D203%26h%3D100%26yaw%3D100.14012%26pitch%3D0%26thumbfov%3D100!7i13312!8i6656

I agree it's not a common enough situation to be worth including in StreetComplete, but "bin=yes" doesn't strike me as a "weird approximation".

**Comment by krzyk** [comment]
The situation shown above is quite common in suburbs in Poland.
In case of a lack of a shelter bin=yes is an exact position of the wastebasket.

**Comment by westnordost** [comment]
Generally, I think more energy should be spent on adding and maintaining the really important things in quests than discussing which things are still barely important enough to be included.

It is not as if there weren't any more important quests still left to design and implement.

Am 14. Juli 2017 10:32:49 MESZ schrieb "Krzysztof Krasoń" <notifications@github.com>:
>The situation shown above is quite common in suburbs in Poland.
>In case of a lack of a shelter bin=yes is an exact position of the
>wastebasket.
>
>-- 
>You are receiving this because you modified the open/close state.
>Reply to this email directly or view it on GitHub:
>https://github.com/westnordost/StreetComplete/issues/200#issuecomment-315303820

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.
