### ISSUE TITLE
Consistently start changeset comments with uppercase letters 

### ISSUE THREAD

**Issue by cyclingcat** [westnordost/StreetComplete#2001]
I just noticed that the comments StreetComplete put into its changesets have the case of the first letter (often: "add") used inconsistently. See this screenshot from my OSM profile:

![Change_sets](https://user-images.githubusercontent.com/32601012/89538885-66390f00-d7fb-11ea-91d8-0315b3fc4874.png)

As changeset comments have the nature of headlines I'd suggest to convert the (probably few) comments with a lowercase first letter to uppercase (e.g. "**A**dd whether traffic signals have a button for pedestrians").

(SC 20.2 and 21.2 from F-Droid.)

The cycling cat

**Comment by westnordost** [comment]
I don't mind either way. If you create a PR for this, I will accept it.

**Comment by westnordost** [comment]
So will you do it? For me, Uppercase consistency in changeset comments has absolutely no importance for me.

**Comment by Atrate** [comment]
If no one does, I'll spin up a PR but only in about two weeks' time

**Comment by cyclingcat** [comment]
If you don't mind, please leave this ticket open. I have never created a PR so far and have always wondered how this works, so I want to take this opportunity to learn how to do it, assuming it's an almost trivial case here, ideal for beginners. (The coming hot days prevent me from cycling anyway :-))

The cycling cat

**Comment by westnordost** [comment]
Basically you fork this repository, do your changes, commit (better on a branch) and push them to your forked repository. Then, on github, you tap on the "New Pull Request" button in this repository and select to pull from your repository ("compare across forks" link).
The Github desktop client might make the workflow easier, I don't know.

**Comment by matkoniecz** [comment]
> I have never created a PR so far and have always wondered how this works, so I want to take this opportunity to learn how to do it, assuming it's an almost trivial case here, ideal for beginners.

If you are stuck with something - ask here.

And yes, it is nearly simplest possible task (except that part that you need to check and change now than one text string).

**Comment by Atrate** [comment]
To make it even simpler, you don't even need to download the repo to your computer, such simple changes can be done in Github's integrated editor — fork, edit, save by comitting, create PR.
