### ISSUE TITLE
Street not displayed on map

### ISSUE THREAD

**Issue by Helium314** [westnordost/StreetComplete#2002]
For some reason this street: https://www.openstreetmap.org/way/9702353 is not displayed on the map, there are only rails visible.
In earlier versions (probably before the switch to jawg) this was displayed correctly.

StreetComplete 22.0
S4 Mini, Android 9

**Comment by westnordost** [comment]
Ok, I passed on the bug report to JawgMaps.

See https://www.jawg.io/en/maps/#17.29/48.173665/16.414761 vs https://www.jawg.io/en/maps/#17.29/48.173665/16.414761
