### ISSUE TITLE
Semi-detached House needs more than one address number

### ISSUE THREAD

**Issue by MattWhilden** [westnordost/StreetComplete#2004]
When doing quests for add:househumber, there's the occasional semi-detached house ("duplex" here in the states). It typically has more than one address number associated with it. Here's an [example](https://www.openstreetmap.org/way/825350939/history). Should the workflow help people with the multi-entry syntax in some way? Not show these for entry? Some other brilliant idea?

Lots of places have these marked as address nodes in the building perimeter which doesn't really lend itself to the StreetComplete quest style. 

**Versions affected**

All

**Comment by matkoniecz** [comment]
See hint after selected proper entry in "can't say" menu.

You can also leave note with photo instead of answering directly.

**Comment by MattWhilden** [comment]
Got it! Appreciate the tip.

**Comment by rhhsm** [comment]
When I find a building that's really two houses sharing a wall, I edit this in OSM by creating 2 areas that share at least two nodes, each area tagged Tag:building=semidetached_house, and give each the correct house number. In my area I often find large (apartment) buildings that have addresses on more than one street, and then I think it's the only way to correctly handle this. See also https://wiki.openstreetmap.org/wiki/Tag:building%3Dterrace

**Comment by MattWhilden** [comment]
Ah, another excellent tip. Thanks!
