### ISSUE TITLE
Emhancement: Allow splitting handrail quests

### ISSUE THREAD

**Issue by Atrate** [westnordost/StreetComplete#2008]
Rationale: many forest paths with steps are often tagged as one long line of steps, where the availability of handrails sometimes varies along the way. 

Adding an ability to split the stairway would be useful.

**Comment by matkoniecz** [comment]
Have you tried using "othe answers..." -> "Differs along the way..."? It is available to me.

**Comment by Atrate** [comment]
Huh, didn't notice that, thanks!
