### ISSUE TITLE
Warning in disabling auto-sync is not warning that also quest download is now manual

### ISSUE THREAD

**Issue by matkoniecz** [westnordost/StreetComplete#2009]
Triggered by #1989 by @kudlav

"To upload your changes manually..." is not mentioning that also download is manually.

Probably it is better to add new text - to reduce workload for translators and to allow mentioning where "scan quests" is available.

**How to Reproduce**
Go to settings, switch to autosync (if disabled), switch to disabled autosync.

**Versions affected**
v22.1 on Android 10

**Comment by westnordost** [comment]
Makes sense
