### ISSUE TITLE
Small error in french translation: "cette édifice" should be "cet édifice"

### ISSUE THREAD

**Issue by SnarkBoojum** [westnordost/StreetComplete#201]
All is in the title.

**Comment by westnordost** [comment]
There is no such string.

**Comment by althio** [comment]
I cannot access French translations anymore on https://poeditor.com/join/project/IE4GC127Ki

Is something disabled for French?

**Comment by SnarkBoojum** [comment]
In fact I looked around and the error is already fixed -- just not in a release which found its way to my phone.

**Comment by althio** [comment]
About French translations on https://poeditor.com/join/project/IE4GC127Ki

Apparently all my translated strings were removed/reverted a week ago.
Is this a problem with my account, or a bug, or a manual action?
Should I change back, or leave as it is?
