### ISSUE TITLE
Ask for roof levels if not set

### ISSUE THREAD

**Issue by Discostu36** [westnordost/StreetComplete#2010]
**Use case**
At the moment, building levels and roof levels are asked in the same quest. This leads to the problem that if a building already has `building:levels` added but no `roof:levels`, StreetComplete will not ask about the roof levels and also not about the roof shape.

**Proposed Solution**

Two possibilities:
1. If a building does have a `building:levels` tag but not a `roof:levels` tag, show it in the building levels quest, pre-fill the building levels field and put the cursor into the roof levels field.
2. Add a separate roof level quest for buildings missing the `roof:levels` tag

**Comment by HolgerJeromin** [comment]
SC does not set `roof:levels` if not given (and does not ask `roof:shape`).
So this behavior is as designed. 
#1744, #1778, #277
