### ISSUE TITLE
crash on start since recent version

### ISSUE THREAD

**Issue by scoid** [westnordost/StreetComplete#2013]
StreetComplete crashes on start

**How to Reproduce**
1. attempt
"StreetComplete has stopped"
2. attempt
"StreetComplete keeps stopping"

**Versions affected**
recent update from 10th or 11th August

**Device**
Samsung Galaxy S4 mini,
Device model GT-I9195

**OS**
LineageOS API Level
Guava (7)

system update /e/OS 0.10-2020080766702
Android 7.1.2
August 7, 2020

**Comment by matkoniecz** [comment]
See #2011 #2006

It should be fixed by upgrading to 22.1

**Comment by scoid** [comment]
OK
