### ISSUE TITLE
Ask building type quest for other buildings than those tagged building=yes

### ISSUE THREAD

**Issue by rhhsm** [westnordost/StreetComplete#2016]
In my area there are many buildings tagged as "residential" that I would like to give a more detailed tag such as "apartments" or "detached". However, only buildings tagged as "yes" show up as quests. Could SC be enhanced to include intermediate detail tags showing up as quests?
Related, I find it unsatisfactory that shops and restaurants can only be tagged as "retail" where much more detail could be given such as "shop", "restaurant", "cafe", etc. (and then more detail on "shop", restaurant cuisine, etc.). If this is implemented, then buildings tagged as "retail" should show up again as quests to be able to add a more detailed tag...

**Comment by matkoniecz** [comment]
Problem with residential is that sometimes it is hard to specify it in greater detail. So it would need to be a separate quest, probably disabled by default.

**Comment by westnordost** [comment]
@matkoniecz no, it would not be a quest at all. The criteria for a by-default-disabled quest are that you need to go inside or something to solve.

Please see the [quest guidelines](https://github.com/westnordost/StreetComplete/wiki/Adding-new-Quests-to-StreetComplete), I don't see how this can be done because of 
> 🤔 No unanswerable quests: All generated quests need to be actually answerable (no false-positives). This means that any answer given by the user must result in something being tagged. For example, a quest that asks for the website of a place must be able to tag the element somehow if the user answers that the place has no website - otherwise, the next user will be asked the same question. Sometimes, due to the nature of how things are tagged in OSM (such as the one given in the example) it is unfortunately simply not possible to fulfill this.

**Comment by matkoniecz** [comment]
> "shop", "restaurant", "cafe"

Is there actually substantial difference in structure between building intented to house a shop / restaurant / cafe?

Near me building was constructed as a retail building to house cafe/restaurant and got transformed into post office without substantial changes to any structure.

It could be turned into shop by changing furniture.

**Comment by Atrate** [comment]
> It could be turned into shop by changing furniture

Exactly. That's why "retail" and the larger "commercial" tags exist — buildings are usually constructed as such, not for extremely specific purposed, this can (and should) only be stored in building:use, @rhhsm

**Comment by rhhsm** [comment]
On the building=residential part of my request, it depends how many of the buildings tagged like this are a result of armchair mapping using areal images, where the building gets this tag because it's in a residential area (in my area, many), and how many are tagged such because they can't be tagged with a more detailed tag.
On the building=retail part, I think we should keep in mind that the ultimate aim of OSM is (or should be) to provide a map that is useful to the user. For a map user, it's hardly useful to know that a building is used for retail, if he's looking for a restaurant. Maybe I should rephrase my request for a quest that asks for the building:use of a retail building?

**Comment by matkoniecz** [comment]
> For a map user, it's hardly useful to know that a building is used for retail, if he's looking for a restaurant.

This is mapped with `amenity=restaurant`, `shop=*`, `amenity=fast_food` tags. `building` tag is nearly useless here, restaurant may be in the `building=office`, desecrated `building=church` and so on.

**Comment by smichel17** [comment]
Details of which tags to use aside, wouldn't the issue of not-fully-specific tags be indirectly solved by map maintenance quests (#1998)? When users are confirming the building type, they can select a more specific version if it applies. (Perhaps in the case of confirming a generic version, the app could prompt the user to take a closer look instead of just confirming that it is residential, etc?

**Comment by westnordost** [comment]
Building type is not asked again though because it is unlikely to change

**Comment by smichel17** [comment]
In that case, it seems like an issue with the tagging schema that needs to be addressed upstream — there should be a way to disambiguate between "this is a residential building and I'm not sure which more specific tag applies" and "this is a residential building and no more specific tag applies". Eg, `building=residential` vs `building=residential:generic`.

**Comment by westnordost** [comment]
Yes

**Comment by westnordost** [comment]
Before StreetComplete entered the stage, few people thought about how to differentiate between "don't know / not applicable" and "not surveyed yet".

**Comment by westnordost** [comment]
So, (at the moment) this can't be a quest in StreetComplete
