### ISSUE TITLE
Find quest error when category "What's the name of" is checked

### ISSUE THREAD

**Issue by horstworst** [westnordost/StreetComplete#2017]
Hello, 

when i check the quest category  "What's the name of" (my version is german, there it's called "Was ist der Name hiervon (...)") then i get an error while updating the quests for the location.
I've tried to empty the cache (app) and also mark cache as invalid in the app itself. No changes of behavior.

![29c012c1-6452-44bf-8149-682347a6823e](https://user-images.githubusercontent.com/69648719/90177069-43ce6500-ddaa-11ea-8211-33d62f722ed6.jpg)

when this particular category is unchecked then all is fine

**How to Reproduce**
as above

**Versions affected**
Android 10
Streetcomplete 22.0 (f-droid)

**Comment by Atrate** [comment]
May be related to https://github.com/westnordost/StreetComplete/issues/2007, but not sure

**Comment by westnordost** [comment]
Yes, it's the same. Already fixed, you need to wait for F-Droid to release the new version.
