### ISSUE TITLE
New quest: operator of the amenity=atm

### ISSUE THREAD

**Issue by Etua** [westnordost/StreetComplete#203]
Useful data (as, depending on the bank, using some networks may not be free) but sometimes missing or put only in the name of the amenity. When combined with localized quests you talked about in #188 the user would choose from just few operators (depending on the country) as usually the ATM belong to one of the major operators. In other case the name could be written manually as "other answer".

**Comment by Hillside502** [comment]
Tag:amenity=atm - OpenStreetMap Wiki
https://wiki.openstreetmap.org/wiki/Tag:amenity%3Datm

**Comment by westnordost** [comment]
Makes sense. Is there a list of bank operators (by country) somewhere? Perhaps iD has it?

**Comment by Etua** [comment]
@westnordost As I remember iD suggested some network names for me but they were the same for the whole world or at least not correct for my country. I tried to add that key about two months ago so maybe something had been changed since then.

**Comment by matkoniecz** [comment]
iD suggests the most commonly used values - so likely they have no special logic for atm operators

**Comment by PanierAvide** [comment]
Not a complete list, but still a start: [all entities in Wikidata in bank industry](http://tinyurl.com/kowcxep).

**Comment by Hillside502** [comment]
@PanierAvide 
Why the tinyurl link?
Please be transparent by supplying the original link.

**Comment by PanierAvide** [comment]
The complete link of wikidata is very long, like `https://query.wikidata.org/#%23Cats%0ASELECT %3Fitem %3FitemLabel %3Fcountry %3FcountryLabel%0AWHERE%0A{%0A%09%3Fitem wdt%3AP452 wd%3AQ22687 .%0A%09%3Fitem wdt%3AP17 %3Fcountry .%0A%09SERVICE wikibase%3Alabel { bd%3AserviceParam wikibase%3Alanguage "en" }%0A %09SERVICE wikibase%3Alabel {%0A %09 %09bd%3AserviceParam wikibase%3Alanguage "en" .%0A %09%3Fcountry rdfs%3Alabel %3FcountryLabel%0A }%0A}`. The tiny URL was given by the wikidate query interface itself, no weird magic intended.

**Comment by Etua** [comment]
Also more preferable input should be an universal operator like Euronet than a specific bank (when possible). Suggesting the bank in the first place can lead to semi-false positive when the ATM is located near the bank (for example on the wall of the bank branch).

**Comment by Hillside502** [comment]
@Etua 
Another example:-
LINK (UK) - Wikipedia, the free encyclopedia
https://en.wikipedia.org/wiki/LINK_(UK)

**Comment by Etua** [comment]
So we can proceed in such order:

1. International operators;
2. universal (for a few banks) operators but more country specific;
3. banks out of big networks with lots of ATMs;
4. the rest only written manually or added in some time;

The sooner localized quests will be developed the better. Also distribution of the tag will be helpful in the current and further work.

**Comment by Etua** [comment]
@westnordost Should we aplly this quest only inclusive to some countries, do it in a manner of sports quest (specified operators first) or choose some kind of mix of these two?

**Comment by westnordost** [comment]
Banks that have ATMs are quite international usually. We need a suggestion list of known operators (perhaps josm/iD has one) and show it for when the user starts typing. So the user is able to input another operator but can choose from a list.
Sorting this list by country is probably too much work.

On August 3, 2017 1:57:06 PM GMT+02:00, Etua <notifications@github.com> wrote:
>@westnordost Should we aplly this quest only inclusive to some
>countries, do it in a manner of sports quest (specified operators
>first) or choose some kind of mix of these two?
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/westnordost/StreetComplete/issues/203#issuecomment-319948386

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by krzyk** [comment]
@westnordost Not in Poland, there are few banks that have international presence, local banks might be owned by bigger international banks, but have their own branding that is almost unknown outside the country.
AFAIR none of the top 10 banks has presence outside the country (or they have only in neighboring countries).

The only ATM operator that is international is Euronet which is a netowork of ATMs (not a bank).

**Comment by Etua** [comment]
@krzyk @ westnordost Maybe we should splot the list of international operators (not very long and shown everywhere) and local operators/banks with their own ATMs shown in a specific country. That way the quest would easily become avaible in most of the places, but the list wouldn't be full of small companies that the user could have never heard of from other countries.

**Comment by hsimpson00** [comment]
Hi, this would be a very good quest!
I also have an extenson for this:
In Germany, most banks are oragnized in Networks which allow the customers to get their money free from every atm in this network.
Some Examples:
CashPool for the Private Banks
Bankcard-Servicenetz for the Volksbanken-Raiffeinsenbanken
Sparkassenverbund for the Sparkassen

Since sometimes you cannot idenity a bank to a service-network only by its name, this Tag is a goos help to find the right ATM.

There are also banks with are part of more than one network.

For more information: http://wiki.openstreetmap.org/wiki/Tag:amenity%3Datm

Regards

**Comment by Etua** [comment]
Over 6 months have passed and still we did not manage to provide a complete list. Therefore I think we should make this quest available only in countries with known data and add more entries over time.

**Comment by ENT8R** [comment]
I did some analysis and created a list of all ATM operators in the world sorted by how often they are used in OSM. The complete list can be found at https://gist.github.com/ENT8R/4c6dac6b112adacea40ee013719f7ec2 but I think maybe only the first 500-700 values (out of about 14000) are worth to be included in this app...

**Comment by Etua** [comment]
@ENT8R Great work, thank you. This list highlights one thing: how inconsistent the naming is in OSM, so you have "Euronet" (1530) and "Euronet Sp. z o.o." (1436), "ING" and "ING Bank" and the list goes on... For such cases we should choose one version and change the rest directly or solve it the same way as "ambiguous values" in sport quest.

**Comment by ENT8R** [comment]
The gist contains now a second file which has all operator sorted by the countries in which they appear.
See https://gist.github.com/ENT8R/4c6dac6b112adacea40ee013719f7ec2#file-atm_operators_by_country-json for the complete list

**Comment by Etua** [comment]
@ENT8R I'm going to group list for Poland into major operators/banks with suggested global name and all current ambiguous/incorrect values that describe them. Whole list has ~420 entries so I won't post it immediately. Such contribution for other countries from people with local knowledge would be encouraged.

**Comment by Etua** [comment]
@matkoniecz I've seen you had done some massive edits before, would you help in unifying multiple names for the same operators after proper lists will be created?

**Comment by matkoniecz** [comment]
> would you help in unifying multiple names for the same operators after proper lists will be created

I am not planning to work on collecting data for "operators of XYZ", beyond collecting raw OSM data - but @ENT8R did it already.

**Comment by Etua** [comment]
For now about half of the list is processed: https://gist.github.com/Etua/fd58cdd9392d7beb2eb2b3829d2c8850

**Comment by westnordost** [comment]
Should be unblocked now by https://github.com/westnordost/osmfeatures

**Comment by westnordost** [comment]
Turns out that iD does not have presets for ATMs, only for banks. But there is for example "Euronet" which is not a bank but an operator of ATMs.

For implementing this, we should do another SPARQL query that lists all the **popular** (more than x usages) operators for ATMs by country and maybe put this information into a YAML meta information file.

The UI should be a free input text field with autosuggestions/-completions for the known operators.

**Comment by matkoniecz** [comment]
> This list highlights one thing: how inconsistent the naming is in OSM, so you have "Euronet" (1530) and "Euronet Sp. z o.o." (1436), "ING" and "ING Bank" and the list goes on...

"Euronet Sp. z o.o." (1436) is now fixed by https://wiki.openstreetmap.org/wiki/Mechanical_Edits/Mateusz_Konieczny_-_bot_account/fix_overly_verbose_Euronet_Sp._z_o.o.

If you see any other so popular duplicates in Poland I may also fix them, if you have support from you local community and want to run bot edit - this page contains full source code needed.

**Comment by HolgerJeromin** [comment]
fixing link (missing dot)
[https://wiki.openstreetmap.org/wiki/Mechanical_Edits/Mateusz_Konieczny_-_bot_account/fix_overly_verbose_Euronet_Sp._z_o.o.](https://wiki.openstreetmap.org/wiki/Mechanical_Edits/Mateusz_Konieczny_-_bot_account/fix_overly_verbose_Euronet_Sp._z_o.o.)

**Comment by westnordost** [comment]
![Screenshot_1602522913](https://user-images.githubusercontent.com/4661658/95773717-4de3e580-0cbf-11eb-845b-ac328eed06ce.png)

**Comment by muralito** [comment]
Hi. ATMs have no bank name in Uruguay, Two ATM networks exists here ("Banred" and "RedBROU") and are mapped using network=tag. In the case of RedBROU the operator is "Banco de la República Oriental del Uruguay", and Banred in Banred network (formed by private banks)
