### ISSUE TITLE
Searching for certain quests results in error 

### ISSUE THREAD

**Issue by schwukas** [westnordost/StreetComplete#2032]
When searching for new quests in some area the process stops and an error message saying "Error when searching for quests. Try again later" (roughly translated from German). It seems to happen on the "price tag" symbol (I think it's something like "What's the name of this child care centre?") but may be similar for quests that are supposed to be downloaded after this failing one. The quests before that one have worked fine.

I _feel_ like this happened first with version 22.2 but I cannot say for sure. I've tried invalidating the quest cache along with several re-installs, some with clearing data in Android. 
I ran into the same problem with versions 22.1 and 22.0, however this may be due to corrupt data remains. As I said, I cleared app data but what do I know, maybe I forgot something or something was left on the device.

**How to Reproduce**
Zoom to an appropriate area and click on "Search for quests in this area". 

**Versions affected**
Android 10
StreetComplete v22.2 from F-Droid

I'm glad to supply further information if necessary.

**Comment by matkoniecz** [comment]
It sounds like #2007 that was fixed two days ago - https://github.com/westnordost/StreetComplete/issues/2007#issuecomment-674527614

It should be fixed v22.3 - see https://github.com/westnordost/StreetComplete/releases/tag/v22.3 (it contains solely fix for that F-Droid specific bug).

**Comment by schwukas** [comment]
It's not available in F-Droid as of now but installing directly from the apk fixed the problem. Sorry for the duplicate :)

**Comment by matkoniecz** [comment]
Just remember to switch to F-Droid later to get new updates :)
