### ISSUE TITLE
House-Level Quest: Use comma and dot key to jump to the next field

### ISSUE THREAD

**Issue by RubenKelevra** [westnordost/StreetComplete#2037]
**Use case**
Current you need to hit the second field in the pop-up. It would be easier, especially on larger phones to just tap dot and/or comma to jump to the next field.

Those buttons have no function currently and it is safe to assume that they never will.

![Screenshot_20200820-121627](https://user-images.githubusercontent.com/614929/90758522-72cf6400-e2df-11ea-9bd6-8c9580ede781.jpg)

**Comment by smichel17** [comment]
On my phone (w/ Swype keyboard v1.8, that comes pre-installed on some Samsung phones), the equivalent of the green button on your screenshot displays the text "next" and already has this functionality.

**Comment by westnordost** [comment]
yes, if you enter the first textfield, tapping the enter/next/go button should bring you to the next textfield. If not, your keyboard app is really bad because this is somewhat of a basic functionality.

**Comment by michaelblyons** [comment]
I'd like to restate that iD has autocomplete for half-levels of building and roof levels (`0.5`, `1`, `1.5`, `2`, `2.5`, ...), so please do not use the `.` for special purposes.

**Comment by westnordost** [comment]
Ok I'm closing this anyway, see the last comment(s). Going to the next input field is possible via the next button
