### ISSUE TITLE
Road chosen for the surace quest may not show fully

### ISSUE THREAD

**Issue by Etua** [westnordost/StreetComplete#204]
I have read #50 but his case is slightly different because the road chosen for the surface quest may not show correctly depending on the zoom level. The example is present in the pictures.
![screenshot_20170509-002701](https://cloud.githubusercontent.com/assets/13040148/25828146/fcb50654-344e-11e7-99a0-77fd90c15649.png)
![screenshot_20170509-002654](https://cloud.githubusercontent.com/assets/13040148/25828154/065e7708-344f-11e7-8998-be46ee38db07.png)

**Comment by Natenom** [comment]
Same problem here.

**Comment by westnordost** [comment]
This seems to be a tangram-es issue, but I do need the exact location where this happens so I can reproduce this. (Because I never saw this effect before). Hope you didn't solve this quest yet. 

Also, what is your Android version?

**Comment by Etua** [comment]
@westnordost I saw this quest here: https://www.openstreetmap.org/#map=15/52.2721/20.8478 Unfortunatelly it is already solved. My Android version is 7.1.1 (LineageOS 14.1)

**Comment by matkoniecz** [comment]
The same happened for me, I will try to reproduce.

**Comment by matkoniecz** [comment]
To reproduce: highest possible zoom at http://www.openstreetmap.org/way/238530360 or http://www.openstreetmap.org/way/25123462

Select surface quest. Zoom level is not changing, not entire object is visible.

Android 6.0.1 MMB29M

**Comment by westnordost** [comment]
Can you attach a screenshot? I cannot reproduce this on my device.

**Comment by matkoniecz** [comment]
![screenshot_2017-05-10-18-39-21-533_de westnordost streetcomplete](https://cloud.githubusercontent.com/assets/899988/25910453/b11edbb2-35b0-11e7-8fcf-eade0060028e.png)

**Comment by westnordost** [comment]
Eh, what? This is not the issue that was reported here. The issue was that part of the blue highlight way was not shown depending on the zoom level!

**Comment by Natenom** [comment]
Screencast: https://files.natenom.com/nidx/nobackup/bug204.mp4

**Comment by westnordost** [comment]
Thank you Natenom!

**Comment by westnordost** [comment]
Natenom, which Android version are you using?

**Comment by westnordost** [comment]
The related tangram issue is fixed and has been released. If you can still reproduce this issue with 0.11, please reopen this bug.

**Comment by HolgerJeromin** [comment]
I don't see the ends of the selected way for a surface quest. But I would like to see them to be sure the way is correct. 
Android 6 with app version 0.11

**Comment by matkoniecz** [comment]
@HolgerJeromin As defined in https://github.com/westnordost/StreetComplete/issues/204#issuecomment-300545578 this is a separate issue, so it may be worth reporting it in separate ticket if that was not done already
