### ISSUE TITLE
Adding access to barrier 

### ISSUE THREAD

**Issue by HolgerJeromin** [westnordost/StreetComplete#2040]
### General
Affected tag(s) to be modified/added: [foot](https://wiki.openstreetmap.org/wiki/Key:foot) and bicycle
Question asked: **Can this bollard passed via foot and via bicycle?**

### Checklist
Checklist for quest suggestions (see guidelines):
- [x] 🚧 To be added tag is established and has a useful purpose
- [x] 🤔 Any answer the user can give must have an equivalent tagging (Quest should not reappear to other users when solved by one)
- [x] 🐿️ Easily answerable by everyone from the outside but a survey is necessary 
- [?] 💤 Not an overwhelming percentage of elements have the same answer (No spam)
- [x] 🕓 Applies to a reasonable number of elements (Worth the effort)

Only 40% has foot on node bollards

https://taginfo.openstreetmap.org/tags/barrier=bollard?filter=nodes#combinations

### Ideas for implementation

**Element selection:** 
barrier=bollard without foot=* and bicycle=*

**Metadata needed:** 

**Proposed GUI:**

I am not sure if foot and bicycle should be asked at once.

* both are possible -> foot=yes, bicycle=yes 
* by foot only  -> foot=yes, bicycle=no
* by bicycle only  -> foot=no, bicycle=yes
* not public  -> foot=private, bicycle=private

**Comment by westnordost** [comment]
well, a bicycle barrier is a physical barrier but has been put there by the muncipality, so one can argue that the muncipality also doesn't want bicyclists on that piece of way.

But anyway, @HolgerJeromin please show us some examples of bollards that would not be traversable on foot or bicycle.

**Comment by HolgerJeromin** [comment]
cc @flohoff as this is one of his favorite nit picking :-)

**Comment by matkoniecz** [comment]
I agree that tagging access on bariers may be usedul, but in specific case of `barrier=bollard` asking this is pointless as all bollards will allow passage of pedestrians and cyclists.

**Comment by westnordost** [comment]
I am closing this as will not fix. Can't think of any bollard that would not let pedestrians/cyclists through.
And even if there are, it would be a very very low percentage.
