### ISSUE TITLE
Connection error while scanning for quests: try again later

### ISSUE THREAD

**Issue by DamienCassou** [westnordost/StreetComplete#2042]
**How to Reproduce**

1. Open the menu
2. Click "Scan for quests herer"

The first 2 or 3 quests happily downloads. The next one triggers an error:

> Connection error while scanning for quests: try again later

**Versions affected**

- v22.2 from f-droid
- LineageOS 16.0 from July 23rd, Android 9, on OnePlus 1

**Comment by alanz** [comment]
Until this actually lands on f-droid, I think it would make sense to re-open this, and pin it.

See e.g. #2048

**Comment by matkoniecz** [comment]
I am not sure whatever people not checking changelelog/releases/closed issues would check pinned issues. And AFAIK it is possible to pin closed issue.

**Comment by smichel17** [comment]
I'm someone who does check both, but even still, sometimes I catch myself starting to write a new issue before I remember to search (or: after I search but realizing that I forgot to search closed issues, too).

For Red Moon I kept track of this with a "Next Release" milestone, to which I would assign issues that are done but not released. To do a release, I'd rename the milestone to the version of the release, close all the assigned issues, and then create a new "Next Release" milestone. Highly recommend this for any project that only had one latest version (it would not work for an api or library with multiple supported versions where the older versions get fixes/features backported). It helps with writing changelogs, too.

**Comment by muelli** [comment]
f-droid still hasn't updated their version :(
https://f-droid.org/packages/de.westnordost.streetcomplete/
weirdly enough, though, the metadata seems to be correct: 
https://gitlab.com/fdroid/fdroiddata/-/commit/8d4b6036b1524c3565b736cc4af8b80b8f52f242

maybe the f-droid infrastructure couldn't cope with the changed version name there :-/

**Comment by DamienCassou** [comment]
Someone from fdroid just told me:

> internal F-Droid build error (could not bring up vm 'builder_default) will be retried in the next cycle

**Comment by westnordost** [comment]
# Workaround for F-Droid users till you can update to v22.3

Go the settings and disable the _"What is the name of this place?"_ quest type (orange icon with white label). Then, the quest download should work again like usual.

**Comment by alanz** [comment]
Please post a note either here or in a changelog to remind us to undo the workaround :)

**Comment by DamienCassou** [comment]
Someone on F-Droid told me that F-Droid still faces internal errors.
