### ISSUE TITLE
Phone number for restaurants

### ISSUE THREAD

**Issue by bmaggi** [westnordost/StreetComplete#2043]
A quest to add phone number to restaurant (maybe extended to other place)

### General
Affected tag(s) to be modified/added: [phone](https://wiki.openstreetmap.org/wiki/Key:phone)
Question asked: **Is there a phone number for this restaurant X?**

### Checklist
Checklist for quest suggestions (see guidelines):
- [*] 🚧 To be added tag is established and has a useful purpose
-> Tag to be added [phone](https://wiki.openstreetmap.org/wiki/Key:phone) 
- [*] 🤔 Any answer the user can give must have an equivalent tagging (Quest should not reappear to other users when solved by one)
-> one phone is already present quest should not pop up
- [*] 🐿️ Easily answerable by everyone from the outside but a survey is necessary 
-> just a phone number
- [*] 💤 Not an overwhelming percentage of elements have the same answer (No spam)
-> different number for each restaurant 
- [*] 🕓 Applies to a reasonable number of elements (Worth the effort)
-> there is a reasonable number of restaurant ;)

**Comment by westnordost** [comment]
What to tag if the restaurant does not have a phone number?

**Comment by Cj-Malone** [comment]
`phone` or `contact:phone`?
What about when the phone number isn't obvious, if it's not on the fascia you have to go in (so quest disabled by default). And what if it's not even listed inside/on the menu, that doesn't mean there isn't a phone number.

I like the idea, but I don't think this fits with StreetComplete, a QA tool for armchair mappers may be a better place.

**Comment by westnordost** [comment]
My question was:

What to tag if the restaurant does **NOT** have a phone number?

**Comment by rhhsm** [comment]
I think it's weak on the "Easily answerable by everyone from the outside but a survey is necessary" criterion. I would have to answer many of such quests with "I don't know" as I think not many restaurants show their phone number from the outside (so not easily answerable). It's more suitable for armchair mapping, looking up the number from the restaurant's website (so survey not necessary).

**Comment by bmaggi** [comment]
As far as I can tell most of the restaurant I see have their phone number written outside.
-> that said, no idea on how to prove that with data...

> My question was:
> 
> What to tag if the restaurant does **NOT** have a phone number?

No idea.  I don't see any recommandation for [phone](https://wiki.openstreetmap.org/wiki/Key:phone) 

But I also don't see recommandation for [opening hours](https://wiki.openstreetmap.org/wiki/Key:opening_hours)
 
What is the effect of choosing "No open hours printed" ?

**Comment by westnordost** [comment]
> What is the effect of choosing "No open hours printed" ?

Well, it is far more likely that a shop will have some opening hours printed on the door than it will have a phone number. In the rare cases it isn't, the user does have the possibility to add instead "irregular opening hours" (f.e. `opening_hours="ask at pub next door"`) or to add the information that the opening hours are not signed (`opening_hours:signed=no`).

Given that `phone:signed` has no usages currently, is not documented and would likely be used far more often than `opening_hours:signed=no`, I won't add this. Think of shops outside of (Western) Europe, Asia, Africa,... 

However, I am all for using something like `phone:signed` or similar to allow for this quest to be implemented (though it should probably only be activated in certain countries?). Feel free to create a proposal in the wiki for it, you'll have my vote.

**Comment by westnordost** [comment]
So, feel free to reopen this when/if a tagging for this is approved but for now this is not eligible.

Also, when we'd actually implement this, we'd need a list of places where it makes sense to ask. For example it will probably not be worth to ask for kiosks and convenience stores, but for hotels and other types of shops it would.

**Comment by goldfndr** [comment]
This might be further narrowed by only asking if it has a tag of `delivery` or `takeaway` or `reservation` that isn't `no`.
