### ISSUE TITLE
Inconsisten surface quest icons

### ISSUE THREAD

**Issue by HolgerJeromin** [westnordost/StreetComplete#2046]
Not really a bug, but some surface icons have an magnify lens on top and some not.

![rps20200823_190826_476](https://user-images.githubusercontent.com/2410353/90984244-10db5c80-e574-11ea-95c3-66a0a12feb9e.jpg)

Why this inconsistency?

**How to Reproduce**

**Versions affected**

v22.3

**Comment by westnordost** [comment]
It is a different quest.

**Comment by matkoniecz** [comment]
And to be more specific - one with magnify ask about specific surface where currently unspecific `surface=paved` or `surface=unpaved` is tagged
