### ISSUE TITLE
Building type for Cabins

### ISSUE THREAD

**Issue by StackKorora** [westnordost/StreetComplete#2047]
**Use case**
The problem I'm trying to solve is that building quests for cabins at camping grounds. I am aware that cabins were removed and there was conversation two years ago, however, I'd like to revive the conversation please.
https://github.com/westnordost/StreetComplete/pull/774

On May 31, 2018 westnordost in the link above said:
removed cabin - definition unclear, not well defined what is the difference to bungalow (small holiday/garden/summer home or dacha), shed (small building for tools), hut (crude/simple shelter or dwelling)

I would claim that the difference between bungalow and cabin is negligible. Thus, one potential solution is to add cabin to the bungalow description in parenthesis. However, where I think this will cause confusion is that in the U.S. bungalow is not a common term. However, in all the national and state parks that I've been to (quite a few) that offer these types of accommodations, the term used is cabin. Where this also gets a little muddled is that there are camping cabins with full amenities and there are mutli-family camping cabins. Some of my preferred camping cabins are single room and there's only one door the four walls. However, I've stayed at a six (!) room 2 full-bathrooms camping cabin in the mountains before and that was the largest of the cabins on the state park grounds where the single and dual rooms were more common. Thus, in my opinion, the biggest difference between bungalow being a generic get-a-way building and a cabin is the location of cabins both in the geographic North America term sense as well as the "hidden in the woods on a mountain or some other nature environment like a national or state park". 

A shed is a small building for tools. Most of the modern cabins at campgrounds have power, air conditioning, beds, ect. However, running water and bathrooms is rare as there is usually a shared common bathroom for the camp.

A hut is more likely to be made of sticks, grass, and mud with dirt floors. Arguing the difference between a hut and a cabin from like the early 1800's that is still standing as a historical piece is a pretty close call as cabins from then were pretty basic. But modern cabins (last 100+ years) I would contend have no likeness to huts.

**Proposed Solution**
Personally, I'd like to see a building type of Cabin. Even if it is just regionally shown in North America.

However, if bungalow is the preferred term by the community then I'd like for that to be clear in the description of a bungalow. 

I hope I've made things more clear. Thank you for your time listening to my feedback. :-)

**Comment by westnordost** [comment]
Thank you for the explanation. So you define a bungalow as a "fancy cabin" and a a cabin as a "holiday hut"?

Am I right in that you do not consider a small dwelling that is similar to a cabin but not a cabin to be a "hut" because you imagine some kind of primitive (tribal) dwelling under "hut"?

In my book, a hut is a small primitive dwelling. No, not only the round primitive hut in Africa, but also small buildings that would be suitable as a dwelling (i.e. not a shed). A tiny house would fall under that definition. A mobile home in a trailer park would be one (if there wasn't already another tag for that).

**Comment by smichel17** [comment]
I can confirm that "bungalow" is not common parlance in the (northeastern) US. While I have an idea of a bungalow as an outdoorsy building, something like a cabin or hut, I couldn't give you a definition precise enough that I would be comfortable tagging something as "this is a bungalow" - at least, not without looking up the definition first.

**Comment by westnordost** [comment]
And "hut"?

Am 24. August 2020 03:48:13 MESZ schrieb smichel17 <notifications@github.com>:
>I can confirm that "bungalow" is not common parlance in the
>(northeastern) US. While I have an idea of a bungalow as an outdoorsy
>building, something like a cabin or hut, I couldn't give you a
>definition precise enough that I would be comfortable tagging something
>as "this is a bungalow" - at least, not without looking up the
>definition first.

**Comment by StackKorora** [comment]
Greetings @westnordost 

Thanks for your time and feedback. I fully admit that these terms are tricky. :-D

While there can be fancy cabins that blur the definition between bungalow and cabin, it has been my experience that cabins do not offer all of the same amenities as a bungalow. For instance, the one I recently stayed in had no air conditioning but had heat (high in the mountains), the only kitchen/cooking area was a firepit outside with a picnic table, bathrooms were a shared facility, no running water, and the "bed" was a wall pull down shelf for a sleeping bag (slightly better than sleeping on the hardwood floor! :-D ). However, it was very well built withing the last 10 years, had power, and even a repeater on the roof for wifi!

Where I personally would draw the line on this cabin and a hut would be if there was a dirt floor, very simply built, and no heat/electricity.

So I guess, I am in complete agreement with you. :-D

Defining the difference between the two when there are so many variations I think is going to be next to impossible. Thus, after thinking about this a little more I think I personally would like to take my stance on this being a regional (North America) term. If a place I'm staying at lists the simple dwellings as "cabins on the mountains" then I would prefer that all of those buildings be tagged as cabin. I recently passed by a place that listed itself as "a cabin village" and all of the buildings were small buildings that looked like typical cabins. Again, I would argue that each of those should be tagged as a cabin.

That's my preference anyway. I really just would prefer not having someone mis-categorize these cabins as something that doesn't fit but is kinda-close when there is a building definition of cabin. :man_shrugging: 

Thank you!

**Comment by westnordost** [comment]
>  it has been my experience that cabins do not offer all of the same amenities as a bungalow. For instance, the one I recently stayed in had no air conditioning but had hea

Well, that's maybe the problem here. The quest is only to determine the building type, not the amenities within. So, luxury condos are `building=apartments`, and also tenement block in the ghetto are `building=apartments`. 

Whether a hut has a dirt floor or not, well, that would be kind of a weirdly specific line to draw.

Interestingly, if you look up the the translation from the German word "Hütte" (=hut), _cottage_ (small house), _shack_ (shed) and _cabin_ (holiday hut) come up next to hut as a result. So, to my understanding, a cabin is a type of hut - a hut made usually of raw logs, usually in the woods, sometimes as a holiday-home, but still a hut.

But anyway, I think we are not getting anywhere like this. How about the description for hut was to be extended or changed, to be more inclusive all all "small simple buildings made for people"?

**Comment by smichel17** [comment]
> And "hut"?

Coming to answer this, I realized I didn't have a concrete definition of hut or cabin, either. (So, disclaimer: this is heavily personal opinion and is more likely to reflect on my lack of knowledge than anything else.) I would still be comfortable adding those tags; it's more of a "I'll know it when I see it" situation (whereas I'm not that confident about a bungalow). They are both residential buildings in areas that are close to nature (forests, mountains, beaches…). My impression in general is that a hut is more rustic than a cabin (less likely to have plumbing/electricity/internet/etc). I probably would not call anything mud walls or a grass roof a cabin, but I might call it a hut — and generally I associate huts more with warm climate and cabins with cool. Not all cabins are made with raw logs, or else we wouldn't have the particular (relatively common — here I do feel comfortable generalizing) term *log cabin.* (There are also cabins and even houses that *look* like a log cabin on the outside but are actually "modern construction" on the inside — I would not call these log cabins.) I *think*, but am very unsure, that a hut tends to be a more permanent residence, where a cabin is more often a vacation or seasonal home — but that might just be modern norms, not actual definitions.

**Comment by StackKorora** [comment]
Greetings,

I've now asked several groups and sent a few emails. Everything I've gotten back is inconclusive and no one (outside of this conversation) seems really interested in taking a firm position. I don't want this ticket to just languish for who-knows-how-long. So...

* I personally would still like a cabin option, even if it is an option only for North America.
* If that isn't the preference for StreetComplete, then under the hut option could a `(or cabin)` be added?

Thank you!

**Comment by westnordost** [comment]
Actually, I had a look at the available options again, and for the described cabins, wouldn't "bungalow" be the correct selection? Described as "small detached house (summer house, holiday cottage, ...)"
