### ISSUE TITLE
Ask for extra confirmation if entered name looks like a note text

### ISSUE THREAD

**Issue by matkoniecz** [westnordost/StreetComplete#2050]
**Use case**
People sometimes make a mistake and instead of creating note enter a name.

Recent examples from Poland: 

`name=Nie ma punktu ksero` ("this copyshop is not existing") https://www.openstreetmap.org/node/6362552776#map=19/51.11399/20.86149
`name=Nie ma nazwy` ("Road without name") https://www.openstreetmap.org/way/8147292
`name=Nieistniejąca droga` ("nonexisting road")

I remember that I added
`name=To nie jest centrum sportowe, to co najwyżej boisko a i to jest wątpliwe bo zarasta` ("it is not a sport center, it is a soccer pitch and even that is dubious as it is overgrowing"

**Proposed Solution**
Ask for extra confirmation if name includes "not existing", "nonexisting", "this is not" and their translations such as "nie istnieje", "nie ma", "niestniejące".

Triggered by https://forum.openstreetmap.org/viewtopic.php?pid=798818#p798818

**Comment by westnordost** [comment]
Nah, I don't think so. Then the app would need to check this for every free-text input field. The app very clearly asks for the name and also offers to leave a note instead. Also, there is a tutorial at the start. So, it is really quite obvious that one should not just write free text into the name field.
Your example are also both the same user, so better contact him about it.
