### ISSUE TITLE
Ability to create profiles

### ISSUE THREAD

**Issue by Norwi** [westnordost/StreetComplete#2054]
**Use case**
I use Streetcomplete in a lot of different situations. But if I am in the passenger seat of a car, I need different quests (and a different prioritisation) than when I am strolling through the streets or using public transport. And sometimes I just want to do a specific set of quests.
Therefore, it is a bit annoying to always search for the quests in the settings and sort it according to the current situation or mode of transport. A simple click but be a lot easier and faster.

**Proposed Solution**
It would be really nice to have different profiles (I don't know if you can use that word in English the same way as in German but I can't think of a better term) or settings that you can simply click and that changes the quest filter/order. Each profile has the same interface as the normal quest sorting that is now in place. And of course naming of the profiles should be available.

**Cheap Mockup**
![github_profiles](https://user-images.githubusercontent.com/18899671/91500945-d69bf300-e8c4-11ea-9c4d-0aaf21dc95c9.png)

**Comment by matkoniecz** [comment]
#1654?

**Comment by westnordost** [comment]
Yes, this is a duplicate. Thank you for that nice mockup though!
