### ISSUE TITLE
connexion error when loading new quests

### ISSUE THREAD

**Issue by petitminion** [westnordost/StreetComplete#2056]
When I have all.the.quests activated in the.option I.got a connexion error when the app try to.load new.quests. "error while fetching new quests. Try again later"

Diseable the quest "what is.the name of this.place?" resolve the issue. 

Runing on lineage os 17.1

**Comment by matkoniecz** [comment]
Are you running F-Droid? Then it is https://github.com/westnordost/StreetComplete/issues/2007

Fix is released but F-Droid still failed to process it.

# Workaround for F-Droid users till you can update to v22.3

Go the settings and disable the "What is the name of this place?" quest type (orange icon with white label). Then, the quest download should work again like usual.
