### ISSUE TITLE
Content of signs - multiselect possible?

### ISSUE THREAD

**Issue by hmartink** [westnordost/StreetComplete#2059]
Yesterday I got a quest I haven't seen before, namely I was asked what the sign displays (my UI is german, so excuse my rough translation). I think this quest is quite valuable so I wanted to provide the content.

The UI gave me a variety of options, like history, plants, ... (I did not note them down). Since the sign in question had quite some information, I wanted to select those categories which are relevant. However, I could only choose one category. This was disappointing, as I had to choose one of several relevant options. I chose the one with the most visual space on the sign (and hopefully the most relevance to readers).

I think it should be possible to select all categories relevant. There a lots of signs where information is given on various topics, like plants, history, travel information etc. If this should be not possible at all (due to limitations in OpenStreetMap), then at least the GUI should clearly state that the most relevant should be selected, but hopefully the former solution can be implemented.

**Comment by westnordost** [comment]
Looking at taginfo, it doesn't really seem to be intended to be used like that. Do you have a photo or examples of such signs?

**Comment by westnordost** [comment]
no answer
