### ISSUE TITLE
v23.0-alpha1: Unable to reach the authorization server

### ISSUE THREAD

**Issue by strct** [westnordost/StreetComplete#2062]
**How to Reproduce**

1. go to profile
2. click on login
3. enter credentials
4. click "Grant access"
5. see error message "Unable to reach the authorization server"
   ![576-1024](https://user-images.githubusercontent.com/48618304/91906387-63b9c000-eca8-11ea-85eb-4bb5630a6d64.png)

**Versions affected**

Only `v23.0-alpha1`, not the fdroid version 23.2

**Unrelated**
The resurveying of opening hours seem to work and are fun to answer :)

**Comment by matkoniecz** [comment]
Is www.openstreetmap.org working at the same time when you get this error? OSM website has some intermittent outages.

**Comment by strct** [comment]
The osm permission page is loading before the error occurs.
![576-1024](https://user-images.githubusercontent.com/48618304/91907610-7208db80-ecaa-11ea-9296-83621ab4f231.png)
And I double checked:
1. installed v23.0-alpha1 and notice error
2. reinstalled fdroid version, login works
3. reinstalled v23.0-alpha1 version and error occured again.

**Comment by Carnildo** [comment]
I can reproduce this bug: something changed between 16.0 and 23.0a1 that prevents me from logging in with the new version.  If I log in with the old version and upgrade, everything works fine.

**Comment by Helium314** [comment]
I have the same problem in 23.0-alpha1 and some self-compiled debug version of 22.3 (didn't try other versions).

**Comment by strct** [comment]
I can login with version 23.3 from Github (and still not with 23.0a1).

**Comment by westnordost** [comment]
Weird, I really didn't change anything in regards to login.

**Comment by westnordost** [comment]
Okay, I found how to fix it, but I don't understand how this could have happened or how this could ever worked before. Apparently an Android SDK function now behaves differently as before (`URLUtil.isValidUrl`)

**Comment by smichel17** [comment]
That was added here, previously the valid check was intended but not actually implemented: https://github.com/westnordost/StreetComplete/pull/2029#discussion_r471578615

**Comment by Quix0r** [comment]
22.2 from F-Droid (latest version available there) is also affected by this bug. Just to mention it.

**Comment by Quix0r** [comment]
22.2 from F-Droid (latest version available there) is also affected by this bug. Just to mention it.
