### ISSUE TITLE
v23.0-alpha1: opening hours on nameless places crashes the app

### ISSUE THREAD

**Issue by Helium314** [westnordost/StreetComplete#2063]
When trying to answer opening hours, the app crashes if the shop has *noname=yes*.
I am not sure, but I think it might have to do with https://github.com/westnordost/StreetComplete/pull/2012#pullrequestreview-474681722, where `?: featureName.value` was removed from AddOpeningHours.kt and *quest_openingHours_no_name_title* now only gets an empty array for %s.

**Comment by westnordost** [comment]
Thank you for testing!
