### ISSUE TITLE
Wiki: wrong overpass query for quest "What street does the (house) number […] belong to? "

### ISSUE THREAD

**Issue by Bibi56** [westnordost/StreetComplete#2072]
On https://wiki.openstreetmap.org/wiki/StreetComplete/Quests, row "What street does the (house) number […] belong to?", second column, we have an outdated (overpass-turbo) link.

Two possibilities:

- updated the link (`addr::housenumber` member of a relation ``associatedStreet` should be excluded as in the real quest).
- fallback: remove the link which would prevent usage in other tools like JOSM :-(.

**Comment by westnordost** [comment]
Thanks for notifying us but the wiki and keeping it up-to-date is not really part of this project. @rugk often keeps it up to date who is hereby pinged.

**Comment by rugk** [comment]
For problems about the wiki please [use the discussion page of the wiki itself](https://wiki.openstreetmap.org/wiki/Talk:StreetComplete/Quests), the issue tracker on GitHub is not meant for this.
Also [seeing your other comment](https://github.com/westnordost/StreetComplete/issues/213#issuecomment-687109784) it seems you thought the same Overpass query as on the wiki is the same as in the app.

**Currently** this is not the case and several of them are outdated. To reduce the maintenance burden, [there is the idea](https://wiki.openstreetmap.org/wiki/Talk:StreetComplete/Quests#Future_of_Overpass_queries) to auto-generate those on a special wiki page.
If you want to help there, feel free to do.

In any case, please continue this discussion in the wiki if you are interested. (or update the Overpass queries there, for now)
