### ISSUE TITLE
Congrats on the grant for map maintenance! 🎉

### ISSUE THREAD

**Issue by RayBB** [westnordost/StreetComplete#2075]
I just saw that you were awarded a grant to keep working on street complete:
https://wiki.openstreetmap.org/wiki/Microgrants/Microgrants_2020/Proposal/Map_Maintenance_with_StreetComplete

This is a really awesome project and I'm happy for you! I think you do a great job making it fun and easy to contribute.

Best of luck ~~

**Comment by westnordost** [comment]
Thank you! It is actually done already, just in Alpha right now. You can download it here: https://github.com/westnordost/StreetComplete/releases

I plan to create a beta release after this weekend or so.

The main ticket for it is here: https://github.com/westnordost/StreetComplete/issues/1998
