### ISSUE TITLE
Cache invalidated earlier than expected

### ISSUE THREAD

**Issue by matkoniecz** [westnordost/StreetComplete#208]
I set cache size to is maximum possible value (250 mb) as I edit on place where basemap is very stable, almost without OSM edits making visible changes and I have disabled mobile internet.

Today, during walk I discovered that tiles near my home are invalidated and I was unable to view map

I am not sure whatever cache size passed over 250mb and tiles are now starting to become invalidated or map cache may decided to invalidate tiles for other reasons.

In the second case I would prefer to update cache as new tiles are downloaded rather than delete leaving me without map.

If cache has grown over maximum limit - I would like to increase cache to greater value, over 250mb and to change cache invalidation strategy to invalidate unused tiles before throwing out ones used very often.

**Comment by matkoniecz** [comment]
Changing maximum value is easy - just change https://github.com/westnordost/StreetComplete/blob/60042171ad155ddbc294c97b5b5cf495a8e68635/app/src/main/res/xml/preferences.xml#L48 but I am not entirely sure whatever there is some other way for cached tiles to become invalid except going over map cache limit (I suspect there is some additional invalidation method - I would be surprised to discover that I already have 250mb of map in cache).

**Comment by matkoniecz** [comment]
For now I found https://mapzen.com/documentation/tangram/android-sdk/0.4.9/com/mapzen/tangram/HttpHandler.html that is not explaining its cache strategy.

**Comment by matkoniecz** [comment]
I tried to find source code for https://mapzen.com/documentation/tangram/android-sdk/0.5.0/ to check how cache works but failed for now.

**Comment by matkoniecz** [comment]
Iff my chase to the cache implementation is correct it has at https://github.com/square/okhttp/blob/87bf21311930d734507aaad25076c1302da828b4/okhttp/src/main/java/okhttp3/internal/cache/DiskLruCache.java

> If a value is returned, it is moved to the head of the LRU queue

What is surprising given that the recently used map tiles were not visible without Internet connection.

**Comment by matkoniecz** [comment]
#209 basically removes upper limit of map cache size setting

**Comment by westnordost** [comment]
Basically, as you probably found out by the research by yourself, StreetComplete (and neither tangram-es) does have a big influence over what things in the cache get invalidated first.

**Comment by westnordost** [comment]
So, I will close this one
