### ISSUE TITLE
Map tiles do not load load

### ISSUE THREAD

**Issue by UristMacGitHub** [westnordost/StreetComplete#2080]
The map tiles do not load, it only show the vert big picture and it is not possible to load closer when zooming.

Zooming is enough to reproduce it on my phone. Changing map cache size does not affect the problem.

OSComplete 17.3, Android 9

**Comment by matkoniecz** [comment]
Sorry for obvious question  - but is internet working for other apps on your phone?

**Comment by matkoniecz** [comment]
SComplete 17.3 - that is a very old version, can you update to more recent one?

**Comment by matkoniecz** [comment]
@Akasch is your tile server even supposed to be running or is it officially shutdown?

**Comment by westnordost** [comment]
In any case, you should simply update to the new versoin. The old version you are using is using the old tileserver, I don't know if the old tileserver even still exists.
