### ISSUE TITLE
Address number not shown on building (polygon)

### ISSUE THREAD

**Issue by TomislavParcina** [westnordost/StreetComplete#2081]
Address number not shown on building when tag is property of polygon. When tag is property of node it is shown.

**How to Reproduce**
Navigate to here https://osm.org/go/xdveCkaxu or anywhere else where there is polygon with street number and where is node with street number close to it. When you zoom street number that is property of node will show up. The street number that is property of polygon wont show up.

**Versions affected**
Android: 9
StreetComplete: v22.3

**Comment by HolgerJeromin** [comment]
This is an upstream issue tracked in
https://github.com/ENT8R/streetcomplete-mapstyle/issues/82

**Comment by westnordost** [comment]
(closing because not fixable by this app, upstream issue)
