### ISSUE TITLE
StreetComplete 23 crashes when upgrading from a very old version

### ISSUE THREAD

**Issue by Carnildo** [westnordost/StreetComplete#2085]
When upgrading from a very old version of StreetComplete (in my testing, 10.0 and 0.10), StreetComplete crashes on launch.

**How to Reproduce**
Install an old version of StreetComplete and run it.  Then upgrade to StreetComplete 23 and launch it.  StreetComplete will crash immediately.

**Versions affected**
Upgrading from 0.10 or 10.0 to 23.0-alpha1
Upgrading from 13.0 to 23.0-beta1

Not affected: Upgrading from 16.0 to 23.0-alpha1

**Stack trace when upgrading from 0.10 to 23.0-alpha1:**
09-01 13:11:35.856  9106  9106 E AndroidRuntime: FATAL EXCEPTION: main
09-01 13:11:35.856  9106  9106 E AndroidRuntime: Process: de.westnordost.streetcomplete, PID: 9106
09-01 13:11:35.856  9106  9106 E AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{de.westnordost.streetcomplete/de.westnordost.streetcompl
ete.MainActivity}: android.database.sqlite.SQLiteException: near "(": syntax error (code 1): , while compiling: SELECT name FROM pragma_table_info(?) WHERE name = ?
09-01 13:11:35.856  9106  9106 E AndroidRuntime:        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2416)
09-01 13:11:35.856  9106  9106 E AndroidRuntime:        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)
09-01 13:11:35.856  9106  9106 E AndroidRuntime:        at android.app.ActivityThread.-wrap11(ActivityThread.java)
09-01 13:11:35.856  9106  9106 E AndroidRuntime:        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
09-01 13:11:35.856  9106  9106 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:102)
09-01 13:11:35.856  9106  9106 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:148)
09-01 13:11:35.856  9106  9106 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:5417)
09-01 13:11:35.856  9106  9106 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
09-01 13:11:35.856  9106  9106 E AndroidRuntime:        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
09-01 13:11:35.856  9106  9106 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
09-01 13:11:35.856  9106  9106 E AndroidRuntime: Caused by: android.database.sqlite.SQLiteException: near "(": syntax error (code 1): , while compiling: SELECT name FROM pr
agma_table_info(?) WHERE name = ?
09-01 13:11:35.856  9106  9106 E AndroidRuntime:        at android.database.sqlite.SQLiteConnection.nativePrepareStatement(Native Method)
09-01 13:11:35.856  9106  9106 E AndroidRuntime:        at android.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:887)
09-01 13:11:35.856  9106  9106 E AndroidRuntime:        at android.database.sqlite.SQLiteConnection.prepare(SQLiteConnection.java:498)
09-01 13:11:35.856  9106  9106 E AndroidRuntime:        at android.database.sqlite.SQLiteSession.prepare(SQLiteSession.java:588)
09-01 13:11:35.856  9106  9106 E AndroidRuntime:        at android.database.sqlite.SQLiteProgram.<init>(SQLiteProgram.java:58)
09-01 13:11:35.856  9106  9106 E AndroidRuntime:        at android.database.sqlite.SQLiteStatement.<init>(SQLiteStatement.java:31)
09-01 13:11:35.856  9106  9106 E AndroidRuntime:        at android.database.sqlite.SQLiteDatabase.compileStatement(SQLiteDatabase.java:994)
09-01 13:11:35.856  9106  9106 E AndroidRuntime:        at de.westnordost.streetcomplete.ktx.SQLiteDatabaseKt.hasColumn(SQLiteDatabase.kt:73)
09-01 13:11:35.856  9106  9106 E AndroidRuntime:        at de.westnordost.streetcomplete.data.StreetCompleteSQLiteOpenHelper.onUpgrade(StreetCompleteSQLiteOpenHelper.kt:92)
09-01 13:11:35.856  9106  9106 E AndroidRuntime:        at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:256)
09-01 13:11:35.856  9106  9106 E AndroidRuntime:        at android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:163)
09-01 13:11:35.856  9106  9106 E AndroidRuntime:        at de.westnordost.streetcomplete.data.osm.osmquest.OsmQuestDao.getDb(OsmQuestDao.kt:43)
09-01 13:11:35.856  9106  9106 E AndroidRuntime:        at de.westnordost.streetcomplete.data.osm.osmquest.OsmQuestDao.getCount(OsmQuestDao.kt:126)
09-01 13:11:35.856  9106  9106 E AndroidRuntime:        at de.westnordost.streetcomplete.data.osm.osmquest.OsmQuestDao.getCount$default(OsmQuestDao.kt:123)
09-01 13:11:35.856  9106  9106 E AndroidRuntime:        at de.westnordost.streetcomplete.data.osm.osmquest.OsmQuestController.getAllAnsweredCount(OsmQuestController.kt:263)
09-01 13:11:35.856  9106  9106 E AndroidRuntime:        at de.westnordost.streetcomplete.data.quest.UnsyncedChangesCountSource.<init>(UnsyncedChangesCountSource.kt:33)
09-01 13:11:35.856  9106  9106 E AndroidRuntime:        at de.westnordost.streetcomplete.data.quest.UnsyncedChangesCountSource_Factory.get(UnsyncedChangesCountSource_Factory.java:44)
09-01 13:11:35.856  9106  9106 E AndroidRuntime:        at de.westnordost.streetcomplete.data.quest.UnsyncedChangesCountSource_Factory.get(UnsyncedChangesCountSource_Factory.java:12)
09-01 13:11:35.856  9106  9106 E AndroidRuntime:        at dagger.internal.DoubleCheck.get(DoubleCheck.java:47)
09-01 13:11:35.856  9106  9106 E AndroidRuntime:        at de.westnordost.streetcomplete.data.quest.QuestAutoSyncer_Factory.get(QuestAutoSyncer_Factory.java:68)
09-01 13:11:35.856  9106  9106 E AndroidRuntime:        at de.westnordost.streetcomplete.data.quest.QuestAutoSyncer_Factory.get(QuestAutoSyncer_Factory.java:15)
09-01 13:11:35.856  9106  9106 E AndroidRuntime:        at dagger.internal.DoubleCheck.get(DoubleCheck.java:47)
09-01 13:11:35.856  9106  9106 E AndroidRuntime:        at de.westnordost.streetcomplete.DaggerApplicationComponent.injectMainActivity(DaggerApplicationComponent.java:1193)
09-01 13:11:35.856  9106  9106 E AndroidRuntime:        at de.westnordost.streetcomplete.DaggerApplicationComponent.inject(DaggerApplicationComponent.java:987)
09-01 13:11:35.856  9106  9106 E AndroidRuntime:        at de.westnordost.streetcomplete.MainActivity.onCreate(MainActivity.java:116)
09-01 13:11:35.856  9106  9106 E AndroidRuntime:        at android.app.Activity.performCreate(Activity.java:6251)
09-01 13:11:35.856  9106  9106 E AndroidRuntime:        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1107)
09-01 13:11:35.856  9106  9106 E AndroidRuntime:        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2369)
09-01 13:11:35.856  9106  9106 E AndroidRuntime:        ... 9 more

**Stack trace when upgrading from 10.0 to 23.0-alpha1:**
09-01 13:21:34.552 12725 12725 E AndroidRuntime: FATAL EXCEPTION: main
09-01 13:21:34.552 12725 12725 E AndroidRuntime: Process: de.westnordost.streetcomplete, PID: 12725
09-01 13:21:34.552 12725 12725 E AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{de.westnordost.streetcomplete/de.westnordost.streetcomplete.MainActivity}: android.database.sqlite.SQLiteException: duplicate column name: quest_types_on_way (code 1): , while compiling: ALTER TABLE osm_split_ways
09-01 13:21:34.552 12725 12725 E AndroidRuntime: ADD COLUMN quest_types_on_way text;
09-01 13:21:34.552 12725 12725 E AndroidRuntime:        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2416)
09-01 13:21:34.552 12725 12725 E AndroidRuntime:        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)
09-01 13:21:34.552 12725 12725 E AndroidRuntime:        at android.app.ActivityThread.-wrap11(ActivityThread.java)
09-01 13:21:34.552 12725 12725 E AndroidRuntime:        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
09-01 13:21:34.552 12725 12725 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:102)
09-01 13:21:34.552 12725 12725 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:148)
09-01 13:21:34.552 12725 12725 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:5417)
09-01 13:21:34.552 12725 12725 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
09-01 13:21:34.552 12725 12725 E AndroidRuntime:        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
09-01 13:21:34.552 12725 12725 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
09-01 13:21:34.552 12725 12725 E AndroidRuntime: Caused by: android.database.sqlite.SQLiteException: duplicate column name: quest_types_on_way (code 1): , while compiling: ALTER TABLE osm_split_ways
09-01 13:21:34.552 12725 12725 E AndroidRuntime: ADD COLUMN quest_types_on_way text;
09-01 13:21:34.552 12725 12725 E AndroidRuntime:        at android.database.sqlite.SQLiteConnection.nativePrepareStatement(Native Method)
09-01 13:21:34.552 12725 12725 E AndroidRuntime:        at android.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:887)
09-01 13:21:34.552 12725 12725 E AndroidRuntime:        at android.database.sqlite.SQLiteConnection.prepare(SQLiteConnection.java:498)
09-01 13:21:34.552 12725 12725 E AndroidRuntime:        at android.database.sqlite.SQLiteSession.prepare(SQLiteSession.java:588)
09-01 13:21:34.552 12725 12725 E AndroidRuntime:        at android.database.sqlite.SQLiteProgram.<init>(SQLiteProgram.java:58)
09-01 13:21:34.552 12725 12725 E AndroidRuntime:        at android.database.sqlite.SQLiteStatement.<init>(SQLiteStatement.java:31)
09-01 13:21:34.552 12725 12725 E AndroidRuntime:        at android.database.sqlite.SQLiteDatabase.executeSql(SQLiteDatabase.java:1674)
09-01 13:21:34.552 12725 12725 E AndroidRuntime:        at android.database.sqlite.SQLiteDatabase.execSQL(SQLiteDatabase.java:1605)
09-01 13:21:34.552 12725 12725 E AndroidRuntime:        at de.westnordost.streetcomplete.data.StreetCompleteSQLiteOpenHelper.onUpgrade(StreetCompleteSQLiteOpenHelper.kt:181)
09-01 13:21:34.552 12725 12725 E AndroidRuntime:        at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:256)
09-01 13:21:34.552 12725 12725 E AndroidRuntime:        at android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:163)
09-01 13:21:34.552 12725 12725 E AndroidRuntime:        at de.westnordost.streetcomplete.data.osm.osmquest.OsmQuestDao.getDb(OsmQuestDao.kt:43)
09-01 13:21:34.552 12725 12725 E AndroidRuntime:        at de.westnordost.streetcomplete.data.osm.osmquest.OsmQuestDao.getCount(OsmQuestDao.kt:126)
09-01 13:21:34.552 12725 12725 E AndroidRuntime:        at de.westnordost.streetcomplete.data.osm.osmquest.OsmQuestDao.getCount$default(OsmQuestDao.kt:123)
09-01 13:21:34.552 12725 12725 E AndroidRuntime:        at de.westnordost.streetcomplete.data.osm.osmquest.OsmQuestController.getAllAnsweredCount(OsmQuestController.kt:263)
09-01 13:21:34.552 12725 12725 E AndroidRuntime:        at de.westnordost.streetcomplete.data.quest.UnsyncedChangesCountSource.<init>(UnsyncedChangesCountSource.kt:33)
09-01 13:21:34.552 12725 12725 E AndroidRuntime:        at de.westnordost.streetcomplete.data.quest.UnsyncedChangesCountSource_Factory.get(UnsyncedChangesCountSource_Factory.java:44)
09-01 13:21:34.552 12725 12725 E AndroidRuntime:        at de.westnordost.streetcomplete.data.quest.UnsyncedChangesCountSource_Factory.get(UnsyncedChangesCountSource_Factory.java:12)
09-01 13:21:34.552 12725 12725 E AndroidRuntime:        at dagger.internal.DoubleCheck.get(DoubleCheck.java:47)
09-01 13:21:34.552 12725 12725 E AndroidRuntime:        at de.westnordost.streetcomplete.data.quest.QuestAutoSyncer_Factory.get(QuestAutoSyncer_Factory.java:68)
09-01 13:21:34.552 12725 12725 E AndroidRuntime:        at de.westnordost.streetcomplete.data.quest.QuestAutoSyncer_Factory.get(QuestAutoSyncer_Factory.java:15)
09-01 13:21:34.552 12725 12725 E AndroidRuntime:        at dagger.internal.DoubleCheck.get(DoubleCheck.java:47)
09-01 13:21:34.552 12725 12725 E AndroidRuntime:        at de.westnordost.streetcomplete.DaggerApplicationComponent.injectMainActivity(DaggerApplicationComponent.java:1193)
09-01 13:21:34.552 12725 12725 E AndroidRuntime:        at de.westnordost.streetcomplete.DaggerApplicationComponent.inject(DaggerApplicationComponent.java:987)
09-01 13:21:34.552 12725 12725 E AndroidRuntime:        at de.westnordost.streetcomplete.MainActivity.onCreate(MainActivity.java:116)
09-01 13:21:34.552 12725 12725 E AndroidRuntime:        at android.app.Activity.performCreate(Activity.java:6251)
09-01 13:21:34.552 12725 12725 E AndroidRuntime:        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1107)
09-01 13:21:34.552 12725 12725 E AndroidRuntime:        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2369)
09-01 13:21:34.552 12725 12725 E AndroidRuntime:        ... 9 more

**Stack trace from 13.0 to 23.0-beta1:**
09-08 21:55:21.978 24876 24876 E AndroidRuntime: FATAL EXCEPTION: main
09-08 21:55:21.978 24876 24876 E AndroidRuntime: Process: de.westnordost.streetcomplete, PID: 24876
09-08 21:55:21.978 24876 24876 E AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{de.westnordost.streetcomplete/de.westnordost.streetcomplete.MainActivity}: android.database.sqlite.SQLiteException: duplicate column name: quest_types_on_way (code 1): , while compiling: ALTER TABLE osm_split_ways
09-08 21:55:21.978 24876 24876 E AndroidRuntime: ADD COLUMN quest_types_on_way text;
09-08 21:55:21.978 24876 24876 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2416)
09-08 21:55:21.978 24876 24876 E AndroidRuntime: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)
09-08 21:55:21.978 24876 24876 E AndroidRuntime: 	at android.app.ActivityThread.-wrap11(ActivityThread.java)
09-08 21:55:21.978 24876 24876 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
09-08 21:55:21.978 24876 24876 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:102)
09-08 21:55:21.978 24876 24876 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:148)
09-08 21:55:21.978 24876 24876 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:5417)
09-08 21:55:21.978 24876 24876 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
09-08 21:55:21.978 24876 24876 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
09-08 21:55:21.978 24876 24876 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
09-08 21:55:21.978 24876 24876 E AndroidRuntime: Caused by: android.database.sqlite.SQLiteException: duplicate column name: quest_types_on_way (code 1): , while compiling: ALTER TABLE osm_split_ways
09-08 21:55:21.978 24876 24876 E AndroidRuntime: ADD COLUMN quest_types_on_way text;
09-08 21:55:21.978 24876 24876 E AndroidRuntime: 	at android.database.sqlite.SQLiteConnection.nativePrepareStatement(Native Method)
09-08 21:55:21.978 24876 24876 E AndroidRuntime: 	at android.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:887)
09-08 21:55:21.978 24876 24876 E AndroidRuntime: 	at android.database.sqlite.SQLiteConnection.prepare(SQLiteConnection.java:498)
09-08 21:55:21.978 24876 24876 E AndroidRuntime: 	at android.database.sqlite.SQLiteSession.prepare(SQLiteSession.java:588)
09-08 21:55:21.978 24876 24876 E AndroidRuntime: 	at android.database.sqlite.SQLiteProgram.<init>(SQLiteProgram.java:58)
09-08 21:55:21.978 24876 24876 E AndroidRuntime: 	at android.database.sqlite.SQLiteStatement.<init>(SQLiteStatement.java:31)
09-08 21:55:21.978 24876 24876 E AndroidRuntime: 	at android.database.sqlite.SQLiteDatabase.executeSql(SQLiteDatabase.java:1674)
09-08 21:55:21.978 24876 24876 E AndroidRuntime: 	at android.database.sqlite.SQLiteDatabase.execSQL(SQLiteDatabase.java:1605)
09-08 21:55:21.978 24876 24876 E AndroidRuntime: 	at de.westnordost.streetcomplete.data.StreetCompleteSQLiteOpenHelper.onUpgrade(StreetCompleteSQLiteOpenHelper.kt:181)
09-08 21:55:21.978 24876 24876 E AndroidRuntime: 	at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:256)
09-08 21:55:21.978 24876 24876 E AndroidRuntime: 	at android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:163)
09-08 21:55:21.978 24876 24876 E AndroidRuntime: 	at de.westnordost.streetcomplete.data.osm.osmquest.OsmQuestDao.getDb(OsmQuestDao.kt:43)
09-08 21:55:21.978 24876 24876 E AndroidRuntime: 	at de.westnordost.streetcomplete.data.osm.osmquest.OsmQuestDao.getCount(OsmQuestDao.kt:126)
09-08 21:55:21.978 24876 24876 E AndroidRuntime: 	at de.westnordost.streetcomplete.data.osm.osmquest.OsmQuestDao.getCount$default(OsmQuestDao.kt:123)
09-08 21:55:21.978 24876 24876 E AndroidRuntime: 	at de.westnordost.streetcomplete.data.osm.osmquest.OsmQuestController.getAllAnsweredCount(OsmQuestController.kt:263)
09-08 21:55:21.978 24876 24876 E AndroidRuntime: 	at de.westnordost.streetcomplete.data.quest.UnsyncedChangesCountSource.<init>(UnsyncedChangesCountSource.kt:33)
09-08 21:55:21.978 24876 24876 E AndroidRuntime: 	at de.westnordost.streetcomplete.data.quest.UnsyncedChangesCountSource_Factory.get(UnsyncedChangesCountSource_Factory.java:44)
09-08 21:55:21.978 24876 24876 E AndroidRuntime: 	at de.westnordost.streetcomplete.data.quest.UnsyncedChangesCountSource_Factory.get(UnsyncedChangesCountSource_Factory.java:12)
09-08 21:55:21.978 24876 24876 E AndroidRuntime: 	at dagger.internal.DoubleCheck.get(DoubleCheck.java:47)
09-08 21:55:21.978 24876 24876 E AndroidRuntime: 	at de.westnordost.streetcomplete.data.quest.QuestAutoSyncer_Factory.get(QuestAutoSyncer_Factory.java:68)
09-08 21:55:21.978 24876 24876 E AndroidRuntime: 	at de.westnordost.streetcomplete.data.quest.QuestAutoSyncer_Factory.get(QuestAutoSyncer_Factory.java:15)
09-08 21:55:21.978 24876 24876 E AndroidRuntime: 	at dagger.internal.DoubleCheck.get(DoubleCheck.java:47)
09-08 21:55:21.978 24876 24876 E AndroidRuntime: 	at de.westnordost.streetcomplete.DaggerApplicationComponent.injectMainActivity(DaggerApplicationComponent.java:1193)
09-08 21:55:21.978 24876 24876 E AndroidRuntime: 	at de.westnordost.streetcomplete.DaggerApplicationComponent.inject(DaggerApplicationComponent.java:987)
09-08 21:55:21.978 24876 24876 E AndroidRuntime: 	at de.westnordost.streetcomplete.MainActivity.onCreate(MainActivity.java:116)
09-08 21:55:21.978 24876 24876 E AndroidRuntime: 	at android.app.Activity.performCreate(Activity.java:6251)
09-08 21:55:21.978 24876 24876 E AndroidRuntime: 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1107)
09-08 21:55:21.978 24876 24876 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2369)
09-08 21:55:21.978 24876 24876 E AndroidRuntime: 	... 9 more

**Comment by westnordost** [comment]
Right, I see you were upgrading from 0.10. Wow. Well, welcome back then!

**Comment by westnordost** [comment]
Check the changelog in the about menu to see what's new. Be sure to read everything ;-)
