### ISSUE TITLE
Downloaded quests should ideally be invalidated if there's an update to the quest

### ISSUE THREAD

**Issue by Identitaet** [westnordost/StreetComplete#2086]
**Use case**

After an update especially for the beta version trying out updated quest requires one to invalidate all quests if I could click on the download quests button and get the new quests (as I already do) and the updated ones that would be great
**Proposed Solution**

This probably requires giving version numbers to the quests if it's supposed to be compatible with all future updates
And then if the version numbers on the quest/some log don't fit invalidate that quest

**Comment by westnordost** [comment]
In theory that would make sense, but quests are not changed that often plus downloaded quests get deleted after 2 weeks or so anyway, so this is not worth the effort.

**Comment by peternewman** [comment]
Would there a compromise to either automatically delete or better just offer to delete all downloaded quests on app update (and the user can read the changelog), warning that they might be stale? Or is that still too much effort?

**Comment by westnordost** [comment]
That's not much effort, but such an option would confuse unsettle users. They'd wonder why there even is such an option. So, that option needs explanation too, etc.

**Comment by peternewman** [comment]
I was going to suggest a menu option, but it's already there with invalidate all :facepalm: . What about turning that into the same list as quest selection, with all quests selected by default and a button to invalidate selected quests?
