### ISSUE TITLE
Extend crossing quest

### ISSUE THREAD

**Issue by RubenKelevra** [westnordost/StreetComplete#2087]
Currently there are three answers for the crossing quest: Traffic signals, 'uncontrolled' and 'without road markings'.

![Screenshot_20200910-063737](https://user-images.githubusercontent.com/614929/92682941-dcb4b980-f331-11ea-95ba-a12de47b0cfe.jpg)

Nothing seems to fit right for this type of crossing, which might have or have not markings on the road for the path of pedestrians and might be a physical island or just a painted one.

![Deutschland_Verkehrsinsel_Furt_PflastersteinkanteJPG](https://user-images.githubusercontent.com/614929/92683004-0c63c180-f332-11ea-889c-4866c5fac9c6.jpg)

It would be nice to collect more specific informations on this quest which should help visually impaired people to navigate.

Additionally I'm not sure what a 'crossing without road markings' actually is. A logical crossing which has no infrastructure at all? 🤔

**Comment by westnordost** [comment]
The right answer is "crossing without markings" here.

**Comment by westnordost** [comment]
Soon there will be a quest that also asks if there is an island.

**Comment by RubenKelevra** [comment]
"uncontrolled crossing" is named confusing IMHO. It should explicitly ask for 'zebra crossing' there.

Then there are crossing with lines on the road and some who don't have them.

All 4 types:

* traffic light controlled
![images](https://user-images.githubusercontent.com/614929/92978078-059e9100-f48f-11ea-9ce0-1c4a2edb36b9.jpeg)

* zebra crossing
![Nr 179 Gustav-Heinemann-Str -Kleeburger Weg](https://user-images.githubusercontent.com/614929/92978001-cd974e00-f48e-11ea-9667-bf2f0abf60fa.jpg)

* crossing with lines
![IMG_3413-1080x675](https://user-images.githubusercontent.com/614929/92977973-b9ebe780-f48e-11ea-8c4e-8c1df4646d13.jpg)

* cossing without lines
![Deutschland_Verkehrsinsel_Furt_PflastersteinkanteJPG](https://user-images.githubusercontent.com/614929/92683004-0c63c180-f332-11ea-889c-4866c5fac9c6.jpg)

can have an island in the middle, like this zebra crossing:
![download](https://user-images.githubusercontent.com/614929/92978081-08998180-f48f-11ea-9b1c-ab344e06cfaa.jpeg)

And all of them could have a dedicated lane for bicycles :)

But those details would be two different quests I guess - as you recommended.
