### ISSUE TITLE
Increase the contrast for roads on farmland on the map

### ISSUE THREAD

**Issue by cyclingcat** [westnordost/StreetComplete#2092]
Hi there,

would it be possible to increase the contrast for roads leading through farmland regions? The white roads with light brown roadsides are hardly visible on the yellow ground. See the screenshot (on the smartphone display it's actually much worse, especially under a bright sky):

![Screenshot_20200914-184155](https://user-images.githubusercontent.com/32601012/93171538-91cbe500-f729-11ea-91d7-7876059c4738.png)

I'm not sure if this is a SC issue or one of the underlying map, but maybe it's possible to configure the map in a way that the contrast will be higher (darken the colour of the farmland areas, blacken the borderlines of the roads).

(SC v22.3 on a Cubot Quest, Android 9.)

The cycling cat

**Comment by Etua** [comment]
Isn't that an issue for [SC mapstyle repo](https://github.com/ENT8R/streetcomplete-mapstyle)?

**Comment by westnordost** [comment]
Yes it is, please open the ticket over there.
