### ISSUE TITLE
Feature request: Add note at my position

### ISSUE THREAD

**Issue by Sequynth** [westnordost/StreetComplete#2094]
**Use case**
As I was hiking lately I wanted to make use of SCs note function to add guideposts, wayside crosses etc. The ability to add pictures makes this a great feature. However being in the mountains, I did not have any signal and since I did not cache the tiles in advance, I had no visual reference in SC other than my position. This makes it very hard to exactly place a note in SC. In that situation, I knew where I was, I knew where I was in relation to the physical object (< 1m), but I couldn't make out where to place the note on the screen, because it was empty. The lack of a scale bar (I am NOT proposing its addition) makes it even harder it this situation to estimate the accuracy of the current GPS signal (blue, semi-transparent disk). This also applies for cases where the tiles are available, but there is just no feature mapped/rendered nearby.

**Proposed Solution**
Currently,  a long-tap triggers the dropdown-menu with the options to place a note or open the coordinate in another map.
Im suggesting, that if the user long-taps close to the blue position indicator, a third options appears 'Add note at my position'.

I can see that this might add complexity and confusion. Another suggestion would be to keep the menu the same, just if the user presses very close to their position, the app automatically takes the current GPS position of the smartphone.

Then I would at least know, that the error in position is at least the distance of my smartphone to the object. It would be great to also append the accuracy of the GPS position to the note in order to get a better sense of the reliability of the position.

**Comment by matkoniecz** [comment]
>  since I did not cache the tiles in advance, I had no visual reference in SC other than my position. This makes it very hard to exactly place a note in SC

In such case I zoom in as much as possible and create note at position of location indicator.

**Comment by westnordost** [comment]
@matkoniecz seems like a reasonable way to do it, I don't see the necessity to add this feature. Also, a "download map area for offline use" feature is on my to-do-list.

**Comment by Sequynth** [comment]
> In such case I zoom in as much as possible and create note at position of location indicator.

This is what I did so fat, but it would be nice to have the accuracy of the GPS signal (i.e. radius of the blue, semi-transparent disc) in the note, otherwise its hard to tell how exact the position of the note is.

**Comment by matkoniecz** [comment]
I typically include photos to have a proper location (if I need it), reported GPS accuracy is completely mismatching reality - at least on my phone
