### ISSUE TITLE
New quest: landuse=construction still valid?

### ISSUE THREAD

**Issue by matthiasfeist** [westnordost/StreetComplete#2095]
### General
Affected tag(s) to be modified/added: [](https://wiki.openstreetmap.org/wiki/Tag:landuse%3Dconstruction)
Question asked: **Is this still a construction site or is construction done?**
Possible answers: Construction ongoing / this is not a construction site anymore.

### Ideas for implementation
I think the action that pops out of this is pretty hard to implement, since essentially it means that it needs resurveying.
So my suggestion would be that if the user selects 
- "Construction ongoing" then we add a tag https://wiki.openstreetmap.org/wiki/Key:check_date with the current date
- "this is not a construction site anymore" then add a fixme=resurvey tag.

**Comment by HolgerJeromin** [comment]
Covered by planned quest #2074
