### ISSUE TITLE
Reword question for railway crossing - ask specifically about crossing barriers

### ISSUE THREAD

**Issue by matkoniecz** [westnordost/StreetComplete#2096]
**Use case**
I think that railway crossing barrier quest can have a more clear question. I think that refering specifically to barriers would be useful as crossings can have also other protection - road signs, light signals, sound signal, human presence and so on.

As side effect translation in Polish would become  far less awkward :)

**Proposed Solution**
Current one:

> How is this railway crossing protected?

Proposed:

> How are the barriers set up at this level crossing?

I am pretty sure that it is a bit Engrish and should be reworded

**Comment by peternewman** [comment]
> > How are the barriers set up at this level crossing?
> 
> I am pretty sure that it is a bit Engrish and should be reworded

It reads okay to me. It's asking part or full isn't it? Set up could also be "configured" which is perhaps more formal, or arranged.

**Comment by westnordost** [comment]
One answer to the question though is _"It's not"_, that does not fit to the proposed rewording of the question.

**Comment by peternewman** [comment]
> One answer to the question though is _"It's not"_, that does not fit to the proposed rewording of the question.

Change to "There are no barriers"?

**Comment by matkoniecz** [comment]
> Change to "There are no barriers"?

Or maybe shorter "no barriers" also would work?

**Comment by westnordost** [comment]
Yes, it would

**Comment by westnordost** [comment]
> How are the barriers set up at this level crossing?

Alternative: "What barriers are used at this level crossing?". A little shorter, maybe easier to translate. ("How are... set up" might be awkward in other languages)

**Comment by peternewman** [comment]
> Alternative: "What barriers are used at this level crossing?". A little shorter, maybe easier to translate. ("How are... set up" might be awkward in other languages)

Sounds good to me. Although it does slightly make me think of single post, versus lifting gate with dangly bits as show in the pictures on here:
https://wiki.openstreetmap.org/wiki/Key:crossing:barrier

But I guess the answers easily rule that out.

**Comment by westnordost** [comment]
Well, we ought not to forget that just below the question, there are the pictures.
