### ISSUE TITLE
Church tower appears as building type quest

### ISSUE THREAD

**Issue by codeinabox** [westnordost/StreetComplete#2097]
In my area there is a church tower and as the building didn't have a specific type it came up as a quest for the building type. I couldn't see an option to mark it as a church tower in StreetComplete so edited it in OpenStreetMap to be as follows: https://www.openstreetmap.org/way/38083615

However it still shows up as a building type quest, is this a bug?

**How to Reproduce**
Open StreetComplete and navigate to the following co-ordinates https://www.openstreetmap.org/#map=19/51.54782/-0.05453

The building Tower of Church of St Augustine will show as a building type quest.

**Comment by matkoniecz** [comment]
`man_made=*` is excluded, see https://github.com/westnordost/StreetComplete/blob/master/app/src/main/java/de/westnordost/streetcomplete/quests/building_type/AddBuildingType.kt#L15

So any other mappers who scan for quests will not get this one. Also, if you scan for quests in other places with objects tagged this way you will not get quest.

But if you download quests and later edit outside StreetComplete then it will not influence StreetComplete immediately. Until quests expire and are fetched again StreetComplete will show old data.

You can manually invalidate quests in settings what should result in a rescan, or wait until it happens automatically (what may take quite long time). StreetComplete will also rescan in case of any edit conflict.

You can also answer "can't say" and choose to hide this specific quest.
