### ISSUE TITLE
app crashes when trying to solve sidewalk quest

### ISSUE THREAD

**Issue by Identitaet** [westnordost/StreetComplete#2098]
**How to Reproduce**
https://youtu.be/Jbwc1jSBA0Y
Open the app click on the quest
(The way used in the demonstration https://www.openstreetmap.org/way/30192748)

**Versions affected**

This is using the 23.0 beta 1 version

**Comment by peternewman** [comment]
Is this not #2084

**Comment by Identitaet** [comment]
Yes looks like that's the same bug
Thanks
