### ISSUE TITLE
Answer a one way road quest. App crashes

### ISSUE THREAD

**Issue by peternewman** [westnordost/StreetComplete#2099]
**How to Reproduce**

Answer a one way road quest. App crashes. 

Is this another #2084? 

**Versions affected**

23.0beta1

**Comment by westnordost** [comment]
Answer, or open?

Stack trace would be helpful 

Am 19. September 2020 23:28:03 MESZ schrieb Peter Newman <notifications@github.com>:
>
>
>
>
>**How to Reproduce**
>
>Answer a one way road quest. App crashes. 
>
>Is this another #2084? 
>
>**Versions affected**
>
>23.0beta1

**Comment by peternewman** [comment]
Open sorry. Can I get a stack trace easily or do I need the debugger? I'm on stock Android 9.

**Comment by peternewman** [comment]
I put a bug report in via Google if it helps?

**Comment by westnordost** [comment]
This helps, but I will try if I can reproduce it anyway

**Comment by westnordost** [comment]
Ah, this is the same problem as for the sidewalk quest, I just realized.
