### ISSUE TITLE
Change barrier=yes on lines into more specific values

### ISSUE THREAD

**Issue by matkoniecz** [westnordost/StreetComplete#2100]
### General
Affected tag(s) to be modified/added: [barrier](https://wiki.openstreetmap.org/wiki/Key:barrier)
Question asked: **What kind of barrier is here?**

### Checklist
Checklist for quest suggestions (see guidelines):
- [x] 🚧 To be added tag is established and has a useful purpose - it is nicer to have `barrier=wall` or `barrier=fence` than catchall `barrier=yes` - but value is not significant
- [x] 🤔 Any answer the user can give must have an equivalent tagging (Quest should not reappear to other users when solved by one) - probably typically barrier=fence or barrier=wall or note about barrier not existing anymore
- [x] 🐿️ Easily answerable by everyone from the outside but a survey is necessary - fences/walls on aerials are obnoxious to distinguish
- [x] 💤 Not an overwhelming percentage of elements have the same answer (No spam)
- [x] 🕓 Applies to a reasonable number of elements (Worth the effort) (over 78k elements - https://taginfo.openstreetmap.org/tags/barrier=yes )

### Ideas for implementation

**Element selection:** Trivial, just select barrier=yes

**Metadata needed:** No

**Proposed GUI:** Sounds like image list selection

**Comment by westnordost** [comment]
The direction matters for certain barrier types. StreetComplete (currently) lacks the ability to change the order of nodes within a way, I am not sure if it is worth implementing that ability just because of this quest.

**Comment by peternewman** [comment]
> The direction matters for certain barrier types. StreetComplete (currently) lacks the ability to change the order of nodes within a way, I am not sure if it is worth implementing that ability just because of this quest.

Wasn't that also wanted for ramps, or is there a separate direction key for them?

**Comment by matkoniecz** [comment]
> Wasn't that also wanted for ramps, or is there a separate direction key for them?

Ramps have yes/no status, without direction indicator.

> The direction matters for certain barrier types. StreetComplete (currently) lacks the ability to change the order of nodes within a way

Right, retaining wall is likely worst one because not including it would result in people selecting wall instead.

I wonder whatever adding `fixme` would be OK, after all `barrier=retaining_wall fixme=check way direction` seems  far better than `barrier=yes`.

On the other hand it may make people unhappy...

> I am not sure if it is worth implementing that ability just because of this quest.

Oneway quest (#1982) would also require this (or tagging awful `oneway=-1`)

**Comment by westnordost** [comment]
> On the other hand it may make people unhappy...

Yes. Whatever StreetComplete does, it should do properly. 

> or tagging awful oneway=-1

Yes, tagging `oneway=-1` is fine.

**Comment by peternewman** [comment]
> > Wasn't that also wanted for ramps, or is there a separate direction key for them?
> 
> Ramps have yes/no status, without direction indicator.

Unless they're co-incident with steps:
https://wiki.openstreetmap.org/wiki/Tag:highway%3Dsteps

Which "By convention, the direction of the way should preferably point uphill"

**Comment by matkoniecz** [comment]
Ramp quest would be asked on already tagged `highway=steps`

Also, I started https://wiki.openstreetmap.org/wiki/Talk:Tag:highway%3Dsteps#by_convention.3F to dispute that part of the wiki page

**Comment by HolgerJeromin** [comment]
Ref #1817

**Comment by westnordost** [comment]
I'd tend to close this because it is not possible to set the direction of the retaining wall with just a tag, and implementing that  StreetComplete gains the ability to upload reversing a way just for this quest seems prohibitively too much effort. (Note that reversing a way is more complex than it seems - when a way is part of a relation).

**Comment by matkoniecz** [comment]
Wait. Flipping way in general may be tricky - `*:backward` `*:forward` tags, relation roles, `oneway` tag, cases where order matters like for some waterways, membership in relations...

But is anything of that applying to `barrier=*` ways? Maybe it could be possible to implement simplest possible flipping and use it here?

**Comment by westnordost** [comment]
Not sure what you mean. What is "simplest possible flipping"?

**Comment by matkoniecz** [comment]
Without implementing support for say "reversing a way is more complex than it seems - when a way is part of a relation"

**Comment by westnordost** [comment]
Theoretically possible, though still in a effort-range I wouldn't deem worth the effort. Note that you'd have to change the format in which the diffs are saved (and applied)
