### ISSUE TITLE
When resurveying postbox collection times show original times first

### ISSUE THREAD

**Issue by peternewman** [westnordost/StreetComplete#2105]
**Use case**
To add a collection time during resurvey, you have to tap as follows:
Add collection times
Confirm Mo-Fr
Tap Hour
Tap Minute
Tap Sa
Tap Hour
Tap Minute

This is quite a lot of taps if nothing has changed, compared to say surface or shelter quests.

If https://github.com/westnordost/StreetComplete/issues/1776#issuecomment-619662195 went in, this would reduce it by one tap, but it's still quite a lot.

**Proposed Solution**
Show the original time first, like opening hours and allow you to accept to change.

This seems to match what was suggested on the interim report:
https://wiki.openstreetmap.org/wiki/Microgrants/Microgrants_2020/Proposal/Map_Maintenance_with_StreetComplete/Interim_Report#Detail_Report

In the UK a lot of postboxes have moved to Mo-Fr 09:00, Sa 07:00, so there are changes, but a lot may already be on that, or haven't changed.

**Comment by westnordost** [comment]
Yes, I didn't implement that. I did not deem it worth the effort. Reasons were:
- postboxes don't need to be resurveyed that often
- as opposed to shops with opening hours or roads (with or without cycleways), there are not that many postboxes

**Comment by cyclingcat** [comment]
Hm... I just wanted to open a similar ticket: I just installed SC 23.0 and tried it out - in addition to the the many opening times resurvey icons there were surprisingly many for postbox collection times. They looked as if the times were missing completely, in fact these were resurvey quests where I had to retype the same collection times again which haven't changed for years. The only changes SC did to the OSM data was replacing semicolons with a comma and removing the "collection_times:lastcheck" tags (if any).

As the resurvey feature is new, such postbox resurvey quests will probably pop up often in the next time for **all** SC users where this quest is activated. However, Postbox collection times don't change very often (in particular compared to shop opening times), so most of these quests have to be answered with many taps, keeping the OSM data essentially unchanged. I hope that this behaviour doesn't frustrate too many users. (Myself, I will deactivate this quest in my direct neighbourhood where all postboxes are already provided with their collection times.)

The cycling cat

**Comment by kmpoppe** [comment]
I had the same impression (see #2109). If we find someone but implement the correct resurveying display (@westnordost said he was over budget on that), that would be welcomed.

**Comment by peternewman** [comment]
> I had the same impression (see #2109). If we find someone but implement the correct resurveying display (@westnordost said he was over budget on that), that would be welcomed.

I'm no Android expert @kmpoppe , I see you've done a few bits though. Can it not be implemented fairly easily by tweaking the changes from #2045 which did the same thing for opening hours?
