### ISSUE TITLE
Ask also about leisure=escape_game opening hours, maybe also names and wheelchair status

### ISSUE THREAD

**Issue by matkoniecz** [westnordost/StreetComplete#2106]
It is not a new quest so relatively low usage is not a problem, right?

**Comment by westnordost** [comment]
In my experience, no escape gane has walk-in opening hours, it's all "by appointment" on different time slots

**Comment by matkoniecz** [comment]
OK, my experience is extremely limited here. But I think that remaining make sense.

**Comment by westnordost** [comment]
I'd say escape games fall into the same categories as theatres, cinemas, concert halls and event locations. They may be open during certain hours in the day, but `opening_hours` are for walk-in opening hours.
