### ISSUE TITLE
Wrong max speed added in max speed questions in the Netherlands

### ISSUE THREAD

**Issue by WebMaster50** [westnordost/StreetComplete#2107]
Often, a street does not have a traffic sign showing the max speed for a street. In the maximum speed question, you would then logically fill in "no sign, apply default traffic rules" > "yes I'm am sure that there is no sign" > "Select in or outside urban area". In the case of the Netherlands, this adds maxspeed:type=NL:urban. According to Wikipedia, this is correct tagging for urban areas but it is creating problems in the Netherlands. Here, the speed is dependent on the road type. It can be 60 or 80km/u outside built-up area or 50, 30 or 15km/u inside a city or village ( and higher for motorways ofcourse). NL:urban is set by default on 50km/u. 

By now, you should understand the problem. Users see no sign and fill in "use default speeds", unaware that with that they assign a max speed of 50 km/u while in a lot of cases, it needs to be 30 or 15km/u (again, it depends on the road type so sometimes 50 is correct).

In my case, I luckily noticed the mistake and corrected it in OSM but I already found some examples of 2 years old where nl:urban is assigned on 30km/u roads.

So, this issue needs to be addressed. Possible ways I can come up with

- Add another option: "no sign but I know the speed" > "fill in the speed." or something like that
- In the answer "no sign but apply default speed" add between () the default speed that will be applied otherwise. ( I think in general for all questions, it would be good to show the users what tag is added or changed to make them more aware of what they are doing to prevent mistakes).
- Next to each answer, add an information button that users can press that teaches them when to select a type of answer
- Add an option "This is a living street". Here a speed of 15km/u is applied. Currently, the living street is hidden in other answers. 

I am curious of what you think of this but I am sure we can find a solution.

**Comment by westnordost** [comment]
> NL:urban is set by default on 50km/u.

The app does not set `maxspeed=50` in case `maxspeed:type=NL:urban` is tagged.

Are you saying that within an urban area, there may be streets that **are not signed in any way** but still a lower speed limit than 50 should apply?

**Comment by westnordost** [comment]
> Add an option "This is a living street". Here a speed of 15km/u is applied. Currently, the living street is hidden in other answers.

That would be a bug, but can't reproduce.
![Screenshot_1600889667](https://user-images.githubusercontent.com/4661658/94060650-9442d480-fde4-11ea-975e-cdd7c2400ac2.png)

**Comment by WebMaster50** [comment]
> The app does not set `maxspeed=50` in case `maxspeed:type=NL:urban` is tagged.
Sorry, Here you can see what according to wiki NL:urban means https://i.imgur.com/XFFpDgS.png . Here you can see that 

NL:urban means 50km/u (but 50km/u is indeed added as tag to maxspeed:type).

> Are you saying that within an urban area, there may be streets that **are not signed in any way** but still a lower speed limit than 50 should apply?

Yes, here you can read more about it https://en.wikipedia.org/wiki/Speed_limits_in_the_Netherlands

**Comment by WebMaster50** [comment]
> > Add an option "This is a living street". Here a speed of 15km/u is applied. Currently, the living street is hidden in other answers.
> 
> That would be a bug, but can't reproduce.
> ![Screenshot_1600889667](https://user-images.githubusercontent.com/4661658/94060650-9442d480-fde4-11ea-975e-cdd7c2400ac2.png)

Sorry, miscommunication. I see the same as you do, so living street is listed under other answers. But living streets are quite common in the Netherlands so by placing it in other answers, it is initially hidden to the user unless they click on it. It would be better if it was not inside other answers (at least for the Netherlands)

**Comment by westnordost** [comment]
>> Are you saying that within an urban area, there may be streets that are not signed in any way but still a lower speed limit than 50 should apply?

> Yes, here you can read more about it https://en.wikipedia.org/wiki/Speed_limits_in_the_Netherlands

30 zones are signed. Living streets (woonerven) are also signed.

**Comment by WebMaster50** [comment]
> > > Are you saying that within an urban area, there may be streets that are not signed in any way but still a lower speed limit than 50 should apply?
> 
> > Yes, here you can read more about it https://en.wikipedia.org/wiki/Speed_limits_in_the_Netherlands
> 
> 30 zones are signed. Living streets (woonerven) are also signed.

Not every street has a speed sign, normally only when you enter a different speed zone but several streets away, still in that zone there is no sign anymore. To me, and apparently other streetcompleet users in the Netherlands, the current answers to the question are not clear and confusing ( even though I have good understanding of the road system). I think that to prevent confusion like this, the answers need to be more clear because with the option "slow traffic zone" I thought a living street was meant (that is slow speed). Also, it was not clear at all that with the option "no sign, default rules" NL:urban would be added and that that would mean 50km/u

**Comment by westnordost** [comment]
> Not every street has a speed sign, normally only when you enter a different speed zone but several streets away, still in that zone there is no sign anymore.

The quest is disabed by default. Did you read the note when you enabled the quest?

**Comment by westnordost** [comment]
> answers need to be more clear because with the option "slow traffic zone" I thought a living street was meant

An image of how the slow zone sign looks like is displayed when you select that option.

**Comment by WebMaster50** [comment]
> The quest is disabed by default. Did you read the note when you enabled the quest?

Nope, but just did and it doesn't change my point because the problem is not that I do not know the speed of a road. The problem is that from the answers, it is not clear what you need to answers because otherwise, people wouldn't have made those mistakes. 

> An image of how the slow zone sign looks like is displayed when you select that option.

A slow zone is relative which is why I atleast was confused about it by reading the text only. Compared to a 30km/u road, 15km/u on a living street is slow and compared to 50km/u you can either see 30 or 15 as a slow speed.

Both streetcompleet is not wrong by assigning NL:urban when the user enters "no sign" because it is correct according to wiki but the user is also not wrong by entering "no sign" because not every street has a speed sign so the user relies on the default answer streetcompleet enters but that doesn't work in the Netherlands.

**Comment by westnordost** [comment]
This is not only about the Netherlands, many other countries have both living streets and slow zones too.

Okay, so having exchanged some information, what of your concerns remain and what do you suggest to change?

**Comment by WebMaster50** [comment]
> what of your concerns remain and what do you suggest to change?

First of all, I think living street needs to be listed by default and not placed under other answers. It is a valid and common road type.

Secondly, it may be good to drop the answer "a slow traffic sign". It doesn't really matter if the sign is round, square or has the text "zone" below the speed limit. If there is any sign that shows the speed limit, you should pick the first answer "a sign" and fill in the speed. Maybe you can show images of a round sign and a zone sign to let people see what can be answered under "a sign". That will remove some confusion I think.

Thirdly, I just noticed that if you press "no sign, apply default", you get a message that explains that a speed CAN apply to an entire zone (like I explained is the case in NL). After you press "yes, no sign" on that page, you get an additional question asking whether it is in urban area or not. That are three questions, to enter one speed limit. When you get multiple speed questions, you know what each button does so you just press the correct button to continue and you then basically ignore that message after seeing it so many times. It is annoying to face so many popups to answer just one question. If you can have that, lets call it educational moment, before selecting the answer. So you can for example show the marked area on the following image in the question it self with the text "important note:....". That already saves one popup for that answer https://i.imgur.com/kugH9x1.png

Fourth, list the "I don't know button" as one of the options and not under "other answers". Because the "i don't know" button is "hidden" in other answers, users likely just select "no sign, apply default" instead of "i don't know". This applies to ALL questions, not only the speed question. Users should be encouraged that when they don't know the answer, press that "I don't know" button and not "no sign, apply default" like in this case. This was a remark from a user on the OSM forum where I chatted with about the issue. It is better to give no answer than a wrong answer and upload wrong data to OSM. Maybe, the "I don't know" button should even be listed above the option to apply a default value.

Fifth, be more transparent about what tags will be added or changed when a user selects a certain answer. When the user chooses "no sign, apply default" and then for example "urban area", show that the tag "maxspeed:type=NL:urban" will be added and show that before they press confirm so they still have an option to prevent that from being applied. Maybe you can then even show the "I don't know" button again to stimulate that if they don't know it for sure, they press that button and nothing will be uploaded to OSM for that question.

Let me know what you think about this.

**Comment by matkoniecz** [comment]
> It doesn't really matter if the sign is round, square or has the text "zone" below the speed limit.

This is an important info during maxspeed resurvey/verification.

**Comment by westnordost** [comment]
Okay, well:

> Secondly, it may be good to drop the answer "a slow traffic sign". It doesn't really matter if the sign is round, square or has the text "zone" below the speed limit. 

It does matter. It is tagged differently than a normal signed speed limit.

> Thirdly [...]

I don't really get your point here. When selecting that there is no sign, you are explicitly warned, every time, that for slow zones , one may need to go to the next main street to confirm if this section of road is really not part of a slow zone - with picture, so it's really difficult to miss. 
You are saying that you read the text once and now ignore it. Well okay, as long as you got the message, that's fine. But if you argue that it's so much text and you did not read it, not even once, that doesn't really fit together with your desire that this fact is made clear to the user. If you are not going to read the text when presented as a confirmation dialog, it wouldn't be much different for if that text is shown as a wall of text when first answering the text, it would be equally ignored.

Exactly this, the existance of slow zones and the fact that within one zone, one will not find a sign at every intersection, is one of the reasons that made me decide to disable this quest type by default. To run to the next main street to confirm the answer is asking too much of the surveyors.

> Fourth, list the "I don't know button" as one of the options and not under "other answers". Because the "i don't know" button is "hidden" in other answers, users likely just select "no sign, apply default" instead of "i don't know". This applies to ALL questions, not only the speed question. Users should be encouraged that when they don't know the answer, press that "I don't know" button ...

Yes, they should be encouraged, and they are. Right when you install the app, there is a tutorial that explains exactly that.

The "Can't say" option automatically goes into the "Other answers..." menu when there are more than one "other answer", this is mostly for space reasons, I don't think both these items would fit in the bottom bar. But since the UI is the same for all quests, and the "Can't say" option is always there, users should understand pretty quickly that this option **always** exists.

> Fifth, be more transparent about what tags will be added or changed when a user selects a certain answer.

It is a deliberate decision for the app to not bother the users with which tags are used to record an answer. The app's target group are people who are not so involved in OpenStreetMap to (want to) know about this. If you are an experienced mapper, you can always look at the changesets created my StreetComplete. You can also upvote #471

---

So, this leaves point 1, adding living street to the options that are visible from the start. I am not sure, does it even fit in there without scrolling?

**Comment by WebMaster50** [comment]
> This is an important info during maxspeed resurvey/verification.

> It does matter. It is tagged differently than a normal signed speed limit.

Fair point. At least in the Netherlands, the speed is often tagged as maxspeed=30. With that in mind, the type of sign doesn't matter but the value does but does streetcompleet add another tag that says what sign it is? Then it makes sense. But then I would maybe change the text of the answer to "speed zone" and remove the word "slow" because that confused me. I thought that you meant a living street and because we have multiple speed limits in an urban area, everybody can interpret it differently.

> I don't really get your point here. When selecting that there is no sign, you are explicitly warned, every time, that for slow zones , one may need to go to the next main street to confirm if this section of road is really not part of a slow zone - with picture, so it's really difficult to miss.

True and I admit, that after reading it, it makes sense. The thing is, If you choose "no sign, apply default" you get two other questions what is annoying to answer just one speed question. I think that the first time, I have read that message half and after reading the first half, I thought I knew what the message was so I continued. And because you are facing so many questions, to answer just one question, you (atleast I) start automatically ignoring that message because you just want to answer the question and you start to know what each button does. I know first hand that when you create a question or survey for users, it is most likely that they interpret something different than you expected. What may seem logical to you is interpreted different by the user, the same applies to this case.

> The "Can't say" option automatically goes into the "Other answers..." menu when there are more than one "other answer", this is mostly for space reasons

I understand you thinking behind this but by placing the "can't say" button in the other answers, you make it easier to answer "no sign, apply default" then to press "can't say".  The user on the OSM forums even told me that it may be better that the first answer should be "can't say" for the case the user has any doubt. Look back at some images you shared and see how many space there is still left to show questions. You should indeed show part of the map with the way or node selected but there is definitely more space available to show answers. 

> It is a deliberate decision for the app to not bother the users with which tags are used to record an answer

Fair point. Maybe you can then create an information button for each question that gives more information on how to answer the question. There you can also give some examples. So, if the user needs help, he/she can find it there. This to encourage to think critically before submitting the answer.

For the living street, see my point about the "can't say" answer.

**Comment by westnordost** [comment]
I moved the living street option now into the radio button group

![Screenshot_1601375661](https://user-images.githubusercontent.com/4661658/94548297-caeb7580-0250-11eb-9c8c-7def28e87b5c.png)
