### ISSUE TITLE
House icon is rotated while scanning quests

### ISSUE THREAD

**Issue by mds08011** [westnordost/StreetComplete#2111]
Scanning for new quests cycles through the icons for each category but the building icon shows the roof facing down.

<img src="https://user-images.githubusercontent.com/8010709/94065376-edd4e000-fd9f-11ea-9a91-fbf70b42cd38.jpg" width="50%">

**How to Reproduce**

1. Press the top right button above the north arrow
2. Select "scan for quests here"
3. Watch for the circular building icon 

**Versions affected**
v23.0

**Comment by kmpoppe** [comment]
**This is NOT a bug**. This is the icon for the quest "Is this building completely underground".

**Comment by westnordost** [comment]
hehe

**Comment by westnordost** [comment]
That would be quite a weird bug if it was one :-)
