### ISSUE TITLE
Add a daily solved quests graph to the profile page

### ISSUE THREAD

**Issue by RubenKelevra** [westnordost/StreetComplete#2113]
Currently the profile page looks a little empty. How about adding a graph which shows the solved quests per day, like Github does for contributions. 

Current design:

![Screenshot_20200925-223014](https://user-images.githubusercontent.com/614929/94313667-71005c80-ff7f-11ea-8762-21461b7c1e46.jpg)

The graph type I think would fit nicely:

![Screenshot_20200925-223110](https://user-images.githubusercontent.com/614929/94313739-8f665800-ff7f-11ea-8d75-a261963ef216.jpg)

**Comment by westnordost** [comment]
What would be the advantage of this which would warrant the time and effort to implement that?
