### ISSUE TITLE
Back-button should revert the hiding quest action too

### ISSUE THREAD

**Issue by RubenKelevra** [westnordost/StreetComplete#2114]
**Use case**
I hide quests which I cannot solve while not entering private property. But sometimes I've already hidden a quest when I realize there's a view from a different angle on the property and it's solvable. 

**Proposed solution**

In such cases it would be nice to be able to go back and bring the hidden quest back on the map.

**Comment by westnordost** [comment]
You mean the undo button?

**Comment by westnordost** [comment]
So the undo button also works for hiding the quest.
