### ISSUE TITLE
German typo in a quest

### ISSUE THREAD

**Issue by cyclingcat** [westnordost/StreetComplete#2116]
Hi there,

today I stumbled upon a funny typo in a quest ("Kindergrippenbetreuung"). Now that I know how to create trivial pull requests I can edit the appropriate file myself (\app\src\main\assets\osmfeatures\de.json), but before I do it, some questions:

1. Would I run the risk to break anything if I edit a "name" key in this JSON file (i. e. does it serve as some kind of a primary key to other structures)? I assume I wouldn't, just want to be sure.

2. While I'm at it: Do you want me to look through the whole file in order to find more possible typos?

3. If you do: What is the "terms" key good for? Would it make sense to look through these strings as well?

The cycling cat

**Comment by matkoniecz** [comment]
This part is imported from iD presets and their translations and can be fixed as described at https://github.com/openstreetmap/iD/blob/develop/CONTRIBUTING.md#translating

It may be also case of something that is fixed in iD but not yet imported into StreetComplete.

**Comment by matkoniecz** [comment]
Changes just in StreetComplete would be overwritten as soon as new import happens. Fixing in iD would benefit iD users, Go Map!! users, StreetComplete users and others.

> What is the "terms" key good for?

Search term matches (where one feature can be searched under various terms).

**Comment by cyclingcat** [comment]
Okay, will try to do it there. Thanks for the hint.

The cycling cat
