### ISSUE TITLE
v23.0 not available on F-Droid

### ISSUE THREAD

**Issue by schuetzm** [westnordost/StreetComplete#2118]
It seems the build on F-Droid is stuck again:
https://f-droid.org/wiki/page/de.westnordost.streetcomplete/lastbuild

> "could not bring up vm 'builder_default'"

**Comment by matkoniecz** [comment]
Note that it is an internal F-Droid bug, especially as

> "could not bring up vm 'builder_default'"

sounds like F-droid infrastructure issue, not something caused by the StreetComplete. Is there anything that can be done on SC side to address this?

**Comment by schuetzm** [comment]
@matkoniecz I have no idea, I just wanted to bring it to the project's attention. Do you know who the maintainer of StreetComplete in F-Droid is, so I can ping him?

**Comment by westnordost** [comment]
I'd think that this is the issue tracker for issues regarding the build bot: 
https://gitlab.com/fdroid/fdroidserver/-/issues
