### ISSUE TITLE
subway_entrances - adding tags (enhancement)

### ISSUE THREAD

**Issue by bjohas** [westnordost/StreetComplete#212]
We've recently looked subway_entrances in London, see e.g. here http://bjohas.de/wiki/Maps/Transport_for_London/Map_Challenge_1_-_underground_entrances#Challenge_1:_Fixing_underground_entrances.2C_node.5Brailway.3Dsubway_entrance.5D and the wheelmap here https://wheelmap.org/en/map#/?categories=public_transfer&lat=51.52650134932504&lon=-0.12707233428955078&zoom=14. 

There are many entrances that do not have wheelchair tagging (or other useful tags, like name and ref). My suggestion is a map quest to add that information.

**Comment by matkoniecz** [comment]
overpass query for subway_entrance without wheelchair=yes/no: http://overpass-turbo.eu/s/oXw

**Comment by bjohas** [comment]
Thanks! It's nice to throw in some MapCSS - see this query, where entrances that are untagged (with wheelchair) appear in red, otherwise in green. http://overpass-turbo.eu/s/oXC

**Comment by westnordost** [comment]
Oh, this has long been solved already

**Comment by bjohas** [comment]
Many thanks!
