### ISSUE TITLE
Posted stop ID numbers

### ISSUE THREAD

**Issue by BalooUriza** [westnordost/StreetComplete#2126]
### General
Affected tag(s) to be modified/added: [](https://wiki.openstreetmap.org/wiki/Key:)
Question asked: What is the ID number for this stop?

### Checklist
Checklist for quest suggestions (see guidelines):
- [x] 🚧 To be added tag is established and has a useful purpose
- [x] 🤔 Any answer the user can give must have an equivalent tagging (Quest should not reappear to other users when solved by one)
- [x] 🐿️ Easily answerable by everyone from the outside but a survey is necessary 
- [x] 💤 Not an overwhelming percentage of elements have the same answer (No spam)
- [x] 🕓 Applies to a reasonable number of elements (Worth the effort)

### Ideas for implementation

**Element selection:** 
Elements with `highway=bus_stop` but no `ref=*` tag.  Almost certainly also applicable to just about any other public transit stop, not just bus stops.

**Metadata needed:** 
I believe this applies worldwide given the widespread adoption of GTFS.

**Proposed GUI:**
Default to numeric keypad as most stop IDs are exclusively numerical, but allow other characters to be entered as occasionally stop IDs get weird.

**Comment by BalooUriza** [comment]
Rationale being that many transit systems put stop ID numbers at their stops so that riders can contact the transit agency to discover what routes will be arriving when.  This is also helpful for creating GTFS feeds (official or otherwise).  The problem is the stop IDs published in some agencies GTFS do not actually reflect the real, on the ground, stop ID.

Stop IDs are mappable in OSM by adding the `ref=*` tag to a transit stop.

**Comment by westnordost** [comment]
I think this is not eligible, for the following reasons:

- **👨‍💻 Users are no experts** / **🐿️ Easy answer**: Users don't know what to look for or where. Is the ref on the pole? Somewhere on the shelter? Somewhere on the the bus schedule? In reality, there are usually a lot of numbers everywhere, users won't know if any has a certain meaning.
- **🤔 No unanswerable quests**: Maybe in Oklahoma, all bus stops have refs, in other places, there may not even be one which would mean that in other places, this quest is not actually answerable. Additionally, we cannot assume that the ref is numerical.

Furthermore, not necessarily a reason to not implement it, but simply to say it is not such a big loss if this information can not be recorded with this app:
- **🤷 Useful purpose** / **💵 Valuable Surveyors**: Within an area, bus stops are usually quite well distinguishable simply by their name, actually already by the location. Data consumers should have little problems to connect the names with their (internal) refs if they need to.

**Comment by matkoniecz** [comment]
> Where there are stop IDs used

The problem is about areas where `ref` is not posted, or even worse - it is not displayed prominently.

**Comment by BalooUriza** [comment]
> The problem is about areas where `ref` is not posted, or even worse - it is not displayed prominently.

This is already the typical situation with `name` at transit stops in North America.

**Comment by westnordost** [comment]
Thank you for the additional information. It looks like on the signs you showed, the ref visible quite clearly.

Zooming in randomly into some town in US shows that at least where I zoomed to, the bus stops do have names https://www.openstreetmap.org/node/6507497885

However, I can not make out from the imagery if it is specified on the the sign
https://www.google.de/maps/@35.777859,-78.6366155,3a,15y,205.5h,88.55t/data=!3m9!1e1!3m7!1sLycTIvwSHA1ewsI69qeF4g!2e0!7i16384!8i8192!9m2!1b1!2i35

---

There are two options what we could do:
1. If in the USA, sometimes bus stops have names and sometimes they have ref codes: Offer "It has no name but a ref code" as an "other answers..." option in the "What is the name of this bus stop?" form
2. If in the USA, (virtually) all bus stops primarily have a ref code, disable the "What is the name of this bus stop" and replace it with an US-only quest that asks for the ref code.

How can we find out whatever is the case?

**Comment by BalooUriza** [comment]
> Thank you for the additional information. It looks like on the signs you showed, the ref visible quite clearly.
> 
> Zooming in randomly into some town in US shows that at least where I zoomed to, the bus stops do have names https://www.openstreetmap.org/node/6507497885
>
> However, I can not make out from the imagery if it is specified on the the sign
> https://www.google.de/maps/@35.777859,-78.6366155,3a,15y,205.5h,88.55t/data=!3m9!1e1!3m7!1sLycTIvwSHA1ewsI69qeF4g!2e0!7i16384!8i8192!9m2!1b1!2i35

Some context, Trimet (the transit agency around Portland, Oregon, which has been heavily involved in both transit mapping within OSM as well as working with Google to co-develop the GTFS standard) has been using stop IDs since at least the 1980s when they started installing kiosks with DOS PCs running their own custom home brew trip planning software.  They'd actually distribute this program via local BBSs as well so you could run it on your own computer, and put out updates 4 or 5 times a year as schedules and routes adapted!  Trimet also doesn't usually name stops save for MAX light rail stations.  Portland Streetcar (owned by the City of Portland and contracted out to Trimet for operations) didn't name their stations back when I lived there.  But, Trimet did seem to start the "Street the route runs on & Nearest Crossstreet" or "nearest major landmark" convention for `name=*` on unnamed stops.

Whether this passes ground truth verifiability is debatable and largely pivots on whether or not word of mouth conventions count as ground truth.  I have no strong opinions on this.

> There are two options what we could do:
> 
> 1. If in the USA, sometimes bus stops have names and sometimes they have ref codes: Offer "It has no name but a ref code" as an "other answers..." option in the "What is the name of this bus stop?" form
> 2. If in the USA, (virtually) all bus stops primarily have a ref code, disable the "What is the name of this bus stop" and replace it with an US-only quest that asks for the ref code.
> 
> How can we find out whatever is the case?

I'm thinking reworking the task might work.  For example, "does this bus stop have a stop ID or a name" with possible answers being "name", "ref", or "both" and then base a followup question from that.

If the transit agency is has been offering GTFS feeds for more than about a year or two, then the odds of them having stop numbers posted is nearly 100%, this has only been recently decoupled in the GTFS spec which originally didn't have `stop_code` which would be the same as what's shown at the stop and matches what `ref` is in OSM.  `stop_id` was formerly both what it currently is (an internal identifier) and what `stop_code` is now, largely owing to Trimet's legacy.  This ultimately split into two fields since, as you pointed out, not every agency has posted stop numbers.

**Comment by westnordost** [comment]
Wow, they were really adopting computerization early, interesting to read!

Anyway, your suggestion sounds fine, however means to introduce one more tap for everyone. Let's assume for a moment that all the bus stops in Germany do not have a ref but only a name, this would mean that all the users in Germany need to first answer a pointless question before they can input the actual information. This is just an assumption, I didn't check if bus stops in Germany actually also have a ref, but I would like to avoid asking at all for this information if it is usually not given. This is why I suggested these two options, based on whether (virtually) all bus stops primarily have a ref instead of a name in the US.

**Comment by BalooUriza** [comment]
> Wow, they were really adopting computerization early, interesting to read!
> 
> Anyway, your suggestion sounds fine, however means to introduce one more tap for everyone. Let's assume for a moment that all the bus stops in Germany do not have a ref but only a name, this would mean that all the users in Germany need to first answer a pointless question before they can input the actual information. This is just an assumption, I didn't check if bus stops in Germany actually also have a ref, but I would like to avoid asking at all for this information if it is usually not given. This is why I suggested these two options, based on whether (virtually) all bus stops primarily have a ref instead of a name in the US.

Just looking real quick at [OpenMobilityData](https://transitfeeds.com/), it looks like, going from your Germany example [just clicking through a few and checking the Stops for a Code column](https://transitfeeds.com/l/168-germany) (thus, they use posted stop numbers), about half seem to (or I just hit a lucky combination).

Maybe just detach it from the bus stop name quest and make it it's own quest?

**Comment by westnordost** [comment]
The existance of `ref` numbers in the OSM database is not relevant. Relevant is what can be seen on the bus stop sign. Again, we need to find out if the norm for the US is that always primarily the ref code is written on the bus stop sign, or the name, or both.

**Comment by BalooUriza** [comment]
> The existance of `ref` numbers in the OSM database is not relevant. Relevant is what can be seen on the bus stop sign. Again, we need to find out if the norm for the US is that always primarily the ref code is written on the bus stop sign, or the name, or both.

Sure.  It's usually the ref or neither.  Though I don't think this question should be limited to the US, either.

**Comment by westnordost** [comment]
We can start with the US and then based on local knowledge, add more.

**Comment by HolgerJeromin** [comment]
The user has to know that this is not [local_ref](https://wiki.openstreetmap.org/wiki/Key:local_ref). 
In Aachen we have a very good bus network. And there are no refs, only local_ref.

**Comment by peternewman** [comment]
They're present in at least London too, although mostly populated via NAPTAN I think, so would only want validating and probably don't really change.

**Comment by westnordost** [comment]
For the record, on the #general channel on OSM slack, I asked 

> Question for US-citizens: Do bus stops in the US primarily have a ref code/number or primarily have a name, or both? I've seen some pictures of signs that only specify the ref number, for example https://user-images.githubusercontent.com/2896518/94818346-a532ad80-03c3-11eb-911e-efefe9dbf3bd.png
> Is this the default in your state?

I kicked off quite a big discussion with this, very informative though. One post that summarizes the discussion quite well is from Kathleen Lu, she wrote:
> `network` is almost always signed. `ref` often signed (even if less visible and harder to find). `name` often not signed (often just the cross street). Agree that `network` is super important. For a lot of the transit networks, you have to pay separately

So what I take out of this is:
- `ref` is often signed, `name` rarely
- it is common that within one city, there may be a multitude of different networks, since the `ref` only unique within one network, `network` is important, too.
- @bhousel is canonicalizing the network names (with polygons where they operate) for the name suggestion index. This data could be used to suggest networks when one day a quest that asks for this is impelemented. He is asking people to contribute public transport networks, you can check if your network is already known to the NSI: https://nsi.guide/index.html?t=transit

**Comment by 1ec5** [comment]
That’s a good summary of the discussion that unfolded in Slack.

> Trimet also doesn't usually name stops save for MAX light rail stations. Portland Streetcar (owned by the City of Portland and contracted out to Trimet for operations) didn't name their stations back when I lived there. But, Trimet did seem to start the "Street the route runs on & Nearest Crossstreet" or "nearest major landmark" convention for name=* on unnamed stops.
> 
> Whether this passes ground truth verifiability is debatable and largely pivots on whether or not word of mouth conventions count as ground truth. I have no strong opinions on this.

Just want to point out that bus stop names in the U.S. are generally verifiable via ground truth. For accessibility reasons, [federal regulations](https://cms7.fta.dot.gov/are-fixed-route-transit-providers-required-provide-audible-stop-announcements) require bus agencies to provide [visual or voice stop announcements](https://kingcounty.gov/depts/transportation/metro/travel-options/accessible/programs/accessible-bus/calling-out-stops.aspx) that indicate the name of each stop. But you have to already be on the bus to hear the announcement for a given stop, which would require a very different workflow than a typical StreetComplete quest.

**Comment by BalooUriza** [comment]
> The user has to know that this is not [local_ref](https://wiki.openstreetmap.org/wiki/Key:local_ref).
> In Aachen we have a very good bus network. And there are no refs, only local_ref.

Is this really widespread or is this some highly regional tagging?  I've never heard of local_ref being used before, normally loc_ref would be for local refs, but this is the first I've heard of this being used on transit stops.

**Comment by peternewman** [comment]
> > The user has to know that this is not [local_ref](https://wiki.openstreetmap.org/wiki/Key:local_ref).
> > In Aachen we have a very good bus network. And there are no refs, only local_ref.
> 
> Is this really widespread or is this some highly regional tagging? I've never heard of local_ref being used before, normally loc_ref would be for local refs, but this is the first I've heard of this being used on transit stops.

It's common in the UK (due to the NAPTAN import apparently), e.g. see:
https://wiki.openstreetmap.org/wiki/Key:local ref

**Comment by Atrate** [comment]
@westnordost Can SC filter by regions smaller than country-level? For example in Poland, the Lesser Poland Voivodeship (region, like a German Land) the bus stops all have refs, though that is not the case for all the regions.

**Comment by matkoniecz** [comment]
> though that is not the case for all the regions.

At least in Kraków `ref` are not exposed to normal users of public transport, in Małopolska in general I never noticed them to be signposted.

**Comment by BalooUriza** [comment]
stop_id=* is the internal number not exposed to the public, ref=* is the ID
number on the pole (if any).

**Comment by Atrate** [comment]
> At least in Kraków ref are not exposed to normal users of public transport, in Małopolska in general I never noticed them to be signposted.

Yes, you're right, I've also not seen refs in Kraków, but outside the city the refs are usually signed white on blue in the top right of a board on about 1.5m from the ground on the pole

**Comment by muralito** [comment]
The GUI preferences shoes that in Uruguay this question is disabled., but a lot of bus stops have ref numbers displayed in posts. It would be useful to enable it.

**Comment by matkoniecz** [comment]
In such cases it is better to open a new issue! Comments in closed issues are easy to miss and may be easily forgotten.

**Comment by westnordost** [comment]
@muralito : And what about bus stop names? Are they also common in Uruguay? (For example in the U.S., they are not that common).

**Comment by mxxcon** [comment]
I just found this issue after trying to figure out why I couldn't add bus stop names, and somewhat surprised and disappointed by the conclusions drawn here.

In NYC there are over 16000 bus stops and every single one has a name and a reference code.
If a bus stop has a shelter, the stop's name is written in GIANT letters on it such as
![bus_shelter](https://user-images.githubusercontent.com/847140/106992767-443b2d80-6747-11eb-8c06-60a10d843ecd.png)

If a stop doesn't have a shelter but marked with just a pole, the stop's name is written on the sign on top of it...
![bus_pole](https://user-images.githubusercontent.com/847140/106992853-69c83700-6747-11eb-8ba4-1808ba86d759.png)

And every bus stop has a reference number written next to the timetable
![image](https://user-images.githubusercontent.com/847140/106993093-f96de580-6747-11eb-8196-4f76f8bfeba3.png)
![image](https://user-images.githubusercontent.com/847140/106993103-fd9a0300-6747-11eb-85cd-6adcdca8e383.png)

MTA(Metropolitan Transportation Authority of New York, agency that runs public transit in NYC) has a website instructing people how to look up relevant information https://bustime.mta.info/wiki/Help/FindingAStopCode

I request to reevaluate the decision not to allow entering of bus stop names in US (or at least make it more granular than country-wide).

**Comment by westnordost** [comment]
> or at least make it more granular than country-wide

This is possible. We just need someone to research this. 

On 5 February 2021 06:37:29 CET, mxxcon <notifications@github.com> wrote:
>I just found this issue after trying to figure out why I couldn't add
>bus stop names, and somewhat surprised and disappointed by the
>conclusions drawn here.
>
>In NYC there are over 16000 bus stops and every single one has a name
>and a reference code.
>If a bus stop has a shelter, the stop's name is written in GIANT
>letters on it such as
>![bus_shelter](https://user-images.githubusercontent.com/847140/106992767-443b2d80-6747-11eb-8c06-60a10d843ecd.png)
>
>If a stop doesn't have a shelter but marked with just a pole, the
>stop's name is written on the sign on top of it...
>![bus_pole](https://user-images.githubusercontent.com/847140/106992853-69c83700-6747-11eb-8ba4-1808ba86d759.png)
>
>And every bus stop has a reference number written next to the timetable
>![image](https://user-images.githubusercontent.com/847140/106993093-f96de580-6747-11eb-8196-4f76f8bfeba3.png)
>![image](https://user-images.githubusercontent.com/847140/106993103-fd9a0300-6747-11eb-85cd-6adcdca8e383.png)
>
>MTA(Metropolitan Transportation Authority of New York, agency that runs
>public transit in NYC) has a website instructing people how to look up
>relevant information
>https://bustime.mta.info/wiki/Help/FindingAStopCode
>
>I request to reevaluate the decision not to allow entering of bus stop
>names in US (or at least make it more granular than country-wide).
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/streetcomplete/StreetComplete/issues/2126#issuecomment-773802224

-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.

**Comment by opk12** [comment]
> or at least make it more granular than country-wide

What about choosing `name` or `ref` based on the existence of a node with `name` or `ref` within a certain radius? (Overpass's [`around:`](https://wiki.openstreetmap.org/wiki/Overpass_API/Language_Guide#.22around.22_-_finding_something_near_something_else) may help.)

A wrong choice is due to unmapped information that I can fill in, so the question still feels reasonable to me and not spam. For example, I cannot answer `Has a ref and no signed name` straight away, without going to the bus stop.

If no bus stop around has `name` or `ref`, I guess OSM maintainance is insufficient for a traveller to rely on complete or up-to-date OSM line mapping anyway (regardless of the node density within the search radius) so maybe the question may as well not be asked.

With this approach, the bus stop quest and the ref quest could also be merged into one quest that allows to enter both.

**Comment by Lee-Carre** [comment]
Please enable this quest for (the island of) Jersey (SC informs me that it's never asked, here, at present).

Bus stops have an ID number (4 digit, base-10), and (for if/when such a quest exists) name.

Names can be a bit cryptic, sometimes, but with the ID the stop can easily be looked-up on [the operator's site](http://www.libertybus.je/) (see also the [near-realtime bus location-tracking map](http://m.gov.je/Bus/Tracker)).

IDs are prominently printed on the road surface (and in the corner of any departures_board at the stop), so would be easy to identify.

If I recall, a previous operator (Connex) made quite an effort to assign each bus stop a unique (at least within Jersey) ID, and then integrated those into their route data and systems for passengers to query bus info (e.g. how long until the next bus).

Not only are many stops not added at all to OSM yet, but those that are frequently lack the ID.

Sometimes a stop won't have any departures_board (with the stop's name, routes, etc.), but the ID is printed on the road. Thus, with the ID, that unique stop can be queried, to yield name and various other data.

Currently, I must use Vespucci to add the ref key to stops.
