### ISSUE TITLE
Multiple simple tags in one quest

### ISSUE THREAD

**Issue by peternewman** [westnordost/StreetComplete#2127]
If I've read the code correctly, you have to answer all three (vibration/noise/spinner) in one go yes?

If so, a couple of observations. Firstly I've often filled in the sound quest when not actually crossing the road e.g. if a crossing on the opposite side (e.g. a T junction), or while walking nearby I can hear the noise I complete that quest (or it might take a few attempts on a regular commute to complete a junction). This would no longer be possible with the current UI.

Also I think I'm right in saying this is the first request which requires you to touch anything (for the vibration bit), or in the UK look underneath, which is a challenge when you're above average height and touching would be easier. Is it really the best time during a global pandemic to introduce a quest which wants you to touch things when we have a virus which is known to live for a long time on hard surfaces (personally I'm trying my best to avoid touching pedestrian crossings, or elbow them if I have to). :mask: 

Finally, having just looked on the wiki, is it worth adding minimap too, I'd not heard of it (or seen it in the UK), or is not deemed used enough?

Would a UI like this not work with relatively minimal changes?:
Assistance|Yes|No
---|---|---
Sound| :o: | :red_circle: 
Arrow| :o: | :o: 
Vibration| :red_circle: | :o:
Mini Map| :o: | :o:
Submit|Merged|Row

Which in this case would only touch sound and vibration.

_Originally posted by @peternewman in https://github.com/westnordost/StreetComplete/issues/1330#issuecomment-701650292_

> If I've read the code correctly, you have to answer all three (vibration/noise/spinner) in one go yes?

Yes.

Your proposed UI looks interesting. So it is intended for people who want to only answer it partially. However there is a problem with this. If you answered it partially, that would mean that the quest will not be solved. It will be shown to others again and right after upload, it will immediately be shown to you again because not all of sound, arrow and vibration (at least) are answered.

_Originally posted by @westnordost in https://github.com/westnordost/StreetComplete/issues/1330#issuecomment-702118076_

@peternewman I think you should open a new issue for this. The idea of filling out multiple pieces of info at once has come up enough — ex: https://github.com/westnordost/StreetComplete/issues/102#issuecomment-689027242 and https://github.com/westnordost/StreetComplete/issues/1717#issuecomment-581188710 — that it would be nice to have one issue to refer back to about the concept in general. Especially now that there is a concrete UI suggestion.

_Originally posted by @smichel17 in https://github.com/westnordost/StreetComplete/issues/1330#issuecomment-702327784_

**Comment by peternewman** [comment]
> Your proposed UI looks interesting.

Thanks

> So it is intended for people who want to only answer it partially.

Yes, for whatever reason (time/access/global pandemic) they might only want to answer some of the quest.

> However there is a problem with this. If you answered it partially, that would mean that the quest will not be solved. It will be shown to others again and right after upload, it will immediately be shown to you again because not all of sound, arrow and vibration (at least) are answered.

I'll admit I hadn't considered this, however there are a few solutions already, in the case of me hearing the noise for the crossing on the other side of the road, I'd actually want it to pop up again, so that when I walk down that side of the road I can check for arrows and look/feel :nauseated_face: (I didn't really used to care, maybe I'm over-paranoid now) for vibration/spinners.

If I decide I really don't want to check for vibration/spinners, or I'm not interested in answering the rest of the bits, I can use the existing no, just hide option to make that particular quest vanish if I chose.

Equally, at any point, as with any other quest, someone can come along and answer the remaining parts of it to resolve it.

As an optional improvement, aside from when resurveying (although for that it could also show everything pre-filled if desired), it could hide the already completed rows, so my second walk past on the other side might look like:
Assistance|Yes|No
---|---|---
Arrow| :o: | :o: 
Vibration| :red_circle: | :o:
Mini Map| :o: | :o:
Submit|Merged|Row

Depending on how complicated you wanted, it would be nice if the sub-quests were presented as quests within the list, you could even use that ordering to decide the order the attributes appeared on the form, along with the quest icon shown (or use a generic one) and the quest priority (and hence how it sits with others). If you wanted to go to town, it could hide the other attributes if I deselected their quests and if it didn't download their sub keys, it presumably also wouldn't show that quest when there was nothing left that I wanted to enter.

> The idea of filling out multiple pieces of info at once has come up enough — ex: [#102 (comment)](https://github.com/westnordost/StreetComplete/issues/102#issuecomment-689027242) and [#1717 (comment)](https://github.com/westnordost/StreetComplete/issues/1717#issuecomment-581188710) — that it would be nice to have one issue to refer back to about the concept in general. Especially now that there is a concrete UI suggestion.

Personally I think this might be better placed for simple quests, although I guess it could have a combo yes/no and then something else.

The other one that does come to mind for me (and would cover my grumbling in #2119 ) would be bus stops, it could be formatted like so:
Feature|Yes|No
---|---|---
Shelter| :o: | :red_circle: 
Bench| :o: | :o: 
Optional|Merged|Image Row
Tactile Paving| :red_circle: | :o:
Submit|Merged|Row

Or you could just drop the tactile bit and it's image to save space.

I guess also bike parking covered and capacity and likewise for motorbikes could be merged.

Toilet fee/baby changing/wheelchair accessible.

I suspect this whole idea perhaps also ties into a few other issues:

**Comment by westnordost** [comment]
Okay, there are several things at once.

> Firstly I've often filled in the sound quest when not actually crossing the road e.g. if a crossing on the opposite side (e.g. a T junction), or while walking nearby I can hear the noise I complete that quest (or it might take a few attempts on a regular commute to complete a junction). This would no longer be possible with the current UI.

What about crossings that only beep when you can cross but don't do the tok tok tok when not? Or it is too loud to hear? Or they only do the beep beep beep when you actually press the button? An audio signal could also be used in place of a vibrating button theoretically. Not sure if such crossings exist, but they should be tagged the same.

> Corona

Well, in spring this year (lockdown-time), there was the notion whether one should actually be encouraged to go outside to map at all. I didn't. But this is certainly each individual's choice and I trust that people are considerate enough that they know of the risks and consequences of their actions. So, there was not a warning when starting the app whether one really wants to use that app right now, nor will there be a warning that you shouldn't use the app when driving etc.. Regarding hand hygiene, since Corona I consider my hands dirty whenever I went outside and wash them after when I get home.
Theoretically of course there is the possibility to disable a quest with a warning message for now, but I think such an action would at best be symbolic.

> [Why (suddenly) a quest with multiple tags being tagged? Change of quest guidelines?]

The guideline to be "atomic" not necessarily refers to tags being used, but "things" being mapped. The former is highly dependent on the tagging scheme, the latter is dependent on the reality.
For example, if we were to map what a ticket vending machine sells (bus tickets, train tickets, tram tickets, ferry tickets,...), this would be one thing, even though it might be expressed as several tags. The type of ramp (#2036) is tagged in OSM not as one property, but as several (because not really the type of ramp is tagged, but what vehicles can use the ramp, i.e.  `ramp:bicycle=yes`, `ramp:stroller=yes/no`, etc...), still of course, there will be just one quest for it.

The same applies to the features for the blind: It is one system on one crossing, especially the arrow (if it exists) and the vibrating button are virtually the same thing:
![Taster 4 Blindenampel](https://user-images.githubusercontent.com/4661658/94916355-d4721900-04ae-11eb-96cc-173dbc41a0e8.jpg)

> Finally, having just looked on the wiki, is it worth adding minimap too, I'd not heard of it (or seen it in the UK), or is not deemed used enough?

Yes, it is not deemed used enough. I think this kind of minimap might be a future of some new models of the pedestrian call buttons, I have not seem them anywhere. Maybe wait a few years and see if the get more widespread. Also, there is a little problem with the tag. Look at this website and scroll down to the pictures of the arrows. They describe that there is some kind of mini-minimap on the arrow itself. It is not clear if that would also count as a minimap or not - and it would be very hard for non-trained people to find this out:

https://www.bsvsb.org/index.php/berichte/articles/barrierefreie-gestaltung-von-ampelanlagen-taktile-und-akustische-signalgeber-besser-erkennen-und-als-hilfe-fuer-eine-sichere-ueb.html

**Comment by westnordost** [comment]
Regarding the idea to further expand on tagging several things at once, while I reckon that it can increase the efficiency a bit, I am somehow reluctant to it. It introduces more complexity, more implementation effort (especially with this dynamic hiding of rows that have already been answered) and it further waters down the "atomic" requirement.

I created this multi-choice form for the blind-traffic-signals mainly because these are really two features on one thing (arrow and button). I was not that happy that happy with it but I think it was the best alternative. I wouldn't want this to become the standard interface.

**Comment by peternewman** [comment]
> Okay, there are several things at once.

Yeah sorry, it became a bit of a random brain dump.

> > Firstly I've often filled in the sound quest when not actually crossing the road e.g. if a crossing on the opposite side (e.g. a T junction), or while walking nearby I can hear the noise I complete that quest (or it might take a few attempts on a regular commute to complete a junction). This would no longer be possible with the current UI.
> 
> What about crossings that only beep when you can cross but don't do the tok tok tok when not? Or it is too loud to hear? Or they only do the beep beep beep when you actually press the button?

All the ones I've ever heard in the UK (whether using SC or before) just beep, the tok tok tok only seems to happen on the continent as far as I'm aware (e.g. France and Switzerland I think most recently for me). I map the positive cases, so when I hear a beep I'll flag that as a yes. I don't think any would not beep when it's green unless you'd pressed the button, that seems rather unhelpful from an accessibility point of view. The cynic in me would wonder if the beep increases the chances of someone immersed in their phone noticing too!

I just went to look here:
https://wiki.openstreetmap.org/wiki/Key:traffic_signals:sound

And it looks like technically the UK ones should be tagged as `traffic_signals:sound=walk` whereas abroad should be yes I guess, I only really noticed the novelty of the tok's, I don't know if they beeped too, although I guess all crossings can tok at a junction, ours generally can't beep at a crossroads unless you can cross in all directions at once, so you don't go at the wrong time.

> An audio signal could also be used in place of a vibrating button theoretically. Not sure if such crossings exist, but they should be tagged the same.

I'm not sure I follow, we've got traffic_signals:sound and traffic_signals:vibration, in the UK, quite a lot beep, but I assume fewer have the spinning cone at the bottom (see my previous link on the original issue) for deaf-blind people, I'm assuming that should be tagged as vibration (although externally it's doing more than just vibrating), which the comment in here seems to agree with:
https://wiki.openstreetmap.org/wiki/Talk:Key:crossing#Tactile_.2F_audible_signals

I assume the yellow ones abroad, the enclosure vibrates when it's time to cross.

So given there are crossings with one, or both, or possibly the other, surely we want them tagged as such, not using one common tag for both audio and vibration? It would also mean blind, deaf and deaf-blind people could all be given appropriate instruction as to what to expect and pay attention to at a crossing.
 
> > Corona
> 
> Well, in spring this year (lockdown-time), there was the notion whether one should actually be encouraged to go outside to map at all. I didn't.

In the UK at its worst we were recommended only an hour's exercise a day I mapped during that, as I found it a bit more interesting than just walking some local pavements and encouraged me to go on a variety of different routes.

> Regarding hand hygiene, since Corona I consider my hands dirty whenever I went outside and wash them after when I get home.

Yeah likewise, although if I'm going to map, or possibly generally anyway, I'll be touching my phone and probably not cleaning it as often as I should, so I'd prefer to avoid additional touching if possible.

> Theoretically of course there is the possibility to disable a quest with a warning message for now, but I think such an action would at best be symbolic.

I wasn't really suggesting anything as strong as that, however the way the quest is currently implemented, I can't only complete the sound part of the quest, as I do currently, so my choices in the UK are to disable the whole quest, or to have to stop and bend over all the time to see if there is a cone (as I don't think UK ones vibrate). The initial aim of my suggested alteration to the UI was to get around this issue.

> > [Why (suddenly) a quest with multiple tags being tagged? Change of quest guidelines?]

I'm not sure if this was aimed at me but some related comments to it below.

> The same applies to the features for the blind: It is one system on one crossing, especially the arrow (if it exists) and the vibrating button are virtually the same thing:
> ![Taster 4 Blindenampel](https://user-images.githubusercontent.com/4661658/94916355-d4721900-04ae-11eb-96cc-173dbc41a0e8.jpg)
 
I think I understand better having read a translation of that. Although I don't believe we have the arrows in the UK and I think the behaviour is quite different. It sounds like the arrow and vibration abroad are fairly linked, but in the UK I think noise and spinner are only as linked as whether there is a button or tactile paving (aside from I guess you won't have the other accessibility features and not tactile paving).

> > Finally, having just looked on the wiki, is it worth adding minimap too, I'd not heard of it (or seen it in the UK), or is not deemed used enough?
> 
> Yes, it is not deemed used enough.
>They describe that there is some kind of mini-minimap on the arrow itself. It is not clear if that would also count as a minimap or not - and it would be very hard for non-trained people to find this out:

Yeah agreed, that would need a proper GUI quest with some example pictures for that one.

> Regarding the idea to further expand on tagging several things at once, while I reckon that it can increase the efficiency a bit, I am somehow reluctant to it.

>It introduces more complexity, more implementation effort (especially with this dynamic hiding of rows that have already been answered) and it further waters down the "atomic" requirement.

Yeah sorry, I went a bit overboard with some of that. Although like I say, I don't think the arrows exist in the UK at all, so tagging every UK traffic signal with no arrow is perhaps a bit spammy (as well as wasted effort) whereas hiding that row in this country would be good.

I don't think the dynamic hiding or most of the other features have to be done. Just switching to my radio button proposal and the submit button, and then pre-selecting any pre-existing data would improve the quest a lot in my opinion for relatively little work. We could use the hide option if we really don't want to see that quest anymore.

> I created this multi-choice form for the blind-traffic-signals mainly because these are really two features on one thing (arrow and button). I was not that happy that happy with it but I think it was the best alternative.

But I thought you've merged sound into that too? I guess that's the crux of my comment, if that was split back out, it would essentially be the same as every other quest (e.g. you tag both building and roof height together, but not roof height and roof shape).

To put an alternative angle on it, you need to be in front of the button itself to answer arrow and vibration, which either due to the 2m for Coronoavirus or just invading someone's personal space is a bit odd/may be restricted, whereas you only need to be in the vicinity of the crossing, or worst case crossing at the same time, to answer the sound quest.

>I wouldn't want this to become the standard interface.

I can appreciate if you don't want to merge say the bus stop ones, it does potentially make it more challenging in terms of explanation etc or having to condense things into one word questions and answers (and I suspect my pictures wouldn't fit well). Something of a cross between #1969 and #124 would still be beneficial and sort of related instead that if there are further quests about the same node already downloaded, as soon as you've answered one it moves onto the next one. So you would do:
Select quest -> Shelter -> Answer -> Tactile -> Answer -> Bench -> Answer

Rather than:
Select quest -> Shelter -> Answer -> Select quest -> Tactile -> Answer -> Select quest -> Bench -> Answer

Which I guess is a half-way house between what I've proposed and what others have.

**Comment by westnordost** [comment]
> But I thought you've merged sound into that too? I guess that's the crux of my comment, if that was split back out, it would essentially be the same as every other quest (e.g. you tag both building and roof height together, but not roof height and roof shape).

Hm okay, so you propose to ask specifically for features of the ehm... button on the traffic signals pole. What wording would you propose for that? - I am not sure how to clearly ask only for blind features that will usually be on that button (casing) on the pole

**Comment by peternewman** [comment]
> Hm okay, so you propose to ask specifically for features of the ehm... button on the traffic signals pole. What wording would you propose for that?

For the quest name/question? How about something like:
Leave the sound one as was seems to work - "Are there sound signals for the blind here?"
"What tactile features for the blind do these traffic light button cases have, if any?"
or "What tactile features for the blind do these traffic lights have, if any?"
or "What touch-based features for the blind do these traffic lights have, if any?"
or use "...these traffic lights have on the pole..."

Or the comments here are almost questions:
https://wiki.openstreetmap.org/wiki/Tag:highway%3Dtraffic_signals#Traffic_signals_for_pedestrians

> I am not sure how to clearly ask only for blind features that will usually be on that button (casing) on the pole

Does it actually matter much? If they're presented with a form with two questions, they'll answer those, another form will only have the audible alert. It's not like you're expecting them to list them themselves.

**Comment by westnordost** [comment]
Maybe "What touch-based features for the blind do these traffic lights have, if any?" is best, because for "tactile" paving, there is already a separate quest.

Regarding the arrow, well I guess it is dependent on from which company they obtain such buttons, or in particular, maybe which model is used.
In Germany, it may not be possible to find ones **without** arrow. So maybe, the information whether there is an arrow or not does not actually belong into OSM (or at least StreetComplete) because it will not really differ within one country.

So maybe after all, the quest should just ask if such a vibrating button is present. Do you have a suggestion how to word it?

**Comment by peternewman** [comment]
> Maybe "What touch-based features for the blind do these traffic lights have, if any?" is best, because for "tactile" paving, there is already a separate quest.

Yeah agreed, a balance between being technically accurate and not confusing for people.

> Regarding the arrow, well I guess it is dependent on from which company they obtain such buttons, or in particular, maybe which model is used.
> In Germany, it may not be possible to find ones **without** arrow. So maybe, the information whether there is an arrow or not does not actually belong into OSM (or at least StreetComplete) because it will not really differ within one country.

So **all** button boxes have it? In which case I guess the quest is the same as, or similar to the question proposed below as it's only one touch-based feature now. Agreed though, unless there are countries where it varies, but I guess it becomes a new quest then and disabled in the UK and Germany.

Wasn't there talk somewhere of meta-surveys? Although I don't know where you'd send the data to. "In your area, do traffic lights usually have arrows for the blind?" Voted and averaged over say 50km grids or something.

> So maybe after all, the quest should just ask if such a vibrating button is present. Do you have a suggestion how to word it?

So in Germany from what I understand the button/arrow thing just shakes after you've pushed it, the UK one always spins when it's safe to cross.

How about this:
"Do these traffic lights have a tactile indicator for deaf-blind people on the control box when it's safe to cross? Hint: This may be a button on the bottom you have to press to trigger it, or a spinning cone underneath the control box or something else similar."

Or change "on the control box" to "near the button".

Which ensures they won't mistake tactile paving, but also means they shouldn't miss-tag:
https://wiki.openstreetmap.org/wiki/Key:traffic_signals:floor_vibration

I guess an "Other answers..."
No but the floor vibrates instead - Tag vibration=no, floor_vibration=yes
Yes and the floor vibrates as well - Tag vibration=yes, floor_vibration=yes

Or they could just tell you to add a note in those cases.

If it's now a single quest, like tactile paving we could add a few example pictures from different countries which probably makes it clearer.

**Comment by westnordost** [comment]
Do you have a (free to use) picture of such a rotating cone?

**Comment by peternewman** [comment]
> Do you have a (free to use) picture of such a rotating cone?

I can't spot one on Wikipedia. There's a slight catch-22 here, as so few are currently tagged on OSM...

Perhaps as a placeholder use one of these with an arrow to the bottom right:
https://commons.wikimedia.org/wiki/File:Puffin_crossing_in_Belfast_(35021074385).jpg
https://commons.wikimedia.org/wiki/File:Dubai_pedestrian_panel.jpg

In the meanwhile I'll try and locate one and take a photo of it.

**Comment by westnordost** [comment]
![Screenshot_1601741303](https://user-images.githubusercontent.com/4661658/94996208-6e1af280-05a3-11eb-99c7-045b77041d3c.png)

I made a photo of one in Germany, in the UK it could be overridden with another picture as soon as you made one. We can add this later.

**Comment by peternewman** [comment]
> in the UK it could be overridden with another picture as soon as you made one.

I'd have thought showing both would be ideal, otherwise we get into needing to know what type of assistance is available in each country...

**Comment by Cj-Malone** [comment]
![A7C4302D-72F4-4BD7-9C84-D433EC82CFC4](https://user-images.githubusercontent.com/10121513/95379863-d89e9c00-08dd-11eb-8d64-30296b8ba2ad.jpeg)

![04980DC6-E88D-4BE2-AC2B-FDA198AF99C7](https://user-images.githubusercontent.com/10121513/95379960-f8ce5b00-08dd-11eb-8ae8-8ef0455f8ea8.jpeg)

If you still want a photo you're welcome to either of theses under CC0.

**Comment by peternewman** [comment]
Thanks @Cj-Malone , I think the second one looks great and saves me going out on a grey or wet day!

**Comment by westnordost** [comment]
Thanks a lot! Though unfortunately, it's all black on black - the cone is black, the pole is black and the button is black. If I further crop the image so that the cone is in the center, you will only see some unidentifiable black areas with the silhouette of some kind of black cone in the middle and a house in the background. I do not think the current picture, even though it is of high quality, is usable in the app. The first picture would be better if it wasn't out of focus - on that yellow truck. It looks like the picture is really about that yellow truck rather than the cone.

For a second try, I'd suggest to
- wait for cloudy whether, so the contrast black/white is not that big
- make a photo of the cone half from below (the perspective of a toddler), the same perspective as the picture you see currently. Because of the perspective, you can see more of the traffic light button as well

**Comment by Cj-Malone** [comment]
![ED798857-85DB-4BDF-929C-C64F9143380F](https://user-images.githubusercontent.com/10121513/95455581-04fdfb00-0966-11eb-801a-e16a3e4cb300.jpeg)

![167E446D-9CF2-4326-878B-6FA9DA962741](https://user-images.githubusercontent.com/10121513/95455604-0deecc80-0966-11eb-842c-364fe8b93c69.jpeg)

Hopefully one of theses are better, I'm clearly not a photographer :p

**Comment by westnordost** [comment]
Absolutely they are, thank you!
