### ISSUE TITLE
quest for missing addr:street

### ISSUE THREAD

**Issue by matkoniecz** [westnordost/StreetComplete#213]
Current state: https://github.com/westnordost/StreetComplete/issues/213#issuecomment-406603714

----------

As discussed in #205 at least for some regions (for example Poland) it makes sense to have quest asking about missing addr:street.

To make quests less complicated it should not be done as part of existing "add house number" quest.

Note that it would be preferable to ask question about addr:street immediately after solving housenumber quest, so overpass query finding quests target should not be in form "addr:housenumber without add:street", but rather the same as one finding missing house numbers.

Given that this quest apparently makes sense only is some regions (where addr:street is both likely to not be obvious and available to surveyor) it is preferable to add

> offline reverse country geocoder (GPS position -> country+region you are in, necessary for localized quests

mentioned in https://github.com/westnordost/StreetComplete/issues/188#issuecomment-299728054 before adding this quest (or at least quest filter, with this one disabled by default).

**Comment by DaubnerF** [comment]
I would like to mention that this quest would make sense for my current mapping efforts in Austria as well. So if you implement it, please don't restrict it only to Poland :)
At least where I live, the street name associated with a house is readily available to the surveyor (most of the time).

**Comment by Dostoi** [comment]
Same in France :)

**Comment by westnordost** [comment]
The quest will not be limited to certain countries but limited to house number 1,2(,3,4).

**Comment by DaubnerF** [comment]
Hmm, I guess this is better than restricting it to Poland, I still wish I could turn it on independent of housenumbers.
Maybe add a settings dialog, where certain quest types can be disabled altogether, with this type disabled by default?

**Comment by rugk** [comment]
> Maybe add a settings dialog, where certain quest types can be disabled altogether, with this type disabled by default?

https://github.com/westnordost/StreetComplete/issues/35

**Comment by DaubnerF** [comment]
Ah, very nice, thanks rugk.
So maybe we could have this quest-type independent of area and housenumber? :)

**Comment by skfd** [comment]
Also note that some mapping communities use relations instead of addr:street. Thanks.

**Comment by britiger** [comment]
In same cases the you can interpolate the addr:street using the street next to the housenumber. At  housenumbers on intersections it is difficult to automate it. Streetcomplete should also ask for the addr:street with a short list of the named roads next to building, including option "none of them" for creating a note.

**Comment by matkoniecz** [comment]
Looking at it again: my plan is to reuse add road name quest interface, it even has (a bit hidden, I noticed it only now) option to select nearby road name.

**Comment by matkoniecz** [comment]
One tricky part: one should include only addresses with named road nearby, as in places without named roads addr:place is used instead. In such cases addr:place may be easily added and quest is not necessary.

Given that there may be incorrectly named road nearby or road from separate settlement with named roads there should be also option "this address has no named road" allowing to add addr:place.

See for example https://www.openstreetmap.org/node/5037711319 found by http://overpass-turbo.eu/s/vT6

**Comment by matkoniecz** [comment]
My plan is to

- ask for addr:housenumber
  - without addr:street
  - without addr:place
  - with named road nearby

Still, it is necessary to provide option "This address is not assigned to a named road, settlement name is used instead" that will allow to set "addr:place".

Both addr:street and addr:place should have suggestion pool populated by nearby streets and places (or maybe nearby addr:street and addr:place)?

helper query used to verify whatever I missed YA valid tagging scheme: http://overpass-turbo.eu/s/xJA

**Comment by westnordost** [comment]
Don't forget conscription numbers, street numbers and house names.

> Still, it is necessary to provide option "This address is not assigned to a named road, settlement name is used instead" that will allow to set "addr:place".

And this is the only option if only a conscription number is specified. No idea about conscription+streetnumber, would need to look into the wiki for how it is exactly.

> Both addr:street and addr:place should have suggestion pool populated by nearby streets and places (or maybe nearby addr:street and addr:place)?

Would make sense, but not required for a PR to be accepted. The suggestion pool for street names is already there. The one for place names would need to be implemented.

**Comment by matkoniecz** [comment]
@RubenKelevra Are you speaking about addr:place? In that case - where are regions without street names that do not add addr:place? How they mark addresses where addr:street is not necessary?

**Comment by RubenKelevra** [comment]
@matkoniecz yep, I usually tag `postal_code=xyz` on the ways of the street and `addr:street=abc` on the buildings. It sounds like you plan to tag the name of the city or suburbs at each building with `addr:place=bef`. I consider this as redundant data, suburbs and citys should be added as boundary, not at building level.

Someone here imported a huge amount of data, tagging each building with a postal code and city name, which makes no sense. I go ahead check of all buildings have the same postal code, tag it on the street and remove the city and postal code on the buildings.

**Comment by matkoniecz** [comment]
>  It sounds like you plan to tag the name of the city or suburbs at each building with addr:place=bef

Only on buildings that a) have address b) address has no `addr:street` part (area has no assigned street names).

And I would do it only in areas where it is established tagging (so far I only checked address tagging standards in Poland where this scheme is used).

Do you know how other places handle addresses in areas without street names?

**Comment by RubenKelevra** [comment]
@matkoniecz alright, this sounds better. :)

> Do you know how other places handle addresses in areas without street names?

Well, I came across many small suburbs in my area which has just a name like "Sonne", where basically 2 or 3 backroads meet. The address is than just "Sonne 3" or similar, while they are spread around those 2 or 3 streets.

So the suburb is added to the street name and the addr:city is just the name of the city which this suburb belongs.

**Comment by matkoniecz** [comment]
I started implementation at https://github.com/westnordost/StreetComplete/compare/master...matkoniecz:address?expand=1 (far away from PR, but I started using it in my fork)

Current state

- [x] ask for addr:street, with filters
- [x] with addr:housenumber
- [x] without addr:street
- [x] without addr:place
- [ ] addr:city (tagging mistake for addr:place) - maybe also should be excluded?
- [ ] addr:town (tagging mistake for addr:place) maybe also should be excluded
- [ ] require named road nearby
- [ ] provide option "This address is not assigned to a named road, settlement name is used instead" that will allow to set "addr:place".
- [ ] addr:street should have suggestion pool populated by nearby streets (or maybe nearby addr:street)?
- [ ] suggestion pool for addr:place
- [ ] research what should be done with conscription numbers
- [ ] research what should be done with house names (exclude addr:housename?)
- [ ] research situation mentioned by @RubenKelevra 

helper query used to verify whatever I missed YA valid tagging scheme: http://overpass-turbo.eu/s/xJA

I am planning to make first version covering only Polish tagging and working only in Poland - it will be useful to catch problems and to pacify bot complaining about edits adding only part of address (affects people solving house number quest in Street Complete).

**Comment by westnordost** [comment]
I think in the next version of StreetComplete, there will be more stuff from you than from me, hehe.

> require named road nearby
Not really necessary IMO, there will just be no suggestions then. (Or do you plan to not allow a free input?)

> provide option "This address is not assigned to a named road, settlement name is used instead" that will allow to set "addr:place".
Does this even exist for `addr:housenumber`? Wouldn't that be a `addr:conscriptionnumber` then?

> research what should be done with conscription numbers
`addr: conscriptionnumber` do not have a street (that's the whole idea), but `addr: streetnumber` do.

> addr:street should have suggestion pool populated by nearby streets (or maybe nearby addr:street)?
This pool already exists and can be relatively easy accessed. See the street name quest for how to do it. Perhaps you should also populate it during download of this quest type.

**Comment by matkoniecz** [comment]
> Does this even exist for addr:housenumber? Wouldn't that be a addr:conscriptionnumber then?

In Poland it exists, there is no distinction between "number of house on a street" and "number of house in a settlement", both are tagged addr:housenumber.

That would explain why I had trouble with understanding what is addr:conscriptionnumber

> Not really necessary IMO

It is not 100% necessary but should reduce how many false-positives are generated. I will drop it (like suggestion pool) if it would be unreasonably complicated.

**Comment by westnordost** [comment]
Okay, that means that `addr:conscriptionnumber` is explicitly a number-per-place and an `addr:streetnumber` is explicitly a number-per-road and these tags are used where it is commonplace to have per-place numbers or even both. Then, `addr:housenumber` could be both, though the assumption should be that it is the same as a `addr:streetnumber`.

**Comment by rugk** [comment]
BTW, if it interpolates a street name from a nearby street and is really sure that this is the right street (I.e. there is no other street nearby), it should pre-enter/fill that name into the input, so the user only has to confirm the street number.
OR basically ask an yes/no question instead of letting the user enter it
OR exclude these cases at all, as data consumers may do the same interpolation (and AFAIK) already do.

**Comment by matkoniecz** [comment]
> name into the input

I plan to do something similar to road name quest with easy reuse of nearby names.

----

I run into an implementation issue:

My plan was to display "What is the street of this address?" quest title, with text box.

To handle case where there is no street name and `addr:place` needs to be added, there would be "No assigned named street" in can't say menu.

After selecting it user would enter place name into text field.

But it turns out that there is no good way to change the "What is the street of this address?" quest title. I though about adding place name in popup, so the now outdated title would not confuse people.

**Comment by westnordost** [comment]
The title also does also not change for any other quest, for example the housenumber quest when selecting that there is no number but a name. The answer-UI simply changes. That has never been a problem. 

The input field could have a label, like `quest_housename.xml` does. That should be clear enough. 

Maybe, the input field for the place name could look different from the street input field. I propose a blue sign with white frame for the street name and a white sign with a black frame for the place name - or maybe even this
<img src="https://upload.wikimedia.org/wikipedia/commons/2/23/5.22.2_Belarus_%28Road_sign%29.svg"/>

**Comment by westnordost** [comment]
Note: The quest may only be asked for addresses with missing street names that are not part of a associatedStreet relation or similar.

**Comment by matkoniecz** [comment]
associatedStreet is already covered in test version of quest, do you know about any similar relations that also should cause exclusion?

**Comment by matkoniecz** [comment]
@westnordost What you think about icon for this quest? I though about taking "What is the name of this road" and changing background to one use by a housenumber quest.

Are you maybe interested in making a completely new icon?

 I am getting close to finishing this one (as part of finishing various half-done PRs and branches), in dev version it is currently using place name icon that is not really suitable.

**Comment by westnordost** [comment]
There is already an icon. Perhaps or is not exported yet

Am 7. Dezember 2019 11:37:42 MEZ schrieb Mateusz Konieczny <notifications@github.com>:
>@westnordost What you think about icon for this quest? I though about
>taking "What is the name of this road" and changing background to one
>use by a housenumber quest.
>
>Are you maybe interested in making a completely new icon?
>
>I am getting close to finishing this one (as part of finishing various
>half-done PRs and branches), in dev version it is currently using place
>name icon that is not really suitable.

**Comment by matkoniecz** [comment]
Oh right - `ic_quest_housenumber_street`. Thanks!

**Comment by matkoniecz** [comment]
I am a bit frustrated by working on the interface. I started this quest basing it on `addRoadName` quest with `RecyclerView` in layout.

I got rid of `RecyclerView` as it was adding plenty of complexity and here just one answer is needed.

The first working version had simple text fields copied from place name quest as input, with suggestion dropdown floating in some random place in line below, what would need to be fixed.

I wanted to have a nicer interface, either reusing elements from AddRoadName layout or from AddHousename layout.

Sadly, it turns out that both layouts rely on `me.grantland.widget.AutofitLayout`. And this `AutofitLayout` may contain just `TextView` elements - otherwise it crashes on `TextView textView = (TextView) child;` in its initialization code.

I can look for a superior replacement of no longer maintained `me.grantland.widget.AutofitLayout`, switch back to `RecyclerView` (arghh) or try to somehow fit both `TextView` and suggestion dropdown button into a `TextView`.

But I think that I prefer to go back to a simple text fields copied from place name quest and solve just dropdown button issue.

**Comment by westnordost** [comment]
I am not entirely sure I understand the problem. Why do you need a non-TextView within the `AutofitLayout`, after all, even an `EditText` is also a `TextView`?

How / why should the interface be any different from the add road name interface?

**Comment by dbdean** [comment]
I'm very interested in getting this quest up and running. I've looked at @matkoniecz `address` branch, updated it to the latest StreetComplete `master`, and taken it out for a spin. It seems to work ok, so I'm interested in what we think is still needed to make into a future release, and how I can help.

**Comment by westnordost** [comment]
I've not looked at it yet. Requirements are:
- 💤 No spam and 💵 Valuable Surveyors rule: limit to housenumbers at start of street, i.e. 1,2,3,4 (and, if possible, to those that are located at intersections with other streets)
- auto-completion should work the same way it works for the add road name quest. So, reusing the same mechanics as for that quest. Maybe, even prohibit typing an own street name but **only** allow selecting nearby streets.
- Handle addr:place correctly (see discussion above)
- Handle conscription numbers correctly

But anyway, you could open a PR and I will look it through. I know that @matkoniecz currently has a lot to do, so I think you would do him a favor if you / we grabbed his work and completed it.

**Comment by dbdean** [comment]
As everyone can see above, I've opened a WIP pull-request to work on this, and made some changes already based upon how I found it handles out surveying.

In particular, I've
* Added the street-number to the prompt to make it easier to tell which house is being referred to (and often as an additional clue to the street it belongs to)
* Upped the distance for close streets to 250 metres as houses in the middle of long, straight streets were getting no suggestions
* Made it remember the last street you entered, for easier surveying along streets.

I still need to look into @westnordost's comments above and see how I can go with them.

**Comment by Bibi56** [comment]
In France (but not only) we use `associatedStreet` to avoid street name duplication. I don't mind if some countries like Germany prefer to avoid `associatedStreet`. This guest is adding wrong information at worst or useless information  at best if the `addr:housename` is part of an `associatedStreet`.
Are you going to add the multilingual variants the same way. No, of course not.
So please avoid asking for nodes members of `associatedStreet` and if such `associatedStreet` exists near by, propose to add it to the `associatedStreet` as house.

**Comment by matkoniecz** [comment]
Can you give example of edit where unwanted data was added? I am pretty sure that I implemented filtering out `associatedStreet`.

> and if such associatedStreet exists near by, propose to add it to the associatedStreet as house.

In such cases tagging address as tags is AFAIK also perfectly fine. Or is there some area where community decided to deprecate `addr:street`, like German community decided to deprecate associated street relations? Personally I have no plans to implement any special support for associatedStreet (except skipping objects with addresses tagged this way, what was implemented already).

**Comment by HolgerJeromin** [comment]
>  I am pretty sure that I implemented filtering out associatedStreet.

yes, you did:

https://github.com/westnordost/StreetComplete/blob/c637e2465ee8d2e1d46477f3228bd5f0fd75f1db/app/src/main/java/de/westnordost/streetcomplete/quests/address/AddAddressStreet.kt#L48

**Comment by Bibi56** [comment]
@HolgerJeromin thanks for the clarification.
@matkoniecz, I looked at the ticket not at the implementation. I checked one Overpass query but it was not the final one I guess.
Yes better to create another ticket. But I was lucky with two interesting answers!
I'm checking with the French community, IMHO opinion it's better to avoid `add:housname` and `addr:street` for France as with the land registry (Cadastre) and the BANO project we can add addresses in a more efficient way. So that mappers using SC will be more efficient too.
On one comment you mentioned "exclude members of associatedStreet relations" but you forgot to but the information in the top comment "current status". So sorry for my mistake and thanks for your work.

**Comment by matkoniecz** [comment]
>  On one comment you mentioned "exclude members of associatedStreet relations" but you forgot to but the information in the top comment "current status". So sorry for my mistake and thanks for your work.

Top comment is what was initially proposed (I was unaware about this relation at that time).

https://github.com/westnordost/StreetComplete/issues/213#issuecomment-406603714 is more recent and includes note about associatedStreet

I will add one more note that this comments are historic and to look at current code
