### ISSUE TITLE
support asking for the crossing's features also on highway=traffic_signals + crossing=traffic_signals

### ISSUE THREAD

**Issue by Lukas458** [westnordost/StreetComplete#2130]
**Use case**
At the moment, for highway=crossing + crossing=traffic_signals there are the "crossing features" quests.
But these questions are not working when crossing=traffic_signals is combined with highway=traffic_signals on the same node, to mark a crossing. 
These combination we have often, especially in Germany but also in other countries. Some mappers use it to mark that the traffic lights for pedestrians and for cars are "on the same place", especially when there is no junction or other traffic to regulate, for example here: https://www.openstreetmap.org/node/4712004392/history

According to taginfo, there are 112.000 crossing=traffic_signals which are combined with highway=traffic_signals. Even though these are only 16% of all traffic-light crossings in osm, these also are 112.000 crossings we do not affect in SC at the moment.

A few months before, I had the purpose to discourage tagging highway=traffic_signals + crossing=traffic_signals on the same node. Use two separate nodes instead. But my discussion on taging mailing list leaded to nothing

Maybe you want read an example massage in the thread, which gives a reason why this tagging exists: https://lists.openstreetmap.org/pipermail/tagging/2020-April/052067.html

https://wiki.openstreetmap.org/wiki/Tag:crossing%3Dtraffic_signals says that crossing=traffic_signals requires highway=crossing, but when you look at the page for highway=traffic_signals, both variants are mentioned: https://wiki.openstreetmap.org/wiki/Tag:highway%3Dtraffic_signals#How_to_map_.28new.29

Because both variants are used, and I don't see a real chance at the moment to change this. So could SC maybe override this issue and support highway=traffic_signals + crossing=traffic_signals for the traffic-light-crossing-quests too?

**Proposed Solution**
Support asking the traffic-light-crossing-quests also for highway=traffic_signals + crossing=traffic_signals

**Comment by westnordost** [comment]
Seems reasonable. As long as `crossing=traffic_signals` is there, it should be clear that it is indeed (also) a crossing.

**Comment by Lukas458** [comment]
Yeah, thanks for your quick reply. As I said, I tried to convince people about tagging highway=crossing + crossing=traffic_signals, but reaching a consensus about this seems to be a big thing, because there is none (no consensus).

So it might be a good middle way.

**Comment by westnordost** [comment]
By the way, could it be that you mistagged https://www.openstreetmap.org/node/4712004392/history#map=19/51.26867/7.20429 
There is an arrow, but no vibration when one can cross?

**Comment by Lukas458** [comment]
Thank you very much for your work. Yeah, its a bit difficult with all these different combinations of equipment a traffic light-crossing can have. In my city, every crossing with buttons has these arrows: https://wiki.openstreetmap.org/wiki/File:TrafficSignalsArrowB2.jpg

But not all of these arrows are "clickable", so in the example I linked, there is no vibration available.
So we see again, all combinations of equipment can be possible. Even a crossing without request buttons can have sound and/or vibration, and the other way round...

**Comment by Lukas458** [comment]
Oh, there comes something else in my mind: Would it be possible to add this combination also for the "tactile_paving" quest? Or is that too complicated?

**Comment by westnordost** [comment]
Hm, the tactile paving quest looks for `highway = crossing` (not `crossing = *`), if it would also look for `highway = traffic_signals`, that woudl be wrong, because it would include "real" traffic lights near crossings.. If you have an idea how to solve this, please open a new issue.

**Comment by Lukas458** [comment]
Okay, thank you, I did.
