### ISSUE TITLE
Quest cache invalidation doesn't work

### ISSUE THREAD

**Issue by cyclingcat** [westnordost/StreetComplete#2134]
Hi there,

I'm currently using StreetComplete on two phones: an **older one with Android 5.1** (still my main phone, SC use meanwhile just incidentally) and a **newer one with Android 9** (faster, bigger and waterproof, bought especially to be mounted on the stems/handlebars of my bikes, used with OSMand and for targeted SC sessions). When I come home from a SC session with the Android 9 device, the other one still shows the quests I have just solved, so I want to invalidate the quest cache on the latter, expecting the solved quests to vanish as soon as the quests are reloaded.

But this doesn't seem to be the case. For example there is a post box collection times resurvey quest which I solved last weekend on the Android 9 phone but still appears on the Android 5.1 phone, no matter how often I invalidate the quest cache in the settings and hit the "Search for quests" button afterwards.

The tags of the corresponding node:

**Before solving the quest:**
```
amenity=post_box
brand=Deutsche Post
collection_times:lastcheck=2015-03-01
collection_times=Mo-Fr 07:30; Sa 07:30
operator=Deutsche Post
```

**After solving the quest:**
```
amenity=post_box
brand=Deutsche Post
collection_times=Mo-Sa 09:00
operator=Deutsche Post
```

There is an untouched `<ref>` tag as well which I omitted here for privacy reasons. I guess that you remove the outdated `collection_times:lastcheck` tag deliberately instead of replacing it with the current date (?)

(SC 23.0 on both devices).

The cycling cat

**Comment by westnordost** [comment]
Note that if you invalidate the quest cache, all quests are marked as invalidated. So in this case, only **the next time the postbox collection times quest is downloaded at this location**, the one invalid quest should vanish. Did the app actually download the postbox collection times quest for that location?

> I guess that you remove the outdated collection_times:lastcheck tag deliberately instead of replacing it with the current date (?)

Correct. This behavior seemed to be what was most preferred when I asked on the tagging mailing list.

**Comment by cyclingcat** [comment]
After some more taps on the "Invalidate quest cache" button the solved quest finally vanished, probably when it came to the turn of the post box collection times quest. So it's working as expected. (But I had tapped onto it at least 5 times!)

Would it be an idea to remove _all_ quest icons if the user hits this "invalidate" button and then rebuild the quest icon set from scratch? This would make the whole feature more transparent IMHO.

The cycling cat

**Comment by westnordost** [comment]
> But I had tapped onto it at least 5 times!

Tapped on the download button you mean, right?
With the multi-download feature merged, a lot will be more swift I think

**Comment by cyclingcat** [comment]
Yes, I meant the quest download button, of course. Sorry for the confusion.

The cycling cat
