### ISSUE TITLE
Remove resurvey quests for defibrillators

### ISSUE THREAD

**Issue by cyclingcat** [westnordost/StreetComplete#2135]
Hi there,

since the introduction of the resurvey quests with StreetComplete v23.0 there are again many opening times survey quests popping up in my neighbourhood. Which is of course a good thing, as according to my own observations surprisingly many opening times have actually changed over time (but beware of temporarily changed opening times due to Corona; it is not always visible that these changes are only temporary, so it would perhaps a good idea to show these opening times quests again as soon as this whole Corona shit is over!).

Among these resurvey quests there are many quests for "opening times for defibrillators". Besides the wording ("access time" would be probably a better choice), these quests are in almost all cases hard, if not impossible to answer without entering a building and do further research inside of it, as these devices seem to be often somewhere (where exactly?) inside of schools, office buildings or private company sites. This violates your own rule "🐿️ Easily answerable by everyone _from the outside_ but a survey is necessary" 😊 

So I'd suggest to remove these quests in order to remove some spamming.

The cycling cat

**Comment by westnordost** [comment]
Yes, you are right

**Comment by westnordost** [comment]
Sorry @matkoniecz , I'll revert the change for #1756 , @cyclingcat has a point.

The assumption was that one can simply look at the opening hours of the shop it is contained within, but schools, hospitals or other commercial buildings do not have opening hours, so it is not always answerable.

**Comment by matkoniecz** [comment]
And tagging "unsigned opening hours" over and over again may be too much...
