### ISSUE TITLE
"What kind of building is this?" options doesn't cover watersports

### ISSUE THREAD

**Issue by ei8fdb** [westnordost/StreetComplete#2138]
I've been trying to map an area of a seaside neighbourhood. It has multiple sailing clubs. 

I understand this may be a question about the metadata options used in Street Complete.

When I try to answer "what kind of building is this?" none of the answer fit. I would expect an answer like 
- watersports building (ideally - SC currently has option for aircraft hangar)
- sports facility building, or 
- multi-purpose building

**Comment by matkoniecz** [comment]
What kind of building you want to tag? Boat storage? Place where sailors meet?

> watersports building (...) sports facility building, or

Is "sport center" not fitting?

> multi-purpose building

As indicate by hint in "can't say" menu you should select primary/main characteristic (leave note with photo/info if you are really unsure)

disclaimer: my sea knowledge is very limited

**Comment by ei8fdb** [comment]
> What kind of building you want to tag? Boat storage? Pub where sailors meet? Administration building of marina? Building constructed to house boats during repairs? Storage unit for boat hardware?

It has a number of purposes: administration building of marina, social club, possibly restaurant/bar/cafe, storage of equipment - *not* boats.
 
> > watersports building (...) sports facility building, or
> 
> Is "sport center" not fitting?

I don't see the "sport center" option. The answers provided to the question "What kind of building is this?" are:
- residential
- commercial building
- civic building
- religious building
- for cars
- on a farm
- Other
-- shed
-- roof
-- service building
-- hut
-- toilets
-- hangar
--  bunker
- Other answer
-- Still being constructed
-- It has multiple purposes (which provides a message saying choose it's main purpose)
-- Can't say

> > multi-purpose building
> 
> As indicate by hint in "can't say" menu you should select primary/main characteristic (leave note with photo/info if you are really unsure)

Right, which says choose one of the above options, none of which really fit.
 
> disclaimer: my sea knowledge is very limited. Sorry if I am confused about something obvious.

Thats OK! I thought this would be a common enough task that I'd file it.

**Comment by HolgerJeromin** [comment]
The "sport centre" is below/inside the "civic building"

**Comment by ei8fdb** [comment]
> The "sport centre" is below/inside the "civic building"

I am terribly sorry - I did not know each of those categories could be expanded. I think this option will suffice for the moment.

Thanks.

**Comment by smichel17** [comment]
Not realizing categories can be expanded seems to be a (surprisingly, to me) common issue (given that you only need to try and submit one of the more generic answers to see that it expands). And if several people posting here -- who are invested enough to open an issue -- have this problem, I'd guess it's more common in the general population of users.

I wonder if this type of interface should be avoided, or whether there is some improvement that would make the functionality more obvious.

Personally, the most confusing part is that *you can select the categories*. So I would advocate for not allowing that, and instead adding a "generic" option at the end of each section when expanded. And then we would need some additional visual queue that it can be expanded.

I wonder if there is a way in general

**Comment by matkoniecz** [comment]
> I wonder if this type of interface should be avoided

Scrolling through loooong list of building types likely would be also problematic...

**Comment by FloEdelmann** [comment]
Just to throw in a new idea:

A long list of all options, ordered like it is now, but flattened. The most recently used options are sorted to the top, so quick answering for same building types is still possible.

Above the list: A text field that filters that list based on the name, description (and maybe also English name/description for non-English users), like the one in the iD editor.

**Comment by ei8fdb** [comment]
I've put together some wireframes based in issue #5192, as I was going to suggest the exact same UI change in this ticket! :)

The wireframes can be also seen here https://miro.com/app/board/o9J_kitrI3E=/
