### ISSUE TITLE
localized quests

### ISSUE THREAD

**Issue by matkoniecz** [westnordost/StreetComplete#214]
It is already planned according to #188

> offline reverse country geocoder (GPS position -> country+region you are in, necessary for localized quests

And I created this issue mainly to link https://josm.openstreetmap.de/ticket/10387 that is about implementing very similar feature in JOSM (feature is implemented and currently used).

**Comment by westnordost** [comment]
basically implemented already in maxspeed branch. The infrastructure can now be used for any quest type.
