### ISSUE TITLE
Improve the instructions for the "steps direction" quest (or a SC bug?)

### ISSUE THREAD

**Issue by cyclingcat** [westnordost/StreetComplete#2140]
Hi,

today I solved my first four steps direction quests with SC v24.0 but wasn't sure if I did it the correct way. So I checked the corresponding ways with JOSM afterwards and noticed indeed that two of my edits with SC were wrong. The other two were correct.

But what has happened here? I tried to reproduce the situation with other stairs I know and finally found a location which is suitable to demonstrate it:

See this screenshot - the stairs are going upwards from the north to the south:

![steps_direction_1](https://user-images.githubusercontent.com/32601012/95218851-04922280-07f5-11eb-834c-84f389bfddde.png)

If the user clicks on the field at the bottom of the screen, the question is displayed:

![steps_direction_2](https://user-images.githubusercontent.com/32601012/95219012-2db2b300-07f5-11eb-8890-7beb5913fb2f.png)

If the user now clicks on the right-hand button (with the arrows showing to the bottom) because he assumes that this is the correct answer (the arrows point to the "upwards" direction on the map!), the wrong _incline_ tag is inserted into the OSM database. I'm not sure if this is a bug in SC (does it handle the direction of the OSM way correctly?) or just an operating error by myself, but in either case there is something that should be improved before more users use this quest, possibly running into the same SC bug or at least making the same mistake that I did.

The cycling cat

**Comment by westnordost** [comment]
Hmm, you forgot to include a third picture, where the form is shown with the preview what will be tagged.

**Comment by cyclingcat** [comment]
Here it is:

![steps_direction_3](https://user-images.githubusercontent.com/32601012/95230450-3493f280-0802-11eb-9992-c81479a419c5.png)

The arrow here shows in the "downwards" direction! Is this something the user should pay attention to? And if it is, what should the user do now?

The cycling cat

**Comment by westnordost** [comment]
Yes, he should What he should do is to select the other one.

**Comment by cyclingcat** [comment]
So the workflow for the user is:

1. Click on the quest icon.
2. Click on the image in the lower part of the screen, see screenshot 1.
3. Choose one of the two appearing icons. **_(It might be the wrong one!)_** See screenshot 2.
4. Check if the arrow in the next screen (see screenshot 3) shows in the correct "upwards" direction. If it doesn't:
  4a. Click on this icon
  4b. Like 3., but choose the other icon.
5. Click Ok.

At least steps 4.* don't look self-explanatory to me, this part of the whole procedure is probably error-prone, so it deserves at least a better guidance to the user IMHO. If it's for some reason hardly possible to replace this workflow with a more straighforward one I'd suggest at least to change the text above the graphics in the three screenshots in order to describe precisely what the user should do.

The cycling cat

**Comment by westnordost** [comment]
You are right

**Comment by westnordost** [comment]
How about this?

![Screenshot_1602013042](https://user-images.githubusercontent.com/4661658/95251640-218e1c00-081c-11eb-837f-0c7cb8916e33.png)
![Screenshot_1602013088](https://user-images.githubusercontent.com/4661658/95251724-3bc7fa00-081c-11eb-8e71-e6057779b520.png)

**Comment by RubenKelevra** [comment]
Yeah I noticed that the other day too. Is it possible to rotate the arrows/streets in the 'choose direction' pop-up to the same degree that the way below is rotated?
