### ISSUE TITLE
let the "tactile paving on crosswalk" quest also look for highway=traffic_signals which have crossing=traffic_signals

### ISSUE THREAD

**Issue by Lukas458** [westnordost/StreetComplete#2141]
**Use case**
When looking at nodes, mostly highway=crossing represents a crossing. But the traffic-light-crossings can also be represented by highway=traffic_signals + crossing=traffic_signals, as we pointed out in #2130 .

Now, it would be nice if tactile_paving=yes/no tagging would also be supported for these kind of "special tagged" crossings.

**Proposed Solution**
So would it be possible to let the "tactile paving crosswalk" quest look for highway=crossing as well as for the combination of highway=traffic_signals + crossing=traffic_signals?

Is it possible to let a quest "look" for the combination of two tags?

Maybe something like this:
node[highway = crossing][foot != no] -> .crossings;
node[highway = traffic_signals][crossing=traffic_signals][foot != no] -> .crossings;

...

**Comment by westnordost** [comment]
Right, this would be possible. Why only `crossing=traffic_signals` though?

**Comment by Lukas458** [comment]
Hmm, maybe also other values of crossing=* can be combined with highway=traffic_signals, yes. Could be that this may be the case in some countries, but I don't know. No matter. So we could just take the combination of highway=traffic_signals and crossing=* (but then we need to exclude crossing=no again, definitive).

**Comment by westnordost** [comment]
Ah right, would probably be a tagging mistake if it was not `crossing=traffic_signals`, wrong thinking by me.
