### ISSUE TITLE
Selecting sign button in Max Weight quest crashes app.

### ISSUE THREAD

**Issue by mxxcon** [westnordost/StreetComplete#2147]
Streetcomplete crashes when I tap on "select sign" button in "Weight limit" question.
I have also submitted this using Android's builtin crash report feature.

**How to Reproduce**
Tap on weight limit quest. Tap on "select sign" button.

**Versions affected**
Android 9
Streetcomplete 24.1

**Comment by westnordost** [comment]
Oh damn, I deleted one line too much... :-(
