### ISSUE TITLE
pressing OK button does not save note when keyboard is present

### ISSUE THREAD

**Issue by IpswichMapper** [westnordost/StreetComplete#2149]
If you press the "OK" button after typing out a note, the note is not saved ,rather the keyboard goes away. Then you have to press the OK button.

i.e. cannot close the note while the keyboard is open.
You have to press twice to save a note

**Comment by westnordost** [comment]
This is deliberate. The user should have the chance to check if the note is at the right position on the map before pressing OK. While the keyboard is open, he can not properly do that.

**Comment by IpswichMapper** [comment]
Can't the chrcking be done before the keyboard is opened?

**Comment by westnordost** [comment]
But many won't. It's not like people would deliberately think "oh, let's double-check if it is at the correct position!", better if the final position is once more shown to the user always before he can OK it.

**Comment by matkoniecz** [comment]
I used this final moment to adjust note location, multiple times.

Often because GPS updated my location while I was writing note.
