### ISSUE TITLE
refetching solved quests

### ISSUE THREAD

**Issue by matkoniecz** [westnordost/StreetComplete#215]
To reproduce:

- solve quest
- upload to OSM
- immediately manually requests new quests
- it is possible that executed query is run on overpass database that is not (yet) including changes made by the user
- as result the same quests that were solved may be recreated, what is more likely as overpass database lag is higher

Probably the same may happen with automatic fetches for quests.

To solve this StreetComplete probably need to remember quests that were solved and uploaded recently (quests needs to be remembered after upload for longer time than the overpass database lag at time of fetching new quests).

Statistics about database lag are at https://overpass-api.de/munin/localdomain/localhost.localdomain/osm_db_lag.html

**Comment by westnordost** [comment]
Manual download is only intended as an option to "download for offline". In the future, the "manual download" option will be replaced with such an option.

The problem should not happen with automatic download.
