### ISSUE TITLE
Quest: Wheter fuel station provides a pump for adblue.

### ISSUE THREAD

**Issue by davidbaumann** [westnordost/StreetComplete#2150]
### General
Affected tag(s) to be modified/added: [fuel:adblue](https://wiki.openstreetmap.org/wiki/Key:fuel:adblue)
Question asked: **Does this gas station offer a pump for adblue?**

### Checklist
Checklist for quest suggestions (see guidelines):
- [x] 🚧 To be added tag is established and has a useful purpose
- [x] 🤔 Any answer the user can give must have an equivalent tagging (Quest should not reappear to other users when solved by one)
- [x] 🐿️ Easily answerable by everyone from the outside but a survey is necessary 
- [x] 💤 Not an overwhelming percentage of elements have the same answer (No spam)
- [x] 🕓 Applies to a reasonable number of elements (Worth the effort)

I was driving around looking for a pump for adblue for my car, as I need over 10 liters. OsmAnd allows me to filter for that, but actually it's almost never tagged in Germany where I live.
In Hungary, there are many gas stations tagged, also with fuel:adblue=no, where there is no pump. 

### Ideas for implementation

All amenity=fuel will be asked for, with a simle yes/no field, where fuel:adblue does not exist.

**Comment by matkoniecz** [comment]
duplicate of  #2151
