### ISSUE TITLE
Splitting a road in two: Slice a way instead of pointing on it

### ISSUE THREAD

**Issue by Spanholz** [westnordost/StreetComplete#2152]
**Use case**
Currently one has to point on certain spot where a way is cut to mark two different road surfaces, speed markings, etc.

Instead of pointing on a point where a way should be split I propose a slice. Like in the game Fruit Ninja. A simple slice that would cut the road in two parts. I for myself never felt so good and sometimes had two markers but I wasn't sure what that means.

**Proposed Solution**
Either the cut is shown afterwards and could be moved to the point where the way should be split or the way is cut directly.

**Comment by westnordost** [comment]
How to move the map then?

**Comment by Spanholz** [comment]
Maybe a scissor symbol, which opens a slicing mode, which can be canceled by a cross button?

**Comment by rhhsm** [comment]
I think slicing is less accurate than the current method, so I wouldn't waste time on coding this.

**Comment by westnordost** [comment]
Regarding accuracy, there is one thing that people may not know about the splitting: The app calculates the estimated radius of the user's finger on the map (based on the zoom level) and will automatically snap the tapped position to the closest vertex (node) of the way within this radius.

**Comment by rhhsm** [comment]
> 
> 
> Regarding accuracy, there is one thing that people may not know about the splitting: ...
That's interesting to know. There are many other things that are interesting to know, esp for users who want to suggest improvements here. Maybe the wiki could be used as a space to occasionally add info on how the app works?
I'm offline while surveying, so for me it would be best if the density of quests is as high as possible, so I need to visit a certain area less often. But I haven't figured out yet how SC decides which quests to show; it's often unpredictable for me. Could you enlighten us?

**Comment by smichel17** [comment]
There is an explanation in another issue (not sure which one off hand and currently on mobile), but the gist is that quests are downloaded in the order from the settings until you have "enough" showing. I don't remember exactly what "enough" is but it's something like, at least one quest within X  distance of your location and at least Y quests within Z distance of your location.

Practically, if you want to get as many quests as possible, pan to the area you will be surveying and keep selecting menu > "scan for quests here" until it tells you there are no more. (But note there are some quests that won't appear until others are answered and uploaded, so you cannot always guarantee a single offline trip will answer all quests in the area.l

**Comment by rhhsm** [comment]
> 
> 
> There is an explanation in another issue (not sure which one off hand and currently on mobile), but the gist is that quests are downloaded in the order from the settings until you have "enough" showing. I don't remember exactly what "enough" is but it's something like, at least one quest within X distance of your location and at least Y quests within Z distance of your location.
> 
> Practically, if you want to get as many quests as possible, pan to the area you will be surveying and keep selecting menu > "scan for quests here" until it tells you there are no more. (But note there are some quests that won't appear until others are answered and uploaded, so you cannot always guarantee a single offline trip will answer all quests in the area.l

It would be nice to find such explanations in a central easy to find place. I think we may disagree on what's "enough", for me the density of quests can never be too much. There might be a desire for not too many overlapping pins, but for me I'd rather have many overlapping pins than pins missing for which I have to go back later.

I'm already scanning for quests multiple times until there appear to be no more, but then, sometimes much later, more appear after I solved many of them.

**Comment by matkoniecz** [comment]
See #122 #2169 - there is an active work by @westnordost to change behavior of SC here, so spending time on documenting current behavior is not too useful

**Comment by smichel17** [comment]
@rhhsm For now: https://github.com/westnordost/StreetComplete/issues/1829#issuecomment-628853379

**Comment by timothywashere** [comment]
I'd just like to say, notwithstanding what everyone else has said, I think it's a really cool idea

**Comment by timothywashere** [comment]
I get really frustrated constantly splitting the way, it takes A lot of button presses. Usually in adding staircases to long footpaths. It would be cool if you could just slice the way when you have already selected the quest and it would ask if you wanted to split the way at that point. 

It's also a shame that there's no option to automatically split the way at your current location, as I am always standing at the exact spot where the staircase begins or ends
