### ISSUE TITLE
Direction on stairs quest is confusing (in german)

### ISSUE THREAD

**Issue by lightonflux** [westnordost/StreetComplete#2159]
The quest added in #1817 is really confusing. But i guess it is (only) because of the german translation 
The current phasing is wrong: the translation should be "Welche**_r_** Weg führt auf dieser Treppe nach oben?"

When i saw the quest in the app i had no idea what is asked. Because Weg usually means path/way. Richtung (direction) would be a better fit.

Or maybe rephrase the question completely: In welcher Richtung geht es auf dieser Treppe aufwärts?

![image](https://user-images.githubusercontent.com/1377943/95781609-7b845b00-0cce-11eb-87c9-092c0a975fa5.png)
![image](https://user-images.githubusercontent.com/1377943/95781846-eafa4a80-0cce-11eb-8308-c2f137d8e4b7.png)

**Versions affected**
v24.0

**Comment by westnordost** [comment]
Ja, welcher Weg im Sinne von welche Richtung. Wie wärs mit "Welche Richtung führt auf dieser Treppe nach oben?"

**Comment by tintinmaster** [comment]
In POEditor ist das schon geändert seit 4 Tagen

**Comment by westnordost** [comment]
ah, super
