### ISSUE TITLE
Update app version in F-Droid

### ISSUE THREAD

**Issue by resah** [westnordost/StreetComplete#216]
Love this app, but I am one of the few without Google account and depend on F-Droid apps.

I am told Play Store already provides version 0.10 while F-Droid still provides only 0.8 of StreetComplete.

It would be great to have the latest version in F-Droid, too.

Thanks a lot for this great app.

**Comment by matkoniecz** [comment]
See https://gitlab.com/fdroid/fdroiddata/merge_requests/2235

It appears that delay at this point is caused by slow update with F-Droid system itself and it is not caused by the author.

**Comment by resah** [comment]
A thank you, i didn't know how the F-Droid release worked.

**Comment by Hillside502** [comment]
@matkoniecz 

> See https://gitlab.com/fdroid/fdroiddata/merge_requests/2235

doesn't show when StreetComplete author submitted 0.10 to F-Droid

**Comment by matkoniecz** [comment]
This link includes data of opening pull request. From history of the affected file it is also clear that update PRs are not made by the author of the app but by fdroid users.

**Comment by Hillside502** [comment]
@matkoniecz 
So, are we saying that StreetComplete is **pushed** to Google Play Store, but **pulled** to F-Droid?

**Comment by westnordost** [comment]
Actually, it is not necessary to do anything regarding F-Droid. F-Droid detects and pulls updates automatically through some automatic script. However, that script is apparently not executed too often. So, updates take a while to appear on F-Droid.

Some people become impatient and manually make F-Droid pull the newest version by filing a pull request which, when merged, triggers an update faster - at least that is what the people who file such pull requests believe, I am not so sure about that.

**Comment by stephan75** [comment]
Why not using the apk file from

https://github.com/westnordost/StreetComplete/releases ?

**Comment by Hillside502** [comment]
@stephan75 
F-Droid has an obsession with only compiling from source.
