### ISSUE TITLE
Information sign content is not multiple choice

### ISSUE THREAD

**Issue by lightonflux** [westnordost/StreetComplete#2163]
Hello dear contributors,

how do you tag the content of a sign with two topics?

Found a sign in a park that was informing about plants and wildlife. But in sc I can only select one topic.

**Versions affected**
V24.1

**Comment by westnordost** [comment]
Nature?

**Comment by westnordost** [comment]
Why don't you select nature?

**Comment by lightonflux** [comment]
I thought that was to general. But i get the point.
