### ISSUE TITLE
localization issue (no german translation) of question "Does this pedestrian crossing have an island?"

### ISSUE THREAD

**Issue by ironspock** [westnordost/StreetComplete#2164]
StreetComplete v24.1
localization issue (no german translation) of question "Does this pedestrian crossing have an island?"

**Comment by westnordost** [comment]
What? That quest type is not even released yet.

**Comment by westnordost** [comment]
Which version are you using? From where?

**Comment by HolgerJeromin** [comment]
My phone says I got v24.1 beta from play store on 8.10.2020

**Comment by westnordost** [comment]
Hm, might have been a mistake by me. So F-Droid v24.1 is actually some kind of early v25.0-beta1: When I created the v24.1 release I accidentally put the `v24.1` tag on master, not on the `24` branch. I corrected that later, but it looks like the F-Droid build bot registered v24.1 in the meantime.

**Comment by matkoniecz** [comment]
And in general translation can be fixed/improved/done as described at https://github.com/westnordost/StreetComplete/blob/master/CONTRIBUTING.md#translating-the-app
