### ISSUE TITLE
support excluding "payment:others=no" objects from the "accepts cash as payment" quest

### ISSUE THREAD

**Issue by Lukas458** [westnordost/StreetComplete#2165]
**Use case**
Hello,
I have two questions concerning the "accepts cash as payment" quest.
1. Am I right that this question only affects things which have a name? If it would, amenity=telephone and amenity=vending_machine for example, which are mentioned in the quest, wouldn't get affected then. But it may be that my interpretation of the overpass query of this quest is not correct.

2. Would it be possible to exclude objects which haven't any of the tags _payment:cash_, _payment:coins_ and _payment:notes_, but which do have the tag _payment:others=no_? The tag is described here: https://wiki.openstreetmap.org/wiki/Key:payment#Showing_that_the_list_of_accepted_payments_is_complete and it can be used to show that all not-tagged payments aren't accepted. Its usage has increased over 2000 times, most by payment:others=no.

Even though the use case maybe would not affect so many objects, the use would concern small amenities like this: https://www.openstreetmap.org/node/1603516226
for which the question would come when I interpret the quest right, but the question wouldn't have to be asked, because all accepted payment are tagged already and that is shown by payment:others=no. As for shops it would not even be so, here in Europe many more amenities "go away from cash payment" with the time, and I think that's also the issue because of which this quest exists, and so it would be great if payment:others=no would be supported.

**Proposed Solution**
Exclude objects which just have the tag _payment:others=no_ (no need to look at other tags) from the accepts_payment quest, because payment:others=no shows that all accepted payments are tagged already.
Of course this can change over the time, but that's another issue. Also, I don't think many objects will accept cash in the future again if they didn't accept it in the past.

**Comment by westnordost** [comment]
That quest ist disabled for all countries except Sweden, you know that?

**Comment by Lukas458** [comment]
Oh, it's _dis_ abled for all countries except Sweden, okay. Then sorry, my interpretation of the code was wrong then. I thought it would be _en_ abled for all except Sweden. Okay, so then we can close this or by the way I don't know the situation in Sweden, but as this quest is only for one country, the effect might be not worth the effort.

**Comment by westnordost** [comment]
Yeah me neither. This quest was basically created because some Swedish guys requested it, saying that it is becoming commonplace that you cannot buy things with cash anymore

**Comment by westnordost** [comment]
Otherwise, or in countries I know, this quest wouldn't make sense because shops are legally required to accept cash iirc.
