### ISSUE TITLE
3d view stuck at one tilt angle

### ISSUE THREAD

**Issue by arne182** [westnordost/StreetComplete#2166]
![Screenshot_20201015-134015_Street­Complete](https://user-images.githubusercontent.com/844102/96147710-d94fb780-0f07-11eb-82ca-16ef8011066a.jpg)
![Screenshot_20201015-134026_Street­Complete](https://user-images.githubusercontent.com/844102/96147749-dead0200-0f07-11eb-9192-cda0e9199e5a.jpg)
Tilting just slightly up or down reduces the view to 2d.

**How to Reproduce**
Have not reproduced it yet

**Versions affected**
Android 8
24.1

**Comment by westnordost** [comment]
I don't understand this bug report

**Comment by arne182** [comment]
Do you see the church with the multi level in the first picture. Just by adjusting the tilt the church flattens to what we always had in the past.

**Comment by westnordost** [comment]
Ah! Hmm...

You have 24.1 from F-Droid?

**Comment by arne182** [comment]
24.1 from play store

**Comment by westnordost** [comment]
Ok, JawgMaps actually updated their tile schema, so whatever is the problem with v24.1 will be fixed (or different) with v25.0, currently in beta.

**Comment by smichel17** [comment]
@westnordost Would you be interested in a PR that adds the git commit to the version name (or similar), like this?:

https://github.com/LibreShift/red-moon/blob/master/app/build.gradle#L47

Makes it just a little bit less ambiguous which version someone is using.

**Comment by westnordost** [comment]
Wouldn't help in this case because this is not a debug version

**Comment by smichel17** [comment]
Well, it can be done for the release version, too. I just only did it for debug for Red Moon since I never had many different release versions to keep track of. Then again, maybe the version number is usually good enough and this mistag is just an exception

**Comment by westnordost** [comment]
Yes, I think it is good enough
