### ISSUE TITLE
Possibility to download/fetch/cach map data/tiles for a certain area

### ISSUE THREAD

**Issue by NotSoImportant** [westnordost/StreetComplete#2169]
**Use case**
Offline / bad mobile internet connnection
Currently it is possible to prefetch map data by scrolling through it. But
- it takes a lot of time (e.g. fetching along a route) 
- needs to be repeted in several resolutions
- even with a big cache sometimes the map data is not available later (sometimes zooming out and in helped, sometimes it was just gone) 

That is why I nearly stopped using SC, although I love it's simplicity for editing otherwise. 

**Proposed Solution**
1) Have a button like "search for quests here" to "cache map here"
2) better keep the map cache persistent
3) have an indicator shown what is the limits to be fetched (if not the screensize) - "search for quests" seems to use a bigger/different radius / rectangle - so 3 applies to this as well

**Comment by peternewman** [comment]
See e.g. #122 this is a duplicate @NotSoImportant

**Comment by westnordost** [comment]
Correct, it is a duplicate and I will soon start working on this!

**Comment by NotSoImportant** [comment]
Hi, I was about to write that although it might look like a duplicate it is not, because it rather proposes
1) a work around that could hopefully be added with little effort
2) some fixes (that probably could be out of reach)

But since you told you would be starting soon, that sounds amazing.
**When is soon and how long will it take? ;-)**

**Comment by westnordost** [comment]
I am already working towards it. #1901 is groundwork for that and that will likely be released in v26.0. Offline-download is planned to be implemented mid of November.

**Comment by NotSoImportant** [comment]
You make me happy 😊 👍
