### ISSUE TITLE
Offline mode

### ISSUE THREAD

**Issue by nikolajsheller** [westnordost/StreetComplete#217]
I live in an area where there is spotty or no cellular network access, coincidentally this is also an area that great need for this app.

Being able to use this app while offline would be invaluable.

**Comment by matkoniecz** [comment]
I am using this app offline without issues.

Remember to set high map cache size in settings, scan for quests in the intended area and pan map around to download tiles. All this can be done in the menu (three dots in top right).

After doing this bring mobile to wifi to allow for answer upload.

**Comment by matkoniecz** [comment]
Also in the readme

> Since the app is meant to be used on a survey, it can be used offline

So in general it would be better to make precise requests (after checking whatever given feature requests is already discussed somewhere).

**Comment by nikolajsheller** [comment]
I think my use-case may be slightly different than what this app caters to.

I live in a third-world country, and I am often without Internet for days, and I often travel large distances where I do not always know where I will be going beforehand (i.e. working in and doing safaris in Northern Botswana).

My use-case is probably closer to OsmAnd with offline editing capabilities.

For mapping around the town I live in this is a great app.
Thank you for the app, and thank you for your answer to my question.

**Comment by matkoniecz** [comment]
> I do not always know where I will be going beforehand

Main problem here is that Overpass queries are quite expensive (though for areas with low-density data it is OK to run queries on larger areas). Can you guess with any precision better than "Northern Botswana" where you will be?

**Comment by westnordost** [comment]
Well, to use anything offline, you need to download the area where you want to go before you go there. After that, you can edit offline. To download the quests in an area, pan the map to that place, zoom out so that the screen covers that area and press "scan for quests here".
(That won't download the map for offline though, this is not implemented yet.)

**Comment by nikolajsheller** [comment]
Thank you for the app, and for taking time to consider and respond to my ticket.
