### ISSUE TITLE
Crossing tactile paving question not adding surveyed tag

### ISSUE THREAD

**Issue by dbdean** [westnordost/StreetComplete#2170]
I'm been walking around my area confirming crossing tactile paving and just noticed all the quests reappeared after a week. Looking at some examples, it looks like StreetComplete has not adjusted the crossing at all if I confirm the existing information:

I just walked past both of these after lunch, and answered them, but there has been no update on the nodes for two years:

https://www.openstreetmap.org/node/5360243110
https://www.openstreetmap.org/node/5360243269

**How to Reproduce**
Answer a tactile paving question that was no before with no in a re-survey.

**Versions affected**
v24.1 and Android 10 (OxygenOS 10.3.5)

**Comment by dbdean** [comment]
For example, this walk had a lot more than just two crossings updated: https://www.openstreetmap.org/changeset/92507652

Looks like I'm going to retracing my steps a bit here once this bug is fixed :)

**Comment by westnordost** [comment]
Crossing type? But the crossing type (unmarked, marked, ...) is only asked every 8 years, why does it even show up for you?

**Comment by westnordost** [comment]
Oh, I misread. It's about the tactile paving

**Comment by peternewman** [comment]
It's this isn't it @westnordost #2172 ?

**Comment by westnordost** [comment]
Yes! I just fixed it parallel to you, actually but I will merge your PR instead, thank you!

**Comment by westnordost** [comment]
@peternewman did you now install Android Studio?

**Comment by peternewman** [comment]
> @peternewman did you now install Android Studio?

No... sorry.

I assume you made the exact same change though?

**Comment by westnordost** [comment]
yes, I did. I just thought the amount of changes you make recently it would be much more convenient for you if you had a proper IDE to work with and test with

**Comment by peternewman** [comment]
Heh maybe, but then I'd probably fall completely down that rabbit hole, believe it or not I'm just trying to be a user of SC! :laughing:

**Comment by westnordost** [comment]
Well, look at it from this angle: If your goal is to invest your time reserved for OpenStreetMap most efficiently (add most data / keep it up to date), then it is probably more efficient to work on tools to make it easier for others to contribute than to (only) contribute yourself.

**Comment by smichel17** [comment]
> it is probably more efficient to work on tools to make it easier for others to contribute than to (only) contribute yourself.

This is basically why I hang around here; why I am part of the [Snowdrift.coop](https://snowdrift.coop/) team; and why I donate to [Represent.us](https://represent.us/). Approaching things from a systemic perspective just has so much more potential than trying to fix problems one-by-one (of course, someone also needs to do the one-by-one fixing, with the help of systemic changes).
