### ISSUE TITLE
general waste container enhancement

### ISSUE THREAD

**Issue by Sierzh** [westnordost/StreetComplete#2171]
hi there. the app is need enhancement request for  a general waste container (black bags) that can be recycled.
like this: **recycling:waste=yes/no**

**Comment by westnordost** [comment]
You can answer Other answers -> "It's for general waste"

**Comment by westnordost** [comment]
In general, by the way, black bags are not recycled, they are either incinerated or dumped. The correct tag for a place where you can dispose waste is `amenity=waste_disposal` and this is exactly what StreetComplete tags if you choose this answer.
