### ISSUE TITLE
"Is this stretch of way lit?" query should not be asked on indoor=yes ways

### ISSUE THREAD

**Issue by WoOS2** [westnordost/StreetComplete#2176]
At least Version 21.1 shows also ways which are indoors (e.g. in supermarkets) with this query. See e.g. https://www.openstreetmap.org/note/2361000#map=19/48.15075/17.17200 . It is difficult to imagine how indoor ways would not be lit, thus the lit tag is useless there (and in case of that supermarket showing the quest cluttered up the map for other quests).

According to https://wiki.openstreetmap.org/wiki/Indoor_Mapping  highway=footway+indoor=yes is a valid representation of indoor paths and as such should be excluded from the quest.

**Comment by HolgerJeromin** [comment]
https://wiki.openstreetmap.org/wiki/Simple_Indoor_Tagging is the up to date approach. But skipping them seems a good change in any case.

**Comment by matkoniecz** [comment]
I would expect `highway=corridor` to be used for such ways, but skipping them makes sense to me.

**Comment by peternewman** [comment]
Both https://wiki.openstreetmap.org/wiki/Key:indoor and https://wiki.openstreetmap.org/wiki/Indoor_Mapping seem to include cases I'd imagine would be https://wiki.openstreetmap.org/wiki/Key:covered such as a walkway between two buildings with just a roof, if they're tagged as indoor there is no guarantee they're lit. Although I'd agree we could just not ask.

Should that be the same with most underground stuff then, which is also generally likely to be lit (but 24/7)?

**Comment by matkoniecz** [comment]
Thanks for reporting!

![screen01](https://user-images.githubusercontent.com/899988/96377794-42456280-1188-11eb-97f5-f008cee909df.jpg)
