### ISSUE TITLE
Achivement "On the Road" ist translated to "Autofahrer" in the German language

### ISSUE THREAD

**Issue by Natenom** [westnordost/StreetComplete#2178]
The translation should not imply a specific vehicle.

**How to Reproduce**
Open Profile, then Achievements :)

**Versions affected**
Current Version.

**Comment by matkoniecz** [comment]
See https://github.com/westnordost/StreetComplete/blob/master/CONTRIBUTING.md#translating-the-app - anyone may (quite easily) fix translations, it does not require programming.

**Comment by Natenom** [comment]
Oki, I wrote a comment on peoeditor.

**Comment by matkoniecz** [comment]
Feel free to simply change translation, if there is a clearly better alternative! German is a bit unique as @westnordost also can improve it, but translations for such programs are generally made by whoever speaks given language.

**Comment by Natenom** [comment]
Ok. Done. Thanks :)
Closing.

**Comment by matkoniecz** [comment]
In general see https://wiki.openstreetmap.org/wiki/Translation#Editors_and_other_contributing_tools (this specific section and rest of the page).

In nearly all of cases you can improve/add translations for various tools. (and the same often applies also to nonOSM software)

**Comment by westnordost** [comment]
Just [found out about it yesterday](https://de.wikipedia.org/wiki/Natenom) through a friend. Not sure where else to post that, so, rest in peace, Natenom.
