### ISSUE TITLE
Additional "On a farm" building types

### ISSUE THREAD

**Issue by Carnildo** [westnordost/StreetComplete#2180]
Two additional "on a farm" buildings I would have found useful recently:

1. Silo (`man_made=silo` + `building=silo`)
2. Barn (`building=barn`)

**Comment by westnordost** [comment]
Isn't a barn an all-purpose farm building? For that there is already an option

Am 19. Oktober 2020 09:41:26 MESZ schrieb Carnildo <notifications@github.com>:
>Two additional "on a farm" buildings I would have found useful
>recently:
>
>1. Silo (`man_made=silo` + `building=silo`)
>2. Barn (`building=barn`)
>
>
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/westnordost/StreetComplete/issues/2180

-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.

**Comment by Carnildo** [comment]
I don't know.  "All-purpose building" is rather vague.

**Comment by matkoniecz** [comment]
`building=farm_auxiliary` is mixing barns with pigsty and woodshed and chickencoop and covering of a manure dump

Especially for barns I sometimes left StreetComplete and tagged it with Vespucci instead. Though I worried that adding `barn` will open floodgates for 271817 specific building types that may be found on a farm, that is why I never proposed to add it.

**Comment by rhhsm** [comment]
I think there's space enough to add it for those who want to use it (which includes me).
For the "others" category, I find that the service buildings I find are almost always power substations, so could that be added as an option (power=substation + building=yes, "A building containing transformers")? I don't mind if hangar and bunker are dropped instead; there are very few of them. As for the public buildings, I'd like to have community centre, library and clinic, and have the school buildings sorted by age (kindergarten - primary school - secondary school - university). Maybe school buildings can be given as a subcategory, to save some space. Just asking...

**Comment by westnordost** [comment]
So, what is a barn used for?

**Comment by matkoniecz** [comment]
Heh, sounds simple but reveals a nasty US vs UK language trap

> In the North American area, a barn refers to structures that house livestock, including cattle and horses, as well as equipment and fodder, and often grain.[2] As a result, the term barn is often qualified e.g. tobacco barn, dairy barn, sheep barn, potato barn. In the British Isles, the term barn is restricted mainly to storage structures for unthreshed cereals and fodder

**Comment by rhhsm** [comment]
> 
> 
> So, what is a barn used for?

According to the OSM wiki, "for storage and as a covered workplace", and not for keeping animals. But if the Yanks want to keep animals in it, they can go ahead :) In general, I think "barn" should mean what it means in the area in which it is mapped.

**Comment by westnordost** [comment]
And how can you see from the outside if it is a covered workplace, storage or for keeping animals? Modern farm buildings are built like industrial warehouses.

**Comment by cyclingcat** [comment]
This is of course a valid argument - but the same works for industrial buildings as well: How can you decide if the main purpose of a building with a company nameplate attached to it is an office, a factory, a warehouse or even a garage if you don't have the possibility to walk in, look around and maybe ask the people there? Perhaps it's the best solution to use more abstract tags in these cases (building:farm_auxiliary or building:commercial respectively) and leave more precise tagging to people with exact knowledge of the interior (and other OSM editing tools).

The cycling cat

**Comment by matkoniecz** [comment]
office vs factory vs warehouse vs garage is (except rare cases) easy to distinguish both in old and new buildings

**Comment by Carnildo** [comment]
>  Modern farm buildings are built like industrial warehouses.

There are a lot of older farms around here.

**Comment by westnordost** [comment]
And you can tell apart which older farm building is/was used for which purpose? I've recently been to some (old) farms, and every barn/building is just a building. Whether they have pigs inside, or it's a storage for hay, or a workshop (for tractors) or something else is not really visible from the outside from my experience. And more importantly, in which building exactly the farmer does or stores what is not exactly public information.

**Comment by smichel17** [comment]
I am not certain if these would be better suited to their own issue(s), so let me know if I should do that.

I had two farm-related questions on my last mapping foray. For context, this is in an area that is rural, but not in the middle of nowhere. These questions are both about edge cases where the answer to "is this on a farm?" is not so clear-cut.

1. Tagging a chicken coop. It appears that neither StreetComplete nor iD have a building type more specific than "Farm Building". SC advises that this applies to any non-residential building on a farm. However, this chicken coop is not on a farm; it is in someone's back yard. So I am not sure how to tag it. https://www.openstreetmap.org/note/2395715#map=19/42.31861/-72.66505
    -  Also, it (like most chicken coops?) is not really suitable for any other activity (compare with a barn, stables, pasture, etc, whose use may change over time), so it would be nice if there were a more specific tag.

2. Opposite scenario: this residential house, while it *is* on a small farm, is also part of a residential neighbourhood; it is not significantly different from nearby houses, aside from the buildings which happen to be around it. If I had seen the "FarmHouse" option when looking through the "farm" category a few minutes earlier, I probably would have tagged it as a detached house without a second thought; I am not really sure what value the "FarmHouse" tag adds — can't that be inferred from the fact that it is a detached house, and is on a farm? https://www.openstreetmap.org/note/2395705#map=18/42.31647/-72.66699
    - Note: the mixing of [former] farmland and residential neighborhoods is quite common. I've had similar questions in the past about how to tag renovated barns which now have a different use (garages, sheds, etc).

**Comment by westnordost** [comment]
1. Yes, it should be tagged as a chicken coop if it is a chicken coop. But farm_aux... wouldn't be wrong either. A chicken coop is a highly specific building value, Streetcomplete cannot contain all of the possible values.
2. Obviously, the transition between "just a house" and "just a house on a farm" is fluent. On modern farms where all the buildings are built anew, the farmhouse would of course look like any other house. But usually, I'd say that farmhouses tend to be older and/or have a distinct look.

**Comment by westnordost** [comment]
So, I'd close this now as will not fix. Reasons (summarized):

- **it is usually/often not visible what the farm building is used for from the outside**
- barn has a different meaning in US English and GB English. Wiki is not clear on which definition exactly should be used
- farms are private property, just like industrial landuses. For buildings on industrial grounds, there is simply `building=industrial` and not `building=assembly_hall` etc because it is also not really possible to see from the outside what each building is for, nor should it be relevant to record because it is private. For farms, this is somewhat similar
- since there are innumerable possible building values, it is better to try to limit to some kind of categorization and maybe only later ask to define it in more detail. `farm_auxiliary` is of course such a category

**Comment by Carnildo** [comment]
Could I get "silo" added, at least?  Unlike barns, silos are immediately obvious from the outside.

**Comment by westnordost** [comment]
There is storage tank for that, doesn't that fit?
![image](https://user-images.githubusercontent.com/4661658/97475633-c7313880-194d-11eb-81eb-56c00b4ce3df.png)

**Comment by matkoniecz** [comment]
Storage tank are for liquids and compressed gases. Silo is typically for storing grain.

**Comment by westnordost** [comment]
Hm well, I guess this would make sense. But how can a user tell from the outside if such a building is a storage tank or silo? Aren't they structurally the same?

**Comment by rhhsm** [comment]
I think a silo is a vertical cylinder that's taller than its diameter, while a storage tank's diameter is more than its height, or a horizontal cylinder. Thin tall buildings are more difficult to build than broad low buildings, so an engineer would only design one in that shape if the contents flow with difficulty (solid grains for instance) so you need some height to give enough pressure so you can drain it from the bottom. (I'm a chemical engineer)

**Comment by matkoniecz** [comment]
1) for shape mentioned by @rhhsm - buildings sized storage tank will AFAIK look like https://en.wikipedia.org/wiki/File:MiRO4.jpg https://en.wikipedia.org/wiki/File:Fuel_tank_gnangarra.jpg while silo like https://en.wikipedia.org/wiki/Silo#/media/File:Port_Giles_silos.jpg  https://en.wikipedia.org/wiki/Silo#/media/File:Harvestore_Silos_Britton_Michigan.JPG 
  
2) context (farm vs refinery, what is written on it and so on) often helps

Though https://en.wikipedia.org/wiki/File:Ralls_Texas_Grain_Silos_2010.jpg without clear context would be tricky

**Comment by Carnildo** [comment]
It's not the best picture in the world, but it shows what's probably the most distinguishing feature of the average silo: [the grain-unloading equipment on the side.](https://user-images.githubusercontent.com/22849154/97524805-b939e280-1962-11eb-8cdb-250b514924f0.jpg)

(The picture shows four of the 19 silos encountered on the trip that prompted this request.)

**Comment by matkoniecz** [comment]
Grain loading equipment shown on this photo seems also quite distinctive (not sure how typical it is, I am familiar with commercial farming but done on significantly smaller scale).

**Comment by Carnildo** [comment]
It's typical for a cluster of silos surrounding a grain elevator.  Individual silos (which are uncommon around here) usually don't have it.
