### ISSUE TITLE
Oneway quest: subtract cycle lane from usable width of street

### ISSUE THREAD

**Issue by westnordost** [westnordost/StreetComplete#2181]
The oneway quest is generated for all roads that have a width of 4m or less reserved for cars.

The `width` tag specifies the width of the whole road, from kerb to kerb. So, subtracted from that width are the parking lanes.

Further, cycle lanes if any should be subtracted as well.

**Comment by matkoniecz** [comment]
> So, subtracted from that width are the parking lanes.

Note that parking lane may be partially or fully on the sidewalk (there is a subtag for that).

**Comment by westnordost** [comment]
I know, this is already taken into account, see https://github.com/westnordost/StreetComplete/blob/master/app/src/main/java/de/westnordost/streetcomplete/quests/parking_lanes/ParkingLane.kt
