### ISSUE TITLE
Never ask for names of cemeteries and allotments

### ISSUE THREAD

**Issue by cyclingcat** [westnordost/StreetComplete#2186]
Hi there,

the quest for missing names is (among others) displayed for cemeteries and allotments. However, 99% of these quests have to be answered with "no name" because there isn't a sign with a name in the vicinity of these objects. This violates the "no spam" and "easily answerable" rules for quests.

**Some thoughts on this topic:**

Typically, **cemeteries** in villages don't have a name at all. According to my observations, names of cemeteries are only common in towns where more than one cemetery exists (probably in order to distinguish them by name). I guess that most of the latter ones got their "name" tags already a long time ago, leaving mainly just those cemeteries left which really don't have a name. A short check with Overpass Turbo (http://overpass-turbo.eu/s/ZgU) reveals that if a name tag ever exists in village cemeteries, it is in most cases trivial ("Cemetery of _villagename_" or similar), which supports my theory.

Concerning **allotments**: They also don't seem to have names very often and if they have "unofficial" names, Street Complete is the wrong tool to add them as it needs deeper research (asking people or similar) when there are no names on signs.

(This is valid at least for Germany, don't know about other countries though.)

The cycling cat

**Comment by matkoniecz** [comment]
So it is request to partially revert #1618

**Comment by rhhsm** [comment]
It's true for Bulgaria, but I don't mind being asked. For the Netherlands, cemeteries having names is more common, and allotments usually have a legal organisation ("volkstuinvereniging") managing them and the allotment carries the name of that organisation.

**Comment by cyclingcat** [comment]
Maybe it actually depends on the country (or region?). The mentioned village cemeteries or allotments here in south-west Germany usually don't have a sign with a name on it at their entrances. If they have really got a name there's the risk that the user answers these quests with "There is no name" (meaning: "There is no _visible_ name"), thus entering wrong information into the OSM database unintentionally (as @westnordost pointed out in https://github.com/westnordost/StreetComplete/pull/1618#issuecomment-546599275).

The cycling cat

**Comment by rhhsm** [comment]
> 
> If they have really got a name there's the risk that the user answers these quests with "There is no name" (meaning: "There is no _visible_ name"), thus entering wrong information into the OSM database unintentionally 

Would be nice if there would be a reply option "not visible" resulting in a tag name:signed=no (like for non-visible opening times).

**Comment by westnordost** [comment]
Not visible instead of "no name"?

**Comment by cyclingcat** [comment]
"Not visible" is at least more accurate than "no name", because the user isn't able determine on-site if the object really has no name or if it _has_ a name and it's just not signed anywhere.

Perhaps @rhhsm's idea is a good compromise and superior to my proposal to remove the quest completely: Leave the quest but tag the object accordingly. This would have two advantages: The tagging is more accurate and as opposed to hiding the quest other SC users would not see it in the future, having to hide it as well because they aren't able to answer it.

The cycling cat

**Comment by SlowMo24** [comment]
I would like to restart this conversation because the quest for the name of allotments is really bothering me. I think the name quest is important. Therefore I would like to keep it enabled. But there are many allotments and 99% of them don't have a name. Many are just single plots between farmland.

It would be great if I could disable the quest only for allotments.

I also think that the quest tries to circumvent a shortcoming of OSM (thereby enshrining it). As @rhhsm wrote above

> [...] allotment carries the name of that organisation.

meaning the place actually does not have a name but displays the ownership and management body prominently. I (personally!) know 0 allotments, that have a proper name. So we should rather establish something like tagging these places with [`club=allotments`](https://wiki.openstreetmap.org/wiki/Key:club) which then certainly gets a name.

**Comment by Helium314** [comment]
> But there are many allotments and 99% of them don't have a name

This is not true, as least concerning OSM elements. Have a look at taginfo: https://taginfo.openstreetmap.org/tags/landuse%3Dallotments#combinations

**Comment by matkoniecz** [comment]
> I would like to restart this conversation

If changes are needed - please create new one (issue or discussion). This one is from 2020 and it is not clear what would be changed now. And comments in closed issues are easy to miss (I am unlikely to remember to followup on this one).
