### ISSUE TITLE
highway construction quest should trigger resurvey of road features

### ISSUE THREAD

**Issue by RubenKelevra** [westnordost/StreetComplete#2188]
**Use case**
If a road gets a major overhaul usually a lot of features of the road are changed. 

**Proposed Solution**
It makes sense to reset all 'check_date' values to something like 'no' to indicate that the features need to be checked again if the construction is completed. Additionally, the resurvey quests need to recognize a 'no' value as 'resurvey required'.

**Comment by westnordost** [comment]
I agree that this would make sense, but I don't see any possibility to implement that technically.
