### ISSUE TITLE
rotating the phone unsets current selection of surface type

### ISSUE THREAD

**Issue by waldyrious** [westnordost/StreetComplete#219]
I recently noticed that if I start a street surface selection (e.g. I pick "paved (generic)" but not one of the sub-types yet) and rotate the phone before clicking OK, the selection I had made disappears and I have to pick the generic type again. The same happens if I had already picked a subtype, but not clicked OK yet.

This is mostly just inconvenient for users, but hopefully the fix is simple :)

**Comment by matkoniecz** [comment]
Duplicate of #197

**Comment by waldyrious** [comment]
Ah yes, I did search before opening this issue, but somehow missed that one. Thanks for the pointer. I would close this as a duplicate, but since that one is closed as wontfix, I'd rather leave this open, as a signal that I consider this worth fixing (or replacing with a different mechanism that avoids this problem, as described in #197).

**Comment by westnordost** [comment]
See @matkoniecz
