### ISSUE TITLE
Extend DetailRoadSurface to also cover for paths/footways/cycleways

### ISSUE THREAD

**Issue by unriccio** [westnordost/StreetComplete#2196]
**Use case**
Currently the DetailRoadSurface quest uses the ALL_ROADS list, that doesn't cover for paths/footways/cycleways.
(I recently passed nearby one of such cases and I wondered why StreetComplete didn't show me anything to detail the surface=paved footway I was on)

**Proposed Solution**
Either:
- add paths/footways/cycleways to the query used by DetailRoadSurface
or
- add a new quest covering only the "non-road" ways (as it is now when the surface tag is missing)

From this comment I'd understand that the second option may be preferred:
https://github.com/westnordost/StreetComplete/issues/279#issuecomment-563974925

(and thanks for that particular quest, it's always nice to find an excuse to resurvey an area) :)

**Comment by matkoniecz** [comment]
Implemented by #2078 that will likely be included in v26 :)

**Comment by matkoniecz** [comment]
To clarify: after this change mapping new surface, resurveying old surface data and detailing `paved` `unpaved` will be in road surface quest, path surface quest, cycleway surface part and footway surface part.

So "detail road surface" quest will disappear, but its functionality will appear in four surface quests.
