### ISSUE TITLE
Loading spinner gets stuck when no new quests are found

### ISSUE THREAD

**Issue by melbournefan** [westnordost/StreetComplete#2197]
Loading spinner gets 'stuck' and returns a white circle after the 'No further quests available' dialog appears on screen, the only way to get rid of the circle is to scan for quests again and wait for the dialog to appear
**How to Reproduce**

1. In an area that has already returned all quests available, in the menu press the 'Scan for quests here' button
2. Then the loading spinner will appear (before the 'no further quests available' dialog appears).
3. The circle will stay at the bottom of the screen unless you repeat the steps above again, note the bug only seems to appear after initially opening the app and wont occur again.

**Versions affected**
Android 10, on ColorOS 7.1 and StreetComplete 25.1

**Comment by HolgerJeromin** [comment]
Where did you find such an area?

**Comment by melbournefan** [comment]
Near where I live in Melbourne Australia. I've mostly completed the quests around here so I just check for quests again every few weeks (or when I update OSM)

**Comment by matkoniecz** [comment]
> I've mostly completed the quests around here so I just check for quests again every few weeks (or when I update OSM)

BTW, if you encounter any type of detailing worth doing and passing StreetComplete requirements ( https://github.com/westnordost/StreetComplete/wiki/Adding-new-Quests-to-StreetComplete ) then please create a new issue for that :)

**Comment by HolgerJeromin** [comment]
I found 
https://www.openstreetmap.org/?mlat=-29.78273&mlon=148.53666#map=19/-29.78264/148.53676
which does not have any quests.
But could not reproduce the bug.

**Comment by westnordost** [comment]
Thanks for testing! Which Android version are you using, @HolgerJeromin ?

@melbournefan can you always reproduce it like the way you described it?

**Comment by HolgerJeromin** [comment]
I have Android 10 on Motorola g7 Power with sc 25.1/25.0

**Comment by peternewman** [comment]
> I have Android 10 on Motorola g7 Power with sc 25.1/25.0

Likewise it doesn't do it for me in an area where it's simply downloaded all the quests, which I thought was what @melbournefan was mentioning initially.

Also just to pick up on @HolgerJeromin 's comment. It displays numerically 25.1 for me, but the 25.0 changelog, so you probably need to +2 the next release to avoid that issue causing issues.

**Comment by melbournefan** [comment]
> Thanks for testing! Which Android version are you using, @HolgerJeromin ?
> 
> @melbournefan can you always reproduce it like the way you described it?

Ironically, it doesn't seem to happen anymore. Just after I updated the app

**Comment by melbournefan** [comment]
> > I have Android 10 on Motorola g7 Power with sc 25.1/25.0
> 
> Likewise it doesn't do it for me in an area where it's simply downloaded all the quests, which I thought was what @melbournefan was mentioning initially.

What It done was it downloaded some quests, then I requested it again though the menu and that's where the bug would occur.

**Comment by peternewman** [comment]
> What It done was it downloaded some quests, then I requested it again though the menu and that's where the bug would occur.

It doesn't seem to do that for me either, it pops down again after saying there are no more quests.

**Comment by westnordost** [comment]
Still reproducible for you in v26.0-beta3, @melbournefan ?

**Comment by melbournefan** [comment]
I use the Google Play version of Streetcomplete so I wouldn't know until it's released

**Comment by smichel17** [comment]
You should be able to install the apk from https://github.com/westnordost/StreetComplete/releases on top of the Google Play release, and then the GPlay release will still update normally when it catches up. Or, if you are willing to set up an android development environment (this is not that hard, if you are willing to install Android Studio), you can install the debug version on your phone alongside the release version.

**Comment by melbournefan** [comment]
Looks like version 26 was uploaded in the early hours of the morning here, needless to say that I can't seem to replicate the issue in version 26.
