### ISSUE TITLE
v25.0 or v25.1?

### ISSUE THREAD

**Issue by cyclingcat** [westnordost/StreetComplete#2198]
Hi there,

I just noticed that the new version of StreetComplete released yesterday reports itself as version **25.1** [on Google Play](https://play.google.com/store/apps/details?id=de.westnordost.streetcomplete) and consequently this is the version number my two phones show in their app lists after the update. However, the "What's new" window and the [release on GitHub](https://github.com/westnordost/StreetComplete/releases) both bear the version number **25.0**.

(Just to be sure that there didn't go anything wrong with the new release.)

The cycling cat

**Comment by westnordost** [comment]
Oh, yeah, accidentally I named the version "v25.1". Well, then there is no v25.0 then, we skipped it. I'll change the tag on github
