### ISSUE TITLE
(Re-) Move the links on the main map screen

### ISSUE THREAD

**Issue by cyclingcat** [westnordost/StreetComplete#2199]
Hi there,

now that the GPS button in the lower right corner of the main screen has been reintroduced (a huge UX improvement IMHO!), another small problem appeared: On the bottom of the main map screen there are two text fields with links to JawgMaps and OSM. When I tap on the GPS button I sometimes inadvertently hit the OSM link, thus starting the default browser and breaking the workflow. Considering the fact that the GPS button is pressed probably 1000x more than the OSM link and the risk to hit the latter one inadvertently I'd suggest to at least remove these links on the map display (showing just the texts for attribution purposes), If you consider these links as useful, show them somewhere in the _About_ window. Yes, they are less prominent there, but how often does a user click on these link deliberately?

This will get more and more important in the coming winter season on the northern hemisphere where many users will start wearing gloves, thus losing tapping precision.

The cycling cat

**Comment by westnordost** [comment]
I'm legally required to show these links

**Comment by cyclingcat** [comment]
Okay, but do they really have to placed on the map screen? Wouldn't it be sufficient just to show the _text_ on the map screen (without the link) and put the link elsewhere (where it wouldn't be in the way like it is the case currently)?

The cycling cat

**Comment by peternewman** [comment]
Thinking outside the box, could they be left aligned instead? Then you could drop the other buttons down too.

**Comment by westnordost** [comment]
> Thinking outside the box, could they be left aligned instead? Then you could drop the other buttons down too.

Looks like @cyclingcat is a person with very small eyes and very big hands then ;-)  - or a small phone. By the way, @cyclingcat , you next smartphone should have an OLED display, the contrast in sunlight is much better than on an a classic LCD screen.

**Comment by peternewman** [comment]
> or a small phone

You may remember my phone is fairly diminutive too...

**Comment by cyclingcat** [comment]
Average-sized hands, smaller phones (4,5" and 5,5"), bad eyesight and still getting older 😃 Maybe OLED next time (but it has to be a waterproof one with a long battery runtime for cycling and walking purposes!).

But don't forget the use case "cycling/walking with smartphone-suitable gloves" which automatically enlarges the touched area on the display and reduces the tactile sense! Furthermore, my question "isn't a pure text string without a link sufficient, legally and otherwise" still remains unanswered.

So I checked some more apps with connection to OSM currently installed on my phones: 

* The widely used **OsmAnd~** doesn't show any attribution information on the map itself, however, in the "About" window there is a link to https://www.openstreetmap.org/copyright.

* **[OSM Contributor](https://play.google.com/store/apps/details?id=io.mapsquare.osmcontributor&hl=en)** (obviously by the JAWG people!) shows the attribution text in the lower left corner. No link.

* **Vespucci** dito.

* **[SatStat](https://f-droid.org/de/packages/com.vonglasow.michael.satstat/)** is also able to show the current position on an OSM-based map. Attribution is shown as a copyright notice at the bottom of the map, without a link.

After this short research I'd still vote for removing the link, leaving the text.

The cycling cat

**Comment by matkoniecz** [comment]
Note that ODBL license requires to

> include a notice associated with the Produced Work reasonably calculated to make any Person that uses, views, accesses, interacts with, or is otherwise exposed to the Produced Work aware that Content was obtained from the Database, Derivative Database, or the Database as part of a Collective Database, and that it is available under this License."

For case where OSM data is directly used to make a map, viewed by user it can be shortened and simplified to (note, I am not a lawyer)

> include a notice associated with the map reasonably calculated to make any Person that views the map aware that Content was obtained from the Database and that it is available under the ODBL License.

Yes, many data users are violating this requirements, for example maps.me show clearly readable attribution with text "MAPS.ME"

Though note that OsmAnd credits OpenStreetMap also on startup screen.

**Comment by matkoniecz** [comment]
Changing it to text only would require something along "OpenStreetMap (ODBL)" to handle also license part.

**Comment by smichel17** [comment]
+1 to text only, but for an entirely different reason: it does not look like a link, so I would not think to try clicking it. While a link on the about screen (or in the main menu?) would be harder to find, paradoxically I think I'd be more likely to end up clicking it.

**Comment by Atrate** [comment]
Even jusy moving the links to the bottom left corner of the map fragment would help

**Comment by westnordost** [comment]
On the left side, there is the undo button though. I will see what I can do.

Maybe not opening the link directly but instead showing a dialog that shows the URL on which one can tap would help too

**Comment by cyclingcat** [comment]
This would mitigate the problem, at least a little, as the undo button is (hopefully) tapped much less often than the GPS button. But is a link here really necessary **here** (for legal or other reasons)? If just the link would be removed, the text could stay at its position. If someone wants to find the precise license information, he could easily (or even more easily, according to @smichel17's comment above) find it in the _About_ screen. There is already a link to the GPL text, maybe put the OSM license link next to it?

The cycling cat

**Comment by peternewman** [comment]
> On the left side, there is the undo button though. I will see what I can do.

I'd imagine people press that less often than the other buttons (hopefully), so undo could always move up couldn't it?

**Comment by peternewman** [comment]
Looks good @westnordost . Any reason the URLs aren't also click-able in the pop-up dialog? I tried to click and select it a few times before I spotted and pressed okay.
