### ISSUE TITLE
explain objects with no name

### ISSUE THREAD

**Issue by Haikuch** [westnordost/StreetComplete#22]
sometimes there are objects without a name, like this one:

https://www.openstreetmap.org/node/573381069

Then the app does just ask "What are the opening hours of this object" and you might not know exactly what object is meant (I only guessed it). For this situations it would be better to see something like "what are the opening hours of this object (shop=funeral_directors)"

**Comment by westnordost** [comment]
You are right, I will disable opening hours quests for objects that are not named.

The long-term solution is to display the generic feature name for an object if the name is not known, i.e. "supermarket". However, what is missing for that is some kind of localized dictionary from tags to primary features for each language.

Such a dictionary does not exist yet. 

On 21 March 2017 15:20:52 CET, Haikuch <notifications@github.com> wrote:
>sometimes there are objects without a name, like this one:
>
>https://www.openstreetmap.org/node/573381069
>
>Then the app does just ask "What are the opening hours of this object"
>and you might not know exactly what object is meant (I only guessed
>it). For this situations it would be better to see something like "what
>are the opening hours of this object (shop=funeral_directors)"
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/westnordost/StreetComplete/issues/22

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by Haikuch** [comment]
> You are right, I will disable opening hours quests for objects that are not named.

mh, thats not been my intention. I would prefer to explain them with the tagging (like shop=*). That might not be the most beautiful solution, but I personally like it more to have raw informations. I see that many developers don't like to confront their users with tags, but in a mapping tool it should be ok.

> Such a dictionary does not exist yet.

yes I know, thats a large gap for the use of OSM DB. I once started a project to collect this dictionary, but had to drop it because of time. At least there is this list thats also used by nominatim:

https://wiki.openstreetmap.org/wiki/Nominatim/Special_Phrases

**Comment by westnordost** [comment]
Regarding the ticket at hand: I will also add a quest "whats the name of this place", so that's covered.

**Comment by daniel-j-h** [comment]
Just stumbled upon the same behavior. In Berlin I can occasionally see Quests such as "What are the opening hours of null?" e.g. for this building http://www.openstreetmap.org/way/28251565

![sc](https://cloud.githubusercontent.com/assets/527241/24586472/1398921a-17a2-11e7-9c02-e03640428d22.png)

The fix in https://github.com/westnordost/StreetComplete/commit/ad5472e468197426e4ddb648981e85b67e85ab5c requires a `name` tag to be present. The question is if there are unnamed buildings for which it would still make sense to add opening hours. Would it make sense to not require a name tag but instead show "What are the opening hours of _this building_" for these cases?

**Comment by rugk** [comment]
When will this quest be included in the StreetComplete release? It's already in master, but [according to @DavidDean](https://wiki.openstreetmap.org/w/index.php?title=StreetComplete/Quests&diff=0&oldid=1513325), not currently active.
