### ISSUE TITLE
Remove empty and not needed packages section from the Github screen

### ISSUE THREAD

**Issue by matkoniecz** [westnordost/StreetComplete#2200]
https://github.com/westnordost/StreetComplete lists "Packages" section (on the right side, above "Contributors") that does not appear to be usable for SC.

I propose to remove it.

Can be done only by repo owner, not doable by editing git repository as it a proprietary Github config.

**Use case**
It is not needed and just takes space.

**Proposed Solution**

Edit repo page config to remove it (cog next to the description).

![Peek 2020-10-25 09-10](https://user-images.githubusercontent.com/899988/97102018-3a168700-16a2-11eb-8c18-7bd9a88922eb.gif)

**Comment by westnordost** [comment]
ok
