### ISSUE TITLE
House number quest asks for house number when an address is 1m away from the house

### ISSUE THREAD

**Issue by BjornRasmussen** [westnordost/StreetComplete#2201]
As seen here: 

![Screenshot_20201025-141142.png](https://user-images.githubusercontent.com/37753777/97115391-e4a39f80-16cc-11eb-8a18-b2939028ce57.png)

Adding the house number would create a duplicate address, which isn't great.  I'm not really sure of a good solution, but perhaps adding better checks for whether there's an address at the house before showing the quest could work.

I could, of course, just leave a note, but I'd prefer not to whenever possible.

I'm using v25.1

**Comment by westnordost** [comment]
Can you post the location where this occurs?

**Comment by BjornRasmussen** [comment]
https://www.openstreetmap.org/way/44321002

**Comment by westnordost** [comment]
The housenumber has been put not inside the building polygon. Move the housenumber as a node onto the outline of the building or inside the building to fix this data problem

![image](https://user-images.githubusercontent.com/4661658/97118069-551be200-1708-11eb-8aab-74e329ecaa65.png)

**Comment by matkoniecz** [comment]
> whether there's an address at the house 

Note that such check already exists. In this case address was not inside house area (=was incorrectly tagged)
