### ISSUE TITLE
Edit note

### ISSUE THREAD

**Issue by EchedeyLR** [westnordost/StreetComplete#2203]
**Use case**
I upload an incorrect report for some confusion and having to open OSM webpage or compatible app (external) to edit the report manually.

**Proposed Solution**
Be able to edit the reports already uploaded by the user in the own app.

**Comment by westnordost** [comment]
I figure you meant notes. It is not possible to edit notes or note comments. Also not on the OSM webpage.

**Comment by EchedeyLR** [comment]
In the OSM webpage I could edit by own "notes" if that or maybe add a reply to it. I remember because I did it recently. 

Anyways, let me check to ensure.

**Comment by EchedeyLR** [comment]
Okay, I added replies. I am sorry for the confusion.
