### ISSUE TITLE
Change "fee" by other word

### ISSUE THREAD

**Issue by EchedeyLR** [westnordost/StreetComplete#2204]
"fee" and "free" words can be confused easily due to similarities and some replacement could be needed.

**How to Reproduce**
The exact case was about parking fees. 

When the question is made some people misread the word "fee" with "free" making a fast read which finished like 25 bad notes today.

**Versions affected**
Since the quests about fees was implemented

**Comment by westnordost** [comment]
What word, for example?

Also, why do you not use the Spanish version?

**Comment by EchedeyLR** [comment]
Maybe could be change to "paid" or "under payment" or "you must pay in this parking" or "not free". The issue is not reported for me but for other person which uploaded a lot of erroneous things because of that.

**Comment by EchedeyLR** [comment]
I could upload a pull request for the strings in english.

**Comment by westnordost** [comment]
"not free" would have the same problem.

@peternewman What's your take on this as a native speaker? Current string is _"Does it cost a fee to park here?"_

**Comment by westnordost** [comment]
What would certainly also be possible is to change the answers from "Yes" and "no" to "**Fee**" and "**No Fee**"

**Comment by EchedeyLR** [comment]
If I can reply to this last message this could ensure the person to read perfectly the answers before choosing. This is speaking as a non-native english speaker and because of similar situations of spanish native speakers in our own lang.

**Comment by EchedeyLR** [comment]
What is about rephrasing the question in the form "Does this parking require a payment?". This could also avoid fast readers confusing the question and/or the reply.

**Comment by peternewman** [comment]
> @peternewman What's your take on this as a native speaker? Current string is _"Does it cost a fee to park here?"_

I was going to suggest _"Is there a charge to park here?"_

Or see:
https://www.lexico.com/synonym/fee

**Comment by peternewman** [comment]
> What would certainly also be possible is to change the answers from "Yes" and "no" to "**Fee**" and "**No Fee**"

Although then we've got to translate those strings and I wonder if some languages may struggle to fit their equivalent on the answer buttons?

**Comment by westnordost** [comment]
Ok, then let's just change it to "Is there a charge to park here?"

**Comment by EchedeyLR** [comment]
> I was going to suggest _"Is there a charge to park here?"_

I agree with it.

**Comment by EchedeyLR** [comment]
Should this be applied too to the toilets? I read a similar sentence while checking string files.

**Comment by peternewman** [comment]
I assume we're not worried about people getting confused about electric vehicle charging? Cost would avoid that, but I don't think it's quite as popular natively.

**Comment by smichel17** [comment]
> Is there a charge to park here?

I'd use the word "cost". If I were asking the question colloquially, I'd probably say, "Does it cost anything to park here?" or "Does parking here cost anything?"

**Comment by peternewman** [comment]
SGTM @smichel17 . Cost would have also been towards the top of my list. Personally I think your Does messages read better with cost than modifying the existing one.

**Comment by goldfndr** [comment]
I don't know if this would be too verbose, but "Is a payment required to park here?" would be my pick. "Pay" is a term that I strongly associate with parking (if required), the unattended spots where fees are collected tend to be labeled with "pay" or "payment".

**Comment by smichel17** [comment]
> What would certainly also be possible is to change the answers from "Yes" and "no" to "Fee" and "No Fee"

If you went this route, ideally these would be "Free" and "Paid". In which case I would phrase the question something like, "Does this parking require payment?" or "Is it free to park here?"

In this case the clarity of the question does not matter so much -- whether the user reads "free" or "fee", the answer is the same. So, I prefer this approach, if it is feasible.

**Comment by westnordost** [comment]
Could you guys make some suggestions for the wordings of other quest types that involve "fee" and/or yes/no answers that can be misinterpreted?
I could the change it all in one go

Am 26. Oktober 2020 15:23:54 MEZ schrieb smichel17 <notifications@github.com>:
>> What would certainly also be possible is to change the answers from
>"Yes" and "no" to "Fee" and "No Fee"
>
>If you went this route, ideally these would be "Free" and "Paid". In
>which case I would phrase the question something like, "Does this
>parking require payment?" or "Is it free to park here?"
>
>In this case the clarity of the question does not matter so much --
>whether the user reads "free" or "fee", the answer is the same. So, I
>prefer this approach, if it is feasible.
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/westnordost/StreetComplete/issues/2204#issuecomment-716580188

-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.

**Comment by rhhsm** [comment]
I'd suggest "Do you have to pay to park here?" (simple English, with users in mind who use the English version because SC is not yet available in their own language). Paid/free are the clearest answer options.

**Comment by westnordost** [comment]
Hmm too bad, almost everyone who took part in this discussion brought up an own suggestion, now I don't know what to choose.

**Comment by smichel17** [comment]
I second @rhhsm's latest suggestion, as good or better than mine.

**Comment by peternewman** [comment]
> I second @rhhsm's latest suggestion, as good or better than mine.

It seems fine to me too, perhaps slightly more informal than some of the earlier suggestions, but that doesn't particularly bother me.
