### ISSUE TITLE
Cannot fully disable 3D (so unable to precisely determine location of quests)

### ISSUE THREAD

**Issue by mnalis** [westnordost/StreetComplete#2206]
In recent months, StreetComplete added possibility of 3D (which does look nice). However, this 3D mode makes it hard/impossible to precisely determine location of quest the StreetComplete gives the user if the quest happens to be under a building (`tunnel=building_passage` and similar), as the quest location moves depending on the location of 3D view.

Before introduction of 3D mode, it worked just fine and was very precise in 2D.

Now the problem is that 3D mode does not seem like it can be **fully** disabled. When I press on compass icon, StreetComplete does change to almost-2D-mode, but tall buildings (like 10+ stories high) are still shown in 3D, and it is there where I have the most problems.

It would be great if 3D mode could be *completely* disabled, so users get precise 2D behaviour that we had before.
 

**How to Reproduce**
- In StreetComplete go to some location having high buildings. (for example, [here](https://osm.org/go/0IsmD~Wk6?node=496502834) - this [photo](https://hr.wikipedia.org/wiki/Datoteka:Zgrade_Papagajke,_Tre%C5%A1njevka.JPG))
- click compass icon to go to 3D mode
- click compass icon to go back to 2D mode (those two steps are just to be sure we are in 2D mode)
- find a quest that is under or near tall building and remember it's location
- scroll map to different sides, and see that quest location is shown at seemingly different locations, making it hard to know exactly where it was.
- attached pictures show three different positions shown for same "working hours" quest (pointed to by red arrow)

![Screenshot_20201019_005333_de westnordost streetcomplete](https://user-images.githubusercontent.com/156656/97249723-bde88480-1804-11eb-9d42-756121953f59.png)
![Screenshot_20201019_005355_de westnordost streetcomplete](https://user-images.githubusercontent.com/156656/97249727-bfb24800-1804-11eb-90bc-e2b9d398cfe6.png)
![Screenshot_20201019_005344_de westnordost streetcomplete](https://user-images.githubusercontent.com/156656/97249730-c04ade80-1804-11eb-9964-149822936075.png)

**Versions affected**
StreetComplete v24.1 from F-droid (some previous versions were also affected)  on Android 10 (EMUI 10.1.0)

**Comment by matkoniecz** [comment]
> attached pictures show three different positions shown for same "working hours" quest (pointed to by red arrow)

Is this displacement something that is problematic for any quest? For example in this case for all views it is "object is in the southern section of the building".

**Comment by mnalis** [comment]
Well, yes. In this quest for example, I didn't find the amenity... Same issue is with all other quests in such complex/high buildings.

There are several ways through the buildings, and at the different layers, and they have different entrance/exit points and usually do not interconnect (not all of them are even drawn in this building yet) . So, with such imprecise location I would basically have to roam many of the entrance/exit points and all ways they connect to eventually find the amenity in question (which in this case would easily be 1-2 extra kilometers walk just for that one building, as entrances are usually at opposite ends of the building complex)

Also, I sometimes find 3D view distracting in trying to orient myself (especially since StreetComplete does not leave the trail where I came from), so option to turn it off would be great in such cases.

**Comment by westnordost** [comment]
@mnalis , do you know that the level of the shop is shown just above the question? It should for example say:

> on level 2:
> What are the opening hours of this shop?

**Comment by HolgerJeromin** [comment]
especially needed for adding notes. We had this already: #1589

**Comment by mnalis** [comment]
@westnordost It would certainly help somewhat if `level` was mapped on all nodes/ways (by eliminating few possibilities that need search), but it would not really fix this problem, as there often are (in this example too) parallel ways that are at same level, but on opposing sides of the building, with different entry/exit points, and it is not possible to see from forced 3D view on which one the quest is, so one would still have to manually roam to determine mapped location of quest pin. 

Might it be possible if user could opt-out of 3D view somehow,  and get pure-2D view, as the one in #1589?  
(BTW @HolgerJeromin thanks for that, somehow I missed that issue even when I specifically searched for "3D" !)

Maybe by providing option in settings so user can choose that 2D mode is in use all the time (as it was in older SC versions)?
Or maybe by making clicking on compass icon activate *real 2D* (flattened building) mode, instead of pseudo-2D-but-still-actually-3D? Either would be fine by me

**Comment by westnordost** [comment]
Actually, the buildings have been 3D **all along**, so I am not sure why you think this is a new feature.

I am not convinced that this is a problem, even after you showed your screenshots. Your screenshots show a library in the south part of that building here https://www.openstreetmap.org/node/2050279332 . I don't think the library couldn't be found based on the information shown on the map, the building is only 20m wide anyway.

**Comment by westnordost** [comment]
Regarding opt-out: this would only make sense if it was up to the user preference. But if it was a general usability problem, then it should be tackled directly rather than supplying an option.

There has been the suggestion (and also implementation!) in the past to disable 3D when the note form is opened up. The problem with this was that with tangram-es, this change required a reload of the whole scene (including reloading all quests onto the map) which at least resulted in a visible jerk even on faster phones. Since in normal usage of the app, you enter and exit quest forms all the time, implementing something like this here would completely disrupt the user experience.

**Comment by smichel17** [comment]
> Actually, the buildings have been 3D **all along**, so I am not sure why you think this is a new feature.

I think it happened with the switch to JAWG maps.

Previously some areas of the world were using nextzen maps, which were very old and I suspect did not include the height of many buildings. Or maybe there was a change to how buildings with no height tag are rendered? Previously I think they rendered as flat, but now as single-story.

Whatever the case, I used to only notice the 3d when I panned over to look at Boston, but now I notice it near my home in western MA.

**Comment by mnalis** [comment]
As for SC always being 3D, I just didn't notice it had 3D until about a month or two ago (update which had new tiles provider as the old one was showing very old building positions), when it somehow activated. Maybe it was less visible on previous tiles, or I just was always near lower buildings so I just never noticed it is not in 2D. Sorry for the confusion!

As for the library, it *is* just on the corner, I had problem finding copyshop north of it (but by the time I submitted bug that task no longer showed in SC for some reason). So the problem was not W-E width, but N-S one (which, esp. in combination with tunnels not yet mapped, was worse).

I understand if underlying library difficulties prevent letting users choose 2D-only version of the app. It would be nice if it was an option, though, some users do prefer 2D (myself included). Maybe if the toolkit allows that in the future...

For anyone stumbling into this in the future, the workaround from #1589 to better locate things using 2D is to long press anywhere on the map, choose 'Create new note', and then browse around while 'Create new note' subwindow is still opened.

**Comment by mnalis** [comment]
Yay! As a side effect of adding `Addresses overlay` in [v48.0-alpha1](https://github.com/streetcomplete/StreetComplete/releases/tag/v48.0-alpha1) and newer, one can now finally actually **_fully disable 3D_** by enabling that `Addresses overlay`, e.g.:

 ![small_Screenshot_20221012_213319_de westnordost streetcomplete mn debug](https://user-images.githubusercontent.com/156656/195432554-2e685255-ce79-4cdc-9491-677123e734f6.jpg) ![small_Screenshot_20221012_213331_de westnordost streetcomplete mn debug](https://user-images.githubusercontent.com/156656/195432552-c17e9a12-e569-44b2-8103-ae8a57490eee.jpg)

https://github.com/streetcomplete/StreetComplete/blob/5c6c5cdbfea369f91180ed8abb16c51f486c085c/app/src/main/java/de/westnordost/streetcomplete/overlays/address/AddressOverlay.kt#L25-L29

**Comment by mnalis** [comment]
- ref: https://github.com/streetcomplete/StreetComplete/discussions/5235
