### ISSUE TITLE
after solving quest check whatever that changes makes new quests possible for a given element

### ISSUE THREAD

**Issue by matkoniecz** [westnordost/StreetComplete#221]
Note that many quests are unlocking additional ones for a given object.

In situation where doing one quests makes further one possible following situation is possible:

- imagine group of varied houses, sparsely scattered along a street
- each one is tagged as building=residential, without additional info
- mapper goes along street doing "add building:levels and roof:levels" quest
- later automatic download kicks in and as result "add roof type" quests are created (at least for ones with roof:levels>0)
- so mapper must go along the same street collecting information again

As new quests appear this may be more common - for example once planned "replace building=yes by more precise data" group of building=yes would be even more irritating: as first steep improve building values, and then go through everything twice like described above.

It would be preferable for StreetComplete to keep database of tags of all objects that spawned quests and on edit by user that changes tags update this local database - and check all quests whatever new tag combination makes given object eligible for new quests.

"Show all quests for element at once" #124 is very closely related.

**Comment by westnordost** [comment]
This is a reasonable request, so I won't close it. But I can tell you that I will not implement this anytime soon.

The implementation would need to go something like this:
- OsmElementQuestType interface needs a method appliesTo(Element)
- on solving a quest for an element e, iterate through the list of osm quest types and ask each quest type if it appliesTo(Element). If it does, create the quest, but only if it doesn't exist yet
- if any new quests were created, update map

**Comment by rugk** [comment]
Can't you just at least implement a workaround for the particular example described (building levels --> roof). This is the only quest, where I can imagine that the issue happens, anyway. And it is a very common quest type.
This implementation would be way easier than the "general implementation" you propose here, which could be implemented later anyway.

**Comment by matkoniecz** [comment]
> Can't you just at least implement a workaround for the particular example described

Workaround will be either not simpler than a proper solution or something that will be terrible for developing the program.

**Comment by westnordost** [comment]
Proper solution is implemented now.

**Comment by matkoniecz** [comment]
Thanks!
