### ISSUE TITLE
SC minimises when tapping a particular (corrupted) quest

### ISSUE THREAD

**Issue by rhhsm** [westnordost/StreetComplete#2211]
Today I went out mapping, as usual without having an Internet connection, found a street with a lighting and a max speed quest and a speed limit sign half way, and split it there without answering the lighting quest. Coming home and having wifi, new quests appeared for the 2 sections of road. I replied to the quests for one section and the lighting quest for the other while SC was also busy uploading my quest answers and downloading new quests. When I tried answering the remaining max speed quest and tapped the quest pin, the app minimises: it disappears from the screen, but still appears on the list of open apps (square button) and can be maximised again from there. Restarting the app or the phone doesn't help: tap that particular quest and SC disappears (also when it's no longer busy up-and downloading). Everything else works normal. Sometimes my phone reports that SC keeps crashing and if I want to report it. It happened once before, a few weeks ago, and it was also a quest for a section of path (or steps) that I'd split while being off line and tried to answer while I had a weak public wifi signal (app busy up- and downloading). That quest disappeared some time later, and when it reappeared, all was normal and I managed to answer it.

**How to Reproduce**
- split a way while being off line
- when on line again, try to answer the newly appearing quests for the split way while app is busy updating quests and replies.
(not sure whether the first time, I managed to answer part of the new split way quests before it happened)
(might be difficult to reproduce, as it happened only twice for me)

**Versions affected**
Today: SC v25.1, Android 10
Previous time: don't know, but surely earlier versions of SC and Android.
Phone LG Q60

**Comment by westnordost** [comment]
Okay, that "minimizing" is a probably an app crash. 

From where did you download the app? F-Droid or Google Play?

**Comment by rhhsm** [comment]
Google Play. What's F-Droid?

**Comment by matkoniecz** [comment]
F-Droid is an alternative to Google Play store, with only only free and open source apps (see https://en.wikipedia.org/wiki/F-Droid ). If you are unaware about it then you are almost certainly not using it.

**Comment by rhhsm** [comment]
The way is here https://www.openstreetmap.org/edit?way=864677630#map=18/42.67889/23.30729 . I see that this section doesn't have a lit tag, so I'm not sure any more if I answered this just before the crash occurred for the first time and it wasn't uploaded, or not. The other section that I split off using SC is northeast of it (lit with 30 kmh speed limit, as it should be).

**Comment by westnordost** [comment]
Okay, on Google Play I don't see any crash reports (from a LG Q60). So, right now, I don't have an idea. 
However, I reworked exactly that part of the app (updating elements from OSM API after upload, f.e. splitting a way), so it makes no point in tryint to reproduce it with the v25.1 code. Better reopen this bug if this keeps being reproducible on v26.0 (not released yet)

**Comment by westnordost** [comment]
(And I can not reproduce it with the new version like this:

1. Split a way, upload
2. Solve first part of the splitted way, upload
3. Solve second part of the splitted way, upload

)
