### ISSUE TITLE
Why are old Quests removed when searching for another place for Quests

### ISSUE THREAD

**Issue by NoNamePro0** [westnordost/StreetComplete#2212]
I wanna to have multiple quest-location downloaded. Currently (Version `24.1`) it seems that the older quests are removes or hidden.

Is that a bug. Or a feature, if yes why? Maybe a option in Settings.

**Comment by matkoniecz** [comment]
Yes, old quests are deliberately deleted. See https://github.com/westnordost/StreetComplete/blob/527f2f1c4e86e545343048ff99fe70ccf7e45809/app/src/main/java/de/westnordost/streetcomplete/data/osm/osmquest/OsmQuestController.kt#L207

Right now it is one month - see https://github.com/westnordost/StreetComplete/blob/ed6ab1426f5c26dc4779c2c84118483a4a84a6eb/app/src/main/java/de/westnordost/streetcomplete/ApplicationConstants.java#L29


There are multiple reasons how quests may disappear (added to https://wiki.openstreetmap.org/wiki/StreetComplete/FAQ#Why_quest_was_shown_and_disappeared.3F )

* you solved this quest
* StreetComplete refreshed quest data and discovered that someone else solved this quest 
  * or made other OpenStreetMap edit causing it to no longer apply
* Zooming out resulted in quest icon not being shown, as it was blocked by more important quest (you can change quest priorities in settings)
* Moving map caused more important quest to appear and block this one
* Changing quest priority in settings caused this quest to disappear
* Enabling showing of more notes resulted in more notes being shown and blocking this quest from display

**Comment by westnordost** [comment]
Quests are not removed when searching in another place for quest. Old quest are removed, after 1 month. (And soon, after 2 weeks)

**Comment by NoNamePro0** [comment]
Oh, okay. Maybe implement a selection into the settings, for change this inteval?
https://github.com/westnordost/StreetComplete/blob/ed6ab1426f5c26dc4779c2c84118483a4a84a6eb/app/src/main/java/de/westnordost/streetcomplete/ApplicationConstants.java#L29

**Comment by westnordost** [comment]
Why?

**Comment by NoNamePro0** [comment]
For people like me who don't want to synchronize all locations every 2 weeks/1 month. But it's also okay how it's done now.

**Comment by westnordost** [comment]
Well, download will be super-fast with the next version anyway
