### ISSUE TITLE
Achievement suggestion: Climate protector / Environmentalist

### ISSUE THREAD

**Issue by FloEdelmann** [westnordost/StreetComplete#2217]
I'd like to propose to add a new achievement called "Climate protector" or "Environmentalist":

It could include the following quests:

* Electric cars
	* AddChargingStationOperator
	* AddChargingStationCapacity *(not yet released)*
* Public transport
	* AddBusStopName
	* AddBusStopRef
	* AddBusStopShelter
	* AddBenchStatusOnBusStop
* Recycling
	* AddRecyclingType
	* AddRecyclingContainerMaterials
	* DetermineRecyclingGlass
* Cycling
	* AddCycleway
	* AddCyclewayPartSurface
	* AddBikeParkingCapacity
	* AddBikeParkingCover
	* AddBikeParkingType
	* AddCyclewaySegregation
	* AddPathSurface (?)
	* AddStepsRamp (?)
* Veggie
	* AddVegetarian
	* AddVegan
* Nature
	* AddForestLeafType

I know these are quite many, and maybe we can exclude all bike-related quests, since there is already the *bicyclist* achievement. Actually, all of these quests (apart from the last one, which could maybe also fit into the *outdoors* achievement?) are already part of another achievement. However, I think this new achievement would be a nice addition.

The achievement description could be something like this: "You solved %d quests that make OSM more useful in the fight against climate change!"

**Comment by westnordost** [comment]
Usually, achievements are connected with links that can be unlocked. Any ideas for that?

**Comment by FloEdelmann** [comment]
What about the Global Climate Protection Map (Klimaschutzkarte)?
https://klimaschutzkarte.de/index_En.html

**Comment by westnordost** [comment]
Thanks, both may be a fit. Though I find klimaschutzkarte.de relatively uninteresting

**Comment by codeinabox** [comment]
I just suggested a zero waste quest which would also fall under this achievement https://github.com/westnordost/StreetComplete/issues/2256

**Comment by FloEdelmann** [comment]
New link suggestions:

* https://pietervdvn.github.io/MapComplete/charging_stations.html
* http://buurtnatuur.be/ (Dutch only)

**Comment by IpswichMapper** [comment]
> Usually, achievements are connected with links that can be unlocked. Any ideas for that?

???

**Comment by westnordost** [comment]
@FloEdelmann : Both links are too technical, they are not made for the end user.

Anyway, right now there are not really any links to unlock or any quests specific to this achievement suggestion (that are not already part of another achievement). I'll close this because even if a graphic for this would be made, I'd probably not (yet) add it as an achievement because of this.

In general, I don't really want "achievement suggestions" to turn into a new category on this issue tracker. Be assured that I'll come up with new achievements myself when quests that fit to a new topic are added.

**Comment by westnordost** [comment]
If you think you found a nice link (for any topic), you can always send it to me via Email. (Chances are that I already know about it though.)

On the other hand, if it is something new and interesting, maybe you should send it to weeklyOSM (via [OSMBC](https://osmbc.openstreetmap.de/)). I read this regularly so anything that appears there is also on "my list".
