### ISSUE TITLE
amenity=recycling without recycling_type tag

### ISSUE THREAD

**Issue by HolgerJeromin** [westnordost/StreetComplete#222]
`amenity=recycling` can be a centre or only a container. Without it `recycling_type=*` the poi is rather useless.

- `recycling_type=centre`: a recycling centre.
- `recycling_type=container`: a recycling container.
- `recycling_type=container` and `location=underground` for an underfloor-container

**Comment by westnordost** [comment]
Good idea, also easy to implement. A textual selection could be even better here than the "usual" image selection because containers (and recycling containers) can look very different in different countries.
