### ISSUE TITLE
Add "publish changes" or hint how to do this on "My profile"

### ISSUE THREAD

**Issue by matkoniecz** [westnordost/StreetComplete#2225]
**Use case**
"My profile" may contain text such as "plus 2 not yet published changes" visible for example after user went through login available there. It would be nice to at least explain how to handle that.

**Proposed Solution**
Add "publish changes" or hint how to do this

**Comment by matkoniecz** [comment]
Maybe trigger change upload after logging in? Leaving this menu triggered upload.

**Comment by RubenKelevra** [comment]
I think as soon as a login is available all changes should be pushed and the text should be changed to 'publishing 2 changes...'

**Comment by matkoniecz** [comment]
> all changes should be pushed and the text should be changed to

Note that there is possibility of internet disappearing between logging in and pushing all changes.

**Comment by RubenKelevra** [comment]
Yeah sure... but the try to push alone should be enough to justify the text, shouldn't it? 🤔

Back on the main screen the changes get pushed, but the counter only 'bounces' but don't count up.

That said the changes are successfully uploaded. So it's just an issue with the counter value.
