### ISSUE TITLE
!leaf_type ignored in AddForestLeafType quest

### ISSUE THREAD

**Issue by matkoniecz** [westnordost/StreetComplete#2226]
https://www.openstreetmap.org/way/407469949 doe not qualify for AddForestLeafType quest due `ways, relations with landuse = forest or natural = wood and !leaf_type` but is listed for quest

**How to Reproduce**
Uninstall StreetComplete, install, scan in area of https://www.openstreetmap.org/way/407469949

I have not investigated it beyond confirming that it happens (I noticed it while testing #2183)

**Versions affected**
recent master - c3ccd7289

**Comment by matkoniecz** [comment]
Curiously, solving it with correct (current answer) does not result in edit or increase in star count (explained by `changes.add("leaf_type", answer)`?)

**Comment by matkoniecz** [comment]
Hmmm, there is already `require(!source.containsKey(key)) { "The key '$key' already exists in the map." }` in `add`

Is it supposed to emit something in logcat? Because nothing appears there.

**Comment by matkoniecz** [comment]
Wait, require should outright throw exception if test would fail, so apparently `add` is never reached. Not sure what is happening here, I will pause this interruption for now.

**Comment by westnordost** [comment]
Right, that's the problem:
```
ways, relations with landuse = forest or natural = wood and !leaf_type
```
... is the same as. ...
```
ways, relations with landuse = forest or (natural = wood and !leaf_type)
```

**Comment by matkoniecz** [comment]
Right, I completely missed it despite looking at it.

Any idea why `require(!source.containsKey(key)) { "The key '$key' already exists in the map." }` was not triggered and solving quest produced no logs whatsoever?

**Comment by westnordost** [comment]
I didn't look into that
