### ISSUE TITLE
Recycling materials quest : add "general waste"

### ISSUE THREAD

**Issue by letypequividelespoubelles** [westnordost/StreetComplete#2228]
**Use case**
While answering the Recycling materials quest, it's not possible to mix general waste with others. We should click on "other answer" then "general waste".
The problem is that, at least in countryside in France, recycling bins are usually recycling bins and general waste bins all together. So we can't answer this quest. 

**Proposed Solution**
Add general waste in the choice, with all other technical recycling stuff.

Thanks to the team (especially westnordost ) for all the work.

**Comment by matkoniecz** [comment]
> While answering the Recycling materials quest, it's not possible to mix general waste with others. 

What SC would be supposed to tag in case of such answer? AFAIK in such case two objects should be mapped, not one - so it would be impossible to answer by just changing tags (as "general mixed trash" is not something that is actually recycled so it is not supposed to be tagged on `amenity=recycling`)

> So we can't answer this quest.

It is still possible to use "other answers" -> "can't say"/

**Comment by letypequividelespoubelles** [comment]
> What SC would be supposed to tag in case of such answer? 

The same tag as when we click on "other answer" and then "general waste". Idk what tag it is.

>AFAIK in such case two objects should be mapped, not one - so it would be impossible to answer by just changing tags (as "general mixed trash" is not something that is actually recycled so it is not supposed to be tagged on amenity=recycling)

Imho, no, because in France (countryside) it's the same placewith for example 5 bins : one for glass, one for paper, one for metal, one for vegetable, and one for general trash. And if there are 2 different POI, with for exemple one without tag and the other one already with tag, so only one visible in SC, how the user can know which one to map ? For me, it needs the tags with all what we can put - general trash and other recyclable trash. 

>It is still possible to use "other answers" -> "can't say" and leave a note.

Yes agree, it's technicaly possible, but in fact we don't want that each recycling POI at least in coutryside of France has a note and no tag :)

**Comment by matkoniecz** [comment]
> The same tag as when we click on "other answer" and then "general waste". Idk what tag it is.

This tags it as `amenity=waste_disposal`. How place where you can both leave general waste (not for recycling) and leave some materials for recycling is supposed to be tagged? As far as I know, as two objects: `amenity=waste_disposal` (maybe `amenity=waste_basket`) and separate `amenity=recycling`

**Comment by westnordost** [comment]
Yes, the correct way to map this is with two nodes. And yes, I find this a little complicated, but this is how the tagging scheme is currently. Could have been avoided if `amenity=waste_disposal` and `amenity=recycling` weren't two tags but one.

**Comment by HolgerJeromin** [comment]
We also have `recycling:waste=yes/no`. I tagged many (customer only) ones in a Center Parcs: 
https://www.openstreetmap.org/node/8015989341
Documented and used 18000 times https://taginfo.openstreetmap.org/keys/recycling%3Awaste

**Comment by matkoniecz** [comment]
[Documented](https://wiki.openstreetmap.org/wiki/Key%3Arecycling%3Awaste) as 

> General waste container (black bags) (don't use this if the waste is not recycled, use a tag like amenity=waste_disposal or amenity=waste_basket instead) 

and in general such waste is not actually recycled. And even if user would be asked about that, SC would be unable to tag "it is not recycled" case

**Comment by letypequividelespoubelles** [comment]
>in general such waste is not actually recycled

Burn the waste do make energy can't be understood as "recycling" ? In fact, you recycle the energy of the chemical liaison of the waste to make electricity ... :)
