### ISSUE TITLE
add possibility to merge buildings for the "what kind of building is it"

### ISSUE THREAD

**Issue by letypequividelespoubelles** [westnordost/StreetComplete#2229]
**Use case**
Very often, on the "what type of building is it"quest, I.don't answer because it's just a few squared meters polygon.who is wrongly detached of the building. It's issue when imported in osm from external data.

**Proposed Solution**
Streetcomplete should add an option "type on the  building it should be merge to". It should accept only close building, and in the data, merge the two buildings.
I.don't see any other solution to solve the issue.

**Comment by matkoniecz** [comment]
> I.don't answer

It is still possible to use "other answers" -> "can't say" to leave a note, like for any other invalid data.

See also rejected "Exclude unreasonably small buildings from building quests" #1439

> My point of view is that as long as the answers StreetComplete users are giving won't make the data (more) wrong, StreetComplete does not have to be considerate of wrong or oddly mapped data.

> I find it problematic to go down the road of intentionally hiding from the user odd or wrong data (by some fuzzy indication, e.g. a X must be at least this big!). If something strikes the user as odd, he should leave a note!

**Comment by letypequividelespoubelles** [comment]
>It is still possible to use "other answers" -> "can't say" to leave a note, like for any other invalid data.

Yes I agree, but there will be two many notes ! In the city where I'm lockdowned, there are around a third of the building which have this problem

>I find it problematic to go down the road of intentionally hiding from the user odd or wrong data (by some fuzzy indication, e.g. a X must be at least this big!). If something strikes the user as odd, he should leave a note!

I totally agree with you ! In few cases, building are really small (car park, small garden building, mountain refuge, finish sauna, etc ...) That's why I think my proposition works : you don't hide anything, AND you give the possibility to merge a small piece of building, wrongly mapped, with the main building.

**Comment by matkoniecz** [comment]
> Yes I agree, but there will be two many notes ! In the city where I'm lockdowned, there are around a third of the building which have this problem

It is also possible to leave note and comment that problem is widespread (not sure about France but in Poland I am monitoring any newly created notes - see http://resultmaps.neis-one.org/osm-notes-country?c=Poland and sometimes fix some systematic issues or remotely fixable things).

No promises, not sure is it remotely fixable - but can you link area where this problem happens?

**Comment by letypequividelespoubelles** [comment]
>No promises, not sure is it remotely fixable - but can you link area where this problem happens?

You can see it randomly everywhere in France. So many buildings has little separated buildings part, and it's the same more or less everywhere. Give the possibility to merge those building would be amazing. 
For exemple : [here](https://www.openstreetmap.org/#map=18/46.10763/3.45263) there are 8 buildings with this problem, out a total of 24.

**Comment by westnordost** [comment]
I acknowledge that this can be a big problem in certain areas. However I have to say that this is unfortunately out of scope of this app. The app is not able to merge geometries and it would take too much effort to implement this.
