### ISSUE TITLE
Restore feedback on downloading where quests are downloaded

### ISSUE THREAD

**Issue by matkoniecz** [westnordost/StreetComplete#2235]
**Use case**
With overpass based download there was a feedback if someone tried downloading in area where everything is downloaded. Now, downloading in fetched area shows white circle without any message.

Note that user may not have any quests on screen if in this specific location no enabled quest is present.
**Proposed Solution**
Show toast that in that area everything is fetched?

**Comment by smichel17** [comment]
It already does this for me. "No further quests available"

**Comment by Atrate** [comment]
> It already does this for me. "No further quests available"
Yep, same here

**Comment by smichel17** [comment]
However, I do have a separate suggestion — maybe instead of just the question mark, the icon could show some indication of whether a small or area is being downloaded? (eg a small vs large circle)

**Comment by matkoniecz** [comment]
OK, I am closing this one as it may be again Xiaomi failing to display toast messages (I had this one before...).
