### ISSUE TITLE
I don't understand the quest "Which direction leads upwards for these steps?"

### ISSUE THREAD

**Issue by Vinnl** [westnordost/StreetComplete#2239]
**Use case**
I am walking along a footpath, and come across a set of four steps. StreetComplete asks me "which direction leads upwards" for those steps. However, you can walk both ways...

**Proposed Solution**
I don't know what I'm supposed to enter there, so some kind of guidance on what to do or an option describing why this quest doesn't apply in this case under "Other answers" would be helpful. (Are there ever non-escalator steps that lead in a particular direction, i.e. that you can't just walk both up and down?)

(Quest introduced in #1817.)

**Comment by matkoniecz** [comment]
> "which direction leads upwards" for those steps. However, you can walk both ways...

On steps one direction would lead downwards (going to lower level), one direction would upwards. If one segment has both directions then it may be needed to split the line.

Steps leading upwards from photographer position: https://commons.wikimedia.org/wiki/File:Harar,_Ethiopia_(10699971753).jpg

Steps leading downwards from photographer position: https://commons.wikimedia.org/wiki/File:From_the_(Botanic)_Gardens_(2515551200).jpg

**Comment by Vinnl** [comment]
Hmm, so those photos are about steps leading in a direction _from the photographer's position_. However, as far as I can see (but the steps are short - there's just about four of them) the quest is displayed in the middle of those steps. How do I know where "the photographer" is?

I'll see if I can take a picture later today, that might help.

**Comment by westnordost** [comment]
You just have to select which direction you'd have to go to reach the upper end of the steps. 

On 5 November 2020 11:39:05 CET, Vincent <notifications@github.com> wrote:
>Hmm, so those photos are about steps leading in a direction _from the
>photographer's position_. However, as far as I can see (but the steps
>are short - there's just about four of them) the quest is displayed in
>the middle of those steps. How do I know where "the photographer" is?
>
>I'll see if I can take a picture later today, that might help.
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/westnordost/StreetComplete/issues/2239#issuecomment-722293940

-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.

**Comment by matkoniecz** [comment]
The answers show direction of way and user is asked to select one where direction matches incline/height increase/upward direction of steps.

Older version had a bit more confusing version of shown answers - which version of SC you are using? Is it possible to update it? See https://github.com/westnordost/StreetComplete/issues/2140

**Comment by Vinnl** [comment]
Aaaahhh. Damn, now it's completely obvious, and re-reading the wording it does make sense now. I suppose I just was confused by the use of the word "leads", that the steps lead somewhere; maybe something like "which side is the upper end of these steps" would've prevented that. But I was probably just being dumb :) 

Going to complete some more quests now then. Thanks for the app!
