### ISSUE TITLE
weird picture in bike lane quest? 

### ISSUE THREAD

**Issue by grafst** [westnordost/StreetComplete#2240]
![Screenshot_20201105_143928](https://user-images.githubusercontent.com/8471055/98248061-bb103100-1f74-11eb-8c42-8fe97af9b179.jpg)
 
**How to Reproduce**
click on a bike lane quest marker

**Versions affected**
Android10 
v26.0-beta3

**Comment by westnordost** [comment]
Did you try tapping on it?

**Comment by rouelibre1** [comment]
Same here. Looks a bit odd but it works. Tapping on the grey zone with question marks leads to the choice of type of bike lane.

![Screenshot_20201109-163714_StreetComplete](https://user-images.githubusercontent.com/73238613/98613937-abd40f00-22f7-11eb-971c-88482bbd7c37.jpg)

Tapping on the white zone outside the grey area didn't work 

![Screenshot_20201109-163735_StreetComplete](https://user-images.githubusercontent.com/73238613/98613941-ad053c00-22f7-11eb-85fc-255c02a2252a.jpg)

Then this shows up

![Screenshot_20201109-163609_StreetComplete](https://user-images.githubusercontent.com/73238613/98614211-3a489080-22f8-11eb-822c-b638b5a5f668.jpg)

**Comment by HaasJona** [comment]
I guess the main problem with the original picture is that the text is cut off/unreadable, so you're not really sure what you're supposed to do if the first time you encounter the quest, the street is in vertical orientation.

**Comment by matkoniecz** [comment]
What about the text above diagram? Is it unclear in translation?

![screen04](https://user-images.githubusercontent.com/899988/98653952-f5474d00-233d-11eb-95c9-ca886bb81383.png)

**Comment by rouelibre1** [comment]
I agree, that part of the UI is confusing and doesn't bring a lot of added value.

**Comment by westnordost** [comment]
And what can be done? Should it be some kind of marquee?

**Comment by HaasJona** [comment]
> And what can be done? Should it be some kind of marquee?

That would be an option. Or make it more clear that the question mark area is tap-able by animating the background color of the tab-able area between blue and gray or something like that. Or add a 👆 icon near the area you're supposed to tap. As is, it looks relatively static and not very interactive.

**Comment by matkoniecz** [comment]
Add big "click on ?" hint message, possibly disabled if user solved multiple quests of that type?

Add text above tappable area?

Add text to side of tappable area?

Add tutorial modal window disabled if user solved any quests of that type?

**Comment by smichel17** [comment]
The simplest solution would be just changing the text hint for everyone. The current message in English is, "The road in the illustration is rotated the same as on the map at the location of the pin."

I think it would probably be enough to change to, "Tap on the road in the illustration. It is rotated the same as on the map ~~at the location of the pin~~." (Separately, I think the second part of the sentence is not needed. After all, the whole map is rotated in the same direction.)

**Comment by HolgerJeromin** [comment]
>  I think the second part of the sentence is not needed

It is needed for ways which are nearly circles.

**Comment by smichel17** [comment]
Ah, now that you mention it, I remember that conversation. It would be nice if we could show a curved road segment, but IIRC there was a good reason why that would be hard.

**Comment by smichel17** [comment]
Ah, now that you mention it, I remember that conversation. It would be nice if we could show a curved road segment, but IIRC there was a good reason why that would be hard.
