### ISSUE TITLE
House name issues after house number quest

### ISSUE THREAD

**Issue by Cj-Malone** [westnordost/StreetComplete#2241]
**How to Reproduce**
If I answer a house number quest, using the new quick +/- controls (#2131), and then the following house has a house name, StreetComplete doesn't display the "OK" button.

**Versions affected**
StreetComplete 25.1
Android 10

Thanks for all the work you put in :)

**Comment by Cj-Malone** [comment]
![Screenshot_20201105-135935_Street­Complete](https://user-images.githubusercontent.com/10121513/98251345-839f8580-1f70-11eb-9c80-88fa68df41ab.png)

**Comment by westnordost** [comment]
Oh!
