### ISSUE TITLE
Nearby sidewalk detector not always works

### ISSUE THREAD

**Issue by matkoniecz** [westnordost/StreetComplete#2248]
**How to Reproduce**
Scan for cycleway quest in area with plenty of separately mapped sidewalks

https://www.openstreetmap.org/way/830880868 https://www.openstreetmap.org/way/19801348 https://www.openstreetmap.org/way/26485827  https://www.openstreetmap.org/way/694435536 https://www.openstreetmap.org/way/793976396 https://www.openstreetmap.org/way/24164606

**Versions affected**
master version of SC - https://github.com/westnordost/StreetComplete/commit/2065b99f0da1fca5b9fa1419a391160e988d7428

**Comment by matkoniecz** [comment]
Sorry for not testing it earlier, I simply had no spare time for that :(

**Comment by westnordost** [comment]
I'll look into it

**Comment by cyclingcat** [comment]
After this afternoon's mapping session I fear the same is valid for cycleways as well and thought about opening a similar ticket soon, after some further investigation.

The cycling cat

**Comment by westnordost** [comment]
No it's fine, I will fix both at the same time.
