### ISSUE TITLE
screen at quest location with no quest displayed

### ISSUE THREAD

**Issue by matkoniecz** [westnordost/StreetComplete#225]
There are no nearby quests but marker hides as I zoom in.

Quest is a note (available as I enabled display of all notes):  http://www.openstreetmap.org/note/614316

It is reappearance of #50 that was mostly fixed in 0.8

I am using version 0.10 on Android 6.0.1 MMB29M, Redmi 4 device

**Comment by HolgerJeromin** [comment]
Same here on Fairphone 2 with Android 6 with housenumber quests.
For example [housenumber quest](https://www.openstreetmap.org/way/109843953) is shown on mid zoom, zoomin in [cycle parking quest](https://www.openstreetmap.org/node/4373104690) is appearing, but housenumber is not anymore.

**Comment by escoand** [comment]
Same on Moto G4 with Android 7.0

**Comment by westnordost** [comment]
The quests hide each other if they come too near, this is rather a feature than a bug that ensures that the map is not become too full. Unfortunately, there is no order yet which quests obscure which quests.

**Comment by matkoniecz** [comment]
It happens on zooming in, with no new quests appearing. One may also zoom in to quest location and see no quest at all on the screen.

**Comment by westnordost** [comment]
Well, then I need a video of this in action as I will have to open a new issue at tangram-es.

**Comment by matkoniecz** [comment]
I am using version 0.10 on Android 6.0.1 MMB29M, Redmi 4 device, StreetComplete 0.10.

![ezgif-2-81a139681b](https://cloud.githubusercontent.com/assets/899988/26034134/213d5eb4-38b8-11e7-81dd-27dd9fa619ff.gif)

**Comment by matkoniecz** [comment]
Exact sequence is less clear:

- note quest disappears, one opening hour quest disappears, new opening hours quest appears (expected)
- on further zooming in note quest never appears, up to screen at quest location with no quest displayed

**Comment by westnordost** [comment]
Nice, thanks.
