### ISSUE TITLE
Too many cycleway quests with the same answer!

### ISSUE THREAD

**Issue by cyclingcat** [westnordost/StreetComplete#2251]
Hi there,

this afternoon I cycled some kilometres into a village nearby through another village, both with at least 2000 inhabitants each. They are typical villages here: One main road (highway=primary/secondary) and a network of many living streets (highway=residential). While previous versions of SC showed very few street-related quests anymore, this changed with v26.0 dramatically: Tons of sidewalk and cycleway quests popping up, and while the answers to the former are quite varying, those to the latter are really monotonous: I solved about 100 cycleway quests but haven't met a single one with an answer other than "No cycleway on both sides"! This isn't really surprising as living streets of typical villages usually don't have cycling lanes/paths, because of the very little car traffic.

This smells spammy to me, at least in those regions. You can probably pick any German village, load the quests and find many, many cycleway quests of which >99% would have to be answered with "No cycleway on both sides". The few exceptions could be cycling lanes/paths along longer living streets having the character of main roads but still tagged as "residential".

I'm afraid that users get bored and soon disable this (otherwise very valuable) quest - doing always the same 5 taps is very tedious (and meets the definition of spam), but I have no idea how to mitigate this. Somehow distinguish between smaller and bigger places (= don't show the cycleway quest for residential streets in smaller villages, but what about huge residential areas of bigger towns then where the same problem would occur)?

So I opened this issue, hoping that someone reading this with a deeper insight into the structure of OSM will have a brilliant idea how to handle this.

The cycling cat

**Comment by westnordost** [comment]
With living streets, you don't mean `highway=residential`, not `highway=living_street`, right?

**Comment by matkoniecz** [comment]
> this changed with v26.0 dramatically: Tons of sidewalk and cycleway quests popping up

Not that at least partially this may be a bug - see #2248

**Comment by westnordost** [comment]
Well, I still changed it so that the cycleway quest is also shown for residential roads.

**Comment by westnordost** [comment]
But no method how to distinguish between big and small places or places with high traffic and low traffic comes to my mind.

**Comment by cyclingcat** [comment]
> With living streets, you don't mean highway=residential, not highway=living_street, right?

Yes, "highway=residential". (Sorry for the confusion, I wasn't aware that there is "highway=living_street" as well.)

> Note that at least partially this may be a bug - see #2248

But I don't mean cases where there are cycleways nearby! Here I'm considering pure residential areas with many streets, typically 50 m (often dead ends) to 500 m long, with none to little with through traffic, just cars of residents, visitors and the odd parcel delivery. Those ones very rarely have any kinds of cycleways...

The cycling cat

**Comment by westnordost** [comment]
Ok, I see no other possibility other than disabling the quest for residential roads again.

**Comment by RubenKelevra** [comment]
This might be just a German thing, I've seen quite a lot cycle ways in the Netherlands in cities along residential roads.

Maybe we can just tone it down for Germany at the moment, where this seems to be not the case in general? 

Another option would be to add a button to the sidewalk quest, and let the user choose between 'ok' and 'there's also a cycleway' for residential streets.

So in a rare case that there's a cycleway the user's can hit this button and the cycle quest pops up next?

This would reduce the spam character of this quest on residential streets in countries where there are very little cycle lanes/ways like Germany.

**Comment by FloEdelmann** [comment]
I also answered some of those new cycleway quests witb v26.0 in a small German town. While most answers were indeed "no cycleways", there were also a few streets where bikes are explicitly allowed on the sidewalk. Those would have been missed otherwise. So I wouldn't mind if residential streets were included.

**Comment by DerDings** [comment]
> 
> 
> Ok, I see no other possibility other than disabling the quest for residential roads again.

I see some criteria how to determine whether a residential road is likely to have cycleways or sidewalks enabled for bicycles:
- The necessity and thus the presence of cycleways depends (among other criteria) on motorcars' speed on that road.
Speaking for Germany, bicycle lanes are not even allowed in `DE:zone30` zones, so it is inevitable that the answer is "no cycle way" in a vast majority of those streets.
-> I think it is a good idea to at least ask the cycleway quest for residential roads with `maxspeed>30` (or similar tags like `maxspeed:type=DE:urban`), while ignoring all other roads. To avoid spam, roads without tagged maxspeeds should be excluded.

- Additionally, there are some one-way roads which have a bicycle lane for the opposite direction. 
-> So the cycleway quest may also be asked for residential roads with `oneway=yes + oneway:bicycle=no`, regardless wether there is any speed limit. (this is also possible in Germany as long as the maxspeed is not a zone)

**Comment by westnordost** [comment]
Ok, that thing with > 30kmh is a good idea

**Comment by FloEdelmann** [comment]
For reference, this was fixed in https://github.com/streetcomplete/StreetComplete/commit/6502a21bfa7104da37f2e1d0fa9511d056f5ef23 and improved in #2448
