### ISSUE TITLE
Hide AddTrafficSignalsVibration where it can't ever be yes

### ISSUE THREAD

**Issue by peternewman** [westnordost/StreetComplete#2252]
**Use case**
In the UK at least, AddTrafficSignalsVibration only makes sense if AddTrafficSignalsButton is true. Without a button (and hence the box it's mounted in), there's nowhere to put the vibration. I suspect it might be similar with AddTrafficSignalsSound but possibly it could just beep anyway; I don't know where the beeper is.

**Proposed Solution**
Potentially require button before checking for vibration to avoid spam, although this would mean button would have to be answered beforehand, which it's suggested isn't actually used anywhere (but is trivial to answer).

I guess even with the new download you'd have to upload and re-fetch to hide it.

I guess if it showed it for `!button or button != no` you'd get the best compromise?

**Comment by westnordost** [comment]
> I guess if it showed it for !button or button != no you'd get the best compromise?

No.  Whether there is a button you have to push to cross is completely independent of a vibrating button for the blind:
- traffic lights with buttons are put in places with very low or irregular pedestrian traffic (compared with car traffic), like a crossing far from any intersection, or on route to schools
- the decision where to put traffic signals for the blind (vibration, sound) are instead based on completely different deliberations 

My personal experience is that more often than not, vibrating buttons for the blind are built into crossing signals of busy intersections (for both pedestrians and cars), a place where it makes no sense at all to put "press to request..."-buttons.

This is not a button to request green light. It is a vibrating button for the blind 
<img src="https://1.bp.blogspot.com/-OGVps4egX7Y/XWbnvihb-EI/AAAAAAADb8U/LomltovRrfsE3fp2y8pdelgamY2Wr_uYgCLcBGAs/s1600/blinda.jpg">

This is a button to request green light. Sometimes they also have this vibration feature at the bottom.
<img src="https://1.bp.blogspot.com/-q3sk8S1LIZ0/XWc4wdejCWI/AAAAAAADb80/m0idjsdjR6M8QKTri3ZvLIBzFcYqRlGpQCLcBGAs/s1600/20190829_043005.jpg"/>

**Comment by peternewman** [comment]
> > I guess if it showed it for !button or button != no you'd get the best compromise?
> 
> No. Whether there is a button you have to push to cross is completely independent of a vibrating button for the blind:

Ah, I guess that's true of most of Western Europe then. In the UK if you haven't got the button, there's no place for the cone:
https://github.com/westnordost/StreetComplete/issues/2127#issuecomment-705521534

>     * traffic lights with buttons are put in places with very low or irregular pedestrian traffic (compared with car traffic), like a crossing far from any intersection, or on route to schools

I think we probably have more buttons too, although how much they actually achieve as opposed to just making you feel good is probably variable and probably varies by time of day in some places.

**Comment by HolgerJeromin** [comment]
Perhaps I should open a new issue but just had this problem:
I see the push button on all three signals of the crossing.
But I can not check if there is something vibrating for the blinds.
We have two very similar button things here. Some with and some without the vibration at the button.

So please give push button quest a higher prio the vibration button quest.

**Comment by westnordost** [comment]
>  But I can not check if there is something vibrating for the blinds.

Why can you not check it?

**Comment by HolgerJeromin** [comment]
> Why can you not check it?

Too lazy to visit all four corners of the crossing.

**Comment by matkoniecz** [comment]
> Too lazy to visit all four corners of the crossing.

It should be enough to check both sides of a crossing, not set of all four pedestrian crossings to solve the quest. And if someone does not want to deal with quest (like I with roof shape or backrests) it is possible to disable them in settings.

**Comment by HolgerJeromin** [comment]
I only speak about quest priority. 
Push button can be solved from about 15 meters. vibrating needs sometimes < 1 meter.

**Comment by westnordost** [comment]
Not really. Whether or not the button casing has actually a button you have to push to request green light is a detail you might not see from far. See my example pictures. The presence of such a button casing doesn't mean that there is such a button.

**Comment by peternewman** [comment]
> > > I guess if it showed it for !button or button != no you'd get the best compromise?
> > 
> > 
> > No. Whether there is a button you have to push to cross is completely independent of a vibrating button for the blind:
> 
> Ah, I guess that's true of most of Western Europe then. In the UK if you haven't got the button, there's no place for the cone:
> [#2127 (comment)](https://github.com/westnordost/StreetComplete/issues/2127#issuecomment-705521534)

You're not interested per-country tweaking of the filtering then, or is that more trouble that it's worth?
