### ISSUE TITLE
Same change in multiple changesets

### ISSUE THREAD

**Issue by dAnjou** [westnordost/StreetComplete#2253]
Hi,

this week another mapper made me aware that some of my changes appear in multiple changesets. For example [this one](https://www.openstreetmap.org/changeset/93550765) and [this one](https://www.openstreetmap.org/changeset/93550776). My changes get uploaded automatically no matter the network.

**How to Reproduce**

Don't know :(

**Versions affected**

StreetComplete 26.0-beta3

**Comment by kmpoppe** [comment]
I don't think this is a bug. You have answered 2 questions about the same node, yet the questions (and thus the changes) are different.

**Comment by westnordost** [comment]
This is a bug in osmcha. I commented in the changeset.
