### ISSUE TITLE
in offline mode, ask all tasks on a building

### ISSUE THREAD

**Issue by Strubbl** [westnordost/StreetComplete#2254]
**Use case**
I am using StreetComplete offline without any connectivity. When mapping the type of the building, StreetComplete does not ask for the roof shape of that building and not for the building levels.
After mapping i upload the results at home. Afterwards i see the next type of quest, either roof shape of building levels. This way i have to do a second or even third survey to complete all open tasks for one building.

**Proposed Solution**
Ask all question w.r.t. to the building: type, roof shape and building/roof levels.

**Comment by matkoniecz** [comment]
See discussion in #1550 and #1510

**Comment by Strubbl** [comment]
Thanks for the pointer. It's a pity there is no simple solution for this problem.
