### ISSUE TITLE
Does "Invalidate quest cache" really work reliably?

### ISSUE THREAD

**Issue by cyclingcat** [westnordost/StreetComplete#2255]
Hi there,

this issue is kind of a follow-up to issue #2134. Meanwhile the quest download procedure has changed fundamentally and I hoped that the problem described in the above mentioned issue would now be gone, but unfortunately it's still there. SC v26.1 has just been released and here we get a good example:

SC v26.1 removed cycleway quests for streets tagged with "highway=residential", fixing issue #2251. After the update I expected most of the cycleway quests to have vanished, at least after invalidating the quest cache and tapping the "Scan for quests here" button. And indeed, many cycleway quests in residential streets have gone, **but not all of them**. There are still some left. Why is this the case? And even more important: What can the user do to really "invalidate" (does this mean: "clear"?) the quest cache?

My expectation as a user would be that if "Invalidate quest cache" is hit, all quests will be deleted from the map and fetched anew. (Now that downloading quests is much faster than in pre-v26 versions it shouldn't be a real performance problem.)

The cycling cat

**Comment by matkoniecz** [comment]
Maybe "Clear and delete all downloaded quests" would be better? At least in many uses I want this behavior, so instead of suing "invalidate" I reinstall the app.
 
> does this mean: "clear"?

No, it marks quests as outdated (like edit conflict in a given area)

> not all of them. There are still some left

Probably one that are still present are outside this download area or actually eligible also under more restrictive rules. You can pan map to their location and scan for quests also there.

**Comment by westnordost** [comment]
Yes, the invalidate quest cache feature works reliably. @matkoniecz yes, now it could be an option to instead have a "delete all quests" feature. It would also be easy to implement - in case you would like to do it, go ahead!

@cyclingcat Please post the location of the streets where the cycleway quest (still) appears and I'll have a look at it

**Comment by cyclingcat** [comment]
> Maybe "Clear and delete all downloaded quests" feature would be better?

Indeed, this would be more transparent to the user. "Clear = begin from scratch". So "invalidate" does something different. But what exactly?

> At least in many uses I want this behavior, so instead of using "invalidate" I reinstall the app.

This shouldn't be a part of the usual process for a user, should it? 😉

> No, it marks quests as outdated (like edit conflict in a given area)

What is the consequence of this "marked as outdated"? What's the use case for using this function? 

> Probably one that are still present are outside this download area or actually eligible also under more restrictive rules. You can pan map to their location and scan for quests also there.

I have already done this. In fact that's what I did immediately after the update to v26.1: Panned/zoomed to a region nearby where many cycleway quests were left. Reactivated this quest (I deactivated it this morning in order to not get spammed with them during my session), saw that they were still there, invalidated the cache, scanned for quests, and afterwards some (but not all!) cycleway quests were gone. Those concerning a tertiary road was still there (good!), but also some of the ons concerning residential roads (bad!).

The cycling cat

**Comment by cyclingcat** [comment]
I just tried to reproduce it on my third device which I usually never use with SC. It's a Samsung tablet, with Android 8.1.

So I installed SC 26.0, panned to a village and scanned for quests. The result was as expected: Many cycleway quests for residential streets:

![v26 0](https://user-images.githubusercontent.com/32601012/98484433-abf8df80-220f-11eb-839d-12f05f869223.jpg)

(It's approximately this map section: http://m.osmtools.de/0Zovt2sxmTI)

Now I deactivated the cycleway quest and updated to SC v26.1. Reactivated the cycleway quest, invalidated the quest cache afterwards and finally scanned for new quests, the same steps I took on my phone some hours ago.

Contrary to my first experience, nothing seems to happen at all - no cycleway quests for residential streets seem to have vanished. After some more tries to scan for quests the message "No further quests available" appears, but the cycleway quests are still there, even the ones for dead ends. Invalidating the cache a second and third time doesn't change anything.

(The bigger "Hauptstraße" in the screenshot is a secondary road, so its cycleway quest (e.g. the one next to the bridge) should remain.)

The cycling cat

**Comment by smichel17** [comment]
+1 to "Clear all downloaded quests" or something similar. I have never been able to figure out what is the practical effect of "invalidate quest cache". I have, however, wanted to clear all quests, in (rare) occasions when I think some quests are outdated (eg, because I mapped the same area on a different device).

**Comment by cyclingcat** [comment]
@smichel17: Exactly your use case was the reason for me to open #2134 some weeks ago - I also use two devices alternating and was wondering why I had to solve the same quests like the day before (the counter didn't increase though!). So I tried to invalidate the quest cache, but the quests I have already solved on the other device were still visible.

The cycling cat
