### ISSUE TITLE
Zero waste quest

### ISSUE THREAD

**Issue by codeinabox** [westnordost/StreetComplete#2256]
### General
Affected tag(s) to be modified/added: [zero_waste](https://wiki.openstreetmap.org/wiki/Key:zero_waste)
Question asked: **Does this shop have zero waste products?**

### Checklist
Checklist for quest suggestions (see guidelines):
- [x] 🚧 To be added tag is established and has a useful purpose
- [x] 🤔 Any answer the user can give must have an equivalent tagging (Quest should not reappear to other users when solved by one)
- [x] 🐿️ Easily answerable by everyone from the outside but a survey is necessary 
- [x] 💤 Not an overwhelming percentage of elements have the same answer (No spam)
- [x] 🕓 Applies to a reasonable number of elements (Worth the effort)

**Comment by matkoniecz** [comment]
https://wiki.openstreetmap.org/wiki/Key:zero_waste

> zero_waste=* is a key for shops that largely do without packaging material.

but

> zero_waste=yes - when the shop sells goods without packing (not specifying).
> zero_waste=only - if the shop sells goods only without packing.

It is not working as expected due to issue pointed at https://wiki.openstreetmap.org/wiki/Talk:Key:zero_waste

> Most supermarkets sell vegetables in bulk where you put the vegs in a disposable plastic bag yourself. Though it's not encouraged, you are free to take your own bags from home. So they technically sell goods without packaging, but it would be ridiculous to tag them with zero_waste=yes. Shouldn't the intent of the shop be taken into account, or at least the majority of goods be unpackaged? Surely if customers aren't even encouraged not to use non-reused packaging, the shops shouldn't be marked as zero waste. 

In a typical supermarket you can buy vegetables in your own bag, but it seems not very useful to tag such shop as zero_waste=yes but at the same time such shop matches zero_waste=yes as defined on that page.

**Comment by westnordost** [comment]
This is not fit for StreetComplete:

> 🚧 Established tags only: No new or unestablished tags should be introduced through StreetComplete. Establishing tags must remain a community process and not be dictated by software implementation.

Not approved, just a few hundred usages.

>💤 No spam: It must be possible to determine whether the quest should reasonably be asked. A quest which is to be answered in 99% of the time with the same answer is not a good quest, don't bore the users. I.e. asking for any road if it is a one-way road, is silly, because the vast majority of all roads will not be one-ways.

The tag was created to correctly tag what we call in German "[Unverpacktladen](https://de.wikipedia.org/wiki/Unverpacktladen)" (unpackaged store). This is a very special kind of shop, usually a variety of an shop that sells only organic food. Thus, 99% of all supermarkets etc. will have `no`, depending on the chain it belongs to.

> 🕵️ Publicly accessible: The information the users are supposed to collect must be easily accessible from the outside, don't lead users into trouble. I.e. users will not be able to answer reliably if a building has a basement or not, if a restaurant has toilets or not etc. without entering it.

Unless it is a zero packaging store that advertises it, you need to check if there are any of those fill-your-own-container vending machines in the store.

**Comment by codeinabox** [comment]
Thank you for speedy feedback on this. Even through there is a growing community interest in shops offering refill services for items such as oats, pasta etc commonly packaged in plastic I appreciate your points about the `zero_waste` tag not being well defined and how it involves people entering shops to survey this.
