### ISSUE TITLE
Determine whether road-aligned paths are allowed to cycle on in both directions

### ISSUE THREAD

**Issue by DerDings** [westnordost/StreetComplete#2259]
### General
Affected tag(s) to be modified/added: [oneway](https://wiki.openstreetmap.org/wiki/Key:oneway)
Question asked: **Is it allowed to cycle here in both directons?**
Rationale: In some places a lot of sidewalks or street-aligned cycleways are mapped seperately (this is not the place to discuss whether this approach makes sense in general). In some countries it is implicit that they are oneway if not explicitly signed to be not, while in the OSM data model oneway paths need to be explicitly marked as such.
Aerial imagery mappers tend to not tag `oneway=*` if they don't know if a way can be used in both directions. This is processed the same as `oneway=no` by routing engines, leading to faulty routes in many cases.

### Checklist
Checklist for quest suggestions (see guidelines):
- [x] 🚧 To be added tag is established and has a useful purpose
- [x] 🤔 Any answer the user can give must have an equivalent tagging (Quest should not reappear to other users when solved by one): The bicycle related wiki pages encourage tagging `oneway=no` on separately mapped cycleways along streets if they are usable in both directions.
- [ ] 🐿️ Easily answerable by everyone from the outside but a survey is necessary: One may need to walk to the end of the road, but not as far as for the maxspeed quest (as there are no zones for that). However, the indicators for a way to be dual-way are not known by everyone and need to be explained.
- [x] 💤 Not an overwhelming percentage of elements have the same answer (No spam)
- [x] 🕓 Applies to a reasonable number of elements (Worth the effort): I have come across a lot of ways along streets without a oneway tag which in reality are only allowed to use in one direction for bicyclists. See Dortmund, Germany for example.

### Ideas for implementation

**Element selection:** 
highway=footway/path + bicycle=yes/designated/official
AND
the way is parallel to a road. (Maybe the existing nearby sidewalk detection feature can be used?)
AND NOT
oneway=* or oneway:bicycle=*

**Metadata needed:** 
As default rules may vary by country, there may be a need to show a specific hint text for each country. Maybe first start enabling this quest in those countries where it is easiest to solve.

**Proposed GUI:**

Markers are shown at the end of the way.

Anwers:

_Two ideas:_
- similar to the oneway quest. The user determines the direction. 
The answers are **yes** / **no, only this direction** / **no, only that direction**
- ~similar to the oneway_suspects quest. The direction is deduced by the side where the near road is found and metadata whether the country has left or right hand driving. The direction is displayed to the user for verification.
The answers are **yes** / **no**~ not possible if cycleway is [in the middle of the road](https://de.wikipedia.org/wiki/Datei:Ciclovia_central_(S%C3%A3o_Caetano_do_Sul,_BR).jpg).

More answers:
**differs along the way** (-> split up)
**Can't say** (ask: leave a note instead? -> No, just hide / ok)

**Comment by matkoniecz** [comment]
> The bicycle related wiki pages encourage tagging oneway=no on separately mapped cycleways along streets if they are usable in both directions.

Which one? Like usual `oneway=no` tagging this is useful only in areas where many of such `highway=cycleway` are oneway.

>  zzz Not an overwhelming percentage of elements have the same answer (No spam)

In which countries this is true?

**Comment by DerDings** [comment]
> 
> 
> > The bicycle related wiki pages encourage tagging oneway=no on separately mapped cycleways along streets if they are usable in both directions.
> 
> Which one? Like usual `oneway=no` tagging this is useful only in areas where many of such `highway=cycleway` are oneway.

https://wiki.openstreetmap.org/wiki/Bicycle and it's localized counterparts (the localizations are sometimes divided in some [subpages](https://wiki.openstreetmap.org/wiki/DE:Bicycle/Radverkehrsanlagen_kartieren))

> > zzz Not an overwhelming percentage of elements have the same answer (No spam)
> 
> In which countries this is true?

In my own experience, Germany and the Netherlands. According to https://wiki.openstreetmap.org/wiki/Bicycle#Cycle_tracks also at least in the UK, USA and Canada both kinds of cycleways are possible. I couldn't find information about any country where this is not true.
However, in NL the difference between one-way and two-way cycleways is often visible on aerial imagery (because two-way cycleways often have lane markings and one-way cycleways are narrower), so the quest probably won't be shown there many times at all.



> Two ideas:
> - similar to the oneway quest. The user determines the direction.
> The answers are yes / no, only this direction / no, only that direction
> - similar to the oneway_suspects quest. The direction is deduced by the side where the near road is found and metadata whether the country has left or right hand driving. The direction is displayed to the user for verification.
> The answers are yes / no

Thinking of possible [cycleways in the middle of a road](https://de.wikipedia.org/wiki/Datei:Ciclovia_central_(S%C3%A3o_Caetano_do_Sul,_BR).jpg), we cannot derive the direction reliably. So the user will need to select the direction.

**Comment by matkoniecz** [comment]
> https://wiki.openstreetmap.org/wiki/Bicycle

I started https://wiki.openstreetmap.org/wiki/Talk:Bicycle#Is_explicit_oneway.3Dno_something_that_should_be_recommended.3F

> both kinds of cycleways are possible

Both are possible in Poland but asking would be waste of time and add unneded tags, as such oneway cycleways are both rare and tagged already.

**Comment by DerDings** [comment]
> Both are possible in Poland but asking would be waste of time and add unneded tags, as such oneway cycleways are both rare and tagged already.

So maybe Poland is a candidate to deactivate this quest. 
In Germany both kinds of ways are common (mostly they are combined foot and cycleways). There are more more dualway usable ways outside of cities and less inside, but there are also quite enough exceptions to legitimate a dedicated quest.

Note that this quest shouldn't only ask for cycleways, but also for footways with bicycles enabled. A lot of sidewalks are mapped separately as `highways=footway`. In my experience, a lot of people (probably pedestrians) simply add the `bicycle=yes` tag on those ways without thinking of the fact that (in Germany) all vehicles are required to drive on the right side of the street, thus all those ways are oneways unless otherwise stated.
As every country I know has a rule that requires vehicles to always drive on one specific side of the street, it is very likely this problem also affects a lot of other countries.

**Comment by westnordost** [comment]
That it is allowed is rare enough that adding `oneway=yes` may be considered spam.

However, what would be possible is to ask if a cycleway is a oneway or not after the width of the cycleway has been recorded.

Though since currently almost no cycleway at all has the width tagged, this could maybe be revisited in a few years or so. Not sure if I should close it then or leave it open as (much) later.

**Comment by DerDings** [comment]
When it comes to so much detail I can now speak for Germany only:

When local authorities consider whether to allow bidirectional cycling on a sidewalk (or street aligned combined foot/cycleways), the main things to consider are
1. prevention of accidents: drivers crossing the way on a driveway or crossing road are used to look for vehicles coming from both sides.
This is a criterion for leaving a way _one way_. 
2.  prevention of detours: when cyclists cannot cross the road everywhere, they may have to drive in the wrong direction for a while until they reach the nearest possibility to cross the road.
This is a criterion of making a way _dual way_.
3. the number of POI on both sides of the way: If there are very few or no things to reach along the road, there may be no need to have a foot/cycleway on both sides.
Thus, only on one side there is a foot/cycleway, which then needs to be _dual way_. 


> That it is allowed is rare enough that adding `oneway=yes` may be considered spam.
> 

It's true that it is rare in urban context. 
On most streets there are a lot of crossings and driveways, strengthening points 1. At the same time, there are a possibilities to cross the road everywhere, weakening point 2. But for the same reason, those streets are often mapped using `sidewalk=`, `cycleway:both=`, `sidewalk:right:bicycle=yes` and similar schemes. 
So most of them are not covered by this question. 

Mapping of separate ways is more common with larger roads where there is some grass or a barrier between carriageway and foot/cycleways. There are fewer crossings and also less possibilities to cross, which also makes _dual way_ more likely.


Thus, I don't think the answer `oneway=yes` will be too spammy. However, for this quest not only the amount of how often it is shown depends on a region's mapping style, also the variety of the answers depends. 

> However, what would be possible is to ask if a cycleway is a oneway or not after the width of the cycleway has been recorded.
> 

I don't think this is a good idea. In more rural areas there are a lot of _dual way_ enabled ways because of point 3. At the same time, those ways are often narrower than their urban counterparts. So the width is not a good indicator to determine whether those ways are _one way_.

**Comment by westnordost** [comment]
Okay, two things to do before this can be implemented then:
1. Have an answer for this question: To satisfy the quest guidelines, it would need to be easy for the user on-site to determine whether a cycleway is two-way or not. By which criteria should he decide that? Think of for example the standard cycle track that goes alongside a road in a town, will there be even any sign to denote that it is a oneway or is this supposed to be implicit because it goes alongside a road? In the absence of a sign, should yes or no be tagged? Or does it depend? On what does it depend?
2. Ask around in the community (forum, wiki, mailing list) whether it'd be ok to add `oneway=*` to every segregated cycleway.

**Comment by DerDings** [comment]
> 
> 
> Okay, two things to do before this can be implemented then:
> 
> 1. Have an answer for this question: To satisfy the quest guidelines, it would need to be easy for the user on-site to determine whether a cycleway is two-way or not. By which criteria should he decide that? Think of for example the standard cycle track that goes alongside a road in a town, will there be even any sign to denote that it is a oneway or is this supposed to be implicit because it goes alongside a road? In the absence of a sign, should yes or no be tagged? Or does it depend? On what does it depend?
> 

Again Germany-only. Feedback regarding the situation in other countries is needed:

A way that is usable in both directions may be indicated by one or more of those signs:
1. the Traffic sign [allowing](https://commons.wikimedia.org/wiki/File:Zusatzzeichen_1022-10_-_Radfahrer_frei,_StVO_1992.svg) or prescribing ([bikeway](https://commons.wikimedia.org/wiki/File:Zeichen_237_-_Sonderweg_Radfahrer,_StVO_1992.svg) / [segregated](https://commons.wikimedia.org/wiki/File:Zeichen_241-30_-_getrennter_Rad-_und_Fu%C3%9Fweg,_StVO_1992.svg) / [shared](https://commons.wikimedia.org/wiki/File:Zeichen_240_-_Gemeinsamer_Fu%C3%9F-_und_Radweg,_StVO_1992.svg)) bicycles is placed at **both ends** of the way
2. on one end of the way, the traffic sign allowing/prescribing bicycles is supplemented by two [arrows](https://commons.wikimedia.org/wiki/File:Zusatzzeichen_1000-31_-_beide_Richtungen,_zwei_gegengerichtete_senkrechte_Pfeile,_StVO_1992.svg)
3. somewhere in the middle of the way a sign allowing/prescribing bicycles is supplemented by [horizontal arrows](https://commons.wikimedia.org/wiki/File:Zusatzzeichen_1000-30_-_beide_Richtungen,_zwei_gegengerichtete_waagerechte_Pfeile,_StVO_1992.svg)
4. any other traffic sign along the way is supplemented by a [bike and two arrows](https://commons.wikimedia.org/wiki/File:Zusatzzeichen_1000-32_-_Radfahrer_kreuzen_von_rechts_und_links,_StVO_1997.svg)


I see this is getting more complicated than I thought at the beginning. To make it possible, this will maybe require an complex interface similar to the maxweight quest:
A screen asking if any sign from point 2 - 4 is shown with _yes_ and _no_ buttons (or all the signs are buttons and there is a _none of them_ button).
Tapping _no_ (or _none of them_) will then ask you if the signs from point 1 are placed at both ends of the way.

I still think this quest is valuable since the information asked for lacks in a lot of places, breaks routing when missing, and can only be added by survey.
However, I understand that this quest may be too complex to be enabled by default, while the effort needed for research and programming may be too much for a quest a lot of users don't even enable. 


> 2. Ask around in the community (forum, wiki, mailing list) whether it'd be ok to add `oneway=*` to every segregated cycleway.
> 
@matkoniecz already did in the wiki:

> I started https://wiki.openstreetmap.org/wiki/Talk:Bicycle#Is_explicit_oneway.3Dno_something_that_should_be_recommended.3F

**Comment by mnalis** [comment]
> Both are possible in Poland but asking would be waste of time and add unneeded tags, as such oneway cycleways are both rare and tagged already.

Lucky Poland! In Croatia, majority of cycleways are oneway (and narrow and shared with pedestrians). Which wouldn't be a problem _if they added another cycleway for going back_, but that unfortunately happens much more rarely. So in many cases, one can cycle to his destination using cycleway, but there is no legal way for cyclist to get back safely. 

Although, they are in majority of cases marked clearly (either a pictogram with arrow indicating direction drawn on the cycleway, or a sign indicating segregated/combined footway facing the direction cyclist is coming from, or usually both). 
![117949752_3316957475014489_5112549685423209121_n](https://user-images.githubusercontent.com/156656/99461233-b7e05200-2931-11eb-9654-26f0d62a1be1.jpg)

**Comment by westnordost** [comment]
@mnalis Which I guess results in that that cycleway is de-facto used a two-way cycleway and/or on the way back, cyclists use the footway? I know I would.

Based on the answer at https://github.com/westnordost/StreetComplete/issues/2259#issuecomment-728874798 I will close this as will not fix: As @DerDings mentioned himself, it's not simple and easy to explain to the user for what signs or markings he or she should look. And additionally, point 2 of https://github.com/westnordost/StreetComplete/issues/2259#issuecomment-727204023 hasn't been done.

What's more useful that oneway is I think the width. If it is broad enough, it will and can be used two-way anyway, regardless of what the signs say.

**Comment by mnalis** [comment]
@westnordost that is correct, many cyclist ignore the markings or use the footway. Unfortunately quite common here, as there is severe lack of any planing in cycling infrastructure here, and nobody implementing it really cares, so you cycleways going over high kerb (even when there is lowered kerb half a meter to the side!) or having a cycleway going straight through the bus stop shelter, or street lamp im the middle of the cycleway etc.

Still, it is required by law, and cyclists have occasionally been ticketed for this :(

Width would be most useful, though, once it gets picked up by OsmAnd or other mobile apps.
