### ISSUE TITLE
Bus stop name (shelter quest)

### ISSUE THREAD

**Issue by steelman** [westnordost/StreetComplete#226]
Display the name of a bus stop when asking for its shelter. It happens,.sometimes, that there are several stops (posts with the sign and timetables) along a street and only one shelter. The map displayed is not detailed enough to judge which stop is the nearest to the shelter.

**Comment by grrgui** [comment]
I agree, there is a lot of improvement to perform in bus transport mapping, at least in France.

**Comment by westnordost** [comment]
A quest like "what is the name of this bus stop" would also make sense though (is that what grrgui meant?)

**Comment by grrgui** [comment]
Yes, what is this bus stop name ?
Is there a shelter ? a bench ?

**Comment by westnordost** [comment]
-> make a new issue
