### ISSUE TITLE
lit on sidewalk

### ISSUE THREAD

**Issue by andrewharvey** [westnordost/StreetComplete#2261]
The current lit quest for sidewalks is unclear, ideally the instructions should say if the footpath needs it's own dedicating lights or if the parallel street lights which light up the road should be an indicator.

This might need more discussion on the OSM side but generally I've been mapping these as no where the sidewalk doesn't have it's own lighting separate from the road.

Same applies to crossings, but generally I've been mapping them as yes where it's inherited from the road lighting.

**Comment by matkoniecz** [comment]
> This might need more discussion on the OSM side but generally I've been mapping these as no where the sidewalk doesn't have it's own lighting separate from the road.

It is not asking whatever it has its own separate lights, it asks whatever it is lit.

In many cases footway is well lit by street lamps covering also roads.

Yes, in some cases it is tricky to decide if one is mapping during day.

**Comment by andrewharvey** [comment]
Okay this wasn't clear to me. Perhaps the quest needs a (?) button which expands to say this.

But still don't think it's a completely agreed convention on the OSM side, https://wiki.openstreetmap.org/wiki/Talk:Key:lit#Near_ambient_lighting discusses this exact topic.

Mapping the footway as lit due to spilled light from the road makes it impossible to identify footways which have their own dedicated lighting.

**Comment by westnordost** [comment]
Well, this is a bit of a definition problem of OSM, not really of Streetcomplete. The app asks simply if it is lit, IIRC. The `lit` key does not carry any more information.
