### ISSUE TITLE
Advanced option: Single Changeset upload & changeset comment

### ISSUE THREAD

**Issue by IpswichMapper** [westnordost/StreetComplete#2264]
Maybe have an advanced option, that when turned on, allows you to upload all your quests in one changest and add a changeset comment describing what you did. 

Two reasons:

1. I avoid tasks like road surface because it adds a new changeset which unnecessarily inflates my changeset count. I tell myself I can do this later in JOSM (you can see surfaces from aerial imagery).
2. Streetcomplete changeset comments such as "Add housenumbers are vague". Instead, I could make one changeset comment such as "Surveyind road surfaces and housenumbers in X neighbourhood"

The problem is a single changeset could make achievement recording difficult

**Comment by westnordost** [comment]
> The problem is a single changeset could make achievement recording difficult

And statistics in general, yes. Not difficult but impossible.

So (unfortunately) this can't be done.

There are good reasons why splitting up the changes into changesets that each describe a certain aspect / data point, but these don't matter anyway that much because it can't be done anyway.
