### ISSUE TITLE
Quest clarification: Road surface

### ISSUE THREAD

**Issue by Groctel** [westnordost/StreetComplete#2268]
Right now there are (as far as I know) two surface quests:

- Blue path surface quests ask for the surface of a clear and short path or fraction of a road.
- Yellow road surface quests ask for the surface of a whole road.

While the former are very short and clear, like road crossings, the latter take a whole street and it's not conveyed if the selected surface should be that of the road or the sidewalk. The word *road* is in the quest's title, but it sounds like a hyperonym for the street name string. 

If the actual road's surface is what's registered by the quest, I believe something like *what surface does the road of $street have here* would be a better way to ask the question.

What's the purpose of thhe yellow surface quests?

**Comment by westnordost** [comment]
The yellow one is for the street (i.e. where the cars go). The blue ones are for footways, sidewalks, paths, cycleways etc.

**Comment by Groctel** [comment]
I'm going to amend some of my edits then. Maybe consider changing the wording there? Roads are clearly roads where cars drive, but when using a mapping application it's not unreasonable to think about the word in a more "computery" way like `road <- street`. Also, blue and yellow quests vectors are both on the center of the road, so unless there's a clear distinction they look the same.

A help button / popup for that case could also be useful. Or maybe I'm making a mountain out of a molehill. I just didn't think the distinction was clear enough when I used it.

**Comment by westnordost** [comment]
I looked at the current wordings and they seem clear to me, so I see no need to act there.

Maybe there is a problem with the Spanish wording? You can contribute to the translation of this project, see the readme.

> Also, blue and yellow quests vectors are both on the center of the road, so unless there's a clear distinction they look the same.

Depends on the quest type. Blue surface quest pins are certainly not on the center of the road, because they specifically ask for the surface of a separately mapped sidewalk/footway, so they are asked for different highlighted paths.

**Comment by matkoniecz** [comment]
> Blue surface quest pins are certainly not on the center of the road,

They may be for crossings or if someone mapped both sides and crossing with one line.

**Comment by matkoniecz** [comment]
Btw, translation info is at https://github.com/westnordost/StreetComplete/blob/master/CONTRIBUTING.md#translating-the-app


In English question is "What surface does the road ROADNAME have here?"
