### ISSUE TITLE
Corona opening times

### ISSUE THREAD

**Issue by Sogolumbo** [westnordost/StreetComplete#2270]
The app asks wether the opening times are right. Some shops have altered opening times specifically due to Covid. There's a special tag for Covid opening times. The app should allow the user to leave the default opening times and instead set the Covid opening time.

**Comment by matkoniecz** [comment]
Very similar to #1774

Personally, as Covid seems long term and not a temporary interruption and simply return to exactly old opening hours is unlikely - I simply modify `opening_hours`, also in manual mapping without SC.

**Comment by Sogolumbo** [comment]
Oh, sorry, I forgot to check the closed issues.
