### ISSUE TITLE
Adding A/B Street to showcase?

### ISSUE THREAD

**Issue by matkoniecz** [westnordost/StreetComplete#2271]
I think that https://github.com/dabreegster/abstreet is good enough to list it in "Showcase" section of links (especially with upcoming `lanes` quest, though name, cycleway, maxspeed, road contruction and sidewalk data was already getting used)

**Comment by westnordost** [comment]
I thought about it, it is certainly pretty cool, but it is a desktop app. It should in general be possible to look at it on the phone. No idea if the author of the app considers creating a port for mobile devices, probably not. 

For now, I'd say "no, maybe later". Maybe in the future, there will be some kiind of nice demo page that you could at least look at from the (mobile) web.

**Comment by matkoniecz** [comment]
Good news, web version recently become available.

Not sure is it usable at all on mobile (performance, controls are both tricky at best), I will test it.

**Comment by westnordost** [comment]
ping

**Comment by dabreegster** [comment]
I tried opening A/B Street on my Android and it didn't work. Even if it does, I don't really have any intention of supporting it there. The UI really requires a mouse and keyboard, and it'd be quite a substantial change to be mobile-friendly. So if the showcase is meant for mobile apps, I think we can close this issue.

**Comment by westnordost** [comment]
Okay, thank you! Yeah, it should at least be possible to try it out on the phone. That's why I said that some demo/showcase would be enough to link it, so people get interested (enough that they remember trying it out when they are back at the PC).
