### ISSUE TITLE
Changeset messages don't reflect its content and quests

### ISSUE THREAD

**Issue by gileri** [westnordost/StreetComplete#2272]
Changesets are pushed with multiple quests data, while the changeset message and `StreetComplete:quest_type` don't match its contents as they only describe one quest.
Here is an [example](https://osmcha.org/changesets/94100583). 

EDIT : Before closing the changeset the data unrelated to the quest is removed. Shouldn't this cleanup be done locally before any upload ?

**Versions affected**
At least 26.1

**Comment by westnordost** [comment]
What exactly is wrong with that changeset?

**Comment by gileri** [comment]
I edited the OP, I just saw that it is only non-closed changeset that has this problem. This becomes visible when comparing between [OSMCha](https://osmcha.org/changesets/94100583/) (which stores open changeset data), and [OSM.org](https://www.openstreetmap.org/changeset/94100583) (which displays closed changeset data).

**Comment by westnordost** [comment]
No, that's a bug of osmcha.

**Comment by westnordost** [comment]
related: #2253

**Comment by gileri** [comment]
Sorry, didn't look hard enough for similar issues. Thank you for the triage @westnordost !
