### ISSUE TITLE
ford=stepping_stones is not considered

### ISSUE THREAD

**Issue by eikel** [westnordost/StreetComplete#2277]
**How to Reproduce**

* Navigate to a path that is labeled with `ford=stepping_stones` ([example](https://www.openstreetmap.org/way/578010090)).
* See that it is rendered like a normal way (e.g., no special marking like on osm.org).
* The “road surface” quest is shown, but according to the [OSM wiki](https://wiki.openstreetmap.org/wiki/Tag:ford%3Dstepping_stones), `ford=stepping_stones` implies `surface=stone`.

**Versions affected**

26.1

**Comment by westnordost** [comment]
> The “road surface” quest is shown, but according to the OSM wiki, ford=stepping_stones implies surface=stone.

Yeah, this is a pretty bad idea. If at all, it is not implies but can reasonably be assumed if the surface tag is missing. I know stepping stones made of concrete for example.

**Comment by joshinils** [comment]
The wiki for [`ford=stepping_stones`](https://wiki.openstreetmap.org/w/index.php?title=Tag:ford%3Dstepping_stones&oldid=2710151) now lists [`surface=stepping_stones`](https://wiki.openstreetmap.org/w/index.php?title=Tag:surface%3Dstepping_stones&oldid=2785211) as implied tag.
It's wiki page does not however say if it's too general of a tag, or such – one could argue that the surface of the stones themselves could/shouldbe tagged instead.

I don't know whether adding it as a value to the list of selectable surfaces to answer with or hiding the quest if it is tagged with `ford=stepping_stones`+`highway=footway` is a worthwhile idea.

But if you come across it, you may not know what to do, and create a [note](https://www.openstreetmap.org/note/3351353) instead.
