### ISSUE TITLE
Hide road questions if section is very short

### ISSUE THREAD

**Issue by W-T-Developer** [westnordost/StreetComplete#2278]
Road relation questions like light, footpaths, cycle lanes and maybe also surfaces should not be asked if the section is only a few meters long or crosses another road.

 ![Screenshot_crossing](https://user-images.githubusercontent.com/74488957/99181435-dcb8a780-272e-11eb-9982-4b45fdd3f9ba.jpg)
![Screenshot_shortRoad](https://user-images.githubusercontent.com/74488957/99181462-0a055580-272f-11eb-8b65-802afe897fd0.jpg)

**Comment by matkoniecz** [comment]
I would say that especially in case of cycleways it makes sense to ask this question as information whatever cycleway lane is continuous or interrupted is especially valuable.

See also #1944

**Comment by westnordost** [comment]
Yes, it may seem silly to answer such short segments that are "not really own streets" but just connecting ways, but it is still crucial to record this information in order to build a comprehensive network.
