### ISSUE TITLE
Profiles for quest-types and -order

### ISSUE THREAD

**Issue by W-T-Developer** [westnordost/StreetComplete#2279]
When using street complete there are different ideas of using it depending on time/motivation/location.
It would be nice, of the quest-configuration could be saved for every single use case, eg.

- Looking out for a region to optimize
- - only "important" quests like housenumbers
- Outside mapping along the way
 - - "Simple" quests like surface
- Especially going to map
- - complex quests like opening hours

**Comment by matkoniecz** [comment]
Sounds like what #1654 proposed
