### ISSUE TITLE
Left hand mode with OK on the left

### ISSUE THREAD

**Issue by HolgerJeromin** [westnordost/StreetComplete#228]
This would blow up the preference...

**Comment by westnordost** [comment]
I am reluctant to add something like that as long as Android does not support some global setting for that. If the user is not able to set up his phone for left hand use with one click _for all applications_ (that support it), it makes no sense if every app is brewing it's own stew there.
Did you try this hack? https://www.youtube.com/watch?v=goC7wX4aNUw

**Comment by HolgerJeromin** [comment]
Nice hack. 
The podcast app AntennaPod has the Play icon on the other side, but StreetComplete OK Button is not changed.
Just for your information. In most situations i have the phone with the right side, but StreetComplete survey is often different.
