### ISSUE TITLE
Default-speed for zones

### ISSUE THREAD

**Issue by W-T-Developer** [westnordost/StreetComplete#2280]
I suggest a one-click option to select 30km/h-zone instead of choosing speed-zone and entering 30 manually.
Of course other countries may have other default zone-limits.

**Comment by westnordost** [comment]
Fair enough. This however requires research which speed zones are common in the different countries that have them.

This is a list of all countries that do have slow zones: https://github.com/westnordost/StreetComplete/blob/master/res/country_metadata/isSlowZoneKnown.yml

For this to be implemented, we need (another) list where, f.e. a file like `commonSlowZoneSpeed.yml` in this format:
```
DE: 30
...
```

Research could happen via taginfo, f.e. https://taginfo.openstreetmap.org/search?q=zone40#values

A short look reveals that in many countries zone20, zone40 zones *are* known, but are somewhat less common that zone30. Countries where the zone30 is not the absolute clear winner in terms of usage should not prefill 30 into the text field.

**Comment by westnordost** [comment]
Are you up for doing that research? Then I am up to implementing it.

**Comment by rouelibre1** [comment]
Sources to help the with the research : 

https://www.eltis.org/in-brief/news/stockholm-declaration-wants-general-30-kmh-speed-limit
https://innovationorigins.com/a-30-kilometers-per-hour-speed-limit-in-all-residential-areas-alone-is-not-enough/
https://www.thelocal.es/20201022/spain-will-lower-speed-limit-in-cities-to-30kmh-to-curb-spike-in-accidents

**TL;DR** : 

- 30 km/h is already the default limit in many major cities across Europe (sometimes not the default but already widespread, and/or set to become the default in a short timeframe). 

- Ministers from around the world met to adopt the “Stockholm Declaration” at a conference in February which includes commitment to 30kmh (20mph) speed limits where vulnerable road users and vehicles mix (in urban areas).

- Setting a speed limit of 30 km/h should become “the new normal” in all places where cars, cyclists, and pedestrians frequently interact

**Comment by matkoniecz** [comment]
Note what we are interested in what is actually signed right now, not in the plans.

**Comment by W-T-Developer** [comment]
Instead of a configured default value, a button to select my last choice could also be helpful.

**Comment by RubenKelevra** [comment]
Yeah I think that makes much more sense. In Germany we got 20 and 30 zones, but you basically just want to get to the last value most of the time.

**Comment by westnordost** [comment]
Ok, fair enough.
