### ISSUE TITLE
Charging station quest has no alternative to cars

### ISSUE THREAD

**Issue by RubenKelevra** [westnordost/StreetComplete#2281]
I noticed the charging station quest popping up on a charger which is just mapped with `amenity=charging_station` and nothing else. 

The quest asks how many cars can be charged there and don't accept `0`. Which is weird since that's a bicycle charger.

There's also no option to answer this differently, except creating a note - which I think is not ideal.

Would be nice if there's an option that offers: "this charger is not for cars" or "this charger is just for bicycles".

![Screenshot_20201115-125631](https://user-images.githubusercontent.com/614929/99184470-66727000-2743-11eb-9738-c5b196160d63.png)

**Comment by matkoniecz** [comment]
> There's also no option to answer this differently, except creating a note - which I think is not ideal.

Is it a common problem? Or is it result of activity of a single mapper?

OSM data can be broken in many, many ways and only the common/typical cases should be handled in SC. Other can be handled with notes.

**Comment by RubenKelevra** [comment]
> > There's also no option to answer this differently, except creating a note - which I think is not ideal.
> 
> Is it a common problem? Or is it result of activity of a single mapper?
> 
> OSM data can be broken in many, many ways and only the common/typical cases should be handled in SC. Other can be handled with notes.

Well, a charging station in general might be for cars or for bikes. If there's no further information it's a bit weird to assume that it's a car charger. 

The OSM Wiki doesn't imply that `amenity=charging_station` only applies for car chargers.

**Comment by westnordost** [comment]
> There's also no option to answer this differently, except creating a note - which I think is not ideal.

I think charging stations, especially charging stations for e-bikes are rare enough that it is okay to leave a note. It is not going to litter the map much and by the way also solving a tagging mistake: a charger for e-bikes should have `bicycle=yes`

**Comment by RubenKelevra** [comment]
Tagged with

```
amenity=charging_station
bicycle=yes
motorcar=no
motorcycle=no
scooter=yes
truck=no
```

it asks for the operator of the charging station, with an icon showing a car and a plug 🤔

![Screenshot_20201115-141521](https://user-images.githubusercontent.com/614929/99185935-3760fc00-274d-11eb-983e-ed619d08ba42.jpg)

I think it makes sense to switch the graphics around, to show the car on the 'how many cars' and the double plug icon on the 'operator' quests.

I would recommend to extend the quest to 'cars can't be charged here' as an option.

**Comment by RubenKelevra** [comment]
> > There's also no option to answer this differently, except creating a note - which I think is not ideal.
> 
> I think charging stations, especially charging stations for e-bikes are rare enough that it is okay to leave a note. It is not going to litter the map much and by the way also solving a tagging mistake: a charger for e-bikes should have `bicycle=yes`

I agree, they are rare. But it's much easier to put a 'cars cannot be charged here' button into SC, and tag `motorcar=no` than create notes for this. I mean each note means more work for other mappers.

**Comment by westnordost** [comment]
Did you maybe download that quest with v26.0-beta1? The current filter with v26.0 is 
```
        nodes, ways with
          amenity = charging_station
          and !capacity
          and bicycle != yes and scooter != yes
```

Please try invalidating the quest cache and download again. Is it still there then?

**Comment by RubenKelevra** [comment]
> Did you maybe download that quest with v26.0-beta1? The current filter with v26.0 is
> 
> ```
>         nodes, ways with
>           amenity = charging_station
>           and !capacity
>           and bicycle != yes and scooter != yes
> ```
> 
> Please try invalidating the quest cache and download again. Is it still there then?

Well, the node was just tagged with `amenity=charging_station`.

Than the quest with 'How many cars?' appeared.

Since SC didn't gave me an option to add, that cars cannot be charged there, I've added this tags with Vespucci:

```
bicycle=yes
motorcar=no
motorcycle=no
scooter=yes
truck=no
```

After that (and refreshing the data in SC) a car with a plug appeared as an Quest icon... which is rather confusing.

**Comment by westnordost** [comment]
If you invalidate the quest cache now and then download that area again, is the quest still there?

**Comment by matkoniecz** [comment]
@RubenKelevra 

> If you invalidate the quest cache now and then download that area again, is the quest still there?

**Comment by RubenKelevra** [comment]
Hey @matkoniecz, sorry for lagging a bit behind.

> If you invalidate the quest cache now and then download that area again, is the quest still there?

Well we talked about two quests:

The first one (how many cars) assumes that all charging stations are for cars, which is not the case. We should rather ask for the type of vehicles supposed to be or allowed to be charged there first.

When the charging station gets `car=no` this quest won't show up. 

But the second quest shows up (which operator) - which is a bit weird, since the image for this quest contains a car - also on charging stations tagged with `car=no`.

**Comment by westnordost** [comment]
> But the second quest shows up (which operator) - which is a bit weird, since the image for this quest contains a car - also on charging stations tagged with car=no.

True, the charging station operator quest shows for all charging stations, even those tagged as for bicycles. There, the icon does not fit that well, but the question does not mention cars. I think it is okay to leave it like that, alternative would be to not show this quest at all for non-car charging stations. Would you prefer that? (I don't care so much either way, because there are really few non-car charging stations.)

**Comment by westnordost** [comment]
So I'll close this.

**Comment by mal-tee** [comment]
I've found `charging_station` with `bicycle=no`, `motorcar=no` and `waterway=yes`. This seems to generate the quest "How many cars can be charged at this charging station at the same time?" which doesn't make much sense for a charging station for boats. :D

**Comment by mnalis** [comment]
You just need to imagine a boat as water-car

Alternatively, maybe "how many cars" can be changed to "how many vehicles" ?
