### ISSUE TITLE
Unable to reach the authorization server

### ISSUE THREAD

**Issue by Quix0r** [westnordost/StreetComplete#2282]
Related to #44 as the change from external browser (Firefox did work) to web view caused this.

Android 4.1 (old, I know)
SC 26.1 from F-Droid

If you need more storage for images, let me know. :-) I have some spare GBs left.

**Comment by westnordost** [comment]
duplicate of #2258

**Comment by Quix0r** [comment]
I was not seeing it anymore and forgot I posted it.
