### ISSUE TITLE
Road lane quest causes Bridge question

### ISSUE THREAD

**Issue by chrisdebian** [westnordost/StreetComplete#2287]
In the latest beta, a quest has been added, that confirms the number of lanes on a road. After submitting an answer, the road is then marked as having a bridge, and asks the bridge height. No bridge exists, so this shouldn't happen.

**Comment by chrisdebian** [comment]
![Screenshot_20201116-224741](https://user-images.githubusercontent.com/17935223/99317774-7af75b00-285e-11eb-9018-6e7c35e093af.png)

**Comment by HolgerJeromin** [comment]
The question is "below" the bridge. So parts of your highway is below another osm way.
Can you add the location?

**Comment by HolgerJeromin** [comment]
Sorry, I was wrong. I had exactly the same with the very short
https://www.openstreetmap.org/way/34371411/history

This is a bug

**Comment by RubenKelevra** [comment]
Well I think it might show up unintentionally in some cases, for example for powerlines. But I'm not sure what triggers it.

**Comment by HolgerJeromin** [comment]
Tested again with https://www.openstreetmap.org/way/412501832/history
Reverted the wrong entry.

**Comment by westnordost** [comment]
This is the situation:
- when downloading normally, the quest should only appear for below bridges, all fine here
- when solving a quest on the same element, StreetComplete checks whether the updated element qualifies for additional quests (now). The check here was wrong, basically it treated every road as if it is below a bridge

Bugfix update will come today.
