### ISSUE TITLE
Lane quest is not solvable with lane=1

### ISSUE THREAD

**Issue by HolgerJeromin** [westnordost/StreetComplete#2288]
**How to Reproduce**

Way (546209218) is buggy.
Way (673494763) works. Huh

Select: "no marking"
Lane: 1
No OK button
Lane: 2
OK

**Versions affected**

27 beta 1

**Comment by HolgerJeromin** [comment]
BTW the car animation is really funny :-)

**Comment by RubenKelevra** [comment]
Noticed this issue too, on way [762843392](https://www.openstreetmap.org/way/762843392 )
