### ISSUE TITLE
Reverse order of most recently used attributes

### ISSUE THREAD

**Issue by mxxcon** [westnordost/StreetComplete#2289]
I'm offering this feedback based on my experience of completing over 10000 quests.

**Use case**
As of a couple of versions ago StreetComplete started offering last 6 attributes(at least on my phone), with the most recent choice being at the top.

![Screenshot_20201116-213608](https://user-images.githubusercontent.com/847140/99339289-e2f47400-2853-11eb-93ce-ee5a11552096.png)

Unfortunately, this makes things a bit less efficient and not as optimal for ergonomics.
If I'm walking down a street of row houses or other types of similar attributes after each selection I have to move my finger a lot further on the screen. During a longer mapping session this is actually fatiguing.

**Proposed Solution**
Reverse the order of these options so that the most recent selection be at the bottom of the screen, closer to the OK button. This would allow people to complete quests faster, with less effort and lower the chance of RSI.

**Comment by westnordost** [comment]
Hm actually, this is a bug. The bottom sheet should not expand by default to full height but just show the first 2-4 items. When this bug is solved, then selecting the topmost element will not be a stretch (for the thumb)

**Comment by westnordost** [comment]
So, this is how it should look.

![Screenshot_20201117-133603_StreetComplete Dev](https://user-images.githubusercontent.com/4661658/99391061-e3375280-28d9-11eb-8fbf-0d19a09dac4c.jpg)
