### ISSUE TITLE
Redundant house number quests in Norway.

### ISSUE THREAD

**Issue by wailashi** [westnordost/StreetComplete#229]
Hello,
While using StreetComplete in Oslo I noticed that almost all buildings have the "What is the house number of this building" quest. It seems the quest is looking for building outlines without house numbers. According to the [OpenStreetMap wiki](http://wiki.openstreetmap.org/wiki/Addresses#Norway) addresses in Norway are not tied to the building outline, but instead are a separate feature.
Furthermore Norwegian addresses are automatically added from a government data source so almost all buildings are already correctly numbered.

Currently StreetComplete is encouraging the adding of unnecessary redundant information in a way that is not in line with the local community guidelines. This issues is probably also valid for Denmark as they use a similar system.

**Comment by matkoniecz** [comment]
In Poland tagging house number both as node and on buildings are considered acceptable.

**Comment by Etua** [comment]
@westnordost Probably another reason to speed up the development of localized quests ;)

**Comment by westnordost** [comment]
This is a bug! The quests should not me shown for buildings that have a node with a housenumber inside.

Could you please tell me an area where this turns up so I can check where is the problem?

**Comment by westnordost** [comment]
Okay, I had a look myself. Some street number quests are shown for example here in Oslo:
http://www.openstreetmap.org/#map=18/59.92431/10.71814

They are shown because those housenumber nodes are not within the building outline. I'd consider this a fault in the data as those nodes should either be inside the building outline or be entrance-nodes on the building outline.

**Comment by wailashi** [comment]
I had a look at the map around Oslo and it seems that the address nodes are in the correct places on the aerial an satellite imagery, but all the building outlines are off by a bit.
I think I'll poke the local osm contributors to find out what is up with that.

Regardless of the above according to the [wiki](http://wiki.openstreetmap.org/wiki/No:Map_Features#Addresses):

> Please do not merge the address node into the building outline. 

which is I understand what StreetComplete does currently, so I think this should be considered a bug.

I am only a casual osm user, but as far as I could find anywhere on the wiki or discussions, there is no requirement for address nodes to be within the building outlines.
I don't know what is the right course of action, but as of now Oslo is covered in quests to add house numbers to buildings that already have them in a way that seems to be discouraged by the local mapping community.

**Comment by westnordost** [comment]
StreetComplete does not merge anything, it only adds data. So, taking the Oslo example, there would be two addresses: One on the building and one on the misplaced node.

If someone (i.e. local contributors) correct the node's position onto the building and delete the housenumber tag from the building, the app will not ask the user again for the housenumber.

**Comment by westnordost** [comment]
If this behavior is not satisfactory for the local Norwegian community, another solution would be to not show the housenumber quests at all for Norway. To X out quests for certain countries is currently not possible yet, but is planned to be implemented for the next major version.

However, this should be discussed by the local community first.

The course of action:
1. discuss with local community: is the behavior explained in the above comment satisfactory?
2. If not, please create a ticket to disable the housenumber quest for Norway. As soon as the "per country" feature is implemented, I can then remove the quest for Norway.

**Comment by althio** [comment]
> However, this should be discussed by the local community first.

Also I don't know if relation:associatedStreet can make the situation different regarding detection of buildings with or without addresses.

**Comment by HolgerJeromin** [comment]
Even with the street relation the number is on the building or node, so there is no difference.

**Comment by matkoniecz** [comment]
https://wiki.openstreetmap.org/wiki/Addresses#Norway mentions import but is not mentioning ban on manual mapping

**Comment by westnordost** [comment]
https://forum.openstreetmap.org/viewtopic.php?id=60356
