### ISSUE TITLE
Deactivate quest from map pin

### ISSUE THREAD

**Issue by rouelibre1** [westnordost/StreetComplete#2292]
**Use case**

When I'm completing quests, I often realize that the selection I have made is not well suited for the location I'm exploring. One example is : if I activate the "what type of building is this ?" in some areas there are only a few buildings that aren't specified so it's manageable in the mix of quests, and in other areas almost all the buildings will show up on the map so it's hard to see anything else on the map and things get too repetitive for the fun not to fade out unless I temporarily deactivate the quest.

**Proposed Solution**
What about adding a 3rd option "Deactivate (or deselect) this quest" to the list that shows up when long pressing on a POI ?

**Comment by westnordost** [comment]
I think such a dark UI would just be confusing. How is the user ought to know that there is a shortcut like that?

**Comment by rouelibre1** [comment]
But then the same logic applies to both shorcuts that are already in the menu. 
Plus I feel it's way less confusing than what is discussed in #2293 

I believe it's UX best practice to provide multiple points of entry to content that users want/need to access regularly + to shorten the path.

Not saying my proposed solution is the best though, but I think facilitating the back and forth path between the map and the quests selection would definitely help users.

It wouldn't help with https://github.com/westnordost/StreetComplete/issues/2243 but would work well with https://github.com/westnordost/StreetComplete/issues/1654

**Comment by mnalis** [comment]
I think presets would work well enough for me... One named "Only actually useful stuff" and another named "I'm bored, gimme everything" (and just maybe one more preset in the middle. or not). Then in such area with a lots of stuff I'd just quickly switch to "usefull stuff" preset and call it a day.

Actually, if SC used quest priorities not just for order when asking questions for same POI, but **also as a "layer depth" for displaying quests on the map**, I wouldn't even need presets. I'd simply put most important quests at the top of the list (as I do now), but then low priority quests wouldn't even be shown if there were more important quests occupying the space on the map.

**Comment by westnordost** [comment]
> But then the same logic applies to both shorcuts that are already in the menu.
> Plus I feel it's way less confusing than what is discussed in #2293

Well, that's whataboutism, that feature was there pretty much from the beginning. Maybe we can talk about removing it if it is not used at all (@smichel17 seems to use it sometimes though), but not in this ticket and not as an argument why this feature should be implemented.

> I believe it's UX best practice to provide multiple points of entry to content

Is it? I believe the opposite actually.

I plan to add something like @mnalis mentioned in his first paragraph.

**Comment by rouelibre1** [comment]
> Well, that's whataboutism, that feature was there pretty much from the beginning. Maybe we can talk about removing it if it is not used at all (@smichel17 seems to use it sometimes though), but not in this ticket and not as an argument why this feature should be implemented.

Understood, makes sense.
 
> > I believe it's UX best practice to provide multiple points of entry to content
> 
> Is it? I believe the opposite actually.

That's what a UX designer kept telling me. That might only be a valid rule for websites and not mobile apps though, and could be different depending on the context I guess.

> I plan to add something like @mnalis mentioned in his first paragraph.

I'll wait & see then 👍🏼

**Comment by westnordost** [comment]
I'll close this one then because I don't intend to implement this.

**Comment by smichel17** [comment]
> (@smichel17 seems to use it sometimes though)

> I use it on very rare occasions when I think it may block another quest that I can answer. (from https://github.com/streetcomplete/StreetComplete/issues/2293#issuecomment-729352059)

Note: if my suggestion in https://github.com/streetcomplete/StreetComplete/issues/124#issuecomment-755492391 were implemented, I don't think I would have any use for hiding quests any more (especially with quest presets (#1654)).
