### ISSUE TITLE
Restoring hidden quest has no effect

### ISSUE THREAD

**Issue by rouelibre1** [westnordost/StreetComplete#2293]
When tapping "Restore hidden quests" a message appears that says "Restored 0 hidden quests"

Even though I have some quests left unchecked in the quest selection menu. 

When I visit que quest selection menu after this action, they are still unchecked.

I suppose that's what this option is for ?

**Comment by westnordost** [comment]
The option is for quests you hid when tapping on "Can't answer" -> "Leave a note instead?" -> "No, just hide"

**Comment by rouelibre1** [comment]
Clearer thanks. I had no idea this feature even existed, I somehow thought the "Can't answer" would directly prompt me to leave instead.

Since most of the time I didn't feel like leaving a note when I couldn't anwser, I used to always hit the "back" button of my device instead of seleting this option, but I was a bit frustrated that I couldn't just hide the pin.

**Comment by westnordost** [comment]
Yeah, it is not really used I think

**Comment by smichel17** [comment]
I use it on very rare occasions when I think it may block another quest that I can answer.

**Comment by rouelibre1** [comment]
Now that I know about it, I will definitly use it. It will be quite useful for me : there are many cases where I would like to hide quests that I'm not able/not willing to answer. 

As we started discussing in #2292, I believe the feature should be kept, but there is definitely a discoverability issue (for which I unfortunately don't have a clever solution to suggest).
