### ISSUE TITLE
Clarify the tracktype quest

### ISSUE THREAD

**Issue by cyclingcat** [westnordost/StreetComplete#2294]
Hi there,

the tracktype quest (= the one with the green tractor icon) shows five short descriptions with associated pictures the user is requested to choose from. However, these descriptions sometimes do not match the ones in the German/English OSM wiki pages, thus causing some confusion. In English language, the wording **"Mostly solid"** is even used in both contexts with different tracktypes!

See this comparison (SC string first, OSM wiki label second):

**[In English:](https://wiki.openstreetmap.org/wiki/Key:tracktype#Values)**
_tracktype=grade1_: Solid / Solid [ok]
_tracktype=grade2_: **Mostly solid** / Solid but unpaved [hm...]
_tracktype=grade3:_ Mixture / **Mostly solid** [huh?]
_tracktype=grade4:_ Mostly soft / Mostly soft [ok]
_tracktype=grade5:_ Soft / Soft [ok]

**[In German:](https://wiki.openstreetmap.org/wiki/DE:Key:tracktype#Schl.C3.BCsselwerte)**
Here it's even more confusing, because the German wording in the wiki is a little inconsistent as it mixes more precise (albeit uncommon) descriptions ("Wassergebundene Decke") with very vague ones ("Einfacher Weg"/"Unbefestigter Weg"):

_tracktype=grade1_: Befestigt / Wasserfester Belag [ok]
_tracktype=grade2_: Größtenteils befestigt / Wassergebundene Decke [hm...]
_tracktype=grade3_: Gemischt / Befestigter oder ausgebesserter Weg [hm...]
_tracktype=grade4_: Größtenteils unbefestigt / Einfacher Weg [hm...]
_tracktype=grade5_: Unbefestigt / Unbefestigter Weg [ok]

Of course there are the guiding pictures. I checked them in the wiki: all but one languages use the same example pictures for the five tracktypes (the only exception is Croatian which has its own pictures, these are quite similar to the other ones though). For "grade5", however, there is a noticeable difference between the pictures in SC and the wiki, possibly leading the user to choose the wrong answer and thus tagging the wrong tracktype value: According to the wiki page in many languages this tracktype means that the way is hardly distinguishable from its surroundings ("same as surrounding soil", "bestehend aus dem natürlich vorkommenden Bodenmaterial", "empreinte visuelle presque nulle sur le paysage", "traccia poco evidente") - the photo in the wiki page reflects this while the one in SC shows a clearly visible way which I would tag at least with "tracktype=grade4".

**Suggestions:**

- Replace the current "grade5" picture in SC with the one from the wiki (I'd prefer the one from the Croatian page) or find an even better one. As this is language-independent, it should be easy to change. grade1-grade4 are fine IMHO.

- Find better wordings. This would be the difficult part, as SC supports much more languages than the "tracktype" wiki page, furthermore some wiki pages miss a description short and concise enough to be suitable for SC (e.g. French or Finnish).  At least fix the English "Mostly solid" discrepancy mentioned above.

The cycling cat

**Comment by matkoniecz** [comment]
> Of course there are the guiding pictures. I checked them in the wiki: all but one languages use the same example pictures for the five tracktypes (the only exception is Croatian which has its own pictures, these are quite similar to the other ones though). For "grade5", however, there is a noticeable difference between the pictures in SC and the wiki, possibly leading the user to choose the wrong answer and thus tagging the wrong tracktype value: 

Wiki photo: https://github.com/westnordost/StreetComplete/blob/master/app/src/main/res/drawable-xhdpi/tracktype_grade5.jpg

SC photo: https://wiki.openstreetmap.org/wiki/File:Tracktype_grade5.jpg

> According to the wiki page in many languages this tracktype means that the way is hardly distinguishable from its surroundings ("same as surrounding soil", "bestehend aus dem natürlich vorkommenden Bodenmaterial", "empreinte visuelle presque nulle sur le paysage", "traccia poco evidente") - the photo in wiki page reflects this 

Note that "same as surrounding soil" seems to refer to material, not to way being indistinguishable from surreounding. For example muddy logging road, with no hard/compacted material may be extremely well visible but still `grade5`. I would say that SC has better photo than OSM Wiki here as it avoids mixing this two concepts.

Or maybe I am misunderstanding wiki (or it was edited).

Looking at original - https://wiki.openstreetmap.org/wiki/Proposed_features/grade1-5 

>     tracktype - Grade 5 - A track that usually runs freely withough hedges and just grass. It is perminent and is clearly visible by the indented shape of the ground.

So it diverged at some point, it may be worth checking when and why

> while the one in SC shows a clearly visible way which I would tag at least with "tracktype=grade4".

Note this part of wiki definition for grade4 "with some hard or compacted materials mixed in."

Tagging it as `grade4` would be against that description (but following https://wiki.openstreetmap.org/wiki/Proposed_features/grade1-5 ...)

>  In German: Here it's even more confusing, because the German wording in the wiki is a little inconsistent as it mixes more precise (albeit uncommon) descriptions ("Wassergebundene Decke") with very vague ones ("Einfacher Weg"/"Unbefestigter Weg"):

Then German translation should be fixed.

**Comment by matkoniecz** [comment]
So SC is following wiki description, not following wiki photos.

Wiki description diverged from wiki photos and original proposal at some point.

**Comment by matkoniecz** [comment]
@cyclingcat So next step would be tracking down when and why wiki wording was changed and whatever it was change that was supported/discussed modification.

**Comment by westnordost** [comment]
@cyclingcat ping

**Comment by cyclingcat** [comment]
Sorry for the delay...

The pictures in the wiki were introduced in July 2008 (English), November 2008 (German, already in the initial version of the page) and September 2009 (Croatian, they used their own "grass on grass" picture from the very beginning) respectively. They have remained unchanged since then, as well as the descriptions, so I'd assume that the definitions have settled down (albeit being a little inconsistent and vague). I don't see a big difference between the descriptions and the pictures in the wiki. Granted, the descriptions in the wiki pages aren't always precise enough here and in addition the tracktypes are defined somewhat differently in different languages. On the other hand those "grass on grass" ways are very common in the wild: Just traces of compressed grass, perhaps created by many tractors having rolled over them in the past, often tagged solely with "highway=track" without further specification. They often make up a whole network of these kinds of tracks in agricultural regions, hardly visible from greater distance but nevertheless real existing tracks regularly used by agricultural vehicles and walkers (sometimes even indicated hiking trails).

The pictures in the wiki meet the current description "same as surrounding soil" (or similar in other languages, as mentioned in my original posting), especially the Croatian one, which is just a cropped and slightly brightened version of the one of the proposal. See here (left side: The Croation wiki picture, right side: The picture from the proposal 12 years ago):

<img src="https://wiki.openstreetmap.org/w/images/6/65/Surface_grade5.jpg" /> ![grade5_proposal](https://user-images.githubusercontent.com/32601012/100428218-eed20880-3093-11eb-9a12-11f72c9862ae.jpg)

The "tracktype=grade5" image in SC, however, looks more like a "dirt on grass" way, further away from the definition "same as surrounding soil":

<img src="https://raw.githubusercontent.com/westnordost/StreetComplete/master/app/src/main/res/drawable-hdpi/tracktype_grade5.jpg" />

So I stick to my opinion that the "grade5" picture from the wiki would be a better illustration of the wording used in the wiki than the one currently used in SC. My personal favourite would be the one from the proposal, cropped to the section of the Croatian picture (higher contrast and without the distracting tree).

And what about the English "Mostly solid" wording? Here the same wording is used for "tracktype=grade3" (in the wiki) and "tracktype=grade2" (in SC). As vague as this wording is, it shoudn't be used in SC for setting a different "tracktype" value than it is mentioned in the wiki.

The cycling cat

**Comment by westnordost** [comment]
Do you have a suggestion for a wording that fits better and does not fall out of line with the rest of the wording? 

On 27 November 2020 09:54:30 CET, cyclingcat <notifications@github.com> wrote:
>Sorry for the delay...
>
>The pictures in the wiki were introduced in July 2008 (English),
>November 2008 (German, already in the initial version of the page) and
>September 2009 (Croatian, they used their own "grass on grass" picture
>from the very beginning) respectively. They have remained unchanged
>since then, as well as the descriptions, so I'd assume that the
>definitions have settled down (albeit being a little inconsistent and
>vague). I don't see a big difference between the descriptions and the
>pictures in the wiki. Granted, the descriptions in the wiki pages
>aren't always precise enough here and in addition the tracktypes are
>defined somewhat differently in different languages. On the other hand
>those "grass on grass" ways are very common in the wild: Just traces of
>compressed grass, perhaps created by many tractors having rolled over
>them in the past, often tagged solely with "highway=track" without
>further specification. They often make up a whole network of these
>kinds of tracks in agricultural regions, hardly visible from greater
>distance but nevertheless real existing tracks regularly used by
>agricultural vehicles and walkers (sometimes even indicated hiking
>trails).
>
>The pictures in the wiki meet the current description "same as
>surrounding soil" (or similar in other languages, as mentioned in my
>original posting), especially the Croatian one, which is just a cropped
>and slightly brightened version of the one of the proposal. See here
>(left side: The Croation wiki picture, right side: The picture from the
>proposal 12 years ago):
>
><img
>src="https://wiki.openstreetmap.org/w/images/6/65/Surface_grade5.jpg"
>/>
>![grade5_proposal](https://user-images.githubusercontent.com/32601012/100428218-eed20880-3093-11eb-9a12-11f72c9862ae.jpg)
>
>The "tracktype=grade5" image in SC, however, looks more like a "dirt on
>grass" way, further away from the definition "same as surrounding
>soil":
>
><img
>src="https://raw.githubusercontent.com/westnordost/StreetComplete/master/app/src/main/res/drawable-hdpi/tracktype_grade5.jpg"
>/>
>
>So I stick to my opinion that the "grade5" picture from the wiki would
>be a better illustration of the wording used in the wiki than the one
>currently used in SC. My personal favourite would be the one from the
>proposal, cropped to the section of the Croatian picture (higher
>contrast and without the distracting tree).
>
>And what about the English "Mostly solid" wording? Here the same
>wording is used for "tracktype=grade3" (in the wiki) and
>"tracktype=grade2" (in SC). As vague as this wording is, it shoudn't be
>used in SC for setting a different "tracktype" value than it is
>mentioned in the wiki.
>
>The cycling cat
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/westnordost/StreetComplete/issues/2294#issuecomment-734721800

-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.

**Comment by cyclingcat** [comment]
<h3>English:</h3>

Considering the fact that the longest German wording currently contains 26 characters, it should be no problem to use the exact English wordings from the wiki. Thus:

**grade2:** "Solid but unpaved" (17 characters)
**grade3:** "Mostly solid" (12 characters)

(this would at least solve the current discrepancy, thus being an improvement and independent from all the other details discussed here.)

<h3>German:</h3>

This is more difficult as the descriptions in the German wiki page are sometimes quite generic or technical: For example, "Einfacher Weg" needs an explanation (the wiki shows one, but it's far too long for SC), while probably only few users know what "Wassergebundene Decke" means. A first attempt, based on the English wording and trying to avoid surface-related words:

**grade1:** "Stabil und befestigt"
**grade2:** "Stabil, aber unbefestigt"
**grade3:** "Größtenteils stabil"
**grade4:** "Wenig stabil" (or "Eher weich"?)
**grade5:** "Instabil" (or "Weich"? Or "Naturboden"?)

Together with the images this could be both fitting and comprehensible, couldn't it?

The cycling cat

**Comment by westnordost** [comment]
Okay, that makes sense. This will go into the next version.

**Comment by westnordost** [comment]
I used the picture from the wiki for tracktype 5 after all because it is a better / more extreme example of "completely ground-surface". The picture from the original proposal still had well visible tracks.
