### ISSUE TITLE
Center left turn lane is right turn in countries driving on the left side

### ISSUE THREAD

**Issue by matkoniecz** [westnordost/StreetComplete#2296]
> quest_lanes_answer_lanes_center_left_turn_lane (...) Does it differ in countries where cars drive on left side as opposed on right side of the road?

https://poeditor.com/projects/po_edit?id=97843&term=267827279&id_language=5#showComments267827279

**Comment by westnordost** [comment]
In countries, not in languages! So for en-GB, it is still a two way left turn lane!

And it so happens that as far as i know,  such turn lanes only exist in the US and Canada, both drive on the right

**Comment by matkoniecz** [comment]
> In countries, not in languages! So for en-GB, it is still a two way left turn lane!

Yes, that is why new string may be needed.

> And it so happens that as far as i know, such turn lanes only exist in the US and Canada, both drive on the right

It is extremely rare, but I have seen them also in Poland.

**Comment by westnordost** [comment]
>> In countries, not in languages! So for en-GB, it is still a two way left turn lane!

>Yes, that is why new string may be needed.

??

**Comment by westnordost** [comment]
`lanes:both_ways=1` is **any** road where one lane goes both ways. These are not all TWLT lanes

**Comment by mnalis** [comment]
as the poeditor link at the top doesn't work for me, to copy/paste westnordost explanation from there:

> Here is an explanation with pictures what it is, probably it only exists in US and Canada. So, if that thing does not exist in your country, feel free to translate it literally or just leave the English wording and put it in quotes:
> 

> https://www.drivesmartbc.ca/lanes/two-way-left-turn-lanes

**Comment by peternewman** [comment]
Britain has them too, although there might be a divider (probably diagonal) at the "collision" point/end of the lanes.

**Comment by westnordost** [comment]
> although there might be a divider (probably diagonal) at the "collision" point/end of the lanes.

There might or there is? If there is, that's not a TWLT lane but a lane in one direction until the collision point and a lane in the other direction starting at the collision point.
Can you post an example?

**Comment by peternewman** [comment]
https://www.google.com/maps/place/51%C2%B040'34.3%22N+0%C2%B022'43.9%22W/@51.6761307,-0.3787638,44m/data=!3m1!1e3!4m5!3m4!1s0x0:0x0!8m2!3d51.6761974!4d-0.3788548

**Comment by westnordost** [comment]
Ok I wouldn't say this is a TWRT lane.

**Comment by westnordost** [comment]
This is an interesting construct though. But also not a TWRT lane.
https://www.google.com/maps/@51.6754363,-0.3795288,3a,75y,21.27h,62.13t/data=!3m6!1e1!3m4!1saPlvOsz2m-jOncF-zE5EsA!2e0!7i16384!8i8192

**Comment by peternewman** [comment]
> Ok I wouldn't say this is a TWRT lane.

Okay, but if it didn't have the line it would be? I'll see if I spot any others when I think of it. Top marks on the L/R swap too! :smile: 



> This is an interesting construct though. But also not a TWRT lane.
> https://www.google.com/maps/@51.6754363,-0.3795288,3a,75y,21.27h,62.13t/data=!3m6!1e1!3m4!1saPlvOsz2m-jOncF-zE5EsA!2e0!7i16384!8i8192

Heh yeah, we have some interesting stuff in the UK!

**Comment by westnordost** [comment]
> Okay, but if it didn't have the line it would be?

The concept of a two way turn lane is pretty defined and I'd say definitely something else than just a little space in the center of an intersection where cars from both directions cross. How that would be tagged, I don't know. Maybe ask on the tagging mailing list or research how such situations are tagged currently.

So I'll cose this. When other countries where a two way turn lane is discovered exist, they will be added to the appropriate file and if this country is also a country where cars drive on the left, a new string needs to be added.
