### ISSUE TITLE
Zooming out with tap+drag gesture is too fast

### ISSUE THREAD

**Issue by kuba-orlik** [westnordost/StreetComplete#2297]
**How to Reproduce**
Tap the map and then drag the finger up to trigger the "zoom by drag" gesture. The map zooms out super-fast, and in a split-second zooms out so far that I see the global map. 

You can see the bug in motion here: 

https://vimeo.com/480702185

**Versions affected**
Android 8.1.0, StreetComplete 26.2 (f-droid)

**Comment by westnordost** [comment]
Okay, I didn't even know that gesture existed. But this is the wrong project, the behavior for such gestures is controlld by tangram-es.

You need to post this bug here: https://github.com/tangrams/tangram-es

**Comment by kuba-orlik** [comment]
Posted an issue here: https://github.com/tangrams/tangram-es/issues/2207
