### ISSUE TITLE
surface=stone cannot be answered in surface quest

### ISSUE THREAD

**Issue by eikel** [westnordost/StreetComplete#2298]
**Use case**
This is a follow up to #2277. I saw that the [OSM wiki](https://wiki.openstreetmap.org/wiki/Tag:ford%3Dstepping_stones) has been updated and that it makes sense to explicitly set the surface of stepping stones. I wanted to answer the surface quest for stepping stones which are really some large stones lying in the water. But, the stone answer is missing.

**Proposed Solution**
Add surface=stone as answer to surface quest.

**Comment by matkoniecz** [comment]
Note that `surface=stone` remains undocumented at OSM Wiki and is fairly rare (https://taginfo.openstreetmap.org/tags/surface=stone ).

Though looking at https://taginfo.openstreetmap.org/keys/surface#values it seems the most popular unsupported viable value.

I would recommend checking how it is used (Overpass Turbo, ask others on tagging mailing list or elsewhere) and documenting it, before it is even considered.

See https://wiki.openstreetmap.org/wiki/Talk:Tag:ford%3Dstepping_stones

**Comment by Atrate** [comment]
I have to say I've run into a similar issue, `surface=stone` would often have helped

**Comment by rhhsm** [comment]
I'd also often have liked to have "natural stone" as an option where I now choose to tag as "paving stones". However I think this should be proposed at OSM and only be adopted by SC when consensus is reached at OSM.

**Comment by matkoniecz** [comment]
> I'd also often have liked to have "natural stone" as an option where I now choose to tag as "paving stones".

Note that `surface=paving_stones` includes quite wide variety, including paving made from actual stones (see https://wiki.openstreetmap.org/wiki/Tag:surface%3Dpaving_stones )

**Comment by westnordost** [comment]
How about this for `surface=rock`? (People on OSM Slack tell me that "rock" would be more fitting for natural rough surfaces while stone would be more fitting for smooth hewn rock.)

https://commons.wikimedia.org/wiki/File:Bare_Rock_Trail_Surface_at_Lake_Roland.jpg

**Comment by matkoniecz** [comment]
Seems fitting to me to some cases not covered by other values ( https://commons.wikimedia.org/wiki/File:Krywan.JPG https://commons.wikimedia.org/wiki/File:Krywan_podejscie.jpg ), though it is also not documented and not very popular so I would also at least create wiki page before adding it

https://taginfo.openstreetmap.org/tags/surface=rock#overview

**Comment by westnordost** [comment]
Loose rocks came up shortly on Slack too. In English, this would probably be `scree` (though difference to `gravel` is not entirely clear to me, maybe size of such loose rocks)

**Comment by westnordost** [comment]
Screenshot for image search for "scree":

![screenshot-scree](https://user-images.githubusercontent.com/4661658/99852740-e81e2f80-2b81-11eb-8b83-8f3645e3e422.jpg)

**Comment by westnordost** [comment]
There is also `bare_rock` (absence of smaller rocks, surface like a slab), however I don't really want to go into that detail here. `rock` seems to be a good category

**Comment by matkoniecz** [comment]
Going by https://en.wikipedia.org/wiki/Scree and my low quality knowledge of English terms - maybe scree is rather for natural gravel/small rocks while gravel is rather for man made crushed rocks of smaller and more regular size?

**Comment by ArloJamesBarnes** [comment]
gravel is a size classification. scree is an origin classification (it's a flow of rocks eroded out of a body uphill by frost action), although it has a size component since on the larger end it's talus. So you can have a gravel scree, a pea gravel scree, boulder talus, etc.

**Comment by matkoniecz** [comment]
Mailing list post posted.

**Comment by westnordost** [comment]
So, there are now some nice pictures for `surface=rock`. Question is, if it should also be possible to tag `stone`?

**Comment by matkoniecz** [comment]
I have feeling that `surface=rock` and `surface=stone` would become tags with de facto the same meaning, even if some mappers/communities would have some different ideas about differences (Like `surface=dirt` vs `surface=earth` or `natural=wood` vs `landuse=forest` and so on)

**Comment by westnordost** [comment]
"would become"?

**Comment by westnordost** [comment]
The comments on the mailing list and on #tagging on osm slack were pretty consistent

**Comment by matkoniecz** [comment]
> "would become"?

I think that even if planned differences would be documented and described then in actual usage the tags would be used interchangeably.

(even relatively clear `surface=compacted` is often problematic for mappers)

> The comments on the mailing list and on #tagging on osm slack were pretty consistent

I am not opposed to this tag, just not planning to spend time on documenting it (I felt that `surface=rock` makes sense and would be an useful, so I put effort into documenting it).

**Comment by jancborchardt** [comment]
Sorry to bring this up again, but it doesn’t seem like it’s concluded (I also read through https://github.com/streetcomplete/StreetComplete/issues/1132 )

I encountered this issue twice just already in Berlin Schöneberg, both with steps:
- Apostel-Paulus-Kirche has natural stone steps on all the entrances around: https://www.flickr.com/photos/ametzelchen/4633224560/ – as do a lot of churches and old buildings
- Carl-Zuckmayer-Brücke has natural stone steps as well: https://www.flickr.com/photos/bridgestream/9076867146/

In both cases:
- It doesn’t fit any of the existing surfaces of https://wiki.openstreetmap.org/wiki/Key:surface
- It’s definitely not `paving_stones` or `concrete`, even though for all intents and purposes it could be made of the same material cause it’s relatively smooth
- It’s absolutely not `rock` though, cause that’s rough: "Exposed rock or big pieces of rock used to improve path quality. Typically in mountainous areas."
- `stone` seems to really be most fitting. But it is not possible to choose, and neither really documented in OSM. So I’m wondering if I should tag that manually via the web interface at all.

I’m fine with any conclusion or decision, but so far it doesn’t seem to be clear what to do in these cases. Thanks! :)

**Comment by Helium314** [comment]
Why is `paving_stones` not suitable?
In my understanding the conditions are satisfied:
* relatively smooth
* natural stones with a flat top
* narrow gaps
* (presumably) carefully selected, fitted and placed in order to form an even, closed surface

**Comment by matkoniecz** [comment]
https://www.flickr.com/photos/ametzelchen/4633224560/ looks like `surface=sett` or `surface=paving_stones`

https://www.flickr.com/photos/bridgestream/9076867146/ is definitely `paving_stones` - completely flat stone, though in relatively large pieces

**Comment by westnordost** [comment]
I'd say `surface=stone` is for natural, i.e. unhewn, stones that are relatively smooth. It's not that well documented in the wiki, but that's how I'd interpret it, given that for hewn stones, there is already sett and/or paving stones.

**Comment by jancborchardt** [comment]
Thanks a lot for that info everyone, I’ll use `paving_stones` then. :)

(I think it was cause my understanding of the word "paving stones" incl also the picture made me imagine small/medium pieces put together rather than massive slabs of granite – but in practice that’s a detail, totally right.)

**Comment by Helium314** [comment]
Yes, the picture is definitely a bit misleading here... covering all cases in such a small graphic is a bit of a problem
