### ISSUE TITLE
Quest for house number

### ISSUE THREAD

**Issue by escoand** [westnordost/StreetComplete#23]
A quest for house numbers is much more important from my point of view than the shape of the roof.
In the feature graphic it is already iconed, is there a reason why it is not implemented yet?

**Comment by westnordost** [comment]
Other than time and perhaps wrong prioritization, as you imply, none.

To find where housenumbers are actually missing is simply a bit more complex programmatically, as housenumbers can be on buildings, entrances, free-floating nodes, on amenities and even on landuses.

This is relatively high on my to do list though now.

**Comment by CloCkWeRX** [comment]
Probably cant do it with the tile layer in place, but find the QA no address layer in vespucci good at addressing this.

perhaps qa.poole.ch 's queries could help

**Comment by Jotam** [comment]
I strongly support this suggestion. However, one problem will be to distinguish those buildings that _should have_ a house number from those that shouldn't. You may find several buildings in one compound, like the main house, a car port and a garden shack. The app shoudn't ask for house numbers on each of these, but only on the main building. I guess it would be hard to clearly make that distinction.

**Comment by westnordost** [comment]
Done
