### ISSUE TITLE
lane quest in version 27.0-beta1, german language

### ISSUE THREAD

**Issue by julietkilo** [westnordost/StreetComplete#2300]
The correct term for a lane in german is "Fahrstreifen", but it's called "Fahrspur".
https://www.bast.de/BASt_2017/DE/Publikationen/Regelwerke/Verkehrstechnik/Downloads/V-asb-begriffsbestimmungen.pdf?__blob=publicationFile&v=3

**How to Reproduce**
Use Lane quest

**Versions affected**
version 27.0-beta1

**Comment by FloEdelmann** [comment]
I've updated the German translation: https://poeditor.com/projects/po_edit?id_language=55&id=97843

You can do this too if you find any other possible translation improvements. See instructions here: https://github.com/westnordost/StreetComplete/blob/master/CONTRIBUTING.md#translating-the-app

**Comment by westnordost** [comment]
Thanks, @FloEdelmann
