### ISSUE TITLE
Width of quest answers is truncated, so text splits into multiple lines

### ISSUE THREAD

**Issue by mnalis** [westnordost/StreetComplete#2302]
Quest hint, and quest answers do not use full width of the form available, but only about half of it.
It is very visible in some translations which are necessary longer than in English (like Croatian).
For example, here one answer is split in even 4 rows, while it could fit in 2:
![Screenshot_20201118_193520_de westnordost streetcomplete](https://user-images.githubusercontent.com/156656/99574293-7a360480-29d7-11eb-96d5-8d1a278876d5.jpg)

**How to Reproduce**
Select system language Croatian, enable and choose SpeedLimit quest.

**Versions affected**
Android 10 (EMUI 10), StreetComplete v26.1 (from f-droid)

**Comment by westnordost** [comment]
This is correct. The right side is reserved for the UI that is displayed when you select one of these options.
