### ISSUE TITLE
Duplicate answer "farm building"

### ISSUE THREAD

**Issue by mnalis** [westnordost/StreetComplete#2303]
On building type quest, there are two `Farm building` answers. They should probably be named and described differently (or one of them removed).

See answers marked with red arrow in picture:
![farm_building_duplicate](https://user-images.githubusercontent.com/156656/99577136-32b17780-29db-11eb-910d-3ea2b13cf866.jpg)

**How to Reproduce**
- Select a `building type` quest, and select `Show more / On a farm`.
- Observe two `Farm building` answers with different icons, one with detailed description and one without.

**Versions affected**
Android 10 (EMUI 10.1), Streetcomplete v26.1 (also v27.0-beta2)

**Comment by westnordost** [comment]
Oops, copy&paste mistake!
