### ISSUE TITLE
Bug while cutting ways for the height quest 

### ISSUE THREAD

**Issue by RubenKelevra** [westnordost/StreetComplete#2304]
Cutting a way which is too long for just the part which is below the bridge doesn't work as expected: The parts of the cut road which are not below the bridge show up too for the height quest:

![Screenshot_20201118-211532](https://user-images.githubusercontent.com/614929/99583283-8d4ed180-29e3-11eb-8f7b-2f63eabdc3e1.jpg)

In this example I've cut the way twice and 3 quests appeared. 

**Versions affected**
v27. 0b2

**Comment by matkoniecz** [comment]
The tricky part is that when way is split it is no longer possible to determine which part is under bridge.

So either all parts will show or none. Showing neither part would be worse and require extra coding to support it.

**Comment by westnordost** [comment]
Yeah right, this is difficult. The assumption so far was that if any way is applicable to a quest before a split, all its elements will be applicable to it afterwards too. For this quest type, this assumption is wrong. And at that point, the information is also not there anymore to determine it.
Unless big things are changed on how the data is used, I think the only solution would be to switch off this assumption for certain quest types manually (in the code)

**Comment by RubenKelevra** [comment]
I think it's fine to mark some quests that they need to re-evaluated against the quest filters after the split - since they depend on the surrounding the tags on the way itself.

I don't see a need to automate this decision, we just need a configuration which can be set for certain quests. :)

Thanks for fixing!
