### ISSUE TITLE
It is possible to have lane markings and lane=1 at once

### ISSUE THREAD

**Issue by matkoniecz** [westnordost/StreetComplete#2306]
For example https://www.openstreetmap.org/way/441972550 https://www.openstreetmap.org/way/453921712

![IMG_20201119_182354](https://user-images.githubusercontent.com/899988/99704455-b7ae9680-2a98-11eb-9d78-2f708905d116.jpg)

I do not feel that selecting "no lane markings" is correct here.

Or cases where there are turn lane markings (one set of arrows for each lane). Or traffic signs with turn lane info.

So I suggest to allow answering "1" after selecting that lanes are marked.

**Comment by Atrate** [comment]
This would hold especially true for the one-way one-lane access roads for motorways

**Comment by HolgerJeromin** [comment]
Yes. Oneway ways should have a special handling/explanation.
I have a similar line like your right lane. Does this have a marking? Feels ambiguous.

https://www.openstreetmap.org/way/58420927

**Comment by westnordost** [comment]
Okay, then why don't you select lane markings and then select "1"?

**Comment by matkoniecz** [comment]
I will need to recheck, but I am pretty sure that "1" is not available for marked lanes answers.

**Comment by westnordost** [comment]
It is for oneways

**Comment by HolgerJeromin** [comment]
Yes it is. But markings are between lanes. If we have "no between" what to answer?
Perhaps we need three buttons:
| marking | | no marking | only one lane |

**Comment by westnordost** [comment]
Sorry, I don't understand the problem.

**Comment by matkoniecz** [comment]
> It is for oneways

Now I feel dumb that I have not tried this. I used it multiple times and learned that for marked lanes available numbers start from 2.

**Comment by westnordost** [comment]
Btw would you mind checking the tagging mailing list?

**Comment by matkoniecz** [comment]
> Btw would you mind checking the tagging mailing list?

Replied on ml.
