### ISSUE TITLE
addr:housenumber nodes for interpolations misinterpreted as for specific buildings

### ISSUE THREAD

**Issue by jtracey** [westnordost/StreetComplete#2307]
SC has the feature of not asking for housenumbers on buildings that have a node already tagged with one geometrically inside them. This is a good thing, but has caused a problem in Canada (and potentially other countries). The Canadian government does not provide individual address data, but does provide address ranges on a ~per-block basis, which were long ago imported as [`addr:interpolation`s](https://wiki.openstreetmap.org/wiki/Addresses#Using_interpolation) adjacent to those streets. Independently of this, buildings have been added (either manually or separate imports as available), often times over the end nodes of the `addr:interpolation` ways. Because the address data was imported on a street-level precision, but buildings are mapped at a geographic precision, these buildings frequently don't actually have the address of the interpolation's `addr:housenumber` inside them. SC doesn't treat these address nodes any differently though, and therefore doesn't load the housenumber quest for them. I only recently discovered this problem, but based on my quick investigations, I'd estimate the address is wrong about half the time.

It's arguable that this is an error in the data that should be fixed, rather than accommodated. In fact, I tried running an overpass query in my area to identify such nodes and move them, but querying for nodes inside polygons is apparently a known shortcoming for overpass, and the query was too slow and missed too many nodes to be particularly useful at large scales. However, even of the results did that did populate, they were extremely common in the area queried. Given how pervasive the problem is here, how `addr:interpolation`s are supposed to be temporary anyway, and the following sentence from the wiki:

>If there is a house number on a single node or single building polygon and that house number also appears as the result of an interpolation, software should handle this case gracefully and favour the individually tagged house number as the real position. 

I'm going to propose that SC ignore `addr:housenumber` tags that are part of `addr:interpolation` ways. I.e., buildings with such nodes need another address regardless, and non-survey sources are empirically awful in this case, so might as well let SC provide it. If for some reason this is considered too severe, my next proposal would be to ignore housenumber nodes tagged with a source from any of the relevant imports (`source=StatCan 92-500-X` and `source=NRCan-CanVec-10.0` being some of the obvious ones, though there may be a few others; shouldn't be too hard to find if need be), or just restricting such behavior to Canada (and any other countries this turns out to be a common issue in).

**How to Reproduce**

Search for the housenumber quest in any neighborhood that has imported addresses from the Canadian government. [Here's an example building](https://www.openstreetmap.org/way/61698467) and [incorrect node](https://www.openstreetmap.org/node/4036640156) in a randomly selected Toronto neighborhood that would cause a failure in SC. The building was manually tagged by someone, and doesn't match the address of the interpolation node that happened to fall in it (or even the street, for that matter). You can pan around there a bit and find dozens of similar examples. [Here's another example](https://www.openstreetmap.org/node/2487395761) where the address is ambiguous, in a random small town on the other side of the country to show it's not localized (again, pan around there and you'll see plenty more).

**Versions affected**

Presumably all releases that detect `addr:housenumber` nodes in buildings.

**Comment by matkoniecz** [comment]
If `addr:housenumber` node is placed on building which does not have this housenumbers then this data is incorrect and wrong.

> I'm going to propose that SC ignore addr:housenumber tags that are part of addr:interpolation ways.

Note that it would break SC in areas with correctly tagged `addr:interpolation` ways where OSM data was not damaged by low quality imports. Such change would cause problem by asking not needed questions and tagging duplicate addresses.

(maybe decision to make this import was overall correct one, but it ended in adding incorrect data).

------

And overall it is better for SC to avoid asking some valid questions than to produce many false positives that would result in damaged data.

So I would say that root problem is that data already in OSM is simply incorrect.

**Comment by westnordost** [comment]
So you want STreetComplete to ignore `addr:interpolation`. Hmm yeah, I am with @matkoniecz here, it shouldn't be ignored only because the data is wrong in some places.

As a workaround for your area, I think the way it works currently is quite fine: Basically for all buildings except the ones on the corner, the address is asked. As soon as this information has been contributed, the address interpolation line can be deleted and the corner buildings then do not have any `addr:housenumber` anymore, thus the quest becomes available for StreetComplete users.
