### ISSUE TITLE
Do not zoom to somewhere-in-Italy at startup

### ISSUE THREAD

**Issue by W-T-Developer** [westnordost/StreetComplete#2311]
Sometimes StreetComplete zooms to a position somewhere in Italy after startup before it recognizes the current GPS-Position.
Suggestion1: Zoom to last position
Suggestion2: Display a wait-symbol instead of a map

Using version v26.2

**Comment by westnordost** [comment]
The app always zooms to the last position. The last position is saved when you exist the map activity. So, either if you end the app or if you for example go into the options and back.

**Comment by W-T-Developer** [comment]
OK, some screenshots of my test shttps://github.com/westnordostcenario:
0: GPS is active
1: map is in Hanover (Screenshot 1)
2: closing the app using regular app switcher
3: disabling GPS for reliability
4: start StreetComplete (it asks for GPS of course)
5: map is in Italy (screenshot 2)

![Screenshot_20201121-203525_StreetComplete](https://user-images.githubusercontent.com/74488957/99886039-c7191580-2c39-11eb-89ca-6d5f9db4a8bc.jpg)
![Screenshot_20201121-203547_StreetComplete](https://user-images.githubusercontent.com/74488957/99886069-ed3eb580-2c39-11eb-9af1-bb8e5e7215a8.jpg)

**Comment by westnordost** [comment]
Can't reproduce. If I zoom to a certain area, then close the app using the app switcher, start the app again, the map is zoomed to exactly where I left it.

**Comment by westnordost** [comment]
What if you go into the settings, then exit the app, then restart the app?

**Comment by W-T-Developer** [comment]
Same problem. Can I access the logs?
I checked two more devices, there it works.
My device data: (Samsung Tab S6 Lite)
![Screenshot_20201121-214839_Settings](https://user-images.githubusercontent.com/74488957/99887313-8d4d0c80-2c43-11eb-824a-e47d91460282.jpg)

**Comment by westnordost** [comment]
I also got a Samsung on Android 10. There are no relevant logs.

**Comment by mnalis** [comment]
@W-T-Developer just an idea: if you go to GPS system settings and disable the Google low-precision positioning (I don't know how it is called on Samsung there days, usually it is called something like "WiFi / bluetooth / mobile tower assisted" or "low precision location" or "improved location accuracy" or "Google location services" or similar), does the problem still persist? 

If so, it may be because wifi/mobile tower triangulation is being used even when GPS is turned off, and is misbehaving by "finding" wrong location.

**Comment by westnordost** [comment]
I created an issue upstream for that. If you have anything to add, best do it there: https://github.com/tangrams/tangram-es/issues/2249
