### ISSUE TITLE
Clustering quests with number indicator

### ISSUE THREAD

**Issue by W-T-Developer** [westnordost/StreetComplete#2312]
If you zoom out and quests are minimized or hidden, it is hard to determine if there are many or few problems in an area.
I suggest a clustering (split by type or not), that displays the number of minimized/hidden icons, as you can find on many websites around the world (like this https://www.entropywins.wtf/blog/wp-content/uploads/2016/05/clustering.jpg).

**Comment by westnordost** [comment]
This is technically not possible
