### ISSUE TITLE
Clarify "kind of building" quest (type vs. use)

### ISSUE THREAD

**Issue by mueslo** [westnordost/StreetComplete#2314]
To me, it is unclear whether in the "kind of building" quest, I am supposed to answer with the kind of building that it is, or the kind of building that it is used as. For example, an industrial building hall may now be used as a theater. Or maybe an old church is now used as a rock-climbing center. I assume I am supposed to answer the latter, but if I take the quest literally, I would fill in the former. 

Edit: After the helpful hints below, this summarises what I consider the problem:

The distinction between building *type* and building *use* is already tricky in the best of cases. A lot of the text strings muddy this distinction further, since they are not exact and imply *use* when they should be implying *type*, making it unclear what the quest is about.

**Comment by matkoniecz** [comment]
> Or maybe an old church is now used as a rock-climbing center.

Is it still a church building? So "church" is a correct answer.

For example following is apartment building used as a church, correct answer would be "apartments":

![800px-Church_of_Feast_of_the_Ascension_of_Jesus_Christ_(Old-Catholic_Church)_in_Cracow,_Poland](https://user-images.githubusercontent.com/899988/99900671-6af1d800-2cb1-11eb-94e0-9026de0cc0d0.jpg)

Following is a church building, repurposed into apartments, correct answer would be "church":

![Christ_Church_Flats,_Kew_Road_-_geograph org uk_-_219419](https://user-images.githubusercontent.com/899988/99900728-91b00e80-2cb1-11eb-9a52-0a3921c94f83.jpg)

----------

Note that it is question about current state, not about original purpose. For example industrial building deeply modified so that it is rather theater building than industrial building, may be more fittingly described as a theater.

**Comment by matkoniecz** [comment]
And note that if cases are less clear that ones shown and building is borderline, then either answer will be fine.

The same for `house` vs `apartments` and so on.

**Comment by matkoniecz** [comment]
@mueslo Have you tried to get answer within app, for example via "can't say" answer? Maybe putting some hint there, like for housenumber quest would be a good idea...

**Comment by mueslo** [comment]
"Can't say" just gives the option of leaving a note. "Show more" also doesn't help. Please also tag this is something else, other than question, since I think other people may have the same problems, and might tag things incorrectly! E.g. add a subtext/context. Currently it says: "What kind of building is this?" Maybe add as a subtext "(**not** the current use, but the original building type)"

**Comment by mueslo** [comment]
Okay, you say it is not about the "current state", not "original use". So it would be good to clarify what this means, or link to the OpenStreetMap wiki for details, since this distinction seems to be quite fuzzy.

**Comment by mueslo** [comment]
The options are also quite misleading. Take your example of a residential house converted to a church. StreetComplete gives the option: "Residential. Building were people live". But this doesn't apply, since it's used as a church. Maybe phrase it as something like "Building that is (intended) for people to live in"

**Comment by mueslo** [comment]
Another thing that is unclear, is e.g. what to tag buildings that are non-commercial research institutes as, that are not part of a university. University? Commercial? Office? Industrial? Government? Non of these really apply - it's non-commercial, not a civic building, and not a university. But looking at the OSM Wiki, this also seems unclear there, so this problem is an issue for there. I have previously tagged them as "University".

**Comment by matkoniecz** [comment]
> buildings that are non-commercial research institutes

Depends on specific buildings. Some will be offices, some will be industrial buildings, some will be garages and so on.

**Comment by mueslo** [comment]
@matkoniecz the problem is that "office" is given as a subcategory to "commercial" in StreetComplete, but it is definitely non-commercial, so I did not consider it at all.

**Comment by westnordost** [comment]
We had this topic already, this is a duplicate.

The answer remains the same: If in doubt, leave a note. This is especially true for buildings who were apparently constructed as someting else they are used now.

**Comment by mueslo** [comment]
@westnordost I disagree as I can't find any similar issue. As someone that is not deep in the exact tag structure of OSM, it is not obvious whether this is setting building:<type> tags or building:use:<use> / amenity:<use>.

**Comment by westnordost** [comment]
It is tagging `building`. When in doubt, people should leave a note instead and explain the situation / make a photo so that maybe both the building use and for what hte buildin was created can be tagged (by others / after discussion in the note). That's all I can say to that really.

That if you are in doubt, for any quest, you should leave a note is mentioned in the tutorial that is shown to every new user.

**Comment by mueslo** [comment]
> It is tagging building. 

Yes, I obviously know this now. However, it is not apparent from within the app. And even if you told that to someone on the street, they still wouldn't know what this would mean in this context, i.e. that you should tag original building type, not current building use.

> When in doubt, people should leave a note instead and explain the situation / make a photo so that maybe both the building use and for what hte buildin was created can be tagged (by others / after discussion in the note). That's all I can say to that really.

Sure, but why not just make it obvious in the App itself, so people don't have to come and ask? I really don't see what the issue with that is.

> That if you are in doubt, for any quest, you should leave a note is mentioned in the tutorial that is shown to every new user.

I've been using the app since the very first published versions, and I really don't remember the tutorial at this point. I agree for the research institute I should left a note.

**Comment by mueslo** [comment]
Form follows function. This is also true for buildings. If you ask "what kind of building is <x>", you are asking a hybrid question. If you asked this question to someone on the street, e.g. for the church-apartments, they would tell you, "well it's a church, *but* it houses apartments now", because the two concepts are intertwined. OSM splits these concepts apart. This needs to be made obvious.

**Comment by westnordost** [comment]
> However, it is not apparent from within the app.

That is deliberate. When in doubt, people should leave a note.

>  so fewer people have to come and ask

They should not come here to ask at all. They should leave a note, as explained by the tutorial.

> It needs to be made obvious which of these concepts is being asked.

As said, this is deliberate. In these cases people should leave a note.

**Comment by mueslo** [comment]
Ok, this is of course ultimately your design choice as the developer (i.e. simplicity/hiding context from the user, à la GNOME). However, I suspect that this may introduce subtle data mistakes that may be hard to find down the line. [The corresponding wiki page](https://wiki.openstreetmap.org/wiki/Key:building) directly leads with 

> The most basic use is building=yes, but the value may be used to classify the type of building. Note that it may be not the same as the building's current use (tagged using building:use=*).

which is context that is missing from the quest. At least this issue is here now for future people asking themselves the same question. Thank you for your work!
