### ISSUE TITLE
Translation clarification: "Pavement" vs. "Sidewalk" vs. "Footpath"

### ISSUE THREAD

**Issue by joshdm42** [westnordost/StreetComplete#2315]
The quest question "İs there a pavement along this street?" is unclear for North Americans. As a Canadian, I accidentally misreported several quests before realizing my error.

İn North American English, pavement refers not only to the part of the road where pedestrians walk, **but also the part where the cars drive.** (A "pavement" road would be contrasted to a "gravel" or dirt road, that is not paved).

The question could be clarified to "İs there a pavement/sidewalk/footpath along this street?", Which is bloated, but inclusive of European, North American, and Oceanian varieties of English. Or maybe an explanation/translation note could be added in the quest?

**Versions affected**

v26.2

**Comment by matkoniecz** [comment]
> "İs there a pavement/sidewalk/footpath along this street?", Which is bloated, but inclusive of European, North American, and Oceanian varieties of English. 

Which ones are unclear/confusing for a given language? Maybe "sidewalk" would be generally understandable?

-----

Note that there is a separate translation for UK English, allowing to override some language used in default US English (already used for example with "curb" vs "kerb").

Adding other English variants is also possible from what I see
![screen08](https://user-images.githubusercontent.com/899988/99901108-72ff4700-2cb4-11eb-8e8d-9a715615a0f8.png)

**Comment by joshdm42** [comment]
Upon closer inspection, I realized the actual problem. My device is set to Canadian English (en-CA). It appears to be that a device en-CA defaults to using the UK translation strings, where using en-US would probably be closer. (Canada and the United States both use _Sidewalk_ instead of _pavement_). When I switch my device to en-US, it displays "Does this street have a sidewalk?" which is much more natural to me as a Canadian.

So maybe the actual bug is that en-CA should default to en-US instead of en-GB? I don't think there's enough differences in this app to make it worth making a whole translation pack for en-CA... At least not yet

**Comment by matkoniecz** [comment]
Seems to be more general issue: see https://stackoverflow.com/questions/45511769/localization-for-canada-defaults-to-uk-should-default-to-us

To override this it may be necessary to ship en-CA translation, identical to default en-US to prevent en-UK from appearing in Canada.

**Comment by joshdm42** [comment]
Makes sense. That sounds like a good solution. Most differences between Canadian and American English are just spelling anyway (i.e. color vs. colour). If we wanted to make it an actual legit language pack, it wouldn't take much more than a quick search-replace script on common variants. But one identical to en-US sounds great as well

**Comment by matkoniecz** [comment]
So I enabled en-CA language version and copied strings with "sidewalk" in them from en-US

https://poeditor.com/projects/po_edit?order=&filter=ut&per_page=20&id=97843&id_language=199&search=sidewalk

I am not closing it as @westnordost needs to enable this translation in published versions. I expect that this will result in "sidewalk" appearing rather than "pavement" and other parts of interface continuing to use en-UK version.

It will be also possible to use https://github.com/westnordost/StreetComplete/blob/master/CONTRIBUTING.md#translating-the-app to override other terms as needed.

**Comment by matkoniecz** [comment]
For other terms I am unfamiliar whatever US or UK version is preferable, so I have not copied anything else.

For example if "curb" is used rather than "kerb" it also may be worth copying unchanged to prevent en-UK version from appearing.

**Comment by westnordost** [comment]
> To override this it may be necessary to ship en-CA translation, identical to default en-US to prevent en-UK from appearing in Canada.

To override this, it is necessary to copy the default strings to en

**Comment by westnordost** [comment]
Which I did now, I added a gradle task to do this automatically
