### ISSUE TITLE
Cycleway quest: First-time picture with resurvey text

### ISSUE THREAD

**Issue by cyclingcat** [westnordost/StreetComplete#2316]
Hi there,

today I came across a cycleway quest which originally looked like a _first-time quest_, however, the text above the quest was the one of a cycleway _resurvey quest_. It was the first time ever I noticed this behaviour (after having solved many, many cycleway quests), so it's probably the result of some rare combination of conditions.

See the following screenshot (it's OSM way 110888347):

![cycleway_quest](https://user-images.githubusercontent.com/32601012/99906489-bcad5900-2cd7-11eb-91de-2ee26ca5193c.png)

The suspect key could be **cycleway:both=shared_lane**. In order to further nail it down I created an [Overpass Turbo query](http://overpass-turbo.eu/s/10ru) which reveals some clusters where this obviously quite rare key/value combination is used. I checked some of these ways and with all of them SC shows the described behaviour which is somewhat confusing as the user stumbles upon the phrasing "still here" in connection with the question mark symbols on the picture.

(SC 26.2, Android 5.1/9.0)

The cycling cat

**Comment by westnordost** [comment]
See #2120
