### ISSUE TITLE
Quest: Drive Through Pharmacies

### ISSUE THREAD

**Issue by NotAFile** [westnordost/StreetComplete#2317]
### General
Rationale: Drive through pharmacies have become increasingly important during the current pandemic. However, they are currently rarely tagged correctly.

Affected tag(s) to be modified/added: [drive_through](https://wiki.openstreetmap.org/wiki/Key:drive_through), [amenity=pharmacy](https://wiki.openstreetmap.org/wiki/Tag:amenity%3Dpharmacy)
Question asked: **Is this a drive through pharmacy?**

### Checklist
Checklist for quest suggestions (see guidelines):
- [x] 🚧 To be added tag is established and has a useful purpose
- [x] 🤔 Any answer the user can give must have an equivalent tagging (Quest should not reappear to other users when solved by one)
- [x] 🐿️ Easily answerable by everyone from the outside but a survey is necessary 
- [x] 💤 Not an overwhelming percentage of elements have the same answer (No spam)
- [x] 🕓 Applies to a reasonable number of elements (Worth the effort)

### Ideas for implementation

**Element selection:** drive through pharmacies usually have a `highway=service` `service=parking_aisle` nearby. They are very often also tagged as `oneway=yes`.

I'm not very good with overpass, but here's an attempt at a query: https://overpass-turbo.eu/s/10s3

**Metadata needed:** Drive through pharmacies seem more common in the US than elsewhere, but overpass finds them in other countries too.

**Proposed GUI:** simple yes/no

**Comment by westnordost** [comment]
I fear this should not be added via StreetComplete. The reason is that it doesn't fit for the...

> 💤 No spam: It must be possible to determine whether the quest should reasonably be asked. A quest which is to be answered in 99% of the time with the same answer is not a good quest, don't bore the users. I.e. asking for any road if it is a one-way road, is silly, because the vast majority of all roads will not be one-ways.

...rule. 99% of all Pharmacies will not be drive through pharmacies. Even in the US, I'd venture.

You mention a solution for this, which is to look for `highway=service` and `service=parking_aisle` near (or through?) it, however, this seems a little much effort for such a rare thing to do.

> 🕓 Effort vs impact: Consider if it is worth the effort when compared to the impact the quest would have. For how many elements would this quest type apply? This point is especially valid if you don't plan to implement a quest suggestion yourself through a PR. A quest to determine the type of building applies to 200 million elements while i.e. a quest to determine what a vending machine is selling applies to less than 1000 elements.

Also, in regards to that it has a useful purpose, even in light of the pandemic I don't find it too convincing.  I saw signs at  "normal" pharmacies that said that you should please ring the bell or something if you have symptoms, so someone will take the necessary precautions when giving you your prescriptions.

**Comment by NotAFile** [comment]
> 99% of all Pharmacies will not be drive through pharmacies. Even in the US, I'd venture.

That's not true at all. Drive through incredibly is very popular in the suburban US due to the car-centric infrastructure.

For example, Walgreen's [press releases](https://news.walgreens.com/press-releases/general-news/walgreens-drive-thru-isnt-just-for-prescription-pick-up-anymore-as-company-expands-product-pick-up-offering-at-its-drive-thrus-nationwide.htm) mention "more than 7,300 pharmacy drive-thrus nationwide", of their total "9,277 stores in the United States" [according to wikipedia](https://en.wikipedia.org/wiki/Walgreens).

**Comment by Cj-Malone** [comment]
I think this could be a pretty good MapRoulette task. I might set one up in the UK for some fastfood chains.

**Comment by goldfndr** [comment]
Additionally, https://www.openstreetmap.org/way/477673957 doesn't appear to be tagged correctly (from aerial imagery) -- [service=parking_aisle](https://wiki.openstreetmap.org/wiki/Tag:service=parking_aisle) should pass between one or two rows of parking spaces; see [Disambiguation](https://wiki.openstreetmap.org/wiki/Tag:service%3Dparking_aisle#Disambiguation). Locally, I haven't seen a parking aisle close to a building; that (too close) also might be worthy of a MapRoulette task.
