### ISSUE TITLE
Is it OK to reorder values in IS_AREA_EXPR into alphabethic order? 

### ISSUE THREAD

**Issue by matkoniecz** [westnordost/StreetComplete#2319]
https://github.com/westnordost/StreetComplete/blob/master/app/src/main/java/de/westnordost/streetcomplete/ktx/Element.kt#L27

It would make comparing them with other such lists (such as JOSM) easier.

https://josm.openstreetmap.de/ticket/20147 is related: "add more tags to hasAreaTags (synchronize with StreetComplete) "

**Comment by matkoniecz** [comment]
Asking as I am not sure is there some order/logic behind current order.

**Comment by westnordost** [comment]
It's ok. The effect it will have is that whenever the statement is executed, the tags at the start will be checked first
