### ISSUE TITLE
Tactile pavings at bus stops and crosswalks in Italy

### ISSUE THREAD

**Issue by fabiobettani** [westnordost/StreetComplete#2320]
Hi there,

I live in Bologna, Italy. In my town, several bus stops and several crosswalks have been renovated in the last years, with the introduction of tactile pavings.

StreetComplete already has two separate quests about the existence of tactile pavings on crosswalks and bus stops, but these quests are currently disabled in Italy, as well as in a handful of other countries.[1][2]

However, I can't see why this is disabled in Italy, and the Java file actually refers to a completely unrelated discussion on the talk-it list about street addresses.[3]

Could these quests be activated in Italy as well? Or is there another reason why they have been disabled? ;-)

Thankls,

[1] https://wiki.openstreetmap.org/wiki/StreetComplete/Quests
[2] https://ent8r.github.io/blacklistr/?java=tactile_paving/AddTactilePavingCrosswalk.java
[3] https://lists.openstreetmap.org/pipermail/talk-it/2018-July/063712.html

**Comment by matkoniecz** [comment]
Ad [1] - not sure where it is linked but this overwiev is outdated.

Right now it is controlled by https://github.com/westnordost/StreetComplete/blob/master/app/src/main/java/de/westnordost/streetcomplete/quests/tactile_paving/TactilePavingUtil.kt - there is list of countries where tactile paving is common.

Italy right now is not listed there.

Not that it is `COUNTRIES_WHERE_TACTILE_PAVING_IS_COMMON` - so the question is not "is tactile paving present anywhere in Italy at all", but - it is common that this question would make sense to ask?

**Comment by matkoniecz** [comment]
So, the question is: is tactile paving in Italy sufficiently popular that this question would make sense to ask?

From new quest guidelines:

> 💤 No spam: It must be possible to determine whether the quest should reasonably be asked. A quest which is to be answered in 99% of the time with the same answer is not a good quest, don't bore the users. I.e. asking for any road if it is a one-way road, is silly, because the vast majority of all roads will not be one-ways.

https://github.com/westnordost/StreetComplete/wiki/Adding-new-Quests-to-StreetComplete

**Comment by fabiobettani** [comment]
Thanks Mateusz, both for clarifying and for updating the wiki. The picture is far clearer now!

As far as bus stops are concerned, tactile pavings have got quite common now in Italy, at least in the main cities. I live in Bologna, and in the city centre a majority of bus stops is now provided with tactile paving, as well as a good amount outside the city centre as well. In my experience, other cities - at least in the north of the country - have a similar situation.

As for crosswalks, the matter is more debatable. In Bologna, most new crosswalks are built with a tactile paving; but, unlike bus stops, there is no plan to actively renovate crosswalks just to make them more accessible - tactile pavings are only added when the whole crosswalk is renovated for other reasons, which doesn't happen as often. So the overall percentage might be rising quite slowly. Also, smaller towns might lag a bit behind on this.

I would support the new quest for bus stops, and be in doubt about crosswalks. Probably useful for urban mappers, less useful in the countryside. Is this similar to other countries already in the list? (https://github.com/westnordost/StreetComplete/blob/master/app/src/main/java/de/westnordost/streetcomplete/quests/tactile_paving/TactilePavingUtil.kt)

**Comment by westnordost** [comment]
As far as I remember, only those countries are on this list where both can reasonably be expected that there might be tactile paving.

**Comment by westnordost** [comment]
Looking at the overpass map, the cases where tactile_paving is yes is scattered enough that it doesn't seem to be a local phenomen. So at least there is *some* of it in Italy and I think this is enough. We can be less cautious with asking for things if they are quite rare in certain countries now as they are asked again periodically.

![Uploading image.png…]()
