### ISSUE TITLE
Dealing with already tagged lanes:backward / lanes:forward

### ISSUE THREAD

**Issue by matkoniecz** [westnordost/StreetComplete#2321]
Does it make sense to ask lanes quest if both `lanes:backward` and `lanes:forward` is tagged?

I see special support for handling it if tagged already ( https://github.com/westnordost/StreetComplete/blob/master/app/src/main/java/de/westnordost/streetcomplete/quests/lanes/AddLanes.kt#L52 ) so maybe asking on `lanes:backward=1` `lanes:forward=2` is intentional, but it seems to be pointless.

**Comment by Atrate** [comment]
Does this code actually not cause bad data to be written?
```
} else {
                    changes.modifyIfExists("lanes:forward", (answer.count / 2).toString())
                    changes.modifyIfExists("lanes:backward", (answer.count / 2).toString())
                }
```
If there's 1 backward lane and 3 forward ones tagged, wouldn't SC then change it to 2 and 2, wrongly?

**Comment by matkoniecz** [comment]
> If there's 1 backward lane and 3 forward ones tagged

If user answered correctly then https://github.com/westnordost/StreetComplete/blob/master/app/src/main/java/de/westnordost/streetcomplete/quests/lanes/AddLanes.kt#L63 should be executed

**Comment by westnordost** [comment]
95.35% of all ways tagged with `lanes:forward` has `lanes` as well. The wiki says that `lanes:forward` etc. can be tagged additionally to `lanes`. So I think it can't hurt, it will not produce much "duplicate" data and some data consumers might only check the `lanes` key.

**Comment by matkoniecz** [comment]
My main worry was that SC surveyors may be a bit more confused/less careful than someone tagging `lanes:forward`/`lanes:backward`, but with 95.35%...

**Comment by westnordost** [comment]
Maybe interesting would be to extend the quest to also ask for places where
`lanes != lanes:forward + lanes:backward + lanes:both_ways`
Not sure how many of these there are
