### ISSUE TITLE
Lanes: allow selecting odd numbers for marked lanes

### ISSUE THREAD

**Issue by Atrate** [westnordost/StreetComplete#2322]
Is there a specific reason why marked lanes on two-way roads can only be even? I get 1 not being an option, but I frequently see roads like 2 forward 3 backward or 1:2.

Relevant code:

https://github.com/westnordost/StreetComplete/blob/d3085e8bfcdf33348c549c50c821c240319d993e/app/src/main/java/de/westnordost/streetcomplete/quests/lanes/AddLanesForm.kt#L259

**Comment by HolgerJeromin** [comment]
In the "more options" menu you have "different for each direction".

**Comment by westnordost** [comment]
Hmpf, why is the distance to tap the "Other answers..." button apparently sometimes longer than going to github and posting an issue?

**Comment by peternewman** [comment]
FWIW I hadn't looked/thought to look in there for this type of answer.

**Comment by smichel17** [comment]
Same. The normal flow of answering a quest is to do it through the form, and that menu is in line with the submission options, so despite the label, it's not very intuitive to look in there for more options that will actually complete the quest.

I would suggest moving all actual options out of that menu, for all quests, and then re-naming it to "Can't say…". It should always contain the options, "Hide this quest" and "Leave a note instead" (which should hopefully make it more obvious that this feature exists). Maybe also "I need clarification" or something like that, which could link to the wiki or something like that to explain the details of how the tags are used. Things like, "It has multiple uses" in the building type quest, where it is just giving you more information, could stay in this menu, but not things like "It has no name" in the road name quest; the dividing line is whether the answer will change tags on the element or not.

I planned to propose this in a new issue a couple days ago, but am very busy for at least the next couple days still.

**Comment by peternewman** [comment]
See also #2104 about whether something is lit 24/7

> the dividing line is whether the answer will change tags on the element or not.

If you wanted a slightly looser dividing line, I think it could also be drawn if it was a negative answer. The issue with this being hidden in that menu and likewise for lit 24/7 is that it's just another answer, I just can't find the answer on the form, or don't know another choice exists. It has lanes, but in what appears to be a bug only even numbers have been offered, or worse still with lit, as the answer yes also encompasses 24/7.

In comparison "It has no name" doesn't feel as bad to me, I can't answer the originally posed question "What is the name of this street?" so I then go looking in menus. Likewise differs along the way, I can't answer if something is concrete and tarmac at the same time so I end up in the menu.

**Comment by smichel17** [comment]
That could be done, but the other half of the reason was making the "leave a note" option more obvious and fewer taps. Which was actually my original/primary motivation. It came up in another issue about it a week or two ago. Don't yet have time to look for it.
