### ISSUE TITLE
Too many lane quests with the same answer!

### ISSUE THREAD

**Issue by cyclingcat** [westnordost/StreetComplete#2324]
Hi there,

yes, I copied and pasted the subject of issue #2251, but the situation here is very similar: Since the intruduction of the lane quest in SC v27.0 the map gets flooded with these quests in residential areas! Almost every quest there has to answered with "No lanes". I checked some villages nearby and as I had expected the situation was the same: >95% of the streets don't have any lane markings, the only exceptions being some primary/secondary/tertiary roads leading through the villages. Even dead end streets are asked for lanes. This violates the "no 💤" criterion for new quests. The typical map looks like this one:

![road_lanes](https://user-images.githubusercontent.com/32601012/100524190-5da78280-31b6-11eb-8e04-f2f366cb49de.png)

(I don't know if marked lanes on residential streets are common in other countries though.)

**Possible solutions:**

- Don't ask for road lanes for ways tagged with "highway=residential" at all (maybe dependent on the country)
- Maybe the idea by @DerDings in https://github.com/westnordost/StreetComplete/issues/2251#issuecomment-723866344 would be an option here as well (=use the maxspeed tag as a criterion to filter out the streets with a chance of nearly 100% of having no lane markings)?

The cycling cat

**Comment by westnordost** [comment]
I don't know about that. Maybe it is the case in your town, but everywhere?

**Comment by DerDings** [comment]
> - Maybe the idea by @DerDings in https://github.com/westnordost/StreetComplete/issues/2251#issuecomment-723866344 would be an option here as well (=use the maxspeed tag as a criterion to filter out the streets with a chance of nearly 100% of having no lane markings)?
> 
> The cycling cat

This is partially true in Germany. Here, traffic authorities are not even allowed to draw lane markings inside a DE:zone30 / DE:zone20. (or the other way round: lane markings should be removed before „30-Zone“ traffic signs are mounted.)
This only affects zones, not roads where the speed limit is indicated by a sign.

Also, there are often lane markings between a crossing and the zone sign, if the crossing is not ruled "left yields to right". I have come around a lot of those places today where I split up the road then ![_20201128_205536.jpg](https://user-images.githubusercontent.com/42044179/100524921-7dda4000-31bc-11eb-8b20-2b0674e18973.jpg)

lane markings are also common in front of traffic islands. While this is not possible in german DE:zone30, it may be possible in many other countries. ![_20201128_210841.JPG](https://user-images.githubusercontent.com/42044179/100525071-ed9cfa80-31bd-11eb-9f19-e6f2c216e96f.JPG)

I'd propose showing this quest for smaller streets at least if one of those properties in given:
- `maxspeed>30`
- a node `crossing:island=yes`, `highway=stop`, `highway=give_way` or `highway=traffic_signals` is within 30 meters of the way

Additionally, if not too complicated to implement, if one of the end nodes of a road is connected to another road which has lane markings, this one may also be included.

**Comment by DerDings** [comment]
> - a node `crossing:island=yes`, `highway=stop`, `highway=give_way` or `highway=traffic_signals` is within 30 meters of the way
> 


even better but also more complicated:
a node `crossing:island=yes`, `highway=stop`, `highway=give_way` or `highway=traffic_signals` is _part_ oft the way or within 30 meters of an _end node_ of the way.

**Comment by cyclingcat** [comment]
My example is probably an extreme one, because I have solved almost every other street-related quest inside some villages nearby, so the new lane quest is the only one remaining. However, if I move the lane quest in the settings to a higher position, I'm easily able to find villages with a similar density of these quests (tested in several rural regions of Germany). Furthermore, the main issue "the very most answers would be the same" remains, whether or not there are quest of other types.

The cycling cat

**Comment by DerDings** [comment]
I found a situation showing a signposted intersection with surrounding lane markings. In this case, there even is an overlap between the place of the DE:zone30 sign and the end of the lane markings.
![Screenshot_20201129-092241.jpg](https://user-images.githubusercontent.com/42044179/100537125-13f68080-3226-11eb-89a6-14c63a34fa8b.jpg)

Eastward of this intersection, there are indeed some residential roads with no lane markings inside a DE:zone30, with no traffic signals and no stop signs.

Speaking for Germany only, it would probably be enough to look for `highway=traffic_signals` or `highway=stop`, but in other countries this may be different, so I included `highway=give_way` to this list, too.


However, I have come across a lot of residential roads without lane markings in my area, but not that much that I would consider this too spammy.

**Comment by cyclingcat** [comment]
> However, I have come across a lot of residential roads without lane markings in my area, but not that much that I would consider this too spammy.

So this means there is a significant number of residential streets in your area with lane markings? Are those streets in one way or another speed-limited (besides the 50 km/h default)? This could mean that the situation possibly varies in different regions of Germany (or even municipalities?), making it more difficult to distinguish between "spammy regions" and "non-spammy regions".

During the next days I will do some specific research in my own neighbourhood (= smaller and larger villages, outskirts of a middle-sized town, residential areas in the town centre, a different and much smaller town and so on). Ride/walk into various districts, led by the lane quests and so on.

The cycling cat

**Comment by DerDings** [comment]
> > However, I have come across a lot of residential roads without lane markings in my area, but not that much that I would consider this too spammy.
> 
> So this means there is a significant number of residential streets in your area with lane markings? Are those streets in one way or another speed-limited (besides the 50 km/h default)? This could mean that the situation possibly varies in different regions of Germany (or even municipalities?), making it more difficult to distinguish between "spammy regions" and "non-spammy regions".
> 
> During the next days I will do some specific research in my own neighbourhood (= smaller and larger villages, outskirts of a middle-sized town, residential areas in the town centre, a different and much smaller town and so on). Ride/walk into various districts, led by the lane quests and so on.
> 
> The cycling cat


Residential roads with lane markings were indeed limited to the ones running into a larger road, under said circumstances of a given stop sign or traffic signals. But due to a close-meshed network of classified roads, many of the residential roads meet a classified road somewhere in their course.

So the advanced filtering I suggested would work perfectly as long as stop signs and traffic signals are mapped. It still doesn't seem necessary to me because where I tried it would only reduce the amount of residential road quest for about a half. The non-residential roads wouldn't (and shouldn't) be filtered like this anyway, because they often have lane markings. So I don't know if it is worth the effort only to reduce the number of quests by far less than a half. 


My suggested kind of filtering would work everywhere I am familiar with traffic rules, but that is only central Europe. So it needs to be checked if this filtering also is useful in other parts of the world. That what I mean by the effort needed to implement this.

**Comment by westnordost** [comment]
A remark here: The whole lane count quest can be considered as spammy in the sense that there will likely be no big surprises: Anything till tertiary/secondary will likely have 2 lanes, primary and trunk may have 2-6 lanes. 

Many questions will likely not yield surprises, such as asphalt as street surface, type of buildings in residential area etc.

As with other data,  the data is collected to find the exceptions to the expectation. 

Furthermore, one important data point that we'd want to gather are which roads are exceptionally narrow as this data point is not well recorded yet in OSM. In other words,  we want to identify roads that are likely narrow enough that it is worth the (users) time to let them record the width. Determining first which roads have lane markings first may be an end to this means.

**Comment by RubenKelevra** [comment]
@westnordost I agree, we have multiple quests which are similar, like the mentioned as well as speed - many cities are 50 kph from one end to the other on most streets. 30 zones are pretty new here, and placed only in some residential areas. 

The idea is to map this detail everywhere to no longer have to rely on "assumptions".

If you have an area which is 100% equal in this data StreetComplete might not be the right tool for the job. There are other editors which can more efficiently tag a large number of roads.

**Comment by HolgerJeromin** [comment]
> Anything till tertiary/secondary will likely have 2 lanes,

Excluding crossing area with turn lanes

**Comment by HaasJona** [comment]
I think it would make sense to exclude residential roads in 30 zones in Germany from this quest. As @DerDings wrote, lane markings in such roads aren't really legally possible and the few exceptions probably don't warrant all the spam.

Not that I really mind this quest, it's quite easy to answer and the data is probably very useful.

**Comment by DerDings** [comment]
> I think it would make sense to exclude residential roads in 30 zones in Germany from this quest. As @DerDings wrote, lane markings in such roads aren't really legally possible and the few exceptions probably don't warrant all the spam.
> 


I think exceptions are not _that_ unusual. Lane markings often end where the 30-Zone sign is placed, while the tag DE:zone30 is used for the whole way until the crossing node.

So in case such filtering is wanted, I think it should be specific enough to also find those exceptions.

**Comment by HaasJona** [comment]
Do we really want to split the ways at each crossing just to tag a few meters of line markings? This level of detail is kinda impractical for most regions I'm aware of.

**Comment by RubenKelevra** [comment]
> Do we really want to split the ways at each crossing just to tag a few meters of line markings? This level of detail is kinda impractical for most regions I'm aware of.

Well we actually do this already to tag the turn lanes, so in many areas where they are already tagged the ways are split and won't show up for this quest anyway. 

Turn lanes are important for routing and should be mapped.

**Comment by HaasJona** [comment]
> Turn lanes are important for routing and should be mapped.

For bigger roads, yes, but not the typical one or two lane residential roads I'm talking about. Here you may have some marking at a crossing with a larger street, but the small street in most cases won't have turnlanes themselves or in the rare case, where they exist, they will be trivial (keep left to turn left, keep right to drive straight or turn right).

**Comment by cyclingcat** [comment]
After having cycled many kilometers through town outskirts and some villages during the past days I have yet to find the first residential street with lane markings! But there are still some locations where I want to go, because I know that there are residential streets without a speed limit lower than the default of 50 km/h and which could have those markings. They seem to be rare here indeed. (The current weather conditions makes cycling somewhat uncomfortable though and it's impossible to look out for lane markings on snowy streets...)

There will always be exceptions, hence the fundamental question is: "Should the user get 100 (or 200 or 500) quests in order to find one exception?" In this case the "No spam" directive would have to be dropped. But perhaps there are cases where this would be justified, then the pros (finding those exceptions) and cons (users may be getting bored and finally disable the quest) had to be weighed.

At least here in Germany, omitting the quest for `"highway=residential" and ("maxspeed<50" or "maxspeed:type=DE:zone30")` (or similar, don't know if this is valid syntax) would mitigate the problem a lot IMHO. This may vary for other countries though, so a more conservative solution would be indeed to remove this quest for `"highway=residential"` generally, understanding that in (hopefully rare) cases it wouldn't be possibly anymore to set this tag for some ways with SC. More sophisticated country-dependent queries could be added in the future.

BTW: The surface quest for residential streets is nowhere near as spammy as the lane (and cycleway) quest! It's not always asphalt but paving stones, cobblestones, occasionally compacted or fine gravel. The same is valid for the building type quests: Surprisingly many residential areas are mixed with detached, semi-detached, appartment houses and other objects like garages or halls.

The cycling cat

**Comment by mnalis** [comment]
@cyclingcat 
> After having cycled many kilometres through town outskirts and some villages during the past days I have yet to find the first residential street with lane markings

I guess it depends on the country. Over here (Croatia) many residential roads have lane markings (1+1 in vast majority of cases), for example:

https://www.mapillary.com/app/?lat=45.80118081199984&lng=15.925851283264137&z=16.345314240132865&pKey=nkYAlAX1TKF1Napi5jXVtg&focus=photo&x=0.4862434467201505&y=0.6733344203363552&zoom=0

https://www.mapillary.com/app/?lat=45.79309585&lng=15.91820374&z=17&pKey=N-7g3fSH1ElZPzMpKnRZcQ&focus=photo&mapStyle=OpenStreetMap&x=0.48453323266346215&y=0.6793170494229206&zoom=0

https://www.mapillary.com/app/?lat=45.80089223&lng=15.89515023&z=17&pKey=e_aoMGIu6T46EJ2l-XAlrA&focus=photo&mapStyle=OpenStreetMap&x=0.5120643621101105&y=0.5964756105901219&zoom=0

**Comment by cyclingcat** [comment]
Yes, I expected this to be heavily country-dependent and I'm sure that there are regions in the world where other situations (and regulations) exist concerning lane markings. My intention to create this ticket was to prevent spamming after I observed the flood of lane quests in villages - I didn't know that it's even disallowed in Germany to mark lanes in zone 30 streets. Good to read that this quest still shows reasonable behaviour in Croatia after the change, but how to collect this information for the >200 countries in the world?

(Still haven't found a residential street with markings here, but another specialty at some locations: Tertiary and even secondary roads inside of villages with lane markings only in the curves. Arghh!)

The cycling cat
