### ISSUE TITLE
Water tower missing from building types

### ISSUE THREAD

**Issue by xaviermarchegay** [westnordost/StreetComplete#2325]
I have a quest relative to a water tower near my apartment and I cannot seem to find it in the list of possible building types.
I guess that it is technically a "Storage Tank" but on the OSM website there are two types :
* https://wiki.openstreetmap.org/wiki/Tag:man_made%3Dstorage_tank
* https://wiki.openstreetmap.org/wiki/Tag:man_made%3Dwater_tower

I also see the storage tank mentioned in the code [here](https://github.com/westnordost/StreetComplete/blob/master/app/src/main/java/de/westnordost/streetcomplete/quests/building_type/BuildingTypes.kt) but not the water tower.

**How to Reproduce**

Click on any quest relative to a building and try to find the water tower

**Versions affected**
Android 10 / StreetComplete v27.0 / French version

**Comment by matkoniecz** [comment]
If it is a water tower then it is not fully tagged.

In cases of such situations it may be necessary to leave note, no quest is able to cover every possible answer.

**Comment by westnordost** [comment]
In the case that a specific building type is not available in the list, you can always answer "can't say"
