### ISSUE TITLE
Don't dispense leaf_type quests during winter

### ISSUE THREAD

**Issue by nagisa** [westnordost/StreetComplete#2326]
In areas where broadleaved trees shed their foliage during winter, giving leaf_type quests in winter/late autumn/early spring runs risk of gathering wrong information. In a mixed forest people will be incentivized to answer with `leaf_type=needleleaved` during winter, but the forest being `leaf_type=mixed` is only apparent during summer/late spring.

**How to Reproduce**

Solve a `leaf_type` quest during a winter, in a location where seasons are apparent and broad leaved trees shed their foliage for the season. 

**Versions affected**

26.2

**Comment by westnordost** [comment]
The foliage doesn't vanish into thin air though but lies on the ground. You do have a point though, but I'd deem the effort too high for a feature to conditionally when the time of year + climate zone + season is right or wrong blend out this quest.

**Comment by nagisa** [comment]
> I'd deem the effort too high

Fair.

>The foliage doesn't vanish into thin air though but lies on the ground.

It has been snowing in my area over past few days, which has hidden anything previously on the ground under a lovely layer of snow. I realized, as I was clicking "needleleaved", that I had no idea if there are sufficiently many broadleaved trees around to make it qualify for a mixed evaluation instead. That's how this issue came to be in the first place.

I'll just disable this quest type during winter locally for now.
