### ISSUE TITLE
Lanes quest appears for streets with lane_markings=no

### ISSUE THREAD

**Issue by tapetis** [westnordost/StreetComplete#2328]
As shown in the code below, the lanes quest does not check whether ```lane_markings=no``` is already set on ways. Thus, the quest erroneously appears for streets already marked like this. This is also a problem, because if you answer the quest with "No marked lanes" only this key is added to ways.

https://github.com/westnordost/StreetComplete/blob/328144765a787f889b2507ed373fed03fad59e7d/app/src/main/java/de/westnordost/streetcomplete/quests/lanes/AddLanes.kt#L10-L15

**Versions affected**
StreetComplete v27.0

**Comment by westnordost** [comment]
Oh my god, you are right, what a blunder!
