### ISSUE TITLE
Open map on specified position

### ISSUE THREAD

**Issue by rmikke** [westnordost/StreetComplete#233]
Is there a posiibility that StreetComplete might be open from another app at specific position and zoom?

I mean this is something that should be easy to implement and allow other apps' authors add an option to correct something in a place they are looking at in their app just by launching StreetComplete from their app at their app's position (which does not have to be the current position of the device) and maybe specified zoom.

**Comment by HolgerJeromin** [comment]
This is the same as my  #190

**Comment by westnordost** [comment]
Also, the app is not intended to be used to edit data not in your vicinity.

**Comment by rmikke** [comment]
First, #190 seems to be basically the other way round - open an editor from from StreetComplete to edit features not covered by StreetComplete. Which is also a good idea, by the way, if someone knows how to edit the map.

But I see StreetComplete as a tool to get good data from people who are NOT map editors and this is where the power of the app is. People who don't know how to edit the map and don't really want to learn (and there is a plenty of them) can provide useful data for OSM. This is why I think it should be possible to call StreetComplete from other apps. This also why I think we should make StreetComplete as popular as we can.

Second, why limit people to the place where they are? 
Of course it's good that the app tries to show user's vicinity, but I have already used it for places that I know well even when not being there.

**Comment by westnordost** [comment]
#190 includes "open SC from another app"
