### ISSUE TITLE
Quest Ideas

### ISSUE THREAD

**Issue by NoNamePro0** [westnordost/StreetComplete#2331]
These Quests are just Ideas. Feel free to create a Issue that uses my Idea.

- [ ] _Which Opening Hours have ... at the corona pandemic?_ 
- [ ] _How many stars have this hotel/restaurant?_
- [ ]_Which material have this wall?_ 
- [ ] _Is smoking here allowed?_
- [ ] _Are dogs here allowed?_

**Comment by matkoniecz** [comment]
When you create a new issue you have option to properly propose a new quest (" Suggest a new question to ask the user about") that leads to form that you can fill with required info.

And some of that were discussed already and have their own issues, see #2270 #539 etc.
