### ISSUE TITLE
Clarify opening_hours quest

### ISSUE THREAD

**Issue by Vascom** [westnordost/StreetComplete#2332]
**Use case**
Please add clarification to use Public Holidays in opening_hours quest.
At this moment it is not clear need to set PH or not if it is not specified for POI.

**Proposed Solution**
Add description for PH setting.

**Comment by matkoniecz** [comment]
It seems pretty clear - what would you set for PH if this info is not specified?

**Comment by Vascom** [comment]
If this info not specified I would add PH because I think that opening hours at public holidays not differ from other days. But it is wrong and I must not add PH at this case.
Fir example:
![Screenshot_2020-12-01-13-11-19-585_de westnordost streetcomplete](https://user-images.githubusercontent.com/550017/100727024-c2d9be80-33d6-11eb-8b06-4a6df47e26f8.jpg)
It seems that I must add all variants if opening hours not differ in all days. So I want to view warning about using PH mark.

**Comment by westnordost** [comment]
You just ought to select whatever you see on the opening hours sign. As with anything in STreetComplete, you answer what you see.

If you see that the sign mentions "on public holidays, 10-12", you add that information. If you don't see anything mentioned, then also don't make anything up.

**Comment by Vascom** [comment]
I know it now but didn't know it a week ago and made a lot of wrong edits because of it. May be not only I am.

**Comment by Vascom** [comment]
> You just ought to select whatever you see on the opening hours sign. As with anything in STreetComplete, you answer what you see.

Yes, I see that shop work at all days including holidays so I enable PH. Thats what I see.
