### ISSUE TITLE
Construction highway updates

### ISSUE THREAD

**Issue by boothym** [westnordost/StreetComplete#2333]
Couple of questions about roads under construction.

https://www.openstreetmap.org/way/835148017 - this was highway=construction and it was presumably marked as open in StreetComplete. But it was changed to highway=road rather than a proper highway type - shouldn't the user be asked about this?

If it was also tagged construction=residential, would it that be used to set the highway type?

Also, in the same changeset - this way had a check_date added: https://www.openstreetmap.org/way/802611794 However the date was 6th July 2020 - why is that, as I would've expected it to be 30th November?

**Comment by matkoniecz** [comment]
> Yes, it would. Asking the user about a classification for some road is too much to ask at this point and location because he may be lacking the OSM experience to know what road should be classified as what and he is missing the context to make the right decision about classification when he is in the field and not have the big picture. In short: It would lead to low(er) quality of that data.

I am pretty experienced mapper and I would be unable to answer that question in StreetComplete for all cases, I would need to check how other nearby roads are tagged.

**Comment by boothym** [comment]
Thanks for the reply. Useful to know about the construction=* values.

You're right, asking users wouldn't be the best idea. 

But the only reason I noticed this issue was because I searched for highway=road in overpass turbo (something I occasionally do). Perhaps this would be a situation where an OSM note could be created? That would more likely be noticed by other mappers, either on the map itself or in RSS feeds.

>I am not entirely sure about the check date of the 6th July 2020. My guess is that he actually did answer that thing on the 6th of July but only uploaded his answer now.

Perhaps in this case StreetComplete can compare any check_date tags it is about to upload with the current date, and if the gap is too large then maybe ask the user again if these things are correct? In this case a construction site is unlikely to have opened and closed again in 6 months, but there could be other places like POIs, cafes, shops etc. which have changed since the check_date?

**Comment by westnordost** [comment]
> Perhaps in this case StreetComplete can compare any check_date tags it is about to upload with the current date, and if the gap is too large then maybe ask the user again if these things are correct?

That would be quite some effort. I'll not implement that. Note that if the element has been changed incompatibly in the meantime, the old answer given with StreetComplete  will not be applied but dropped.
So if someone else visited that place in the meantime (and f.e. set a newer check date), that answer from July wouldn't have been applied. I think it is okay behavior. Better data outdated by 6 months than data outdated by even more.

**Comment by matkoniecz** [comment]
> Perhaps this would be a situation where an OSM note could be created?

Generally, it is not accepted to create OSM notes automatically.

For finding such issues JOSM validator is great, Osmose may be also ( http://osmose.openstreetmap.fr/en/map/ )

**Comment by boothym** [comment]
Who said anything about an automatic OSM note? I would hardly say it's automatic if they are created when a StreetComplete user says a road is now open and there is no construction=* tag so the highway type is unknown.

StreetComplete already opens OSM notes when there is something that needs other mappers to fix outside of the app. The same user in the OP had a note created to say a bus stop is gone, do you not think that is a good idea? https://www.openstreetmap.org/note/2449246

An OSM note would be lot better than a road tagged highway=road for months because nobody noticed it.

And yes I know about Osmose. Not sure why you mentioned the JOSM validator would of course require me to open JOSM...

**Comment by HolgerJeromin** [comment]
> if the gap is too large then maybe ask the user again if these things are correct?

Here we have a new user who has finally found a way to connect a new app with osm. 🍾
You do not want to ask him what he have seen 6 month a go.
Even as an experienced mapper I am often having a hard time remembering details of a note I opened a few month ago.

And we are are also talking about quests like "what surface does this street have?". You wont get a good answer on that.
