### ISSUE TITLE
Worldwide ranking doesn't update

### ISSUE THREAD

**Issue by rhhsm** [westnordost/StreetComplete#2334]
I noticed that my worldwide rank in my profile hasn't changed in the last couple of weeks. Did it stop updating?

**Comment by matkoniecz** [comment]
It is also possible that it simply stayed the same. Is "days active" and "achievement levels" still updating?

**Comment by rhhsm** [comment]
Of course my rise was faster in the beginning just after I joined. Is the ranking list visible somewhere? I've been # 43 for about a month now.

**Comment by westnordost** [comment]
I found some issues with the rank generation. What rank are you now?

**Comment by westnordost** [comment]
FYI, currently:
- Ranks 1-20 are each about 1000 ⭐s apart.
- Ranks 21-30 are each about 500 ⭐s apart.
- Ranks 31-80 are each about 100 ⭐s apart.

**Comment by rhhsm** [comment]
In the app, I've been no. 43 for about a month, and have done several surveys with 100+ ⭐s each in that month.

**Comment by westnordost** [comment]
So you are still rank 43? What's your username/user id?

**Comment by rhhsm** [comment]
rhhsmits, 18303 ⭐s

**Comment by westnordost** [comment]
You are now rank 23 in the database. It could be that it is only updated after you solved and uploaded another quest and restarted the app.

**Comment by rhhsm** [comment]
I've been using the app almost every day, solving and uploading hundreds of quests and also updated the app. However just now I restarted my phone, and it shows me as no 23.

**Comment by goldfndr** [comment]
I'd been at 2389 worldwide for at least two weeks, and was going to comment about 5 hours ago (got distracted), but it's suddenly updated now to 1468. Thanks. My ranking in the US (151 for the same time period) is no longer visible.

**Comment by rhhsm** [comment]
> My ranking in the US (151 for the same time period) is no longer visible.

My national ranking is gone too.

**Comment by westnordost** [comment]
IIRC the national rank is only shown if you are amongst the top X (which mihgt be 150 or so)

**Comment by rhhsm** [comment]
There are very few SC users in Bulgaria, so I've been no 1 from almost the day I started using it. Since the worldwide rank updated, my national rank doesn't show any more (the dark grey circle is absent).

**Comment by matkoniecz** [comment]
My national rank disappeared what I noticed about 4 days ago (after @goldfndr comment), now it is back.
