### ISSUE TITLE
Lanes differs for each side add question marks

### ISSUE THREAD

**Issue by peternewman** [westnordost/StreetComplete#2337]
**Use case**
When you go into the lanes "differs for each side" on going to write this I've seen it briefly flashes left and right a slightly different shade of grey, but seemingly only once and only if you spot it, then you're just left with a grey strip with no indication of what to do.

**Proposed Solution**
Having question marks like for cycling and pavement, but across the whole lane, would probably be a lot more obvious IMHO.

I also thought part of the text was missing as it just says about the road orientation and nothing more.

**Comment by westnordost** [comment]
Ok, fair enough
