### ISSUE TITLE
Marked/unmarked single lane one-way roads

### ISSUE THREAD

**Issue by peternewman** [westnordost/StreetComplete#2339]
**Use case**
This is possibly philosophical as much as anything else, but SC knows a road is one way, as it offers different multiples of marked lanes. What's the difference between an unmarked and marked one-way single lane road? Is it marked if there is a cycle-way on the road, or say some no-stopping zig-zags or no-parking (or even a parking lane) at the edge, but unmarked if it's just a bit of tarmac between two pavements?

**Proposed Solution**
Either add a hint to the app for which we should pick, or hide the option to select unmarked and tag appropriately based on if we pick one or more lanes?

**Comment by westnordost** [comment]
> What's the difference between an unmarked and marked one-way single lane road?

None as far as the app is concerned. It is tagged the same in that case.

```kotlin
// if there is just one lane, the information whether it is marked or not is irrelevant
// (if there are no more than one lane, there are no markings to separate them)
when {
  laneCount == 1 -> changes.deleteIfExists("lane_markings")
  isMarked ->       changes.modifyIfExists("lane_markings", "yes")
  else ->           changes.addOrModify("lane_markings", "no")
}
```
https://github.com/westnordost/StreetComplete/blob/master/app/src/main/java/de/westnordost/streetcomplete/quests/lanes/AddLanes.kt#L33-L39

Hence, since it doesn't matter which option the user selects, it is also not necessary to clarify whether a oneway road with one lane should count as an unmarked or marked road.

**Comment by peternewman** [comment]
Hence couldn't it just only show the marked option with the number of lane choices @westnordost so we don't need to spend any effort thinking if it's marked or unmarked?

Also I see your deleting the key, if there is a one way single lane road with an adjacent cycle lane, would that not be lane markings?

**Comment by westnordost** [comment]
> Hence couldn't it just only show the marked option with the number of lane choices

No, because it could be a oneway but with several lanes.

But wait a moment, yes I think this conflicts with that other feature I added, that the user does not actually specify the number of lanes if he tapped on "unmarked".

**Comment by peternewman** [comment]
> > Hence couldn't it just only show the marked option with the number of lane choices
> 
> No, because it could be a oneway but with several lanes.

Yes, so when the multi-lane popup appears, I can choose 1 lane (philosophically unmarked) or 2, 3 etc upwards if it is a multi-lane one-way road.

I think you've said Marked->1 == Unmarked->1 (or just unmarked if it auto-completes), therefore one of them appears to be unnecessary duplication to me.

**Comment by westnordost** [comment]
> Yes, so when the multi-lane popup appears, I can choose 1 lane (philosophically unmarked)

Well, a reaally wide unmarked oneway road would certainly have several lanes (but unmarked)

**Comment by westnordost** [comment]
I decided to close this after all. The possible mistake I spotted was no mistake after all.

**Comment by peternewman** [comment]
> > Yes, so when the multi-lane popup appears, I can choose 1 lane (philosophically unmarked)
> 
> Well, a reaally wide unmarked oneway road would certainly have several lanes (but unmarked)

But we can't enter a multi-lane unmarked road, you removed that option... We can only enter unmarked or the number of marked lanes.
