### ISSUE TITLE
Mark StreetComplete changesets

### ISSUE THREAD

**Issue by rmikke** [westnordost/StreetComplete#234]
I believe every changeset description should contain the word "StreetComplete". This would make StreetComplete changesets easily identifiable.

Advantages:
1. QA tools could use it
2. Stats of StreetComplete usage might be done by anyone who needs them
3. StreetComplete would get more publicity. Which I truly believe it deserves :D

**Comment by westnordost** [comment]
The editor name and version is specified in the created_by field just like any other editor does it. For QA tools and stats, this is easier to evaluate than writing it into the changeset description.

**Comment by rmikke** [comment]
You are probably right abou QA and stats.

But I think the "marketing" side is important. The strength of the app depends on its popularity - the more people use it, the more good data OSM gets. So every way of advertising StreetComplete's existence is useful. And showing it in changeset comments is one of them. And a cheap one.
