### ISSUE TITLE
Question: Statistics StreetComplete ./. OSM-changesets

### ISSUE THREAD

**Issue by GITMichaelK** [westnordost/StreetComplete#2342]
I'm trying to understand the differences in counting changes (or OSM.changesets?) between Streetcomplete (were the number of stars is shown) and OpenStreetMap, where I can see my daily changesets f.e. using [HDYC](https://hdyc.neis-one.org/); an actual example:
 * Road surface defined: +1 star
 * For a certain Parking lot:
   * open access allowable: + 1 star
   * surface defined: + 1 star
   * fee defined: + 1 star

As I'm doing these changes OFFline (having the quests downloaded in advance), the changes are uploaded as one package after I return to an online-access. In my example, I earned 5 stars. I could understand, that these result in two changesets only, due to the fact, that only two different nodes are affected. But I've got the impressions, that those changes reult in only one changeset at times.  

Would appreciate to understand the counting of changesets, provided by StreetComplete. Thank you, Michael

**Comment by matkoniecz** [comment]
Changes of the same type are grouped.

For example in https://www.openstreetmap.org/changeset/95278642 I edited 26 ways (and got 26 stars), but it was uploaded as a single changeset.

If you edit one parking lot and solve access and fee and type, then you will get 3 stars and changes will be uploaded in one changeset.

**Comment by matkoniecz** [comment]
If you edit one parking lot and solve access and fee and type, then you will get 3 stars and changes will be uploaded in three changesets.

**Comment by mnalis** [comment]
@matkoniecz I guess that is supposing one was using "offline mode"? How would that 26 ways be put in changesets if you were using auto-upload feature of SC? As 26 separate OSM changesets (each with one way), or SC would group and upload them periodically in batches?

**Comment by westnordost** [comment]
>How would that 26 ways be put in changesets if you were using auto-upload feature of SC?

In OSM, you can open a changeset, then keep it open and continue to add changes to it. Finally, close it. This concept is quite unique for OSM I believe and this feature for the API as such is not really used by other editors. Maybe JOSM has a checkbox for it ("keep changeset open"?) that nobody uses.
So with auto-upload, when you for example only solve (+ upload right away ) street surface quests while moving around in the city, it will be added all to the same changesets. (As long as each edit is less than I think 20min apart).

**Comment by HolgerJeromin** [comment]
> This concept is quite unique for OSM I believe and this feature for the API as such is not really used by other editors. Maybe JOSM has a checkbox for it ("keep changeset open"?) that nobody uses.

Vespucci and josm has checkboxes for that for ages and at least I use it to group uploads.
