### ISSUE TITLE
No sidewalk/cyclelane quest shows up for part of a tertiary 

### ISSUE THREAD

**Issue by RubenKelevra** [westnordost/StreetComplete#2343]
I tagged some parts of a tertiary which I previously missed with the cycle way and was just curious if I had added a tag on one part. 

This part still has neither a sidewalk nor a cyclelane information but isn't showing up in SC.

I don't see no reason why it shouldn't create quests for it. 

These are the tags:

![Screenshot_20201204-093007](https://user-images.githubusercontent.com/614929/101141986-4da7fc80-3615-11eb-888a-0e2c0725cd3d.jpg)

This shows how it looks like in SC:

https://photos.app.goo.gl/nZf4FYf1HxAExz1Z8

Here's the way in the database:

https://www.openstreetmap.org/way/32443854

**Versions affected**

v27.1

**Comment by matkoniecz** [comment]
Nearby footway alongside of road blocks sidewalk and cycleway quests: https://www.openstreetmap.org/?mlat=51.19085&mlon=7.25362#map=19/51.19085/7.25362

**Comment by RubenKelevra** [comment]
> Nearby footway alongside of road blocks sidewalk and cycleway quests: https://www.openstreetmap.org/?mlat=51.19085&mlon=7.25362#map=19/51.19085/7.25362
> 
> Sidewalks mapped as a separate way are intended to block sidewalk and cycleway quests.

Yeah I thought about that, but the footway isn't tagged that it's the sidewalk. 

You're supposed to tag them with

```
highway=footway
footway=sidewalk
```

as the wiki explains:

![Screenshot_20201204-124306](https://user-images.githubusercontent.com/614929/101160062-ab950e00-362e-11eb-98ec-5820d5a8bfde.jpg)


and tag the street with `sidewalk=separate`.

If the sidewalk isn't tagged on the street correctly with `sidewalk=separate` the user can answer the quest appropriately:

![Screenshot_20201204-124345](https://user-images.githubusercontent.com/614929/101160006-96b87a80-362e-11eb-9162-9453935eba79.jpg)

---

I feel like this filter is too restrictive, there is in reality just a second path separated with plants in front of the building. This path isn't a sidewalk. I think that's the reason someone created this way - it's not visible in the sattelite view since it's below the roof. 

Why don't we modify the filter just to hide quests where the sidewalk path is properly mapped with `footway=sidewalk` and let the user decide in the other cases if the paths along the way shows the sidewalk or not? 🤔

**Comment by westnordost** [comment]
Because not all sidewalks are tagged with footway=sidewalk. 
We cannot assume that OpenStreetMap data is complete.

On 4 December 2020 12:50:52 CET, "@RubenKelevra" <notifications@github.com> wrote:
>> Nearby footway alongside of road blocks sidewalk and cycleway quests:
>https://www.openstreetmap.org/?mlat=51.19085&mlon=7.25362#map=19/51.19085/7.25362>
>> >
>> Sidewalks mapped as a separate way are intended to block sidewalk and
>cycleway quests.>
>>
>Yeah I thought about that, but the footway isn't tagged that it's the
>sidewalk. >
>>
>You're supposed to tag them with>
>>
>```>
>highway=footway>
>footway=sidewalk>
>```>
>>
>as the wiki explains:>
>>
>![Screenshot_20201204-124306](https://user-images.githubusercontent.com/614929/101160062-ab950e00-362e-11eb-98ec-5820d5a8bfde.jpg)>
>>
>>
>and tag the street with `sidewalk=separate`.>
>>
>If the sidewalk isn't tagged on the street correctly with
>`sidewalk=separate` the user can answer the quest appropriately:>
>>
>![Screenshot_20201204-124345](https://user-images.githubusercontent.com/614929/101160006-96b87a80-362e-11eb-9162-9453935eba79.jpg)>
>>
>--->
>>
>I feel like this filter is too restrictive, there is in reality just a
>second path separated with plants in front of the building. This path
>isn't a sidewalk. I think that's the reason someone created this way -
>it's not visible in the sattelite view since it's below the roof. >
>>
>Why don't we modify the filter just to hide quests where the sidewalk
>path is properly mapped with `footway=sidewalk` and let the user decide
>in the other cases if the paths along the way shows the sidewalk or
>not? 🤔 >
>>
>-- >
>You are receiving this because you are subscribed to this thread.>
>Reply to this email directly or view it on GitHub:>
>https://github.com/westnordost/StreetComplete/issues/2343#issuecomment-738741936

-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.

**Comment by RubenKelevra** [comment]
> Because not all sidewalks are tagged with footway=sidewalk. 
> We cannot assume that OpenStreetMap data is complete.


True. But the quest would only show up when `footway=sidewalk` *and* `sidewalk=separate` on the road itself are missing.

I feel like this is a missing information we should complete, not filter out.

The quest would show up and the user can decide that the path along on one or both sides is meant to be the sidewalk and thus can add the missing `sidewalk=separate` tag with SC.

**Comment by matkoniecz** [comment]
> the quest would only show up when footway=sidewalk and sidewalk=separate on the road itself are missing.

This is also very common.

**Comment by westnordost** [comment]
I am also upset about this situation and the fact that it is not even possible to better the situation with a tool like SC (f.e. "Is this footway a sidewalk?") because the tagging schema doesn't allow it. In particular, it is possible to mark a footway as a sidewalk, but it is not possible to mark a footway as **not** a sidewalk.

**Comment by matkoniecz** [comment]
> There is no tagging scheme to specify the subtype of a footway.

I even tried to invent one and failed to invent anything suitable. I wanted to achieve ability tag any `highway=footway` with some `footway` tag.

Maybe I should just go with `footway=not_sidewalk_not_crossing`

**Comment by westnordost** [comment]
`footway=footway` ;-)
