### ISSUE TITLE
Suggestion: Keep kerb height options in same order

### ISSUE THREAD

**Issue by pkoby** [westnordost/StreetComplete#2345]
Great job on the kerb height and tactile paving quests! They're a very nice, useful addition that I've been looking forward to.

However, I noticed the first time I used the kerb height quest that the latest selection bumps to the front, which I wasn't expecting. Thus, I answered the next kerb with the wrong value (because I thought it would be at the top right).

I think the latest selection option is great for the roof quest and others that have a lot of options that aren't all used a lot. But with this quest having only four options (three of which look quite similar), I think it might make more sense to keep them static.

I welcome other opinions, though, because I also understand that having some quests switch around and others stay fixed could be confusing...

**Comment by matkoniecz** [comment]
> Great job on the kerb height and tactile paving quests! They're a very nice, useful addition that I've been looking forward to.

Thanks! :)

> I think it might make more sense to keep them static.

+1

> I welcome other opinions, though, because I also understand that having some quests switch around and others stay fixed could be confusing...

Tracktype already stays fixed in place without reordering, so it should not be a problem.
