### ISSUE TITLE
Add "street_side" to parking type quest

### ISSUE THREAD

**Issue by Mannivu** [westnordost/StreetComplete#2346]
On Nov 28 the [`parking=street_side`](https://wiki.openstreetmap.org/wiki/Tag:parking%3Dstreet_side) tag has been [approved](https://wiki.openstreetmap.org/wiki/Proposed_features/parking%3Dstreet_side). I think this parking type should be added to the parking type quest (the one asking if the parking is a multi-storey, surface or underground).

**Comment by westnordost** [comment]
Part of the proposal was to deprecated lay-by, lane etc. Why hasn't this been done?

**Comment by jdhoek** [comment]
The proposal set out to clarify and tighten the definitions of `parking=layby` and `parking=lane` as collateral of the new tagging-value, having found them unsuitable in their intent and practical usage for the type of parking amenity represented by `parking=street_side`.

These two `parking=*` still exist. We, the authors of the proposal, have attempted to provide some better documentation for these two for the cases that they were seemingly intended to address, based on their original documentation, and how they are used in OSM. Our proposal was to deprecate them only for the niche covered by `parking=street_side`, but they should be fine to use for their own purposes.

Due to their _in use_ status and lack of proposal process or championing by any one mapper, the exact definition of `parking=layby` and `parking=lane` is perhaps not as strict as the other parking-values are though.

See also the heading of _Relation to other parking=* values_ in the [proposal](https://wiki.openstreetmap.org/w/index.php?oldid=2066642).

**Comment by jdhoek** [comment]
I documented `parking=layby` and `parking=lane` to the best of my knowledge and based on the feedback from the proposal with what they seem to represent. I've started with a fairly neutral wording, but Supaplex030 and I were thinking that for `parking=lane` in particular the wording pointing mappers to `parking:lane=*` tagged on the highway instead could be stronger though.

**Comment by jdhoek** [comment]
As a value for `parking:lane=*` specifically the value `layby`/`lay-by` can probably be considered deprecated though. It doesn't make much sense to map a lay-by (i.e., a place you can pull over to rest en-route) using `parking:lane=*`.

**Comment by westnordost** [comment]
Ah, okay. Added this now to StreetComplete.

**Comment by westnordost** [comment]
I think if I add street side parking, I also need to add `lane`.

**Comment by jdhoek** [comment]
It depends on how common it is for an `amenity=parking` without `parking=*`-tag to have been intended as `parking=lane`. I would guess that most `amenity=parking` mapped without a `parking=*`-tag represent the more tangible parking types (i.e., `surface`, `street_side` (the larger ones in particular), `underground`, `multi_storey`, and `rooftop`).

If you do add it, I would recommend setting the label to something explicit like “Parking in a lane on the carriage way”.

**Comment by westnordost** [comment]
FYI regarding the phrasing of "street side parking", (Parkbuchten) there is an ambiguity. It seems that in American English, there is no real distinction between what would be tagged as `parking=lane` and `parking=street_side`. I asked on OSM US:

![image](https://user-images.githubusercontent.com/4661658/101213934-74991980-367b-11eb-9687-2630238da9db.png)

So maybe the explanation in the wiki could be refined to make the clear distinction between `parking=lane` and `parking=street_side`.

**Comment by westnordost** [comment]
And further, maybe exchange the picture that shows the Parkbuchten with something along a "real" street (not a residential/living street) so that the picture doesn't appear as if this is just parking for an apartment complex or a "small parking lot"?

**Comment by jdhoek** [comment]
Thanks, I've added a _When not to use_ section to the documentation of street_side.

**Comment by michaelblyons** [comment]
I've been tagging those as "surface" for months. Is there a way to find them for review?

**Comment by matkoniecz** [comment]
> Is there a way to find them for review?

In specific area? Overpass Turbo. Open http://overpass-turbo.eu/s/10X5 on your computer. Move to a desired location, press "run" button to run. You can export to JOSM or download directly from within JOSM or edit found objects elsewhere.

Query was generated by pressing "wizard" button and typing "parking=surface".

**Comment by SupaplexOSM** [comment]
I just made some [graphics](https://wiki.openstreetmap.org/wiki/File:Parking_orientation_and_location.png) to illustrate the different common parking values and the difference between parking orientation and parking position/location. Maybe it helps to understand or communicate the differences, especially for people who rarely deal with parking spaces.

![](https://wiki.openstreetmap.org/w/images/f/f3/Parking_orientation_and_location.png)

**Comment by westnordost** [comment]
Should "lane" be included? Would be the same as "on_street" but have some sort of lane markings?

On 8 December 2020 12:11:20 CET, SupaplexOSM <notifications@github.com> wrote:
>I just made some
>[graphics](https://wiki.openstreetmap.org/wiki/File:Parking_orientation_and_location.png)
>to illustrate the different common parking values and the difference
>between parking orientation and parking position/location. Maybe it
>helps to understand or communicate the differences, especially for
>people who rarely deal with parking spaces.
>
>![](https://wiki.openstreetmap.org/w/images/f/f3/Parking_orientation_and_location.png)
>
>
>-- 
>You are receiving this because you modified the open/close state.
>Reply to this email directly or view it on GitHub:
>https://github.com/westnordost/StreetComplete/issues/2346#issuecomment-740554954

-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.

**Comment by SupaplexOSM** [comment]
The graphics are related to the parking:lane scheme – "lane" refers to the same value/the same parking position as "on_street", but is the term (actually informal) used on separate polygons with amenity=parking. At least that's my understanding and that's how Jeroen has documented it in the Wiki now. It's not a question of whether they are marked or unmarked. The terms "lane" and "on_street" are not synchronised, so to speak, but it's actually the same. In the case of "street_side" parking bays, however, we have now created the same terms in both mapping variants (street way vs. separate).
Interestingly, there is no separate equivalent for "kerb" and "half_on_kerb". In the rare cases where I have mapped them separately, I have tagged them with "parking=street_side" + "parking:position=on_kerb" (see e.g. [here on the right side of the picture](https://www.mapillary.com/map/im/9k_n5uBLH5aqt1wxjKT1RA) / [OSM](https://www.openstreetmap.org/way/856970576)) but I am not sure if this is a good solution as it is not really "street_side" according to our definition...

**Comment by westnordost** [comment]
Isn't there any tagging to distinguish these situations?

![parallel_parking_lane](https://user-images.githubusercontent.com/4661658/101532586-0fa03500-3995-11eb-980f-35d6744ff930.png)

**Comment by jdhoek** [comment]
> The graphics are related to the parking:lane scheme – "lane" refers to the same value/the same parking position as "on_street", but is the term (actually informal) used on separate polygons with amenity=parking. At least that's my understanding and that's how Jeroen has documented it in the Wiki now.

Yeah, that pretty much sums it up. `parking=lane` is a bit tricky because it was created without proper documentation (hence its *in use* status), but it seems to be used mostly as the explicitly mapped variant of `parking:lane` with `on_street`.

I guess there aren't too many cases where you would explicitly map `half_on_kerb` and `on_kerb`; `parking:lane` on the street itself is often the cleaner solution there.

I do find that sometimes a `parking=street_side` area can lean towards what you might tag as `on_kerb` with the `parking:lane` scheme, [like these](https://www.google.com/maps/@53.2151042,5.7932603,3a,75y,313.73h,61.37t/data=!3m6!1e1!3m4!1sVdIroGuPhWL86Be3uIN8Vw!2e0!7i16384!8i8192), but I usually consider something a candidate for explicitly mapped `amenity=parking` with `parking=street_side` if the area is at least clearly demarcated by lines, area colour, grass/bushes, or kerb elements.

**Comment by jdhoek** [comment]
> Isn't there any tagging to distinguish these situations?

There was a discussion on the Tagging Mailinglist about something similar recently that might be interesting to peruse. I think that if `lanes` is tagged, any `parking:lane` is again separate of those.

So left would be:

```
lanes=2
parking:lane:right:parallel=on_street
```

And right looks like:

```
lanes=2
parking:lane:right:parallel=half_on_kerb
```

Or if the right lane is effectively unusable:

```
lanes=1
parking:lane:right:parallel=on_street
```

I don't think there is a way to indicate how much of the road space of the actual traffic lanes is taken up.

**Comment by jdhoek** [comment]
This one:

First mail: https://lists.openstreetmap.org/pipermail/tagging/2020-November/056322.html
Thread: https://lists.openstreetmap.org/pipermail/tagging/2020-November/thread.html#56322

**Comment by jdhoek** [comment]
Of course that dedicated parking area in the left example may be one of those places where simply drawing a `parking=lane` is clearer, especially if it's clearly demarcated.

**Comment by michaelblyons** [comment]
> Of course that dedicated parking area in the left example may be one of those places where simply drawing a `parking=lane` is clearer, especially if it's clearly demarcated.

Clearer, maybe, but sometimes these [are silly](https://www.openstreetmap.org/way/649333106) on curvy roads.

**Comment by westnordost** [comment]
@jdhoek I know about this mailingl ist discussion. I initiated it.

See this message: https://lists.openstreetmap.org/pipermail/tagging/2020-November/056340.html
And then this message: https://lists.openstreetmap.org/pipermail/tagging/2020-November/056361.html

**Comment by jdhoek** [comment]
Sorry, I didn't notice the senders at all. :smiley:  I followed that discussion a bit to see if anything related to the proposal @SupaplexOSM and I were drafting at that time popped up.

> Clearer, maybe, but sometimes these are silly on curvy roads.

Ugh. Agreed there.

**Comment by RubenKelevra** [comment]
@westnordost is it planned to revisit all 'surface' parking nodes/areas? 

I answered a large quantity of them which now got a more specific value. 

So maybe v28 should show the quest for all `parking=surface` again and set a `parking:check_date=*`. 

If the check_date is prior to the release date of v28 we could just ignore it and reask immediately.

**Comment by westnordost** [comment]
Maybe an option. Though this would be somewhat of a precedent, not sure if SC should go down this road.
