### ISSUE TITLE
Tactile paving double-tagging at crossings

### ISSUE THREAD

**Issue by peternewman** [westnordost/StreetComplete#2347]
I think I'm being asked unnecessarily about tactile paving twice at crossings

**How to Reproduce**
This crossing:
https://www.openstreetmap.org/node/2833955771

Already has tactile_paving=yes yet I'm being asked about it for adjacent kerbs that have been drawn. Surely this is duplication as the crossing already has the detail (aside from island tactile paving cases).

Sort of linked, this way (the kerb):
https://www.openstreetmap.org/way/427341975

Has tactile_paving=yes too, but I'm still being asked at that point, is that because it's not on the node itself ( https://www.openstreetmap.org/node/5125180422 ) I think?

**Versions affected**
v27.1

**Comment by matkoniecz** [comment]
This part is deliberate, mostly due to problems with crossing having tactile paving on one side only.

**Comment by westnordost** [comment]
Well, it's two different tagging schemes. Tagging tactile paving on kerbs (detailed mapping) and tagging tactile paving on the crossing node.

Theoretically one could try to not ask when the detailed mapping is used, i.e. maybe not asked if the crossing node is part of a way with the tags `highway=footway + footway=crossing`? What do you think , @matkoniecz ?

**Comment by peternewman** [comment]
> Well, it's two different tagging schemes. Tagging tactile paving on kerbs (detailed mapping) and tagging tactile paving on the crossing node.

Presumably different renderers make use of the different info then?

> Theoretically one could try to not ask when the detailed mapping is used, i.e. maybe not asked if the crossing node is part of a way with the tags `highway=footway + footway=crossing`? What do you think , @matkoniecz ?

Could you also ensure consistency somehow, perhaps prompt a resurvey of the older one if the newer one conflicts?

It just seems odd I could currently tag `crossing=yes tactile_paving=yes` then I or someone else could later tag the kerbs as `tactile_paving=no`!

**Comment by westnordost** [comment]
> Could you also ensure consistency somehow, perhaps prompt a resurvey of the older one if the newer one conflicts?

Too complex. That whole kerb tagging scheme is already borderline too complex with its 4 different ways how to map the same thing.

**Comment by matkoniecz** [comment]
> It just seems odd I could currently tag crossing=yes tactile_paving=yes then I or someone else could later tag the kerbs as tactile_paving=no!

(1) There are sometimes cases where it may be partially needed (like actual case with island in the middle that has no tactile paving and tactile paving present where you enter road at https://www.openstreetmap.org/?mlat=50.07409&mlon=19.92915#map=18/50.07409/19.92915 ).

(2) crossing tagging is filled with double tagging (or even tripple tagging in some cases) and as in some situations more complex solution is needed, while in most cases simple is preferred by people....

---------

"Presumably different renderers make use of the different info then?" I am not sure whatever anything is using this data right now :) But adding quest to collect this was doable, and I have seen reports about experimental routing for blind people using OSM data, so I think that collecting this is a good idea.


---------

> Theoretically one could try to not ask when the detailed mapping is used, i.e. maybe not asked if the crossing node is part of a way with the tags highway=footway + footway=crossing? What do you think , @matkoniecz ?

It would be fine to add this but note that not asking on `highway=footway + footway=crossing` will result in no quest at all in some cases ( https://user-images.githubusercontent.com/4661658/92394949-c7b60b80-f122-11ea-9b8b-ccba004fd088.png from https://github.com/westnordost/StreetComplete/issues/1305#issuecomment-688333976 ).

Overall crossing tagging is a big pile of double tagging, so someone sooner or later would feel need to add this info. So I see nothing wrong in adding it right now with SC.

Especially as avoiding this would be tricky (something along "check whatever footway way of crossing is intersecting with `barrier=kerb` OR reaches single strand of `footway=sidewalk`") or would drop this quest completely in some places.

**Comment by matkoniecz** [comment]
Overall I have no strong feelings about changes in any direction - it is just matter of preferences between 

- avoiding repetition
- avoiding false negatives
- avoiding coding that will not bring clear benefits and/or will be very tricky

If someone really dislikes duplication in crossing tagging. Then following may be useful: reading proposals (failed and succesfull), documenting situation and/or making proposal that would reduce duplication and tricky issues (tagging on crossing node, on crossing way, on kerb, `crossing_ref` mess, `zebra` mess, `bicycle=no` on crossings. Personally I am not irritated enough to write a proposal, discuss it, amend it and go through a vote that may fail :)

**Comment by westnordost** [comment]
Ok then I'd close this. For data consumers, it is easy to filter this duplication because it is easy to tell apart tactile pavings tagged on a `highway=crossing` node and "somewhere else". "Somewhere else" would be probably on a kerb, i.e. either on a `barrier=kerb` node or on the intersection point between a sidewalk and a crossing or on an intersection point between a `barrier=kerb` way and a footway.

**Comment by peternewman** [comment]
> (1) There are sometimes cases where it may be partially needed (like actual case with island in the middle that has no tactile paving and tactile paving present where you enter road at https://www.openstreetmap.org/?mlat=50.07409&mlon=19.92915#map=18/50.07409/19.92915 ).

Yeah I'd often wondered about island tactile paving. Although how do you know if the tagging on the crossing node is the island or the whole crossing? :confused: 

Okay fair enough anyway.
