### ISSUE TITLE
Lane quest defaults to 14 lanes in older Android versions

### ISSUE THREAD

**Issue by cyclingcat** [westnordost/StreetComplete#2349]
Hi there,

here is a weird one:

When solving a lane quest, the number picker on my 4-year-old bq Aquaris M4.5 with Android 5.1 defaults to 14! Furthermore, the picker is an endless one, you can swipe in both directions forever, like a closed circle. Both effects are reproducible. My Cubot Quest with Android 9 doesn't show this behaviour.

See the screenshots:

**Android 9** (looking fine):
![Screenshot_Android_9](https://user-images.githubusercontent.com/32601012/101342653-29515780-3883-11eb-96ba-57b9c9b19633.png)

**Android 5.1** (oops!?):
![Screenshot_Android_51](https://user-images.githubusercontent.com/32601012/101342525-fc9d4000-3882-11eb-90df-79824777fc8b.png)

(SC v27.2)

The cycling cat

**Comment by westnordost** [comment]
That it wraps around seems to be a problem of Android 5.1, that it preselected the highest value was a bug in the app.
