### ISSUE TITLE
OSM Then And Now is decommissioned

### ISSUE THREAD

**Issue by losuler** [westnordost/StreetComplete#2351]
**How to Reproduce**
1. Open `My Profile` from the top right burger menu.
2. Select the right most top menu tab.
3. Open [`OSM Then And Now`](https://mvexel.github.io/thenandnow/).
4. See the message that says the site is decommissioned.

**Versions affected**
Android 11
StreetComplete 27.1

**Notes**
This is notable because it was mentioned in a popup achievement.

**Comment by westnordost** [comment]
Hm too bad. I'll remove it.

**Comment by westnordost** [comment]
Ha, on the occasion I noticed I copy&pasted the wrong description for that link. It should have said _"Curious what progress we made over the years? Compare to how the map looked more than 10 years ago!"_
