### ISSUE TITLE
Multiselection of quests

### ISSUE THREAD

**Issue by a123qwertz567** [westnordost/StreetComplete#2353]
**Use case**

Save time when adding tags for whole streets and areas. For example for a whole street of townhouses you have to select every house one by one, while the map and ui flings around.

**Proposed Solution**

Add multi select support for quests, so you can tag whole streets more easily.

**Comment by smichel17** [comment]
Duplicate of #73 (and others, which you can find from #73)

**Comment by a123qwertz567** [comment]
Oops, wasn't able to find these issues.
