### ISSUE TITLE
Invisible map

### ISSUE THREAD

**Issue by platypro** [westnordost/StreetComplete#236]
My map is invisible. I can still select quests, and they still light up things, but I cant see the map.

It worked on the previous version (0.8), but no longer works for me.

I'm running a HTC Desire 601 phone with Android version 4.4

The following screenshot is from the latest development version:
![](https://cloud.githubusercontent.com/assets/15664710/26030180/d4b17e94-37ff-11e7-827d-b3147f3ac265.png)

**Comment by westnordost** [comment]
#175
