### ISSUE TITLE
GPS movement is too smooth

### ISSUE THREAD

**Issue by mycae** [westnordost/StreetComplete#237]
The GPS movement shown is really hard to judge, particularly when near large buildings, where the calculated position is distorted. This is due to excessive filtering on the computed position coordinates, which highly over-weights the historical coordinates the GPS has provided.

Please consider either an option, or a default, to reduce the level of temporal smoothing done on the GPS position. It currently sluggishly sloshes about in a confusing way.

A more accurate "jump" is fine, and doesn't give the impression of the GPS being accurate when it clearly is not. Its quite confusing to be standing still and have the GPS do little smooth sloshes. Having it perform discrete jumps is easier to tell how accurate the GPS actually is being (i realise there is the circle, but it can't show biasses very well. only statistical error.), without having to wait a few minutes to figure it out from the slow wobbles.

Streetcomplete users are probably a bit more technically inclined than a google-maps user, so some small nods to reality are probably fine.

**Comment by westnordost** [comment]
With slow wobbles, you mean the 1s animation towards the new location?

**Comment by mycae** [comment]
Yes, having used it on a train, where the rail runs in a straight line, the GPS pauses at each GPS fix position, then slides smoothly to the next update. Perhaps it is that the low update rate, combined with the "sliding" interpolation is creating the visual effect that I term "sloshing".

I'm not sure about the frequency - it might be every second, but maybe higher?  As I was at speed, the vector is mostly correct, owing to the large baseline between points

I found today that its quite hard to catch roads when moving at speed, as I'm uncertain which road it is i'm passing - is it the one the GPS shows - I don't think so, as it doesn't match the terrain layout.  The error circle shows an unreasonably small error too.

Perhaps it needs a forwards predictor term, rather than a historical one? I've not looked at the code for the update algorithm, and don't develop for android (GPS or not), so I'm unsure where the coordinate decisions are made.

**Comment by gappleto97** [comment]
> The error circle shows an unreasonably small error too.

For me that circle is just inconsistent. Even changing the zoom level will cause it to change in proportion to the rest of the map, even though the GPS hasn't updated yet.

**Comment by westnordost** [comment]
It's now half as sloshy. (animation time to new position: 500ms)
