### ISSUE TITLE
Mapillary imagery to add building attributes

### ISSUE THREAD

**Issue by iamnunocaldeira** [westnordost/StreetComplete#239]
OSMand is applying Mapillary on their app. would be great if possible to have street level imagery to detail highway surface, building levels. Obviously you had to be on WiFi to access Mapillary for the photos, but none the less would be a nice way to have an OFFLINE editing mode like now and an ONLINE where you could check the Mapillary photos.

https://github.com/osmandapp/Osmand/tree/a6b99f1e41bbabd030fdeca8b72694e13606842d/OsmAnd/src/net/osmand/plus/mapillary

Keep up the good work, im not really a coder, but gave my contribution by translating to portuguese.

**Comment by westnordost** [comment]
The app is supposed to be used on survey, no need for mapillary imagery if you are on site. So, sorry, but now.
