### ISSUE TITLE
F-Droid screenshots & release notes

### ISSUE THREAD

**Issue by rugk** [westnordost/StreetComplete#241]
F-Droid has a [new UI](https://f-droid.org/posts/a-new-ux-6-years-in-the-making/) and thus allows applications to show screenshots and e.g. release notes for updates. It would be nice if you could use this possibility and embed them for your application.

**Comment by westnordost** [comment]
But how?

**Comment by rugk** [comment]
Ehh, edit the meta data or so?
Better ask F-Droid about how to do this.😀

**Comment by EdoPut** [comment]
[Here](https://eighthave.gitlab.io/fdroid-website/docs/All_About_Descriptions_Graphics_and_Screenshots/) there is the wiki article about it.

As with #2  the metadata directory is already there it may be the simpler thing to do, just add the screenshots to the fdroid repo and update them when something changes.

**Comment by rugk** [comment]
The new [page is here](https://fdroid.gitlab.io/fdroid-website/docs/All_About_Descriptions_Graphics_and_Screenshots/) and I think using the "app’s source repository" is a better and easier idea than using the fdroid repo again (and needing to update it).

**Comment by westnordost** [comment]
OK, I added all the descriptions in all the languages. I hope it is the correct format, I did actually not use fastlane because it does not work on Windows.
