### ISSUE TITLE
UI improvement on opening hours quest

### ISSUE THREAD

**Issue by f6fvy** [westnordost/StreetComplete#242]
In the vast majority of cases, the minutes of the opening hours are 00, 15, 30 or 45. Would it be possible to add 4 buttons for these values, instead of spinning the control to these values (longer and error-prone).

**Comment by westnordost** [comment]
Perhaps it is possible. The time-select is an Android component, not sure how much I can interfere there.

**Comment by westnordost** [comment]
Nope, not possible, sorry. (Just tested it.)

**Comment by f6fvy** [comment]
Thanks for trying. I will limit these quests. Too tedious.
