### ISSUE TITLE
Change StreetComplete to an OsmAnd Plugin

### ISSUE THREAD

**Issue by HolgerJeromin** [westnordost/StreetComplete#243]
To improve offline rendering we could look at the popular OsmAnd app.
OsmAnd can download raster tiles and has even offline rendering with regular updates (free of charge: monthly, about 1.1 euro per month: weekly, daily, hourly).

OsmAnd has no possibility to be used as a rendering library.

But the other way round could be possible to change StreetComplete into an OsmAnd plugin.

Ref #175

**Comment by grauschnabel** [comment]
I really would recommend this. I use osmand daily, so I would give very much input that way.

**Comment by westnordost** [comment]
Certainly possible with considerable effort, but this would be another project. If someone were to implement this, is could start as a fork and eventually I could split StreetComplete into a core project and an app project, so the osmand plugin and the standalone app would share most of the code.
