### ISSUE TITLE
Feature Request: Download Settings

### ISSUE THREAD

**Issue by mds08011** [westnordost/StreetComplete#245]
I have a feature suggestion: provide a “download via wifi only” setting for caching maps (similar to the Auto-sync option).  I realize the app is intended to be used and performs well offline, but I am sometimes nervous that my phone may download more map via cellular data as I move around.  If only for peace of mind, I think it would be beneficial to clarify data permissions/settings.

**Comment by matkoniecz** [comment]
To clarify - you want to keep downloading quests and upload answers, without downloading malls?

**Comment by mds08011** [comment]
Essentially, I would like options similar to the Auto-Sync settings (On, Only on Wifi, or Off) implemented for map and quest downloads.  While using the app, I would like to leave my phone's cellular data activated to improve my GPS location, but also be confident that I will not unintentionally download additional maps or quests as I move around and scroll through the cached map.

**Comment by althio** [comment]
I proposed something similar (more granulary and clarity in upload/download settings)
https://github.com/westnordost/StreetComplete/issues/75#issuecomment-297489595

**Comment by westnordost** [comment]
Afaik this is not possible yet with tangram-es. You'd need to create a feature request there https://github.com/tangrams/tangram-es/issues (and link it to this one).

**Comment by Hillside502** [comment]
@mds08011 
3G Watchdog Pro - Data Usage – Android Apps on Google Play
https://play.google.com/store/apps/details?id=net.rgruet.android.g3watchdogpro

**Comment by mds08011** [comment]
Thank you!

**Comment by westnordost** [comment]
I found out that a change in tangram-es is actually not necessary. The class TileHttpHandler simply needs to be extended to add this feature.

**Comment by leftshift** [comment]
Do we want this as a second option, like
* Auto-sync Quests
* Auto-load Map
or use the existing auto-sync option to also turn off automatic loading of the map?

**Comment by rugk** [comment]
IMHO the map should always load automatically (as it works currently), as StreetComplete is pretty useless without a map in the background (you cannot see which quest is what, i.e. what element is the quest asked about). So just leave it as it is, currently.

**Comment by westnordost** [comment]
Decided this will be a will-not-fix. If/when there will be something like that, it will be a "Download this area for offline"-feature.
