### ISSUE TITLE
add appname and version hashtag to note

### ISSUE THREAD

**Issue by it4workflow** [westnordost/StreetComplete#247]
https://forum.openstreetmap.org/viewtopic.php?pid=646466#p646466

**Comment by westnordost** [comment]
Appname and version is not helpful for the case you discuss in the forum. Helpful is the context in which the note was created. Today, I implemented this and this will be live for the next version:

https://github.com/westnordost/StreetComplete/issues/54
https://github.com/westnordost/StreetComplete/issues/171

**Comment by westnordost** [comment]
The note will look like this:

_In reply to "What is the housenumber of this building?":
It's a garage.

http://www.openstreetmap.org/way/1234_

**Comment by it4workflow** [comment]
Appname and version IS helpful, e.g. for statistics, etc.

And this will not be the first application that accidentally sets a note to 0° 0°.

**Comment by westnordost** [comment]
> Appname and version IS helpful, e.g. for statistics, etc.

It certainly is. Though, the Notes Api does not provide a way to specify a "created_by" for notes so far. This is something that needs to be implemented on the openstreetmap api side. Please see these tickets:
[Add a field to notes to indicate what software is creating them #385](https://github.com/openstreetmap/openstreetmap-website/issues/385)
[Filterable Map Notes #486](https://github.com/openstreetmap/openstreetmap-website/issues/486)

**Comment by RicoElectrico** [comment]
For anyone who doesn't know how StreetComplete works and that is exists it IS very confusing.

**Comment by tilmanb** [comment]
you should just add "#streetcomplete" at the end of the note body, until the notes API changes the way proposed in openstreetmap-website/issues/385 and openstreetmap-website/issues/486 .
