### ISSUE TITLE
housenumber quests doesn't allow entering letters

### ISSUE THREAD

**Issue by krzyk** [westnordost/StreetComplete#249]
House numbers in Poland can have following format:
1. [0-9]+ (e.g. 5)
2. [0-9]+[A-Z]? (e.g. 5C)
3. [0-9]+[A-Z]?(/[0-9]+)? (e.g. 5C/13)

Right now the app allows only to enter the first kind - only numbers, please remove the restriction and allow entering other characters there as well.

**Comment by matkoniecz** [comment]
What is your StreetComplete version, android version and phone? In http://www.openstreetmap.org/changeset/48486305 I added

> 109a

with StreetComplete.

**Comment by krzyk** [comment]
Oops, I didn't notice that there is a button "ABC" :), after clicking it I'm able to enter letters, closing.

**Comment by westnordost** [comment]
There is a regex which checks if the housenumber seems plausible and warns the user if "this housenumber looks unusual". Country specific valid/normal housenumber formats are valuable. Can you give me some examples of still normal/valid housenumbers in PL?

Am 18. Mai 2017 13:01:13 MESZ schrieb "Krzysztof Krasoń" <notifications@github.com>:
>Closed #249.
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/westnordost/StreetComplete/issues/249#event-1087583415

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.
