### ISSUE TITLE
Double tap on images should submit quest 

### ISSUE THREAD

**Issue by HolgerJeromin** [westnordost/StreetComplete#254]
Some quests are images. Roof shape, highway  surface for example. 
Double tap should submit them.

**Comment by westnordost** [comment]
I do not think this is a good idea. It is not clear from the UI that a double tap would do something like this specifically for this quest. Also, the OK button is always in reach, as it floats at the bottom of the screen, so there is really no reason why this is necessary and can only serve to that users accidentally submit an answer.

The form should be "stable". No interaction other than the bottom bar should do any "definite" action, this is a deliberate design decision.

**Comment by HolgerJeromin** [comment]
Combined with the "no easy undo" this is probably not a good idea. Could be a preference, but your design goal is to have as few as possible. OK for me
