### ISSUE TITLE
The full feature is not visible after selecting a quest for it

### ISSUE THREAD

**Issue by HolgerJeromin** [westnordost/StreetComplete#258]
I don't see the ends of the selected way for a surface quest. But I would like to see them to be sure the way is correct. 
Android 6 on Fairphone 2 with app version 0.11

https://www.openstreetmap.org/way/385592029

![rps20170522_001428_248](https://cloud.githubusercontent.com/assets/2410353/26287849/aea68408-3e83-11e7-95d6-e8468f73da57.jpg)

Issue moved from #204

**Comment by matkoniecz** [comment]
Is it also fixed by https://github.com/westnordost/StreetComplete/commit/6c25e124cc2f61a8d9d1c79b6ec1a326cc588210 ("zoom to a level so that it completely encompasses the quest")?
