### ISSUE TITLE
Quest Request: Intersection Stop Signs

### ISSUE THREAD

**Issue by gappleto97** [westnordost/StreetComplete#259]
I know that there is currently some  confusion about how to encode stop signs and the like, however:

In Michigan (and I think several other states) it is required that all intersections have at least one stop or yield sign/light. Once the above confusion is resolved, it would be nice if the app would ask about intersections which did not have this in place.

**Comment by matkoniecz** [comment]
Maybe close this and open issue once tagging problem is fixed? Some tagging problems remain unresolved for many, many years.

Also, note that adding new objects is out of scope.
