### ISSUE TITLE
Quest for mobility access

### ISSUE THREAD

**Issue by Monduiz** [westnordost/StreetComplete#26]
Could a mobility access quest be added? This would be great to add this info on buildings.

**Comment by westnordost** [comment]
Buildings in general would be quite a lot, plus the normal surveyor won't be able to find that out for the most buildings, since he cannot simple go in there. I do not want to have quests that are not solveable by the user.

I would suggest only for shops (and what else?)

**Comment by Monduiz** [comment]
Well, shops are often nodes, not buildings and most often than not, they are nodes attached to a way(buildings), just like amenities.  Yes, I can see how buildings would be a lot. 

Civic places and transport though would make sense.

**Comment by CloCkWeRX** [comment]
I'd put up there amenity=toilet
Answers: https://wiki.openstreetmap.org/wiki/Key:wheelchair#Common_values

**Comment by CloCkWeRX** [comment]
And of course; visualisation/consumed by https://wheelmap.org/map

**Comment by PanierAvide** [comment]
+1 for transports, in particular (but not only) bus stops (highway=bus_stop or public_transport=platform).

**Comment by rmikke** [comment]
I would suggest this quest for shops and amenities.

**Comment by wojtekmaj** [comment]
I vote for this! This is one of the things that is always omitted, easy to check and makes a huge difference, adds a huge value for OSM making it much more useful for people truly in need.

**Comment by westnordost** [comment]
Oh, that has been implemented already by @Teester (and being refined as we speak)
