### ISSUE TITLE
Not asking material for highway=trunk_link

### ISSUE THREAD

**Issue by gappleto97** [westnordost/StreetComplete#262]
It would appear that some highway nodes don't ask you what material they are. highway=trunk_link is the example I've come across, but I would imagine that there are a few others.

**Comment by HolgerJeromin** [comment]
This is intentional. Here is the [source](https://github.com/westnordost/StreetComplete/blob/master/app/src/main/java/de/westnordost/streetcomplete/quests/road_surface/AddRoadSurface.java#L19):

```
private static final String[] ROADS_WITH_SURFACES = {
    // "trunk","trunk_link","motorway","motorway_link", // too much, motorways are almost by definition asphalt (or concrete)
```

**Comment by gappleto97** [comment]
Hm.... I disagree with that, but not strongly enough to argue very hard about it. Unless it's a server-side problem, I would much rather have that be a toggle than a blanket ban. If @westnordost makes a ruling, I'll close without a fuss though.

I might consider putting in a PR if I can remember enough of the UX code to put the toggle in. I'm certainly willing to add in the necessary if statements.

**Comment by HolgerJeromin** [comment]
@westnordost is against more settings.

**Comment by claudiush** [comment]
@gappleto97 Do you have real world examples where a trunk_link wouldn't be asphalted? Even the trunk roads I have been mapping in Iran and Turkmenistan are asphalted. I can think of a few trunk roads that have concrete surface, but that's about the only border case I can think of.

**Comment by gappleto97** [comment]
All of the ones in my hometown are concrete. And there are several places in the northern parts of US-41 that have asphalt roads and concrete links.

**Comment by matkoniecz** [comment]
@claudiush For example, https://www.google.com/maps/@14.5575655,121.0638086,3a,75y,210.15h,56.34t/data=!3m7!1e1!3m5!1suGF4abw3vaKqc6Wa27h0hQ!2e0!6s%2F%2Fgeo0.ggpht.com%2Fcbk%3Fpanoid%3DuGF4abw3vaKqc6Wa27h0hQ%26output%3Dthumbnail%26cb_client%3Dmaps_sv.tactile.gps%26thumb%3D2%26w%3D203%26h%3D100%26yaw%3D55.901505%26pitch%3D0%26thumbfov%3D100!7i13312!8i6656

![selection_001](https://cloud.githubusercontent.com/assets/899988/26520149/66c52362-42cd-11e7-92bf-e84641537353.png)

Found by http://overpass-turbo.eu/s/pjC

According to http://overpass-turbo.eu/s/pjx there are also motorways mapped as surface=concrete

**Comment by HolgerJeromin** [comment]
In data usage asphalt or concrete is (nearly) identical. Probably that's why the surface quest gains much more value on smaller roads where we have unpaved surfaces which makes a real difference for routing engines.

**Comment by westnordost** [comment]
See @HolgerJeromin 

The data value for these roads is very low when we assume that every motorway or trunk will be paved by either asphalt or concrete because it really makes very little difference. Surface quests are repetitive enough as they are already.
Also, the app is more an "on foot" app. It would be much more efficient to add the surface tag to motorways etc. using sparse editing with JOSM + Overpass query.
