### ISSUE TITLE
Authentication should use external browser instead of embedded webview

### ISSUE THREAD

**Issue by mormegil-cz** [westnordost/StreetComplete#265]
See [OAuth 2.0 for Native Apps (draft)](https://tools.ietf.org/html/draft-ietf-oauth-native-apps-11). The best practice for OAuth in native mobile apps is to open the (default external) browser, not to embed the authentication flow in a webview inside the app.

**Comment by HolgerJeromin** [comment]
Yes. 
My default browser is already authenticated on osm.org.
Furthermore i am sure that the website to enter my passwords is really the correct one (if i trust my default browser). 
Streetcomplete could present my a fishing site in the web view.

**Comment by westnordost** [comment]
I would accept a pull request that implements this but I am not planning to implement this myself.

**Comment by westnordost** [comment]
Done
