### ISSUE TITLE
Can't add housenumbers that are not numbers in 0.11 release

### ISSUE THREAD

**Issue by krzyk** [westnordost/StreetComplete#266]
In 0.10 I was able to add housenumbers that have letters (pretty common in Poland) by clicking on an icon of "ABC".
In 0.11 this icon disappeared and the dialog allows only numbers to be entered.
Please bring back the ability to enter other characters in housenumbers.

Moto X Style, Android 6.0.1, SwiftKey Keyboard

**Comment by matkoniecz** [comment]
What is your StreetComplete version, android version and phone? I have "ABC" button in 0.11.

**Comment by matkoniecz** [comment]
Especially, can you show screenshot with at least one number in blue box?

**Comment by matkoniecz** [comment]
I am guessing that you need to simply click on blue box to start input (see #227 for discussion about this design).

**Comment by krzyk** [comment]
I clicked on the blue box, entered 16 and then I wanted to add "A", but I don't see the ABC button and the keyboard doesn't allow to enter anything other than numbers. In 0.10 I had the ABC button.

This is a more complicated case actually.
1. Click on a housenumber quest
2. Click on blue part
2. There is no ABC button
3. Hide keyboard
4. Click on the blue box again
5. ABC button appears.

Moto X Style, Android 6.0.1

**Comment by westnordost** [comment]
The ABC button should appear immediately when you click on the text field. Do you have animations off? Does it work if you turn on animations?

**Comment by krzyk** [comment]
Yes, I have animations off. When I turned them on the ABC button appears at first click on the text field. With animations if I need to click, hide keyboard and click again and ABC button appears.
