### ISSUE TITLE
local language when leaving a note

### ISSUE THREAD

**Issue by lenod** [westnordost/StreetComplete#267]
When a question cannot be answered, a note can be left on OSM of the form:

In reply to: [question], [user's answer]

The issue is that the question is written in the user's own app language. It should instead be written in the location's language (or at least english) so that local users can understand the note.

The user could also be encouraged to leave their note in the local language (or English).

**Comment by westnordost** [comment]
The question could be written in the location's language, but then it might not match with the user's answer which will create some question marks with readers of the note, I think more question marks than reading a note that is completely in another language.

Other opinions or ideas?

**Comment by lenod** [comment]
This already does raise questions marks from readers.
The question is: should we encourage users to publish notes in random languages?

We could add a warning before publishing a note in another language, saying which languages are recommended to write the note.
The user could also select the language of the question, with a relevant default value.
These two solutions could be merged this way : your note will be published in [flag] (selectable), the recommended languages are [flag], ..., [flag].

The question could also be displayed before the text area so that the user can see what the note will look like.

**Comment by matkoniecz** [comment]
Is it a real problem? Are there really real cases where foreign editor posts from StreetComplete notes that are unusable due to language barrier?

Recommended languages is a can of worms - sooner or later it will make a stupid suggestion and it may be a very thorny issue.

**Comment by Aypac** [comment]
Yeah, I agree. I guess a static note of the type "Please consider using either the local language or English for your note" should do just fine.

**Comment by matkoniecz** [comment]
Is it really necessary? Is it a real problem? I rather dislike warnings that suggest that people are complete idiots. In large part because it leads to skipping all warnings, also useful ones.

**Comment by Aypac** [comment]
I agree, I would not like to have a warning popup you have to confirm. But the way the comment screen is currently designed, there would be enough space to add a small gray text with this "tip".

**Comment by lenod** [comment]
Here are two examples where language is an issue:
http://www.openstreetmap.org/note/1009960
http://www.openstreetmap.org/note/1009964

@Aypac Yes, I meant a tip which does not require confirmation. It could also be a warning (requiring confirmation) only the first time (or the first time the users writes a note in a country with a different language).

**Comment by westnordost** [comment]
The problem with the examples you mention is not the language of the question.
1st: it is unclear what the user means. A complete sentence "This is a private service lane" would have been better. 
2nd: only because the opening hours are not posted doesn't mean it has no opening hours. Why did the user leave a note only because he wasn't able to find out the OH? Perhaps the app needs to communicate better that he can simply hide the quest if he is not able to solve it?

Am 31. Mai 2017 19:58:11 MESZ schrieb lenod <notifications@github.com>:
>Here are two examples where language is an issue:
>http://www.openstreetmap.org/note/1009960
>http://www.openstreetmap.org/note/1009964
>
>@Aypac Yes, I meant a tip which does not require confirmation. It could
>also be a warning (requiring confirmation) only the first time (or the
>first time the users writes a note in a country with a different
>language).
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/westnordost/StreetComplete/issues/267#issuecomment-305267570

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by CloCkWeRX** [comment]
labs.strava.com/routing-errors/ suffers the same kind of issue; IMO its not really that bad of a problem. Most notes are easily worked out via google translate. If anything did warrant fixing I'd suggest one click tools in the note display UI (ie, not this project) to translate.

**Comment by westnordost** [comment]
The question is now always in English, because the people who are likely looking at the notes are OSM members which very likely can understand English (since all tags are in English, the wiki is mostly English etc.)

**Comment by althio** [comment]
If the language in the app is not English, I think you could add more informations in the note creation.

I propose this kind of information and order:
> _english_ - From the survey mobile app StreetComplete, in reply to:
> _english_ - [question]
> _english_ - [app language] / _app language_ - [app language]
> _app language_ - [question]
> _app language_ - [user's answer]

for instance:
> From the survey mobile app StreetComplete, in reply to:
> What is this?
> Japanese / 日本語
> これは何ですか？
> これがそうです。
