### ISSUE TITLE
Authentication with openstreetmap not working

### ISSUE THREAD

**Issue by lupa18** [westnordost/StreetComplete#268]
Hello, 

I installed 0.11 and when trying to authenticate using my osm credentials, I got an error. I did a triple check before publish this issue. I tried several times and it doesn't work. 

Nevertheless, same credentials, applied in my desktop works perfect.  

thanks in advance !

**Comment by matkoniecz** [comment]
> I got an error

What kind of error? What is the exact message? How you were logging in (password + user name or login using X)? What is your phone and android version?

**Comment by lupa18** [comment]
Hello ! 
Error says: "Sorry. Can't make access with this data". Screenshot:

![screenshot_20170529-094022](https://cloud.githubusercontent.com/assets/463429/26552040/72972ba4-4453-11e7-868b-6c8c3a1c0ea4.png)

I'm loggin using username and password as you can see above. 

I'm using Xiaomi mi4 with CM14.1 (android 7.1.1) 

thanks!

**Comment by westnordost** [comment]
This is of the website, not the app. My guess is that you used autocomplete when filling in the username/email and Android autocomplete usually adds a space after that. So, openstreetmap.org tells you, there is no user named "lupa@inventati.org ".
You can try to login on openstreetmap.org website.

**Comment by volt4ire** [comment]
I had this issue as well. For me the problem was not that autocomplete adds a space, but that the username field was case-sensitive. Only after entering my username in all lowercase did it work.
