### ISSUE TITLE
building:levels=2, roof:levels=1 both set to 1 in OSM.

### ISSUE THREAD

**Issue by johnwhelan** [westnordost/StreetComplete#27]

**Comment by westnordost** [comment]
As can be seen here
<img src="https://raw.githubusercontent.com/westnordost/StreetComplete/master/res/screenshot4.png" width="300"/>
The app asks for the total levels, inclusive roofs. So if you specify 2 in this field and one for the roof, you have building:levels=1 and roof:levels=1 in the end in OSM.

**Comment by johnwhelan** [comment]
I think the idea would be to use it with untrained or disposable users.  ie normally building levels refers to the number of floors.  Can it be misunderstood?

Also the white type on a blue background is easy to read.  the grey type below might need glasses for an elderly volunteer.

Bjenk has a particular project in mind and for that one it has to be English and French and robust.  The user interface is particularly good.

Can we filter the quests?  That way we would only have to explain one thing at a time.  Opening hours is more complex for example.  We have 300,000 buildings we're interested in.  Some more than others.

**Comment by westnordost** [comment]
Please stick to one topic per issue, otherwise it gets messy.

I don't know if it can be understood. I wrote it, so I understand. Did you misunderstand it? Can the wording be changed so that it is more clear?

**Comment by johnwhelan** [comment]
Bjenk can you have someone look at the wording?

Bjenk is the wording specialist or has people around him who are.

Thanks John

**Comment by johnwhelan** [comment]
1720 Caminiti Crescent ottawa K4A 1M1 Canada is an example that is awkward.  three levels but one is in the sloping roof attics.

building:levels should be 3 in OSM agreed?  but what should roof:levels be in OSM?  How would you enter this in streetcomplete to get the desired result in OSM?  Thanks John

**Comment by westnordost** [comment]
It's this one, right?: [OpenStreetMap](http://www.openstreetmap.org/way/471177667), [Google Maps](https://www.google.de/maps/place/1720+Caminiti+Crescent,+Orl%C3%A9ans,+ON+K4A+1M1,+Kanada/@45.4723305,-75.4860583,118a,35y,39.5t/data=!3m1!1e3!4m5!3m4!1s0x4cce13b4dec22683:0x8ae838e3cb263d3!8m2!3d45.4732113!4d-75.4859607)

Well, I'd say it has 3 levels in total, 2 of these are roof levels. Furthermore, it is (mainly) a gabled roof. That's how I'd input it in StreetComplete. In OSM, it then becomes:
```
building:levels=1
roof:levels=2
roof:shape=gabled
```
However, if you then look at a 3D rendering of it, it will look not at all like the original. This is because the house and garage have been mapped as one building. To achieve a higher detail here, one would have to map the garage as an own building (or building part). Note though, that the data inserted is still correct, only the rendering would be off.
Which is okay really, as these tags can only serve as a very rough approximation of its 3-dimensional shape anyway.

**Comment by johnwhelan** [comment]
I think it depends if you are mapping to create a 3D image of it or mapping to get an idea of the square footage or total floor area.  

For stats purposes they would consider this a building:level=3 building since it has three floors above the ground level surface.  It actually has a large basement but we won't count that.

The house next to it has a ground floor and second floor above it.  It also has a gabled roof so stats would think this is building:levels=2 looking for floor area.  There is no attic room under the gable roof.

and I think that is where the possible misunderstandings about building and floor levels come from.

Thanks for the insight.

John

**Comment by westnordost** [comment]
[If anything is still unclear, you can read the definition in the wiki, there is also an illustration.](https://wiki.openstreetmap.org/wiki/Key:building:levels)

I'll close this one.

**Comment by johnwhelan** [comment]
Interesting.  I wonder if this will change the analysis.

However the most common case will be building levels only.

I might tag the first line as "Building levels"
and the second as "additional floor levels in the roof"

but it depends on space for wording and I'd still run it by Bjenk's editors first.  It would also save a mental  calculation.

John

**Comment by Monduiz** [comment]
It can be confusing when adding roofs and basement. The notion of roofs structure is for dedicated mappers. What is important for the general public which is building:levels=*.  An app like this will appeal to a broader range of users and I would say that its best to keep it simple for them: focusing on the number of floors above ground while avoiding getting the roof into the question.

House -> How many floors above ground? -> 2
bungalow -> How many floors above ground -> 1

A building like the one I am working in would be building:levels=13

For most users, I believe it is easier to understand: number of floors above ground than number of floors inclusive roof.

Great work by the way, the UI is amazing!
