### ISSUE TITLE
Not asking number of stories for a cluster of buildings

### ISSUE THREAD

**Issue by gappleto97** [westnordost/StreetComplete#272]
Not sure if this is intentional or not, so I'm leaving the buildings without story information until this issue gets closed. I'm referring specifically to [this](https://www.openstreetmap.org/#map=19/46.55918/-87.40653) cluster. Story information is not known for any of them, but StreetComplete says that there are no quests in that area.

**Comment by matkoniecz** [comment]
These buildings are tagged as building=yes. StreetComplete is not generating building level quests in such cases. Quest for detailing building=yes in StreetComplete was mentioned as planned by the author.

**Comment by matkoniecz** [comment]
See GetTagFilters in https://github.com/westnordost/StreetComplete/blob/master/app/src/main/java/de/westnordost/streetcomplete/quests/building_levels/AddBuildingLevels.java

**Comment by gappleto97** [comment]
Okay. Thank you for the help.
