### ISSUE TITLE
App is not asking for level or roof shape in one region 

### ISSUE THREAD

**Issue by HolgerJeromin** [westnordost/StreetComplete#275]
I am a bit puzzled why streetcomplete does not ask building quests for this area:

https://www.openstreetmap.org/way/286063836/history#map=18/51.87171/8.47247

building=house was added 16 days ago. 
Quest cache is set to one day. Map cache size is 250 MB but should not influence the quests. 

Other regions of the town got many quests after my mass tagging of the buildings.

**Comment by westnordost** [comment]
Can't reproduce. It asks for me.

**Comment by westnordost** [comment]
Keep in mind the app only downloads new quests automatically if there are very few left in your vicinity.
