### ISSUE TITLE
Show roof shape quests for all roof:level

### ISSUE THREAD

**Issue by HolgerJeromin** [westnordost/StreetComplete#277]
Right now the quest is only shown when we have roof levels (and they must be non zero) . 
This does not work for flat roofs. 
And often the roof level are not high enough to have 1.

**Comment by matkoniecz** [comment]
It would also remove problem of roof quest not appearing immediately after solving building levels quest (currently requires exhausting nearby quests and trigering quest fetching).

**Comment by matkoniecz** [comment]
Current query is

> "ways, relations with roof:levels and roof:levels!=0 and !roof:shape";

After dropping roof:levels!=0 requirement it makes no sense to wait for roof:levels. So as result it ends in something like https://github.com/westnordost/StreetComplete/compare/master...matkoniecz:277?expand=1 (this building list should not be duplicated between querries, that would be fixed if I would make a PR)

@westnordost Would you prefer to change behavior as proposed here or keep the current one?

**Comment by westnordost** [comment]
Keep the current one. I think to ask users for basically flat roofs which roof shape it has is something where the annoyingness of repetitively answering "no, flat!" far outweighs the value. Even more so than for street surface, but street surface is much more valuable information.

**Comment by HolgerJeromin** [comment]
All 3D visualisations i know default to gabled.
And often the roof is not high enough to have level of 1.
imo roof shape is more important than the surface of a tertiary.

**Comment by pkoby** [comment]
I would agree with Holger. I have been trying to understand this quest with the building levels quest. As it is presented with the image in the levels quest, roof:levels would refer only to stories/floors internal to the roof, probably with windows.

However, in my area, many buildings have a non-flat roof that I would not count as a storey, but should not be discounted.

One thought I had would be to consider roof:levels to refer to either an actual storey or the equivalent size of roof. Then I would say a non-windowed roof area would be 1 level. However, many roofs are not a whole storey high. I would tag a 0.5 level, but SC doesn't allow partial values. 

Alternatively, I would welcome the roof:shape quest to ask for all buildings. In my area, it would not be a case of constantly tagging =flat, but probably =gabled. If only the roof:shape quest is answered, I think renderers would assume building:levels=1, roof:levels=0, but still render a gabled roof (at least F4Map would?).

Thoughts? Alternatively, how would I tag things in SC to get a roof shape on all buildings?

**Comment by westnordost** [comment]
I know very well that buildings that have 0 roof levels can still have a non-flat roof shape, that it is correct tagging. Likewise, there may be trunk roads that do have another surface than asphalt, residential 20km/h roads that have cycle lanes, unpaved streets that have street-lighting etc.

However, there are many countries, where the default roof shape is flat. In fact, so default that basically every building there is has a flat roof. Example: https://www.google.com/maps/@28.0184242,73.3080841,1005m/data=!3m1!1e3

And this is not only the case in certain countries. Many/most modern business districts or otherwise city center districts are full of these kind of high-rise buildings that do not have a roof.

Asking for every single building that previously was already tagged with zero roof levels what kind of (even less relevant than usually) roof shape it has, would mean to massively spam users with this question.
This is also part of the quest guidelines, by the way.

**Comment by pkoby** [comment]
That's fair. I guess it would be really nice for my area to have the quest, but I understand if it's not something SC will have. It's a bit annoying to have roof:shape for some houses in a neighborhood (because some houses have roof:levels=>0) and have to resurvey, but I get that this app cannot have everything and still be simple for every user.

**Comment by matkoniecz** [comment]
And in this case change is relatively simple - see https://github.com/matkoniecz/Zazolc/commit/00e1cca52293a6f16ec48dfa02f8dfe2d0f5540e

**Comment by pkoby** [comment]
Cheers! I figured it out and it works as I want it to.

**Comment by smichel17** [comment]
Adding keyword to aid future searching: type roof:type

**Comment by Atrate** [comment]
@matkoniecz Are you gonna release Zażółć apks on Github if someone wanted to use it?

Tried to compile, but it fails

**Comment by smichel17** [comment]
@Atrate If you can build streetcomplete, you can then add the Zażółć repo as a remote, `git fetch --all`, and `git cherry-pick 00e1cca`

**Comment by Atrate** [comment]
Oh yes, I forgot you could do that with git, thank you!

**Comment by matkoniecz** [comment]
> Are you gonna release Zażółć apks on Github if someone wanted to use it?

Not planning, as it includes several things that are either without proper interface, known to be crashing, behaving in weird way, require external editor or being in an early testing stage.

It is intended as a fork for a private use, without any attempt to make it usable by others.

I am not opposed to others using parts of code (or all of it), but it is "do it on your own risk".

But compiling should work (I enabled issues on fork repo).

----

In general, parts usable by general public are already in SC. Except tiny unimportant parts that were rejected, like name quest for `waterway=stream` `=river`, but it is not worth releasing a fork.

**Comment by peternewman** [comment]
@westnordost , a thought, given there seem to be at least a few people who wish to fill in the roof level quest for roofs with no floors, what about having it disabled by default with a suitable warning, would that compromise keep everyone happy?

**Comment by westnordost** [comment]
For this case, or rather for cases like these, I think it makes more sense to enable quest-specific settings in the future. There are more quests that could profit from a responsible use of "showing more" quests of a type.

**Comment by smichel17** [comment]
Just thoughts:

1. I wouldn't mind just disabling roof type by default. There are many houses where I live with roofs that do not fit any of the shapes perfectly, but are close enough that I'm not comfortable picking "It has multiple shapes", either. So it can be very hard to answer. Given that it's only useful for 3d visualizations, as far as I know, I actually just disabled the quest altogether.
2. Partially inspired by #1749 -- It would be interesting if we could dynamically prioritize quests based on what a user has already completed. For example, if I have never completed a roof quest, reduce their priority. Tricky to implement, though (risk of doing the wrong thing).
