### ISSUE TITLE
Add bench and other attributes to public transport platforms

### ISSUE THREAD

**Issue by gileri** [westnordost/StreetComplete#278]
Public transport (bus, tram etc) platforms could benefit from more easily defined attributes :

- Does the bus stop have a bench ?
  - Useful for people which can not stand for long periods
  - Tag : bench=yes/no
- Does there is a trash bin ?
  - Tag : bin=yes/no

More difficult to appreciate but possible imo :

- Is the stop accessible in wheelchair ?
  - ie specific signage, or if there is a sloped curb nearby and no obvious obstacles to wheelchair movements
  - Tag : wheelchair=yes/no

**Comment by CloCkWeRX** [comment]
Similar
 * #212 - subway_entrance wheelchair=yes/no
 * #26 - Wheelchair access

**Comment by gileri** [comment]
Huh, I don't know how I didn't find those while searching before submitting the issue...

Wheelchair access could also be plugged into #212 as it's similar enough imo.
