### ISSUE TITLE
Housenames

### ISSUE THREAD

**Issue by westnordost** [westnordost/StreetComplete#281]
It has been requested to extend the housenumber quest to enable specifying housenames.
It makes sense to request this information right in the housenumber quest, because there is not other point in time where it makes sense to ask for a housename (as most houses have no names).

I think the best way to implement this would be to offer an option in the "Other answers..." menu called "It has a housename". On clicking it, the form transforms into an input where one can specify both a housenumber and a name. In this form, the user can leave the house number empty (he usually may not).

Another option would be to provide an option for all quests to submit the form but _also_ leave a note (i.e. "these are the opening hours BUT the name changed to xyz". This is a feature that goes around in my mind some time already but I haven't had an idea yet how to squeeze this it into the UI and if it is worth over simply leaving a note.

Apropos simply leaving a note, I am going back and forth on the idea of implementing this at all, since the user can simply leave a note in the rare case that a house has a name. Anyway, this has no high priority for me, just wanted to write it down. Ideas, opinions and PRs are welcome.

**Comment by Mannshoch** [comment]
What do you think I'm new in Mapping but wouldn't it better to map the entrance as Housenumber?
Could we use [/Key:entrance](https://wiki.openstreetmap.org/wiki/Key:entrance) to setup entrances? If we get asked what the House number is, we maybe could also add the entrance into the map on the contour of the house.

**Comment by westnordost** [comment]
Yes, if a house has several entrances, tagging the housenumbers on the entrances is better. However, StreetComplete is too simple, you can only add taggings to already existing elements (i.e. the house).

**Comment by CloCkWeRX** [comment]
For 
>Apropos simply leaving a note
... what about just making a dedicated form for it; somewhat like vespucci has; seperate from quests?

 * Select 'new note' control, which shows a crosshair or similar to precisely locate it
 * Key in details
 * Save/publish

![image](https://cloud.githubusercontent.com/assets/365751/26766908/32901c56-49d9-11e7-84c1-d1aaea47b832.png)

![image](https://cloud.githubusercontent.com/assets/365751/26766962/ee34cede-49d9-11e7-8fd4-60a27aa849c0.png)

It would possibly solve the 'I made a mistake' case; as well as "I'm looking at something, but not being prompted to add it"

**Comment by westnordost** [comment]
Yes, isn't there a ticket for that already? I though there is. Otherwise, please open a new one for that and best delete the stuff here. One ticket, one issue.

**Comment by Mannshoch** [comment]
Would you say that if a house only has one entrance you have to put the housenumber to the building and if it has more then one number you have to put it as entrance? because in A vilage i looked ed on openstreetmap all hauses even with only one number had a point called addres on it but also without a housenumbe. 

 I tryed to work with vespucci but it a pain. But maybe you could add some of it's code to add entrances and maybe remove wrong points.

**Comment by westnordost** [comment]
Both are valid. Personally I only put the housenumber on entrances if there are several with different housenumbers because there is no information value gain for doing that with houses with only one entrance.

Am 5. Juni 2017 14:35:33 MESZ schrieb Mannshoch <notifications@github.com>:
>Would you say that if a house only has one entrance you have to put the
>housenumber to the building and if it has more then one number you have
>to put it as entrance? because in A vilage i looked ed on openstreetmap
>all hauses even with only one number had a point called addres on it
>but also without a housenumbe. 
>
>I tryed to work with vespucci but it a pain. But maybe you could add
>some of it's code to add entrances and maybe remove wrong points.
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/westnordost/StreetComplete/issues/281#issuecomment-306176869

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by tomchance** [comment]
I used your app for the first time over the weekend, sitting on a couple of buses.

In London it's quite common for blocks of flats or commercial buildings to display addr:housename on the outside, but not to indicate the addr:housenumber. In terms of navigating and searching, the two are equally useful. One often looks for "Heron House on Lyndhurst Way" or "Mordaunt House on the Pelican Estate" for example, and often without any idea of a house number.

For some buildings the app asked me to add a house number when there wasn't one visible, and upon checking later I found the housename had already been entered. For others the housename wasn't in OSM yet and I could have added it.

So I'd suggest:

* the house name is shown on the form along with the house number, as standard
* both/either are pre-filled where the data is already in OSM
* it let's you say for either that you can't say any more - there's no name or number visible (though such data might in fact exist and be obtainable from another source)

**Comment by westnordost** [comment]
> For some buildings the app asked me to add a house number when there wasn't one visible, and upon checking later I found the housename had already been entered. For others the housename wasn't in OSM yet and I could have added it.

True, but there are also places which only have house names and not house numbers. Changing the implementation like you suggest would create a lot of unanswerable quests. (Users are prompted to enter a housenumber, but there is none.) So, this can't be done.

**Comment by westnordost** [comment]
Today, I learnt that there are places in the world, where in fact **only** housenames are used (or at least, are the only thing visible from the road), such as Punta del Este.

**Comment by westnordost** [comment]
Ok, implemented.

**Comment by rugk** [comment]
BTW, @westnordost, you can also (automaticaslly) [let issues close](https://help.github.com/articles/closing-issues-via-commit-messages/) when you push a commit. Then, you don't have to manually close it afterwards.
