### ISSUE TITLE
Change language in Settings

### ISSUE THREAD

**Issue by Monduiz** [westnordost/StreetComplete#29]
May I suggest that language may be changed in settings? In my experience, it is best to have this option activated by users and accessible somewhere.

**Comment by westnordost** [comment]
The app uses the system language. Are you suggesting that this setting should be overriden? That would be quite unusual.

**Comment by westnordost** [comment]
So, yeah, you don't see other languages because Italian, French etc will be added for version 0.5. I will close this one.

**Comment by Monduiz** [comment]
Ok, I see. The app takes the language from the OS.
