### ISSUE TITLE
Getting points in StreetComplete when using other apps?

### ISSUE THREAD

**Issue by ericblank** [westnordost/StreetComplete#290]
There's a lot of unlabeled paved streets in my area. Instead of manually tagging them all one by one with streetcomplete, is there a way to mass-tag them in josm and get credit in streetcomplete? maybe a specific changelog comment or something?

**Comment by westnordost** [comment]
Eh, no. Just use JOSM, man!

**Comment by ericblank** [comment]
thanks, i was just thinking of when it's done being gamefied :-)
