### ISSUE TITLE
Crashes when I answer the "which sport" quest

### ISSUE THREAD

**Issue by arnaud-jacquemin** [westnordost/StreetComplete#291]
Hello,

Every time I try to answer the question "_For which sport is this pitch made?_" for this specific place : http://www.openstreetmap.org/way/95069556, StreetComplete crashes when I click "OK"

![recording_20170604_073857](https://cloud.githubusercontent.com/assets/1387489/26764055/9e47808a-495f-11e7-9fef-224276b148f1.gif)

The answer is "_Field hockey_".

I am using version 0.11 via F-Droid.

Thanks in advance

**Comment by westnordost** [comment]
Good catch! And I know exactly what the problem is already.

Am 4. Juni 2017 20:09:33 MESZ schrieb Arnaud Jacquemin <notifications@github.com>:
>Hello,
>
>Every time I try to answer the question "_For which sport is this pitch
>made?_" for this specific place :
>http://www.openstreetmap.org/way/95069556, StreetComplete crashes when
>I click "OK"
>
>![recording_20170604_073857](https://cloud.githubusercontent.com/assets/1387489/26764055/9e47808a-495f-11e7-9fef-224276b148f1.gif)
>
>The answer is "_Field hockey_".
>
>I am using version 0.11 via F-Droid.
>
>Thanks in advance
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/westnordost/StreetComplete/issues/291

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.
