### ISSUE TITLE
Not rendering road over building correctly

### ISSUE THREAD

**Issue by winfried** [westnordost/StreetComplete#292]
First of all compliments for streetcomplete, it is very accessible and fun!

At de 'Oudegracht' in Utrecht there is a side walk with terraces right at the water, with restaurants in cellars at the same level. Above it is the (main) street. To get the picture:

![bezembrug](https://cloud.githubusercontent.com/assets/607036/26764929/652cc082-4971-11e7-801b-d2d6e2fe7b7e.jpg)

https://www.openstreetmap.org/#map=19/52.09157/5.11863 renders it correctly:
![bezembrug_osm](https://cloud.githubusercontent.com/assets/607036/26764956/d81985a8-4971-11e7-9034-b9291ed75506.png)

Streetcomplete renders the structures under the main street above it, so it becomes hard to judge what road to answer the question about: 
![bezembrug_streetcomplete](https://cloud.githubusercontent.com/assets/607036/26764980/200b2baa-4972-11e7-9425-fb7f3edb3354.png)
I guess the layering has to be a bit more advanced...

**Comment by matkoniecz** [comment]
Have you tried reporting it at https://github.com/tangrams/cinnabar-style/issues ? In my experience ( https://github.com/tangrams/cinnabar-style/issues/26 ) it works quite well.

**Comment by matkoniecz** [comment]
See also

> The cinnabar style should be considered more or less read only. Maintaining a fork of this here adds too much maintenance work. I'd like to encourage you start a new very simple SC style from scratch, that only displays the information needed specifically for this app. This will be easy to maintain as well.

by @westnordost at https://github.com/westnordost/StreetComplete/pull/271#issuecomment-305865869

**Comment by westnordost** [comment]
Yes, this should be fixed upstream. Please create a bug in https://github.com/tangrams/cinnabar-style/issues or directly create a PR for that.

**Comment by nvkelso** [comment]
@westnordost This will be a two part fix, so suggest:

1. re-opening this issue to apply the fix described below, and 
2. you'll need to pull in a new version of the Cinnabar style with a Mapzen fix tracked in https://github.com/tangrams/cinnabar-style/issues/30.

**Per point 1 above, turn off 3d building extrusion in the style:**

https://mapzen.com/documentation/cartography/api-reference/#building-extrusion

You need to set `sdk_building_extrude: false` in the global section. Since you're in Tangram ES it'd look something like:

```
map->loadScene(
    "https://mapzen.com/carto/refill-style/6/refill-style.yaml",
    false,
    { SceneUpdate("global.sdk_mapzen_api_key", "mapzen-xxxxxx"),
      SceneUpdate("global.sdk_building_extrude:", "false") }
);
```

The Mapzen documentation needs to be clarified, I'm tracking that in https://github.com/tangrams/cartography-docs/issues/27.

The rest of the Mapzen basemap styles show the path correctly above the buildings, should be a minor fix to bring Cinnabar (and Zinc) into order.

**Comment by westnordost** [comment]
But I don't want to turn off extruding buildings. Extruded buildings are cool. If the bug can only be fixed by turning the feature off, I rather will not fix this bug.

**Comment by nvkelso** [comment]
There's another option, here's that area in a new version of Refill I'm noodling with:

<img width="729" alt="screen shot 2017-06-09 at 12 57 24" src="https://user-images.githubusercontent.com/853051/26992369-3a89f098-4d13-11e7-972b-c8abd9936919.png">

_Most_ but not all terrace "basement" buildings are tagged `layer=-1` here so filtering on that in the style I can tell them **not** to extrude. Fixing that will need a stylesheet change still. I'll leave it up to you if you want to keep this issue open to ingest the new stylesheet or not.

I'll track implementing that in the aforementioned Cinnabar issue.

**Comment by nvkelso** [comment]
I've finished updating Cinnabar in https://github.com/tangrams/cinnabar-style/commit/41f7108a14bd51fe968d2e8d7950763a4a977bfe, planned for release Tuesday of next week.

**Comment by nvkelso** [comment]
(So all other buildings will extrude but these "basements" – the only change you need to make is to pull in new version of the scene file).

**Comment by nvkelso** [comment]
This fix is now live on the Mapzen CDN and released on Github:

https://github.com/tangrams/cinnabar-style-more-labels/releases/tag/v7.0.2
