### ISSUE TITLE
Select or prioritize quests

### ISSUE THREAD

**Issue by winfried** [westnordost/StreetComplete#293]
The area I live in, has 1450 houses in less then one square kilometre and from those houses 1415 are three stories high, including one layer of roof. Though I love to update the map, I don't fancy entering literary thousands of times '3-1' at the building levels while surveying my neighbourhood. I would rather use my time to fix issues with the streets or POIs. Would it be possible to add a interface to prioritize certain queries or filter certain queries?

**Comment by matkoniecz** [comment]
Duplicate of #35, #263

**Comment by winfried** [comment]
Sorry for missing those two
