### ISSUE TITLE
Rank address housenumber quests higher than building/house level quests

### ISSUE THREAD

**Issue by CloCkWeRX** [westnordost/StreetComplete#294]
This is a more specific thing than #35 

Addresses are useful for routing & geocoding; and are harder to determine due to a lot of edge cases.

Building levels quests currently appear first for a given building. These do make the map more 'complete', but arguably are less useful for data consumers (3d rendering is the main use afaict?)

In terms of default priority, I feel addresses are more important/useful to capture.

**Comment by HolgerJeromin** [comment]
In my experience this is the case. 
With "naked" detached buildings I had housenumber, levels and after that roof shape.

**Comment by matkoniecz** [comment]
@CloCkWeRX 

Can you give an example of place where it happens?

**Comment by westnordost** [comment]
You feel it has the same priority because currently there is no "order" in which the markers are displayed on the map. There is an order generally for the quests, but it is only applied to which quests get downloaded first. This is something that may change in the long run, currently it is technically not possible.

**Comment by matkoniecz** [comment]
> currently it is technically not possible

I tried to find relevant issue at https://github.com/tangrams/tangram-es/issues but failed - is it maybe blocked by something else or simply not reported?

**Comment by westnordost** [comment]
Hmm, perhaps it is possible. Basically, the "priority" key in the streetcomplete.yaml must be dynamic based on the type of quest. I made it dynamic for the sprite to be used using a simple js function, perhaps the same would be possible with the priority. Would need to try it out.

**Comment by westnordost** [comment]
If you'd like to investigate, I can reopen the ticket and assign it to you

**Comment by matkoniecz** [comment]
>  I can reopen the ticket and assign it to you

OK, I will try to figure it out.

**Comment by westnordost** [comment]
If it is not possible easily, don't bother. Sooner or later, the streetcomplete.yaml (and the spritesheet of quests) should be dynamically created by the build script.

**Comment by westnordost** [comment]
Hm I can't assign it to you. GitHub limitation?

**Comment by matkoniecz** [comment]
> Hm I can't assign it to you. GitHub limitation?

I guess that one may assign to original reporter and collaborators on a given repo?

**Comment by matkoniecz** [comment]
fixed by #321, may be closed
