### ISSUE TITLE
Quest for house number for unspecific buildings

### ISSUE THREAD

**Issue by dontub** [westnordost/StreetComplete#297]
There should be a quest for house numbers for unspecific buildings, though in some cases those buildings might not have a house number. I've used StreetComplete in a village where multiple buildings which are houses or apartments have no building type set and wasn't able to add the house number.

**Comment by HolgerJeromin** [comment]
I tagged all residential buildings in my hometown to =apartments,  =house or =detached . 
Having a quest for housenumbers would be not a good idea  as every garage or shed in the garden would be shown.

**Comment by dontub** [comment]
To tag the correct building type is of course the preferable solution, though this is not possible with StreetComplete, yet #25. Uniil then it is IMHO better to quest for house numbers on buildings without specific type then to forego the chance to have the number added, even though there might be a garage (or something else) that is not tagged appropriate.

**Comment by HolgerJeromin** [comment]
In many residential areas everyone has a garage or a shed. Do you really want one or two false positive house number quest for every. single. house? 

This would make the app completely unusable at least in some areas. 

Asking for house numbers without the possibility to tag (!) the reason why this building has no own number would result in asking for clarification for building=yes two times on the long run. 

Send the people to every garage for a house number now. They have to select "has no number" (which is saved on device only). After implementing #25 send them again(!) to every garage for proper classification.

**Comment by matkoniecz** [comment]
This restriction is intentional to avoid creating false positives for every single shed, garage, chicken coop etc tagged as building=yes.

**Comment by westnordost** [comment]
See @HolgerJeromin and @matkoniecz 

If you want to push towards that #25 is implemented (it will be sooner or later), you can contribute by searching for good and representative pictures for all the buildings. The ones in the wiki are not always good and generic enough to be representative (worldwide).
