### ISSUE TITLE
clear privacy description needed

### ISSUE THREAD

**Issue by gdt** [westnordost/StreetComplete#3]
I am pretty sure what the app does is ok, but there should be a clear statement of what it does with location data in terms of fetching and uploading data.    Presumably other than some kind of data download in the region around the current location and uploading of commits of answered questions, no information would be sent anywhere else.  But it would be good to make that claim, if true.

**Comment by westnordost** [comment]
Where do you think this statement should go? You mean just somewhere in the "About" menu or here on Github?

**Comment by gdt** [comment]
I'm not sure, but for now I would vote for a section in the README.md on github.   I personally want to understand how an app will behave before I even install it.   This is a larger issue within Android, where there isn't documentation in the form of a manual for each app, so I suspect there isn't an agreed-on place for it.   Overall I think having it someplace findable is the most important thing, and exactly where is not that important.

**Comment by westnordost** [comment]
This sounds like the best place for this would be the description in the google play store / F-Droid repository. I think I will add a broad description there and go into more detail in the about menu within the app. So this issue will stay open until I did this

**Comment by gdt** [comment]
That sounds good, but please put it in README.md (or even better, link to it), so that people looking at github find out too.  I suggest you put a file in the sources, and that can be the source for play/fdroid.  Thanks for listening.

**Comment by westnordost** [comment]
The privacy statement is here:
https://github.com/westnordost/StreetComplete/blob/master/app/src/main/res/raw/privacy.html
or within the app in the **About** menu

**Comment by gdt** [comment]
Sorry, I missed the message with the draft.   Thanks for doing that, and it definitely addresses the issues.  The only tiny thing I'd add is about queries to overpass and mapzen not having any identifiers other than  of course IP address.

Basically, my view is that when you decide to do a quest and make a change, that is public, just like any other OSM editor.  It's more the background of loading  at other times that I was curious about.
