### ISSUE TITLE
uploading to / downloading from a POSM server?

### ISSUE THREAD

**Issue by johnwhelan** [westnordost/StreetComplete#30]
In some parts of the world the internet doesn't exist.  The American red cross have come up with a remote OSM server but it would need the ability to change the pointer in the software to a different server.

This is slow time but I suspect it will be of great interest to the HOT NGOs.

John

**Comment by westnordost** [comment]
Could you give me more info on this?

**Comment by johnwhelan** [comment]
Essentially its a intel NUC running ubuntu and everything you need for a mapathon without the internet.  It's sort of beta but the Red Cross are running in the field in multiple instances.  It uses a WiFi card so laptops and smartphones into a private copy of OSM then the new stuff is uploaded back to OSM when they get to civilisation.

Note smartphone. They use $50 ones and one of the things they're interested in is adding detail after the armchair mappers have been in.

In Zambia at the moment one bit of local government is adding building details much the same as Bjenk.  With smartphones and streetcomplete they can map things like water taps, toilets, building material used for houses etc. This stuff they need for city planning etc. 

I don't have an instance of POSM running yet but I have what is thought to be a suitable laptop so when the documentation improves I'll play.

https://github.com/posm/posm

Cheerio John

**Comment by johnwhelan** [comment]
More information here:

http://stateofthemap.us/2016/field-mapping-at-scale/

**Comment by westnordost** [comment]
That looks like a very interesting project, StreetComplete could indeed be a handy tool forthat, perhaps with a few adaptions built into an own product flavor, as you indicate. There are probably certain adaptions that would only make sense in the frame of HOT NGOs and/or the POSM projects, others can go upstream.

A few notes on that:
- Note that StreetComplete communicates both to the main OSM API to upload changes and to an Overpass API instance to find the quests. If it needed to work completely off the Internet, then an Overpass instance would need to be available in the local network as well.
- Currently, StreetComplete is only about adding details to existing elements. Adding new POIs is not planned in the near future. Maps.ME can do that, I think.

**Comment by johnwhelan** [comment]
JOSM can switch to different openstreetmap databases.  For example FOSM or Fork of OpenStreetMap users use JOSM But with a different connection point or url.

The Overpass side might be trickery but I'm sure with enough motivation the Red Cross can add it to their magic box.  Having said that streetcomplete can store the results for currently up to a week.  I'm sure that could be extended to say two or three weeks as a temporary work round.

Usually the first pass is armchair mappers adding buildings, the second pass is adding detail to the buildings so no creating new buildings would be required.  These sort of projects work with building outlines so OSMand doesn't work, as it only allows you to add tags to a POI not an outline.

**Comment by westnordost** [comment]
StreetComplete can actually store results for an unlimited time. That option is only relevant if Auto-Sync is on and it only means that X days have to passt until StreetComplete will re-check if the downloaded quests are still current (i.e. they could have been solved by other people).

So, write me here if/when the POSM/Red Cross guys were able to set up an Overpass instance on their magic box. Creating an option to change the server address(es) can be implemented quickly.

**Comment by johnwhelan** [comment]
Thanks

I suspect it might well take a little time for the POSM guys to get their
act together.

Cheerio John

**Comment by matkoniecz** [comment]
@johnwhelan And what they said?

**Comment by westnordost** [comment]
Well, let them open a ticket then if they are interested.
