### ISSUE TITLE
Do not add names which equals the current ref on roads

### ISSUE THREAD

**Issue by boothym** [westnordost/StreetComplete#301]
I did search for "name ref" and found issue #5 but this might be slightly different.

Where a road already has a ref tag, if a user adds a name which is equal to the ref tag, it should not be added to the map. Here is the example which prompted me to open this issue: https://www.openstreetmap.org/changeset/49244440 - as you can see these roads already had ref=A9 before name=A9 was added to the map: https://www.openstreetmap.org/way/33908517/history

**Comment by westnordost** [comment]
This looks like a bug. The app should not ask for the name if a ref is available.

That is weird. I claimed in #5 that the app is not asking for road names if a `ref `is already present. But this is clearly not the case right now. This needs to be fixed.
