### ISSUE TITLE
regularShoppingDays: 5 in Poland

### ISSUE THREAD

**Issue by matkoniecz** [westnordost/StreetComplete#306]
I propose to set regularShoppingDays to 5 for Poland.

It is based on observation that most objects has special opening hours for Sunday and Saturday so on filling opening hours the first step is typically to unmark Saturday to set weekday opening hours.

recovered from #296

**Comment by westnordost** [comment]
I'll leave a comment here when you can add this to the configuration files okay?

**Comment by matkoniecz** [comment]
OK, probably this will be a trivial PR as it is edit in a config file.

**Comment by matkoniecz** [comment]
done in https://github.com/westnordost/StreetComplete/commit/aab7e8170aff4f036e9905157d9fb3644beafad2
