### ISSUE TITLE
refetch quests on detection that uploaded quest was already done

### ISSUE THREAD

**Issue by matkoniecz** [westnordost/StreetComplete#307]
To my surprise manual refetching quest in my area caused several quests to disappear. It was caused by somebody else solving them.

Without manual refetch I would not notice anything and would go to solve quests that were already solved (some people would be irritated by lack of star points).

It may be smart to refetch quests if app becomes aware that in given region some quests recently were solved - edit conflict on edit attempt seems to be an obvious signal.

**Comment by westnordost** [comment]
Good idea. Actually, better would be that on conflict, the "quest cache" is cleared for the area the user is in. So, users who do not use auto sync profit from that as well (because then the "scan for quests here" option will not simply answer "Nothing more to download").

**Comment by matkoniecz** [comment]
> is cleared for the area the user is in

rather for area the quest is in (user may be lacking internet access at time of solving already solved quest and upload answers later)
