### ISSUE TITLE
Add StreetComplete name to notes

### ISSUE THREAD

**Issue by boothym** [westnordost/StreetComplete#308]
I've seen a few notes from StreetComplete and was confused until I realised which app created the note. For example this note http://www.openstreetmap.org/note/1019058 says:
>In reply to "What is the name of this road?":
Footpath

The note should make it clear where it has come from as it's not written by a normal user on the OSM website, Maybe change it to:
>Submitted from the StreetComplete app - in reply to the question "What is the name of this road?"
Answer: "Footpath"

**Comment by westnordost** [comment]
For this example, changing "in reply to" to "Unable to answer" would clarify this better. Or perhaps

> Unable to answer "What is the name of this road?", comment: 
> Footpath

?

**Comment by boothym** [comment]
Well that's a separate issue to the lack of app name in the note - it was the only example note I could find.

**Comment by westnordost** [comment]
My point is: if the note itself is clear, the app name does not need to be there. In fact, I wouldn't know how the app name would help to clear it up.
See #247

**Comment by boothym** [comment]
For a start it would let people know about your app! 😄 

As mentioned in https://github.com/westnordost/StreetComplete/issues/247#issuecomment-304956689 it is confusing when you first see and try to understand where the note has come from. It's like when you see a note submitted by maps.me - you know what you're dealing with!
