### ISSUE TITLE
easier opening hours with half hours

### ISSUE THREAD

**Issue by Haikuch** [westnordost/StreetComplete#31]
setting an opening hour like 7:30 - 12:30 is tedious because you have to scroll through each of the 30 minutes. Because most of the times should be either *:00 oder *:30 they should be easier to choose. Or is that a operating system component? Because there is a lot of free space on the time choosing page there might be even other possibilities to choose the hours and minutes than the scrolling menu.

**Comment by westnordost** [comment]
Yes, this is an Android component. On older versions, the time picker still looks [like this](http://i.stack.imgur.com/2A3kx.png).

**Comment by johnwhelan** [comment]
I like the new one.  You can just click on the 30 directly.

John

**Comment by westnordost** [comment]
Oh wait, so you have an old Android, Haikuch? Android pre 5.0 (Lollipop) will have the classic picker.

Perhaps it is possible to get the new component into an old Android via the compatibility libraries.

**Comment by Haikuch** [comment]
yes its an old one, so its not an issue for this repo when its based on the sys components
