### ISSUE TITLE
id reuse race condition

### ISSUE THREAD

**Issue by matkoniecz** [westnordost/StreetComplete#310]
It seems possible that following may happen:

- user fetches quests, including quest for object with a given id (lets say that it is building with way id 190)
- quests stay in cache (with longer time it is more likely, but it is always possible)
- somebody else edits object and as result way with id 190 is now describing lake (for example somebody split/moved road, or somebody deleted object and id was reused in object created later[1])
- quest is solved
- StreetComplete makes edit that makes no sense whatsoever

[1] see https://www.openstreetmap.org/node/1/history for example of node that was recreated with completely different meaning and location

It is going to be quite rare but it is not impossible (I already encountered this situation, as result of editing with StreetComplete and Vespucci at the same location with badly mapped road - as I was aware what is happening I avoided last part and no ridiculous edit occurred). But given that many people use this editor this kind of problematic edits will sooner or later occur.

Maybe StreetComplete should remember location of quest and at least in cases of major movements do not apply edit? Remembering exact geometry is not ideal, as minor changes are OK.

It is open question whatever effort necessary to fix that is worth avoiding this possibility of problems.

**Comment by westnordost** [comment]
Yes, this is indeed a possible problem, though unlikely. The solution is to reintroduce the method _boolean appliesTo(Element element)_ to the interface OsmElementQuestType and implement it in every subclass. For SimpleOverpassQuestType it is easy (just use the overpass filter string).

On upload, if there is an element conflict and as a result of it, the new version of the element in question is downloaded, the OsmQuestChangesUpload must call questType.appliesTo(downloadedElement) before applying the changes and uploading.

**Comment by westnordost** [comment]
Implemented in frame of another ticket
