### ISSUE TITLE
Don't remove existing quests on rescan until rescan is finished

### ISSUE THREAD

**Issue by jancborchardt** [westnordost/StreetComplete#311]
I often have a bad mobile internet connection (even in Berlin, yes it happens). The other day I wanted to fix some things on the way home. Halfway I hit rescan just in case there were new/other things.

This resulted in all quests vanishing, and they only came back after I returned home and had wifi. I'm assuming this was because of the bad connection.

**Comment by westnordost** [comment]
Quests are not removed on rescanning, only specifically those that had been solved (by other people) already. 
Please try to reproduce this. I suspect that the quests were vanishing because the quests were being redisplayed on the map. Did you try zooming in/out, did they appear then?
