### ISSUE TITLE
New Queestion: water well / fontain / waterpoint / watering_place

### ISSUE THREAD

**Issue by Mannshoch** [westnordost/StreetComplete#312]
In Switzerland are very much drinking water well. In Osmand are many of these described as fontain even they are water well or waterpoint.
Please add a Question to set if it is a water well, fontain, waterpoint, watering_place and if it is drink water or not.
the rule in Switzerland on public ground is that, if there is no  "Kein Trinkwasser" (no drink water) sign you could drink it. Outside on non Public ground it depend on the owner. Answers should be yes, no, unknown.
Most but not all drinking water well on public ground in Switzerland contain a year of building.

See also:
https://www.srf.ch/sendungen/puls/alltag-umwelt/wasser-ist-nicht-immer-zum-trinken-da

**Comment by Mannshoch** [comment]
Hmm...
Better ask this way:

1. driven by local government - yes/no/unknown
2. has a "Kein Trinkwasser" (no drinkwater) sign - yes/no
3. is a fontain, water well, waterpoint, watering_place
4. insert name / year of building if available

**Comment by matkoniecz** [comment]
> driven by local government - yes/no/unknown

Can you link to OSM wiki page describing the tag?

**Comment by matkoniecz** [comment]
> many of these described as fontain even they are water well or waterpoint.
> Please add a Question to set if it is a water well, fontain, waterpoint, watering_place

It is unclear for what kind of tags quest is supposed to be created. Can you clarify it?

**Comment by Mannshoch** [comment]
>> driven by local government - yes/no/unknown
>> has a "Kein Trinkwasser" (no drinkwater) sign - yes/no

> Can you link to OSM wiki page describing the tag?

The Idea behind this Questions is to get a more Qualified answer. Because in Switzerland Drink water is not setup as drink water but thats only given on a well driven by government. I would like to ask this two question to get the description drink water.

http://wiki.openstreetmap.org/wiki/Key:drinking_water
http://wiki.openstreetmap.org/wiki/Tag:amenity%3Dwatering_place
http://wiki.openstreetmap.org/wiki/Tag:amenity%3Ddrinking_water
http://wiki.openstreetmap.org/wiki/Tag:amenity%3Dfountain

I'm not a professional mapper I started only to use your app since some weeks but got some information by searching in Internet.

**Comment by Mannshoch** [comment]
My English is not the best. I found following tag also.
http://wiki.openstreetmap.org/wiki/Tag:man_made%3Dwater_tap
I'm not sure under which tag following kind of Well, water tab goes:
http://www.sehenswertes.ch/sehenswertes/schweiz/brunnen/brunnen.html

**Comment by westnordost** [comment]
You cannot ask "is this really a fountain?" when something is mapped as a fountain because if the user answers "yes, it is a fountain", then the quest would be displayed again next time the quests are downloaded.

What you can ask is "Is the water from (this fountain) drinkable?". Though, I claim that it won't be the case that outside switzerland (worldwide) it can be reliably determined by looking at a sign.

So, I think this is not quest material.

**Comment by Mannshoch** [comment]
Such kind off quests could be made if Informations on map is older then a specific time (maybe around 15year since last update) .

**Comment by rugk** [comment]
A related quest suggestion is https://github.com/westnordost/StreetComplete/issues/549, BTW.

But I agree with @westnordost, you can't ask this. What you ask for is a tag "lastcheck" or so (see alos https://github.com/westnordost/StreetComplete/issues/314), this is however not currently intended/possible in OSM and we already had discussions about it here.
