### ISSUE TITLE
on the first run blue location dot is not displayed

### ISSUE THREAD

**Issue by matkoniecz** [westnordost/StreetComplete#318]
To reproduce: uninstall app, install again (either via adb or from store)

![screenshot_2017-06-12-20-48-34-441_de westnordost streetcomplete](https://user-images.githubusercontent.com/899988/27050163-d9d95670-4fb1-11e7-9c06-5897080de40f.png)

**Comment by Binnette** [comment]
:+1:  I encounter this bug many times... But i was too lazy to report it or try fix it thanks ! :sweat_smile:
On my phone, it happens sometimes when i run the app (and not only after install). When it happen, i'm used to close the app, and run it again.

**Comment by westnordost** [comment]
Interestingly the accuracy circle is, even though they are created the same way. Only difference: 

`locationMarker.setStylingFromString("{ style: 'points', color: 'white', size: ["+TextUtils.join(",",sizeInDp(dot))+"], order: 2000, flat: true, collide: false }");`
is set immediately once and then not again (as opposed to the accuracy circle, which updates all the time).

This will be a tangram-es issue. When you create a bug report, add your Android version, device etc., as usual.

**Comment by matkoniecz** [comment]
In my case it is 

Device (Manufacturer and Model) - Redmi 4 Xiaomi
Android Version - 6.0.1 MMB29M

(I have not created tangram-es issue as I have no idea what happens here and would prefer to understand it before reporting bugs)

**Comment by westnordost** [comment]
But you reported a bug!

**Comment by matkoniecz** [comment]
It was "something is wrong with SC" and it was quite easy to check that the SC is wrong (rather than a bug introduced by my own changes). But I would prefer to understand how tangram-es is used before reporting it as a tangram-es bug.

**Comment by westnordost** [comment]
So, what about this? I can't reproduce this on my phone.
