### ISSUE TITLE
Working off line user unfriendly message

### ISSUE THREAD

**Issue by johnwhelan** [westnordost/StreetComplete#32]
I have a couple of smartphones that I only use with WiFi.  I opened up streetcomplete with WiFi on downloaded the map and quests.  I think I closed streetcomplete turned WiFi off then opened up Streetcomplete again.  I could see and complete the quests but since it had WiFi off it couldn't update the OSM database directly.

It gave an error message saying see log.  

The edits were held correctly and when WiFi mas enabled a batch was sent up correctly and entered OSM correctly.  So it all functioned as it should except the error message when it couldn't send the edits because it was off line.

For a new user this can be confusing.

Have fun John

**Comment by westnordost** [comment]
This is fixed already in the upcoming version. It was actually a bug, the app did not check if it was connected before attempting to automatically upload the changes.

**Comment by johnwhelan** [comment]
Ta

I used to program in assembler fifty years ago so testing comes naturally.  It's these modern languages that use things other than 0 and 1 that bug me.

Cheerio John
