### ISSUE TITLE
No siesta possible in opening_hours

### ISSUE THREAD

**Issue by rugk** [westnordost/StreetComplete#320]
When adding opening hours one cannot specify a lunch break time or something similar (a time during a day where the amenity is closed and before/afterwards it is open). Other OSM apps do have the possibility to add this.

**Comment by westnordost** [comment]
Yes you can. You can specify
`Mo-Fr 8-10`
and then add
`Mo-Fr 16-18`

Voilá.

I do not plan to add "Off" times.

**Comment by rugk** [comment]
Is this really the format OpenStreetMap "likes"? I thought one could(/should) specify "Mo-Fr 8-10 16-18" or so…

**Comment by westnordost** [comment]
You can specify exactly that, just try it

**Comment by rugk** [comment]
Yes, you can. Just was not sure, whether it is frowned upon.
