### ISSUE TITLE
Is it possible to make a web version of streetcomplete?

### ISSUE THREAD

**Issue by tshrinivasan** [westnordost/StreetComplete#325]
Is it possible to make a web version of streetcomplete?
so that we can enter details with our computers.

**Comment by matkoniecz** [comment]
Walking with laptop (it is a survey app) seems to be a poor idea.

Main point of the web version would be that it would work also on iPhones and other nonandroid OSes. 

But anyway that would be a completely separate project (AFAIK all code would need to be written from scratch, though ideas, graphics, design and details like overpass queries would be reusable).

**Comment by matkoniecz** [comment]
See also #43 

Too answer question - it is possible, I am not aware about anybody working on it.

**Comment by westnordost** [comment]
No, it isn't.

**Comment by wadouk** [comment]
still nobody working on it ?

**Comment by ENT8R** [comment]
I think the reason why nobody is working on it is that it would probably reduce the trustworthiness of StreetComplete as SC is a surveyor app and how could a web version determine if you are really on a survey...? I also don't know if @westnordost really wants something like this...

**Comment by wadouk** [comment]
Force usage of GPS to push surveys ? like now where SC push a warning message if the point modified is too far ?

**Comment by rugk** [comment]
Also don't think that argument of "quality" is too strong. Yes, it should of course require GPS. And if done as a PWA it could also visually be distinguished from other websites.

The reason nobody is working on it is just one simple one: That's a lot to do. Especially if you wanted to make it in the same quality as StreetComplete, and maybe even with the same quests.

**Comment by ENT8R** [comment]
That's true. Didn't thought about this. So maybe @westnordost can give his opinion on this whether he wants something like this at all...

**Comment by westnordost** [comment]
I think I have been pretty clear on this.

**Comment by matkoniecz** [comment]
> if one wants to use the name "StreetComplete" (or icon) or so for it, it is of course a good idea to ask @westnordost before

I would phrase it as "must ask and should not expect that he will agree"

**Comment by rugk** [comment]
Well… legally there is no "must", that app name is not trademarked, but hey… yes, it's a morally "must". :smiley:
