### ISSUE TITLE
Ask for bicycle_parking=*

### ISSUE THREAD

**Issue by matkoniecz** [westnordost/StreetComplete#330]
My current idea is

What is the bicycle parking type?
- Stand against which you can lean your entire bicycle. Makes it possible to lock the frame and a wheel to it [bicycle_parking=stand]
- Secures only the front wheel (or possibly back wheel) [bicycle_parking=wall_loops]
- ? [bicycle_parking=rack] I have no idea what is the real difference compared to bicycle=stand
-  custom-built closed shed in which many bikes can be stored, possibly with individual stands inside. [bicycle_parking=shed]
- A special kind of bollard designed for bike locking. Generally, the bike is locked to the central pole and "arms" of some sort prevent thieves from simply lifting the bike over the pole. [bicycle_parking=bollard]
- Parking takes the form of lockers which enclose bicycles fully and individually, typically secured with some form of key or combination system. [bicycle_parking=lockers]

These answers cover more than 95% of bicycle parking types https://taginfo.openstreetmap.org/keys/bicycle_parking#values

**Comment by westnordost** [comment]
Picture is always better than text

**Comment by matkoniecz** [comment]
I am not convinced in that case. bicycle_parking=stand may be extremely varied and something that looks very similar to bicycle_parking=stand may be bicycle_parking_wall_loops.

At least text+image is required here.

**Comment by westnordost** [comment]
I think image+word (_stand, wheelbenders, shed, individual lockers_) is enough.
As _stand_ and _wheelbender_ are the only standard stands you plan to implement, it is not difficult to distinguish them from the photo - simply from the size.
Keep in mind that in Android, you can show different images for different countries if they really vary so much. But really, the basic shape is the same: an upside down U or |_| for stands, small tilted c for wheelbenders. 
_Sheds_ and _individual lockers_ are already clear from the name, the photo is not so important for these. It is not necessary to explain to the user the concept of a locker. To stress the fact that sheds are in fact lockable and not just "open sheds" that only protect the cycles from rain, a different word could be used. I.e. "private shed" or "lockable shed".

**Comment by rugk** [comment]
From your descriptions I can hardly imagine what you mean… So I seriously need images here.
Apart from that, good quest. :+1:

**Comment by Binnette** [comment]
Here is a mockup :innocent:
![racks](https://user-images.githubusercontent.com/6597721/27612449-d8fcbb2a-5b96-11e7-9db9-f9a9cf3f7a53.png)

I miss a "free" image for the "simple anchor". Can someone find or take a picture of these kind of parling ?
I do not thing I ever seen something like that in real...

https://wiki.openstreetmap.org/wiki/Key:bicycle_parking

Pictures I use :
- https://commons.wikimedia.org/wiki/File:Bike_racks,_Union_Station_light_rail.jpg
- https://commons.wikimedia.org/wiki/File:Bizikletak_lotzekoa.JPG
- https://commons.wikimedia.org/wiki/File:Dunkerque_stojaki_rowerowe.jpg
- https://commons.wikimedia.org/wiki/File:Station_Buggenhout_-_Foto_4_(2009).png
- https://commons.wikimedia.org/wiki/File:Seattle_-_stylized_bike_rack.jpg

Todo :
- lockers
- wide_stands
- ground_slots
- building
- informal
- streetpod
- tree
- rope

**Comment by westnordost** [comment]
Thanks for searching for fitting pictures! The picture looks like as if you already implemented it(?).

Hmm, the shed is wrong, these are covered stands (or racks, don't really know the difference). 

The stands and wall loops pictures are good, the bollard and rack look too specific.
What about the pics in the OSM wiki?

> Todo
Please only search for pictures / include the following tags:
* stands
* wall loops
* anchors
* shed
* lockers
* building
and leave out rack and bollard. The distinction to stands won't be clear to the user (and not even to me) and also the distinction adds very little value.

**Comment by matkoniecz** [comment]
> https://commons.wikimedia.org/wiki/File:Bike_racks,_Union_Station_light_rail.jpg

I was also looking for pictures and I am not fan of this one - it depicts badly made bicycle parking - stands are hold only by screws attached to small paving stones.

>  leave out rack and bollard. The distinction to stands won't be clear to the user (and not even to me) and also the distinction adds very little value

rack is also completely unclear for me, bollard is distinguished by being a single pole, rather than inverted U like a typical stand (though difference is minor).

**Comment by westnordost** [comment]
> rack is also completely unclear for me, bollard is distinguished by being a single pole, rather than inverted U like a typical stand (though difference is minor).

For me the reason to not have bollard - while being clearly distinguishable - is that it is in effect the same as a stand: you can attach a bicycle on either side and it is usually as secure as a stand.

**Comment by Binnette** [comment]
> @westnordost : What about the pics in the OSM wiki?

Because those pics do not have licence. If thoses pics are better may be we can ask permission to owners, but I fear that it gonna take a lot of time... :cry: 

New mockup :
![racks2](https://user-images.githubusercontent.com/6597721/27659573-4e1a2dc6-5c54-11e7-9cbe-d2b4a55a15cb.png)

**Comment by westnordost** [comment]
Nice, the building and lockers are quite representative I think. The shed - there is too much detail for such a small image I'd say.
[These](http://www.null-euro-urbanismus.de/wordpress/wp-content/uploads/2008/03/2015_011.jpg) probably only exist in Hamburg, right?

**Comment by rugk** [comment]
> These probably only exist in Hamburg, right?

Hmm, would these be buildings or sheds?

**Comment by westnordost** [comment]
Shed

On 29 June 2017 15:06:58 CEST, rugk <notifications@github.com> wrote:
>> These probably only exist in Hamburg, right?
>
>Hmm, would these be buildings or sheds?
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/westnordost/StreetComplete/issues/330#issuecomment-311960428

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by Binnette** [comment]
New mockup version. With better shed and more light for building.
![racks2](https://user-images.githubusercontent.com/6597721/27713388-c1851942-5d2b-11e7-9612-b27ff20c4504.png)

Please, can someone help me find an "anchor". I tried many words in https://search.creativecommons.org/
Bur I can't find one. :cry: 

Shed : https://commons.wikimedia.org/wiki/File:Parking_v%C3%A9los_s%C3%A9curis%C3%A9_gare_des_Martres_2015-08-20.JPG

**Comment by callis** [comment]
will take a picture of an anchor this evening

**Comment by matkoniecz** [comment]
Maybe it would be better to use "wheel benders" name rather than "wall loops"?

**Comment by rugk** [comment]
> Maybe it would be better to use "wheel benders" name rather than "wall loops"?

Indeed, it seems to be [the corrct term](https://bikeswelcome.wordpress.com/2016/12/04/wheel-benders-whats-all-the-fuss/). (nice article, BTW)

**Comment by Binnette** [comment]
I will keep "wall loops" because the OSM value is "wall_loops". But it will be possible to translate "wall loops" to "Wheel benders" via POEditor. In the wiki, value "wheel benders" does not exist. See : https://wiki.openstreetmap.org/wiki/Key:bicycle_parking

**Comment by matkoniecz** [comment]
Wiki has "Often scathingly referred to as "wheelbenders" by cyclists." (wheelbenders, wheel benders, wheel-benders forms are popular, one with space has less problems with fitting into narrow space).

**Comment by callis** [comment]
Here are two Pictures of the anchor I know.

![img_0549](https://user-images.githubusercontent.com/16670844/27751062-d18bce4e-5dda-11e7-9dcf-9c8aba3e9d0b.JPG)
![img_0546](https://user-images.githubusercontent.com/16670844/27751063-d1baaa66-5dda-11e7-97ee-2f292036ee41.JPG)

**Comment by rugk** [comment]
Eh, oh, this is really something for bikes? Rather looks like something in an ancient castle or so… :smile:

**Comment by westnordost** [comment]
I have the suspicion that "anchors" being amont the top values for bicycle_parking is based on a misunderstanding. Anyone care to crosscheck some of these taggings with StreetView?

**Comment by rugk** [comment]
Hmm, I think [this](https://www.mapillary.com/app/?pKey=S-k4IOkHJ6oVgLz72S7lDw&focus=photo) is and [this](https://www.mapillary.com/app/?pKey=bZ1igt-on5moeyq1rGMEuA&focus=photo) clearly wrong. ([map](https://www.openstreetmap.org/edit?way=404320744#map=19/52.51747/13.50084))

[This](https://www.mapillary.com/app/?pKey=0o0FizWSapo00wTZWcGb_A&focus=photo&lat=52.52890277777777&lng=13.377836111111112&z=17) (on the right side) ([map](https://www.openstreetmap.org/edit?way=291686445#map=20/52.52890/13.37784)) too…

Generally they seem to be extremely rare (and possibly mapped wrongly).

**Comment by rugk** [comment]
BTW if you want some cliparts for the types maybe https://thenounproject.com/search/?q=bike%20parking&i=449496 can also help a bit.

**Comment by matkoniecz** [comment]
I was unhappy with available images for bicycle_parking=stand so I made
https://commons.wikimedia.org/wiki/File:Bicycle_parking_stand_2.jpg  and https://commons.wikimedia.org/wiki/File:Bicycle_parking_stand_1.jpg

Still not ideal, but better than what I found.

**Comment by rugk** [comment]
Yeah, they look good. I'd choose the first one if I need to guess.

**Comment by matkoniecz** [comment]
@Binnette What is the source of building image in https://github.com/westnordost/StreetComplete/issues/330#issuecomment-311786772 ?

I am preparing to (finally) implement it.

To summarize, based on https://github.com/westnordost/StreetComplete/issues/330#issuecomment-311511732 and https://github.com/westnordost/StreetComplete/issues/330#issuecomment-312370685 we need images for 

* stands - I plan to use https://commons.wikimedia.org/wiki/File:Bicycle_parking_stand_2.jpg
* wheellbenders - https://commons.wikimedia.org/wiki/File:Bizikletak_lotzekoa.JPG
* shed - https://commons.wikimedia.org/wiki/File:Parking_v%C3%A9los_s%C3%A9curis%C3%A9_gare_des_Martres_2015-08-20.JPG
* lockers - I located it, it seems to be https://commons.wikimedia.org/wiki/File:Fahrradgaragen_in_Einbeck.jpg  ( https://commons.wikimedia.org/wiki/Category:Bicycle_lockers has some potential alternatives)
* building - I plan to use https://en.wikipedia.org/wiki/File:McDonald%27s_Cycle_Center_inside.jpg - I am not entirely happy with https://commons.wikimedia.org/wiki/File:Kortrijk7725.JPG it is supposed to be "with a proper building, which means that bicycles are protected from wind, heavy rain etc". I looked at https://commons.wikimedia.org/wiki/Category:Fietsflat or https://commons.wikimedia.org/wiki/Category:Fietsenstalling_Heuvel_Tilburg among others but I failed to find anything better.

**Comment by westnordost** [comment]
These are all good photos! Though, I find the picture for stands originally posted by @Binnette slightly better, because in yours, the asphalt has so much contrast that it almost springs into the foreground. I am also not too happy with the building-picture - it looks like a bicycle shop or something. Perhaps crop it so that only the bicycles (without those flyers and the man) are visible.

**Comment by matkoniecz** [comment]
I will try to make a better picture (I dislike original stands picture as stands are incorrectly attached to surface - just by using screws, making them nearly completely useless for protection against thieves).

**Comment by matkoniecz** [comment]
It turns out that building image is really small - but hopefully it will be big enough. In the worst case I will try to find alternative image of this object.

![selection_007](https://user-images.githubusercontent.com/899988/36647424-c7714b06-1a85-11e8-92cf-288e36069f42.png)

**Comment by rugk** [comment]
> I dislike original stands picture as stands are incorrectly attached to surface - just by using screws, making them nearly completely useless for protection against thieves

I really doubt that matters for StreetComplete. In such a small size as it is used, it does not even may be visible.

**Comment by matkoniecz** [comment]
Potential alternative building photo: https://www.flickr.com/photos/climens/2215047236/in/photolist-4nJGnA-7rp11r-7rp15z-ptDFvt-ohH8TC-Q1ag4W-21nKZEQ-nGdRbb-4v5Lty-6QZmtX-5TV2d2-ntN5XN-qPitym-38G34D-QoN3VH-6voCBy-pwKKFt-5nNyZL-7JKM4A-5dCC8n-ubxLA-9kz9gq-F5EkSN-amjkwA-JZxsWq-r2xDAt-oN4zNe-qM5TtY-ahR5Bv-ewLWN-hjr95X-nHjnSf-8dg5XL-6EmLoq-nZqkCV-nYVZpJ-7j4AeA-nGszvh-nFXPWg-nXnUks-6fBwbY-nGeyjT-64AoMP-e9Nk7S-nZjGKf-o2A8nD-nGx73k-nGVWJo-732PBt-8fcohf

**Comment by westnordost** [comment]
Indeed!

On 27 February 2018 09:38:37 CET, Mateusz Konieczny <notifications@github.com> wrote:
>Potential alternative building photo:
>https://www.flickr.com/photos/climens/2215047236/in/photolist-4nJGnA-7rp11r-7rp15z-ptDFvt-ohH8TC-Q1ag4W-21nKZEQ-nGdRbb-4v5Lty-6QZmtX-5TV2d2-ntN5XN-qPitym-38G34D-QoN3VH-6voCBy-pwKKFt-5nNyZL-7JKM4A-5dCC8n-ubxLA-9kz9gq-F5EkSN-amjkwA-JZxsWq-r2xDAt-oN4zNe-qM5TtY-ahR5Bv-ewLWN-hjr95X-nHjnSf-8dg5XL-6EmLoq-nZqkCV-nYVZpJ-7j4AeA-nGszvh-nFXPWg-nXnUks-6fBwbY-nGeyjT-64AoMP-e9Nk7S-nZjGKf-o2A8nD-nGx73k-nGVWJo-732PBt-8fcohf
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/westnordost/StreetComplete/issues/330#issuecomment-368787762

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by matkoniecz** [comment]
The flickr one has problem with lines crossing image, Macdonald one is not obvious that it is inside building.

I found https://commons.wikimedia.org/wiki/File:Victoria_Park_TTC_bike_storage.JPG https://commons.wikimedia.org/wiki/File:BikesZurich_ST_08.jpg and https://commons.wikimedia.org/wiki/File:Bike_Storage_(YAUS).jpg that are potentially better.

**Comment by matkoniecz** [comment]
Next part of bikeshedding: current locker image has not enough space at bottom to for crop that leaves space for text.

alternatives that I found

https://commons.wikimedia.org/wiki/File:Bicycle_lockers_at_Gathurst_railway_station.JPG 

- other, without a clear bicycle symbol: https://commons.wikimedia.org/wiki/File:Diridon_Station_2477_17.JPG https://commons.wikimedia.org/wiki/File:RTD_Bike-n-Ride_Rent_a_Locker,_Olde_Town_Arvada_PnR.jpg https://commons.wikimedia.org/wiki/File:Construction_of_Arvada_Ridge_station,_bike_lockers.jpg https://commons.wikimedia.org/wiki/File:Hayward_Park_Station_3098_04.JPG https://commons.wikimedia.org/wiki/File:Peoria_Station_bike_lockers.jpg https://commons.wikimedia.org/wiki/File:Sowerby_Bridge_Station_-_Cycle_Lockers_-_geograph.org.uk_-_823843.jpg https://commons.wikimedia.org/wiki/File:Cycle_Lockers_-_South_Elmsall_Station_-_Station_Road_-_geograph.org.uk_-_1328930.jpg
