### ISSUE TITLE
highway=bicycle_road is not a standard tag

### ISSUE THREAD

**Issue by matkoniecz** [westnordost/StreetComplete#332]
https://github.com/westnordost/StreetComplete/blob/65075f04a11367de054d95853426212f5dd2bc14/app/src/main/java/de/westnordost/streetcomplete/quests/road_surface/AddRoadSurface.java#L21 has highway=bicycle_road that does not exists in OSM - see https://taginfo.openstreetmap.org/keys/highway#values

I guess that it should be simply removed from the list.

as spotted in https://github.com/westnordost/StreetComplete/pull/327#pullrequestreview-44377019 by @HolgerJeromin

**Comment by westnordost** [comment]
jup ok, go ahead
