### ISSUE TITLE
Prevent errors with bicycle racks

### ISSUE THREAD

**Issue by rugk** [westnordost/StreetComplete#334]
As for the bicycle stands quest I recently made a big error.

When you have these poles here:
![bicycle "poles"](https://apps2.campusservices.harvard.edu/images/blackstone/bicycle-racks.JPG)

I counted 6 poles, so I entered 6. However, one can put one at each side, so the correct number would be 12. Your quests, however, does not indicate that.

Maybe change the picture, so you see a pole with two bikes at each side, or so.

Maybe I'm also just too stupid, but in any case I only noticed this "problem" later.

**Comment by HolgerJeromin** [comment]
We have no image right now in the app.
I think adding an image would add confusion.

**Comment by rugk** [comment]
I meant the graphic. It currently shows a bike. :bike:

**Comment by HolgerJeromin** [comment]
> pole with two bikes at each side

...would suggest that you have to enter pairs of bicycles. Or am i wrong?

**Comment by westnordost** [comment]
A short description text like in a few other quests could be added. Any suggestions for what should be the content?

**Comment by rugk** [comment]
Hmm, yes, with that pic. If you leave it as it currently is ("_ x :bike: :straight_ruler: :bike:").
However without the x that could just be an image nearby showing how it is meant. (I mean, how bikes look is known anyway, so the current image does not really add much information for solving the quest.)

**Comment by rugk** [comment]
"When there are poles, each side counts"(?)

Or maybe better: "Count all places where one can place a bike (in a regular/useful way)"

**Comment by matkoniecz** [comment]
> Count all places where one can place a bike (in a regular/useful way)

is better, there are cases where only one side of stand is usable.

**Comment by althio** [comment]
"What is the maximum number of bikes?"
_"typically one or two bike per stand"_
