### ISSUE TITLE
StreetComplete tagging disused buildings as abandoned

### ISSUE THREAD

**Issue by 10992-osm** [westnordost/StreetComplete#3386]
# What happened

I encountered this issue today while surveying.

- Prior to my survey, the building was tagged (by me in June, I might add) as `building=yes` + `disused=yes`.
- Today, when I was doing a survey in the area, I was asked what the type of the building was.
- I remember thinking that I had tagged it before, but I didn't check.
- I also remembered about the abandoned option, which seemed to be the best fit.
- I therefore selected *Abandoned*, and the `abandoned=yes` tag was added.

# What I think should happen

StreetComplete should not add the `abandoned=yes` tag to buildings with a `disused=yes` tag.

I do not necessarily think that the quest should not be asked, since it may be possible to more precisely determine the building's type, even if it is disused.

# Situational information

Just for some background, I'm not 100% sure how the building ([way 954753584](https://osm.org/way/954753584/history)) concerned should be tagged.  I have, however, found a photo on Geograph which more or less depicts the current state, and also provides some context as to what the building actually is.  However, regardless of how this building should be tagged (I am leaving both in place for now), the issue still (as far as I am concerned) remains.

[![Image showing what is labelled as The West Lodge, in Leazes Park, Newcastle upon Tyne.  It is a building built of red brick, with two storeys.  The building is of a somewhat ornamental nature.  All its windows and doors have been boarded up with metal boarding, and graffiti is present on some parts of the walls/boarding.  Surrounding the building is some metal temporary fencing of the standard design.  To the left we can see grass and trees, and also a building in the distant background.  To the right, we can see a trees and a low fence, beyond which there is grass.](https://user-images.githubusercontent.com/83511672/137548037-458ab12c-31b2-4876-bc78-483be480607a.png)](https://www.geograph.org.uk/photo/5693609 "Geograph: The West Lodge, Leazes Park cc-by-sa/2.0 - © Mike Quinn - geograph.org.uk/p/5693609")

**Comment by matkoniecz** [comment]
> should not end up tagged with both disused=yes and abandoned=yes

Would it be fine if `disused=yes` would be removed while setting `abandoned=yes`?
