### ISSUE TITLE
Disable "birdseye" 3d when quest is selected

### ISSUE THREAD

**Issue by smichel17** [westnordost/StreetComplete#3397]
**Use case**
Specifically for building quests, when you select them, only the **base** of the building is highlighted. In **birdseye 3d** (left), it's difficult to see the vertical "corners" of the house when it's ~centered in the screen. This leads to the impression that the rendered map shows things in the **wrong position**, at an offset. In **full 3d** (right), this is not a problem, since the left wall is visible (but, the map automatically switches to birdseye 3d when a quest is selected; in the screenshot, I manually tilted it with a two-finger shove gesture.

<img alt="sc-birdseye3d-during-quest-selection" src="https://user-images.githubusercontent.com/6563664/137623681-9f2e811d-06b3-416b-89a2-9197ac571ea3.png" height="500" /> |||||||||||||||||||||||||||| <img alt="sc-full-3d-during-quest-selection" src="https://user-images.githubusercontent.com/6563664/137623689-8622c822-531b-471a-b013-579d1d6fad54.png" height="500" />

**Proposed Solution**

When a quest is selected, and the map is switched back to flat, also turn off birdseye 3d.

**Comment by westnordost** [comment]
What do you mean with "turn off birdseye 3d"?

**Comment by westnordost** [comment]
Okay, this is not going to happen then, since this means that the whole scene is reloaded in tangram-es which leads to a visual jerk, especially on less powerful/old devices.

**Comment by westnordost** [comment]
I don't think so
