### ISSUE TITLE
Street names including "ß" broken

### ISSUE THREAD

**Issue by Ellibeere** [westnordost/StreetComplete#34]
Hey,
here's a screen shot of my Android phone with German settings and it doesn't seem to render the "ß". It's supposed to be "Neue Blumenstraße" in Berlin. It shows up correctly in the OSM database (http://www.openstreetmap.org/way/190863137).

I didn't check but maybe there's the same problem for umlauts?

![image](https://cloud.githubusercontent.com/assets/26724381/24376180/448142a2-133b-11e7-91f6-f70b14f6afff.png)

**Comment by westnordost** [comment]
Can you tell which version of Android you are using? This might help to solve the problem.

**Comment by Ellibeere** [comment]
Android 7.1.1 / OxygenOS-Version 4.1.0

**Comment by ax3l** [comment]
Reporting the same problem with same Android/OxygenOS, updating from StreetComplete 0.4 to 0.5 today did not fix it.

**Comment by westnordost** [comment]
It's not fixed yet, this bug is a duplicate.

**Comment by ax3l** [comment]
Ok thanks :) can you please link the appropriate issue, I saw the label but could not find the right one to subscribe.

**Comment by westnordost** [comment]
#36
