### ISSUE TITLE
Redundant "tactile paving" quest being asked - both on kerbs and on highway=crossing node

### ISSUE THREAD

**Issue by mnalis** [westnordost/StreetComplete#3407]
**Use case**

At some crossings (encountered it multiple times), user is being asked about `tactile_paving` on each side of the crossing individually, and *then again* "if there is tactile paving on both sides". It is confusing and seems redundant.

Example this location: https://www.openstreetmap.org/note/2894360

https://user-images.githubusercontent.com/156656/137835934-394a2370-a0d8-456b-b02e-3a05649a4ccb.mp4

**Proposed Solution**

- ideally, user would be asked just one question - if there is `tactile_paving` on both sides, and if there is, two additional individual questions if it exists on each side individually would be skipped (that is, they would automatically solved by that one quest).
- alternatively, if the user is asked for each of the sides if it has tactile paving, asking them again "if it exists on both sides" is redundant and confusing, so it should be removed. 

(this was logged on `SC 36.0-beta2` based my fork, but no changes related to that issues should be in there)

**Comment by westnordost** [comment]
Well, two are for the kerbs, one is for the crossing. 

And the wording reflects that:
- Is there tactile paving on this curb here?
- Does this crosswalk have tactile pavings on both sides?

So there is nothing wrong with the questions as such. Yeah, maybe it would be "nice" if the other things then get solved automatically or something, but such complexity is not really worth to implement.

So, if the translation into Croatian is also OK, the only thing that may be considered is to:

Not display the tactile-paving crossing quest if the way the `highway=crossing` is part of also contains a node that has `barrier=kerb` tagged OR any other node in that way would be a candidate for an (implicit) kerb (i.e. common vertex of a `footway=crossing` and `footway=sidewalk` that meet or of a `barrier=kerb` line) - in other words, if a quest is displayed for the kerbs.

...

Okay, I wrote the above to show a possible enhancement and float a suggestion whether it is worth it to implement the additional complexity. Now, having written what would be necessary to implement, it already makes me sick in the stomach. This is simply not worth the time and complexity to avoid asking kind of duplicate questions.
Also, in general duplicate tagging like this is not that bad IMO - inconsistencies can be found automatically and some applications may only know how to process one of the two infos.

**Comment by smichel17** [comment]
Okay, just to clarify, in a situation like the image below, where there are lowered curbs on both sides, both with tactile pavings, I've currently been tagging `yes` to both curbs AND `yes` to the crossing. Now I'm wondering if I should be tagging `no` to the crossing, because it is already tagged on the curbs.

![image](https://user-images.githubusercontent.com/6563664/137953782-a1caaeec-3296-44f5-af9c-145b33fb3e90.png)

**Comment by pkoby** [comment]
Clarification question:
When asked if a crossing has tactile paving on "both sides", does this mean on each end (where the kerbs are), or along the crossing way (where the zebra stripes or whatever are)?

As I understand https://wiki.openstreetmap.org/wiki/Key:tactile_paving#Use_on_ways, `tactile_paving` on a way means it's along the whole way. On a node, it means it's in a small point area.

So tagging `tactile_paving` on a `highway=crossing` node suggests to me that it would apply to the crossing itself, not the ends (kerbs), but that doesn't seem to be how many people interpret this, nor how the wiki suggests it should be used.

**Comment by westnordost** [comment]
On each side

**Comment by Nadyita** [comment]
> If the kerb is identical on both sides of a crossing and the location of the actual kerbs is not clear (e.g., due to a lack of high resolution imagery), `kerb=*` is sometimes added to the `highway=crossing` node **instead**.

The same logic pretty much applies to tactile pavings, because they are made to warn about the kerb. You either put them on the nodes where they are, **or** on the crossing, if the location is unclear. Not both. I get that it's going to be hard to implement, but it would be more than worth it.

**Comment by endolith** [comment]
> No. The question is very clear. "Does this crosswalk have tactile pavings **on both sides**?"

Meaning that both ramps at the end of the crosswalk have tactile paving, right?

**Comment by matkoniecz** [comment]
> Meaning that both ramps at the ends of the crosswalk have tactile paving, right?

yes

**Comment by pkoby** [comment]
I think it's wrong/inaccurate/confusing/ambiguous to tag a node with `tactile_paving=*`. As you can see here, it's not clear to everyone. It's probably way too late to change it now, but I don't think I would be comfortable assuming that all nodes tagged with `tactile_paving` refer to the kerb ends and not the way.

Assuming that the quest remains as is, can we simply change the wording to "Does this crosswalk have tactile pavings on both **_ends_**" to disambiguate it? And maybe only ask it if it's not shared by a crossing way?

**Comment by endolith** [comment]
It should definitely have a diagram, as in https://github.com/streetcomplete/StreetComplete/issues/3407#issuecomment-946901763

There are also crosswalks with a strip of tactile paving along the way: https://wiki.openstreetmap.org/wiki/Key:tactile_paving#Use_on_ways

**Comment by Nadyita** [comment]
The tactile pavings at the **ends** of a crosswalk are not because of the crosswalk, but because of the flush kerbs. The kerbs for a crosswalk would be completely *along* the crosswalk and belong to a way. If the crosswalk is mapped as a node, though, you will never know whether this refers to the crosswalk, or the flushed kerbs. :cry:

**Comment by westnordost** [comment]
> you will never know whether this refers to the crosswalk, or the flushed kerbs. 😢

It refers to the kerbs simply because that a crosswalk has tactile paving all the way is extremely rare when compared to the former and hence it follows that `tactile_paving=yes` must also mean the former.

This means that if one wants to clearly distinguish the former with the latter, another (tbd) (sub)tag would need to be invented. 
For tagging that a crosswalk has tactile paving all the way,  the only possibility to have it clear is to use a (TBD) (sub)tag that
