### ISSUE TITLE
Excessive Storage Utilisation

### ISSUE THREAD

**Issue by peternewman** [westnordost/StreetComplete#3417]
Storage is still excessive for me, even after installing 36.1 and running the Delete Cache thing.

Map cache size: 250 MB

Before:
App: 30.98 MB
User data: 170 MB
Cache: 475 MB
Total: 676 MB

After:
App: 30.98 MB
User data: 6.95 MB
Cache: 475 MB
Total: 513 MB

So it's certainly cleared my user data a lot, which is the database presumably? I only got back from a trip on the 9th, so maybe there was still some excess data there which was less than 14 days old, but I think my overall usage has been around this figure for quite some time...

Indeed previously:
User data: 313MB
Cache: 399MB

_Originally posted by @peternewman in https://github.com/streetcomplete/StreetComplete/issues/3133#issuecomment-898052174_

**How to Reproduce**
I'm not really sure, use the app, travel to lots of different places maybe.

**Versions affected**
SC 36.1
Android 9

**Comment by westnordost** [comment]
A quick debugging revealed that the `DiskLruCache` (included in okhttp3 dependency, a dependency of tangram-es) indeed correctly prunes anything above the set limit, but for some reason, the files themselves seem to remain in the directory.

**Comment by westnordost** [comment]
Android claims that **StreetComplete Dev v37.0 beta1** needs:
- 42.41 MB for app
- 80.65 MB for data
- 85.92 MB for cache

---

The app itself apart, there are two directories assigned to the app:

`/data/data/de.westnordost.streetcomplete.debug/` (on internal memory)
![image](https://user-images.githubusercontent.com/4661658/138367856-fcf49a4a-72b3-4d3e-af40-0cbd7256c95d.png)

`/sdcard/Android/data/de.westnordost.streetcomplete.debug/` (on "external" SD card. If there isn't one, it's emulated)
![image](https://user-images.githubusercontent.com/4661658/138368137-3116edf3-74d3-4496-bfb4-f964d5a07e62.png)

**The following is definitely data:**
- databases
- app_webview
- files (in internal)
- no_backup
- shared_prefs
- files (in external)

In total, it is 76 MB.

**The following is definitely cache:**
- cache (on internal)
- code_cache
- cache (on external)

In total, it is 48.9 MB.

---

So, it doesn't add up. Nevermind the few MB on the data. For some reason, Android claims there is almost double as much cache in use as there is in data in that directory. So far, I have no explanation for this.

**Comment by peternewman** [comment]
> It looks like the physical size for the tiles on the sdcard is simply about double the size as the logical size because many tiles are so small that they are below the minimum block size for the file system.

Thanks @westnordost . I sort of wondered if it might be something like that from the start, but my phone wasn't mounting properly on my laptop to try and run some equivalent commands to compare the two.

Is it worth a note on that settings page like the old hard drive warnings (or wing mirrors), "size on disk may be bigger than configured"?

**Comment by westnordost** [comment]
I don't think so
