### ISSUE TITLE
Housenumber quest: no blinking cursor

### ISSUE THREAD

**Issue by CloCkWeRX** [westnordost/StreetComplete#342]
1. House number quest

expected:
form opens, keyboard is shown, house number input has focus

actual:
form opens, no keyboard.

In other circumstances which I cant pin down; the keyboard has appeared (perhaps retained from existing keyboard being shown? in #341), but input lags/the input has no focus

**Comment by HolgerJeromin** [comment]
This is no regression:
#227

**Comment by CloCkWeRX** [comment]
Are all quests changing to no longer focus on the inputs on display; ie building levels or street sign name entry? At the moment this is very inconsistent; so appears to be a regression. 
It also doubles the number of interactions required in current form - walking pace data entry turns into walk/stop every few houses; as compared to the previous version

**Comment by westnordost** [comment]
It has never been the case that the keyboard immediately appears. For no quest type.

**Comment by CloCkWeRX** [comment]
Alright, #341 was confusing the matter a bit; making the keyboard appear when I was using it on some quests.

That said; here's a video of what I mean:
https://www.youtube.com/watch?v=B4tbR6GwBoI&feature=youtu.be

The house number input doesn't behave like a normal input; nor does it have UI stylings to hint its an input. I could have sworn that the default behaviour set the focus on the house number input prior to the update yesterday; which made it less of a problem as a blinking cursor indicated it was something you interact with.

**Comment by westnordost** [comment]
okay, I see
