### ISSUE TITLE
Edit history timestamp temporarily disappears when you undo certain entries

### ISSUE THREAD

**Issue by smichel17** [westnordost/StreetComplete#3426]
**How to Reproduce**

- Answer a quest — (1)
- Wait 1 minute
- Answer two more quests — (2), then (3)
- Open history drawer. Note that a timestamp appears above (2) / below (1).
- Undo quest (2)

Expected: Timestamp continues to exist, now between (1) and (3)
Actual: Timestamp disappears along with (2)

Workaround: Select (3). Timestamp re-appears.

---

The fix is to re-render (3) when (2) gets un-done. IIRC there's some callback to tell an adapter to do this; I don't remember the exact invocation off-hand (`invalidateSomething`?).

**Comment by mnalis** [comment]
I can confirm I can reproduce it with `v37.0-beta1`. 
It probably does not happen in my fork because it does not have final version of your `single undo` PR, but some older revision.
