### ISSUE TITLE
Distance for remote editing too small at least for buildings

### ISSUE THREAD

**Issue by HolgerJeromin** [westnordost/StreetComplete#345]
I was about 180 meter away from the detached building:
https://www.daftlogic.com/projects-google-maps-distance-calculator.htm?route=51.87401668486683,8.478369458786005|51.87459670165442,8.475892301648855
I got the question if i was there...

**Comment by westnordost** [comment]
Well, you can simply answer it with "yes". There is only one max distance for automatic detection that you are indeed on-site, not per-quest.

Am 20. Juni 2017 09:17:06 MESZ schrieb Holger Jeromin <notifications@github.com>:
>I was about 180 meter away from the detached building:
>https://www.daftlogic.com/projects-google-maps-distance-calculator.htm?route=51.87401668486683,8.478369458786005|51.87459670165442,8.475892301648855
>I got the question if i was there... 
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/westnordost/StreetComplete/issues/345

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by HolgerJeromin** [comment]
> Well, you can simply answer it with "yes".

I did, but i was too lazy to walk the muddy way to earn the real star :)

But you are probably right. This is not worth the effort.
