### ISSUE TITLE
Don't use cycleway:both=lane on one-way streets

### ISSUE THREAD

**Issue by Rudloff** [westnordost/StreetComplete#3459]
**Use case**
When a one-way street has a bike lane in both directions, having `cycleway:left=opposite_lane` and `cycleway:right=lane` gives obvious information about which lane is a classic bike lane and which one is a contraflow lane.

Currently, StreetComplete simply adds `cycleway:both=lane`.

**Proposed Solution**
When adding a lane in both directions for a one-way street, StreetComplete could add:
* `cycleway:left=opposite_lane`
* `cycleway:right=lane` (or vice-versa)
* `oneway:bicycle=no`

(This is what [the French bicycle wiki page](https://wiki.openstreetmap.org/wiki/FR:Bicycle) recommends.)

Edit: [here](https://www.openstreetmap.org/way/40848257) is a example of such a street.

**Comment by Florimondable** [comment]
```
    cycleway:both=lane
    oneway:bicycle=no
```
is ambiguous !

It doesn’t specify on which side of the road the contraflow lane is.
For this you must add `cycleway:left|right:oneway=-1` !

I also heard from @MathiasVadot that StreetComplete replace the tagging `cycleway:left|right=opposite_lane` with the two tags scheme.
This shouldn’t be done, StreetComplete should be able to read others scheme.

**Comment by matkoniecz** [comment]
> It doesn’t specify on which side of the road the contraflow lane is.

Is it really not reasonable to assume this based on a driving side?

And note that explicit tagging here is not really helpful given substantial amount of confusion of left/right subtag and extreme rareness of such situation

**Comment by Florimondable** [comment]
> 
> > It doesn’t specify on which side of the road the contraflow lane is.
> 
> Is it really not reasonable to assume this based on a driving side?
> 
It works 99% of the time.

But it worst than that, you may have both lane in the same direction..., real world cases are always more diverse than you may think ;)

**Comment by matkoniecz** [comment]
> you may have both lane in the same direction...,

At the same time as `oneway:bicycle=no` is present?

**Comment by westnordost** [comment]
In the situation of a `oneway=yes` street with exclusive lanes on both sides, StreetComplete actually tags 
```
cycleway:left=lane
cycleway:left:lane=exclusive
cycleway:right=lane
cycleway:right:lane=exclusive
cycleway:left:oneway=-1
oneway:bicycle=no
```

**Comment by BalooUriza** [comment]
Unrelated to streetcomplete and more related to tagging, this is yet
another example of "let's start including bike lanes in lane tagging and
treat them like any other conditional lane already".

**Comment by matkoniecz** [comment]
@BalooUriza Please, do not start "lets redefine `lanes` tag" discussion here

**Comment by MathiasVadot** [comment]
So the debat is not over about the contraflow bike lane. 

Is it possible for Streetcomple to work for the moment like this : 
- If there is no information about bike line in contraflow, Streetcomple use the rule mentioned above.
- If there is already opposite tag, then Streetcomplete let this tag.

Indeed, if a territory has to modify all the tags, this must be done in consistency and not in dotted lines. Keep in mind that OSM data is used in databases by associations and local authority, so it is important to keep this information consistent.

**Comment by matkoniecz** [comment]
> Keep in mind that OSM data is used in databases by associations and local authority, so it is important to keep this information consistent.

Both methods are in a standard use, so this is not really relevant. Ideally there would be agreement to deprecate either version, but as it stands both are fine to use and data consumers must support both variants.

**Comment by MathiasVadot** [comment]
Hello, Ok so, to answer my question, if the both are fine to use, streetcomplete can let Opposite tag in place for the moment? If the oneway:bicycle = no tag is missing, streetcomplate can add it.

**Comment by westnordost** [comment]
This adds complexity in implementation and testing effort. Furthermore, as I explained, the opposite tag is ambiguous in some cases. So I don't see a reason to do this or even just allowing a PR from a contributor to do this.
