### ISSUE TITLE
Localise note language

### ISSUE THREAD

**Issue by SomeoneElseOSM** [westnordost/StreetComplete#349]
https://www.openstreetmap.org/note/1008774 is in French (I guess because the user's phone was).

This makes no sense in England.  By all means ask the a French user questions in French, but when adding notes in England, use the English translation.

Obviously a bit more thought is needed for multilingual places (e.g. Belgium, India) where the "note language" to use isn't obvious.

**Comment by westnordost** [comment]
This is implemented already. See https://github.com/westnordost/StreetComplete/issues/267#issuecomment-309165384

**Comment by SomeoneElseOSM** [comment]
Great - thanks.
