### ISSUE TITLE
Make it clear that StreetComplete notes are created by an app, not a human

### ISSUE THREAD

**Issue by SomeoneElseOSM** [westnordost/StreetComplete#350]
For example, https://www.openstreetmap.org/note/1039567 .  There's no indication on that note that it came from here, although there is on edits.

Adding this context would greatly help the other mappers who presumably are the ones who are expected to tidy up after these app notes?

**Comment by westnordost** [comment]
The StreetComplete notes are created by a human, not an app. The app only adds context to what the user writes.

Anyway, I already changed the wording and made it clear where the note is coming from. See
https://github.com/westnordost/StreetComplete/commit/36503377eb19becd73db0ea007df2eab35ffd54a#diff-3609c06c5baa57042643d114d500172aR156

(This is not part of v0.12 yet but will go into v1.x)

**Comment by SomeoneElseOSM** [comment]
When is v1.x likely to appear?

**Comment by westnordost** [comment]
In 2-4 weeks I would say. However, during development, it will be marked as "beta" (like v0.x is now). I plan to mark v0.x as non-beta soon, the coming week probably. Only bugfixes are accepted into v0.x since the last month or so.
