### ISSUE TITLE
Missing building level quest

### ISSUE THREAD

**Issue by grrgui** [westnordost/StreetComplete#352]
Hi,
StreetComplete is a great tool ! thx for all that work.

Looking 3D OSM maps of Paris, I found that some buildings do not have the right levels (no level at all in fact !). After checking in OSM, I discovered that the "building:level" was missing for these buildings, but in the same time, there is no quest on that topic for these buildings on StreetComplete. Is it normal ?
An example here: 
http://osmbuildings.org/?lat=48.88336&lon=2.36103&zoom=19&rotation=0&tilt=30
(In that area, almost all the buildings have the same level).

**Comment by westnordost** [comment]
The quest is only created for certain types of buildings (Most notably, not "building=yes"). There is already a ticket for creating a quest to specify the building type.
