### ISSUE TITLE
StreetComplete crash OnPause

### ISSUE THREAD

**Issue by Binnette** [westnordost/StreetComplete#354]
Step to reproduce :
-Run StreetComplete 8ecab6e 
-Wait StreetComplete to display Map and your GPS location
-Press your device Home button (long press to view all running apps)
-StreetComplete crash !

Android : 6.0
Linux : 3.18.19
Device : HOMTOM HT17 PRO

Here is the exception message :
`--------- beginning of crash`
`FATAL EXCEPTION: main`
`Process: de.westnordost.streetcomplete, PID: 26444`
`java.lang.IllegalStateException: Location update received after client was disconnected. Did you forget to unregister location updates before disconnecting?`
`    at com.mapzen.android.lost.internal.FusedLocationServiceCallbackManager.onLocationChanged(FusedLocationServiceCallbackManager.java:31)`
`    at com.mapzen.android.lost.internal.FusedLocationProviderApiImpl$1$1.run(FusedLocationProviderApiImpl.java:48)`
`    at android.os.Handler.handleCallback(Handler.java:815)`
`    at android.os.Handler.dispatchMessage(Handler.java:104)`
`    at android.os.Looper.loop(Looper.java:207)`
`    at android.app.ActivityThread.main(ActivityThread.java:5737)`
`    at java.lang.reflect.Method.invoke(Native Method)`
`    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789)`
`    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:679)`

Complete exception here : https://gist.github.com/Binnette/b1eca343ea9276c0e3556f1067d71b4f

This issue seems to be a LOST issue and is tracked here :  mapzen/lost#218

**Comment by Binnette** [comment]
Oups. I just see your issue... mapzen/lost#224

**Comment by Binnette** [comment]
Here is the main exception with details of variables and context :

We can see that the exception is thrown by class "FusedLocationServiceCallbackManager" in method "onLocationChanged" line "31". Because service == null 

![ex2](https://user-images.githubusercontent.com/6597721/27606343-26ba1680-5b80-11e7-8916-787edc4e305a.png)

**Comment by Binnette** [comment]
And here is an other exception that happens before the "main" one. I don't know if there is a link between them...

![ex1](https://user-images.githubusercontent.com/6597721/27606430-82f7f0de-5b80-11e7-8189-13101e229ed6.png)

**Comment by Binnette** [comment]
It also simply crashes when I place my device on landscape mode with the same 2 exceptions.

**Comment by westnordost** [comment]
I shouldn't have removed the try-catchall around the LOST code after https://github.com/mapzen/lost/issues/178 was apparently fixed.
I think I will need to wrap it in this again.

**Comment by westnordost** [comment]
My fix did not fix it because the crash happens deferred on the main thread. Actually, it _can not_ be worked around, it must be fixed in LOST.

**Comment by Binnette** [comment]
With a0d7550, StreetComplete does not crash anymore, and this is a very good point.
But as you can imagine, this workaround is still... a workaround
So when i place my device from portrait to landscape, SC does not crash but it loses my location. So I have to wait few seconds for the GPS to give me a new position.

I'm gonna run SC with a0d7550, but will wait for SC to use fixed LOST version. @sarahlensing and you have fixed the bug mapzen/lost#224
