### ISSUE TITLE
Best way to identify Future Quests?

### ISSUE THREAD

**Issue by chrisdebian** [westnordost/StreetComplete#355]
Hi, all.

People are coming up with some really good ideas for new Quests. This has made me wonder the best way to analyse what data is missing from OSM, and the creating quests. This is also something that interests me.

1. Does a guide/ how-to exist, that explains how missing data can be identified?

2. Can this data be analysed by non-programmers?

3. Does the guide suggest that people can volunteer to study the data, and suggest new Quests?

4. Once a new quest has been identified, it can be raised as an issue, here, for others to comment on/ refine, prior to being considered for addition to StreetComplete.

Any thoughts? I'm keen to see wide usage of this tool, to improve data.

Thanks,

Chris
chris_debian
UK
2E0FRU

**Comment by westnordost** [comment]
No guide exists. I guess the starting point is to look at what elements are captured in OSM and then think of what properties could appropriately be added and whether a tag for that exists in the OSM wiki already. For example, obviously tunnels are mapped in OSM. One property that would make a meaningful addition to the data is to add the maximum height of vehicles that may go through the tunnel.

The [README](https://github.com/westnordost/StreetComplete/blob/master/README.md) gives some hints however what would be acceptable quests:
- Only quests should be conceived that are quickly, clearly and easily answerable without background knowledge on-site by users
- The user should not be asked invalid questions ("false positive"). An example of an invalid question would be that users are asked for the housenumber of garages.

> 2. & 3.

What do you mean? Anyone can analyse OSM data.

> 4.

Exactly.

**Comment by HolgerJeromin** [comment]
I think right now we don't have a problem with [too few ideas](https://github.com/westnordost/StreetComplete/issues?q=is%3Aopen+is%3Aissue+label%3A"new+quest") for new quests, but to few resource to implement them.

**Comment by chrisdebian** [comment]
Agreed. That's why I suggested we have some way of attracting and coordinating volunteers.
