### ISSUE TITLE
Feature Request- Nearest Quest/ Map Issue

### ISSUE THREAD

**Issue by chrisdebian** [westnordost/StreetComplete#356]
Hi,

Would it be possible to have an option to centre the map on the nearest map issue, so that we can methodically improve map data?

Thanks,

Chris.

**Comment by westnordost** [comment]
You mean a button?

**Comment by chrisdebian** [comment]
Yes, thanks Tobias.

Chris

**Comment by westnordost** [comment]
I do not plan to add a button. But I plan to add something similar later. A floating arrow at the side of the screen that points to the closest quest(s). Perhaps that arrow will also be clickable.

However, this is still blocked by a third party library.
