### ISSUE TITLE
Coordination Suggestion

### ISSUE THREAD

**Issue by chrisdebian** [westnordost/StreetComplete#357]
Would it be possible to have a list somewhere, of who is doing what on this project, so we can identify what areas need help/ volunteers?

Thanks,

Chris.

**Comment by westnordost** [comment]
I am doing everything, people help by adding contributions through [Pull Requests](https://github.com/westnordost/StreetComplete/pulls?utf8=%E2%9C%93&q=is%3Apr) (usually new quests). :-D

So, basically, if you want to help the project in general but do not have any own ideas what specifically you would like to add, write me telling what is you area of expertise and I can tell you.

**Comment by chrisdebian** [comment]
Ok, not the ideal open source way to do things. Usually ideas are shared in a viewable page; many people will have no idea what a pull request is. You're in charge, though.
