### ISSUE TITLE
Interoperability?

### ISSUE THREAD

**Issue by chrisdebian** [westnordost/StreetComplete#359]
Hi, 

Do we know how to identify possibilities to use data from other sources, or for other applications to benefit from the good work of StreetComplete? Maybe just collecting data is sufficient?

Thanks,

Chris.

**Comment by westnordost** [comment]
Not sure what you are getting at. Do you have a concrete example?

Data that is contributed via StreetComplete is added to OpenStreetMap. Anyone can use the data from OpenStreetMap.

**Comment by chrisdebian** [comment]
Companies like Telenav, have ways of augmenting the quality of the data, and they contribute a lot. I was just thinking about API's,  etc. Understand if you want to close this.

**Comment by westnordost** [comment]
Still not sure what you are getting at.

You say that Telenav augments the quality of the OSM, that's nice. But how does it relate to this app? Not sure if this is clear to you: StreetComplete contributions are **directly** and immediately added to OSM.

Or do you speak about other data sources for quests?

**Comment by chrisdebian** [comment]
This can wait, the app is looking good, and these sorts off 'value adds' can be revisited in the future.

Thanks,

Chris.
