### ISSUE TITLE
Streetnames missing on Nexus 4 / Android 5.1 / small screens

### ISSUE THREAD

**Issue by Ellibeere** [westnordost/StreetComplete#36]
First screenshot is taken with the Nexus 4, second one with OnePlus T3. The streetnames didn't render on the Nexus on **any** zoom level. Maybe related to Nexus 4 screen size?

![image1](https://cloud.githubusercontent.com/assets/26724381/24376403/0ef5e556-133c-11e7-914e-cbb3f6a23ad6.png)
![image2](https://cloud.githubusercontent.com/assets/26724381/24376404/0ef868bc-133c-11e7-9d5d-b44c7e699938.png)

**Comment by westnordost** [comment]
Could you also add on which versions of Android these devices are running?

**Comment by Ellibeere** [comment]
Nexus 4: Android 5.1.1
OnePlus T3: Android 7.1.1

**Comment by westnordost** [comment]
I'll close the other bug since all info there is here also.

**Comment by denis-dordoigne** [comment]
Samedi issue with Staraddict 6 with Android 6.0.1
