### ISSUE TITLE
Quest: maxweight for bridges

### ISSUE THREAD

**Issue by krzyk** [westnordost/StreetComplete#361]
This quest is very similar to the maxspeed one. Add a quest to set the `maxweight` tag (together with `source:maxweight=sign`) to highways.

It might be beneficial to have the tonnes set using images/text (so selecting the most popular maxweights would be easier) + a way to enter a number if none of the images/text have the given limit.

This should be applicable to all the highways that maxspeed + service roads also (there are restrictions on those for maxweight already in OSM).

I'm not sure how to deal with the situation when there is not max weight set for given road, so now I'm wondering, is this quest doable in StreetComplete?

**Comment by westnordost** [comment]
Lets do it only for bridges.

On 30 June 2017 11:04:57 CEST, "Krzysztof Krasoń" <notifications@github.com> wrote:
>This quest is very similar to the maxspeed one. Add a quest to set the
>`maxweight` tag (together with `source:maxweight=sign`) to highways.
>
>It might be beneficial to have the tonnes set using images/text (so
>selecting the most popular maxweights would be easier) + a way to enter
>a number if none of the images/text have the given limit.
>
>This should be applicable to all the highways that maxspeed + service
>roads also (there are restrictions on those for maxweight already in
>OSM).
>
>I'm not sure how to deal with the situation when there is not max
>weight set for given road, so now I'm wondering, is this quest doable
>in StreetComplete?
>
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/westnordost/StreetComplete/issues/361

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by matkoniecz** [comment]
https://wiki.openstreetmap.org/wiki/Key:maxweight is not mentioning how to tag unsigned cases so I created https://wiki.openstreetmap.org/wiki/Talk:Key:maxweight#Support_for_.22no_weight_limit.22

**Comment by rugk** [comment]
It looks bad for this quest:

> The vast majority of roads have no explicit weight limit posted, though, so this is clearly the default situation. When there's such a clear default, it's not common to explicitly tag the absence of a special case, even if such a value exists.

https://wiki.openstreetmap.org/wiki/Talk:Key:maxweight#Support_for_.22no_weight_limit.22

@matkoniecz Maybe ask them about bridges, only?

**Comment by westnordost** [comment]
The question is: How to tag **bridges** that have no weight limit posted?

**Comment by krzyk** [comment]
Yeah, I haven't thought of that. And it is the same as roads, if there is no weigh limit, there is no tag.

So I think I'll close this as it is unsolvable, at least until there will be some kind of DB outside OSM that would track surveyed locations (per quest, with timelimit) - this would add costs, but it would extend usefulness of StreetComplete.

**Comment by westnordost** [comment]
Don't close it. This idea that the information whether something has been sueveyed but indeed has not a certain feature should be held in a database outside OSM is a is not a good one.

The information is not just necessary for StreetComplete but for any one person doing a survey for missing data - whether assisted by a tool like this app or not. To have this data in a second database is not helpful because other surveyors or applications cannot access this information.
In the OSM db, there are already a number of tags that primarily serve surveyors, such as noname, fixme, note, noaddress, source, lastcheck,... so thinking of a new tag to describe the situation is completely okay, imo, as long as it does not collide with the understanding of existing tags. I.e. maxweight=unsigned would be a bad idea.

On 4 July 2017 09:55:30 CEST, "Krzysztof Krasoń" <notifications@github.com> wrote:
>Yeah, I haven't thought of that. And it is the same as roads, if there
>is no weigh limit, there is no tag.
>
>So I think I'll close this as it is unsolvable, at least until there
>will be some kind of DB outside OSM that would track surveyed locations
>(per quest, with timelimit) - this would add costs, but it would extend
>usefulness of StreetComplete.
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/westnordost/StreetComplete/issues/361#issuecomment-312807584

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by matkoniecz** [comment]
Does it make sense to ask it all over the world? Are there any countries where signing max weight is so rare that asking about it makes no sense?

**Comment by westnordost** [comment]
I think it makes sense anywhere

**Comment by matkoniecz** [comment]
I went looking through local units and so far I found only USA with its short tons.

There is also Guernsey that uses hundredweight as unit.

I see some lbs in taginfo, it is nearly 100% from USA. Most of use is conversion from short ton on signs, but I encountered claim that it is actually present on some signs.

For now I plan of leaving that weird weight limits for notes.

![proxy duckduckgo com](https://user-images.githubusercontent.com/899988/59866487-f912b200-938b-11e9-94e2-e0ae9576ff87.jpeg)

**Comment by matkoniecz** [comment]
I tested first working version and it is better than expected - I already found two bridge that were missing maxweight limit and I worried that in well mapped area I will just select "no maxweight sign" over and over again.

Still, my current query

```
ways with highway ~ trunk|primary|secondary|tertiary|unclassified|residential|living_street|service
         and !maxweight and maxweight:signed!=no
         and bridge ~ yes|viaduct|movable|covered|tresle|cantilever
         and motor_vehicle !~ private|no
         and vehicle !~ private|no
         and (access !~ private|no or (foot and foot !~ private|no))
         and area != yes
```

is probably overenthusiastic and there are probably ways to exclude bridges unlikely to have posted max weight limits.

I thought about excluding ones with high `lane` count, high `maxspeed`, with `motorroad` and maybe dropping also `trunk` and `primary` roads.

**Comment by westnordost** [comment]
I think maxweight is an important property on any bridge, so no reason to be so cautious to not ask for too many bridges.

Couldn't it be bridge!=no?

What about link roads? But maybe trunk could be dropped. You could check first how many maxweight on trunk is set in well-mapped places

**Comment by matkoniecz** [comment]
> Couldn't it be bridge!=no?

Maybe - difference, if any, is tiny. Changed.

> What about link roads?

I thought that they will be included by `highway ~` match without end of string/start of string matches. But I see that it is not happening and link roads are not included. It is now fixed.

> But maybe trunk could be dropped. You could check first how many maxweight on trunk is set in well-mapped places

First step is to assume that this makes sense for bridges on minor roads - and it makes sense as expected, I found missing `maxweight` on third and fourth minor bridge.

Then I plan to compare how often maxweight is tagged on minor bridges and bridges on more major roads (I am currently running querries).

It may be a good idea to run such comparison limited to, for example Germany - thanks for reminding me about this.

> I think maxweight is an important property on any bridge, so no reason to be so cautious to not ask for too many bridges.

I would not expect explicit `maxweight` to be signed for example on a typical major road interchange - say https://www.openstreetmap.org/way/441972553#map=18/50.09400/19.89305 or https://www.openstreetmap.org/way/21920244

Asking there seems pointless. Looking at this specific instances I am tempted to skip any road with `foot=no` and `turn:lanes`. I would expect such major roads to not have lowered maxweight limits.

**Comment by westnordost** [comment]
Still, I do not see the problem with adding the information that there is no maxweight sign in cases like these. Do we not also map the absence of a maxspeed sign?

**Comment by matkoniecz** [comment]
It gets a bit spammy and pointless to be asked about maxweight on bridges on flyovers such as https://commons.wikimedia.org/wiki/File:Rondo_ofiar_katynia_krk.jpg

![Rondo_ofiar_katynia_krk](https://user-images.githubusercontent.com/899988/59962839-0c885f00-94eb-11e9-8ace-12ab9e4ac110.jpg)

Especially in case of major roads going through area with many flyovers.

----

> Do we not also map the absence of a maxspeed sign?

In my experience maxspeed signs are often present on major roads. It is not unusual for even `highway=primary` to have explicit maxspeed sign that sets speed limit.

In comparison I would expect weak bridge with explicit maxweight limit to be extremely unusual on `highway=primary`.

On the other hand, in some countries `highway=primary` may actually have lower standards so I want to base exclusions on `foot=no`, `turn:lanes`, `lane`, `motorroad` and similar tags to skip major bridges where asking is almost certainly not useful.

**Comment by matkoniecz** [comment]
Looking at data it seems that Poland may be unusual - see `highway=primary` bridges with `maxweight` set: http://overpass-turbo.eu/s/K8M

![Selection_005](https://user-images.githubusercontent.com/899988/59963089-6b030c80-94ee-11e9-89b1-9b6e52e9bbad.png)

`maxweight and maxweight != none and maxweight != unsigned` popularity on bridges:

```
motorway 0.2%
motorway_link 0.2%
trunk 0.4%
trunk_link 0.4%
primary 0.5%
primary_link 0.2%
secondary 0.7%
secondary_link 0.5%
tertiary 1.0%
tertiary_link 0.2%
unclassified 0.9%
residential 0.9%
living_street 2.7%
service 0.9%
track 0.8%
pedestrian 0.3%
road 0.0%
```

based on this - I am thinking about including `highway=track` and dropping `highway=trunk/trunk_link`

**Comment by westnordost** [comment]
> On the other hand, in some countries highway=primary may actually have lower standards so I want to base exclusions on foot=no, turn:lanes, lane, motorroad and similar tags to skip major bridges where asking is almost certainly not useful.

But on the other hand, towns are not exactly full of flyovers. Again, I do not see a problem asking it for primary roads etc.

I also recently found out that using too many `or` in the tag filter expression will slow down the overpass query hugely. The tag filter expression used for the "Pedestrians prohibited" takes something like half a minute for an area the size of a neighbourhood.
This is because as Overpass itself knows no `or`, every `or` is a permutation. So, if a query includes (A or B or C) and (D or E), these actually become 6 subqueries (A and D, B and C etc) whose result is merged together. For the "Pedestrians prohibited" quest, it is blown up into 15 subqueries(!)
(Because of:
```
[...]
(
    sidewalk ~ none|no or 
    sidewalk:both ~ none|no or 
    (sidewalk:left ~ none|no and sidewalk:right ~ none|no)
)
[...]
and ( oneway~yes|-1 or bridge=yes or tunnel=yes or bicycle~no|use_sidepath or lit=yes )
```
So, in the future we must be more economical with these `or` expressions and think about what we can do about the current ones. @mmd-osm or is there an `or` after all and I oversaw it?

**Comment by mmd-osm** [comment]
Yes, there’s an or operator available via „(if:  ... )“

**Comment by 1ec5** [comment]
In the U.S., the presence of posted weight limits depends more on the age of the bridge than the road classification or number of lanes. Freeway bridges over rivers (like `highway=motorway` `lanes=2` `oneway=yes`) might have posted weight limits, while relatively minor bridges over creeks (like `highway=tertiary` `lanes=2`) might not.

**Comment by matkoniecz** [comment]
I started using and documented `maxweight:signed=no` - see https://wiki.openstreetmap.org/wiki/Key:maxweight#Marking_objects_without_signed_max_weight

I also posted about this on tagging mailing list.
