### ISSUE TITLE
Quest: fire_hydrant type, position and diameter

### ISSUE THREAD

**Issue by krzyk** [westnordost/StreetComplete#362]
There are many `emergency=fire_hydrant` that don't have useful tags, that could be easily added during survey using StreetComplete.
Tags:
* fire_hydrant:type
* fire_hydrant:position
* fire_hydrant:diameter (this tag is most useful for firefighters)

Type and position are easily visible even from far away, and diameter should be clearly written on the fire hydrant itself or on a plate near it (at least that's the case in Poland, would be good to have information how it looks like in other countries).

**Comment by westnordost** [comment]
Needs some research for which countries it can be shown (inclusive list).
Also, the feature to only show quest for certain regions.

On 30 June 2017 13:55:43 CEST, "Krzysztof Krasoń" <notifications@github.com> wrote:
>There are many `emergency=fire_hydrant` that don't have useful tags,
>that could be easily added during survey using StreetComplete.
>Tags:
>* fire_hydrant:type
>* fire_hydrant:position
>* fire_hydrant:diameter (this tag is most useful for firefighters)
>
>Type and position are easily visible even from far away, and diameter
>should be clearly written on the fire hydrant itself or on a plate near
>it (at least that's the case in Poland, would be good to have
>information how it looks like in other countries).
>
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/westnordost/StreetComplete/issues/362

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by matkoniecz** [comment]
fire_hydrant:position seems like something that can be done worldwide - and it would also as side effect verify whatever mapped hydrants are really there.

**Comment by krzyk** [comment]
I think both fire_hydrant:position and fire_hydrant:type can be shown worldwide - maybe this should be a separate quest from the diameter one (as the diameter is harder). Splitting it into 3 quests would be probably even better. What do you think?


As for diameter, this is tricky because we need to have probably different pictures per country to show the "badge" where one can read the diameter.

From a quick look on the web (and local knowledge of Poland), the list with diameters:
- Poland (https://wiki.openstreetmap.org/wiki/Pl:Tag:emergency%3Dfire_hydrant)
- UK (http://www.mappa-mercia.org/2016/12/a-guide-to-mapping-fire-hydrants-in-the-uk.html)
- Ireland (based on https://en.wikipedia.org/wiki/Fire_hydrant they use the same plates as in the UK)
- Germany (https://wiki.openstreetmap.org/wiki/DE:Tag:emergency%3Dfire_hydrant)
- Australia (also from https://en.wikipedia.org/wiki/Fire_hydrant - need to find out the plate image)

So if we start with the list above we could later on extend it.

**Comment by chrisdebian** [comment]
That's a good idea. It's better to gather good data, and add later, rather than try to get the complete solution ready, before we start gathering data.

Cheers,

Chris.

**Comment by rugk** [comment]
Things like diameter (and pressure) are, at least in some countries, also shown on special plates ([this here](https://wiki.openstreetmap.org/wiki/File:Hydrantenschild_Beispielgrafik_2009-01-29.svg) in Germany) or at least on the hydrant directly.
If you give the user the same image with empty numbers, they could easily fill in the data – even without knowing what number means what.

**Comment by krzyk** [comment]
@westnordost Are you OK with splitting this quest into 3 smaller ones (or 2: type+position and diameter)?

**Comment by westnordost** [comment]
Yes, first type, then position etc.

Btw, shouldn't the position be clear from the gps position?

On 4 July 2017 09:57:30 CEST, "Krzysztof Krasoń" <notifications@github.com> wrote:
>@westnordost Are you OK with splitting this quest into 3 smaller ones
>(or 2: type+position and diameter)?
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/westnordost/StreetComplete/issues/362#issuecomment-312808045

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by rugk** [comment]
It can be:
```
fire_hydrant:position=lane/parking_lot/sidewalk/green
```

And maybe a hydrant is near a lane/sidewalk near a parking_slot so it is hard to find out from the GPS only.

**Comment by gustavecha** [comment]
I'd like to inform you that a proposal aiming to clarify some fire hydrant keys is currently under RFC on OSM wiki
https://wiki.openstreetmap.org/wiki/Proposed_features/Fire_Hydrant_Extensions

Event if voting hasn't started, there are undergoing discussions and it may be useful to join them.
I find fire_hydrant:position completely redundant with a simple location=* and this may be refined.
Furthermore, many keys with :type suffix aren't so user-friendly

**Comment by krzyk** [comment]
@westnordost Do you want each quest to have its own icon, or could I reuse the hydrant one for the position/diameter quest?

If not, then for the diameter quest I think it is enough to add a ruler (there is one in one of the icons) to the hydrant. But I have trouble with the position quest, what should be added to differentiate it from the other hydrant quest s?

**Comment by westnordost** [comment]
I find it nicer (for the users) to have each an own icon, but it is not strictly required.

You sure you want to do position + diameter at all? The hydrant is not one of the most established tags and TBH beyond saying what kind of hydrant it is, I don't see much sense in the other tags.

**Comment by rugk** [comment]
> I find it nicer (for the users) to have each an own icon, but it is not strictly required.

IMHO you could just use a slight variation of the same icon if it is really similar. Don't know a good example for fire hydrants, however.

**Comment by matkoniecz** [comment]
> Btw, shouldn't the position be clear from the gps position?

In cases where hydrant was mapped at exact position and road as area (`area:highway`) is mapped - yes.

Otherwise it is easy to switch between `green` and `sidewalk` or `sidewalk` and `lane`

**Comment by matkoniecz** [comment]
`fire_hydrant:diameter` is problematic because it will be hard to obtain this value for non-experienced mappers. Some hydrants will be without indicators, other will have different way of specifying this depending on a location.

`fire_hydrant:position` should be mapped by locating hydrant node at the exact position where it is located, like any other objects. And mapping surrounding of fire hydrant is best done by, well, mapping surroundings of hydrant rather describing them as a special tag.

And #404 implemented the most valuable part of this suggestion (thanks!).

So overall it seems that it can be closed.

**Comment by krzyk** [comment]
@matkoniecz  @westnordost 
I disagree on both tags.

If you have underground hydrant `position` it is quite useful for firefighters to know how to find it quickly, GPS is not that reliable if the underground hydrant is buried in grass (seen one such case) or on a lane, which was also covered with leaning long grass.

And the diameter in some countries is shown on the sign near the hydrant (it is required by the law in Poland and I think also Germany and on the wiki you can see it in Belgium also - so maybe all EU countries? - and those signs look quite similar to each other).

So this can be enabled per country.

**Comment by matkoniecz** [comment]
> If you have underground hydrant position it is quite useful for firefighters to know how to find it quickly, GPS is not that reliable if the underground hydrant is buried in grass (seen one such case) or on a lane, which was also covered with leaning long grass.

But how `fire_hydrant:position=green` will help in this case? "hydrant is hidden in grass somewhere, anywhere" seems to not be an useful hint, while seeing hydrant position in relation to buildings/street/whatever seems much more effective.

At least basing on my surveying/resurveying fire hydrants (I am not a firefighter).

> And the diameter in some countries is shown on the sign near the hydrant (it is required by the law in Poland

Maybe it is required by law but it is often missing/unreadable. Is there even a standard format for that sign? Still, it would probably require quest interface per country.

**Comment by westnordost** [comment]
Additionally,  `position` is basically a free-form tag, so it is difficult to present these as options in StreetComplete. Should it be a free text input? In the local language? Or only a few selections (grass, parking lot, sidewalk)?
`diameter` is basically specialist knowledge that a surveyor with StreetComplete cannot be expected to understand (which value to read from the sign).

**Comment by tiptoptom** [comment]
> diameter is basically specialist knowledge that a surveyor with StreetComplete cannot be expected to understand (which value to read from the sign).

I think you don't have to be a specialist to fill in the right number in a blank sign. ([look here](https://github.com/streetcomplete/StreetComplete/issues/362#issuecomment-312503053)) 
However, this quest could be disabled by default. So if you not a specialist you don't see it on the map and if you're a specialist you can activate the quest and collect data more efficient than with any other editor.

**Comment by dr2okevin** [comment]
I would like to see a diameter quest. There are a lot of mapped hydrants that don't have a diameter. Adding the diameter should be as easy as adding a house number.
https://overpass-turbo.eu/s/14Pr

**Comment by matkoniecz** [comment]
> Adding the diameter should be as easy as adding a house number.

house numbers a re more typically signed, even unsigned can be relatively easy to obtain by asking. It is fairly common that both are unavailable for diameter.

**Comment by mnalis** [comment]
@dr2okevin did you read the rest of the issue? I cannot see how a regular person (ie. not an experienced firefighter with special tools) would know how to find diameter of [this](https://en.wikipedia.org/wiki/Fire_hydrant#/media/File:Fire_hydrant_in_chicago.jpg) or [this](https://upload.wikimedia.org/wikipedia/commons/6/65/Berlin_hydrant_20050211_p1000517.jpg) or [this](https://i.pinimg.com/originals/47/66/1c/47661cda4f26a324268514990bb2d8e6.jpg) (or many of the other types mentioned)? 
So to me (as layman) it looks infinitely more complex than copying few numbers from clearly visible house number plate which anyone can do.

Also, you could always leave a note in SC (with a photo!) and then later add details in full blown editor.

**Comment by tiptoptom** [comment]
@mnalis @matkoniecz

Most of the hydrants are underground so there is always a standardized sign. So I think it would be easier than mapping a housenumber because the sign looks all was the same.
Look here:
https://wiki.openstreetmap.org/wiki/File:Hydrantenschild_Beispielgrafik_2009-01-29.svg
The big number after the H is the diameter.

**Comment by matkoniecz** [comment]
> it is required by the law in Poland

It is often (mostly) missing in Poland, even if legally required

**Comment by dr2okevin** [comment]
I'm not in any way related to firefighters or otherwise specialized in this topic. But I mapped in my town maybe around 100 fire hydrands, and only one had no sign. (~1% fail rate) The Number is always clear visible and has no variations. But to compare house numbers, they are way more often missing or unclear. 
Exampels
- 1 House 2 complete different house numbers
- 3 Houses all 3 the same number
- No number visible
- 1 house with the number "3a-g"
So who can search for the correct house number, should have no problems finding the diameter.

**Comment by krzyk** [comment]
So basically there pros and cons of this. And cons can be resolved by disabling, or disabling by default the fire hydrant diameter quests.

This means one needs to create such quest :)

**Comment by dr2okevin** [comment]
> Here in my area, Germany, there are no such signs.
There must be. I'm also in Germany, every hydrant has a sign. Go out for a walk and look especially to the sidewalks. Sign is white with a red border. Usually around 30-50cm over ground. There are also blue signs for water and yellow for gas.

**Comment by Lee-Carre** [comment]
Re fire hydrant diameter of fitting / connector

> It is often (mostly) missing in Poland, even if legally required

While the vast majority in Jersey have a conspicuous (UK-style) sign, I've encountered several which did not (though, this may mean that they're disused, I dunno; I simply add a note:fire_hydrant in each case containing either the numerical values or that I couldn't find the sign).

Especially when there's no sign, for underground hydrants (I've never seen a non-underground hydrant, here) not only would a surveyor need to know how to correctly measure (and what to measure), but also have a tool to pry up the metal plate covering the hydrant's location. Besides the effort (and risk of being treated as suspicious), many are located within the roadway (some of which have heavy traffic) which would pose a risk of injury (and irritating drivers).

Even if there is a sign, it seems dubious to assume that it's accurate. I've encountered incorrect signage, before.

So, to me, FH diameter seems far more comparable to FH flow-rate. Thus, diameter seems well beyond the scope of SC asking simple questions that are easy to answer. This kind of surveying is far more specialist (knowledge, tools, time-of-day).

Worse, there's quite a mix of values, here. Some are likely metric, while some are likely still imperial. So, there would also need to be a way of setting (non-metric) units for an answer to be correct.

Not everything has to be an SC quest; some may be better left to non-novices using more general / generic / capable editors (like Vespucci). If such data would be used by actual fire-fighters in an emergency, it's even more important to avoid misleading data (guesses, or a number from a different part of the sign being mistakenly entered).

The likes of type & position of a hydrant seem trivial by comparison.

**Comment by Lee-Carre** [comment]
Re fire hydrant type

Perhaps this shouldn't be asked in Jersey(?), as all seem to be underground.

I'm unsure, though. I can see the value of explicit confirmation (rather than assuming a default). However, I've never been asked this quest, and am reasonably confident that it's never been asked (of anyone) in Jersey, since the only Jersey hydrants in OSM are my additions, for which I specify as many tags as I can (including type). Not to say that hydrants won't be added (possibly without characteristics being tagged) by others.

The quest being asked in Jersey is probably better decided by others.

**Comment by VileGecko** [comment]
An example from Ukraine re hydrants (underground hydrants are used almost exclusively).
While in big cities the majority of fire hydrants would be properly marked with signs nearby in smaller towns signs are often missing and the best what you can possibly expect most of the times is a [painted marker](https://commons.wikimedia.org/wiki/File:Fire_hydrant_sign,_Izmail,_Rosynka.jpg) sometimes even lacking distance to the hydrant. On some occasions there is no sign or marker at all and the presence of a hydrant can only be discerned by a red painted manhole cover.

Possibly this could be resolved by a new quest asking if a hydrant is marked by at least one sign (possible values `fire_hydrant:sign=yes`; `fire_hydrant:sign=informal`; `fire_hydrant:sign=no`). If there is no sign associated with a hydrant, or if there is only an informal marker then the quest for diameter should not pop up. This would also be useful to document any unmarked hydrants.

**Comment by westnordost** [comment]
Do you have a picture of the sign?

**Comment by danieldegroot2** [comment]
**Notice of deprecation**
`fire_hydrant:type=pond` has since been [deprecated](https://wiki.openstreetmap.org/wiki/Proposed_features/Fire_Hydrant_Extensions_(part_2)#Revisions_to_fire_hydrant:type=*) (2017-11-27).

From the [Fire hydrant](https://wiki.openstreetmap.org/wiki/Tag:emergency%3Dfire_hydrant) page
> A designated place where fire engines can park to pump water from a body of water (such as a river or lake), is mapped with [emergency](https://wiki.openstreetmap.org/wiki/Key:emergency)=[suction_point](https://wiki.openstreetmap.org/wiki/Tag:emergency%3Dsuction_point) (see the wiki page for that tag). If there is also a [pipe](https://wiki.openstreetmap.org/wiki/Tag:emergency%3Dfire_hydrant#fire_hydrant:type=*_details) present to make it easier to pump water, that pipe can be mapped as a hydrant with appropriate [water_source](https://wiki.openstreetmap.org/wiki/Key:water_source)=* and [fire_hydrant:pressure](https://wiki.openstreetmap.org/wiki/Key:fire_hydrant:pressure)=suction (see below).

(where the water may be tagged as [`emergency=fire_water_pond`](https://wiki.openstreetmap.org/wiki/Tag:emergency%3Dfire_water_pond) / [`emergency=water_tank`](https://wiki.openstreetmap.org/wiki/Tag:emergency%3Dwater_tank))

**Comment by westnordost** [comment]
Will change to `pipe` because that is what the photo shows.
