### ISSUE TITLE
Quests hidden in high zoom levels

### ISSUE THREAD

**Issue by rugk** [westnordost/StreetComplete#364]
The zooming behaviour is sometimes strange. I get that some quests may be hidden when the zoom level is low (= wide area to see), but sometimes you can also see a quest in a low zoom level, but when you zoom in (to a bigger zoom level) it is hidden.

E.g.
Low zoom level:
![lowzoom](https://user-images.githubusercontent.com/11966684/27740799-641c3280-5db3-11e7-9363-2cee9bc1c793.png)

(You can see the house number quest near the current position.)

Now when you zoom in:
![noicon](https://user-images.githubusercontent.com/11966684/27740863-947f390e-5db3-11e7-9e87-54de17d3e3d2.png)
![highzoom](https://user-images.githubusercontent.com/11966684/27740866-964c8cd2-5db3-11e7-9848-5a6d89475c2b.png)

Funnily enough it sometimes even happens when you answer the quest. 

This is how it looks in this case:
![answer_high_zoom](https://user-images.githubusercontent.com/11966684/27740910-c38e5900-5db3-11e7-84f6-205b1d6a09d5.png)

v0.12

**Comment by westnordost** [comment]
https://github.com/westnordost/StreetComplete/commit/6c25e124cc2f61a8d9d1c79b6ec1a326cc588210 is not in version 0.12, I think this greatly improves the user experience. It will be included in v1.

**Comment by Natenom** [comment]
In current git master this bug is back, see https://files.natenom.com/nidx/nobackup/sharing/6d5eefc3d2c02544b3992c3707ed9c50696409ea8157a1d0dd08622e3db1b5aa.png

The same area in three different zoom levels.
