### ISSUE TITLE
New quest: Ask what is produced on this landuse

### ISSUE THREAD

**Issue by rugk** [westnordost/StreetComplete#367]
Some non-agricultural things, which are unlikely to change. The [produce](https://wiki.openstreetmap.org/wiki/Key:produce#Typical_Values) wiki page has some:
* `landuse=aquaculture` --> fish/mussels/oysters/shrimp
* `landuse=farmland` --> cereal/berries
* `landuse=forest` --> cork/christmas_trees

Should be fairly simple to answer and only applies to specific `landuse` objects, so it is not shown in cases where you cannot answer anything.

**Comment by rugk** [comment]
I think we could include vineyard here. At least a quest if nothing else has been specified, …

**Comment by HolgerJeromin** [comment]
Many wood/forest are tagged as landuse=forest. That would be a) too much and b) i would have no idea what to answer.

![image](https://user-images.githubusercontent.com/2410353/27753008-103978e0-5de4-11e7-91d5-25dc67a1f2d2.png)

**Comment by westnordost** [comment]
Yeah, no. You should focus on the orchard quest, I find it promising and interesting. There is also much research to be done for that and pictures to be found.

> aquaculture 
How would you see what is in the water?

> forest
See Holger

**Comment by rugk** [comment]
Oh, actually I did not thought forests are so widespread, but ehm… yeah… of course. And they have no "product".

As for aquaculture: There is surely a plate somewhere… :smile:
