### ISSUE TITLE
Keyboard overlays password input field in registration form

### ISSUE THREAD

**Issue by Ellibeere** [westnordost/StreetComplete#37]
When inputting my info for registration I couldn't scroll further during the input of the password. Thus I wasn't able to see me typing there (see second image). It still worked though.

![image1](https://cloud.githubusercontent.com/assets/26724381/24376773/63d6cce2-133d-11e7-856f-d5fd5887037f.png)
![image2](https://cloud.githubusercontent.com/assets/26724381/24376774/63db68ba-133d-11e7-9898-d9861dc7ef7a.png)

**Comment by westnordost** [comment]
I might have to make this dialog fullscreen then.
