### ISSUE TITLE
Use oneway-data from improveosm.org

### ISSUE THREAD

**Issue by amilopowers** [westnordost/StreetComplete#370]
Hello

improveosm.org is an amazing tool to find turn restrictions, oneways, missing roads and so on. It uses metadata from traffic data.

I don't know how hard this would be to implement but I'd love to see if your app could work together with improveosm.

Like this your app could ask questions like "is there a turn restriction from raod x to y?" (maybe with visual support) or is this a one-way restricted road?

I am not a dev so I can't help with implementing.

**Comment by chrisdebian** [comment]
This is what I was suggesting, here: 

https://github.com/westnordost/StreetComplete/issues/359

Thanks,

Chris.

**Comment by westnordost** [comment]
What is the URL?

**Comment by matkoniecz** [comment]
https://improveosm.org/

**Comment by matkoniecz** [comment]
> missing roads

See https://github.com/westnordost/StreetComplete/wiki/Adding-new-Quests-to-StreetComplete (linked during creating a new issue)

> Only existing elements can be extended, no elements can be added or removed.

**Comment by chrisdebian** [comment]
Maybe also some crossover with Mapswipe (http://wiki.openstreetmap.org/wiki/MapSwipe) and OpenMapKit (http://openmapkit.org/index.html).

But they could probably gain more from StreetComplete

**Comment by westnordost** [comment]
Perhaps you should include what data exactly could be used as a data source for quest types.

On 2 July 2017 14:38:13 CEST, chris_debian <notifications@github.com> wrote:
>Maybe also some crossover with Mapswipe
>(http://wiki.openstreetmap.org/wiki/MapSwipe) and OpenMapKit
>(http://openmapkit.org/index.html).
>
>But they could probably gain more from StreetComplete
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/westnordost/StreetComplete/issues/370#issuecomment-312489448

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by rugk** [comment]
> Like this your app could ask questions like "is there a turn restriction from raod x to y?" (maybe with visual support) or is this a one-way restricted road?

Yeah, I think that's a good example. Maybe you should collect such examples and open new issues with "New quest:" for each of them, so each of these questions can be tracked separately.
You can mention there that osmimprove.org also does it, but the implementation will likely be independent to it. Anyway, it is of course a good source for some ideas… :smile: 
Of course [pay attention to the docs](https://github.com/westnordost/StreetComplete/wiki/Adding-new-Quests-to-StreetComplete).

> Mapswipe

Not really. The purpose of this app is not really to show you satellite images.

> OpenMapKit

A library or so, somehow about surveys with OSM. Not sure what this has to do with StreetComplete.

**Comment by westnordost** [comment]
Okay, I looked through the source code of improveosm.org. The only thing that would be usable for StreetComplete would be the "is probably a oneway" detection.

There is an API, but it is not documented.Example call to get all open "direction of flow":

http://directionofflow.skobbler.net/directionOfFlowService/search?format=fjson&south=53.0&north=53.1&west=9.0&east=9.1&zoom=15&confidenceLevel=C1%2CC2%2CC3&status=OPEN&client=WEBAPP&version=StreetComplete%200.11

As far as I can see, the API part of improveosm.org is closed source, so there are a few problems and open questions:
- the client parameter must always be WEBAPP, anything else is not accepted. This sounds like it is not wanted that other applications use this API
- a zoom level MUST be specified, depending on the zoom level (and/or density of found road sections), "clusters" are returned. StreetComplete is not interested in clusters, we need the real data. In my test call, starting with zoom level 15, proper data is returned, but:
- the bounding box is very limited. The exact max bounds are unclear, but it relates to the zoom level. 
- it is unclear whether the API returns results for whole ways (probably not?) or also for way-sections that'd have to be split up. Currently, StreetComplete is not able to split ways up.

**Comment by chrisdebian** [comment]
Thanks for looking at this, Tobias. Sounds disappointing, as it was
hopefully a good source of data that needs clarifying.

Thank you,

Chris.

**Comment by chrisdebian** [comment]
This is related, so won't open a new ticket.

Can we use the data from Osmose (http://osmose.openstreetmap.fr/en/map/) or KeepRight (https://www.keepright.at/), to help generate quests?

Thanks,

Chris.

**Comment by rugk** [comment]
Could you please explain what (useful data) these sites provide, which could be used in StreetComplete? And how could it be used?

**Comment by westnordost** [comment]
So, no reply from telenav so far. improveosm.org doesn't seem to be still maintained and I don't know any other way to contact them.

**Comment by westnordost** [comment]
If anyone wants to follow this further, perhaps here: https://telenav.zendesk.com/

**Comment by Binnette** [comment]
Note JOSM plugin for ImproveOSM is available here :
https://github.com/Telenav/improve-osm-plugin
May be you can find answer in it.
BTW, i also contact Telenav and ubermih. Waiting for answers...

**Comment by beataj-telenav** [comment]
Hello all, currently the ImproveOSM services are not open sourced, and are consumed only by Telenav projects. 
For more information regarding this, please send an email to: beata.jancso@telenav.com and martijnv@telenav.com.

**Comment by rugk** [comment]
> Since the services are not open sourced (not open for the public)

Why are not they?

**Comment by westnordost** [comment]
OK, I will send you and email explaining why this project would like to use this data and what requirements would need to be met to properly use the data. Thanks for your answer and thanks @Binnette for taking over to reach out.

**Comment by mvexel** [comment]
Update: @westnordost and I have been in touch and we are exploring the integration. @beataj-telenav is on vacation right now but we hope to check back in in a couple of weeks.

**Comment by westnordost** [comment]
done

**Comment by rugk** [comment]
Did I miss something or what happened to the "turn restrictions"? Telenav [also has some dumps for it](https://missingroads.skobbler.net/dumps/) and it could be implemented in a similar way.

**Comment by westnordost** [comment]
I wrote
> Okay, I looked through the source code of improveosm.org. The only thing that would be usable for StreetComplete would be the "is probably a oneway" detection.

in https://github.com/westnordost/StreetComplete/issues/370#issuecomment-312927346

Turn restrictions would often involve splitting up the ways. Can't be done in StreetComplete.

**Comment by rugk** [comment]
Are not turn restrictions just at intersections of ways? Don't see where you need to split a way there. It just needs a quite complex GUI as iD e.g. has:

![grafik](https://user-images.githubusercontent.com/11966684/42134107-0a52cd52-7d35-11e8-808c-9350ede7fd79.png)

(Don't know the details, but for a user it looks just as if you edit the single points, where the streets meet. Technically likely done with something in a relation or so…)

**Comment by matkoniecz** [comment]
> Don't see where you need to split a way there.

iD editor splits ways to create some restrinctions

**Comment by rugk** [comment]
Okay, mhh… :thinking:

**Comment by beataj-telenav** [comment]
Telenav suggest possible turn restrictions missing from OpenStreetMap. Editing a turn restriction is indeed a more complex task.
