### ISSUE TITLE
Setting to use "original" Google Play Services/Location API

### ISSUE THREAD

**Issue by rugk** [westnordost/StreetComplete#372]
I see you are currently using [lost](https://github.com/mapzen/lost) for location access. This is nice as it is independent from Google.

However, some users may just have nothing against using the original Google Play location API to get the current location in a faster way (with wifi/cellular data) or may even have [microg](https://microg.org/) or [UnifiedNlp](https://github.com/microg/android_packages_apps_UnifiedNlp/blob/master/README.md) (for non-root users) installed, so the data does not touch Google anyway.

These users would likely like an option "Use Google Play Services" in the settings to use the original Play Services for getting the location. It can be off by-default.

**Comment by westnordost** [comment]
LOST also uses wifi and cellular. The only difference is that 
* lost is pretty unstable still it seems
* lost has no nice "location is off, turn it on now?" dialog but instead the user needs to be sent to the settings

Anyhow, I will not include Google Play Services, sorry. AFAIK apps that use play services also get flagged or downright not-accepted on F-Droid.

**Comment by rugk** [comment]
> lost is pretty unstable still it seems

Haha, what an argument in favour of using it.

> AFAIK apps that use play services also get flagged or downright not-accepted on F-Droid.

Yeah, right. I should have mentioned this. Other app developers do it by just doing two builds. One for Google Play with all these things built-in and one for F-Droid. Also do you really need to include some proprietary library from Google in order to use the Play Services?

**Comment by westnordost** [comment]
I am pretty sure I do.

**Comment by rugk** [comment]
You do separate builds? (i.e. have a way to modify some things with parameters or so at built time) Then fixing this issue is possible…
