### ISSUE TITLE
Solving quests while "Scanning for new quests" let them reappear after the scan

### ISSUE THREAD

**Issue by Natenom** [westnordost/StreetComplete#373]
How do reproduce?

Press "Scan for new quests", solve one or more quests, wait until scan was finished. Solve the same quests again. This is very annoying in "auto sync mode".

Version: current git master

**Comment by westnordost** [comment]
Oh, right. I guess solved and successfully uploaded quests must still remain in the local database for at least the time Overpass needs takes to update its data.

On 2 July 2017 21:52:42 CEST, Natenom <notifications@github.com> wrote:
>How do reproduce?
>
>Press "Scan for new quests", solve one or more quests, wait until scan
>was finished. Solve the same quests again. This is very annoying in
>"auto sync mode".
>
>Version: current git master
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/westnordost/StreetComplete/issues/373

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by matkoniecz** [comment]
>  for at least the time Overpass needs takes to update its data.

Statistics about database lag are at https://overpass-api.de/munin/localdomain/localhost.localdomain/osm_db_lag.html

**Comment by westnordost** [comment]
Nice, thanks. So 5 minutes would be on the safe side.
