### ISSUE TITLE
Import Trees in Germany/Berlin

### ISSUE THREAD

**Issue by joshinils** [westnordost/StreetComplete#3738]
There exist public (and regularly maintained) Datasets usable for OSM;
Trees - https://fbinter.stadt-berlin.de/fb/berlin/service_intern.jsp?id=k_wfs_baumbestand@senstadt&type=WMS
Grouped into several types:

Trees alongside Roads:
* Baumbestand Berlin - Straßenbäume ohne Datenbankeintrag
* Baumbestand Berlin - Straßenbäume

Trees in Public Parks:
* Baumbestand Berlin - Anlagenbäume ohne Datenbankeintrag
* Baumbestand Berlin - Anlagenbäume

The WFS source also includes more info than "here is a tree":
for example I added this tree from this source after manually verifying its location and number (which is on the tree itself); https://www.openstreetmap.org/node/9044602822
but, the format may have to be converted to be conforming to osm tags, the circumference for example is in centimeters, not meters which the osm-tag circumference assumes.

### related: https://wiki.openstreetmap.org/wiki/User:Supaplex030/Baumabgleich
@supaplexosm ([supaplex030](https://www.openstreetmap.org/user/Supaplex030/)) has checked the data for themselves as well

----
### General
Affected tag(s) to be modified/added:
`check_date:ref`=*
[`circumference`](https://wiki.openstreetmap.org/wiki/Key:circumference?uselang=en)=0.31
[`genus`](https://wiki.openstreetmap.org/wiki/Key:genus?uselang=en)=Quercus
[`genus:de`](https://wiki.openstreetmap.org/wiki/Key:genus:de?uselang=en)=Eiche
[`height`](https://wiki.openstreetmap.org/wiki/Key:height?uselang=en)=5
[`natural`](https://wiki.openstreetmap.org/wiki/Key:natural?uselang=en)=[`tree`](https://wiki.openstreetmap.org/wiki/Tag:natural=tree?uselang=en)
[`ref`](https://wiki.openstreetmap.org/wiki/Key:ref?uselang=en)=001/02
[`source`](https://wiki.openstreetmap.org/wiki/Key:source?uselang=en)=Geoportal Berlin / Baumbestand Berlin / Straßenbäume
[`source:date`](https://wiki.openstreetmap.org/wiki/Key:source:date?uselang=en)=2021-08-22
[`species`](https://wiki.openstreetmap.org/wiki/Key:species?uselang=en)=Quercus rubra
[`species:de`](https://wiki.openstreetmap.org/wiki/Key:species:de?uselang=en)=Amerikanische Rot-Eiche
[`start_date`](https://wiki.openstreetmap.org/wiki/Key:start%20date?uselang=en)=2006`

Question asked: 
**Is there a Tree here with the number "001/02?" on it somewhere**
**Is this an oak tree?**
since the data-source includes detailed information about the types of tree this could also be checked and added, amybe as another quest
**is the circumference of this tree about 0.31 metres?**

### Checklist
Checklist for quest suggestions (see [guidelines](https://github.com/streetcomplete/StreetComplete/wiki/Adding-new-Quests-to-StreetComplete)):
- [x] 🚧 To be added tag is established and has a useful purpose
- [x] 🤔 Any answer the user can give must have an equivalent tagging (Quest should not reappear to other users when solved by one)
- [x] 🐿️ Easily answerable by everyone from the outside but a survey is necessary
- [ ] 💤 Not an overwhelming percentage of quests have the same answer (No spam)
no, if the tree is not in the osm data the anser will probably be the same for every tree on any given road
- [x] 🕓 Applies to a reasonable number of map data (Worth the effort)
The dataset includes more than 400'000 individual trees alongside roads, 
and about 350'000 trees in parks (which may be hard to identify, since some parks may have many trees in a small area and look like a forest from areal imagery. 

#### checking for existing trees in osm
- if there is a tree in the vicinity of a datapoint it would need to be referenced against, if it has no ref.
- if it has a ref, ignore the datapoint, since the tree already exists, even if at another position.
  - the ref may be wrong in the data-source, so the offset may be more than a few metres.
  - i have seen this once; this could be because of a one-off error in the source, then every tree has the ref of the next tree, the positions may still be accurate enough though
- the ref may be missing on the tree itself, but the tree exists on-the-ground.
- the tree may no longer exist on-the-ground.
  - re-checking of all trees in berlin occurs about once a year by paid "tree-checkers", i've met one of them and they also check if the tree is healthy or needs care.
- the tree may no longer exist as in the data-source, and has been replaced by a new tree. this should be obvious as the new tree is much smaller, has a smaller circumference, height, crown-diameter or may not have a ref or may be another type of tree.

then, add the tree to osm

**Element selection:** 
for each non-imported tree show a quest with a tree icon.
while answering, show all trees on the map to reference against, with their numbers, also show non-answered trees with their numbers. this should be useful to check if one has missed a tree or if the ref is wrong on the tree itself or in the data-source

#### other related quests:
- checking which type of tree a tree is could be another quest, which includes pictures of leaves, the whole tree, what the bark looks like. i am not qualified for this.
- the same type of source exists for streetlamps of berlin
  - about 210'000 lamps
  - each with more info than just the position
    - https://www.openstreetmap.org/node/8362598839
    - `check_date:ref`=`2021-08-28`
    - [highway](https://wiki.openstreetmap.org/wiki/Key:highway?uselang=en)=[`street_lamp`](https://wiki.openstreetmap.org/wiki/Tag:highway=street%20lamp?uselang=en)
    - `lamp_model:de`=Lichtmast mit Auslegerleuchte
    - [`lamp_mount`](https://wiki.openstreetmap.org/wiki/Key:lamp%20mount?uselang=en)=bent_mast
    - [`lamp_type`](https://wiki.openstreetmap.org/wiki/Key:lamp%20type?uselang=en)=electric
    - [`ref`](https://wiki.openstreetmap.org/wiki/Key:ref?uselang=en)=1
    - [`source`](https://wiki.openstreetmap.org/wiki/Key:source?uselang=en)=Geoportal Berlin / Öffentliche Beleuchtung
    - [`source:date`](https://wiki.openstreetmap.org/wiki/Key:source:date?uselang=en)=2021-08-22
    - [`support`](https://wiki.openstreetmap.org/wiki/Key:support?uselang=en)=pole

**Comment by matkoniecz** [comment]
See https://github.com/streetcomplete/StreetComplete/discussions/2477

**Comment by westnordost** [comment]
I don't think this can be done with reasonable effort / complexity which is why I'll close this:
1. The data from the source needs to be represented to the user somehow. That's a lot of data to display and StreetComplete usually doesn't display bare tags but text, icons, graphics
2. What to do if the location of the tree is slightly wrong? Moving things is not implemented and is considerable effort to do #3502 (because of all the edge cases) but at the same time would be very useful or even necessary
3. For the data to be usable by StreetComplete, there must be an API with which the data can be queried by arbitrary bounding box. If it doesn't exist yet, it would need to be implemented.
4. https://wiki.openstreetmap.org/wiki/User:Supaplex030/Baumabgleich came to the conclusion that the data is of high quality and precision and suggested that the data it should be enough to compare the data with aerial imagery as validity check. Hence, it is much better and more efficient to do this in JOSM

**Comment by joshinils** [comment]
ok, thank you for reading. 
i feel the need to look at every tree on-the-ground to validate the ref-number in person, so i wish there was an easy-to-use editor like streetcomplete for this kind of thing.
i have previously printed a list of all trees in one street and manually verified them on-the-ground and later imported the data via josm.

**Comment by matkoniecz** [comment]
>  i feel the need to look at every tree on-the-ground to validate the ref-number in person, so i wish there was an easy-to-use editor like streetcomplete for this kind of thing.

If data is high quality one I would do this with a sample and just import everything if dataset would be consistently correct.

**Comment by joshinils** [comment]
> > i feel the need to look at every tree on-the-ground to validate the ref-number in person, so i wish there was an easy-to-use editor like streetcomplete for this kind of thing.
> 
> If data is high quality one I would do this with a sample and just import everything if dataset would be consistently correct.

well, yeah. 
but i have done this for two streets, and on one oth them a section of trees were numbered one-off and so the position was wrong or the ref was wrong.
also, for another street two streetlamps shared the same number on-the-ground, then one was skipped, the data showed no double number and no skip.

so I'd say i am not satisfied with the quality of the data, it is good - yes, but not perfect.

**Comment by thibaultmol** [comment]
@joshinils Mapcomplete has a builtin import helper tool sort of. It was originally developed for the Flemish gov tourism org to add a bunch of their dataset (benches, toilets, bike chargers, ...) to osm but manually verify everything. https://github.com/pietervdvn/MapComplete

**Comment by joshinils** [comment]
> @joshinils Mapcomplete has a builtin import helper tool sort of. It was originally developed for the Flemish gov tourism org to add a bunch of their dataset (benches, toilets, bike chargers, ...) to osm but manually verify everything. https://github.com/pietervdvn/MapComplete

interesting, yes.
though I only see an option for an overpass query to select already existing elements on which i can operate and ask custom questions.
not one where i can point to another data source like the berlin geoportal or for uploading a file with data to-be-imported like this.
