### ISSUE TITLE
What's sport=skating?

### ISSUE THREAD

**Issue by antonv6** [westnordost/StreetComplete#374]
https://wiki.openstreetmap.org/wiki/Tag:sport%3Dskating says that "Skating involves any sports or recreational activity which consists of traveling on surfaces or on ice using skates" and suggests to "Use sport=ice_skating and sport=roller_skating to avoid confusion".

Since we already have sport=skateboard and sport=ice_skating, maybe this should also be renamed to the more specific roller_skating?

**Comment by westnordost** [comment]
Right, makes sense

**Comment by westnordost** [comment]
It should probably also be included in the overpass filter so that the app asks the user for the sport played in all places with sport=skating again.
