### ISSUE TITLE
i18n: piecing words together to make a human-facing phrase is bad

### ISSUE THREAD

**Issue by antonv6** [westnordost/StreetComplete#375]
For example, "Is this %s wheelchair accessible?" that would be used with "bus stop", "subway entrance" and "location". Many languages are gendered, and can have different forms of pronouns and even adjectives depending on a subject described. Let's take pronoun "this", in e.g. Spanish it will depend on gender of that thing that it points to: "este" for masculine and "esta" for feminine. Adjective "accessible" in Russian is also tricky like this: "доступен" and "доступна". So there's no way to translate this phrase so that it would always work correctly in those languages.

To be fair, I don't know if Spanish would be fine for now, because "parada", "entrada" and "ubicación" (if that's what the translators chose, I can't see it) are all feminine, but there's also no way to guarantee that all location types would be like that in the future. The fact is, in Russian this phrase already falls apart as it is now.

**Comment by westnordost** [comment]
Right. Same in German actually, haha. Perhaps a neutral wording can be found which does bot require a pronoun.

On 3 July 2017 08:56:50 CEST, Anton Shestakov <notifications@github.com> wrote:
>For example, "Is this %s wheelchair accessible?" that would be used
>with "bus stop", "subway entrance" and "location". Many languages are
>gendered, and can have different forms of pronouns and even adjectives
>depending on a subject described. Let's take pronoun "this", in e.g.
>Spanish it will depend on gender of that thing that it points to:
>"este" for masculine and "esta" for feminine. Adjective "accessible" in
>Russian is also tricky like this: "доступен" and "доступна". So there's
>no way to translate this phrase so that it would always work correctly
>in those languages.
>
>To be fair, I don't know if Spanish would be fine for now, because
>"parada", "entrada" and "ubicación" (if that's what the translators
>chose, I can't see it) are all feminine, but there's also no way to
>guarantee that all location types would be like that in the future. The
>fact is, in Russian this phrase already falls apart as it is now.
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/westnordost/StreetComplete/issues/375

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by matkoniecz** [comment]
The same in Polish. Probably it would be better to have separate sentence for every case. I would not expect that it is possible to find wording that would be natural and work by piecing words together in all languages (even if something works in several major languages it will surely fail once people will start translating obscure ones).

**Comment by rugk** [comment]
> if that's what the translators chose, I can't see it

https://github.com/westnordost/StreetComplete/blob/95517385016a1b8e56ff348979f92c4ef3d8a5fc/app/src/main/res/values-es/strings.xml

Likely you have to find different versions and have the possibility for the translator to specify whether e.g. a plural version should be used. Or e.g. include the "this" in the "%s" part…
