### ISSUE TITLE
Mention street name in quests about streets

### ISSUE THREAD

**Issue by rugk** [westnordost/StreetComplete#378]
When a quest about a street (surface) is asked, it would be nice if the street name (if available) of the selected street is mentioned in the question (or, better, the small grey text below).
This would make it easier to find the street you've just tapped on (in case the zoom was too fast or so…). It could also help in https://github.com/westnordost/StreetComplete/issues/237 a bit.

**Comment by matkoniecz** [comment]
Done by #347
