### ISSUE TITLE
The form to select schedule of building does not set hours (when it is selected diferent schedule by month).

### ISSUE THREAD

**Issue by mdtrooper** [westnordost/StreetComplete#380]
I can not select a hours for schedule of the library of my district. Because previously I set the diferent schedule by months.

There are screenshots...in spanish.

The app version is 0.12 .

Thanks and regards.

**Comment by mdtrooper** [comment]
![screenshot_2017-07-05-10-21-16](https://user-images.githubusercontent.com/1285451/27856268-e21ed670-616d-11e7-8ea2-983f46a7ae3a.png)

![screenshot_2017-07-05-10-21-32](https://user-images.githubusercontent.com/1285451/27856288-eef064c2-616d-11e7-9337-bc55a70ef0c2.png)

**Comment by westnordost** [comment]
What's the problem here?

You need to click `Anadir horarios de apertura` after you selected the months.
