### ISSUE TITLE
sometimes on "there is no sign" nothing happens

### ISSUE THREAD

**Issue by matkoniecz** [westnordost/StreetComplete#382]
reproduced with 5ccfc3c
persists across installs and clearing quest cache

go to https://www.openstreetmap.org/way/24376991#map=18/50.08270/19.93749 in SC
fetch quests
select "other answers..."
select "there is no sign"

at this point nothing happens (including no entries in Android Monitor in Android Studio).

expected: "Are you sure that no..." dialog (or at least exception visible in Android Monitor)

**Comment by westnordost** [comment]
[Whoops, I already see the error.](https://github.com/westnordost/StreetComplete/blob/master/app/src/main/java/de/westnordost/streetcomplete/quests/max_speed/AddMaxSpeedForm.java#L34) Happens with all unclassified roads. Would you like to commit the fix?
