### ISSUE TITLE
Release first v1.0 beta

### ISSUE THREAD

**Issue by westnordost** [westnordost/StreetComplete#383]
v0.13 has been released and if there are (finally) no major issues with it, I will release it as non-beta on Google Play this weekend. Then, the way is free for a first v1 beta release.

I felt I should write something about the roadmap, since many of you already contributed quests and you might wonder when they are finally included in a public version.

I plan to release a first v1 beta after I am done with `multilingual-streetnames` and `cycleways`, that is in about two weeks from now.

This will not be a feature complete version, since #35 should also go in v1. When I am done with that, the preceding will be like for v0. Bugfixes and/or small improvements can still go in that version, everything else will go into v2.

So, the time frame for getting things into v1 (already started and) ends - more or less, no sweat! - with when I am done with #35. Very rough estimation would be in 2 months.

**Comment by chrisdebian** [comment]
Tobias,

Is there a way to download APKs, before they hit the Play store, to help
with testing; I couldn't see any on Github?

Cheers,

Chris
chris_debian

**Comment by westnordost** [comment]
Actually, there is no real reason to delay the next major version. It's not as if it would be faster if I put the mentioned feature in version 1 instead of version 2.

So, version 1 will soon be released. The next weeks will just be polishing existing quests, betatesting and resolving bugs.
