### ISSUE TITLE
GPS indicater not working correctly

### ISSUE THREAD

**Issue by Natenom** [westnordost/StreetComplete#384]
Version: current git master

How to reproduce:

- Open App first time, wait until position is available
- Switch to another app and then back

GPS indicator is blinking even if position is displayed.

+It takes very long until the position is displayed although it is available in other apps very fast at the same time.

How to fix:
- Kill the app SC
- Start it.
- = instant gpx fix

**Comment by westnordost** [comment]
Already reported https://github.com/mapzen/lost/issues/233

On 7 July 2017 07:16:19 CEST, Natenom <notifications@github.com> wrote:
>Version: current git master
>
>How to reproduce:
>
>- Open App first time, wait until position is available
>- Switch to another app and then back
>
>GPS indicator is blinking even if position is displayed.
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/westnordost/StreetComplete/issues/384

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by westnordost** [comment]
Ah right, this is fixed since 1.2
