### ISSUE TITLE
ask for sac_scale for highway=path/footway with route=hiking relations

### ISSUE THREAD

**Issue by matkoniecz** [westnordost/StreetComplete#387]
http://wiki.openstreetmap.org/wiki/Tag:route%3Dhiking
http://wiki.openstreetmap.org/wiki/Key:sac_scale

idea extracted from #385

**Comment by westnordost** [comment]
If you expect others to implement it, you need to be a bit more forthcoming: What should the Overpass query look like, what should the design look like etc pp.

**Comment by matkoniecz** [comment]
after attempting to implement this quest at start for my fork I discovered that the scale is too detailed to ever fit into SC quest

at least I see no way to do it properly

**Comment by westnordost** [comment]
What do you mean, too detailed?

**Comment by matkoniecz** [comment]
Yes, with wiki description at https://wiki.openstreetmap.org/wiki/Key:sac_scale#Values I was unable to classify a route that I remembered well.

And given that I am still stuck with [answers](https://github.com/matkoniecz/Zazolc/blob/fork/app/src/main/res/values/strings.xml#L282) to [parking access quest](https://github.com/matkoniecz/Zazolc/tree/fork/app/src/main/java/de/westnordost/streetcomplete/quests/parking_access) as being not a good enough to make PR, I would not expect a success here.

**Comment by michalgwo** [comment]
I don't think it's too hard to classify sac_scale, we can add photos from the wiki. If we are asking for smoothness, we could also ask for sac_scale, which in my opinion is easier to classify and sac_scale would be highly beneficial for hikers. I think we should reconsider this.

**Comment by matkoniecz** [comment]
> I don't think it's too hard to classify sac_scale, we can add photos from the wiki.

with wiki descriptions and photos at https://wiki.openstreetmap.org/wiki/Key:sac_scale#Values I was unable to classify a route that I remembered well.

**Comment by mnalis** [comment]
> If we are asking for smoothness

Note that `smoothness` quest was already at the limits of what could possibly be supported, and it required _huge_ amount of work to make it suitable for SC. 

And yet, whole of  `smoothness` is just one (smaller) point of several in the matrix (like trail, use of hands, terrain, steepness, danger, equipment/skills required are some of the others) needed to properly determine `sac_scale`.  


> I don't think it's too hard to classify sac_scale, we can add photos from the wiki

It is IMHO significantly more complex than just photos... Especially ones resized to just a part of (already tiny!) mobile screens!

As a survivor of ["scramble" community thread](https://community.openstreetmap.org/t/feature-proposal-voting-highway-scramble/5228) for example, I'm too not feeling confident that average SC user would be able to [verifiably](https://wiki.openstreetmap.org/wiki/Verifiability) identify `sac_scale` (even if we _somehow_ managed to present them that whole [identification table](https://wiki.openstreetmap.org/wiki/Key:sac_scale#Values) from the `sac_scale` wiki without overwhelming them), unless there happened to be official sign with SAC T1-T6 markings posted on the trail.

Importantly, [StreetComplete Quest Guidelines](https://github.com/streetcomplete/StreetComplete/blob/master/QUEST_GUIDELINES.md) (among other things) say:
 
- _👨‍💻 Users are no experts: No knowledge about OpenStreetMap or any other background knowledge must be necessary_

For tagging `sac_scale`, I'm afraid that both mountaineering experience  as well as knowledge of OSM wiki definitions (as many regions use other different scales/rating systems, see the thread above) might be required.

---

That being said, what might be interesting to you @michalgwo is [SCEE](https://wiki.openstreetmap.org/wiki/SCEE) (StreetComplete _"expert edition"_). 

It already allows one to add custom tags (like `sac_scale`) manually to ways (so solves your need, albeit not in most user-friendly way - you need to enable `expert mode` first); but also it does not balk at **required domain expert knowledge** as prerequisite for solving quests, so it should be significantly more open to such quest if one were to [suggest](https://github.com/Helium314/SCEE/issues) it.
You can have both SCEE and regular StreetComplete installed simultaneously if you want to try it out.

**Comment by rhhsm** [comment]
I hope one day this and other hiking related keys will be StreetComplete quests, but I think we should wait until [this discussion](https://community.openstreetmap.org/t/rfc-part-3-foot-scale-aims-to-describe-global-paths-in-a-more-helpful-and-informative-scale-than-sac/109193/42) will lead to an accepted proposal.
