### ISSUE TITLE
Signin wth Github

### ISSUE THREAD

**Issue by Raffaele74** [westnordost/StreetComplete#389]
Android 6 Huawei VNS L31
When I write my Github name in login, app doesn't do.

**Comment by westnordost** [comment]
Which version? What is the error?

**Comment by Raffaele74** [comment]
Build 0.13. Last on Google Store.
If I try to sign in with Github  i push keys but app replaces pw, not replaces username. Username remains empty.

**Comment by westnordost** [comment]
You need to be more specific here. Nowhere in this app, there is any password or username field.

**Comment by matkoniecz** [comment]
>  Nowhere in this app, there is any password or username field

Authentication dialog (even in in external browser form) may be perceived as part of app.

**Comment by Raffaele74** [comment]
Ok. Cheked. Thakyou.
