### ISSUE TITLE
Es dauert lange bis andere Quests angezeigt werden

### ISSUE THREAD

**Issue by Natenom** [westnordost/StreetComplete#390]
In einer der vorherigen Versionen war es noch so, dass man eine Aufgabe gelöst hat und sofort eine andere anklicken konnte.

Im aktuellen git master (und schon etwas länger) ist es jedoch so, dass nach dem Lösen einer Aufgabe alle anderen Aufgaben ausgeblendet werden und es dauert bei mir bis zu 4 Sekunden, bis sie wieder sichtbar sind. Das macht das Lösen von weiteren Aufgaben zu einer Geduldsprobe.

**Comment by westnordost** [comment]
Technically it worked like that from the beginning. But that usually happens so fast that you see at most a flash.
Could you bisect to see which commit made it so slow?

**Comment by Natenom** [comment]
Das hört sich nach sehr, sehr viel Arbeit an, vor allem, weil ich keine wirkliche Umgebung dafür habe.

Solange es mich nicht sonderlich stört, werde ich es vermutlich nicht tun.


Mir ist aber aufgefallen, dass es immer dann sehr lange dauert, wenn Auto-Sync aktiviert ist und die Internetverbindung sehr schlecht ist.

Man sieht dann das (+1) in Klammern hinter der Anzahl der gelösten Aufgaben und erst wenn das verschwindet, werden die anderen Quests angezeigt.

**Comment by westnordost** [comment]
Naja, es geht. Du musst dir nur Android Studio runterladen, dieses Projekt in Git klonen und dann in Android Studio öffnen.

**Comment by Natenom** [comment]
Inzwischen habe ich das Problem nicht mehr gehabt, ich schließe das hier mal und falls es wieder passieren sollte, kann ich es wieder öffnen.
