### ISSUE TITLE
Quest to tag availability of toilets in restaurants/malls

### ISSUE THREAD

**Issue by krzyk** [westnordost/StreetComplete#391]
This is is proposition for a quest to add `toilets=yes/no` to places where we would expect to find a toilet.
I propose to add it to (similarly to `diaper` tag #381):
```
nodes, ways with ((amenity ~ restaurant|cafe|fuel|fast_food or shop ~ mall|department_store) and name) and !toilet
```

**Comment by westnordost** [comment]
No, not for every restaurant, cafe, fuel, fast food. At most, only for big shops like department_stores and malls

**Comment by krzyk** [comment]
So the query would be:
```
nodes, ways with (shop ~ mall|department_store and name) and !toilet
```

**Comment by matkoniecz** [comment]
Is it a good idea to use toilets=yes tag if toilet is already tagged as a separate object (like at http://www.openstreetmap.org/?mlat=50.06677&mlon=19.94591#map=19/50.06677/19.94591) ?

**Comment by westnordost** [comment]
Why would that be a good idea?

**Comment by rugk** [comment]
> No, not for every restaurant, cafe, fuel, fast food. 

At lest for the first thing it would be a good idea, at least in Germany. Here they are required to offer toilets…

**Comment by westnordost** [comment]
So if they are required to have toilets it also doesn't make sense to tag them explicity because they will always have them.

On 10 July 2017 13:09:44 CEST, rugk <notifications@github.com> wrote:
>> No, not for every restaurant, cafe, fuel, fast food. 
>
>At lest for the first thing it would be a good idea, at least in
>Germany. Here they are required to offer toilets…
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/westnordost/StreetComplete/issues/391#issuecomment-314075623

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by Etua** [comment]
@westnordost Didn't you say that a good quest should not require entering an amenity? The sticker or other sign about the toilet (for example on the door) is not always visible from outside so it could lead to false positives.

**Comment by westnordost** [comment]
True, it would be weird to walk into every restaurant and look for/ask for a toilet. Another argument to not include these.

However, a mall or department store is a sufficiently public place (a mall is basically a shopping street in-a-building with facilities) that it wouldn't be weird to ask.

**Comment by ENT8R** [comment]
> `nodes, ways with (shop ~ mall|department_store and name) and !toilet`

@krzyk 
Why did you include `name` in the query?

**Comment by krzyk** [comment]
It was left over from the time when it had restaurants and other small amenities that for now need a name to distinguish one from the other. I don't think it is needed for large malls/department stores.

**Comment by rugk** [comment]
BTW, this was fixed by https://github.com/westnordost/StreetComplete/pull/504.

**Comment by matkoniecz** [comment]
> No, not for every restaurant, cafe, fuel, fast food.

Are you sure that not asking for amenity=fuel is necessary? In my experience, at least in Poland some fuel stations have toilets and some not - making them ideal targets for this type of quest.

**Comment by westnordost** [comment]
Not sure. Thinking about it now, I'd say that it may often not be apparent from the outside whether a fuel station has toilets or not because they are sometimes/often for customers only and not marked - i.e. you have to ask at the counter and you will get the key.

**Comment by ViolaineDo** [comment]
Hi, 
Why not asking it by default for restaurant or cinema also? I understand that fast food do not always have toilets, but would think restaurant have. Knowing POI with toilets is quite important for tagging accessibility for wheelchair afterwards..

**Comment by westnordost** [comment]
Restaurants usually *always* have toilets but they are not public but for customers only.  There's very very little information value in adding this information.

Am 2. Mai 2019 02:50:18 MESZ schrieb ViolaineDo <notifications@github.com>:
>Hi, 
>Why not asking it by default for restaurant or cinema also? I
>understand that fast food do not always have toilets, but would think
>restaurant have. Knowing POI with toilets is quite important for
>tagging accessibility for wheelchair afterwards..

**Comment by krzyk** [comment]
The issues is with "usually", I don't want to go to a restaurant that doesn't have a restroom.
There are some parts of the world that don't require restaurants to have those

It would be good to at least map those that don't have restrooms.

**Comment by westnordost** [comment]
Yes, that is a valid point. So, asking whether toilets=customer exists for restaurants in countries where it is not required by law and/or standard.

This requires an inclusive list of this countries though.

Also, as per the quest guidelines, this quest would need to be disabled by default because the surveyor is required to enter the place.

Am 2. Mai 2019 09:20:49 MESZ schrieb "Krzysztof Krasoń" <notifications@github.com>:
>The issues is with "usually", I don't want to go to a restaurant that
>doesn't have a restroom.
>There are some parts of the world that don't require restaurants to
>have those
>
>It would be good to at least map those that don't have restrooms.

**Comment by timothywashere** [comment]
Often petrol stations and supermarkets have signs on the outside of the facilities inside.

https://www.google.com/maps/@50.38665,-4.1602122,3a,73.6y,143.4h,96.63t/data=!3m6!1e1!3m4!1sIkxI2BsKzhiXfvqVopC2Kg!2e0!7i16384!8i8192

**Comment by andrewharvey** [comment]
I support extending this to cover amenity=restaurant|cafe|fuel all of those may or may not have a toilet and it's very useful for people to know this. Perhaps you could use a list of countries to exclude, rather than a list of countries to include.
