### ISSUE TITLE
UI improvement: surface type

### ISSUE THREAD

**Issue by gumida** [westnordost/StreetComplete#393]
After tagging several missing surfaces I've noticed two things that might improve the usability a little bit:

1. When clicking on the surface icon a popup message appears and asks for a type to submit. But this message is only visible halfway so the next step is always to pull up the message box.
![screen01](https://user-images.githubusercontent.com/5578303/27996937-91647806-64ed-11e7-88a2-537fc3f2c4f8.png)
Wouldn't it be easier, if the message would pop up completely? It least after clicking on "Paved" the complete collection should present itself without any further user interaction needed, I guess?
![screen02](https://user-images.githubusercontent.com/5578303/27996944-94231606-64ed-11e7-9ae9-76fb8a257cc9.png)

2. That's say I'm in a neighborhood where a lot of surface tags are missing. Usually all this streets are of the same type (Asphalt for example) but I have to redo all this steps for each road/segment: clicking on the icon, selecting Paved, pull up, selecting Asphalt...)
Maybe a small "same as last time" button would be helpful? So after clicking on the surface icon I could still select between the surface types but on top of the list would be a shortcut with my last selection?

**Comment by westnordost** [comment]
> 1.

Won't do. However, what I could do is that the behavior as described happens when you double-tap on a quest. Does that sound good?

> 2.

Has been proposed already. I prefer making the image selector easier to use (with less scrolling), but I haven't had the time to implement it yet.

**Comment by rugk** [comment]
As for 2. see https://github.com/westnordost/StreetComplete/issues/131.
