### ISSUE TITLE
Quest: Ask for "covered=?" status

### ISSUE THREAD

**Issue by rugk** [westnordost/StreetComplete#394]
"[Covered](https://wiki.openstreetmap.org/wiki/Key:covered)" is a nice and easy to answer key, which is useful for many (or at least some?) objects.

For example:
* bicycle_parking
* …

I am looking for other examples. Please comment and I am adding them to the list above.
(For tunnels etc. is is obviously not suitable in our case, as we cannot ask this question for all streets…)

**Comment by westnordost** [comment]
There is already a bicycle cover quest.

**Comment by westnordost** [comment]
And the same for bus stops.

**Comment by rugk** [comment]
Uh, really, never noticed it for bicycles. For bus stops, yeah…

So, okay, I do not have any other ideas.
