### ISSUE TITLE
Quest: type of crossing

### ISSUE THREAD

**Issue by krzyk** [westnordost/StreetComplete#397]
The basic idea is to look for `nodes with highway=crossing and !crossing` and ask the user to select what kind of crossing it is (https://wiki.openstreetmap.org/wiki/Key:crossing):
* `crossing=traffic_signals`
* `crossing=uncontrolled`
* `crossing=island`
* `crossing=unmarked`

Optionally we could also try to handle lack of possibility to cross the street, this would require removal of `highway=crossing` and adding `crossing=no`.

**Comment by Etua** [comment]
Does the OSM specification allow multiple crossing types? If so, then in order to avoid false positives, this quest should.

**Comment by rugk** [comment]
I think this is fixed by https://github.com/westnordost/StreetComplete/issues/397. I opened a new issue for the missing traffic island: https://github.com/westnordost/StreetComplete/issues/495
