### ISSUE TITLE
close dialog

### ISSUE THREAD

**Issue by robybully** [westnordost/StreetComplete#4]
Please add a close dialog if the app is closed.
Otherwise hitting the return button too often closes the app undesired.
Also if there are contributions left they should be commited.

If the app is only put into the background the dialog shouldn't appear.

**Comment by westnordost** [comment]
Sounds reasonable. Will implement this in a way consistent to how other apps with maps do this.

However, you should know:

>Also if there are contributions left they should be commited.
The moment you answer a question, it is safely stored in a local database. The app can be closed (or crash) any time, your contributions are save. Actually, the app immediately tries to upload the answer and will continue to do so in the background if you close the app while it is in progress. If the upload fails, the app will try again later.

**Comment by gdt** [comment]
For what it's worth, I dislike the 'are you sure' dialog.  It makes the app seem like it thinks it is more important than anything else, and hitting the back button on the main screen is supposed to return you to the home screen.

Instead, I suggest asking "what bad things happen if someone hits back, and then hits the app icon on the home screen"?  If anything really changes, arguably that's a bug and should be fixed, and then we won't care if the back button works like it is supposed to.

**Comment by westnordost** [comment]
You have a point. Actually, the only thing that will happen is that the map view must be rebuild and the quests newly displayed, which brings the smartphone's processor to it's knees for half a minute or so.
This is something I will fix. 

So perhaps I should instead make sure the users trust app to properly persist everything the user does so he does not need to worry about "saving his work". I think I will achieve this mostly by making the app more stable and adding more feedback in the form of animations etc.

**Comment by westnordost** [comment]
So what I will do:
* solve the performance issue (there is another bug for that)
* add more visual feedback for the user to see better what's going on (I don't need a ticket for that, that is on my todo list anyway)

The initial feature request here will be a will-not-fix after consideration about what gdt said about this topic.
