### ISSUE TITLE
surface "paved" inacurate

### ISSUE THREAD

**Issue by amilopowers** [westnordost/StreetComplete#400]
Hello

According to the wiki surface=paved is implied on roads for motor vehicles and isn't very accurate.

http://wiki.openstreetmap.org/wiki/Key:surface

Could your app ask for roads with a surface=paved tag what it exactly is? I think this shouldn't be a hard task for you to implement and would improve OSM-data a lot.

**Comment by althio** [comment]
Hi @amilopowers this good idea was already proposed https://github.com/westnordost/StreetComplete/issues/279 and there is progress https://github.com/westnordost/StreetComplete/pull/327
