### ISSUE TITLE
No visual confirmation of data upload

### ISSUE THREAD

**Issue by Edoardo-M** [westnordost/StreetComplete#401]
When answering questions the star counter is updated but there is no visual confirmation that data has been actually transmitted to OSM. 

I verified my are looking at object history but would be nice to get a notification every time data is uploaded, sucessfully or not.

**Comment by HolgerJeromin** [comment]
There is a "(+1)" (or a higher number) behind the star count. You have not seen it before because you had always a working and fast connection.

**Comment by Edoardo-M** [comment]
Still is not a clear confirmation, looks like as a count of provided
answares. Just add a (0 to upload) on the side or something like that

Il 17 lug 2017 11:44 PM, "Holger Jeromin" <notifications@github.com> ha
scritto:

**Comment by matkoniecz** [comment]
duplicate of #75
