### ISSUE TITLE
Toilet fees quest on private property

### ISSUE THREAD

**Issue by Natenom** [westnordost/StreetComplete#408]
There are some of this quests here but all the toilets are on private property, for example a camping site. They are accessible for free for campers, but not for public. How should I answer the quest in such a quest?

**Comment by westnordost** [comment]
@Binnette

**Comment by westnordost** [comment]
My opinion: Leave a note, saying that the toilets are for campsite users only (= someone needs to retag it to access=customers)

**Comment by HolgerJeromin** [comment]
perhaps it would be the best to add =customers with this app

**Comment by westnordost** [comment]
Actually the app does display toilets which have access=customers. I think this shouldn't be.
