### ISSUE TITLE
MaxSpeed quest: Add "Is a living street" answer

### ISSUE THREAD

**Issue by westnordost** [westnordost/StreetComplete#409]
Because from initial satellite imagery mapping, streets that may be in reality living streets will usually be tagged as residential.

UI flow:

1. Limit to countries where such a thing exists -> **Research needed**
2. user clicks on other answers -> "It is a living street"
3. a confirmation dialog pops up that displays how the sign looks and asks if there is really such a sign. (People may have a different idea what this is when they simply read the text) -> **Collecting all the images / creating the SVGs for all countries needed**

**Comment by rindlerblabla** [comment]
Do exist is Sweden. Don't know if you want the image by know, anyway https://commons.m.wikimedia.org/wiki/File:Sweden_road_sign_E9.svg#mw-jump-to-license.

**Comment by callis** [comment]
For european countries a comparison can be found here.
https://en.wikipedia.org/wiki/Comparison_of_European_road_signs

The article links to other countries as well.

**Comment by westnordost** [comment]
Nice, thanks for the answers so far. So the signs look similar, but in each country a little different. 
To save work, I think I will create an own simplified graphic that resembles a bit of every of these signs and ask in the app if it looks "similar to this". I did the same for 30-zones. Only for countries in which it looks very different, I create another graphic (perhaps Romania, Russia, Ukraine?).

**What I could use would be a list of all countries where the concept of living streets exists _in the same format as_: https://github.com/westnordost/StreetComplete/blob/master/res/country_metadata/isSlowZoneKnown.yml**

**Comment by callis** [comment]
I can put something together later today / this week

**Comment by westnordost** [comment]
I implemented the rest

**Comment by westnordost** [comment]
(Not tested)

**Comment by HolgerJeromin** [comment]
They look the same because of 

https://de.m.wikipedia.org/wiki/Wiener_%C3%9Cbereinkommen_%C3%BCber_Stra%C3%9Fenverkehrszeichen

Perhaps take a look at 
https://github.com/mapillary/traffico

**Comment by westnordost** [comment]
I implemented it already:
https://github.com/westnordost/StreetComplete/blob/master/res/living_street.svg

Only the list of country codes where living streets are known is missing and I hope @callis delivers :-)

**Comment by HolgerJeromin** [comment]
Perhaps 
https://de.wikipedia.org/wiki/Vergleich_europ%C3%A4ischer_Verkehrszeichen
Helps. 
It has a section Verkehrsberuhigter Bereich for many countries

**Comment by callis** [comment]
Great! 57 countries identified. I will send the detailed list later.

**Comment by westnordost** [comment]
Thanks callis, all done now!
