### ISSUE TITLE
maxspeed:forward/backward

### ISSUE THREAD

**Issue by OSMmapper** [westnordost/StreetComplete#410]
Hallo,

erst mal ein dickes Lob für die neue Version und die neuen Aufgaben.
Doch leider ist mir gleich aufgefallen, das die App eine fehlende Höchstgeschwindigkeit anzeigt obwohl in diesem Straßenbereich für forward und backward bereits eine Höchstgeschwindigkeit eingetragen ist.

Daher mein Gedanke, ob dies nicht mit ausgewertet wird.

**Comment by westnordost** [comment]
Du hast recht, es wird nicht ausgewertet! Danke für den Hinweis, wird schnellstmöglichst korrigiert!
