### ISSUE TITLE
"Discard input?" dialog shown even when nothing was input

### ISSUE THREAD

**Issue by tapetis** [westnordost/StreetComplete#4118]
The latest app version shows the "Discard input?" dialog even when nothing was selected in the `StreetSideSelectForm`. In previous app versions, this was not the case.

https://user-images.githubusercontent.com/6892794/173798033-acd67cab-48f9-47a7-b25c-8d250c74625f.mp4

**Versions affected**
[v45.0-alpha1](https://github.com/streetcomplete/StreetComplete/releases/tag/v45.0-alpha1)

**Comment by HolgerJeromin** [comment]
Same with adding "Bürgersteige"
