### ISSUE TITLE
Quests werden nicht zuverlässig geladen...

### ISSUE THREAD

**Issue by Natenom** [westnordost/StreetComplete#414]
Mal wieder in DE, damit ich nicht stundenlang überlegen muss, wie man es schreibt.

Gestern habe ich bei SC alle Daten über die Android-Funktion "CLEAR DATA" gelöscht und es neu eingerichtet. Es wird eine selbst gebaute Version vom aktuellen Git master verwendet.

Dann habe ich die "Arbeit" in einem Ortsteil begonnen, in dem noch viele Quests verfügbar waren. Diese habe ich abgearbeitet, zu meinem Erstaunen gab es zwar einige Quests wegen überdachten Bushaltestellen, aber keine wegen speziellen Pflasterungen für Sehbehinderte. Das wunderte mich etwas und so habe ich an dieser Stelle noch explizit die Funktion "Search for quests here" mehrfach aufgerufen, aber es erschienen immer noch keine entsprechenden Quests.

Erst viel später, nachdem ich alles abgefahren hatte und woanders war, sah ich, dass es jetzt doch die Quests nach den Pflasterungen für Sehbehinderte gab. Da ich mir sowas mittlerweile merke, konnte ich diese im Nachhinein trotzdem noch lösen, aber trotzdem kann das sehr frustrierend sein.

Ich weiss nicht, in welcher Reihenfolge oder sonstwie die App die Quests "holt", aber es wäre sehr wünschenswert, wenn für den aktuellen Bereich alle Questtypen direkt verfügbar wären und nicht erst irgendwann.

Ich hatte übrigens während der gesamten Zeit eine sehr gute Internetanbindung.

**Comment by westnordost** [comment]
In Version 1 habe ich das Verhalten des "Hier nach Aufgaben suchen"-Buttons verändert so dass nurnoch 5 Quest auf mal heruntergeladen werden. Wenn du wirklich *alle* quests haben möchtest, musst du mehrere male hintereinander jeweils nachdem er fertig heruntergeladen hat den Knopf drücken.
Grund hierfür war dass dieser Button ursprünglich ausschließlich für den Use Case des "auf Offline-Survey vorbereiten" vorgesehen war, aber mittlerweile auch einfach so benutzt wird von Leuten die Auto-Sync aus haben um mehr Kontrolle zu haben. Wenn irgendwann das _echte_ "auf Offline-Survey vorbereiten (inkl. offline Maps)" Feature kommt, wird das dann vermutlich wieder **alles** runterladen.

Anyway, Ich bin mir nicht sicher ob das das Problem hier ist, kannst ja mal was dazu sagen.

Generell ist es so, dass automatisch neue Quests am aktuellen Ort nur heruntergeladen werden wenn 1. Auto-Sync an ist, 2. nurnoch wenige Quests im Umfeld vorhanden sind.

**Comment by Natenom** [comment]
Ich habe mittlerweile immer Autosync an. Es sollte also eigentlich alles da gewesen sein auch ohne "Hier nach Aufgaben suchen", oder?

**Comment by westnordost** [comment]
Bei Autosync werden immer nur 3 Aufgabentypen geladen. Erst wenn nurnoch ganz wenige Quests übrig sind, werden neue nachgeladen.

**Comment by Natenom** [comment]
Okay, aber ist das nicht genau das Problem? Wenn ich an einem bestimmten Ort bin und per "Definition" nicht alles von dort bekomme und das dann erst geladen wird, wenn ich da schon durch bin. (?)

**Comment by westnordost** [comment]
Ich wollte es nur sagen. Also, die Situation ist dass du alles dort gelöst hast und es ist einfach nichts mehr da ist und es kommt nix neues?

**Comment by Natenom** [comment]
Genau, und irgendwann später kam dann die Aufgabe wegen der Pavements für Sehbehinderte an Bushaltestellen.

**Comment by Natenom** [comment]
Falls es hilfreich sein könnte, kann ich das ganze auch nochmal in einem "neuen" Ort in meiner Umgebung machen und genau dokumentieren :)

Muss dann aber etwas weiter fahren...

**Comment by westnordost** [comment]
Wie lange hat das gedauert dass neue kamen? War das noch per Auto-Sync oder hast du später manuell heruntergeladen?

**Comment by Natenom** [comment]
Das kann ich nicht sagen, ich habe die ganze Zeit das SC genutzt aber mir sind sie erst aufgefallen, als ich am Ende wieder durch das Gebiet gefahren bin.

Sobald der Regen weg ist bei uns, kann ich das nochmal unterwegs testen, bei Regen kann ich das Display nicht wegen der Handschuhe bedinen.

**Comment by westnordost** [comment]
http://i2.wp.com/www.ausgefallenesachen.com/wp-content/images/2011/02/Regenschirm-Hut-1.jpg

;-) 

On July 25, 2017 8:39:33 PM GMT+02:00, Natenom <notifications@github.com> wrote:
>Das kann ich nicht sagen, ich habe die ganze Zeit das SC genutzt aber
>mir sind sie erst aufgefallen, als ich am Ende wieder durch das Gebiet
>gefahren bin.
>
>Sobald der Regen weg ist bei uns, kann ich das nochmal unterwegs
>testen, bei Regen kann ich das Display nicht wegen der Handschuhe
>bedinen.
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/westnordost/StreetComplete/issues/414#issuecomment-317830539

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by rugk** [comment]
Note: On GitHub you should preferably speak English, so that other users having the same issue can also benefit of the issue (find it, etc.).
(HInweis: Jetzt erst den ersten Satz des Issues gelesen, dennoch nicht schön. Zumindest ein kleines Abstrakt sollte man hinzufügen.)

> Bei Autosync werden immer nur 3 Aufgabentypen geladen.

So that behaviour is indeed not nice. IMHO I also keep pressing this "Get quests" button although you once said, it does not work anyway and now I hear it does not even load all quests… :cry:

**Comment by rugk** [comment]
> Da ich mir sowas mittlerweile merke, konnte ich diese im Nachhinein trotzdem noch lösen, aber trotzdem kann das sehr frustrierend sein.

Ohh, das alles zu merken… je nachdem wie viele Haltestellen. Gut. :+1: 

Eijn bisschen bzw. schöner gelöst wäre das Problem aber mit https://github.com/westnordost/StreetComplete/issues/164 und/oder https://github.com/westnordost/StreetComplete/issues/73.

**Comment by Natenom** [comment]
So today I did a survey and the following happened:
I finished "levels of building" quests for one street, may be 15 quests, (time was 17:00).

I know that after that there should be new quests for "roof type" available for those buildings. So I did a "scan for quests" manually but there were no such quests.

I finished another street parallel of the first one and then scanned again for new quests, nothing for both streets.

Did the same for a third parallel street and finished "work" at 17:09.

Still no quests available, message this time was "no further quests available". Tried also to zoom out and scan manually, but still no new quests.

Then I drove to another location, did some other quests and continued to scan manually for new quests, still nothing new.

Then at 17:26 I did a new manual scan and then all the roof quests for the solved three streets appeared. In this case it was easy, because all the building had the same roof type and I was able to solve them remotely, but normally I wouldn't want to drive again and again the same streets.

**Comment by rugk** [comment]
Maybe that is because the commit on the OSM server is kept open… and only automatically closes after some time? This likely takes longer than 9 minutes.

**Comment by krzyk** [comment]
Overpass has a lag of at least few minutes behind the main OSM database, and sometimes during some outages even few hours (https://wiki.openstreetmap.org/wiki/Overpass_API/status). I don't what's the average one.

But it would be nice to have a way to create a quest from a combination of overpass and locally resolved quests, e.g. in this case show the roof quest right after the user has add the levels to a building.

**Comment by westnordost** [comment]
The data for quest creation is pulled from another server (Overpass) than where the answers are uploaded to (Openstreetmap). Thus, Overpass does not always have the newest data. 

Additionally, if StreetComplete once scans for a certain quest type (in this case: Roof shapes), then it will memorize that it scanned for this quest type there already and will not attempt to do it again for one week. So, if the app did that - and the user has no control over that - then the roof shape quests won't turn up for another week. Except if the mentioned cache is cleared. This option does not exist yet. There is a ticket for that though and it is rather trivial to implement.

Overall, what you described is intended behavior and not a bug.

**Comment by westnordost** [comment]
Also, for all mentioned things here, there are other issues:

https://github.com/westnordost/StreetComplete/issues/300
https://github.com/westnordost/StreetComplete/issues/221
https://github.com/westnordost/StreetComplete/issues/480
