### ISSUE TITLE
Make question white rather than black

### ISSUE THREAD

**Issue by Tonat** [westnordost/StreetComplete#415]
Currently the colour of the quests' questions (A la "What are the opening times of Mc D?") is black. 

White would offer a better readability, contrast, and would make it similar to the colours used in the action bar (blue+white). :)

**Comment by westnordost** [comment]
Why, it is white.

What's your Android version and model?

**Comment by krzyk** [comment]
@Tonat It would be easier to understand if you would show us a screenshot (and even better if you showed the target look)

**Comment by Tonat** [comment]
Sorry, I was on mobile (web) when I originally posted this and figured it might be clear enough without one :! 
I'm on StreetComplete 1.0 (FDroid), Android 7.0 Samsung Stock. 

Especially when outside, black's hard to read against blue, so I thought it'd be better to have the encircled text in white. 

![20170725_124359](https://user-images.githubusercontent.com/16524907/28568804-6ed01a88-7137-11e7-90cd-d27eef271a2e.png)

**Comment by westnordost** [comment]
Hum... Galaxy...
