### ISSUE TITLE
Performance problem with getCountryInfo()

### ISSUE THREAD

**Issue by westnordost** [westnordost/StreetComplete#416]
- Recently, reading the JSON boundaries file takes extemely long. There is a bug somewhere in the recursive section of the code
- Querying the country in which the user is also takes extremely long (5s+). If this is not related to the above point, the data needs to be indexed in a grid instead of a quad/strtree

**Comment by westnordost** [comment]
Is anyone else experiencing this problem on master by the way?
It takes more than 2 minutes to load the country boundaries (first time opening a quest that uses country-data, i.e. housenumber) and more than 5 seconds to check in which country a quest is (subsequent opening a quest that uses country-data).

**Comment by Binnette** [comment]
Hi, can you give us a way to mesure it ? On which lines/files, can we put some breakpoint ?
Or is it a simple way to do so ?
(I don't even know in which files those info are get). Thanks.

**Comment by Binnette** [comment]
Also, like @ENT8R said in issue #412, when application starts "there is just a white screen".
Also, on april/may, when i was using SC a lot, i never was shocked by a "long white screen at start".
But since i update my master recently, i can see this "long white screen at start".

May be, this is what your are talking about ?

**Comment by westnordost** [comment]
It's loaded in CountryBoundaries.load() and accessed in CountryBoundaries.getIsoCodes()

On July 25, 2017 11:14:16 AM GMT+02:00, Binnette <notifications@github.com> wrote:
>Also, like @ENT8R said in issue #412, when application starts "there is
>just a white screen".
>Also, on april/may, when i was using SC a lot, i never was shocked by a
>"long white screen at start".
>But since i update my master recently, i can see this "long white
>screen at start".
>
>May be, this is what your are talking about ?
>
>-- 
>You are receiving this because you were assigned.
>Reply to this email directly or view it on GitHub:
>https://github.com/westnordost/StreetComplete/issues/416#issuecomment-317678640

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by Binnette** [comment]
Ok, i have done several mesures. On start, getIsoCodes is not called.
Method load is called and following instruction :
`new GeoJsonReader().read(readToString(is))`
take an average time of 8 seconds on my device.

**Comment by westnordost** [comment]
Okay, this is still 10 times faster than on my device, but still far too long.

**Comment by Binnette** [comment]
Ah ! I just think that yesterday when i was doing my tests, I was in a building. In fact my GPS was not able to determine my position. Can it have an impact on the timing ?
I will try again near a window or outside to get my GPS to work during the tests.

**Comment by westnordost** [comment]
No. The performance issue is solely in **GeoJsonReader**. It reads the [countryBoundaries GeoJSON](https://github.com/westnordost/StreetComplete/blob/master/app/src/main/assets/countryBoundaries.json) file into [JTS geometry](https://en.wikipedia.org/wiki/JTS_Topology_Suite) data classes.

What takes 99% of the time here is the unfortunate fact that the GeoJSON cannot be 1:1 read into a JTS geometry but must be converted because of a JTS MultiPolygon imposes a restriction on the contained Polygons that a GeoJson MultiPolygon does not impose. From the JTS documentation: 

> ["As per the OGC SFS specification, the Polygons in a MultiPolygon may not overlap, and may only touch at single points."](https://github.com/westnordost/StreetComplete/blob/master/app/src/main/java/de/westnordost/streetcomplete/data/meta/GeoJsonReader.java#L148-L152)

Thus, geometries that touch each other in the GeoJSON file must be merged into one. This process is computationally very expensive.
I only wonder why this becomes apparent so extremely now because I implemented this feature more than a month ago.

I am currently looking into how to optimize the process somehow but I cannot completely remove that functionality because I don't see a possibility to tell JTS to be forgiving, i.e. "this MultiPolygon may contain polygons that touch each other, but that's okay, don't throw an exception if there are any".

**Comment by westnordost** [comment]
@Binnette Could you again measure how long it takes to load the country boundaries with current master? On my device it now takes 7s (before: 39s).

**Comment by westnordost** [comment]
(Made the loading asynchronous now because 7s is still too much to wait until the app pops up.)

**Comment by Binnette** [comment]
So I test on b185135, this is a way more better :+1:
It now takes an average time of 3.1 seconds
