### ISSUE TITLE
Quest for lit highways

### ISSUE THREAD

**Issue by ninjamask** [westnordost/StreetComplete#418]
From the wiki:
> `lit=24/7`: Both night and day; e.g. in tunnels.
> `lit=yes`: At night (unknown time schedule or daylight detection)
> `lit=automatic`: When someone enters the way the lights are turned on.
> `lit=no`: There are no lights installed
> `lit=operating times`: Use the schema of opening_hours to document when the light is ON, when the lighting is solely or primarily time dependent. For example lit=Mo-Fr 05:00-07:45 for a way lit for working days' morning rush hour only.

Germany has extra:
> In Deutschland werden Laternen, die nicht die ganze Nacht leuchten, mit dem Verkehrszeichen 394 (weiß, rot, weiß farbiger Laternenring]) gekennzeichnet. Dafür kann `lit=limited` genutzt werden. Laut StVO kann (muss aber nicht) in dem roten Feld in weißer Schrift angegeben sein, wann die Laterne erlischt. Das kann mit `hour_off=*` erfasst werden.

**Comment by HolgerJeromin** [comment]
Very good idea. Thanks. 
This is already discussed in  #84
