### ISSUE TITLE
Determine railway crossing barrier

### ISSUE THREAD

**Issue by westnordost** [westnordost/StreetComplete#422]
Add quest to add the `crossing:barrier` for a railway crossing and perhaps `crossing:bell` and `crossing:light` as these are the most used / useful values.

Perhaps these values could be swiftly combined in one quest with some sort of enjoyable diorama / illustration.

**Comment by Etua** [comment]
Today I've started working on it and about half of the work with code is done; I need to finish it and find some clear photos with barriers/lights/bells. As it will be my first PR with quest you'll have to check it carefully.

**Comment by Etua** [comment]
Should we ask only for yes/no condition for crossing:barrier or more precise value? I want to add all three values (barrier, light, bell) in the same quest and I don't know if asking whether barrier is full/half/double half would not make it too big as you have to add pictures for every case.

**Comment by Etua** [comment]
Probably I'll drop for now asking for other values in `crossing:barrier` as it causes some UI problems. but at the same time could be asked many times (`yes` answer applies both to unspecified and other crossing types than full/half/double half) and probably has not wide range of use cases.

**Comment by rugk** [comment]
@westnordost spoke of a "panorama". So I thought you add a big illustration there and the user can tap on the barrier to activate it and at a bell icon and at a crossing light. 
The illustration just shows all these three as you would see it on real live. If one feature is not activated by the user it us greyed out.
So one can switch all these things on or off in one UI. You just have to make it obvious that the user can tap there.

**Comment by Etua** [comment]
@rugk I thought about making it kinda like surface quest so you would have extensible barrier answer and simple yes/no for bell and light. However i found it too confusing for users that are used to panorama quest with only one possible choose, also difficult to add three clear images in a row for full/double/double half answers. Do you have some pictures that are self-explaining even when put in such small size?

**Comment by rugk** [comment]
No, sorry. But I think something can more or less easily be made up as an svg.

**Comment by Etua** [comment]
![crossings](https://user-images.githubusercontent.com/13040148/34378254-39b28fb0-eaf5-11e7-9f20-a928c1c09f0b.jpeg)
What do you think about such UI? Other _barrier_ answers under arrows would be visible after touching _barrier_ first, like in surface quest.

**Comment by westnordost** [comment]
The idea I tossed in at the beginning was only a very rough idea. I thought perhaps some UI like the cycleway quest would be possible where before you press, you have some kind of Wysiwyg view, a vector graphics illustration of the whole railway crossing. 

https://github.com/westnordost/StreetComplete/issues/422#issuecomment-353752373 is fine and probably better anyway too as I didn't think through what kind of UI could be used to get to the mentioned "big picture".

**Comment by rugk** [comment]
I more or less thought of a generalized picture (SVG) of a railway with all features present (as you see them when you are in front of it):

As a **sketch**:
![grafik](https://user-images.githubusercontent.com/11966684/34463733-da250e82-ee65-11e7-8362-3c6bb11ffa2c.png)

Tapping on the barrier would cycle through the three variants and switch the image there. The bell and light would be simple on/off switches, which grey out when deactivated and be colored when activated.

Thinking about it, one may of course also want to not specify a value (if it is not clear whether it has this feature or not). For that, next to each feature there could be an additional checkbox, or you just have an additional state for each one, where a question mark (`?`) is shown on top of a greyed out icon.

**Comment by westnordost** [comment]
That's not really wysiwyg though, but just a bunch of buttons. It is also not self-explanatory that you have to press the btns to cycle through the options.

Am 1. Januar 2018 02:09:35 GMT+07:00 schrieb rugk <notifications@github.com>:
>I more or less thought of a generalized picture (SVG) of a railway with
>all features present (as you see them when you are in front of it):
>
>As a **sketch**:
>![grafik](https://user-images.githubusercontent.com/11966684/34463733-da250e82-ee65-11e7-8362-3c6bb11ffa2c.png)
>
>Tapping on the barrier would cycle through the three variants and
>switch the image there. The bell and light would be simple on/off
>switches, which grey out when deactivated and be colored when
>activated.
>
>Thinking about it, one may of course also want to not specify a value
>(if it is not clear whether it has this feature or not). For that, next
>to each feature there could be an additional checkbox, or you just have
>an additional state for each one, where a question mark (`?`) is shown
>on top of a greyed out icon.
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/westnordost/StreetComplete/issues/422#issuecomment-354619577

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by rugk** [comment]
Well. of course with real images or cliparts. That was just a **sketch**(!) to show the position/method to select these. Mhh, don't know whether it is intuitive, that could indeed be difficult.

**Comment by Etua** [comment]
I'm not sure if the second approach is within my skills.

**Comment by rugk** [comment]
Some kind of image map (for Java/Android, however – in contrast to the known SVG one) would be required. Don't know whether such a thing exists.

However, as far as I see, there is no consent on how consensus on how the UI should look like, anyway.

**Comment by ServusWorld** [comment]
For the barrier type, how about this icons:

`no` | `full` | `half` | `double-half`
--- | --- | --- | ---
![ek1](https://user-images.githubusercontent.com/31391499/36749304-ac80eb1e-1bfa-11e8-9f8f-0f4b969637ac.png) | ![ek2](https://user-images.githubusercontent.com/31391499/36749329-ba2eec52-1bfa-11e8-9cf8-46e96e0d0ae9.png) | ![ek3](https://user-images.githubusercontent.com/31391499/36749336-c3a3a4f8-1bfa-11e8-8fd6-8f39d4569b86.png) | ![ek4](https://user-images.githubusercontent.com/31391499/36749341-c6771750-1bfa-11e8-99d1-ba390d637297.png)

_(I don't know why they look so spongy on GitHub, actually they are sharper)_

Usually, there are no ties on the street but in an illustration rails wouldn't really look like rails without them ...

**Comment by Etua** [comment]
@ServusWorld I think the gap in _half_ icon should be broadened in order to be clearly visible on every screen size.

**Comment by rugk** [comment]
>  in countries with left-hand traffic, maybe such a metadata file already exists

[It does](https://github.com/westnordost/StreetComplete/blob/master/res/country_metadata/isLeftHandTraffic.yml).

**Comment by ServusWorld** [comment]
> I think the gap in half icon should be broadened in order to be clearly visible on every screen size.

True I will change this


> It does.

Perfect!

**Comment by westnordost** [comment]
Actually, the most important detail about these icons is the location and length of the red-white-striped line. But that line is not really prominent at all. There is really no reason why the icon would need to show the situation from the top (I can think of). Why not show the different configuration frontal, as the surveyor is also seeing these?

**Comment by westnordost** [comment]
I.e. like this (the perspective)
![perspective](https://user-images.githubusercontent.com/4661658/36754797-60ef066c-1c0a-11e8-9b90-ffb7b4cf507b.png)

**Comment by Etua** [comment]
@westnordost How would you include all possible barrier cases with such perspective?

**Comment by matkoniecz** [comment]
@Etus Is there anything in addition to cases listed in https://github.com/westnordost/StreetComplete/issues/422#issuecomment-368993631 ?

**Comment by rugk** [comment]
Well... the original issue was also about bells and lights. Maybe we could later do that in different quests, if needed.

**Comment by rugk** [comment]
> How would you include all possible barrier cases with such perspective?

Yeah, double-half and half may be hard to differentiate in such a perspective...

**Comment by ServusWorld** [comment]
But I can try to make the icons "perspective" ...

**Comment by rugk** [comment]
I'd need more or less some serious 3d design, so you can see the barrier in a "flight/bird's perspective".

**Comment by Etua** [comment]
@matkoniecz Not really, I'm not sure how clear _barrier_  UI can be achieved with such perspective as it's more difficult case than bell and light: you can't just change transparency of the icon depending on the user choice, but handle a few cases. How would this switch look like?

**Comment by rugk** [comment]
The UI here may just be 4 pictures (as [here](https://github.com/westnordost/StreetComplete/issues/422#issuecomment-368993631)), where the user chooses one. Don't make it too complicated...

The only issue I still see is how the pictures should look, exactly, but @ServusWorld seems to come up with some ones in a "perspective" way, so that sounds good.

**Comment by Etua** [comment]
@rugk You can't have only 4 pictures and answer about bell, light and barrier at the same time.

**Comment by rugk** [comment]
Yeah, and one should not try to put all that into the same quest. That's why I propose to add bell and light in separate quests. This issue here, may focus on the current approach with 4 pictures,

**Comment by Etua** [comment]
@rugk Then I don't really see clear advantages of other perspective than the one presented by @ServusWorld These icons can be made more prominent so you can see the difference between them at a glance, but they will not take as much space as car-like perspective.

BTW: which quest would you consider more valuable in order to show it first?

**Comment by westnordost** [comment]
Barrier is the most important one, the others are "meh".

**Comment by Etua** [comment]
@westnordost Barrier importance 7 and bell + lights 8?

**Comment by ServusWorld** [comment]
Something like this:
![ek_half](https://user-images.githubusercontent.com/31391499/36909483-5db9d400-1e3e-11e8-83c1-0b0419be8e24.png)

_(Others following ...)_

**Comment by rugk** [comment]
BTW, SVGs would be preferable, but it seems you just exported this from an SVG. Looks good, BTW.

**Comment by ServusWorld** [comment]
Yeah, you guessed it. I made it as SVG, but GitHub doesn't seem to support SVGs in issue comments.
I guess I should upload them somewhere else then ...?
Thanks, btw :)

**Comment by ServusWorld** [comment]
Apropos, I guess the easiest way to also cover `light` and `bell` would be to divide it into 3 quests:

Tag | Question | Type | Priority
--- | --- | --- | ---
`crossing:barrier` | "How is this railway crossing protected?" | Image quest | 7
`crossing:bell` | "Does this railway crossing have a bell?" | Yes/No quest | 8
`crossing:light` | "Does this railway crossing have lights?" | Yes/No quest | 8

**Comment by westnordost** [comment]
Cool, the barriers are much better visible this way. I have a few more suggestions based on that it is an icon that should carry but one notion: The type of barrier there.

- Necessary to show the barrier on the other side? Can it not assumed to be the same on the other side? If yes, the icon could be 3:1 and the four option could well fit into the form in a 2x2 grid.

- The railway is not important, the street neither, only the barriers are. So, the barriers could be exaggerated/iconified while the rest should move to the background visually (in colors)

On 2 March 2018 17:23:38 CET, ServusWorld <notifications@github.com> wrote:
>Something like this:
>![ek_half](https://user-images.githubusercontent.com/31391499/36909483-5db9d400-1e3e-11e8-83c1-0b0419be8e24.png)
>
>_(Others following ...)_
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/westnordost/StreetComplete/issues/422#issuecomment-369971616

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by ServusWorld** [comment]
Good point, I gonna try to highlight the barriers better.
I think showing both sides might be more logic, as it better complies with the user's real view.

**Comment by rugk** [comment]
So as for the other two quests, I've created separate issues in https://github.com/westnordost/StreetComplete/issues/935 and https://github.com/westnordost/StreetComplete/issues/936.

So here we can focus on the barrier one.

**Comment by ServusWorld** [comment]
Okay ... all types with reduced colours for rails and street:

`no` | `full` | `half` | `double-half`
--- | --- | --- | ---
![ek_none](https://user-images.githubusercontent.com/31391499/36932763-69ddaef6-1ece-11e8-9eca-6f5522788555.png) | ![ek_full](https://user-images.githubusercontent.com/31391499/36932761-6970a7d4-1ece-11e8-95b4-130b033d386c.png) | ![ek_half](https://user-images.githubusercontent.com/31391499/36932762-69a25158-1ece-11e8-9a55-2ea6a49d4f2c.png) | ![ek_double_half](https://user-images.githubusercontent.com/31391499/36932760-6936601a-1ece-11e8-8f3b-bd5300d0a6e9.png)

**Comment by matkoniecz** [comment]
Maybe also rails and sleepers can be gray (with rail in dark gray)?

**Comment by matkoniecz** [comment]
@ServusWorld Are you interested in making code itself? If not I can make PR once you make SVG file available and select license for it (probably https://creativecommons.org/publicdomain/zero/1.0/ or https://creativecommons.org/licenses/by-sa/4.0/ would be the best),

**Comment by rugk** [comment]
The contrast of the white stripes of the barrier and the bacground is indeed a bit low… well… white on white. So maybe add a shadow or change the color or so.

**Comment by ServusWorld** [comment]
Sorry for the long interruption, now I created a version where the rails and the sleepers are in gray shades (the white stripes of the foreground barrier are better visible now).

`no` | `full` | `half` | `double-half`
--- | --- | --- | ---
![ek_none](https://user-images.githubusercontent.com/31391499/44918213-b5868300-ad3a-11e8-81c6-328e0c2c75b8.png) | ![ek_full](https://user-images.githubusercontent.com/31391499/44918263-c0411800-ad3a-11e8-8082-3fa2b637ae0d.png) | ![ek_half](https://user-images.githubusercontent.com/31391499/44918264-c0d9ae80-ad3a-11e8-8b15-82903e8a8d6c.png) | ![ek_double_half](https://user-images.githubusercontent.com/31391499/44918273-c3d49f00-ad3a-11e8-906c-b07cae38e1da.png)

If the graphics are okay now, where should I drop them and how do I declare them to be CC0?

**Comment by rugk** [comment]
> how do I declare them to be CC0?

https://creativecommons.org/choose/zero/

(In the end you get a small text to include with your assets.)
Also, FYI, you can embed metadata in SVGs stating they are CC0. In Inkscape you can e.g. do that in the document properties.

> where should I drop them?

I guess it does not matter, where. However, two ideas by me:
* As they look nice for a general use case, let's provide them in a general database. I'd suggest https://openclipart.org/. :smile: (they have CC0-licensed stuff there, so it aligns with the license you want to choose)
* Also, if you want to be nice, you may open a PR here to place them in some assets dir. But what the exact location should be, is what @westnordost has to decide.

**Comment by westnordost** [comment]
Hi @ServusWorld!
Cool, they look pretty nice now! You just have to say that you declare that, no formalities.
If you have no place to drop them, you could email them to me or create a PR here to put them into the res directory of this repo.

**Comment by westnordost** [comment]
Okay, so, I was almost done with the implementation when it struck me to ask the simple question:
For what purpose do we want to record any information about the barrier used in a railway crossing **beyond yes or no**? Is there any purpose for it at all, for whom would this information be interesting? does it change anything for the road or rail traffic, or anyone else?

(3D representation does not count, because you can warrant recording *every* information with this, even brightness of lamp posts and color of garbage cans!)

**Comment by ServusWorld** [comment]
of course that's a good question ... :thinking:
but one argument: if the user is already answering the question, it's not more effort to select the type (generally: if it's possible to be more precise I'd not just use `yes`)
and the second one: the icons have already been made :rofl:

that both doesn't really make tagging it more useful, but something where it can be used are e.g. navigation apps, which could warn the driver depending on how the railway crossing is secured

**Comment by westnordost** [comment]
By the way, I started thinking about that when I asked myself what to select in the case of a barrier like these
https://youtu.be/KUzE75mc1Fo?t=1318 (half-gate-on-wheels?) 
https://youtu.be/1S8DyhItHAA?t=490 (full-swing-gate?)
https://youtu.be/1S8DyhItHAA?t=3029 (double-swing-gate?)
https://youtu.be/1S8DyhItHAA?t=3413 (half-gate-on wheels on one side, half-swing-gate on other)
I've also seen a mixture of all of these as well as a crossing that had all three different types.

( Also, some ball magicians at play here: ;-) https://youtu.be/1S8DyhItHAA?t=4589 )

So, when thinking about it, I asked myself, why get lost into detail here again? It can get quite complicated, but what is the gain exactly.

**Comment by westnordost** [comment]
I also opened a topic in the German forum: https://forum.openstreetmap.org/viewtopic.php?id=63605

**Comment by westnordost** [comment]
Okay, so @Nakaner provided a good reason why these values make sense even outside the world of railway enthusiasts: railway crossings with `half` barriers can be assumed (e.g. by route planners) to block the road for a much shorter duration than the `full` and `double_half` barriers.

**Comment by westnordost** [comment]
The problems with the icons is that they get really small when 4 of them are in one row. But if there are two rows, the last two are not fully visible and the user must scroll. I will see to modifying the icons to be less wide

**Comment by Nakaner** [comment]
@westnordost wrote:
> By the way, I started thinking about that when I asked myself what to select in the case of a barrier like these
> https://youtu.be/KUzE75mc1Fo?t=1318 (half-gate-on-wheels?)

IMHO `half` because it closes the half of the road.

> https://youtu.be/1S8DyhItHAA?t=490 (full-swing-gate?)

IMHO `gate` if it prevents pedestrians and cattle to enter the tracks when the crossing is open to them. See [this British level crossing](https://www.youtube.com/watch?v=3VF4hWvjC3g) which has "gates".

> https://youtu.be/1S8DyhItHAA?t=3029 (double-swing-gate?)

They don't seem to prevent pedestrians and cattle to enter the tracks. IMHO `double_half`.

> https://youtu.be/1S8DyhItHAA?t=3413 (half-gate-on wheels on one side, half-swing-gate on other)

IMHO `half`

> I've also seen a mixture of all of these as well as a crossing that had all three different types. I.e. full-barrier + two half-barriers on one side, one half-gate on the other and stuff.
> 
> ( Also, some ball magicians at play here: ;-) https://youtu.be/1S8DyhItHAA?t=4589 )
> 
> So, when thinking about it, I asked myself, why get lost into detail here again? It can get quite complicated, but what is the gain exactly.

There are `yes`, `no`, `half`, `full`, `double_half` to cover most. Everything else should go into sub-tags where local mappers know best what exists and how to model in tags.

I would like to ask to move tagging discussions to a suitable mailing list.

You can add a generic `yes` option as a "other than shown".

**Comment by westnordost** [comment]
I do want to avoid a generic `yes` for _"other than shown"_ because then it cannot be distinguished from _"it just hasn't been specified more precisely yet"_.

**Comment by westnordost** [comment]
![device-2018-09-05-170920](https://user-images.githubusercontent.com/4661658/45102683-8e5ef580-b12e-11e8-846c-0a3e21b0c646.png)

**Comment by ServusWorld** [comment]
Looks good to me!
Is this a mockup or is it already "real"? :)

**Comment by westnordost** [comment]
It's real, dude
