### ISSUE TITLE
Quest cache age too long? 

### ISSUE THREAD

**Issue by HolgerJeromin** [westnordost/StreetComplete#425]
Streetcomplete asked me about building levels. The situation was too complex so I tagged the area with vespucci. 
Even after nine days the quest is still shown open in my streetcomplete. 

In the past I could tweak the life time. What is the current refresh time?

**Comment by westnordost** [comment]
After one week, they are considered as old. That does not mean that they are downloaded again right away, only next time when a download is started that includes them. Then, they those you mention would be deleted.

**Comment by westnordost** [comment]
By the way, if you try to solve one of the now old quests that are based on old data, StreetComplete will detect that there is a conflict and invalidate the whole tile (= the vicinity of that quest) as to-be-downloaded anew.

**Comment by HolgerJeromin** [comment]
I still see an osm note in streetcomplete which i closed 21 days ago with vespucci.
