### ISSUE TITLE
"Road lit" quest for streets in forests, really? :)

### ISSUE THREAD

**Issue by Natenom** [westnordost/StreetComplete#427]
Sorry for posting again regarding a feature that was just merged. But there are now many, many of those quests in the forests where I live. There are many forests here.

May I solve them all now and get several hundreds stars or should I wait for a fix?

**Comment by westnordost** [comment]
Hmm,... @krzyk what do you say? That can definitely not stay like this, but how to filter?

Perhaps only include ways with surface= something paved? Or highway=path which do have one of these designated-tags set?

@all: Is there any tag that is usually set on footways in a city but not in forests etc.?

**Comment by krzyk** [comment]
@Natenom Could you show us an example of such way?

**Comment by HolgerJeromin** [comment]
There are lit footways and vehicle roads in forests. 
It is exactly interesting finding them.
A friend of me was very sad that no one tagged lit in his forest, as he searched for lit running training areas.

**Comment by HolgerJeromin** [comment]
ok, unpaved (see list in wiki) footway/path are probably unlit.

**Comment by Natenom** [comment]
I drive a lot through forests and I can't remember any lit street within a radius of ~20km at least in my area.

Here is a screenshot. All of this green area is a forst.

https://files.natenom.com/nidx/nobackup/sharing/2cd47d53fe794cfe24071a279a58cedec849e5a64d9da1776f7bc165a0d4bf68.png

**Comment by westnordost** [comment]
The best solution would be of course to detect if the quest is in town or not. In town (i.e. parks) may be lit, out of town, pretty much never. But for this app, this is pretty much not detectable, it must be detected by tell-tale tags on the way.

@HolgerJeromin Of course if then one of hundreds of ways is lit, the information value of tagging that one way with lit=yes is big, as it is unexpected, but this is not how quests in StreetComplete should work. If a quest is to be answered 99% of the time with the same answer, it is not good design.

Lit ways in parks (in cities) are often unpaved, so I'd use the "unpaved" tell-tale tag only if no other could be found. 
Digging through the https://wiki.openstreetmap.org/wiki/Path_examples page, I'd suggest the following:

`highway ~ cycleway|footway or highway = path and (foot = designated or bicycle = designated)`

**Comment by krzyk** [comment]
@westnordost but from what @Natenom wrote, the problem is for streets (highway=primary|secondary|tertiary|residential|service) not for footways/cycleways/paths.

**Comment by Natenom** [comment]
BTW, this is the area: http://www.openstreetmap.org/#map=16/48.8715/8.6986

**Comment by krzyk** [comment]
Oh, so it is mostly for paths in forests.

**Comment by westnordost** [comment]
@krzyk I understood it is for paths mainly. For streets, I don't know. Haven't been out of town at night recently but it seems reasonable that these are usually not lit.
I suggest to add for streets:
`highway ~ all_those_streets and sidewalk and sidewalk != no`

**Comment by krzyk** [comment]
for streets it might be too much, sidewalks are frequently mapped as a separate ways. So maybe in the beginning let's limit it for path, as the area from the @Natenom has mostly those (I see only one quest for street, all others are for paths)

**Comment by krzyk** [comment]
Created #428 PR with the change for paths, maybe it will be enough?

**Comment by westnordost** [comment]
I think not. We need to think about countries out of Europe as well. If there is a sidewalk, it is a tell-tale tag to detect that a street reached a certain development state. I am adding a sidewalk-check as well

**Comment by westnordost** [comment]
Also see this http://product.itoworld.com/map/69?lon=4.32927&lat=51.45528&zoom=7&fullscreen=true

**Comment by westnordost** [comment]
That roads where the sidewalk is mapped separately are now excluded as well is unfortunate, but reducing the number of false positives is more important than being "complete" - StreetComplete is not a QA tool that should show all places where it _may_ make sense to add the info.

**Comment by westnordost** [comment]
Actually, there is an undocumented but frequently used (16k usages) tag `sidwalk=separate`, the app could at least respect this tag. Thats 16k more quests which are not false-positives 👍

**Comment by krzyk** [comment]
@westnordost maybe we could use `around` to check for near footway/cycleway? Something like this in overpass:
```
way["highway"~"footway|cycleway"]({{bbox}});
way(around:10)["highway"~"primary|secondary|tertiary|unclassified|residential|living_street|service|pedestrian"]({{bbox}});
(._;>;);
out;
```
