### ISSUE TITLE
Request: iOS Version

### ISSUE THREAD

**Issue by heubergen** [westnordost/StreetComplete#43]
The app looks promising and it would be great to have it on iOS too.
May not today or in the next months but you could leave the issue open and see how other use responds to it.

**Comment by westnordost** [comment]
Sorry, this is not going to happen. iOS is a completely different platform, One would have to write this application completely anew for iOS. That would be another project.

**Comment by habi** [comment]
I know this issue is closed, but nonetheless; Do you know of a similar app for iOS?

**Comment by althio** [comment]
[Kort relaunch](http://www.kort.ch/) is in progress, not yet ready.

Other apps are not gamified: 
- http://wiki.openstreetmap.org/wiki/Go_Map!!
- http://osmand.net/
- http://maps.me/en/home
- ... http://wiki.openstreetmap.org/wiki/Apple_iOS#OpenStreetMap_applications

**Comment by habi** [comment]
Thanks for the hints!
I was not aware of Kort, will see how this turns out, the other apps are ‘on my radar’ :)

**Comment by wadouk** [comment]
Or a pwa/web only version ?

**Comment by rugk** [comment]
A web version has already been suggested in https://github.com/westnordost/StreetComplete/issues/325, but it is still a totally separate project.

**Comment by rugk** [comment]
BTW there is an iOS version/"clone" in development in https://github.com/wtimme/OSM-Completionist by @wtimme

**Comment by westnordost** [comment]
#1892

**Comment by knowname** [comment]
See https://github.com/streetcomplete/StreetComplete/issues/5421 :)
