### ISSUE TITLE
Feature Request: Keep answered quests in order to correct them

### ISSUE THREAD

**Issue by sedrubal** [westnordost/StreetComplete#435]
It was helpful if answered quests are still visible until you upload the answers. Then you could edit and correct your answers if you realize that you misunderstood the question / you mixed up buildings etc. Maybe you can make the quests green like this or grey them out or add a green tick ✅. And maybe there should be a setting to disable this feature...

![quests_solved](https://user-images.githubusercontent.com/5571650/28777416-456ab59a-75fb-11e7-9ed6-655d7d8f1690.png)

**Comment by Binnette** [comment]
For the moment, it can't be done, because "answered quests" will hide others quests.
Example : a single road can have 3 question : 1 for surface, 1 for name and 1 for lit.

**Comment by sedrubal** [comment]
Ah ok. Maybe it is possible to show a list of answered quests when you tab on the star in the menu bar? Then one could edit the quests that are not yet uploaded. (And the uploaded quests may be marked as successfully uploaded which might help a bit for #75)...

**Comment by Binnette** [comment]
In fact, may be you just want to "undo your mistakes" ??? #116 
That way, you can correct your last answer. So there is no more need to "keep answered quests".
Can #116, solve your real need ?

**Comment by sedrubal** [comment]
Ah yes, indeed. But I'd prefer a list of answered quests 😇

**Comment by Binnette** [comment]
If feature #142 is implemented, we can think about adding a "tab" that display "answered quests".

**Comment by rugk** [comment]
…so rather reopen this as a TODO item after https://github.com/westnordost/StreetComplete/issues/142.

**Comment by westnordost** [comment]
> If feature #142 is implemented, we can think about adding a "tab" that display "answered quests".

I thought about this quite a long time and I came to the conclusion that I won't show the changes in a list (because the most important information is missing from this list: the position). Perhaps later I will show the recent changes in another map (in a different screen) but not soon because of what Binette said initially. For now, I will just implement an undo-feature.
