### ISSUE TITLE
After solving a quest, other quest aren't displayed until i touch my device screen

### ISSUE THREAD

**Issue by Binnette** [westnordost/StreetComplete#437]
This bug is pretty annonying. I think it is caused by the fact that there are thousands of quests in my area. So maybe, SC is too slow.

How to reproduce :
1. Solve a quest
2. do not touch anything !
3. others quests available in current map view are not displayed
4. wait as long as you want
5. touch the screen (do not need to move the map, etc.)
6. others quest are finally displayed

Android 6.0
Devide: Homtom HT17 Pro

Can anyone reproduce it ?

**Comment by westnordost** [comment]
Hmm I don't have this. But I think @HolgerJeromin has the same problem.

**Comment by HolgerJeromin** [comment]
> But I think @HolgerJeromin has the same problem.

No. At least i never observed it. :-)

**Comment by Binnette** [comment]
@westnordost : Ok, may be I will try to debug it. I will dig in files to find the code "clear all quest then display all quests".

**Comment by westnordost** [comment]
`QuestsMapFragment.removeQuests(...)`

**Comment by westnordost** [comment]
Can't reproduce and would be an issue of tangram-es anyway.
