### ISSUE TITLE
Cafe, restaurant, nightclub quests for toilets and payment options

### ISSUE THREAD

**Issue by andrasfuchs** [westnordost/StreetComplete#438]
If the amenity is cafe, restaurant, nightclub, ask for the following:
* Does the place have a toilet? (toilets:yes/no)
* Do they accept credit cards? (payment:credit_cards) If yes, which ones? (payment:visa, payment:visa_debit, payment:mastercard, payment:maestro)
* Do they accept fiat currencies? (payment:cash) If yes, and other than the local currency, which ones? (payment:cash:USD or payment:cash:EUR)
* Do they accept cryptocurrencies? (payment:cryptocurrencies) Bitcoin? (payment:bitcoin) Dash? (payment:dash) Litecoin? (payment:litecoin) Ethereum? (payment:ethereum)

Please note that we are still debating the proper tags for cryptos, here are the details: https://wiki.openstreetmap.org/wiki/Talk:Key:payment#Cryptocurrencies

**Comment by Etua** [comment]
I think that for the current app form this quest is too detailed especially as it requires entering the amenity for most of the cases or even asking the staff for help which is currently discouraged. Maybe it would fit for _expert mode_.

**Comment by westnordost** [comment]
[Before you submit an issue, please review the guidelines for contributing to this repository.](https://github.com/westnordost/StreetComplete/blob/master/CONTRIBUTING.md)

In particular:
- See @Etua
- You cannot assume that it is reasonable to ask for every restaurant, cafe etc. in the world if it accepts credit cards, much less fiat currencies and even much less cryptocurrencies. If, at all, this would need to be limited to regions where it is very common to pay with credit card (such as certain areas in the US, I heard).
- One issue per quest type
