### ISSUE TITLE
Feature request: multiple housenumbers per building

### ISSUE THREAD

**Issue by frafra** [westnordost/StreetComplete#439]
There are buildings with multiple house numbers, because they have shops on the ground floor or they are on a corner or they are a big structure with multiple apartments. It would be nice to be able to select the exact entrance on the border of the building.

**Comment by westnordost** [comment]
Sorry, adding new geometry and editing geometry in general is currently out of scope of this app. You can simply add housenumbers like "3-5" or whatever, this is not wrong. This can be made more detailed by other mappers later.

**Comment by frafra** [comment]
Ok! Thank you for your quick response.

I will leave here a related link for future users: https://wiki.openstreetmap.org/wiki/Addresses#Buildings_with_multiple_house_numbers
