### ISSUE TITLE
Unable to reach the authorization server

### ISSUE THREAD

**Issue by basilgohar** [westnordost/StreetComplete#44]
I just installed StreetComplete through F-Droid and I answered a couple of questions in my area, but I am unable to upload them as when I try to authorize my account I consistently get, "Unable to reach the authorization server" after a timeout of some sort.  Searching did not reveal any additional information about this kind of error yet.

I am running Android 7 on an HTC 10 for what it's worth.  Not sure what other information might be useful.

**Comment by westnordost** [comment]
This is odd, given that you can download quests normally and the map also renders normally.

Do you have Vespucci? Does the problem occur there as well with OAuth? (if you reauthenticate there)

**Comment by westnordost** [comment]
Ah, I see in the source code that the exact error that occurs is already logged. So the only information I need from you is the error that has been logged. If you do not have Android debugging tools (adb) installed on your device, you need to use an app. I.e. aLogcat, CatLog or SysLog should do the trick. (It needs to be started while you reproduce the error).

**Comment by basilgohar** [comment]
I'll try one of those apps and see what I can get.  Thanks for the insight.

**Comment by basilgohar** [comment]
Of course, I go to do the same thing and the darn things perfectly 
fine.  I wonder if the authentication server was having problems. The 
only thing I did after encountering the issue was installing Vespucci 
but I also had a problem authing with that, too (at the time).  Not sure 
if that makes any difference.

**Comment by westnordost** [comment]
Glad to hear that it is working fine now!

Well, with mobile phones, there can always be connection problems. Perhaps at that moment, the mobile wasn't able to get a connection and that was all. Then I'll close this one, feel free to reopen/open a new issue if it happens again reproducable.

**Comment by asdmin** [comment]
Would it be possible to reopen this case? I can't auth my user. I see this in logcat:

    04-06 16:07:45.181 15462 15462 I OAuth   : Step 1: Retrieving request token...
    04-06 16:07:45.961 15462 15462 I OAuth   : Step 2: Authorize app on web page...
    04-06 16:08:07.851 15462 15462 E OAuth   : Error during authorization
    04-06 16:08:21.581 16717 16730 V OAuthClientKeys: Class org.andstatus.app.net.http.OAuthClientKeysSecret was not loaded
    04-06 16:08:21.581 16717 16730 V OAuthClientKeys: java.lang.ClassNotFoundException: org.andstatus.app.net.http.OAuthClientKeysSecret

**Comment by Quix0r** [comment]
Not working under Android 4.1 (yes, it is old).
