### ISSUE TITLE
Quest. Add tunnel for waterways

### ISSUE THREAD

**Issue by rindlerblabla** [westnordost/StreetComplete#440]
When the quest #398 is solved (how to ask the overpass query) the same question could be asked for waterways (streams etc) that are passing different highway types, adding `tunnel=culvert` and `layer=-1` at the crossing node.

When running the validator in JOSM this is probably on of the most common errors in areas I'm updating.

**Comment by westnordost** [comment]
What would be the answer options, though? "Yes, it's a culvert" and...?

**Comment by rindlerblabla** [comment]
Hm. True. And the area with the culvert tag maybe should be a bit wider than just the node where the stream and road are passing each other. Otherwise the other answer could be that it's a bridge and also add layer=1 for the road, but seems like it's not really suitable to add this tag with StreetComplete.

**Comment by althio** [comment]
You can do it properly for a ford.
For a culvert or a bridge, you can provide indications with survey knowledge, but exact tagging is difficult.

With the capabilities of the app, a set of options could be:
1. "_The stream goes into a culvert below the road_": just add a note [with some proposed default text]
or preliminary tagging _eg._ [`tunnel=culvert`](http://wiki.openstreetmap.org/wiki/Tag:tunnel%3Dculvert) + `fixme="improve waterway with tunnel as way and add tag layer = -1"`
2. "_The road is on a bridge above the stream_": just add a note [with some proposed default text]
or preliminary tagging _eg._ [`bridge=yes`](http://wiki.openstreetmap.org/wiki/Key:bridge) + `fixme="improve highway with bridge as way and add tag layer = 1"`
3. "_This is a ford: the road and the stream are on same level_": [`ford=yes`](http://wiki.openstreetmap.org/wiki/Key:ford)

As @rindlerblabla wrote, some caveats, best practices are:
- [`tunnel` applies to a way](http://wiki.openstreetmap.org/wiki/Key:tunnel#How_to_map), not a node: "How to map - split the way in question at the points were the tunnel starts and ends and add the tunnel tag."
- [`bridge` applies to a way](http://wiki.openstreetmap.org/wiki/Key:bridge#How_to_map), not a node: "How to map - Split the upper way at each end of the bridge (which is where it joins solid ground) and add bridge=yes to the central section"
- OK for [`ford` as a node](http://wiki.openstreetmap.org/wiki/Key:ford#How_to_Map): "How to Map - use a single node ford where a highway crosses a waterway that is mapped as linear stream"

**Comment by rindlerblabla** [comment]
But have a question that leads to a lot of fixme:s doesn't seem like the best solution. Will keep the issue open though.
