### ISSUE TITLE
Fix for #427 too restrictive?

### ISSUE THREAD

**Issue by Natenom** [westnordost/StreetComplete#441]
After the commit to fix #427 many of the "is street lit" quests disappeared, even for streets. For example https://www.openstreetmap.org/way/27933011 ... no lit tag yet, but there is not a quest for it in SC.

A second example: Before the commit there were dozens of such quests in a village here, now there are only few left for "thinks" like this: https://www.openstreetmap.org/way/137404913

**Comment by westnordost** [comment]
There will be those quests again after the sidewalk-quest has been implemented.
