### ISSUE TITLE
New quest: Does that car wash is automated/self-service

### ISSUE THREAD

**Issue by Etua** [westnordost/StreetComplete#445]
The quest could apply to all car wash amenities without automated or self_service tag. A set of the pictures containing all combinations could be shown to the users.

**Comment by Crochetdavid** [comment]
- map icon : https://mapicons.mapsmarker.com/markers/transportation/road-transportation/car-wash/
- reply "manual" : ??
- reply "automatic" : https://commons.wikimedia.org/wiki/File:Broadways_Car_Wash.jpg

**Comment by Crochetdavid** [comment]
- map icon : https://mapicons.mapsmarker.com/markers/transportation/road-transportation/car-wash/
- reply "automated=no" and " self_service=yes" :  ??
- reply "automated=yes" and " self_service=no" : https://commons.wikimedia.org/wiki/File:Broadways_Car_Wash.jpg

**Comment by afmenez** [comment]
Most of the car washes here in brazil are neither automated or self-service, but with people to wash your car.  I guess this would warrant "automated=no" and "self_service=no".

**Comment by Etua** [comment]
A proper pull request has been merged.
