### ISSUE TITLE
New quest: contact:phone=* for amenity=telephone

### ISSUE THREAD

**Issue by ninjamask** [westnordost/StreetComplete#448]
Add the phone number which can be used to call this phone.
Two tags are used `phone=*` and `contact:phone=*`

https://wiki.openstreetmap.org/wiki/Tag:amenity=telephone

**Comment by HolgerJeromin** [comment]
At least in Germany i rarely saw an official phone number on a public phone. 
15 years ago there was a telekom ref on my favorite phone which could be identifiered as a phone number which even worked. 
But after a few years the ref was changed and i had no way to detect a call-in number.

**Comment by ninjamask** [comment]
Oh, apparently you can't call public phones anymore in germany. (At least Telekom ones.)
Didn't know this.

**Comment by Binnette** [comment]
In france, public phone are to be removed.
