### ISSUE TITLE
Quest information panel not shown in battery saver mode

### ISSUE THREAD

**Issue by Natenom** [westnordost/StreetComplete#45]
Its a Samsung Galaxy S5.

Always reproducible.

Version 0.5

**Comment by westnordost** [comment]
What is a battery saver mode? Can you give me a few infos on that? I think it is a Samsung-only feature.

**Comment by Natenom** [comment]
From the description in the battery saver mode:
Maximum power savings. Reduces devices performance, disables background tasks and data, disables animations, and reduces display frame rate.

**Comment by westnordost** [comment]
I'll need to have a look at this. I think this might be connected to the animations.

**Comment by miniskipper** [comment]
Also experienced this. Had disabled the animations in developer options.
After enabling them again, the app works.

Moto G5 / Android 7.0.

**Comment by Philippe-Arnaud** [comment]
I'm having the same problem. Had to disable the animations because my phone tends to be really slow. The panel only shows went rotating the device.
Is there any way this issue could be fixed?

**Comment by matkoniecz** [comment]
@Philippe-Arnaud In general, after bug was closed and described as fixed it is better to open a new one and describe it as a similar to the old one (it applies to bug trackers in general).
