### ISSUE TITLE
"Shop does not exist" for opening hours

### ISSUE THREAD

**Issue by rugk** [westnordost/StreetComplete#450]
IMHO the opening hours quest should, similar to the street surface quest, have an item "This shop does not exist", which then creates a note about a non-existent shop.

**Comment by Binnette** [comment]
I am used to leave a note : "Remove this shop". Then when i'm back home, i use JOSM (or whatever) to remove the shop. Sometimes, other people see my note and "fix" the shop for me :+1:

**Comment by rugk** [comment]
Yeah, but thenyou always have to write this. This can be easier with a menu item… :smiley:

**Comment by chrisdebian** [comment]
Sometimes the business has closed, like a local (to me) pub, and it's not
clear whether it will reopen. Have a 'Business closed' option, perhaps, as
the building will probably continue to exist?

Thanks,

Chris.

**Comment by rugk** [comment]
Hmm, maybe, but would not you really just leave a note there? I think that case it not that common that it needs a menu entry…

**Comment by westnordost** [comment]
SC does not delete things, this'd open another can of worms. In the case that a quest is not answerable, always simply leave a note.

**Comment by rugk** [comment]
But street surface has a "street does not exists/no real street" too. Why do you include it as an option there, then?

**Comment by westnordost** [comment]
You mean street name quest -> "no proper street", right?

It allows the user to retag the road as a track, service way or link, not delete it. 

On August 4, 2017 9:11:20 PM GMT+02:00, rugk <notifications@github.com> wrote:
>But street surface has a "street does not exists/no real street" too.
>Why do you include it as an option there, then?
>
>-- 
>You are receiving this because you modified the open/close state.
>Reply to this email directly or view it on GitHub:
>https://github.com/westnordost/StreetComplete/issues/450#issuecomment-320330664

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by awst-baum** [comment]
It would be really nice to have the option "This shop has shut down/closed/whatever" as an option in the GUI (and not having to type that out manually in a note). But maybe I just live in an area where quite a few shops open and then go bust a few months/years later.

**Comment by ENT8R** [comment]
But a major problem of that would be the internationalization/translation of the strings... If e.g. a German user travels through a lot of countries (and of course always leaves the system language at German), which language should be used to describe the issue? The local language, the language of the user or simply English?
Can't you simply type in the text once and then copy/paste it?

**Comment by awst-baum** [comment]
Personally, I'd be fine with English as it's probably the common language of many OSM users and most likely to be the one both the traveller and the locals understand. If course, if you want to implement it "super fancy style", you could leave the message in up to three languages (if that's allowed).

I can certainly copy and paste the message from somewhere else (which language should I use? ;-)) - but that wouldn't be "simple" for me. TBH, in that case, I probably wouldn't bother doing anything about that particular quest :-/

**Comment by rugk** [comment]
Why not just local language + English. Actually using the local language for this would be a good thing only street complete knows, because this is a thing you cannot always manually do.

It even could let the user select the string based on their own language, so the app "translates" stuff for them.

In general I think the concept of "note templates" in general (which are adjustable by the user) might be a good idea.😀
I'll have to look whether we already have a big for that …

Then I could describe my ideas there in detail.

**Comment by HolgerJeromin** [comment]
I know only english and german. 
If i leave a note in france via sc in french and english a local user would reply in his local language (because i seem to speak this language). 
I will never be able to answer his questions

**Comment by rugk** [comment]
Here you go: https://github.com/westnordost/StreetComplete/issues/1191

**Comment by awst-baum** [comment]
@HolgerJeromin So is your recommendation to not leave a note at all about a closed shop (whether template or copy-pasted or manually typed) if you're travelling in an area where you don't speak the local language? But in case I do speak the local language (say the German traveller we're talking about goes to Austria), is there any way to make leaving a note about about a disused/closed shop (or even a removed postbox) easier?
