### ISSUE TITLE
What type of gate is this? (Ask for `gate:type` for all `barrier=gate`)

### ISSUE THREAD

**Issue by mcliquid** [westnordost/StreetComplete#4507]
### General
Affected tag(s) to be modified/added: [gate:type](https://wiki.openstreetmap.org/wiki/Tag:barrier%3Dgate#Additional_details)
Question asked: **What type of gate is this?**

### Checklist
Checklist for quest suggestions (see [guidelines](https://github.com/streetcomplete/StreetComplete/blob/master/QUEST_GUIDELINES.md)):
- [x] 🚧 To be added tag is established and has a useful purpose
There are three different tagging styles available but I would say "gate:type" has been established with 16k uses compared to 2k and 0,5k uses for `gate` and `gate_type`
- [x] 🤔 Any answer the user can give must have an equivalent tagging (Quest should not reappear to other users when solved by one)
When it is a `barrier=gate`, then one of the answers should match. Otherwise it's not a `barrier=gate` or leave a note.
- [ ] 🐿️ Easily answerable by any pedestrian from the outside but a survey is necessary
I want to leave this open yet, as I suspect it's like the shelter_type quest: too many possible answers and probably too difficult to distinguish them. (#4428)
- [x] 💤 Not an overwhelming percentage of quests have the same answer (No spam)
The answer will definitely come very often, as the tag is not very common yet, but there shouldn't be a barrier=gate on every corner either.
- [x] 🕓 Applies to a reasonable number of map data (Worth the effort)
There are more then 4 million barrier=gate out there, but only ~ 20k have a specific "type of gate" tag.

### Ideas for implementation

**Element selection:** 
`nodes with
         barrier=gate
         and (!gate:type or !gate_type or !gate)
)`

**Proposed UI:**
Same UI as in stile quest #3372

**Comment by legofahrrad** [comment]
I like detailed OSM data and love to collect these specific information, but what is actually the useful purpose of the `gate:type`?

**Comment by westnordost** [comment]
I don't see a useful purpose for that neither. To check if current data is correct is a weak argument.

**Comment by mnalis** [comment]
Also, linked [wiki](https://wiki.openstreetmap.org/wiki/Tag:barrier%3Dgate#Additional_details) stating:

> The keys [gate](https://wiki.openstreetmap.org/w/index.php?title=Key:gate&action=edit&redlink=1)=* or [gate:type](https://wiki.openstreetmap.org/wiki/Key:gate:type)=* are in use to specify more details for the gate type. Have a look at [Taginfo (gate:type=)](http://taginfo.osm.org/keys/gate%3Atype#values) and [Taginfo (gate=)](http://taginfo.osm.org/keys/gate#values) until some definitions get agreed on and documented here.

is not too reassuring (at the moment)...
