### ISSUE TITLE
New quest: species for attraction=animal

### ISSUE THREAD

**Issue by rugk** [westnordost/StreetComplete#451]
May be mostly asked in zoos.

> What animal is kept here?

https://wiki.openstreetmap.org/wiki/Tag:attraction%3Danimal

Low (or none) non-answerable quests and clear answers hopefully everybody understands. Maybe we need a country-specific list as in the sports quest.

One problem is, the [scientific names](https://wiki.openstreetmap.org/wiki/Key:species) should be saved. That's why we should use a "non-scientific" UI to let the user choose from the most common types and a "Another answer" -> "I know the scientific name/not listed", where the user can enter the scientific name. This may actually not be that difficult, as in zoos often there are plates where this name is given and the user can thus just transcript it.l

**Comment by westnordost** [comment]
No, because effort of implementation far outweighs the importance of the tag:
- Very insignificant: Only 7k usages worldwide
- The data is not really used (yet), no application 
- A **vast** pool of possible values, even much bigger than (popular) crops -> lots of names to research/translate and maintain
And:
- Zoos are not public, you usually need to pay for entry

**Comment by rugk** [comment]
But zoos are hopefully mapped anyway…

**Comment by rugk** [comment]
As for the usage: Yeah, this means low false-positives… :wink: And in zoos, where this tag can mostly be found, it is very useful/important. As what animals is there might be the most useful or even the only information you might want in a zoo…

As for usage: Yeah, but I'd really like a map/application that can show me a nice map of any zoo including where I can find what animal.

values: No, I don't think so. Just some common values. It's likely way less than crops. I mean we don't have to include any bird or so… And as I said, manually entering the value should be easy:
>  This may actually not be that difficult, as in zoos often there are plates where this name is given and the user can thus just transcript it.

Note this issue has even got 1 upvote in 2 or 5 hours, so I am not the only one liking it. And for a PR it is likely a nice idea.

**Comment by HolgerJeromin** [comment]
The problem is to create the osm areas. This is nothing this app does right now.

**Comment by rugk** [comment]
Create? No, it's not about creating. It has to be tagged as `attraction=animal` already, of course.

**Comment by westnordost** [comment]
Does anyone add `attraction=animal` but not what animal it is?

**Comment by rugk** [comment]
I just run an [query](https://overpass-turbo.eu/s/qQH) and saw that it is quite common that there is no "species" tag. Mostly they use the "name" to specify the animal…

**Comment by rugk** [comment]
The [species tag](https://taginfo.openstreetmap.org/keys/?key=species#combinations) is not really often used for "attraction" (only 389 elements).
