### ISSUE TITLE
New quest: min_age and max_age for common age-limited amenities

### ISSUE THREAD

**Issue by rugk** [westnordost/StreetComplete#452]
E.g.
* any [attraction](https://wiki.openstreetmap.org/wiki/Proposed_features/Key:attraction) (except of attraction=animal and =maze probably)
* possibly amenity=kindergarten/school (and leisure=playground?), however it may be difficult to judge from the outside only
* don't know if it also makes sense to ask for things, which are usually 18+ (`amenity=nightclub`, penny arcarde and so on…)

**Comment by westnordost** [comment]
This seems to be very insignificant data. Also, asking this is to assume that these attractions will always/often have some kind of sign there.

**Comment by rugk** [comment]
> This seems to be very insignificant data.

Depends on how old you are. I mean, seriously, it is important for a family trip and so on. And having the ability to look up where you can go, before entering the amusement park might be a good idea, IMHO.

**Comment by matkoniecz** [comment]
At least in Poland leisure=playground, amenity=kindergarten/school are not age limited.

(I have not enough experience to say that about attraction=* and amenity=nightclub)

**Comment by westnordost** [comment]
In Germany, they are, kind of. Sometimes, there are signs, saying that adults may only enter together with their children. But for this kind of "access restriction", min_age and max_age would be wrong anyway. It also does not make too much sense to map this.
Regarding attraction, I think this would apply to too few elements to be worth implementing.
