### ISSUE TITLE
New quest: Tag education level/school type assigned to kindergarten/school/college/university

### ISSUE THREAD

**Issue by rugk** [westnordost/StreetComplete#453]
Tagging this: https://wiki.openstreetmap.org/wiki/Proposed_features/ISCED
Translations/mappings are listed on the wiki page or [on Wikipedia](https://en.wikipedia.org/wiki/International_Standard_Classification_of_Education) or so…

As for Germany (Gymnasium, Mittelschule, Oberschule, etc.) or New Zealand, where there are different kinds of schools in the same education level, the `isced:field=*` could be used. I think that's what this type of field is to be used for…

Of course, this could also be used for detecting wrong tags, i.e. there could be an entry "this is a different educational building" and offer to retag it as a different building. (Or, of course, "this is no educational building".)

**Comment by westnordost** [comment]
Last time I looked, the isced-tag didn't really make sense because the different types of schools (minus Grundschule / weiterführende Schule) were already expressed in the top-level tags themselves:

```
amenity=kindergarten
amenity=school
amenity=college
amenity=university
```

**Comment by rugk** [comment]
There is not difference between elementary school, middle school and high school e.g.
And as I said for some countries the `isced:field` can be very useful to determinate whether it is e.g. a Gymnasium or Mittelschule, Hauptschule…

**Comment by westnordost** [comment]
So, basically only show the quest for `amenity=school` to determine whether it is elementary, middle school or high school. OK.

The problem I see with this though is that the ranges (elementary, middle and high for US but only Grundschule and Stadtteilschule/Gymnasium in Hamburg) differ from country to country and perhaps even Bundesland to Bundesland.
This data could be taken from the wiki page you linked, but it is very incomplete (only 21 countries) and needs some thought to arrange into a format that would allow different ranges for different regions and also is only a "proposed feature".
Also, I am not sure if it can be expected that it is always visible from the street what kind of school it is.

So, these are just my initial comments for this, doesn't mean that I think it is not doable. First priority here would be to have the isced tagging or an alternative that covers the same function be approved.

**Comment by rugk** [comment]
> Also, I am not sure if it can be expected that it is always visible from the street what kind of school it is.

If not then maybe the name shows it. Or there is a plate stating "Grundschule <name of school>", which is not always refelected in the name.

> This data could be taken from the wiki page you linked, but it is very incomplete (only 21 countries)

Yeah, but if we cover 21 countries as a start that is also not bad…

**Comment by matkoniecz** [comment]
I am not sure is it a good fit for StreetComplete, at least in Poland far more efficient solution is to tag based solely on names - survey is not required at all.

**Comment by westnordost** [comment]
This is highly country-specific

**Comment by westnordost** [comment]
OK so I will close this.
