### ISSUE TITLE
New quest: contact information for shops (hairdresser & doctors)

### ISSUE THREAD

**Issue by rugk** [westnordost/StreetComplete#454]
Reviewing somehow, but not a dupe (I would not open a new issue for that…)

There you said:
> Perhaps in conjunction with general contact data (phone number, website etc), but also that probably not.

Yeah, why not do it in this way.

IMHO/AFAIK/Here in Germany I think the most common contact information is a phone number. Maybe not for restaurants, but at least most shops, hairdresser and doctors have it… (list could be expanded, or made country-specific)
Often they are written on the door/outside of the building.

So:
overpass query: all these amenities/buildings without [phone](https://wiki.openstreetmap.org/wiki/Key:phone)/`contact:phone` tag
input: primarily focus on phone number, but also allow (maybe after swiping/moving the box up) to input other [contact information](https://wiki.openstreetmap.org/wiki/Key:contact) such as fax, website and email. Possibly also social media…

However when talking about contact information also the address belongs to it. Not sure how we want to handle this. Maybe a new quest or do not ask that at all? I mean the house number quest only tags houses. A shop could have:  addr:street=*, addr:housenumber=* and addr:postcode=*. But as addr:housenumber=* and addr:postcode=*. are often [redundant](https://wiki.openstreetmap.org/wiki/Addresses#How_to_map_addresses), only asking for `addr:housenumber` (in that quest) could be okay…

**Comment by Etua** [comment]
Before adding that feature an inclusive country list should be created.

**Comment by rugk** [comment]
For what? Does not shops and so on have phone numbers etc. in the whole world?

**Comment by Etua** [comment]
Actually not. It depends on type of facility but based on my experience that information is often not visible and I'm talking about the basic information like phone number, not even website etc. BTW a user may ask: what is the website for one of the many shops in the same network?
That quest won't be easy to fulfill, asking for multiple information is discouraged and definitely should not require browsing the Internet to complete it rather than using terrain survey.

**Comment by matkoniecz** [comment]
In Poland this quest would frequently require internet to check (and almost always check using internet would be preferable), sometimes would not be doable at all.

**Comment by rugk** [comment]
This could be made as a disabled-by-default quest (ref https://github.com/westnordost/StreetComplete/issues/558).

**Comment by rugk** [comment]
Okay for takeaways it would make sense. Thinking of pizza takeaways they almost always have a phone numbers, but I am not sure how these are tagged. Pizza "take aways" might also be tagged as restaurants or so…

**Comment by HolgerJeromin** [comment]
I phoned yesterday to reserve a table, but the number of the restaurant was only visible when it is open.
So checking the website is often a better source for that.

**Comment by rugk** [comment]
Sorry, but what? And what has this to do with this issue?

Usually you do not reserve seats in pizza shops, but order it for delivery… :laughing: So okay, maybe "takeaway" is the wrong term here. That's why I looked whether they are tagged differently, but apparently they are not.

**Comment by westnordost** [comment]
So what if the place has no phone number posted?

**Comment by xuiqzy** [comment]
What about using `contact:phone:signed=no`, similar to the now used `opening_hours:signed=no`?

**Comment by westnordost** [comment]
This'd imply that these places have a phone number, but it is not posted. While in fact, it might not have one at all.
For opening hours we know that any shop will have this by definition, and be it "by appointment".

**Comment by westnordost** [comment]
So, I don't think this is eligible. Even if limited to countries where it is very likely that a place will have at least a phone number, it is not clear how to tag it if it has none. I looked at taginfo, `phone=no` just has 74 uses.

**Comment by xuiqzy** [comment]
> This'd imply that these places have a phone number, but it is not posted. While in fact, it might not have one at all.
> For opening hours we know that any shop will have this by definition, and be it "by appointment".

It doesn't have to imply that. For clearer wording, it could be something like `contact:phone:visible`. What I mean is that the tag `*:signed` could mean, like for `opening_hours`, just that there is nothing *signed*. For `opening_hours` it just happens to be the case that there *are* always opening hours.  
For opening hours, the tag means that someone (not a StreetComplete user) has to invest more time (going inside, searching the internet) to determine the opening hours.  
For a phone number, it means the same, only that the result could be that the place has no phone number.  


Of course, it would be good to explicitly tag that a place has no phone number, but couldn't the `*:signed` key be good enough for now until such a tag for "no phone number" exists?

This way, this quest could be hidden if the answer is no phone number is signed!
That would already add a lot of valuable information: the phone numbers or the info that more time intensive research is needed to find one, if it exists.

Unless introducing this new variant of `*:signed` tag is also not desirable. In that case, it is not possible as a quest of course.

**Comment by westnordost** [comment]
Well, maybe. But that is not the only reason why I closed it, the quest type is also problematic because depending on the country, it may be very uncommon to have phone numbers at all and/or to post them at the front door which would result in quite the spam. So at least what would be necessary here is to check for all the countries if this quest should reasonably be asked.

**Comment by mnalis** [comment]
Just to note for those interested that [SCEE](https://wiki.openstreetmap.org/wiki/SCEE) (StreetComplete _"Expert Edition"_ fork) does have quests asking for `phone` and `website` on various amenities/shops (a list of which one can configure if needed).

Of course, caveat emptor - such quests can be quite spammy even in countries where it is somewhat common for that information to be displayed.

**Comment by mnalis** [comment]
- (ref. https://github.com/streetcomplete/StreetComplete/discussions/5863)
