### ISSUE TITLE
Option to not turn off display

### ISSUE THREAD

**Issue by Natenom** [westnordost/StreetComplete#46]

**Comment by westnordost** [comment]
What?

**Comment by Natenom** [comment]
The display turns off after x minutes idle time. I know for example from Osmand that it can prevent the display to turn off. Such an option would be nice in StreetComplete.

**Comment by westnordost** [comment]
Hmm, so you would use this option? If you would use this option, could you think of any reason why it should not be the default? I am trying to find out why such an option makes sense (how people use this app), whether then it should be the default and whether it should be able to turn it off at all.

**Comment by Natenom** [comment]
I would definitely use this option in the case I have enough power in my battery pack or when the sun is shining.

It should not be the default because thats not always the case and while you walk from one quest to the next there is no need for the display to stay on.
But in my case it should stay on because while cycling you see lots of quests in a short time frame.

**Comment by lightonflux** [comment]
If you map with your bike and mount your phone to the handle bar it helps. Other wise you have to unlock your phone every 50 meters or so. (I am obviously against tagging while riding!)

**Comment by Natenom** [comment]
I do not excatlcy tag while riding. Of course I stop riding if there is something to tag.
