### ISSUE TITLE
New quest: Detail what "animal=yes" really is

### ISSUE THREAD

**Issue by rugk** [westnordost/StreetComplete#460]
As another animal request is unlikely to get a quest (https://github.com/westnordost/StreetComplete/issues/451) I have a new idea for something with animals… :horse: 🦉🐒🐢

There is also an [animals](https://wiki.openstreetmap.org/wiki/Animals) tag. The problem is [more than 60%](https://taginfo.openstreetmap.org/keys/animal) of this tags use the value "yes", which, I think, makes no sense. A quest could help to detail what is really done with animals/animal-related there…

Also good: low false positives, not many resulting values to consider (i.e. we do not need a list of species; see table in wiki)

Also the quest could pre-filter the answers based on the type. If it is a node it is e.g. not possible to be a horse way…

**Comment by HolgerJeromin** [comment]
Do you have examples of osm elements which you like to change?

> we do not need a list of species; see table in wiki)

This tag holds complete [random stuff](https://taginfo.openstreetmap.org/keys/animal#values) in the osm database:

yes
school
horse_walker
chicken
sport
cow
wellness
horse
shelter
dog
cemetery
cattle
no

> Also good: low false positives, not many resulting values to consider 

false positive are also elements which has used animal=yes which can not be changed with streetcomplete:
https://www.openstreetmap.org/node/4570865865 (alternative medicin stuff for animals)
https://www.openstreetmap.org/way/26322728 (used as access subtag)

**Comment by rugk** [comment]
I thought of this table: https://wiki.openstreetmap.org/wiki/Animals#amenity-veterinary

Needs extensive retagging maybe, but that's it. I don't know what "animal=chicken" or so is supposed to mean, so this is not something we may consider.

Hmm if animals=yes has a meaning then it may be more difficult, but I do not get what it is.

E.g. https://www.openstreetmap.org/node/4570865865 should be amenity=veterinary (see wiki)?

**Comment by HolgerJeromin** [comment]
This table is a list of animal related features we have or should have a proper tag. 
This is not a table listing special values as a replacement for generic animal=yes

**Comment by rugk** [comment]
Ah, okay… So you can have animals=yes, but also use the other tags… still I think "animals=yes" does not say much. As said when it is an "animal doctor" use veterinary or the other proper tags… "animals=yes", is, AFAIK, also no value documented in the wiki. It does not say anything.

**Comment by westnordost** [comment]
So, I don't really see quest material here.
