### ISSUE TITLE
Provide .apk files as download

### ISSUE THREAD

**Issue by ltog** [westnordost/StreetComplete#461]
Some people use phones/operating systems without Google Play Store, e.g. Fairphone 2 with the Open OS (see https://code.fairphone.com/projects/fp-osos/ ).

It would be nice to have the most current .apk file provided as download, so these users don't have to wait for the latest version to appear in the F-Droid store.

**Comment by westnordost** [comment]
See https://github.com/westnordost/StreetComplete/releases

**Comment by ltog** [comment]
@westnordost : Thanks for the quick answer and change to the README.
