### ISSUE TITLE
Some ideas and problems with the new gpx fix mode...

### ISSUE THREAD

**Issue by Natenom** [westnordost/StreetComplete#465]
1. In my opinion the new "orient map to compass" mode should be accessible through the "compass icon" and should be independent from the gps fix which would make much more sense to me.

2. The new mode made #429 even worse because one needs to click twice after every quest if one wants to use this instead of the default mode.

3. There should be a filter or something I don't know what to call because even if my device is laying on the table the map is constantly rotating within a few degrees.

I like the new mode, it is great, but from my point of view is is useless currently because it is not fixed.

**Comment by Binnette** [comment]
I definitively agree with you.

- Compass button is for compass mode
- GPX button is for GPS (not for compass)

**Comment by westnordost** [comment]
I expect a few iterations until the feature is "nicest possible" so this won't go into any v1.x.

How does the tilt feel when in compass mode?

> 1.

It is this way in Maps.me and in Google Maps, I mirrored this behavior. The compass mode is a "third-person-follow-direction" mode, so it is very related to the simple "follow position" mode. I tried it out separately and having the rotation follow your device orientation while looking at the map someplace else than where you actually are feels very weird and unexpected. I dare say that it makes no sense to have the map rotate according to your orientation when looking at a remote place.

**Comment by Natenom** [comment]
**Tilt**
The tilt is nice. Not only in compass mode. Just found out that you can do it manually by moving the map with two fingers after reading your post here :)

But the edges of the buildings should be made better. Currently there are only the top edges visible, not the "insert the correct word here/die seitlichen Kanten", see screenshot:
https://files.natenom.com/nidx/nobackup/sharing/5ab8e839ec78f5f4a91a6e6cd36733027fb54297542ef16a64d19777d2dd957c.png

This looks wired sometimes.

I like the tilt because it is a motivation for me to solve "how many levels" quests which I didn't like until now :)

**Compass and GPS**
What I described is what I know from OsmAnd, I didn't use maps.me or google maps on Android yet.

Btw: It should be possible to orient to north somehow when not in GPS mode.

**Comment by Natenom** [comment]
Most buildings in my village are flat in the tilt mode and I checked some of them in JOSM. There are no building:level tags. 

I remember I solved some level quests and those buildings have a height in tilt mode. 

But there are no more quests for that in SC, why is that?

**Comment by westnordost** [comment]
Level is only asked for certain buildings. Most prominently not for building=yes.

I'll try out Osmand.

**Comment by Natenom** [comment]
Is it worth to create an issue for implementing a quest for "building=" if "building=yes"?

**Comment by westnordost** [comment]
There is an issue.

**Comment by westnordost** [comment]
> There should be a filter or something I don't know what to call because even if my device is laying on the table the map is constantly rotating within a few degrees.

Tried to, but looked odd / didn't work the way it'd feel good. So this won't be implemented for now.

**Comment by westnordost** [comment]
> Btw: It should be possible to orient to north somehow when not in GPS mode.

Implemented
