### ISSUE TITLE
Scanning for more quests in tilt mode does not work

### ISSUE THREAD

**Issue by Natenom** [westnordost/StreetComplete#466]
When in "maximum" tilt mode it says "Can't scan here. Try to zoom in further" though I can see quest icons and when switching back to normal mode or to less tilt but the same height it scans for new quests.

**Comment by westnordost** [comment]
"Can't scan here. Try to zoom in further or tilt the screen less"?

Tilt greatly enlarges the area visible on screen and the download button downloads in the visible area.

**Comment by Natenom** [comment]
Sounds ok.
