### ISSUE TITLE
Wheelchair accessibility for Stolpersteine/small monuments

### ISSUE THREAD

**Issue by bbastin** [westnordost/StreetComplete#467]
StreetComplete asks for wheelchair accessibility for small monuments such as the Stolpersteine in Germany. I don't think this is intended behaviour and I would personally abstain from tagging those stones as wheelchair accessible because they obviously are.

Suggestion:
Filter out memorial=stolperstein in the wheelchair accessibility quest.

**Comment by westnordost** [comment]
Actually, I think any memorial is by default wheelchair accessible.

**Comment by westnordost** [comment]
And removed some more where it doesn't make so much sense to ask
