### ISSUE TITLE
Display authorized account name in settings

### ISSUE THREAD

**Issue by Binnette** [westnordost/StreetComplete#469]
In settings, can I replace :
> "Successfully authorized to your account"

by

> "Account %1 successfully authorized"

And insert current username in %1.
I you are ok, i'm gonna implement it.

**Comment by westnordost** [comment]
Sure, go ahead. Please rename the string id then so that it can be translated anew.

On 10 August 2017 09:52:54 CEST, Binnette <notifications@github.com> wrote:
>In settings, can I replace :
>> "Successfully authorized to your account"
>
>by
>
>> "Account %1 successfully authorized"
>
>And insert current username in %1.
>I you are ok, i'm gonna implement it.
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/westnordost/StreetComplete/issues/469

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by Binnette** [comment]
It seems not possible cause OAuth via our library [signpost](https://github.com/mttkay/signpost) only store user token and secret. It do not store user name.

Like in [JOSM](https://josm.openstreetmap.de/), we have to query OSM server in order to get user name (and user id).

May be we can do this query one time when user connect on OSM. Then we can store his username in local SC files.

I'm gonna try to implements it like that.

**Comment by westnordost** [comment]
The user information is already fetched, see line 267 in OsmOAuthDialogFragment. You can store the user name similarly as the id.

**Comment by Binnette** [comment]
PR #472 is ready to be merged :+1:

**Comment by westnordost** [comment]
I'll close this issue because there is a PR already.
