### ISSUE TITLE
Provide way to flag outdated data during tasks

### ISSUE THREAD

**Issue by daniel-j-h** [westnordost/StreetComplete#474]
I was using StreetComplete today (it matured a lot in recent months - keep up the good work!) and came across quite a few situations where there was a quest for adding a restaurant's opening hours. But unfortunately the restaurant data wasn't up to date.

You would get a task of "Can you add the opening hours for Pizzeria X" but instead of a pizzeria there's now a Korean restaurant.

- Should there be a way to flag these issues?
- How can this be made user-friendly?
- Should there just be a button to flag these issues which will open a note?

Related: should there be a task asking the user if some tags are still up to date? The restaurant example is one tag where it could make sense to now and again ask the user if it's still correct (maybe based on the osm object's last edit).

Cheers from Berlin where hip restaurants seems to change owners a lot.

**Comment by westnordost** [comment]
Yes, there should be a way and there is: Leave a note describing the situation. Leaving a note (aka "cant answer") counts as "solving", as far as the visibility is concerned.

Regarding related: Good idea, there is an issue for that already, though.

**Comment by daniel-j-h** [comment]
Perfect, merci!
