### ISSUE TITLE
Surface type quests: please improve UX / screen estate use

### ISSUE THREAD

**Issue by madduck** [westnordost/StreetComplete#475]
Most of the quests in my area related to road surfaces. When I select a quest, then I am presented with a number of choices down below, but not even the first one is fully visible:

![screenshot_20170812-205634](https://user-images.githubusercontent.com/195073/29243540-7b77cdee-7fa1-11e7-9a41-568927c48695.png)

Worse, when I click on it (which is what I want in 99% of all cases, the subchoices presented unroll completely out of view. So I first have to scroll down to be able to actually select "asphalt".

I am not entirely sure how to do this better, but you should certainly be able to improve this for your users a bit by

- using less screen estate for the map, maybe making the map tile quite small actually, especially since the question "what road surface does $Roadname have here" is specifically asked.
- making it optional whether this question is displayed at all.
- using smaller buttons for surface types, maybe allowing for long-presses to get more information, or overlaying text. The button size could be configurable, and the first row could be e.g. hard surfaces, the second row gravel surfaces, etc.
- presenting the most common responses in a row by itself at the top
- letting the user define shortcuts or favourite answers etc.

In general, I'd appreciate (and would contribute a whole lot more) if it was as simple as hitting on a surface type quest and then having to touch the screen only one more time before confirmation.

**Comment by westnordost** [comment]
> 2

There is a ticket for that already and I will work on it soon.

> 3,5

There is a ticket for that already, however, I don't like it. Before I do that, the UX of the grouped selection in general should be improved (because it opens a can of worms)

**Comment by westnordost** [comment]
Finally, there is a ticket already for the UX change Id be willing to do (or accept a PR) which is expanding a group leading directly to a submenu) like entering a folder in Explorer and similar). But, I have not come around to doing that because of other priorities yet.

**Comment by madduck** [comment]
Thanks, I am sorry I didn't find the tickets myself. I'll keep looking, or do you have their numbers handy?

**Comment by westnordost** [comment]
#76 I think
