### ISSUE TITLE
Quest: is this restaurant suitable for vegetarians?

### ISSUE THREAD

**Issue by Rudloff** [westnordost/StreetComplete#479]
Hello,

I am the developer of [OpenVegeMap](https://openvegemap.netlib.re/), a web app that displays vegetarian restaurants based on OSM data (mainly the [`diet:vegetarian` and `diet:vegan` tags](https://wiki.openstreetmap.org/wiki/Key:diet)).
Unfortunately this information is still missing for a lot of restaurants and I think StreetComplete could help with that.

Would it be possible to add the following quests for `fast_food`, `restaurant`, `cafe`, `bar` and `pub` nodes:
* "Is this place suitable for vegetarians?" (yes/no/only serves vegetarian food)
* "Is this place suitable for vegans?" (yes/no/only serves vegan food)

**Comment by westnordost** [comment]
Yes, it would. However, is the information always accessible without going into the restaurant? Sure it is for places that advertise offering veg food, but for other places, perhaps not.

StreetComplete quests must always be answerable from the street, i.e. without entering the place. See the wiki page for more details. I am not sure if this is always given for restaurants that do not advertise being veg. And as far as I know, there is no tagging option like "serves veg food= unknown/not advertised".

**Comment by Rudloff** [comment]
Most of the restaurants here in France display their menu on a window so it can be seen from the street.
I've seen the same thing in other countries from Western Europe but I honestly don't know if it's the same in other parts of the world.

**Comment by matkoniecz** [comment]
> Most of the restaurants

So it is rare, but not very unusual that menu is not available without going into the restaurant?

**Comment by Rudloff** [comment]
In France it is [mandatory](https://www.legifrance.gouv.fr/affichTexteArticle.do;jsessionid=65546A6118F96D70CFE21B323CAD81A8.tpdila22v_1?idArticle=LEGIARTI000006880034&cidTexte=LEGITEXT000006074983&dateTexte=20151020) for a restaurant to display the menu so that it can be seen from the outside.

I have also often seen boards like [this](https://media-cdn.tripadvisor.com/media/photo-s/0d/d0/79/bc/menu-displayed-outside.jpg) or [this](http://www.gardenaction.co.uk/images/garden_centres/whitehall_bristol/menu_specials.jpg) in other European cities like Berlin or London, but I'm not sure you find the same thing in smaller cities with less tourists.

(Some restaurants also display stickers like [this](http://www.vegetarianchristchurch.org.nz/wp-content/uploads/2014/08/v-sticker-on-door.jpg) but I don't think it's very common.)

**Comment by rugk** [comment]
Yeah, in German you can see the menu on the outside often, too.

**Comment by westnordost** [comment]
Well, maybe limit it to certain countries first.

**Comment by ENT8R** [comment]
What about this query for vegetarian:

`nodes, ways with ( amenity ~ restaurant|cafe|pub|fast_food|bar ) and !diet:vegetarian`

and this for vegan:

`nodes, ways with ( amenity ~ restaurant|cafe|pub|fast_food|bar ) and !diet:vegan`

**Comment by rugk** [comment]
Can't you answer these things in one quest?

`nodes, ways with ( amenity ~ restaurant|cafe|pub|fast_food|bar ) and !diet:vegan and !diet:vegetarian` would be more useful for me.

Then the quest:
> **Is this … vegetarian/vegan?**
> (small text:) *A \<type of amenity\> fulfills the criteria if there is a proper choice of dishes.*
> [Yes, vegan] [Yes, vegetarian] [No]

As, of course, vegetarian includes the vegan places.

This, skips the "only serves vegetarian food", however, so mhh… that could only be included as additional options.

Also, BTW: Should really each Starbucks café be tagged as vegan? I mean, yes, sure the coffee :coffee:  is clearly vegan.

Another problem I see: Likely the menu changes and one time you may have one dish presented outside that is vegetarian. Generally, you may see some "featured" dishes outside, but not always the whole menu. And if you only see this subset, you could get a wrong picture of the place.
On the other hand, I think, one can quite likely apply common sense there and see if a restaurant presents many heavy dishes with meat outside. Then you may only have to look for the "vegetarian" part of the menu, if there is one, and then estimate if that is enough to tag it as suitable for vegetarians (e.g. one dish may not be enough, IMHO).

**Comment by rugk** [comment]
BTW for subscribers of this issue, the current PR is: https://github.com/westnordost/StreetComplete/pull/506

**Comment by tomchance** [comment]
In the UK it is not required to display menus, and there is very mixed practice. But I think it is common enough, and easy enough to find out, to make this a useful quest.

It can also apply to markets, supermarkets and convenience stores, for selling vegetarian and vegan options.

**Comment by rugk** [comment]
Generally please also have a look on the discussion whether [it makes sense](https://github.com/westnordost/StreetComplete/pull/506#issuecomment-323605065) to ask the vegetarian quest for cafés too.

> It can also apply to markets, supermarkets and convenience stores, for selling vegetarian and vegan options.

But that might even harder considering that in every supermarket you can also buy vegetables or so… So when is a supermarket "suitable for vegetarians" then. I think there it would only make sense if it is _only_ vegetarian, but these are few amenities, so this quest has too many false-positives, i.e. too many cases, where you just have to answer" no, not vegetarian, only".

**Comment by tomchance** [comment]
Yes, good point on supermarkets. There has been some use of the tag for these where "substitute" products like soy milk, quorn, tofu etc. are sold. These days most supermarkets sell these, but it's much less common with convenience stores. But then it may, as you say, create too many false positives to be worthwhile.

Cafes, I think, are a different matter. Often in the UK cafes sell lunch food, and can be veggie-friendly or not.

**Comment by westnordost** [comment]
Need list of countries where vegetarianism / veganism is a thing.

**Comment by tomchance** [comment]
Current usage - albeit very small  - is scattered across the world: http://overpass-turbo.eu/s/rk9

Wikipedia has some info on the prevelance of vegetarianism in some countries: https://en.wikipedia.org/wiki/Vegetarianism_by_country

Are you concerned that it will create too many false positives in countries where 99.9% of restaurants won't serve vegetarian and vegan options?

I've wondered whether there could be a section in the settings to tick/untick quests of interest to the user, so this could be off by default for example.

**Comment by matkoniecz** [comment]
> I've wondered whether there could be a section in the settings to tick/untick quests of interest to the user, so this could be off by default for example.

#35

**Comment by rugk** [comment]
As for everything else, see the PR https://github.com/westnordost/StreetComplete/pull/506, I've already made a YAML out of the Wikipedia article.

**Comment by skfd** [comment]
Is there a page of detailed descriptions of how to do each Quest? This one sounds very arbitrary, can the OP or implementer write detailed guide with examples?

**Comment by Rudloff** [comment]
The reference for this quest is this wiki page: https://wiki.openstreetmap.org/wiki/Key:diet
There is a [discussion](https://wiki.openstreetmap.org/wiki/Talk:Key:diet#Full_options_:_add_a_.22friendly.22_value) about using more well-defined tags but nothing has been decided yet.
