### ISSUE TITLE
New quest: Has amenity=bench a backrest?

### ISSUE THREAD

**Issue by rugk** [westnordost/StreetComplete#484]
[backrest](https://wiki.openstreetmap.org/wiki/Key:backrest)=yes/no?

Easy, simple, lovely…

"Other options" -> [This is a picknick table](https://wiki.openstreetmap.org/wiki/Tag:leisure%3Dpicnic_table). (two benches, mostly found in highway rest places, here.)

~What about other quests about [benches](https://wiki.openstreetmap.org/wiki/Tag:amenity%3Dbench)? Or are mapping color, material or number of seats too crazy? 🙄 Note that in contrast to the backrest thing, these are [only proposed yet](https://wiki.openstreetmap.org/wiki/Proposed_features/Attributes).~

**Comment by westnordost** [comment]
Oh man, really?

What is this even used for??

**Comment by rugk** [comment]
It is **really** easy to answer. So, hey…
It is really a beginner quest and so easy, you cannot miss it.

According to [taginfo](https://taginfo.openstreetmap.org/keys/backrest#projects) it is used by OsmAnd and Vespucci… Maybe they display a minor difference in the icon?

**Comment by rugk** [comment]
And IMHO the older you get, the more useful this information may be for you. :stuck_out_tongue_winking_eye:

**Comment by PanderMusubi** [comment]
I was just about to request this quest too. See also https://wiki.openstreetmap.org/wiki/Tag:amenity%3Dbench

By the way, this quest cannot yet be extended with number of seats as there is no way to differentiate between "number of seats is not yet added to OSM" or "bench sts several people but in traditional bench style without separating arm rests." For the latter a discussion is going on to define a tag for that.

**Comment by rugk** [comment]
Nice, I'd suggest you just to upvote the issue in order to show your support for the idea.

**Comment by rugk** [comment]
Also see [this site](https://www.mapcontrib.xyz/t/4da70b-Bancs_et_tables_de_pique_nique#) for a map only about benches (and picknick tables).
