### ISSUE TITLE
New quest: Fence type/material

### ISSUE THREAD

**Issue by rugk** [westnordost/StreetComplete#485]
There is a big difference between a wooden fence and an electric [fence](https://wiki.openstreetmap.org/wiki/Tag:barrier%3Dfence)…

Mapped as: [fence_type](https://wiki.openstreetmap.org/wiki/Key:fence_type)

Other answers: "This is a wall, not a fence." --> Retag as [wall](https://wiki.openstreetmap.org/wiki/Tag:barrier%3Dfence).

Also useful: Another quest about "fence height"? Or is this too difficult to measure?

**Comment by westnordost** [comment]
Shouldn't it be just `fence=` ? Anyway, I am not sure about the application of such mapping.

**Comment by rugk** [comment]
I think it cannot be `fence=` as fences are mapped as `barrier=fence`.

Application, ehm… to know how to get over a fence. :wink: Or, Vespucci does some [stuff with it](https://taginfo.openstreetmap.org/keys/fence_type#projects)
Fences are very [diverse](https://en.wikipedia.org/wiki/Fence#Types) and the exact application of a fence (preventing [farm] animals from breaking out or preventing people from falling of a climb, …) is very likely connected to the type of a fence.

**Comment by matkoniecz** [comment]
> Vespucci does some stuff with it.

Vespucci is an editor, it just allows entering this data.

Yet another case of quest with extremely poor ROI.

**Comment by westnordost** [comment]
ROI?

**Comment by chrisdebian** [comment]
Return on Investment
Republic of Ireland?

**Comment by matkoniecz** [comment]
Return on Investment (plenty of work, without any

**Comment by rugk** [comment]
Again: data mining, completing OSM, showing show a fence looks like…

BTW, "ROI" is a funny term. But better use a tag for this ("low priority").

**Comment by PanderMusubi** [comment]
Some details might seem too nitty gritty but in 3D-rendering they improve the recognition of a location a lot when it is not simply default rendering of objects but more specific renderings.

**Comment by westnordost** [comment]
Not convinced about the "ROI", closing. 3D-rendering is an argument for any kind of feature, even color temperature of street lanterns and shapes of garbage cans.
