### ISSUE TITLE
New quest: Wall type

### ISSUE THREAD

**Issue by rugk** [westnordost/StreetComplete#486]
Similar to fences https://github.com/westnordost/StreetComplete/issues/485, walls can also be very [different](https://wiki.openstreetmap.org/wiki/Tag:barrier%3Dwall#Wall_details):
* noise_barrier near highways…
* flood_wall
* castel_wall

Other answers: "This is actually a fence." -> retag

**Comment by westnordost** [comment]
On the wiki page, there is a mix between building materials (brick, dry_stone,...) and wall designations (the ones you mentioned and more).
Also, look at taginfo: https://taginfo.openstreetmap.org/keys/wall
This is not really used at all yet.

**Comment by rugk** [comment]
Hmm… most used "no".

But you see the difference in my examples, so it may be a good task for StreetComplete to actually make use of it. As – if is not used so much yet – there is clearly a need for **completion**.

Maybe look on OSM for some walls near highways to see whether/how they are tagged…

**Comment by westnordost** [comment]
Yes, but my point is that dry_stone, brick etc. belong in a different tag than the other values. So, this makes the tag `wall=` not well-defined in the wiki.

**Comment by rugk** [comment]
Indeed it does, but this is nothing we can solve on the StreetComplete site. (Anyway, for the good, better create a discussion somewhere, either wiki or mailinglist…)

As for StreetComplete I think we can focus on the "usage/function" of a wall. The material may be a secondary thing.
Although, in this case, we would have many false-positives as most fences are likely just "ehm, some fence put somewhere…".

**Comment by westnordost** [comment]
In what case?

**Comment by rugk** [comment]
If we only care about the function and do not offer the material as an option. There are not so many values for functions as I see. So these are not false-positives, but many quests which cannot be answered…

**Comment by westnordost** [comment]
`wall=normal` ... ? ;-)

**Comment by rugk** [comment]
Yeah, think it is a bad idea. I'll rather close this issue… Walls are secondary, let's focus on fences. :wink:

**Comment by HolgerJeromin** [comment]
FYI
wall=no was added in a french import to model some open (roof only) building parts.
