### ISSUE TITLE
Semantic versioning

### ISSUE THREAD

**Issue by rugk** [westnordost/StreetComplete#488]
Next time, better tag the betas as v0.3-beta, as per [semantic versioning](http://semver.org/).

**Comment by rugk** [comment]
One result would be that these pre-releases do not appear on FDroid, as they currently seem to do so… even when the setting "use unstable updates" is set to false.

Alos the ordering on GitHub (maybe because of this?) gets [totally confused](https://github.com/westnordost/StreetComplete/releases) and lists v0.3 currently on top of all others, including on top of v1.1.

**Comment by westnordost** [comment]
> A pre-release version **MAY** be denoted by [...]

**Comment by rugk** [comment]
Yay, and now explain why GitHub messes this up…

**Comment by westnordost** [comment]
Because I renamed the tag for 0.3 to v0.3. So, "v0.3" was created new today.

**Comment by westnordost** [comment]
So, I rather not do "v0.3**-beta**"
