### ISSUE TITLE
F-Droid screenshots etc. do not show up

### ISSUE THREAD

**Issue by rugk** [westnordost/StreetComplete#489]
Follow-up of https://github.com/westnordost/StreetComplete/issues/241

Viewing the current version (last published: v1.1) in F-Droid I do not see the screenshots or even the header image.

Note that I see similar issues with other apps:
* https://github.com/cemrich/zapp/issues/54
* https://forum.f-droid.org/t/screenshots-dont-show-up-in-client-using-gradle-play-publisher/881
* https://gitlab.com/fdroid/fdroidserver/issues/357

**Comment by westnordost** [comment]
So, do you know why?

**Comment by rugk** [comment]
No idea. If you want compare the file paths with https://github.com/cemrich/zapp, there at least the header image is shown.
In any case report it to F-Droid using the links I added.

**Comment by westnordost** [comment]
I'd rather not invest time in that but wait that another project figured out the correct directory structure (or whatever seems to be the problem) and then copy it from there.

**Comment by rugk** [comment]
Okay, then follow https://github.com/cemrich/zapp/issues/54.

**Comment by westnordost** [comment]
They use the Triple-T-like directory structure. This project uses the fastlane-like directory structure. (I did not actually use fastlane but put it together with an own script because fastlane does not run on Windows)

**Comment by rugk** [comment]
Okay, thanks for the info. I've commented in the various F-Droid issues/threads there for you…

**Comment by westnordost** [comment]
Thanks

On 17 August 2017 11:23:32 CEST, rugk <notifications@github.com> wrote:
>Okay, thanks for the info. I've commented in the various F-Droid
>issues/threads there for you…
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/westnordost/StreetComplete/issues/489#issuecomment-323016741

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by mimi89999** [comment]
@westnordost We first try in `fastlane/metadata/android/` and then in `metadata/`. How did you end up with `fastlane/metadata/`? And why do you have `en` and not `en-US`?

**Comment by westnordost** [comment]
@mimi89999 :

I did not actually use fastlane to construct the directory structure (because it does not work on Windows) but wrote my [own script](https://github.com/westnordost/StreetComplete/blob/master/app/copyShopDescriptions.py) which copies over the strings from the Android `strings.xml`.

> How did you end up with `fastlane/metadata/`? 

So, `fastlane/metadata` was just a guess. Are you saying that I can simply put everything in otherwise the same structure in `/metadata/` and that would be correct?

> And why do you have `en` and not `en-US`?

My script simply extracts the strings from how they are defined for Android. So, i.e. for `pt-BR` and `pt-PT` there are different translations, but not for `de`,`es`,`pl` etc etc.
So, I get from that that F-Droid will not pick up those languages which are not defined in `languageCode-CountryCode` manner?

**Comment by mimi89999** [comment]
@westnordost You can use any of those two directory structures: `fastlane/metadata/android/` or `metadata/`. As for the language directories, I think it might work.

**Comment by westnordost** [comment]
Okay, thank you for the hints, @mimi89999 . I did this now and we will see if it shows up in the next time in F-Droid.

**Comment by rugk** [comment]
Still does not seem to work…

But the dev of PrivacyBrowser seems to found a way to make it work:
> With the 2.7.2 release of Privacy Browser, it is apparent that just removing the spaces from the file names is insufficient for resolving the problem with the screenshots not displaying.
> As such, I have moved the screenshot directories inside the images directories.

https://gitlab.com/fdroid/fdroidserver/issues/357#note_49632677
