### ISSUE TITLE
Ability to edit not yet uploaded answers instead of just hiding them

### ISSUE THREAD

**Issue by Natenom** [westnordost/StreetComplete#49]

**Comment by westnordost** [comment]
Why?

Usually, answers are uploaded right away. If this would be implemented, it would also make the workflow different for offline users <-> online users.

**Comment by Natenom** [comment]
Because you make mistakes sometimes. In such I case I need to edit the map later at home – if I remember the mistake.

**Comment by westnordost** [comment]
Hmm, I think this would better be solved by leaving private notes #47 for oneself and/or simply looking at the own history.

Adding an "edit quest" option would introduce a whole new layer of complexity (as it is a linear process now). I'll close this one in favour of #47 and creating new notes as free positions (for expert mode)
