### ISSUE TITLE
Wheelchair accessibility often asked for "stone" monuments

### ISSUE THREAD

**Issue by rugk** [westnordost/StreetComplete#490]
When there is a single stone on the ground, which has no entry as it is really just a rock, there is no need to ask for wheelchair accessibility.

/cc @Teester

**Comment by westnordost** [comment]
What tagging does this single stone have?

**Comment by rugk** [comment]
`historic=memorial` (altghough I am not sure, whether for this thing a quest was displayed)

Very sure: `historic=memorial;memorial=stone` or in conjunction with `memorial=stele`

**Comment by westnordost** [comment]
Duplicate of #467
