### ISSUE TITLE
StreetComplete - poor error message on exhausted Overpass resources

### ISSUE THREAD

**Issue by matkoniecz** [westnordost/StreetComplete#494]
In some situations StreetComplete may ask on every attempt to trigger manual scan for quest with "Cancel the current search and scan here instead?", without quest starting or error message appearing

https://github.com/westnordost/StreetComplete/blob/da98f68e4fbaf0291036d45ffc6be7e13d082c57/app/src/main/java/de/westnordost/streetcomplete/MainActivity.java#L395

It seems to happen for example with exhausted Overpass resources

```
Connected as: 1309396269
Current time: 2017-08-17T07:05:20Z
Rate limit: 3
Slot available after: 2017-08-17T07:22:38Z, in 1038 seconds.
Slot available after: 2017-08-17T07:29:05Z, in 1425 seconds.
Slot available after: 2017-08-17T07:33:33Z, in 1693 seconds.
Currently running queries (pid, space limit, time limit, start time):
```
(note, long slot timeouts were not caused by StreetComplete - it was result of large querries by other program)

**Comment by westnordost** [comment]
It asks whether to cancel the current scan because the current download is still in progress: As you noticed yourself, it waits for the overpass quota to replenish. If you wait 1038 seconds in this case, the download will continue.

**Comment by westnordost** [comment]
So, that SC runs into the overpass quota is not an error and is not shown to the user. Instead, the app just waits until the quota is replenished and then continues.
