### ISSUE TITLE
holding phone upside down (or with other unusual phone tilt) confuses tilt mode

### ISSUE THREAD

**Issue by matkoniecz** [westnordost/StreetComplete#496]
Xiaomi redmi 4

To reproduce

Hold phone, activate tilt mode

Rotate it so it is upside down, with orientation otherwise the same

Wait for StreetComplete view to update so menu is no longer upside down

Reactivate tilt mode (a separate bug)

Notice that view of the map is now toward back, not front

**Comment by matkoniecz** [comment]
Present in 7b4459d (the latest master at this moment)

**Comment by matkoniecz** [comment]
tilt mode is also confused (showing back, not front) with top of phone closer to person using it than bottom

This unusual position (one needs to look at phone from below) may be cause by attempting to shield phone screen from sun (happened for me yesterday), it is also present in 7b4459d.

**Comment by westnordost** [comment]
This should be solved now.
