### ISSUE TITLE
tilt frozen after rotating phone

### ISSUE THREAD

**Issue by matkoniecz** [westnordost/StreetComplete#497]
Tilt view is no longer behaving properly after phone is rotated

View is frozen and position is no longer followed

**Comment by westnordost** [comment]
Which StreetComplete version?

**Comment by matkoniecz** [comment]
7b4459d4df4d8126f0e911ac1c1957bdb6c04013 (the latest master at this moment)

may be related to #384 (or even outright duplicate)

**Comment by westnordost** [comment]
compass and tilt now works fine in landscape mode.
