### ISSUE TITLE
Some quest don't want to be upload

### ISSUE THREAD

**Issue by Crochetdavid** [westnordost/StreetComplete#498]
On my phone, some quest are not upload (I use WhoDoIt to see OSM diff) : 
- the surface of the street (any modif I do was upload)
- And now it's the street speed (no modification upload)

You know why ?

**Comment by westnordost** [comment]
* Please add a link to the changeset in question. You can access your own changesets in My Profile -> My Edits
* How do you know you uploaded the answer?

**Comment by Crochetdavid** [comment]
Hum, the problem is not from StreetView, it's from WhoDoIt which note feed the changset in the RSS feed
