### ISSUE TITLE
Quests not always shown in different zoomlevels

### ISSUE THREAD

**Issue by Natenom** [westnordost/StreetComplete#50]
For example there is one area where I see no quests at all when zoomed out. But I see quests few streets a little furhter on.
When I zoom in a bit one of the quests appears. Zooming in a bit more and the quest disappears. Zooming in a bit more the previous quest appears again and also a second one.

From my understanding I should see both always in every zoom level.

With this it is very hard to do all the quests in an area because you always miss some of them.

**Comment by westnordost** [comment]
If the quests would otherwise collide with each other visually, they are not shown. This is a feature of the map rendering library. I can try turning that feature off, but I think the result will not look good.

**Comment by stephan75** [comment]
Is there any map marker clustering feature in the tangram library like in leafletjs?

**Comment by westnordost** [comment]
Unfortunately not, and even if, it wouldn't help because I am not using markers. They ate not designed to be used as I use them (as a "data layer")

Am 30. März 2017 05:56:58 MESZ schrieb stephan75 <notifications@github.com>:
>Is there any map marker clustering feature in the tangram library like
>in leafletjs?
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/westnordost/StreetComplete/issues/50#issuecomment-290295659

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by Natenom** [comment]
In my example there was nothing to collide with.

**Comment by westnordost** [comment]
Could you tell me the GPS location or better submit some screenshots? This is an issue in the rendering library in any case (whether it is a bug or a missing feature), so I will send it upstream and see what they think  of it.

**Comment by Natenom** [comment]
https://files.natenom.com/public/cs/1.png
https://files.natenom.com/public/cs/2.png
https://files.natenom.com/public/cs/3.png

While making the screenshots I noticed that sometimes (very rare) the quest symbols hide while others appear for maybe 1 or 2 seconds after changing the zoom.

This is here: http://www.openstreetmap.org/search?query=leonberg%20brennerstra%C3%9Fe#map=18/48.79342/9.00717

**Comment by Natenom** [comment]
I think this is a better example because you see both complete streets in the first screenshot:
https://files.natenom.com/public/cs/a_1.png
https://files.natenom.com/public/cs/a_2.png

**Comment by Natenom** [comment]
I made a screencast. You can see that this problem is everywhere.

https://files.natenom.com/public/cs/cs.mp4

**Comment by claudiush** [comment]
I keep hitting this bug frequently as well:
Happens more often with small objects (e.g. short streets). There are no nearby other markers, but still I see those markers only blink shortly when the zoom level of the map layer changes. 
I can work around some by carefully pinch zooming to a zoom level where they stay visible so I can tap them. 

An example would be the surface quest for "Prestwick Street": https://www.openstreetmap.org/#map=18/51.53106/-0.09363. Try selecting it in the app

**Comment by escoand** [comment]
For me the street names ae1

**Comment by Chris2000SP** [comment]
I have that problem too.

**Comment by fnordson** [comment]
This problem persists in .7 
It's quite confusing in cities.

**Comment by aracnus** [comment]
In my experience, this bug is worse in 0.7. I didn't noticed it too much on previous version. As @escoand said maybe street names have something with this?

**Comment by claudiush** [comment]
Just wanted to feed back that since 0.8 this bug is properly fixed and marker do not magically disappear any longer. Thanks a lot,  @westnordost 👏
