### ISSUE TITLE
New quest: Type of bridge

### ISSUE THREAD

**Issue by rugk** [westnordost/StreetComplete#501]
"What is the [structure](https://wiki.openstreetmap.org/wiki/Key:bridge:structure) of this bridge?"

**Comment by westnordost** [comment]
Ok, this is interesting. 

But why?

By now, you might have guessed that I don't want to include anything in this application just because it _can_ be tagged, there should be some sort of application for this.

**Comment by rugk** [comment]
Yeah, I mainly think bridges are rare, so you won't see too many unnecessary quests and it is always answerable. 
Also I think this is the most useful tag/key for bridges.

I just looked at [taginfo](https://taginfo.openstreetmap.org/keys/bridge%3Astructure#projects) and was quite surprised that it is used by so many apps/in so many ways. It is even used for Wikidata…
I can also imagine it for 3d modeling…

**Comment by westnordost** [comment]
Ok

**Comment by Southernswampfrog** [comment]
Me and another student would like to try and solve this issue as a part of a course we are taking. Would that be ok by you?

**Comment by westnordost** [comment]
Sure! There is also already an icon for it I think.

Make sure you find representative photos that fit well together and show the structure of the bridge in a distinguishable manner with an adequate Cc license or (self-made) (vector) illustrations of the bridge structures.
This is the major part of the work, the rest is some lines of code.

**Comment by Southernswampfrog** [comment]
Ok, cool! Just to run our approach by you, we would first write the code and use filler-images to make sure everything works from a technical standpoint. Then we would replace the fillers with the images we make or find and then ask you for approval.
Do we just create a new branch and clone the project or what would you prefer otherwise?

I'm sorry if these are beginner questions, it's just the first time we participate in a project like this.

**Comment by westnordost** [comment]
You'd fork this project, (best create and checkout a branch named i.e. "bridge-quest" on your fork), make your changes there, then create a new Pull Request [here](https://github.com/westnordost/StreetComplete/pulls) from your branch to master on westnordost/StreetComplete.

**Comment by Southernswampfrog** [comment]
Ok, great. Thanks for the advice!

**Comment by Southernswampfrog** [comment]
Ok, I think I have most of it done, the only thing I am unsure about is what the string should look like that is returned by getTagFilters()

**Comment by ENT8R** [comment]
I would say this could be
`ways with bridge or man_made=bridge and !bridge:structure`
which gets all `ways` with [`bridge=*`](https://wiki.openstreetmap.org/wiki/Key:bridge) or [`man_made=bridge`](https://wiki.openstreetmap.org/wiki/Tag:man_made%3Dbridge) and without a [`bridge:structure`](https://wiki.openstreetmap.org/wiki/Key:bridge:structure) tag
