### ISSUE TITLE
New quest: 🅿️ (Car) parking capacity

### ISSUE THREAD

**Issue by rugk** [westnordost/StreetComplete#502]
Similar to the quest for [bicycles](https://github.com/westnordost/StreetComplete/issues/172), of course also car parking areas have a capacity tag, where you can/ and should enter how many :car:  can be parked there…

**Comment by matkoniecz** [comment]
Sorry for offtopic - but why you placed image rather than writing "car"? It makes harder to read text.

**Comment by matkoniecz** [comment]
On topic: given that car parking with capacity within hundreds are not unusual and parking capacity is typically not advertised on the ground answering may be obnoxious.

Also, in for amenity=parking, parking=surface tagged as areas it should be possible to get fair approximation of capacity from area itself.

**Comment by krzyk** [comment]
I agree with @matkoniecz this quest is not as easy to solve as the bicycle one. For bicycles you can in most cases count the places for the bicycles, but in case of parkings you either need to count the places if they are clearly marked on the road (around malls it can take some time) or you don't have the markings and you would need to approximate the amount of cars that can fit there. I haven't seen a parking with a number of total places displayed (currently free places at best).

So if there is no way to answer this quest with "places are not marked" (or similar) it doesn't look like a good candidate for a quest.

**Comment by rugk** [comment]
> Sorry for offtopic - but why you placed image rather than writing "car"?

Haha, like Emojis. But for SEO I already mentioned the word "car" in the text. :smiley: 

Mhh, counting can sometimes really be hard when the parking place is hard… If we don't want to ask the quest for all of them could we maybe limit the quest to certain sizes, i.e. only ask for smaller ones?

**Comment by westnordost** [comment]
Hmm right, I think @krzyk and @matkoniecz are right. This would be better either approximated by data consumers by area or input through looking at satellite imagery.

**Comment by rugk** [comment]
Really? What about small parking places, or… better: About nodes?
It is also possible to tag parking places as notes, so there, you have no area information and the parking place is certainly small.
Would not this be, at least, a case for StreetComplete?

**Comment by matkoniecz** [comment]
> or… better: About nodes?

Nodes should be remapped as areas, typically from aerial images.
