### ISSUE TITLE
Make wiki editable

### ISSUE THREAD

**Issue by rugk** [westnordost/StreetComplete#505]
Repeatedly requested, but let's make a proper issue…

![grafik](https://user-images.githubusercontent.com/11966684/29487146-03ef127e-84f5-11e7-9c0d-8854e6b5c747.png)

**Comment by westnordost** [comment]
Why?

**Comment by rugk** [comment]
To:
* add [photo guidelines](https://github.com/westnordost/StreetComplete/issues/487#issuecomment-322747622)
* improve or add [contributor guidelines](https://github.com/westnordost/StreetComplete/issues/503#issuecomment-323524458)

**Comment by westnordost** [comment]
Hmm, this should remain in my hands.
