### ISSUE TITLE
Auto-hide StreetComplete title bar

### ISSUE THREAD

**Issue by rugk** [westnordost/StreetComplete#507]
The big blue bar at the top of StreetComplete is "stealing" precious vertical space. In portrait mode, that may not be that bad, but in landscape mode it really ~sucks~ is not that nice.
And the only thing it shows is the app title and some things of minor importance.

My idea would be to auto-hide it, so that it disappears on a tap on the screen e.g. – similar to how things are hidden when playing a video in most apps.

Related: https://github.com/westnordost/StreetComplete/issues/402

**Comment by westnordost** [comment]
No, don't want to do that. In the frame of a larger UI redesign, I will basically remove the title bar completely and replace it probably with a few free-floating buttons (menu, star-icon with amount, perhaps max. one more).

But this is ~planned for the release where I add quest statistics and leaderboards (v4 or later)

**Comment by westnordost** [comment]
So, any fiddling around with the current design is wasted time for me.

**Comment by rugk** [comment]
Okay, that's also great idea… :smile: 

> But this is ~planned for the release where I add quest statistics and leaderboards

Better track that with GitHub issues and milestones. Then one can estimate that…
