### ISSUE TITLE
quests with ic_quest_notes icon are invisible

### ISSUE THREAD

**Issue by matkoniecz** [westnordost/StreetComplete#509]
tested with 7b4459d4

after changing https://github.com/westnordost/StreetComplete/blob/7b4459d4df4d8126f0e911ac1c1957bdb6c04013/app/src/main/java/de/westnordost/streetcomplete/data/osmnotes/OsmNoteQuest.java#L118 to ic_quest_apple quests appeared, after changing back to ic_quest_notes quests disappeared

note quests were mentioned in log as loaded, other quests with ic_quest_notes icon are also invisible.

Xiaomi Redmi 4, Android 6.0.1

As result quests showing notes are invisible.

**Comment by westnordost** [comment]
Yes, noted. I fixed this in the undo branch already.
