### ISSUE TITLE
Option to not move map to current location and not zoom to default when app gets focused

### ISSUE THREAD

**Issue by Natenom** [westnordost/StreetComplete#51]
This is a very annoying behaviour especially if you have set a different zoomlevel, want to open another app and then switch back to StreetComplete.

**Comment by daniel-j-h** [comment]
Probably related: https://github.com/westnordost/StreetComplete/issues/33

**Comment by westnordost** [comment]
Yes, it's a bug/missing feature. It should only zoom if you lock on your position (the location button is highlighted).
