### ISSUE TITLE
Don't ask for house numbers inside an area that already has a housenumber (or name)

### ISSUE THREAD

**Issue by dbdean** [westnordost/StreetComplete#510]
If I have a small school, or residential estate, etc. that has multiple buildings within in, but the site itself is all the same street address, StreetComplete still asks for street numbers for the individual buildings even though the landuse (or other area tagging) already has a streetnumber.

An example of such a situation would be this way http://www.openstreetmap.org/way/56759983.

Would it be possible to add a `NON_BUILDING_AREA_WITH_HOUSENUMBER` query and logic to check that `HOUSES_WITHOUT_HOUSENUMBERS` are not in those areas, similar to the `NODES_WITH_HOUSENUMBERS` check that already occurs in `app/src/main/java/de/westnordost/streetcomplete/quests/housenumber/AddHousenumber.java`?

**Comment by westnordost** [comment]
I have identified this as a problem as well but haven't been sure how to go about this yet. StreetComplete should not promote deprecated taggings and as far as I know, it is deprecated to have the housenumber not on the building but on an amenity/landuse area.

Or isn't it?

**Comment by dbdean** [comment]
@westnordost, I believe this way is accepted tagging, and the wiki does say so (from https://wiki.openstreetmap.org/wiki/Addresses#Multiple_buildings_for_one_housenumber):

> This often happens in farms, factories or schools. In that case, it's possible to add a perimeter to the site which contains the addr tags and other general tags such as the name.

It certainly happens a lot in real tagging, so I think StreetComplete should be able to deal with it, the only issue might be deciding what areas to include (or if including all non-building areas would be appropriate).

**Comment by westnordost** [comment]
Okay cool, then I can simply implement the way you suggested.
