### ISSUE TITLE
Don't ask for quests on access=private roads, or in access=private areas

### ISSUE THREAD

**Issue by dbdean** [westnordost/StreetComplete#511]
Would it be a good idea to keep track of private roads and areas in the quest download and suppress normal quests that would be asked on them. Just using 'access=private' would be a good start, but adding things like landuse=military might be useful too (and maybe others - schools?).

For example, I get a lot of missing street-name and building number quests in a military barracks near my house, but I'm not going to be able to go in and fix them, so it is just a source of false-alarms, or quests I cannot answer.

**Comment by westnordost** [comment]
Yes, that makes sense.

**Comment by westnordost** [comment]
(Or do you want to do that and create a PR?)

**Comment by dbdean** [comment]
I'm not really planning on coding for StreetComplete right now, so please feel free to take it, if you have the time. I'll certainly keep an eye on it, and may deal with it in the future if it is still hanging around.

On a quick implementation question though (as I have given this some thought :) ), would you see this as a separate process before other quests, and then pre-caching the forbidden areas and/or roads, or would you just add the forbidden logic to each quest on a case-by-case basis?

I can see adding access ~= private to linear-way quests could be relatively easy, but adding it to area check would require special polygon is-in checking on every quest, and it might make sense to refactor that out somewhere common.

Is it even possible to send masking areas into overpass and not even get the quests in the first place?

**Comment by westnordost** [comment]
I do not intend to add any complicated behavior. Just for street surface and perhaps some other quests, I will add `access!=private` to the overpass query. Anything else is too complex, IMO.

**Comment by HolgerJeromin** [comment]
There are some streets which are accessable inside a military area. And routers will route you through such ways. 
If this is wrong it should be popup. Streetcomplete users can leave a note and someone will add the missing access.
so +1 for only looking at the highway.

**Comment by dbdean** [comment]
Sounds reasonable.

**Comment by chrisdebian** [comment]
I understand the point, but feel that even private areas are used by people
(such as me), and this means that information can be checked and improved.
Could this perhaps be 'toggled on/off'?

Thanks,

Chris.
