### ISSUE TITLE
Clocks should always show 10 past 10

### ISSUE THREAD

**Issue by rugk** [westnordost/StreetComplete#514]
In your quest icon SVG the parking/clock icon has a clock. The clock, whoever, has the "wrong" hand position. The clock hands should show 10 past 10.
See ⏰ or any other image [of a clock](https://www.redbubble.com/de/shop/smile+yellow+design+clocks). They always "smile". Of course, you could also have [other theories](http://mentalfloss.com/article/22461/why-1010-default-setting-clocks-and-watches) about that, but it is basic designing and everyone follows it, so you should too.

**Comment by krzyk** [comment]
Why is it a basic designing? And not everyone follows it, see my browser/font for the UTF you provided:


![screenshot-2017-8-20 clocks should always show 10 past 10 issue 514 westnordost streetcomplete](https://user-images.githubusercontent.com/105730/29497538-d1793284-85e9-11e7-97a9-25de0ea99be5.png)

**Comment by rugk** [comment]
Ah funny, yeah, strange font I assume. But really, it is a well-known thing in certain "spheres". Not really an easier egg, but a common (and partly also reasonable) thing to do.

I think this issue needs not much discussion, I could easily change it in the SVG, at least.

**Comment by westnordost** [comment]
I have more important things to do.

**Comment by westnordost** [comment]
Come on, rugk. Answering to all your feature requests all take time. Time that I can otherwise invest in **actually working on the tickets**, don't you realize that? If you want to have a smiley face on some icon, then do it yourself!

**Comment by rugk** [comment]
I know, that's why I'd prefer to keep the discussion short. I think I'll just send you a PR.
