### ISSUE TITLE
Speed limit quest does not mention street name

### ISSUE THREAD

**Issue by rugk** [westnordost/StreetComplete#518]
https://github.com/westnordost/StreetComplete/issues/378, respectively, https://github.com/westnordost/StreetComplete/pull/347 introduced the name in the quest for the street surface. So why not do the same for the speed limit? It is also a street…

Note one difference: If possible, here, the "ID" (or how it is called) of the street could be preferred, such as B1 or A1 (for highways). As that is a more common attribution when talking about big streets and about traveling by car on them. And it is shorter, BTW.

/cc @Binnette

**Comment by westnordost** [comment]
It is quite irrelevant. The user should search for a speed limit sign, it is not relevant in which road he is.
(Yes, it is quite similar for street surfaces, I just accepted it because it was ~no work for me)

**Comment by rugk** [comment]
But it depends what road the user selects and in which direction the street points to. I also don't consider that too relevant, but if @Binnette maybe wants to have a look… :wink:
