### ISSUE TITLE
New quest: petrol station

### ISSUE THREAD

**Issue by rugk** [westnordost/StreetComplete#519]
@westnordost I am curious: What do you plan to do with the petrol/gas station quest?

**Comment by westnordost** [comment]
What quest?

**Comment by rugk** [comment]
Interesting you do not remember what icons you make…

This icon:
![petrol station on yellow background](https://user-images.githubusercontent.com/11966684/29497824-90fab6e6-85ef-11e7-8300-53dd2356039a.png)

**Comment by westnordost** [comment]
That's an icon, not a quest. It may be used for fuel-related quests later.

I premade some icons in expectation that sooner or later certain quests will be implemented.
