### ISSUE TITLE
Undo button

### ISSUE THREAD

**Issue by Luensche** [westnordost/StreetComplete#522]
Yesterday, while testing this app, I was a little bit to fast and suddenly the wrong house number was submitted. So is it possible to add an undo button, maybe for the last two submissions?

**Comment by matkoniecz** [comment]
see search results for "undo": https://github.com/westnordost/StreetComplete/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aopen%20undo

**Comment by westnordost** [comment]
Duplicate

**Comment by rugk** [comment]
Duplicate of https://github.com/westnordost/StreetComplete/issues/116
