### ISSUE TITLE
Low zoom level causes performance issues

### ISSUE THREAD

**Issue by rugk** [westnordost/StreetComplete#526]
STR:
1. Use a low zoom level, where some, but few quests are visible
2. Move around
3. (optional) Slightly change the zoom level in between. This seems to increase the effect.

What happens: It staggers/hangs.
What should happen: Move smoothly.

Version: 1.1

**Comment by westnordost** [comment]
Yes, known issue, can't really do anything about it. See also https://github.com/tangrams/tangram-es/issues/1565
