### ISSUE TITLE
Modify bike parking cover quest icon

### ISSUE THREAD

**Issue by rugk** [westnordost/StreetComplete#528]
Currently the bicycle capacity and cover icon use the same icon. To differentiate these quests, there should at lest be a slight modification (somehow put a roof into the icon of the cover quest?).

**Comment by westnordost** [comment]
Sure, you can do it.

**Comment by rugk** [comment]
I'll have a look. However, maybe better push your SVG changes through, to prevent merge conflicts then.

**Comment by rugk** [comment]
I'd suggest something like this:
![grafik](https://user-images.githubusercontent.com/11966684/29583614-3efacdb6-8781-11e7-9fff-898db27d408b.png)

To simplify this, I just dropped the _P_. It is quite clear that the app can only ask about bike parking stands and not about bikes driving around. Also the street sign-design makes everything clear.

**Comment by rugk** [comment]
Here is an optimized SVG version of the icon alone:
[StreetComplete_quest_bikecover.zip](https://github.com/westnordost/StreetComplete/files/1243143/StreetComplete_quest_bikecover.zip)

**Comment by westnordost** [comment]
Ok
