### ISSUE TITLE
Split SVG sprite into single SVG files per quest

### ISSUE THREAD

**Issue by rugk** [westnordost/StreetComplete#530]
So they are easier to maintain, to export (don't need to copy or select things) and it prevents merge conflicts.
If you want, I can do that next week.

**Comment by westnordost** [comment]
Mh no, I want to keep them in one file to look & see that they all fit together visually.

**Comment by rugk** [comment]
Okay, I did it myself in https://github.com/westnordost/StreetComplete/issues/530, as I need these for the wiki.
