### ISSUE TITLE
Displaying all the quest for a same element

### ISSUE THREAD

**Issue by sebja** [westnordost/StreetComplete#531]
Currently, when there are several quests for the same element, only one quest is displayed, the user has to answer or hide the displayed quest to see if there is another one for this element. 

e. g. for a road, if the information RoadSurface and MaxSpeed are missing, only the MaxSpeed quest is displayed. 

All the quest about the same element should be displayed at the same time, so the user can add the information he knows, without having to dismiss the first quest.

**Comment by westnordost** [comment]
This is technically currently not possible with the third-party map view library that this project is using.

**Comment by rugk** [comment]
Also, I think, there is already an open issue for that.
