### ISSUE TITLE
Request: enhace the new quest guide

### ISSUE THREAD

**Issue by Etua** [westnordost/StreetComplete#532]
As I can see some effort was put in order to standardize colors of the quest icons, I think that the "new quest guide" should cover so no extra changes will be needed if someone would like to upload it himself.
Edit: For now we have the following tasks:
- [ ] establish a list of categories used to match quests to the correct colors, in other words: match quests in groups
- [ ] mark every established category with a color
- [ ] explain these standards outside this issue
Of course I don't want to force rearrangement of everything, we just need to decide what combinations will work best and sustain them.

**Comment by Etua** [comment]
BTW: I find the color of the last row questionable.

**Comment by westnordost** [comment]
You mean the backgrounds...?

**Comment by Etua** [comment]
@westnordost Yes, I think it's ugly especially when combined with some icons (like money).

**Comment by rugk** [comment]
As for other enhancements: You might also suggest to look for other quests first, to check whether they are implemented or so. (Link to the wiki page)

**Comment by westnordost** [comment]
I am not bound on the background colors. The background colors should just sort the quests into rough categories:
- building related
- other man made related
- pedestrian and cyclists related
- car/streets related
- nature / agricultural related
- (open) amenities related
- shop / commercial / amenities related

I am not even bound on the exact boundaries and/or the number of these categories. I.e. the last two a very similar, as are the first two, etc.

Generally, you are free to experiment with other colors and/or sortings. You can present your results here and have it discussed by other interested members of the community.

**Comment by Etua** [comment]
What do you think of using different shades of the same color for similar groups like "open" amenities and shop/commercial?

**Comment by westnordost** [comment]
That's an option, yes.

**Comment by Etua** [comment]
I can make a new branch in my repository for tests, get feedback and make PR when everything will be ready. @westnordost How do you export svg to Android format? Is there a way to do it once (by one action) for all icons from quest_icons.svg?

**Comment by westnordost** [comment]
No, sadly not.

1. I export each and every icon by hand to each a single 128x128px SVG file and before saving, ungroup everything (Ctrl-A, Ctrl-Shift-G until nothing is grouped)
2. In Android Studio, rightclick on `res`, New -> Vector Asset -> Local File

The ungrouping is necessary if the SVG defines strokes because the Android drawable importer cannot handle group transforms.

**Comment by Etua** [comment]
@westnordost Thank you. I'll try to work something out and post updates here in order to post them. Of course I also encourage direct feedback against my repo.

**Comment by rugk** [comment]
> hand to each a single 128x128px SVG file

Ohh, so you actually temporarily have an SVG file. Maybe I should give you commit access to https://github.com/rugk/streetcomplete-quest-svgs to just prevent the work of me doing the same steps as you do, anyway…
