### ISSUE TITLE
Why not let users enter the price for toilets fees in the quest directly?

### ISSUE THREAD

**Issue by rugk** [westnordost/StreetComplete#536]
In https://github.com/westnordost/StreetComplete/pull/270 @Brinette introduced the toilets fee quest.
However there is also the [charge tag](https://wiki.openstreetmap.org/wiki/Key:charge), which you can use to specify the amount of money to be paid directly.

IMHO if you see that money has to be paid from the outside, you also very likely see the amount of it.

**Comment by rugk** [comment]
Or make this another quest…

**Comment by westnordost** [comment]
The tag is not established. Also, it is subject to change relatively often, so I do not think it is a good idea.
