### ISSUE TITLE
disable housenumber quest for parts of Portugal (especially Porto)

### ISSUE THREAD

**Issue by matkoniecz** [westnordost/StreetComplete#537]
It is request to make #535 more detailed than country level

> In Portugal, the European scheme is the most commonly used house numbering style. However, in Porto and several other cities in the Portuguese Northern region, houses are numbered in the North American style, with the number assigned being proportional to the distance in meters from the baseline of the street.

https://en.m.wikipedia.org/wiki/House_numbering

As result it is impossible to respond there to housenumber quests as every single door in building has its own number

![img_20170825_155201](https://user-images.githubusercontent.com/899988/29722678-aaba0d5c-89b9-11e7-9f8d-b340b96c0e05.jpg)

**Comment by westnordost** [comment]
It is not really possible to make it more detailed, especially not city-specific.

> As result it is impossible to respond there to housenumber quests as every single door in building has its own number

But it is! Simply answer (in this case) `413-419`. This is totally legal and a helpful approximation for a first-time mapping (and already immediately helpful for geocoders)

**Comment by matkoniecz** [comment]
Thanks, I was unaware about this tagging method.

**Comment by rugk** [comment]
I did not know that either…

> But it is! Simply answer (in this case) 413-419. 

I actually cannot do that. The default AOSP keyboard has a "-" key, but pressing it (just like the "," key) does not show it in the UI. I can only enter numbers.
And switching to the full keyboard for entering numbers connected with a hyphen, feels awkward and is certainly not intuitive.
