### ISSUE TITLE
New quest: outdoor_seating possible?

### ISSUE THREAD

**Issue by rugk** [westnordost/StreetComplete#538]
See https://wiki.openstreetmap.org/wiki/Key:outdoor_seating

Simple yes/no on many restaurants, cafes, etc. Also very easily visible from the outside, but maybe there should be a note: "When mapping during winter times, please be aware that outdoor seating may only be possible in the summer.".

**Comment by Etua** [comment]
Actually at the end of the issue you wrote the reason why this quest probably won't be included, indeed it will flood the app for the whole year with a significant chance of false positives.

**Comment by westnordost** [comment]
Well, if that is the only reason, the app could show these quests only during summertime.

**Comment by rugk** [comment]
> Well, if that is the only reason, the app could show these quests only during summertime.

Yeah, I thought this too. :+1: 

> But of course, this requires some work so to it being not simply a hack for one (unimportant) quest type.

You'll never know when another quest needs it. (and I think many quests could depend on snow or winter time or so…) So the "hack" needs to be a general thing all quests can use, of course…

**Comment by Etua** [comment]
@westnordost  @rugk  How do you define summertime? Some restaurants may allow seating outside in late March/April, some in June and end that possibility at different times. I think that no information is better than the wrong one, but I agree that such type of quest could be used elsewhere.

**Comment by rugk** [comment]
It's easy, I'd say just hide the quest in the (meteorologic) winter (except for countries near the equator, as the difference is there low/not there). That would be December, January and February on the north hemisphere and in the south hemisphere from June to September.
I mean it does not have to be too specific anyway, as the main purpose of hiding it is just to prevent accidental wrong data entered by users.
I would still include the note/warning that "it may be different in some seasons".

Alternatively, you could e.g. still show the quest, but ignore the answer if it is "no" in the winter, hide the quest (using maybe a similar logic when the quet is hidden by the user manually, when selecting "no answer") and display it again during summer time to confirm it. If the user, however answers "yes" in the winder or autumn or so, it is immediately clear that sitting outside is possible.

**Comment by rugk** [comment]
Okay, yeah gamification is a risk here.

> The only safe option would be to change OSM database only for "yes" and treat "no" the same as dismiss what is of course very impractical.

That's exactly what I proposed in my second paragraph. "impractical"… well… when other users could get confused or maybe it is not nice to ask a quest multiple times. Is that your concern or why it is "impractical"?

Anyway, I think these are enough arguments against this quest. Maybe when there is some summer/winter logic we could have a look on this again.
