### ISSUE TITLE
Include question that was asked in note comment

### ISSUE THREAD

**Issue by bobatsar** [westnordost/StreetComplete#54]
First, thanks for the nice app.

I got some quests for the level of a building where it doesn't make much sense. I know it is hard to identify but perhaps some of them can be filtered out.

One was a footway tunnel to a train station. (see http://www.openstreetmap.org/note/945746) So there is no real level.

Another was a bell_tower (http://www.openstreetmap.org/note/945759). When I had a look at the properties in openstreetmap editor, there is already a height and that it is a bell_tower.

Another problem was with an elevator entrance. Is this really a building with floors?

I think some buildings should be filtered out based on some attributes

I also added a note about the tunnel but it was mapped correctly. Perhaps it would be good to add automatically to the note, that it was inserted via "Streetcomplete" to a specific quest.

**Comment by westnordost** [comment]
> One was a footway tunnel to a train station. (see http://www.openstreetmap.org/note/945746) So there is no real level.
This is because an outline around the tunnel is tagged as "building:part" (http://www.openstreetmap.org/way/365048436#map=19/48.15591/11.41449). This is an undocumented usage of the building:part tag, if not to say, it is a wrong usage. I guess the creator of that outline way attempted to do something with the footway tunnel similar to an outline around a bridge (`man_made=bridge`). So, nothing I can do there, there can always be wrong data on the map.

> bell_tower
This is also an odd case. It looks like the creator tried to use the simple 3d buildings tagging model for 3D-modelling this bell tower. The building part in question only has information where it starts (at 45m) but not how high it is, so the data is kinda incomplete. I could hide all quests that have incomplete information, but that's eh... What do you think of this?

> Another problem was with an elevator entrance. Is this really a building with floors?
I would say no, but could you show the element in OSM? I have the suspicion it uses the same debatable usage of building:levels as the first example. 

> I also added a note about the tunnel but it was mapped correctly. Perhaps it would be good to add automatically to the note, that it was inserted via "Streetcomplete" to a specific quest.
That's possible and makes sense to communicate where this came from. It may also lead to a bug report in StreetComplete, which is also good. What wording would you suggest?

**Comment by bobatsar** [comment]
>> bell_tower
> This is also an odd case. It looks like the creator tried to use the simple 3d buildings tagging model for 3D-modelling this bell tower. The building part in question only has information where it starts (at 45m) but not how high it is, so the data is kinda incomplete. I could hide all quests that have incomplete information, but that's eh... What do you think of this?

Ok then this is wrong as it doesn't start at 45m. Munich is at about 500m above sea level.
But are you sure it is wrong? [The tower](http://www.openstreetmap.org/way/232571778#map=18/48.10766/11.57654&layers=N) has the attribute [building:height](http://wiki.openstreetmap.org/w/index.php?title=Key:height&uselang=en-US) which seems ok to me.

>> Another problem was with an elevator entrance. Is this really a building with floors?

> I would say no, but could you show the element in OSM? I have the suspicion it uses the same debatable usage of building:levels as the first example.

http://www.openstreetmap.org/node/1698297582

>>    I also added a note about the tunnel but it was mapped correctly. Perhaps it would be good to add automatically to the note, that it was inserted via "Streetcomplete" to a specific quest.

> That's possible and makes sense to communicate where this came from. It may also lead to a bug report in StreetComplete, which is also good. What wording would you suggest?

Perhaps something like:
'Inserted via StreetComplete v0.5 to quest: "How many levels has this building?":  Here comes the text of the note'

**Comment by westnordost** [comment]
> Ok then this is wrong as it doesn't start at 45m. Munich is at about 500m above sea level.
> But are you sure it is wrong? The tower has the attribute building:height which seems ok to me.

I didn't say it's wrong, it is incomplete (and weird). The "inner part" of this tower is tagged to start at +45m (0m is ground level, not sea level) but it doesn't say how high or how many levels it has. Instead, I think the author wanted to say "this is a staircase". 

> http://www.openstreetmap.org/node/1698297582

This is neither tagged as building nor building:part. This can't be the node for which the quest wanted the building levels. (Also, the quest does not apply to nodes).

**Comment by bobatsar** [comment]
First thanks for the great app, I got also a note about stopping editing with your app (https://forum.openstreetmap.org/viewtopic.php?id=57855&p=2) but I am waiting for an improved version. Keep up the good work.

Here is another example of the elevator and I think there are many of those in Munich.

http://www.openstreetmap.org/node/2554311034
http://www.openstreetmap.org/way/309047860

![screenshot_2017-04-03-09-06-43](https://cloud.githubusercontent.com/assets/7723101/24599424/693d9ffe-1850-11e7-94ad-ea4979cb7bf7.png)

**Comment by westnordost** [comment]
The thing with the elevator: I learnt this is a deprecated tagging scheme for indoor mapping. Don't ask me how the recommended one looks now, though.

Am 3. April 2017 09:38:36 MESZ schrieb bobatsar <notifications@github.com>:
>First thanks for the great app, I got also a note about stopping
>editing with your app
>(https://forum.openstreetmap.org/viewtopic.php?id=57855&p=2) but I am
>waiting for an improved version. Keep up the good work.
>
>Here is another example of the elevator and I think there are many of
>those in Munich.
>
>http://www.openstreetmap.org/node/2554311034
>http://www.openstreetmap.org/way/309047860
>
>![screenshot_2017-04-03-09-06-43](https://cloud.githubusercontent.com/assets/7723101/24599424/693d9ffe-1850-11e7-94ad-ea4979cb7bf7.png)
>
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/westnordost/StreetComplete/issues/54#issuecomment-291069706

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by westnordost** [comment]
I excluded all `building:part`s from that quest for the new version already. So this ticket is now about adding info about for which quest a note was added.
