### ISSUE TITLE
New quest: building:levels:underground

### ISSUE THREAD

**Issue by krzyk** [westnordost/StreetComplete#540]
`building:levels:underground` is not that popular like `building:levels`, but I think it is mostly because people don't know it exists (and the name is terribly long and hard to enter during surveys with mobile).

I think the query should check that a building has building:levels and then allow entering underground levels, so something like this:
```
ways, relations with building = yes and building:levels and !building:levels:underground
```

It is used for 3D rendering, building with `building:levels:underground=1` is higher than a one with `building:levels:underground=0`.

**Comment by westnordost** [comment]
No, because a surveyor won't know from the street how many underground levels a building has.

**Comment by krzyk** [comment]
What about a simple question for houses: Does this house have a basement?
With answers:
*no* = `building:levels:underground=0`
*yes* = `building:levels:underground=1`

Houses with more than one level of basement are very rare (e.g. all buildings with underground levels > 1 are only 6% of all the ones with `building:levels:underground`).
I did some overpassing and the results for building=house:
* underground = 0 -> *58*
* underground = 1 -> *1386*
* underground > 1 -> *11*

So I think that only answers 0 and 1 would be enough and those are visible from street (if one can see the building levels then to correctly answers those one has to take into account if the building has a basement).

**Comment by westnordost** [comment]
1. a basement is not always visible from the street
2. tagging `building:levels:underground=1` for _"has a basement"_ is intentionally adding potentially wrong data to OSM, as there may be more
3. the application for that data is not given. Your example is actually tagging for (that specific) renderer!
