### ISSUE TITLE
Annoyment with "follow me" mode

### ISSUE THREAD

**Issue by krzyk** [westnordost/StreetComplete#544]
After "follow me" mode was introduced I'm quite frustrated with it.
Previous mode was much saner, I could at any time just move the view to other places e.g. to:
- see if there is a street surface quest - because those are displayed on the middle of the street always, not at the beginning/ending
- see where to go next for more quests.
- solve a quest that I just saw, but couldn't solve because I had others to do first

Right now I have to:
1. click on the compass.
2. click on the compass (again, because follow me is very sticky)
3. click on N (to reset the view to the "north is up")

and now I can move the view and have north at the top. (but now If i click on the compass to move the view to the user I'm back to the follow  me mode, with zoom reset).

More over the zoom level is reset every time I enter the application if I'm in the follow me mode, which additionally forces me to click on the compass to get rid of it.

Ideal fix for me would be:
1. Remember the zoom level in follow me mode, between application restarts (e.g. after disabling and enabling the screen)
2. Allow moving the view in this mode, by doing a switch to a "free" mode
3. When clicking on compass when in "free" mode, move back to the follow me mode (but remember the zoom level).

Or get back to the previous behavior.

**Comment by westnordost** [comment]
What about if the compass-mode would be activated only via clicking the compass button, so if you want to disable follow-me mode, you don't need to click twice (and activating follow-me-mode does not reset the orientation to North)

**Comment by krzyk** [comment]
Hmm.
Let's start from the beginning.

There are three modes:
1. follow-me
2. compass (this is also follow-me, but with rotation/tilting)
3. free

You switch between the modes by clicking on the button in bottom right corner (which changes between three states: position dot/compass/different color position dot).

So I'm not sure if I understand it correctly but you want to introduce another icon for compass (besides the position dot)? If so, this would definitely help.

**Comment by matkoniecz** [comment]
I have the same problems as @krzyk.

Tilt mode for me is completely useless as it jumps wildly all time (may be result of using low quality smartphone - Xiaomi Redmi 4).

Follow mode is simply not useful for me.

Is is made worse by StreetComplete forgetting map mode all the time, so again and again I need to cycle through modes to free and click compass to orient toward North to get normal map view.

So maybe better fix would be to remember properly map mode set by user (if possible, permanently, not affected also by exciting app)?

Is it maybe also possible to improve new tilt mode and reduce jumping?

**Comment by krzyk** [comment]
It is much better now, thanks
