### ISSUE TITLE
New quest: restrictions on sex or gender

### ISSUE THREAD

**Issue by PanderMusubi** [westnordost/StreetComplete#546]
Offer quest to tag `amenity=toilets` and `amenity=shower` for restrictions on sex or gender to the entire facility. The toilet or shower is available to:
* females only
  * `female=yes`
  * `male=no`
* males only
  * `female=no`
  * `male=yes`
* females and males (may still be in different toilets or showers, but this is regarding the facility in its entirety)
  * `female=yes`
  * `male=yes`

If both are set to `no` it might also be reason to offer it again as a quest as both set to `no` is not very useful data.

See also https://wiki.openstreetmap.org/wiki/Tag:amenity%3Dtoilets and https://wiki.openstreetmap.org/wiki/Tag:amenity%3Dshower

Use for icons https://en.wikipedia.org/wiki/Gender_symbol#/media/File:Toilets_unisex.svg (also in Inkscape open symbols)

**Comment by HolgerJeromin** [comment]
I would say that 99% of all toilettes are useable to men and women at least in Germany.
Exeption are micro mapped places, but they should be tagged already correct.

**Comment by Etua** [comment]
@HolgerJeronim I agree, places with such restrictions are very rare.

**Comment by matkoniecz** [comment]
What are countries where asking this would be useful? I am not sure whatever I encountered in my life place that was open to public and females or males were banned.

**Comment by matkoniecz** [comment]
@westnordost maybe quests should be proposed in a separate bug tracker where it will be easier to ignore them?

**Comment by PanderMusubi** [comment]
Some historic toilets in the city center or showers in historic harbours or toilet buildings (often including showers) at campings have these restrictions. See for example:
* Netherlands, Groningen, city center, male only https://groninganus.files.wordpress.com/2006/08/geplaatst-op-16-augustus-2006-ondergrondse-toilet.jpg?w=590
* Netherlands, Groningen, city center, female only https://stadclickt.nl/wp-content/uploads/2016/03/Openbare-toiletten-in-Groningen-3.jpg
* Netherlands, Amsterdam, city center, male only http://amsterdamse-school.nl/Content/images/StreetFurniture/13565/_960/Van%20der%20Meij-krul%20-%20Annemarieke%20Verheij.jpg

Most Western European countries are moving towards gender neutral toilets in office buildings and restaurants, luckily, but the examples above will remain like this for a long time. If you are in dire need of a toilet and use OSM to find one, better you find one that suits your needs. The last url is not at all suited for women to use.

**Comment by rugk** [comment]
@matkoniecz Haha, no. Better don't ignore them… Don't get to be used to such a rude behavior. You could however built or use a platform for proposing quests, maybe with some voting mechanism or other things to track these ideas better.

Personally I'd say an [issue template](https://help.github.com/articles/creating-an-issue-template-for-your-repository/) could already help.

----

Back to this quest:
I also did not understand the OSM tagging there in general. `female=yes` and `male=yes` means it is a unisex toilet, but also all other toilets usually have separated entries for males and females, and I never noticed male or female-only toilets, either…

**Comment by PanderMusubi** [comment]
@rugk, unisex only refers to a unisex entrance to the facilities, not that the toilets themselves are unisex. More info on this is at OSM wiki. Was confusing to me too in the beginning.

**Comment by westnordost** [comment]
See comments

**Comment by althio** [comment]
This is needed in some countries, especially India.
I remember from [this talk from Srravya](http://2016.stateofthemap.org/2016/is-she-a-part-of-your-community/) ([video at 10:00](https://youtu.be/qn2wk4JT2FQ?t=10m)) and following questions/discussions.

**Comment by rugk** [comment]
Okay, the public showers thing is a bit crazy, I mean I have never seen a public shower in Germany. (And if, they would be connected to a toilet, presumably.)

Generally I also see that the male/female tags are **both** not used much according to taginfo (for `
amenity=toilets`):
![grafik](https://user-images.githubusercontent.com/11966684/29789355-0a55b828-8c36-11e7-93f2-03ddf7087d75.png)

And seeing our discussion I can also understand why nobody tags it as such. `unisex=*` is also only 7.54%, so most toilets have no gender information at all.

However, it could still be useful to know about a situation like in India. The question is: Are there male-only or female-only toilets?

**Comment by PanderMusubi** [comment]
Public showers you will find in harbours and natural swimming, surfing or kitesurfing locations and have their own entrance in order not to occupy toilet the same time.

**Comment by rugk** [comment]
Ahh, okay, so that is clearer to me now. The situation is however likely the same than for toilets: Either they are "unisex" (there is no information about who can use it – just some shower in the swimming bath) or they have parts for both sexes.

**Comment by PanderMusubi** [comment]
Note that unisex, by the definition on the wiki, is regarding the entrance. Perhaps you meant that by the double quotation marks. Just to be sure. So better call it male+female or gender neutral for the discussion here.

**Comment by rugk** [comment]
In my sentence I just used it as "there is no information about who can use it", …
But yes, you are right.

**Comment by rory** [comment]
I'd like to work on this, as part of the [Diversity quarterly project](https://wiki.openstreetmap.org/wiki/Diversity_Quarterly_Project/2018_Q2). There is benefit especially with `unisex=yes` tag. I'd like to seek consensus on the `unisex=*` tag, since ["unisex toilet"](https://en.wikipedia.org/wiki/Unisex_public_toilet) means a gender neutral toilet, and is very different from `male=yes female=yes` (which means gender segregated)

Many, smaller public toilets, often can only have one user at a time, so are likely to be "unisex"/"gender neutral", whereas larger public toilets are likely to be gender segregated. I think this split might be within the 20/80% split suggested. Some privately owned cafes/restaurants in some areas are switching to gender neutral toilets (e.g. [some Starbucks's](https://jezebel.com/5653179/dc-starbucks-will-switch-to-gender-neutral-restrooms)).

For trans, or gender non-conforming, people, there is a big difference between a "unisex"/"gender neutral" toilet, and a toilet which is usable for both men & women (but they must use separate rooms/areas.

Perhaps a "Is this toilet gender segregated?" quest would be better? With options for "yes", "no, separate male & female", "only male", "only female".

**Comment by matkoniecz** [comment]
> Perhaps a "Is this toilet gender segregated?" quest would be better? With options for "yes", "no, separate male & female", "only male", "only female".

I strongly suggest to open a new issue:

- see the title, that quest is completely different from one originally suggested
- discussions in closed issues are likely to be ignored

**Comment by rugk** [comment]
BTW what this issue here has shown is that the tagging of toilets in this aspect is very confusing. It is not clear whether the tag applies to the entrance, to segregated or not, etc. toilets.

**Comment by rory** [comment]
I am not sure *what* the correct tagging is. When that's clear, I'll open a new issue (and maybe submit a patch) 🙂

**Comment by pandark** [comment]
The correct tagging is probably `gender_segregated=yes/no`
It's one possibility, [according to the wiki](https://wiki.openstreetmap.org/wiki/Tag:amenity%3Dtoilets#Gender_neutral_toilets), and the good thing is that, since it's specific, it should be easy to automatically convert, if the way to tag this changed.
Should I open a new issue?

**Comment by matkoniecz** [comment]
If it is passing https://github.com/westnordost/StreetComplete/wiki/Adding-new-Quests-to-StreetComplete then new issue would be a good idea.

**Comment by rory** [comment]
> The correct tagging is probably `gender_segregated=yes/no`

**Comment by pandark** [comment]
@rory Have you read [the paragraph](https://wiki.openstreetmap.org/wiki/Tag:amenity%3Dtoilets#Gender_neutral_toilets) I linked?

**Comment by rory** [comment]
Yes, I have read it (and wrote it 😉). But `unisex=yes/no` is considerably more common in OSM than `gender_segregated=yes/no`.

**Comment by pandark** [comment]
Can one rely on this tag to make an map of gender-neutral toilets (for transgender/non-binary people), for example, or will there be a non-negligible risk that a toilet marked `unisex=yes` is actually a `male=yes`+`female=yes`?

From what I understand, there's no way to distinguish gender-neutral toilets without a field survey (which is what street complete is for) at the moment.

Every `gender_segregated=no` is `male=yes`+`female=yes`+`unisex=true` but according to OSM wiki every `unisex=true` is not necessary `gender_segregated=no` but it can also be a `male=yes` and a `female=yes` with a common entrance.

As I said, if later a consensus forms that `unisex=true` means gender-neutral, there's always the possibility to automatically replace `gender_segregated=no` with `unisex=true`.

**Comment by rory** [comment]
Yes, I'm aware of the risk and the ambiguity. I plan (at some time) to do a proper analysis of the `unisex=yes` tags to try to deduce what people are actually mapping.

I thought StreetComplete did not intend to promote new tagging schemes? `gender_segregated=yes/no` is not used enough to be established IMO

**Comment by westnordost** [comment]
> I thought StreetComplete did not intend to promote new tagging schemes?

Correct

**Comment by pandark** [comment]
Thanks for the replies.
I thought it was already used, but I see it's actually marginal. I guess it's not time to open a new issue yet, then :man_shrugging:
