### ISSUE TITLE
Issue with the podotactil crosswalk quest

### ISSUE THREAD

**Issue by Dostoi** [westnordost/StreetComplete#547]
There's a quest asking if a crosswalk has podotactil equipment or not. But I've found a lot of crosswalk which have podotactil equipment on only one side and not both.
I think this can be an issue if you're a blind person and you choose a path with podotactil equipment at every crosswalk and you expect them to be there everytime but they're only on one side.

It would be better to allow more precise response instead of just yes/no. Like be able to say on only one side and precise which one afterward.

**Comment by rugk** [comment]
The English name for the quest is [tactile paving](https://wiki.openstreetmap.org/wiki/Key:tactile_paving). And according to the wiki, there is no difference between right or left. I think, if there is a tactile paving then it is there, mostly it is just in the middle or so…

**Comment by westnordost** [comment]
A tactile paving just on one side of the crossing does not make sense, so that's a "no".

Do you believe that it is necessary to explicitly state that in the quest?

**Comment by rugk** [comment]
Aha, I've never understood how it is meant as I never saw such a tactile paving on a crossing (for bus station it is common, here, but not for crossing).

So is the paving for crossings to be meant on each side of the crossing? I thought it has to be on the street it crosses, as [seen here](https://wiki.openstreetmap.org/wiki/File:Tactile_paving_on_crossing_ja.jpg)…

If one side only is incorrect, it may be `tactile_paving=incorrect`, theoretically…

**Comment by Dostoi** [comment]
It's pretty common where I live to see it only on one side of the crosswalk.
So if only one side isn't good maybe saying it.
Or adding an answer "only on one side" and setting tactile_paving=incorrect as said by rugk

**Comment by westnordost** [comment]
I find that pretty weird. So what were the city planners thinking? That blind people walk this only in one direction??

**Comment by westnordost** [comment]
So, are they any suggestions on how to change the question _"Does this crosswalk have tactile pavings?"_ to make it clear that the tactile pavings should be present at both ends of the crosswalk?

**Comment by rugk** [comment]
So I misunderstood the quest all the time. :disappointed: 

I did not even understand that the **end** of the crosswalk is meant. I always thought they need a line going **over** the crosswalk, i.e. over the street. (This was also, although I of course know it is always the case, indicated by the way the **whole** crosswalk is marked on the map.)
I mean the images are not showing that "end" thing, neither. They are just the same as for bus stop.

You see the UX issue here? So maybe this also needs a better image or so.

**Comment by westnordost** [comment]
Perhaps, yes. Tactile pavings can look very different from country to country. In Germany, it is usually 

![](https://www.baulinks.de/webplugin/2010/i/1565-kann2.jpg)

(And at "Bordabsenkung", there'd be each the crosswalk to the other side of the road)

**Comment by westnordost** [comment]
But basically, as StreetComplete is not for experts but laymen, what the users should look for is not this whole construc,t but if those _"genoppte und geriffelte"_ pavings are present or not. If they are present, we should be able to trust the city planners that they know what they are doing - that the pavings are not there for fun and part of a blind-enabled intersection.

**Comment by rugk** [comment]
Indeed, and because it is not for experts, a noob such as me did not knew how the quest is meant until you posted that picture. :laughing: 

BTW that picture is awesome. What is the source? (May we possible even use parts of it?)

And if we use an image showing a crosswalk with tactile pavings at both ends, we also satisfy the original problem of this issue that only one side is "tactile-paved".
Hard criteria, however…

**Comment by westnordost** [comment]
I am not entirely happy with the example tactile-pavings-images shown currently in the quest (but it is better than none), so this can always be improved.

**Comment by rugk** [comment]
Is "feedback [still] required"? (the tag)

**Comment by pandark** [comment]
When I came across one-sided tactile paving, I was unsure, but eventually answered yes… So if the answer should be no, the question should probably explicitly say so.

**Comment by westnordost** [comment]
The problem is that I am not sure myself. The wiki is also not clear about this.

**Comment by westnordost** [comment]
The issue that must be considered is that StreetComplete users are not experts. They must be able to answer the quest(ion) without having to have an introduction beyond the phrasing of the question an a short explanatory text and/or image.

**Comment by dbdean** [comment]
Does this crossing have tactile pacing on both sides: [Yes] [Only One Side] [None], and apply the appropriate tagging. (yes, incorrect, no)

**Comment by westnordost** [comment]
Hm, I read the wiki again. It does not state what to tag if it is only present on one side. It is not really `incorrect`, but `incomplete`. So, if it is incomplete, does that mean an intersection has tactile paving or not? Or is the paving incorrect?
I would tag it as "not", because the paving that is there, is correct, only it is not enough to declare this crossing as "blind enabled". (I rather tag something as `no` than `yes` in doubt, because for blind people to rely on this tag, a `yes` must be really a certainty (and not `perhaps`).

(Anyway, this issue should be solved soon, so I mark it for v3).

**Comment by westnordost** [comment]
So I posted that as a question on the wiki page, put it on my watchlist and for now only changed the wording of the question to "...on both sides?". I will see how the argumentation goes and adapt the implementation when a conclusion has been reached.
