### ISSUE TITLE
Quest Enhancement- Bus Stops

### ISSUE THREAD

**Issue by chrisdebian** [westnordost/StreetComplete#548]
Hi, all.

I was just doing some surveying, and had a thought about Bus Stops.

http://wiki.openstreetmap.org/wiki/Tag:highway%3Dbus_stop

Could we add additional functionality to the Bus Stop quest, to establish the name of the bus stop?

Eg:

'Does this bus stop have a name?' (name=*) and,

'Does this bus stop have a Passenger Information Display?' (passenger_information_display=* (yes/no))

http://wiki.openstreetmap.org/wiki/Key:passenger_information_display

What do you think?

Many thanks,

Chris
chris_debian

**Comment by Etua** [comment]
Good idea

**Comment by westnordost** [comment]
1. No, one quest, one question. 
2. Please make one issue per quest
3. Yes, asking the name of a bus stop makes sense. You can open a ticket for that.
4. You failed to explain why the unapproved tag "Passenger Information Display" is of any value to record

**Comment by chrisdebian** [comment]
As stated: "close proposals -> rude, not in the faith of FLOSS, destroys
community, frightens potential contributors, i.e. no solution"

Thanks! What we tend to do, is wait for a reply on a mailing list, then say
something like 'If it's ok with you, I'll close this bug / request, for the
reasons we discussed'; it's just how people interact.

The application is great, but I won't respond to the mailings anymore, and
will unsubscribe on Git.

I have a great deal of experience with open source projects, and I guess
that working with this one, isn't meant to be.

Bye!

Chris

**Comment by rugk** [comment]
Outch, hey @chrisdebian, I see you've copied that quote from my issue. Just to clarify: There, I meant "close immediately without any explanation". Of course, it is okay to [say no](https://opensource.guide/best-practices/#learning-to-say-no) as a maintainer.
And I am saying this as someone who created a lot of "new quest" issues here. [If you search for my issues](https://github.com/westnordost/StreetComplete/issues?q=is%3Aissue+author%3Arugk+is%3Aclosed) you see I've had to accept this here multiple times, too. It's sometimes hard, but you have to accept the goal of a project and that some things cannot be done.

In your case, I BTW see a good explanation and even suggestions for further things to be done. So I've created a new issue for the bus stop name (https://github.com/westnordost/StreetComplete/issues/551).
Maybe you want to create a new one for "Passenger Information Display"? (Or just explain here, why it is useful?)
You can use my ticklist template or just explain why the tag should be included in StreetComplete.
