### ISSUE TITLE
Crash on startup.

### ISSUE THREAD

**Issue by dafoxia** [westnordost/StreetComplete#55]
Crash on startup on Android 4.4.2. (Version 0.5) Older version (0.4) runs fine.
Where could I find a crashreport to submit more information?

**Comment by Natenom** [comment]
I had the same problem. Worked after "Clear Data" in the app information.

**Comment by dafoxia** [comment]
Uninstalling 0.4 first and then install 0.5 worked for me. Clearing Data did'nt solved it.

**Comment by westnordost** [comment]
Hmm, ok. Wonder what it was, though.

Anyway, thank you for the info.

**Comment by rugk** [comment]
After update:
````
E/AndroidRuntime(22502): FATAL EXCEPTION: Thread-2148
E/AndroidRuntime(22502): Process: de.westnordost.streetcomplete, PID: 22502
E/AndroidRuntime(22502): Theme: themes:{com.android.providers.downloads.ui=overlay:com.spastef.inversion, com.fsck.k9=overlay:com.chummy.jezebel.material.dark.regression, default=overlay:com.chummy.jezebel.material.dark.regression, iconPack:system, fontPkg:com.chummy.jezebel.material.dark, com.android.systemui=overlay:com.chummy.jezebel.material.dark.regression, com.android.systemui.navbar=overlay:com.chummy.jezebel.material.dark.regression}
E/AndroidRuntime(22502): java.lang.NullPointerException: Attempt to invoke interface method 'java.lang.String de.westnordost.streetcomplete.data.QuestType.getIconName()' on a null object reference
E/AndroidRuntime(22502): 	at de.westnordost.streetcomplete.tangram.QuestsMapFragment.addQuests(QuestsMapFragment.java:277)
E/AndroidRuntime(22502): 	at de.westnordost.streetcomplete.MainActivity.onQuestsCreated(MainActivity.java:563)
E/AndroidRuntime(22502): 	at de.westnordost.streetcomplete.data.VisibleQuestRelay.onQuestsCreated(VisibleQuestRelay.java:32)
E/AndroidRuntime(22502): 	at de.westnordost.streetcomplete.data.QuestController$6.run(QuestController.java:230)
E/AndroidRuntime(22758): FATAL EXCEPTION: Thread-2192
E/AndroidRuntime(22758): Process: de.westnordost.streetcomplete, PID: 22758
E/AndroidRuntime(22758): Theme: themes:{com.android.providers.downloads.ui=overlay:com.spastef.inversion, com.fsck.k9=overlay:com.chummy.jezebel.material.dark.regression, default=overlay:com.chummy.jezebel.material.dark.regression, iconPack:system, fontPkg:com.chummy.jezebel.material.dark, com.android.systemui=overlay:com.chummy.jezebel.material.dark.regression, com.android.systemui.navbar=overlay:com.chummy.jezebel.material.dark.regression}
E/AndroidRuntime(22758): java.lang.NullPointerException: Attempt to invoke interface method 'java.lang.String de.westnordost.streetcomplete.data.QuestType.getIconName()' on a null object reference
E/AndroidRuntime(22758): 	at de.westnordost.streetcomplete.tangram.QuestsMapFragment.addQuests(QuestsMapFragment.java:277)
E/AndroidRuntime(22758): 	at de.westnordost.streetcomplete.MainActivity.onQuestsCreated(MainActivity.java:563)
E/AndroidRuntime(22758): 	at de.westnordost.streetcomplete.data.VisibleQuestRelay.onQuestsCreated(VisibleQuestRelay.java:32)
E/AndroidRuntime(22758): 	at de.westnordost.streetcomplete.data.QuestController$6.run(QuestController.java:230)
```

Clearing data is no solution as this destroys potentially unsaved (not yet uploaded) changes and maybe also the OSM login.
Please reopen this issue and fix it properly. Deleting data is users and making the app unusable is horrible.

**Comment by westnordost** [comment]
Thank you for the stack trace.

This can be fixed. It looks like there are quests in the database that do not exist anymore. I wonder which these would be, I did not delete any. Anyway, the solution is to simply not recreate quests from the DB that become somehow invalid (and log an error to console + delete the invalid quest from DB).

The bad news for you is, that if you have a lot of changes and do not want to delete them, you will have to wait for a new version where this is fixed. This will take some time.
If you have Android development tools, you can have a look into the database and delete the entries that are invalid (nonexisting quest type) by hand.

**Comment by rugk** [comment]
I'll either wait or just delete my data. Hopefully you'll get out a fix fastly.😎

**Comment by westnordost** [comment]
Of course this does not solve the underlying problem, why the quests got corrupt in the first place. Please, the first thing you do after getting the new version, send me the log. Do you know how to do this?

**Comment by limburgher** [comment]
Same here, upgrade causes a crash, but uninstalling 0.4 and installing 0.5 works.

**Comment by rugk** [comment]
Sorry, I've already deleted the data and reset it…
I would have helped otherwise, but it seems I was too impatient.

**Comment by westnordost** [comment]
Hm ok, then I will close it.

**Comment by rugk** [comment]
Nevertheless you should try to fix the reason of this crash/bug here. I don't want the same to happen on an update later.

**Comment by forteller** [comment]
I've updated to 0.5 and now have the same issue as the others here. If I can be of any help to try and fix this issue, please let me know. I don't know how to get a stack trace or a log, so please tell me how if that's needed.

**Comment by rugk** [comment]
You need to access the logcat and filter for `AndroidRuntime` for app crashes. There are apps for accessing the logcat with root or you can also do it with adb AFAIK.

Anyway sad to see this issue still occurring, that's why I've requested to reopen this issue. Obviously it is *not* fixed…

**Comment by forteller** [comment]
Well, this did happen to me long before I commented, though. So it might be fixed if it's possible to upload a new version to F-droid that just has the exact same version number and only is pushed out to those that hasn't updated yet? I dunno.

I don't have root, unfortunately. Never figured out how to root my Galaxy Note 3. And adb is a bit complicated stuff, isn't it? And is it available via Linux? As you understand, I'm far from an expert on these things. I'll wait and see if the devs want this info enough for the work to be worth it.

**Comment by rugk** [comment]
> So it might be fixed if it's possible to upload a new version to F-droid that just has the exact same version number and only is pushed out to those that hasn't updated yet?

No, I doubt so. Git tags and thus version numbers in FDroid must be unique. The version number could only have a string appended (`v0.3-fixed`), but in this case you can also just push out a new version.

> Never figured out how to root my Galaxy Note 3. 
There are [many guides for this](https://lmddgtfy.net/?q=Galaxy%20Note%203%20root)…

> And adb is a bit complicated stuff, isn't it?

Not that complicated…

>  And is it available via Linux? 

Installing on Linux is often the easiest way for adb. Use your distro's packages, e.g. `sudo apt-get install apt`.
