### ISSUE TITLE
New quest: Add name to bus stops/trams

### ISSUE THREAD

**Issue by rugk** [westnordost/StreetComplete#551]
[Bus stops](https://wiki.openstreetmap.org/wiki/Tag:highway%3Dbus_stop) should always have a name. Because otherwise you cannot search for bus stops on the map, which makes them quite useless.

* [x] Easy to answer, i.e. everyone can easily solve it (from the outside)
* [x] Easy user interface. (similar to streetname quest)
* [x] Has a useful purpose. (bus stops are useless without it, see above)
* [x] Established tag. (name is established, of course)
* [x] Low unanswerable quests. (i.e. low false positives; bus stops should have a street sign in all countries)
* [x] It can be determined, if the quest is needed to be asked. (Yes, if the name is not set.)

However…
* [ ] the quest applies to a reasonable number of things (i.e. is not a small quest, whcih can only be found in one city) – I am not sure about this, as I don't know how common is this "defect" of a missing for such an object is.

Issue idea by @chrisdebian, original issue https://github.com/westnordost/StreetComplete/issues/548

**Comment by rugk** [comment]
Of course, this also applies to trams.

**Comment by westnordost** [comment]
Not sure what you mean with the last checkbox, I see no problem there. Generally, all/most bus stops across most countries have names.

**Comment by rugk** [comment]
I just mean that maybe the problem this quest tackles is really small (in your new checklist that is the "Applies to a reasonable number of elements"): Because are not all bus stops on OSM mostly correctly mapped with a name on it? Is there even a reasonable number of bus stops without a name?

I am not sure about this…

**Comment by westnordost** [comment]
About 400000 bus stops currently have no name

**Comment by rugk** [comment]
I have no idea how you got this number, but that is more than enough to be worth a quest.

**Comment by westnordost** [comment]
https://taginfo.openstreetmap.org/tags/highway=bus_stop#combinations

Total highway=bus_stop: 1918159
highway=bus_stop with name=*: 1573134

(And that's only highway=bus_stop)

**Comment by dbdean** [comment]
This would fall under https://github.com/westnordost/StreetComplete/issues/309, right? And have the same translation problems?

**Comment by westnordost** [comment]
Hm`? Usually, bus stops are not that close to each other that you can mistake one for the other.

**Comment by dbdean** [comment]
Not that there would be bus stop confusion, but that it would make sense to roll this into the general 'What is the name of this {object}?" quest, rather than having a separate name quest for bus stops. And that that quest is blocked by the translation issue.

**Comment by rugk** [comment]
I think a specific quest would make sense – even if it is just for the different (more appropriate) icon. I see no translation issue when you just ask "What is the name of this bus stop?" for this quest.

**Comment by PanierAvide** [comment]
Still something that should be done ? We have an interest for a local group of having a quest for setting bus stop names, so I can work on this.
