### ISSUE TITLE
Enable more quests for Austria

### ISSUE THREAD

**Issue by ServusWorld** [westnordost/StreetComplete#552]
I haven't seen many of the existing quests in Austria, though they would make sense here.
The following quests could definitively also be applied in Austria:

- BabyChangingTable
- BikeParkingCover
- CrossingType
- TactilePavingBusStop
- TactilePavingCrosswalk
- ToiletsFee
- WayLit
- WheelchairAccessBusiness
- WheelChairAccessPublicTransport
- OrchardProduce
- PlaceName
- PowerpolesMaterial

**Comment by westnordost** [comment]
All quests are applied in all countries. So, they are there, also in Austria.
