### ISSUE TITLE
Quest icon suggestions

### ISSUE THREAD

**Issue by rugk** [westnordost/StreetComplete#554]
The [baby icon](https://wiki.openstreetmap.org/wiki/File:StreetComplete_quest_baby.svg) looks a bit confusing as the diaper is green on a green background, is not it? Or does the baby have nothing there, but only legs hanging somewhere in the air?
Suggestion: Just change it to a white diaper or so…

The [bus stop icon](https://wiki.openstreetmap.org/wiki/File:StreetComplete_quest_bus.svg) has no indication that the quest is actually about the shelter. Especially if other bus quests come (https://github.com/westnordost/StreetComplete/issues/551) we need to differentiation icons here.
Solution: Add some roof as for bike parking quest.

The quest icons about the [visually impaired users](https://wiki.openstreetmap.org/wiki/File:StreetComplete_quest_tactile_paving_crossing.svg)/tactile paving could maybe get the well-known [yellow blind sign](https://openclipart.org/detail/68263/blind-symbol). What do you think about this?

**Comment by westnordost** [comment]
> baby icon

Naah, it's fine, imo. (Also, I am unsure if this quest should be kept in the long term, because it collides with the guideline that one shouldn't need to enter a place :-/)

> bus stop icon

Yeah, okay. Or rain drops.

> Yellow blind sign

This is only known in Germany et al. The icon used in StreetComplete is the international one.
https://de.wikipedia.org/wiki/Sehbehinderung

**Comment by Etua** [comment]
I agree with @westnordost about the blind sign. However as the number of suggestions of quests that require entering some place (or specifically building) will increase (even already implemented wheelchair access may be considered as one) we may think of including them together with #35. Ideally all such tasks wouldn't be shown by default, but a possibility to turn them on as a group or only some of them depending on a user's decision would be offered.

**Comment by westnordost** [comment]
So, you are free to create an icon for the bus stop shelter and create a PR for that.

**Comment by rugk** [comment]
As you seem to accept a PR and have a thing, which should be changed, please leave this issue open until it is closed. Closing it before a fix made it into master is considered rejecting the issue.

So back to the issue. I tried. I think the rain drop idea is good, but designing a rain drop is not really my thing, so I tried to use [this icon](https://openclipart.org/detail/116773/dew-drops) and this is what came out:
![grafik](https://user-images.githubusercontent.com/11966684/29794661-3bedd59c-8c49-11e7-87f2-80963868e73e.png)

Yes, ugly, I know. I think here we need a raindrop icon in the same style as you design all other icons, otherwise it just does not fit.
Or maybe we have better ideas instead of using a :droplet:?

**Comment by westnordost** [comment]
😅
