### ISSUE TITLE
add halo/dark glow/outer shadow to text over images in quests

### ISSUE THREAD

**Issue by HolgerJeromin** [westnordost/StreetComplete#557]
I am not sure if this is a generic problem, but on the recycling quest the white text is no easy visible over white parts of the icons.
Having a dark background around the text chars would help. Similar to this:
![image](https://user-images.githubusercontent.com/2410353/29763962-a39957f8-8bd5-11e7-8297-316c6aaf4dea.png)

![image](https://user-images.githubusercontent.com/2410353/29763999-c46ce2d8-8bd5-11e7-867c-f4184caf7c9b.png)

Screenshot:
![rps20170828_161350_729](https://user-images.githubusercontent.com/2410353/29777337-faabb0aa-8c0b-11e7-8277-36af26b7ae6d.jpg)
**Note**: The white blur comes from the OK button row. I can scroll the icons a few pixel to the top which makes the icon bottom sharp again.

**Comment by Binnette** [comment]
Hum ? Can you provide a screenshot of what you get on your device please ?

**Comment by westnordost** [comment]
There is already a shadow like this. It can certainly be increased in size. See `styles.xml` line 68. Perhaps someone wants to experiment what is the best value there?

**Comment by ENT8R** [comment]
What do you think about this?
Can I create a PR for that? Or isn't this enough?
<img src="https://user-images.githubusercontent.com/25306497/31578070-075b3a40-b11a-11e7-952f-4e2db6ef049c.png">

**Comment by westnordost** [comment]
I think it could be a bit more around the text and less only below it.

**Comment by HolgerJeromin** [comment]
Wertstoffhof is still very/too noisy

**Comment by ENT8R** [comment]
If this isn't enough we maybe have to change the color of the shadow?!
![screenshot_20171015-151302](https://user-images.githubusercontent.com/25306497/31585096-ef97ed02-b1bb-11e7-928b-3791377c640f.png)

**Comment by westnordost** [comment]
That looks good.
