### ISSUE TITLE
"Searching for quests": German wording is confusing

### ISSUE THREAD

**Issue by ServusWorld** [westnordost/StreetComplete#559]
When the app starts searching for new quests, it alerts _"Suche nach weiteren Aufgaben"_ in the German version. This can also be understood as a prompt, like "Search for new quests".

_"Suche nach weiteren Aufgaben läuft"_ would be more clear.

**Comment by rugk** [comment]
You can join POEditor to improve the translations: https://poeditor.com/join/project/IE4GC127Ki

**Comment by rugk** [comment]
IMHO "Suche nach weiteren Aufgaben…" would already make it clear, but that "…" to indicate a progress should then be added to all translations.

**Comment by westnordost** [comment]
See @rugk. POEditor also as a comment function so other German language contributors can talk about it. Personally, I agree with @rugk and wouldn't mind if the "…" would be added to the translation of that string for any language (to be consistent).

**Comment by rugk** [comment]
The question only you can tackle here is: May be maybe add `…` in the original English string? Then all translators know, how to translate it. Otherwise we cannot expect them to translate it as such…

**Comment by ServusWorld** [comment]
So may I simply add `...` to the German translation in POEditor?

**Comment by rugk** [comment]
(Although I'd prefer the – proper – unicode symbol `…`.)

**Comment by ServusWorld** [comment]
Oh yes, of course! :)
