### ISSUE TITLE
Author is out 1-2 weeks

### ISSUE THREAD

**Issue by westnordost** [westnordost/StreetComplete#564]
Hey guys, I will not be online for the next 1-2 weeks.

When I am back, I will finalize version 2. Missing still is a final polishing of the compass/follow-me mode and merging the PR about the landscape UI. After that, only bugfixes will go into version 2. So, if you want to see your feature / quest in that version, make a PR until I am back ;-)

**Comment by rugk** [comment]
Oh wow, what crazy tagging… :laughing: 

Happy holidays (as I assume)! …and maybe map one thing or two wherever you are. :smiley:

**Comment by westnordost** [comment]
No holiday, but it has been postponed now.
