### ISSUE TITLE
support surface=metal

### ISSUE THREAD

**Issue by matkoniecz** [westnordost/StreetComplete#568]
I am not sure what is better - putting it with image together with other paved values, adding separate category for weird values or putting it into "Can't say" menu.

Obviously, another option is ignoring it like it is currently done, but at least I am irritated now by tagging surface=metal as it requires: 

- creating note
- later locating it in JOSM
- closing note
- finally adding proper tag

**Comment by matkoniecz** [comment]
@westnordost What is your opinion on this? What option is preferable for you?

**Comment by rugk** [comment]
Accordig to [taginfo](https://taginfo.openstreetmap.org/keys/surface#values) metal is quite rare. (8 092
0.04%)
But is belongs to one of the last values, which might be useful in some cases.

The same for the tag `concrete:lanes`, which may at least be popular in Germany. 
BTW both belong into the "paved" category according to the wiki.

`grass_paver` is also something I've often seen in Germany, at least.

**Comment by matkoniecz** [comment]
> Accordig to taginfo metal is quite rare. (8 092 0.04%)

Maybe, but at least for me need to enter it it happened multiple times, in different places (even in different countries).

**Comment by matkoniecz** [comment]
Ping @westnordost what is your preference?

Putting surface=metal image together with other paved values?

Adding separate category for weird values?

Putting it into "Can't say" menu?

Obviously, another option is ignoring it like it is currently done, as it is a quite rare value, but at least I am irritated now by tagging surface=metal as it requires:

    creating note
    later locating it in JOSM
    closing note
    finally adding proper tag

And it is rare but it regularly happens.

I would make a PR, so I prefer to know what is the preferable design before starting coding (personally, I think that adding is a new paved value is preferable).

**Comment by westnordost** [comment]
Ok.

You can move grass_paver in paved as well, if you think this fits better.

**Comment by matkoniecz** [comment]
I plan on using https://commons.wikimedia.org/wiki/File:Slip_resistant_metal_tread.jpg as an image.

**Comment by westnordost** [comment]
Sure
