### ISSUE TITLE
Notes don't show up if created by user, even if externally

### ISSUE THREAD

**Issue by dbdean** [westnordost/StreetComplete#569]
When I add notes while doing 'armchair mapping', or when I notice a problem that requires a survey to fix (housenumbers in a weird order, etc.), they don't show up in StreetComplete, no matter what settings I choose.

Looking at makeNoteClosed in app/src/main/java/de/westnordost/streetcomplete/data/osmnotes/OsmNotesDownload.java, it looks like If I have a comment on a note (which I guess includes the creation comment), it won't show up.

I understand this is an issue so that quests I left notes on don't show back up in StreetComplete, this happens for notes I create on the website and from within JOSM too.

In thinking through the scenarios, I think the following could happen:

1. Anyone (_including myself_) creates a note externally to StreetComplete: **these should show up**
2. Anyone (_including myself_) creates a note, and I answer it in StreetComplete: **these shouldn't show up**
3. A note is created by myself (and maybe anyone else?) using StreetComplete can't say feature: **these shouldn't show up**.
4. A note that I have answered in StreetComplete has another comment added since answering in StreetComplete: **unsure what should happen**?

It seems to me a more sensible logic should be 'Was the last comment on the note created by StreetComplete (and then maybe was it also from the current user)?' which could be checked by looking for the string 'StreetComplete'.

Alternatively, is it possible to add metadata to OSM Notes to make this more robust? I couldn't find a clear indication on the OSM API page which doesn't seem to actually outline the notes data format.

**Comment by westnordost** [comment]
> Alternatively, is it possible to add metadata to OSM Notes to make this more robust?

No it isn't possible

To summarize, your feature request is to change the logic when notes show up to:
`show if note is a question and either I did not comment on it at all yet or I created the note not via StreetComplete`
Correct?

**Comment by dbdean** [comment]
Should notes created by StreetComplete be shown, even if created by a different user? If I couldn't answer it on site, would another StreetComplete user be able to?

I think a sensible logic might be: `show note if (it is a question and) it doesn't have any comments (including initial creation) by StreetComplete`. The creator of the note needn't come into it.

I'm not sure if additional comments from StreetComplete indicate that StreetComplete was used, so we might need to add something to the comment so we can perform this test on future notes. (maybe a #streetcomplete hashtag?)

**Comment by dbdean** [comment]
Of course, occasionally I will take a comment I created in StreetComplete, look at the aerial imagery, and add a comment like "It looks like it might be accessible from Blah St.", so it would be nice if the comment showed up then.

So, maybe an even better logic would be `show note if (it is a question and) the last comment (including initial creation) wasn't created by StreetComplete`.

**Comment by matkoniecz** [comment]
> show note if (it is a question and) the latest comment (including initial creation) wasn't created by StreetComplete.

AFAIK it is impossible to check whatever comment was made by SC.

**Comment by dbdean** [comment]
Yes, I agree, that is why we would need to modify the comment-reply feature to add something that will identify it as a StreetComplete comment reply (such as a #streetcomplete hashtag perhaps, or just prepend 'Replied using StreetComplete: ' to whatever is put in the comment-reply field in StreetComplete.

**Comment by rugk** [comment]
> I modified my SC fork to completely eliminate note filtering and show all of them. Maybe that would be a desirable option for expert mode in SC?

Is not that what the checkbox in the settings to allow to see all notes, does?

Generally, what is the current behavior when described in the same way you did earlier? Do I think correctly that it is `show note if, it is a question`? (when the checkbox in the settings is *not* ticked, obviously)

**Comment by westnordost** [comment]
> Should notes created by StreetComplete be shown, even if created by a different user? If I couldn't answer it on site, would another StreetComplete user be able to?

If it is a question: yes. Imagine a note like this: "Not sure what kind of paving this is. Is this rather compacted or fine gravel?". Generally, I'd say that questions can be assumed to often (enough) be directed at (other) surveyors, independent of in which app they have been added.

I also don't want to add a hashtag to every comment, really.

I will change the logic to:
_show (if note is a question and) I did not **comment** on it yet - creating, closing or reopening a note does not count as a comment_

This should cover your use case of creating notes at home to answer them yourself during your own survey.

**Comment by matkoniecz** [comment]
> Is not that what the checkbox in the settings to allow to see all notes, does?

No, it still hides notes that I created or where I commented. I wanted to see also notes that I created (nearly all of them are request to verify something by a survey) and commented (ones that are still open are typically where I asked for a clarification).

**Comment by rugk** [comment]
> I also don't want to add a hashtag to every comment, really.

It is really not bad and very common for apps like Maps.me… They do it all the time and as a mapper you then at least know, with which app the comment was made.

~But if you do not add a hashtag how do you check the condition "I created the note but not via StreetComplete"?~ Ah, just saw [your implementation](https://github.com/westnordost/StreetComplete/commit/75446db7906324f65f32bb6efa28c0f0037dd664#diff-a0718887593389e99815e591c0f650c4R187), which just checks for "via StreetComplete", so basically you know have this hashtag. (it works the same) :+1:
