### ISSUE TITLE
Multi selection of quests

### ISSUE THREAD

**Issue by bobatsar** [westnordost/StreetComplete#57]
I see that there are a lot of quests about the street surface. Very often nearby elements have the same surface.

Would it be possible to answer multiple quest of the same type at the same time with a kind of multiselection for the quests?

**Comment by Natenom** [comment]
+1

**Comment by westnordost** [comment]
This is quite an advanced feature. I fear this is not on my radar at all yet.

**Comment by westnordost** [comment]
So, I'll close this for now. Such expert editor features are not planned at all yet. Let's see how the app looks in one year.
