### ISSUE TITLE
New quest: Add operator for old clothes container

### ISSUE THREAD

**Issue by rugk** [westnordost/StreetComplete#570]
### General
Affected tag(s) to be modified: [operator](https://wiki.openstreetmap.org/wiki/Tag:operator)
Question asked: **What is the operator of this recycling container?**

### Checklist
Checklist for quest suggestions (see guidelines):
- [x] 🚧 To be added tag is established and has a useful purpose
- [x] 🤔 Any answer the user can give must have an equivalent tagging (Quest should not reappear to other users when solved by one)
- [x] 🐿️ Easily answerable by everyone from the outside (mostly written on the outside of the container, if not container company is dubious anyway)
- [x] 💤 Not an overwhelming percentage of elements have the same answer (No spam)
- [x] 🕓 Applies to a reasonable number of elements (Worth the effort) (According to [taginfo](https://taginfo.openstreetmap.org/tags/?key=amenity&value=recycling#combinations) 40 914 elements are tagged with `amenity=recycling` and `recycling:clothes`)

**Purpose:** Sometime dubious companies setup containers ([see here](https://www.ndr.de/ratgeber/verbraucher/Altkleider-Sammlung-Container,altkleider194.html), German) and people may want to find containers from organizations they trust, as otherwise their clothes may not actually be recycled or so…

### Ideas for implementation

**Element selection:** All `amenity=recycling` with `recycling:clothes=yes`, i.e. only include cloth recycling containers

**Metadata needed:** Yes, common companies/organizations per country (or are they mostly international?)

**Proposed GUI:** Just an input field, with a suggestion for possible/common entries; similar to the street name quest

Technically this quest is BTW very similar to https://github.com/westnordost/StreetComplete/issues/203.

**Comment by ENT8R** [comment]
I did now the same what I did for #203 also for this quest and the full list of operators sorted by country can be found at https://gist.github.com/ENT8R/caee56398b1b8225f9ed196290818696

**Comment by rugk** [comment]
BTW as for Germany I even found a detailed wiki guide: https://wiki.openstreetmap.org/wiki/Deutsche_Altkleider-Container_Betreiber

**Comment by rugk** [comment]
Also important for this quest:
> Bitte die Unternehmensform weglassen: also bspw. "Deutsches Rotes Kreuz" anstatt "Deutsches Rotes Kreuz e.V.".

I.e. you should leave out the company registration information (i.e. "Cooperation/…").

https://wiki.openstreetmap.org/wiki/DE:How_to_map_a#Altkleider-Container

**Comment by westnordost** [comment]
Using the same method as for operators of ATMs, we should create a list of popular operators by country for auto-completion. Also, probably an `operator:signed=no` option must be added for cases where it is not signed. (We could start without that option and see if many notes pop up)

**Comment by wurzel-3** [comment]
>Also, probably an `operator:signed=no` option must be added for cases where it is not signed. (We could start without that option and see if many notes pop up)

This would be quite useful, since i encountered some containers which where not signed. Dubious origin of the containers aside, it generates a lot of notices from unexperienced Streetcomplete users when encountering this situation.

**Comment by matkoniecz** [comment]
Can you make a new issue for that? In general, posting in old closed issues can be easily missed
