### ISSUE TITLE
Deprecated quests are still asked after upgrade

### ISSUE THREAD

**Issue by HolgerJeromin** [westnordost/StreetComplete#573]
In the last update some quests have changed 

> Don't ask for house numbers inside an area with a housenumber (i.e. schools etc.)

I have such objects in my cache which are still shown. 
Imo such quests should be cleared after upgrade.

**Comment by matkoniecz** [comment]
Quests should disappear once cache time outs (IIRC it is set to one week).

**Comment by westnordost** [comment]
See @matkoniecz

**Comment by HolgerJeromin** [comment]
Still waiting for the timeout. :-(

**Comment by rugk** [comment]
After 12 days this should certainly work. Also, in previous versions, you could configure the cache time… (Wonder why it has been removed…)

**Comment by westnordost** [comment]
#562 

Basically, I have no clue.
