### ISSUE TITLE
New Quest: Do these traffic lights have a button?

### ISSUE THREAD

**Issue by hsimpson00** [westnordost/StreetComplete#574]
Hi, this is a series of new possible Quests to give more details for pedestrian traffic signals. Since there are already quests for these crossings, it shouldn't be hard to implement these (I'm not a programmer, but I guess so).
The point is, that it's a good thing for disabled, especially blind people, to now, if the traffic light is button_operated, has a sound, etc. But these informations are very rare on OSM, because you don't notice them as a normal person.

Necessary Tags on the Node:
_highway=crossing_ + _crossing=traffic_signals_
Sould also work for:
_highway=traffic_signals_ + _crossing=traffic_signals_

### General
Affected key(s) (or tags) to be modified: _button_operated=yes/no_
Question asked: _Is this crossing button operated?_

Affected key(s) (or tags) to be modified: _traffic_signals:sound=yes/no_
Question asked: _Are there sound signals for visually impaired people?_

Affected key(s) (or tags) to be modified: _traffic_signals:arrow=yes/no_
Question asked: _Is there a tactile arrow available at the traffic light pole? (mostly unter the button)_

I think these are the most common supports for blind people at traffic signals, the other ones are too rare to make an own quest for them.

### Checklist
Checklist for quest suggestions (see guidelines):
- [x ] 🚧 To be added tag is established and has a useful purpose
- [x ] 🤔 Any answer the user can give must have an equivalent tagging (Quest should not reappear to other users when solved by one)
- [x ] 🐿️ Easily answerable by everyone from the outside
- [x ] 💤 Not an overwhelming percentage of elements have the same answer (No spam)
- [ x] 🕓 Applies to a reasonable number of elements (Worth the effort)

**Comment by rugk** [comment]
Also `traffic_signals:vibration` could be nice/useful. It is strongly correlated to `traffic_signals:arrow=yes/no` as it is the same place. So with a simple image you can also point user, who have never heard about that to the position "under the button" (as you said).

AFAIK it is quite common in Germany, I've actually never heard of the arrow, but I'll take a ~look~ touch next time whether it is just the button or there is really an arrow.

**Comment by rugk** [comment]
Okay, so maybe `traffic_signals:arrow` and `traffic_signals:vibration` is often combined. (And BTW, they should of course only be asked if the crossing is `button_operated=yes`) I mean combing them makes the most sense…

**Comment by hsimpson00** [comment]
> And BTW, they should of course only be asked if the crossing is button_operated=yes

+1

I didn't know that vibration is used that open. The only problem I can see is, that it's maye not that obvious to find out.

> I mean combing them makes the most sense…

I would seperate the questions, but make them dependent of each other:
-Arrow only if button=yes
-vibration only if arrow=yes

**Comment by rugk** [comment]
Yeah, maybe. For vibration you just have to press the button at the bottom (the one with the arrow). And both the arrow and the vibration need an image showing the user where to press/touch.

**Comment by hsimpson00** [comment]
Hi,
I have to correct myself:
Of course, there are Traffic signals which are not button operated, but do have an arrow, sound and so on.
These devices (the newer ones) naerly look the same as the normal buttons, but they don't have a touch sensor and also no display. Instead they are only yellow withe the three black dots which mark the Infrastructure for blind people.
Regards

**Comment by rugk** [comment]
> Instead they are only yellow withe the three black dots which mark the Infrastructure for blind people.

Yeah, *of course*… That's the thing nearly everyone "pressed", because one thinks it goes faster, then… :wink: :laughing:

**Comment by matkoniecz** [comment]
> Is there a tactile arrow available at the traffic light pole? (mostly unter the button)

Can you give an example photo? I have no idea what is described here.

> Not an overwhelming percentage of elements have the same answer (No spam)

Where `traffic_signals:sound` would not be overwhelmingly no? Maybe ask only for major roads, maybe only in some countries...

**Comment by ENT8R** [comment]
I found the following picture:
![Traffic light button](https://i1.wp.com/digitalcosmonaut.com/wp-content/uploads/2013/10/Verdeckter-Druck-Taster-ampel-german-traffic-light-berlin-secret-button.jpg?resize=768%2C510&ssl=1)
The button is also explained in the following article: https://digitalcosmonaut.com/2013/berlin-traffic-lights-youre-using-wrong/
And it seems like it is a thing which exists only in Germany...

**Comment by goldfndr** [comment]
I've seen some newer pelican crossings here in the US where the large pushbutton had a large embossed arrow on it indicating the direction of travel; I don't have a photo, sorry. The older pushbuttons are a bit less than fingernail size, not the best feel for pushing.

**Comment by goldfndr** [comment]
Here are a couple of snapshots I took today.

![overview](https://user-images.githubusercontent.com/173956/42730839-21bb8404-87b5-11e8-93c7-392ecca14b55.jpg)
![closeup](https://user-images.githubusercontent.com/173956/42730843-33e68958-87b5-11e8-9369-41d94466ba81.jpg)

**Comment by matkoniecz** [comment]
I started testing one of ideas from this issue - adding traffic_signals:sound tag in #1268 

I see no real value in collecting button_operated as there is no easy way to check what exactly the button is doing. In many cases buttons are left as placebo/to save money necessary to remove them despite that pressing button is changing nothing.

**Comment by rugk** [comment]
> In many cases buttons are left as placebo/to save money necessary to remove them despite that pressing button is changing nothing.

"[citation needed]" :wink: At least this is the first time I hear this, but nevertheless, I agree with your conclusion and guess the "sound" thing is really the most important value.

**Comment by matkoniecz** [comment]
https://www.nytimes.com/2016/10/28/us/placebo-buttons-elevators-crosswalks.html

https://www.citylab.com/life/2015/09/ask-citylab-do-walk-buttons-actually-do-anything/400760/

https://www.forbes.com/sites/lauriewinkless/2017/10/27/does-pushing-the-button-at-a-crossing-actually-do-anything/#825548640107

https://www.bbc.com/news/magazine-23869955

Googling may reveal more - here is my search https://duckduckgo.com/?q=button+press+traffic+crossing+nothing

**Comment by westnordost** [comment]
I read the last article you linked. After reading, it is clear that surveyors will have to survey what they find on the ground - **whether there is a button or not**. It is not really possible to find out how exactly or if at all and at what times the button does anything, because it is software controlled. So even if the exact behavior can be found out, it may change at any time in the future. Same thing with street lamps - that's why we survey if there are street lamps or not, not if they are on during all the night.

So, this ticket is now about **button_operated**. I agree that the rest can be ignored.

**Comment by rugk** [comment]
Don't know though whether the information "button_operated" does provide any real enhancement to the OSM data/has a use case. I mean the other things are obviously about accessibility, but whether I can press a button – is this something I care about as a blind or not blind user – I doubt so?

**Comment by westnordost** [comment]
Button operated traffic lights at crossings can be counted as less of an obstruction for routing algorithms

Am 20. November 2018 17:40:03 MEZ schrieb rugk <notifications@github.com>:
>Don't know though whether the information "button_operated" does
>provide any real enhancement to the OSM data/has a use case. I mean the
>other things are obviously about accessibility, but whether I can press
>a button – is this something I care about as a blind or not blind user
>– I doubt so?

**Comment by call-me-matt** [comment]
Hi there. Good idea, useful addon! Concerning sounds, should this distinguish between yes, walk, and locate as described in the [wiki](https://wiki.openstreetmap.org/wiki/Key:traffic_signals:sound)?

**Comment by matkoniecz** [comment]
If you think that it is necessary - please open a new issue with https://github.com/westnordost/StreetComplete/issues/new , comment like this may be easily missed.

**Comment by call-me-matt** [comment]
> If you think that it is necessary - please open a new issue with https://github.com/westnordost/StreetComplete/issues/new , comment like this may be easily missed.

OK, [done](https://github.com/westnordost/StreetComplete/issues/1300)
