### ISSUE TITLE
Opening hours quest - include "place no longer exists" option 

### ISSUE THREAD

**Issue by DaCor1** [westnordost/StreetComplete#575]
Similar functionality to maps.me

I've spotted a number of mapped places /amenities during the opening hours quest, that no longer exist. 

Suggest adding an option under "Other Answers" for places that have shut down. 

It would be great if this automatically added a note to osm. 

Sorry I can't do code, I'm not a coder

**Comment by westnordost** [comment]
You can answer "Can't answer" and then describe why not (i.e. "does not exist anymore, there is now X")

**Comment by DaCor1** [comment]
While that's true, it's not at all intuitive.

**Comment by rugk** [comment]
This is a duplicate of https://github.com/westnordost/StreetComplete/issues/450. See there for details.
