### ISSUE TITLE
Street name/traffic signals in Japan

### ISSUE THREAD

**Issue by rugk** [westnordost/StreetComplete#576]
I just saw [this note](https://wiki.openstreetmap.org/wiki/Tag:highway%3Dtraffic_signals#Named_traffic_signals.2Ftraffic_signal_systems_.28Japan..._.29):
> In some countries (such as Japan), people orient themselves in the local area using the names of traffic signals or traffic signal systems rather than the names of streets. While street names may also exist, they are less important for orientation. See “[Named spots instead of street names](https://wiki.openstreetmap.org/wiki/Named_spots_instead_of_street_names)” for details. Note that Korea and Nicaragua used named intersections, but these are tagged as junction=yes and reference_point=* respectively, not highway=traffic_signals. 

So you may rethink (maybe blacklist?) the streetname quest. And you may think about asking for junctions/traffic signals there, instead or so…

**Comment by matkoniecz** [comment]
From looking at random spot in Japan - street names are existing there (I ended at http://www.openstreetmap.org/#map=18/38.25608/140.87974)

> While street names may also exist, they are less important for orientation

mentions that street names still may be used

**Comment by rugk** [comment]
Yeah, sure, but at least a high number of false-positives/unanswerable quests may be created there as some/a lot(?) street do not have a name(?). If you e.g. look at bit to the right ([here](https://www.openstreetmap.org/#map=18/38.25407/140.88775)) you'll see there are no street names at all… although it could of course also be mapped badly)

**Comment by westnordost** [comment]
Tgen it is equally important to record that they don't have names, if they have no names
