### ISSUE TITLE
Do not ask for building:level when building:part exists

### ISSUE THREAD

**Issue by sb12** [westnordost/StreetComplete#579]
Often it is not as simple as adding a `building:level` to buildings, because e.g. there are different number of levels for different parts of a building.
This cases are mapped with [`building:part`](https://wiki.openstreetmap.org/wiki/Key:building:part). To prevent users adding `building:level` to these buildings or opening unnecessary notes, buildings that contain `building:part` elements should be ignored by the app.

**Comment by rugk** [comment]
Could not it also ask the "house quests" for each `building:part`?

**Comment by rugk** [comment]
Ah, and BTW from the wiki:
> Where a building has been split into parts, the whole building way should still have the tags building:levels=* and height=*. These values should be the maximum of all the building parts.

**Comment by westnordost** [comment]
See @rugk

**Comment by rugk** [comment]
Yes, **but** the app does not state that. I.e. I did not know that "in case this building has multiple levels, specify the highest one".
Also, in the app it would in such a case still be useful to leave a note, as the "correct" mapping cannot be done in the whole app.
