### ISSUE TITLE
Option to disable zoom in on quest selection

### ISSUE THREAD

**Issue by Natenom** [westnordost/StreetComplete#58]
Currently when solving many quests at once I need to:
1. Select quest; map zooms in
2. Answer quest
3. Zoom out manually to see the whole area instead of a street only, then go to 1.

If would help if I could disable the zoom in.

**Comment by westnordost** [comment]
Why do you want to see the whole area?

What if the app zoomed back to the previous position after answering the quest?

**Comment by Natenom** [comment]
Not the whole area but a bit more than just one short street in maximal zoom.

Zooming back to the previous position would be the best option.

**Comment by westnordost** [comment]
I'd rather not implement an option but get the UX right in the first place. (So that there is no need to customize it.)

The zoom logic currently is:

```
		controller.setPositionEased(zoomTo, 500);
		if(controller.getZoom() < 19)
		{
			controller.setZoomEased(19, 500);
		}
```
I could change it so that it only zooms in if the zoom level is very low. I.e. it zooms to 19 if the zoom level is smaller than 17. I will try that.

**Comment by westnordost** [comment]
Hab mal einiges ausprobiert, so fühlt sich das jetzt am besten an, finde ich. Zur alten Position (also nicht nur Zoom) zurückzukehren, fühlt sich sehr komisch an, aber Zoom (eingeschränkt) ist okay.

**Comment by Natenom** [comment]
This is better, thank you.

**Comment by fnordson** [comment]
Also ich weiß nicht. Ich fände es angenehmer wenn sie überhaupt nicht zoomen würde sondern da bleibt wo man war als man draufgetippt hatte. 
Im Moment hat es noch den Vorteil, dass Aufgaben auftauchen die man in einer anderen Zoomstufe nicht gesehen hatte. Das hatte aber jemand schon irgendwo als Issue markiert.

Ansonsten nutze ich die Stelle nochmal um ein großes DANKE auszusprechen. 
Ich freue mich immer etwas beizutragen aber habe bei solchen komplexen System Angst Mist zu bauen. Solche Apps wie deine sind perfekt dafür. Habe sie schon Freunden weiterempfohlen :)

**Comment by Natenom** [comment]
Bei Straßen ist es eher schlecht, wenn reingezoomt wird, weil man dann erst selbst wieder herauszoomen muss, um zu sehen, welcher Teil der Straße gemeint ist.

**Comment by westnordost** [comment]
Hmm, so I will open this again. Apparently this needs some more discussion and/or adjusting.

**Comment by C0RD** [comment]
Maybe just setting a default zoom value in the settings would help?

**Comment by zxmon21** [comment]
"zoom to a level so that it completely encompasses the element. (I.e. zoom out a bit for streets if the street is larger etc)."

That sounds great. And return to previous zoom after ok
