### ISSUE TITLE
Change order of "north is up" and "compass mode" when GPS-mode is on?

### ISSUE THREAD

**Issue by Natenom** [westnordost/StreetComplete#580]
When clicking the "north" icon when nort is not up and GPS mode is off then the map aligns to "north is up".

Doing the same when GPS mode on it changes to "compass mode", after another click to "north is up".

I would expect it on the first click to do "north is up" and then "compass mode".

**Comment by westnordost** [comment]
Yeah that's how I implemented it initially but during testing, it did not feel good, so I made it how it is now.
