### ISSUE TITLE
New Quest: GNIS Schools (US)

### ISSUE THREAD

**Issue by mvexel** [westnordost/StreetComplete#583]
### General
This quest is currently impossible because you can't delete things using SC. Still, if that ever becomes possible, this might be a nice one.

Question asked: **Does a school exist at this location?**

In the US community, we are currently developing a MapRoulette challenge for validating an old import of school locations in MapRoulette. You can find the challenge [here](http://maproulette.org/map/2774).

The instruction on MapRoulette is: 

> The highlighted feature represents a school location from the GNIS import. Please verify if a school exists at the location using available aerial imagery. If there is clearly no school building, delete the node. If there is a school, draw the building outline and copy the relevant tags over to the outline. If it is a large school complex, you can also map the entire school grounds and copy the relevant tags to that area, and map the school building within it just as building=school. Please also add other details like sports facilities, parking lots, service roads as you observe them.
> 
> Much more information on mapping schools is available on the OSM wiki.
> 
> As always: if you’re not sure, just skip the task.
> 
> 

StreetComplete could help by focusing on just deleting non-existing shools (which are many).

Let me know when deleting becomes possible and we can work on it some more.

**Comment by westnordost** [comment]
So, this is only relevant for US, right?

The quest as you imagine does not work, though. Deleting would actually not be the problem but what should be done for when the user confirms that there is a school. What should happen then?

**Comment by mvexel** [comment]
This would be relevant specifically for the United States, yes.

In my opinion -- but I don't know very much about the internals of SC or what it can or cannot do -- the question should simply be 'Is there a school 'NAME' at this location?'. If the user taps 'no' then the node gets deleted. If the user taps 'yes' a number of things could happen, for example: add a tag `gnis:reviewed=yes` (similar to `tiger:reviewed=yes` which is already in use), or just mark it as done in the SC internal database and leave the node alone.

A second layer of questions is possible, to confirm the name: 'Is the school at this location named 'NAME'? Yes --> Leave node alone No --> Ask for correct name, update OSM. But our initial priority would be to delete the non-existent schools (of which there are probably thousands!)

**Comment by HolgerJeromin** [comment]
👎 for `reviewed` tags. Is there a way to detect that the node is from the import?

**Comment by mvexel** [comment]
@HolgerJeromin yes there is a way (`gnis:feature_id` tag, see [TagInfo](https://taginfo.openstreetmap.org/keys/gnis:feature_id) - not all of these are schools). 

The `reviewed` tags are not ideal, I agree, but they are a reality in the US and people are used to them. There is a JOSM paint style to highlight them to encourage people to look at them and remove. We can also always clean them up later with a mechanical edit.

**Comment by HolgerJeromin** [comment]
Ok fine. What about searching all nodes with
gnis:feature_id= and
amemity=school
 and when this school exists remove the gnis:feature_id tag :)

**Comment by mvexel** [comment]
@HolgerJeromin that sounds like a good approach to me!

**Comment by westnordost** [comment]
Okay, that'd work

**Comment by dericke** [comment]
Is it a good idea to remove foreign keys from features, especially from a data source so notable as a national government? It seems that it would be better to preserve the keys. The OSM wiki page about GNIS suggests that these keys are important.

**Comment by westnordost** [comment]
I reviewed this again, I am going to close this as will not fix because:
- I found only this MapRoulette challenge: https://maproulette.org/browse/challenges/4047 - this is about 2000 objects, that is really not worth the effort and **very** local - just West Virginia. I think MapRoulette is the better tool for such kind of local import fixing
- see @dericke 
- The nodes in the challenge are additionally somewhat scattered around the country. SC is a tool aimed at pedestrians/cyclists, it would not be very efficient to try to solve these on a survey rather than looking at aerial imagery.

**Comment by matkoniecz** [comment]
Note that https://www.openstreetmap.org/node/356527007 https://www.openstreetmap.org/node/356530213 and many others are already deleted by https://wiki.openstreetmap.org/wiki/Mechanical_Edits/Mateusz_Konieczny_-_bot_account/remove_objects_that_are_not_existing_according_to_source_of_import_that_added_them
