### ISSUE TITLE
Improve UI for entering shops times

### ISSUE THREAD

**Issue by Phyks** [westnordost/StreetComplete#586]
Hi,

I was wondering whether we could improve the UI layout for the "shops times" quest. The main issues I see are:

* Opening and closing times are not on the same page, but in different tabs, then requiring one extra click. However, I think there could be room for both of them to fit inside the same tab.
* The time "wheel" to select minutes display all possibilities, from 1 to 59. It's very rare that a shop closes at some hour 54 minutes for instance, they would rather open and close according to multiple of 15. Then, we could display only 0, 15, 30 and 45, so that the selection would be way faster in these cases. Sure, we should need another way to enter precise exact values, such as "54".

This would allow to enter opening and closing times way faster, and this quest has been one of the most time consuming I have tackled so far :)

Also, the UI can be misleading about the proper way to enter data. Say I am facing a shop with following schedules:

> Mon-Fri : 8am-12am, 2pm-6pm
> Sat : 8am-12am

I usually add in this order:
1. "Mon-Fri", "8am-12am"
2. "Mon-Fri", "2pm-6pm"
3. "Sat", "8am-12am"
which gives me the same UI output as the one I am facing on the shop sign.

However, it seems that I could be more efficient and enter:
1. "Mon-Sat", "8am-12am"
2. "Mon-Fri", "2pm-6pm"

This would describe the same schedules, but the UI render them differently. Not sure if there is a reason behind that. Otherwise, I'll suggest collapsing the Saturday entry in my first example, to have the same render with both inputs.

Sorry for the long issue :/ Thanks a lot for all the work you are putting in StreetComplete, this is awesome! :)

**Comment by rugk** [comment]
> However, I think there could be room for both of them to fit inside the same tab.

On tablets, but not on phones. On phones the width is so sparse, only one clock fits there.

As for the other issue I've already asked about it in https://github.com/westnordost/StreetComplete/issues/320.

> "Mon-Fri", "8am-12am"
> "Mon-Fri", "2pm-6pm"

That is completely okay, and I would not suggest to enter it otherwise. And I really won't calculate the times in another way as you suggested.

Maybe you could change the UI, however, in a way to indicate that entering different times for the same day (span) is okay. Just like OsmAnd does it:
![osm](https://user-images.githubusercontent.com/11966684/30065121-2edcc230-9254-11e7-8bf9-fea84d8f2b05.png)

**Comment by Phyks** [comment]
> On tablets, but not on phones. On phones the width is so sparse, only one clock fits there.

I was thinking about having two clocks in a column, one on top of the other. Should be fitting on my phone (Fairphone FP1, not a huge screen).

> As for the other issue I've already asked about it in #320.

Indeed, I missed #320, my bad :/ My issue was about the Saturday though, having:

> Mon-Fri : 8am-12am, 2pm-6pm
> Sat : 8am-12am

vs

> Mon-Sat : 8am-12am
> Mon-Fri : 2pm-6pm

Would you have an english version of your screenshot? I don't speak german :/ Thanks!

**Comment by rugk** [comment]
The German text in the screenshot hardly matters, just look the the times. I meant that the Mo-Fr times are grouped together, but mhh…

Reading your example again, I now see what you mean. Giving the time is repeated for all days and only one day has a different time (after the siesta :wink:). Okay, but how would you change the UI?

**Comment by rugk** [comment]
BTW yust saw the UI is very similar too OsmAnd [from this screenshot](https://github.com/westnordost/StreetComplete/blob/master/metadata/en/images/phoneScreenshots/screenshot5.png). I like that UI, however…

**Comment by Phyks** [comment]
> Reading your example again, I now see what you mean. Giving the time is repeated for all days and only one day has a different time (after the siesta 😉). Okay, but how would you change the UI?

Indeed, my true issue about it is: should I enter

> Mon-Sat : 8am-12am
> Mon-Fri : 2pm-6pm

(grouping by time slots)

or

> Mon-Fri : 8am-12am, 2pm-6pm
> Sat : 8am-12am

(grouping by day)

I write this from a user perspective (without much knowledge about OSM internals, and absolutely no knowledge about StreetComplete internals). I am not sure if both ways are valid OSM schedules or if one should be preferred to the other. Two cases:

1. The two schedules are identical from a OSM coding point of view. Then, I would tend to say it does not matter and people will just write what fits best for them. At best, there could be some hint or some doc somewhere explicitly stating that both are correct and that's all.
2. There is a preferred way of writing it. Then, I think it is easy for StreetComplete to handle the conversion itself between the formats and notify the user something like "the schedule you entered is not in the usual OSM format, we converted it automatically, please check this is correct".


P.S. : Sorry if my first example was not super clear :/

**Comment by westnordost** [comment]
It's 1, basically.

Personally, I would always write it like it is written on the sign.

I do not want to add the "ADD HOURS" button again (for now).

**Comment by Phyks** [comment]
Ok.

What about the other points in the original post? Thanks!

> * Opening and closing times are not on the same page, but in different tabs, then requiring one extra click. However, I think there could be room for both of them to fit inside the same tab.
> * The time "wheel" to select minutes display all possibilities, from 1 to 59. It's very rare that a shop closes at some hour 54 minutes for instance, they would rather open and close according to multiple of 15. Then, we could display only 0, 15, 30 and 45, so that the selection would be way faster in these cases. Sure, we should need another way to enter precise exact values, such as "54".

**Comment by westnordost** [comment]
1. No, there isn't
2. This is a default Android component, I can't change this.

**Comment by westnordost** [comment]
>1.

Except in landscape mode, there'd be. Are you referring to that?

**Comment by westnordost** [comment]
You are using quite an old Android phone. For Android 5 and above, the default time picker looks like this:
https://neurobin.org/docs/android/android-time-picker-example/img/s1_2.png

**Comment by Phyks** [comment]
Indeed, my phone is stuck at Android 4.2.2. Is there a way to backport the default time picker for Android 5+ to all the Android? It seems some apps are doing it as I already came across this time picker. Now I get your remarks about missing space :)

**Comment by westnordost** [comment]
Technically, there is always a way, somehow. Everything boils down to effort vs gain. And if it is imbalanced somewhat, I prefer to say, that it is not possible. Android 4 is soon to be deprecated as well, I give it another 1-2 years, then apps will increasingly become incompatible with Android 4 altogether.

**Comment by Phyks** [comment]
Ok, I get the point. Too bad, I should really find a way to upgrade to Android 5+ :/ Thanks for all the input!

**Comment by rugk** [comment]
What about [LIneageOS](https://lineageos.org/)? It is available for most devices, even some older ones.

**Comment by Phyks** [comment]
Sadly, not an option :( I own a Fairphone 1, and it is not supported :/
