### ISSUE TITLE
Need an UI too see the pending answers

### ISSUE THREAD

**Issue by afmenez** [westnordost/StreetComplete#588]
Currently the UI shows the number of answers I have filled so far, but not how many are pending synchronization.

**Comment by rugk** [comment]
It does. This is the "(+x)" part in "100(+x)"…

**Comment by afmenez** [comment]
Hum, never seen this.  I'll check my configuration.

**Comment by rugk** [comment]
Maybe you have "auto-upload" enabled. In this case, the answers are of course uploaded very fast and you may not see it.

**Comment by afmenez** [comment]
Yep, that was it.  Thanks.
