### ISSUE TITLE
Make it easier to change the app ID

### ISSUE THREAD

**Issue by rugk** [westnordost/StreetComplete#591]
Contributors may want to install a dev version of your app besides the stable version downloaded from another source. As users may develop "just" a new quest they may not wish to uninstall the stable StreetComplete version, but just temporarily install a dev version on their device.
Thus, they may want to change the app ID.

I, however, had some issues as the settings seem to use this ID somehow (the custom minValue/maxValue). When I removed them, it worked, but I think this is not how it should be.

Maybe you could also add it as a built flavour/type or so…
The best would be if the app name is also changed ("StreetComplete dev" or so), but that's just nice-to-have.

**Comment by westnordost** [comment]
I've no idea how to achieve this though. Needs some research.

**Comment by MrSunday334** [comment]
it seems to work if you also change the value of "xmlns:custom=" in preferences.xml

This way you have at least not to remove the values.
