### ISSUE TITLE
3d rendering of some buildings fails

### ISSUE THREAD

**Issue by rugk** [westnordost/StreetComplete#592]
On particular building fails to render in the 3d mode. When rotating/moving it flickers between grey and this type of brown:
![color](https://user-images.githubusercontent.com/11966684/30444437-42966534-9983-11e7-8946-b73287927634.png)

I can send you a video and the place where it happens via mail.

Or is this a tangram issue only?

Version: a59f0fcd813c0acfae3191fcd0b6c3a8311c5f5c

**Comment by westnordost** [comment]
This'd be either bug of [tangram-es](https://github.com/tangrams/tangram-es) or of the style used here, [cinnabar](https://github.com/tangrams/cinnabar-style).

You'd better start by checking whether the render problem you observe also appears in the [cinnabar web demo version](http://tangrams.github.io/cinnabar-style/#15/37.7926/-122.4003), if yes, report it as an issue in the cinnabar-style, if not, report it as an issue in tangram-es (I'd say).

**Comment by westnordost** [comment]
(Closing because it is not a SC bug)

**Comment by rugk** [comment]
Thanks for your help. I'll do that.
