### ISSUE TITLE
Login or authenticaton should be more userfriendly and clear

### ISSUE THREAD

**Issue by hoergen** [westnordost/StreetComplete#593]
The authorization process is kinda complicated, even if you are technical interested person. I already had a OSM account, but I needed 8-9 tries before i could authorize my account with this wonderful App.

Is there a way that you just can put in the two fields "username" and "password", so that not so technical persons just have a clear vision, what they have to do? 

Or add some more explanations, what you have to do with that authorization process? Like "It opens your browser and then login there. After it is successful, it will guide you back to your app" or something like this.

I have installed the OSM App on my phone and my phone gave me the options to open a browser or the OSM app and because I came from StreetComplete I opened the OSM app several times, which was very logical  for me. But this was a dead end, what I didn't understand until someone helped me to try the other way with the browser.

**Comment by westnordost** [comment]
What is an "OSM app"?

**Comment by hoergen** [comment]
OpenStreetMap is called in the store OSM.

**Comment by westnordost** [comment]
If you mean OsmAnd, OsmAnd is not the official OpenStreetMap app. The website and the app has no affiliation to each other whatsoever.

**Comment by hoergen** [comment]
Ok sorry, that I missunderstod that. But I think many others do the same mistake.

**Comment by westnordost** [comment]
So, your assumption is wrong. OsmAnd is not to OpenStreetMap what the Youtube app is to the Youtube website, it is a completely different app. Supposing there were a MyVideoDownloader app that would offer itself to open youtube.com links, you wouldn't assume that this app would be the "app version" of Youtube, would you?
If anywhere, the error is OsmAnd's name choice for creating such misunderstandings and [their aggressive registering of URLs](https://github.com/osmandapp/Osmand/blob/master/OsmAnd/AndroidManifest.xml#L230-L244).

I opened an issue in their tracker. https://github.com/osmandapp/Osmand/issues/4440 Let's see what comes of it.

This is not an issue of this app, any app that needs OAuth permission from openstreetmap.org will have the same problem.

**Comment by westnordost** [comment]
> Is there a way that you just can put in the two fields "username" and "password", so that not so technical persons just have a clear vision, what they have to do?

This would defy the meaning of using OAuth at all. The reason to use OAuth is that the user doesn't need to give his (OSM) credentials to any such app/website/service but can authorize the app to have a revokable access to his profile there - **without knowing the password**.

**Comment by westnordost** [comment]
However, if this persists to be a problem (Osmand team does not want to do anything about it), I might come back to this and be forced to add some kind of dialog in between that announces that the user now needs to authorize the app **in the browser**.

**Comment by hoergen** [comment]
I think it would help to put a help text like I described, so that nobody else is tapping into that trap , like I did ;)

**Comment by westnordost** [comment]
I fear this issue needs to stay open until Osmand team did something about it or I.

**Comment by smichel17** [comment]
Regardless of what happens with osmAnd, I don't think it will be sufficient, since they are not the only ones who may register this url (for example, [addressToGPS](https://f-droid.org/app/me.danielbarnett.addresstogps) also does this).

However, I don't think you need to go as far as a popup. Just modify the "Not yet authorized" string to something like "Log in from your web browser to authorize."

**Comment by westnordost** [comment]
I think I will add a dialog in between, that explains that a browser will open etc.

**Comment by westnordost** [comment]
I now created a PR at OsmAnd at https://github.com/osmandapp/Osmand/pull/4584 to fix this issue.

**Comment by westnordost** [comment]
@smichel17 I misunderstood your suggestion first. Implemented it now like you suggested.
