### ISSUE TITLE
Quest for opening hours needs an option "permanently closed" 

### ISSUE THREAD

**Issue by nukul4r** [westnordost/StreetComplete#594]
There are some locations in my neighbourhood which are permanently closed. However they are still listed on OpenStreetMaps, so I get the quest regarding the opening hours for them. The closest appropriate answers at the moment are "don't know" or "no regular opening hours", an option "permanently closed" would be useful.

**Comment by matkoniecz** [comment]
Why not answer don't know with "no longer existing" ?

**Comment by HolgerJeromin** [comment]
With the "other" menu you can add a osm note so other can delete the poi or do other stuff

**Comment by westnordost** [comment]
Basically, @matkoniecz and @HolgerJeromin said it already: There are a couple of reasons why a quest -  **any** quest, not just the opening hours one - may not be answerable. The place may not exist any more, it may have changed its name or another shop is there now etc. All of this can be dealt with leaving a short comment explaining the current situation.
