### ISSUE TITLE
Android Wear support

### ISSUE THREAD

**Issue by Rudloff** [westnordost/StreetComplete#595]
Hello,

I often have my smartwatch when I am walking and it could be nice to be able to complete some quests without having to take my phone out.

I tried sideloading StreetComplete to my watch and the map works but clearly the interface could be improved to better fit such a small device. Moreover questions & answers are too big to fit the screen.
Another issue is that Android Wear 1.5 does not have a virtual keyboard so quests that require typing can't be completed.

![screen](https://user-images.githubusercontent.com/840125/30537658-d73d1c3e-9c6a-11e7-8055-da3e06975047.png)
![screen2](https://user-images.githubusercontent.com/840125/30537657-d7385654-9c6a-11e7-8e6b-2ecc2ce3a0d2.png)

**Comment by westnordost** [comment]
Hmm, I will definitely not implement it as it is too much effort and I don't have a smartwatch.

However, I would accept a PR that enabled this. Though, it is more effort that to simply create a layout for a watch. I guess a smartwatch-enabled version would need to have a completely different concept in displaying quests (i.e. fullscreen without map etc).
