### ISSUE TITLE
Update Persian translation

### ISSUE THREAD

**Issue by claudiush** [westnordost/StreetComplete#597]
The Iranian OSM community just discovered StreetComplete and in an around-the-clock effort over the past 24h translated the interface into Persian (language code **fa**). Would be great if you can pull the translation from POEditor so it can be delivered in the next release. It will also give the first opportunity for UI feedback from a right-to-left language which should pave the way other RTL languages like Arabic or Hebrew.

**Comment by westnordost** [comment]
Wow, very cool. Don't worry, I regularly pull the translations from POEditor (before each release)

**Comment by westnordost** [comment]
I will keep this ticket open to collect any RTL-problems that might occur.

**Comment by westnordost** [comment]
Or actually, better create separate tickets for that
