### ISSUE TITLE
A flag for improvements outside of the app

### ISSUE THREAD

**Issue by zonderr** [westnordost/StreetComplete#598]
One could find useful to be able to put flags on the maps, for example to point at some places where something has to be fixed outside of the app.

One thing that happened several times to me is that a quest ask for a speed limit on a road portion, but there are actually two different speed limits, depending on where you are on that portion. I have to remember where it was to fix that at home later.

**Comment by HolgerJeromin** [comment]
Every quest has a "other" option where you can eventually submit an osm note.

**Comment by zonderr** [comment]
Indeed, it can do the trick. I was thinking about something more personal.
