### ISSUE TITLE
UX: Provide better feedback when location issues

### ISSUE THREAD

**Issue by carlinmack** [westnordost/StreetComplete#5983]
I was a user of streetcomplete back in 2020 and now downloaded on a new phone. My whole map looks like the following (not zoomed on my actual location but looks the same with no quests)

![Screenshot_20241023_162131_StreetComplete](https://github.com/user-attachments/assets/b8d18b6e-0a57-4321-9e8f-3a9b621fa6a3)

The location icon in the bottom right is flashing whether it is the arrow or the circle icon. The app doesn't know my location and therefore doesn't show any quests

I have enabled all the location settings I can find and have deleted the apps cache within and outwith the app.

**How to Reproduce**

**Expected Behavior**

**Versions affected**

Android, v59.2

**Comment by matkoniecz** [comment]
> The app doesn't know my location and therefore doesn't show any quests

is location detection working for other apps?

If you zoom out to show entire world - is SC showing you as being located somewhere?

**Comment by westnordost** [comment]
> The location icon in the bottom right is flashing whether it is the arrow or the circle icon. 

A flashing icon means that you granted the app permission to use the location, but not location has been received by the Android system yet. I.e. waiting for a GPS fix or however you'd call it. This is the standard behavior/feedback you see in other apps, too, when no location is known yet.

So, I don't really see the necessity to change anything here. The UI has been exactly the same in 2020 in that regard, by the way. What's new since 2020 is that areas that haven't been downloaded yet have this crosshatch styling.

**Comment by westnordost** [comment]
To go into a bit more detail here. The icon looks the following in the following situations

- location denied by user: crossed out gps icon
- location allowed by user, but location is off via system settings: crossed out gps icon
- (location is on and allowed, but app did not ask for a location yet: gps icon without dot in the middle) _never occurs_
- location is on, allowed and app is waiting for the system to respond with a location: gps icon with flashing dot in the middle
- app has location: gps icon with dot in the middle

**Comment by carlinmack** [comment]
> is location detection working for other apps?

Yes, in apps like citymapper I have geolocation working

> If you zoom out to show entire world - is SC showing you as being located somewhere?

No, the SC map looks uniform with the diagonal lines

> So, I don't really see the necessity to change anything here.

Do you not think it would be a good idea to have some sort of pop up or section near the settings where it explains this state? The problem is that there is no communication of what the flashing means (and personally I haven't seen this flashing indicating that behaviour in other apps)

**Comment by carlinmack** [comment]
for the record here are the two flashing icon states I can toggle between

![20241023_183429.jpg](https://github.com/user-attachments/assets/b093ff3a-97df-40c5-99e1-015cf738199c)

and fully zoomed out map

![Screenshot_20241023_183526_StreetComplete.jpg](https://github.com/user-attachments/assets/52284163-1c13-4174-b06f-d2131187bf5b)

**Comment by carlinmack** [comment]
I've now figured out what the problem was and it's that I didn't have [Location Accuracy](https://support.google.com/android/answer/15157297) enabled. I found out because citymapper had also stopped showing me my location
