### ISSUE TITLE
Add a way to have more info about the quest object

### ISSUE THREAD

**Issue by Dostoi** [westnordost/StreetComplete#599]
Sometimes it can be hard to know which building the quest is about, for example when the quest is about a building in a middle of a long street with very similar building side by side.
It would be great to have a button/option "More info about the quest object" or something similar that will show every known info about the quest object (in the example, the house number would be the best info to get but other things can help)

That can help make it easier to pinpoint the correct building aimed by the quest.

**Comment by westnordost** [comment]
Showing housenumbers etc. on the map is blocked by #183

**Comment by westnordost** [comment]
The map style now shows the housenumbers
