### ISSUE TITLE
Authorized account: null afer upgrade

### ISSUE THREAD

**Issue by HolgerJeromin** [westnordost/StreetComplete#600]
i just updated to 2.0 and found in the setting 
Authorized account: null
Clicking on it, open browser question, abort => 
Authorized account: not authorized
Clicking on it, open url, auth  => 
Authorized account: authorized as holgerjeromin

**Comment by westnordost** [comment]
Hm yes, this is only a display bug. For 2.0, a feature was added to display the OSM user name there which is being collected on authorization. So as you authenticated before 2.0, the username info is not there

**Comment by rugk** [comment]
Maybe display "unknown" there, at least…
