### ISSUE TITLE
Slippy map glued to position when GPs is disabled

### ISSUE THREAD

**Issue by eehpcm** [westnordost/StreetComplete#601]

**Comment by westnordost** [comment]
Please provide a proper description or I will close this issue without further comment.

**Comment by westnordost** [comment]
Okay, I do not want to wait for you to update the description, so I will just leave this comment:

**Press on the location button on the lower right corner to unglue the view from your GPS location. Press it again to glue it back on.**

**Comment by HolgerJeromin** [comment]
The flashing of the icon in this situation is nice, but unvisible if the map is manipulated with the right hand. I almost opened an issue, too

**Comment by HolgerJeromin** [comment]
Most (all?) map apps unglue on manipulation with the finger

**Comment by eehpcm** [comment]
Hmmm, this is the **first** map, particularly ones involving OSM in some way, that glue the position.  And this one did not behave that way until this recent update.  Behaviour changed, and documentation didn't obviously explain that.

Yeah, I saw the flashing icon.  Which appeared to be because I didn't have GPS turned on (I normally don't).  It stopped flashing when I turned on GPS.  Nice feature, to let me know I don't have GPS turned on, but the map doesn't move.  That was the situation as I saw it.

Now it's been explained, it's not a software bug but a documentation bug.

Actually, maybe it **is** a design bug.  Right now I cannot think of a single reason why I'd want to glue the position.  I never missed the feature before it was implemented (or maybe it was there but never affected me).  I don't foresee ever wanting to glue the position.  I'd be perfectly happy if you removed it completely.  But, if you don't want to remove it, please consider having the app start up unglued rather than glued.  Maybe have the user's choice of glued/unglued persist over shut-down/restart, but a first-time user seeing it glued is very likely to immediately delete it.

**Comment by rugk** [comment]
> but a first-time user seeing it glued is very likely to immediately delete it.

That's a good argument as you see that users may think of this "feature" as a bug. "The map does not move…"

**Comment by eehpcm** [comment]
@rugk 

That's close to what happened to me.  Checked the phone before going to bed.  Saw an update, downloaded it and tried it.  Map wouldn't move.  Raised a bug on github.  Went to bed.  Awoke to a complaint that I hadn't instantly provided more details when requested. :)

Had that been my first install, rather than an update to something I've had for months, I would probably have left a 1-star critical review on the playstore and then deleted it.

**Comment by stephan75** [comment]
When I have GPS disabled on my device (that is default GPS setting by me), I am NOT able to unlock map panning with latest SC version ...

I must turn on GPS feature first to unlock panning feature inside SC app.

Can this be improved that unlocking the map is possible and NOT depends on GPS status on device?

**Comment by westnordost** [comment]
Okay, so that the position is glued even though GPS is disabled is definitely a bug. I will fix that and then we will see how the opinions will be about that then.

**Comment by tkan** [comment]
> but a first-time user seeing it glued is very likely to immediately delete it.

+1 for this. 

If this unusual behaviour is what it is, at least a small note (not in the right, lower corner) could appear when the user tries to do a glued move.

**Comment by westnordost** [comment]
Do try out the changed behavior for 2.1 when it is released
