### ISSUE TITLE
Notifications for solvable quests

### ISSUE THREAD

**Issue by Phyks** [westnordost/StreetComplete#602]
Hi,

Not sure how doable this is, but I just noticed that when you go to a restaurant (for instance), Google Maps sometimes asks you questions about the restaurant, to crowdsource the info. I was wondering whether StreetComplete could do something similar (with an option to disable it for instance).

Typical use case is I don't always think about starting StreetComplete to look for quests nearby. But very often, I realize that I could have filled infos about a restaurant or a shop while I was there, and that it would have been super convenient to have a notification at this time (typically for shop schedule or restaurant menu). Maybe StreetComplete could have fetched the nearby quests in background and if I had stayed at some restaurant or shop for some time, it could notify me about such quests? Of course, it would be an anti-feature if StreetComplete was to ask me about ground type for every street I pass, there should be some limitations to given quests types.

What do you think?

P.S.: Not sure if ideas should be posted here or elsewhere. I did not find any IRC channel or relative chat to discuss it :)

**Comment by westnordost** [comment]
It's not really possible. That would mean that StreetComplete would need to always run in the background and scan for quests in the background on changing the location. Scanning for quests is quite a (resource-)heavy process.

Also, I personally despise if apps push in like that. If I do not have an app open, I do not want it to spy on me, much less my location.

>P.S

Yes, this is the right place to post your ideas, no worries.

**Comment by Phyks** [comment]
Ok, I get your point. I will wollofw #48. Thanks!
