### ISSUE TITLE
 Missing string for localization for building levels quest

### ISSUE THREAD

**Issue by claudiush** [westnordost/StreetComplete#605]
Two strings from the levels quest are not translatable:
- "regular levels (not counting the roof)"
- "levels in the roof"
![streetcomplete_missing_loc_levels](https://user-images.githubusercontent.com/428616/30782862-d9b7634c-a139-11e7-9eb9-156e1332850e.jpg)

**Comment by rindlerblabla** [comment]
Same with "Just an advisory speed limit" for the maxspeed quest.

**Comment by westnordost** [comment]
They are now in POEditor.
