### ISSUE TITLE
Building level quest shown although building:levels is marked in parts

### ISSUE THREAD

**Issue by nmxcgeo** [westnordost/StreetComplete#606]
### What happened until now:
In StreetComplete I got a quest for [this building](https://www.openstreetmap.org/way/325741838) asking for its levels. I answered in [this note](https://www.openstreetmap.org/note/1045655) saying that the north part is one level and the south part 4 levels plus one roof level. A kind mapper used this to complete the information in OSM using tags on the building parts. 

### Unexpected behavior:
I got the quest shown again (see attached screenshot). This is despite the levels are marked (correctly?) for all parts and a note was there, which is now resolved.
![screenshot](https://user-images.githubusercontent.com/25130823/30785720-5e2b581e-a16b-11e7-8ac0-5c82e53daa64.png)

### What I expected:
No quest should be shown.

### Information on my setup:
StreetComplete version: 2.0 (Google Play Store beta tester)
Bug appeared before and after reinstall
Samsung Galaxy S5 mini
Android-Version 6.0.1

I know some programming but so far I was never involved in Android-apps. Just tell me if you need any more information.

Thanks for your effort.
NmxCgeo

**Comment by westnordost** [comment]
The quest is shown because the levels are only entered for the parts, not for the building as a whole.

**Comment by westnordost** [comment]
Perhaps I should add a hint in the app that explains this.

**Comment by westnordost** [comment]
Ok done that.
