### ISSUE TITLE
Lit/Street quest filter problems?

### ISSUE THREAD

**Issue by rugk** [westnordost/StreetComplete#608]
Just looking at the source I found this:

https://github.com/westnordost/StreetComplete/blob/e2e71c4e88aacefae81406028848755f1d0a3678/app/src/main/java/de/westnordost/streetcomplete/quests/way_lit/AddWayLit.java#L45

Rewritten into Overpass-Turbo (wizard) this becomes:
```
type:way and 
(
	highway~="residential|living_street|pedestrian"
	or highway~="primary|secondary|tertiary|unclassified|service"
	and ( sidewalk~="both|left|right|yes|separate" or source:maxspeed=~".+:urban" )
	or highway~="footway|cycleway"
	or highway=path and (foot=designated or bicycle=designated)
) and lit!=* and (access!~"private|no" or (foot=* and foot!~"private|no"))
```

However, does not this mix streets and footways (and would e.g. require a footway to have the sidewalk tag?)?
So are not there some brackets missing? I'd say you may want to separate streets and foot/cycleways like this:

```
type:way and 
(
	(
		highway~="residential|living_street|pedestrian"
		or highway~="primary|secondary|tertiary|unclassified|service"
		and ( sidewalk~="both|left|right|yes|separate" or source:maxspeed=~".+:urban" )
	) or (
		highway~="footway|cycleway"
		or highway=path and (foot=designated or bicycle=designated)
	)
) and lit!=* and (access!~"private|no" or (foot=* and foot!~"private|no"))
``` 

From my testing it did - strangely - not make a difference, but even if they are basically the same, I find the second one clearer, so maybe just change it for clarity…

**Comment by westnordost** [comment]
There is no problem. "And" has a higher operator precedence as "or", just like * related to +.

4+5*2 = 14, not 18

**Comment by rugk** [comment]
Okay, but still don't change it even for clarity? (I could make a PR.)

**Comment by westnordost** [comment]
No thanks

On 26 September 2017 16:07:23 EEST, rugk <notifications@github.com> wrote:
>Okay, but still don't change it even for clarity? (I could make a PR.)
>
>-- 
>You are receiving this because you modified the open/close state.
>Reply to this email directly or view it on GitHub:
>https://github.com/westnordost/StreetComplete/issues/608#issuecomment-332192182

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by rugk** [comment]
Okay, so in this case, however, is not this query then wrong?

[Here](https://github.com/westnordost/StreetComplete/blob/master/app/src/main/java/de/westnordost/streetcomplete/quests/wheelchair_access/AddWheelChairAccessPublicTransport.java#L26) you mention the important criteria (no wheelchair) at the end, connected with "and". So this and would not apply for `amenity = bus_station`, if I interpret it correctly…

**Comment by westnordost** [comment]
Correct, the brackets around the two or-conditions are missing, you found a bug!

 Could you open another issue for that (or create a Pr to fix it right away)?

On 27 September 2017 22:04:11 CEST, rugk <notifications@github.com> wrote:
>Okay, so in this case, however, is not this query then wrong?
>
>[Here](https://github.com/westnordost/StreetComplete/blob/master/app/src/main/java/de/westnordost/streetcomplete/quests/wheelchair_access/AddWheelChairAccessPublicTransport.java#L26)
>you mention the important criteria (no wheelchair) at the end,
>connected with "and". So this and would not apply for `amenity =
>bus_station`, if I interpret it correctly…
>
>-- 
>You are receiving this because you modified the open/close state.
>Reply to this email directly or view it on GitHub:
>https://github.com/westnordost/StreetComplete/issues/608#issuecomment-332639232

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.
