### ISSUE TITLE
Power poles material quest isn't visible

### ISSUE THREAD

**Issue by gustavecha** [westnordost/StreetComplete#613]
Hi

I recently updated street complete, but the quest asking for power poles material doesn't show anything on map.
Since no power infrastructure is visible in the app, should poles be loaded prior to use the quest?

Thanks in advance to have a look on it

**Comment by rugk** [comment]
I think you have to press "search for quests" multiple times. I think it only searches for 3 quests peer tap, so if you have luck, you may get the power poles quest.

**Comment by Dostoi** [comment]
It doesn't load all the quest of the area at once ?

**Comment by gustavecha** [comment]
Hi,
Even if I try to load requests a dozen times, power poles quest won't show any point.
Why is StreetComplete look for 3 quests only at a time ?
It can't be comprehensive on a given area since the quests number is increasing.

An extra improvement would be to add the user ability to select which quests he wants to see.

**Comment by rugk** [comment]
> An extra improvement would be to add the user ability to select which quests he wants to see.

https://github.com/westnordost/StreetComplete/issues/35

**Comment by westnordost** [comment]
> Why is StreetComplete look for 3 quests only at a time ?

Because loading the quests is an expensive operation, not only for the app itself but even more so for the Overpass API. StreetComplete is cautious with the number of requests it makes to not overload the Overpass API.

**Comment by westnordost** [comment]
Regarding this bug, please tell me a GPS position where you would expect this quest but it does not show up so that I may reproduce this issue.

**Comment by gustavecha** [comment]
Ok for OAPI requests
Then a planel to select quests would be more than useful. I saw it planned for v3

You can try to reproduce the issue near this node
https://www.openstreetmap.org/node/3298021551

I've loaded the quests 10 times without any pop up on it

**Comment by westnordost** [comment]
Found it.

**Comment by gustavecha** [comment]
Did you find the quest/pole or the responsible bug?
