### ISSUE TITLE
Street Complete 2.0 F-Droid: I can not dragging the map

### ISSUE THREAD

**Issue by mdtrooper** [westnordost/StreetComplete#614]
I have updated the streetcomplete to the new  version.

And I can not dragging the map.

I think the feature of dragging is good, because for example I know my district and I want to fill other places in the district out of my gps position.

Thanks and awesome app.

**Comment by westnordost** [comment]
Did you try tapping on the gps button on the lower right?

On 28 September 2017 13:36:41 CEST, Miguel de Dios Matias <notifications@github.com> wrote:
>I have updated the streetcomplete to the new  version.
>
>And I can not dragging the map.
>
>I think the feature of dragging is good, because for example I know my
>district and I want to fill other places in the district out of my gps
>position.
>
>Thanks and awesome app.
>
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/westnordost/StreetComplete/issues/614

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by mdtrooper** [comment]
Yes, yes. Sorry the icon of gps are lock the drag action.

Thanks.

**Comment by rugk** [comment]
Dupe of https://github.com/westnordost/StreetComplete/issues/601, basically

**Comment by westnordost** [comment]
Duplicate, yes, but I rededicated the mentioned ticket to fix a bug. If you want, you can discuss here what could be done to convey better to the user that he needs to press that button to unglue

On 28 September 2017 16:23:22 CEST, rugk <notifications@github.com> wrote:
>Dupe of https://github.com/westnordost/StreetComplete/issues/601,
>basically
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/westnordost/StreetComplete/issues/614#issuecomment-332852355

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by dbdean** [comment]
I've had a thought about this. Given that you can two finger rotate in this mode, and that the map is locked at the centre, shouldn't one finger drag also rotate the map? This would also make it easier to map one handed, while the other hand is holding the dog's lead 🐕

**Comment by dbdean** [comment]
Of course, I'm also interested in the logic of *why* dragging the map shouldn't disable GPS mode, as I certainly expected it to the first time I used this mode too.
