### ISSUE TITLE
further surface type: tiles

### ISSUE THREAD

**Issue by Oi-sin** [westnordost/StreetComplete#616]
I completed a quest for surface type on https://www.openstreetmap.org/note/1150576 The surface are large tile-like stones that are not uncommon for pedestrian zones. It was not the first place I stumbled over this missing type of surface. Maybe you could include it?

**Comment by westnordost** [comment]
Certainly not. It is used by only **0,001%** of elements that have surface tagged and is not even documented.

**Comment by biketeur** [comment]
Siehe auch
https://forum.openstreetmap.org/viewtopic.php?id=69714
