### ISSUE TITLE
[French] Confusing choice when reverting a change

### ISSUE THREAD

**Issue by Rudloff** [westnordost/StreetComplete#617]
Hello,

When reverting a change, both answers are the same:
![screenshot_20170929-163429](https://user-images.githubusercontent.com/840125/31030291-1a461560-a555-11e7-9500-29cea4fa77f4.png)

This probably comes from the fact that "cancel" and "revert" can both be translated as "annuler".

**Comment by westnordost** [comment]
:-D

**Comment by westnordost** [comment]
Well, any suggestions? How is it translated for Version control systems like Git, SVN etc? How is it translated in Mediawiki etc?

**Comment by Rudloff** [comment]
MediaWiki translates both as "annuler" too but I guess they never have them side to side.
I don't know how Git offically translates it but French developers often use the neologism "reverter" in order to avoid this confusion.

We could use "révoquer" which is a correct translation of "revert" but is a bit formal.

**Comment by westnordost** [comment]
Is simply "OK" (or the French equivalent) also an option?

**Comment by Rudloff** [comment]
Oh right, didn't think about that...

**Comment by westnordost** [comment]
So, choose something and I will change it :-)

**Comment by westnordost** [comment]
Also, consider the following translations. All good?:
_Nothing to undo_ -> _Rien à annuler_
_Undo the following last answer?_ -> _Annuler la dernière réponse ?_

**Comment by Rudloff** [comment]
I think you can use "Confirmer" (= to confirm), that's what makes the most sense in this context.

**Comment by Rudloff** [comment]
Yes, those other translations are fine.

**Comment by westnordost** [comment]
Done

**Comment by Binnette** [comment]
Hi, maybe we can use :

|label|en|fr|
|-----|----|----|
|confirmation_discard_negative|Do not undo|Ne pas annuler|
|action_undo|Undo|Annuler|
