### ISSUE TITLE
Remove "created_by" on ways/nodes on upload

### ISSUE THREAD

**Issue by HolgerJeromin** [westnordost/StreetComplete#623]
Most osm editors does some cleanup on ways it touches anyway.
Most notably "created_by"

This is the list of iD
https://github.com/openstreetmap/iD/blob/577637f97a185fb60e30c5c3bb5e15a2f2cab545/data/discarded.json

**Comment by westnordost** [comment]
StreetComplete should not do any more than what the user expects it to do. So, no automatic fix-ups of things that have nothing to do with the change.
