### ISSUE TITLE
Asks for housenumber for building=hospital with name="Haus F"

### ISSUE THREAD

**Issue by versat** [westnordost/StreetComplete#624]
It is about this building:
https://www.openstreetmap.org/way/337269628
and this building:
https://www.openstreetmap.org/way/131908057

Despite these buildings have already names, StreetComplete keeps asking for a housenumber.
I can not see any housenumber and i think the buildings of this hospital are not numbered but have names (maybe this is common about hospitals, i do not know).
I think it is still ok for StreetComplete to ask for a housenumber when there is only a name.

But what i would say is a bug is the following:
If i click on "Weitere Antworten"/"Further Answers", there is the option "Keine Nummer aber ein Hausname"/"No number but a housename". This is the case, so i clicked on it. Then it lets me enter the housename. But i know that the building already has a name, so i do not want to enter a name again.
I'm not sure what i would expect to be the correct behaviour.
Maybe StreetComplete should not ask for housenumbers at hospital buildings that already have a name (Like it is the case with university buildings i guess).
Maybe StreetComplete should have another option when there is already a name to just tell it that the building has no housenumber and ignore this specific issue in the future.
But overwriting an existing name is not that good i would say.

Regards
versat

**Comment by rugk** [comment]
As per [the Overpass query here](https://github.com/westnordost/StreetComplete/blob/master/app/src/main/java/de/westnordost/streetcomplete/quests/housenumber/AddHousenumber.java#L35) it should already exclude buildings, which already have a `addr:housename`.

**Comment by versat** [comment]
I see. And since the tag "name" is used in my examples and not "addr:housename", StreetComplete asks for a name.
I'm not sure which tagging is correct for my examples.
Should i add "addr:housename" or change "name" to "addr:housename"?
Should/Could StreetComplete give a hint when a "name" tag is already used and ask to copy it to "addr:housename" (or use "name" value as default for "addr:housename" value)?
These are just some thoughts, i do not know what would be correct.

**Comment by westnordost** [comment]
What would you write on a letter if you were to send one to.a person working in that building?

1. If it was "Breslauer Straße 201, Haus F", then I'd say, the Housenumber is "201, Haus F" (because only "Haus F" would imply that there is a house named that way sonewhere in that street.

2. If you'd say that you can't send a letter to that building (because the hospital manages their mail-stuff in the main building or whatever), then that building should probably have no address.

It is an edge case. For the neighbouring building, I'd say it is definitely a name, not a addr:housename/number. But for "house x", it's difficult.

On 2 October 2017 09:35:37 CEST, Sebastian <notifications@github.com> wrote:
>It is about this building:
>https://www.openstreetmap.org/way/337269628
>and this building:
>https://www.openstreetmap.org/way/131908057
>
>Despite these buildings have already names, StreetComplete keeps asking
>for a housenumber.
>I can not see any housenumber and i think the buildings of this
>hospital are not numbered but have names (maybe this is common about
>hospitals, i do not know).
>I think it is still ok for StreetComplete to ask for a housenumber when
>there is only a name.
>
>But what i would say is a bug is the following:
>If i click on "Weitere Antworten"/"Further Answers", there is the
>option "Keine Nummer aber ein Hausname"/"No number but a housename".
>This is the case, so i clicked on it. Then it lets me enter the
>housename. But i know that the building already has a name, so i do not
>want to enter a name again.
>I'm not sure what i would expect to be the correct behaviour.
>Maybe StreetComplete should not ask for housenumbers at hospital
>buildings that already have a name (Like it is the case with university
>buildings i guess).
>Maybe StreetComplete should have another option when there is already a
>name to just tell it that the building has no housenumber and ignore
>this specific issue in the future.
>But overwriting an existing name is not that good i would say.
>
>Regards
>versat
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/westnordost/StreetComplete/issues/624

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by westnordost** [comment]
Actually, @versat , which version of Streetcomplete are you using? Since 2.0, the app does not ask for the housenumber for buildings within an area that already has a housenumber anymore.

**Comment by versat** [comment]
I'm using the version 2.1 and it still asks me for the housenumbers.

Am 04.10.2017 12:09 nachm. schrieb "Tobias Zwick" <notifications@github.com
>:

Actually, @versat <https://github.com/versat> , which version of
Streetcomplete are you using? Since 2.0, the app does not ask for the
housenumber for buildings within an area that already has a housenumber
anymore.

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/westnordost/StreetComplete/issues/624#issuecomment-334110403>,
or mute the thread

**Comment by rugk** [comment]
Related: https://github.com/westnordost/StreetComplete/issues/626#issuecomment-334105444 ?

**Comment by westnordost** [comment]
Once the quests are created on your device, they don't vanish if the behavior how they are created changed.

**Comment by versat** [comment]
I have deleted the cache and data of the app. Now some issues that were missing are shown. But the wrong housenumber issues (examples) are still shown too. I guess i can not do more to get rid of obsolete issues.

**Comment by westnordost** [comment]
I will investigate.

**Comment by westnordost** [comment]
Ok so the hospital area is not recognized as an area by the app, investigating why...
