### ISSUE TITLE
opening hours monday not deselactable

### ISSUE THREAD

**Issue by tilladams** [westnordost/StreetComplete#625]
Android 5.0.2,  title says it all

**Comment by rugk** [comment]
You can remove all the stuff you do not need. As you report a bug, remove the other things.

**Comment by westnordost** [comment]
Can not reproduce. Also tested on Android 5.

**Comment by tilladams** [comment]
hm. problem with my phone? I think as screenshot does not help. If I open the 1st panel for Opening Hours, I can't deactivate mondays (and unfortunately a lot of shops have closed on monday). If I open a 2nd tab for more opening hours and all days are unchecked, I can't select mondays.I use a Sony XPeria D5803 with Android 5.0.2

**Comment by westnordost** [comment]
And what App version do you use?

**Comment by westnordost** [comment]
In the current version, and I think in any version so far, there has not been implemented any logic to disallow selection/deselection within this dialog.

Do you have the same problem with January when you select Other answers -> Differs by month?

**Comment by tilladams** [comment]
I use version 1.3
The function " Other answers -> Differs by month?" works perfect, also "January".

Perhaps we close this issue and I'll try the next version. Right now, I just leave the issues open, when having a shop that has closed on monday ;-)
Many thanks!

**Comment by westnordost** [comment]
Okay. Version 2.3 will be out soon.

**Comment by tilladams** [comment]
Hi. thanks for the new version - new TODO's ;-)
I have a new mobile and no problems with the "mondays2 any more. Perhaps it was just due to the old phone. Sorry for the noise.

**Comment by westnordost** [comment]
Thanks for reporting back :-)
