### ISSUE TITLE
Translators credits are truncated to just 8 languages

### ISSUE THREAD

**Issue by antonv6** [westnordost/StreetComplete#628]
In 2.1, credits screen only shows translators for these languages: Català, Dansk, Deutsch, English, Español, Euskara, Français and Italiano, in this order. So, only 8 languages out of 24 supported are shown.

**Comment by westnordost** [comment]
Hm I can't reproduce this. Which Android version are you using? Is the "See the project on POEditor for a complete list" shown?

**Comment by antonv6** [comment]
I'm on plain android 6.0.1. I've switched to various system languages, but still could only see these 8 items.

For the record, I see the link, but #629.

**Comment by antonv6** [comment]
Oh, I've found something: I can see the full list in horizontal mode, but not in vertical.

**Comment by westnordost** [comment]
Hm, I can see it in portrait and landscape either way.

**Comment by westnordost** [comment]
Can you independently scroll the area in which the language credits are shown?

**Comment by antonv6** [comment]
I can, using two fingers: sort of like one is holding the whole screen to prevent it from scrolling, and then the other finger scrolls the credits.

**Comment by westnordost** [comment]
Okay, so that seems to be the issue. I couldn't reproduce it though, and I did not find any hints how to fix this issue, so I ditched the RecyclerView layout and instead used a normal LinearLayout (it's also easier-to-read-code this way).

Does anyone of you two build from source? Then you could check if this fixed the issue.

**Comment by Binnette** [comment]
@westnordost 
I can reproduce the error before a838a36 and can not after. So I confirm that this bug is fixed :+1:
