### ISSUE TITLE
Bug: not asking levels for buildings with address info

### ISSUE THREAD

**Issue by gappleto97** [westnordost/StreetComplete#632]
Specifically in this area: https://www.openstreetmap.org/way/525479712

Most houses in that neighborhood have no level info, but none of them are asking.

**Comment by westnordost** [comment]
One does not have anything to do with the other.

**Comment by gappleto97** [comment]
Okay, but why is that quest not showing up there then?

**Comment by westnordost** [comment]
Ok, I'll have a look.

**Comment by westnordost** [comment]
Can't reproduce. The area is full of housenumbers. Might be #562.
