### ISSUE TITLE
[Feature Request] Add a "Complete StreetComplete" Question

### ISSUE THREAD

**Issue by Mannshoch** [westnordost/StreetComplete#633]
While Browsing through the Issues I got some discussions about the situation in specific Countries. Maybe a special Quest would be nice (maybe a Opt-in, or appear if user stay a lot of time in a specific country ) which ask some information like about:

- #561 "Are these peak features common in your country? - Yes/No/Add a peak Feature" 
- #527 "How does Walking signs look like in your country? - Take a photo"
- #547 "Are tactile paving  common in your country? -Yes/No"

This Information should be sent to StreetComplete so @westnordost could safe time for researches and has only to decide how to implement it.

**Comment by rugk** [comment]
That's a very interesting idea. I really like it. It would basically be a user survey/feedback integrated into the web. Quite obtrusive and likely useful (as I think only a small percentage of StreetComplete users finds and comments on GitHub issues).

To ask them in a useful way one could:
* of course only ask the question when no data for a specific country has been included
* only ask it once, of course (easy to do)
* only ask it when the specific feature (mountain/peak, …) are near the current location
* display it as a marker on the map, so users are not surprised to suddenly see a popup (as UX advise says: never surprise the user)

Actually maybe the server integration could be the harder part. Although I think that a small script could do it. One could even just access some specific text (or other) files on the server and then look into the server log and count the responses (using command line tools such as grep and wc).

**Comment by westnordost** [comment]
> This Information should be sent to StreetComplete

StreetComplete is just the app, there is no backend "behind" the app.

**Comment by westnordost** [comment]
But if there were such a class of quest, it could also be used for crowdsourced collection of translations of places in different countries. "How do you call this type of shop in [some language]?"

**Comment by westnordost** [comment]
So, this class of quest would require a backend which would collect this information and also be able to aggregate the data and (publicly?) show it in some web interface. This is no small thing.

**Comment by rugk** [comment]
> show it in some web interface.

Why? Don't make it so complicated…

> This is no small thing.

Depends on how you want to do it. What about the idea I expressed?:
> One could even just access some specific text (or other) files on the server and then look into the server log and count the responses (using command line tools such as grep and wc).

**Comment by westnordost** [comment]
@rugk Hmm, by the way, are you proficient with script languages, most importantly probably python?

**Comment by rugk** [comment]
I can help with PHP, Shell or so. Python rather not. A small database connection (via PHP) may also be no problem.

But this still does not answer my question of why not use this kind of webserver log files? BTW, you could even use professional programs such as [Piwik](https://piwik.org/) to automate the data analysis. Piwik can also analyze web server logs and as it is FLOSS and can anonymize IPs (or you just don't save them in the log in the first place) it is a privacy-sensitive solution.

**Comment by HolgerJeromin** [comment]
This needs at least a full featured webserver. Which this app does not have right now.

**Comment by rugk** [comment]
Yes, but actually there is a web server and the app queries it regularly. See the privacy policy. It is http://www.westnordost.de/streetcomplete. So there this thing could be hosted.

I'd say this depends on https://github.com/westnordost/StreetComplete/issues/63, however. We do not want user data (even if it is nothing secret) flowing over insecure connections. At least HTTPS assures integrity in that case.

**Comment by matkoniecz** [comment]
It may be a very ugly hack - but maybe answers to such questions may be send as an email?

**Comment by rugk** [comment]
But evaluating mails is hard, is not it?

**Comment by Mannshoch** [comment]
Maybe transfer it over the OSM account? A message from user to you in a specific format you could collect by script? 
![grafik](https://user-images.githubusercontent.com/7795891/32144410-a5e609e8-bcb8-11e7-86e0-b7ac1f2b8a25.png)

**Comment by ENT8R** [comment]
I wrote a simple website using PHP and Javascript for this purpose. It can be found at https://ent8r.lima-city.de/CompleteStreetComplete/ 
It even has a small API. What do you think about it?

**Comment by rugk** [comment]
From a first look it is awesome! Is the source for that available?

**Comment by ENT8R** [comment]
Yes, the source code can be found at https://github.com/ENT8R/CompleteStreetComplete

**Comment by rugk** [comment]
BTW, that @ENT8R did in #783 was to show these "quests" on the map.
However showing then in a special menu as a usual survey may also be possible. (As these quests can be answered from anywhere for a user)

So I just like to add another argument for the "in-map" method:
* It really encourages users to solve the quests/answer the question. As users are unlikely to look into a submenu, especially if they don't expect anything new (after an app update). And I doubt we have many users in some "smaller" countries or so, so we really need every answer.

So to get every answer it is not a bad idea to also have this menu, for users who already know these surveys and who want to answer it directly without going anywhere.

Also we may consider not showing it at a specific point on the map, by rather a bottom material design notification or an Android notification, or showing it randomly on the map (let it appear in the center), so users don't think they need to go there to solve the quest.

**Comment by Mannshoch** [comment]
**Mockup:**
![2018-05-08 16_46_50-clipboard](https://user-images.githubusercontent.com/7795891/39764585-38668956-52e0-11e8-8c5a-1ceda8fde563.png)

**Comment by westnordost** [comment]
@ENT8R 's initiative has been abandoned by him and I am not particularly avid about the idea anyway. Some kind of in-app voting/questionaire thing could be a nice feature, for usability studies and also studies what kind of things can be expected in which country, but we did not have this feature in the last 3 years and it did not seem to be a big obstruction for creating new quests limited to certain countries.

After all, the information we can get through this feature would be mostly anecdotal, as StreetComplete users are also not that representative in the country they map in.

I am going to close this, but I wouldn't reject a PR that implements it because it may become useful one day. Also, since the notification button feature, such a "questionaire" feature could be conveniently added as a notification to not be too obstrusive to users who don't like to answer such things.
