### ISSUE TITLE
Automated Quest: Free Wifi coverage

### ISSUE THREAD

**Issue by Thorsten-Sick** [westnordost/StreetComplete#634]
Hi

A kind of automated quests would be to map free wifi coverage. That way travellers would know if a city has free wifi, which ssids it has and in which area it is available.

How-to automate it
************************
- A list of standard free-wifi ssids is in StreetComplete
- Also: The client can learn when a Wifi can be received in many places around the area and let the user verify ("Is this <SSID> a free wifi ?")
- After that signal quality for the free wifi is mapped in the background without user interaction. Sending the data to the server could still be verified by the user

**Comment by HolgerJeromin** [comment]
Osm is the wrong database for that and streetcomplete is the wrong app.
Ref  #635

**Comment by rugk** [comment]
Have a look at https://location.services.mozilla.com/. This is a project that does this. I agree that it is outside the scope of StreetComplete.

**Comment by westnordost** [comment]
Jup
