### ISSUE TITLE
Automated Quest: Free Mobile phone coverage

### ISSUE THREAD

**Issue by Thorsten-Sick** [westnordost/StreetComplete#635]
Hi

(Similar to free wifi coverage issue)
StreetComplete could automatically collect mobile coverage/quality data for every location. Relevant data to include would be:
- ISP (Telekom, Vodafone, O2, ...)
- Network (2G, 3G, LTE)
- Signal quality

A bubble on the map could guide the user to the point to measure. After getting the data automatically, sending the data could be something to confirm by the user.

Not only relevant for Pokemon Go players :-) But also when deciding for a phone provider when moving to a small town or similar....

**Comment by HolgerJeromin** [comment]
There are some apps on the market with open and closed database.
Integrating into streetcomplete would require an own database because osm is the wrong place for that.
Streetcomplete does not run in the background so the value would not be big.

**Comment by rugk** [comment]
Have a look at https://location.services.mozilla.com/. This is a project that does this. I agree that it is outside the scope of StreetComplete.
