### ISSUE TITLE
Bus stop shelter should appear before tactile paving

### ISSUE THREAD

**Issue by Athoss9** [westnordost/StreetComplete#637]
Surveying a bus stop shelter is much more easier, since they are visible from a way bigger distance. All bus stop shelters of a route can be surveyed while sitting on the bus. For surveying the tactile paving, you have to go directly next to it, it's impossible surveying from the bus itself, so a survey is needed for each bus stop separately. So my suggestion is, that shelter quest should have higher priority and tactile paving should appear, when shelter is already filled in.

**Comment by rugk** [comment]
> For surveying the tactile paving, you have to go directly next to it, it's impossible surveying from the bus itself

Not really impossible (you can see the – in most cases – white tactile pavings), but harder.

**Comment by westnordost** [comment]
The quests are not sorted by difficulty to solve but by importance of use. The order is:
1. may be shown as missing in QA tools
2. important data that is used by many data consumers
3. useful data that is used by some data consumers
4. data useful for only a specific use case
5. defined in the wiki, but not really used by anyone yet. Just collected for the sake of mapping it in case it makes sense later

Currently, bus stop shelters are in category 5. Do you know any application (, map, etc) that makes use of this tag?

**Comment by HolgerJeromin** [comment]
osmand shows a different icon for bus stops with a shelter
(red roof if no shelter, blue roof if a shelter and no roof if unknown)

**Comment by westnordost** [comment]
Okay, so it can be moved up to 5 or 6

**Comment by Echolon** [comment]
Hello, I would like to also suggest to ask if the station is only covered (normally big or central busstations). How about this?
(New issue?)

**Comment by rugk** [comment]
You commented in an really old issue. If I interpret your comment correctly, you want to ask for a complete new quest. If that is the case, yes, please create a new issue and fill out the "new quest" template. Thanks.
