### ISSUE TITLE
Sometimes shows no question

### ISSUE THREAD

**Issue by rugk** [westnordost/StreetComplete#64]
### STR
1. Let GPS search forever, never let it finish. (go into a tunnel or just fake it)
2. Select a question (maybe somewhere else than where your "current" location/blue dot is)

### What happens
The object is highlighted/selected, but the question does not appear.

However a workaround is to turn your device, e.g. from portrait into landscape mode or vice versa and it is shown. (You can rotate it back afterwards.)

### What should happen
Just show the question. The circumstances described in the STR should not limit this feature.

v0.5
CM 13

**Comment by westnordost** [comment]
So this is only reproducible if you have no GPS fix? Is it also reproducible if you simple turned off location (in the settings)?

**Comment by rugk** [comment]
No, only reproachable with missing GPS fix when I last tested it.

**Comment by westnordost** [comment]
Try rotating the display or turning on animations (=turning off battery saving mode) as a workaround. Fix is in next verison.
