### ISSUE TITLE
move AddBikeParkingCapacity priority up, to 6. useful data that is used by some data consumers

### ISSUE THREAD

**Issue by matkoniecz** [westnordost/StreetComplete#641]
At least cycle layer at main OSM website is using this data https://www.openstreetmap.org/#map=18/50.06628/19.94675&layers=C

![selection_001](https://user-images.githubusercontent.com/899988/31463986-422b2fbe-aed0-11e7-9475-56468bb71097.png)

(there are three bicycle parkings here, only larger ones is displayed with the full icon and capacity)

**Comment by westnordost** [comment]
Sure. you can also make a PR
