### ISSUE TITLE
on authorization attempt loading spinner spins for minutes without feedback

### ISSUE THREAD

**Issue by matkoniecz** [westnordost/StreetComplete#643]
As result it is not clear what is broken - app? My internet connection? App? OSM website?

Note - during writing this bug report I got authorization window.

Report based on beta version from Play.

**Comment by matkoniecz** [comment]
> Note - during writing this bug report I got authorization window

That lead me back to spinning spinner in StreetComplete (with "loading") and failed to result in authorization.

**Comment by matkoniecz** [comment]
Forever spinner appears for me also in standard Google Play version.

**Comment by matkoniecz** [comment]
And now it is gone. Not that OSM website and OSM API worked perfectly at the same time, at the same network. So it may be either temporary issue caused by my hardware/network/my other software/whatever or indicator of a real bug.

But I would consider more verbose information under spinner than just "Loading".

**Comment by westnordost** [comment]
?

**Comment by matkoniecz** [comment]
> ?

I reinstalled app.
I went to settings, selected authorization section.

Spinner with "loading" under it appeared and nothing changed for multiple minutes (usually browser window appears almost immediately, but for some reason multiple times in row it was not happening).

I think it would be preferable to show what went wrong/what app is attempting to do in case when action goes for several minutes.

**Comment by westnordost** [comment]
It looks like the request timed out.

**Comment by matkoniecz** [comment]
> westnordost added the feedback required label 5 days ago

Is there anything else that I should clarify?

**Comment by westnordost** [comment]
I don't really get what you suggest. It's loading the URL, there is nothing to give feedback. If you load a webpage and it does not respond, you also get no feedback other than the loading indicator.

**Comment by matkoniecz** [comment]
Is it at least possible to detect that connection timed out and will never complete? Or show "try again" after some time like 30s or minute?

Or is it an overkill and not worth handling specially?

**Comment by westnordost** [comment]
When the connection timed out, the authorization should cancel and a toast saying "Unable to reach the authorization server" should pop up. I don't know though what the connect timeout is set to, it is an external library (oauth.signpost:signpost-core)

**Comment by westnordost** [comment]
So... I am closing this.
