### ISSUE TITLE
different icon for Dev version

### ISSUE THREAD

**Issue by matkoniecz** [westnordost/StreetComplete#644]
#630 allows one to use both Dev and Google Play version. At this moment it is quite confusing as displayed part of the name and icons are the same

Would it be welcomed to make pr changing icon of Dev version (for example, yellow background instead of blue)?

**Comment by Binnette** [comment]
Or maybe a background like this one :
![image](https://user-images.githubusercontent.com/6597721/31484970-8df86238-af32-11e7-9ab4-bb4f724b8e42.png)

**Comment by matkoniecz** [comment]
That would be quite irritating (at least for me), as I normally use Dev version and it would look like icon of crashed app.

**Comment by Binnette** [comment]
Here is a compromise. Just the top is "under construction" :smile: 
![image](https://user-images.githubusercontent.com/6597721/31485857-9cf1a31e-af35-11e7-92c4-6dd2ced7aa89.png)

**Comment by rugk** [comment]
Well… just a D or Dev would be enough.

**Comment by westnordost** [comment]
Sure

**Comment by matkoniecz** [comment]
I will look again at this later, so far I discovered

- metadata/en/images/icon.png - modyfying this file is nor changing icon of the program
- res/appicon_fancy.svg, res/appicon_flat.svg - expected that https://github.com/matkoniecz/Zazolc/commit/6614c02580b326b9d3293cba004c30022e9ccbe8 + https://github.com/matkoniecz/Zazolc/commit/ddeb55c4fb8831511a31435db8f1ac0f07879898 will enable separate icon for dev build, but it turned to be not working. In fact, after unistalling both SC builds, deleting all three icon files and invalidating caches Android Studio builds app with an old icon! So it is located at yet another location that should be found (or maybe invalidate caches is not invalidating caches properly...)

**Comment by westnordost** [comment]
/app/src/main/res/mipmap-*/ic_launcher.png

**Comment by matkoniecz** [comment]
Thanks!
