### ISSUE TITLE
Bug: entering long non-numeric housenumbers crashes the app

### ISSUE THREAD

**Issue by DaubnerF** [westnordost/StreetComplete#645]
I am fairly new to StreetComplete, but today managed to reproducibly crash the app by entering a housenumber with a certain format:

The house was part of a larger row-house complex, so on the sign it said 25/11 (house number 25 house 11). This is quite a common naming scheme here in Austria.

When I tried to enter 25/11 (by switching to the normal keyboard) the app crashed in a reproducible way. Entering 25/1 (or any other single-digit number at the end) works fine.

**Comment by MrSunday334** [comment]
I had the same issue when trying to tag a building with "10,10a". This should be a valid value according to https://wiki.openstreetmap.org/wiki/Addresses#Buildings_with_multiple_house_numbers .

**Comment by westnordost** [comment]
Which version are you using?
Are you using the version from google play or from F-Droid? If it is from F-Droid, you are asked to send the bug report - in that case, could you do that? For Google Play, I **think** I get the crash reports automatically - but if in case you are asked, could you press "yes"?

**Comment by MrSunday334** [comment]
I'm using the current master but I could reproduce it also on the current beta version in GooglePlay (2.1).  I submitted a feedback from the crash dialog.

**Comment by DaubnerF** [comment]
I'm using the version from Google Play. I was asked if I want to send the crash report and I already did that before I opened this issue. If you did not get the report, I can either try to reproduce the issue and send the report again or do something else which helps you in identifying the issue.

**Comment by westnordost** [comment]
I think I got it, thanks!

On 13 October 2017 14:12:09 CEST, DaubnerF <notifications@github.com> wrote:
>I'm using the version from Google Play. I was asked if I want to send
>the crash report and I already did that before I opened this issue. If
>you did not get the report, I can either try to reproduce the issue and
>send the report again or do something else which helps you in
>identifying the issue.
>
>-- 
>You are receiving this because you were assigned.
>Reply to this email directly or view it on GitHub:
>https://github.com/westnordost/StreetComplete/issues/645#issuecomment-336435459

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.
