### ISSUE TITLE
A lot of apartment buildings have a building name. My idea is a new question: "has this building a name?" I think we can start with the buildings from the "big apartment building" type.

### ISSUE THREAD

**Issue by boute002** [westnordost/StreetComplete#648]
### General
Affected key(s) (or tags) to be modified: [](https://wiki.openstreetmap.org/wiki/Key:)
Question asked: **Is there an example tag on item XY?**

### Checklist
Checklist for quest suggestions (see guidelines):
- [ ] 🚧 To be added tag is established and has a useful purpose
- [ ] 🤔 Any answer the user can give must have an equivalent tagging (Quest should not reappear to other users when solved by one)
- [ ] 🐿️ Easily answerable by everyone from the outside
- [ ] 💤 Not an overwhelming percentage of elements have the same answer (No spam)
- [ ] 🕓 Applies to a reasonable number of elements (Worth the effort)

### Ideas for implementation

**Element selection:** 

**Metadata needed:** 

**Proposed GUI:**

**Comment by rugk** [comment]
Please delete the issue template and add a description of your issue. Do not put everything into the title.

**Comment by westnordost** [comment]
1. Please read these guidelines before posting an issue: https://github.com/westnordost/StreetComplete/wiki/Adding-new-Quests-to-StreetComplete
2. See @rugk
