### ISSUE TITLE
New quest: "has this building a name?"

### ISSUE THREAD

**Issue by boute002** [westnordost/StreetComplete#649]
A lot of apartment buildings have a building name. My idea is a new question: "has this building a name?" I think we can start with the buildings from the "big apartment building"

**Comment by westnordost** [comment]
Please read these guidelines before posting an issue: https://github.com/westnordost/StreetComplete/wiki/Adding-new-Quests-to-StreetComplete

**Comment by boute002** [comment]
Hi Tobias,

I have read the guidelines 3 times now, I don't see where I am wrong? Can
you please clarify, what guideline I am missing?

Grt Alert

Op 18 okt. 2017 12:27 AM schreef "Tobias Zwick" <notifications@github.com>:

**Comment by westnordost** [comment]
Well, first I expect that the issue template is actually filled out. But in any case, what you missed is this:

> 💤 No spam: It must be possible to determine whether the quest should reasonably be asked. A quest which is to be answered in 99% of the time with the same answer is not a good quest, don't bore the users. I.e. asking for any road if it is a one-way road, is silly, because the vast majority of all roads will not be one-ways.

The vast majority of any (apartment) building will have no name. So, the users would be spammed with questions for names of buildings that do not have names (and the OSM as well with noname=yes tags).

**Comment by boute002** [comment]
Hi Tobias, Seeing you're comments I understand where you are afraid of,
but, of course I can only speak about the Netherlands. In the Netherlands
the vast majority of apartment buildings does have a building name. I am
daily on the road, because of my work. And I see them everywhere.

Grt. Alert

Op 18 okt. 2017 12:41 AM schreef "Tobias Zwick" <notifications@github.com>:

**Comment by westnordost** [comment]
I don't think so, Alert. Any building that has more than one dwelling unit inside, is tagged as apartments.

This here: https://www.google.de/maps/@52.3548291,4.7952914,3a,54.4y,0.22h,94.8t/data=!3m10!1e1!3m8!1sWaUtWqO0Gx-xYVdfgQC4Ow!2e0!6s%2F%2Fgeo2.ggpht.com%2Fcbk%3Fpanoid%3DWaUtWqO0Gx-xYVdfgQC4Ow%26output%3Dthumbnail%26cb_client%3Dmaps_sv.tactile.gps%26thumb%3D2%26w%3D203%26h%3D100%26yaw%3D272.50223%26pitch%3D0%26thumbfov%3D100!7i13312!8i6656!9m2!1b1!2i43

Is all building=apartments.
