### ISSUE TITLE
Intuitively closing/canceling question

### ISSUE THREAD

**Issue by rugk** [westnordost/StreetComplete#65]
Wen I mistakenly open a question or see I cannot answer it I often want to close it. However to do so I first have to open it and close it in the top left.
That's a bit cumbersome IMHO, so I'd like to close the question directly in the cases I described above.

E.g.:
1. Swipe the question away/swipe down.
2. Tap somewhere else/deselect the question.

In both cases you could still show the question whether I really want to hide the question, but IMHO this question is not really necessary anyway as mostly you only have to tap in two or three things, one word, two numbers or so. Only for opening hours it could be frustrating to lose the changes, but also there in most cases not much is lost and the users of your app likely have a good enough short-term memory to remember the information they were entering.

**In any case** you could skip this "Really cancel?" question if no change is made, so that I can instantly hide the question if I see it is "too difficult" or so.

**Comment by westnordost** [comment]
The "Really cancel?" dialog **should** only pop up when you actually change anything. Where does it always pop up?
Anyway, did you know you can answer "Can't answer" and then click on "just hide"? It will hide the quest from you (forever).

**Comment by rugk** [comment]
You're right, indeed it already only pops up if there are changes. If not I'll open a new issue.
I also know of this hiding feature, but this is not what I want. This issue is about just hiding the input/quest bar at the bottom using more intuitive methods.
