### ISSUE TITLE
switch osm-account

### ISSUE THREAD

**Issue by my-na-me** [westnordost/StreetComplete#650]
How can I switch osm-account user?
If this isn't possible (currently using v2.2), please could you add this feature?

**Comment by westnordost** [comment]
Just click on the "authorize OSM access" item in the settings and reauthorize in the browser with a different user.

**Comment by my-na-me** [comment]
Thank you.
It's working now, also for me. Initially the upper right corner of the webpage (including user drop down menu) was hidden by using android dolphin browser app. So, actually I didn't found the user control menu including "Log Out" menu item...
