### ISSUE TITLE
"No house number but a name" field cannot be submitted

### ISSUE THREAD

**Issue by ianrenton** [westnordost/StreetComplete#651]
First of all thanks for making a great app!

Unfortunately I think I have found a bug. Using v2.2 from Play Store.

I have a number of nearby quests for house numbers, but the buildings in question only have a name.

When I use the house number pop-up, one of the "other answers" is "no house number but a name". When I click that, I get a text box to fill in the name. After entering the name, clicking OK does not seem to do anything. The pop-up does not disappear and no data is saved.

**Comment by westnordost** [comment]
Oh no! Will investigate.

(In the meantime, you can instead leave a note in cases where a building has a house name instead of a house number)

**Comment by westnordost** [comment]
Ah, this is actually a regression bug of the fix for #645.

**Comment by rugk** [comment]
unit tests? 😊

**Comment by westnordost** [comment]
Yeah, there are tests, but no UI unit tests yet. The effort to create and maintain this seems too high.
