### ISSUE TITLE
New Quest type : Validation of given informations

### ISSUE THREAD

**Issue by FX7** [westnordost/StreetComplete#657]
As I use StreetComplete on a daily base, i realised a problem of OSM itself, or better say: a problem of a detailed information collection:
_The more detailed informations you got, the more likely they will be become outdated over time._

**For example:**
A building will not change so often. It can be tear down or rebuild, but this is something that will (normaly) not change for decades.
But the shops in the building, or the opening hours of a shop, will most likely change over years or even more often.

With the right parameters (time) this problem of corse matches for nearly all kind of informations.

**The general Idea:**
I think it would be great to implement an easy way to verify and delete outdated informations.

**A concrete implementation:**
Would it be possible to show the opening hours of a shop for verification? For example: "Are the given opening hours 'Mo-Fr 09:00-16:00' for 'Shopname' still valid?"
If the answer is no, then delete the opening hours.

**Problems:**
How to filter, which opening hours should be presented? It should be possible, to extract the last change date of the opening hours. If this date is older than a given period, show them for verification.
How to apply the answer "Yes, opening hours still valid"? If someone already verified the opening hours, they shouldnt be presented to the next user for verification. I can imagine a lot of ways, how to do this, but dont know what whould be best practice to fit into OSM patterns.

So, looking forward for feedback.

**Comment by westnordost** [comment]
I think this is a duplicate. It has been brought up and discussed before. The main problem is this:

> It should be possible, to extract the last change date of the opening hours. 

How?

**Comment by westnordost** [comment]
Or, to elaborate: Theoretically, it is possible to extract the last change date of any one tag by digging through the change history of that object. But this is too expensive to do for each single element. The OSM Api wasn't made for this and neither Overpass nor any other API so far offers this kind of shortcut to the last-change-of-tags data.

**Comment by FX7** [comment]
I also thought of this as an important general topic, but hoped that there would be an easy approach.

One way to store these "check" informations would be a "lastcheck" tag. There are many reasons against this solution, thats why I didn't mention it ;-)
So you are right, this should be put on a wider platform. As I'm new to OSM, I don't know where right the forum / mailinglist / wiki for this would be.

And also I underestimated the costs of getting the last change date. You say, the OSM API didnt provide easy access for this information. The only chance is to dig through the whole history, which is of corse, very expensive.

But this also may be put on a wider platform and is a more generel problem of OSM and its API.

**Comment by westnordost** [comment]
The mailing lists are here https://wiki.openstreetmap.org/wiki/Mailing_lists
I consider the main/general one to be **talk**. **dev** might also be a good place.

**Comment by FX7** [comment]
Ok, thanks a lot for you help!

And of corse for the great app!
