### ISSUE TITLE
Show note about how to count floors

### ISSUE THREAD

**Issue by rugk** [westnordost/StreetComplete#66]
The floor question does not show how to count the floors? In different countries the ground/first floor is counted, in some it is not. When a new OSM user uses this app, they do not know how to do it here, so it should definitively be noted/shown somewhere.

**Comment by johnwhelan** [comment]
Locally we have buildings that number 1,2,3, G,2,3 some have a 13th floor but many do not.

However they all have physical floors and I think the count of physical floors is what should be in the map not what they are called.

I don't think you need a Ph.D. in floor counting to count them.

**Comment by rugk** [comment]
😂
No but you need to know that the first floor also counts as a floor. Without this information also someone with a Ph.D. cannot reliability enter the number of floors there.

**Comment by johnwhelan** [comment]
And for those buildings with no 13th floor?

**Comment by westnordost** [comment]
Guys, just stand in front of a building and count the windows one over another, you do not need to go inside!
As said, I will add an illustration.

**Comment by rugk** [comment]
Nice, maybe also adding the "physical", i.e. "physical floor", you mentioned in another comment, makes the whole thing already much clearer.

**Comment by cstackpole** [comment]
I had a similar question. Nearly all of the houses in the neighborhoods that surround me have basements. Do they count? 
Some of the houses *look* like two stories from the front, but they are considered basements because ground level is floor one in the back yard. Some basements are completely finished while others are unfinished.

**Comment by johnwhelan** [comment]
If you look at the wiki 

https://wiki.openstreetmap.org/wiki/Key:building:levels

It does describe it fairly well.  Currently streetcomplete does not handle all cases.

**Comment by westnordost** [comment]
See ticket #41, I added an illustration and shortened the phrasing. One image says more than 1000 words.
