### ISSUE TITLE
Improve the unglue function

### ISSUE THREAD

**Issue by cyclingcat** [westnordost/StreetComplete#660]
The glue/unglue function is very useful, but it could be improved: If the app is in glue mode, it's currently only possible to zoom in/out but not to move the map. If you want to move it, you have to unglue it first by tapping on the glue button. This could be avoided, if moving the map automatically switches the app in unglue mode. OsmAnd does it this exactly this way.

Or is there a special reason not to allow moving the map while it is glued?

The cycling cat

**Comment by westnordost** [comment]
Yes. But I explained it before, several times. Please look through the issue tracker.
