### ISSUE TITLE
Predefined notes for special cases (e.g. "way has to be split")

### ISSUE THREAD

**Issue by cyclingcat** [westnordost/StreetComplete#661]
Surprisingly often I'm not able to answer a "surface" or "lit" quest, because I had to split a way, since its surface or lit state changes somewhere. It's probably beyond the scope of StreetComplete to split a way in order to tag these attributes correctly, so each SC user will see this quest and noone will be able to solve it! The best a SC user can do is to leave a note.

As this case occurs quite often, it would make life easier if there were a possibility to leave a pre-defined note (e.g. "Way must be split in order to tag 'surface' correctly") instead of having to type the same text over and over again. (Maybe there is more use of predefined texts, so the user could choose between them in addition to a free text field? Just an idea.)

The cycling cat

**Comment by westnordost** [comment]
Hm, no. This app shall only use the note feature to let the user itself input text. It should not add text (semi-)automatically.
Rather than putting thought into how to improve the "last resort" note feature, rather, it should be put time into developing the possibility to _really_ split ways.

**Comment by cyclingcat** [comment]
I assumed that implementing a possibility to split a way would be challenging (you will even have to introduce intermediate nodes at the split positions quite often) and error-prone (is the computed GPS position really accurate enough? What if it isn't located on the quested way?) Hence the idea to make it easier to leave a note (and correct it later with JOSM or let other people correct it).

The cycling cat
