### ISSUE TITLE
Check and correct inconsistent surface attributes

### ISSUE THREAD

**Issue by cyclingcat** [westnordost/StreetComplete#662]
The OSM tags "surface" and "tracktype" are often used together in order to describe a way tagged as "highway=track". However, sometimes the attributes are inconsistent with each other, e.g. "surface=asphalt, tracktype=grade2" or "surface=gravel, tracktype=grade1". Many maps (e.g. OsmAnd and OpenMTBMap/Velomap for Garmin devices) render paved ways differently which is very useful for road cyclists.

Ideas:

- If a surface quest is solved, the app could examine, if "tracktype" is set. If it's not, set it accordingly. If this attribute is already set, check if it's correct and in case it's not, correct it (maybe show a warning?)

- Discover these kinds of discrepancies and show them as normal "surface" quest as if the attributes aren't already set. If the quest has been solved by a user, proceed as stated above.

The cycling cat

**Comment by westnordost** [comment]
To be designed more specifically. Not sure if this quest can be made:

Take into account, that a "these attributes are inconsistent"-detection must be in **always** correct. Since SC is not a QA tool where you can in doubt opt to mark something as false-positive, this option does not exist for this app. To cite the quest suggestion guidelines:

> 🤔 No unanswerable quests: All generated quests need to be actually answerable (no false-positives). This means that any answer given by the user must result in something being tagged. For example, a quest that asks for the website of a place must be able to tag the element somehow if the user answers that the place has no website - otherwise, the next user will be asked the same question. Sometimes, due to the nature of how things are tagged in OSM (such as the one given in the example) it is unfortunately simply not possible to fulfill this.

For example, the case that this app detects a (possible) inconsistency and asks the user of this app which surface this road really has, and the user answers exactly the same surface as was tagged before, **may never happen**. Can you guarantee that?

**Comment by matkoniecz** [comment]
> surface=asphalt, tracktype=grade2

May be valid with overgrown or extremely deteriorated asphalt.

> surface=gravel, tracktype=grade1

This one should be always incorrect and require either changing of surface (for example to compacted) or of tracktype.

**Comment by westnordost** [comment]
So, any feedback, @cyclingcat ?

**Comment by cyclingcat** [comment]
I tried to research if "surface=asphalt, tracktype=grade2" is indeed a valid combination. While the English wiki page is sometimes a little vague (it uses adverbs like "mostly" or "usually", thus allowing these kinds of combinations, at least for special cases), its German counterpart clearly distinguishes between "waterproof surface" (like tarmac, concrete, cobblestones) for tracktype=grade1 and "water-bound surface" (like gravel and other compacted materials) for tracktype=grade2, thus forbidding "surface=asphalt, tracktype=grade2". So maybe it isn't as clear as I originally assumed. The same goes for "surface=gravel, tracktype=grade1".

Perhaps it's indeed too ambiguous for SC...

The cycling cat

**Comment by westnordost** [comment]
Ok then, but would be an idea for osmose!
