### ISSUE TITLE
highway name="sans nom"

### ISSUE THREAD

**Issue by Marc-marc-marc** [westnordost/StreetComplete#663]
https://www.openstreetmap.org/changeset/49440578
a user add name="sans nom"
In French "sans nom" mean "no name"
is it a user mistake or a missing choice in the quest ?

**Comment by westnordost** [comment]
It is a user mistake. The form looks like this
![screenshot](https://raw.githubusercontent.com/westnordost/StreetComplete/master/metadata/en/images/phoneScreenshots/screenshot1.png).

It specifically asks for how it is written on the street sign and the input field also looks like a street sign. The user should have clicked on "Other Answers..." and selected "This street has no name".
