### ISSUE TITLE
use local language for names on the map

### ISSUE THREAD

**Issue by matkoniecz** [westnordost/StreetComplete#664]
Passing current language set on phone to https://github.com/westnordost/StreetComplete/blob/master/app/src/main/assets/cinnabar-style-8.0.0.yaml#L24 would result in displaying names on the map in the local language (except low zoom as result of https://github.com/tilezen/vector-datasource/issues/977 )

According to https://github.com/westnordost/StreetComplete/pull/659#issuecomment-339464463 ideal app version would include a dynamic map style, so it may be a good first step.

**Comment by matkoniecz** [comment]
@ENT8R @westnordost Do you know is it possible to dynamically modify style in tangram-es?

**Comment by westnordost** [comment]
Yes. I am doing this for the quests.

**Comment by matkoniecz** [comment]
Depends on style - for example see https://github.com/ENT8R/streetcomplete-mapstyle/blob/master/global.yaml#L24 where source of names (later reused) is defined. With language defined in section above (for example in https://github.com/ENT8R/streetcomplete-mapstyle/blob/master/global.yaml#L18 - like `path_outline`) this specific language would be preferred and used if available.

So http://www.openstreetmap.org/node/25248662 is currently displayed on map as 北京市, with language set to en it would be Beijing (and with language set to de it would be Peking).

With Cinnabar it is also possible to set it somewhere, I would need to check variable name.

**Comment by matkoniecz** [comment]
In Cinnabar it would be `ux_language`

https://github.com/westnordost/StreetComplete/blob/master/app/src/main/assets/cinnabar-style-8.0.0.yaml#L24

**Comment by matkoniecz** [comment]
And https://github.com/tangrams/tangram-es/blob/master/platforms/android/demo/src/main/java/com/mapzen/tangram/android/MainActivity.java#L87 has what seems to be example of doing this.
