### ISSUE TITLE
App should not add "source:maxspeed = sign" to maxspeed entries

### ISSUE THREAD

**Issue by pinkdroyd** [westnordost/StreetComplete#665]
There are two types of possibilities to enter speed limits for streets: Either just giving the maximum speed or adding the "zone" attribute to it (see [screenshot](https://github.com/westnordost/StreetComplete/blob/master/metadata/en/images/phoneScreenshots/screenshot4.png) from the readme-file).
When you select "zone", it adds the correct maxspeed:type element (e.g. "maxspeed:type = DE:zone30" for a zone with a maxspeed of 30 km/h in Germany).
Whenever you add only the speed without the zone element selected, the app adds "maxspeed:type = sign". This should not be happening since it could also have the maxspeed type "DE:urban" for 50km/h in a German town without any further restrictions.

So, my point basically: **The app should not add "maxspeed:type = sign" by default** or it might add wrong data to the map.

**Comment by rugk** [comment]
The app has a button "There is no sign" in the "other answers" menu. This is what should be used for speed limits without a sign.
Thus, the behavior is correct. The app does not ask for a speed limit, but *whether there is a street sign* limiting the speed. The icon also initiates this.

**Comment by westnordost** [comment]
It could be a translation issue. I can't access the translations right now. Does the question asked explicitly ask for a _sign_ in your language?

On 27 October 2017 15:31:10 CEST, "Benedikt Häring" <notifications@github.com> wrote:
>There are two types of possibilities to enter speed limits for streets:
>Either just giving the maximum speed or adding the "zone" attribute to
>it (see
>[screenshot](https://github.com/westnordost/StreetComplete/blob/master/metadata/en/images/phoneScreenshots/screenshot4.png)
>from the readme-file).
>When you select "zone", it adds the correct maxspeed:type element (e.g.
>"maxspeed:type = DE:zone30" for a zone with a maxspeed of 30 km/h in
>Germany).
>Whenever you add only the speed without the zone element selected, the
>app adds "maxspeed:type = sign". This should not be happening since it
>could also have the maxspeed type "DE:urban" for 50km/h in a German
>town without any further restrictions.
>
>So, my point basically: **The app should not add "maxspeed:type = sign"
>by default** or it might add wrong data to the map.
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/westnordost/StreetComplete/issues/665

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by pinkdroyd** [comment]
> The app has a button "There is no sign" in the "other answers" menu.

Did not realise that until now, thanks for the hint!

> Does the question asked explicitly ask for a _sign_ in your language?

A sign is not mentioned in the German translation. Basically says: "What maximum speed is specified (or given) for this street?"
"There is no sign" is literally translated, so it should be asking for a sign in the first place. I guess that would fix it.

**Comment by westnordost** [comment]
_Welche Höchstgeschwindigkeit ist für diese Straße angegeben?_

Do you have a suggestion how it can be formulated to (more) explicitly mention a sign?
"Was ist auf dem Schild für die Geschwindigkeitsbegrenzung angegeben?" perhaps?

**Comment by LeopoldKellers** [comment]
I agree that the app/translation should more explicitly direct the user's attention towards the fact that the value to be entered must be read off an official sign.
How about
> Welche Höchstgeschwindigkeit ist hier per Schild vorgeschrieben?

or
> Laut Schild gilt auf dieser Straße welche Höchstgeschwindigkeit?

**Comment by westnordost** [comment]
The first one sounds good, also is not much longer than before. I'll take that.
