### ISSUE TITLE
Opening hours : shop is closed some months

### ISSUE THREAD

**Issue by pandark** [westnordost/StreetComplete#666]
Hi.

I have seen several shops indicating that they are closed during some months. Using the UI, I have to add the hours for the months where it is open, possibly several times.

For example, if it is closed during August and December, I will have to add the opening hours for every day once for January-July, and once for September-November.

This could probably be maid more user friendly by adding a "closed between date x and date y" or "closed during some months" to the UI.

**Comment by westnordost** [comment]
True, but I won't put any more work in the months selection, because it is used by only a very small portion of places. The necessary work / the necessary addition of complexity in the form is not worth it.

**Comment by matkoniecz** [comment]
Also, one may use a traditional editor like JOSM or Vespucci.
