### ISSUE TITLE
android-apt is deprecated, AndroidStudio 3.0 is not supported

### ISSUE THREAD

**Issue by matkoniecz** [westnordost/StreetComplete#667]
I upgraded to AndroidStudio 3.0, now build fails with

```
FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':app'.
> android-apt plugin is incompatible with the Android Gradle plugin.  Please use 'annotationProcessor' configuration instead.
```

according to https://bitbucket.org/hvisser/android-apt/wiki/Migration android-apt is already deprecated

**Comment by westnordost** [comment]
Hmm, I also updated to Android Studio 3 and did not see that problem yet. Let's see.

**Comment by matkoniecz** [comment]
Maybe there is a different behavior depending on OS? Update already mentioned OS specific changes (something about 32 bit Windows).
