### ISSUE TITLE
Display quests even after solving them in order to revert them

### ISSUE THREAD

**Issue by rugk** [westnordost/StreetComplete#67]
It would be nice if the quests could even be shown after I solved them (in a grey – or green – and potentially smaller version of course). Probably some people will like it to impress other people or so, don't know… 😆

Otherwise I rather had the idea in mind to make it possible for the user to revert the chances. Say e.g., the user accidentally missed to count the ground floor (https://github.com/westnordost/StreetComplete/issues/66) or so and wants to revert it. When the quest is, however, submitted once, they cannot do it in the app anymore…

**Comment by westnordost** [comment]
Hmm nah, the better approach is to have the quests be so clear from the beginning, that there will be no misunderstandings. I know that the building level quest in particularly is currently confusing for some users, I intend to add an illustration and adapt the.
Not mentioning the non trivial amount of work I had to put in such a feature.

**Comment by rugk** [comment]
For reference, I consider this issue to be replaced by https://github.com/westnordost/StreetComplete/issues/116.
