### ISSUE TITLE
Buildings have become very high some time ago in tilt view

### ISSUE THREAD

**Issue by Natenom** [westnordost/StreetComplete#674]
I don't exactly remember in which version. For example garages which have 1 level are shown double as high as a building with 4 levels + 1 roof level.

**Comment by westnordost** [comment]
Hmm, please report any bugs with the map (style) here: https://github.com/tangrams/cinnabar-style
(And before reporting the bug, check if the problem is reproducable here http://tangrams.github.io/cinnabar-style/ )
