### ISSUE TITLE
consider skipping some ways for cycleway quest

### ISSUE THREAD

**Issue by matkoniecz** [westnordost/StreetComplete#675]
was mentioned in #671 Sorry if that was not missed but rather considered as a poor idea for one reason or another

maybe skip surface=gravel and similar roads? http://www.openstreetmap.org/way/25116628#map=19/50.07320/19.88894 and similar are extremely unlikely to have cycleway infrastructure.

Maybe skip also roads with low max speed? I think that maxspeed=20, maxspeed=30 roads are very unlikely to have a special cycling infrastructure (except contraflow) and tagging cycleway:both=none there is not really useful.

**Comment by westnordost** [comment]
Hmm,... you have a point. The `surface=gravel` thing would be difficult to do/maintain since there are so many different surfaces... :-/

**Comment by matkoniecz** [comment]
> The surface=gravel thing would be difficult to do/maintain since there are so many different surfaces... :-/

Fortunately I already did it as part of road rework in openstreetmap-carto:

https://github.com/gravitystorm/openstreetmap-carto/blob/e1599e5c2722b809153190ed15c1763f0622e4fe/project.mml#L475

> unpaved', 'compacted', 'dirt', 'earth', 'fine_gravel', 'grass', 'grass_paver', 'gravel', 'ground', 'mud', 'pebblestone', 'salt', 'sand', 'woodchips', 'clay'

is quite good and stable list of unpaved values for roads

**Comment by westnordost** [comment]
salt?

**Comment by matkoniecz** [comment]
This list includes everything documented on wiki that makes sense, and at least at time of writing this code there were some roads going through dry salt lakes where surface=salt has chance to be correct.

**Comment by westnordost** [comment]
What would you say about the street lighting in roads like the one you linked?

**Comment by matkoniecz** [comment]
It seems quite likely that unlit ways also may be skipped.

**Comment by westnordost** [comment]
No, I meant whether the "street lights" quest should perhaps also be limited further to only include streets that are paved.

**Comment by matkoniecz** [comment]
> No, I meant whether the "street lights" quest should perhaps also be limited further to only include streets that are paved.

I think that would not be a good idea. Yes, unpaved ways are much less likely to be lit but it is not very unlikely (though it also be my local bias). In addition in places where lit roads are less likely information whatever road is lit is more valuable (in the same way as surface=asphalt gives more information on highway=path than on highway=motorway).

And I have yet to see single unpaved road (even on a photo) that has cycleway lane, separate cycleway or contraflow.
