### ISSUE TITLE
Issue with cycleway quest

### ISSUE THREAD

**Issue by ENT8R** [westnordost/StreetComplete#676]
I just wanted to test the new cycleway quest but if I want to build from source, the Gradle build ends with this error message:
`Class 'AddCycleway' must either be declared abstract or implement abstract method 'isDefaultEnabled()' in 'QuestType'`
I think that this is not wanted, isn't it?

**Comment by ENT8R** [comment]
I think there is another problem [here](https://github.com/westnordost/StreetComplete/blob/a1bceeacffeb6699c8dcc53bcabccb2b8bdbf139/app/src/main/java/de/westnordost/streetcomplete/quests/bikeway/AddCyclewayForm.java#L224) because there it says: `Class 'Anonymous class derived from ViewHolder' must either be declared abstract or implement abstract method 'onBind(U)' in 'ViewHolder'`

**Comment by HolgerJeromin** [comment]
Perhaps we should have a CI like Travis for this project:

https://docs.travis-ci.com/user/languages/android/
