### ISSUE TITLE
Multiple quests on the same street are not shown until one is completed

### ISSUE THREAD

**Issue by buralien** [westnordost/StreetComplete#677]
When a street is missing multiple tags, typically speed limit, surface type and lightning, only one of these quests is visible and until it is completed, there is no way to fill the other ones.
I would like to see either all quests side by side along the street. Alternatively, the priority of which quest is shown on top should be changed, because some of the quests are easier to "solve" then others. Right now, I always see "speed limit" quest first, which requires travelling to the start of the street. On the other hand, quests for "surface type" and "lightning" can usually be completed at any point of the street, so these should be prioritized/on top of the "speed limit" quest.

**Comment by ENT8R** [comment]
I think this is a duplicate of #124.

> Alternatively, the priority of which quest is shown on top should be changed

There will be an option to change the priority of the quests in one of the next releases. The PR for this issue was merged just two days ago...

**Comment by buralien** [comment]
I agree, this is a dupe. Not sure how I missed the original, did search around before submitting. Sorry.
