### ISSUE TITLE
Cycleway quest should skip ways tagged as cycleway:both=no

### ISSUE THREAD

**Issue by dbdean** [westnordost/StreetComplete#678]
I have recently wiped my StreetComplete storage, and noticed that some cycleway quests have come back. It appears that perhaps `cycleway:both`=`no` is not being removed from the filtering?

For example, this way http://www.openstreetmap.org/way/383557609, shows up again in SC, asking me about the cycleways, even though I tagged it a few days ago as no cycleway on either side.

**Comment by westnordost** [comment]
Will investigate
