### ISSUE TITLE
Support SOCKS proxy

### ISSUE THREAD

**Issue by steelman** [westnordost/StreetComplete#68]
Support connections via SOCKS proxy to support [TOR](https://www.torproject.org/).

**Comment by westnordost** [comment]
Contributions to OSM are not anonymous, I see no reason to put TOR in the middle.

**Comment by steelman** [comment]
>Contributions to OSM are not anonymous,

Actually they are in a way. OSM does not require users to give any of their personally identifiable data (name, address or a state-issued ID number). While the contributions are not anonymous (they can be attributed to OSM accounts), contributors may remain anonymous.

> I see no reason to put TOR in the middle.

Communication between a client and the OSM servers involves many more parties than these two. Users may wish to hide their activities from those between them and OSM.
