### ISSUE TITLE
Always unglue the map while solving a quest

### ISSUE THREAD

**Issue by cyclingcat** [westnordost/StreetComplete#680]
If you want to solve a quest concerning an OSM way correctly (e.g. road surface, lit status, speed limit) you will have to make sure that the attribute in question doesn't change throughout the whole way. At least for road surfaces on agricultural ways such a change occurs surprisingly often, maybe it's due to the fact that many ways are originally drawn from aerial images. The only way to solve such a quest would be to split the way, which is currently not possible with StreetComplete (and possibly dangerous). At least the user should check the positions of the way's ends in order to determine if the quest is solvable at all.

However, if StreetComplete is in glue mode before tapping on a quest icon, it's currently impossible to do this thoroughly, because you're not able to move the map in order to find both ends. Zooming out is not always a real option for longer ways because the map gets sometimes very confusing and unclear, especially if there are many ways in a region.

Suggestion: Remember the glue state of the map before entering edit mode. Change the map state to "unglued" while in edit mode. Restore the previous mode after leaving edit mode. This way a user would be always able to check if an attribute is valid for the whole length of a way without destroying your general "gule/unglue" philosophy.

The cycling cat

**Comment by westnordost** [comment]
But the map is zoomed automatically into position so that the whole way is in view. Why is this not enough?

On 7 November 2017 16:33:06 CET, cyclingcat <notifications@github.com> wrote:
>If you want to solve a quest concerning an OSM way correctly (e.g. road
>surface, lit status, speed limit) you will have to make sure that the
>attribute in question doesn't change throughout the whole way. At least
>for road surfaces on agricultural ways such a change occurs
>surprisingly often, maybe it's due to the fact that many ways are
>originally drawn from aerial images. The only way to solve such a quest
>would be to split the way, which is currently not possible with
>StreetComplete (and possibly dangerous). At least the user should check
>the positions of the way's ends in order to determine if the quest is
>solvable at all.
>
>However, if StreetComplete is in glue mode before tapping on a quest
>icon, it's currently impossible to do this thoroughly, because you're
>not able to move the map in order to find both ends. Zooming out is not
>always a real option for longer ways because the map gets sometimes
>very confusing and unclear, especially if there are many ways in a
>region.
>
>Suggestion: Remember the glue state of the map before entering edit
>mode. Change the map state to "unglued" while in edit mode. Restore the
>previous mode after leaving edit mode. This way a user would be always
>able to check if an attribute is valid for the whole length of a way
>without destroying your general "gule/unglue" philosophy.
>
>The cycling cat
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/westnordost/StreetComplete/issues/680

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by cyclingcat** [comment]
Really? I will double-check this soon (unfortunately it's currently cold and rainy here...) and try to give an example.

Nevertheless, zooming out is sometimes not sufficient for long ways because you don't see the details anymore (especially if there are crossings with sharp angles inbetween).

The cycling cat

**Comment by westnordost** [comment]
Yes, but why do you need to see the details? You need to see where it starts and where it ends, no?

**Comment by cyclingcat** [comment]
Today I tried to find the way from Tuesday last week again but failed to do so. I will try to find another appropriate way at home (it's better to demonstrate the problem with a quite long OSM way with sharp-angled crossings).

Indeed, the map is zoomed out automatically, trying to show the whole way on the screen. However, if the way touches the southern border of the map, its end lies a little bit outside the map. Today I recorded a video before I clicked on a surface quest: While the north-eastern end of the way is clearly visible (including the crossing the way starts at), the southern end looks like it will continue further south. The ways that branch away from the southern end aren't visible until you zoom out a little further (which I did in second 10 of the video).

https://we.tl/wBO1OonhTm

The cycling cat

**Comment by westnordost** [comment]
Thank you for the demonstration, this surely looks like a bug.

Unfortunately, everything regarding the display of quests, including the zoom-to-contain function is quite an elaborate hack because the map rendering library as such does not really have that feature. I would not like to invest any more time into that hack because my hope is is that the library one day will support this out of the box so that I can throw my code away.

You know what, I will just zoom out a tiny bit further by default, so it should become less of a problem.
