### ISSUE TITLE
undo is not undoing hiding quests

### ISSUE THREAD

**Issue by matkoniecz** [westnordost/StreetComplete#681]
I made quest hidden and I expected that undo will fix this.

I understand that undo is currently undoing only OSM edits, but I think that typical user would expect that also other decisions may be reversed.

**Comment by westnordost** [comment]
Phew, I think this is actually quite easy to implement.

**Comment by matkoniecz** [comment]
I am going to assume that it is a sign of well designed program architecture :)

**Comment by westnordost** [comment]
Particularly the undo feature is more convoluted than I hoped for, but I didn't have any better idea.
