### ISSUE TITLE
changing quest priority requires app restart to change how quests are displayed on the map

### ISSUE THREAD

**Issue by matkoniecz** [westnordost/StreetComplete#682]
If it is not trivial to fix this - maybe just mention it in the quest reordering menu?

**Comment by westnordost** [comment]
It should be, odd.

The setting is done in an own activity, so when coming back to Main, I'd expect it to onCreate again

**Comment by westnordost** [comment]
Right, all the important classes that handle the list are singletons, thus, never get to update their quest list data. Fixed.
