### ISSUE TITLE
Problem with italian translation

### ISSUE THREAD

**Issue by LuisRiug95** [westnordost/StreetComplete#684]
In the pop-up for delete the last modify the two buttons have the same string ("Annulla") in italian version

**Comment by ENT8R** [comment]
Related to #617

**Comment by matkoniecz** [comment]
You can fix it by fixing Italian translation at https://poeditor.com/join/project/IE4GC127Ki

**Comment by westnordost** [comment]
So, I changed it so that for any localization, the text on the OK and on the CANCEL button can be chosen freely. For English, it is still the same - Undo and Cancel, for i.e. Italian, French etc. it can be something different so that it is clear which button is which.
