### ISSUE TITLE
Bank vs atm confusion

### ISSUE THREAD

**Issue by HolgerJeromin** [westnordost/StreetComplete#686]
I got a money icon quest and clicked on it.
It asked: enter Opening hours for "sparkasse" 

I thought this must be the bank (as there was a bank), but later check with vespucci showed that only the atm was in osm.
so i entered the wrong hours.

**Comment by rugk** [comment]
…whcih is to disable that quest.

**Comment by westnordost** [comment]
...for atms

**Comment by HolgerJeromin** [comment]
Thanks for the pragmatic solution. 
Indoor ATM are often not 24/7 but for example closed 00:00 till 5:00 so i would look forward to the better solution.
