### ISSUE TITLE
Are there any other implemented, but disabled quests?

### ISSUE THREAD

**Issue by rugk** [westnordost/StreetComplete#687]
I've heard the "add name for this object" quest is implemented, but disabled (hardcoded). So just a quick question: Are there any other quests, which are disabled in the same way?

**Comment by westnordost** [comment]
No

Am 13. November 2017 00:32:58 MEZ schrieb rugk <notifications@github.com>:
>I've heard the "add name for this object" quest is implemented, but
>disabled (hardcoded). So just a quick question: Are there any other
>quests, which are disabled in the same way?
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/westnordost/StreetComplete/issues/687

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.
