### ISSUE TITLE
Rotate map according to user's perspective

### ISSUE THREAD

**Issue by exploide** [westnordost/StreetComplete#69]
Sometimes, it would be easier to locate and move to a certain quest when the map were rotatable to match user's perspective. Similar to what navigation apps like OSMAnd can do. The mentioned app also provides an example of how the UX controls could look like, i.e. a simple compass that switches between user's perspective and north orientation.

**Comment by westnordost** [comment]
If this is implemented, there must also be a compass displayed on the map which points north, because quests will refer to directions when answering them (i.e. "is this a oneway street? In which direction?", "Is there a sidewalk? On which side?") etc.

**Comment by waldyrious** [comment]
I just tried to complete a few quests as a passenger on a car ride, but the inability to orient the map (or have it oriented automatically) made it quite harder than I expected. This feature would be very helpful.

**Comment by penpendede** [comment]
I frequently use OSMand~ for navigation purposes and have it always map "up" to my forward direction as I find it the most natural map behavior because when orienting without a map I visualize a map in my inner mind that has precisely the same orientation.

**Comment by westnordost** [comment]
(Not high prio for me right now, but this would be a really cool feature for new contributors who know Java+Android to this project to implement. I can give advice.)

**Comment by matkoniecz** [comment]
If added, please add also option to disable it.

**Comment by arbie65** [comment]
A feature I would love to see,  it can be very confusing trying to pick out the correct features when the map is fixed to north is up and you are going any other direction

> If added, please add also option to disable it.

It would be good to have as @westnordost said a compass indicating the setting.   Click it for either "north is up" or "direction of travel is up"
