### ISSUE TITLE
Avoid asking about maxspeed, cyclelanes for junction=roundabout?

### ISSUE THREAD

**Issue by CloCkWeRX** [westnordost/StreetComplete#690]
For roundabouts in Australia; a cycle lane will always end prior to a roundabout; so doesnt make sense to ask for this info. I am fairly sure that would apply to both large and small roundabouts, and would be similar in other countries.

For maxspeed, I dont think it makes sense on roundabouts except for very large scale junctions; and even then its difficult to decide which entry road defines the maxspeed.

**Comment by HolgerJeromin** [comment]
Nice catch. 
Adding `maxspeed=70` to [this roundabout](https://www.openstreetmap.org/way/24033337) seems a bit silly.

**Comment by westnordost** [comment]
Okay, but I don't see why it should not be asked for cycle lanes. Why do cycle lanes end before roundabouts in Australia? Where do the bicycles go then?

For the roundabout that @HolgerJeromin mentioned, there is a cycleway, but mapped separately (so the quest should not show there).

**Comment by CloCkWeRX** [comment]
Typical Australian roundabout:
https://www.mapillary.com/app/?lat=-34.825873411027004&lng=138.48612280333123&z=17&pKey=FFaKsPCXMNn41sNTua2V2A&focus=photo

It's generally signed as 'bike lane ends', and in the road rules you can't generally overtake a cyclist/other traffic.

For something like the typical Dutch separated roundabout, it makes sense to ask
![image](https://user-images.githubusercontent.com/365751/32887929-7a189d88-cb15-11e7-9611-684e8fe46232.png)

https://en.wikipedia.org/wiki/Roundabout#Bicycles lists a few other design approaches taken around the world.

**Comment by westnordost** [comment]
So, I'd say, it _does_ make sense to ask for cycleways on a roundabout.

But I could remove the maxspeed question.

**Comment by HolgerJeromin** [comment]
Have you addressed maxspeed?
