### ISSUE TITLE
Translators are not given enough time or attention

### ISSUE THREAD

**Issue by antonv6** [westnordost/StreetComplete#691]
A couple of exhibits:

1. Filtering and reordering quests was added 13 days ago;
2. Vegan/vegetarian and car wash quests were added 3 days ago;

I was excited to update to 3.0 today only to find that none of these things were actually translated in the interface. Turns out, there are two reasons for that:

- exhibit 2 is not translated because it only today got into POEditor, not sure why it's been so slow, but here we go. I saw it there only 12 or so hours ago. Did other people have enough time to even see it? Well, let's go to https://poeditor.com/join/project/IE4GC127Ki and see that almost every language sits at around 90% on average, only German and English (the source language) is at 100%.
- exhibit 1 is more interesting. Why am I not seeing things I definitely got translated a week ago? Oh yeah, you'll notice that values-ru is not in https://github.com/westnordost/StreetComplete/commit/c78917e8396399b5c028cee6d880978fd451a71a and I bet some other languages too - after all, it only updates 8 files, one of them being values/strings.xml (source).

**Comment by westnordost** [comment]
3.0 is a beta release. Don't expect these releases to have complete translations. Between the first beta release and the first public release, there are minimum 1-2 weeks. After the first beta is out, usually no new terms are added (but I can't guarantee that)

New terms for features are only uploaded to POEditor when the feature is merged to master. This happens only short before the release to beta.

During the beta phase, testers can find and report bugs and translators can see in which context the terms are used and translate them.

On 16 November 2017 16:29:10 CET, Anton Shestakov <notifications@github.com> wrote:
>A couple of exhibits:
>
>1. Filtering and reordering quests was added 13 days ago;
>2. Vegan/vegetarian and car wash quests were added 3 days ago;
>
>I was excited to update to 3.0 today only to find that none of these
>things were actually translated in the interface. Turns out, there are
>two reasons for that:
>
>- exhibit 2 is not translated because it only today got into POEditor,
>not sure why it's been so slow, but here we go. I saw it there only 12
>or so hours ago. Did other people have enough time to even see it?
>Well, let's go to https://poeditor.com/join/project/IE4GC127Ki and see
>that almost every language sits at around 90% on average, only German
>and English (the source language) is at 100%.
>- exhibit 1 is more interesting. Why am I not seeing things I
>definitely got translated a week ago? Oh yeah, you'll notice that
>values-ru is not in
>https://github.com/westnordost/StreetComplete/commit/c78917e8396399b5c028cee6d880978fd451a71a
>and I bet some other languages too - after all, it only updates 8
>files, one of them being values/strings.xml (source).
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/westnordost/StreetComplete/issues/691

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by westnordost** [comment]
Regarding the specific point: I simply forgot yesterday. I saw you online and thought I'd wait a bit before I update Russian since you might be translating right then but in the end forgot to export it overall.

On 16 November 2017 16:29:10 CET, Anton Shestakov <notifications@github.com> wrote:
>A couple of exhibits:
>
>1. Filtering and reordering quests was added 13 days ago;
>2. Vegan/vegetarian and car wash quests were added 3 days ago;
>
>I was excited to update to 3.0 today only to find that none of these
>things were actually translated in the interface. Turns out, there are
>two reasons for that:
>
>- exhibit 2 is not translated because it only today got into POEditor,
>not sure why it's been so slow, but here we go. I saw it there only 12
>or so hours ago. Did other people have enough time to even see it?
>Well, let's go to https://poeditor.com/join/project/IE4GC127Ki and see
>that almost every language sits at around 90% on average, only German
>and English (the source language) is at 100%.
>- exhibit 1 is more interesting. Why am I not seeing things I
>definitely got translated a week ago? Oh yeah, you'll notice that
>values-ru is not in
>https://github.com/westnordost/StreetComplete/commit/c78917e8396399b5c028cee6d880978fd451a71a
>and I bet some other languages too - after all, it only updates 8
>files, one of them being values/strings.xml (source).
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/westnordost/StreetComplete/issues/691

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by antonv6** [comment]
> I simply forgot yesterday

It happens, no problem. I just want to say that things below are not touching this issue.

> 3.0 is a beta release. Don't expect these releases to have complete translations.

That's fine to tell regular users, but think about translators. If they are willing to put work into a release, any release, should they not expect their work to get into that release? Why?

> During the beta phase, testers can find and report bugs

I found a bug: the two last quests are not translated.

> and translators can see in which context the terms are used and translate them.

Personally I feel that context for most things is actually obvious from the wording or based on the string id and it's largely not a problem. But you're right, it does sound great to have something less abstract to work with, except compare

- a beta that allows no time for translators, followed by a release that allows them to do one pass over the UI
- a beta that allows some time for translators so they do one pass, followed by a release that allows a second pass to reword and improve the UI

**Comment by westnordost** [comment]
> I found a bug: the two last quests are not translated.

Hm? Please create a separate ticket for that then, I don't know what you mean.

> except compare
> a beta that allows no time for translators, followed by a release that allows them to do one pass over the UI
> a beta that allows some time for translators so they do one pass, followed by a release that allows a second pass to reword and improve the UI

So basically you advocate that a release should be delayed to wait for translators to catch up.

My priorities are to get things as fast as possible out in the open while at the same time guaranteeing the maximum stability (and decent translation completeness) for stable versions. 
That is why we have the distinction between beta and stable versions. During the time between beta release and stable release, no new features or quests are added (and thus), no new terms are added for translators.
And even though, I try to get out new releases as soon as possible, i.e. @ENT8R 's PR about the car wash quest still took more than two months to find its way into a release (and technically, 3.0 is still not officially released yet, as it is still beta). Adding further delays is really not acceptable for me.

**Comment by antonv6** [comment]
>> I found a bug: the two last quests are not translated.

> Hm? Please create a separate ticket for that then, I don't know what you mean.

This means you released a version to find a bug that was obvious to everybody, including you.

> That is why we have the distinction between beta and stable versions.

I could understand that "3.0-beta" or "3.0-rc" is a beta, even "2.9999" could be a beta. Where is this "distinction" you're talking about? People have already pointed out that you don't use versioning scheme to mark betas, there's no mention of "beta" on 3.0 release page, there's no announcement on poeditor that 3.0 is a beta. You sure know that it's a beta, but where is this distinction that "we have"?

> i.e. @ENT8R 's PR about the car wash quest still took more than two months

And yet you refuse to give a weekend to translators. That's what I'm talking about: not enough time. Look at the current state in poeditor: many languages already are sitting at 99% when this weekend is not yet over. Translators don't need a lot, and you still give none.

> Adding further delays is really not acceptable for me.

Wow, I sure am sorry for criticizing your release cycle, didn't know you had such strict deadlines. Can we see your plan ahead though? Or can we maybe talk some sense into your manager brute who whips your back if you don't release the very same hour that you merge new features?

**Comment by rugk** [comment]
As for the beta: The only indication can be seen on the [GitHub releases page](https://github.com/westnordost/StreetComplete/releases). See https://github.com/westnordost/StreetComplete/issues/622 for details (and how it can be done in a better way/how one could prevent FDroid from building beta versions, when they have a suffix).

**Comment by ENT8R** [comment]
I don't really get your point too:
I think that every person who downloads a beta release of this application can speak at least a little bit english...
And if the terms are then translated in an official release, there is IMO really no problem...

**Comment by rugk** [comment]
Yeah, I'd also say that for beta releases it is okay if they are not fully translated. For stable releases it should work, however…

**Comment by antonv6** [comment]
> for beta releases it is okay if they are not fully translated

That's definitely a convenient opinion to have, since as the things are now, it will happen literally every time a beta is released. The better question is: is it okay to _prevent_ people from translating betas.

**Comment by westnordost** [comment]
Generally, @antonv6 please stay objective about this. We cannot have a meaningful discussion about this if we get abusive. (After all, this is neither the talk-mailinglist nor the German OSM forum ;-) )

I will now answer you thoroughly, please appreciate this.

>  there's no announcement on poeditor that 3.0 is a beta.

As far as I know, there is no announcement at all on poeditor about any kind of versioning.

> I could understand that "3.0-beta" or "3.0-rc" is a beta, even "2.9999" could be a beta. Where is this "distinction" you're talking about? 

Additionally to what @rugk mentioned, everyone who downloads the app from Google play should be aware that something is a beta release, because to subscribe to the beta channel, the user needs to explicitly click a "become a beta tester" button on the storefront.
Judging from your argumentation, I would say that you initially did not know that 3.0 is a beta release. How, though?

> _prevent_ people from translating betas.

I reckon what you mean with "_prevent_" is that new terms are not uploaded to POEditor immediately when the feature is finished. This has several reasons:

1. I assume that translators get some kind of notification when new terms are added. That is why I usually bulk the new translations together for one version. All translators for this project are investing their free time here, so I am trying to be respectful by not triggering new notifications all the time in the same way as posts to a low-traffic mailinglist should happen rarely. (This whole point is based on the assumption that translators actually do get notified automatically.)
2. There is no versioning in POEditor. Oftentimes, the maintenance of a live version (2.x) is still active while the next version is under development. In the new version, new strings may have been added, but also other strings (that are still used in the old version) are deleted or changed. Importing this new strings-version to POEditor and then exporting to an old app version can break that version (already did once), so to be on the safe side, the strings for the new version can only be added when I can reasonably assume that I do not need to make another update for the live version.
3. As opposed to early development of this app, where I was alone and committed everything on master, development is slowly shifting to development in feature branches. Similar to my previous point, this means that at any given point in time during the development of a new feature release, there is never one single strings.xml but multiple versions that each add/remove/change their terms. Only when they are merged on master, they are final, and that's when they can be exported without danger. For 3.0, this happened like a domino-game, because the features were partly based on each other.

**Comment by antonv6** [comment]
> I will now answer you thoroughly, please appreciate this.

I will now appreciate your thorough answers.

> I reckon what you mean with "prevent" is that new terms are not uploaded to POEditor immediately when the feature is finished

No, although it would be nice to have the terms appear there shortly after the feature has been merged into master.

By "prevent" I mean leave no time to translate betas: there's not enough time between strings appearing in POEditor and a release. A decent amount of time would not only allow people to translate new things now and then see them live (see my point about a second pass), but it also would not discourage them from doing it quickly (because right now their work won't make it into beta anyway). Translations may always drag behind the development version, that's their nature, but in this case it's just artificially made worse.

> I assume that translators get some kind of notification when new terms are added.

No, there are no notifications, not for strings added, not for strings changed, you in fact can't see any history of the original strings, there are only notifications for comments and coordinator messages.

> That is why I usually bulk the new translations together for one version.

> Only when they are merged on master, they are final, and that's when they can be exported without danger.

I'm afraid to ask, but is export and import on POEditor all manual?

**Comment by westnordost** [comment]
> [Time should be given between last translation change and first beta release]

Well, I guess we have different opinions about this. But consider especially early beta versions will get updates pretty quickly with the first feedbacks and bugs coming in. In fact, I will do an update to 3.1 in an hour or so.

> No, there are no notifications, not for strings added, not for strings changed, you in fact can't see any history of the original strings, there are only notifications for comments and coordinator messages.

Hmm, this changes things. Could you double-check if you not just disabled it somewhere in the options?

> I'm afraid to ask, but is export and import on POEditor all manual?

Yes.

**Comment by westnordost** [comment]
Also, but you got the manual notification I sent Friday or Saturday on POEditor, right?

**Comment by rugk** [comment]
You _can_ configure POEditor to automatically sync files when you make changes on GitHUb. See https://poeditor.com/help/how_to_use_the_github_webhook

**Comment by westnordost** [comment]
I know, but see point 2 and in particular, 3. I rather not do that. It is not as if I forget to export it to POEditor. Also, exporting to there is done in 1 minute or so, that is really not the problem.

**Comment by westnordost** [comment]
So, I will close this. But I will consider using a different versioning theme for v4 to make clear that something is a beta.
Also, since I will be gone the whole of December, getting a beta out was a bit rushed for v3 anyway.
