### ISSUE TITLE
Reordering only save the first drop of the quest

### ISSUE THREAD

**Issue by Dostoi** [westnordost/StreetComplete#693]
If you move a quest order several time, the app will only register the first position where you drop it.

For example I wanted to put a quest at the bottom of the order and had to drag and drop it several time as my screen was too small to do it in one go and I noticed that the app only register the first drop of the quest. So you have to come back to the main menu, then drop it, then go back to the main menu, then drop and so on until you've dropped it where you wanted.

With the 3.0 version

**Comment by westnordost** [comment]
Damn, can reproduce this... :-(
