### ISSUE TITLE
Enlarge the area where the scroll down is automated in the quest order screen

### ISSUE THREAD

**Issue by Dostoi** [westnordost/StreetComplete#694]
Right now the area where the screen will automatically scroll down in the quest order screen is too small on my phone. It's at the edge of the screen making me drop the quest without wanting too because my finger left the screen.

With the version 3.0 on a samsung galaxy J1 (2016) with android 5.1.1

**Comment by westnordost** [comment]
I am using ItemTouchHelper to manage the drag&dropping of the quests. I did not find any possibility to influence when the view starts to scroll.

However, did you know that you do not actually have to fully leave the bounds to initiate the scrolling? The scrolling will start slowly, then gain speed.

What I will do is to add a tiny blank area at the bottom of the screen, hopefully this solves the problem for you.

**Comment by westnordost** [comment]
So it is just 16dp but I hope already makes the situation better. Going over that will make the window for landscape mode really small.

**Comment by Dostoi** [comment]
Thanks :)

**Comment by Dostoi** [comment]
I tested it with the last version and it didn't change the issue. So I guess you can take it off as it has some downside and no upside
