### ISSUE TITLE
F-Droid built fails since v2.4

### ISSUE THREAD

**Issue by rugk** [westnordost/StreetComplete#695]
v2.4 failed: https://f-droid.org/wiki/page/de.westnordost.streetcomplete/lastbuild_204 (gradle, again)
v3.0 failed: https://f-droid.org/wiki/page/de.westnordost.streetcomplete/lastbuild_300 (okay, that may have been a temporary issue there…)

Seems to be the same as https://gitlab.com/fdroid/fdroiddata/issues/960. Gradle cannot be downloaded from jcenter.bintray.com (404 error).

**Comment by rugk** [comment]
I've opened https://gitlab.com/fdroid/fdroiddata/issues/989 for tracking this.

**Comment by Bubu** [comment]
It's not directly about gradle but about the android gradle plugin. Starting with version 3.0 this plugin is not available from jcenter any more, but only from the google maven repository (which can be included in the build with `google()`). Android Studio seems to silently fix this problem, but it's apparent when calling `./gradlew` from the terminal.

**Comment by westnordost** [comment]
oh, okay. Thanks for the info, you spared me hours of investigative work, @Bubu :-)
