### ISSUE TITLE
Surface of a cycleway (and perhaps footpath)

### ISSUE THREAD

**Issue by pietervdvn** [westnordost/StreetComplete#697]
### General

**Example question**: `What is the surface of this cycleway?`

Not only car drivers like to know the surface of the road - also cyclists are impacted by the surface of a cycleway. A smooth asphalt pavement is more comfortable then a sett surface to drive on.

Therefore I propose to extend the 'surface of road' quest to cycleways as well. 

### Checklist
Checklist for quest suggestions (see guidelines):
- [X] 🚧 To be added tag is established and has a useful purpose
- [X] 🤔 Any answer the user can give must have an equivalent tagging (Quest should not reappear to other users when solved by one)
- [X] 🐿️ Easily answerable by everyone from the outside
- [X] 💤 Not an overwhelming percentage of elements have the same answer (No spam)
- [X] 🕓 Applies to a reasonable number of elements (Worth the effort)

### Ideas for implementation

**Element selection:** ` way["cycleway"]["surface"!~".*"]({{bbox}});`

This quest could be a seperate quest from the surface. The icon could be the same, with a small bicycle overlaid. This way, persons never taking the bike can disable it.

**Proposed GUI:** same as surface quest

**Comment by ENT8R** [comment]
Duplicate of #133

**Comment by pietervdvn** [comment]
Just saw the same. Missed #133 as it missed the keyword cycleway.
