### ISSUE TITLE
FDoid Update 0.4-0.5

### ISSUE THREAD

**Issue by ax3l** [westnordost/StreetComplete#70]
First all all: thank you for this great app!

I updated from StreetComplete 0.4 to 0.5 today and starting the app afterwards resulted in a opened window which was then quickly closed again. Closing the app via force quit and starting again did not solve it. Ultimately, I had to remove it, install it again and add my OSM credentials for oauth again.

Might there be a bug in updating?

System: Android 7.1.1 / OxygenOS-Version 4.1.0

**Comment by westnordost** [comment]
Several people now reported this issue. This is bad, and I do not have a clue yet where this is coming from, as I didn't change anything in the DB.

I will try to reproduce this using the builds from F-Droid. As it has very likely something to do with getting data from DB, can you tell me the area you scanned for quests *before* upgrading to 0.5?

**Comment by ax3l** [comment]
Sure, I scanned in Dresden (äußere Neustadt), Germany.

**Comment by westnordost** [comment]
Hmm, I cannot reproduce it, taking the repos version 0.4, downloading quests at Dresden Neustadt and then taking the master version (0.5+).

**Comment by ax3l** [comment]
Hm, idk how to help with that. I will simply report again if it happens with the next update, too.

**Comment by westnordost** [comment]
ok

**Comment by aracnus** [comment]
Just for the records, I had the same problem here: version 0.5, Android 6.0.1 (ResurrectionRemix). Version 0.4 from F-Droid was working without problems, but couldn't open 0.5. Reinstalled it and everything is fine. I'm scanning from Belo Horizonte - MG, Brazil.

**Comment by andreas-breitbach** [comment]
Also just for the record: Celaning Cache and removing the previous version before installing 0.5 helped here as well. Scanning from Simmern/Hunsrück, Germany.

**Comment by aracnus** [comment]
Just for the records, I had the same problem here: version 0.5, Android 6.0.1 (ResurrectionRemix). Version 0.4 from F-Droid was working without problems, but couldn't open 0.5. Reinstalled it and everything is fine. I'm scanning from Belo Horizonte - MG, Brazil.

**Comment by Undearius** [comment]
[Logcat on PasteBin](https://pastebin.com/NPkUveLA)

I've included a Logcat just after the app crashes from opening. Hopefully it can provide some useful information

**Comment by westnordost** [comment]
I had a look into the logs, thank you. It is the same error I fixed already, invalid quests. If this happens again for the next version, the app will not crash and instead log which quests it could not fetch from database.
