### ISSUE TITLE
Explicitly state in cycleway quest that both sides need to be filled in

### ISSUE THREAD

**Issue by boute002** [westnordost/StreetComplete#700]
After selecting the appropriate picture in the quest: "is there a cycleway in this street?" and clicking OK to confirm my choice, I get an error stating "you left the form empty". I did tried it today and yesterday with the same result. Please check if there is a bug in the script.

**Comment by westnordost** [comment]
Which version are you using?

Also, how did the form look like? Did it show only one side or both sides? In the second case, did you actually select both sides?

**Comment by westnordost** [comment]
I cannot reproduce this with the current version. My guess is that you perhaps only selected one side? Should the app give a more explicit error message (like "You need to specify both sides"?)

**Comment by stulli** [comment]
I had the same problem but it has been resolved after a couple of days for unknown reasons.

**Comment by tom-hills** [comment]
I had this issue too using 3.1 on a OnePlus 2. I tried several different options but none worked. 

I then worked it out - you need to do both sides of the road. This is not clear in the instructions. But it works now!

**Comment by tom-hills** [comment]
A shortcut for none on both sides, or a way to do both directions at the same time, may also make mapping more efficient.

**Comment by westnordost** [comment]
@tom-hills I had this in an early version of the implementation, by clicking roughly in the center of the road. It however turned out to be not good UX, because it was not self-explanatory and the click area was too slim and there was also no feedback for it.

**Comment by tom-hills** [comment]
@westnordost fair enough!

By the way, I love your project. StreetComplete makes mapping in OSM so much easier and fun! I sit on the bus and look out for cycle lanes, lamp posts, road surfaces...

Please keep it up, you're awesome :) Is there any way to contribute financially to the project?

**Comment by boute002** [comment]
The problem is indeed that you need to repeat the form for both directions. It might be indeed a good idea to add an instruction to this like "note the you need to fill both directions to complete the form"

**Comment by westnordost** [comment]
Ok I will add a custom error message that says that one needs to fill both sides to solve the quest.

@tom-hills Thank you very much :-) The project does not run on money, so you cannot support the project financially.

**Comment by boute002** [comment]
Thank you Tobias

Op 21 nov. 2017 20:17 schreef "Tobias Zwick" <notifications@github.com>:

**Comment by rugk** [comment]
> @tom-hills Thank you very much :-) The project does not run on money, so you cannot support the project financially.

Off-topic, but do you really don't want to try something like https://liberapay.com/? I like their concept quite much… And even if one just sends you one cent per week… 😃
