### ISSUE TITLE
Undo quest resolution

### ISSUE THREAD

**Issue by Phyks** [westnordost/StreetComplete#701]
Hi,

Sometimes one may fatfinger a quest solution. It would be really cool to be able to undo the quest resolution in such cases (rather than having to go on OSM editor to fix it afterwards, which I fear most newcomers to OSM may not do).

For the implementation, when mapping in 3G quests are not sent immediately. Then, giving access to this queue might be a quite efficient compromise?

Thanks

**Comment by rugk** [comment]
This is already implemented. There is an "back" arrow in the top right.
Maybe update your StreetComplete version. Which version do you use?

**Comment by westnordost** [comment]
See rugk

**Comment by Phyks** [comment]
Oh indeed, I was out of date, thanks!

Sorry for the noise :/

**Comment by Phyks** [comment]
Just another note on this. When clicking undo (maybe long-click?) it could be useful to have access to the list of undoable things to undo something else than the last quest solved.

This is useful for instance when tagging speed limits in an area and realizing afterwards that we missed a "speed area" sign. Very often, the user will also have tagged cycle lanes and lights for these streets and which to undo only the speed limits for the last 2/3 streets.

**Comment by westnordost** [comment]
Do you have an idea for the UI for this? How to tell one undo-entry apart from another?

Am 2. Januar 2018 12:53:02 MEZ schrieb Lucas Verney <notifications@github.com>:
>Just another note on this. When clicking undo (maybe long-click?) it
>could be useful to have access to the list of undoable things to undo
>something else than the last quest solved.
>
>This is useful for instance when tagging speed limits in an area and
>realizing afterwards that we missed a "speed area" sign. Very often,
>the user will also have tagged cycle lanes and lights for these streets
>and which to undo only the speed limits for the last 2/3 streets.
>
>-- 
>You are receiving this because you modified the open/close state.
>Reply to this email directly or view it on GitHub:
>https://github.com/westnordost/StreetComplete/issues/701#issuecomment-354751521

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by Phyks** [comment]
The idea I have for now would be that a long click on undo would open some new panel showing last lines of history (maybe 10?). Then, user cloud swipe any of them to undo it.

**Comment by rugk** [comment]
Could you either open a new issue for that or reopen this issue… (I'd prefer the former to keep it clean.)

**Comment by Phyks** [comment]
Sure!
