### ISSUE TITLE
better prefill opening hours menu days menu

### ISSUE THREAD

**Issue by matkoniecz** [westnordost/StreetComplete#702]
Tested in country with 5 regularShoppingDays

To add opening hours in Poland I typically need to:

- select quest
- select button "add opening hours"
- add opening hours data for workweek
- select button
- manually select Saturday (1)
- add opening hours data
- finish if object is closed on Sunday, otherwise
- select button
- manually select Sunday (2)
- add opening hours data

Maybe (1) and (2) may be done automatically?

At least in my experience this is anyway done in 98% of cases.

Especially, if every day already has time set and user selected button again then typically the last one day may be pulled.

Main problem is that it may be different in various countries so it may require country config.

----

Proposed logic: if user already added some opening hours data and no day has multiple rules added and there is at least one day without rule - then autoselect first day that has no opening hours data.

**Comment by westnordost** [comment]
(2) should be done automatically.

For (1), you can make a pull request. Just remove the entry for Poland here or set it to 6 explicitly. https://github.com/westnordost/StreetComplete/blob/master/res/country_metadata/regularShoppingDays.yml

**Comment by westnordost** [comment]
> Proposed logic: if user already added some opening hours data and no day has multiple rules added and there is at least one day without rule - then autoselect first day that has no opening hours data.

So are you sure this is not the case yet?

**Comment by matkoniecz** [comment]
> For (1), you can make a pull request. Just remove the entry for Poland here or set it to 6 explicitly. 

AFAIK it would make things worse.

"unselect Saturday" would be necessary before "add opening hours data for workweek", and (1) would be still necessary (Mon-Friday and Sunday typically have different opening hours).

**Comment by westnordost** [comment]
Then I don't get what you mean. Isn't your point for (1) that Saturday should be preselected?

**Comment by matkoniecz** [comment]
In my experience adding opening hours data requires three steps

1) adding workweek - I expect workweek to be preselected (and it is, workweek is defined in regularShoppingDays)
2) adding Saturday - I expect Saturday and only Saturday to preselected (currently nothing is preselected)
2) adding Sunday - I expect Sunday and only Sunday to preselected (currently nothing is preselected)

**Comment by matkoniecz** [comment]
If I am explaining it poorly - maybe screen recording would be helpful?

**Comment by westnordost** [comment]
Okay, I get it.

I think I remember that I implemented it like this initially. I think I did that because in many countries, especially outside of bigger cities, opening hours are often a bit more "wacky", i.e. like "Monday to Thursday 8-12, Tuesday and Thursday 14 - 16, Friday 10 - 12", thus, requiring the user to have multiple entries (3 in this example) for the work week. If the quest would preselect already Saturday on the second selection of workdays, this would be irritating in these cases. In doubt, I'd rather have less intelligence than intelligence gets things wrong often. For people that live in those smaller towns, that would definitely be often.
Also, preselecting those days of the work week that haven't been selected yet can get it wrong, as my example above illustrates already.

**Comment by matkoniecz** [comment]
> In doubt, I'd rather have less intelligence than intelligence that gets things wrong often.

I know, I am frequently frustrated by programs that are trying to be smart and end as "smart".

>  If the quest would preselect already Saturday on the second selection of workdays, this would be irritating in these cases.

I think that proposed logic would not be so bad - with "and no day has multiple rules" it would be irritating only once

- adding "Monday to Thursday 8-12" is affected by default prefill (that is OK as this day range is unusual)
- adding "Tuesday and Thursday 14 - 16" is affected by proposed prefiil
 - adding "Friday 10 - 12" is not affected as "no day has multiple rules added" rule is triggered.

I would expect that overall it would save much more clicks that wasted and it would be worth adding that - but maybe one should verify opening hours data before claiming that? I found http://openingh.openstreetmap.de/stats/ but it is not helpful in figuring typical opening hours format...

**Comment by matkoniecz** [comment]
I thought about automatic detecting of common opening hours tagging method and prefilling based on that - for example, in region with "Monday to Thursday 8-12, Tuesday and Thursday 14 - 16, Friday 10 - 12" prefill would be disabled, in regions where "shop open from X to Y every day" prefill would default to full week, in regions with "Saturday, Sunday, Monday from X to Y, otherwise A to B" first prefill would include Sat, Sun, Mon, second prefill would include all four days.

But it may be an overkill for a limited benefit...

**Comment by westnordost** [comment]
> But it may be an overkill for a limited benefit...

Yes. Because how would you find out these "regions"? StreetComplete can only distinguish between countries, not between urban areas and countryside.

**Comment by westnordost** [comment]
So, I will close this.
