### ISSUE TITLE
make opening hours less tedious by removing button

### ISSUE THREAD

**Issue by matkoniecz** [westnordost/StreetComplete#703]
To add opening hours I typically need to:

- select quest
- select button "add opening hours" (1)
- add opening hours data for workweek
- select button (1)
- manually select Saturday
- add opening hours data
- finish if object is closed on Sunday, otherwise
- select button (1)
- manually select Sunday
- add opening hours data

Would it be possible to merge day selection menu into initial screen, what would remove need to have "add opening hours" button what would reduce needed clicks to complete quest.

**Comment by westnordost** [comment]
I don't know what you mean.

**Comment by westnordost** [comment]
Ping
