### ISSUE TITLE
reconsider cheese icon for vegetarian quest

### ISSUE THREAD

**Issue by matkoniecz** [westnordost/StreetComplete#705]
Typical cheese is not vegetarian

> Rennet is used in the production of most cheeses. (...) Deep-frozen stomachs are milled and put into an enzyme-extracting solution. The crude rennet extract is then activated by adding acid

https://en.wikipedia.org/wiki/Rennet#Modern_method

**Comment by westnordost** [comment]
Good that vegetarians just eat the cheese and not those deep-frozen stomachs then.

Anyway, I won't change this.

**Comment by rugk** [comment]
Oh, many vegans will _really_ dislike that statement… 

But if someone stumbles over this issue again: Please propose a solution, i.e. a better icon. Only complaining is not that effective.:smile:
