### ISSUE TITLE
Maintainer not available until January

### ISSUE THREAD

**Issue by westnordost** [westnordost/StreetComplete#708]
Hey guys, I am out for the whole of December, so I will not be able to reply to any requests etc.

Perhaps I will continue my [travel blog](http://www.westnordost.de/blog), if you want to follow me.

**Comment by rugk** [comment]
Great! I am sure you'll map some stuff. 😃 

BTW instead of this crazy tagging, you could also just add one special tag `----------important-----------` or so (if that's possible) – that would also draw enough attention, but does not hurt my eyes so much. 😉

**Comment by Mannshoch** [comment]
Hi westnordost
I wish you a really nice journey. And because you ar also on tour at Christmas. I wish you am Mapy.., errm.. Marry Christmas.

I would like to use this thread to thank you much for your work on these bit of Software. I'm curious where this Software goes in future.

Have a nice Time

**Comment by westnordost** [comment]
Ok I'm back. I am also writing up about my travel now on http://www.westnordost.de/blog if anyone is interested.
