### ISSUE TITLE
Cycleway quest crashes app on highways where area=yes

### ISSUE THREAD

**Issue by Stigjb** [westnordost/StreetComplete#711]
Discovered this on this residential road: http://www.openstreetmap.org/way/115886432
The cycleway quest shows up on this road segment, but clicking it immediately crashes the app. I assume this is because the road is tagged as area=yes. It would probably make sense to disable the quest on such roads.

On Android 6.0.1

**Comment by westnordost** [comment]
Did not know that this is legal. Yes, it should ignore roads that are areas, I suppose.
