### ISSUE TITLE
Add housenumber quest should be disabled for Italy

### ISSUE THREAD

**Issue by musuruan** [westnordost/StreetComplete#714]
In Italy, a housenumber is associated to an entrance (building entrances, gates, garages, etc). Therefore addresses should be tagged as nodes, and should not be part of the building. I think StreetComplete should not offer the add-housenumber quest in Italy (as it has been already done for other countries).

**Comment by musuruan** [comment]
More info about housenumbers in Italy can be found in the following publication (in Italian):
https://rnc.istat.it/DOCUMENTI/Manuale_per_le_operazioni_sul_campo.pdf

**Comment by HolgerJeromin** [comment]
this app checks for numbers on nodes on the outline or inside the building outline. 
But on gates (outside a building) is not covered IMO.

**Comment by westnordost** [comment]
Yes, @HolgerJeromin is right, if in OSM in Italy, housenumbers are mapped on the gate to a property, the housenumber quest will create lots of false positives and thus should be disabled. Which is a pity, but can't be helped. Even when #351 is implemented, it would need to stay disabled, I fear.

@musuruan could you provide a link to the OSM wiki/forum/mailinglist where it is documented that addresses in Italy should be recorded that way or/and show an instance where it is done this way?

**Comment by musuruan** [comment]
Hi Tobias, 
according to Italian Law _"Address numbering is constituted by the numbers that distinguish the external accesses, i.e. those that from the circulation area enter, directly or indirectly, to the houses, shops, offices, etc..."_

Address numbering must be carried out by Municipalities in accordance with the standards established by [ISTAT](http://www.istat.it/) (Istituto Nazionale di Statitica)

The full text on how to perform this task is available (in Italian) in this [document](http://www.agenziaentrate.gov.it/wps/file/Nsilib/Nsi/Schede/FabbricatiTerreni/Portale+per+i+Comuni/Servizi+portale+dei+comuni/toponomastica/Informativa+Istat/Informativa+Istat+ANSC+del+6+maggio_AGGIORNAMENTO+27_11_2014.pdf) in the section "NOTE DI CARATTERE GENERALE RELATIVE ALLA COMPILAZIONE DELL’INDIRIZZARIO".

I tried to find a German text (which _may_ have been made for our German speaking minorities) but I couldn't find it.

The OpenStreeMap wiki is not yet updated with these data. I hope to update it in the coming days. Right now the topic on the [talk-it](https://lists.openstreetmap.org/listinfo/talk-it) mailing list is about street names.

Latest threads about house numbering in Italy:
[Import numeri civici Trento](https://lists.openstreetmap.org/pipermail/talk-it/2017-September/060263.html)
[import numeri civici Regione Toscana](https://lists.openstreetmap.org/pipermail/talk-it/2017-June/059038.html)
[mappiamo i civici](https://lists.openstreetmap.org/pipermail/talk-it/2016-September/055188.html)

**Comment by westnordost** [comment]
Okay, thank you for the heads-up. Let me know when it is properly documented in the wiki.

I intend to do a bugfix update in the next days, this ticket could be part of it. But I really want some link to documentation I can include in the commit for traceability. The linked threads from the mailing lists mostly concerned data imports from ISTAT, this does not necessarily mean that it [mapping housenumbers on gates] is the recommended practice in Italy within the OSM project.

**Comment by nightflyer73** [comment]
The first two threads are about importing data from a Municipality and a Region, not from ISTAT. These open data follow ISTAT rules. In fact you can see that addresses are always on nodes and never on areas (i.e. buildings). 

Please note that addresses can be also placed on entrance doors, garages, etc. Non just gates. 

A building can have more than one entrance and - according to ISTAT rules - each entrance must have a *different* address. Even two adjacent entrances separated by some kind of wall structure must have two different addresses (refer to figure 5 page 23 of the "NOTE DI CARATTERE GENERALE RELATIVE ALLA COMPILAZIONE DELL’INDIRIZZARIO"). That is why placing addresses on building is a nonsense in Italy.

The last thread does talk about mapping address number. You can see that the focus is always on nodes. E.g.:
https://lists.openstreetmap.org/pipermail/talk-it/2016-September/055195.html

I'll let you know when the wiki is updated.

**Comment by westnordost** [comment]
> Please note that addresses can be also placed on entrance doors, garages, etc. Non just gates.

Yes, I know. But it is only the gates that are the issue for StreetComplete, the other things is something the app can handle. See https://github.com/westnordost/StreetComplete/issues/714#issuecomment-348579672 .

**Comment by althio** [comment]
I opened a similar subject on talk-fr because I think the mapping practices in France are also difficult to handle for StreetComplete.

The community allows all types of geometry as valid:
- isolated nodes (gates, entrances of parcel...)
- nodes that are parts of building polygons (entrances of building...)
- building polygons
- polygons representing the perimeter (site, parcel

https://wiki.openstreetmap.org/wiki/Adresses / https://wiki.openstreetmap.org/wiki/FR:Adresses
https://wiki.openstreetmap.org/wiki/WikiProject_France/Cadastre/Import_semi-automatique_des_adresses

Hopefully more information soon after the discussion.

**Comment by westnordost** [comment]
Well, no further reply -> close

**Comment by musuruan** [comment]
I'm sorry, I totally forgot about this.

Addresses in Italy are described here in the wiki:
https://wiki.openstreetmap.org/wiki/IT:Addresses#Regole_specifiche_per_l.27Italia

The related discussion on talk-it is archived here:
https://lists.openstreetmap.org/pipermail/talk-it/2018-January/061775.html

**Comment by westnordost** [comment]
I skimmed through the talk archives, but it seemed to mainly deal with how to write names. I will just ask very straightforward on the mailing list now.
