### ISSUE TITLE
Small portions of streets

### ISSUE THREAD

**Issue by Phyks** [westnordost/StreetComplete#715]
Hi,

In France, in Paris, very often there are small portions of streets in OSM connecting two larger portions, whereas it is actually a single physical street. See for instance https://www.openstreetmap.org/way/140033649#map=19/48.84118/2.38965&layers=N. Looking at the map, it is obvious that this segment is part of "Avenue Daumesnil" with neighbouring segments.

StreetComplete asks to fill-in quests for every segments of the street, including this small portion, and that's usually fine. However, it could be sometimes quite unclear for a total newcomer how to best fill-in these quests. For instance, for speed limits, should they fill-in the speed only on the segment where the sign physically is (and set "No sign" on any other segments)? Or extrapolate from the signs in the real world to set the correct speed limits accordingly?

**Comment by matkoniecz** [comment]
> For instance, for speed limits, should they fill-in the speed only on the segment where the sign physically is (and set "No sign" on any other segments)? Or extrapolate from the signs in the real world to set the correct speed limits accordingly?

Is "What is the speed limit sign for this street?" a clear question? At least for me it is (for start, it is worth checking whatever it may be a translation issue).

**Comment by Phyks** [comment]
Actually, the issue lies in the fact that there is an option called "no sign", I think. For someone not having any knowledge of the way speed limits are tagged in OSM, they will assume that "no sign" is a special tagging, whereas actually it boils down to tagging "default urban/extra-urban speed limit".

So, basically, I would naively tend to tag "no sign" if there is no sign on this portion of street, thinking it just means that there is no sign and anyone using OSM data as to extrapolate the speed from connecting segments on their own. Obviously, that's a wrong approach.

My proposal to reword [the note displayed on clicking "no sign"](https://github.com/westnordost/StreetComplete/blob/fb3f6ccddf64e35ecb1576a7cb13471474d775f5/app/src/main/res/values/strings.xml#L211-L212) to emphasize that one should extrapolate values from signs nearby. Something like (roughly, English is not my mother tongue so I guess it's far from perfect)

> Did you check at the ends of the street?
> 
> If the sign is not directly on the higlighted segment, but applies to this segment of street, you should fill in the speed. If there are no signs along the street, default speed limits apply. Click "OK" to apply default speed limits.

**Comment by westnordost** [comment]
Makes sense, I'll reword it. (marking as bug so I know I can take immediate action as soon as I get to my computer)

**Comment by westnordost** [comment]
I think this should be clear and concise:
_"Did you check at the ends of the street?
If there are no signs along the whole street which apply for the highlighted section, default speed limits apply."_

**Comment by Phyks** [comment]
:+1: Thanks!
