### ISSUE TITLE
Incoroporating Bitcoin rewards

### ISSUE THREAD

**Issue by slackline** [westnordost/StreetComplete#716]
Hi,

 I've been using for a while now both around the city I live and when travelling and I've some spare time.  Really like being able to contribute in a small way to a much needed free and open alternative to GoogleMaps/Bing, thank you.

I read with interest this article on [Mark your street asphalted and earn Bitcoins](http://www.thomas-liebig.eu/wordpress/mark-your-street-asphalted-and-earn-bitcoins/) and immediately thought of StreetComplete which it might be possible to extend and incorporate such functionality.  This would be really neat and I would have no objection to a percentage being taken by the StreetComplete dev(s) at all.

Just a thought, but figured it would further encourage use and at the same time increase revenue from StreetComplete development.

slackline

**Comment by rugk** [comment]
Well… in OsmAnd the money seems to comes from users buying OsmLive subscriptions. StreetComplete does not have this, so where should the money come from?

**Comment by slackline** [comment]
Ah, I had read that that was where the money was coming from but hadn't clocked that repayment is limited to those with subscriptions.

Not much point leaving this open then.

**Comment by slackline** [comment]
Actually I've just re-read the [official page](https://www.osmand.net/osm_live#report) and whilst the source of funds is from OsmLive subscriptions there is nothing there to say that payments are limited to those who are subscribed.

Since we authorise our OSM account from StreetComplete I don't think there is any barrier to receiving payments via StreetComplete, providing a Bitcoin address has been associated with the account.

**Comment by rugk** [comment]
So what? As far as I see you can sign up there and OsmAnd will consider all edits (no matter with which application they are done) for their cashout. So if you want to do that, go ahead…

But what does this has to do with StreetComplete?

**Comment by slackline** [comment]
> I would have no objection to a percentage being taken by the StreetComplete dev(s) at all.

If there is a way of incorporating automatic payment of a proportion of earnings to the StreetComplete  devs.

Just an idea, please do carry on shooting it down.

**Comment by westnordost** [comment]
Definitely not! That's a very dangerous road to take, it is just asking for fake data.

**Comment by slackline** [comment]
Fair-dos, thanks for a rational reason as to why not.

**Comment by westnordost** [comment]
Was that sarcasm? I am on a travel and on mobile. But I think it should not require great creativism to think of what are the dangers if one gives other incentives for mapping than simple renown.

**Comment by ns-ctru** [comment]
Not at all, its a good rational reason of why not to use financial gains to incentivise contribution to open-source projects and  more informative and reasonable than other comments to my suggestion.

Thank you for taking the time to respond.
