### ISSUE TITLE
support oneway:bicycle=no also for cases where only contraflow infrastructure is present

### ISSUE THREAD

**Issue by matkoniecz** [westnordost/StreetComplete#717]
In some cases answering "Add whether there are cycleways" quest allows to set oneway:bicycle=no.

In general iff road has oneway=yes and cycleway:left is set to something other than `none` the oneway:bicycle may be set to no.

For example see https://www.openstreetmap.org/way/24525611/history at version 16 with http://www.openstreetmap.org/changeset/54435511

**Comment by matkoniecz** [comment]
From looking at https://github.com/westnordost/StreetComplete/blob/686c2bbd798797550673dd82746084158b426af0/app/src/main/java/de/westnordost/streetcomplete/quests/bikeway/AddCyclewayForm.java#L174 it seems that problem is cause by 

> leftSide != null && rightSide != null

Contraflow may be present without any special infrastructure in direction where both cyclists and general traffic are allowed.

**Comment by westnordost** [comment]
oneway:bicycle=no is only set if the contraflow cycleway is set to either track or lane. 

To set the contraflow cycleway to shared lane is definitely wrong for the case of a oneway road that is simply not a oneway for bicycles. Shared lane should probably not even be an answer option in the case of oneways.
The quest explicitly asks for the existance of a cycleway, not wether a road is a oneway not for bicycles.

**Comment by matkoniecz** [comment]
This road is case of https://github.com/westnordost/StreetComplete/pull/671#issuecomment-341564363 - https://user-images.githubusercontent.com/899988/32351387-7c7e1114-c01d-11e7-8411-33ea1ec4c23e.jpeg

Oneway for vehicles, not oneway for cyclists, with bike pictograms markings in direction of contraflow.

It is not a lane like https://github.com/westnordost/StreetComplete/pull/671#issuecomment-341563931 https://user-images.githubusercontent.com/899988/32351334-459bf2ec-c01d-11e7-9df9-fa1deb00c489.JPG so selecting lane answer is incorrect.

I think that there is no good answer in what SC provides but in https://github.com/westnordost/StreetComplete/pull/671#issuecomment-341566092 you mentioned that shared lane should be used as an answer.

**Comment by westnordost** [comment]
Hmm okay, so the shared lane marking is used (in some places) also for oneway roads that allow contraflow bicycle traffic.

Two options how to solve this:
1. As you suggest, fixing the oneway:bicycle logic to at least include shared_lane -> the contraflow bicycle traffic would be tagged as shared lane as well in places where the road markings like that are there. mapping WYSIWYG style, even though it is debatable if that situation counts as shared lane as there is no other traffic the lane is shared with, right?
2. Showing a different label for the shared lane option in the contraflow case like "no cycleway, but no oneway road for cyclists" and only tagging oneway:bicycle=yes

Let's say the shared lane marking is not there but only a sign at one end of this road (Germany), then I guess option 1 wouldn't be obvious for the users, instead they'd simply select "no", right?

**Comment by matkoniecz** [comment]
> even though it is debatable if that situation counts as shared lane as there is no other traffic the lane is shared with, right?

I agree, that is the problem that I attempted to report in https://github.com/westnordost/StreetComplete/pull/671#issuecomment-341567330

Personally I tag such cases as cycleway=opposite (and I think that cycleway:left=opposite is also ok)

> Showing a different label for the shared lane option in the contraflow case like "no cycleway, but no oneway road for cyclists" and only tagging oneway:bicycle=yes

Seems to be a good idea. Though I would suggest "no cycleway, cyclists may use road in both directions" as more clear and with lower amount of negations.

And I think that *=opposite is better than leaving it blank.

> Let's say the shared lane marking is not there but only a sign at one end of this road (Germany), then I guess option 1 wouldn't be obvious for the users, instead they'd simply select "no", right?

I agree.

**Comment by westnordost** [comment]
> And I think that *=opposite is better than leaving it blank.

I am not a friend of duplicating information. I will not leave it blank, it will be cycleway:left=no.
