### ISSUE TITLE
Cycleway quest: Don't ask for cycleway with separately mapped sidewalk

### ISSUE THREAD

**Issue by westnordost** [westnordost/StreetComplete#718]
The app currently does not ask is users for the existance of a cycleway if a separately mapped cycleway exists in the vicinity.
However, it should also not ask if that separately mapped way is a sidewalk only (without cycleway).

**Comment by matkoniecz** [comment]
>  However, it should also not ask if that separately mapped way is a sidewalk only (without cycleway).

What is the reason for that? I am unable to imagine case where not skipping such cases would qualify as a bug.

**Comment by rugk** [comment]
I think he also wants to exclude the quest when "footways" (no bike!) are nearby.

This would mean if a "footway" is there, no cycleway can be on/at the street. But why not? (Pedestrians often get better "treatment" than bikers, so it is not an unlikely case that there is a footway and a cycleway *on* or *at* the street) I think this is definitively possible, so I agree to @matkoniecz .

**Comment by westnordost** [comment]
Because if a way, be it cycleway or footway (sidewalk) is mapped separately, it means that whether there is a cycleway or not should be asked for that separate way, not for the street.

Am 14. Dezember 2017 23:40:29 GMT+07:00 schrieb Mateusz Konieczny <notifications@github.com>:
>>  However, it should also not ask if that separately mapped way is a
>sidewalk only (without cycleway).
>
>What is the reason for that? I am unable to imagine case where not
>skipping such cases would qualify as a bug.
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/westnordost/StreetComplete/issues/718#issuecomment-351765694

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by rugk** [comment]
You may also ask it there, but in any case the result can still be "No this is a footway, but there is a cycleway on the street nearby.".

**Comment by matkoniecz** [comment]
> Because if a way, be it cycleway or footway (sidewalk) is mapped separately, it means that whether there is a cycleway or not should be asked for that separate way, not for the street.

1) There are many cases where street itself has cycleway property and separate footway not (contraflow lanes etc)

2) It is completely OK to put cycleway tag on a road (cycleway=lane/track/opposite or using SC style tagging cycleway:both=lane/track, cycleway:left=opposite, cycleway:left=opposite_lane )

**Comment by westnordost** [comment]
Perhaps for lanes, shared lanes etc., but every kind of cycleway that is beyond the curb (track, shared sidewalk, etc) should be mapped on that separate way, if the sidewalk is mapped separately, to stay consistent.

Am 15. Dezember 2017 21:16:22 GMT+07:00 schrieb Mateusz Konieczny <notifications@github.com>:
>> Because if a way, be it cycleway or footway (sidewalk) is mapped
>separately, it means that whether there is a cycleway or not should be
>asked for that separate way, not for the street.
>
>1) There are many cases where street itself has cycleway property and
>separate footway not (contraflow lanes etc)
>
>2) It is completely OK to put cycleway tag on a road
>(cycleway=lane/track/opposite or using SC style tagging
>cycleway:both=lane/track, cycleway:left=opposite,
>cycleway:left=opposite_lane )
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/westnordost/StreetComplete/issues/718#issuecomment-352016002

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by rugk** [comment]
>  but every kind of cycleway that is beyond the curb (track, shared sidewalk, etc) should be mapped on that separate way, if the sidewalk is mapped separately

Actually that rather means the footway is already mapped wrongly, because only when it is really separated (by trees or so) it should be mapped separately.

**Comment by westnordost** [comment]
Well, I agree with you there, though I know that this opinion is not shared by everyone - I think i.e. @matkoniecz would object.

But anyway, that is beyond the argument - if the sidewalk/footway that runs parallel to the street is mapped separately, then if the cycleway is not *on* the street (lane, bus lane, shared lane,...), it should be tagged as a property of that separate way, not as a property of the street.

Now, to conclude, the app can of course not know beforehand, whether the user is going to select something like lane ( -> tag on road) or something like track ( -> tag on separate way) and thus there is a chance that the app will tag the property on the wrong element (i.e "track" on the road when a separately mapped sidewalk exists).
To eliminate this, the app needs to be more defensive in for what elements the app shows the quest.

**Comment by matkoniecz** [comment]
> should be mapped on that separate way, if the sidewalk is mapped separately

I encountered this kind of tagging before and while suboptimal I would not describe it as wrong - and I think that it is better that no tagging of cycleway at all (but obviously it is not my decision, I am not one that gets all complaints about poor edits made using app)

**Comment by westnordost** [comment]
Perhaps someone could raise this question on the mailing list / forum to clear that up. I am still on travels, so I don't have time to involve myself in discussions.

I created this issue in response to https://www.openstreetmap.org/changeset/54211276#map=17/51.55301/5.05100

Talked about here https://forum.openstreetmap.org/viewtopic.php?id=60615

Am 15. Dezember 2017 23:22:20 GMT+07:00 schrieb Mateusz Konieczny <notifications@github.com>:
>> should be mapped on that separate way, if the sidewalk is mapped
>separately
>
>I encountered this kind of tagging before and while suboptimal I would
>not describe it as wrong - and I think that it is better that no
>tagging of cycleway at all (but obviously it is not my decision, I am
>not one that gets all complaints about poor edits made using app)
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/westnordost/StreetComplete/issues/718#issuecomment-352047620

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by westnordost** [comment]
Hmm, actually, I think you are right, @matkoniecz . In the described case, tagging on the road instead of the separate way is perhaps suboptimal - as suboptimal as tagging "13-17" as a housenumber on a building with several entrances - but not wrong and definitely adds information.

So, I will not do anything here.

**Comment by westnordost** [comment]
Further thought about that.
Actually, it is still a problem, @matkoniecz . The user may answer _"cyclists share the sidewalk"_, then `sidewalk=X` is tagged on road, which would be wrong if there is a separately mapped way.

**Comment by westnordost** [comment]
So, I wonder, @matkoniecz , do you have an idea what we could do? Otherwise, I guess I must disable the quest for seperately mapped sidewalks.

**Comment by matkoniecz** [comment]
What may happen:

- there is a separately tagged sidewalk, not tagged as available for bicycles
- there is road without cycleway info
- sidewalk is available for cyclists

https://github.com/westnordost/StreetComplete/blob/3d0a08bf274297fc25b0e94c87b0f8c7651810dd/app/src/main/java/de/westnordost/streetcomplete/quests/bikeway/AddCycleway.java#L137 is applied

road ends with cycleway=no, sidewalk:X:bicycle=yes, separately tagged sidewalk is not modified

While this tagging is a bit weird - I personally think still the same about situation:

> I encountered this kind of tagging before and while suboptimal I would not describe it as wrong - and I think that it is better that no tagging of cycleway at all (but obviously it is not my decision, I am not one that gets all complaints about poor edits made using app)

I may ask on tagging list if asking others would be a good idea.

**Comment by westnordost** [comment]
You can do that. But I am pretty sure that in the strict sense, it is definitely wrong. Question is perhaps, how strict we [the community] wants to be.
