### ISSUE TITLE
Impossible to upload changes

### ISSUE THREAD

**Issue by dkocich** [westnordost/StreetComplete#719]
I have a problem with upload of created changes on my Huawei p8 lite.
I made some of them, I was logged in and after the click on upload answers function nothing really happened. I tried it several times and then I tried to repeat the whole process again with cleared application cache/storage and it still did not work. Please tell me if I should provide some more info or if there is any way how to fix this... Thanks.

**Comment by HolgerJeromin** [comment]
Are you sure that you have pending uploads? 

If your topline is something like that:
StreetComplete (staricon) 32
You have NO pending uploads. This would look like this:
StreetComplete (staricon) 32(+2)

**Comment by westnordost** [comment]
See Holger. Your changes have been uploaded automatically already.

I think I should remove the manual upload button and the autosync=off setting, it causes confusion and I don't see the gain in having that.

Am 13. Dezember 2017 01:37:37 GMT+06:30 schrieb David Kocich <notifications@github.com>:
>I have a problem with upload of created changes on my Huawei p8 lite.
>I made some of them, I was logged in and after the click on upload
>answers function nothing really happened. I tried it several times and
>then I tried to repeat the whole process again with cleared application
>cache/storage and it still did not work. Please tell me if I should
>provide some more info or if there is any way how to fix this...
>Thanks.
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/westnordost/StreetComplete/issues/719

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by dkocich** [comment]
Thanks for the help. I think that this is really confusing @westnordost. I managed to find the closed changeset that I was looking for already. It would be good to be able to click on star icon and see the list of changes with status (pending, uploaded). I am probably used to the behaviour of the ID editor where you always have 0 after the upload. Closing.

**Comment by althio** [comment]
For reference, main issue for this is #75 
Maybe waiting for a improvement (pull request might be [proposed](https://github.com/westnordost/StreetComplete/issues/75#issuecomment-344451816) by @errolpais)
