### ISSUE TITLE
Provide a way to access POI metadata (address)

### ISSUE THREAD

**Issue by Phyks** [westnordost/StreetComplete#722]
Hi,

I solved a couple of "opening hours" quests in a very dense area, with lots of shops. Sometimes, it is not easy to spot whether the shop simply disappeared, was renamed or whether my GPS is just buggy and do not point correctly.

I think it could help a lot if there was a way to get more infos about the POI and in particular the exact address.

What do you think?

Thanks!

**Comment by skfd** [comment]
I'd add that marker clustering is too aggressive. many quests are hidden until you zoom way in.

**Comment by westnordost** [comment]
Two issues would need to solved here:
1. Where to display this address?
2. Find a library that formats addr:* tags into human readable format. A library is necessary because in each country, addresses are written differently. I am pretty sure there is a library since this is a very common task.

**Comment by Phyks** [comment]
Maybe there could be a "plus" icon somewhere to open more infos about the POI? Could even be a link to `openstreetmap.org/node/NODE_ID`.

**Comment by Phyks** [comment]
Coming back on this one. Recently, the tile server changed and the new one displays house numbers in the tiles. That's a huge improvement, very helpful I think.

Not sure this issue would add much more value. It could be closed or low priority I guess. Thanks for the work on this!

**Comment by westnordost** [comment]
Wirh pleasure
