### ISSUE TITLE
UI tweaks for cycleway quest

### ISSUE THREAD

**Issue by rugk** [westnordost/StreetComplete#723]
I think for the cycleway quest the direction really matters, as you can add another way on the other site. So in the map there should be an arrow, so you can see which direction you are currently editing.

Also, I hope, by default the right side is added, is not it? That is not obvious from the UI as it shows the cycleway at the top (and the "other side" at the bottom) of that image.

Maybe you can turn this for 90°, so the right side is really right from the users point of view. And the left site is left. This would then also match the road when walking/driving/… the road as it exactly matches the "real world situation" the user is currently seeing.
And when there is e.g. a cycleway only on the left, the user then sees this immediately, instead of maybe inadvertently adding a wrong value. So you could prevent some accidental changes.

Also the user has to be aware not to add the left side cycleway, if the street in the other direction is mapped separately. I don't know a solution for that, maybe we can just assume the user is clever enough to see that (if there are two streets on the map), but it is still a point of failure. Especially as you have to imagine users with no knowledge of OSM – they likely won't know streets can also be mapped separately using one-ways.

So the first two things can be solved with small UI tweaks, the last thing may be more complex and I'd don't argue to change anything there. Just wanting to let you know…

**Comment by westnordost** [comment]
Hu? Wait, did you try to rotate the map?

The street illustration is always rotated exactly like it is displayed on the map.

Am 15. Dezember 2017 00:57:51 GMT+07:00 schrieb rugk <notifications@github.com>:
>I think for the cycleway quest the direction really matters, as you can
>add another way on the other site. So in the map there should be an
>arrow, so you can see which direction you are currently editing.
>
>Also, I hope, by default the right side is added, is not it? That is
>not obvious from the UI as it shows the cycleway at the top (and the
>"other side" at the bottom) of that image.
>
>Maybe you can turn this for 90°, so the right side is really right from
>the users point of view. And the left site is left. This would then
>also match the road when walking/driving/… the road as it exactly
>matches the "real world situation" the user is currently seeing.
>And when there is e.g. a cycleway only on the left, the user then sees
>this immediately, instead of maybe inadvertently adding a wrong value.
>So you could prevent some accidental changes.
>
>Also the user has to be aware not to add the left side cycleway, if the
>street in the other direction is mapped separately. I don't know a
>solution for that, maybe we can just assume the user is clever enough
>to see that (if there are two streets on the map), but it is still a
>point of failure. Especially as you have to imagine users with no
>knowledge of OSM – they likely won't know streets can also be mapped
>separately using one-ways.
>
>So the first two things can be solved with small UI tweaks, the last
>thing may be more complex and I'd don't argue to change anything there.
>Just wanting to let you know…
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/westnordost/StreetComplete/issues/723

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by rugk** [comment]
Ahhh… 😲 did not notice that, you are right. This solves many problems.

**Comment by matkoniecz** [comment]
> So in the map there should be an arrow, so you can see which direction you are currently editing.

Why? Street on map and quest solving screen is oriented in the same way. Maybe with long and windy roads it would be an issue, con you give an example of way that is causing your problems?

**Comment by rugk** [comment]
As you see from my comment above, I did not see that it rotates with the map…

**Comment by westnordost** [comment]
@rugk Also, did you actually try to enter a cycleway for a oneway street (=one part of a dual carriageway)? I already implemented something there

**Comment by rugk** [comment]
No, this did not happen, yet. 😃

**Comment by Phyks** [comment]
> As you see from my comment above, I did not see that it rotates with the map…

Same thing for me, maybe there could be an extra hint in the UI? (sadly, I don't have much ideas about it for the moment :/). Maybe this could be in a form of a getting started / on boarding per quest, giving a bit of doc and background for each quests. This could also maybe solve #715 with no max speed signs. 

Additionally, I know OSM cycleway left/right tagging refers to the orientation of the path. I guess then that StreetComplete automagically handles the conversion between displayed side and path side?

**Comment by rugk** [comment]
> I guess then that StreetComplete automagically handles the conversion between displayed side and path side?

I hope so… 😄

**Comment by westnordost** [comment]
You hope right, it does.

Am 26. Dezember 2017 04:06:10 GMT+07:00 schrieb rugk <notifications@github.com>:
>> I guess then that StreetComplete automagically handles the conversion
>between displayed side and path side?
>
>I hope so… 😄 
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/westnordost/StreetComplete/issues/723#issuecomment-353890778

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by westnordost** [comment]
I could add one sentence at the top, below the question (but this makes the illustration smaller):

"This illustration is rotated the same way as the street appears on the map at the marker position."

Am 26. Dezember 2017 04:02:13 GMT+07:00 schrieb Lucas Verney <notifications@github.com>:
>> As you see from my comment above, I did not see that it rotates with
>the map…
>
>Same thing for me, maybe there could be an extra hint in the UI?
>(sadly, I don't have much ideas about it for the moment :/). Maybe this
>could be in a form of a getting started / on boarding per quest, giving
>a bit of doc and background for each quests. This could also maybe
>solve #715 with no max speed signs. 
>
>Additionally, I know OSM cycleway left/right tagging refers to the
>orientation of the path. I guess then that StreetComplete automagically
>handles the conversion between displayed side and path side?
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/westnordost/StreetComplete/issues/723#issuecomment-353890653

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by Phyks** [comment]
> You hope right, it does.

Cool! Thanks for the confirmation. 

> I could add one sentence at the top, below the question

Not sure how smaller the illustration might get but this might be a nice solution. Other ideas I can offer are having onboarding / per quest help section. Or maybe just a "?" icon with a popup/hint?


BTW, do you think having somewhere (a website for instance, github-hosted) a description and FAQ for each quest could be something interesting? I can't help with Android dev but could help with some doc like this :)

**Comment by rugk** [comment]
> BTW, do you think having somewhere (a website for instance, github-hosted) a description and FAQ for each quest could be something interesting?

You mean something like that? https://wiki.openstreetmap.org/wiki/StreetComplete/Quests

It would be very nice of you to help there. Especially look if new quests are not already documented or so. If you need icons you can get them from [here](https://github.com/rugk/streetcomplete-quest-svgs), most of them should also already be uploaded to the OSM Wiki.

**Comment by westnordost** [comment]
It'd need to be within the app, not a wiki page.
The "?" is a good idea, I will consider it. The best of course would be if the UI can be made self-explanatory. I.e. you will find nowhere a usage help for the Android time selector, even though it is quite complex.

Am 26. Dezember 2017 18:40:54 GMT+07:00 schrieb Lucas Verney <notifications@github.com>:
>> You hope right, it does.
>
>Cool! Thanks for the confirmation. 
>
>> I could add one sentence at the top, below the question
>
>Not sure how smaller the illustration might get but this might be a
>nice solution. Other ideas I can offer are having onboarding / per
>quest help section. Or maybe just a "?" icon with a popup/hint?
>
>
>BTW, do you think having somewhere (a website for instance,
>github-hosted) a description and FAQ for each quest could be something
>interesting? I can't help with Android dev but could help with some doc
>like this :)
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/westnordost/StreetComplete/issues/723#issuecomment-353959108

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by Phyks** [comment]
> You mean something like that? https://wiki.openstreetmap.org/wiki/StreetComplete/Quests

Yes, but there is no link to it from within the app it seems. And I was thinking about having a small FAQ for each quest as well. 

> It'd need to be within the app, not a wiki page.

:+1: or maybe a website with a link from within the app. Having a website would help one in getting a rough idea about the quests StreetComplete offer without installing it. 

> The best of course would be if the UI can be made self-explanatory

:+1: but I guess even the best UI could lead to some questions, especially for OSM-savvy users.

**Comment by rugk** [comment]
So maybe just make a general FAQ? There you can then have a heading "Questions about specific quests" and answer common answers for some quest types, which need this.

**Comment by Phyks** [comment]
@rugk like a "StreetComplete FAQ" page on the OSM wiki? Sure, this could be a nice addition but there should be some reflection of the data in the app IMHO.

I think it would be worth first trying to write up some typical content and see how it would best fit. Sadly, I am stuck with my phone for now, but I will try to gather typical info I have in mind and type something when I get back my laptop, by end of the week. :)

**Comment by Phyks** [comment]
Here is a small write up of what came to mind when thinking about frequently asked questions for SC quests.

StreetComplete quests FAQ
=========================

## Opening hours

### Managing off times (_siesta_)

If you want to specify an off time for a shop, just enter the two opening
periods separately. That is, typically

> Mo-Fr 8-12

and then

> Mo-Fr 16-18

for a shop opened from Monday to Friday, from 8 to 18 and closed between
noon and 16.


### Is there a preferred way to enter opening hours?

OSM [`opening_hours`
syntax](https://wiki.openstreetmap.org/wiki/Key:opening_hours#Values) allows a
given set of opening hours to be written in different ways. StreetComplete
simply builds a valid `opening_hours` tag from the info you enter and there is
no preferred way of entering it.

That is,

> Mon-Fri: 8am-12am, 2pm-6pm
> Sat: 8am-12am

and

> Mon-Sat: 8am-12am
> Mon-Fri: 2pm-6pm

represent the same opening hours. You can enter whatever is more convenient
for you, but the best way is to try to match as closely as possible what is
written on the sign.


## Speed limits

### What to do when there is no sign on a segment?

When there is no speed sign on a segment of a street, you should look at the
whole street and try to see if a speed limit defined outside the segment might
apply. In this case, fill it.

Otherwise, if there is no speed limit and default limit applies, choose the "No
sign" option.

Just keep in mind that clicking "no sign" option in StreetComplete will tag
the street with the default speed limit for urban/extraurban area, so ensure
the street is actually limited to default speed limit before checking it.


## Cycleway quests

### What is the left and right side of the street?

The street in the cycleway quest is oriented the same way as it is in the
main (navigation) view. Then, left side and right side of the streets are
defined according to the orientation (direction of the north) in the main
view and StreetComplete handles automatically the conversion into left and
right side of the path for OSM.

**Comment by westnordost** [comment]
Well, see my last post. A very small percentage of StreetComplete users will actually go to the wiki and read this. Maintaining this kind of in-depth FAQ (in all the languages) within the app is too much effort.

Any input help given to the user - if really absolutely necessary and cannot be solved via intuitive UI design - should be done within the app, but should be concise and to the point.

Now, a (future) FAQ in the wiki has a different focus group, so to say. Especially in the German forum, topics come up regularly which enquire about the inner workings of StreetComplete. Much work here to document StreetComplete behavior for people interested ratjer in the outcome that in how it is to be operated has been done by @rugk already [here](https://wiki.openstreetmap.org/wiki/StreetComplete/Quests). I might add another sub-article to the wiki concerning StreetComplete soon, where I answer frequently asked questions (and concerns).

**Comment by Phyks** [comment]
> Well, see my last post. A very small percentage of StreetComplete users will actually go to the wiki and read this. Maintaining this kind of in-depth FAQ (in all the languages) within the app is too much effort.

I totally agree this would not be super practical ti do within the app. My idea was rather to have a wiki page and a link to it inside the app. But then, the app would no longer be self-consistent. 

> Any input help given to the user - if really absolutely necessary and cannot be solved via intuitive UI design - should be done within the app, but should be concise and to the point.

This draft could be seen as a list of UI points that could be better explanatory then :) not sure how these could be solved easily though. :/

For the cycleway quest, maybe putting a compass icon in the quest panel, matching the navigation compass would help?

**Comment by westnordost** [comment]
> For the cycleway quest, maybe putting a compass icon in the quest panel, matching the navigation compass would help?

Hmm, good idea. I guess this would replace the _"This illustration is rotated the same way as the street appears on the map at the marker position."_ explanation and can fit easily in one corner

**Comment by Phyks** [comment]
Hi,

I juste updated to 3.4 in FDroid, and noticed that although the compass is now shown, the orientation no longer matches the one from the map panel. Is it expected?

![screenshot_20180109-163814](https://user-images.githubusercontent.com/3856586/34731231-0a228ed6-f562-11e7-83f7-5befffb1c8e0.png)

**Comment by matkoniecz** [comment]
@Phyks Can you make screenshoot with entire way? Maybe it is unusually curved...

**Comment by westnordost** [comment]
Whoa, what is that? How can I reproduce this?

**Comment by Phyks** [comment]
Sorry, I won't be able to take a screenshot again there until some time, it's not some place I pass by very often.

The way shown on picture should be [this one](https://www.openstreetmap.org/way/37550639) though, hope this helps :/

**Comment by westnordost** [comment]
I can reproduce this. It happens on the very first time, one opens a quest details.

The orientation of the compass in relation to the road in the form is still correct though, so it is not a critical bug.

**Comment by Phyks** [comment]
> The orientation of the compass in relation to the road in the form is still correct though, so it is not a critical bug.

Sure, this is not critical :) I was mostly wondering whether this was a bug or whether the compass was expected to have a fixed orientation toward north, got the answer :) Thanks for the quick look into this!

**Comment by rugk** [comment]
BTW for reference: Your new issue has been tracked and fixed in https://github.com/westnordost/StreetComplete/issues/760.
