### ISSUE TITLE
Noticable delay when loading new quests or rotating device

### ISSUE THREAD

**Issue by rugk** [westnordost/StreetComplete#724]
When you turn your device or click on the "Fetch quests" button in the menu, first all quest icons disappear and then it takes several seconds until they are shown again.

This delay is really huge and it annoys me when trying to solve some quests in a fast way while hitting the request button to also get new quests if needed. The (background) map is much faster…

v3.2
LineageOS 14.1
Android 7.1.1

**Comment by westnordost** [comment]
Yes, it is a known issue and nothing can be done about that for now.

**Comment by rugk** [comment]
Is it something Tangram-es can do something about?

**Comment by westnordost** [comment]
Yes, if they properly support the use case that StreetComplete uses (showing a mass of markers from a different source on the map).  https://github.com/tangrams/tangram-es/issues/1565

Am 27. Dezember 2017 02:37:04 GMT+07:00 schrieb rugk <notifications@github.com>:
>Is it something Tangram-es can do something about?
>
>-- 
>You are receiving this because you modified the open/close state.
>Reply to this email directly or view it on GitHub:
>https://github.com/westnordost/StreetComplete/issues/724#issuecomment-354005107

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by rugk** [comment]
BTW can anyone reproduce the fact that this delay does _not_ happen for notes (?) quests? I just had a case, where all icons were hidden as usual after solving a quest, but one icon remained: The ? one.
BTW, I have the option to show all notes quests enabled in the settings.
