### ISSUE TITLE
Add a way to edit a building with no quests

### ISSUE THREAD

**Issue by afmenez** [westnordost/StreetComplete#729]
There's always something to add to incomplete streets, but there's no way to edit most of the buildings.  I was walking with the app open, and I could see the house number and number of floors on dozens of buildings, but there was no way to add the information.

**Comment by westnordost** [comment]
House number quests and building levels quests are only shown for certain types of buildings, most prominently not for building=yes. A quest to let users of StreetComplete specify the type of building is in planning #25

Am 18. Dezember 2017 20:00:28 GMT+07:00 schrieb Alexandre Folle de Menezes <notifications@github.com>:
>There's always something to add to incomplete streets, but there's no
>way to edit most of the buildings.  I was walking with the app open,
>and I could see the house number and number of floors on dozens of
>buildings, but there was no way to add the information.
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/westnordost/StreetComplete/issues/729

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by westnordost** [comment]
(question answered i hope)
