### ISSUE TITLE
Feature: solve multiple quests with same solution

### ISSUE THREAD

**Issue by ivarveen** [westnordost/StreetComplete#73]
First, thanks for this nice app! 

Could be helpful if we were able to solve the same type of quest for multiple items on the map. 
For example: set same number of levels for multiple buildings, set same road type for multiple roads, etc. 

Could be implemented with long press on first quest and than regular press on consecutive quests of the same type (hide other quest types?) 

Br, Ivar

**Comment by westnordost** [comment]
Hi Irvaveen
I'm sorry, an advanced editing function like this is not planned. I agree that if this were implemented, the thing with the long press were a good way to integrate it. The app is intended as a surveyor app, so to solve a quest, you are required to actually walk there. If I give users the possibility to mass-solve quests it can affect the quality of the input because there is less of a guarantee that they were really looking. After all, there is no and will not be an "undo" function in case for when you were sure that street was asphalt, but whoops, around the corner there is a cobblestone section.
- Tobias

**Comment by ivarveen** [comment]
Hi Tobias, 
Thanks for your quick reply! I see your point.
Keep up the good work! 
Ivar

**Comment by Bugsbane** [comment]
Just to play Devils advocate, if you really only want people entering data from on foot surveys, then why have the ability to scroll the map at all? Why not just have the map always locked to your current GPS coordinates?

**Comment by westnordost** [comment]
To look around.

I will soon implement, however, that you can only solve quests near your location.

On 12 April 2017 12:13:29 CEST, Bugsbane <notifications@github.com> wrote:
>Just to play Devils advocate, if you really only want people entering
>data from on foot surveys, then why have the ability to scroll the map
>at all? Why not just have the map always locked to your current GPS
>coordinates?
>
>-- 
>You are receiving this because you modified the open/close state.
>Reply to this email directly or view it on GitHub:
>https://github.com/westnordost/StreetComplete/issues/73#issuecomment-293533873

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by HolgerJeromin** [comment]
Often i know very certain which surface a street has. This is not necessary in my current location but i want to fill some minutes while waiting.

**Comment by Piskvor** [comment]
"Offer the last selection" could be an alternative to "answer multiple quests". When mapping in an area, the answers are often (not always) quite homogenous - if a street has surface=asphalt, it is probable that the surrounding streets also will; if a track has surface=compacted, others in the area are also likely to have it.

What exists now:
1. select a road surface quest
2. from the available options (Paved/Unpaved/Ground), choose Paved
3. scroll and choose Asphalt
4. select another road surface quest
5. from the available options, choose Paved
6. scroll and choose Asphalt
repeat from 4 ad infinitum

What would be more efficient:
1. select a road surface quest
2. from the available options, choose Paved
3. scroll and choose Asphalt
4. select another road surface quest
5. choose Asphalt, as the last chosen is offered amongst the first-level options ("Previous: Asphalt"/"Paved"/"Unpaved"/"Ground")
repeat from 4 (less scrolling, less tapping)

Choosing a different option would likewise change it in the first-level menu.

**Comment by HolgerJeromin** [comment]
@Piskvor  very good idea, but should probably go to #170

**Comment by madduck** [comment]
Please do not limit solving quests to your current location. First, this can be easily circumvented, and second, as someone else said: I solved some quests around my home from thousand kilometres away, with certainty.

I suppose you could prevent this by default, but please give us an "expert" checkbox to turn this "feature" off.

**Comment by westnordost** [comment]
Sure, don't worry.

**Comment by westnordost** [comment]
Closing in favor of #76
