### ISSUE TITLE
authentication server not reachable after OAuth procedure => No successful authentication

### ISSUE THREAD

**Issue by huste** [westnordost/StreetComplete#731]
I am on an LG G4 Stylus H-635 with Android 6.0, German locale.

When I try to authenticate StreetComplete via OAuth with my OSM-Account (Einstellungen> OSM-Zugang autorisieren), this happens:
1) The web browser opens and asks me to log in
2) I log in
3) The web site asks for 3 permissions which I grant
4) The web browser closes
5) StreetComplete comes back again and pops up a Toast-message: "Autorisierungsserver kann nicht erreicht werden"

In my OSM-account I can see a newly created OAuth token.

The same happens, no matter if I use Opera or Firefox as default browser.

As a result, I cannot upload anything.

**Comment by westnordost** [comment]
The specific error that occurs is written to the system log in that case. Could you look there and post what is being logged?

You need an app to monitor the system log and save it away, i.e. catlog or syslog.

Am 19. Dezember 2017 22:54:14 GMT+07:00 schrieb huste <notifications@github.com>:
>I am on an LG G4 Stylus H-635 with Android 6.0, German locale.
>
>When I try to authenticate StreetComplete via OAuth with my OSM-Account
>(Einstellungen> OSM-Zugang autorisieren), this happens:
>1) The web browser opens and asks me to log in
>2) I log in
>3) The web site asks for 3 permissions which I grant
>4) The web browser closes
>5) StreetComplete comes back again and pops up a Toast-message:
>"Autorisierungsserver kann nicht erreicht werden"
>
>In my OSM-account I can see a newly created OAuth token.
>
>The same happens, no matter if I use Opera or Firefox as default
>browser.
>
>As a result, I cannot upload anything.

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by huste** [comment]
How much I hate software testing...
I tried it incountable times. With opera. With Firefox. After rebooting. Always the same.
After installing logcat and trying again, it worked.

Great. :)

I will still try to discard the OAuth connection and reproduce the issue again. Until then, I'll closer this issue.

Good night for now
