### ISSUE TITLE
Request: Quest for waste bins, with or without free excrement bags for dogs

### ISSUE THREAD

**Issue by huste** [westnordost/StreetComplete#734]
I suggest adding a quest for waste bins that have free dog excrement bags on them:

existing:
amenity=waste_basket

adding:
payment_none=yes
venging=excrement_bags

**Comment by rugk** [comment]
(Next time) please fill out the issue template. It is not there for fun.

E.g. how do you tag a trash bin when it has not such a thing?

**Comment by huste** [comment]
I'm sorry, yes.
A trash bag without such a thing just does not have these two properties. From what I got, addig properties is possible. ah, but I see the issue: You can't determine if the question has already been answered...
The documentation to vending says nothing about "none", unfortunately. So I guess, this quest is impossible to perform.
Feel free to close this request, unless anyone has an idea of how to positively mark a waste bin without excrement bags.

Merry Christmas to all of you!

**Comment by westnordost** [comment]
Merry Christmas to you too, enjoy the holidays
