### ISSUE TITLE
StreetComplete notes review

### ISSUE THREAD

**Issue by matkoniecz** [westnordost/StreetComplete#739]
Is there some way to get list of notes created by StreetComplete? I see no tool allowing search listed in https://wiki.openstreetmap.org/wiki/Notes

After resolving some local StreetComplete notes I noticed that significant part of them is result of people unaware that answer may be selected within app and there is no need to create note.

So review of notes by people familiar with SC may be a good idea.

**Comment by westnordost** [comment]
Not that I know. The user agent/editor used for creating a note is not recorded by the OpenStreetMap website. There is an open ticket for that though, but it has been open for a very long time. Perhaps they would accept a PR if you are inclined.

Am 27. Dezember 2017 16:30:56 GMT+07:00 schrieb Mateusz Konieczny <notifications@github.com>:
>Is there some way to get list of notes created by StreetComplete? I see
>no tool allowing search listed in
>https://wiki.openstreetmap.org/wiki/Notes
>
>After resolving some local StreetComplete notes I noticed that
>significant part of them is result of people unaware that answer may be
>selected within app and there is no need to create note.
>
>So review of notes by people familiar with SC may be a good idea.
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/westnordost/StreetComplete/issues/739

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by matkoniecz** [comment]
I thought rather about whatever somebody made separate website/tool script to search through note dump (that AFAIK is available).

**Comment by matkoniecz** [comment]
Closing, to avoid polluting bug tracker.

**Comment by rugk** [comment]
Hmm so you cannot filter by user agent? But I think you can filter/search by the text in the notes.
So other apps just add an #hashtag to the text to allow this…

If you find any way to search for these notes, meet me know (in this issue).

**Comment by matkoniecz** [comment]
> But I think you can filter/search by the text in the notes.

How?

**Comment by rugk** [comment]
Don't really know, I thought I saw a webpage for that at someday.

**Comment by ENT8R** [comment]
> I thought I saw a webpage for that at someday.

I serached for a website too, but I couldn't find one...
So I decided to create a small tool which can do that, as the infrastructure already exists (You can search for specific keywords using the OSM Notes API).
Just go to https://ent8r.github.io/NotesReview/?query=StreetComplete&limit=3000 and hit the search button. It will currently find about 2300 Notes which contain the keyword "StreetComplete". Maybe you can have a look at it?!...

**Comment by westnordost** [comment]
Wow, cool!

I also thought there might be a webpage for that already, but I think I confounded it with https://osmcha.mapbox.com/ (showing changesets). 

This is a handy tool, perhaps you could add it to the wiki (QA tools and link on wiki entry to StreetComplete perhaps).
