### ISSUE TITLE
opening hours are added wrong way round

### ISSUE THREAD

**Issue by mo-ki** [westnordost/StreetComplete#74]
Aparrently the opening hours are added to osm in the wrong order. You can see the issue here:
https://www.openstreetmap.org/node/877484630/history#map=19/48.08423/11.27694
The opening hours by mobeki were added using StreetComplete.

**Comment by westnordost** [comment]
They are added in the same order as the user input them. Semantically, any order is correct, so the app is not enforcing it. It's WYSIWYG.

**Comment by ax3l** [comment]
That's true, but user's won't necessary know the whole [rulebook](https://wiki.openstreetmap.org/wiki/Key:opening_hours#Rules) and expectations the community came up with and in that case it can indeed be tooled during input. It's also kind of logical to sort them ascending.

**Comment by westnordost** [comment]
Huh, why, which rule? If there is a rule that the opening hours need to be sorted, then this is a bug and must be fixed. But I didn't see any, could you quote it?

**Comment by ax3l** [comment]
OSM usually collects it's defined attributes and rules in its wiki (as linked in my post). Here is the link again for opening hours:
  https://wiki.openstreetmap.org/wiki/Key:opening_hours#Rules

(+ [formal specification](https://wiki.openstreetmap.org/wiki/Key:opening_hours/specification)).

Admittedly, @mo-ki , I can not find in it that times of a single day must be sorted ascending, you might want to add that rule if you want to make your point ;-)

**Comment by mo-ki** [comment]
First of all: I do not have a strong opinion on the issue; IMHO the
answers 'We don't care about the order.' or 'Ordering DB entries is the
Job of the renderer (i.e. there is no ordering)' are perfectly reasonable.

I was just supprised to see that the opening hours I entered had to be 'fixed' by a nother user; and I can't see any difference but the order
in which they appear.

Since I was fairly certain I did not enter them in the 'wrong' order (listig the afternoon before the morning seems wrong to me), I was concerned that StreetComplete might be systematically swaping the order, requiring corrections for all entered data (which would undermine its
purpose, right?).

If there is no order as far as StreetComplete is concerned, then that's not the case, and this issue can be dropped.

**Comment by westnordost** [comment]
Well, I didn't have time to check, I am only as sure as you are that you did enter the times correctly. I will mark it as a bug, so I try to reproduce it later. Currently, #21 is my top priority, so I won't get around to this this week. 
If you (or someone else) can reliably reproduce this or confirm that SC does indeed not tamper with the order in which the user entered, I'd be grateful.

**Comment by mo-ki** [comment]
Uhm. I tried it again, and everything is fine. So its either randomly, or I was having a major senjor moment. Since I'm afraid the latter is more likely, I guess I owe you an apology.
I'm sorry for waisting our time.

**Comment by westnordost** [comment]
Nice, thanks for confirming that. That's part of a betatest, better finding a few bugs too many than too few :-)
