### ISSUE TITLE
34c3 advertisement

### ISSUE THREAD

**Issue by rugk** [westnordost/StreetComplete#741]
Hi,
I am planning to make an ad (for the TV screens) for the 34c3 here. 

If that is okay to you, @westnordost. Are you at the 34c3 probably?

Repo for that: https://github.com/rugk/streetcomplete-ad-34c3
Anyone can throw in ideas here!

**Comment by rugk** [comment]
Another question: Do you want a user/click statistic via the shortlink service https://is.gd?

**Comment by westnordost** [comment]
Nice!

I am still in Bangkok.

Am 28. Dezember 2017 06:14:50 GMT+07:00 schrieb rugk <notifications@github.com>:
>Hi,
>I am planning to make an ad (for the TV screens) for the 34c3 here. 
>
>If that is okay to you, @westnordost. Are you at the 34c3 probably?
>
>Repo for that: https://github.com/rugk/streetcomplete-ad-34c3
>Anyone can throw in ideas here!
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/westnordost/StreetComplete/issues/741

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by rugk** [comment]
Basically finished, I am going to add it soon.
If you want to have anything changed or so, here is the image: https://github.com/rugk/streetcomplete-ad-34c3/blob/master/streetcomplete-banner.svg

**Comment by rugk** [comment]
Hey, another great news! Yet anopther versioon is finished. Enjoy the Leipzig version: https://github.com/rugk/streetcomplete-ad-34c3/blob/master/streetcomplete-banner-Leipzig.svg

**Comment by rugk** [comment]
So 34c3 has finished. It was not merged in the small infoscreens in CCL, but in the real big screens of the talks it was shown multiple times. 😃 

Anyway, I think this issue can be closed now.

**Comment by westnordost** [comment]
Cool! Id like to have this still open so that I remember to have a look at it when i come back home soon - did not load on my mobile.

**Comment by rugk** [comment]
Yeah the svg is quite huge. You can find (minified) images of these in the repo I linked.

**Comment by westnordost** [comment]
Nice!

**Comment by rugk** [comment]
BTW showing it at the 35c3, too, now…
