### ISSUE TITLE
Drop area requirement for building quests

### ISSUE THREAD

**Issue by HolgerJeromin** [westnordost/StreetComplete#742]
When i find a new building but there is no aerial available i add a node with building=detached at the place. 
It would be nice if this app would ask for housenumber, levels and roof for them. 
If later the outline is available the meta data is already known.

https://www.openstreetmap.org/node/5078327042

**Comment by westnordost** [comment]
I'd rather not. It is only a matter of time until the node is made an outline (or deleted). Gps may be imprecise, without an outline showing on the map, the user has no point of reference as there is neither a name as usually required for shops etc (for quests to appear in StreetComplete) nor the outline, giving the user an idea about the size and location relating to the other buildings.

I'd venture that your technique is used somewhat rarely - most will add a rough outline and add a note or just wait for the aerial images - as Josm afaik also shows building-nodes as a warning.

Am 31. Dezember 2017 19:34:42 GMT+07:00 schrieb Holger Jeromin <notifications@github.com>:
>When i find a new building but there is no aerial available i add a
>node with building=detached at the place. 
>It would be nice if this app would ask for housenumber, levels and roof
>for them. 
>If later the outline is available the meta data is already known.
>
>https://www.openstreetmap.org/node/5078327042
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/westnordost/StreetComplete/issues/742

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by HolgerJeromin** [comment]
I see it as a normal upgrade of known information while construction 
=> building=residential (from surrounding) => building:levels => roof:levels+roof:shape
after the construction it gets a visible housenumber.

But checking other building nodes your are probably right, the most are copy and paste errors.
