### ISSUE TITLE
Limit cycleways to a set of countries

### ISSUE THREAD

**Issue by westnordost** [westnordost/StreetComplete#749]
After I visited Myanmar (and Thailand), I found that StreetComplete must be much more exclusive regarding certain quest types. Let's start with cycleways (no cycleways at all in Myanmar).

I am using Google Street View to look into the different cities and check if bicycleways are commonplace there. So far, I found the following countries in Europe (from north to south) to have bicycle infrastructure often.

```
NO, SE, FI, IS, GB, DK, IE, DE, PL, NL, BE, FR, LU, AT, CH, IT, ES
```

For these countries in Europe, I didn't find any cycleways / only *very* rarely one. Can you confirm?: Portugal, Andorra, Monaco, Liechtenstein, any country in East Europe (except Poland)

Do you know other countries outside Europe where cycleways are commonplace?

**Comment by westnordost** [comment]
I further got Japan, South Korea and Taiwan.

Australia, the US etc. seem somewhat "car countries".

**Comment by matkoniecz** [comment]
From quick look - it appears that cycleways are present in Estonia (EE) - http://www.openstreetmap.org/#map=18/59.41408/24.69063

In my limited experience Hungary (Hu) has plenty of cycleways.

Cz (czech republic) appears to have plenty cycleways - http://overpass-turbo.eu/s/uch (8 MB of results)

Slovakia appears to have lower cycleway density (1 MB of highway=cycleway) - http://overpass-turbo.eu/s/uci

**Comment by matkoniecz** [comment]
From https://en.wikivoyage.org/wiki/Cycling_in_Europe it seems that Switzerland (CH), France (FR), Spain (ES), Sweden (SE) are also likely candidates.

**Comment by dbdean** [comment]
We certainly have cycleways in Australia, although the vast majority the answer is either 'no' or 'there is a separate sidewalk where cycles are allowed (but not signposted for)'.

**Comment by dbdean** [comment]
How will the quest actually be disabled in other countries? Will it just be unticked in the settings and users can turn it back on if they want, or will it be enabled, but no quests will appear?

**Comment by westnordost** [comment]
It will be enabled but no quests will appear.

**Comment by westnordost** [comment]
I would like to leave out countries with very few cycleways from that quest, because if the answer is 99% "no, no cycleway", it's no fun for the user.

Perhaps I can add a feature later to extend the quest selection screen to actually showing in which countries the quest is enabled/disabled and giving the user the option to override this setting. This would be a new feature though, a rather big one as well.

**Comment by dbdean** [comment]
OK. In that case, please leave Australia in the 'has cycleways' list, as I've found enough around for this quest to certainly be useful.

**Comment by rugk** [comment]
What about having two lists?

* blacklist - never show quest as it is not common
* whitelist - show quest as usual
* all others: show quest with reduced priority

Or maybe in a more detailed way: assign a score to each country and calculate the priority from that

**Comment by gappleto97** [comment]
An alternate solution would be for it to look for cycleways *and* attached sidewalks. It already has some progress on that front, since several options have sidewalks in them.

**Comment by gappleto97** [comment]
Also, many US cities have cycleways and cycle lanes. Its much more of an urban/rural divide than it is a "US is a car place" thing.

**Comment by westnordost** [comment]
> An alternate solution would be for it to look for cycleways and attached sidewalks.

This would make the form too complex. I would like to keep it reasonable atomic.

>Also, many US cities have cycleways and cycle lanes. Its much more of an urban/rural divide than it is a "US is a car place" thing.

Hmm yes, that makes sense. I figure it is the same with China (big cities / western hinterland) and Russia (European part / Siberia).
For US (, China and Australia), it is possible to filter by state. Would that make sense? If yes, which states can be expected to probably have cycleways, which will probably have next to none?

**Comment by westnordost** [comment]
Same question goes to @dbdean

**Comment by westnordost** [comment]
Ok I'll start with, more can be added later on request.

```
// all of Northern and Western Europe, most of Central Europe, some of Southern Europe
"NO","SE","FI","IS","DK",
"GB","IE","NL","BE","FR","LU",
"DE","PL","CZ","HU","AT","CH",
"ES","IT",
// East Asia
"JP","KR","TW",
// Australia etc
"NZ","AU",
// some of Canada
"CA-BC","CA-QC","CA-ON","CA-NS","CA-PE",
// some of the US
// West Coast, East Coast, Center
"US-WA","US-OR","US-CA",
"US-MA","US-NJ","US-DC",
"US-MN"
```

**Comment by barilla-aldente** [comment]
>For these countries in Europe, I didn't find any cycleways / only very rarely one. Can you confirm?: >Portugal, Andorra, Monaco, Liechtenstein, any country in East Europe (except Poland)
Liechtenstein (li) is equal in Switzerland (ch). We have the same rules and the same style as our neighbor.

**Comment by dbdean** [comment]
I would say all states of Australia are likely to have cycleways, at least in the built up cities and towns.

**Comment by matkoniecz** [comment]
> Ok I'll start with, more can be added later on request.

Is there some feedback displayed to user that quest got disable due to location?

**Comment by westnordost** [comment]
No, this would be a new feature. See https://github.com/westnordost/StreetComplete/issues/749#issuecomment-355152093

**Comment by gappleto97** [comment]
I know of at least one major city with cycle lanes in WA, OR, CA, MI, NY, NJ, TX, AZ, NM, UT, IL, IN, WI, MA, CT, FL, KY, TN, and DC. Probably not an exhaustive list.

**Comment by matkoniecz** [comment]
Results of extremely basic tag distribution analysis (may be worth doing more sophisticated) - https://gist.github.com/matkoniecz/24fa1f16911a6edecee42daefe0e6e01

whitelist:
Slovakia (SK), Austria (AT), Hungary (HU), Poland (PL), Denmark (DK), Germany (DE), Czechia (CZ), Switzerland (CH), Belgium (BE), Sweden (SE), Albania (AL), Macedonia (MK), Finland (FI), Belarus (BY), Brazil (BR), Russia (RU), Ukraine (UA), United Kingdom (GB), Ireland (IE), Lithuania (LT), Australia (AU), South Africa (ZA), Ecuador (EC), Mexico (MX), Colombia (CO), United States of America (US), Chile (CL), Turkey (TR), Bulgaria (BG), Greece (GR), Burkina Faso (BF), Croatia (HR), Slovenia (SI), China (CN), Argentina (AR), Uruguay (UY), Peru (PE), Portugal (PT), Iceland (IS), India (IN), Indonesia (ID), South Korea (KR), Italy (IT), Japan (JP), Philippines (PH), Taiwan (TW), Singapore (SG), New Zealand (NZ), Liechtenstein (LI), Spain (ES), Canada (CA), Israel (IL), Thailand (TH), Malaysia (MY), Luxembourg (LU), France (FR), The Netherlands (NL), Bosnia and Herzegovina (BA), Norway (NO), 

blacklist:
Georgia (GE), Romania (RO), Venezuela (VE), Brunei (BN),

**Comment by matkoniecz** [comment]
List above may be used either as hint for what countries are worth checking manually or countries may be added and situation reevaluated later (Thailand is on the list - but maybe 118 cyclewayXXX=lane ways represent most of cycleways in this country? And once SC mappers will appear there many more cycleway:both=no will appear).

**Comment by westnordost** [comment]
To include all of US (and China etc) surprises me a bit now. What are the results if you split US and China by state?

Am 8. Januar 2018 02:25:58 MEZ schrieb Mateusz Konieczny <notifications@github.com>:
>Results of extremely basic tag distribution analysis (may be worth
>doing more sophisticated) -
>https://gist.github.com/matkoniecz/24fa1f16911a6edecee42daefe0e6e01
>
>whitelist:
>Slovakia (SK), Austria (AT), Hungary (HU), Poland (PL), Denmark (DK),
>Germany (DE), Czechia (CZ), Switzerland (CH), Belgium (BE), Sweden
>(SE), Albania (AL), Macedonia (MK), Finland (FI), Belarus (BY), Brazil
>(BR), Russia (RU), Ukraine (UA), United Kingdom (GB), Ireland (IE),
>Lithuania (LT), Australia (AU), South Africa (ZA), Ecuador (EC), Mexico
>(MX), Colombia (CO), United States of America (US), Chile (CL), Turkey
>(TR), Bulgaria (BG), Greece (GR), Burkina Faso (BF), Croatia (HR),
>Slovenia (SI), China (CN), Argentina (AR), Uruguay (UY), Peru (PE),
>Portugal (PT), Iceland (IS), India (IN), Indonesia (ID), South Korea
>(KR), Italy (IT), Japan (JP), Philippines (PH), Taiwan (TW), Singapore
>(SG), New Zealand (NZ), Liechtenstein (LI), Spain (ES), Canada (CA),
>Israel (IL), Thailand (TH), Malaysia (MY), Luxembourg (LU), France
>(FR), The Netherlands (NL), Bosnia and Herzegovina (BA), Norway (NO), 
>
>blacklist:
>Georgia (GE), Romania (RO), Venezuela (VE), Brunei (BN), 
>
>-- 
>You are receiving this because you modified the open/close state.
>Reply to this email directly or view it on GitHub:
>https://github.com/westnordost/StreetComplete/issues/749#issuecomment-355869606

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by matkoniecz** [comment]
data is posted to https://gist.github.com/matkoniecz/8fa156189a2579940396d82387a7a2af

USA whitelist starts at https://gist.github.com/matkoniecz/8fa156189a2579940396d82387a7a2af#file-data-txt-L163 (raw data posted earlier, it is likely that better criteria may be used - let me know if somebody invents something useful)

China whitelist starts at https://gist.github.com/matkoniecz/8fa156189a2579940396d82387a7a2af#file-data-txt-L306 (raw data is also posted).

None area qualified for blacklist with its current criteria.

**Comment by matkoniecz** [comment]
From what I see there are significant differences will be rather between rural and urban areas and between different cities. It seems obvious that currently tagging cyclewayX=no is quite rare.

Maybe StreetComplete should check what is mapped in local area and disable quests if many cyclewayX=no are present without cycleways present? It would adapt to local area at cost of making additional overpass querries (that may be cached for a long time) and once some initial cyclewayX=no are mapped no additional unneeded tags would appear.

Or maybe disable quests where user keeps repeating no over and over again?

**Comment by andrewharvey** [comment]
> OK. In that case, please leave Australia in the 'has cycleways' list, as I've found enough around for this quest to certainly be useful.

@dbdean Actually I find the quest distracting (both from the mapper in StreetComplete, the changeset reviewer, and future editors who have to deal with the increase in these cycleway=no tags), we have very few cycleways in Australia/NZ, it's not like some European cities in which cycleways are common.

Can we turn it off please?

**Comment by westnordost** [comment]
Hmm, can you back up your claim that (almost) all streets tagged for cycleways in Australia (an NZ) are tagged with cycleway:right/left=no (via StreetComplete) with data?

Am 2. Oktober 2018 02:15:23 MESZ schrieb Andrew Harvey <notifications@github.com>:
>> OK. In that case, please leave Australia in the 'has cycleways' list,
>as I've found enough around for this quest to certainly be useful.
>
>@dbdean Actually I find the quest distracting (both from the mapper in
>StreetComplete, the changeset reviewer, and future editors who have to
>deal with the increase in these cycleway=no tags), we have very few
>cycleways in Australia/NZ, it's not like some European cities in which
>cycleways are common.
>
>Can we turn it off please?

**Comment by matkoniecz** [comment]
Based on all tagged cycleway stats it is hard to say, but cycleway:both that is used primarily by StreetComplete suggests that there may be a problem.

I may expand my tool to sample for edits that were made by StreetComplete, but I make no promises on when I will do that.

```
cycleway:both 
no x2319
shared_lane x78
lane x73

cycleway 
lane x14804
track x7668
no x2346
shared_lane x1764
shoulder x1284
shared x228
sidewalk x149
crossing x100
opposite_lane x73
share_busway x70
opposite x58
yes x50
path x23
shared_path x21
left=lane x17
segregated x8
designated x7
parallel x7
opposite_track x6
shared_bus_way x5

cycleway:left 
lane x3132
no x651
shoulder x248
shared_lane x167
track x54
share_busway x27
none x8
opposite x7
opposite_lane x6

cycleway:right 
no x174
lane x152
shared_lane x36
opposite_lane x23
track x22
none x12
```

raw data:

```
cycleway:both {"no"=>2319, "lane"=>73, "shared_lane"=>78, "track"=>1}
cycleway {"shoulder"=>1284, "track"=>7668, "lane"=>14804, "shared_lane"=>1764, "asl"=>2, "no"=>2346, "yes"=>50, "share_busway"=>70, "shared_path"=>21, "opposite"=>58, "shared"=>228, "opposite_lane"=>73, "designated"=>7, "opposite_track"=>6, "designated; track"=>2, "sidewalk"=>149, "crossing"=>100, "left=lane"=>17, "segregated"=>8, "path"=>23, "both"=>1, "none"=>3, "parallel"=>7, "doorzone"=>3, "ferry"=>2, "Laanecoorie Track"=>1, "Moliagul Cycle Track"=>2, "shared_bus_way"=>5, "Rezerve"=>2, "?dismount"=>1, "ride"=>4, "shared_way"=>1, "uphill"=>1, "traffic_island"=>2}
cycleway:left {"lane"=>3132, "no"=>651, "shared_lane"=>167, "share_busway"=>27, "shoulder"=>248, "designated"=>3, "opposite_lane"=>6, "track"=>54, "yes"=>1, "none"=>8, "opposite"=>7, "path"=>4, "opposite_track"=>2, "asl"=>1}
cycleway:right {"no"=>174, "shared_lane"=>36, "lane"=>152, "opposite_lane"=>23, "track"=>22, "yes"=>1, "none"=>12, "asl"=>1, "opposite"=>1, "share_busway"=>2, "dismount"=>1, "opposite_track"=>1, "path"=>1}
```

**Comment by westnordost** [comment]
Okay, thank you @matkoniecz

Let's ignore cycleway,because it is greatly skewed towards cycleways (people tend to not tag cycleway=no).

Then we have...
No cycleway = 2732
Something else = 1932

That looks pretty balanced. However, the cycleway:left=lane data point looks somewhat fishy. Why only the left side and not the right?

**Comment by matkoniecz** [comment]
> cycleway:left=lane data point looks somewhat fishy. Why only the left side and not the right?

Maybe contraflow lanes in Australia are tagged this way? According to https://overpass-turbo.eu/s/Cr4 there are 2916 of cycleway:left with oneway=yes, though only 26 are on oneway:bicycle=no ( https://overpass-turbo.eu/s/Cr5 ).

**Comment by andrewharvey** [comment]
> Maybe contraflow lanes in Australia are tagged this way? According to https://overpass-turbo.eu/s/Cr4 there are 2916 of cycleway:left with oneway=yes, though only 26 are on oneway:bicycle=no ( https://overpass-turbo.eu/s/Cr5 ).

What's wrong with that? It just means that it's a oneway road with a cycleway on the left only going in the same direction as traffic.

**Comment by andrewharvey** [comment]
> Hmm, can you back up your claim that (almost) all streets tagged for cycleways in Australia (an NZ) are tagged with cycleway:right/left=no (via StreetComplete) with data?

Sorry I'm not sure I understand, this quest is asking asking for all roads, is there a cycleway? Just like a quest for "Is this road oneway?". Most roads are not oneway, and generally in OSM it's only needed to tag these oneway=no if someone would otherwise think it's oneway, just for the mappers benefit. If you go around adding oneway=no to the vast magority of roads, it adds to the reviewer noise/overhead and also makes the list of tags on the feature longer which makes it more complicated for mappers to edit tags.

@matkoniecz stat's says there are about 18,000 cycleways tagged in OSM (I assume that's in Australia only?) compare than to how many highway=* (excluding steps, path, footway, cycleway) etc. there are.

**Comment by westnordost** [comment]
Ok, I understand. So the many cycleway:left=lane come from oneway streets that have a lane.

So then, the data says that it is reasonable to ask for cycleways in Australia.

**Comment by andrewharvey** [comment]
> So then, the data says that it is reasonable to ask for cycleways in Australia.

That part I don't understand, is this any different to asking "Is this road oneway?" on all roads?

**Comment by ENT8R** [comment]
> Most roads are not oneway

This is also because this quest is not asked for **all** roads but just for roads which were considered to be oneway by the navigation provider Telenav. (See also https://github.com/ENT8R/oneway-data-api) The cycleway quest is asked for nearly all ways a surveyor can survey by foot.

**Comment by andrewharvey** [comment]
bus_lane=no, horse_lane=no, electric_scooter_lane=no, there are many things we can tag as `no`,  they just adds noise to changeset feed and make it harder for mappers to maintain OSM as each object now has a large number of tags which are assumed by default.

**Comment by ENT8R** [comment]
> which are assumed by default

OSM does not have _real_ default values. One can always **assume** that a certain feature does (not) exist, but only a surveyor setting the value explicitly to no can determine that something does (not) exist at all...

**Comment by matkoniecz** [comment]
> What's wrong with that? It just means that it's a oneway road with a cycleway on the left only going in the same direction as traffic (ie. it's not contraflow).

> A contraflow on the left would be very uncommon, most of the time the contraflow cycleway would be on the right. ...in left side driving countries, in right side driving I'd expect the opposite.

Sorry for confusion. I failed to check driving side direction and assumed right-hand traffic what was untrue ( https://en.wikipedia.org/wiki/Left-_and_right-hand_traffic ).

**Comment by matkoniecz** [comment]
>  horse_lane=no

Is it something that exists on such scale that it is tagged as existing on over 10 000 road segments in Australia? If not, then it is not comparable.

**Comment by andrewharvey** [comment]
> osmium tags-filter australia.osm.pbf w/highway=motorway,trunk,primary,secondary,tertiary,unclassified,residential,service,motorway_link,trunk_link,primary_link,secondary_link,tertiary_link,road -o road-ways.osm.pbf
> osmium fileinfo -e road-ways.osm.pbf 
> osmium tags-filter australia.osm.pbf w/cycleway=lane "w/cycleway:left=lane" "w/cycleway:right=lane" "w/cycleway:both=lane" -o cyclelane.osm.pbf

18,000 existing cycleway*=lane way segments out of 1.1M road way segments is 1.6%. Of course that means nothing without knowing how complete we are, but I guess we're at least 80% complete in terms of cycle lanes.

**Comment by westnordost** [comment]
Where does that guess come from?

Am 2. Oktober 2018 15:29:09 MESZ schrieb Andrew Harvey <notifications@github.com>:
>> osmium tags-filter australia.osm.pbf
>w/highway=motorway,trunk,primary,secondary,tertiary,unclassified,residential,service,motorway_link,trunk_link,primary_link,secondary_link,tertiary_link,road
>-o road-ways.osm.pbf
>> osmium fileinfo -e road-ways.osm.pbf 
>> osmium tags-filter australia.osm.pbf w/cycleway=lane
>"w/cycleway:left=lane" "w/cycleway:right=lane" "w/cycleway:both=lane"
>-o cyclelane.osm.pbf
>
>18,000 existing cycleway*=lane way segments out of 1.1M road way
>segments is 1.6%. Of course that means nothing without knowing how
>complete we are, but I guess we're at least 80% complete in terms of
>cycle lanes.

**Comment by westnordost** [comment]
By the way, on the topic of tagging the absence of features: 

> You probably heard that if a feature is not tagged, the assumption is of course, that it is not there. I.e. if it is not tagged whether a street is lit, it means that it is not. However, this is an assumption the data consumer has to make when it is dealing with incomplete data. The absence of a tag is in no way equivalent to any value - it is what it is - unspecified.
> 
> So the reason why StreetComplete tags also the absence of features is to indicate that a user surveyed the place and determined that the feature is indeed absent, i.e. a street is not lit. The distinction of whether a feature has been surveyed or whether it is simply unspecified is an important information for other surveyors and thus for the maintainability of the map.
> 
> That being said, the app takes great care to limit the amount of quests where the answer can be assumed to always be the same (i.e. “no”) with a relative certainty.
> 
> As an example, the cycleway quest is only shown for a certain subset of roads which additionally do not have any cycleway tagging in any form (including separately mapped cycleways), which don't have a speed limit set to 30 km/h and below and are not unpaved. Additionally, the quest is only shown in certain countries, where it can be assumed that (sometimes) dedicated bicycle infrastructure is present in the first place. 
(from the [StreetComplete FAQ](https://wiki.openstreetmap.org/wiki/StreetComplete/FAQ#Why_does_StreetComplete_often_tag_the_absence_of_features.3F))

**Comment by goldfndr** [comment]
> > osmium tags-filter australia.osm.pbf w/highway=motorway,trunk,primary,secondary,tertiary,unclassified,residential,service,motorway_link,trunk_link,primary_link,secondary_link,tertiary_link,road -o road-ways.osm.pbf
> 
> 1.1M road way segments

For a proper count, [the query](https://github.com/westnordost/StreetComplete/blob/master/app/src/main/java/de/westnordost/streetcomplete/quests/bikeway/AddCycleway.java#L189) is considerably more restrictive.

**Comment by matkoniecz** [comment]
@andrewharvey One thing that may be not 100% obvious - this discussion is about disabling this quest for everybody in Australia.

Any user may disable any quest manually in settings menu.

Also, can you give example of any case where SC asked to add cycleways on way where there are tags making obvious that cycleway is extremely unlikely? Maybe it is possible to discard more obviously poor questions in a query? ( https://github.com/westnordost/StreetComplete/blob/master/app/src/main/java/de/westnordost/streetcomplete/quests/bikeway/AddCycleway.java#L189 )

**Comment by westnordost** [comment]
Okay, so, just to summarize, because I think this is leading nowhere:
1. I have no problem to disable this quest again for countries/states where it turns out that it is extremely unlikely that any cycleway infrastructure exists. (In other words, seeing a cycleway should be somewhat of a novelty.) I reckon that at some point, the additional work for surveyors (StreetComplete users) and maintainers (QA tool users etc.) outweights the information gain
2. A request for removal must be based on data. [Data + guess is still a guess](https://github.com/westnordost/StreetComplete/issues/749#issuecomment-426273618). **A hint here**: Most/many?/some? people do not tag `cycleway=no` but just leave it out. This means that it is not possible to find out how much of the cycleway network is missing and how much is simply not tagged yet by looking at the values of `cycleway`. However, few people use the `cycleway:both` / `cycleway:left` / `cycleway:right` scheme, but StreetComplete does (and so do their users). And with StreetComplete, the absence of a cycleway is always tagged as well. So, by looking at `cycleway:both` / `cycleway:left` / `cycleway:right` and not `cycleway`, or even better by looking only at those taggings done via StreetComplete (if possible), one can get reliable data about the distribution of _no cycleway_ and _some cycleway_.
