### ISSUE TITLE
Feedback for data upload

### ISSUE THREAD

**Issue by claudiush** [westnordost/StreetComplete#75]
Tapping the "Upload Answers" menu option there's no feedback on whether this upload was successful. The menu item remains active. User currently has no option to verify their data was successfully uploaded.
Please add an confirmation message to give peace of mind that all the detours to fix quests were worth it :)

**Comment by westnordost** [comment]
Did you notice the star icon on the toolbar? What do you think it is for?

(Spoiler: it is for that, but apparently it is not made clear in the app)

**Comment by claudiush** [comment]
The star icon didn't change for me either. I can see the counter increasing for every quest I solved, but there's no change to the count or styling whenever I use "Upload Answers".

**Comment by westnordost** [comment]
Because it uploads them immediately. It there is `★ 5(+3)`, it means you solved 3 that haven't been uploaded yet and 5 that already have been uploaded.

Basically, the upload answers button is only (useful) for when you turned automatic sync off.

**Comment by claudiush** [comment]
May I suggest to hide the "Upload answers" item then, if automatic sync is enabled?

**Comment by westnordost** [comment]
Fair enough, but the option is not a simple on/off. It's on, off, only on wifi.

**Comment by cstackpole** [comment]
I was just looking for the same answer! I couldn't figure out what the star was. Maybe add a short "help" menu that explains a few of the interface options?
Thanks! This is an awesome app. Solving a lot of the quests around my neighborhood.

**Comment by Etua** [comment]
@westnordost Indeed, the explanation would be helpful. I've worked out how that stars counter works myself, but at first (before I have checked contributions of my OSM account) it was not obvious.

**Comment by claudiush** [comment]
Maybe at least provide some feedback if there's nothing to upload because the "+x" was already uploaded via mobile internet or wifi: 
If nothing to upload show message _"Good news. All your changes have been uploaded to OSM already."_

**Comment by gdt** [comment]
Also, you could grey out the upload answers menu item if there are none to upload or if auto-upload is in progress.

**Comment by anttitelio** [comment]
Also for me, the upload functionality was very unclear until I found this topic. Could the upload button be the star itself? Maybe the color could change if an upload is needed?

**Comment by james2432** [comment]
Just to let you know people are criticizing that there is one changeset per tag: https://forum.openstreetmap.org/viewtopic.php?id=57855

**Comment by claudiush** [comment]
@james2432 This is already discussed (and resolved) in #21

**Comment by johnwhelan** [comment]
So to recap then if I have 50 quests ready to go and its on autosync I can just assme they have gone unless I see (+45) in the bar at the top?

Thanks John

**Comment by westnordost** [comment]
Yes, the (+XX) are the amount of answers still pending for upload. If this is not there, everything is safely uploaded.

**Comment by johnwhelan** [comment]
Sounds like a documentation issue. How to get over the important bits without having a 300 page manual. 

Ta John

**Comment by westnordost** [comment]
Well, I am open for ideas how to make this more clear without the need for an explanation

**Comment by johnwhelan** [comment]
added a bit into the OSM wiki here 
https://wiki.openstreetmap.org/wiki/StreetComplete

John

**Comment by matkoniecz** [comment]
Feedback would be useful in cases of failure. I have autosync on, I used upload answers and star was still stuck at 15 (+8) without feedback what was happening - is it uploading, failing to upload or something.

Maybe if upload is proceeding then progress bar may appear somewhere (at top of the screen)?

**Comment by matkoniecz** [comment]
Additional idea: clicking on stars brings window/widget/message that displays something like "X improvements uploaded, Y waiting for wifi to upload. Thank you for improving OpenStreetMap!".

**Comment by westnordost** [comment]
Actually I planned the star-button to bring up more detailed statistics of how many quests of which type one fixed.
But of course, this text could be at the top of this screen.

But I think, the best way would be another button in the navigation bar, something like an arrow-up, which uploads the quests (manually). The number displayed within this arrow is the number of quests pending to be uploaded. While quests are being uploaded, the arrow could have some kind of animation.

**Comment by waldyrious** [comment]
An arrow-up would be much more intuitive for this purpose (I thought about suggesting that myself), and the star button showing overall contribution stats instead also makes more sense :)

**Comment by althio** [comment]
> May I suggest to hide the "Upload answers" item then, if automatic sync is enabled?

> Fair enough, but the option is not a simple on/off. It's on, off, only on wifi.

I like the idea of arrow-up, in the navigation bar, for manual upload.
If this option is accessible direcly on map screen, I think it would be better to move a textual option into the settings.

In the settings, I suggest:
- Settings > Communication
  - Upload answers policy
    - Always upload
    - Upload only on Wifi
    - Manual upload
  - Upload answers now [clickable; when answers waiting for upload] 
OR No answer to upload [greyed out; when no answer to upload] 
OR Uploading answers... [greyed out; if (auto-)upload is in progress]
  - Download quests policy
    - Always download
    - Download only on Wifi
    - Manual download
  - Download quests now [clickable; overrides download policy] 
OR Downloading quests... [greyed out; if (auto-)download is in progress]
  - Authorize OSM access
- Settings > Cache
...

**Comment by errolpais** [comment]
I took a stab at implementing the arrow up suggested by @westnordost 
> another button in the navigation bar, something like an arrow-up, which uploads the quests (manually). (Replaces the menu item "upload answers"). The number displayed within this arrow is the number of quests pending to be uploaded. 

I wanted to check with everyone to confirm if this is the right direction that the conversation was going in before submitting a pull request.

![streetcomplete](https://user-images.githubusercontent.com/2432170/32813109-52ef2222-c95d-11e7-9fa9-5db913feadf4.png)

**Comment by westnordost** [comment]
Cool, yeah! It's getting a bit tight there, but I guess that it is still fine for now. As far as I remember, the undo-button will move in the menu automatically if there is not enough space.
