### ISSUE TITLE
Limit tactile pavings to set of countries

### ISSUE THREAD

**Issue by westnordost** [westnordost/StreetComplete#750]
Tactile pavings are also something that does not exists in many countries. 

I did not research here yet. Perhaps if someone wants to help, he could get into a Google Streetview car, drive around the world and write here of his findings.

**Comment by westnordost** [comment]
I'll start:

**Yes:** Singapur, Hong Konk(, Malaysia?)
**No:** all of southeast asia

**Comment by dbdean** [comment]
**Yes**: Australia, New Zealand

**Comment by rugk** [comment]
I think for such things, we really need https://github.com/westnordost/StreetComplete/issues/633 as a kind of in-app "survey".

**Comment by matkoniecz** [comment]
Maybe it would be useful to check what is currently tagged in each country (run overpass query)? And blacklist ones with heavy *=no usage?

**Comment by matkoniecz** [comment]
Yes: Poland

**Comment by westnordost** [comment]
I think checking intersections in bigg(er) cities with Google Street View would be the most efficient.

**Comment by matkoniecz** [comment]
> I think checking intersections in bigg(er) cities with Google Street View would be the most efficient.

If that is main reason, rather than doubts about data usefulness I made https://gist.github.com/matkoniecz/6fc0e5f3f2f399849cf8117731fc5afe and https://gist.github.com/matkoniecz/a81ae6516fa8d39567140c2ac8dd293c

Quick tag check suggests SK, AT, HU, PL, DE, CZ, CH, BE, SE, BR, RU, GB, IE, LT, AU, US, AR, IT, SG, NZ, ES, FR, NL, ES, for whitelist (tactile_paving=yes used more than 100 times, at least 5% of tactile_paving=yes/no is tactile_paving=yes).

If such list/data is useful I may run it also for cycleways or share code used to create it.

**Comment by westnordost** [comment]
Wow, that is very cool! How did you put this together?

For cycleways, it would indeed also be helpful!

**Comment by matkoniecz** [comment]
> Wow, that is very cool! How did you put this together?

`[out:json];relation["admin_level"="2"][boundary=administrative][type!=multilinestring];out; ` to get list of countries, fetching all tactile_paving=* objects and counting how these objects are tagged.

I am currently trying to make my code publishable (note that Ruby is required to run it).

**Comment by matkoniecz** [comment]
Note: I updated list in https://github.com/westnordost/StreetComplete/issues/750#issuecomment-355823893 , by mistake it included twice data for highway=crossing (both for highway=crossing and highway=bus_stop). Now highway=bus_stop contains correct data and list has both country codes and less cryptic country names.

**Comment by matkoniecz** [comment]
If whitelist from https://github.com/westnordost/StreetComplete/issues/750#issuecomment-355823893 looks like a good list of countries with enabled quest I make a PR that limits quest to this list of countries.

**Comment by westnordost** [comment]
OK! :-)

**Comment by matkoniecz** [comment]
I wonder what countries should be split in regions here. I suspect that USA may be considered as one entity and China, Russia should be split.

**Comment by matkoniecz** [comment]
@dbdean

> Yes: New Zealand

Also for bus stops?

**Comment by dbdean** [comment]
I don't know about tactile paving for bus stops in NZ, sorry.

**Comment by matkoniecz** [comment]
So bus stops in New Zealand are almost always without tactile markings?

**Comment by Mannivu** [comment]
Some italian cities have tactile pavements near crossings. See [this crossing](https://www.google.com/maps/@45.5543776,9.6192922,3a,75y,24.35h,46.09t/data=!3m6!1e1!3m4!1sUEfhuS7ufhBGvf0LrL73xw!2e0!7i16384!8i8192) for exemple. I think Italy shouldn't be on the whitelist for the crossings.
