### ISSUE TITLE
disable maxspeed quest for unpaved roads

### ISSUE THREAD

**Issue by matkoniecz** [westnordost/StreetComplete#752]
https://github.com/westnordost/StreetComplete/blob/master/app/src/main/java/de/westnordost/streetcomplete/quests/max_speed/AddMaxSpeed.java - currently it will generate quests in places where legal limit is irrelevant

It is useful mostly in countries with poor infrastructure, but also in Europe some landuse=residential may be unpaved.

**Comment by westnordost** [comment]
Yes, makes sense.

**Comment by westnordost** [comment]
also moved down in priority slightly, so the user specifies road surface before maxspeed.

**Comment by matkoniecz** [comment]
> so the user specifies road surface before maxspeed

Without fixing #746 it will not work as expected - user after entering unpaved will be anyway asked about maxspeed.

**Comment by westnordost** [comment]
Right. Too  bad :-/

**Comment by westnordost** [comment]
But now, #746 could be implemented actually for "simple" quests.

**Comment by westnordost** [comment]
Since https://github.com/westnordost/StreetComplete/commit/15d1e90d9aa66322097db05dcb46103a9d3766e9
