### ISSUE TITLE
Multiple version of same object in a bulk changeset

### ISSUE THREAD

**Issue by gileri** [westnordost/StreetComplete#754]
Multiple changes are grouped in a changeset in StreetComplete.
However, it seems that multiple edits of the same objects are not squashed together and sent as 1 version in a changeset.

[Example](https://www.openstreetmap.org/changeset/55005864)

There should be only one version of n262998576

**Comment by westnordost** [comment]
This is correct.

**Comment by westnordost** [comment]
Changes are (by default) immediately uploaded. If you undo (=revert) an already uploaded object, it needs to be done as another change. This creates another version of the object.

**Comment by westnordost** [comment]
This is related to #753, by the way :-)
