### ISSUE TITLE
trigger upload on reaching wifi

### ISSUE THREAD

**Issue by matkoniecz** [westnordost/StreetComplete#755]
Note that I noticed one issue that I have yet to fully debug but would be made more significant by #753 change.

Is upload attempt triggered only on edits? Because if I edit without Internet connection and return to wifi it seems that it is not triggering upload and changes are stuck for a long time (until edit/manual upload?).

**Comment by westnordost** [comment]
It should. See https://github.com/westnordost/StreetComplete/blob/master/app/src/main/java/de/westnordost/streetcomplete/data/QuestAutoSyncer.java#L63

**Comment by matkoniecz** [comment]
https://github.com/westnordost/StreetComplete/blob/3d0a08bf274297fc25b0e94c87b0f8c7651810dd/app/build.gradle#L23 - this app targets API level 26, later than N according to https://developer.android.com/guide/topics/manifest/uses-sdk-element.html .

It is trying to use ConnectivityManager.CONNECTIVITY_ACTION https://github.com/westnordost/StreetComplete/blob/master/app/src/main/java/de/westnordost/streetcomplete/data/QuestAutoSyncer.java#L63

According to https://stackoverflow.com/questions/36421930/connectivitymanager-connectivity-action-deprecated  "Apps targeting Android N do not receive CONNECTIVITY_ACTION broadcasts"

> Apps targeting Android N do not receive CONNECTIVITY_ACTION broadcasts, even if they have manifest entries to request notification of these events. Apps running in the foreground can still listen for CONNECTIVITY_CHANGE on their main thread if they request notification with a BroadcastReceiver.

**Comment by westnordost** [comment]
The official documentation states

> Apps targeting Android 7.0 (API level 24) and higher do not receive this broadcast if they declare the broadcast receiver in their manifest. Apps will still receive broadcasts if they register their BroadcastReceiver with Context.registerReceiver() and that context is still valid.

 https://developer.android.com/reference/android/net/ConnectivityManager.html#CONNECTIVITY_ACTION

The receiver is registered programmatically with Context.registerReceiver().

**Comment by matkoniecz** [comment]
I tried to reproduce it and run out of ideas.
