### ISSUE TITLE
Clarify terms in "Name of this road" quest

### ISSUE THREAD

**Issue by smichel17** [westnordost/StreetComplete#756]
There is a segment of road I was trying to name. It's part of an intersection, around 30 feet long, and is kind of like a yield lane that peels off, but with a stop sign at the end instead (it's for a left turn). I can take a picture if this description is not clear enough. 

I have no familiarity with OSM terms. There are two parts to the question that are confusing to me:

1. "Not a proper road" vs "It has no name" -- what is a "proper road"?
    - My first instinct was to say it's not a proper road, since it's only 30 feet long. As I think about it more, I think that's wrong, though, since people do drive on it like a normal road.
2. If it is a road, does it have a name?
    - It has no sign, so I'm inclined to say no name. However, I could also see the rationale for putting the name of the road it comes off of.
3. What is a track?
    - As I mentioned, my instinct was to mark it as not a proper road. So now I see my options are a service road, a track, or something else. But I'm not sure what a track is, so I can't answer the question. 

Note: overall I'm more interested in getting this phrasing clarified than answering about this particular street, which I just provide as an example.

**Comment by westnordost** [comment]
Didn't you get the option "it just links two roads"?

Which street was it?

**Comment by smichel17** [comment]
Not sure how to link the quest but here's the location:

40°45'05.6"N 73°44'46.6"W
Horace Harding Expy, Oakland Gardens, NY 11364, USA
https://maps.google.com/maps?q=40.75155249999998,-73.74627734375001

**Comment by smichel17** [comment]
<img alt="Screenshot" height="500" src="https://user-images.githubusercontent.com/6563664/34683922-63540042-f49b-11e7-9754-e6d43c2adaf2.png"> <img alt="Screenshot" height="500" src="https://user-images.githubusercontent.com/6563664/34683858-3ca48b24-f49b-11e7-99a1-56b11ab471d2.png">

**Comment by westnordost** [comment]
I see. Well, to answer your questions earlier:

> What is a "proper road"? 

A "road proper", a road in the usual sense. I.e. a driveway, an alleyway, a lane in a parking lot (all service roads), a agricultural or forestry track and "something that links two roads" (don't know if there is a name in English, this: https://upload.wikimedia.org/wikipedia/commons/e/ec/Ausfahrkeil.jpg ) are not proper roads.
Let me know if you think the wording can be improved, I am not a native speaker.

> What is a track? 
Something like this https://en.wikipedia.org/wiki/Agricultural_road or this https://en.wikipedia.org/wiki/Forest_road
A road, used for agricultural things (like a road between fields that lead nowhere else than to the fields) or for forestry things (a road that is used by foresters etc).
If this is not clear to you from the name "track", would there be a more fitting name for these kinds of roads?

Finally, if there were an option "it just links two roads", would you think this would be the correct answer to give? Or would you also be unsure?
(TBH, it would be, but for certain reasons I will explain and that we can discuss later, it is not shown in this case)

**Comment by matkoniecz** [comment]
I noticed in notes left by SC users that many are confused by roads that are parts of crossings (like linked by @smichel17 or some that do not really exists like http://www.openstreetmap.org/way/383825801#map=19/50.04555/19.92144 )

![selection_001](https://user-images.githubusercontent.com/899988/34706473-3d8a5aa6-f508-11e7-9fcf-9bce91ba3102.png)

Maybe give an option "is part of crossing"? Some apparently feel that "It has no name" is not correct as it is not road at all.

For me "it as no name" felt OK, but I was aware of internal app logic and for me it was "apply noname=yes" button.

**Comment by rugk** [comment]
Ah so for crossing we should choose "it is no proper road"?

**Comment by matkoniecz** [comment]
I use "it has no name".

**Comment by exploide** [comment]
Doesn't this depend on the fact if there are 4 differently named roads which form the crossing or if there are 2 roads which intersect at some point but have the same name before and after the crossing respectively? In this case I would assume the connecting parts that point in the same direction deserve the same name as the road that preceeds before and after the crossing.

Generally, I'm often not sure how to answer the street naming quest. Sometimes it is due to really small portions that I cannot confidentially associate to some of the streets around, and sometimes it is because the difference between "no proper road" and "has no name" is not clear enough (I can see above this does not only happen to me). The way I think is "when this is no proper road, it probably has no name too, so what should I select now...".

**Comment by westnordost** [comment]
> The way I think is "when this is no proper road, it probably has no name too, so what should I select now...".

Well, it doesn't really matter that much, I guess, whether the center part or other parts of one intersection have `noname=yes` tagged, or carry over the name of the neighbouring street, in my opinion. It's very much a matter of taste. Some mappers map it like this, some like that.

So, StreetComplete users being unsure about answering this or that, are not alone. All mappers are are faced with this uncertainty, or call it freedom.

As long as nobody comes forth and gives a really strong argument for tagging it this way or the other, the situation will stay the same.

**Comment by smichel17** [comment]
> "something that links two roads" (don't know if there is a name in English, this: https://upload.wikimedia.org/wikipedia/commons/e/ec/Ausfahrkeil.jpg )

That's exactly what I was trying to describe with "a yield lane that peels off" in the top comment. I think the best umbrella term to catch both this and the example @matkoniecz gave would be, "Part of an intersection," although, "It connects two roads" would also be clear enough (This might be desirable if there are places where there is a connector that is not strictly part of an intersection, although I can't think of anything like that off the top of my head).

> A "street proper", a street in the usual sense. I.e. a driveway, an alleyway, a lane in a parking lot (all service roads), a agricultural or forestry track

I think the problem is that "proper road" is too vague of a category to be useful. If it were a normal road, I would probably be able to enter it's name in the first step; the fact that I opened the "Other Answers" already implies that it's unusual; all the choices within should be as mutually exclusive as possible.

Also, a service road can be a proper road, in my opinion. For example, "Horace Harding Expressway" above is actually the service road for Route 495... but it still seems like a proper road when I'm driving on it (it's public, named, paved, two lanes, etc).

Here's an attempt at re-doing the "Other Answers..." menu, which I think would make sense to rename to "No Name..." (after all, if it had a name, I'd just enter it). It's not perfect yet but maybe a starting point.

- Can't type the characters on the sign
- It is part of an intersection
- It is not a public road (parking lot or driveway -- this one could have a sub-menu if it's useful)
- It a service road (could also have a sub-menu if it's useful to distinguish agricultural & forest roads, etc)
- Can't say / something else (opens "Leave a note instead?" dialog)

**Comment by westnordost** [comment]
@smichel17 Thank you for your input, I will give you a bit of an insight about how things are supposed to be tagged in OSM, some of what you suggest is not possible.

| Situation | Tagging |
| ---- | ---- |
| a forestry road | `highway=track` |
| an agricultural road | `highway=track` |
| a driveway | `highway=service`, `service=driveway` |
| an alleyway | `highway=service`, `service=alley` |
| a drive-through | `highway=service`, `service=drive-through`|
| any other non-public service road used to access a location | `highway=service`|
| a lane within a parking lot | `highway=service`, `service=parking_aisle` |
| a lane that peels off | for `motorway`, `trunk`, `primary`, `secondary` and `tertiary` roads: `highway={road type}_link`. For `unclassified` roads: ??? (Not defined?) |
| is within the (center) part of an intersection | up for discussion, a matter of taste. Either `noname=yes` or taking the name of the connecting road. Definitely **not** `highway={road type}_link` |

**Comment by westnordost** [comment]
I guess, the naming really matters here so that these roads are clearly distinguished:
- tracks (forestry + agricultural roads)
- service ("small" access roads, often on private property)
- road links (on-ramps + road links + lanes that peel off but _not_ sections of roads within (center of) intersection)

**Comment by smichel17** [comment]
> Certainly an idea, but what about the option "Can't type the characters on the sign" then?

Oh, good point. What does that option do in the database?

> I will give you a bit of an insight about how things are supposed to be tagged in OSM

Okay, second pass:

- Can't type the characters on the sign
- It is part of an intersection
    - It is the center of an intersection
    - It is a lane that peels off (maybe there's a better phrasing for this?)
- It a service road
    - Agricultural or Forest road
    - Highway (no public access[1])
- It is a private[1] road
    - driveway
    - parking lot
    - alleyway
    - drive-through
- Can't say / something else (opens "Leave a note instead?" dialog)

[1] Note that I changed from "not public" to "private". The reason is that sometimes service roads for highways are "public" in the sense that they are maintained by the government using tax revenue, but they're not necessarily *public access.* This might confuse someone who is not sure which menu to look in[2]; "private" is a little different though, so hopefully it's more clear that this type of road belongs under the service road heading.

[2] This is important because I -- at least -- often avoid clicking on those options if I'm not sure they're the right choice. It's because I'm not sure whether doing so will actually submit something and am (irrationally) afraid of mis-tagging something.

**Comment by westnordost** [comment]
> Oh, good point. What does that option do in the database?

Nothing. It just shows a help dialog that gives tips how/where to get a multilingual keyboard (and buttons lead to the play store / the keyboard preferences)

> Highway (no public access)

What is this?

Hmm, you second try is not so good.

When rephrasing, avoid words that have a meaning in OpenStreetMap.

For example, "a service road" is usually associated to roads that qualify as `highway=service`, especially of course by users who know OpenStreetMap a bit (more). Such a redefinition would be very confusing. So, if the current words are not good, perhaps we can find other phrasing that is not taken already.
Same for "private roads". Private roads in OSM are any roads that are tagged as having a private access (like private driveways, roads within a military base etc.): `highway=anything` + `access=private`. Alleys need not to be private, same as (long) driveways to i.e. museums etc.
Well, you get my point, right?

Also, you are missing the "It has no name" option, ... like "none of the above, but it still has no name!".

Perhaps like this (only regarding the menu structure, not the phrasing in US-English):

- Can't type the characters on the sign
- It has no name (opens dialog, asking "Why not?")
  - It is a service road
  - It is a track
  - It just links two roads
  - None of the above, it just has no name (opens confirmation dialog, by the way, telling the user what that would mean)
- Can't say

**Comment by matkoniecz** [comment]
- Can't type the characters on the sign
- It has no name (opens dialog, asking "Why not?")
  - It is a service road
  - It is a track
  - It just links two roads
  - None of the above, it just has no name (opens confirmation dialog, by the way, telling the user what that would mean)
  - Can't say

Would be better - from looking at SC notes it is clear that some use "Can't say" where some options in "It has no name" menu match.

Probably because they think that given highway=* line is not road at all.

**Comment by smichel17** [comment]
I'm out of energy to think about this today; I'll come back to it tomorrow.

**Comment by smichel17** [comment]
> > Highway (no public access)
> 
> What is this?

I meant, a service road for a highway, like in the picture at the top of this page:

https://en.m.wikipedia.org/wiki/Frontage_road

> For example, "a service road" is usually associated to roads that qualify as highway=service, especially of course by users who know OpenStreetMap a bit (more). Such a redefinition would be very confusing.

This is a problem and I'm not sure how to resolve it. The Wikipedia article makes it seem like frontage roads, service roads, and access roads are all the same thing. However:

- I didn't know what a frontage road was until I found that article when searching for "service road"
- I have only ever known the type of road running parallel to a highway as a "service road" (I would not call it an access road).
- Although I could see calling an agricultural or forestry road a service road, I'd be inclined to call them access roads; if you talk to me about a service road, I'm going to assume you mean, for a highway.
- ***Most importantly,** I am not sure that my intuition in the 3 points above matches the general population.*

So, I'm at a loss because *I* would call these service roads and I have a lot of trouble trying to think of a different name for them, which is the reason why the option above was poorly phrased.

---

Here's another attempt. Maybe better, maybe not.

- Can't type the characters on the sign
- It connects two roads
    - It is the center of an intersection
    - It is a lane that peels off[1]

- It is not a proper[2] road -> Opens a dialog or sub-menu, "What is it?"
    - a driveway
    - a parking lot
    - an alleyway
    - a drive-through
    - a service road
    - a track
- Can't say / other (opens "Leave a note instead?" dialog)

[1]: I have additional ideas for phrasing now, but I want to figure out one piece at a time, and the structure of the list items comes first.

[2]: I still don't like this phrasing, but I'm not sure how to do it better and, like above, we can figure that out later.

**Comment by westnordost** [comment]
> Your first section

Well, I guess then the only option is to be more wordy in the "what is it then" dialog and not use the word "service" anywhere.

> Second section

Well, I would go with this now:
I am open for suggestions regarding the wording - it can be longer phrases

- Can't type the characters on the sign
- It has no name _(opens dialog, asking "Why not?")_
  - It is something like a driveway or parking aisle
  - It is a agricultural or forestry road
  - It just links two roads
  - It is a center part of a large intersection
  - None of the above, it just has no name _(opens confirmation dialog, by the way, telling the user what that would mean)_
- Can't say

> It is a center part of a large intersection

Though, perhaps I leave this out. See my comments above.

**Comment by smichel17** [comment]
> It is something like a driveway or parking aisle

In this case, how would you distinguish between `service=driveway` and `service=parking_aisle`?

> It is a agricultural or forestry road

:+1: and s/a/an/

> It just links two roads

How will we determine which of the `highway={road type}_link`s to make this?

**Comment by westnordost** [comment]
> In this case, how would you distinguish between service=driveway and service=parking_aisle?

I don't, I just tag `highway=service`.

> How will we determine which of the `highway={road type}_links` to make this?

If it is `tertiary`, it will become `tertiary_link`, if it is `secondary`, it will become `secondary_link` etc.
For `unclassified` (and `residential`), the options are to either leave this answer-option out, this is the current behavior, or, to display it and tag something like `noname=yes` or better something like `link=yes`, if this tagging or something similar exists.
