### ISSUE TITLE
Clarify in-town vs out-of-town speed limits

### ISSUE THREAD

**Issue by smichel17** [westnordost/StreetComplete#757]
When a road has no speed limit sign, you are asked to choose whether it is in-town and out-of-town.

I grew up in a fairly rural area where there are clear distinctions between town center and out of town roads. Currently, though, I'm mapping in a fairly dense, suburban, residential area (Queens, NY). It's not clear to me whether these streets should be marked as in-town or out.

Is it possible to display any additional information that might help me make a decision? Either explicitly clarifying about suburbs in the question, or providing context so I can understand the effect of each choice (What's the in/out of town speed limit? If 20/35, this is probably out of town. If 25/45, probably in town).

**Comment by westnordost** [comment]
Hmm, not really. Usually, I guess also in the United States, the default speed limits (when no signs are posted) differ between in-town and out-of-town. The situation in Germany is, that it is clearly signposted when a locality begins and when it ends (because of the default speed limits).
Is it different in the US?

**Comment by matkoniecz** [comment]
https://en.wikipedia.org/wiki/Speed_limits_in_the_United_States#Speed_limits

If I read it correctly then "Residential" ten to have its own speed limits, though it is unclear how it is defined.

According to https://en.wikipedia.org/wiki/Speed_limits_in_the_United_States_by_jurisdiction

- Alabama has separate limits for urban areas, unpaved roads, rural paved county roads, other two-lane roads, four-lane roads, Interstate Highways
- Alaska has three classes of urban areas - business district, residential district, alleys and single default limit for all other roads
- Arizona has urban areas and school areas and as bonus has night speed limits in some places
- etc etc

And according to http://www.mit.edu/%7Ejfc/urban-speed.html local goverments in some states may set their own limits (it is unclear is it equivalent of European zone sign or is it allowing to pass legislation affecting speed limits without signing them)

>  A ``Y'' in the ``Area?'' column means state law allows local governments to set speed limits effective in an area, as opposed to posting speed limits on every street.

**Comment by smichel17** [comment]
> Hmm, not really. Usually, I guess also in the United States, the default speed limits (when no signs are posted) differ between in-town and out-of-town. The situation in Germany is, that it is clearly signposted when a locality begins and when it ends (because of the default speed limits).
> Is it different in the US?

In Massachusetts, in town is 25 mph and rural roads are 35 mph. Residential roads are also 25, but there's no clear line that I know of between residential and rural,  since people live in the latter as well; it's mostly a "feel" thing. (Note: this is from personal experience; there may actually be a formal set of rules I don't know about. But, I wouldn't expect the average mapper to know what they are).

Although that's vague, it actually does end up working in practice. Based on the width of the roads and population density, I generally know how quickly I am expected to drive on any given road. 

The lack of clarity *is* a problem when mapping, though. Particularly: while I can often estimate how fast I should drive, it's not clear to me what the effect of choosing "in town" vs "out of town" is, so I can't apply my intuition about the speed limit.

How is this recorded in the OSM database / is there a standardized format? Depending on those answer, I could see one or both of these solutions:

- Instead of selecting "in town" vs "out of town", allow putting an estimate of the speed limit.
- Separate into two quests, one for marking no sign and another for providing additional info (since "No sign" is still useful info even if it's not known whether the road is in or out of town).

**Comment by matkoniecz** [comment]
>  it's mostly a "feel" thing

https://en.wikipedia.org/wiki/Speed_limits_in_the_United_States_by_jurisdiction#Massachusetts has

> 30 mph (48 km/h) on a road in a "thickly settled" or business district for at least 1⁄8 mile (200 m)
> 40 mph (64 km/h) on a road outside of a "thickly settled" or business district for at least 1⁄4 mile (400 m)
> 50 mph (80 km/h) on a divided highway outside of a "thickly settled" or business district for at least 1⁄4 mile (400 m

with link to https://malegislature.gov/Laws/GeneralLaws/PartI/TitleXIV/Chapter90/Section17

**Comment by smichel17** [comment]
Alright, since my estimate was wrong (although close), maybe let's not allow an estimate :P

**Comment by westnordost** [comment]
I already created a special case for the United Kingdom regarding implicit speed limits. There, it does not matter for which implicit speed limit apply whether a road is in or out of town, but another factor - namely whether it is a single or dual carriageway. [See code](https://github.com/westnordost/StreetComplete/blob/master/app/src/main/java/de/westnordost/streetcomplete/quests/max_speed/AddMaxSpeedForm.java#L187).

What I want to say with this is that it is possible to add more exceptions, even on a per-state level in the US. But if something should be implemented there, I would need to know, what the surveyor should be asked in the case he specifies that there is no speed limit posted.

**Comment by matkoniecz** [comment]
The problem is that  it is unreasonable to ask user whatever road matches insane 'thickly settled" or business district for at least 1⁄4 mile'

Is there a good way to tag that maxspeed is unsigned, without tagging max speed?

**Comment by westnordost** [comment]
> How is this recorded in the OSM database / is there a standardized format? Depending on those answers, I could see one or both of these solutions:

It is recorded as not setting `maxspeed` to any numerical value but instead set `maxspeed:type` to `US:urban` or `US:rural` (in the US).

**Comment by westnordost** [comment]
> The problem is that it is unreasonable to ask user whatever road matches insane 'thickly settled" or business district for at least 1⁄4 mile'

Well, as @smichel17 said, it's a "feel" thing. So, while the 1⁄4 mile might be the hard definition, in practice, people will decide whether something is `urban` (aka "thickly settled") or `rural` (aka "not thickly settled") subjectively. As subjectively as a surveyor with StreetComplete would decide that. Also, by the way, the definition you cited is really not that fixed because "thickly settled" is subjective anyway.

**Comment by smichel17** [comment]
I think I figured out the root problem I was having answering this question for a suburban area like this. If you asked me "Is it Urban or Rural?" I'd end up saying "Urban". If you asked me, "Is it in town or out?" I'd say out.

I *think* in this case, `US:Urban` makes more sense as a label (40 mph is not reasonable on these roads; 30 is). So, maybe a solution would be to just make the choices Urban/Rural instead of in/out of town?

**Comment by smichel17** [comment]
Maybe something like, "Roads have a different default speed limit in urban (in town or densely populated) and rural *(out of town, sparsely populated)* areas."

I think the italicized part could be left out and would still be implied. That would make the sentence flow better, so I would do it unless you're concerned that it would be confusing.

**Comment by westnordost** [comment]
The current text is:

**Where is this street?**
Urban roads have a different default speed limit than rural roads.
[In town] [Out of town]

So the description already mentions urban and rural. It were the button names I guess that confused you.

**Comment by smichel17** [comment]
> The description already mentions urban and rural.

I know; I based my suggestion on the current text. 

> It were the button names I guess that confused you.

Specifically, it was the fact that the button names conflicted with the description text. Changing the labels and (more importantly) adding the parenthetical clarifies that I should pick the `Urban` label if the area is densely populated, *even if it is out of town.*

**Comment by rugk** [comment]
I also think in the German version this is less problematic, as there "in town" and "out of town" are the official terms for these things ("innerorts", "außerorts") that everyone knows.
So maybe the literal translation into English has caused some confusion here.

**Comment by westnordost** [comment]
Ok, I will change it as suggested and also change the button names (in English) to rural and urban
