### ISSUE TITLE
image and answers not intuitive in tactile pavings quest

### ISSUE THREAD

**Issue by althio** [westnordost/StreetComplete#762]
I find it slightly counter-intuitive that with the composite image of tactile pavings https://github.com/westnordost/StreetComplete/issues/238#issuecomment-306461754 the 3 images are more or less aligned with the possible answers
![](https://camo.githubusercontent.com/ddd0dafd508a3a3c52b496bc97e6daaf39282186/68747470733a2f2f6672616d617069632e6f72672f757144577970436f6e4350782f59696554426575544657496a2e6a7067)

1 | 2 | 3
--- | --- | ---
[CAN'T SAY] | [NO] | [YES]

**Comment by CloCkWeRX** [comment]
Yeah, that broke my brain for a bit after having gotten used to the select-a-picture UX of road surfaces.

**Comment by westnordost** [comment]
True, this might be confusing. Do you have a proposal how to solve this?

**Comment by althio** [comment]
> Do you have a proposal how to solve this?

Here is a proposal mockup (picture can be clicked on, for answer as YES):
![tactile_mockup_sm](https://user-images.githubusercontent.com/9863567/34775277-e170e288-f612-11e7-83ae-ab8fe53fd322.png)

for reference, the current layout (picture cannot be clicked on):
![tactile_before_sm](https://user-images.githubusercontent.com/9863567/34775285-e8c48102-f612-11e7-81c4-85952895deee.png)

**Comment by westnordost** [comment]
Mh no, don't like it. This is a break from the normal UI.

One could add "Usually looks like this:" above the picture and make the picture a bit less high (so that the form does not scroll)

**Comment by althio** [comment]
Well, the fact that you see picture but cannot click on them: this is also a break from the normal UI.
I find it worse.

I may try one or two other options for different mockups.
Is it an option to include pictures without tactile paving for NO?

**Comment by lokaman** [comment]
As you both realize none of the two options is 100% consistent.

May take a look at the "street paving" quest to see how "clickable picture" quests are designed - sadly my mobile github client doesn't support the upload of pictures:

-  Pictures you can click on, have a description in white letters
- If you click on one of the three main category, a sub category is opened
- This sub category contains different pictures, separated by empty white space

The current solution is indeed a small UI change, but as the pictures aren't seperated it is a intuitive solution - at least this is my experience. The proposed option includes more fundamental UI breaks - moving a standard answer like "yes", giving less space for the pictures.

I don't think it is necessary, but may a "for example" or something similar would to the trick?!

Is there a design guideline, any rules?
