### ISSUE TITLE
toggling "show all notes" setting takes several seconds

### ISSUE THREAD

**Issue by matkoniecz** [westnordost/StreetComplete#763]
Is it intentional (circle in the first image is fom capturing exact moment when I clicked to cycle state)?

![selection_002](https://user-images.githubusercontent.com/899988/34780291-096b46ce-f623-11e7-94c3-fbb430d26b38.png)
![selection_003](https://user-images.githubusercontent.com/899988/34780294-0a624690-f623-11e7-82b9-32f3ce8d22ad.png)
![selection_004](https://user-images.githubusercontent.com/899988/34780296-0b5bf208-f623-11e7-93ca-c0e5b310f2c0.png)

**Comment by matkoniecz** [comment]
![ezgif-4-fe75757d6d](https://user-images.githubusercontent.com/899988/34780505-a20ad78c-f623-11e7-934d-2deb6c85f760.gif)

**Comment by westnordost** [comment]
Did you just click the button while it was disabled?

Am 10. Januar 2018 16:30:59 MEZ schrieb Mateusz Konieczny <notifications@github.com>:
>![ezgif-4-fe75757d6d](https://user-images.githubusercontent.com/899988/34780505-a20ad78c-f623-11e7-934d-2deb6c85f760.gif)
>
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/westnordost/StreetComplete/issues/763#issuecomment-356637169

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by matkoniecz** [comment]
Yes, simple clicking cycles it through three states (at least I attempted to only click, without trying weird things).

**Comment by westnordost** [comment]
I don't really know what you mean with three states, I see only two, but that you can click while it is disabled is a bug.

Am 10. Januar 2018 16:49:01 MEZ schrieb Mateusz Konieczny <notifications@github.com>:
>Yes, simple clicking cycles it through three states (at least I
>attempted to only click, without trying weird things).
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/westnordost/StreetComplete/issues/763#issuecomment-356642998

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by matkoniecz** [comment]
> I don't really know what you mean with three states, I see only two, but that you can click while it is disabled is a bug.

On your phone or in my video? I see three states what should be visible in posted images.

**Comment by westnordost** [comment]
In the video. Either the switch is on or off.

Am 10. Januar 2018 18:03:43 MEZ schrieb Mateusz Konieczny <notifications@github.com>:
>> I don't really know what you mean with three states, I see only two,
>but that you can click while it is disabled is a bug.
>
>On your phone or in my video? I see three states what should be visible
>in posted images.
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/westnordost/StreetComplete/issues/763#issuecomment-356667587

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by rugk** [comment]
No it has three states:
* disabled, greyed out
* enabled, greyed out
* enabled, orange

I think the second state (kinda inconsistent) is the bug here.

**Comment by matkoniecz** [comment]
Yes, in video I clicked thrice. On additional testing (clicking on show notes setting in SC 3.4) I managed to get also "disabled, not greyed out" state.

**Comment by westnordost** [comment]
It is grayed out (=disabled) when it is applying the changes, which takes a second or two. It is a bug if it is clickable while being disabled. Is it? Then, perhaps you can try to fix that and create a PR for that.

Am 10. Januar 2018 18:46:33 MEZ schrieb Mateusz Konieczny <notifications@github.com>:
>Yes, in video I clicked thrice. On additional testing (clicking on show
>notes setting in SC 3.4) I managed to get also "disabled, not greyed
>out" state.
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/westnordost/StreetComplete/issues/763#issuecomment-356680495

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by matkoniecz** [comment]
> It is grayed out (=disabled) when it is applying the changes, which takes a second or two. 

Is it possible to disable this? It is kind of information completely useless for user that will be either ignored (useless) or confuse user (harmful).

**Comment by westnordost** [comment]
What, this is completely normal behavior. If you write a comment on GitHub and click on the Comment-button, it will also be greyed out while it loads.

**Comment by matkoniecz** [comment]
Probably my confusion here is caused by that unlike during using browser I was not expecting lag reaching multiple seconds.

Probably in ideal world toggling would toggle setting rather than iterate over all quests or whatever expensive operation that is triggered here.

If changing that would be too time consuming to be worth removing confusing it probably may be closed (at this moment I have no idea how complicated that change would be).

**Comment by westnordost** [comment]
Well, it is a bug if it is clickable while being disabled. Is it?

**Comment by matkoniecz** [comment]
> Is it?

No

**Comment by westnordost** [comment]
Ok then
