### ISSUE TITLE
force refresh if quest cache is very old

### ISSUE THREAD

**Issue by matkoniecz** [westnordost/StreetComplete#766]
https://www.openstreetmap.org/note/1267879 answered 2 hours ago to quest that was outdated since 5 months https://www.openstreetmap.org/node/258828603/history

next case - https://www.openstreetmap.org/note/1381967#map=18/50.73701/7.10388 that triggerred #1046 

I think that quests older than 1 month should be invalidated, no matter whatever user downloaded new or not.

**Comment by matkoniecz** [comment]
Given earlier edits like https://www.openstreetmap.org/changeset/55414660#map=19/48.58106/7.77016 I think it is safe to rule out situation of answering months ago and uploading answers now.

**Comment by westnordost** [comment]
However, if someone is explicitly downloading an area for offline use later, these quests should be save from auto-deletion, shouldn't they?

**Comment by matkoniecz** [comment]
Yes, that is why I think 1 month is a good limit.

**Comment by westnordost** [comment]
But how to communicate this to the user? Or do you think it does not need to be communicated?

**Comment by matkoniecz** [comment]
I think that silent deletion after month is OK.

I am not sure is it necessary to handle usecase of caching quests for months. At this moment SC is anyway not supporting well such large-scale offline editing as there is no way to cache map for any substantial area (scrolling through map to download works for areas up to a small town).

If one want to warn user there is one complication - any message about quests about to expire would also be displayed to any users who edited in some location is past and stopped doing this (they were on holidays or some other trip).

**Comment by rugk** [comment]
If this background information is really necessary to communicate (in the unlikely chance that any user encounters it), just put it into the FAQ. Such a question may answer cache invalidation things in general… I think that is also a quite common question (i.e. something like "What effect does the setting for quest invalidation in the settings have?"

**Comment by matkoniecz** [comment]
> added the feedback required label 12 days ago

I tried to answer in https://github.com/westnordost/StreetComplete/issues/766#issuecomment-357538521 - let me know if anything is unclear/not explained.

**Comment by leftshift** [comment]
We could add a warning about this when disabling auto-sync, which is probably the most likely way to end up with old completed quests
