### ISSUE TITLE
add "it is a garage" option for housenumber quest

### ISSUE THREAD

**Issue by matkoniecz** [westnordost/StreetComplete#767]
Sometimes building value are not correctly set. From looking at OSM notes it seems that the most common mistake is garage tagged as a residential building.

Maybe making possible to fix it directly in SC would be a good idea?

example of note: https://www.openstreetmap.org/note/1267738

**Comment by matkoniecz** [comment]
If other cases of mistagged buildings are common it may be also worth adding them.

**Comment by westnordost** [comment]
Or perhaps rather_It has no housenumber_ -> Opens dialog, which asks why not. There are then several answer options, one of them would be _"It is not a kind of building where one would expect it to have a housenumber"_ (or shorter somehow).

**Comment by matkoniecz** [comment]
"It is not a kind of building where one would expect it to have a housenumber" would retag it to building=yes, right?

I think that it may be also an option but direct retagging to building=garage also should be available (for some reason it is quite common tagging issue).

**Comment by westnordost** [comment]
Well, that is an option. But I thought it would open the notes dialog in which the user is prompted to explain what building it is then.

When the building quest is implemented, that prompt could be replaced by using the same UI as the building type quest.

**Comment by matkoniecz** [comment]
> user is prompted to explain what building it is then.

Is it then used to create note anyway? Main benefit of what I proposed is that it edits directly rather than creating a note.

> When the building quest is implemented, that prompt could be replaced by using the same UI as the building type quest.

That is probably the best solution.

**Comment by westnordost** [comment]
> Is it then used to create note anyway?

Yes, the goal would be to make it clearer to the user what to do (and what information to provide), not to avoid notes.

**Comment by rugk** [comment]
> Main benefit of what I proposed is that it edits directly rather than creating a note.

Generally the note field could have a pre-defined set of values (dropdown like in streetname quest), which – when selected – avoid the note generation and directly edit the object.

**Comment by matkoniecz** [comment]
I think that note generation is also a good goal.

With direct edit user taps something in SC.

With note creation user taps something in SC, others review note, look at aerial images or resurvey, make edit, close note...

Whenever possible note generation should be avoided.

**Comment by exploide** [comment]
Since almost all house number quests in my area are mistagged garages, I'm wishing for this a long time. But I considered #351 as the covering issue, even if the opening post is somewhat different in contrast to the goals developed later. It's already marked as blocked by the building type quest #25, the currently most upvoted issue.

So :+1: for the solution involving the building type quest.

**Comment by westnordost** [comment]
True, #351 is the covering issue.
