### ISSUE TITLE
[Road Surface] Selecting "Unpaved (generic)" should scroll up

### ISSUE THREAD

**Issue by smichel17** [westnordost/StreetComplete#770]
There are two issues with the same solution:

1. When selecting 'paved (generic)' it's not clear that additional options have appeared below. I was initially confused because I didn't see any other options. Particularly, I almost submitted the generic option because I did not realize more specific options existed
2. I most commonly select asphalt. This would be much, much faster if I did not have to manually scroll up each time.

**Comment by ENT8R** [comment]
Duplicate of #76?

**Comment by smichel17** [comment]
Oops, yes, I should have searched.

**Comment by westnordost** [comment]
After all, I managed to implement this.
