### ISSUE TITLE
opening_hours syntax error: different hours on different days should be separated by a semicolon

### ISSUE THREAD

**Issue by stefannagy** [westnordost/StreetComplete#773]
I used StreetComplete to add opening hours to some shops and a pub; after coming home I checked the results (see node 620475772, node 5026653045 and node 1717933599).

In all three cases there are different opening hours on different days – which AFAIK should be separated by a semicolon (see https://wiki.openstreetmap.org/wiki/Key:opening_hours) but it seems StreetComplete uses commas.

**Comment by westnordost** [comment]
This is correct, and a comma is also correct syntax (has a different meaning). See https://wiki.openstreetmap.org/wiki/Key:opening_hours/specification

**Comment by stefannagy** [comment]
Oh, I see – thanks! Just one more question: Since I can't see any reason why the normal rule separator isn't used in the cases mentioned above – am I correct when I assume you use the additional rule separator by default (and maybe only in special cases you use the normal rule separator)? I'm just trying to understand…

**Comment by westnordost** [comment]
Yes, I use the additional rule separator always because that rule separator has exactly the meaning as opening hours given on a name plate usually have to be interpreted - and thus are supplied in the app, as it should be WYSIWYG.

Look here:
http://www.ag-medebach.nrw.de/kontakt/oeffnungszeiten/index.php

Mind the difference between:
1. http://openingh.openstreetmap.de/evaluation_tool/?EXP=Mo-Fr%2008:00-12:00;%20Mo%2014:00-15:00
2. http://openingh.openstreetmap.de/evaluation_tool/?EXP=Mo-Fr%2008:00-12:00,%20Mo%2014:00-15:00

**Comment by stefannagy** [comment]
This makes a lot of sense to me… Thanks a lot for taking the time!

**Comment by matkoniecz** [comment]
note that https://github.com/streetcomplete/StreetComplete/issues/773#issuecomment-357799074 (comment by `@westnordost`  just above comment by `@stefannagy` is outdated now, see https://github.com/Helium314/SCEE/issues/581#issuecomment-2221165148

> Thanks for the link, but that comment is outdated. No longer does StreetComplete always use the comma operator.

> The "magic" that decides in StreetComplete whether to use , or ; as a rule separator is here:

> https://github.com/streetcomplete/StreetComplete/blob/fa538aaf983bc32559e8cc6f682fdbe10dd0133c/app/src/main/java/de/westnordost/streetcomplete/osm/opening_hours/parser/OpeningHoursGenerator.kt#L121-L123

> The comment explains it:

>    if any rule collides with another, e.g. "Mo-Fr 10:00-12:00; We 14:00-16:00", switch to additive rules e.g. "Mo-Fr 10:00-12:00, We 14:00-16:00"

> Compare these two opening hours strings in https://openingh.openstreetmap.de/evaluation_tool/ to learn the difference in meaning.
