### ISSUE TITLE
Streetsurface quest: Long-press on item for "advanced options"

### ISSUE THREAD

**Issue by rugk** [westnordost/StreetComplete#775]
I think you may consider it to be a bad thing (too far hidden), but I had the idea that advanced users may get some more options without an UI change at all.
E.g. selecting concrete is not so obvious in the street surface quest, because you may also have "concrete:planes" or "concrete:plates", which are different that just the whole area filled with concrete.

The same "grouping" mechanism could be applied to the sett/cobblestone issue, see https://github.com/westnordost/StreetComplete/issues/728.

Note that it is designed to be a feature to show some rarely used entries. That's why it is "hidden" from an UX point of view, i.e. only advanced users may see it (e.g. these used to OSM mapping). It could be mentioned in the FAQ if needed.

So what do you say about this?

**Comment by westnordost** [comment]
Hmm, I do not like the idea about having such a hidden UI, to be honest. It's almost like an easter egg.

**Comment by rugk** [comment]
Hmm, you could give a visual indicator, at least. E.g. on some emoji "keyboard"/"input" fields, which basically have the same feature for selecting the color/variant of the Emoji, they display a triangle in the top-right corner. That usually gives the clue there.

**Comment by westnordost** [comment]
Hmm no, I find this a weird mixup of UI concepts.
