### ISSUE TITLE
add missing religion tag to amenity=place_of_worship

### ISSUE THREAD

**Issue by matkoniecz** [westnordost/StreetComplete#777]
### General
Affected key(s) (or tags) to be modified: [religion](https://wiki.openstreetmap.org/wiki/Key:religion)
Question asked: **What is the religion on XY?**

### Checklist
Checklist for quest suggestions (see guidelines):
- [x] 🚧 To be added tag is established and has a useful purpose - prominently used in many maps, including default style on the OSM main site
- [x] 🤔 Any answer the user can give must have an equivalent tagging (Quest should not reappear to other users when solved by one) - every place of worship can be tagged (or it is invalid and should be deleted)  (note that some may have religion=multifaith)
- [x] 🐿️ Easily answerable by everyone from the outside but a survey is necessary (at least in European countries, may be not enabled everywhere)
- [x] 💤 Not an overwhelming percentage of elements have the same answer (No spam) - amenity=place_of_worship is relatively rare compared to missing surface or building tags
- [x] 🕓 Applies to a reasonable number of elements (Worth the effort) 9% of 948k place_of_worship has no religion tag - https://taginfo.openstreetmap.org/tags/amenity=place_of_worship#combinations

### Ideas for implementation

https://commons.wikimedia.org/wiki/Category:Religious_computer_icons has decent icons ( https://commons.wikimedia.org/wiki/Category:Religious_computer_icons#/media/File:Emoji_u2721.svg )

https://github.com/gravitystorm/openstreetmap-carto/tree/master/symbols has decent icons ( https://github.com/gravitystorm/openstreetmap-carto/blob/master/symbols/jewish.svg )

https://github.com/gravitystorm/openstreetmap-carto/blob/master/symbols/place_of_worship.svg for the quest icon

**Element selection:** 
Reuse sport/crop quest.

**Metadata needed:** 
yes it is necessary and I may supply it (for areas that are already mapped in OSM)

**Proposed GUI:** 

It would be a good idea to allow supplying info about denomination (so at least in some countries there may be a separate answer for religion=christian and religion=christian  with denomination=catholic)

**Promises:**

I plan of making quest like this, if idea of quest is accepted I plan on making it good enough for StreetComplete PR.

**Comment by matkoniecz** [comment]
note hat it may be possible to make very similar quests for other objects taggable with religion tag, but these quests have lower priority as data is less frequently used

**Comment by westnordost** [comment]
I could have sworn that there was already a ticket for that. At least, I already made an icon :-)

**Comment by westnordost** [comment]
I would make the icons for this. For the most popular ones, I think the Emoji-ones are nice.

Also another source: https://commons.wikimedia.org/wiki/Religious_symbol

**Comment by westnordost** [comment]
By the way, especially for Chinese temples, from my experience, it is very difficult to see which religion it is actually. Generally, people would refer to these temples rather as "Chinese temple" than say exactly which religion it is.

**Comment by matkoniecz** [comment]
> especially for Chinese temples

Is it as in "temples in China" (easy, quest would be disabled in China) or "temple that may appear in any country and typical person is unable to identify religion that is practiced there"?

**Comment by rugk** [comment]
https://en.wikipedia.org/wiki/Chinese_temple

**Comment by rugk** [comment]
>  At least, I already made an icon :-)

You maybe did that for https://github.com/westnordost/StreetComplete/issues/232, which is similar (and may require similar data, such as country-level data), but still a different quest. 😃

**Comment by matkoniecz** [comment]
I started thread on tagging mailing list as part of working on this quest.

**Comment by matkoniecz** [comment]
It turns out that significant part of untagged religions is result if useless MAPS.ME edits resulting in

![selection_007](https://user-images.githubusercontent.com/899988/35157110-48780e62-fd33-11e7-8263-f06a82ede4d1.png)

**Comment by westnordost** [comment]
Not necessarily. That nodes are added as duplicates is something that would affect every quest. To add detail to a duplicate node does not make the data worse.

**Comment by matkoniecz** [comment]
OK, I will make PR without such filtering. Anyway, it can be later changed if it turns out to be necessary.

> something that would affect every quest

Maybe I am unlucky but this quest appears to be affected more than usually.

> To add detail to a duplicate node does not make the data worse.

But it wastes time of surveyor.

**Comment by westnordost** [comment]
Also, the country metadata does not need to be so detailed (as for orchards). As long as the *most* popular religions are in the top row (first four), it's fine. That means that for most countries, no special order that overrides the default needs to be defined.
Obviously for i.e. India it should be defined: Hindu, Sikh, Jain,...

**Comment by matkoniecz** [comment]
> does not need to be so detailed (as for orchards). As long as the most popular religions are in the top row (first four), it's fine

It will probably be something similar to sports metadata. I will try to allow specifying also denomination, but I will need to verify whatever it is possible without making it confusing.

**Comment by matkoniecz** [comment]
Initial code: https://github.com/westnordost/StreetComplete/compare/master...matkoniecz:religion?expand=1

I am considering making new class so onCreateView, createItems, getMaxSelectableItems and applyMultiAnswer would not be duplicate in this new quest and AddSport.

**Comment by my-na-me** [comment]
btw, this is maybe a bit off topic, but in some way related to the "place_of_worship"-tagging.

I have a feeling especially some JOSM user don't really care for the building tag* at the moment when they are adding place_of_worship-POIs into osm-db.

Is the building-tag-check for place_of_worship-POIs an idea to create other quest type or could/should the building-tag-check be done at the same time when the religion-check takes place?

* (maybe the JOSM preset place_of_worship could be also modified in same way)

**Comment by matkoniecz** [comment]
> btw, this is maybe a bit off topic

Is is better to create a new issue in such situations.

>   (maybe the JOSM preset place_of_worship could be also modified in same way)

it seems that it should be reported at http://josm.openstreetmap.de/wiki/Help/Action/ReportBug

**Comment by matkoniecz** [comment]
>  could/should the building-tag-check be done at the same time when the religion-check takes place?

Sounds like #25

**Comment by westnordost** [comment]
By the way, some sources:

1. http://www.religionfacts.com/big-religion-chart
2. https://en.wikipedia.org/wiki/Religious_information_by_country

**Comment by rugk** [comment]
Also:
* https://www.statista.com/statistics/374661/countries-with-the-largest-muslim-population/
* https://www.statista.com/statistics/374664/countries-with-the-largest-hindu-population/
* https://www.statista.com/statistics/374666/countries-with-the-largest-buddhist-population/
* https://www.statista.com/statistics/374657/countries-with-the-largest-christian-population/
* https://www.statista.com/statistics/374669/countries-with-the-largest-jewish-population/

**Comment by matkoniecz** [comment]
icons for religion quest added in https://github.com/westnordost/StreetComplete/commit/52bd6f41f4e14b437f70e6db3dc05f117540db19appear to be unavailable from R.drawable.

I expected them to be available like `R.drawable.ic_sport_soccer`.

It is not obvious what should be changed (in code or on my computer) to make this group of icons available.

**Comment by callis** [comment]
The UN has all the data
http://data.un.org/Data.aspx?q=population+religion&d=POP&f=tableCode%3a28%3bsexCode%3a0&c=2,3,6,8,10,12,14,15,16&s=_countryEnglishNameOrderBy:asc,refYear:desc,areaCode:asc&v=1

**Comment by rugk** [comment]
Hmm, you can download it as CSV (comma or semicolon)… So it could be evaluated similar to the https://github.com/rugk/crops-parser, with some adjustments.

**Comment by matkoniecz** [comment]
> icons for religion quest added in 52bd6f4 appear to be unavailable from R.drawable.

fixed in https://github.com/westnordost/StreetComplete/commit/429a92c932f95acb2356adce3965f66634760f21 - thanks!

**Comment by matkoniecz** [comment]
I have trouble with Haiti. From looking at data it seems that supporting religion=voodoo would make sense.

But I failed to find good icon or even any symbol that would work well as an icon.

I am thinking about using blank icon for it or ignoring that this religion exists.

**Comment by westnordost** [comment]
I'd say, ignore it. See https://en.wikipedia.org/wiki/Religion_in_Haiti

They may practice more Vodou at home, but all those religious buildings and places of worship will be Christian then.

It is the same with (Neo-)Paganism or Falung Gong I guess. May be practiced by a (bigger) minority in certain countries, but they do not really have places of worship.

**Comment by rugk** [comment]
Fixed by https://github.com/westnordost/StreetComplete/pull/802

@matkoniecz the "fixes" in the title is not recognized by GitHub. You have to include it in the body of the PR.

**Comment by matkoniecz** [comment]
hmmm.

**Comment by matkoniecz** [comment]
Well, apparently github decided to broke something - see https://help.github.com/articles/closing-issues-using-keywords/ (fixes is in list).

Thanks for noticing!

**Comment by rugk** [comment]
He, no, you say there:
>  one from #777 (comment)

This is missing the "Fixes" keyword and I am also not sure whether it works when you link to a comment.
