### ISSUE TITLE
Add download-in-progress indication

### ISSUE THREAD

**Issue by gdt** [westnordost/StreetComplete#78]
When streetcomplete does not have the screen, there's a download-in-progress notification.   But when it's foreground, you can't tell if it's downloading or not.   Some sort of subtle indication would be nice.

**Comment by westnordost** [comment]
This is actually a bug. There should be one just below the toolbar.

**Comment by westnordost** [comment]
Could you say which smartphone and android version you are using, in case this is only reproducible on certain devices and versions?

**Comment by gdt** [comment]
Nexus 5, CM 13.1

**Comment by westnordost** [comment]
Hmm, I just cannot reproduce it. I tested the following:
- manual quest download
- clearing all data, starting app -> on GPS fix, quests are downloaded automatically
- manually downloading quests, press home, see progress notification, click on progress notification to go back to the app
- having animations off and downloading them automatically
For all these, the progress is shown as normal.

So, it is not shown at all? Or only if you have autosync on?

**Comment by westnordost** [comment]
Also can't reproduce on an Android 6.0 emulator (CM 13 is Android 6)
