### ISSUE TITLE
Link to FAQ in app description and maybe app itself

### ISSUE THREAD

**Issue by rugk** [westnordost/StreetComplete#781]
So as the FAQ is on https://wiki.openstreetmap.org/wiki/StreetComplete/FAQ, you may just link there in the app description and other places…

So I'd say it would be good to have these in:
* [x] OSM wiki (Already done)
* [ ] GitHub Readme
* [ ] Google PlayStore description
* [ ] F-Droid Readme
* [ ] in-app (maybe?)

**Comment by westnordost** [comment]
The FAQ is for OpenStreetMap users who wonder about how StreetComplete works - neither for users of it (in-app + app stores), nor for developers (who can look themselves). Thus, to link it in the OSM wiki is enough, in my opinion.

**Comment by rugk** [comment]
Hmm, I doubt that we should only have a FAQ for OSM people. That's also why I added usual user-questions like "Do I need to be an OpenStreetMap expert to use it?" or "Why does StreetComplete show so few quests when I first start the app?"…

Note you can always group the FAQ in the OSM wiki a bit if there are questions only "for users" and some only for "all who want to know the details how it work".

**Comment by HolgerJeromin** [comment]
FAQ 1, 2, 7 are for app users.

**Comment by westnordost** [comment]
I did not write that.

**Comment by westnordost** [comment]
OK you can add something in a PR for the readme here, if you want.

**Comment by rugk** [comment]
Okay, so far, but I'd still argue that this would also be useful in the app description, as there you will get new users, respectively these users may be looking for information about the app before installing them.
