### ISSUE TITLE
Highlight quests in settings, which were added in an app update

### ISSUE THREAD

**Issue by rugk** [westnordost/StreetComplete#790]
In the quest selection/sort settings, you should highlight (yellow background and maybe a note on the top or so) quests, which were added in an app update, when the user first looks into the new settings.

_At least_ you should do so, when the user has customized the settings there, before. Because after an update one may "pigeon-hole" (sort) the new quest into the existing order. I don't know what determinates where in the list they appear, when the list was customized by the user, but in any case the user mnight want to review and change the order for new quests.

As a nice additional feature, it would act as a kind of "integrated changelog" as it highlights the new nice quests, the user has always hoped to solve with StreetComplete… 😉 

As for the UI I'd say on top of that settings screen (or on the bottom with these material design-like bottom notification) you should in such a case display a yellow message "New quests were added by updates, since you last reviewed this list. We suggest you to scroll down and adjust it, accordingly."). That message should, of course, (as the other highlights) only appear once after an update (if the user looks into the settings screen) and the user should have an `x` or so in order to close it directly.

**Comment by westnordost** [comment]
> Because after an update one may "pigeon-hole" (sort) the new quest into the existing order. I don't know what determinates where in the list they appear, when the list was customized by the user, but in any case the user mnight want to review and change the order for new quests.

It's quite an elaborate algorithm :-). Basically, StreetComplete only memorizes what the user changed from the default order. So, if the default order changes or new quests are introduced, they should appear at the correct position.

As for your feature request, the answer is no :-(, I find this too much effort and the whole quest selection screen is supposed to be somewhat of an advanced feature.

However, you can open a feature request for an integrated changelog. That is a feature request I can understand, though, for me, it has not such a high priority.

**Comment by rugk** [comment]
> However, you can open a feature request for an integrated changelog.

Actually, I would not find that useful. Especially as for StreetComplete the changelog for mayor versions is just new quests, this issue *here* is about a changelog, more or less. (And usually the users 
If you want I phrase it differently (and also a bit different functionality)…

On an app start after an update, show a banner "See new quests".
This may take you to the settings page, where all quests are listed, and highlights the new ones with a yellow background. What the user does, afterwards, does not matter… 😃
