### ISSUE TITLE
Privacy Issue: File Name of Uploaded Pictures Contains Date and Time

### ISSUE THREAD

**Issue by blipp** [westnordost/StreetComplete#791]
**Situation:** The filename of images uploaded by the application contains the exact date and time at which the picture was taken. Example: https://lut.im/tdaceZP1nK/3K9j5PNSaINt5cNu has as filename `photo_20180122_113718_-113362464.jpg`. This contains the exact time I took the picture.

**Comment:** The privacy issue here is that more or less detailed movement profiles could be constructed. Sure, when uploading to OpenStreetMap, the timestamp of this moment when the uploading took place is automatically included by the OpenStreetMap server. But users can wait some hours or days before uploading if they want to protect some of their location privacy.

**Suggestion:** I suggest to give the image a random filename. Date and time are not needed, and are anyway only included in the filename, which most people won't spot.

Please note that overall I am very happy about privacy: images do not contain any other metadata, and StreetComplete does apparently not include other timestamps in the uploaded data. Nice :) Keep up the good work, I enjoyed doing some quests today and will definitely continue to do so.

**Comment by blipp** [comment]
For completeness: I checked before that it's not lut.im who chooses the filename, but I could not find within a reasonable time the location in StreetComplete's code that sets it.

**Comment by rugk** [comment]
Ref: https://github.com/westnordost/StreetComplete/issues/753 (privacy considering upload times, has been discussed there, too; nobody found that in the images, however, good found!)

**Comment by rugk** [comment]
As a suggestion for an alternative name. GPS coordinates. This is not-private data here… 😄

**Comment by althio** [comment]
> @blipp   I could not find within a reasonable time the location in StreetComplete's code that sets it.

I guess the name of the image is set here
https://github.com/ENT8R/StreetComplete/blob/master/app/src/main/java/de/westnordost/streetcomplete/quests/note_discussion/AttachPhotoFragment.java#L166

**Comment by ENT8R** [comment]
According to the [android documentation](https://developer.android.com/reference/java/io/File.html#createTempFile(java.lang.String,%20java.lang.String,%20java.io.File)), we do not even need to pass the date when the picture was taken as the first argument. calling
```java
File.createTempFile("photo", ".jpg", directory);
```
is enough because this method does automatically generate a random string which does not conflict with an existing file in the specified directory.
The documentation says:

> Creates a new empty file in the specified directory, using the given prefix and suffix strings to **generate its name**.

In the example above this is the `-113362464` before the `.jpg`...
I created a PR to fix this. (see #793)

**Comment by blipp** [comment]
Cool, thanks for the positive and fast feedback, and also the really fast fix :)
