### ISSUE TITLE
Ordering of quests – Indicator of priority order

### ISSUE THREAD

**Issue by rugk** [westnordost/StreetComplete#792]
IMHO in the ordering of quests it is not clear whether I should move quests *up* or *down* when I want to increase the priority e.g. I can guess based on the preset values, but that is no good (UX).

So maybe add some indicator where "higher priority" or "more often shown" is and where the opposite is.

**Comment by westnordost** [comment]
So, what do you think?

**Comment by rugk** [comment]
At the right top right a small text "top priority" or, to avoid the priority term "mostly shown" and, similarly, on the bottom "low priority".

**Comment by westnordost** [comment]
Correct. Top is highest prio, bottom is lowest. If you got it right, what is this ticket for, then?

**Comment by rugk** [comment]
I had to guess/evaluate it from the existing quests It just was not really obvious ("intuitive").

**Comment by westnordost** [comment]
Are there more opinions?

Am 23. Januar 2018 12:52:27 MEZ schrieb rugk <notifications@github.com>:
>I had to guess/evaluate it from the existing quests It just was not
>really obvious ("intuitive").
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/westnordost/StreetComplete/issues/792#issuecomment-359767299

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by matkoniecz** [comment]
For me "top of the list", "first on the list", "ones that appear before other quests", "sounding more important" were enough to make intuitive that top of the list is for high-priority entries.

**Comment by rugk** [comment]
> "top of the list", "first on the list", "ones that appear before other quests", "sounding more important"

Where are your quotes from? In the app it does not show that. But maybe one can include it there.

The [current text](https://github.com/westnordost/StreetComplete/blob/master/app/src/main/res/values/strings.xml#L437) states:
> Long-press and move a quest to reorder its priority for download and display on the map.

So maybe just change it slightly:
> Long-press and move a quest down to lower its priority for download and display on the map.

(The user should be clever enough to get, that you can also move quests up. But as you start from the top, you may actually move them down.)

Or:
> Long-press and move a quest to reorder its display and download priority from top [priority] to lowest.

**Comment by lokaman** [comment]
I don't know any reason why someone could think important stuff is at the bottom. May @rugk can explain this? Are there any cultural differences I don't know yet?

**Comment by rugk** [comment]
Well… maybe a bit too "programmer's thinking" of starting a list from the top and just beginning with the smallest value or so… Don't know *why* it was not really obvious, but I think a small text change is easy, s it should not hurt.

**Comment by westnordost** [comment]
Yeah, so, I don't see need for action here.

**Comment by thymaro** [comment]
I know why it wasn't intuitively clear. Because priorities don't seem to be respected. I'll open a new ticket about it.
