### ISSUE TITLE
Tactile paving/crossing quest changes highway=crossing node

### ISSUE THREAD

**Issue by goldfndr** [westnordost/StreetComplete#796]
I tried the tactile paving quest and I saw that it changed the highway=crossing node, which was in the middle of the road and not at an edge (kerb).

The [English crossing Wiki page](https://wiki.openstreetmap.org/wiki/Key:crossing) says, for the tactile_paving key, "Tag on the node representing the kerb (en_US: curb) on the highway=footway. Add the footway as single way where needed." Usually, the only time there's a kerb in the middle of the crossing is if there's a dual carriage that's been mapped as a single carriage.

The [English tactile_paving Wiki page](https://wiki.openstreetmap.org/wiki/Key:tactile_paving) says "When a footway next to a road ends at a crossing with a lowered kerb (kerb), tactile_paving is often used to indicate the dangerous spot tactile_paving=yes." If the crosswalk doesn't have tactile paving along its length then there is no "dangerous spot" in the middle of the road, to my reading.

Is this different in other languages? Is this tag so commonly used for highway=crossing nodes that the wiki should be updated to reflect common usage?

**Comment by matkoniecz** [comment]
It seems that https://wiki.openstreetmap.org/wiki/Key:tactile_paving#Use_on_nodes https://wiki.openstreetmap.org/wiki/Tag:highway%3Dcrossing should be updated given real use - https://taginfo.openstreetmap.org/tags/tactile_paving=yes#combinations

**Comment by westnordost** [comment]
I'd also say that actual usage of tactile_paving is as a property of crossings (, bus stops, metro stations, ...), not as a property of (arbitrary) nodes on footways. Besides, you will only actually have a footway crossing a `highway=crossing`, if the sidewalk is mapped separately from the road. Given that this mapping technique is kinda deprecated or at least should only be used when the sidewalk is _really_ separate from the road (some space between footway and curb), only a very small percentage of sidewalks would actually be mapped separately.
