### ISSUE TITLE
Make getting the country for GPS pos more performant

### ISSUE THREAD

**Issue by westnordost** [westnordost/StreetComplete#798]
Getting a country for a given set of GPS coordinates is quite heavy on the CPU because it's a point-in-polygon-check for quite some big polygons.

**Comment by westnordost** [comment]
(Would make it possible to make the country-blacklist/whitelist more precise as well)

**Comment by rugk** [comment]
https://stackoverflow.com/questions/3659809/where-am-i-get-country#19415296

Variant listed there:
* get via SIM (getNetworkCountryIso)
* via IP (as the online service) using an ip database as flagfox

**Comment by westnordost** [comment]
Where a point is, not where you yourself are. Don't worry, I do know exactly what to do.

**Comment by westnordost** [comment]
Success! (AddMaxSpeed is disabled in US, but not in Mexico)

![device-2018-03-18-204524](https://user-images.githubusercontent.com/4661658/37570215-61605ffa-2aed-11e8-951c-bb3904e33413.png)

**Comment by westnordost** [comment]
Finally got this off my todo list.

In the last 1-2 weeks, I worked on this: https://github.com/westnordost/countryboundaries

**Comment by rugk** [comment]
Awesome! 🎉
