### ISSUE TITLE
add missing religion tag to historic=wayside_shrine

### ISSUE THREAD

**Issue by matkoniecz** [westnordost/StreetComplete#799]
### General
Affected key(s) (or tags) to be modified: [religion](https://wiki.openstreetmap.org/wiki/Key:religion)
Question asked: **What is the religion on XY?**

### Checklist
Checklist for quest suggestions (see guidelines):
- [x] 🚧 To be added tag is established and has a useful purpose - used by other editors ( https://josm.openstreetmap.de/changeset/8016/josm ), tag is used ( https://taginfo.openstreetmap.org/tags/historic=wayside_shrine#combinations ), there are at least considerations to use it during map rendering ( https://github.com/gravitystorm/openstreetmap-carto/issues/131 )
- [x] 🤔 Any answer the user can give must have an equivalent tagging (Quest should not reappear to other users when solved by one) - every place of worship can be tagged (or it is invalid and should be deleted)  (note that some may have religion=multifaith)
- [x] 🐿️ Easily answerable by everyone from the outside but a survey is necessary (at least in European countries, may be not enabled everywhere)
- [x] 💤 Not an overwhelming percentage of elements have the same answer (No spam) - historic=wayside_shrine is relatively rare compared to missing surface or building tags
- [x] 🕓 Applies to a reasonable number of elements (Worth the effort) 70% of 45k elements has no tag like this https://taginfo.openstreetmap.org/tags/historic=wayside_shrine#combinations

### Ideas for implementation

reuse #777 

**Element selection:** 
Reuse #777

**Metadata needed:** 
yes it is necessary and I may supply it (for areas that are already mapped in OSM)

**Proposed GUI:** 

Reuse #777, but without allowing to  supply info about denomination (as it is extremely tricky to get this right for some shrines)

**Promises:**

I plan of making quest like this, if idea of quest is accepted I plan on making it good enough for StreetComplete PR.

**Comment by rugk** [comment]
Hmm, good idea, but the difference to https://github.com/westnordost/StreetComplete/issues/777 is extremely low. So I'd think this can be done in one quest. (It's basically just one more item to select and the denomination selection to hide.)

**Comment by matkoniecz** [comment]
It needs to be in separate quests reusing code as here denominations should not be selectable and per country data will be different, as done religions are not making wayside shrines.

**Comment by westnordost** [comment]
Denomination should also not be selectable for other religious places. I already gave the reason for that.

**Comment by matkoniecz** [comment]
> Denomination should also not be selectable for other religious places. I already gave the reason for that.

Are you sure? I looked through #777 again and I see no relevant comments. And at least for PoW I think that making possible to select both only religion (christian) or exact denomination (Roman Catholic, orthodox, Greek Catholic, Polish Catholic) at least on some countries.

**Comment by westnordost** [comment]
Hmm, yes, I am pretty sure. Don't know where it ended up (email response), I can't find it neither.
The reasons were 
- it is easy for a layman to distinguish a mosque from a church and a church from a temple etc. But it's not that easy to distinguish greek catholic from polish catholic etc. because the symbolism is very similar (✝️). Not knowing which denomination something is should not
  - prevent or make them insecure from answering the religion
  - make the UI interaction more cumbersome/slow
- there are hundreds and thousands of christian denominations. I think this kind of complexity would rather fit into a separate quest

**Comment by matkoniecz** [comment]
> distinguish greek catholic from polish catholic etc

At least in Poland any church will have this info posted on board/building plaque.

> would rather fit into a separate quest

Ok, so I will make a separate one.

**Comment by matkoniecz** [comment]
I have a bit trouble with question here.

Current best idea is awful

> What religion is represented at this shrine?

Note that a) shrines commonly have no names b) historic=wayside_shrine is also for places not used fr religious practices (and ones also tagged as place_of_worship are anyway covered by #777)

**Comment by matkoniecz** [comment]
code waits at at https://github.com/matkoniecz/Zazolc/commits/wayside_shrine for handling of #777 as it relies on some code changes introduced by this PR.

Once #777 is processed I will make a PR, but I would appreciate feedback.

Changes are all in https://github.com/matkoniecz/Zazolc/commit/7a36468958d39617a9c157ddbbbb13c3e0cf2071

Country-specific data is directly from OSM, if somebody is aware about some statistics which religion have wayside shrines in specific countries it may be useful.

**Comment by westnordost** [comment]
I know from my travels, that Buddhist and Hindu wayside shrines exist. No idea about the rest.

**Comment by matkoniecz** [comment]
From what I know Islamic shrines are not existing or highly unusual.

I was unsure whatever it should be available as an option but in the end I kept it.
