### ISSUE TITLE
add add:street field for the quest for addr:housenumber

### ISSUE THREAD

**Issue by GeorgV** [westnordost/StreetComplete#800]
You ask for adding a house number also for buildings without any street information. But the minimum keys for an valid address is addr:street and addr:housenumber (in most countries of the world)! 

There are different possibilities:
a) you add a field for addr:street (maybe with a selection list of the street names in the surrounding area )
b) you add a new quest for the street name, if a building has only a house number
c) you change the quest query for building with addr:street and no addr:housenumber

**Comment by matkoniecz** [comment]
#213 covers this

**Comment by westnordost** [comment]
b) it is. See #213
