### ISSUE TITLE
consider renaming ic_religion_caodaist.xml to ic_religion_caodaism.xml

### ISSUE THREAD

**Issue by matkoniecz** [westnordost/StreetComplete#801]
caodaism seems to be value used both as name for religion and value of religion tag

I can make a PR.

**Comment by westnordost** [comment]
No thanks. Let's stay consistent. The value of the `religion` tag is obviously not the name of the religion (not christianity, not islam, etc..) but the **adjective**:

- A christian church
- A muslim mosque
- A hindu temple
- A buddhist pagoda
- A chinese (folk) temple
- A caodaist church
- ...
