### ISSUE TITLE
OAuth Fails

### ISSUE THREAD

**Issue by ralph-schleicher** [westnordost/StreetComplete#804]
Installed version 3.5 yesterday on a LG G4 running LineageOS 7.1.2.

OAuth behaviour is similar to #731.
The error message is as follows:

```
Webseite nicht verfügbar

Die Website unter
https://www.openstreetmap.org/oauth/authorize
konnte nicht geladen, weil:

net::ERR_UNKNOWN_URL_SCHEME
```

There are multiple StreetComplete items listed on the OAuth details page of my OSM account. Seems as if a new one is generated whenever StreetComplete tries to authenticate.

**Comment by ENT8R** [comment]
Are you using the default browser of LineageOS (Gello) and did you tried to autheticate with other browsers (e.g. Firefox or Chrome)?

**Comment by ralph-schleicher** [comment]
Yes its Jelly. Haven't tried another browser.

I just searched the syslog for StreetComplete/OAuth related messages and the only thing I could find is this:

```
01-27 10:39:00.667 I/chromium(31030): ", source: https://www.openstreetmap.org/oauth/authorize?oauth_token=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx (0)
01-27 10:39:00.761 E/SuggestionProvider(31030): Problem getting search suggestions
01-27 10:39:00.761 E/SuggestionProvider(31030): java.io.FileNotFoundException: https://www.google.com/complete/search?client=android&oe=utf8&ie=utf8&hl=de&q=streetcomplete%3A%2F%2Foauth%3Foauth_token%3Dxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx%26oauth_verifier%3Dyyyyyyyyyyyyyyyyyyyy
01-27 10:39:00.761 E/SuggestionProvider(31030): 	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getInputStream(HttpURLConnectionImpl.java:250)
01-27 10:39:00.761 E/SuggestionProvider(31030): 	at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getInputStream(DelegatingHttpsURLConnection.java:210)
01-27 10:39:00.761 E/SuggestionProvider(31030): 	at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java)
01-27 10:39:00.761 E/SuggestionProvider(31030): 	at org.lineageos.jelly.suggestions.SuggestionProvider.downloadSuggestionsForQuery(SuggestionProvider.java:150)
01-27 10:39:00.761 E/SuggestionProvider(31030): 	at org.lineageos.jelly.suggestions.SuggestionProvider.fetchResults(SuggestionProvider.java:116)
01-27 10:39:00.761 E/SuggestionProvider(31030): 	at org.lineageos.jelly.suggestions.SuggestionsAdapter$ItemFilter.performFiltering(SuggestionsAdapter.java:111)
01-27 10:39:00.761 E/SuggestionProvider(31030): 	at android.widget.Filter$RequestHandler.handleMessage(Filter.java:234)
01-27 10:39:00.761 E/SuggestionProvider(31030): 	at android.os.Handler.dispatchMessage(Handler.java:102)
01-27 10:39:00.761 E/SuggestionProvider(31030): 	at android.os.Looper.loop(Looper.java:154)
01-27 10:39:00.761 E/SuggestionProvider(31030): 	at android.os.HandlerThread.run(HandlerThread.java:61)
```

**Comment by ENT8R** [comment]
Mmhh... Okay, It seems like Jelly can't handle the OAuth callback URL for StreetComplete... Instead it tries to search for a result using google which results in a 404 error... I would consider this as a problem of LineageOS's Jelly browser, but could you please download Firefox and then tell me the result to make sure that this issue is not related to StreetComplete?

**Comment by westnordost** [comment]
You need to use another browser for that. See See https://github.com/westnordost/StreetComplete/issues/413#issuecomment-328339064 for more details.

I wonder if it would be possible to report this problem to the Jelly developers somewhere. I did not find any repository with a bugtracker.

**Comment by ralph-schleicher** [comment]
I installed Firefox Klar and now it works. Thanks for your help.

Since this is not the first issue related to StreetComplete's OAuth mechanism it might be a good idea to document this problem more clearly so that new users don't quit immediately.

**Comment by ENT8R** [comment]
I finally found their bugtracker and opened a new issue for that!
It can be found at https://jira.lineageos.org/browse/BUGBASH-1393
BTW: their bug reporting system is IMO completely weird... You can only report general bugs/issues from Midnight UTC on Friday through Midnight UTC on Monday... Why???

**Comment by quite** [comment]
Btw, Lineageos's Jira now redirects here: https://gitlab.com/LineageOS/issues and I can't find that bug there in the Android project.

**Comment by westnordost** [comment]
I will change the authorization (back) to using an internal webview to avoid being dependent on buggy browsers in the future.

**Comment by Quix0r** [comment]
This change doesn't work in latest version, sorry to say: "Unable to reach the authentication server" it says. Should I open another issue ticket?
