### ISSUE TITLE
Note left by anonymous user

### ISSUE THREAD

**Issue by ENT8R** [westnordost/StreetComplete#805]
I just found this note:
https://www.openstreetmap.org/note/1279061
It was created using StreetComplete by an **anonymous** user. I thought that every user who uses SC has to authenticate with his OSM account to leave notes or upload changes in general... Is this an issue or can notes be left without authentication?
BTW: This is the only note which was created by an anonymous user that I found, so this case seems to be extremely rare...

**Comment by westnordost** [comment]
It must be a really old version because the note does not state the version. I don't think it is possible with a current version. If it is, you can reopen this bug.

**Comment by westnordost** [comment]
Must be version 1.3 or below:
https://github.com/westnordost/StreetComplete/releases/tag/v1.4

**Comment by ENT8R** [comment]
Ok thank you!
