### ISSUE TITLE
public_transport=platform is not only for bus stops

### ISSUE THREAD

**Issue by matkoniecz** [westnordost/StreetComplete#806]
https://wiki.openstreetmap.org/wiki/Tag:public%20transport=platform?uselang=en-GB

> Use public_transport=platform to identify the places where passengers wait for public transport of any type, including boarding facilities at airports, bus stations, ports, railway stations, as well as for ski lifts and at roadside bus stops, taxi ranks.

Currently for example tram stops result in confusing quests (tram stop is described as a bus stop) and confusing edit descriptions.

Real example:   https://github.com/westnordost/StreetComplete/blob/master/app/src/main/java/de/westnordost/streetcomplete/quests/bus_stop_shelter/AddBusStopShelter.java 
for https://www.openstreetmap.org/node/1701722936/history#map=19/51.08436/17.02529

**Comment by matkoniecz** [comment]
I have no good idea for a better text or generic icon that would cover this hopelessly broad tag value.

**Comment by westnordost** [comment]
`bus=yes` should be set.

**Comment by rugk** [comment]
"bus/tram stop"
or
"stop of this means of transport"
or
"stop of this vehicle"

**Comment by matkoniecz** [comment]
Fixed (btw, adding fixes #number in commit describtion autocloses issues).
