### ISSUE TITLE
New Quest: What type of service road is this?

### ISSUE THREAD

**Issue by dbdean** [westnordost/StreetComplete#808]
### General
Affected key(s) (or tags) to be modified: [service=*](https://wiki.openstreetmap.org/wiki/Key:service) on highway=service
Question asked: **What type of service road is this?**

### Checklist
Checklist for quest suggestions (see guidelines):
- [x] 🚧 To be added tag is established and has a useful purpose
- [x] 🤔 Any answer the user can give must have an equivalent tagging (Quest should not reappear to other users when solved by one)
- [x] 🐿️ Easily answerable by everyone from the outside but a survey is necessary 
- [x] 💤 Not an overwhelming percentage of elements have the same answer (No spam)
- [x] 🕓 Applies to a reasonable number of elements (Worth the effort)

It would be useful if we could indicate if a highway=service is a driveway, a parking_isle, an alley or a drive_thru, or something else (using a note). This would be particularly useful as the main map renders different service roads differently, so having them tagged correctly makes the map work better, and would surely be useful for routing too.

**Comment by matkoniecz** [comment]
> Any answer the user can give must have an equivalent tagging (Quest should not reappear to other users when solved by one)

It is not true, as there are service road where no service tag may be added.

**Comment by westnordost** [comment]
What kind of service roads would that be?

**Comment by matkoniecz** [comment]
For example main service road through parking - according to https://wiki.openstreetmap.org/wiki/Tag:amenity%3Dparking#Related_Features it is typical tagging

**Comment by matkoniecz** [comment]
@dbdean - is there any proper service value for main service road through a parking? AFAIK current practice ( https://wiki.openstreetmap.org/wiki/Tag:amenity%3Dparking#Related_Features ) is to use highway=service without any service tag.

**Comment by dbdean** [comment]
Damn. I was worried something like that would pop up. While I might be able to come up with some suggestions, it does seem that the current practice is to not tag any sort of service= on the main roads through parking, so this Quest is not solvable without some sort of meta-tagging (noservice=yes, or streetcomplete:service=no, etc.) which we obviously want to avoid.

**Comment by dbdean** [comment]
service=parking is used around 10k times already, and from looking at a few, but it isn't documented on the wiki: https://taginfo.openstreetmap.org/tags/service=parking#map.

I think I might put a proposal on the tagging list to see if people can agree to make this somewhat official.

**Comment by dbdean** [comment]
I have put a proposal page up at https://wiki.openstreetmap.org/wiki/Proposed_features/service%3Dparking, and confirmed that tagging the main roads of parking lots with highway=service is definitely widely used. I have also send an email to the tagging list, but it is currently awaiting moderator approval. I'll let you know how it goes.

**Comment by westnordost** [comment]
To be honest, I think service roads within a parking lot are certainly not the only kind of service road whose specific subtag cannot really be determined (for the lack of subtags). I.e. take roads in military bases or on other large complexes like hospitals, civil protection, etc., roads in and around mines, wastewater plants, harbors and other industrial complexes, etc.
A quest like this, however, would require everything to be taggable, thus, everything to be defined. This is not the case. Maybe one day, but at the moment, not really.

But by the way, if you know how to write proposals and such, perhaps you could write a proposal to [easily tag the absence of posted speed limits](https://github.com/westnordost/StreetComplete/issues/813#issuecomment-362349606)? ;-)

**Comment by dbdean** [comment]
I'm getting back into this quest, starting with a question on the tagging mailing list: https://lists.openstreetmap.org/pipermail/tagging/2020-August/054470.html

**Comment by mnalis** [comment]
(also related discussion at: https://community.openstreetmap.org/t/proposed-bulk-removal-of-service-driveway2/100549/37)
