### ISSUE TITLE
Update fails to parse on fairphone2

### ISSUE THREAD

**Issue by KaiMartin** [westnordost/StreetComplete#809]
I tried to update the streetcomplete app on my fairphone2. Download seemed to be fine. Unfortunately, it failed immediately at the upgrade stage. The reason given is:
  "Parse error -- There was a problem while parsing the package"

Some details of the affected system:
  * currently installed version of streetcomplete: Version 3.4 (added on 09/01/2018)
    This version installed fine and runs smoothly.
  * repository used: fdroid 1.0.2
  * OS version: fairphone open 18.01.1
  * The google framework suite (GSF) and other google apps are not installed on this phone 

hope, this helps to fix the issue,

---<)kaimartin(>---

**Comment by ENT8R** [comment]
Could you please remove the issue template and describe a little more detailed what happens?

**Comment by KaiMartin** [comment]
Sorry, I started the report on my fairphone and accidentally clicked the send button. Now, that I am on my desktop, I was able to write a proper report.

---<)kaimartin(>---

**Comment by westnordost** [comment]
I don't really see what a problem with the packaging manager has to do with this app.

You can try to download the APK directly from github https://github.com/westnordost/StreetComplete/releases/tag/v3.5 and see if it works for you then.

**Comment by westnordost** [comment]
> "Parse error -- There was a problem while parsing the package"

The package is created by the F-Droid build server, not by me, so, this is the wrong bugtracker.

**Comment by KaiMartin** [comment]
Thanks. The apk directly from github works as expected . I will contact the f-droid bugtrcker. 

---<)kaimartin(>---

**Comment by rugk** [comment]
Any news?

BTW pure guessing, maybe it is something like https://github.com/cemrich/zapp/issues/103.

**Comment by matkoniecz** [comment]
See https://gitlab.com/fdroid/fdroidclient/issues/1310 (reported month ago, ignored by whoever maintains F-droid).

But there is a workaround:

> Disabling "Privileged Extension" in the F-Droid settings allowed me to re-install StreetComplete and to update PassAndroid using the respective buttons in F-Droid. This was while "Force old index format" was still enabled, but I don't know whether that matters.
