### ISSUE TITLE
detect source:maxspeed=** as missing maxspeed

### ISSUE THREAD

**Issue by hakuchi** [westnordost/StreetComplete#810]
For example in Frace, are set `source:maxspeed=***`(99% are from this app) but there is missing the `maxspeed=**`.
StreetComplete have set `source:maxspeed=FR:urban` but no `maxspeed=50`.

Here a little list with ways what have `source:maxspeed` without any `maxspeed` + example street:
In France are over 2700      => https://www.openstreetmap.org/way/166816674      
In Germany are over 3200 => https://www.openstreetmap.org/way/106513052
In Austria are over 300 => https://www.openstreetmap.org/way/88454666
In Italy are over 1000 => https://www.openstreetmap.org/way/23035827
In Spain are over 500 => https://www.openstreetmap.org/way/94561164

Also there are `maxspeed:forward` without `maxspeed:backward` an and vice versa.

StreetComplete should be able to detect all of these errors!

**Comment by matkoniecz** [comment]
Sounds like duplicate of #457

**Comment by hakuchi** [comment]
but if I zoom on the way https://www.openstreetmap.org/way/166816674 StreetComplete no giving me any maxspeed to fix

**Comment by westnordost** [comment]
You would like to specify `maxspeed`, when only `maxspeed:type` / `source:maxspeed` is defined?

**Comment by matkoniecz** [comment]
That would be unfortunately duplicate if rejected 'Answers to speed limit quests create "source:maxspeed" without "maxspeed"' #457
