### ISSUE TITLE
Wrong default language for "name"

### ISSUE THREAD

**Issue by jmontane** [westnordost/StreetComplete#811]
Hi,

I've phone set to Catalan language, and I map on Catalonia, where Catalan is default language for street plates, but StreetComplete ask me to put "name:es" as default. Of course, I can add "name:ca" manually, but usually only "name" and "name:ca" are needed to be filled here, so current behaviour is a pain.

How is default "name" language computed? It can be changed by user? Thanks.

**Comment by westnordost** [comment]
> How is default "name" language computed?

The default name language is computed by
1. determining in which country the quest is, using a [geojson file](https://github.com/westnordost/StreetComplete/blob/master/app/src/main/assets/countryBoundaries.json) that defines the borders of the world
2. looking at [officialLanguages.yml](https://github.com/westnordost/StreetComplete/blob/master/res/country_metadata/officialLanguages.yml)
3. then looking at [additionalStreetsignLanguages.yml](https://github.com/westnordost/StreetComplete/blob/master/res/country_metadata/additionalStreetsignLanguages.yml) for complementing the list

> It can be changed by user?

No, it can't.

---

To enable Catalan as default language in certain regions of Spain, the countryBoundaries would need to be extended. The file is a copy from JOSM (boundaries.osm) and I am somewhat reluctant to add even more sub-country borders, it is now already almost 2MB. If I do it for Spain, it is like opening a can of worms. There are many more countries in the world, where in different parts of the country, different languages are spoken (starting with Belgium, Switzerland, and then countless in Africa and Asia).

**Comment by westnordost** [comment]
So, I will not do it, for now.

**Comment by jmontane** [comment]
Thanks for quick reply.

I understand managing different language/country case arround Worls is a big can of worms. For such reason I suggest a custom user setting for areas where primary country language differs from primary area language.

**Comment by westnordost** [comment]
FYI I am currently working on performance improvements on using [countryBoundaries.json](https://github.com/westnordost/StreetComplete/blob/master/app/src/main/assets/countryBoundaries.json), so perhaps after that I can think about getting more detail into that file.
