### ISSUE TITLE
python generateCountryMetadata.py without any changes to metadata changes order

### ISSUE THREAD

**Issue by matkoniecz** [westnordost/StreetComplete#815]
to reproduce:

```
git checkout master
cd app
python3 generateCountryMetadata.py
git diff
```
for me it caused changes to appear, with diff available at https://github.com/westnordost/StreetComplete/commit/dbdf1eedc601389e9f6c95b275d20141ad8252e6

It would be preferable to keep order consistent across python/library/OS versions, otherwise PRs changing metadata are doomed to have very messy diffs

**Comment by westnordost** [comment]
Weird, how can that be?

**Comment by matkoniecz** [comment]
Probably some function used here is allowed to return values in arbitrary order and values differ not between subsequent find but between OS/filesystems/versions/etc.
