### ISSUE TITLE
Housenumber quest doesn't show up if only building=yes is tagged

### ISSUE THREAD

**Issue by tobylorenz** [westnordost/StreetComplete#821]
### General
Affected key(s) (or tags) to be modified: [addr](https://wiki.openstreetmap.org/wiki/Key:)
Question asked: **Why isn't the housenumber asked, if there is just building=yes is there?**

### Checklist
Checklist for quest suggestions (see guidelines):
- [x] 🚧 To be added tag is established and has a useful purpose
- [x] 🤔 Any answer the user can give must have an equivalent tagging (Quest should not reappear to other users when solved by one)
- [x] 🐿️ Easily answerable by everyone from the outside but a survey is necessary 
- [x] 💤 Not an overwhelming percentage of elements have the same answer (No spam)
- [x] 🕓 Applies to a reasonable number of elements (Worth the effort)

### Ideas for implementation
I think the filter expression in the housenumber quest is incomplete. I have many houses in my neighborhood, which are tagged only with building=yes. For these houses the quests doesn't show up to set a housenumber. So maybe it's sufficient to just add building=yes to the filter list (HOUSES_WITHOUT_HOUSENUMBERS).

**Element selection:**
The filters should not just include building=residential, but also building=yes.

**Metadata needed:** 
It might be that building=yes is not appropriate, but often it is the initial value, if the buildings are drawn from satellite maps, but no local survey took place.

**Proposed GUI:** 
The existing GUI is perfect. It just should quest, also in case where only building=yes is tagged.

**Comment by matkoniecz** [comment]
Duplicate of #352

We do not want this quest for garages, sheds etc.

**Comment by ENT8R** [comment]
This will be fixed by #774

**Comment by rugk** [comment]
Also BTW, the issue template is meant for proposing _new quests_, not for asking questions about existing ones.

**Comment by tobylorenz** [comment]
@matkoniecz Yes, right. building=yes would really flood the streets with quests ;-)

@ENT8R That's indeed the best approach for this. As soon as the building type is properly set, the quest for the housenumber will appear automatically.

@rugk Indeed it's written in the template "If you are not suggesting a new quest, ignore this issue template. Otherwise we kindly ask you to fill it out."... Just wanted to do it properly, but read over this important exception ;-)

So, I propose to close this issue then. Nothing remains to be done in this context. Thank you all for the quick reply. I'll happily continue to answer quests then ;-)
