### ISSUE TITLE
Filling out multiple quests with the same answers quickly

### ISSUE THREAD

**Issue by smichel17** [westnordost/StreetComplete#826]
Some areas have many roads next to each other that share many characteristics. The most common example I can think of is marking the surface of a neighborhood's roads that are all asphalt. It would be really nice if there were some way for me to answer, "This road is exactly the same as the last 3 roads I tagged" without having to click through the same dialogs over and over.

I seldom go on a trip for the explicit purpose of tagging with StreetComplete. Rather, I do it when I have a minute of down time while I'm out for some other reason. Speed of entry has a dramatic impact on the number of quests I am able **or willing** to complete before I get bored/frustrated and move on to the next thing.

I am not quite sure how a UI for this should be. I could imagine two ways:

1. A single action to answer multiple quests that share an answer.
2. A quick way to answer "same as last" or "same as neighboring street".
    - Could be for a single quest or for multiple characteristics.

**Comment by matkoniecz** [comment]
> A quick way to answer "same as last"

I think it was proposed already but quick search failed to find a ticket

> A single action to answer multiple quests that share an answer.

duplicate of #274, #264, #73, #149

**Comment by smichel17** [comment]
I should have searched first. I'll close this in favor of #76.
