### ISSUE TITLE
do not show wheelchair quest (and other indoor) for objects that are currently closed, based on opening_hours tag

### ISSUE THREAD

**Issue by matkoniecz** [westnordost/StreetComplete#827]
It would require pulling in library parsing opening_hours but it would allow to avoid showing quests that are unsolvable at given time

**Comment by rugk** [comment]
Oh well… but these are already disabled? And not all indoor quests are really only solvable when getting into the amenity, i.e. restaurants can e.g. advertise (permanently) that they offer vegetarian food or so…

**Comment by westnordost** [comment]
Mh, this would get to complex, in my opinion.
