### ISSUE TITLE
3d view stuck, only blue circle turns around

### ISSUE THREAD

**Issue by rugk** [westnordost/StreetComplete#828]
I am testing out the latest master (beta) version a bit and I see some differences compared to the current stable version in the **3d view**:

* **Good:** It does not jiggle/dangle so much, anymore.
* **Bad:** Sometimes it is just stuck, i.e. when I turn around I see the blue circle moves correctly, but the map does not turn in order to adjust the direction

STR for the bad thing:
1. Enable 3d view and GPS locking.
2. Turn around heavily.
3. At some point your turns are only "recognized" by the blue circle and not the map. However, you can verify your still in the locked mode as you cannot manually turn the map.
4. In order to make it work again, I had to unlock it multiple times/move/turn it manually, before begginning with 1. again.

So maybe the mechnism to stabilize the view is a bit too strong. Or maybe that's not the issue as it actually seems to recognize it (the blue circle always points into the correct direction.)

Same device, Android 7/LineageOS

**Comment by westnordost** [comment]
> Good: It does not jiggle/dangle so much, anymore.

I did not change anything there.

Perhaps you could make a short screenrecording, showcasing this?
