### ISSUE TITLE
Quest solvings should be written to Logcat

### ISSUE THREAD

**Issue by Map3428** [westnordost/StreetComplete#829]
I've created my first pull request for a new quest and I've noticed some things that aren't so nice, for example, it should be the case that replies to quests are written in Logcat so that you can test the change without giving the test app access and without uploading the change to OSM.

**Comment by ENT8R** [comment]
You can always debug quests/code in general by adding something like `Log.d("TestQuest", the answer variable goes here)` by yourself. There shouldn't be an entry in the logcat for every solved quest in production... For debugging it's all fine, you can e.g. simply output the answer by the code from above in the `applyAnswerTo()` function.
e.g. after this line: https://github.com/westnordost/StreetComplete/blob/5e161a62287aae6e2cadb9bf06f307888225273e/app/src/main/java/de/westnordost/streetcomplete/quests/crossing_type/AddCrossingType.java#L29
you can simply type `Log.d("AddCrossingType", values.get(0))` and you will see your answer in the console.

**Comment by Map3428** [comment]
Thanks for the tip!

**Comment by westnordost** [comment]
For testing, I usually do not authorize myself, so the app cannot upload the changes and set a breakpoint in the `applyAnswerTo` method. Then, I undo my quest answer (to test other answer paths).

I guess a debug or verbose log that logs what OSM tags will be applied by the answer would be okay, this is the kind of thing that one would expect from a debug/verbose log, after all.

> P.S.: And I wouldn't say that there are "some things that aren't so nice"... The code quality of StreetComplete is IMO awesome!

Thank you, this is a compliment I hold in high regard. :-)

**Comment by rugk** [comment]
I also see really much other (useless) output in logcat from StreetComplete (from mapzen and also things like "point is too far away" and such stuff), so i think adding such a useful output may not be bad. Not everyone thinks of breakpoints directly… 😉

**Comment by matkoniecz** [comment]
Good idea. I implemented it in https://github.com/matkoniecz/Zazolc/commit/b0e744cc055c402b8351e5c24af7f1bfec7aac8a - no PR for now as it relies on my other PR that I will submit soon.

**Comment by rugk** [comment]
>  no PR for now as it relies on my other PR 

Oh, well… Next time you know you'd better of to branch the master and separate that change, yeah· (you can still merge branches into your's as wanted)
You could also cherry-pick commits… but well… let's don't make such a fuzz for such a small feature. :smiley:

**Comment by matkoniecz** [comment]
It would not be a good idea as I am adding new function that needs logging - cherry picking is easy, but I wanted to avoid merge conflicts that would add work for maintainer.
