### ISSUE TITLE
Add advanced mode for quests

### ISSUE THREAD

**Issue by HolgerJeromin** [westnordost/StreetComplete#831]
It would be nice if we can have advanced (mass/spam/flood) mode for quests which would drop some filter in the queries. for example:
* Lit for all highways #427
* roof shape quests for all roof:level #277

I am not shocked when the screen is flooded with markers. Instead i am happy to answer a quest without moving a lot. :)

**Comment by matkoniecz** [comment]
If it is accepted I may implement this setting (note that it would require this quests to have additional function returning expanded quest, without some limitations).

**Comment by rugk** [comment]
Hmm, changing the way quests apply by using a setting is a bit strange, IMHO.

At least don't call it "expert mode", as this is what we planned in https://github.com/westnordost/StreetComplete/issues/471 for a different feature. So maybe name it "Show quests for more items…", if this feature is really wanted.

**Comment by matkoniecz** [comment]
@westnordost Would you accept PRs adding such flood mode?

**Comment by westnordost** [comment]
Hmm, at the moment not.

**Comment by matkoniecz** [comment]
So you probably should close this issue (at least for me open issue on bug tracker indicates that owner of project would want given issue implemented).
