### ISSUE TITLE
Blue circle looks strange in 3d view when zooming in

### ISSUE THREAD

**Issue by rugk** [westnordost/StreetComplete#833]
In a recent master version, this is what I saw when using the 3d view and zooming in a bit:

![streetcompletebluecircle](https://user-images.githubusercontent.com/11966684/35778085-6048f500-09b9-11e8-8081-2f9083fc2f7d.png)

So is this strange view of the (not so round) circle expected? In the current stable version, it does not look like that, AFAIK.

**Comment by matkoniecz** [comment]
I am not sure why circle displayed in a perspective is weird in a perspective mode.

**Comment by westnordost** [comment]
This is a bug in the new tangram-es 0.9.0, not in StreetComplete, I believe this is the same bug as already reported here:
https://github.com/tangrams/tangram-es/issues/1764
