### ISSUE TITLE
Add editorconfig file to enforce indentation/line endings/… style

### ISSUE THREAD

**Issue by rugk** [westnordost/StreetComplete#834]
Have a look at http://editorconfig.org/. It is a simple file, which allows you to define whether you want to use tabs or spaces, and other things in your files, so they stay consistent even when multiple contributors edit/add files.
Also the line endings can get confused when editing on Windows and Linux and so on…

[Multiple plugins](http://editorconfig.org/#download) or even built-in versions for that thing exist. According to the website support is built-in into IntelliJ, so in Android Studio it may also work (not tested, I just hope so).

**Comment by ENT8R** [comment]
Note that there is already a [code_scheme.xml](https://github.com/westnordost/StreetComplete/blob/master/code_scheme.xml)... But this is maybe not imported by all contributors...

**Comment by rugk** [comment]
From having a quick look at this, it looks as if that covers something different. code_scheme.xml only seems to be about the coding style, while editorconfig is about very basic things (which can easily go unnoticed in code reviews, but "destroy" files) like line endings, spaces and so on.

Also don't know which IDEs support  code_scheme.xml and what action you need when using it. As for editorconfig that works automatically, when your IDE supports it.

**Comment by matkoniecz** [comment]
> not tested, I just hope so

Can you test it?

**Comment by rugk** [comment]
Yes, it works.

**Comment by westnordost** [comment]
Ok, you are invited to create a PR for that.

**Comment by rugk** [comment]
But I can't do it. You have to tell me at least how you want it. Which file type should have what? Spaces or tabs?

Also please don't close issues when you ask for PRs. Closing means it is either finished or rejected. Tag it with "help wanted" and leave it open.

**Comment by westnordost** [comment]
Tabs
