### ISSUE TITLE
Maps no longer updating on new vector tile server, out-of-date with quests

### ISSUE THREAD

**Issue by dbdean** [westnordost/StreetComplete#835]
Firstly, thanks to @Akasch for his great work in setting up a new vector tile server for rescue StreetComplete from the demise of Mapzen.

I am opening this issue to mention that as the server is not updating at the moment (and I'm sure it is probably not trivial to do so easily or cheaply), and therefore the map is no longer up-to-date with the quests that are appearing, as in this screenshot:

![screenshot_20180205-104217 1](https://user-images.githubusercontent.com/12725310/35784354-257c0062-0a62-11e8-9b2e-e48539042930.png)

Is it possible to add an alternative background map to StreetComplete that pulls direct from osm.org rendered tiles, or perhaps satellite imagery, like https://github.com/ENT8R/streetcomplete-mapstyle/blob/master/streetcomplete-satellite-style.yaml?

Alternatively, given that StreetComplete is about editing the map, is there anyway on quest download, to download the OSM data directly using the API and render that locally using Tangram?

**Comment by ENT8R** [comment]
The quest download has nothing to do with the map... All quests are downloaded via the Overpass API which is independent of Mapzen or Tangram...

**Comment by matkoniecz** [comment]
> Isn't that enough?

No. Context is important.

**Comment by dbdean** [comment]
It's hard to work out which building is being referred to without the surrounding buildings, and new roads, etc would be missing to. I think it's important we have an up to date background layer.

**Comment by dbdean** [comment]
It's hard to work out which building is being referred to without the surrounding buildings, and new roads, etc would be missing to. I think it's important we have an up to date background layer.

**Comment by Akasch** [comment]
The Updates of the map is in work. I think it will take one or two weeks until it is fully working.

**Comment by matkoniecz** [comment]
Thanks! Can you consider making notes how one may setup map server?

So in case you will be unable to continue somebody else may setup new map server without figuring out everything from scratch?

Maybe such notes may be committed to this repo, after all as Mapzen died such map server is part of StreetComplete project.

**Comment by westnordost** [comment]
Also, unfortunately (for whom a current background layer is important), probably StreetComplete will use a tileserver soon which will update even less frequently.

Basically, a proper and up-to-date tileserver requires a dedicated server whose costs of about 200$ per month need to be raised somehow while the other solution ([nextzen / Tapalcatl](https://developers.nextzen.org/)) uses old/very infrequently updated tiles but costs about 10$ per month, an amount I can easily pay myself without looking for sponsors.

Of course it may be of benefit to have a proper vector tileserver around for use in OpenStreetMap related projects and probably it will be not a big problem to find sponsors, but that is not something that I want to concern myself with while I have more than enough work with StreetComplete already and the other solution is so conveniently close.

**Comment by rugk** [comment]
BTW [people repeatedly asked for ways to donate](https://github.com/westnordost/StreetComplete/issues/184) [to the project](https://github.com/westnordost/StreetComplete/issues/700#issuecomment-346095625). So i think you would get some support to keep a server running…

**Comment by rugk** [comment]
…or… with lower fees, easy payment and more FLOSS-like LiberaPay, but yeah… also proposed that.

**Comment by ENT8R** [comment]
> Can we add a background layer option to the app, with Aerial Imagery being one of them? And maybe the current main OSM map?

This is tracked with #673.

**Comment by westnordost** [comment]
Anyway, whether or not a vector tile server with current tiles is available or not, is out of my hands. If a server like this would be available, that would be cool of course, but trying to maintain the costs for a server through variable donations to this project is a too shaky foundation for my taste. And TBH, I don't believe I would receive a steady $200 donations for this project in any case.

**Comment by Akasch** [comment]
The Update is working now. It does roughly 12 hours of updates in 4 hours, so it will need some time to catch on. The State of the map at the moment is from 15.01. at 23:00.

**Comment by dbdean** [comment]
@Akasch, is your vector server still updating? The map in StreetComplete seems to have gotten stuck for me, and is still at least a few months old, I think.
