### ISSUE TITLE
Quest suggestion: Is this street lit?

### ISSUE THREAD

**Issue by lightonflux** [westnordost/StreetComplete#84]
[key:lit](https://wiki.openstreetmap.org/wiki/Key:lit) is a mostly used with `highway`. There are different tags for it but these three are best for a quest:

It is probably best to narrow this quest down to paved roads and bigger streets. So users don't get bored by hundreds of pathways without lighting.  

### Answers

 * lit_by_gaslight=yes: For streets lit by gas lighting
 * llit=yes: At night (unknown time schedule or daylight detection)
 * lit=no

The question is strait forward and the options can be easily interpreted in a friendly UI.

### UI Mockup
![sc](https://cloud.githubusercontent.com/assets/1377943/24594986/9b2a9468-1832-11e7-97a1-b76bb75f4351.jpg)

(excuse the particles in my scanner)

### Extras questions for tunnels

And maybe these in context of tunnels:

 * lit=automatic: When someone enters the way the lights are turned on.
 * lit=24/7

**Comment by PanderMusubi** [comment]
Automatic and 24/7 might also apply to non-tunnel situations. So lit results in a 1-out-of-4 selection (no default):
* `no`
* `yes` (time schedule or daylight detection)
* `automatic` (motion detection)
* `24/7` (always on)

If lit is not `no`, you can choose from 1-out-of-2-selection (or boolean called `gas`):
* electric (default)
* gas

**Comment by westnordost** [comment]
I'd stuff everything except yes and no into "Other answers...", don't want to clutter up the interface for the standard case.

**Comment by CloCkWeRX** [comment]
Visualisation of it: http://product.itoworld.com/map/69

(I'm not sure, but this might be the only consumer of that data)

**Comment by lightonflux** [comment]
> I'm not sure, but this might be the only consumer of that data

Osmand can display it if you enable it in "details".

![lights](https://cloud.githubusercontent.com/assets/1377943/24739451/612c24a4-1a9c-11e7-95ae-cbce6136f7eb.gif)

**Comment by HolgerJeromin** [comment]
This is nice, but please also for footways. At least if they are longer than a few meters (which could be connecting footways from a residential to a house). 
It is imo much more interesting if a footway is lit in a park than a secondary or residential street.

**Comment by matkoniecz** [comment]
Also cycleways.

**Comment by matkoniecz** [comment]
I think that it should be spli into two separate quests (reuse of icon is possible, so difference would not be obvious to user) as asked questions would be different.

both quests would ask for objects that fulfill all of following criteria:

- highway=motorway|motorway_link|trunk|trunk_link|primary|primary_link|secondary|secondary_link|tertiary|tertiary_link|unclassified|residential|service|living_street|pedestrian|footway|cycleway|path
- lit key is not present on the object
- object is not a node or relation
- access key is not present or access=yes or access=permissive

general one would skip objects with tunnel key, except tunnel=no

tunnel specific would process only objects with tunnel=yes, tunnel=building_passage, tunnel=avalanche_protector

Additional idea: maybe show general lit only during night (that is possible to compute from GPS position and time).

---

I am interested in this issue - I am not promising anything but PR is possible.

**Comment by lightonflux** [comment]
Not sure if this should be the same quest but a way with `amenity=parking` could be lit as well. Way because then it is likely to be a bigger parking space. But i haven't seen a lit tagged in my area. But they [exist](https://taginfo.openstreetmap.org/tags/amenity=parking#combinations) 21 515 with `lit=*` and 16 870 with yes. Not much but a good idea to expand on.

**Comment by matkoniecz** [comment]
Maybe third group, for user the same as general one for areas

- relation with type=multipolygon
- (highway=pedestrian|service) or amenity=parking
- lit key is not present on the object
- access key is not present or access=yes or access=permissive or access = customers

**Comment by HolgerJeromin** [comment]
> Additional idea: maybe show general lit only during night (that is possible to compute from GPS position and time).

I am against this as most of the time you see the street lamps even when it is not dark. You do not know if they are working or operating but still this would reduce impact.

**Comment by PanderMusubi** [comment]
That could be an option for e.g. OsmAnd, not OSM data

**Comment by matkoniecz** [comment]
> I am against this as most of the time you see the street lamps even when it is not dark. You do not know if they are working or operating but still this would reduce impact.

Maybe it is a regional problem but it is quite hard to decide whatever something is lit or not, based solely on presence of streetlamps. For example many footways are not lit despite lamps on the street (only part of road used by cars is lit).

**Comment by HolgerJeromin** [comment]
There are places where it is obvious which part is lit. [Cycleway on the left is lit, the car road is not](https://www.mapillary.com/app/?lat=51.873155&lng=8.535632999999962&z=17&pKey=NVyG70CB8T1CYPXPf5EdLg&focus=photo).

**Comment by matkoniecz** [comment]
Yes, but app is unable to guess it. I think that it is better to present questions that almost certainly can be easily answered.

**Comment by lightonflux** [comment]
@HolgerJeromin can you check if that example has a separate walk/bicycle way in OSM? If they are two separate ways then it won't be an issue as @matkoniecz said (at least in this configuration). [This is more problematic for users](https://www.google.de/maps/@51.4619012,7.014454,3a,75y,106.09h,82.27t/data=!3m6!1e1!3m4!1soASlJMBVKclw_z_RFrNJuQ!2e0!7i13312!8i6656!6m1!1e1?hl=de), is the walkway lit? The road is. Although the situation looks much clearer in [OSM data](https://www.openstreetmap.org/#map=19/51.4619012/7.014454). 

I say we should start simple and then review the OSM data after a month or two. We can still add the time feature later. Or the layout of the answer could be imporved.

**Comment by althio** [comment]
**Maybe** such a quest could get higher priority at night (real hour for the user, time of the phone) and lower priority at day.

**Comment by HolgerJeromin** [comment]
@lightonflux my cycleway example are two separate ways in OSM (and already tagged lit+unlit).

**Comment by matkoniecz** [comment]
It is an expanded spec, now I added also schema of questions that user would answer.

I think that it should be split into separate quests (reuse of icon is possible, so difference would not be obvious to user) as asked questions would be different.

both quests would ask for objects that fulfil all of following criteria:
    highway=motorway|motorway_link|trunk|trunk_link|primary|primary_link|secondary|secondary_link|tertiary|tertiary_link|unclassified|residential|service|living_street|pedestrian|footway|cycleway|path
- lit key is not present on the object
- object is not a node or relation
- access key is not present or access=yes or access=permissive

# general one

it would skip objects with tunnel key, except tunnel=no

asked question: "Is this street lit?"
 - [ ] During night
 - [ ] Never
 - [ ] Other

- 'Other' would bring subquestion
 - [ ] Always
 - [ ] Motion detection

# tunnels

tunnel specific would process only objects with tunnel=yes, tunnel=building_passage, tunnel=avalanche_protector

asked question: "Is this tunnel lit?" (ask 'Is this passage lit?' for tunnel=building_passage
 - [ ] Always
 - [ ] Never
 - [ ] Other

- 'Other' would bring subquestion
 - [ ] During night
 - [ ] Motion detection

Additional idea: maybe differ priority of lit quest and increase it during night (that is possible to compute from GPS position and time).

Lit may be asked about other objects like pitches, parkings, pedestrian areas, statues, historic buildings etc - but it is probably better to start from less specialized version.

At this point I am unsure whatever special version of questions for tunnels is worth it - maybe always include "during night", "never", "always" and leave other options for full scale editors?

**Comment by westnordost** [comment]
> access key is not present or access=yes or access=permissive
I'd leave this out. If the user is not able to get there, then he can't answer the quest, big deal. There can be many other reasons why a user cannot access a location. But +shrug+

The priority for the user interface design is to make the most usual cases easy to access while not making all the edge cases impossible. Look at [taginfo](https://taginfo.openstreetmap.org/keys/?key=lit#values): 99% is yes/no.

**So, the UI should just be a simple Yes/No answer.**
Leaving to the user whether he answers "during night" or "always" will only create confusion. Please leave that out.

Regarding all the other cases, remember, for every quest, there is the "Other answers..." menu available. In this menu, I'd only include "motion detection" and "can't answer" to cover everything else.

> Tunnels
I'd say, leave this out first. It can be added later.

**Comment by matkoniecz** [comment]
I see that there is already quest icon prepared (https://github.com/westnordost/StreetComplete/commit/40c9ee5187f7b4f23159afbbd86cd9d16c605925), I wonder whatever there is need to find suitable images for answers (but I think that this quest would work well also without images).

>  Leaving to the user whether he answers "during night" or "always" will only create confusion. Please leave that out.

It will result in some places that should be tagged as `lit=24/7` ending as `lit=yes` - but that is result of poorly handled tag system that for some result decided to put values that should be handled by multiple tags into one. I am tempted to put 24/7 into 'other' to make possible to add this data - but yes, that would be at least a bit confusing...

**Comment by westnordost** [comment]
Sounds good, I'd name the item "It's lit night and day" or similar.

On 27 April 2017 08:58:05 CEST, Mateusz Konieczny <notifications@github.com> wrote:
>I see that there is already quest icon prepared
>(https://github.com/westnordost/StreetComplete/commit/40c9ee5187f7b4f23159afbbd86cd9d16c605925),
>I wonder whatever there is need to find suitable images for answers
>(but I think that this quest would work well also without images).
>
>>  Leaving to the user whether he answers "during night" or "always"
>will only create confusion. Please leave that out.
>
>It will result in some places that should be tagged as `lit=24/7`
>ending as `lit=yes` - but that is result of poorly handled tag system
>that for some result decided to put values that should be handled by
>multiple tags into one. I am tempted to put 24/7 into 'other' to make
>possible to add this data - but yes, that would be at least a bit
>confusing...
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/westnordost/StreetComplete/issues/84#issuecomment-297628760

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by westnordost** [comment]
So, are you up for implementing it? If yes, you can create a branch in a fork right away in case you find it helpful if I give you feedback early.

**Comment by matkoniecz** [comment]
I really want to work on it, but at this moment I make no promises.

**Comment by Piskvor** [comment]
@lightonflux: Yes, they're mapped separately (and tagged lit=yes/no) : https://www.openstreetmap.org/way/57372604#map=17/51.86990/8.54413
https://www.openstreetmap.org/way/34378839#map=16/51.8698/8.5418

**Comment by Carnildo** [comment]
In my experience with mapping street lights, a simple "yes/no" only works in the built-up portions of a city (almost always "yes"), or in rural areas (almost always "no").  For everything in between, you frequently need to split a way because the lights end with a change of jurisdiction, or a residential area opted out of street lights while the nearby commercial district didn't, or the lighting status changes for other reasons.

**Comment by ninjamask** [comment]
In germany and austria streetlights can be `lit=limited` for lights that are not lit the whole night. They may but don't have to show a time at which they go off.

https://de.wikipedia.org/wiki/Laternenring

**Comment by krzyk** [comment]
@lightonflux I think this can be closed, added it in #424

**Comment by ninjamask** [comment]
what about `lit=limited`?

**Comment by krzyk** [comment]
@ninjamask `hour_off` would make it quite complicated quest for tag value that is 0.11% of total `lit` tag usage. I'm also not sure that using a tag value that exists only in German version, maybe someone would "upgrade" it to English one.

**Comment by westnordost** [comment]
With v1.1.
