### ISSUE TITLE
Quest UI - Bottom, Slice of the Map

### ISSUE THREAD

**Issue by lokaman** [westnordost/StreetComplete#841]
Hey,

just updated to 4.0beta01 - I noticed that there is a small slice of the map at the bottom of the quest UI.

Is this intended? Or even a new feature?

See https://lut.im/ydHhb5BSlA/Q5PzzVkENLOdn4Pd.png

Keep up the the good work! :relaxed:

**Comment by westnordost** [comment]
Yeah I noticed that on screenshots from other devices as well. On my device, though, I do not see this slice, so I cannot reproduce it.
I did not try with emulators yet. What version of Android do you have?

**Comment by matkoniecz** [comment]
Happens also for me with Android 6.0.1 on Xiaomi Redmi 4.

**Comment by westnordost** [comment]
Cool, @matkoniecz , could you perhaps inspect the layout on your phone then? (Tools->Android->Layout Inspector in Android Studio when the bottom sheet is open)

**Comment by rugk** [comment]
Can reproduce this.

And there is one way to "fill the slice":
1. Switch to another app (or that app drawer or how that switcher is caled)
2. An dswitch back
-> The glitch is gone.

**But** I just tested it and it is it is reproducible with…
* the stable version of StreetComplete, so it is no new issue. (maybe you only notice it now, because of the more prominent green color for landuse, while it was grey before.)
* the landscape view of the phone, *if* the quest' height is smaller than the height of your phone (when hold in landscape view).

LineageOS 14.1/Android 7.

**Comment by lokaman** [comment]
@westnordost 7.1.2 (LineageOS), on Xiaomi Redmi Note 4 - 5.5" Phone

**Comment by matkoniecz** [comment]
> Cool, @matkoniecz , could you perhaps inspect the layout on your phone then? 

> (Tools->Android->Layout Inspector in Android Studio when the bottom sheet is open)

I did this and unfortunately in layout inspector buttons are reaching bottom of the screen, despite what I see on screen.

I would be happy to do whatever is necessary to proceed with debugging, unfortunately I have no idea what I should do (and I am curious how one debugs such issues).

**Comment by westnordost** [comment]
What if you make the background of the button bar pink, will the pink also not cover the whole bottom of the screen?

**Comment by rugk** [comment]
BTW you can move the map as you want and see the correct map "slice" at the bottom. So it is not something freezing, it fully "works", or something like that…

**Comment by matkoniecz** [comment]
> What if you make the background of the button bar pink

How one may do this? I looked through https://developer.android.com/studio/debug/layout-inspector.html and similar and I noticed no way to do that.

**Comment by ENT8R** [comment]
I think @westnordost meant this:
<img src="https://user-images.githubusercontent.com/25306497/35981366-5d83ea00-0ced-11e8-9214-16364c6708a9.png" width="300px">
Which has no effect on the gap...

**Comment by westnordost** [comment]
Hmm, what if the bottom bar style is removed (`style="?android:attr/buttonBarStyle"`)? Does this problem also exist in landscape mode? If you give the whole SlidingLayout a pink background color, would it still be transparent at the bottom?

**Comment by rugk** [comment]
> Does this problem also exist in landscape mode?

Yes, see [my comment above](https://github.com/westnordost/StreetComplete/issues/841#issuecomment-363916480):
> it is reproducible with […] the landscape view of the phone, if the quest' height is smaller than the height of your phone (when hold in landscape view).

**Comment by ENT8R** [comment]
> it is reproducible with […] the landscape view of the phone, if the quest' height is smaller than the height of your phone (when hold in landscape view).

And looks like this:
<img src="https://user-images.githubusercontent.com/25306497/36032118-423588d8-0dad-11e8-9a49-90c800dfccc8.png" width="300px"> <img src="https://user-images.githubusercontent.com/25306497/36032125-46c76150-0dad-11e8-92f6-0591f6e69da3.png" width="300px">

---

BTW: On **Android 8.0.1** it looks like this:
<img src="https://user-images.githubusercontent.com/25306497/36031645-c2414d16-0dab-11e8-8a5f-33835a8a22ca.png" width="300px">

---

If the bottom bar style is removed:
<img src="https://user-images.githubusercontent.com/25306497/36031859-72d3532c-0dac-11e8-9935-e26ca2507c2b.png" width="300px">

---

And after pressing the home button and switching back into the app
<img src="https://user-images.githubusercontent.com/25306497/36031882-860360ea-0dac-11e8-8cfd-fc1c3918d7f0.png" width="300px">

---

> If you give the whole SlidingLayout a pink background color, would it still be transparent at the bottom?

<img src="https://user-images.githubusercontent.com/25306497/36032224-9bcf3146-0dad-11e8-9f7d-e103e218dfcd.png" width="300px">

---

So it does seem to be a problem with the parent layout...

**Comment by westnordost** [comment]
Wow, thanks for trying out all this. I wonder if my hack in SlidingRelativeLayout may somehow cause this and if this would be fixed if it would be replaced with a proper solution like here https://github.com/DesarrolloAntonio/FragmentTransactionExtended/blob/master/libraryFragmentTransactionExtended/src/main/java/com/desarrollodroide/libraryfragmenttransactionextended/SlidingRelativeLayout.java#L30-L44

I don't see a connection though, but worth a try.

Otherwise, perhaps one can set clipChildren of the parent layout to false.

**Comment by westnordost** [comment]
@ENT8R does any of the things I proposed solve the problem on your device?

**Comment by ENT8R** [comment]
I didn't try it yet... Perhaps today

**Comment by westnordost** [comment]
Or today? :-P

**Comment by ENT8R** [comment]
The proper solution works:
<img src="https://user-images.githubusercontent.com/25306497/36426542-964a98dc-164a-11e8-8376-e756fc106bce.png" width="300px">

I only have to test now whether it works also with the battery saver mode, or what you said here:
https://github.com/westnordost/StreetComplete/blob/b2e38abb12522064bf8f2576772295808db45178/app/src/main/java/de/westnordost/streetcomplete/view/SlidingRelativeLayout.java#L27

**Comment by ENT8R** [comment]
Works even with battery saver on! 🎉 I will make a PR now!
