### ISSUE TITLE
Icon: toilets fee should get wad of banknotes

### ISSUE THREAD

**Issue by rugk** [westnordost/StreetComplete#843]
In order to differentiate the toiletfee and "is there a toilet" quests, I think you should stay consistent to other (i.e. parking) quest icons and also show the wad of banknotes in the toilets fee quest.

**Comment by westnordost** [comment]
Yeah.

**Comment by rugk** [comment]
You'd accept a PR?

**Comment by westnordost** [comment]
No, I am doing this right now
