### ISSUE TITLE
Crash on 'street with no name' on 4.0b1 

### ISSUE THREAD

**Issue by RubenKelevra** [westnordost/StreetComplete#845]
Selecting this menu point crash SC. Version 4.0b1
![screenshot_20180208-122456__01](https://user-images.githubusercontent.com/614929/35970909-66e9450c-0ccc-11e8-8db8-929d0ac140a9.jpg)

**Comment by westnordost** [comment]
Damn, looks like beta2 at the weekend.

**Comment by RubenKelevra** [comment]
Thanks for the fast fix :)
