### ISSUE TITLE
Loading cached tile data is blocked while bad reception

### ISSUE THREAD

**Issue by RubenKelevra** [westnordost/StreetComplete#846]
Opening the App with no internet connection (airplane mode) all stored offline tiles are shown immediately. Opening the app with a working but extremely slow internet connection, like very slow edge-network, only some or none of the cached tiles are shown and after a very long time something seems to timeout or give up and all cached tiles are shown.

This looks like the first non-cached or outdated cached tile blocks the loading of (other) cached tiles while the app tries to download/update it.

Those operations should be split, creating a list with a prioritization sorting for needed-to-be-downloaded/updated tiles while this is diverted to a background process and all other tiles which are available are loaded from the cache.

This is not always the case, the chance that this happens seem to be around 1/4 probably makes it hard to track down.

**Comment by ENT8R** [comment]
I am pretty sure that this issue is not related to SC at all... It is very probably an issue with the rendering library https://github.com/tangrams/tangram-es
Please report your issue there!

**Comment by Akasch** [comment]
> This is not always the case, the chance that this happens seem to be around 1/4 probably makes it hard to track down.

I think this have something to do with the expire times as told by the server, as I think the rechecking only happens if the expire date is approached but not in the past.

**Comment by westnordost** [comment]
So is this a problem of tangram-es or the vector tile server?

**Comment by westnordost** [comment]
See @ENT8R

**Comment by RubenKelevra** [comment]
Thanks for pointing this out, I thought you was waiting for a response from @ENT8R not from me.

I've created a ticket for tangram-es: https://github.com/tangrams/tangram-es/issues/1777

**Comment by matteblair** [comment]
I've looked into this in Tangram ES and I don't think there's much we can do in the engine about this. We're just respecting the `cache-control` as specified by the tile server. 

The current tile source in the app (`https://tiles.map-data.de/vector/v1/512/all/{z}/{x}/{y}.mvt`) provides tile responses with the header `cache-control: max-age=86400`. 86400 seconds is 24 hours, so the server is asking us not to show any responses more than a day old.

If you want the client to accept stale responses from the cache, then the client should provide a `CachePolicy` to the `HttpHandler`. There's an example of this in the Tangram Android demo app: https://github.com/tangrams/tangram-es/blob/master/platforms/android/demo/src/main/java/com/mapzen/tangram/android/MainActivity.java#L174-L190
