### ISSUE TITLE
Quest: postboxes collection times

### ISSUE THREAD

**Issue by lightonflux** [westnordost/StreetComplete#85]
This one is really easy basically the same as opening hours for shops but with `collection_times=` for `amenity=post_box`.

Maybe with a nice postbox icon for the quest instead of the clock icon. Just to make it more appealing. 

[OSM wiki](https://wiki.openstreetmap.org/wiki/Tag:amenity%3Dpost_box)

**Comment by PanderMusubi** [comment]
Just added a picture of a post box in the (continental) Netherlands to https://wiki.openstreetmap.org/wiki/Tag:amenity%3Dpost_box Unfortunately, these do **not** have a visible ID and full collection schedule is only available online. The box itself only lists the next collection. According to https://www.postnl.nl/versturen/brief-of-kaart-versturen/hoe-verstuur-ik-een-brief-of-kaart/brievenbussen/ all Dutch post boxes are collected Monday, Tuesday, Wednesday, Thursday and Friday at 17:00, according to a national law. So if that law changes, it applies to all post boxes in the Netherlands. This information can be added via a bulk edit. Shall I ask the Dutch OSM community for this? Could you not offer this option in the (continental) Netherlands to prevent accidental variations?

**Comment by lightonflux** [comment]
If it is already tagged then StreetComplete does not change existing values. It only adds.

For the Netherlands it would make sense to create a discussion in your localised OSM forum and change all your post boxes that are affected by the law.

If possible we could limit the scope so the Quest does not include the Netherlands.

**Comment by westnordost** [comment]
OK this quest may make sense, **BUT** only in those countries where a timetable is actually (usually) visible on every post box. Otherwise, it creates **a lot** of false positives.

What I need here before is a list of countries in which is the case.

**Comment by PanderMusubi** [comment]
So only when a country is listed, this quest becomes available in that country?

**Comment by westnordost** [comment]
That's the plan. To have an exclusive list (all minus the Netherlands for example) is not a good idea if we want to avoid false positives (=quests where the answer would be "Can't Answer").

**Comment by lightonflux** [comment]
100% sure:

 * Germany [image](http://c8.alamy.com/comp/ARB3JR/post-box-of-the-german-post-office-ARB3JR.jpg)

**Comment by Jotam** [comment]
Very good quest. Strongly supported.

**Comment by westnordost** [comment]
Thanks for the research, lightsonflux! But, I need more, more more!!!1 :-)

**Comment by PanierAvide** [comment]
Timetable is also visible on pretty all French post boxes: [image](https://commons.wikimedia.org/wiki/File:Savign%C3%A9_86_Bo%C3%AEte_aux_lettres_2012.jpg).

**Comment by Etua** [comment]
In Poland the hour of collection is written on the postbox and it cannot be latter than 15.00 so if localized quests will have a feature of special requirements for the input that could be one.

**Comment by PanderMusubi** [comment]
In Netherlands, a lot of postboxes is going to be removed. So also an option: 'here is no postbox' should be available via this quest.

**Comment by Jotam** [comment]
@PanderMusubi: It doesn't make a lot of sense to add the string "no postbox" to the "collection_times" tag. This must be solved in a different way, I think.

**Comment by PanderMusubi** [comment]
Adding a tag is not useful. Should indeed be handled in another way, but incorporating this in this and similar quests is useful.

**Comment by Codain** [comment]
+1

Collection times are also displayed:

- On USPS boxes in USA: [image](https://upload.wikimedia.org/wikipedia/commons/6/6d/USPS_mailboxes.jpg)
- On Post Canada boxes in Canada: [image](https://s3.amazonaws.com/images.thestar.com/content/dam/thestar/business/2013/04/23/canada_post_faces_1b_annual_operating_loss_by_2020/canada_post_box.jpg)

**Comment by majkaz** [comment]
Not sure about Czech republic - just in the last year, we started to import the data from the Czech post office.  The quest should at least be consulted with the local community.
As a note - there are changes every month in the schedule since we started to enter and compare the data - the quest as such doesn't make sense from this point of view (never completes accurately).

**Comment by westnordost** [comment]
A quest would only pop up for post boxes that have no collection times yet.

On 23 October 2017 10:29:13 CEST, majkaz <notifications@github.com> wrote:
>Not sure about Czech republic - just in the last year, we started to
>import the data from the Czech post office.  The quest should at least
>be consulted with the local community.
>As a note - there are changes every month in the schedule since we
>started to enter and compare the data - the quest as such doesn't make
>sense from this point of view (never completes accurately).
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/westnordost/StreetComplete/issues/85#issuecomment-338585183

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by fgouget** [comment]
As I have been mapping the French post boxes for a while I strongly support this quest for France.

In France the collection time is always the same from Monday to Friday, and only Saturday may be different. Taking this into account could help simplify entering the data. But I guess it would make the code specific to France so I quite understand if the generic code is used to keep the code simple.

Also in France all post boxes have a unique id and adding this id in the 'ref' field is very useful as it makes it possible to cross-reference the postbox with the government's open-data list of post boxes (which does not provide the collection times, how stupid is that!). Should this be the subject of a separate quest and/or bug?

**Comment by ENT8R** [comment]
The ID/ref quest has already been proposed in #81

**Comment by westnordost** [comment]
The implementation is basically done, but:

> There is one thing that should be cleared up before this is merged: How to tag a post box, that has no collection times posted?
> 
> I raised this question in the wiki discussion page, you are welcome to contribute to the discussion there:
> https://wiki.openstreetmap.org/wiki/Talk:Key:collection_times
