### ISSUE TITLE
StreetComplete banned / Undo Feature was broken Jan 7 - Feb 9

### ISSUE THREAD

**Issue by westnordost** [westnordost/StreetComplete#852]
### My version of StreetComplete is banned??
Jup, I disabled uploads for versions v3.3 to v3.6 and the v4.0 beta1 because it turned out that the undo feature was partly broken in these versions. Version 3.3 came out on January 7th.

**To enable uploads again, just update.**

Here is some more information on this:

### What exactly did not work?
Technically, the undo feature consists of two parts: undoing an answer while it hasn't been uploaded yet, and undoing an answer that has already been uploaded to OpenStreetMap - a.k.a. reverting.
It was the reverting that was broken. In the app, it looked like it worked alright, but in reality, nothing was reverted. That it did not work, you could only see by that the seemingly undone quest did not pop up again on the map. This is also how the bug was found today (#849).
So, in a nutshell, if you always uploaded your answers manually after your survey and made your corrections "offline" (if any), you can ignore all this, all is fine.
If not (by default, answers are uploaded immediately) and you remember undoing things in the last month, you should check your OSM history for not-actually-undone-mistakes.

### When is this fixed?
It is fixed now. In version 3.7 and version v4.0-beta2.

If you are here from **F-Droid**: Their repository takes up to one week to update to the latest version. But that's fine, you can still continue to solve quests offline and when the new version is out, upload everything. Or, you can also download the new APK from github. 

### How do I see my changes / How to correct this?
You see all the changes you made on https://www.openstreetmap.org/. Click on your name, then on "My Edits". There, you have an overview over all your changesets, ordered by date.
If that feels to unwieldy, you can also try https://osmcha.mapbox.com. This tool can also show your changes and does that in a very clearly arranged fashion. On Osmcha, click on "Filters" and scroll down to fill in your username in order to show only changes made by you.
Once you identified that there is a mistake, the easiest way to correct it would be to use the editor on the openstreetmap website, **iD**, to correct the information (click the Edit button on openstreetmap.org).

**Comment by rugk** [comment]
> Or, you can also download the new APK from github.

But that does not allow you to upgrade the old versioon to a new one, as it has a different signature.

**Comment by lenod** [comment]
Unfortunately, the build failed on fdroid, seemingly for a simple http timeout reason…
https://f-droid.org/wiki/page/de.westnordost.streetcomplete/lastbuild_307

**Comment by westnordost** [comment]
Uhm, yeah, looks like it. I can download that jar without problem.

This will somewhat delay everything now. I think their build server does not automatically retry, one has to create a ticket and all that.

**Comment by westnordost** [comment]
So, I asked in the F-Droid forum if after the failing build, any manual action for retrying is necessary or not, let's see.

**Comment by rugk** [comment]
link?

**Comment by rugk** [comment]
Reply:
> Yes. No action required.

**Comment by nebulon42** [comment]
Build succeeded: https://f-droid.org/wiki/page/de.westnordost.streetcomplete/lastbuild_307

**Comment by JeanFred** [comment]
Got the 3.7 upgrade this morning via F-Droid :)

**Comment by privatwolke** [comment]
I really appreciate the transparency with this issue!  Thank you for your exemplary work! :+1:

**Comment by privatwolke** [comment]
I really appreciate the transparency with this issue!  Thank you for your exemplary work! :+1:

**Comment by privatwolke** [comment]
I really appreciate the transparency with this issue!  Thank you for your exemplary work! :+1:

**Comment by privatwolke** [comment]
I really appreciate the transparency with this issue!  Thank you for your exemplary work! :+1:

**Comment by westnordost** [comment]
On Google Play, on Thursday there were still 6.8% on the affected versions. I expect the number will go down to near-zero until before the next update, so I will remove the alert message (and close this issue).
