### ISSUE TITLE
Edits seem to be grouped into changesets incorrectly

### ISSUE THREAD

**Issue by codingcatgirl** [westnordost/StreetComplete#853]
Hi again,

while reviewing my changes to find out which errors were not undone due to #849, i noticed something strange. If i understand correctly, StreetComplete should group edits into changesets by change type. 

However, 3 days ago i did an StreetComplete walk and added roof shapes and levels. The app created two changesets for this, namely [56188288: Add building and roof levels](https://osmcha.mapbox.com/changesets/56188288) and [56188354: Add roof shapes](https://osmcha.mapbox.com/changesets/56188354).

However, while these changesets largely contain the same buildings and were being continuously updated during the same time, some building and roof level changes were assigned to the roof shapes changeset. See this screenshot:

![download](https://user-images.githubusercontent.com/3868507/36061813-51cac0ac-0e60-11e8-81d9-51ea2ced2590.png)

The highlighted building is completely missing from the levels changeset and all changes made to it (levels and roof shape) were added to the same roof shape changeset. This is not the case for most of the other buildings that were changed during that session (before and after that building) – their changes were split up into both changesets correctly.

Is this expected behaviour? It looks like a bug to me.

**Comment by codingcatgirl** [comment]
Another example from that day are changesets [56188363: Add speed limits](https://osmcha.mapbox.com/changesets/56188363) and [56188366: Add way lit](https://osmcha.mapbox.com/changesets/56188366). The latter contains speed limit changes which should propably belong to the former changeset. Also, it contains road surfaces.

The reason cannot be that the former changeset was closed, because there were still speed limits added to it later.

**Comment by westnordost** [comment]
Hmm, it seems to be a problem with Osm Changeset Analyzer. Let's look at the [56188366 - Add Way Lit changeset](https://osmcha.mapbox.com/changesets/56188366).
According to Osm Changeset Analyzer, you added four tags on the **Heidbusch** road in that changeset:
![heidbusch-osmcha](https://user-images.githubusercontent.com/4661658/36062773-256944c6-0e73-11e8-9ab7-6f0d967374cd.png)

However, looking at the history of the element in JOSM, one can see that the four changes were actually uploaded in three different changesets (i.e. look at the changeset number I framed with a green rectangle in the screenshot)
![heidbusch-josm](https://user-images.githubusercontent.com/4661658/36062787-839137f2-0e73-11e8-8b29-b738ed4a4d7c.png)

The [changeset on OpenStreetMap](https://www.openstreetmap.org/changeset/56188366#map=17/51.46089/6.94899) also lists only version 10 of the way as being part of the Add Way List changeset:
![heidbusch-osm-history](https://user-images.githubusercontent.com/4661658/36062808-e833ab90-0e73-11e8-9a06-7586ce340331.png)

So, I will forward this bug report to OsmCha.

**Comment by westnordost** [comment]
Alright, posted it in their bugtracker.

Wow, anyway, thank you for being so vigilant. Who knows how much later anyone would have noticed (especially the one you reported yesterday) if you hadn't reported it!

**Comment by codingcatgirl** [comment]
Thanks and you're welcome :)
