### ISSUE TITLE
Tunnels and swimming pools not rendering properly 

### ISSUE THREAD

**Issue by iamnunocaldeira** [westnordost/StreetComplete#854]
Congrats on the last updates. However in the new map layout there's no tunnels rendering and swimming pools look weird.

Keep up the good work

**Comment by ENT8R** [comment]
The new mapstyle is maintained at https://github.com/ENT8R/streetcomplete-mapstyle/
Please report your issue there and give also examples where you can see the issue...

**Comment by rugk** [comment]
Can be closed, as https://github.com/ENT8R/streetcomplete-mapstyle/issues/46 has been opened.
