### ISSUE TITLE
Cached tiles get discarded too early

### ISSUE THREAD

**Issue by RubenKelevra** [westnordost/StreetComplete#855]
I've been using SC in many Edge-areas aka forests and often discover already surveyed aeres to be empty (no tiles in cache). I've rised the cache size to 250 MB (which seem to me a oddly low maximum limit nowadays) and SC still uses just 60 MB while parts of the map I've been viewed just 2-3 days ago are just void.

I don't care if the tiles are outdated, it's better than nothing at all... if I visit an area where the tiles are outdated SC could just refresh them in background. But removing tiles while the cache size isn't reached is not useful.

**Comment by matkoniecz** [comment]
I encountered similar problem and in my case problem was apparently caused by Android System deleting cache as device had limited memory available.

Is there plenty of space available on your device?

**Comment by matkoniecz** [comment]
See #208 

> Basically, as you probably found out by the research by yourself, StreetComplete (and neither tangram-es) does have a big influence over what things in the cache get invalidated first.

See also https://github.com/westnordost/StreetComplete/pull/209#issuecomment-301320132

**Comment by RubenKelevra** [comment]
@matkoniecz currently my memory is filled 21%, leaving 95 GB free.

I never clean the cache of applications (this is just a dumb practice) and there is around 80 MB used for cache on SC.

I think this issue might still be this one https://github.com/westnordost/StreetComplete/issues/846 and not different. I gonna ask for a reopening if this loading from cache blocking this is fixed in tangram-es.
