### ISSUE TITLE
Lanes for streets

### ISSUE THREAD

**Issue by RubenKelevra** [westnordost/StreetComplete#856]
### General

We in Germany got many country roads which doesn't have center divider line and are very narrow. This would be a very useful information for routers, because you cannot drive that fast on those roads.

So it would be interesting of a unclassified road has 2 lanes, 1.5 or just 1 lane, where you need to find a wide place to pass other vehicles.

In cities this is a very bad idea to implement this, cause the lane numbers often change, which would make way splits necessary, but in rural environments this would be possible.

### Checklist
Checklist for quest suggestions (see guidelines):
- [x] 🚧 To be added tag is established and has a useful purpose
- [x] 🤔 Any answer the user can give must have an equivalent tagging (Quest should not reappear to other users when solved by one)
- [x] 🐿️ Easily answerable by everyone from the outside but a survey is necessary 
- [x] 💤 Not an overwhelming percentage of elements have the same answer (No spam)
- [x] 🕓 Applies to a reasonable number of elements (Worth the effort)

### Ideas for implementation

**Element selection:** 

If there's no lane tag for a highway=unclassified|tertiary|track(+grade1)|service" and it's not inside a city (maybe determine by the speed restrictions) than ask for the lane numbers: 1, 1.5, 2.

**Proposed GUI:** 

If 3 or more as answer should be possible we need to display the street like for bike lanes, to make it possible to select a direction per lane count.

I don't feel this is necessary, most lane counts should be below 3.

**Comment by ENT8R** [comment]
If you want to propose a new quest, please use the issue template to fill out answers which makes it easier to implement the quest...

**Comment by RubenKelevra** [comment]
Yea I read this but there's currently no issue open for this, so I opend one. :)

**Comment by RubenKelevra** [comment]
Updated the issue with the template, thanks for the hint. :)

**Comment by rugk** [comment]
@RubenKelevra I assume you accidentally closed this issue.

**Comment by ENT8R** [comment]
@rugk I think you should have a look at this statement: https://github.com/westnordost/StreetComplete/pull/1081#issuecomment-392332668

**Comment by rugk** [comment]
Yeah, saw it later, so in whatever way that turns out, @westnordost, please reopen this. :smile:

**Comment by matkoniecz** [comment]
> 2 lanes, 1.5 or just 1 lane

1.5? How road with 1.5 lane looks like? I see some minimal usage ( https://taginfo.openstreetmap.org/tags/?key=lanes&value=1.5 ) and

> Some people prefer to tag narrow two-way roads with lanes=1.5.

on wiki, but I am not really convinced that it is a valid tagging. On the other hand I am not sure what `lane` tag road without explicit lane markings wide enough to make passing of vehicles usually possible but narrow to require passing places for busses/trucks.

`lanes=2`? After all, there are full sized roads with explicit lane markings where busses have big trouble to pass.

**Comment by RubenKelevra** [comment]
@matkoniecz maybe there's a better tag for this, than lane=1.5, but it's definitely not lane=2 in this case.

Here's an example
![narrow](https://user-images.githubusercontent.com/614929/82141079-becbc200-9833-11ea-9796-b9f2d9969af4.jpg)

**Comment by westnordost** [comment]
https://wiki.openstreetmap.org/wiki/Key:lanes#No_lane_markings

**Comment by RubenKelevra** [comment]
> https://wiki.openstreetmap.org/wiki/Key:lanes#No_lane_markings

Yeah, this article changed significantly since I've opened this ticket. [See the old version](https://wiki.openstreetmap.org/w/index.php?title=Key:lanes&oldid=1542635#Narrow_roads)

This idea boils now down to add a quest:

---

IF `highway=unclassified` AND ( NOT `lanes=*` OR `lanes=1.5` OR (`lanes=1` AND NOT `oneway=yes`) OR `lanes=1` ) THEN

ask for `lane_markings`

IF `lane_markings=no` THEN

ask for width

IF `lane_markings=yes` THEN

ask for lanes

---

I think that quest is pretty important since we will collect details that are crucial for HGV routing.

**Comment by matkoniecz** [comment]
I found a very interesting use case - https://github.com/dabreegster/abstreet (it is a traffic simulator/game) that generates city maps from OSM data. Seattle is prominently supported, but making maps by importing from `.osm` file is also possible.

I am mentioning it, as it is the first data consumer known to me actually using this kind of data - and it is generally accessible.

**Comment by arne182** [comment]
I am also using this for https://github.com/arne182/ArnePilot autonomous driving to figure out which way is the most likely path that would be driven on. On the idea of 1.5 lanes, how I understand it is the amount of center lines is a clear indication of 1 or 2 and if one then rather width with source:width=estimated

**Comment by kmpoppe** [comment]
While I was trying to build a quest for this I noticed that there must have been a "streetLanes" quest at some point? Is it gone? Did it never get finished @westnordost?

**Comment by westnordost** [comment]
There isn't a street lanes quest yet.

**Comment by westnordost** [comment]
And it will be more work, because I need to think of a good UI for this too. I think this quest is not eligible for new contributors. But I will implement it, soon.

**Comment by RubenKelevra** [comment]
@westnordost please reopen this ticket, since we still don't collect the lane count or width for roads with unmarked lanes

**Comment by matkoniecz** [comment]
> @westnordost please reopen this ticket, since we still don't collect the lane count or width for roads with unmarked lanes

Collecting lane count for streets with unmarked lanes was implemented and deliberately removed.

Collecting width would go into a separate issue (that may exist already).
