### ISSUE TITLE
Crashes while uploading

### ISSUE THREAD

**Issue by RubenKelevra** [westnordost/StreetComplete#857]
I've send two reports from crashes while uploading via crash feedback to you. Once is some minutes old, one around 6 hours. Before 4.x had no issues at all.

I'm currently running 4.0b2.

**Comment by westnordost** [comment]
How did you sent it? Via email? I did not receive anything.

If you sent it with Google Play, the only crash that is happening with 4.0-beta2 I see there is https://github.com/tangrams/tangram-es/issues/1772

**Comment by westnordost** [comment]
So,  I guess that is that, I did not receive any other crash reports on Google Play or via email.

**Comment by RubenKelevra** [comment]
Thanks, yep it was sent via Google Play. :)
