### ISSUE TITLE
When banning a version, allow the server to offer a reason

### ISSUE THREAD

**Issue by raboof** [westnordost/StreetComplete#858]
I ran into #852. While the explanation in the github issue was great and relatively easy to find, it would be even nicer if the error message in the app could have been something like: "You are running version X.Y of streetcomplete, which is banned from uploading because it contained a bug affecting undo. This bug has been fixed on version 3.7, which is expected to be available on F-Droid around XyZ. Until that time you can still continue to solve quests offline and when the new version is out, upload everything".

This would of course require the server to not just reply 'banned', but also provide the message to be shown.

**Comment by rugk** [comment]
Such a message will be shown in the next version, see https://github.com/westnordost/StreetComplete/commit/bc88dc7e0c1e9df173f030d275fb1f22e7e94b22.

But what you actually want is just a way to add an explanation to the blocking message. That is a good idea, IMHO.

**Comment by PanderMusubi** [comment]
And perhaps some information on when to expect a new version in the app stores.

**Comment by westnordost** [comment]
Done.
@PanderMusubi: F-Droid usually takes up to one week to update supply the latest version.

**Comment by PanderMusubi** [comment]
Wow, that is a reasonably long time. Isn't there a fast track?

**Comment by rugk** [comment]
No, they built it as fast as they can, but sometimes builds fail and so on, so mhh... there may always be something. Sometimes it takes just one day, sometimes considerably more.
