### ISSUE TITLE
Create quest template for issue tracker

### ISSUE THREAD

**Issue by lightonflux** [westnordost/StreetComplete#86]
With github you can [prefil](https://eric.blog/2016/01/08/prefilling-github-issues/) issues. I think it would be helpful to developers and issue creators if we linked to a quest template  (e.g. from the README).

Here a first draft for a quest template:

```
# Quest suggestions/request are really helpful to improve StreetComplete and
# know what our users want to tag...
#
### Question
# Every quest should be formulated as a question that is easy to understand. 
# Example: Is this road lit?

### Answers
# List all reasonable answers. If possible use OSM keys and link to the OSM wiki.
# Example:
#  * yes
#  * no
#  * lit_by_gaslight
# [OSM Wiki](https://wiki.openstreetmap.org/wiki/Key:lit) 

### UI (optional)
# Describe how you imagine the UI to look. You can also include mockups as images. 
# Example:
#  Every answer has a little image above its text:
# * yes: a road with glowing lamp posts
# * no: a road with a read X next to it
# * lit_by_gaslight: a gas lamp
# ![](image.png)

### Quest scope (optional)
# If the quest would affect a huge number of object it can make sense to limit its scope to certain features or types. 
# Example: 
# Only offer this quest for bigger roads or roads that are paved.

```

I know this isn't perfect and not well formulated. 
Would like to hear what you think of the idea.

**Comment by westnordost** [comment]
Actually, can you as a non-project member edit the wiki for this project? I thought about putting this info into the wiki.

**Comment by CloCkWeRX** [comment]
#93 is an idea or two about a more structured version that can be just done as a pull request or similar, also trying to lower the barrier to contributing quests.

**Comment by lightonflux** [comment]
> Actually, can you as a non-project member edit the wiki for this project? 

Don't find any edit buttons. So no.

**Comment by westnordost** [comment]
Actually, I will close this issue. The requests for quests are fine as they come in now, most of the designing work is up to the implementer (that's me) anyway. And if there is someone who is especially engaged to provide already a sketch-up of how the form could look, that's fine as well.
