### ISSUE TITLE
banned version to upload answers???

### ISSUE THREAD

**Issue by easyKL** [westnordost/StreetComplete#860]
Being on 3.6 from F-Droid, I got:
_This version of StreetComplete has been banned from uploading any answers! Please update your version!_
Yes, 3.6 is the last available on F-Droid now. 
_Banned_? What a word!

pls check

**Comment by ENT8R** [comment]
Please see #852 This should answer all your questions!

**Comment by easyKL** [comment]
**Please always check the open issues to avoid redundancy**

**Comment by rugk** [comment]
Indeed, that's what you may have done before. And now you can close the issue.
