### ISSUE TITLE
What is the typical size of an upload?

### ISSUE THREAD

**Issue by DaCor1** [westnordost/StreetComplete#861]
I'm asking in relation to doing field surveys in low bandwidth/high data cost locations. 

If I was to avoid caching and instead download/upload as I go, in terms of map tiles, quests and uploads, roughly how much data would I expect to consume if I was using the app out in the field for 2 hours

**Comment by matkoniecz** [comment]
Note that it depends not on time but on (a) area covered by mapping (b) density of OSM data in this area.

Note also that with known mapping area you can run quest download using WiFi and fetch map tiles and upload quest after returning what allows to not use mobile data at all.

**Comment by matkoniecz** [comment]
It also depend on whatever user requests  additional quests manually or is it processing all downloaded quests before downloading more.

But overall data usage is low, I would estimate it to be around 1MB/h for walking around (with massive differences depending on factors that I mentioned).

**Comment by DaCor1** [comment]
Thank you for those details. I'm aware of the prep you can do before going
out into the field but the folks who will be using this will likely not
have wifi at all, so I'm looking at worst case. Where its (wifi) available,
I'll be encouraging them to use it

On Mon, Feb 12, 2018 at 5:05 PM, Mateusz Konieczny <notifications@github.com

**Comment by westnordost** [comment]
Can't give an estimate, I never tested it out. As @matkoniecz said, it also depends. But you are free to post your results here, so we can have an estimate in the future.

I can tell you that uploading quest answers is very light on data, I would say around 300B per answer (and around 1kB if there is a conflict). Of course, if you leave notes with attached pictures, this is a different story, that would be around 300kB per photo.

**Comment by westnordost** [comment]
By the way, where would that be? Without Wi-Fi and high data cost?

**Comment by DaCor1** [comment]
I'm currently in Lesotho with the MapLesotho project. We've mapped the
country using aerial imagery over the last 4 years and are now looking on
expanding the gathered data with field surveys. Trying to identify the best
tools to use. We're currently looking at Mapillary (where data is
available) Field Papers and StreetComplete and OSMTracker.

We're putting together some material for additional quests that would see
us using StreetComplete more than either of the other tools if implemented.
These are mainly to do with the composition of buildings (usage and
construction materials) but I'll save details on those for the pull
requests.

btw, loving the app. I was waiting years for something like this

**Comment by westnordost** [comment]
Wow, that sounds cool! 

Are you aware of POSM (=portable OSM)? See ticket #30.

**Comment by DaCor1** [comment]
I'm looking at one right now :)

**Comment by matkoniecz** [comment]
To expand on

> density of OSM data in this area

StreetComplete runs an overpass query, with a very small request and response depending on how many quests may be created. For example, for "add surface" quest - for city with fully mapped surface or forest without roads response will contain no elements so it will be tiny.

For place with hundreds of roads with unpaved surface StreetComplete will get reply describing road for every quest, so data usage will be higher.

Similar thing happens with map tiles - in remote places tiles may be empty, in well mapped city center each map tile may have significant amount of data.

So doing exactly the same (loading map and running scan for the same quests) in two different places may give wildly different results.

I never tested it but I expect data usage to be dominated by downloading map data, followed by usage during downloading quests and tiny usage for uploading answers (assuming that photo uploading feature is not heavily used).

#122 is also related to this issue

**Comment by DaCor1** [comment]
I asked one of the team who has his data monitored (work phone) and he said
that it's less data than apps that run in the background which do periodic
updates so it definitely looks to be manageable but you make a good point.

I can account for it in the instructions that I'm working on for the team.
Hopefully that should mitigate against any major issues.

I will, however, ask him to run an extreme set of quest requests and
navigate through a significant amount of areas just to put some numbers
around it.

I'll report back and let you know, for future reference

Thank you

**Comment by matkoniecz** [comment]
For worst case scenario you may try some major, well mapped city (highest data density).

**Comment by westnordost** [comment]
So, I am going to close this issue as the question asked was answered as far as we can provide the answer. But still you are invited to post any of your findings here to know that for the future! :-)
