### ISSUE TITLE
Quest for advertising type

### ISSUE THREAD

**Issue by rugk** [westnordost/StreetComplete#865]
### General
Affected key(s) (or tags) to be modified: [Key:advertising](https://wiki.openstreetmap.org/wiki/Key:advertising)
Question asked: **What kind of advertising is this here?**

### Checklist
Checklist for quest suggestions (see guidelines):
- [x] 🚧 To be added tag is established and has a useful purpose, see http://projets.pavie.info/openadvertmap/
  Rendering is also explained at https://wiki.openstreetmap.org/wiki/Advertising_devices_examples and https://wiki.openstreetmap.org/wiki/Key:advertising#Rendering.
- [x] 🤔 Any answer the user can give must have an equivalent tagging (Quest should not reappear to other users when solved by one)
- [x] 🐿️ Easily answerable by everyone from the outside but a survey is necessary 
- [x] 💤 Not an overwhelming percentage of elements have the same answer (No spam)
- [x] 🕓 Applies to a reasonable number of elements (Worth the effort)

### Ideas for implementation

**Element selection:** `man_made=advertising` with `advertising=no` or yes or so set

**Metadata needed:** no

**Proposed GUI:** picture selection

**Comment by rugk** [comment]
But well… maybe not. While writing this I noticed we may have not so many elements there, so mhh… never know. I'll let someone else decide… 😄

**Comment by rugk** [comment]
BTW, @goldfndr, are you the one who can change the taginfo.json for openadvertmap? Because it is wrong: It does not use the non-existent "Key:advertisment" (only), but the real `Key:advertising`.

(Off-topic, but I choose this issue at least as it is related.)

**Comment by matkoniecz** [comment]
Less than 126 elements worldwide - http://overpass-turbo.eu/s/Jw0

**Comment by westnordost** [comment]
You are right, this is not worth it. I'll close this issue, but a PR that implements it would be OK by me.
