### ISSUE TITLE
Don't show opening_hours quest for sport_centre which belongs to a school

### ISSUE THREAD

**Issue by ENT8R** [westnordost/StreetComplete#868]
I encountered some notes at a gym of a school which typically has no opening hours...
My proposal is to add `!(leisure=sports_centre and building=school)` somewhere in the query.
What do you think?

**Comment by matkoniecz** [comment]
Can you link examples of objects? For me it sounds like either missing or missing access=private.

**Comment by ENT8R** [comment]
https://www.openstreetmap.org/note/1300146 which links to https://www.openstreetmap.org/way/99511882
Probably it should be `access=private`... But the opening hours quest doesn't exclude them yet... Maybe this should be the real enhancement as I've found some other buildings/shops within private ground of e.g. a police academy...

**Comment by matkoniecz** [comment]
I would exclude access=private like done in #769
