### ISSUE TITLE
Quest density heatmap

### ISSUE THREAD

**Issue by lenod** [westnordost/StreetComplete#869]
First, I'd like to say that StreetComplete is a great way to encourage people to have a walk! And in addition to this major public health benefit, it helps to contribute to OSM, as a side effect ;-)

My point is: once I've contributed all around the places I go everyday (work, home, etc.), I want to choose a place where I can contribute the most using StreetComplete. For this, I guess the best tool would be to have a heat map of quests per square meter.

This could be integrated at the android app, or provided as a service on a separate webpage.
The in-app solution would allow users to change their direction while using the app and not plan this in advance, although one could argue that this could complicate the interface a bit.

**Comment by rugk** [comment]
So maybe you want an arrow at the border of the map pointing to a new quest? That would be https://github.com/westnordost/StreetComplete/issues/642.

As for your suggestion, mhh… If Mapzen would be great one would just have to zoom out in the app to see such a thing (see https://github.com/westnordost/StreetComplete/issues/179, where it was proposed and why it cannot be done).
As for a standalone website… yeah possibly. Note that you can already click on [the overpass queries in the wiki](https://wiki.openstreetmap.org/wiki/StreetComplete/Quests) and have such a view, but per quest type.

And BTW in-app solutions are quite difficult, as the app would have to download all quests for a larger area… this can take very long. 😉

**Comment by westnordost** [comment]
This is not really doable technically.
