### ISSUE TITLE
Only see map when connected

### ISSUE THREAD

**Issue by DamienCassou** [westnordost/StreetComplete#872]
When having an internet connection, I can always see maps and quests. However, I don't have mobile internet access, only wifi. When going out, the maps quickly disappear and I only see quests making StreetComplete unusable. I pushed the "Map cache size" value to its maximum but haven't seen any difference.

**Comment by DamienCassou** [comment]
Allow me to add that I tried to populate the map cache by navigating the whole city while connected. This had no visible effect.

**Comment by westnordost** [comment]
StreetComplete does not have any control over which tiles are cached and which are not. Note that for each different zoom level, there are different tiles. So, if you navigated the city in a certain zoom level, then only for that zoom level, the app will have downloaded the tiles.

It is technically possible to have a more complex cache which would work like storing the downloaded tiles in a local MBTiles sqlite database. That could be implemented in the frame of enabling offline maps, however, anything implementation efforts regarding the map display is currently frozen until the future of the map rendering library that StreetComplete uses is more clear.
