### ISSUE TITLE
General Fee Quest

### ISSUE THREAD

**Issue by ServusWorld** [westnordost/StreetComplete#873]
### General
_Currently, there are quests to complete whether there is a fee for toilets or a car parks.
But there are many other OSM objects where the `fee` tag could be used._

Affected key(s) (or tags) to be modified: [fee](https://wiki.openstreetmap.org/wiki/Key:fee)
Question asked: **Does it cost something to use this [object type]?**

### Checklist
Checklist for quest suggestions (see guidelines):
- [x] 🚧 To be added tag is established and has a useful purpose
- [x] 🤔 Any answer the user can give must have an equivalent tagging (Quest should not reappear to other users when solved by one)
- [x] 🐿️ Easily answerable by everyone from the outside but a survey is necessary 
- [x] 💤 Not an overwhelming percentage of elements have the same answer (No spam)
- [x] 🕓 Applies to a reasonable number of elements (Worth the effort)

### Ideas for implementation
**Element selection:** (see list of objects below) with `[!fee]`

**Metadata needed:** Not necessarily, but maybe some objects could be disabled in some countries if there is a strong tendency for things to be (not) free so that it is obsolete to ask it

**Proposed GUI:** Simply a yes/no form as it already exists for the 2 current fee quests.

### (Incomplete) List of POIs possibly with fee:
- Museums: `tourism=museum`
- Attractions: `tourism=attraction`
- Theme parks: `tourism=theme_park` (could be "no" if it is to be paid at the particular attractions)
- Galleries: `tourism=gallery`
- Viewpoints: `tourism=viewpoint`
- Public gardens: `leisure=garden`
- Beach resorts: `leisure=beach_resort`
- Charging stations: `amenity=charging_station`
- Newspaper vending "machines": `[amenity=vending_machine][vending=newspapers]`
- Charging stations (for mobile phones etc.): `amenity=device_charging_station`
- and of course `amenity=toilets` and `amenity=parking`

**Comment by rugk** [comment]
> As an icons, how about just a wad of money?

Just FYI: That is even already designed.

And generally, please always fill out the issue template when suggesting a new quest.

**Comment by HolgerJeromin** [comment]
> leisure=pitch, leisure=playground, tourism=viewpoint

There are probably too many without fee.

**Comment by ServusWorld** [comment]
You're right. I will remove them from the list

**Comment by CloCkWeRX** [comment]
Its a pity device_charging_station isn't too widespread, that'd be a pretty useful thing to know when travelling

**Comment by ServusWorld** [comment]
That's true. I will add it.

**Comment by RubenKelevra** [comment]
I've added an additional ticket for charging fees on charge stations. This is pretty more difficult than yes or no, which I explain in this ticket, so it might be worth a discussion with the community before adding this to SC, to be able to add additional information per plug type or similar, before flooding the database with not-that-accurate-informations. 

https://github.com/westnordost/StreetComplete/issues/904

**Comment by matkoniecz** [comment]
>    Museums: tourism=museum

I expect fee=yes spam. At least in my city 98%+ are paid (some have free days, but it is not appearing common enough across the world to make quest for it).

>    Attractions: tourism=attraction

tourism=attraction is qualifier of other objects and in case of atypical objects (field/rock/railway tracks/bridge etc) tourism attractions are almost always unpaid ones.

>    Theme parks: tourism=theme_park (could be "no" if it is to be paid at the particular attractions)

I would still describe "if it is to be paid at the particular attractions" to be paid.

>    Viewpoints: tourism=viewpoint

In Poland it would be fee=no spam.

>    Public gardens: leisure=garden

Maybe, would require special answer for "it is a private garden" so it requires separate special quest.

>    Newspaper vending "machines": [amenity=vending_machine][vending=newspapers]

There are free ones?

>    Charging stations (for mobile phones etc.): amenity=device_charging_station

Only 97 uses across the entire world, not worth time to make a quest - https://taginfo.openstreetmap.org//search?q=amenity%3Ddevice_charging_station

>    and of course amenity=toilets and amenity=parking

Makes sense, quests exist already.

**Comment by westnordost** [comment]
So, uh, is there anything left where it makes sense to ask?

**Comment by matkoniecz** [comment]
tourism=gallery, leisure=garden and leisure=beach_resort are not appearing in my list, these may or may not make sense - I have no significant experience with this kind of objects

**Comment by rugk** [comment]
> tourism=museum[...] At least in my city 98%+ are paid

Depends on the city. AFAIK in London all public museums are free.

**Comment by rugk** [comment]
`tourism=gallery` is the same as museum, IMHO.

**Comment by matkoniecz** [comment]
> Depends on the city. AFAIK in London all public museums are free.

Interesting. So quest may be spammy in a given region (fee=yes spam in Poland, fee=no spam in UK...) but overall information is useful. I wonder how @westnordost feels about this situation in context of "no spam guideline".

**Comment by rugk** [comment]
In the UK (or, at least London) I think you may still have private museums, but I am not sure about that.

**Comment by matkoniecz** [comment]
Thanks  a further research now I can say that asking about fee makes sense for museums and I withdraw my negative opinion.

I also plan on making "does it cost a fee to visit xyz" PR for museums (after fixing issues in my construction PR).

**Comment by rugk** [comment]
And for the museum we already have an icon (for https://github.com/westnordost/StreetComplete/issues/890), so only a small coin etc. on the icon may be needed to have a good icon for it.

**Comment by matkoniecz** [comment]
leisure=beach_resort has fee tag in 10% of cases ( https://taginfo.openstreetmap.org/tags/leisure=beach_resort#overview http://overpass-turbo.eu/s/xdk ), description on wiki has "Entry may also require payment of a fee". For simplicity I would ask only if object has a name (only 757 is currently without name - http://overpass-turbo.eu/s/xdl ).

**Comment by matkoniecz** [comment]
Note that of 4400 tourism=gallery only 44 has currently fee tag ( http://overpass-turbo.eu/s/xdm https://taginfo.openstreetmap.org/tags/tourism=gallery ).

**Comment by matkoniecz** [comment]
Vast majority of gardens has no fee tag.

Overall I propose to add quests for tourism=museum, leisure=beach_resort and maybe for tourism=gallery. Some generic coin icon would be useful.

**Comment by rugk** [comment]
The icon is already there for the parking fee quest.

**Comment by matkoniecz** [comment]
I implemented this and promptly discovered that at least in my city nearly all tourism=gallery are actually art shops.

Supposedly this is mistagging so it should be fine. Also, adding fee tag may help in finding mistagged `shop=art` (at least in Poland `tourism=gallery fee=yes` is not going to be art shop, `tourism=gallery fee=no` is quite likely to be mistagged art shop).
