### ISSUE TITLE
"Not accessible" as other answer

### ISSUE THREAD

**Issue by ServusWorld** [westnordost/StreetComplete#874]
It may happen while StreetCompleting that a query can not be answered (or doesn't make sense to be answered) because the affected object is not publicly accessible and this hasn't been tagged yet.

Therefore, an option like "Not accessibly" could be added to _Other answers_ for all quests.

If the user selects this option, a window could open asking him, whether accessing the object is completely restricted (`access=no`) or only for customers (`access=customers`).
StreetComplete then adds the corresponding tag.

**Comment by HolgerJeromin** [comment]
You always can add an OSM Note. ref #870

**Comment by ServusWorld** [comment]
Yes, of course.
But this would be a more elegant solution, although maybe a lot of work to implement ...
If a note is created, another mapper has to see about it. If StreetComplete changes it directly, it's done and the quest does not show up anymore for other users.

**Comment by westnordost** [comment]
I think I rather not have this in the app. Some reasons:
* I am not sure if it desirable to tag every thing within a private area as private (i.e. think of a military base). But on the other hand, checking for every POI whether it is within a private area is computationally too expensive (for SC). 
* Implementing this for any quest would mean that I need to be sure that this is an answer that makes sense for any kind of element (mentioned in a quest). I wouldn't want to take away this decision from the quest-maker
* "Not accessible" for a surveyor does not necessarily mean that it is private or that the access is really restricted to the public. It could be misunderstood as "I can't access this". (I.e. quest asks something about a tunnel that has no pedestrian way and thus he cannot answer this question without walking on the road)
* Only a tiny part of any element will be private, so it's somewhat of an uncommon answer and thus I don't think it justifies the amount of thought and work that would need to go into this to implement it correctly
