### ISSUE TITLE
Step count quest

### ISSUE THREAD

**Issue by ServusWorld** [westnordost/StreetComplete#875]
### General
Affected key(s) (or tags) to be modified: [step_count](https://wiki.openstreetmap.org/wiki/Key:step_count)
Question asked: **How many steps does this stair have?**

### Checklist
Checklist for quest suggestions (see guidelines):
- [x] 🚧 To be added tag is established and has a useful purpose > _For (wheelchair) routing, [OSM for the blind](https://wiki.openstreetmap.org/wiki/OSM_for_the_blind) and maybe even 3D renderings
- [x] 🤔 Any answer the user can give must have an equivalent tagging (Quest should not reappear to other users when solved by one) > _Yes_
- [x] 🐿️ Easily answerable by everyone from the outside but a survey is necessary > _Yeah, it's easy to count steps_
- [x] 💤 Not an overwhelming percentage of elements have the same answer (No spam) > _No, the number of steps differs for sure :D_
- [x] 🕓 Applies to a reasonable number of elements (Worth the effort) > _The cities are full of stairways_

### Ideas for implementation
**Element selection:** [see this overpass-turbo query](
### General
Affected key(s) (or tags) to be modified: [step_count](https://wiki.openstreetmap.org/wiki/Key:step_count)
Question asked: **How many steps does this stair have?**

### Checklist
Checklist for quest suggestions (see guidelines):
- [x] 🚧 To be added tag is established and has a useful purpose > _For (wheelchair) routing, [OSM for the blind](https://wiki.openstreetmap.org/wiki/OSM_for_the_blind) and maybe even 3D renderings
- [x] 🤔 Any answer the user can give must have an equivalent tagging (Quest should not reappear to other users when solved by one) > _Yes_
- [x] 🐿️ Easily answerable by everyone from the outside but a survey is necessary > _Yeah, it's easy to count steps_
- [x] 💤 Not an overwhelming percentage of elements have the same answer (No spam) > _No, the number of steps differs for sure :D_
- [x] 🕓 Applies to a reasonable number of elements (Worth the effort) > _The cities are full of stairways_

### Ideas for implementation
**Element selection:** [see this overpass-turbo query](http://overpass-turbo.eu/s/wgp)

**Metadata needed:** I can't think of any

**Proposed GUI:** Doesn't require more than an integer input. Like the maxspeed quest, just without the traffic sign around.

**Other answers:** 
- **It's a moving stairway** ➡️ adds `conveying=yes`

**Comment by ENT8R** [comment]
Related with #503

---

Speaking from my point of view, I would say that for steps with a huge amount of steps, it can be pretty annoying to count all steps and maybe even lead to put in fake or guessed data...

**Comment by ServusWorld** [comment]
I hope that users disable a quest if they think it is to annoying to complete ...

**Comment by ENT8R** [comment]
This should be the normal case, but I think that we can't expect the user to do this... There are maybe even users who don't know at all how to disable a quest. And there might be people who see this app as a game and the one who answers the most questions "wins" :smile:

**Comment by matkoniecz** [comment]
Is there method to query on overpass ways by length? From #503 it seems that this data may have some use mostly for very short steps.

**Comment by westnordost** [comment]
Hmm, I am going to mark it as quest, but the discussion in #503 should be kept in mind before thinking about implementing this quest.

**Comment by rugk** [comment]
>  but I think that we can't expect the user to do this...

Then make it opt-in.

**Comment by RubenKelevra** [comment]
Maybe point out that the amount of steps should just be input if the step is straight, and not tilted on one side, leading to an uneven amount of steps over the width of the steps and also just insert the exact count of steps. :)

**Comment by westnordost** [comment]
I find this is not a blocker. By the way, even if it were, StreetComplete could still query simply all steps and filter out by measuring the length of the ways itself.

**Comment by RubenKelevra** [comment]
Speaking of living in a City with an overwhelming amount of extreme long steps, I wouldn't hesitate to just walk them in one direction just counting the steps. Why not. :)

**Comment by westnordost** [comment]
Istanbul?

**Comment by ServusWorld** [comment]
Yes, that's true.
That the user should rather skip a quest instead of completing it messily is a topic not only affecting this quest
But maybe there could be a note like "plaease enter the exact number of steps" but it shouldn't make the whole quest impossible ...

**Comment by matkoniecz** [comment]
See https://github.com/drolbr/Overpass-API/issues/464#issuecomment-370218992 - in future it will be possible to filter ways by their length.

**Comment by rugk** [comment]
Still think a length filter is not necessary for this quest. IMHO the longer the steps are the more usefulness has the data added in the quest in general. It might be more important to know how much steps you need for a big than a short step. (except of very short steps, where this information is useful for wheelchair users etc.)

**Comment by HolgerJeromin** [comment]
Did I miss an issue about adding the direction of steps? Which side is the "up" direction?
https://wiki.openstreetmap.org/wiki/Key:incline
> Most occurrences of this tag are on steps (highway=steps), usually tagged with incline=up or incline=down.

Should I open a new issue?

**Comment by matkoniecz** [comment]
> Should I open a new issue?

Probably yes - seems to be not covered so far https://github.com/westnordost/StreetComplete/search?q=incline&type=Issues

At least as long as it fulfills requirements for quests, but it should not be a problem.

**Comment by sun-geo** [comment]
app/src/main/res/values/strings.xml:
typo in: "<string name="quest_step_count_title">How **may** steps are here?</string>"
=>many

**Comment by westnordost** [comment]
corrected, thanks!
