### ISSUE TITLE
Map: Smaller visual bugs

### ISSUE THREAD

**Issue by ServusWorld** [westnordost/StreetComplete#877]
I've seen two thinks looking strange in the new map style (although the new map style is excellent apart from that):

## Street names overlie a 3D building if they are behind it
See this screenshot to understand. But it's not actually grave ...
![street_behind_3d_building](https://user-images.githubusercontent.com/31391499/36355142-31c81216-14df-11e8-9c79-26d18e4525c1.png)

## Location marker is sometimes below the street
![location_below_street](https://user-images.githubusercontent.com/31391499/36355144-60169b9c-14df-11e8-8909-28cd4209fd22.png)

**Comment by ENT8R** [comment]
Please report all your issues at the repository which was made for maintaining this stylesheet: https://github.com/ENT8R/streetcomplete-mapstyle

**Comment by ServusWorld** [comment]
Okay thanks.
