### ISSUE TITLE
Prioritize issues (quest suggestions) with GitHub's project boards

### ISSUE THREAD

**Issue by rugk** [westnordost/StreetComplete#878]
In https://github.com/westnordost/StreetComplete/issues/503#issuecomment-323523685 @westnordost said:
> There is no way in the github issue tracker to properly prioritise these things,

I'd say we now have a way. You can use [GitHub's kanban-like board](https://github.com/westnordost/StreetComplete/projects) here. 

Either you make different columns for prios or just the usual kanban style (backlog, todo, done, ...) and then order it from top to bottom.

Or sort them in a different way...

Also it would give contributors an overview of what is needed/what quests they may have a look at, etc.

**Comment by matkoniecz** [comment]
> There is no way in the github issue tracker to properly prioritise these things

What about marking priority by labels? For example Vespucci is using this scheme - see https://github.com/MarcusWolschon/osmeditor4android/issues?q=is%3Aissue+is%3Aopen+label%3A%22Low+Priority%22 or https://github.com/MarcusWolschon/osmeditor4android/issues?q=is%3Aissue+is%3Aopen+label%3A%22High+Priority%22

**Comment by rugk** [comment]
Yeah, that's another idea, but you cannot prioritize each item there, you more or less group them. So it depends how fine-graned we'd want it.

**Comment by westnordost** [comment]
Hmm, not sure about it. I will experiment a bit with it.

**Comment by westnordost** [comment]
I tried it out. I am not convinced that this will actually be a time saving for me.
