### ISSUE TITLE
Credits reference non-existent translator list

### ISSUE THREAD

**Issue by huftis** [westnordost/StreetComplete#882]
The ‘Credits’ page in the app lists several translators, and ends with the following text.

> See the [project on POEditor](https://poeditor.com/projects/view?id=97843) for a complete list.

However, that page has no publicly available list of translators. And even if one logs in as a translator, the ‘Contributors’ link that appears only shows ‘There are no contributors assigned to the project(s) you own or administrate.’. So it looks like the list of translators is only available to the owner of the StreetComplete project at the POEditor site.

So I guess the list of translators should be updated (its currently outdated) and the link dropped. Or perhaps the link could stay but text changed to say that people could visit the project on POEditor if they want to *contribute* a translation.

**Comment by ENT8R** [comment]
This is a duplicate of #629
The feature has been forwarded to the developers of POEditor (https://poeditor.uservoice.com/forums/171919-general/suggestions/31242085-public-url-to-view-project-contributors) and you can vote there to show that you want to have this kind of feature!

**Comment by huftis** [comment]
Sorry for the duplicate (it didn’t show up when I searched for ‘translation’ – I should have used ‘translator’ instead). I’ll close this issue.

**Comment by westnordost** [comment]
I update the list of translators about every major release. Don't worry, you will be included ;-)
