### ISSUE TITLE
Clarify vegetarian and vegan strings

### ISSUE THREAD

**Issue by huftis** [westnordost/StreetComplete#883]
The two strings clarifying what ‘vegetarian meals’ and ‘vegan meals’ are currently says:

> Vegetarian meals contain no meat.
> Vegan meals contain no animal products (no meat, no milk products, no eggs, …).

It’s a common misunderstanding, especially in some countries, that vegetarians eat fish (or even chicken!). So could this be changed to

> Vegetarian meals contain no meat, fish, or poultry.
> Vegan meals contain no animal products (no meat, fish, poultry, milk products, eggs, …).

?

I can create a PR if you approve this change.

**Comment by westnordost** [comment]
Okay

**Comment by huftis** [comment]
BTW, @westnordost, the comma before ‘or’ was not a typo. It was the serial comma, which most style guides for *American English* recommend: https://en.wikipedia.org/wiki/Serial_comma

Since the (de facto) default variant of English in free software is American English (with British English commonly provided as a ‘translation’), I used the serial comma. For British English, I would have omitted it.

(BTW, there are also a couple of other ‘britishisms’ and spelling inconsistencies in the strings.xml file.)

**Comment by rugk** [comment]
Yes, AFAIK these are mostly wanted, as OSM uses British English. No 'Americanism' here… :wink:

**Comment by rugk** [comment]
However, one may surely make a en_US translation at POEditor if that is possible. If not, open an issue, … :smile:

**Comment by huftis** [comment]
@rugk I would guess that the default should be the *Android* default, which might differ from the *OSM* default. However, Android doesn’t seem to have a default language (https://developer.android.com/guide/topics/resources/multilingual-support.html).

But even with British English as the default for StreetComplete, there are still inconsistencies, e.g. ‘practised’ but ‘authorized’. (And the quotation marks for placeholders should be ‘ and ’, not “ and ”.) But all this it OT for this issue, so I‘ll add a separate issue (not tonight, probably tomorrow).

**Comment by westnordost** [comment]
Ah, I did not know this.

Probably, it would be good to create an en_US strings.xml which overrides some of the strings in the default strings.xml and let the default strings.xml be British English all through. (Or the other way round, I don't really care). But anyway, that's a separate issue.

To go forward with this one, you could create a PR where you remove all the quotation marks from the quest titles. I will then contribute to that PR to implement to make it italic or something.

**Comment by westnordost** [comment]
Oh, this is the vegetarian issue, nevermind.
