### ISSUE TITLE
Remove buildings from AddHousenumber if addressed entrance exists

### ISSUE THREAD

**Issue by britiger** [westnordost/StreetComplete#885]
It would be helpful to remove buildings from AddHousenumber-Quest if the buildung already have several addresses as Nodes on the way of the Building. Mostly they are mapped as entrance=* with complete addr:*=* Some buildings have doors to different streets with different names of the streets. If you have blocks of flats, sometime with entrance on backside or anywhere else it is usefull to put the address not on the complete building.
Sample: https://www.openstreetmap.org/way/48916730

**Comment by westnordost** [comment]
This is already the case since the quest was first implemented.

**Comment by britiger** [comment]
Here was added a housenumber: https://www.openstreetmap.org/changeset/56437830
The entrance-Node exists since 7 Month: https://www.openstreetmap.org/node/4163739078

**Comment by westnordost** [comment]
Hmm, I cannot explain why this wasn't excluded then. I will investigate.

**Comment by westnordost** [comment]
For the initial building you linked, the quest does not show up. It would be a great help to reproduce this issue if someone could find an example where the quest shows up.

**Comment by DeusFigendi** [comment]
I'm just guessing, but maybe the problem is, that the [entrace-node](https://www.openstreetmap.org/node/4163739078) is not ony part of the [building](https://www.openstreetmap.org/way/28249453) but also of the [parking lot in the east](https://www.openstreetmap.org/way/398655482).

**Comment by westnordost** [comment]
That should not be a problem. StreetComplete does a point-in-polygon (or outline) check.

**Comment by westnordost** [comment]
So I removed the address information from the building to reproduce this issue, but I can't reproduce it. The housenumber quest does not show for that building.

**Comment by britiger** [comment]
I've found a example in my 4.0 beta2
: 
Have a quest for: https://www.openstreetmap.org/way/26242308
This one of the addresses of the building: https://www.openstreetmap.org/node/3661893704
![photo_2018-02-21_17-18-59](https://user-images.githubusercontent.com/2057760/36491577-5b463d7c-172b-11e8-90d1-280a796aaf1e.jpg)

**Comment by matkoniecz** [comment]
>  This one of the addresses node within the building polygon: https://www.openstreetmap.org/node/3661893704

It may or may not be related but I opened this are in edit mode and this building is invisible in iD, but it appears in current overpass querries - see http://overpass-turbo.eu/s/wmM

Maybe it is viable to blame it on a database corruption that occurred as you fetched quests, and that it is an overpass bug - not a SC bug?

**Comment by westnordost** [comment]
It isn't invisible for me in iD. 

![id-invis](https://user-images.githubusercontent.com/4661658/36494753-5288f91a-1733-11e8-9e2b-cbc73b741682.jpg)

But with my StreetComplete installation (v4.0-beta2), I can not reproduce it. The quest is not shown:

![device-2018-02-21-181737](https://user-images.githubusercontent.com/4661658/36494825-89b1b116-1733-11e8-8dab-106caa35420c.png)

**Comment by matkoniecz** [comment]
> It isn't invisible for me in iD.

Now it is OK also for me.

**Comment by britiger** [comment]
I only had the building I mentioned as quest. After reload quests in this area I now have the two building of your screenshot. May it was some cached data, how long does the app hold data in cache? I've reloaded the data in an area in Potsdam before I took the screenshot. But using the history of both objects I've seen that the building including the node within the building was added in 2015. You have mentioned that the check exists in first implementation. Very curious bug.

**Comment by britiger** [comment]
Now I've found a second building nearby: https://www.openstreetmap.org/way/397490707
Address: https://www.openstreetmap.org/way/397490707 both created 2016.

After searching for new quests it's also gone away like the first building. So I think it is a problem with my cache. But I can reproduce the error:
 - I remove cache, all data and settings for the application 
 - Login again with my osm user
 - Setting only quest with addresses
 - I moved to https://www.openstreetmap.org/way/26242308 loading quests in this area
   - Only see the two buildings of your screenshot => OK
 - Now moving to https://www.openstreetmap.org/way/397490707
    - the quest for this building is visible after a while without loading data (maybe automatic load)
 - After loading new quests the quest was removed

**Comment by westnordost** [comment]
> the quest for this building is visible after a while without loading data (maybe automatic load)

I don't understand. How can the quest for the building be visible after you cleared all data for the application but before loading new quests is finished?

**Comment by britiger** [comment]
I've checked it on a second device with fresh installed app and on the first again. 
Here the steps in short:
 - goto https://www.openstreetmap.org/way/26242308
 - invalid quest cache
 - automatic load of quests
 - at https://www.openstreetmap.org/way/397490707  no quest found
 - load quests at https://www.openstreetmap.org/way/26242308
 - at https://www.openstreetmap.org/way/397490707  quest found
 - reload quest at https://www.openstreetmap.org/way/397490707 
   - quest will be removed

I've take screenrecord: https://youtu.be/9ZEcZUiZCdY

I also used Android Studio to capture some logs while verify the behaviour on second device: 
 - load at 26242308 (added wrong quest)
 - 2nd load at 397490707 (remove wrong quest):
```
02-21 21:08:56.156 15736-16671/de.westnordost.streetcomplete I/QuestDownload: (13.0517578125,52.36218321674426,13.07373046875,52.40241887397332) Starting
02-21 21:08:56.708 15736-16671/de.westnordost.streetcomplete I/QuestDownload: Successfully added 0 new and removed 0 closed notes (0 of 0 notes are hidden)
02-21 21:09:01.403 15736-16671/de.westnordost.streetcomplete I/QuestDownload: AddRoadName: Added 0 new and removed 0 already resolved quests. (Total: 0) in 4607ms
02-21 21:09:16.198 15736-16671/de.westnordost.streetcomplete I/QuestDownload: AddHousenumber: Added 1 new and removed 0 already resolved quests. (Total: 1) in 14695ms
02-21 21:09:23.494 15736-16671/de.westnordost.streetcomplete I/QuestDownload: AddRecyclingType: Added 0 new and removed 0 already resolved quests. (Total: 0) in 7220ms
02-21 21:09:29.423 15736-16671/de.westnordost.streetcomplete I/QuestDownload: AddRoadSurface: Added 0 new and removed 0 already resolved quests. (Total: 0) in 5838ms
02-21 21:09:29.460 15736-16671/de.westnordost.streetcomplete I/QuestDownload: (13.0517578125,52.36218321674426,13.07373046875,52.40241887397332) Finished
02-21 21:09:40.855 15736-16671/de.westnordost.streetcomplete I/QuestDownload: (13.0517578125,52.36218321674426,13.095703125,52.38901106223455) Starting
02-21 21:09:41.388 15736-16671/de.westnordost.streetcomplete I/QuestDownload: Successfully added 0 new and removed 6 closed notes (6 of 6 notes are hidden)
02-21 21:09:47.018 15736-16671/de.westnordost.streetcomplete I/QuestDownload: AddRoadName: Added 0 new and removed 0 already resolved quests. (Total: 0) in 5568ms
02-21 21:10:08.556 15736-15747/de.westnordost.streetcomplete I/art: Background sticky concurrent mark sweep GC freed 100042(3MB) AllocSpace objects, 0(0B) LOS objects, 23% free, 9MB/12MB, paused 752us total 111.490ms
02-21 21:10:08.874 15736-15747/de.westnordost.streetcomplete I/art: Background partial concurrent mark sweep GC freed 145441(4MB) AllocSpace objects, 6(3MB) LOS objects, 43% free, 5MB/9MB, paused 1.248ms total 109.597ms
02-21 21:10:11.423 15736-16671/de.westnordost.streetcomplete I/QuestDownload: AddHousenumber: Added 0 new and removed 1 already resolved quests. (Total: 0) in 24285ms
02-21 21:10:14.567 15736-16671/de.westnordost.streetcomplete I/QuestDownload: AddRecyclingType: Added 0 new and removed 0 already resolved quests. (Total: 0) in 3094ms
02-21 21:10:18.961 15736-16671/de.westnordost.streetcomplete I/QuestDownload: AddRoadSurface: Added 0 new and removed 0 already resolved quests. (Total: 0) in 4290ms
02-21 21:10:19.001 15736-16671/de.westnordost.streetcomplete I/QuestDownload: (13.0517578125,52.36218321674426,13.095703125,52.38901106223455) Finished
```

**Comment by rugk** [comment]
https://www.youtube.com/watch?v=9ZEcZUiZCdY&feature=youtu.be has been deleted, because it violates YouTube's TOS. 🙄 Try https://streamable.com/ if the video is short enough.

**Comment by britiger** [comment]
I don't know why I was block but now I uploaded it here: https://streamable.com/hvonc

**Comment by westnordost** [comment]
I've got it

**Comment by westnordost** [comment]
![building1](https://user-images.githubusercontent.com/4661658/36506989-94f0b2be-1758-11e8-8261-877273581ee3.png)

zoomed in...:

![building2](https://user-images.githubusercontent.com/4661658/36506991-9b78af24-1758-11e8-9c6f-420d98009116.png)

**Comment by westnordost** [comment]
Does anyone know if it is possible somehow to filter a result set in Overpass? I.e. to return all nodes of a building that have an `addr:housenumber` tag?

This does not work:

```
[bbox:{{bbox}}];
way[building] > -> .building_nodes;
building_nodes["addr:housenumber"] -> .addr_nodes;
out meta geom;
```

**Comment by westnordost** [comment]
Nevermind, I got it

```
(
  way[building]({{bbox}});
  rel[building]({{bbox}});
) -> .buildings;

.buildings > -> .building_nodes;
node.building_nodes["addr:housenumber"];< -> .buildings_with_addr_nodes;

(.buildings; - .buildings_with_addr_nodes;);

out meta geom;
```

(Returns all buildings that have no address nodes on their outline, even if the address node itself is not inside the bbox)
