### ISSUE TITLE
Update thread when opening Note discussion quest

### ISSUE THREAD

**Issue by ServusWorld** [westnordost/StreetComplete#887]
It can happen that new comments have been posted to a OSM note discussion since StreetComplete has queried for quests the last time - which means: The Note thread can be outdated.
The SC user might answer something that has already been answered. That can be annoying to other mappers.

As a solution, the app could (in background) query again for that certain note after the user has opened a discussion.

**Comment by ServusWorld** [comment]
For example:
User 1: "Place name missing - does somebody know how this is called"
User 2: "It's called Hotel XY" _(StreetComplete doesn't show this yet)_
SC user: "Its name is Hotel XY" _(double-answered)_

**Comment by westnordost** [comment]
Hmm, this does not really convince me. As long as the note isn't closed yet, any comment, even if duplicate, is potentially helpful, if only to confirm the findings of the first person.

**Comment by matkoniecz** [comment]
Yes, independent confirmations are useful.

**Comment by westnordost** [comment]
So, I am going to close this. When a user tries to answer on a note that has already been closed, his answer is automatically discarded. As long as the note is still open, his answer is probably useful.

It is comparable with a forum thread: Often, people answer to the start post without reading through the whole history. In this case, the whole history is not even shown to the user, and I do not see this as such a big problem.
