### ISSUE TITLE
Dashed Cycle Lane tagging

### ISSUE THREAD

**Issue by westnordost** [westnordost/StreetComplete#888]
The app should offer to select dashed cycle lanes as one option in the add cycleway quest (German: Schutzstreifen or Angebotsstreifen).

Currently, there is no tagging scheme for this.

I asked in the Forum to make a decision on this. Anyone reading this here is invited to contribute his opinion and/or arguments to it: https://forum.openstreetmap.org/viewtopic.php?id=61427

**Comment by westnordost** [comment]
Perhaps people who read this here could participate there. I would like to get this topic cleared as soon as possible, so that I can implement the decided on solution quickly.

**Comment by lokaman** [comment]
@westnordost will definitely take the time tomorow to read & participate. Just looked at it yesterday and then whuuups my intention to read through was suddenly gone ^^

**Comment by westnordost** [comment]
I am back from my research and I have a different suggestion now:
https://forum.openstreetmap.org/viewtopic.php?pid=687929#p687929
