### ISSUE TITLE
BlackBerry KeyONE UI problems

### ISSUE THREAD

**Issue by rapadu** [westnordost/StreetComplete#889]
The forms won't show up on a BlackBerry KeyONE. Seems like the display resolution is not right. Selecting pre defined answers is not possible.

Update: Updating to v4.0 slowed the problem

**Comment by ENT8R** [comment]
> Selecting pre defined answers is not possible.

But you can't select predefined answers when the quest form doesn't show up at all, can't you?
And BTW: would it be possible that you take a screenshot and attach it here?

**Comment by ENT8R** [comment]
Could you maybe update SC to the latest version (4.0) and tell here if this issue does still exist?
Because in this version there was a change to the quest container fragment (#881) which might fix your issue...

**Comment by rapadu** [comment]
Case is closed. Updated to v4.0 and works perfectly! 
Thanks!

**Comment by rugk** [comment]
BTW you can close the issue by yourself.
