### ISSUE TITLE
"of these, levels in the roof" - This is confusing

### ISSUE THREAD

**Issue by orblivion** [westnordost/StreetComplete#89]
"How many levels does this building have?" "total levels (inclusive roof)" "of these, levels in the roof"

To me, it's a little odd thinking of the roof as having levels. Maybe it's an American thing. I think of a roof as a flat thing that covers the building. I assume you're talking about a sloped roof that spans multiple levels? I'm having trouble remembering ever seeing a sloped roof ever spanning more than one level.

Also, off-by-one errors: If the roof is flat, is the answer 0 or 1?

I'm really not sure how to answer these quests. Perhaps you could add an explainer somewhere?

**Comment by CloCkWeRX** [comment]
Covered in #94 and #66 a bit I think

**Comment by orblivion** [comment]
It could be covered in a fix to these, we'll see. However, the specific confusion related to the roof was not explicitly mentioned (from what I could tell). It's good to have linked the issues as you did by mentioning them.

**Comment by anttitelio** [comment]
I find the quest very confusing also. Definitely requires rephrasing.

**Comment by peteroupc** [comment]
A better word for "levels" is _stories_ (called _storeys_ at least in European English).

**Comment by westnordost** [comment]
Wikipedia article for [Storey ](https://en.wikipedia.org/wiki/Storey) says: "The words "storey" and "floor" also generally exclude levels of the building that have no roof, even if they are used by people—such as the terrace on the top roof of many buildings."

**Comment by orblivion** [comment]
There's a visual aide for roads. I think this is _fantastic_. If you had something similar for this, it could easily solve the problem.

**Comment by gsurrel** [comment]
I think that using  [this illustration](https://wiki.openstreetmap.org/w/images/thumb/4/47/Building-levels.png/400px-Building-levels.png) would be awesome, asking for number of floors in {A}, {B+C+D} and {E}.

[Reference](https://wiki.openstreetmap.org/wiki/Key:building:levels)

**Comment by westnordost** [comment]
Added an illustration, see #41
