### ISSUE TITLE
BTW: Screenshots

### ISSUE THREAD

**Issue by rugk** [westnordost/StreetComplete#892]
@westnordost Very off-topic, but the easiest way right now to contact you: I saw you also have a video for the new 4.0 version.

You can use Android's [demo mode](https://android.googlesource.com/platform/frameworks/base/+/android-6.0.0_r1/packages/SystemUI/docs/demo_mode.md) to make the navigation bar static and just some some standard values. I've linked to some internal stuff, but you can alps just enable it in the developer options in recent Android versions. It then just shows you "12:15" or so at the time, always.
Then such things look better. Just a not for the next time.

**Comment by westnordost** [comment]
Is it? Well, I also read my email. 
By the way, I just made that really quick. If you think you can create a better video, go ahead :-)

**Comment by rugk** [comment]
Yeah, if I knew your mail out of my mind, sure, but was too hard to quickly find it on the website (nowhere…) or GitHub profile or so. Maybe better so, unless you want too much spam… :wink: 

> If you think you can create a better video, go ahead :-)
No, it's all right, just for the next time.
