### ISSUE TITLE
Google Play Statistics

### ISSUE THREAD

**Issue by westnordost** [westnordost/StreetComplete#894]
I thought I share some statistics with you from Google Play

# By Country

Country | Users | % of Total
-- | -- | --
Germany | 2210 | 36.2%
United States | 627 | 10.3%
France | 454 | 7.4%
United Kingdom | 343 | 5.6%
Italy | 210 | 3.4%
Switzerland | 140 | 2.3%
Czechia | 128 | 2.1%
Spain | 126 | 2.1%
Austria | 113 | 1.8%
Netherlands | 112 | 1.8%
Sweden | 106 | 1.7%
Canada | 100 | 1.6%
Poland | 95 | 1.6%
Russia | 95 | 1.6%
Belgium | 93 | 1.5%
Australia | 86 | 1.4%
Finland | 67 | 1.1%
Myanmar (Burma) | 58 | 0.9%
India | 56 | 0.9%
Denmark | 55 | 0.9%
Turkey | 54 | 0.9%
Brazil | 52 | 0.9%
Norway | 51 | 0.8%
Ireland | 41 | 0.7%
Iran | 39 | 0.6%
Hungary | 32 | 0.5%
Romania | 27 | 0.4%
Argentina | 26 | 0.4%
Lithuania | 24 | 0.4%
Japan | 23 | 0.4%
Portugal | 23 | 0.4%
Slovakia | 23 | 0.4%
Ukraine | 21 | 0.3%
Others | 399 | 6.5%
**Total** | **6109** | **100.0%**

# By Android Version

Android Version | Users | % of Total
-- | -- | --
Android 8.1 | 563 | 9.2%
Android 8.0 | 658 | 10.8%
Android 7.1 | 1176 | 19.3%
Android 7.0 | 1904 | 31.2%
Android 6.0 | 1149 | 18.8%
Android 5.1 | 276 | 4.5%
Android 5.0 | 189 | 3.1%
Android 4.4 | 153 | 2.5%
Android 4.3 | 14 | 0.2%
Android 4.2 | 27 | 0.4%
**All** | **6109** | **100.0%**

**Comment by ENT8R** [comment]
Nice to see that only a relatively small amount of users uses android versions below 5.0 😀

**Comment by lokaman** [comment]
Could be more diverse in the future but it shows that SC is used around the world. Wow! Just looked at some of the notes created by the users and were thrilled to to see South America here. Although notes are not necessarily a good sign ^^

For the future it would be certainly good if some non-german hop into the development and share country specific ideas / knowledge. As this project seems to be growing its work must be divided into more people than I regularly see at github.

**Comment by Etua** [comment]
I wonder how these numbers would look like for F-Droid users.

**Comment by rugk** [comment]
Well... F-Droid does not track their users, so you cannot say that. AFAIK the only thing they can provide is the number of downloads.

**Comment by Akasch** [comment]
Some statistics from the Tileserver:
Counted was the left-top coordinate of each computed tile. So cached and prerendered tiles are not in this statistics. The "doted lines" are from the raster of lower zoom tiles. The data is from nearly the last month.

![figure_4](https://user-images.githubusercontent.com/1304154/36557753-721e8ca0-1809-11e8-8e5a-f86f40c524b7.png)

The Tileserver is mostly used by StreetComplete at the moment.

**Comment by rza31** [comment]
Overview about activity from streetcomplete.
![streetcomplete](https://user-images.githubusercontent.com/12858962/36585750-724925e8-187f-11e8-86b7-b6c48960d7f7.png)
