### ISSUE TITLE
Do not ask for roof:shape if 3dr:type is given

### ISSUE THREAD

**Issue by geowas-github** [westnordost/StreetComplete#896]
Currently StreetComplete asks for entering roof:type even if 3dr:type is given, which is another tagging scheme to describe roofs: https://wiki.openstreetmap.org/wiki/OSM-4D/Roof_table

If people now also enter roof:shape in StreetComplete there is a high risk of breaking carefully designed 3D models.

Example:
http://demo.f4map.com/#lat=51.5462455&lon=7.8126840&zoom=20
![grafik](https://user-images.githubusercontent.com/2790128/36565615-47a17ae2-1821-11e8-8378-ffc0af276ec9.png)

![grafik](https://user-images.githubusercontent.com/2790128/36565418-bafc21dc-1820-11e8-8023-4298d2c573c7.png)

![grafik](https://user-images.githubusercontent.com/2790128/36565465-d58f7724-1820-11e8-9c5f-5135a73af1aa.png)

**Comment by westnordost** [comment]
fair enough

**Comment by goldfndr** [comment]
That Roof_table wiki page includes the following line:

*NOTE: For the correct application of this schema, the building should be marked tag roof:shape=3dr*

I'm not seeing that tag in the screenshot. Is it elsewhere on the building?

**Comment by geowas-github** [comment]
Richard, true, when I modelled the building I mixed things up quite a bit - the building around were my first experiments. And this "roof:shape=3dr" thing I missed completely. 

But: F4map (which I find the best renderer... are there others?) is rendering all these buildings with mixed tagging and tagging maybe not meeting the requirements quit nicely. So I expect there are more buildings with 3dr:type, with and without additional roof:shape=3dr. So it's better to make sure not to spoil things with adding the extra roof information which might say something different. Especially with the more complex buildings I expect that people spent some energy creating the models.

**Comment by westnordost** [comment]
Ok then it is not a bug, I will still implement this though.

**Comment by goldfndr** [comment]
I'm thinking you should probably also add `!3dr:roof` in case someone uses the other tag (as mentioned on the [OSM-4D/3D building page](https://wiki.openstreetmap.org/wiki/OSM-4D/3D_building#Roof)). It certainly looks like both tags are used for the same purpose, and perhaps someone intended to eventually convert the `3dr:type` tags to `3dr:roof` tags (to match the usage of the other 3dr:\* tags).

**Comment by matkoniecz** [comment]
@goldfndr If you think that it should be changed I would recommend opening a new issue (this is fixed and closed, comments may be easily missed).

Note that !3dr:roof is used less than 150 times worldwide: https://taginfo.openstreetmap.org//search?q=3dr%3Aroof
