### ISSUE TITLE
additional details on charging_station - opening_hours

### ISSUE THREAD

**Issue by RubenKelevra** [westnordost/StreetComplete#897]
### General
Affected tag(s) to be modified/added: [opening_hours=*]
Question asked: **"What are the opening hours of this charging station?"**

### Checklist
Checklist for quest suggestions (see guidelines):
- [x] 🚧 To be added tag is established and has a useful purpose
- [x] 🤔 Any answer the user can give must have an equivalent tagging (Quest should not reappear to other users when solved by one)
- [x] 🐿️ Easily answerable by everyone from the outside but a survey is necessary 
- [x] 💤 Not an overwhelming percentage of elements have the same answer (No spam)
- [x] 🕓 Applies to a reasonable number of elements (Worth the effort)

### Ideas for implementation
Same as for shops.

**Element selection:** 
if amenity=charging_stations is present and opening_hours=* not

**Comment by lokaman** [comment]
Do you know charging stations which are not opened 24/7?

**Comment by RubenKelevra** [comment]
Yes. Nearly all charging stations on parking lots are closed after the shop has been closed or an hour after. So, therefore, the charging station has also an opening_hour.

**Comment by matkoniecz** [comment]
It is probably for amenity=charging_station elements, not amenity=charging_station**s**

**Comment by ENT8R** [comment]
But in cities those charging stations are open 24/7 AFAIK and for those objects this quest would be a spam...

**Comment by lokaman** [comment]
1880 of 2159 tagged charging stations with opening hours are 24/7.
Thats are 87%.

I already said that bringing up new quests here is encouraged.
But may ask yourself if you even thought about

"Not an overwhelming percentage of elements have the same answer (No spam)"

But thats probably not possible if you create a new quest every 6 minutes (8 new quest in about 1h).

Quality over quantity?

**Comment by RubenKelevra** [comment]
Well, if you want to talk about spam, tagging all roads manually with surface=asphalt might be considered also as spam, since there's not much use by heaving this information on roads, or am I missing something? 

But mapping an opening hour to a charging station if the information is missing, is spam? Why should this vital information be spam? If the mapper has knowledge while adding this charging station in the first place, he shurly already added an opening_hour, as you have proven. 

> I already said that bringing up new quests here is encouraged.
> But may ask yourself if you even thought about
> 
> But thats probably not possible if you create a new quest every few minutes (8 new quest in about 1h).
> 
> Quality over quantity?
Well as you discovered I sat down more than an hour to think and write just 8 simple tickets, I surely made my thought over the current and future usefulness of the data I propose to be mapped by this and all other tickets I've created.

**Comment by RubenKelevra** [comment]
These are the typical charging facilities which currently pop up like crazy in Germany and many other EU states, which are for destination charging while shopping and sometimes bound to a shop, where you need a card and sometimes are just free. But most of the time they have an opening hour attached to them.

https://www.openstreetmap.org/node/4423663036

Currently only 14% of all charging_station's do have any information at all if they are avaible around the clock or are resticted. So it's speculative to estimate, that mappers add this information if there's a restriction and if not they don't add a tag at all.

**Comment by lokaman** [comment]
@RubenKelevra 

Just keep cool. I dont said all your issues are complete nonsense. I just wonder if you really thought about for example the spam box or just clicked it.

As shown, the vast majority of mapped charging stations are 24/7. There are two options now - we dont implement this or we accept the fact that most will be 24/7 & design the quest with that fact in mind.

by the way, for the surface value: https://taginfo.openstreetmap.org/keys/surface#values
yeah, spam. indeed. i dont see 87% asphalt there.

**Comment by ENT8R** [comment]
> we accept the fact that most will be 24/7 & design the quest with that fact in mind

That's a pretty good compromise 👍
The problem with the current opening hours quest would be that this option is hidden in a submenu...

> since there's not much use by heaving this information on roads, or am I missing something?

The surface value can be used for routing applications to filter out ways with a "bad" surface...

**Comment by RubenKelevra** [comment]
> Just keep cool. I dont said all your issues are complete nonsense. I just wonder if you really thought about for example the spam box or just clicked it.

Yeah, sorry about this, hope you don't take it personally, was a hard week. :)

> by the way, for the surface value: https://taginfo.openstreetmap.org/keys/surface#values
> yeah, spam. indeed. i dont see 87% asphalt there.

@lokaman yep, seen worldwide you're true, but I don't think this is true if you filter for Germany. Indeed the streets like highway=residential were long time considered as always asphalt if not tagged different, but this changed a lot since more less-developed countries started to take off in this project. :)

I think I've tagged maybe a dozen streets with different surfaces since I've been using SC... so yeah, the part of the screen where asphalt is is pretty much worn out. ;)

> > we accept the fact that most will be 24/7 & design the quest with that fact in mind

> That's a pretty good compromise +1

Yep I think too, maybe just a "not taggable", "always useable", "time restricted access" or similar and a submenu for time restricted access with different options like currently for the opening_hour of shops etc?

**Comment by westnordost** [comment]
I am not convinced. I suspect that much more than just 87% of charging stations are 24/7, only they are usually not tagged that way because people assume this as given. (As for i.e. outside-ATMs)

Closing this for now.

**Comment by RubenKelevra** [comment]
@westnordost I've been looking around in Plugshare and the most charging stations in my area do have opening hours, since they are located at shopping malls or supermarkets. I doubt that this is a regional thing. Please consider reopening this ticket, thanks.
