### ISSUE TITLE
additional details on charging_station - parking:fee=yes/no

### ISSUE THREAD

**Issue by RubenKelevra** [westnordost/StreetComplete#898]
### General
Affected tag(s) to be modified/added: [fee=yes/no]
Question asked: **"Do parking for charging at this charging station require a fee?**

### Checklist
Checklist for quest suggestions (see guidelines):
- [x] 🚧 To be added tag is established and has a useful purpose
- [x] 🤔 Any answer the user can give must have an equivalent tagging (Quest should not reappear to other users when solved by one)
- [x] 🐿️ Easily answerable by everyone from the outside but a survey is necessary 
- [x] 💤 Not an overwhelming percentage of elements have the same answer (No spam)
- [x] 🕓 Applies to a reasonable number of elements (Worth the effort)

### Ideas for implementation

simple yes/no question

**Element selection:** 

If amenity=charging_station is present and parking:fee=* is not present.

**Comment by westnordost** [comment]
You mean `fee=yes/no`, right?

**Comment by westnordost** [comment]
Oh, now I get it. I think the fee for parking should be given on the parking lot.

**Comment by dbrgn** [comment]
> Oh, now I get it. I think the fee for parking should be given on the parking lot.

Not quite. The tag is set on the charging station itself, and it indicates whether the user needs to pay a parking fee in addition to the charging fee. In some places, there is a parking fee on the general parking lots, but you may park for free while charging.

In order for charging map apps to be able to indicate free parking, it's useful to have this field on the charging station node.

See OSM wiki at https://wiki.openstreetmap.org/wiki/Tag:amenity%3Dcharging_station

**Comment by westnordost** [comment]
The user of a charging station needs to pay anyway. OSM does not record how much the user has to pay, so the information whether he additionally need to pay a parking fee is rather irrelevant. F.e. one charging station costs 10€, the other costs 5€+5€ parking fee -> no difference.

**Comment by dbrgn** [comment]
No, the differences can be quite large. Here, some charging stations are free, with parking fees of 0.50 CHF per hour (so 1.50 CHF for 3 hours charging), while other charging stations cost 0.60 CHF per kWh, so a three-hour charge might cost 25-30 CHF.

**Comment by westnordost** [comment]
and both will be tagged with `fee=yes`

**Comment by westnordost** [comment]
So it could be asked if there is a fee for the charing station. I just doubt that this occurs often enough that it makes sense to ask about it for every station. Also, I expect that those that are really free will already be tagged like that from the beginning (when a surveyor added it) because it seems to be a very noteworthy feature.
