### ISSUE TITLE
additional details on charging_station - vehicle types

### ISSUE THREAD

**Issue by RubenKelevra** [westnordost/StreetComplete#899]
There are different charging stations for different purposes, in my surroundings are several ebike-charging stations, so differentiating them for cars would be nice.

### General
Affected tag(s) to be modified/added: [bicycle=yes/no; car=yes/no]
Question asked: 

**Can eBikes be charged here (possible and allowed)?**
**Can cars be charged here (possible and allowed)?**

### Checklist
Checklist for quest suggestions (see guidelines):
- [x] 🚧 To be added tag is established and has a useful purpose
- [x] 🤔 Any answer the user can give must have an equivalent tagging (Quest should not reappear to other users when solved by one)
- [x] 🐿️ Easily answerable by everyone from the outside but a survey is necessary 
- [x] 💤 Not an overwhelming percentage of elements have the same answer (No spam)
- [x] 🕓 Applies to a reasonable number of elements (Worth the effort)

**Element selection:** 

If amenity=charging_station is present and 'bicycle=*' or 'cars=*' not.

**Comment by ENT8R** [comment]
I think that this question is rather spam because nearly all charging stations are for cars...

**Comment by RubenKelevra** [comment]
Well, we got a lot of bicycle charging stations around here which are basically a wall outlet in a box with a key while there's no parking spot for a car nearby. In the Netherlands those charging spots are a lot more common than in Germany, but we also got some. :)

**Comment by westnordost** [comment]
I agree with ENT8R. I would expect that people who survey and map e-bike-loading-stations would not simply add a charging-station without any further tags but explicitly add that they are for e-bikes (as well).

**Comment by tiptoptom** [comment]
I think in the meantime a distinction between bicycle and car makes sense, because there are more and more e-bike charging stations.
