### ISSUE TITLE
Solve quest with photo

### ISSUE THREAD

**Issue by CloCkWeRX** [westnordost/StreetComplete#90]
(Just adding here instead of email)

Sometimes an answer is more complex than easily input.
When this happens, opening the camera to allow taking a photo/attaching from gallery would ve good,
Publishing via mapillary or openstreetcam plus adding a note to OSM would be a good way to ensure complex answers can be mapped by others

**Comment by westnordost** [comment]
I plan to add a feature later where the user can attach a photograph to a note. However, I don't have that amount of webspace available to store all these pictures. Question is, are there any suitable third parties where such photos could be uploaded to? You mention mapillary and openstreetcam already. I prefer something that does not require a login.

**Comment by Dryusdan** [comment]
There somes third party of lutim :)
https://lutim.dryusdan.fr
https://images.mondedie.fr/
https://framapics.org
https://lut.im/

**Comment by Dryusdan** [comment]
https://framapic.org ans not framapics

**Comment by CloCkWeRX** [comment]
> something that does not require a login.

Openstreetcam and Mapillary luckily supports oauth with your OSM login; so you aren't forced to come up with a new set of credentials.

From looking at https://gist.github.com/peterneubauer/288633b8ae0358fa53ae#check-whats-missing Mapillary puts the auth into the image exif data.

Openstreetcam might be a little better:
https://github.com/openstreetcam/upload-scripts/blob/master/upload_osv_photos/upload_photos.py

The oauth it wants is with openstreetmap itself from the looks of it.

**Comment by rugk** [comment]
In any case please embed GPS location and orientation and such meta data in the photo.

**Comment by westnordost** [comment]
This should actually not be that hard to implement while probably adding quite some value when leaving a note. But, I never have the time to do this.

**If you want to help:**
I need an image hosting service that does not require login and that offers some kind of API that I can call from code. framapic and lutim look good, but it's a web app - no idea if they offer that. So, you can do some research here if it exists. 

In case nothing exists, I will have to write a small python/php script that does exactly that on my webspace. (Plus deletes old images if the assigned disc spaces becomes critical). If you know php, python, perl or other script languages that run on a normal webspace, you can help me out there as well.

**Comment by Phyks** [comment]
> framapic and lutim look good, but it's a web app - no idea if they offer that. So, you can do some research here if it exists.

Both Framapic, Lut.im and the instances listed above rely on [Lutim](https://framagit.org/luc/lutim) which offers an [API](https://framagit.org/luc/lutim/wikis/API). No credentials should be required to use it, if I remember correctly.

**Comment by rugk** [comment]
IMHO you may at least also provide a way for Mapillary users to upload their images there. They offer [a powerful API](https://www.mapillary.com/developer) but I imagine another, way simpler way: As a mapillary user, you likely have the mapillary app installed. The app is good, because it includes location data and all that stuff, so you do not need to implement all that in StreetComplete (which may get difficult). So just sent an intend to that app, to take a picture. And if possible, the app may then return the URL of the uploaded picture, so you can include that in your comment. That would be an awesome workflow/UX IMHO…

**Comment by ENT8R** [comment]
That sounds good and maybe not that hard to implement... But we should have an option to upload images for non-users of the mapillary app...
