### ISSUE TITLE
additional details on charging_station - no authentication required

### ISSUE THREAD

**Issue by RubenKelevra** [westnordost/StreetComplete#901]
If you ever drove an EV you got to know this awful situation with charging network cards, chips, apps, etc. to authenticate yourself to the charging station before you're able to start the charge. But many charging stations which are free does not require any type of authentification.

Since this is a very useful information, it would be nice to be able to survey those informations via SC.

### General
Affected tag(s) to be modified/added: [authentication:none=yes/no]
Question asked: **Is a authenfication required to start charging on this charging station (eg. chip-card, app, sms)?**

If the user answers yes, we need to tag authentication:none=no and if the user answers no, we need to tag authentication:none=yes.

### Checklist
Checklist for quest suggestions (see guidelines):
- [x] 🚧 To be added tag is established and has a useful purpose
- [x] 🤔 Any answer the user can give must have an equivalent tagging (Quest should not reappear to other users when solved by one)
- [x] 🐿️ Easily answerable by everyone from the outside but a survey is necessary 
- [x] 💤 Not an overwhelming percentage of elements have the same answer (No spam)
- [x] 🕓 Applies to a reasonable number of elements (Worth the effort)

**Element selection:**

If amenity=charging_station is present and authentication:*=* is not

**Comment by rugk** [comment]
Can you test that without any card, etc. at all? I.e. can you really see it when not being a EC driver?

**Comment by westnordost** [comment]
Is this even an accepted and documented tag? Also, I find this information a bit too specific. We also don't map if the wifi offered by a place requires authentication etc.

**Comment by rugk** [comment]
Well… for EC drivers it is clearly a useful information. But maybe it could also be implicitly derived by the provider – they likely either always require authentication or never. Basically, also ` fee=no` would be the same as no authentication in most cases.

**Comment by matkoniecz** [comment]
> documented tag?

It is listed on https://wiki.openstreetmap.org/wiki/Key:authentication and there is some usage according to https://taginfo.openstreetmap.org/keys/authentication%3Anone#values

**Comment by westnordost** [comment]
Actually, I made up my mind about this. I will close these quest requests but instead have one that asks for the operator. The same operator will very likely have the same policy on fee, authentication, (plug type) and more.
