### ISSUE TITLE
additional details on charging_station - wheelchair access

### ISSUE THREAD

**Issue by RubenKelevra** [westnordost/StreetComplete#902]
The OSM community already tags shops for wheelchair accessibility, I think we should start this charging_stations too.

This tag, thus very similar to the car/bicycle tags from https://github.com/westnordost/StreetComplete/issues/899, does not represent the ability to charge wheelchairs on this charge station but the accessibility of it.

### General
Affected tag(s) to be modified/added: [wheelchair=yes/no]
Question asked: **Is this charging station wheelchair accessible?**

### Checklist
Checklist for quest suggestions (see guidelines):
- [x] 🚧 To be added tag is established and has a useful purpose
- [x] 🤔 Any answer the user can give must have an equivalent tagging (Quest should not reappear to other users when solved by one)
- [x] 🐿️ Easily answerable by everyone from the outside but a survey is necessary 
- [x] 💤 Not an overwhelming percentage of elements have the same answer (No spam)
- [x] 🕓 Applies to a reasonable number of elements (Worth the effort)

**Element selection:** 

If amenity=charging_station is present and wheelchair=* not.

**Comment by lokaman** [comment]
Aaand we are over 100 open issues. Did your brain already exploded @westnordost?

I see you @RubenKelevra opened some threads regarding new quest, mainly about stuff for charging stations.

Opening issues for seperate quest is the right thing to do, but consider that the more issues you have its a lot of work to prioritize stuff.

**Comment by RubenKelevra** [comment]
Well, I don't have any inside into your workload or the amount of work necessary to add such quests. But most of them, which I've added are pretty low hanging food, which has low complexity too. I've just opened more than one ticket to be able to discuss them separately in case I miss something important which need to be discussed in the first place.

But, I think it's a good opportunity to thank you all for this great app which helps a lot to find missing informations and save me from boring trips as a passenger. :)

**Comment by rugk** [comment]
I really see how you are committed to do something with charging stations, and seem to really like them (:wink:), but I fear that these are still often still very specific quests, which require some knowledge, an electric car or so for that.

BTW most quests are really low hanging fruits. If you want too help, check out [the new quest tag](https://github.com/westnordost/StreetComplete/issues?q=is%3Aissue+is%3Aopen+label%3A%22new+quest%22). You can implement all of them. :wink: 

As for this quest, it is indeed answerable by everyone, but which charging station is not accessible by wheelchair users? I mean these are outside. If you have a curb there, it is a bit harder, but one cannot really tag that. (Everywhere at parking places are kerbs, and these are not so high that they may be problematic. Note tha definition of "maybe" also allows one step according to StreetComplete)
So I'd guess there are not really many charging stations, which are not accessible…

**Comment by RubenKelevra** [comment]
@rugk well, I never learned Java, so implementing is a task I could not complete without a review, which neglect the helpfulness of my work I guess.
