### ISSUE TITLE
additional details on charging_station - charging fee

### ISSUE THREAD

**Issue by RubenKelevra** [westnordost/StreetComplete#904]
This is sometimes more difficult than one might think, sometimes is charging via Shuko free but DC-Fast charging is not free or just a half hours if for free etc.

So there might be not often a simple answer for charging fees, but this tag exists like this and I think the user should be able to distinguish between a "free" station, a "non-free" station and some more complex situations.

### General
Affected tag(s) to be modified/added: [fee=*](https://wiki.openstreetmap.org/wiki/Key:)
Question asked: **Is charging on this charging station always free (on all plugs at all times)?**

### Checklist
Checklist for quest suggestions (see guidelines):
- [x] 🚧 To be added tag is established and has a useful purpose
- [x] 🤔 Any answer the user can give must have an equivalent tagging (Quest should not reappear to other users when solved by one)
- [x] 🐿️ Easily answerable by everyone from the outside but a survey is necessary 
- [x] 💤 Not an overwhelming percentage of elements have the same answer (No spam)
- [x] 🕓 Applies to a reasonable number of elements (Worth the effort)

**Element selection:** 

If amenity=charging_station is set but no fee=* tag exists.

**Comment by rugk** [comment]
I think in your first sentence, you unfortunately, already explained, why this quest cannot be included in StreetComplete.

Note the requirement:
> Easily answerable by **everyone**

i.e.… non-electric car drivers.

I am not sure whether just tagging "yes" when at least one thing requires the fee is really appreciated. It's kind of adding wrong data…
