### ISSUE TITLE
House number quest: Some buildings have multiple house numbers.

### ISSUE THREAD

**Issue by hungrymonkey** [westnordost/StreetComplete#910]
### General
Affected tag(s) to be modified/added: [](https://wiki.openstreetmap.org/wiki/Key:)
Question asked: **Is there an example tag on item XY?**

House number building quest

### Checklist
Checklist for quest suggestions (see guidelines):
- [ ] 🚧 To be added tag is established and has a useful purpose
- [ ] 🤔 Any answer the user can give must have an equivalent tagging (Quest should not reappear to other users when solved by one)
- [X] 🐿️ Easily answerable by everyone from the outside but a survey is necessary 
- [X] 💤 Not an overwhelming percentage of elements have the same answer (No spam)
- [X] 🕓 Applies to a reasonable number of elements (Worth the effort)

### Ideas for implementation

**Element selection:** 

**Metadata needed:** 

**Proposed GUI:** 

Add to other answers.

**Comment by westnordost** [comment]
You can simply answer with something like i.e. "13,15" or "9-15". This is not that precise, but legal tagging and a good start.

**Comment by rugk** [comment]
Wait before closing this. I think we had this question before... So maybe it is a UX issue here.

Can we maybe change the quest to indicate that this is a valid tagging?

One suggestion: Just add a "Other answer" -> "There are multiple house numbers", which either pop ups a different dialog for entering, or just explains that you can tag it like that.
Maybe once this was shown (and the user checkboxed "Do not show again"?) this entry can then be then hidden from the "Other answers".

**Comment by matkoniecz** [comment]
> or just explains that you can tag it like that.

Good idea, I think that this issue was created multiple times (and only tiny minority reports problems).

There is also #712 #439 and #537

> this entry can then be then hidden from the "Other answers".

Confusing, one may wish to check this confirmation again.

I will create a new issue for that.
