### ISSUE TITLE
additional details on charging_station - operator

### ISSUE THREAD

**Issue by westnordost** [westnordost/StreetComplete#911]
### General
Affected tag(s) to be modified/added: [operator=*](https://wiki.openstreetmap.org/wiki/Key:operator)
Question asked: **What is the name of the operator for this car charging station?**
### Checklist
- [x] 🚧 To be added tag is established and has a useful purpose: Can infer other values from the operator
- [x] 🤔 Any answer the user can give must have an equivalent tagging (Quest should not reappear to other users when solved by one)
- [x] 🐿️ Easily answerable by everyone from the outside but a survey is necessary : It's printed on each station
- [ ] 💤 Not an overwhelming percentage of elements have the same answer (No spam): Within one city, probably there are only few operators. Maybe the quest could offer auto-completion to mitigate likely having to write the same operator again and again.
- [x] 🕓 Applies to a reasonable number of elements (Worth the effort): Car charging stations are coming out big now

**Metadata needed:** 

As mentioned, perhaps metadata for the likely operators can be provided for auto-completion or selection (like in street name quest).

**Comment by matkoniecz** [comment]
It is quest for amenity=charging_station ( https://taginfo.openstreetmap.org/tags/amenity=charging_station#combinations ) - 8k (about half) have set operator.

There is something at https://en.wikipedia.org/wiki/Charging_station#Charging_network_operators but this list is not impressive.

**Comment by rugk** [comment]
Just a general observation: [Our list of "operator" quests](https://github.com/westnordost/StreetComplete/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+operator+) is growing. That cries for an abstract(?) class or some other form of generalisation.
Or one quest for all of them, but I'd not favour that, as the icons for the quests may often need to look completely different.

Also seeing that the autocomplete thing is quite hard to implement, such a generalisation would be helpful. Maybe also interface-like? Aka "ChargingStationOperator implements IQuestAutoComplete".
That would also help contributors very much, who then preferably only need to specify/implement the data source or so.

---

I see that can go off-topic here, so discuss that in a new issue(?)
