### ISSUE TITLE
add location to buildings with negative layer from -1 to -5

### ISSUE THREAD

**Issue by matkoniecz** [westnordost/StreetComplete#912]
### General
Affected tag(s) to be modified/added: [location](https://wiki.openstreetmap.org/wiki/Key:Location)
Question asked: **Is this building is existing and located underground?**

### Checklist
Checklist for quest suggestions (see guidelines):
- [x] 🚧 To be added tag is established and has a useful purpose (it is used in StreetComplete itself, allows to clearly mark something as underground - some mappers use solely negative layer/level and expect that it is enough to describe something as located underground)
- [x] 🤔 Any answer the user can give must have an equivalent tagging (Quest should not reappear to other users when solved by one) location=underground/surface/overground/overhead should cover all cases, except complete mistaggings
- [x] 🐿️ Easily answerable by everyone from the outside but a survey is necessary: distinguishing location=surface/overground/overhead requires survey, checking whatever structure exists requires survey
- [x] 💤 Not an overwhelming percentage of elements have the same answer (No spam)
- [x] 🕓 Applies to a reasonable number of elements (Worth the effort)

### Ideas for implementation

**Element selection:** http://overpass-turbo.eu/s/wv2

**Metadata needed:** no

**Proposed GUI:**

**Comment by goldfndr** [comment]
You could simplify the query to `way["building"]["layer"~"-.*"]["location"!~".*"]({{bbox}});` in case someone uses a number beyond -5. Although it's improper to exceed -5, such instances can usually be solved by an armchair mapper. [openstreetmap-carto accepts integers -99 to 99.](https://github.com/gravitystorm/openstreetmap-carto/blob/master/openstreetmap-carto.lua#L421)

**Comment by westnordost** [comment]
Well, in StreetComplete, one can use a simplified tag query syntax anyway: `ways, relations with layer ~ -.* and !location`

**Comment by rugk** [comment]
Hmm, don't understand this quest. So this is basically correcting a tagging mistake (only tagging layer=).
And when the building is underground, should not it usually be tagged with `level`?

[Here](https://www.openstreetmap.org/way/381646628) something is tagged with `building:levels:underground=1`. Is not that enough, so is this `location` tag really needed?

**Comment by ENT8R** [comment]
I think it is needed, because without that location=underground tag, there will be underground train stations displayed as normal overground buildings on the map of SC...

**Comment by matkoniecz** [comment]
>  So this is basically correcting a tagging mistake

Yes.

> Here something is tagged with building:levels:underground=1. Is not that enough, so is this location tag really needed?

At least for me at this moment it is not entirely clear. If that object is entirely underground, I would add also location=underground.

> building:levels:underground=1

building:levels:underground may be given to any object that has 1 level underground, not only ones entirely underground.

> I think it is needed, because without that location=underground tag, there will be underground train stations displayed as normal overground buildings on the map of SC...

I would add it because it is useful tag explaining situation, not just because one particular data consumer relies on it.
