### ISSUE TITLE
explain that tagging list or range of housenumbers is OK

### ISSUE THREAD

**Issue by matkoniecz** [westnordost/StreetComplete#917]
"12,14,16" or "1190-1300" are valid answers to a housenumber quest but many people are unaware about this as #910 #712 #439 and #537 indicate.

Some people ask on bug tracker but many more will never check it.

I think that idea from @rugk proposed in #910 would help

> add a "Other answer" -> "There are multiple house numbers", which either pop ups a different dialog for entering, or just explains that you can tag it like that.

It would (a) reduce chance that further duplicates of #910 #712 #439 and #537 will be posted (b) will help people able to use "can't say" menu that would not check bugtracker (c) reduce response times for ones that create issues on a bug racker.

**Comment by westnordost** [comment]
> or just explains that you can tag it like that.

Oh yeah, that would work!

**Comment by hungrymonkey** [comment]
btw, some house numbers have these 1/2 in addition to integers
