### ISSUE TITLE
Publish beta version as separate app on F-Droid

### ISSUE THREAD

**Issue by rugk** [westnordost/StreetComplete#918]
After fixing the suffixes for the F-Droid build (https://github.com/westnordost/StreetComplete/issues/622) F-Droid now only get's stable releases.

However, you also mentioned you'd like if F-Droid users can beta test that app, as they are more likely to report issues.
So why not publish a _StreetComplete Beta_ as a "different app" on F-Droid. Other apps like [NextCloud](https://f-droid.org/packages/com.nextcloud.android.beta/) or [NewPipe](https://f-droid.org/packages/org.schabi.newpipe.beta/) also do it like that.
Users could then decide to test the beta deliberately.

And maybe also choose a different icon or so for it (as with the dev version, currently, maybe yet another color), so that users can differentiate the versions. (Or add a "Beta" badge, or so...)

I don't know if you use the beta program on Google Play, but you could also realize that on F-Droid, too.

**Comment by lokaman** [comment]
FYI: StreetComplete on Google Play uses the Beta Feature.

**Comment by westnordost** [comment]
No, I don't want to do that. Obviously, F-Droid does not support publishing beta versions. Creating a separate app for that looks somewhat like a workaround to me. I think it is too much effort.

**Comment by rugk** [comment]
AFAIK they have a setting in the settings for showing "unstable versions". Don't know what it does, though…

**Comment by tiptoptom** [comment]
I don't understand why no beta versions can be published on F-Droid labeled as "pre-release"?

**Comment by matkoniecz** [comment]
> I don't understand why no beta versions can be published on F-Droid labeled as "pre-release"?

Also not sure about it - but note that this issue is about something different

if

> Obviously, F-Droid does not support publishing beta versions.

is no longer true then opening a new issue may make sense
