### ISSUE TITLE
bridge type quest - a first try

### ISSUE THREAD

**Issue by axre** [westnordost/StreetComplete#921]
It was quiet hard for me to map with the bridge type quest. So i want to share some thoughts here:

As you may know no names are provided for the pictures. i still support that as probably nobody knows the somewhat technical names for the structures. see #842 

Pictures may be to big, forgive me, im new to github ^^ of course i didnt map those bridges in osm.

(1) small bridges are not represented in the pictures, so its quite hard to pick the right picture.  example of a extremely dirty & closed one: 
![img_20180209_135643](https://user-images.githubusercontent.com/16156320/36696068-7afa5768-1b43-11e8-933a-c0da507e0382.jpg)
![img_20180209_135122](https://user-images.githubusercontent.com/16156320/36696398-5933d900-1b44-11e8-98ca-126dcc46e666.jpg)

i had no idea which one to pick. if i understand the [wiki](https://wiki.openstreetmap.org/wiki/Key:bridge:structure) correct it would be "beam".
![whut](https://raw.githubusercontent.com/westnordost/StreetComplete/master/app/src/main/res/drawable-mdpi/bridge_structure_beam.jpg)

(2)
![img_20180209_134719](https://user-images.githubusercontent.com/16156320/36696483-9b0f8766-1b44-11e8-8007-bdffa8d821c6.jpg)
This one is probably "beam" too, although it looks completely different.

(3)
![img_20180216_132127](https://user-images.githubusercontent.com/16156320/36697079-4d6fdc5c-1b46-11e8-94b2-a6c8ba0d13a0.png)
![img_20180216_132225](https://user-images.githubusercontent.com/16156320/36697089-540849f0-1b46-11e8-913d-372ad73d49d4.jpg)
with the wiki article in mind - is this "arch"?
![](https://raw.githubusercontent.com/westnordost/StreetComplete/master/app/src/main/res/drawable-mdpi/bridge_structure_arch.jpg)
![](https://raw.githubusercontent.com/westnordost/StreetComplete/master/app/src/main/res/drawable-mdpi/bridge_structure_tied_arch.jpg)

Conclusion:
Small bridges are not well represented, most of them are probably beam (?), just without the pillars.
For some bridges its still hard to map, as you only have a picture, and no name or description.

I may look if other people are more sucessful than me by checking the changesets sometime & search for more bridges in my area.

**Comment by westnordost** [comment]
It's all beam.

**Comment by westnordost** [comment]
As a solution, we may search for another representative picture of a "small" beam bridge (perhaps not a footbridge) and when the user selects that bridge, also tag it as "beam".

**Comment by westnordost** [comment]
Well, does not make sense to keep this open if nothing is proposed.

**Comment by matkoniecz** [comment]
Can you reopen and reassign to me? I was waiting for a better weather to make photo of one of small bridges.

I tried 

> search for another representative picture of a "small" beam bridge

and found nothing on suitable license

**Comment by westnordost** [comment]
(I cannot assign you)

**Comment by westnordost** [comment]
@matkoniecz

**Comment by matkoniecz** [comment]
I remember about it, I made even a special bicycle trip to one bridge that should fit bit for various reasons none was suitable.

**Comment by westnordost** [comment]
Ok then i close it. Thanks for tge effort though ^^
