### ISSUE TITLE
Add Number of Fire Hydrant quest

### ISSUE THREAD

**Issue by nmoyroud** [westnordost/StreetComplete#922]
### General
Affected tag(s) to be modified/added: [ref](https://wiki.openstreetmap.org/wiki/Key:ref)
Question asked: **What is the number of this fire hydrant?**

### Ideas for implementation
**Element selection:** emergency=fire_hydrant (https://overpass-turbo.eu/s/raQ)

**Comment by matkoniecz** [comment]
Note that at least in some regions fire hydrants have no numbers obtainable by field survey (for example in Poland).

Where fire hydrants almost always have numbers?

**Comment by rugk** [comment]
Also please go through the checklist. (It's not there for fun) The problem here is "🐿️ Easily answerable by everyone from the outside", so I agree to @matkoniecz.

**Comment by nmoyroud** [comment]
In France I can say that approximatively 80% of fire hydrants have numbers. They are written in white and can be easily obtainable by field survey.

**Comment by ENT8R** [comment]
Reading the checklist is good but making it visable for others to discuss it properly is better and the way it is wanted...

**Comment by rugk** [comment]
Also the checklist is not only for just checking the things there. In case one item is not self-explanatory, you should also add a reason, i.e. why the quest is not spammy, e.g. Always try to back the thing with facts. That always helps.

**Comment by ENT8R** [comment]
Regarding this issue: you might take a look at #81 where something like this was already proposed

**Comment by rugk** [comment]
Also see https://github.com/westnordost/StreetComplete/issues/362, where diameter and position were already proposed.

**Comment by westnordost** [comment]
How is the ref helpful data?
In which countries do hydrants have refs?
How to distinguish the ref from other numbers (if any) that may possibly be found on the hydrants? Per-Country-guids necessary?

**Comment by matkoniecz** [comment]
Ping @nmoyroud - see https://github.com/westnordost/StreetComplete/issues/922#issuecomment-369411770
