### ISSUE TITLE
Ask about waterway names

### ISSUE THREAD

**Issue by matkoniecz** [westnordost/StreetComplete#924]
### General
Affected tag(s) to be modified/added: [Name](https://wiki.openstreetmap.org/wiki/Key:Name)
Question asked: **What is the name of this waterway?**

### Checklist
Checklist for quest suggestions (see guidelines):
- [x] 🚧 To be added tag is established and has a useful purpose
- [x] 🤔 Any answer the user can give must have an equivalent tagging (Quest should not reappear to other users when solved by one) (potentially noname=yes may be applied)
- [x] 🐿️ Easily answerable by everyone from the outside but a survey is necessary (in my experience this one may require asking local people, but I would still qualify it as "Easily answerable by everyone")
- [x] 💤 Not an overwhelming percentage of elements have the same answer (No spam), some waterways may be split but it is not worse that surface/lit for roads
- [x] 🕓 Applies to a reasonable number of elements (Worth the effort) - just waterway=stream has 8M elements with neither name tag nor noname tag ( https://taginfo.openstreetmap.org/tags/waterway=stream#combinations (of 10.5M waterway=stream name is used 1.7M times, noname is used just 537 times for waterways - see https://taginfo.openstreetmap.org/keys/noname#combinations and less than 400k of 1M river elements have name tag - see https://taginfo.openstreetmap.org/tags/waterway=river#combinations )

### Ideas for implementation

May be done as part of AddPlaceName, may be done as a separate quest. I think that separate quest is preferable as it is likely to include its own logic and its own icon.

**Element selection:** waterway=river/canal/stream ways without name and noname tags. Maybe also waterway=waterfall/dam but these probably should be rather included in AddPlaceName.

**Metadata needed:** I hope that it is not necessary, hopefully waterways are named everywhere.

**Implementing:**

I am planning to implement this quest if it is not rejected.

**Comment by matkoniecz** [comment]
Waterways without names that are in https://wiki.openstreetmap.org/wiki/Relation:waterway probably should be ignored (assuming that this situation is likely to occur).

**Comment by rugk** [comment]
Hmm... compared to the street name quest, this is indeed more difficult, as I never saw any "~street~ water name sign" near something like that. 😄

**Comment by matkoniecz** [comment]
Interesting, there is a road sign for that in Poland (though small stream and rivers not crossing roads still require asking, local knowledge or obtaining this information in other way).

![250px-tabliczka](https://user-images.githubusercontent.com/899988/36797878-6b8ebfbe-1ca9-11e8-8983-17d98f4dba94.JPG)

**Comment by rugk** [comment]
Okay, yeah, in Germany there is also a road sign if some _big_ roads cross a _big_ waterway, but there we can forget this quest, because such waterways (rivers) are very likely already mapped.

**Comment by westnordost** [comment]
Jup. This would be too often unsolvable.

If at all, it would have to ask at bridges, because that is where one can likely see a sign. But this would be pretty hard to implement, plus, I still believe in the vast majority, there won't be signs like that.

**Comment by matkoniecz** [comment]
Also if it would be limited to waterway=river? While some stream may be without name I would expect waterway=river to be unnamed only if it is a mistagged stream.

**Comment by westnordost** [comment]
Yes, because even if it has a name, it will not be apparent from everywhere. As said, in Europe there might be signs at (major) bridges, but worldwide, surely not.
If the user does not spot the name where he is standing at, what do you expect him to do? Walk the river "to the end", as for streets, in the search for a sign? Basically, there won't be any situation where the user can say with confidence "it has no name". But it is a quest guideline to always be able to tag something.

On 1 March 2018 06:26:23 CET, Mateusz Konieczny <notifications@github.com> wrote:
>Also if it would be limited to waterway=river? While some stream may be
>without name I would expect waterway=river to be unnamed only if it is
>a mistagged stream.
>
>-- 
>You are receiving this because you modified the open/close state.
>Reply to this email directly or view it on GitHub:
>https://github.com/westnordost/StreetComplete/issues/924#issuecomment-369477921

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by matkoniecz** [comment]
> Basically, there won't be any situation where the user can say with confidence "it has no name".

I do this after asking people living in a given location (though so far I did it only with streams, I have yet to encounter river without tagged name).

**Comment by rugk** [comment]
Sorry, but I'd say it is a very high requirement for the average SC user. We cannot expect them to ask people around them. (provided there are some/they find some)

**Comment by HolgerJeromin** [comment]
Often a part of the waterway is missing a name. But this gaps can be easy filled from remote/armchair.
