### ISSUE TITLE
ask about lake names

### ISSUE THREAD

**Issue by matkoniecz** [westnordost/StreetComplete#925]
### General
Affected tag(s) to be modified/added: [Name](https://wiki.openstreetmap.org/wiki/Key:Name)
Question asked: **What is the name of this lake?**

### Checklist
Checklist for quest suggestions (see guidelines):
- [x] 🚧 To be added tag is established and has a useful purpose
- [x] 🤔 Any answer the user can give must have an equivalent tagging (Quest should not reappear to other users when solved by one)
- [x] 🐿️ Easily answerable by everyone from the outside but a survey is necessary 
- [x] 💤 Not an overwhelming percentage of elements have the same answer (No spam)
- [x] 🕓 Applies to a reasonable number of elements (Worth the effort) 300k+ according to https://taginfo.openstreetmap.org/tags/water=lake#combinations

### Ideas for implementation

**Element selection:**  natural=water and water=lake and !name and !noname

**Metadata needed:** Hopefully not.

**Proposed GUI:** 

**Implementing:**

I am planning to implement this quest if it is not rejected. It may done via AddPlaceName or as a separate quest (latter solution is preferable - this quest should be asked for ways and relations and not asked for nodes)

**Comment by rugk** [comment]
Maybe limit by size? (minimum size) Not that it asks about each pond in a garden... (or are these differently mapped?)

**Comment by matkoniecz** [comment]
Note water=lake requirement, it is not asking about every natural=water area.

If water=lake is frequently mistagged some special "can't say" may be implemented.

**Comment by ENT8R** [comment]
I just wanted to write the same as @rugk 😄 
Maybe 10000m3 (100m*100m) is OK?
But ponds should be mapped with "natural=water" and "water=pond"... So it does not show up for every pond...

**Comment by westnordost** [comment]
This quest has the same problem as the river name quest. Not every lake has a name, just as not every forest has a name etc.
Whether a lake has a name, is not trivial to find out.
