### ISSUE TITLE
Consider making StreetComplete GitHub organisation

### ISSUE THREAD

**Issue by rugk** [westnordost/StreetComplete#928]
Considering StreetComplet's growth, I think, it may be a good idea to create a new GitHub organisation, where you can collect all repos, including this one as the main repo, of course.

E.g. @ENT8R already created a lot of software for StreetComplete only, which may only be needed for StreetComplete, all these repos can be placed in the new organisation, so they are all together.

Or it may host a potential future website… (a project website may be a nice thing, anyway)

You'd alos get some features like [team discussions](https://blog.github.com/2017-11-20-introducing-team-discussions/), which one may not need.

**Comment by matkoniecz** [comment]
Is there any benefit over listing such projects in https://github.com/westnordost/StreetComplete/blob/master/CONTRIBUTING.md like it is done with a map style?

**Comment by rugk** [comment]
A lot, because it is much more than a list. One can see that these repos clearly belong together and they will be something "official" of StreetComplete.
Just look at [other projects](https://github.com/asciinema) [who do this](https://github.com/borgbackup).

**Comment by westnordost** [comment]
I also do not see the gain. What do the other regular contributors (@ENT8R, @PanierAvide, @goldfndr etc) say?

**Comment by rugk** [comment]
Indeed nearly all of these you mentioned also have repos about SC . So the best question to you would be: Could you think to transfer your SC-related repos under one "StreetComplete" organisation, to keep them together?

**Comment by matkoniecz** [comment]
> One can see that these repos clearly belong together and they will be something "official" of StreetComplete.

I still see no benefit over list, it seems to merely add administrative work for @westnordost (who AFAIK is not liking it).

>  Just look at other projects who do this.

In this cases it seems to be more useful as there is one project with multiple products (terminal program, web app) rather than single project with some related tools - so it probably simplifies handling of admin rights.

**Comment by matkoniecz** [comment]
@rugk 

I would not transfer https://github.com/matkoniecz/Zazolc as it would go against entire point of my private fork.

**Comment by ENT8R** [comment]
I have no strong opinion on this... I mean if the links to the other projects exist in this project you should find the repository even without a Github Organization...
On the other hand you could say that with a StreetComplete organization other people can see which projects really belong to SC...

**Comment by rugk** [comment]
> I would not transfer https://github.com/matkoniecz/Zazolc

Of course, yes, personal forks are personal forks. These would not be useful to transfer…

> rather than single project with some related tools - so it probably simplifies handling of admin rights

Good point, AFAIK StreetComplete's tools are really only developed by one person or so

> I still see no benefit over list,

BTW, "over a list, which we do not even have currently"… :disappointed: 

----

So as I see I meet much resistance to this idea, I'll give up. It's not worth it then…
Then, instead let's make a simple list: [issue is being created]

**Comment by rugk** [comment]
I think this here would really make sense only, if @westnordost would e.g. want to move the dependencies he created (countryboundaries, etc.) into one organization under SC, so they belong together. But I think this is not the case. :wink:
