### ISSUE TITLE
Using alternative tile server / renderings?

### ISSUE THREAD

**Issue by Phyks** [westnordost/StreetComplete#931]
Hi,

The recent addition of the ability to leave notes anywhere from StreetComplete is super convenient I think, as it lets users fill-in missing stuff while also filling StreetComplete tasks. For instance my typical use case might be: I want to solve quests in a given area, and at the same time, I'd like to leave notes about missing stuff such as bike parks, to fill them later online when I get back to my computer. Previously, this meant having to switch between SC and another editor regularly, which was not very convenient.

The remaining problem though is that the tiles are super convenient for solving SC quests but not really convenient for noting missing items. Do you think it could be possible to let the user define a custom tile server to use, rather than the default one (in parameters, for advanced users)? This way, one may use for instance [tile.openstreetmap.fr](http://tile.openstreetmap.fr/) which features all POIs, bike stands and crossings etc.

Not sure how hard it would be to change the tile server through a parameter, if it's just a variable to tweak or if it is more tightly bound to the SC code.

Thanks!

**Comment by matkoniecz** [comment]
See #673 for more restricted version.

Note that in densely mapped areas (in cities) map styles are unable to show everything, I would still recommend checking using Vespucci or OSMfocus before creating notes.

**Comment by Phyks** [comment]
Ok, feel free to close in favor of #673, it simply did not show up in my search :/

They might now show everything but will most likely show the major stuff (large recycling bins, pedestrian crossings, bike stands etc).

**Comment by matkoniecz** [comment]
You should have available "close" button at the bottom (as you created this issue).

**Comment by rugk** [comment]
Note, however, [the other issue](https://github.com/westnordost/StreetComplete/issues/673) is mainly about dark/night/... mode. You likely won't get more information in the tiles there.
