### ISSUE TITLE
New quest: Railway crossing – bell

### ISSUE THREAD

**Issue by rugk** [westnordost/StreetComplete#935]
Followup of https://github.com/westnordost/StreetComplete/issues/422

### General
Affected tag(s) to be modified/added: [crossing:bell](https://wiki.openstreetmap.org/wiki/Key:crossing:bell)
Question asked: **Does this railway crossing have a bell??**

### Checklist
Checklist for quest suggestions (see guidelines):
- [ ] 🚧 To be added tag is established and has a useful purpose (Purpose is not be that clear to me, BTW.)
- [x] 🤔 Any answer the user can give must have an equivalent tagging (Quest should not reappear to other users when solved by one)
- [x] 🐿️ Easily answerable by everyone from the outside but a survey is necessary 
- [x] 💤 Not an overwhelming percentage of elements have the same answer (No spam)
- [x] 🕓 Applies to a reasonable number of elements (Worth the effort)  – only 21 000 of over 600 000 level_crossing have this tag set

As for the survey: The issue here may be that you cannot directly spot (see) the bell. As such, you may have to wait until it rings (when a train comes) to be able to say, whether it is there.

### Ideas for implementation

**Element selection:** all [`railway=level_crossing`](https://wiki.openstreetmap.org/wiki/Tag:railway%3Dlevel_crossing)

**Metadata needed:** likely not

**Proposed GUI:** yes/no

Maybe also show an image of such bells, so if one may try/need to see them, this can help.

**Comment by westnordost** [comment]
Purpose is not that clear to me neither. I'd say, let's close this quest until someone comes along that can explain this and then it can be reopened.

Also, bells are not visible, so it may be difficult to solve.

**Comment by rugk** [comment]
> Also, bells are not visible, so it may be difficult to solve.

I said that already:

> The issue here may be that you cannot directly spot (see) the bell. As such, you may have to wait until it rings (when a train comes) to be able to say, whether it is there.

As such,if the quest may be included in the future, it may be deactivated by default as you "may only be able to hear the bell, but not see it" (that's the reason it should state then).

**Comment by mnalis** [comment]
> Also, bells are not visible, so it may be difficult to solve.

Although, in the meantime we've got _"Are there sound signals for the blind here?"_ which also relies on "hearing only" in most cases (at least around here, push-button boxes with and without sound look exactly the same from the outside). 

However, pedestrian crossings (and sounds signals there) have the advantage that they trigger (usually significantly) more often then the ones at railroads  so that likely makes the noticeable difference for _"🐿️ Easy answer: Users are out and about and impatient. A quick, straightforward and clear answer must be possible"_
