### ISSUE TITLE
New quest: Railway crossing – light

### ISSUE THREAD

**Issue by rugk** [westnordost/StreetComplete#936]
Followup of https://github.com/westnordost/StreetComplete/issues/422

### General
Affected tag(s) to be modified/added: [crossing:light](https://wiki.openstreetmap.org/wiki/Key:crossing:light)
Question asked: **Does this railway crossing have lights?**

### Checklist
Checklist for quest suggestions (see guidelines):
- [ ] 🚧 To be added tag is established and has a useful purpose (also not clear whether it has such a big purpose)
- [x] 🤔 Any answer the user can give must have an equivalent tagging (Quest should not reappear to other users when solved by one)
- [x] 🐿️ Easily answerable by everyone from the outside but a survey is necessary 
- [x] 💤 Not an overwhelming percentage of elements have the same answer (No spam)
- [x] 🕓 Applies to a reasonable number of elements (Worth the effort)

### Ideas for implementation

**Element selection:** all [`railway=level_crossing`](https://wiki.openstreetmap.org/wiki/Tag:railway%3Dlevel_crossing)

**Metadata needed:** likely not

**Proposed GUI:** yes/no

Maybe also show the same image as https://github.com/westnordost/StreetComplete/issues/422#issuecomment-369971616, but with some lights, so it is clear what is meant. Or better call them "traffic lights", so one does not confuse them with street lights or so.

**Comment by Etua** [comment]
I've seen some bells that were not clearly visible from the road, for example hidden behind the lights. As this quest will not be common anyway, I think we should ask for confirmation when the answer is "no", just like in speed limit quest.

**Comment by rugk** [comment]
> Edit: I intended to post it in #935

Then do so and delete the comment here afterwards. It has confused me a bit… :laughing:

**Comment by rugk** [comment]
BTW @westnordost why do you see a purpose here, but not for bells? What differentiates a bell from a light in the SC sense?

**Comment by westnordost** [comment]
I don't know, should I close it? This here is less of a problem because it is at least visible.

On 3 March 2018 18:47:12 CET, rugk <notifications@github.com> wrote:
>BTW @westnordost why do you see a purpose here, but not for bells? What
>differentiates a bell from a light in the SC sense?
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/westnordost/StreetComplete/issues/936#issuecomment-370166227

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by matkoniecz** [comment]
> should I close it?

I would close it with note that good PR implementing it would not be rejected but as this data is not really useful there is no reason to keep this issue open in a bug tracker .

**Comment by westnordost** [comment]
See @matkoniecz

**Comment by Etua** [comment]
@rugk Actually barrier quest is for me level 8 too, but most of the work has been already done there in contrast to #935 and #936

**Comment by rugk** [comment]
> Actually barrier quest is for me level 8 too

Yeah, but I think the bell/light quest is even less useful. At least that is what the current "common meaning" here seems to be judging from the issues.

**Comment by natrius** [comment]
Why is this closed? I have around my place some crossing that just have lights but no bells or barriers. Always wondered, why its asking about barriers but not lights. 

Please reopen this and make something like https://github.com/westnordost/StreetComplete/issues/422#issuecomment-369971616 as @rugk mentioned before. I always wondered why its asking about barriers but not lights. 

@westnordost

**Comment by westnordost** [comment]
Well, see the comments. You can implement it and open a PR if you like 

Am 6. Mai 2020 10:46:17 MESZ schrieb Stefan <notifications@github.com>:
>Why is this closed? I have around my place some crossing that just have
>lights but no bells or barriers. Always wondered, why its asking about
>barriers but not lights. 
>
>Please reopen this and make something like
>https://github.com/westnordost/StreetComplete/issues/422#issuecomment-369971616
>as @rugk mentioned before. I always wondered why its asking about
>barriers but not lights. 
>
>@westnordost
