### ISSUE TITLE
Add privacy notice before opening camera

### ISSUE THREAD

**Issue by ServusWorld** [westnordost/StreetComplete#937]
As far as I know, some things on images aren't allowed to up to the internet, like car's numberplates and other people's faces. Of course, these rules differ from country to country, but I think one should be careful with these two things everywhere.
To achieve that the users keep that in mind, StreetComplete could show a notice before starting the camera, something like _"Please take care that no numberplates, faces and other private things are on the image you upload."_

**Comment by matkoniecz** [comment]
Source? AFAIK "some things on images aren't allowed to up to the internet, like car's numberplates and other people's faces" is not true, though there are certain limitations (see for example https://commons.wikimedia.org/wiki/Template:Personality_rights )

**Comment by rugk** [comment]
I also don't think a note would really help here. Either leave it as it is, or, automatically censor faces and number plates. These both things may always be censored, this applies internationally.
Mapillary does it like that, but they do it on a server, whcih is not possible for StreetComplete.

Or just offer the user a feature to "pixelate" image parts.

**Comment by westnordost** [comment]
Won't implement. It is the responsibility of the camera user to heed the law. I don't recall any camera app or any other app where it is clear that the photo is uploaded to the internet to have this kind of warning.

And by the way, these photos will be deleted after half a year.
