### ISSUE TITLE
Rest area and highway=services have toilettes?

### ISSUE THREAD

**Issue by HolgerJeromin** [westnordost/StreetComplete#940]
### General
Affected tag(s) to be modified/added: [](https://wiki.openstreetmap.org/wiki/Key:toilets)
Question asked: **Is there a toilet on the rest area?** yes/no

### Checklist
Checklist for quest suggestions (see guidelines):
- [x] 🚧 To be added tag is established and has a useful purpose
- [x] 🤔 Any answer the user can give must have an equivalent tagging (Quest should not reappear to other users when solved by one)
- [x] 🐿️ Easily answerable by everyone from the outside but a survey is necessary 
- [x] 💤 Not an overwhelming percentage of elements have the same answer (No spam)
- [x] 🕓 Applies to a reasonable number of elements (Worth the effort)

Perhaps we want to exclude areas where a toilet is mapped explict inside the area.

**Comment by rugk** [comment]
We had something similar in the past (https://github.com/westnordost/StreetComplete/issues/391), which has been rejected, but as this is about restrooms I think it is a good quest.

**Comment by ENT8R** [comment]
But if we want to exclude toilet nodes inside those areas (which is IMO a good idea), then this can't be added to the existing quest but rather needs to be a new one...

**Comment by rugk** [comment]
But, would not that alos useful for the other quest queries for malls and so on?

**Comment by ENT8R** [comment]
Yeah... I think you are right. Does make sense

**Comment by ENT8R** [comment]
I added this right now to my fork (https://github.com/westnordost/StreetComplete/compare/master...ENT8R:940) and if it gets accepted here I can make a PR...

**Comment by rugk** [comment]
A PR is the tool for accepting (or declining) a contribution. So make a PR and get it reviewed there.

**Comment by westnordost** [comment]
So, should be included in the other toilet-quest.

**Comment by ENT8R** [comment]
> So, should be included in the other toilet-quest.

You mean the toilet availability quest?

**Comment by westnordost** [comment]
Yes
