### ISSUE TITLE
Ease contribution with Janitor

### ISSUE THREAD

**Issue by rugk** [westnordost/StreetComplete#941]
I've recently discovered Janitor, see https://janitor.technology/, which is a really nice project allowing you to contribute to FLOSS projects in the browser without having to download all the sources and tools for building that stuff, and so on.

So maybe we can get StreetComplete in it?
[I've asked what is basically needed](https://discourse.janitor.technology/t/how-to-add-a-project/165/2).

One thing I am not sure is whether Android Studio's emulator would work in Docker. Otherwise one would maybe need a way to download the APK and test it on a real device… mhh…

**Comment by matkoniecz** [comment]
@rugk Have you tried any existing project? Is it working well?

**Comment by matkoniecz** [comment]
Overall, I am not sure whatever downloading Android Studio and cloning repository is a significant barrier - unlike for example https://github.com/gravitystorm/openstreetmap-carto where setup of rendering chain is a torture.

For the openstreetmap-carto docker images were a wonderful tool, here I would not expect real improvements.

**Comment by rugk** [comment]
I've just watched the video, but it looks great.

**Comment by westnordost** [comment]
Out of scope. Anyone who wants to setup this project for Janitor can do so, but I will certainly not spend time on that.
