### ISSUE TITLE
Improve feedback when uploading solved quests

### ISSUE THREAD

**Issue by cyclingcat** [westnordost/StreetComplete#944]
Hello,

yesterday I solved some quests in a rural region with very slow and unstable mobile Internet connection. When I tried to upload my answers by tapping on the icon (I don't use auto-upload), nothing seemed to happen at first, so I tapped again and about 30-40 seconds later my quests were finally uploaded (usually the whole process takes less than 5 seconds). Of course I blamed the delay to the bad Internet connection in this area, but I think the user should get some information that his upload action is currently being processed. (My first tap on the icon was probably sufficient, I was just too impatient.)

UI suggestion: Change the colour of the upload button (including the counter) from the moment the user taps on the "Upload" button to the moment the upload has finished (i.e. the upload counter is changed to 0 again). This way, the user gets the feedback "Okay, my command has been received and is being processed. No need to worry."

The cycling cat

**Comment by ENT8R** [comment]
> Change the colour of the upload button

Or simply disable it like it is done with the note visibility setting...

**Comment by deerwood** [comment]
Counting down while uploading would also be nice to have. Especially if one has auto upload/sync disabled or set to WLAN only.

**Comment by TobiasMie** [comment]
Or simply show a toast message.

**Comment by westnordost** [comment]
There is better feedback now. (Progress bar on upload button and visual "plop" effect when the counter below the upload button goes up/down and the same with the stars)
