### ISSUE TITLE
Upload button clickable, star button not

### ISSUE THREAD

**Issue by rugk** [westnordost/StreetComplete#945]
A minor issue, but the upload button is clickable (it has some animation, when you tap on it) – in contrast to the star button, which cannot be clicked.

To solve:
* either add a feature to that button (bring manual upload back :laughing: :wink: )
* or just make it unclickable

SC 4

**Comment by westnordost** [comment]
Haha

**Comment by rugk** [comment]
So did you fix it?

(Best is always to just push a commit and include "Closes #XY", so you do not even have to manually close it.)
