### ISSUE TITLE
Auto opening next quest for object is confusing

### ISSUE THREAD

**Issue by rugk** [westnordost/StreetComplete#947]
I think opening the next quest for the same element as it is currently implemented is not a good UX. (Version 4)

what happens:
1. I solve a quest.
2. It takes some seconds as usual and so already scroll/move the map
3. Surprisingly and without any explanation the map zooms around, back to my old position and shows another quest, which I have not selected.

That is bad, not only because of the delay, but also because it breaks the usual flow of sc (user chooses quest by icon, solves it, moves to next item). The user just gets a completely different quest than what he chose before.

E.g. I experienced that I of chose learn the quests by heard when you solve then. I.e. select street surface and first item for asphalt. That then goes so fast, such a _different_ quest is just an _interruption_ of your current flow. And, what may be worse, the user actually notices quests much more *by the icon* than by anything else. So when I get a different quest in such a way, I actually have to skim the shown question before I actually know what is being asked. That is annoying and I would not have noticed that, but it really seems to be that these quest icons (and tapping on them) are really the thing, where you recognise a quest, already think of the answer and "nearly automatically" select the answer without having to read/think of the question, because you already know that.

## summary

That thing is surprising, unexpected for the user and breaks the expected workflow. This does not seem to be so good.

## solution?

Maybe decrease the time until the next quest is shown, lock the map on between (although that can also frustrate users, so better don't do it) or show an indicator this is another quest.

Or, which I would prefer, show a number at the quest icon so the user already sees before solving one quest, that there is another.

BTW I would even go so far to revert the behavior/disable it. It is kinda counterproductive and could even lead to users actually tapping on the wrong answer as they expect another quest if think the first quest has not really been submitted. Only because I noticed it fast enough, this has not happened to me, but I nearly did so.

**Comment by rugk** [comment]
Also opened a bug there: when (while) the second quest is shown there is no quest icon being displayed for one second or so. So the question (and object selection on the map) is shown, before the icon.

**Comment by rugk** [comment]
Sometimes it is more then one second…

**Comment by matkoniecz** [comment]
> not only because of the delay, but also because it breaks the usual flow of sc

I disagree with this - solving quest for object A, walking to object B, solving quest there and getting again quest for object A (that was hidden due to low priority) would be even worse. At least in my opinion.

**Comment by rugk** [comment]
I also experienced another problem: After one quest is solved, first the next quest is shown and before one can answer it, the same is hidden and shown again (with the quest icon as it seems).

**Comment by rugk** [comment]
To keep one bug in a scope, I opened a different issue for the bug that the quest is shown twice: https://github.com/westnordost/StreetComplete/issues/973

Maybe if the performance is better and this issue there is solved, it is really all to solve this UX problem here. Currently, this feature just often annoys me, but maybe it is really just because I have to answer quests again and have to wait multiple seconds before I can answer. If the quest is shown immediately, that may not be a problem.

But generally, maybe an option in the settings, to deactivate the behaviour, may be useful.

**Comment by westnordost** [comment]
Two things have changed now:
1. opening a quest is much faster now, should be almost instantaneous - thus, opening the next quest as well
2. #973 should be fixed

So, I'll close this issue.
