### ISSUE TITLE
App terminates suddenly

### ISSUE THREAD

**Issue by l00ping** [westnordost/StreetComplete#948]
App v4.0 terminates suddenly without user interaction. It happens while staying in Map view and moving with the phone or rotating it. Sometimes in the end with the android message: "StreetCompleet wurde beendet."

**Comment by ENT8R** [comment]
Well, I don't think that the information you give might be useful... Perhaps @westnordost did already receive a crash report for this issue, but if not, you will maybe need to attach the logcat in oder to debug it correctly.
Was it possible for you to submit a crash report? And which phone and which android version do you use?

**Comment by l00ping** [comment]
Sorry, but I do not know how to make any debugging.

**Comment by ENT8R** [comment]
But you can at least answer my other questions from above, can't you?

**Comment by l00ping** [comment]
bq Aquaria E5 with android 6.0.1;
There was no prompt for a crash report

**Comment by ENT8R** [comment]
Alright... This makes it a little bit harder, because we have no idea what exactly goes wrong and you can't debug it... Maybe you can install [ADB](https://developer.android.com/studio/command-line/adb.html) and follow [this guide](https://developer.android.com/studio/command-line/logcat.html) to create a copy of your log...

**Comment by rugk** [comment]
There are also apps which may dump a logcat.

BTW I think I also experienced this issue, it mostly happens when you turn your phone or so.

**Comment by rugk** [comment]
(And afterwards the black quest rectangle issue appeared once)

**Comment by westnordost** [comment]
This will be the same as #857. This is the only crash I see on Google Play, but it happens very often (~20 times a day).
(https://github.com/tangrams/tangram-es/issues/1772)
