### ISSUE TITLE
Take a picture of this element

### ISSUE THREAD

**Issue by xotgucuni** [westnordost/StreetComplete#952]
### General
Affected tag(s) to be modified/added: [`wikimedia_commons=*`](https://wiki.openstreetmap.org/wiki/Key:wikimedia_commons)
~Question asked~ Prompt shown, I guess?: **Take a picture of …** or **Can you take a picture of …?**

### Checklist
Checklist for quest suggestions (see guidelines):
- [x] 🚧 To be added tag is established and has a useful purpose
- [x] 🤔 Any answer the user can give must have an equivalent tagging (Quest should not reappear to other users when solved by one)
- [x] 🐿️ Easily answerable by everyone from the outside but a survey is necessary 
- [x] 💤 Not an overwhelming percentage of elements have the same answer (No spam)
- [x] 🕓 Applies to a reasonable number of elements (Worth the effort)

Currently, images of elements are quite rare on OSM, but users of OSM could greatly benefit from having more images. Images would improve the UX of map and navigation applications by showing the user what elements look like.

### Ideas for implementation

The user must connect StreetComplete to a Wikimedia Commons account before enabling the quest. The quest opens a camera intent and the user takes a picture. The user can alternatively select "poor photo conditions" if it is foggy or dark outside or whatever, and StreetComplete should offer to temporarily disable the quest. If, for whatever reason, they cannot provide a photo of the element, they can select "can't provide photo". This should behave like the "can't say" option on other quests.

Upon uploading changes, the photo is uploaded to Wikimedia Commons in the user's name. The title of the image should be automatically generated from the name of the element. The element is then tagged with [`wikimedia_commons=*`](https://wiki.openstreetmap.org/wiki/Key:wikimedia_commons), linking it to the image.

Perhaps it would be best to disable this quest from sunset to sunrise.

**Element selection**

It seems like the [query for the wheel chair access quest](https://github.com/westnordost/StreetComplete/blob/master/app/src/main/java/de/westnordost/streetcomplete/quests/wheelchair_access/AddWheelchairAccessBusiness.java) would work well. Also make sure to exclude elements that already have images from the following tags:

- `mapillary=*`
- `flickr=*`
- `wikimedia_commons=*`
- `image=*`

**Proposed GUI** 

Show a large button that opens the camera intent. Once the user has taken the picture, replace this button with a preview of the picture and an "X" button if they want to remove the picture and try again. Hide the options "poor photo conditions" and "can't provide photo" in the "other options" menu.

**Comment by matkoniecz** [comment]
> Not an overwhelming percentage of elements have the same answer (No spam)

How you propose to select objects that are both

- worth photographing
- without existing photo on Wikimedia Commons?

Given effort to implement this, I believe that using https://github.com/EdwardBetts/osm-wikidata to link OSM element and Wikidata elements and https://meta.wikimedia.org/wiki/WDFIST to link Wikidata elements with images on Commons is far more efficient.

Using this tools allows adding several images per minute, far faster than making new images that likely duplicate existing ones and are of worse quality.

**Comment by ENT8R** [comment]
> This should behave like the "can't say" option on other quests

But are you aware that this button adds a new public note to OSM which other mappers should resolve? If there would be such a button which creates a new note all the time the user can't answer the question properly, this will lead to a huge spam of OSM Notes...
And what is your plan in general? Should this quest popup for e.g. every node tagged as bicycle parking? I think this quest would then also be spam to users of SC because this would be a never ending task of taking photos...

**Comment by xotgucuni** [comment]
@matkoniecz:
> In addition, implementing this feature would take significant effort and is not really fitting spirit of the app (at least as I understand it).

That's fair. I just wanted to see what people might think of it.

> without existing photo on Wikimedia Commons?

It shouldn't matter too much whether there are already other photos out there of the element. If someone wants to connect existing photos with OpenStreetMap, then they should do that without StreetComplete, but the vast majority of POIs don't already have photos of them on Wikimedia Commons. Anyways, even a somewhat crappy photo connected to OpenStreetMap would be better than no photo at all.

@ENT8R:
> But are you aware that this button adds a new public note to OSM which other mappers should resolve?

Huh, I was not aware of that. I suppose that would be kind of spammy, so I'm open to suggestions.

> Should this quest popup for e.g. every node tagged as bicycle parking?

I agree that things like bicycle parking would be a bit overkill. I was thinking more along the lines of POIs like restaurants, shops, or libraries, and the [query for the wheelchair access quest](https://github.com/westnordost/StreetComplete/blob/master/app/src/main/java/de/westnordost/streetcomplete/quests/wheelchair_access/AddWheelchairAccessBusiness.java) seemed to work well.

**Comment by ENT8R** [comment]
> I was thinking more along the lines of POIs like restaurants, shops, or libraries—you know, the kinds of things for which you would see images on Google Maps

But then why don't simply use Mapillary? If I want to have street-level imagery I always look there first and to be honest, I have never used the `wikimedia_commons` tag to search street-level imagery...

> Does it add the note by default, or only if the user enters something in the note field?

The option "Can't say" does prompt the user to input a description why he can't answer the question which creates immediately a new OSM note... Otherwise there is a button saying "Just hide this quest" which hides this quest and does not leave a new note...

**Comment by rugk** [comment]
I think the idea may be funny, and not that hard to implement as we already have a picture feature.

Also to not require users to login into Wikipedia Commons, we may use a different tag (`image`?), where we can just choose any location for uploading the picture.

The big question is how to select nodes, which are worth for pictures.
Maybe choose ones with a `wikipedia` tag? These pictures could then also be used for Wikipedia.

---

BTW, if this is implemented, the license of the images must be clear. E.g. the user could just get a message that the image is licensed under CC-BY-SA 4.0 or so. (I think choosing a license may not be the highest priority.) The license should just be compatible to Wikipedia for the reasons stated above.

---

Another thing to discuss is the purpose. Is there a website/app, which shows these?
I only know Osmand, which AFAIK has Mapillary integration (as an integrated plugin) and shows these pictures, but not others AFAIK.

**Comment by xotgucuni** [comment]
Alright, so it seems that people here prefer Mapillary, since it has more established use. That would be fine, too—I just preferred Wikimedia Commons for its integration with Wikidata and Wikipedia. If we use Wikimedia Commons, I agree that CC-BY-SA 4.0 is an appropriate license.

Oh, and an alternative to making the user log in with a Wikimedia Commons account would be to register for a StreetComplete [bot on Wikimedia Commons](https://commons.wikimedia.org/wiki/Commons:Bots) and upload all images through that account.

**Comment by TO-92** [comment]
This is a huge can of worms ...

https://en.wikipedia.org/wiki/Freedom_of_panorama
https://de.wikipedia.org/wiki/Panoramafreiheit

**Comment by rugk** [comment]
Well as for the panorama freedom thing, I think SC does not have to care. At most, notice users they have to abine the law, period.
It's the duty of the user to abine the law, not the one of SC, when taking pictures. (Same as for pictures of people, I.e. personality rights or so, see another issue)
And if needed, reviewers on Wikimedia or wherever it will be uploaded then, can still delete the image.

**Comment by matkoniecz** [comment]
>  And if needed, reviewers on Wikimedia or wherever it will be uploaded then, can still delete the image.

FYI, this approach would probably result in banning app from uploading to Commons (and certainly, after repeated upload with this attitude they would ban individual users).

**Comment by rugk** [comment]
Hmm, okay ensuring the quality if the picture may be hard.
I can only imagine that this quest would then only be shown when the user had reached a certain "level" (star count).

**Comment by goldfndr** [comment]
Notice users that they need to abide the law was rejected in #937.

**Comment by westnordost** [comment]
I have to concur with the other people who posted here. This is too problematic to implement as a quest, i.e. to find a heuristic first what a "photo worthy" object on the map would be.

So, I will close this.

**Comment by TO-92** [comment]
> reviewers on Wikimedia or wherever it will be uploaded then, can still delete the image.

… leaving a broken link behind on OSM, or how would that be handled?

> Notice users that they need to abide the law was rejected in #937.

Of course anybody should always abide by the law, there is no need to tell people that. But then not everybody is a copyright expert.

Iceland for example has a limited freedom of panorama for non-commerical use only. Wikimedia Commons, however, does not offer a NC license. So before uploading a photo of a building or a statue you need to make sure that the copyright has expired, which means you must know (1) who the artist or architect was, and (2) if they are still alive, and if not if they died more than 70 years ago. Who would be able to decide that when they are standing in front of an object and the photo quest pops up? After all, the reasoning behind StreetComplete is to make contributing to OSM easier, not horribly complicated.

I just noticed that while I was typing the above this issue has been closed anyway, but if it had been implemented it should probably have been disabled in countries with problematic legislation.
