### ISSUE TITLE
piste:type quest

### ISSUE THREAD

**Issue by rugk** [westnordost/StreetComplete#956]
### General
Affected tag(s) to be modified/added: [piste:type](https://wiki.openstreetmap.org/wiki/Key:piste:type/)
Question asked: **What type is this piste?**

### Checklist
Checklist for quest suggestions (see guidelines):
- [x] 🚧 To be added tag is established and has a useful purpose, e.g. maps see https://wiki.openstreetmap.org/wiki/Tag:route%3Dpiste#Maps, OsmAnd has a ski mode, etc.
- [x] 🤔 Any answer the user can give must have an equivalent tagging (Quest should not reappear to other users when solved by one), i.e. a piste must has a type AFAIK
- [x] 🐿️ Easily answerable by everyone from the outside but a survey is necessary 
- [x] 💤 Not an overwhelming percentage of elements have the same answer (No spam)
- [x] 🕓 Applies to a reasonable number of elements (Worth the effort)

The last requirement is unclear, because `route=piste` is used much less than `piste:type`so I don't know how much may be missing. (Maybe there is an old tagging?)

### Ideas for implementation

**Element selection:** `route=piste`

**Metadata needed:** no, if there is no piste in one country, there is none

**Proposed GUI:** picture-like quest

A problem could be that it may be seasonal. So maybe it needs to be limited by time, or disabled by default or so… don't know.
On the other hand, we currently have few useful quests in such areas, where this quest may be asked, and actually other quests (like street surface for ways) may not be answerable too, as they are covered by snow.

**Comment by HolgerJeromin** [comment]
I dont think there are many objects which misses this info. But i have not checked it

**Comment by matkoniecz** [comment]
https://overpass-turbo.eu/s/wNh - only 149 cases across the entire Europe, I doubt

>  clock4 Applies to a reasonable number of elements (Worth the effort)

**Comment by rugk** [comment]
Uh, ok. Thanks for checking via the query. As said, taginfo alone could not give me a concluding result.

**Comment by matkoniecz** [comment]
> As said, taginfo alone could not give me a concluding result.

Overpass turbo wizard is quite nice for that - see https://wiki.openstreetmap.org/wiki/Overpass_turbo/Wizard

**Comment by rugk** [comment]
Yeah, I know that, but the query for large areas takes forever. I think overpass is usually not intended for large queries there.

**Comment by matkoniecz** [comment]
> Yeah, I know that, but the query for large areas takes forever. I think overpass is usually not intended for large queries.

See https://wiki.openstreetmap.org/wiki/Overpass_turbo/Wizard#Timeout (I just added this section)

> I think overpass is usually not intended for large queries.

See https://wiki.openstreetmap.org/wiki/Overpass_API#Limitations and https://wiki.openstreetmap.org/wiki/Overpass_API#Introduction

Note especially `You can safely assume that you don't disturb other users when you do less than 10.000 queries per day and download less than 5 GB data per day.` and `Overpass API is most useful when the amount of data needed is only a selection of the data available in the region. `.

With manual in-browser use it is quite hard to overload servers (maybe impossible with nonmalicious use). I added https://wiki.openstreetmap.org/wiki/Overpass_turbo/Wizard#Limitations to cover this.

**Comment by mmd-osm** [comment]
The solution is pretty easy: leave out the bounding box and the query will finish in 600ms in this case!

See https://overpass-turbo.eu/s/wQf

**Comment by mmd-osm** [comment]
>  I added https://wiki.openstreetmap.org/wiki/Overpass_turbo/Wizard#Limitations to cover this.

Can you please remove the numbers on Wizard page and just link to the other page? Otherwise we have to maintain the limits on two different pages, which gets quickly out of hand.

**Comment by rugk** [comment]
Hmm, don't get why this is closed if https://github.com/westnordost/StreetComplete/issues/957 and https://github.com/westnordost/StreetComplete/issues/958, which are very much related are still open?
Okay, this one here is maybe really in 90% of the cases already tagged, but it likely blocks the other two sking-related quests. Hmm…

I am going to reopen this. Feel free to close this, if you think it is really not worth the effort.

**Comment by pietervdvn** [comment]
Here to, I don't think this is useful. Not only because there are extremely few such cases as mentioned earlier, but also for all the same reasons I mentioned here: 

https://github.com/westnordost/StreetComplete/issues/957#issuecomment-632941603

**Comment by westnordost** [comment]
ok
