### ISSUE TITLE
piste:difficulty quest

### ISSUE THREAD

**Issue by rugk** [westnordost/StreetComplete#957]
### General
Affected tag(s) to be modified/added: [piste:difficulty](https://wiki.openstreetmap.org/wiki/Key:piste:difficulty/)
Question asked: **What the difficulty of this piste?**

### Checklist
Checklist for quest suggestions (see guidelines):
- [x] 🚧 To be added tag is established and has a useful purpose, e.g. maps see https://wiki.openstreetmap.org/wiki/Tag:route%3Dpiste#Maps, OsmAnd has a ski mode, etc.
- [x] 🤔 Any answer the user can give must have an equivalent tagging (Quest should not reappear to other users when solved by one), i.e. a piste of a certain type must has a difficulty AFAIK
- [x] 🐿️ Easily answerable by everyone from the outside but a survey is necessary 
- [x] 💤 Not an overwhelming percentage of elements have the same answer (No spam)
- [x] 🕓 Applies to a reasonable number of elements (Worth the effort)

The last requirement is unclear, because `route=piste` is used much less than `piste:difficulty`so I don't know how much may be missing. (Maybe there is an old tagging?)

### Ideas for implementation

**Element selection:** `route=piste` with `piste:type` = downhill, nordic, …

**Metadata needed:** no, if there is no piste in one country, there is none

**Proposed GUI:** picture-like quest

**Attention:** The pictures need to be different in different regions, as e.g. in the US and Europe the signs are completely different. See the wiki.

_Optionally_ it may also set the `colour` tag (for rendering on maps), but maybe these renderers can also determinate it by themselves.

A problem could be that it may be seasonal. So maybe it needs to be limited by time, or disabled by default or so… don't know.
On the other hand, we currently have few useful quests in such areas, where this quest may be asked, and actually other quests (like street surface for ways) may not be answerable too, as they are covered by snow.

**Comment by HolgerJeromin** [comment]
I dont think there are many objects which misses this info. But i have not checked it

**Comment by rindlerblabla** [comment]
And piste:type=nordic doesn't have difficulty specified. For piste:type=nordic it would make more sense to ask for grooming, oneway or whether it's lit.

**Comment by rindlerblabla** [comment]
The reason why I edited my post is because piste:type=difficulty isn't as used in real life for piste:type=nordic as it for downhill, so I think nordic skiing should be excluded as there will be no hints in markers or anything else along the route.

**Comment by matkoniecz** [comment]
https://overpass-turbo.eu/s/wNq found 1000+ plus across Europe

**Comment by rugk** [comment]
Okay, that seems to be enough.

**Comment by matkoniecz** [comment]
https://wiki.openstreetmap.org/wiki/Key:piste:difficulty

What is the symbol for piste:difficulty	expert in Europe outside Alps and Scandinavia? Or is it unused in other countries?

**Comment by matkoniecz** [comment]
@rugk Is this going to be surveyable during summer? Is it possible that routes will be marked only during winter?

**Comment by HolgerJeromin** [comment]
> Is it possible that routes will be marked only during winter?

The way itself is only marked in winter, but the main direction signs (at lift stations) should be visible the whole year.

**Comment by rugk** [comment]
Anyway, I would only ask this during winter times… :thinking:

**Comment by HolgerJeromin** [comment]
> Anyway, I would only ask this during winter times… 🤔

Attention: Winter can be in June depending on your latitude :)

**Comment by pietervdvn** [comment]
Hey,

I hate to be this person, but I don't think that this quest is very useful for downhill skiing.

- According to taginfo, 63% of all objects having 'piste:type' do have a 'piste:difficulty'. I suspect that this is way more for downhill skiing.
- Ski piste mapping is better done at the hotel using a decent computer and editor which can edit geometry, with the information (and thus the official ratings) of the ski resort map nearby. It can be tricky to figure out where every piece of ski piste is going. Also, even on an expert route, some parts could be novice difficulty and should be marked, a.g. if a novice route goes with the expert route for a few meters. Marking these few meters as 'expert' too breaks routing for the novices, as they will not be able to cross this little part
- The main problem for ski routing is that often, ski pistes are not well-connected to the lifts. This again is something that streetcomplete can not (and should not) attempt to solve
- It is kinda dangerous to constantly stop to streetcomplete - skiing can be quite high-speed - not to mention that using a touchscreen in freezing temperatures with gloves isn't easy too
- In practice, there are very few parts where difficulty is missing. 

For reference, I'm the one who made the skiing routeplanner for OsmAnd, so I do know what I'm talking about. It could be worth it for nordic skiing though - I don't have any experience that discipline.

**Comment by westnordost** [comment]
Ok, let's close this then. In any case, it would have had a very low importance.
