### ISSUE TITLE
number/name quest for piste

### ISSUE THREAD

**Issue by rugk** [westnordost/StreetComplete#958]
### General
Affected tag(s) to be modified/added: [piste:name](https://wiki.openstreetmap.org/wiki/Key:piste:name/)/usual name tag
Question asked: **What the name/number of this piste?**

### Checklist
Checklist for quest suggestions (see guidelines):
- [x] 🚧 To be added tag is established and has a useful purpose, e.g. maps see https://wiki.openstreetmap.org/wiki/Tag:route%3Dpiste#Maps, OsmAnd has a ski mode, etc.
- [x] 🤔 Any answer the user can give must have an equivalent tagging (Quest should not reappear to other users when solved by one), i.e. a downhill piste must has a number, at least in Germany, AFAIK
   even if not, maybe the `noname` tag can be set, as in the street name quest
- [x] 🐿️ Easily answerable by everyone from the outside but a survey is necessary (usually labeled)
- [x] 💤 Not an overwhelming percentage of elements have the same answer (No spam)
- [ ] 🕓 Applies to a reasonable number of elements (Worth the effort) (needs to be determinated)

### Ideas for implementation

**Element selection:** `route=piste` with `piste:type` = downhill, (nordic?), …

**Metadata needed:** no, if there is no piste in one country, there is none

**Proposed GUI:** similar to street name quest, for downhill maybe only offer number input by default (similar to house number quest) as they may not always have a real name

A problem could be that it may be seasonal. So maybe it needs to be limited by time, or disabled by default or so… don't know.
On the other hand, we currently have few useful quests in such areas, where this quest may be asked, and actually other quests (like street surface for ways) may not be answerable too, as they are covered by snow.

**Comment by rugk** [comment]
BTW I don't know whether `name` or `piste:name` is preferred. The original [proposal](https://wiki.openstreetmap.org/wiki/Piste_Maps) lists it, but iD e.g. does not show the `piste:name` but only allows editing `name` by default.

**Comment by HolgerJeromin** [comment]
If the piste shares a highway osm object the name is not for the piste.

**Comment by rugk** [comment]
Okay, so for this quest that may not be a problem: the quest may only add `piste:name` and ignore ways with `name` tag, so there cannot be potential problems.

**Comment by rindlerblabla** [comment]
I think it's better to add a name to the route relation itself. piste:name is less common. As long as you don't add the name tag to different highways I don't see a problem.

**Comment by rindlerblabla** [comment]
(That is for piste:type=nordic where the route can be shared with normal highways (paths/tracks). Don't think it will be a problem adding a name to piste:type=downhill even if it's not a relation.)

**Comment by HolgerJeromin** [comment]
Sled pistes are often footways, too

**Comment by pietervdvn** [comment]
Here too, I propose this to be closed for the same reasons as https://github.com/westnordost/StreetComplete/issues/957#issuecomment-632941603

Not to mention that indeed ski pistes often share their tracé with an underlying road.

**Comment by westnordost** [comment]
ok
