### ISSUE TITLE
Crashes on multi-window usage

### ISSUE THREAD

**Issue by RubenKelevra** [westnordost/StreetComplete#961]
Currently SC seems to be very unstable with multi-window usage. I've sent 2-3 crash reports to you.

Since there are some UI assumption which also break, since the window is differently dimensioned, maybe blocking SC from beeing used in multi-window mode would be the best solution for now?

Running Android 8.0 on a OnePlus 5T - full hd 18:9 screen  vertically

**Comment by westnordost** [comment]
SC 4.x is quite unstable altogether whivh is due to unfixed crashbugs in some dependencies. I'll downgrade these for the 4.1 update.
I did not see anything related to multiwindow.

On 9 March 2018 08:26:34 CET, "@RubenKelevra" <notifications@github.com> wrote:
>Currently SC seems to be very unstable with multi-window usage. I've
>sent 2-3 crash reports to you.
>
>Since there are some UI assumption which also break, since the window
>is differently dimensioned, maybe blocking SC from beeing used in
>multi-window mode would be the best solution for now?
>
>Running Android 8.0 on a OnePlus 5T - full hd 18:9 screen  vertically
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/westnordost/StreetComplete/issues/961

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by RubenKelevra** [comment]
@westnordost well, I've sent some crash reports to you via the report function, it might not read that way, but it can be easily reproduced on my device. That's why I asked to just forbid the usage, which other apps, like Netflix do.

**Comment by RubenKelevra** [comment]
I have to update my statement, just saw the new 5.0b1, this bug has actually been fixed in it. 🙂
