### ISSUE TITLE
No manual upload button when autoupload is disabled

### ISSUE THREAD

**Issue by rugk** [westnordost/StreetComplete#963]
I just tried something and wonder how users should upload quests, when auto-upload is disabled?

The previous "upload now" button does not appear when the setting is disabled, so I wonder how that should work then.

**Comment by ENT8R** [comment]
It is done via the upload button in the title bar:
![32813109-52ef2222-c95d-11e7-9fa9-5db913feadf4](https://user-images.githubusercontent.com/25306497/37238990-bd402560-2432-11e8-97a3-f6a2a022e723.png)
(The right button)
But this was already discussed in other issues so you should know that, should not you?

**Comment by rugk** [comment]
Ah, so it does indeed work like that?
As you can see at #945 I did not expect to see that. It is kinda confusing, as you can see.
I did not really expect that this button does something and I also could not find out, as the feedback when clicked did not really indicate success.
There is an animation, yes, but it e.g. does not immediately count down or so.

So it could maybe just show a toast notification, if the upload was triggered manually.

**Comment by westnordost** [comment]
See #944
