### ISSUE TITLE
Add building roof rendering

### ISSUE THREAD

**Issue by gappleto97** [westnordost/StreetComplete#970]
Currently all buildings render with a flat roof. This results in some odd things, like the Superior Dome appearing as a cylinder. It would be cool if buildings had their roof accurately rendered. It would be even cooler if this could happen live as you complete the relevant quest.

**Comment by matkoniecz** [comment]
See https://github.com/westnordost/StreetComplete/blob/master/CONTRIBUTING.md

> Map style used by StreetComplete is developed as a separate project and related issues should be reported there.

That links to https://github.com/ENT8R/streetcomplete-mapstyle

**Comment by matkoniecz** [comment]
Yeah, but it was faster to copy link.

**Comment by ENT8R** [comment]
I already thought about that feature some time ago, but I don't even know whether this would be possible at all using tangram-es... For more information: see this issue of the JS version of tangram: https://github.com/tangrams/tangram/issues/316
I don't think that this would be easy to do and maybe even needs changes in the source of tangram-es...

**Comment by westnordost** [comment]
As @ENT8R said, that would be up to the people at tangram(-es). But tangram's future is unclear, I think they have barely enough active people to take care of bugs and the sort. I don't think a feature like that is realistic unless they get an influx of motivated C++ programmers.
