### ISSUE TITLE
Automatically opened next quest for object hides in between/opens twice

### ISSUE THREAD

**Issue by rugk** [westnordost/StreetComplete#973]
Split out of https://github.com/westnordost/StreetComplete/issues/947

> After one quest is solved, first the next quest is shown and before one can answer it, the same is hidden and shown again (with the quest icon as it seems).

Best reproducible with street quests. When you solve one thing, another thing (e.g. street surface quest) pops up and you answer it (if you are fast). But after you did so, it is hidden again and shown, so you need to re-answer that.
This results in the fact that I often already solve (click the answer of) the new quest when shown first, click on "OK", but often when I click "OK" the quest is already shown the second time and thus the input is cleared. So I often get the message that the form is empty and I need to enter my input yet again.

LineageOS 14.1
SC 4

**Comment by westnordost** [comment]
I found a problem there. I think it should be fixed now.
