### ISSUE TITLE
Unclear UI of implicit/explicit permission for sidewalk/cycleways

### ISSUE THREAD

**Issue by rugk** [westnordost/StreetComplete#978]
You can select these two things in StreetComplete for the bicycle quest:

![using](https://user-images.githubusercontent.com/11966684/37338846-ef55923c-26b8-11e8-9a0a-d1bef28705e3.jpg)

AFAIK the right thing is not (legally) possible - in Germany, at least. The reason is just that there has to be a sign (or something else) allowing you to use a sidewalk with a bike. (this is "explicit", IMHO) Without a sign, you just are not allowed to use the sidewalk. This is not possible if you abide the law. Also, BTW, I don't know how a user may judge how such a "implicit permission" may be determinated/seen by the user. If there are no "explicit" signs/markings/..., how is the user supposed to see whether using the sidewalk is allowed?

**Comment by matkoniecz** [comment]
> If there are no "explicit" signs/markings/..., how is the user supposed to see whether using the sidewalk is allowed?

For example In Poland one is allowed to cycle on footways wider than 2m along roads with maxspeed greater than 50 km/h.

**Comment by westnordost** [comment]
Blue 🚶sign with a white rectangular sign below it, saying "🚲 free". I'm sure you've seen them.

On 13 March 2018 12:25:10 CET, rugk <notifications@github.com> wrote:
>You can select these two things in StreetComplete for the bicycle
>quest:
>
>![using](https://user-images.githubusercontent.com/11966684/37338846-ef55923c-26b8-11e8-9a0a-d1bef28705e3.jpg)
>
>AFAIK the right thing is not (legally) possible - in Germany, at least.
>The reason is just that there has to be a sign (or something else)
>allowing you to use a sidewalk with a bike. (this is "explicit", IMHO)
>Without a sign, you just are not allowed to use the sidewalk. This is
>not possible if you abide the law. Also, BTW, I don't know how a user
>may judge how such a "implicit permission" may be determinated/seen by
>the user. If there are no "explicit" signs/markings/..., how is the
>user supposed to see whether using the sidewalk is allowed?
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/westnordost/StreetComplete/issues/978

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by rugk** [comment]
> For example in Poland one is allowed to cycle on footways wider than 2m along roads with maxspeed greater than 50 km/h.

Okay, such a thing does not exist in Germany. BTW, do you think all users know this and select the right thing? They also have to estimate the width of the way.

> Blue 🚶sign with a white rectangular sign below it, saying "🚲 free". I'm sure you've seen them.

Of course, yes. [This one](https://www.elektrobike-online.com/know-how/pedelec-und-fahrrad-wissen/wichtige-verkehrsschilder.736938.410636.htm#10):
![](https://www.elektrobike-online.com/sixcms/media.php/6/UB-Verkehrsschilder-_2000px-Zusatzzeichen_1022-10-580px.jpg)

However, this is still "explicitly using the foodway", IMHO.
I know now what these mean, but when the user just reads "explicitly marked vs not explicitly marked", I cannot see how they get that the difference are actually two street signs.

It's the difference between the ":bike: free" and [these blue ones](https://github.com/westnordost/StreetComplete/issues/527) (whether segregated or not...).

---

So looking into the code, I see that, the sidewalk ("explicit using") answer also adds `segregated=no`:

https://github.com/westnordost/StreetComplete/blob/a1bceeacffeb6699c8dcc53bcabccb2b8bdbf139/app/src/main/java/de/westnordost/streetcomplete/quests/bikeway/AddCycleway.java#L102

I think this is wrong. The user has no way to select "segregated=yes". So what are they supposed to select when there is a segregated way?

Also, should not it add `...:bicycle=designated` somehow, here?
https://github.com/westnordost/StreetComplete/blob/8dd6cb0076d2455567fc38e8cebe01c3e0cec87b/app/src/main/java/de/westnordost/streetcomplete/quests/bikeway/AddCycleway.java#L133-L137

I.e. `changes.add("sidewalk:" + side.value + ":bicycle", "designated");`.

So I re-read [the wiki](https://wiki.openstreetmap.org/wiki/DE:Key:cycleway) and the important part (for Germany) is here:
> Die Unterscheidung zwischen Radwegen mit und ohne Benutzungspflicht kann nach der DE:Bicycle/Radverkehrsanlagen kartieren Lübecker Methode, in Deutschland und Polen inzwischen von einem großen Teil der Mapper verwendet, wiefolgt dargestellt werden:
> * Benutzungspflicht: cycleway:right:bicycle=designated
> * keine Benutzungspflicht cycleway:right:bicycle=yes

The whole site https://wiki.openstreetmap.org/wiki/DE:Bicycle/Radverkehrsanlagen_kartieren_L%C3%BCbecker_Methode is quite good.

----


However, I think we should in any case first ignore any `segregated` stuff and then just also ask the segregated quest (https://github.com/westnordost/StreetComplete/issues/527) for these lanes.
I.e. when the user selects "explicitly shared", we do not add segregated values, but ask for that in another quest.

**Comment by westnordost** [comment]
Hold your horses, mate.

> I think this is wrong. The user has no way to select "segregated=yes". So what are they supposed to select when there is a segregated way?

When the sidewalk is segregated between cyclists and pedestrians, it is a **cycleway track**, what else? If a surveyor sees something segregated, then he will click on the cycle track icon. Why do you think a user would click on the "must/can use sidewalk" button?

> Also, should not it add ...:bicycle=designated somehow, here?

No, only if there would be a blue sign with a cycle on it. The quest does not ask for the (blue) signs, it asks for cycleways/sidewalks. There might as well be a cycleway or clearly a broad sidewalk where it is evident from survey that it is for cyclists without these signs. (Especially if you think outside-Germany)
To be clear: The quest only asks for the physical presence of cycleways (and in what form), not whether their use is obligatory.

**Comment by westnordost** [comment]
By the way, the second case ("SIDEWALK_OK") also and in particular covers those cases where the sidewalk is broad enough or undeveloped enough to be usable by cyclists and in reality also used that way (can only be found out through survey/local knowledge).

In Germany, that would be in certain rural areas where i.e. the sidewalk is sometimes not even paved but just a (unsigned) way beside the road.
And outside "everything must be regulated"-Europe, almost every sidewalk, if usable (broad enough etc), would qualify as such.

**Comment by rugk** [comment]
Okay, so if I understand it correctly, this quest:
* must not tag the permission for bikes
* must not tag, whether the track is segregated or not

So the second thing it currently violates, because `SIDEWALK` tags this.

> When the sidewalk is segregated between cyclists and pedestrians, it is a cycleway track, what else? If a surveyor sees something segregated, then he will click on the cycle track icon.

So this?
![bike](https://user-images.githubusercontent.com/11966684/37456734-5bddd31e-2840-11e8-9d02-bc02d2885f57.png)

So, IMHO a segregated bicycle/pedestrian would look this this:
![37338846-ef55923c-26b8-11e8-9a0a-d1bef28705e3](https://user-images.githubusercontent.com/11966684/37458814-7aa7fcb0-2846-11e8-9028-a651dd72addf.jpg)

Because of course, it is segregated on the _track_, not on the lane.

**Comment by westnordost** [comment]
No, the user will click on "Radweg"

On 15 March 2018 11:48:03 CET, rugk <notifications@github.com> wrote:
>Okay, so if I understand it correctly, this quest:
>* must not tag the permission for bikes
>* must not tag, whether the track is segregated or not
>
>So the second thing it currently violates, because `SIDEWALK` tags
>this.
>
>> When the sidewalk is segregated between cyclists and pedestrians, it
>is a cycleway track, what else? If a surveyor sees something
>segregated, then he will click on the cycle track icon.
>
>So this?
>![bike](https://user-images.githubusercontent.com/11966684/37456734-5bddd31e-2840-11e8-9d02-bc02d2885f57.png)
>
>So, IMHO a segregated bicycle/pedestrian would look this this:
>![37338846-ef55923c-26b8-11e8-9a0a-d1bef28705e3](https://user-images.githubusercontent.com/11966684/37458814-7aa7fcb0-2846-11e8-9028-a651dd72addf.jpg)
>
>Because of course, it is segregated on the _track_, not on the lane.
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/westnordost/StreetComplete/issues/978#issuecomment-373335093

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by rugk** [comment]
Ah… Of course, you are right! :man_facepalming: 

This also explains the segregated=no because when bikers can use the footway, there obviously of course is no sidewalk.

So okay let's get the back to the origin issue. The difference between "explicitly" and "implicitly" using the sidewalk.

**Comment by westnordost** [comment]
I would merge these two options into one "cyclists can and may use sidewalk" but I think it is not possible to tag it that way.

Basically explicitly-sidewalk means that it is usually obligatory for cyclists to use it (i.e. blue sign) while the other should just mean that cyclists informally (or formally, see "bicycle frei" sign) use it.

On 15 March 2018 18:22:29 CET, rugk <notifications@github.com> wrote:
>Ah… Of course, you are right! :man_facepalming: 
>
>This also explains the segregated=no because when bikers can use the
>footway, there obviously of course is no sidewalk.
>
>So okay let's get the back to the origin issue. The difference between
>"explicitly" and "implicitly" using the sidewalk.
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/westnordost/StreetComplete/issues/978#issuecomment-373456819

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by rugk** [comment]
And here we are at the problem that we do not want to tag the legal status of these tracks.

Maybe the German translation with "dürfen" in the implicit case is bad, because this implies some must/must not/allowed/legal stuff. On the other hand the left thing only 
Maybe rather use ":bike: may drive here" or ":bike: could drive here" or :bike: is not forbitten to drive here". Huh, kinda hard this formulations.

Basically for we need:
* for the left thing: a definition that includes "allowance" (i.e. what "dürfen" is on the right side currently)
* for the right thing: a less strict definition of allowance or just not-disallowed or just "possible to drive there"

We do not need:
* any reference to markings (in general), because both can be marked -> what the left option currently says

So solutions:
* rename that labels. IMHO that's kinda hard as you can see above.
* or maybe the best way, at least for Germany and where this sign exists: Just show the street signs! Just include them in the sidewalk. This would make it really clear and in your source code, you also link to them.
* On the other hand for Poland the situation (this width things) may be perfect (unless this ":bike: free" sign is also possible there): When wider than wm without markings the right thing clearly applies.

So IMHO, let's introduce another metadata.

**Comment by rugk** [comment]
BTW another problem: ":bike: free" does not exclude a real bike lane or so.

**Comment by westnordost** [comment]
> or maybe the best way, at least for Germany and where this sign exists: Just show the street signs! Just include them in the sidewalk. This would make it really clear and in your source code, you also link to them.

I think there is already a ticket for that. Labeled as [Enhancement], low prio (for me).

For cyclists, by the way, the left and right quite makes a difference, at least in Germany. Because the left would usually be obligatory, so the cyclists may not use the road. This is usually a bad thing.
The right picture on the other hand just speaks about the eligibility (and legality) of the sidewalk to be used by cyclists. But they don't have to use it.

**Comment by westnordost** [comment]
So, what about htis now?

**Comment by rugk** [comment]
> Labeled as [Enhancement], low prio (for me).

You do not have a [low prio tag](https://github.com/westnordost/StreetComplete/labels).

And BTW, no. I [cannot find this issue](https://github.com/westnordost/StreetComplete/issues?q=is%3Aissue+cycleway+label%3Aenhancement+is%3Aopen).

Also it is just about the cycleway quest here. A simple icon change for Germany, at least. That is what I'd propose.

> Because the left would usually be obligatory, so the cyclists may not use the road. This is usually a bad thing.

BTW, I'd really prefer a real cycleway (which I have to use) instead of a bad (not smooth) sidewalk, which has been made for passengers, not cyclists - or, to drive on the road.

**Comment by westnordost** [comment]
If I would add the explicit signs in Germany, then people will be confused about what to select for the kind of sidewalks where a surveyor can assume that implictly cyclists are allowed there ( https://github.com/westnordost/StreetComplete/issues/978#issuecomment-373205031 ) - where there are no signs.
So, I will close this one because the solution of adding an overlay with the signs does not solve the uncertainty there.
