### ISSUE TITLE
make quests possible as plugins

### ISSUE THREAD

**Issue by Haikuch** [westnordost/StreetComplete#98]
because there are a lot of questions about new quests, maybe you could make it possible to add them as plugins? So other developers could contribute quest code easily and users could activate/deactivate them. Might be more complicated to make this possible, but would provide benefits in the long run.

**Comment by lightonflux** [comment]
> would provide benefits in the long run.

I would like to hear why it would be beneficial. Because i don't see the benefit of adding a plugin API now. The project is still very young and open to PRs.

**Comment by CloCkWeRX** [comment]
#93 is basically the same idea; but for *when there are multiple highly similar quests that are more or less copy/paste of each other*

**Comment by savissimo** [comment]
@lightonflux The project is open to PRs, true, but you have to review them, approve them, merge them, and release. A plugin system would allow you to focus on the core, or on the plugins that you love and endorse, while other developers fill in the blanks with their own expansions.

**Comment by matkoniecz** [comment]
@Haikuch Can you give example of Android app that supports plugins? How it is supposed to work - installing additional apps?

**Comment by HolgerJeromin** [comment]
http://yatse.tv/ has own plug in  apps, same with OsmAnd

**Comment by Haikuch** [comment]
@matkoniecz to be honest, Iam not very experienced with mobile apps. But Iam sure you will find suitable examples

**Comment by gappleto97** [comment]
Termux is another good example of how to use plugins. Same with Tasker, though that's closed source.

**Comment by HolgerJeromin** [comment]
Perhaps it would be possible to have a generic quest infrastructure so (most) quest are defined only with a (JSON?) config file with linked images.

With this everyone can add own quests similar to the way vespucci and josm handles tag Presets. 

No need to have programming skills for most quests. And not all quests have to be maintained by westnordost

**Comment by westnordost** [comment]
I do not plan to implement this in the near future. 

[You can add simple quests quite easily in Java](https://github.com/westnordost/StreetComplete/blob/master/app/src/main/java/de/westnordost/streetcomplete/quests/bus_stop_shelter/AddBusStopShelter.java) and for more anything more complex, you need Java anyway.

**Comment by rugk** [comment]
From https://github.com/westnordost/StreetComplete/issues/196:
From https://github.com/westnordost/StreetComplete/issues/192#issuecomment-299730451 I see how it can be useful to make it possible for contributors to add easy quests **without coding**. That's very important and can be a good argument to find contributors.
The aim could be to get it working as in [HTTPS Everywhere](https://github.com/EFForg/https-everywhere/), where you have many, many contributors adding XML files.

So what could be covered?
* Simple yes/no questions. (https://github.com/westnordost/StreetComplete/issues/107, e.g.)
* A generic image.
* Simple questions with text input connected to a tag.

How?
Your decision: JSON, XML, …
The only thing I'd suggest is to put one new quest type into a new file, so we won't have crazy big files, disputes how to sort/order entries or maybe even merge conflicts.

Also:
* A guide or a small tool making it even easier to create a quest.
* Example quests. (or just in the guide if it is easy)
* A very clear explanation what quests are wanted and what not. And maybe suggest to open an issue before, so one can check whether it is wanted first.

**Comment by rugk** [comment]
> You can add simple quests quite easily in Java and for more anything more complex, you need Java anyway.

So if you do not implement it (yet) at least add a CONTRIBUTING.md (completely missing currently) and point to some examples and add some more explanation useful to newbie-contributors with not many coding skills.
If one can create easy quests without nearly no java knowledge (e.g. by copying templates for common quest types), this would already fullfill my idea.

**Comment by Haikuch** [comment]
> The aim could be to get it working as in HTTPS Everywhere, where you have many, many contributors adding XML files.

Thats what I also had in mind when I started this issue

**Comment by HolgerJeromin** [comment]
We can compare it to the presets system which josm and vespucci uses.

**Comment by westnordost** [comment]
In the meantime, I created a CONTRIBUTING.md

I will gradulally refine the quests, making it easier to implement. Next on my list is:
* remove the priority defined in the java class, instead have a simple order
* remove the necessity to edit and export the icon sheet but instead auto-generate the icon sheet

However, as I mentioned earlier, enabling defining quests in a JSON file or similar is not planned in the near future.

**Comment by rugk** [comment]
Hmm, maybe open a new issue for an API? So other apps, could "inject" new quests into SC.

That is different from what is discussed here, as it has mainly been discussed, that we could offer a special format as JSON or so. An API for other apps could however be better defined and allows more flexible quests.
