### ISSUE TITLE
Add update menu item to about window

### ISSUE THREAD

**Issue by my-na-me** [westnordost/StreetComplete#980]
Hi together.

I usually don't use a google-play account. That’s why I’m happy to be able using Streetcomplete in general by installing direct apk file. For apk download source I’m using link[1].

I would like to have a new additional menu item at "About StreetComplete" menu for manual update/download to link [1] in case of potential Streetcomplete version update.
So maybe similar to menu items which are currently available like "License" / "Source Repository" / "Report error".

What do you think about this idea? 

[1] https://github.com/westnordost/StreetComplete/releases

The wording is a first idea, please modify to corporate wording.

![about sc](https://user-images.githubusercontent.com/27923772/37555687-b1366a90-29eb-11e8-83be-dd078212f042.jpg)

**Comment by TomJansen** [comment]
You can use fdroid as an alternative to the play store, it only contains open-source apps. StreetComplete is in fdroid too.

**Comment by ENT8R** [comment]
I agree with @TomJansen. This would also not work for users which have installed the app via Google Play or F-Droid and then use a different APK with a different signature from the Github Release section. (The user would need to deinstall and then reinstall the app instead of simply updating it...)

**Comment by my-na-me** [comment]
so it sounds like there 3 diffrent type of user groups:
a) direct apk installer
b) fdroid user/updater
c) google play user/updater
Maybe the request should be modified in some way

"deinstall and then reinstall the app instead of simply updating it"
It seems the same I have to do when I switch to fdroid...

**Comment by westnordost** [comment]
Yeah, if you want automatic updates, you can use F-Droid.

**Comment by ENT8R** [comment]
> Maybe the request should be modified in some way

I don't know how this can be done... You can have both Google Play and F-Droid installed on your phone, so this can not be differenciated...

**Comment by my-na-me** [comment]
No, I don't what to have automatic updates. I'm checking for updates periodically by myself:
"https://github.com/westnordost/StreetComplete/releases"
I want to have more convenient check procedure by using a internal the app-about item which sends me direct to "https://github.com/westnordost/StreetComplete/releases" so I can check manual if there is a new apk available. The final installation I want to do also manual by downlaod the apk using the preinstalled browser for manual installation at next momemt (after download)...

Wording modified, see picture below...

But in meantime I found a workaround for this. I can also press to "Report error" in "about screen", which opens a browser window and sends me to "https://github.com/westnordost/StreetComplete/issues". From there I have only 2 more clicks to "https://github.com/westnordost/StreetComplete/releases"

![about sc2](https://user-images.githubusercontent.com/27923772/37556526-e4543b08-29f7-11e8-8500-2d700666167c.jpg)

**Comment by rugk** [comment]
@my-na-me You don't get automatic updates by default completely. (And BTW, why would not you want automatic updates?)
So the solution to your problem:
1. Go to https://f-droid.org/. Download and install the F-Droid APK.
2. Search for Streetcomplete in the app (or click [this link](https://f-droid.org/packages/de.westnordost.streetcomplete/)) and install the app.
3. Unfortunately, you need to setup StreetComplete there again.
4. Uninstall the GitHub version.

You now do not even have a button in F-Droid for checking the app, but it automatically notifies you, when there are updates. (You can even configure it to automatically download these, etc.) That is much more convenient than what you propose here, **and** as an addition you also have access to a lot of other great FLOSS apps in F-Droid. Check it out!

**Comment by HolgerJeromin** [comment]
I think a list of bookmarks in the phone browser could be an idea for @my-na-me too :-)
