### ISSUE TITLE
allow to select osm language that is displayed for quests

### ISSUE THREAD

**Issue by seb-1204** [westnordost/StreetComplete#984]
My phone language is set to english.
I am adding details in areas where english is not the primary language.
E.g. when adding opening times the app asks 'what are the opening times of <text in non english>'.
It would be good it the preferred osm language tag can be set in preferences.
The app should then load the en. Name tag (if it is set to english) and not the local one e.g. fr, ru ,ko.

**Comment by rugk** [comment]
Okay, so if I understand it correctly:
* phone: English
* StreetComplete UI: English
* Country: non-English
* Name shown for quests, where element is named: localized name (i.e. French or so)

If that is the case, this is, IMHO, clearly a bug. It does not need an extra settting for that. IMHO the app should always fetch/use the names of your preferred locale (if available) and not the one where the country is.
It _may_ help sometimes to see the localized version (if the sign outside only shows it), but I'd say if the object actually has international names (in other languages) then they are likely to be known when you are there, or, you can see them from the outside (FWIW the mappers, who added the names, also had to get them from somewhere…).

**Comment by westnordost** [comment]
It is not a bug, the app simply shows whatever is seen in the name tag. This could be changed, but that the name is displayed at all has the reason to help you find it, i.e. that you can spot it by looking for the sign.

What is the reason that you want to see it in the language set on your phone? Do you have an example of where it actually happened to you where it would have been more helpful than the "main" name?

Often, the localized names are given on the sign, but there is no guarantee for that. Sometimes, especially for things like tourist attractions or even street names, it may just be a translation. So in these cases I imagine to show the localized names would be rhe opposite of helpful.

On 22 March 2018 23:47:07 CET, rugk <notifications@github.com> wrote:
>Okay, so if I understand it correctly:
>* phone: English
>* StreetComplete UI: English
>* Country: non-English
>* Name shown for quests, where element is named: localized name (i.e.
>French or so)
>
>If that is the case, this is, IMHO, clearly a bug. It does not need an
>extra settting for that. IMHO the app should always fetch/use the names
>of your preferred locale (if available) and not the one where the
>country is.
>It _may_ help sometimes to see the localized version (if the sign
>outside only shows it), but I'd say if the object actually has
>international names (in other languages) then they are likely to be
>known when you are there, or, you can see them from the outside (FWIW
>the mappers, who added the names, also had to get them from
>somewhere…).
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/westnordost/StreetComplete/issues/984#issuecomment-375482316

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by rugk** [comment]
Ah okay, so it does not even handle `name:xy` (like `name:de` or so). Okay, then call it enhancement…

**Comment by westnordost** [comment]
Well, as said, I would want to hear a good reason to change the current behavior.

**Comment by matkoniecz** [comment]
I have no experience in using in situation like this but I expect to prefer names as displayed on signs (so name rather than name:my_language).
