### ISSUE TITLE
App not downloading map anymore

### ISSUE THREAD

**Issue by fnordson** [westnordost/StreetComplete#987]
My app is not downloading new map tiles anymore.
I have the newest app version from F-Droid, I have Android 7.1.1
Tried: deleting cache, restarting app, restarted phone, WiFi/Data connection. 

There is a map available if I zoom out quite far but this one is missing tiles also and not downloading.
Quests are available. GPS is working too. 

Any ideas what I could do?

**Comment by ENT8R** [comment]
How far did you approximately zoomed in? Can you see the house numbers? And did you also waited some time to see what happens then? Maybe your connection is not the best and can't handle large map tiles...

**Comment by ENT8R** [comment]
You are right. I just tested it and there is really no map at some kind of zoom level. Maybe this is an issue with the tile server @Akasch?

**Comment by Akasch** [comment]
Yes It is a problem with the server, I am on it to resolve it. The Database crashed because the Hard disk was full. Should be up again soon.

**Comment by Akasch** [comment]
Working again.

**Comment by fnordson** [comment]
Can confirm. Everything working now. Thank you :)
