### ISSUE TITLE
Use GPS for getting direction when moving

### ISSUE THREAD

**Issue by rugk** [westnordost/StreetComplete#988]
Sometimes the blue circle points directly in the wrong direction when I am moving fast (tram e.g.). In such a case, why not better do it like most navigation systems and get the direction from the change of the GPS position, where you can easily calculate the direction from.

And when you are moving in a fast way, that is much more accurate than the compass/gyroscope or similar things.

**Comment by westnordost** [comment]
the blue triangle is showing not the movement direction but the view direction.

**Comment by rugk** [comment]
Mhh okay, but that does not work properly there, often. So it might be an idea to change that if you move fast… But mhh, maybe not.

**Comment by klawdhfzasjhaa** [comment]
Would you please consider reopening? Also see #1040.
The current behavior feels unnatural when moving. Most of the time I'm busy turning and spinning the map so it fits my view angle. Using the "standard" movement following using GPS would also improve user experience when using Street Complete while being in the bus or on the passenger seat.

I talked to some of my friends who I recommended the app to. They also find current compass mode irritating.

If needed, I could do a little screencast to illustrate the issue further.

**Comment by rugk** [comment]
Well… also see https://github.com/streetcomplete/StreetComplete/issues/1040, that is open at least and covers the same topic, IMHO. :smiley: 
Also people also explained other use cases where the current behavior does have downsides.
