### ISSUE TITLE
Quest: Is bus/tram stop elevated?

### ISSUE THREAD

**Issue by rugk** [westnordost/StreetComplete#989]
### General
Affected tag(s) to be modified/added: [???](https://wiki.openstreetmap.org/wiki/Key:)
Question asked: **Is bus/tram stop elevated?**

The "tactile paving" quest for SC is already well known and likely quite useful. However, I think we can map more useful information for some other ♿️/ 🚲/... users.

E.g. whether the tram stop/bus is lowered, so you can go in easily. Some tram operators even show these information on their plans.

However, I have no idea whether there is a tag for this or how to tag it. That's why I have to propose this without a clear tag in mind.
If there should really be none, maybe let's introduce one. I think this information is useful - potentially even more useful than tactile paving information - but it's a useful for a different user base, so it's hard to compare.

### Checklist
Checklist for quest suggestions (see guidelines):
- [ ] 🚧 To be added tag is established and has a useful purpose (purpose yes, tag: no idea?)
- [x] 🤔 Any answer the user can give must have an equivalent tagging (Quest should not reappear to other users when solved by one)
- [x] 🐿️ Easily answerable by everyone from the outside but a survey is necessary (Usually you see whether the stop is high enough.)
- [x] 💤 Not an overwhelming percentage of elements have the same answer (No spam)
- [x] 🕓 Applies to a reasonable number of elements (Worth the effort)

### Ideas for implementation

**Element selection:** as tactile paving for bus/tram

**Metadata needed:** maybe

**Proposed GUI:** yes/no

**Comment by ENT8R** [comment]
The tag you are looking for is maybe [`kerb=*`](https://wiki.openstreetmap.org/wiki/Key:kerb)...

**Comment by rugk** [comment]
Actually, I think, I have to correct the wording here. It is not actually a kerb, but an elevation, so you can get from the tram/bus platform/stop directly into the tram/bus without having to lift your wheelchair or whatever…

**Comment by westnordost** [comment]
This is a place where there is no kerb.

![bus](https://static.independent.co.uk/s3fs-public/styles/story_medium/public/thumbnails/image/2014/12/12/22/moore2.jpg)

Still, a bridge is necessary. Even more so without a kerb. So, what sense does it make to ask for a kerb if it is irrelevant for whether a person in a wheelchair can enter without aid?

**Comment by rugk** [comment]
No, no kerb. Did not meant that.

It should just ask for the elevation, so easier getting in is possible. Also without a bridge, often. Howver some trams even have bridges, which move out automatically at the station.

So let's not care about the kerb or bridge. It's the elevation, which the quest has to ask for.

**Comment by westnordost** [comment]
This quest is missing the point.

An elevation _may_ make it more convenient to enter but only _if_ the height of the elevation is the same as that of the bus entrance - which is not tagged in OSM. 
Also, the elevation makes no statement about the much more important information whether the means of transport accessible at that stop take people in wheelchairs _at all_. Compared with that information, the elevation information is really irrelevant. Also, I would say that whether people in wheelchairs can use this bus or not is rather dependent on the country/region than on every single bus/bus stop, so it does not make sense to tag it for every bus (stop).
It goes with common sense that buses in [certain countries](http://cms.indiawave.in/uploads/images/2018/03/24/delhi-lucknow-bus.jpg) will not be wheelchair-friendly.

**Comment by rugk** [comment]
Hehe, yeah, it's likely very location specific. At least in my area buses and trams have sometimes at some bus stops this elevation. And of course, it "is elevated" should mean: The elevation is the same as on the stop.

**Comment by ViolaineDo** [comment]
@rugk I think your concern fits in the wheelchair=yes/no/limited applied to public transport platforms, see : https://wiki.openstreetmap.org/wiki/Key:wheelchair#Public_transport_stops.2Fplatforms
