### ISSUE TITLE
Quest: Internet access for hotels

### ISSUE THREAD

**Issue by CloCkWeRX** [westnordost/StreetComplete#99]
See https://wiki.openstreetmap.org/wiki/Key:internet_access#What_should_be_tagged

Not sure if hotel/hostel/library is worth including or not.

Possible answers:
 * https://wiki.openstreetmap.org/wiki/Key:internet_access#Access_types

**Comment by westnordost** [comment]
Same problem as "website". Few will have this.

**Comment by westnordost** [comment]
I'll hijack this ticket if you don't mind, for reasons stated, I think it is not applicable globally for cafés, bars and pubs.

**Comment by gupascal** [comment]
Other interesting nodes for internet access: restaurant and shop=mall.

**Comment by rugk** [comment]
This is a very important quest IMHO!

**Comment by jancborchardt** [comment]
Yeah, cafés and restaurants often have wifi, and it's an important info for travelers and people whonwork from cafés like students or digital nomads. :)

**Comment by rugk** [comment]
Does anybody know how it should be tagged when multiple things are offered? E.g. wired internet and wifi?

**Comment by jancborchardt** [comment]
@rugk the page at https://wiki.openstreetmap.org/wiki/Key:internet_access doesn’t say anything about multiple entries. Since many 3rdparty apps seem to look for `internet_access=wlan` and it’s the most used tag of them, I’d recommend that for mixed setups.
