### ISSUE TITLE
Show disabled quests in quest list in a disabled state

### ISSUE THREAD

**Issue by rugk** [westnordost/StreetComplete#990]
I'd propose to show the disabled quests in the quest list, which are disabled, because of a country restriction/metadata. Just at the bottom.

The reason is that we maybe never will have complete metadata/all data for each country. Now, if a user from that country notices, that there is a quest, which is disabled in their country, but thinks this is wrong and the quest should be enabled, they can contact us/open an issue and we can change that. Without that, we do not give them that chance and they may always be excluded without noticing it.

**Comment by westnordost** [comment]
It is not shown at all currently that a quest is disabled for any given country. It appears as if it is enabled in the list.
But yes, it would make sense to somehow show that this quest is disabled in the country in which the user is currently.

**Comment by rugk** [comment]
> It is not shown at all currently that a quest is disabled for any given country. It appears as if it is enabled in the list.

Uh, did not know this. So that is bad… :laughing: 

SO IMHO it should:
* be greyed out
* "pinned" at the bottom (i.e. listed at the bottom and not movable)
* somehow show a message (e.g. when tapped) that explain why it is disabled/shown like that

**Comment by HolgerJeromin** [comment]
The "hiding" does only work when you are never on holiday and not living at a country border.

The quest could come active than and needed to be sorted at any time.
