### ISSUE TITLE
Undo for notes missing

### ISSUE THREAD

**Issue by anttitelio** [westnordost/StreetComplete#993]
In issue #116, it became obvious that undo is a useful feature, but seemingly it hasn't reached the new note adding functionality. I currently have an unnecessary note pending for upload, but I can't cancel it anyhow.

**Comment by westnordost** [comment]
Notes are not part of the undo-feature and would be a major refactor to enable this. Even then, it would naturally only work for notes that have not been uploaded yet, something that would only be relevant for users that disabled the auto-sync in the options. Additionally, this behaviour would be difficult to communicate to the user.
So, I will not do this, sorry. You can simply upload your note and then close it from the openstreetmap website.
