### ISSUE TITLE
Overhaul contributing documentation

### ISSUE THREAD

**Issue by rugk** [westnordost/StreetComplete#996]
As contributing gets increasingly important for (any big FLOSS project over time, but of course also for) StreetComplete, I think the docs for that need to be adjusted a bit.

I noticed this when changing things for https://github.com/westnordost/StreetComplete/pull/995, which I consider is a first step.

Things, which need to be changed, IMHO:
1. Unify the location of contributing information. Currently parts are split in the Readme and an extra Contributing file. I'd choose the latter for all of them.
    BTW the link to the wiki is fine. Extensive information about one thing can (and maybe should) still go into the wiki. There should just be one place, where all potential contributors can look and directly find the thing they want to do.
2. Avoid long texts. Contributers won't read that wall of text in the Readme, they need short parts, bullet points, **highlighting**, structure with headlines, …
3. > I have a few tasks in mind that would be very helpful for the project, some of which do not require knowledge about the current code base. So best get in touch with me.
   
   Sorry, but this is not how FLOSS works. And also not good for the maintainer, as you won't like each one to contact you privately (via mail…) to ask what/how they can contribute.
   Instead make use of special tags for such stuff and link them in the guide.
4. [Also pay attention to the general guidelines](https://opensource.guide/starting-a-project/#writing-your-contributing-guidelines).

BTW I can do this, so you asign it to me (if that's possible on GitHub). I) just want to gather the ideas on how it should look afterwards, first.

----

Collected TODOs:
* [ ] How to add new languages? [ref](https://github.com/westnordost/StreetComplete/pull/995#issuecomment-378021346) (/to @westnordost?)
* [ ] Is there a translation percentage for inclusion of a new language? [ref](https://github.com/westnordost/StreetComplete/pull/995#issuecomment-378021346) (/to @westnordost?)
* [ ] How to contribute metadata? [ref](https://github.com/westnordost/StreetComplete/pull/995#issuecomment-378021346) (Some things mentioned in different places.
    E.g. (https://github.com/westnordost/StreetComplete/pull/919):
    > You need to run the generatecountrymetadata.py script in the app directory
* [ ] Do app descriptions need specific behaviour when translating or are they also ranslated in POEditor? (/to @westnordost?)
* [ ]  Clarify when metadata is needed (vs) when a country-blacklist is needed. (maybe needs changes in the wiki, soI cannot do this)

**Comment by stefanb** [comment]
All of it should be included in CONTRIBUTING.md which is then linked for users before they submit PRs.
https://help.github.com/articles/setting-guidelines-for-repository-contributors/

An example here: https://gist.github.com/PurpleBooth/b24679402957c63ec426

@rugk, this is a personal repository and github does not support assigning rights to others, but it is easy to create an organisation where more people have specific access levels.

https://help.github.com/articles/transferring-a-repository-owned-by-your-personal-account/

**Comment by rugk** [comment]
@stefanb I don't know how you got on the topic of rights, but the topic is discussed in https://github.com/westnordost/StreetComplete/issues/928. (feel free to upvote :wink:)

Just one line: Maybe you got to this, because you can assign me then. AFAIK/The last time I looked team vs. personal repos make no difference. (Still AFAIK) GitHub introduced the feature you can assign the OP (original poster/issue creator here) to an issue even when they are not a member. Apart from that, only members of the repo/organisation can be assigned.

**Comment by westnordost** [comment]
As far as I remember, I didn't really write any part of CONTRIBUTING.md. Anyway, I am all fine with your suggestions, @rugk.

**Comment by rugk** [comment]
Okay, still need answers to the questions where I added `/to @westnordost?`, because I have no experience with that.

And, as said, any other requests are also fine.

**Comment by stefanb** [comment]
@rugk clarification: i meant "rights" as in "access rights" or "access level", triggered by
> BTW I can do this, so you asign it to me (if that's possible on GitHub).

https://help.github.com/articles/access-permissions-on-github/
It seems I was wrong claiming that it is not possible to assign Access permissions on personal repositories (as this one is). It is possible, but is limited compared to organizations.

**Comment by westnordost** [comment]
> How to add new languages? ref (/to @westnordost?)

One gets this option when joining the project on POEditor.

> Is there a translation percentage for inclusion of a new language? ref (/to @westnordost?)

Nothing official. 

> Do app descriptions need specific behaviour when translating or are they also ranslated in POEditor? (/to @westnordost?)

No special behavior.

**Comment by rugk** [comment]
Thanks for your replies. BTW, I just rechecked in another repo, where I have access, one can assign the issue creator to issues on GitHub, so @westnordost – better do so.
