### ISSUE TITLE
Require an unique icon for each quest

### ISSUE THREAD

**Issue by rugk** [westnordost/StreetComplete#998]
Currently the official stance of SC/@westnordost is that an "unique icon for each quest" would be nice. 

And, yes, it would be nice, but IMHO it is really a fundamental thing for SC and it's users.

So I advise to change the guide to require such a difference. And if it is just the background color, as for the wheelchair acessibility quests, such a small change is enough.

With a small change (https://github.com/westnordost/StreetComplete/issues/999) we can fulfill this requirement as of the current state of the icons.

**Comment by rugk** [comment]
I think as a user story one can see best why this is useful:

As a user of SC I want to have one icon for each quest (and only one), because I want to know what quest I am about to be asked/solve and recognize/remember that quest when clicking on an icon.

So it's all about convenience and user's behaviour of remembering things and the desire to answer quest fast. When users need to think what type of quest this icon was they clicked on, this is counterproductive.

(This is more or less a folowup of https://github.com/westnordost/StreetComplete/issues/590, BTW), which has accidentally been solved. :wink:)

**Comment by westnordost** [comment]
I find not that it is a hard requirement (as in I will not merge PRs). I make most of the icons anyway, so making this a hard requirement would be weird.
