### ISSUE TITLE
Icon for bicycle parking quest should show many bicycles behind each other

### ISSUE THREAD

**Issue by rugk** [westnordost/StreetComplete#999]
"How many bikes can be parked here?" should have an icon variant, so it can be differentiated from the "What is the type of this bicycle parking?" quest.

I propose multiple bikes arranged behind each other (just two or three).

I'll take this one, if it is ok.

If that is done we have an unique icon for each quest. I think that's how it is supposed to be. (see https://github.com/westnordost/StreetComplete/issues/998)

**Comment by westnordost** [comment]
The bicycle pictogram is already quite/too detailed, duplicating it in the quest icon would not look good/clear.
Ideas: same as bicycle parking covered icon but instead of the roof, another bike

**Comment by rugk** [comment]
> Ideas: same as bicycle parking covered icon but instead of the roof, another bike

Actually that's what I mean. I'd also imagine a small gap between the lines of the two biokes, so one can see these do not belong together, but are two ones. That makes it a bit more like a pictograph.
